### ISSUE TITLE
Error on opening download file link on android "Domain: undefined Error code -1"

### ISSUE THREAD

**Issue by vpankov** [react-native-webview/react-native-webview#1050]
- Site was opened
- Trying to open file download link
- File downloaded successfully
- Webview crashed with the next error message 
"Error loading page. Domain: undefined. Error Code: -1. Description: net::ERR_FAILED"
I tried it for 2 different app builds and for different download file links.

One of the tested urls http://sources.codenet.ru/file/609/example.rar

`<WebView
        source={{ uri: 'http://sources.codenet.ru/file/609/example.rar' }}
      />`

To AndroidManifest added 
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />`

![Screenshot_2019-11-29-20-04-38](https://user-images.githubusercontent.com/10135175/69883098-b31b2c00-12e3-11ea-96cc-8032660f7172.png)

![Screenshot_2019-11-29-20-28-22~3](https://user-images.githubusercontent.com/10135175/69883919-3d18c400-12e7-11ea-9322-ce12d7e8abca.png)

**Environment:**
 - OS: Android
 - OS version: 7
 - react-native version: 0.61.3
 - react-native-webview version: 7.4.3

- Working fine for Android 10 emulator
- Working fine for Android 7 emulator
- Crashing for Android 7 device

**Comment by AmitPandya007** [comment]
@vpankov have you got any solutions? I am also facing the same issue.

**Comment by vpankov** [comment]
Hi @AmitPandya007  
No, I didn't. I just added onError handler, that reload webview.
So user still see error message for about 2 seconds, but file is successful downloaded and user can use app after page reloaded. So it's not a solution of the bug, but user experience process was saved and user doesn't need to reload the app.
`<WebView
          source={{ uri: 'http://example.page' }}
          ref={ref => {
            this.webView = ref;
          }}
          onError={
            ()=>{
              this.webView.reload();
            }
          }
        />`

**Comment by AmitPandya007** [comment]
@vpankov I need to open a document file on the same webview. The file gets downloaded but after that it gives-
**Encountered an error loading page', 
{ 
      description: 'net::ERR_FAILED',
      code: -1,
      canGoForward: false,
      canGoBack: false,
      title: 'project name',
      loading: false,
      url: 'url_which_i_am_opening_for_downloading_file',
      target: 1313 
}**

Can you help me out with this, please?

**Comment by truongluuxuan** [comment]
Me too, in Debug it working but on release it show this error: "Domain: undefined Error code -1"

**Comment by hamzapiri** [comment]
I am facing the same issue as @truongluuxuan

**Comment by salvariable** [comment]
iOS works perfectly but Android is showing this

**Comment by vpankov** [comment]
I found some time for researching. 

When application at this point, file already downloaded and it tries to redirect to a broken page.
![image](https://user-images.githubusercontent.com/10135175/72008384-bbf90900-3264-11ea-8bc1-abc1b1d16e18.png)
So I tried to check url in props.onLoadStart event, to stop webView loading for the download link, but it crashed, so it seems that props.onLoadStart event is running after webview tried to redirect to a broken page.
`          onLoadStart={e => {
            if(e.nativeEvent.url.indexOf('/download?') != -1){
              this.webView.reload();
            }
            this.setState({
              isLoading: true,
            });
          }}`

So I used onShouldStartLoadWithRequest event, that starting before webview redirection and added url checking there. Unfortunately, it's also blocking file downloading, so I opened downloading link in external browser.
`          onNavigationStateChange={event => {
            if (event.url.indexOf('download') !== -1 && Platform.OS === 'ios') {
              this.webView.stopLoading();
              Linking.openURL(event.url);
            } else {
              this.setState({ url: this.state.url });
            }
          }}`

Now I trying to process this download link with rn-fetch-blob library, to except external browser. I also have bug with "blob" links downloading, so I hope to close both bugs in this way.

**Comment by vpankov** [comment]
Just checked bug with "blob" link crashing, but unfortunately, app is crashing before onShouldStartLoadWithRequest was called. :(

**Comment by openlife** [comment]
Someone find a solution ?

**Comment by fredattack** [comment]
same issue here.. work on ios , work on simulator or expo release, not in prod...

**Comment by trcoffman** [comment]
We are experiencing the same bug as well on android.

**Comment by trcoffman** [comment]
I've been investigating this issue and it appears that it might actually be a bug not in react-native-webview but in the underlying Android WebView. I modified a simple WebView example app I found on GitHub. I found that when I clicked a link to download a file on a page the file would download, but I would get an error via onReceivedError being called on my WebViewClient.

**Comment by dvicory** [comment]
After more investigation with @trcoffman we've determined this to be an underlying WebView bug. We made a very stripped down pure Android WebView app. `onReceivedError` is always called for the download URL, including other lifecycle methods like `onPageStarted` and `onPageFinished`.

I found a filed [Chrome bug](https://crbug.com/1023678) and followed up there with more details for their team.

There is potential workarounds that could be done to ignore the lifecycle methods when a download just happened, but that solution isn't the most appealing.

**Comment by shinigami3000** [comment]
Same issue. Works on debug, but doesnt work on release version

**Comment by Dror-Bar** [comment]
If anyone has a workaround solution, please share here.

**Comment by trcoffman** [comment]
> If anyone has a workaround solution, please share here.

PR #1221 works around this bug but I haven't been able to get it code reviewed by maintainers...

**Comment by liushiniuniu** [comment]
Same issue.  show on release, debug version work fine

**Comment by liushiniuniu** [comment]
Same issue. show on phone, simulator work fine.

**Comment by sebgam** [comment]
> Mismo problema. mostrar en el teléfono, el simulador funciona bien.

Were you lucky?

**Comment by salvariable** [comment]
Still doesn't work for me, not even on simulator

**Comment by sebgam** [comment]
I solved it by adding `proyect/android/src/AndroidManifest.xml`

`android:usesCleartextTraffic="true"`

<img width="300" alt="Captura de Pantalla 2020-05-03 a la(s) 12 18 41 p  m" src="https://user-images.githubusercontent.com/22036132/80920923-85c22680-8d38-11ea-99b7-6133f10f38b0.png">
<img width="357" alt="Captura de Pantalla 2020-05-03 a la(s) 12 20 40 p  m" src="https://user-images.githubusercontent.com/22036132/80920924-88248080-8d38-11ea-9ead-29aaa50f7564.png">

**Comment by Rdarz** [comment]
> I solved it by adding `proyect/android/src/AndroidManifest.xml`
> 
> `android:usesCleartextTraffic="true"`
> 
> <img alt="Captura de Pantalla 2020-05-03 a la(s) 12 18 41 p  m" width="300" src="https://user-images.githubusercontent.com/22036132/80920923-85c22680-8d38-11ea-99b7-6133f10f38b0.png">
> 
> <img alt="Captura de Pantalla 2020-05-03 a la(s) 12 20 40 p  m" width="357" src="https://user-images.githubusercontent.com/22036132/80920924-88248080-8d38-11ea-9ead-29aaa50f7564.png">

Thanks @sebgam it is working for me.

**Comment by ruanblima** [comment]
> Eu o resolvi adicionando `proyect/android/src/AndroidManifest.xml`
> 
> `android:usesCleartextTraffic="true"`
> 
> <img alt="Captura de tela 2020-05-03 a (s) 12 18 41 p m" width="300" src="https://user-images.githubusercontent.com/22036132/80920923-85c22680-8d38-11ea-99b7-6133f10f38b0.png">
> 
> <img alt="Captura de tela 2020-05-03 a (s) 12 20 40 p m" width="357" src="https://user-images.githubusercontent.com/22036132/80920924-88248080-8d38-11ea-9ead-29aaa50f7564.png">


This did not work for me, the problem is still happening, has anyone managed to solve it?

**Comment by Dror-Bar** [comment]
@ruanblima 

ClearTextTraffic didn't fix it for me either.

I ended up using something like this:

```
<WebView
    {...other props...}
    key={update}
    onShouldStartLoadWithRequest={this.onShouldStartLoadWithRequest}
    onError={() => { if (isFile) this.setState({ isFile: false, update: !update }); }}
/>
```

And the method:

```
onShouldStartLoadWithRequest = ({url}) {
    if (Platform.OS === 'android' && url.endsWith('.ppt')) {   //  Add any file extensions you need
        this.setState({ isFile: true });
    }
    return true;
}
```

**Comment by ThirashaWijerathna** [comment]
> I solved it by adding `proyect/android/src/AndroidManifest.xml`
> 
> `android:usesCleartextTraffic="true"`
> 
> <img alt="Captura de Pantalla 2020-05-03 a la(s) 12 18 41 p  m" width="300" src="https://user-images.githubusercontent.com/22036132/80920923-85c22680-8d38-11ea-99b7-6133f10f38b0.png">
> 
> <img alt="Captura de Pantalla 2020-05-03 a la(s) 12 20 40 p  m" width="357" src="https://user-images.githubusercontent.com/22036132/80920924-88248080-8d38-11ea-9ead-29aaa50f7564.png">

Thanks its works for me

**Comment by umairalirehan** [comment]
> I solved it by adding `proyect/android/src/AndroidManifest.xml`
> 
> `android:usesCleartextTraffic="true"`
> 
> <img alt="Captura de Pantalla 2020-05-03 a la(s) 12 18 41 p  m" width="300" src="https://user-images.githubusercontent.com/22036132/80920923-85c22680-8d38-11ea-99b7-6133f10f38b0.png">
> 
> <img alt="Captura de Pantalla 2020-05-03 a la(s) 12 20 40 p  m" width="357" src="https://user-images.githubusercontent.com/22036132/80920924-88248080-8d38-11ea-9ead-29aaa50f7564.png">

i solved this problem using this 
android:usesCleartextTraffic="true"

**Comment by cx5168** [comment]
Thanks @sebgam it is working for me.

**Comment by SuperXonic** [comment]
android:usesCleartextTraffic="true" still not work. 
<img width="318" alt="bug" src="https://user-images.githubusercontent.com/52225482/87496849-92d78c00-c67e-11ea-8237-55f926f880ed.png">

**Comment by Unity-Group-BFGI** [comment]
![Screenshot (108)](https://user-images.githubusercontent.com/50524941/88485022-975e4780-cf90-11ea-8eee-0ebbb683efd6.png)
same issue, i might thinking about , enable that option somewhere, its was in android stupid known as 
`<manifest ... >
    <uses-permission android:name="android.permission.INTERNET" />
    ...
</manifest>`

**Comment by DmitriyGalyanov** [comment]
still searching for solutions

**Comment by luojiong** [comment]
@DmitriyGalyanov   Did you solve the problem? I also encountered the problem

**Comment by 026binit** [comment]
looking for solutions

**Comment by Dror-Bar** [comment]
@DmitriyGalyanov @luojiong @026binit did you try [my solution](https://github.com/react-native-webview/react-native-webview/issues/1050#issuecomment-633242191) per chance?

**Comment by akbari6776** [comment]
@vpankov I have solutions only for don't show " Encountered an error loading page "
`
import { LogBox } from 'react-native'
LogBox.ignoreLogs(['Encountered an error loading page']);

`

**Comment by Enoooch** [comment]
If it doesn't work by adding `android:usesCleartextTraffic="true"`.

1. You can also add `android:networkSecurityConfig="@xml/network_security_config"` in your `android/app/src/main/AndroidManifest.xml` file.
<img width="551" alt="img" src="https://user-images.githubusercontent.com/39915133/105275337-08965480-5bda-11eb-8a55-1e1d5f3e358a.png">

2. Creating `network_security_config.xml` file in `android/app/src/main/res/xml`

```
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">add your domain like www.google.com</domain>
        <domain includeSubdomains="true">or local ip address 192.168.1.101</domain>

        <trust-anchors>
            <certificates src="system" />
            <certificates src="user" />
        </trust-anchors>
    </domain-config>

    <base-config cleartextTrafficPermitted="false" />
</network-security-config>
```
It may ignore some cert error.

Tested in
- "react-native": "0.63.4"
- "react-native-webview": "^11.2.0"


And I am still looking for a way to ignore all certificate error. Especially self-signed certificate.

**Comment by amahJennifer** [comment]
I got this error because I was trying to open an "http" link in the WebView , It worked for IOS though , but not Android , I simply changed the link from http to https and it worked .

a workaround for this if you dont have https is to add it to the network_security_config.xml file

**Comment by hoangdvhou** [comment]
> I solved it by adding `proyect/android/src/AndroidManifest.xml`
> 
> `android:usesCleartextTraffic="true"`
> 
> <img alt="Captura de Pantalla 2020-05-03 a la(s) 12 18 41 p  m" width="300" src="https://user-images.githubusercontent.com/22036132/80920923-85c22680-8d38-11ea-99b7-6133f10f38b0.png">
> 
> <img alt="Captura de Pantalla 2020-05-03 a la(s) 12 20 40 p  m" width="357" src="https://user-images.githubusercontent.com/22036132/80920924-88248080-8d38-11ea-9ead-29aaa50f7564.png">

you saved my day :D
