### ISSUE TITLE
Move WebKit related cookie logic to react-native-webview

### ISSUE THREAD

**Issue by safaiyeh** [react-native-webview/react-native-webview#1139]
Should WebKit cookies be moved to the `react-native-webview` module from `react-native-cookies`?

The only time WebKit cookies are needed is usage with WebView. The two are coupled.

How would y'all feel about moving that functionality over or is there another way that this can be handled?

Issue in `react-native-cookies`: https://github.com/react-native-community/react-native-cookies/issues/5

**Comment by MRS-97** [comment]
@github-actions this issue should be opened

**Comment by DSp4wN** [comment]
not resolved
