### ISSUE TITLE
Remove Android WebView from view system before calling destroy()

### ISSUE THREAD

**Issue by nfischer** [react-native-webview/react-native-webview#1161]
**Bug description:**

React-native needs to remove WebView from the view hierarchy before calling `.destroy()`. From [this comment](https://github.com/react-native-community/react-native-webview/issues/429#issuecomment-577080538) it seems react-native is not doing so:

> ```
> ...
> W/cr_AwContents: WebView.destroy() called while WebView is still attached to window.
> ...
> ```

This probably isn't causing a crash (WebView tries to handle this case gracefully), but older versions of WebView may not handle this as gracefully (I've observed crashes on really old Android versions).

**To Reproduce:**

Not sure. This log message probably repros every time you trigger the [cleanup code path](https://github.com/react-native-community/react-native-webview/blob/5b0c634f15dbf8eb8210d4393da9ca86df1de453/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java#L634).

**Expected behavior:**

The documentation states:

> This method should be called after this WebView has been removed from the view system. No other methods may be called on this WebView after destroy.

https://developer.android.com/reference/android/webkit/WebView.html#destroy()

**Screenshots/Videos:**

N/A

**Environment:**
 - OS: Android
 - OS version: probably all
 - react-native version:
 - react-native-webview version:

**Comment by srajesh636** [comment]
Hi Nate is there any fix for the above issue coming soon . We are facing exactly the same issue. on android.

**Comment by nfischer** [comment]
I don't work on react-native-webview, but the fix would need to be in this project.

**Comment by ysfzrn** [comment]
I resolved with using conditional rendering, like this. Before pop action, I set show state to false

```jsx
const AccountDetailScreen = ({route, navigation}) => {
  const {title, url} = route.params;
  const [show, setShow] = useState(true);

  useFocusEffect(
    useCallback(() => {
      const onBackPress = () => {
        setShow(false);
        return false;
      };
      BackHandler.addEventListener('hardwareBackPress', onBackPress);
      return () =>
        BackHandler.removeEventListener('hardwareBackPress', onBackPress);
    }, []),
  );

  const goBack = () => {
    setShow(false);
    navigation.pop();
  };

  return (
    <SafeAreaView style={[styles.container]}>
      <Header title={title} onPress={goBack} />
      {show && (
        <WebView
          style={styles.view}
          renderLoading={() => <Loader backgroundColor="white" />}
          startInLoadingState
          source={{uri: url}}
        />
      )}
    </SafeAreaView>
  );
};
```_

**Comment by zlwu** [comment]
when using react navigation, we can hide WebView in event listener
```javascript

  React.useEffect(() => navigation.addListener('blur', () => setShow(false)), [ navigation ]);

```

**Comment by Leanderson-Coelho** [comment]
> when using react navigation, we can hide WebView in event listener
> 
> ```js
>   React.useEffect(() => navigation.addListener('blur', () => setShow(false)), [ navigation ]);
> ```

work here!!!! thank you <3
