### ISSUE TITLE
Did not receive response to shouldStartLoad in time, defaulting to YES

### ISSUE THREAD

**Issue by dlferro** [react-native-webview/react-native-webview#124]
Can someone give me a bit more details on why I would get the above warning?

**Comment by Titozzz** [comment]
I've never seen that before, can you give us a way to repro this ?

**Comment by dlferro** [comment]
It appears to exist in the core Webview as well.

https://github.com/react-native-community/react-native-webview/blob/7f3534463291893154bd41dc560c092a7b9bf746/ios/RNCWKWebViewManager.m#L157

My component presenting it is just
```
import React, { PureComponent } from 'react';
import { WebView } from 'react-native-webview';

class CloudPageScreen extends PureComponent {
  render() {
    const { navigation } = this.props;
    const uri = navigation.getParam('uri');

    return <WebView source={{ uri }} />;
  }
}

export default CloudPageScreen;
```

**Comment by Titozzz** [comment]
We have a current PR https://github.com/react-native-community/react-native-webview/pull/107 trying to implement this on android and fix iOS, hopefuly it will help

**Comment by zmnv** [comment]
Is it a some critical thing or I can skip it for your updates?

**Comment by MickaelNeves** [comment]
Same here, can I ignore those warnings? I try to found more info about them but no success.

RN: 0.57.8
RN Webview: 5.2.1

![captura de ecra 2019-02-20 as 15 51 26](https://user-images.githubusercontent.com/20476271/53104719-cd8bd200-3527-11e9-9e35-d23d50741323.png)

**Comment by zmnv** [comment]
I can ignore it if there are 3-4 warnings like that.
But... more code = more warning messages..

**Comment by Titozzz** [comment]
If you have chrome debugger on it's 'normal' cause it's too slow

**Comment by bosshog** [comment]
even with chrome debugger off I see a lot of these warnings (on iOS)

**Comment by IlinIgor** [comment]
Are there any fixes of that?

**Comment by Johncy1997** [comment]
I am getting the same warning and can't able to view the web page.Is there any fixes?

**Comment by scarlac** [comment]
Error is caused by app being slow. It attempts to execute the callback defined for `onShouldStartLoadWithRequest`, an event handler that should return a boolean (aka `YES`/`NO`) indicating if loading of a given URL should actually happen, but if that function does not return within 250ms, it'll still load the page. Even if you define `onShouldStartLoadWithRequest={() => true}` it will still give this warning.

This happens regardless if developers define `onShouldStartLoadWithRequest` or not, which is confusing. My proposed solution would be one or multiple of:
1. If `onShouldStartLoadWithRequest` is undefined, do not attempt to run it (e.g. do not provide an internal default function). This would also increase performance if only ever so little
2. Update documentation to include this caveat
3. Mark the callback as async, update docs to indicate it, and handle it as such
4. Wait for longer than 250ms (if function is kept synchronous)

Some combination of the above 4 solution would work. I think the 1st one would work just fine by itself.

For those looking for a workaround: If you are NOT using `onShouldStartLoadWithRequest` prop, don't worry about this warning! It's meaningless for you. If you ARE using that prop, it may break your app, as it might ignore whatever you're trying to return.

**Comment by davidcort** [comment]
For a while:
onShouldStartLoadWithRequest={false} do the trick :)

**Comment by elirangoshen** [comment]
happen to me as well..
since i added: startInLoadingState={true} to my webview  and only in that webview

**Comment by DibPuelma** [comment]
For now I solved the problem only using startInLoadingState={true} on android. It seems that iOS 12 has problems with that prop. Hope it helps someone.

**Comment by Hieutt1704** [comment]
I solved the problem with add onShouldStartLoadWithRequest={() => true. Hope it helps someone.

**Comment by student-t** [comment]
I solve it by simple killed off the remote debugger.

**Comment by skay97** [comment]
@elirangoshen @DibPuelma, this is aside from the issue, however, just thought I'd mention that you do not need to set a prop to true like `startInLoadingState={true}`. You can simply use `startInLoadingState` and JS will automatically default it to true.

Also using the `startInLoadingState` prop doesn't solve the issue for me, I still get the same warning, unfortunately.

**Comment by davidcort** [comment]
I pass from this package, contains a lot of issues. Change to in App Browser Reborn and works like a charm 💯

**Comment by henrikra** [comment]
Is there any reason not to refactor the code in a way that there is no hard coded 250ms and JS has full control whether web view can load or not? Imo the current implementation is not very good :/ At least the native docs say that promise is possible: https://facebook.github.io/react-native/docs/native-modules-ios#promises

**Comment by akread** [comment]
I would like to request that we re-open this ticket. This is still an issue and has gotten significantly worse with recent iOS OS updates.

**Comment by daviddelusenet** [comment]
Please reopen indeed.

**Comment by laurent22** [comment]
Please reopen the ticket, especially since there's a number of possible listed solutions there: https://github.com/react-native-webview/react-native-webview/issues/124#issuecomment-489677422

It's indeed got worse with recent iOS releases and it doesn't seem too hard to fix.

**Comment by Titozzz** [comment]
This ticket was closed by a very aggressive bot that was trying to help but failed.

Tbh I have never had issues with this in production and we heavily use webviews, which is why I never dug that much into that "issue". Please note that the bridge is light years faster in release.

Also I am waiting for the new react native architecture that should enable synchronous calls from native to JS to rewrite the webview ...

In the meantime if anyone want to submit PRs please do

**Comment by btejes** [comment]
This is still affecting us. Has anyone else been affected by this issue?

**Comment by scarlac** [comment]
Yes. The issue resurfaced for me recently.

**Comment by whitefang57** [comment]
@scarlac, have you been able to implement any fixes in your project? This is affecting me as well, and would love a solution

**Comment by scarlac** [comment]
I don't have a fix, sorry.

**Comment by dezudas** [comment]
+1  It has been resurfaced for me too

**Comment by btejes** [comment]
We have tried so many things that have not worked. Has anyone had success?

**Comment by cjhines** [comment]
This is occurring in `11.13.0`.

**Comment by mym0404** [comment]
I am suffering this issue today. 
Also, my package version is `11.13.0` (latest).
Please reopen this ticket. It should be

**Comment by dentemple** [comment]
+1

**Comment by my-name-is-nheo** [comment]
+1, still seeing this issue

**Comment by H3DZZZ** [comment]
+1, still seeing this issue

**Comment by H3DZZZ** [comment]
+1, still seeing this issue

**Comment by jeltehomminga** [comment]
+1, still seeing this issue

**Comment by nikmatswace** [comment]
I'm also seeing this issue. It happens when I start the app from a closed state and try to open another uri than the "default" one.

**Comment by ChrisEU** [comment]
+1, still seeing this issue, but not all the time. Haven't been able to determine why it only shows up occasionally.

**Comment by mustafaasif1** [comment]
Still seeing this issue

**Comment by afzdev13** [comment]
3 years from this ticket opened and still exist the problem :(

**Comment by rares-lupascu** [comment]
yeap ... same here

**Comment by shawnapril** [comment]
yeap ... same here

**Comment by nawfalhaddi** [comment]
Still seeing the issue

**Comment by MorenoMdz** [comment]
Why is this closed, still seeing this error.

**Comment by roydaw** [comment]
Stilling seeing this error.

**Comment by dezudas** [comment]
+1

**Comment by PhillipFraThailand** [comment]
Still seeing the issue, can we reopen?

**Comment by trungtruc91** [comment]
same issue

**Comment by Facundo1609** [comment]
Still seeing the issue, can we reopen?

**Comment by bdhcode** [comment]
+1

**Comment by bdhcode** [comment]
Is there any new version since [11.0.0](2020-11-24)?

**Comment by zakharchenkoAndrii** [comment]
+1

**Comment by M1ck0** [comment]
The issue is still active. Any hope?

**Comment by Attique033** [comment]
I'm also facing this problem, below listed RN, expo and Webview versions I'm using

"react-native-webview": "11.23.1",
"react-native": "0.70.5",
 "expo": "~47.0.6",

**Comment by billyduong88** [comment]
weird, this issue has been there for more than 5 years and still not getting fixed :(

**Comment by dancosta-fed** [comment]
Also looking for a fix or a workaround.

**Comment by ShepSims** [comment]
If using  react-native version 0.69.7 or lower then downgrading from "react-native-webview": "^11.26.0", to "react-native-webview": "^11.23.1" fixed this issue for me! 

Have not verified if this works for 70 or 71+ yet...

My package.json now looks like...
```

{
   ...
   "dependencies": {
         ...
         "react-native": "0.69.7",
         "react-native-webview": "^11.23.1",
         ...
    }
}

```

**Comment by matthijn** [comment]
Having the same issue here @ react-native-webview 11.23.1 and react native @ 0.70.5

**Comment by karel-suchomel-ed** [comment]
Same issue

"react-native": "0.71.3"
"react-native-webview": "^11.26.1"

**Comment by Anthony-333** [comment]
+ 1 same issue

**Comment by dks333** [comment]
Same issue:
"react-native": "0.71.7",
"react-native-webview": "11.26.0",

**Comment by shahjahanpak** [comment]
Not getting this warning on **12.2.0**.
