### ISSUE TITLE
chromium: [ERROR:ssl_client_socket_impl.cc

### ISSUE THREAD

**Issue by viswakarmalovekush** [react-native-webview/react-native-webview#1253]
I am loading url: https://bioconuat.cluster1.traform.io/TravoSSOAuthenticator?domain=biocon and getting error on android devices only,  but it is loading on ios perfectly.
error is : E/chromium: [ERROR:ssl_client_socket_impl.cc(946)] handshake failed; returned -1, SSL error code 1, net_error -202

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS: Android
 - OS version: All OS level
 - react-native version: 0.61.0
 - react-native-webview version: ^7.5.1

**Comment by GabrielePrestifilippo** [comment]
I am experiencing the same on `Android`.
I tried both last version (as of today)`v9.3.0` and all the previous versions till `^6`

**Comment by whitesnow9291** [comment]
me too

**Comment by KisaragiAkira** [comment]
I have similar error when i want to load a website where in local area network.
The error log is :
`chromium: [ERROR:ssl_client_socket_impl.cc(959)] handshake failed; returned -1, SSL error code 1, net_error -201`

I find around the network to resolve this problem, but i didn't find anything that is useful.

And i can't load https://bioconuat.cluster1.traform.io/TravoSSOAuthenticator?domain=biocon on webview too, but load on firefox(PC Ubuntu18.04) is success.

And i can load https://www.brrmedia.co.uk on webview.

**Comment by taxon-hub** [comment]
Even i have the same error in flutter.

**Comment by juansaav** [comment]
Any solution ?

**Comment by vvalerian** [comment]
still searching for solutions

**Comment by davidkhanpk** [comment]
I have same error when connecting to websocket in capacitor build app.

**Comment by Cosmopal** [comment]
Still facing this issue, anyone any solutions?

**Comment by stevezhougs** [comment]
I have the same error with md5RSA certificate.

**Comment by BrixSat** [comment]
E/chromium: [ERROR:ssl_client_socket_impl.cc(962)] handshake failed; returned -1, SSL error code 1, net_error -202

This is a lets encryt cert.

**Comment by XMMR12** [comment]
i need help in this too can't connect to a link inside the website
 https://ayatee.eu5.org/

**Comment by XMMR12** [comment]
Finally worked for me by using this :
//html code in <head>
<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
========================================================
//flutter code in webview():
bool get wantKeepAlive => true;


//<flutter full code>:
//webview function [start]
class WebViewLoad extends StatefulWidget {
  @override
  WebViewExampleState createState() => WebViewExampleState();
}

class WebViewExampleState extends State<WebViewLoad> {
  WebViewController _webViewController;
  @override
  bool get wantKeepAlive => true;

  @override
  void initState() {
    super.initState();
    // Enable hybrid composition.
    if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();
  }

  @override
  Widget build(BuildContext context) {
    return WebView(
      initialUrl: 'https://ayatee.eu5.org/',
      javascriptMode: JavascriptMode.unrestricted,

      onWebViewCreated: (controller) {_webViewController = controller;},
    );
  }
}
//webview function [end]

**Comment by angelorobo** [comment]
@XMMR12 

> wantKeepAlive

So the solution is to set wantKeepAlive=true?

**Comment by ElGrimbo** [comment]
Same problem here in a simple webview app. Images are failing to load, showing as "cancelled" in devtools. I suspect it's a mixed content issue but none of the settings I'm changing seem to affect it.
