### ISSUE TITLE
allowsFullscreenVideo breaks with <Modal>

### ISSUE THREAD

**Issue by cristianoccazinsp** [react-native-webview/react-native-webview#1293]
**Bug description:**

On Android, `allowsFullscreenVideo` on a WebView that's rendered inside a <Modal> component completely breaks the app when the full screen button is pressed.  The full screen player seems to render behind the modal, and closing the modal will leave a blank screen stuck on top of the app. After this point, the app is unusable and must be closed.

**To Reproduce:**

Render a `<WebView allowsFullscreenVideo={true} />` inside a <Modal> component.  Have the webview render something with a video in it; for example, a youtube video. Lastly, press the full screen button and observe.

**Expected behavior:**

Full screen player should not break the application, and should properly play above the app's modal.

**Screenshots/Videos:**

**Environment:**
 - OS: Android
 - OS version: Android 8.1 and 10 (tested on these)
 - react-native version: 0.61.5
 - react-native-webview version: 9.0.2

**Comment by Gabogg07** [comment]
Same problem over here, is there any update on this issue?

**Comment by LonelyCpp** [comment]
The screen completely goes black after entering fullscreen from a modal :(

![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/18496510/84428096-85744f80-ac43-11ea-84aa-ebaaf4845f9e.gif)

What is even happening here?

**Comment by bilalsyed001** [comment]
If you're using react-native-modal try setting `coverScreen={false}`.

**Comment by gilshaan** [comment]
Issue still exists for Native Modal in react native.

**Comment by djhr** [comment]
having the same issue, also tried the `Modal` provided by react-native-community with `coverScreen={false}` but it doesn't help much since `coverScreen={false}` won't render a `Modal`

**Comment by cristianoccazinsp** [comment]
Still an issue.

**Comment by cristianoccazinsp** [comment]
Update: Looks like the issue is related to these lines: https://github.com/react-native-webview/react-native-webview/blob/master/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java#L730

Bascically, when in a <Modal>, the root view is used incorrectly.  I have been trying to find the right root view where to add the video View, but nothing works.  Additionally, one could hide the root view if within a Modal, but there's also no way to know if the webview was rendered in a Modal or not. Still trying some work arounds.
