### ISSUE TITLE
onMessage prop is required in some or all environments for injectedJavaScript/injectedJavaScriptBeforeContentLoaded to work

### ISSUE THREAD

**Issue by shirakaba** [react-native-webview/react-native-webview#1311]
Several users (e.g. in #1260 and #1291) are tripping up on the unintuitive behaviour of an `onMessage` prop needing to be provided in order for `injectedJavaScript` to run. It also tripped me up when I first came to use this package.

We currently document the behaviour in `docs/Guide.md`, in the section [`The window.ReactNativeWebView.postMessage method and onMessage prop`](https://github.com/react-native-community/react-native-webview/blob/master/docs/Guide.md#the-windowreactnativewebviewpostmessage-method-and-onmessage-prop):

<img width="831" alt="image" src="https://user-images.githubusercontent.com/14055146/78121267-1ab4c580-7403-11ea-97e0-0f3339ea5fd6.png">

However, I see no reason in the first place why lack of `onMessage` should abrogate JS injection, other than the fact that it's *always* behaved like this.

Here is what's causing it, in case anyone feels like making a PR:

* [`src/WebView.ios.tsx#L339`](https://github.com/react-native-community/react-native-webview/blob/9fbcedd6b88af631edbc3d455339b3072a4aa0ea/src/WebView.ios.tsx#L339) `messagingEnabled` is set to `false` only if `onMessage` is defined.
* [`src/WebView.macos.tsx#L320`](https://github.com/react-native-community/react-native-webview/blob/9fbcedd6b88af631edbc3d455339b3072a4aa0ea/src/WebView.macos.tsx#L320) `messagingEnabled` is set to `false` only if `onMessage` is defined.
* [`src/WebView.android.tsx#L329`](https://github.com/react-native-community/react-native-webview/blob/9fbcedd6b88af631edbc3d455339b3072a4aa0ea/src/WebView.android.tsx#L329) `messagingEnabled` is set to `false` only if `onMessage` is defined.
* [`src/WebView.windows.tsx#L235`](https://github.com/react-native-community/react-native-webview/blob/9fbcedd6b88af631edbc3d455339b3072a4aa0ea/src/WebView.windows.tsx#L235) `messagingEnabled` is set to `false` only if `onMessage` is defined.
* [`ios/RNCWebView.m#L1249-L1254`](https://github.com/react-native-community/react-native-webview/blob/9fbcedd6b88af631edbc3d455339b3072a4aa0ea/ios/RNCWebView.m#L1249-L1254): the `injectedJavaScriptBeforeContentLoaded` and `injectedJavaScript` user scripts do not get added if `messagingEnabled` is `false` (my own FIXME recommendation appears above these lines).
* [`android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java#L1058-L1062`](https://github.com/react-native-community/react-native-webview/blob/9fbcedd6b88af631edbc3d455339b3072a4aa0ea/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java#L1058-L1062): Addition and removal of JS interfaces are toggled by the state of `messagingEnabled`.
* I can't find references to `messagingEnabled` in `windows/ReactNativeWebView`. Maybe I'm just looking in the wrong places, or maybe JS injection isn't supported at all on Windows, yet?

Since #1286 was merged, this issue is solved for iOS, but hasn't to my understanding been addressed for any of the other platforms.

The PR also didn't touch `src/WebView.ios.ts`, so it may furthermore be incomplete in any case.

**Comment by ekkis** [comment]
if the code is broken, fixing the documentation would be great to save us poor sods from hours of struggle.  the current documentation for `injectedJavaScript` says nothing of adding an `onMessage` prop.  granted that is documented below in the section properly concerned with that, but no reader could draw the conclusion the two usecases are interdependent

**Comment by ekkis** [comment]
in any case, the behaviour I see is a little different.  please refer to: https://stackoverflow.com/questions/61582866/why-dont-webview-script-injections-work

**Comment by gwmccull** [comment]
yeah, better documentation would certainly help but the behavior definitely changes in the last version or two

We're using the `injectedJavaScript` prop to add JS to our page that will hide some elements. It just runs this code:
```
document.querySelectorAll(`${selector}`)
          .forEach(selector => selector.style.display = 'none');
```
In the current version of our app, this code works correctly on iOS and Android. In a recent beta, I updated the version of `react-native-webview` that we're using and this function broke on iOS, but not on Android

adding `onMessage={() => null}` fixes the JS function but it's not obvious that this should be needed as I'm not expecting a message from the injected JavaScript

**Comment by zaptrem** [comment]
Still an issue as of 10.3.2.

**Comment by PrantikMondal** [comment]
I am already using 'onMessage'. Still it is not working to inject javascript.
My WebView something like that:
<WebView
onLoadEnd={() => { this._setstatus() }}
onNavigationStateChange={this.on_navigaton_new}
injectedJavaScript={custom_script}
onMessage={x => this.onMessageGet(x)}
javaScriptEnabled={true}
source={{ uri: this.state.url, forceReload: this.state.forceReload }}
allowsLinkPsreview={true}
incognito={true}
domStorageEnabled={true}
ref={(ref) => this.myWebView = ref}/>

**Comment by Peretz30** [comment]
still not fixed

**Comment by geiz** [comment]
Still an issue for me.
