### ISSUE TITLE
Cookies passed in custom header not working

### ISSUE THREAD

**Issue by dquessenberry** [react-native-webview/react-native-webview#1352]
**Bug description:**
I am trying to pass a cookie via a custom header, but it does not seem to work at all. My site looks for a specific cookie on certain pages and it doesn't seem to find it. I have also tried a super simple test example, exactly like the documentation, except the url is hitting a test page on a local server that creates an alert with all cookies. The documentation I am following is here: [https://github.com/react-native-community/react-native-webview/blob/master/docs/Guide.md#working-with-custom-headers-sessions-and-cookies](https://github.com/react-native-community/react-native-webview/blob/master/docs/Guide.md#working-with-custom-headers-sessions-and-cookies)

Am I missing something???

**To Reproduce:**
1) Spin up a local web server with a simple web page that uses JS to show an alert with all the document's cookies. JS example: 
```
<script type="text/javascript">
  alert('document.cookie='+document.cookie);
</script>
```
2) Create a simple RN app with the latest react-native-webview module, and add the following code:
```
const App = () => {
  return (
    <WebView
      source={{
        uri: 'http://localhost:8083', // location of the web page of step 1
        headers: {
          Cookie: 'cookie1=asdf; cookie2=dfasdfdas',
        },
      }}
      sharedCookiesEnabled={true}
    />
  );
};
```
3) Notice that none of the cookies set in the custom header are not found.

**Expected behavior:**
Cookies passed in a custom header can be read by the receiving web page.

**Environment:**
 - OS: macOS Catalina
 - OS version: 10.15.4
 - react-native version: 0.62.2
 - react-native-webview version: 9.4.0

**Comment by jenriquejr** [comment]
Maybe it is not the same thing, but I was able to workaround this by setting incognito=true in the WebView.

In my case the android implementation was overriding the cookie header I was setting.
I need to debug further to see why this happens.

Hope it helps.

**Comment by dharminderraja** [comment]
It was happening same with my implementation also. It was rewriting the cookies. After setting `incognito=true ` it seems to be working fine for now.

**Comment by dwxw** [comment]
I've also found this, but only on Android, iOS works fine.  Adding incognito mode made Android work, but sadly I can't use incognito mode for other reasons.

**Comment by TommyLeong** [comment]
@dwxw You mean you managed to send out custom header from iOS on all subsequent pages? I'm stuck here with this issue too. For now, my issue with iOS.

**Comment by dwxw** [comment]
> @dwxw You mean you managed to send out custom header from iOS on all subsequent pages? 

I did (for cookies at least), but I also had to do the [suggestion](https://github.com/react-native-community/react-native-webview/blob/master/docs/Guide.md#working-with-custom-headers-sessions-and-cookies) to get the route changes to resend the header cookies.  Are you doing that?

**Comment by TommyLeong** [comment]
@dwxw Glad that worked for you. Just curious, are you attaching cookie to the header? 

Yes, I did follow the suggestion given. Unfortunately it didn't work as expected, the cookie I passed via header to prop source didn't show up in subsequent page load. 

Well, I have just managed to fixed my issue. For me, I need to dive into the library manually and make some custom solution for my project. I extract the cookie's value from `websiteDataStore.httpCookieStore` then append into my request's HTTPHeaderField. Lastly, I reload my webpage with this new request (:

**Comment by teseo** [comment]
Is this meant to be fixed any time soon?

**Comment by tamarasuarezrod** [comment]
> I've also found this, but only on Android, iOS works fine. Adding incognito mode made Android work, but sadly I can't use incognito mode for other reasons. Interestingly it only seems to happen the first time I open the webview, subsequent times it is receiving the cookies for me.

The same thing happened to me, in my case, it was because my server redirects to another URL (for example, from `http://myweb.com` to `http://www.myweb.com`), and the cookies were loaded just on the first one. To fix it, I did what the [library guide says](https://rootstrap.atlassian.net/secure/RapidBoard.jspa?rapidView=50&projectKey=MR&modal=detail&selectedIssue=MR-870&assignee=5f1f13070d8b1a001b91b039). Basically, tracking the new URLs redirects, and rendering the web-view with the new one.

``` javascript
const CustomHeaderWebView = (props) => {
  const { uri, onLoadStart, ...restProps } = props;
  const [currentURI, setURI] = useState(props.source.uri);
  const newSource = { ...props.source, uri: currentURI };

  return (
    <WebView
      {...restProps}
      source={newSource}
      onShouldStartLoadWithRequest={(request) => {
        // If we're loading the current URI, allow it to load
        if (request.url === currentURI) return true;
        // We're loading a new URL -- change state first
        setURI(request.url);
        return false;
      }}
    />
  );
};

<CustomHeaderWebView
  source={{
    uri: 'http://example.com',
    headers: {
      'my-custom-header-key': 'my-custom-header-value',
    },
  }}
/>;
```

**Comment by Matiyeu** [comment]
Same for me, the cookies are not passed except with incognito=true ..
Has anyone found a solution?

**Comment by timbrownsf** [comment]
This still doesnt work. Has anyone figured out a solution for this? There are clearly provided repros and this is a big issue. Why does it keep getting closed? I've found 6 issues for the same subject all auto-closed.

**Comment by ccreonopoulos** [comment]
@timbrownsf @Matiyeu Just submitted a PR with a fix that worked for our project and have been using it as a patch. Finally got around to submit a PR after I've been using it for about 6 months. https://github.com/react-native-webview/react-native-webview/pull/2711
