### ISSUE TITLE
Error Loading Page Domain undefind

### ISSUE THREAD

**Issue by IntelliJAbhishek** [react-native-webview/react-native-webview#1374]
Hello,

I have implemented Brightcove direct play URL in webview. It working fine across many devices but few of them are getting error like below.

    Error Loading Page
    Domain: undefined
    Error Code: -8
    Description: net::ERR_TIMED_OUT

Please suggest me idea to fix this.

**Environment:**

- OS: Android
- OS Version: Unknown (Users getting this not my devices)
- react-native version: 0.61.5
- react-native-webview version: ^9.0.2

**Comment by ha-family** [comment]
got same issue on android 

OS: Android
react-native version: 0.61.5

**Comment by harunsmrkovic** [comment]
+1, have same issue on Android only (although code is sometimes `-6` or `-2`)

I've also had it happen once on my emulator, showing this:
![image](https://user-images.githubusercontent.com/6838180/82428508-e6689780-9a8a-11ea-8acb-5321a452da24.png)

**Comment by cx5168** [comment]
Works normally  in debug mode. but, same error in release mode. the url is [https://]

**Comment by cx5168** [comment]
solution:
https://github.com/react-native-community/react-native-webview/issues/1050

AndroidManifest.xml:
<application...
android:usesCleartextTraffic="true"

**Comment by IntelliJAbhishek** [comment]
@cx5168 Manifest already have that line. Still i got.

**Comment by 29er** [comment]
same issue here. Already confirmed that **android:usesCleartextTraffic="true"** exists in my manifest...
any clues ?

**Comment by gvsakhil** [comment]
same issue :(... **android:usesCleartextTraffic="true"** didnt help me

**Comment by SuperXonic** [comment]
I also have the same issue and android:usesCleartextTraffic="true" also not work.

<img width="318" alt="bug" src="https://user-images.githubusercontent.com/52225482/87496577-0f1d9f80-c67e-11ea-92fd-26cc2b116aa6.png">

**Comment by fletc3her** [comment]
I'm getting the same error as other posters. I'm loading the WebView with code below using a local HTML file which I require into the source. It works fine on iOS. In Expo 37 I saw the HTML raw on Android. Since upgrading to Expo 38 I get this error.

![Screen Shot 2020-08-08 at 12 24 05 PM](https://user-images.githubusercontent.com/3633406/89718325-8808d200-d972-11ea-8683-19c3b442ced9.png)

```
<WebView
  originWhitelist={['*']}
  source={ require('./assets/myHtml/complete.html') }
  style={{ marginTop: 0, width:288, height:288 }}
  injectedJavaScript={ 'if(window.myLoad)window.myLoad();true;' }
  onMessage={event => {
	const { data } = event.nativeEvent;
	setPicture(data);
  }}
  ref={MyWebView}
/>
```

**Comment by luojiong** [comment]
@SuperXonic  
Did you solve it？

**Comment by xCTAPx** [comment]
Still searching for solution...

**Comment by joseygordev** [comment]
Same here...Any solution ?

**Comment by tuladharjaa** [comment]
> I also have the same issue and android:usesCleartextTraffic="true" also not work.
> 
> <img alt="bug" width="318" src="https://user-images.githubusercontent.com/52225482/87496577-0f1d9f80-c67e-11ea-92fd-26cc2b116aa6.png">

Having the same issue in some Android devices only.

**Comment by xCTAPx** [comment]
May be cause is request to http, but not to https? Because I changed request to address with https protocol and everything is work.

**Comment by flashman2** [comment]
Have same situation, URL is https. Strange to see that the problem still not solved after 7 months of issue opening.

**Comment by testime007** [comment]
Hey team,

Kindly provide an update on this.

**Comment by joaomantovani** [comment]
Facing the same issue on production, any tips?

**Comment by testime007** [comment]
Guys, this issue is in expo, they have to roll out a fix

https://github.com/expo/expo/issues/6665#issuecomment-571623759

**Comment by sanshao** [comment]
Any news about this issue? I am having the same problem
RN: 0.63.2

![image](https://user-images.githubusercontent.com/2107913/103969867-dfb99c80-51a1-11eb-8846-9c4dc664c243.png)

**Comment by joaomantovani** [comment]
Hey guys, I resolved this issue updating the expo version!

```json
"@expo/config-types": "^40.0.0-beta.2",
"expo": "40.0.0",
```

**Comment by 026binit** [comment]
i updated expo version 
"expo": "^40.0.0",

but issue not resolved. still looking for solutions

**Comment by testime007** [comment]
+1

Yes, the issue still exists. I tried on android v5. Please post the working solutions

**Comment by iamabdulhaseeb** [comment]
Is the issue solved?

**Comment by Sushmeet** [comment]
Hi I am seeing this similar issue happening on
Android: Version 5
"expo": "^40.0.0",

I am not sure judging from comments if there was resolution to it. Would there be any steps possible to open this issue again or link to a new issue if that has already been done.

Thanks to everyone for there comments and chiming in

**Comment by SpeysPiotr** [comment]
I also face exactly the same problem on release build (it works fine in debug). I don't use expo. 

"react-native": "0.63.4",
"react-native-webview": "^11.2.1",

**Comment by haseeb0066** [comment]
It worked on both emulator and  APK file

step1:
just I add this line of code in AndroidManifest.XML
android:usesCleartextTraffic="true"

step2:
cd android     
gradlew clean 

step3:
then build APK file 
gradlew assembleRelease

**Comment by HammadAkbarRana** [comment]
need to run on real device problem is slove

**Comment by babyrusa** [comment]
same problem here just suddenly appear

**Comment by Moumene** [comment]
It's still happening too

**Comment by dvasquez** [comment]
same problem here using usesCleartextTraffic="true", release build doesn't work only debug

**Comment by Schtakelberg** [comment]
same problem on Android

**Comment by makcim392** [comment]
Same issue on Android, target SDK 31, RN version 0.64, http link, already have androidCleartextTraffic=true set

**Comment by AbhishekMuknak** [comment]
same issue here on Android RN version 0.65, https link,  already have androidCleartextTraffic=true set

**Comment by yeyintnaung135** [comment]
step1:
just I add this line of code in AndroidManifest.XML
android:usesCleartextTraffic="true"

step2:
cd android
gradlew clean

step3:
then build APK file
gradlew assembleRelease


step4:
then build APK file
open data usage permission for your app in your phone
https://www.youtube.com/watch?v=cu6j1W32jJ8

**Comment by theMasix** [comment]
+1. same issue here. Doesn't really matter if you set the `android:usesCleartextTraffic="true"`.
RN: `0.65`

**Comment by majidsajadi** [comment]
Cold booting the device/emulator fixed the issue for me. I guess using VPN in the machine would interrupt the device network.

**Comment by jeafgilbert** [comment]
Having the same issue on some devices, even already using prop `incognito={true}`. Clearing app data works though, but how to prevent it? incognito true should do the trick if it's related to cache. Any idea?

**Comment by cdliefanto** [comment]
I met the same issues and still does not have any solutions, i tried changing my AndroidManifest.xml/debug in permission or changed my info.plist the result is still the same. I am curious, is it the Component bug or is it my emulator?

**Comment by marwan2** [comment]
It works for me by do the following:
1- downgrade from reactnative-webview "11.0.0" to "^10.10.2"
2- downgrade react-native "0.64.2" to "0.67.0"

**Comment by JamersonWalderson** [comment]
Apparently the problem is related to permissions, some cookies are saved in the device's memory, and for that it is necessary to have read and write permission in the storage. I can solve it by adding to my code:

Manifest:

android.permission.WRITE_EXTERNAL_STORAGE" />
android.permission.READ_EXTERNAL_STORAGE" />

Screens:

PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE);
PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE);

**Comment by gersonmontenegroepam** [comment]
In case you are loading an external website, are you sure you have the correct URL with https prefix?

**Comment by sdkAppgain** [comment]
yes it has https
Any Solutions??

**Comment by sarah-hamdi-work** [comment]
> 

if we need to use https , whats wrong with it

**Comment by sarah-hamdi-work** [comment]
> > 
> 
> if we need to use https , whats wrong with it


if we need to use https , whats wrong with it

**Comment by AaronTJDev** [comment]
For me it was that it was that the link I was trying to open was using an http prefix. Added the following to my injected script and it resolved the issue. This the domain on the receiving end doesn't also have https setup.

` 
const tags = document.querySelectorAll('a[href*="http://<site-that-is-causing-issues>.com/"]');
  tags.forEach(tag => {
    tag.href = tag.href.replace('http','https');
  });
`

**Comment by zh17625375207** [comment]
![image](https://user-images.githubusercontent.com/40682261/191893406-69e8ccb5-b18f-46c6-b60c-8a4f5c08ec30.png)
ME TOO

**Comment by Maria-Elena-98** [comment]
Hi team!! Any solution? the problem still on android 🥺
"react-native": "0.65.1",
"react-native-webview": "^11.23.1",

**Comment by mainguyenhoi** [comment]
> > 
> 
> if we need to use https , whats wrong with it

tks, it work for me

**Comment by chubo274** [comment]
i still got same issue on:
i try to test on url: https://infinite.red
OS: Android
Simulator API 31
react-native version: 0.70.5
react-native-webview version: ^11.26.1

pls help :(

**Comment by chaudev** [comment]
Hi! 
I still on this issue.
My url is: https://,,,,

react-native version: 0.67.4
react-native-webview version: ^11.26.1

**Comment by jaroslavhuss** [comment]
Adding myself to the thread - iOS works fine, but Android does not work.

**Comment by niveditasharma428** [comment]
Hi.... It Worked for me 👍 💯  
1. Enter: npm install -g react-native-cli
2. detete assets folder - React Native Project - >android ->app->src->main->assets
3. Create New assets folder
4. Run command in React Native Project directory 
    eact-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res

**Comment by hannanstd** [comment]
it helped me:
https://github.com/react-native-webview/react-native-webview/issues/1050#issuecomment-664014859

**Comment by zechkonja** [comment]
How we can solve this? :) i also have this problem :(

**Comment by hieungochoangit** [comment]
How we can solve this? :) i also have this problem :(

**Comment by lufemas** [comment]
Same here
![image](https://github.com/react-native-webview/react-native-webview/assets/5956618/7c6f1008-29a2-4763-ab50-2eda945df431)

![image](https://github.com/react-native-webview/react-native-webview/assets/5956618/280b205b-13a3-4227-bec6-12ac36bc365a)

I'm not using expo.
    "react-native": "0.71.11",
    "react-native-webview": "^12.0.2",

**Comment by andyanday33** [comment]
Been getting 
Error loading page
Domain Undefined
Error Code: -6
Description: net::ERR_CONNECTION_REFUSED

using:
"expo": "~49.0.15",
"react-native": "0.72.6",

Switching to HTTPS worked for me

**Comment by naveen42266** [comment]
i getting this error
Error loading page
Domain: undefined 
Error Code: -1 
Description: net :: ERR_CLEARTEXT_NOT_PERMITTED

using :
"expo": "~50.0.3",
"react-native": "0.73.2"

any one help me to fix it ???

**Comment by abdalla3yash** [comment]
try it
adding a network security configuration file 

> network_security_config.xml 

to your app's res/xml 

```
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">localhost</domain>
    </domain-config>
</network-security-config>
```

Then, reference it in your app's manifest file

```
<application
    android:networkSecurityConfig="@xml/network_security_config"
    android:usesCleartextTraffic="true"
    >
  
</application>

```

**Comment by NoobMahbub** [comment]
I was facing the same error and here is how I fixed this issue

1. Restarted my android device

2. Removed the https:// from the url
https://techhelpbd.com/gitdown was throwing this error when I removed https:// then it worked fine.

```jsx
import * as React from 'react';
import { WebView } from 'react-native-webview';

export default function Browser() {
  return (
    <WebView
      source={{ uri: 'techhelpbd.com/gitdown' }}
    />
  );
}
```

**Comment by daskabe** [comment]
I was connecting to localhost node server. 

what worked for me is using 10.0.2.2  instead of localhost.

**Comment by Sumansourabh14** [comment]
Does anyone know how to fix this issue on an Expo managed project?

**Comment by xcboi2k** [comment]
i am encountering this problem in apk, in emulation and development build it works fine

**Comment by gabrielbiga** [comment]
I'm having the issue as well. Only for builded APKs. Emulation and Expo Go is working fine.

**Comment by choijiho0021** [comment]
There was exactly the same error, and I solved it like this. The server solved it by changing the redirect response to 301 or 302 instead of 308.

Example.

Before.
redirect(s"https://localhost/auth/canc?resultCode=99999&resultMsg=Unknown+Error", StatusCodes.PermanentRedirect)

After.
redirect(s"https://localhost/auth/canc?resultCode=99999&resultMsg=Unknown+Error", StatusCodes.TemporaryRedirect)

**Comment by ekko2665** [comment]
Is there have a solution?

**Comment by batazo** [comment]
Are there not a solution still?

**Comment by aderounmu** [comment]
Is there still no solution ?
