### ISSUE TITLE
Could not signal service com.apple.WebKit.WebContent

### ISSUE THREAD

**Issue by venkataluri** [react-native-webview/react-native-webview#1433]
**Bug description:**

While running webview on IOS i am getting warning message 
**Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service** 
and while submitting to Appstore also i am getting  webview deprecation warning.

**code:**
```

import {WebView} from 'react-native-webview';

<WebView source={{ uri: url}} style={{ marginTop: 0}} />
```

**Environment:**
- Platform: IOS
 - react-native version: '0.62.2'
 - react-native-webview version: '10.2.3'

**Comment by Zero-Zheng** [comment]
Do you have any news？

**Comment by jcohenho** [comment]
Running into the same issue. Is this [stackoverflow thread useful?](https://stackoverflow.com/questions/44585980/com-apple-webkit-webcontent-drops-113-error-could-not-find-specified-service)

**Comment by zaptrem** [comment]
Same issue here.

**Comment by crystalwm** [comment]
this issue sometimes occurs

**Comment by PundoJnr** [comment]
Still searching for solutions, facing the same [issue](https://github.com/apache/cordova-ios/issues/998)

**Comment by ahmedmhussein111** [comment]
Still searching for solutions, facing the same issue

**Comment by tututututututu** [comment]
still searching for solutions ...

**Comment by promit13** [comment]
still searching for solution

**Comment by Quietly-20201113** [comment]
+1

**Comment by chenweigh** [comment]
+1

**Comment by jhuonas** [comment]
still searching for solution

**Comment by nickhealy** [comment]
+1

**Comment by Svjard** [comment]
+1

**Comment by w8ight** [comment]
same issue here

**Comment by alzalabany** [comment]
still on-going. usually happen when react-navigation navigate back from a screen that had a webview

**Comment by gom1** [comment]
still searching for solution

**Comment by adithkrishnan98** [comment]
I too am facing this issue.. Webview runs well on Android but on iOS it doesn't even open.. Any solutions for this? Getting the error "Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service" on Xcode logs.
