### ISSUE TITLE
Task :react-native-webview:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by vervin** [react-native-webview/react-native-webview#1438]
```


import React, { Component } from 'react';
import { View } from 'react-native';
import { WebView } from 'react-native-webview';

export default class App extends Component {
  render() {
    return (
      <View style={{ flex: 1 }}>
        <WebView source={{ uri: 'https://www.baidu.com' }} />
      </View>
    );
  }
}


yarn add react-native-webview

yarn android


```

have a problem

> Task :react-native-webview:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings
16 actionable tasks: 16 executed
E:\react-native-pro\test\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\RNCWebViewModule.java:276: �
���: �Ҳ�������
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                                                    ^
  ����:   ���� Q
  λ��: �� VERSION_CODES
ע: E:\react-native-pro\test\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\RNCWebViewManager.javaʹ�
û�����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
ע: E:\react-native-pro\test\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\RNCWebViewManager.javaʹ�
���δ�������ȫ�Ĳ�����
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:unchecked ���±��롣
1 ������

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-webview:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 34s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
E:\react-native-pro\test\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\RNCWebViewModule.java:276: �
���: �Ҳ�������
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                                                    ^
  ����:   ���� Q
  λ��: �� VERSION_CODES
ע: E:\react-native-pro\test\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\RNCWebViewManager.javaʹ�
û�����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
ע: E:\react-native-pro\test\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\RNCWebViewManager.javaʹ�
���δ�������ȫ�Ĳ�����
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:unchecked ���±��롣
1 ������

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-webview:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 34s

    at makeError (E:\react-native-pro\test\node_modules\execa\index.js:174:9)
    at E:\react-native-pro\test\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runOnAllDevices (E:\react-native-pro\test\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:5)
    at async Command.handleAction (E:\react-native-pro\test\node_modules\@react-native-community\cli\build\index.js:186:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by vladrozhnev** [comment]
@vervin I have a solution.
1. Open the `build.gradle` file in the `android` folder (${workspace}/android/build.gradle).
2. Change `compileSdkVersion` to 29 in the `buildscript > ext` section.

**Comment by AbePlays** [comment]
> @vervin I have a solution.
> 
> 1. Open the `build.gradle` file in the `android` folder (${workspace}/android/build.gradle).
> 2. Change `compileSdkVersion` to 29 in the `buildscript > ext` section.

This solution works!!

**Comment by filipesr** [comment]
> @vervin I have a solution.
> 
>     1. Open the `build.gradle` file in the `android` folder (${workspace}/android/build.gradle).
> 
>     2. Change `compileSdkVersion` to 29 in the `buildscript > ext` section.

works!! thanks!

**Comment by Hani-Ghazi** [comment]
> @vervin I have a solution.
> 
> 1. Open the `build.gradle` file in the `android` folder (${workspace}/android/build.gradle).
> 2. Change `compileSdkVersion` to 29 in the `buildscript > ext` section.

Works! thanks!

**Comment by aashu700** [comment]
> @vervin I have a solution.
> 
> 1. Open the `build.gradle` file in the `android` folder (${workspace}/android/build.gradle).
> 2. Change `compileSdkVersion` to 29 in the `buildscript > ext` section.

It Works! Thank you!

**Comment by fgeorgsson** [comment]
Bumping compileSdkVersion to 29 does not help me, still get the `if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {` problem. Tried `gradlew clean` in the Android folder too, to no avail. I have SDK 29 installed.

**Comment by camilo7davila** [comment]
> Bumping compileSdkVersion to 29 does not help me, still get the `if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {` problem. Tried `gradlew clean` in the Android folder too, to no avail. I have SDK 29 installed.

I have the same issue, I don´t find compileSdkVersion  in buildscript > ext, I´m using react-native-webview 10.3.1

**Comment by ajengrf** [comment]
> @vervin I have a solution.
> 
> 1. Open the `build.gradle` file in the `android` folder (${workspace}/android/build.gradle).
> 2. Change `compileSdkVersion` to 29 in the `buildscript > ext` section.

Thanks it works for me, but changing it to 29 would not cause any problem right?

**Comment by pdsouza** [comment]
Upgrading to v10.4.0 fixed this issue for me.

**Comment by wiredmatrix** [comment]
In my case, I installed react-native-webview 11.4.6
in my android/build.gradle I have the following: 
buildToolsVersion = "30.0.0"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        ndkVersion = "23.0.7272597"

my complieSdkVersion and targetSdkVersion are 30 because expo-permission requires it to be 30, but all the solution am seeing for the react-native-webview is to make complieSdkVersion and targetSdkVersion to 29. How do I solve my issue? Any help is appreciated.

**Comment by wiredmatrix** [comment]
In my case, I installed react-native-webview 11.4.6
in my android/build.gradle I have the following: 
buildToolsVersion = "30.0.0"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        ndkVersion = "23.0.7272597"

my complieSdkVersion and targetSdkVersion are 30 because expo-permission requires it to be 30, but all the solution am seeing for the react-native-webview is to make complieSdkVersion and targetSdkVersion to 29. How do I solve my issue? Any help is appreciated.

**Comment by henrineken** [comment]
Revert version to 11.4.5

There is a bug on 11.4.6 PR

**Comment by mkamals** [comment]
@wiredmatrix I have the same config what you have but react-native-webview 11.4.5. Still facing the below issue.
 error: method onPermissionRequest(PermissionRequest) is already defined in class RNCWebChromeClient
    public void onPermissionRequest(final PermissionRequest request)

 buildToolsVersion = "30.0.3"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        androidXCore = "1.0.2"

**Comment by AndersonSchmidt** [comment]
> In my case, I installed react-native-webview 11.4.6
> in my android/build.gradle I have the following:
> buildToolsVersion = "30.0.0"
> minSdkVersion = 21
> compileSdkVersion = 30
> targetSdkVersion = 30
> ndkVersion = "23.0.7272597"
> 
> my complieSdkVersion and targetSdkVersion are 30 because expo-permission requires it to be 30, but all the solution am seeing for the react-native-webview is to make complieSdkVersion and targetSdkVersion to 29. How do I solve my issue? Any help is appreciated.

Did you manage to solve it?

**Comment by mkamals** [comment]
> @wiredmatrix I have the same config what you have but react-native-webview 11.4.5. Still facing the below issue.
> error: method onPermissionRequest(PermissionRequest) is already defined in class RNCWebChromeClient
> public void onPermissionRequest(final PermissionRequest request)
> 
> buildToolsVersion = "30.0.3"
> minSdkVersion = 21
> compileSdkVersion = 30
> targetSdkVersion = 30
> androidXCore = "1.0.2"
> 
> Any help would be appreciated. Thanks in advance.

Hey @wiredmatrix , I was able to fix this. The version in package.json and package-lock.json was mismatching. I uninstalled the old package and reinstalled it again to get it fixed. I hope this should fix your issue as well.

**Comment by wiredmatrix** [comment]
> > @wiredmatrix I have the same config what you have but react-native-webview 11.4.5. Still facing the below issue.
> > error: method onPermissionRequest(PermissionRequest) is already defined in class RNCWebChromeClient
> > public void onPermissionRequest(final PermissionRequest request)
> > buildToolsVersion = "30.0.3"
> > minSdkVersion = 21
> > compileSdkVersion = 30
> > targetSdkVersion = 30
> > androidXCore = "1.0.2"
> > Any help would be appreciated. Thanks in advance.
> 
> Hey @wiredmatrix , I was able to fix this. The version in package.json and package-lock.json was mismatching. I uninstalled the old package and reinstalled it again to get it fixed. I hope this should fix your issue as well.

In my own case there's no package-lock.json in my project, am using yarn. I solve the issue by uninstalling/remove react-native-webview and installing it from react-native-community/react-native-webview.
Therefore, react-native-community/react-native-webview worked for me with no errors.

**Comment by deksmond** [comment]
Using this article https://engineering.brigad.co/demystifying-react-native-modules-linking-964399ec731b worked for me

**Comment by jalispran** [comment]
> In my case, I installed react-native-webview 11.4.6
> in my android/build.gradle I have the following:
> buildToolsVersion = "30.0.0"
> minSdkVersion = 21
> compileSdkVersion = 30
> targetSdkVersion = 30
> ndkVersion = "23.0.7272597"
> 
> my complieSdkVersion and targetSdkVersion are 30 because expo-permission requires it to be 30, but all the solution am seeing for the react-native-webview is to make complieSdkVersion and targetSdkVersion to 29. How do I solve my issue? Any help is appreciated.

I had the exact same issue. In my case it was because of a corrupted `package-lock.json`  file. Removing `package-lock.json` and `node_modules`  and running `npm install` solved it for me.

**Comment by azamali6995** [comment]
> > @vervin I have a solution.
> > 
> > 1. Open the `build.gradle` file in the `android` folder (${workspace}/android/build.gradle).
> > 2. Change `compileSdkVersion` to 29 in the `buildscript > ext` section.
> 
> 
hy!
i hope you will be fine.

i don't understand how to change. i change it manually. 
please guide me. how i do.
regard shall be thankfull to you.

**Comment by faizanaliedu** [comment]
After hours of searching and bursting my head against wall I figured out that Android in React Native does not allow similar packages to reside in the project. 

In my case I had `react-native-cookies` and `@react-native-cookies/cookies` packages that add similar code to the Kotlin file upon build. This causes issue of similar imports in java JDK. 

I removed one and it worked like a charm.

Happy coding!

**Comment by zhuernm** [comment]
> https://engineering.brigad.co/demystifying-react-native-modules-linking-964399ec731b

 buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 30

It worked for me

**Comment by faddablack** [comment]
In my case it was caused by having used both yarn and npm for package management. Deleting package-lock.json fixed the issue for me.

**Comment by luishng** [comment]
Hello, I'm still using expo sdk 43 in the project, with this build.gradle:

kotlin_version = "1.6.10"
buildToolsVersion = "29.0.3"
minSdkVersion = 23
compileSdkVersion = 33
targetSdkVersion = 33

In my case I needed to change the react-native-webview to version "11.22.7". This version had a fix to support this sdkVersion "33"

**Comment by Akash-Pavithran** [comment]
I had to update the targetSdkVersion and compileSdkVersion  to 33 as per Play Store warning.
Webview threw the same error and it was fixed when react-native-webview was upgraded to version "11.22.7".
