### ISSUE TITLE
iOS: White screen after a large API request load

### ISSUE THREAD

**Issue by DevArenaCN** [react-native-webview/react-native-webview#1468]
**Bug description:**

React Native WebView would render a white screen during a large API request.
This behavior is really depending on how much data you are requesting, smaller dataset would be working just fine, only when the data gets larger the problem would appear. Now I know there's two sides of this issue, just wondering if there're some setup that I'm missing

**To Reproduce:**

Dispatch a request within the website (roughly 7000kb of data), request won't finish and the WebView is dead, rendering a white screen with.

**Expected behavior:**

Should render as normal

**Screenshots/Videos:**

```
2020-06-18 08:39:15.996582-0400 myApp[2928:529484] [shim] BKSProcessAssertion "ConnectionTerminationWatchdog" initialized with invalid pid
2020-06-18 08:39:16.157852-0400 myApp[2928:529484] [ProcessSuspension] 0x10436f450 - ProcessAssertion::processAssertionWasInvalidated()
```

**Environment:**
 - OS: iOS
 - OS version: 13.5.1
 - react-native version: 0.61.5
 - react-native-webview version: 10.3.1

**Comment by GiuseppePennisi** [comment]
Hi, i got the same problem. Did you find a solution?

**Comment by DevArenaCN** [comment]
> Hi, i got the same problem. Did you find a solution?

No unfortunately, had to do some stuff with the api to reduce the load.

**Comment by mayursarode4** [comment]
> 
> 
> > Hi, i got the same problem. Did you find a solution?
> 
> No unfortunately, had to do some stuff with the api to reduce the load.

@DevArenaCN I'm also having the same issue, in my case I'm loading a url with body (around 15+ params) and with method: "POST", I'm getting white screen, can you tell me how to reduce the load?

**Comment by mayursarode4** [comment]
Hi @DevArenaCN , I'm able to solve this issue, Here is a workaround that worked for me :

Add below in your source props:
`headers: { 'Content-Type': 'application/x-www-form-urlencoded', }`

For example:
`<WebView`
      `style={styles.WebViewStyle}`
      `source={{` 
                        `uri: web_url,` 
                        `method: "POST",` 
                        `headers: { 'Content-Type': 'application/x-www-form-urlencoded', },` 
                        `body: "name=test"`
                  `}}`
  `/>`

Try it and let me know.

**Comment by dexterlohnes** [comment]
@mayursarode4 I am running into the same issue and this solution did not help me. What is the theory behind it being a solution?

**Comment by jtreat3** [comment]
I am also interested in a full solution.

**Comment by GiuseppePennisi** [comment]
I tried the solution indicated by @mayursarode4 but it doesn't work.

**Comment by MarcelSchuermann** [comment]
I have a similar issue here:
https://stackoverflow.com/questions/67571345/ios-iphone-11-flashing-black-and-white-while-browsler-is-constantly-reloading-r
Did you find any solution to this?

**Comment by NIXBLACK11** [comment]
still searching for solutions
