### ISSUE TITLE
Keyboard event event.key is unidentified

### ISSUE THREAD

**Issue by aliazizi** [react-native-webview/react-native-webview#1473]
**Bug description:**
I have a texteditor ( quill.js ) in my webview, and there is a bug in it, enter ( new line ) does not change text focus

I try to figure out what is the problem and add 'keydown' event to a custom div with content-editable. and after that I see the value of event.key is unidentified for all input

**To Reproduce:**
Try load webview with this html

```
<div
      tabindex="1"
      contenteditable="true"
      id="test-test"
      style="width: 300px; height: 300px;"
    ></div>
    <script>
      document
        .getElementById("test-test")
        .addEventListener("keydown", function (e) {
          alert(e.key || e.keyCode || "empty");
        });
    </script>
```

**Expected behavior:**
event.key or event.keyCode has value

**Screenshots/Videos:**
![image](https://user-images.githubusercontent.com/8492767/85202261-639d5b80-b31a-11ea-8fb2-0b539a9631ff.png)

**Environment:**
 - OS: android
 - OS version: android 9
 - react-native version: 62.2
 - react-native-webview version: 10.3.1

**Comment by aliazizi** [comment]
the issue still exist

**Comment by aliazizi** [comment]
the issue exist @github-actions

**Comment by aliazizi** [comment]
the issue exist @github-actions

**Comment by aliazizi** [comment]
the issue exist @github-actions

**Comment by aliazizi** [comment]
the issue exist @github-actions

**Comment by aliazizi** [comment]
the issue exist @github-actions

**Comment by bittu1028** [comment]
this issue still exist

**Comment by JunDev76** [comment]
this issue still exist only on "Android"

**Comment by kevalkikani180** [comment]
this issue i still face on android and ios in real device but when i check on simulator or emulator at time its complete working fine

**Comment by PedroBozzeta** [comment]
I got the same problem, like [kevalkikani180](https://github.com/kevalkikani180), i tested my app on differents emulators and works perfectly fine, but in android it doesn't.
