### ISSUE TITLE
Facebook Login problem

### ISSUE THREAD

**Issue by falay26** [react-native-webview/react-native-webview#1475]
Hey guys,
I am building a mobile application with this git, via expo-cli.
I do not even know if this is related but i am so frustrated with a problem i have encountered so here it goes:
The web site which i am trying to convert to an application with web view has 'Login with FaceBook' and 'Login with Google' options and they are working well on web browsers. But on the webview i am not getting the result as in the browsers.
For FB login, it redirects to the facebook's oauth page, after you login there redirects back to the website but nothing happens.
For Google login, it redirects to the google's url with an error (disallowed_useragent)
I know these are not issues about git, maybe it is just because i am new to the webview. But i read all the docs for several times and couldn't seem to figure out how to handle these.
Any help would be appreciated a lot guys, thanks all.

**Environment:**
 - OS: iOs
 - OS version: 13.5.1
 - react-native-webview version: 10.3.1

**Comment by unpokolokko** [comment]
I'm facing the same problem. Any solution/ workaround ?

**Comment by unpokolokko** [comment]
for google login, you need to set the useragent :

`  <WebView
            ref={browserRef}
            userAgent="Mozilla/5.0 (Linux; Android 4.1.1; Galaxy Nexus Build/JRO03C) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.166 Mobile Safari/535.19"
            source={{ uri: selectedUrl }}
          />`

i refer to this https://github.com/react-native-community/react-native-webview/issues/162

**Comment by trithien98** [comment]
Hi @falay26 , i currently facing this issue , do you solves this problem

**Comment by naiduyanda** [comment]
me also facing the same issue with facebook login

**Comment by markdavies** [comment]
This is still an issue for me for any Facebook links
