### ISSUE TITLE
Using webview causes OOM on emulator

### ISSUE THREAD

**Issue by richardfelkl** [react-native-webview/react-native-webview#1477]
**Bug description:**
When using web view on a screen with fetched data Webview it causes out of memory kill of the process.

From logcat:

```
2020-06-22 19:44:14.983 1651-1651/? E/lowmemorykiller: Error writing /proc/11599/oom_score_adj; errno=22
```

**To Reproduce:**
Use android Emulator on a Mac, load object using fetch and try to render a Webview. I wasn't able to reproduce on iOS or Android physical device.

**Expected behavior:**
Webview working on emulator without killing the app.

**Environment:**
 - OS: Android
 - OS version: 9, 10
 - react-native version: 61.2
 - react-native-webview version: 10.3.1

**Comment by sej1228** [comment]
How did it solve it later
