### ISSUE TITLE
onLoadingFinish on Android not working as expected

### ISSUE THREAD

**Issue by Foomethod** [react-native-webview/react-native-webview#1482]
**Bug description:**
The issue only persists in Android.
A change in the navigation state url causing Android Webview's viewState to be forever stuck in "LOADING" due to previous url having some capital letters when compared to current loading url. However, i found that Webview.ios.js doesnt have such checking in the onLoadingFinish function.

**To Reproduce:**
Redirect from any url with the SAME url but with some capital alphabets.
Example: from www.google.com to www.Google.com

**Expected behavior:**
onLoadingFinish function should have the same checking function in iOS and Android.

**Screenshots/Videos:**
<img width="682" alt="Screenshot 2020-06-24 at 7 26 52 PM" src="https://user-images.githubusercontent.com/18421394/85648464-6958bf80-b6d3-11ea-9c75-5458297b8c9f.png">
_(Webview.ios.js)_

<img width="631" alt="Screenshot 2020-06-24 at 7 26 42 PM" src="https://user-images.githubusercontent.com/18421394/85648475-6e1d7380-b6d3-11ea-81f6-c01280a4acfe.png">
_(Webview.android.js)_

**Environment:**
 - react-native version: 0.61.5
 - react-native-webview version: 8.0.2

**Comment by Foomethod** [comment]
Issue still persist on latest version of React-Native-Webview: 10.3.1

Suggest to change to compare the start and current urls in lowercases.

if (url && this.startUrl && url.toLowerCase() === this.startUrl.toLowerCase()) { this.setState({ viewState: 'IDLE' }); }

I'm not sure about the impact to the rest but this works fine for me.

**Comment by Foomethod** [comment]
#1487

**Comment by dabonnestor** [comment]
@Foomethod I have similar problem as well. Were you able to make temp fix for this issue without modifying the lib files?

**Comment by Foomethod** [comment]
@dabonnestor

The main reason why it was loading forever was because the state of the webview component was still in **"LOADING"** after a **_strict comparison (===)_** of the current and previous url.

`
if (url === _this.startUrl) {
      _this.setState({
            viewState: 'IDLE'
      });
}
`

The webview component doesn't provide any other way to modify it's own state to **"IDLE"**.
I resorted to modifying the lib file because `webviewRef.current.stopLoading()` wasn't an ideal solution for me as the website I'm on does multiple redirects, doing stopLoading() would stop the entire redirection process.

stopLoading may just work for you if the website you are visiting doesn't redirect too much.
Alternately, you may replace the above code with the below in the lib files. _(Webview.android.js)_

`if (url && _this.startUrl && url.toLowerCase() === _this.startUrl.toLowerCase()) {
                _this.setState({
                    viewState: 'IDLE'
                });
            }`

**Comment by Foomethod** [comment]
#1487
