### ISSUE TITLE
Way to detect is user has scrolled to the last page in the webview

### ISSUE THREAD

**Issue by alysiatran** [react-native-webview/react-native-webview#1508]
Hello, I've attached a link to a multiple page long pdf for the webview but wanted to see if there is a way to detect if a user has scrolled to the end of the pdf/webview. Is there a way to detect this? I wanted to add a button to the bottom of the last page, but it just ends up showing at the bottom of the webview on initial load.

**Comment by timothydlee** [comment]
Any news on this one? I'd like to achieve a similar effect.
