### ISSUE TITLE
Weird Cookies managment - android

### ISSUE THREAD

**Issue by nicoceledon** [react-native-webview/react-native-webview#1509]
**Bug description:**
When login to a website and closing the app right away after logged in, the session get lost. It isn't always like that, but most of the time on my testing device. If you navigate a on the site, and the close the app(maybe 30 seconds), if you close the app you keep the session.

It also happens something similar when you logout. I guess that it also has something to do with the server too, but still it seems that it doesn't save the cookies in the right manner.

**To Reproduce:**
https://github.com/nicoceledon/webview

Clone the repo and to put a website on the uri where you need to login, and close the app as soon as you get logged in. It doesn't happens always, what's make verifying the bug a little tedious, but it happens. One of those times when you open the app you won't be logged in, even if you did before.

**Expected behavior:**
Keep the session if i close the app

**Environment:**
 - OS: Android 
 - OS version: 10 and 9
 - react-native version: 0.63.0
 - react-native-webview version: 10.3.2

**Comment by linyoujie** [comment]
same problem here, let me know if there is an alternate way to do it.

**Comment by nicoceledon** [comment]
@linyoujie What I did is use the cookie manager. You can retrieve it with [Cookie Manager](https://github.com/react-native-community/cookies). As soon as I got the logged, I read the cookie and save it in memory. For the next time, I restore this with the same Cookie Manager

**Comment by xcxooxl** [comment]
Having the same issue, syncing cookies when logging out or logging in is a problem,
When closing the app too fast the session get lost, if you tried to logout and then close app then you are still logged in.
and if you are logging in and closed the app then you stay logged out.

**Comment by jpodpro** [comment]
cookies on android have had this bug for at least a year and a half. see #631

**Comment by ojaspatharkar-qure** [comment]
I am still facing this issue, any solution yet?

**Comment by tocttou** [comment]
I had the webview opened in a modal that got closed right after login, which prevented the cookies from being persisted only on Android (iOS worked fine). await CookieManager.flush() before closing the modal made it work.

https://github.com/react-native-cookies/cookies
