### ISSUE TITLE
onNavigationStateChange is not working on Android in Expo App

### ISSUE THREAD

**Issue by mitchobrian** [react-native-webview/react-native-webview#1510]
Hey, in the current Version "react-native-webview": "8.1.1" the onNavigationStateChange event is not triggered in any Android device. On iOS it works perfectly. It is no normal # tag url change, it is a real change from /home to /dashboard.

```
import React, {
  useEffect,
  useState,
  useRef,
  useCallback,
  StyleSheet,
  useContext,
} from "react";
import {
  RefreshControl,
  ActivityIndicator,
  View,
  ScrollView,
  Alert,
} from "react-native";
import { WebView } from "react-native-webview";

const WebViewComponent = (props) => {
  const [refreshing, setRefreshing] = useState(false);
  const [loaded, isLoaded] = useState(false);
  const [urlReal, setUrl] = useState((props?.url != undefined
        ? props.url
        : "httsp://google.com)
  );

  const webViewRef = useRef();

  const onRefresh = useCallback(async () => {
    setRefreshing(true);
    webViewRef.current.reload();
    setRefreshing(false);
  }, [refreshing]);

  const _onNavigationStateChange = (webViewState) => {
    console.log(webViewState.url);
    // no action on android
  };

  return (
    <View>
      <ScrollView
        refreshControl={
          <RefreshControl refreshing={refreshing} onRefresh={onRefresh} />
        }
      >
        <WebView
          ref={(ref) => (webViewRef.current = ref)}
          onLoadStart={(e) => {
            console.log("onLoadStart");
          }}
          onLoad={(e) => {
            console.log("onLoad");
          }}
          onLoadEnd={(e) => {
            console.log("onLoadEnd");
          }}
          renderError={(e) => {
            console.log("renderError");
          }}
          source={{
            uri: urlReal,
          }}
          startInLoadingState={true}
          domStorageEnabled={true}
          javaScriptEnabled={true}
          onNavigationStateChange={(e) => _onNavigationStateChange(e)}
          thirdPartyCookiesEnabled={true}
        />
      </ScrollView>
    </View>
  );
};
```

**Environment:**
 - OS: Andriod
 - expo version: 37.0.3
 - react-native-webview version: 8.1.1

**Comment by mitchobrian** [comment]
It also do not work with the current Version of webview:
"react-native-webview": "^10.3.2"

**Comment by mobihack** [comment]
Are you using an SPA like Nuxt.JS in the webpage?

**Comment by mobihack** [comment]
I think what is happening is that after the initial page load there is "no actual" page load taking place. Vue based application when router-link/nuxt-link are used they don't reload the page. The replace the content of the next page minimizing loading. But in the case of react-native-webview it doesn't constitute a page load.

[updateNavigationState](https://github.com/react-native-community/react-native-webview/blob/438e29298b39c54ff70629ca4274c979a67b2b3e/src/WebView.android.tsx#L182) is the function called when a navigation state change takes place. This method is only called when [onLoadingStart](https://github.com/react-native-community/react-native-webview/blob/438e29298b39c54ff70629ca4274c979a67b2b3e/src/WebView.android.tsx#L197) and [onLoadingFinish](https://github.com/react-native-community/react-native-webview/blob/438e29298b39c54ff70629ca4274c979a67b2b3e/src/WebView.android.tsx#L231). In the case of SPA, a page reload may not take place.

**Comment by mobihack** [comment]
Possible fix is to call updateNavigationState when webview url is changed.

**Comment by mitchobrian** [comment]
> Possible fix is to call updateNavigationState when webview url is changed.

How could that work? How can I watch the url when NavigationState is not called?

**Comment by mobihack** [comment]
That was for an internal fix.

Check below link for an idea. You could find some way to send route change in the SPA to the react native application.
 
https://stackoverflow.com/questions/53297300/how-to-communcation-between-web-inside-webview-back-to-react-native-apps

> Possible fix is to call updateNavigationState when webview url is changed.

**Comment by mitchobrian** [comment]
> > Possible fix is to call updateNavigationState when webview url is changed.
> 
> That was for an internal fix.
> 
> Check below link for an idea. You could find some way to send route change in the SPA to the react native application.
> 
> https://stackoverflow.com/questions/53297300/how-to-communcation-between-web-inside-webview-back-to-react-native-apps

I fixed it that way, but this could only be a workaround in my mind!

**Comment by jkoutavas** [comment]
This issue still exists. I'm seeing it on React Native 0.61.0 and react-native-webview 10.9.1

**Comment by ali27001** [comment]
the problem continues. The site I connected with webview is react (so spa) I caught the url to navigate in iOS, but after connecting to android I can't catch the url

**Comment by maknom66** [comment]
> the problem continues. The site I connected with webview is react (so spa) I caught the url to navigate in iOS, but after connecting to android I can't catch the url

Facing the same issue

**Comment by rmat-rahmat** [comment]
> > the problem continues. The site I connected with webview is react (so spa) I caught the url to navigate in iOS, but after connecting to android I can't catch the url
> 
> Facing the same issue, working on ios but not on android

i got the same issue with url without https
for the one with https i don't have any problems.

i suggest to use shouldStartLoadWithRequestHandler to listen to the url.

from what i experience i can conclude that
https can be listen by shouldStartLoadWithRequestHandler &  onNavigationStateChange
http can only be listen by shouldStartLoadWithRequestHandler

**Comment by blackstar0223** [comment]
@ali27001 Have you got any solutions? I'm facing the same issue.

**Comment by hojasc** [comment]
Same problem, any solution?

**Comment by AndrosVGL** [comment]
Same issue. Any news on this?

**Comment by valery-lavrik** [comment]
Same issue. Any news on this?

**Comment by de-jure** [comment]
Same too

**Comment by OxamaHxn** [comment]
same problem too

**Comment by Th0masso** [comment]
In my case using html as a source for the webview was the problem (android only)
```js
source={{ html: myHtml, }}
```
I changed it to uri and it worked
```js
source={{ uri: myUri, }}
```

**Comment by paulg0614** [comment]
Seems to be calledon android if I set 
setSupportMultipleWindows={false}

**Comment by clemwo** [comment]
setSupportMultipleWindows={false} doesn't change anything for me.  
However I saw that you can use `onLoadProgress`to handle opening links in external browser on Android.
My solution that allows opening external links in both iOS and Android: 
```
  // iOS open external links in browser
  // doesnt work on android
  const onNavigationStateChange = (navState: WebViewNavigation) => {
    if (navState.url.includes('maindomain.com')) return
    webViewRef.current?.stopLoading()
    Linking.openURL(navState.url)
  }

  // android open external links in browser
  // doesnt work on iOS
  const onLoadProgress = (event: WebViewProgressEvent) => {
    if (event.nativeEvent.url.includes('maindomain.com')) return
    webViewRef.current?.stopLoading()
    Linking.openURL(event.nativeEvent.url)
  }

  return (
    <WebView
      {...webViewProps}
      source={{ uri: url }}
      ...
      onNavigationStateChange={onNavigationStateChange}
      onLoadProgress={event => onLoadProgress(event)}
    />
  )
```
