### ISSUE TITLE
[Android] Dimensions API stops working randomly after a while

### ISSUE THREAD

**Issue by cristianoccazinsp** [react-native-webview/react-native-webview#1527]
**Bug description:**

Something within the WebView component breaks the RN Dimensions API.  I can't still figure out which update broke it (RN or WebView), but still testing.

Basically, after mounting and unmounting a WebView, the Dimensions API becomes completely broken (no events are fired, and values never update).  The issue started after upgrading to RN 0.63.1 and WebView to 10.3.2. I will be reverting to see what's causing the issue.

Reported here as well: https://github.com/facebook/react-native/issues/29451

**To Reproduce:**

Render a simple Android app that listens to Dimension changes (or uses the API) and that supports rotation. Mount and unmount a webview. Rotate the device a few times and observe how the Dimensions API no longer fires events nor updates.

**Expected behavior:**

WebView should not break the Dimensions API.

**Screenshots/Videos:**

**Environment:**
 - OS: Android
 - OS version: any
 - react-native version: 0.63.1
 - react-native-webview version: 10.3.2

**Comment by cristianoccazinsp** [comment]
Update: Downgrading the library did not help, definitely an issue with RN.  However, it is still curious how only after a webview is loaded the issue is triggered.

**Comment by cristianoccazinsp** [comment]
Still an issue

**Comment by cristianoccazinsp** [comment]
Please re open this; this is a critical bug for apps that support rotation.

**Comment by junaid-cloud9** [comment]
facing same issue when device rotates. The Dimensions API stops providing updated values.

**Comment by ReyRod** [comment]
Having the same bug, please reopen

**Comment by jgcook935** [comment]
I'm having the same issue. Is there any workaround or solution?

**Comment by TarasDumych** [comment]
This issue was fixed in RN 0.63.4.
For me it works with next versions:
    "react-native": "0.63.4"
    "react-native-webview": "^11.6.5"
