### ISSUE TITLE
Cookie not being sent with resource requests

### ISSUE THREAD

**Issue by 1rahul1** [react-native-webview/react-native-webview#1532]
We have a use case in which when we loading a page in the webview, it itself does many resource requests and these resource requests require the cookie to be sent with them. Currently, react-native-webview can only intercept the URLs on new page load but not for the resource requests sent by the page itself.

**Proposed solution**
We can use a map to keep the record of the "authority name" of the URL and the cookie for it. We get this data from the header in the **source** prop. We can then override the **shouldInterceptRequest** callback in the RNCWebViewClient to intercept and send the cookie according to the "authority name". This will send the cookie with the resource requests which are sent by the page which we loaded. 
I can raise a PR for this.

**Comment by TommyLeong** [comment]
Same here having issue in getting cookie pass into request header for subsequent pages load.
