### ISSUE TITLE
Bug: WebView scrollbar when keyboard is showing

### ISSUE THREAD

**Issue by bryan-opslock** [react-native-webview/react-native-webview#1541]
**Bug description:**

There is a foreign scrollbar for the WebView that displays when the keyboard shows up. This happens even if a Webview is being shown where the page was built to never show a `body` overflow scroll.

When there is the following HTML, it still causes a scrollbar to occur when a keyboard is shown:

	<!DOCTYPE html>
	<html>
		<head>
			<meta content="width=device-width, initial-scale=1" name="viewport">
		</head>
		<body style="overflow:hidden">
			<div style="position:fixed; height:100%; width:100%; border:1px solid red"></div>
		</body>
	</html>

**To Reproduce:**

    <WebView  source={{ uri: 'http://localhost:3000/views/comments/5ebdbe10a397b9418a962e86' }} />;

**Expected behavior:**

There should be no scrollbar on the WebView if there is no scrollbar regardless of the window size on in a regular browser.

**Environment:**
 - react-native version: 0.61.5
 - react-native-webview version: ^10.3.2

**Comment by CesarLanderos** [comment]
@bryan-opslock did you found a fix for this by any chance?
