### ISSUE TITLE
Intercept Network Calls in Webview

### ISSUE THREAD

**Issue by pravz71** [react-native-webview/react-native-webview#1548]
Hi,
My issue is more of a question than a feature-request. I wanted to know if there is a way to intercept network calls(like any AJAX calls) made inside the WebView. Do we have anything similar to onNavigationStateChange as this only triggers when url changes occur. Please correct me if I am missing out on something.

TIA

**Comment by evanc** [comment]
maybe you could inject some javascript to wrap the built-in `fetch` and `XMLHttpRequest`.

**Comment by DANIELVISPOBLOG** [comment]
Something like the following code should work to log calls:

XMLHttpRequest.prototype.openParent = XMLHttpRequest.prototype.open;
XMLHttpRequest.prototype.open = function (...params) { 
    console.log("########## NEW REQUEST");
    console.log(params);
    this.openParent(...params);
};

**Comment by pravz71** [comment]
Thank you @evanc  and @DANIELVISPOBLOG  for the response. What I want to do by intercepting network calls and load the assets from the app cache if available. Is this possible?
The Webview default caching also works but it clears the cache when the webview component is unmounted.
Could you please help me with this.

**Comment by evanc** [comment]
I don't think you'll be able to do that.

If it's really critical that you maintain the cache maybe instead of unmounting the webview when you leave whatever page you could mount it at a high enough level in your tree that it's always mounted, and then show/hide it as needed, absolute positioned to fit on top of where you want it to go.

You'd said in the first post that you were looking at stopping AJAX requests, which generally are not cached.

**Comment by vk562398** [comment]
> Something like the following code should work to log calls:
> 
> XMLHttpRequest.prototype.openParent = XMLHttpRequest.prototype.open; XMLHttpRequest.prototype.open = function (...params) { console.log("########## NEW REQUEST"); console.log(params); this.openParent(...params); };

How we can inject it

**Comment by thanhnvpk01168** [comment]
@pravz71 , can you share your code if you did

**Comment by DeepakSharma04** [comment]
```
   const INJECTED_JAVASCRIPT = `(function() {
      var open = XMLHttpRequest.prototype.open;
      XMLHttpRequest.prototype.open = function() {
          this.addEventListener("load", function() {
              var message = {"status" : this.status, "response" : this.response}
              window.ReactNativeWebView.postMessage(JSON.stringify(message));
          });
          open.apply(this, arguments);
      };})();`;


<WebView
          style={[{
            alignSelf: 'stretch',
            width: Dimensions.get('window').width,
            height: Dimensions.get('window').height,
            marginTop: Platform.OS === 'ios' ? 36 : 0
          }]}
          source={{ uri: azureLoginUrl }}
          javaScriptEnabled={true}
          domStorageEnabled={true}
          decelerationRate="normal"
          javaScriptEnabledAndroid={true}
          onNavigationStateChange={(navState) => { this._handleTokenRequest(navState) }}
          startInLoadingState={true}
          renderLoading={() => {
            return this.displaySpinner()
          }}
          injectedJavaScript={INJECTED_JAVASCRIPT}
          scalesPageToFit={true}
          onMessage={event => {
            console.log('>>>', event);
          }}
        />
```

But not working to get API response.

**Comment by Deepak-meena2000** [comment]
> 

@DeepakSharma04 do u have the full code of this implementation ??

**Comment by Artem0302** [comment]
https://github.com/react-native-webview/react-native-webview/blob/master/docs/Guide.md#controlling-navigation-state-changes

**Comment by wuxnz** [comment]
Hello. For anyone still looking for a solution to intercept requests from a WebView I have just made a React Native module for this. It is for Android only right now but here it is if you are interested:
 [react-native-intercepting-webview](https://www.npmjs.com/package/react-native-intercepting-webview)

**Comment by deflexable** [comment]
it will really be nice to have a feature like this, so we can intercept all requests made by the webview including inline links like script src and img src and the rest.

a prop like:

```js
onInterceptRequest: (request) => {

  return new Response(); // then we can return our own custom response
}
```

**Comment by vladrozhnev** [comment]
If anyone needs this functionality, I did that.
https://github.com/vladrozhnev/react-native-interception-webview
