### ISSUE TITLE
Library dependencies, Invariant Violation: requireNativeComponent: "RNCWebView" was not found in the UIManager

### ISSUE THREAD

**Issue by Onreg** [react-native-webview/react-native-webview#1549]
I have a custom library, which is based on [react-native-webview](https://github.com/react-native-community/react-native-webview). In my library `package.json` I have: 
`  "dependencies": {
    "prop-types": "^15.7.2",
    "react-native-webview": "10.3.2"
  }
`
When I install my library to a project I get error: "invariant Violation: requireNativeComponent: "RNCWebView" was not found in the UIManager".  Inside `node_modules` I can find `react-native-webview`. I can't run `npx react-native link react-native-webview` because `react-native-webview` must be in package.json. 

To clarify what I want to achieve: `some-project -> my-library -> react-native-webview`.

I can link it either manually as described: [android-link](https://github.com/react-native-community/react-native-webview/issues/1225#issuecomment-594083551) or installing `react-native-webview` directly to the project in both cases it works.

**Environment:**
 - OS:Android
 - OS version: Android R
 - react-native version: 0.62.2
 - react-native-webview version: 10.3.2

**Comment by smolster** [comment]
Also experiencing this issue, both on iOS and Android.

**Comment by hugoh59** [comment]
Me too, any fix? I'm using RN 0.63.2 and did a pod install but still does not work.

**Comment by wudihui** [comment]
me to

**Comment by wudihui** [comment]
my react native vesion is 0.59.8

**Comment by doumart** [comment]
Same for me but not on Xcode. If i user react-native run-ios i get the error

    "react-native": "0.61.5",
    "react": "16.9.0",
    "react-native-webview": "10.10.2",

**Comment by lsc949982212** [comment]
run react-native link react-native-webview
reload project
