### ISSUE TITLE
Relative links in href are empty when loading a local HTML file on Android

### ISSUE THREAD

**Issue by DominikHinc** [react-native-webview/react-native-webview#1550]
I am downloading a .html file using react-native-fs and then reading it using the same library, then I set the read HTML string as a `source={html: readfile}`. The pages render fine on both platforms, but with one exception. The relative links ("/page/subpage") are not working, which is expected since for a local file the root URL is always "file://". I tried fixing it by injecting a JS script onLoad (the script looks for `<a/>` tags and if the first letter of its href is "/" it adds "www.somesite.com" at the beginning). This solution works perfect on IOS, but not on android. For some reason on android all hrefs with relative links are empty.  (hrefs with absolute links are working fine).
Ps. When I console.log the .html file, all of the hrefs are there, so it is not a problem with downloading nor reading the file.

**To Reproduce:**
-> Download a page using react-native-fs (or any other library, I don't think it matters)
-> Read the file 
-> Set the read file as a `source={html: myfile}` in webview
-> The relative URLs are gone on Android, while still being present on IOS

**Expected behavior:**
->The URLs should behave the same on both platforms

**Environment:**
 - OS: Android
 - OS version: 28
 - react-native version: 0.62
 - react-native-webview version: 10.3.3

**Comment by DominikHinc** [comment]
I found a solution. Instead of reading the file and then passing it as a `source={{html: myFileAsString}}` i just pass the path to the file: `source={{uri: "file://" + myPathToFile}}`. Thanks to that modification i was able to solve my issue.

**Comment by mofengfs** [comment]
> I found a solution. Instead of reading the file and then passing it as a `source={{html: myFileAsString}}` i just pass the path to the file: `source={{uri: "file://" + myPathToFile}}`. Thanks to that modification i was able to solve my issue.

I tried this method, but failed：https://github.com/react-native-webview/react-native-webview/issues/1560#issuecomment-765145276
