### ISSUE TITLE
[Android] Redirect 302 with url that contains hash not reload webview

### ISSUE THREAD

**Issue by Aure77** [react-native-webview/react-native-webview#1556]
**Bug description:**
For some reason, Android webkit webview doesn't load url if it contains hash (#) after a 302 redirect.

On native side, RNCWebViewClient enter in `shouldOverrideUrlLoading` that trigger a onShouldStartLoadWithRequestEvent, it also trigger a command that call `webView.loadUrl(urlWithHashInside)`. But this call seems to do nothing when a hash is present.

On iOS, 302 redirect are correctly handled.

**To Reproduce:**
Start an example server:
```javascript
const http = require("http");

const hostname = "127.0.0.1";
const port = 3000;

let body = "";

const server = http.createServer((req, res) => {
  const html = `
<html>
  <head>
    <title>Test</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>
    <body>
        <h1>Hey body : ${body}<h1>
        <form method="post" action="http://localhost:3000/#test">Name: 
            <input type="text" name="name" />
            <input type="submit" value="Submit" />
        </form>
    </body>
</html>`;

  if (req.method === "POST") {
    console.log("POST", req.url);
    body = "";
    req.on("data", function(data) {
      body += data;
    });
    req.on("end", function() {
      console.log(`Body: ${body}`);
      res.writeHead(302, {
        Location: "http://localhost:3000/#test"
      });
      res.end();
    });
  } else {
    console.log("GET", req.url);
    res.writeHead(200, { "Content-Type": "text/html" });
    res.end(html);
  }
});

server.listen(port, hostname, () => {
  console.log(`Server running at http://${hostname}:${port}/`);
});
```
This server expose a form. On form submit, it will perform a POST request, server side, it's save form data and redirect (302) to an url with a hash: /**#test**

To make this server accessible on your device in localhost, run:
`adb reverse tcp:3000 tcp:3000`

then start a Webview with this uri: http://localhost:3000/#test
Ex App.js :
```javascript
import * as React from 'react';
import { View, StyleSheet } from 'react-native';
import { WebView } from 'react-native-webview';

export default () => (
    <View style={styles.container}>
      <WebView
          style={styles.webview}
          source={{ uri: 'http://localhost:3000/#test' }}
          />
    </View>
);

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    padding: 8
  },
  webview: {
    flex: 1
  }
});
```

**Expected behavior:**
After submit/post data & redirect to same url, webview should be reloaded and data should appear in the body.

**Screenshots/Videos:**
After click on "Submit" button. onNavigationStateChange & onShouldStartLoadWithRequest are logged in Yellow Box.
![image](https://user-images.githubusercontent.com/1374354/89518404-26fac600-d7db-11ea-8f44-2539395cecf2.png)

**Environment:**
 - OS: Android
 - OS version: 10
 - react-native version: 0.63.3
 - react-native-webview version: 10.10.0

**Comment by Aure77** [comment]
Still searching for solutions

**Comment by nitinarv** [comment]
Hi @Aure77 , 
I have been experiencing the exact same issue, Any luck with a solution for this?

**Comment by Aure77** [comment]
No and the bot close this issue, so I think nobody take a look at this issue... 
@Titozzz, @jamonholmgren, @andreipfeiffer, @Salakar : how can I re-open this issue ? I am not alone !

**Comment by andreipfeiffer** [comment]
@Aure77 take a look at the [Versioning](https://github.com/react-native-webview/react-native-webview#versioning) Readme section:

`8.0.0 - onNavigationStateChange now triggers with hash url changes`

I see you are using `react-native-webview: 6.11.1`. The latest version is `10.10.2`.

**Comment by Aure77** [comment]
@andreipfeiffer I just retest it with 10.10.0, same problem. 8.0.0 have fix _onNavigationStateChange_ for iOS only. But here a _onShouldStartLoadWithRequest_ should be triggered (to load the redirect) on Android.

**Comment by andreipfeiffer** [comment]
@Aure77 you're right, got it.
@Titozzz this issue should be left open.

**Comment by Daha62** [comment]
same issue

**Comment by cokealmonacid** [comment]
Any solution on this?

**Comment by shameeryou** [comment]
I'm facing the same issue with android. Was taking some parameters from the URL using the hashtag. It works perfectly in iOS, but not in Android.

Android returns about:blank URL or about:blank#blocked URL.
This is what my code looks like:

<a href='#&taxId=545&title=CategoryName&isTag=false' class='post-cat'>CategoryName</a>`

based on id in navigating the drawer to a different part of the application.
