### ISSUE TITLE
[Android] WebView Worker Cannot Access Local File via Fetch

### ISSUE THREAD

**Issue by nickfujita** [react-native-webview/react-native-webview#1560]
**Bug description:**
When attempting to use WebAssembly from a Worker inside of the WebView on Android, the following error is presented in the Chome debugger:

```
Fetch API cannot load file:///android_asset/my_wasm_file.wasm. URL scheme "file" is not supported.
```

**To Reproduce:**
When using the WebView component, the following properties are being set:
```
<WebView
    originWhitelist={['*']}
    source={{ uri: 'file:///android_asset/my_website.html' }}
    allowFileAccessFromFileURLs
    allowUniversalAccessFromFileURLs
    allowFileAccess
/>
```

This properly loads the html file from Android local storage via the "file" scheme.

Within this local html file, I am also dynamically loading a local JS file, which also loads successfully.

```
var script = document.createElement('script');
script.src = 'file:///android_asset/my_script.js';
document.head.appendChild(script);
```

In the locally loaded JS file, a Worker is started, referencing a separate local js file:

```
var myWorker = new Worker('file:///android_asset/my_worker_script.js');
```

This also loads successfully from local Android storage.

However, the error occurs when trying to utilize WebAssembly from a local wasm file:

```
WebAssembly.instantiateStreaming(fetch('file:///android_asset/my_wasm_file.wasm'), {})
  .then(
    () => console.log('success'),
    error => console.error('an error has occurred')
  });
```

My assumption was that by setting `allowUniversalAccessFromFileURLs` to `true`, any code running in the webview is allowed to access local storage using the `file` scheme (including in a Worker). However, based on my testing, this appears to not be the case.

**Expected behavior:**
The wasm file stored in Android local storage should be accessible via the `fetch` method from within a Worker that is running in the Webview when the `allowUniversalAccessFromFileURLs` property is set.

**Environment:**
 - OS: Android
 - OS version: 10
 - react-native version:0.62
 - react-native-webview version:10.4.0

**Comment by nickfujita** [comment]
Just wanted to check back to see if anyone else was able to reproduce this?

**Comment by mofengfs** [comment]
@nickfujita 

I want to know how `file:///android_asset/` came from? Which file path does it represent?

**Comment by nickfujita** [comment]
@mofengfs This path maps to the project asset directory. More information on it can be found in this thread, with links to the source code:
https://stackoverflow.com/a/18720439/3827155

**Comment by mofengfs** [comment]
@nickfujita 
But it gave me wrong information

![image](https://user-images.githubusercontent.com/16655229/105452120-b37d4000-5cb8-11eb-88e7-23a8a0fe0a0d.png)
![Uploading image.png…]()

**Comment by oferRounds** [comment]
@nickfujita have you found a solution? Facing a more-or-less similar issue

**Comment by stefan-grigore** [comment]
@nickfujita have you found a solution for this? I have the exact same issue.

**Comment by 5eeman** [comment]
@nickfujita @oferRounds @stefan-grigore I've got the solution.
I encountered the same problem while trying to create WebView in React Native that gonna use html and other files packed in assets.
First same as other devs I've tried to use `fetch`, but it gave me `TypeError: Failed to fetch`.
Solution that worked is using `XMLHttpRequest`.
Here is a function I'm using
`function getFileXHR(path) {
            return new Promise((resolve, reject) => {
                try {
                    let xhr = new XMLHttpRequest();
                    xhr.onreadystatechange = function () {
                        if (xhr.readyState === 4) {
                            if (xhr.status === 200) {
                                resolve(xhr.responseText);
                            } else {
                                resolve(null);
                            }
                        }
                    };
                    xhr.open("GET", path);
                    xhr.send();
                } catch (e) {
                    reject(e);
                }
            });
        }`

**Comment by trajano** [comment]
@5eeman so the `path` can be a file URL?  Is it the same path as Expo FileSystem.documentDirectory or FileSystem.cacheDirectory?

would it work with both iOS and Android?
