### ISSUE TITLE
Webview reloads when coming back on the main page?

### ISSUE THREAD

**Issue by ekalostz** [react-native-webview/react-native-webview#1561]
**Bug description:**
I have a main screen when I go forward to new history and coming back webview reload automatically.

**Environment:**
 - OS: Android
 - react-native version: 0.63.2
 - react-native-webview version: 10.3.0

**Comment by shariqahmed525** [comment]
@ekalostz Hey, Did you find any solution?

**Comment by vivianlys90** [comment]
Hi, Im having the same issue. And seem like the reload issue only happens in Android. iOS works perfectly.
