### ISSUE TITLE
WebView net::ERR_CACHE_MISS on Android 5.0

### ISSUE THREAD

**Issue by freedomzzzii** [react-native-webview/react-native-webview#1562]
###  Bug Report

WebView Android version 5.0 doesn't work (Android version 8-10 don't have any problem),
The problem occurs when I use WebView to create PWA (test on Standalone Apps) but the app stuck on splash-screen. This problem occurs in Android only (Not found in IOS)

Do you have any suggestions to fix this issue?

Error loading page
Domain: undefined
Error Code: -1
Desctiption: net::ERR_CACHE_MISS

Environment
Expo CLI: 3.21.10 
expo: 36.0.0
react: 16.9.0
react-dom: 16.9.0
react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz
react-native-web: 0.11.7

System device:
ASUS ZenFone 2
android version: 5.0

### Code
`<WebView
          style={styles.webView}
          ref={this.ref}
          onMessage={this.handleMessage}
          source={{ 'uri': URL  }}
          onLoadEnd={this.handleCookieWebView}
          injectedJavaScript={`
            window.postMessageForAndroid = data => window.ReactNativeWebView.postMessage(data);
            window.deviceToken = DEVICE_TOKEN;
          `}
 />`

**Comment by odeke** [comment]
Got the same issue. it maybe related to expo and android 5.0 and 5.1
Try a new android, or make an apk.
