### ISSUE TITLE
[Question] Audio controls for webview

### ISSUE THREAD

**Issue by xunto** [react-native-webview/react-native-webview#1563]
Hi! How do I make so audio tag controls were displayed in notification drawer on android? It works in browser (firefox) so there should be a way.

**Comment by xunto** [comment]
still searching for solutions

**Comment by keikhosrow** [comment]
Hi again, I have the same question, any solutions?

**Comment by alirezaj1997** [comment]
Hi everybody still searching for solutions

**Comment by Jojocaster** [comment]
Can we reopen this? iOS seems to work fine, but Android doesn't - it'd be great if we could enable controls on Android 😃

**Comment by indjeto** [comment]
I'm looking for solution also.

**Comment by namgaxilem** [comment]
Please support this on android, I having this problem
