### ISSUE TITLE
[Bug Android] - WebView inside ScrollView scroll in iOS but no in Android 

### ISSUE THREAD

**Issue by mrigo** [react-native-webview/react-native-webview#1568]
**Bug description:**
I've created a WebView inside a ScrollView.
I know is not a great UX choice for usability, but I need it to show privacy text that is veeeeery long with links.
In iOS, I can scroll the ScrollView AND the WebView, interacting with the links inside the WebView.
In Android, I can scroll ONLY the ScrollView, but I can still interact with the links inside the WebView.

**To Reproduce:**
- Install the library
- Create a WebView inside a ScrollView
- Run Android
- Try to scroll the WebView

**Expected behavior:**
I can scroll the content inside the WebView, like in iOS.

**Environment:**
 - OS: Android
 - OS version: every Android version
 - react-native version: 0.60.5
 - react-native-webview version: 10.4.0

**Comment by lukeramsden** [comment]
Getting this exact same issue, RN 0.62 and react-native-webview 10.7.0. Is there any workaround? I tried the auto-height webview method (https://gist.github.com/jkga/4ee1c366d46a3eba9045f88c58d3bc37) but that has some insane rendering issues on my device and I have no idea why.

**Comment by jsamr** [comment]
@lukeramsden Might want to try this: https://formidable-webview.github.io/webshell/docs/autoheight/

**Comment by aditya1711** [comment]
This issue still persist with latest web-view and pan-gesture-handler. Any solutions of workaround?

**Comment by krunalinfynno** [comment]
getting same issue
