### ISSUE TITLE
Media stops on Android background state

### ISSUE THREAD

**Issue by DANIELVISPOBLOG** [react-native-webview/react-native-webview#1570]
Video or audio automatically stops when activity goes to background. For example playing a video on YouTube or Vimeo

Load a Youtube Video on the webview and go to Home Screen. The video automatically stops.

It should be defined by a param like 'enableMediaOnBackground': true. If true then activate...
- Adding the following code on RNCWebViewManager.java fix the problem

@Override
protected void onWindowVisibilityChanged(int visibility) {
  if (visibility != View.GONE) super.onWindowVisibilityChanged(View.VISIBLE);
}

**Screenshots/Videos:**

**Environment:**
 - OS: Android
 - OS version: 10, LineageOS
 - react-native version: 0.63.2
 - react-native-webview version: 10.4.0

**Comment by flexgrip** [comment]
Can you tell me where I'd paste that, or what it should be changed to for the latest version? I keep getting errors when I try using it in the current version.

**Comment by rohitsingh2410** [comment]
@flexgrip did you found nay solution?
