### ISSUE TITLE
injectedJavaScriptBeforeContentLoaded do not work on some android device

### ISSUE THREAD

**Issue by KingAmo** [react-native-webview/react-native-webview#1571]
**Bug description:**
`injectedJavaScriptBeforeContentLoaded ` do not work on my Huawei device, EMUI 10.0.0

**To Reproduce:**

**Expected behavior:**

`injectedJavaScriptBeforeContentLoaded ` works as expected

**Screenshots/Videos:**

**Environment:**
 - OS: Android 
 - OS version: android 10
 - react-native version: 0.62.2
 - react-native-webview version: ^10.3.2

**Comment by KingAmo** [comment]
related issue https://github.com/react-native-community/react-native-webview/pull/1099

**Comment by rekmarks** [comment]
This issue is not stale, and persists in production as evidenced by e.g. https://github.com/MetaMask/metamask-mobile/issues/1975.

**Comment by Damoness** [comment]
HONOR 30 has the same problem .
