### ISSUE TITLE
Invariant Violation: Module  is not a registered callable module (calling onMessage)

### ISSUE THREAD

**Issue by ZaDarkSide** [react-native-webview/react-native-webview#1573]
**Bug description:**
Setting onMessage prop triggers error on Android:
`Invariant Violation: Module  is not a registered callable module (calling onMessage)`

**To Reproduce:**
Create a webview with onMessage prop on Android like this:
`<WebView source={{html: 'test'}} onMessage={e => { console.log(e)}}/>`

**Expected behavior:**
Should not trigger error, last known package version that not triggers the error is `react-native-webview` version `9.0.2`

**Screenshots/Videos:**
![image](https://user-images.githubusercontent.com/291278/90034184-faf2af80-dcc8-11ea-9a05-be88bc8f0883.png)

**Environment:**
 - OS: Windows 10
 - OS version: 1909
 - react-native version: 0.63.2
 - react-native-webview version: 10.4.0

**Comment by ChasePwn14** [comment]
This is still an issue.

**Comment by ccanalesdote** [comment]
Any update?

**Comment by jamonholmgren** [comment]
I just tested this in a new app and I'm not getting this error. 

<img src="https://user-images.githubusercontent.com/1479215/98422699-49ea7f80-2041-11eb-974b-aa435882728e.png" width="200" />

**Comment by ZaDarkSide** [comment]
It happens only with:

* react-native version: 0.63.2
* react-native-webview version: 10.4.0

**Comment by rutul089** [comment]
> * react-native

 My react-native version is 0.61.4 and react-native-webview version 10.3.2 still I am facing the same issue

**Comment by rutul089** [comment]
> It happens only with:
> 
> * react-native version: 0.63.2
> * react-native-webview version: 10.4.0

 My react-native version is 0.61.4 and react-native-webview version 10.3.2 still I am facing the same issue

**Comment by vadim312** [comment]
I am still got issue with latest RN version 0.63.4 and react-native-webview@11.2.3

**Comment by vgm8** [comment]
is there any update on this? I'm having the same problem using 0.63.4 and react-native-webview 11.2.3

**Comment by hkar19** [comment]
> I just tested this in a new app and I'm not getting this error.
> 
> <img alt="" width="200" src="https://user-images.githubusercontent.com/1479215/98422699-49ea7f80-2041-11eb-974b-aa435882728e.png">

can you please share how did you make that work?
