### ISSUE TITLE
Question: How to get HTTP Errors from react Webview in onLoad() callback?

### ISSUE THREAD

**Issue by divanshArora** [react-native-webview/react-native-webview#1579]
I know there was a fix in v7 to add callback onHttpErrors( ) for 5xx, 4xx and other server errors. But I am running on an older version and cannot upgrade unfortunately.

Is there any way to get the HTTP error code in the onLoad() callback?

**Comment by TheAlmightyBob** [comment]
There is not. That's why the callback was added. But you could try digging up the PRs that added `onHttpError` support and patch in just those changes to your version.
