### ISSUE TITLE
Statusbar get white text after fullscreen video cancelled in IOS dark mode.

### ISSUE THREAD

**Issue by yoojeen126** [react-native-webview/react-native-webview#1580]
**Bug description:**
Statusbar get white text after fullscreen video cancelled in IOS dark mode.
I try to set darkmode after fullscreen video cancelled action event in web call to app. but still white text.
Anyone with the same issue? 
**Environment:**
 - OS: IOS
 - OS version: 13.6
 - react-native version: 0.62.1
 - react-native-webview version: 10.7.0

**Comment by mattwoberts** [comment]
I have something similar.

In my app, on the simulator, no worries. On my device, in dark mode, using the webview is resulting in the statusbar always being light, despite me setting it.

E.g. - this screen will render a statusbar with white text:

```<SafeAreaView style={{flex:1, backgroundColor:'#fafbfb'}}>
      <StatusBar barStyle="dark-content"/>
      <WebView
        ref={webref}
        source={{ uri: url}}
        style={{ flex: 1 }}
        onNavigationStateChange={handleNavigate}
      />
    </SafeAreaView>```

Whereas if I replace that <Webview> with a `<Text>` component, the statusbar will work as expected, and be dark text.
