### ISSUE TITLE
Doesn't work on ios

### ISSUE THREAD

**Issue by TasksAndreySorokin** [react-native-webview/react-native-webview#1582]
Installing "react-native-webview": "^ 10.7.0"
    "react": "16.13.1",
    "react-native": "0.63.2",

I run the project an error comes out

`Macs-Air:testapp macuser$ npx react-native run-ios
info Found Xcode workspace "testapp.xcworkspace"
info Building (using "xcodebuild -workspace testapp.xcworkspace -configuration Debug -scheme testapp -destination id=B68C1DD3-B4BE-4852-AFE2-E8E348AEC713")
.........................................................................................................
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening testapp.xcworkspace. Run CLI with --verbose flag for more details.
note: Using new build system
note: Planning build
note: Constructing build description
Build system information
warning: The iOS Simulator deployment target is set to 5.0, but the range of supported deployment target versions for this platform is 8.0 to 12.4.99. (in target 'CocoaAsyncSocket')`

**Comment by TasksAndreySorokin** [comment]
plz HELP!

**Comment by chrisbobbe** [comment]
Hmm, that looks like a frustrating bug! What causes you to think there's something going wrong with `react-native-webview`? Also, did you run `yarn` / `npm install`, then run `pod install` from the folder where your Podfile is (maybe `ios/`)?

**Comment by designervoid** [comment]
same issue
bump

**Comment by deviro** [comment]
i have the same issue, hello from 2021

**Comment by chrisbobbe** [comment]
@designervoid @deviro, I think a good next step would be to find some evidence that this is related to a current bug in react-native-webview.

There may be clues to follow in the error output you're seeing, or the output pasted in the issue description, or in the report at https://github.com/react-native-webview/react-native-webview/issues/1582#issuecomment-678262710.

Without that evidence, I think this issue is unlikely to get any attention from maintainers of react-native-webview.

**Comment by xcsob** [comment]
Hello, 
I'm using "react-native": "0.64.3" and latest version of react-native-webview (11.15.0). 
What happens is that after I run: 
npm install react-native-webview
npm react-native link 

When I run npx react-native run-ios I get this error: 
_`error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening Project.xcworkspace.`_

Can you help me understand how to solve this? If you need more info, I'm glad to provide them.

**Comment by xcsob** [comment]
> Hello, I'm using "react-native": "0.64.3" and latest version of react-native-webview (11.15.0). What happens is that after I run: npm install react-native-webview npm react-native link
> 
> When I run npx react-native run-ios I get this error: _`error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening Project.xcworkspace.`_
> 
> Can you help me understand how to solve this? If you need more info, I'm glad to provide them.

I solved this issue by removing all the font from copy build in xcode. 
These are the steps: 

- go to xcode project
- select your targets
- build phase tab
- [CP] Copy pod resources
- delete all the output files having the .ttf extensions from the list
