### ISSUE TITLE
onNavigationStateChange triggered twice when url change

### ISSUE THREAD

**Issue by KingAmo** [react-native-webview/react-native-webview#1584]
**Bug description:**
when i an in `www.a.com` , and run `window.location.href='www.b.com'`  , `onNavigationStateChange` triggered twice, and the two callback has the same url: 'www.b.com'; and when i go back,  `onNavigationStateChange` also triggered twice, and the url  are all  `www.a.com`

**Expected behavior:**
`onNavigationStateChange`  trigger only once on every url change

**Screenshots/Videos:**

**Environment:**
 - OS: android/ios
 - OS version:
 - react-native version: 0.62.2
 - react-native-webview version: 10.3.2

**Comment by Nitro1231** [comment]
I have the same issue with you, and it seems like was there a long time ago and not fixed yet.
Check this out: https://github.com/facebook/react-native/issues/9201

**Comment by atalkrishna** [comment]
I'm facing the same problem. Any update on the above issue ?

**Comment by iamrohitagg** [comment]
@atalkrishna  were you able to find any solution?

**Comment by atalshrivastava** [comment]
@iamrohitagg I created a variable and assign initial value as 0. When this function called i iterate the value to 1 and then in if condition i checked if this variable value is greater then 0 then i will initiate my code and in the end again make that variable value 0. This way i solved my problem.

**Comment by iamrohitagg** [comment]
@atalshrivastava I've just checked, the object from `onNavigationStateChange` gives a property `loading` and I am calling the required function when loading is `false`.

**Comment by atalshrivastava** [comment]
@iamrohitagg I assume if you are using inbuilt parameter, Remember this function is calling twice when second time this function invokes again loading will be true. That's why i created a variable in component not inside that function.
Assume you have a component named RenderWebView 


`const RenderWebView = () => {
let count = 1

const navigationChange = () => {

if(count > 0) {
count = 0
// your code here
}

}
}
export default RenderWebView`


Here if this function call twice your `count` value will set to 0 for second time and it will not satisfy your condition.

So your code in the if block will not run second time.

Hope this helps you.

**Comment by r-arvind** [comment]
@iamrohitagg's method of using the `loading` variable seems to work for me too

**Comment by Y-k-Y** [comment]
Struggled a lot of days. Using `loading` variable works for me as well It should be added at document

**Comment by bgb10** [comment]
Using `loading` variable works for me! thanks!!!

**Comment by kesavanmaharajan** [comment]
I'm trying to capture the URL and from that I'm calling an REST API, even when using `loading` `onNavigationStateChange` is still being called twice and so the API call. So switched to `onLoadEnd` works fine with `loading` false check but I'm not 100% sure that it'll not trigger twice.

**Comment by MelihaDuman** [comment]
loading worked thanks a lot. This is how I used 
handleWebViewNavigationStateChange = newNavState => {
   const  {loading, url} = newNavState
    if (loading === false) {
           //your code 
}
}

**Comment by mominur-helios** [comment]
After using `loading` still the return url triggered twice

**Comment by VJ-GURU** [comment]
https://github.com/react-native-webview/react-native-webview/issues/1584#issuecomment-880511539
didn't work for me
because both the time I'm getting loading as false
