### ISSUE TITLE
Youtube video play stack on the Youtube web site

### ISSUE THREAD

**Issue by ktomi42** [react-native-webview/react-native-webview#1586]
**Bug description:**
Play Youtube on Youtube web site makes vide stack. This happens only on Andoird real device, for iOS seems fine. 
I thought it could be something with my project, then I started a bare project only with react-native-webview module where I put simple structure to load the web view. While the video seems stack, video image seems like it has an interference.
I have tried to run the app on the following devices: 
- HUAWEI P smart Z (Andoird 9)
- Samsung SM-G965F (Android 10)

`<View
      style={{
        flex: 1,
      }}>
      <WebView
        source={{uri: 'https://youtube.com'}}
        style={{
          flex: 1,
        }}
      />
    </View>`

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS: macOS Catalina
 - OS version: 10.15.6 
 - react-native version: "0.63.2"
 - react-native-webview version: "10.7.0"

**Comment by ddguru777** [comment]
hi @ktomi42,
I also have this issue in my project. Have you already figured this out? Thanks! Steven

**Comment by ddguru777** [comment]
gotcha,
do you think this "setAppCacheMaxSize" can help figure out the issue?

**Comment by brunof17** [comment]
I also have this issue in our project.
But I found out that this is a general problem with many apps that use webviews in android. This would happen on facebook messeger, whatsapp, and, not sure, also on firefox/chrome browser.

At our company we also had a previous version of our app that used the native webview, and the problem also happened there.

So i guess the problem is with android itself?

**Comment by ktomi42** [comment]
> gotcha,
> do you think this "setAppCacheMaxSize" can help figure out the issue?

i do see that settgin in [react-native-community/react-native-webview](https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md)
Or you meant somewhere else?

**Comment by ddguru777** [comment]
yeh, that's why i asked :)
This is the android setting and not available in this library.

**Comment by ktomi42** [comment]
> yeh, that's why i asked :)
> This is the android setting and not available in this library.

I am not sure, if setAppCacheMaxSize setting could solve the issue as I am not good with Java.

**Comment by ktomi42** [comment]
> I also have this issue in our project.
> But I found out that this is a general problem with many apps that use webviews in android. This would happen on facebook messeger, whatsapp, and, not sure, also on firefox/chrome browser.
> 
> At our company we also had a previous version of our app that used the native webview, and the problem also happened there.
> 
> So i guess the problem is with android itself?

How frequently you have this issue? My app behaves on random, 3 times work, then 4th video get messed up :(

**Comment by brunof17** [comment]
> How frequently you have this issue? My app behaves on random, 3 times work, then 4th video get messed up :(
> I never have a problem with YouTube in the Chrome browser on an Android phone


Mostly like you... Sometimes it works, sometimes it does not
If you ever happen to get the bug, please check the youtube on the browser and see if it also happens.
That is a behaviour that I always get. I also have a friend with the same cellphone, and she said that the problem happens with "normal" apps as well.

**Comment by ktomi42** [comment]
Thank you for the info 👍 , at least now I know I am not crazy :)
A month ago I have asked [the same question on Stackowerflow](https://stackoverflow.com/questions/63545994/playing-youtube-in-react-native-webview-makes-video-stack-or-video-has-interfere) and I did not get any response.
