### ISSUE TITLE
[Question] How to enable mobile browsers' 'swipe to navigate' features within WebView components?

### ISSUE THREAD

**Issue by jko12130** [react-native-webview/react-native-webview#1587]
<Situation>
-I have a web app built by using ReactJS and React-Router-DOM, and am planning to transform it into RN-based app.
-Before actually starting the work, I quickly developed an actual app by using a simple single WebView component--so that it looks and feels like a RN app but what is working behind the scenes is ReactJS and mobile browser.
-However, it seems that 'swipe to navigate' features supported by mobile browsers--i.e. swipe left to go back and right to go forward--don't work in the WebView component. Since my web app involves lots of transitions between screens, this is an issue.

<Question/Feature Request>
-Is there a built-in way to enable 'swipe to navigate' features provided by mobile browsers within a WebView component?
-If so, could you point me where to look at? If not, is there any plan to enable them? 

Thanks!

**Comment by coolswood** [comment]
Still relevant
