### ISSUE TITLE
react-native-webview postMessage sometimes not work.

### ISSUE THREAD

**Issue by fanzhibing** [react-native-webview/react-native-webview#1593]
import React, { Component } from 'react';
import { View } from 'react-native';
import { WebView } from 'react-native-webview';

export default class App extends Component {
  render() {
    const html = `
      <html>
      <head></head>
      <body>
        <script>
          setTimeout(function () {
            window.ReactNativeWebView.postMessage("Hello!")
          }, 2000)
        </script>
      </body>
      </html>
    `;

    return (
      <View style={{ flex: 1 }}>
        <WebView
          source={{ html }}
          onMessage={(event) => {
            alert(event.nativeEvent.data);
          }}
        />
      </View>
    );
  }
}

**Environment:**
 - OS: Windows10
 - OS version: xiaomi Android6.0
 - react-native version: 0.63.0
 - react-native-webview version: 10.8.0

**Comment by tero-paananen** [comment]
If you have multiple WebViews in Windows is onMessage sended to last created, see issue https://github.com/react-native-community/react-native-webview/issues/1572

**Comment by luojiong** [comment]
@tero-paananen   There is still this problem and the merger has not been successful

**Comment by tero-paananen** [comment]
> @tero-paananen There is still this problem and the merger has not been successful

You tested my PR in Windows enviroment? I currently use that PR code in Windows without any problems about messaging on react-native-windows 0.62.x. PR may not compile on 0.63.x. (I am not sure is my PR ever to be merged into master, there is so many PRs waiting)

**Comment by tero-paananen** [comment]
My PR is for Windows React Native app not for Android

**Comment by luojiong** [comment]
@tero-paananen  Well, I use it on Android and iOS. Thanks for your answers

**Comment by tero-paananen** [comment]
I will need working post messaging also later for iOS and Android. At least iOS have some kind of messaging implementation done but i have not tested it. I have to test it also soon...so sad if it does not work

**Comment by luojiong** [comment]
Ok, waiting for your good news

**Comment by juhasuni** [comment]
@luojiong, tested on iOS simulator using RN 0.62.2 and I don't see the issue you've described with postMessage API.

Here's the code I've been using:

```
import React from 'react';
import { WebView } from 'react-native-webview';
import { View } from 'react-native';

export default () => {
  return (
    <View style={{ flex: 1 }}>
      <WebView
        source={{
          html:
            '<html> <head></head> <body> <script> setTimeout(function () { window.ReactNativeWebView.postMessage("Hello!") }, 2000) </script> </body> </html>',
        }}
        onMessage={event => {
          console.log(event.nativeEvent.data);
        }}
      />
    </View>
  );
};
```

It is good to notice, that this is not valid HTML and might even activate some weird quirks mode (if such even exists in WKWebView), because the markup is missing doctype declaration. Also, I'm not sure there's a guarantee that the `window.ReactNativeWebView.postMessage` API is available before the document has been fully loaded. I'd wait for the document to load before calling the API, or follow the react-native-webview documentation if it says anything about this.

**Comment by juhasuni** [comment]
@luojiong, perhaps the problem is, that you're using `alert()` function, which is not available in React Native.

**Comment by luojiong** [comment]
Hi my problem is that I have used multiple web views in "ios" or "android". When loading two web views, I can use postMessage correctly, but only the first web view is triggered 
@juhasuni

**Comment by juhasuni** [comment]
Well, this seems to work also:
```
export default () => {
  return (
    <View style={{ flex: 1 }}>
      <WebView
        style={{ flex: 1, backgroundColor: 'green' }}
        source={{
          html:
            '<html> <head></head> <body> <script> setTimeout(function () { window.ReactNativeWebView.postMessage("Hello 1!") }, 2000) </script> </body> </html>',
        }}
        onMessage={event => {
          console.log(event.nativeEvent.data);
        }}
      />
      <WebView
        style={{ flex: 1, backgroundColor: 'red' }}
        source={{
          html:
            '<html> <head></head> <body> <script> setTimeout(function () { window.ReactNativeWebView.postMessage("Hello 2!") }, 2000) </script> </body> </html>',
        }}
        onMessage={event => {
          console.log(event.nativeEvent.data);
        }}
      />
    </View>
  );
};
```

My log says:
```
[Thu Sep 17 2020 11:00:13.515]  LOG      Hello 1!
[Thu Sep 17 2020 11:00:13.516]  LOG      Hello 2!
```

**Comment by luojiong** [comment]
I use setTimeout to delay the triggering of the second webview postMessage after loading the first webview. The problem is solved but I don’t think this is a good idea. I put the html file in the static resource directory, not directly source={{html:''}}

**Comment by juhasuni** [comment]
Okay, but it seems to work also without setTimeout:

```
export default () => {
  return (
    <View style={{ flex: 1 }}>
      <WebView
        style={{ flex: 1, backgroundColor: 'green' }}
        source={{
          html:
            '<html> <head></head> <body> <script> window.ReactNativeWebView.postMessage("Hello 1!") </script> </body> </html>',
        }}
        onMessage={event => {
          console.log('Web view 1:' + event.nativeEvent.data);
        }}
      />
      <WebView
        style={{ flex: 1, backgroundColor: 'red' }}
        source={{
          html:
            '<html> <head></head> <body> <script> window.ReactNativeWebView.postMessage("Hello 2!") </script> </body> </html>',
        }}
        onMessage={event => {
          console.log('Web view 2:' + event.nativeEvent.data);
        }}
      />
    </View>
  );
};
```

Now, the order in which the messages appear, varies.

Run #1
```
[Thu Sep 17 2020 11:21:10.720]  LOG      Web view 2:Hello 2!
[Thu Sep 17 2020 11:21:10.723]  LOG      Web view 1:Hello 1!
```

Run #2
```
[Thu Sep 17 2020 11:21:18.925]  LOG      Web view 1:Hello 1!
[Thu Sep 17 2020 11:21:18.936]  LOG      Web view 2:Hello 2!
```

This is of course not a bug.

**Comment by luojiong** [comment]
Sorry, maybe I didn't describe my problem clearly. My problem is that I use react-native to pass information to html instead of htlm to pass to react-native @juhasuni

**Comment by tero-paananen** [comment]
> Sorry, maybe I didn't describe my problem clearly. My problem is that I use react-native to pass information to html instead of htlm to pass to react-native @juhasuni

It is then different bug, not that kind of. You could close this and try to create new issue.

**Comment by luojiong** [comment]
Okay thank you
