### ISSUE TITLE
WebView not working at all with expo. GIves an ERR_CACHE_MISS error.

### ISSUE THREAD

**Issue by pratikluitel** [react-native-webview/react-native-webview#1596]
**Bug description:**
WebView not working at all with expo. GIves a ERR_CACHE_MISS error.

<WebVIew> doesn't render the source uri at all. It seems to be working with html though.
The error on console:
```
Encountered an error loading page, 
Object {
  "canGoBack": false,
  "canGoForward": false,
  "code": -1,
  "description": "net::ERR_CACHE_MISS",
  "loading": false,
  "target": 5005,
  "title": "",
  "url": "https://www.google.com/",
}
```
**To Reproduce:**

repo: https://github.com/pratikluitel/texdit
The file `/components/WebVIewComponent.js` causes the error. The bug happens if I use uri inside the Webview

**Expected behavior:**

The webview should render instead of giving an error message.

**Environment:**
 - OS: linux ubuntu
 - OS version: 19.10
 - react-native version: 0.62.2
 - react-native-webview version: 9.4.0

**Comment by 026binit** [comment]
looking for solutions

expo sdk :- 39
plaform :- Android 5.1.1

**Comment by NameNull** [comment]
the same 
expo sdk: ~39.0.2
react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz
react-native-webview: 10.7.0
android: 5

**Comment by NameNull** [comment]
> looking for solutions
> 
> expo sdk :- 39
> plaform :- Android 5.1.1

any solutions?

**Comment by NameNull** [comment]
if anyone has solutions, plz contact me at wechat: yjavacn
