### ISSUE TITLE
On webview: Webcamera shows black screen after giving PERMISSIONS.ANDROID.CAMERA and file permissions

### ISSUE THREAD

**Issue by vasanthhr** [react-native-webview/react-native-webview#1599]
Hello,

I gave camera permission and also media files permissions on componentDidMount, but webcamera displays black-screen at begining.
And our website has switch-camera option, so when I click on switch camera then it opens back-camera with proper streaming and again I click on switch camera then it lands on front-camera and streaming properly.

**So issues is happening when app is clicked and open and display black-screen, and it works when we do switch camera.**
(FYI: This issue is happening for other webcamera website links as well, I suspect something bug in react-native webview).

I used below code to give camera and file permissions:

`
componentDidMount(){
   request(PERMISSIONS.ANDROID.CAMERA).then((result) => {
        console.log('CAMERA', result);
        request(PERMISSIONS.ANDROID.WRITE_EXTERNAL_STORAGE).then((result) => {
          console.log('WRITE_EXTERNAL_STORAGE', result);
          request(PERMISSIONS.ANDROID.READ_EXTERNAL_STORAGE).then((result) => {
            console.log('READ_EXTERNAL_STORAGE', result);
          });
        });
      });
}
`

**Comment by ansalmishra10** [comment]
issue still remains, please help us out!
