### ISSUE TITLE
Content is getting selected when swipe a drawer on Android

### ISSUE THREAD

**Issue by AntiXYZ** [react-native-webview/react-native-webview#1601]
**Bug description:**
Text in the webview become selected on android devices when i try to swipe a menu drawer

**To Reproduce:**
[https://github.com/AntiXYZ/selection-issue](https://github.com/AntiXYZ/selection-issue)

**Screenshots/Videos:**
[bandicam 2020-08-28 11-29-02-811.zip](https://github.com/react-native-community/react-native-webview/files/5142896/bandicam.2020-08-28.11-29-02-811.zip)

**Environment:**
 - OS: -
 - OS version: - 
 - react-native version: expo sdk 38
 - react-native-webview version: 9.4.0

**Comment by weishengkui** [comment]
So, have you solve it right now ?

**Comment by AntiXYZ** [comment]
> So, have you solve it right now ?

I am doing js injection after opening a drawer
```
const runClearSelection = () => {
  if (Platform.OS !== "android") {
    return;
  }
  const removeSelection = `
      var sel = window.getSelection ? window.getSelection() : document.selection;
      if (sel) {
          if (sel.removeAllRanges) {
              sel.removeAllRanges();
          } else if (sel.empty) {
              sel.empty();
          }
      }`;

    window.current.injectJavaScript(removeSelection);
};
```

**Comment by weishengkui** [comment]
> 

seems like it is not the best solution. because the Injection Function act too slow.
