### ISSUE TITLE
In  android The correct height cannot be obtained after setting the font

### ISSUE THREAD

**Issue by k1195453766** [react-native-webview/react-native-webview#1602]
环境：webview:6.3.1 ; rn: 0.59.5
在android中设置字体后无法获取内容的具体高度
my code：
let fontFamily = 'SourceHanSerifCN-Medium-6';
let fileFormat = 'ttf';
const fileName = Platform.select({
    ios: `${fontFamily}.${fileFormat}`,
    android: `file:///android_asset/fonts/SourceHanSerifCN-Medium-6.ttf`
})

<WebView
       originWhitelist={['*']}
       useWebKit={true}
       source={{
            html: `
               <html>
               <head>
               <meta name="viewport" content=width=device-width, initial-scale=0.5, maximum-scale=0.5, minimum-scale=0.5, user-scalable=no">
               <style media="screen" type="text/css">
                      @font-face {
                             font-family: ${fontFamily};
                             src: url('${fileName}') format('${fileFormat === 'ttf' ? 'truetype' : 'opentype'}');
                      };
               </style>
               </head>
               <body style="height:'100%';">
                         ${this.state.details.content}
                </body>
                 </html>
                  `
                  , baseUrl: ''
         }}
         injectedJavaScript={BaseScript}
         onMessage={this.onMessage}
         scrollEnabled={false}
         javaScriptEnabled={true}
         domStorageEnabled
        style={{ width: '100%', height: this.state.height }}
>
</WebView>

const BaseScript =
    `
    (function () {
        var height = null;
      if (document.body.scrollHeight != height) {
        for(var i=0; i<document.getElementsByTagName('p').length;i++){
            if(document.getElementsByTagName('p')[i].className=='user'){
                document.getElementsByTagName('p')[i].style.fontSize="14px";
                document.getElementsByTagName('p')[i].style.lineHeight="20px";
                document.getElementsByTagName('p')[i].style.color="#999"
                document.getElementsByTagName('p')[i].style.fontFamily="MicrosoftYaHei"
            }else{
                document.getElementsByTagName('p')[i].style.fontSize="18px"; 
                document.getElementsByTagName('p')[i].style.lineHeight="30px";
                document.getElementsByTagName('p')[i].style.color="#333333"
                document.getElementsByTagName('p')[i].style.fontFamily="SourceHanSerifCN-Medium-6"
            }
        }

        function changeHeight() {
            height = document.body.scrollHeight;
            if (window.ReactNativeWebView) {
                window.ReactNativeWebView.postMessage(JSON.stringify({
                type: 'setHeight',
                height: height,
              }))
            }
          }
        }
        setTimeout(changeHeight, 300);
    } ())
    true;
    `
效果图：
![image](https://user-images.githubusercontent.com/45040711/91674483-74185080-eb6b-11ea-8b02-a618c1880ded.png)

help!!help!!help!!
thanks!!!

**Comment by k1195453766** [comment]
[效果图链接](http://sidama.sidama.work/demos.png)

**Comment by jsamr** [comment]
@k1195453766 Might want to try this: https://formidable-webview.github.io/webshell/docs/autoheight/

**Comment by k1195453766** [comment]
Thank you. I solved it in other ways！[查看我的解决方式](https://blog.csdn.net/qq_41457238/article/details/108366042)
