### ISSUE TITLE
WebView JavascriptInterface with React-Native

### ISSUE THREAD

**Issue by Abdallah4021** [react-native-webview/react-native-webview#1607]
This is a quistion: 

How to user JavascriptInterface with React-Native webview ? 
in my react native webview, I'm calling  `injectJavaScript` function to executes the JavaScript. 
im sending a variable and everuthinf is working really well,  but i have problem in sending fuction, 

example: 

This script is working well : 
```
      window.MYWEBSITE.init({
            id:"5f040d7cdbd59b001804c401",
      })
      true; 
```

but this now working : 

```
      window.MYWEBSITE.init({
            id:"5f040d7cdbd59b001804c401",
            goToAuth: function (event) {
                  console.log("event")
            }
      })
      true; 
```

any help to pass a function to the backend correctly? 

PS: this is worked with me really well in Android [native] Webview, using

```
     webView.addJavascriptInterface(
            JavaScriptInterface(), JAVASCRIPT_OBJ
        )
```

and using this annotation 

        @JavascriptInterface

**Comment by shukerullah** [comment]
@Abdallah4021 Did you solve this issue?
