### ISSUE TITLE
Code from the injectedJavaScriptBeforeContentLoaded prop runs AFTER the web code.

### ISSUE THREAD

**Issue by Kreozot** [react-native-webview/react-native-webview#1609]
**Bug description:**

According to official docs of `react-native-webview` (The injectedJavaScriptBeforeContentLoaded prop):

> This is a script that runs before the web page loads for the first time. It only runs once, even if the page is reloaded or navigated away. This is useful if you want to inject anything into the window, localstorage, or document prior to the web code executing.

But we can see that the script on the page runs first, and only then runs the code from the `injectedJavaScriptBeforeContentLoaded` prop.

The setup is:

* index.html with test.js script: https://github.com/Kreozot/webview-scripts-test/tree/master/android/app/src/main/assets
  The script has alert _"script executed"_

* WebView with the injectedJavaScriptBeforeContentLoaded prop: https://github.com/Kreozot/webview-scripts-test/blob/master/App.js
  The prop has alert _"injectedJavaScriptBeforeContentLoaded"_

**To Reproduce:**

1. `git clone git@github.com:Kreozot/webview-scripts-test.git`
1. `cd webview-scripts-test`
1. `yarn`
1. `yarn run android`

**Expected behavior:**

Alert "injectedJavaScriptBeforeContentLoaded" shows **before** "script executed".

**Screenshots/Videos:**

Alert "injectedJavaScriptBeforeContentLoaded" shows **after** "script executed".

**Environment:**
 - OS: Android
 - OS version: 9
 - react-native version: 0.63.2
 - react-native-webview version: 10.8.3

**Comment by Kreozot** [comment]
I have tested it on 10.3.0 version of react-native-webview and it behave as expected. So, maybe it's a new bug.

**Comment by Kreozot** [comment]
UPD: sometimes it works as expected, but like 50/50.

**Comment by renwenci** [comment]
i have the same issue on IOS 13.6.1, anyone has ideas?

**Comment by roscorcoran** [comment]
Same or similar issues here, however on Android the Javascript injected via _injectedJavaScriptBeforeContentLoaded_ never runs, even when Javascript injected via _injectedJavaScript_ does run.

**Comment by Kreozot** [comment]
Dear bot, please don't close this issue because it still an issue.

**Comment by ArthurSampaio** [comment]
Hi @Kreozot, did you find an away or workaround to solve this?

**Comment by Kreozot** [comment]
> Hi @Kreozot, did you find an away or workaround to solve this?

I've avoided injecting. Instead I just put some async scripts loading in my HTML template:

```html
...
      <body>
        <script>
          // Function that runs some script and then calling the callback
          function evalScript(filename, callback) {
            var head=document.getElementsByTagName("head")[0];
            var script=document.createElement('script');
            script.src=filename;
            script.type='text/javascript';
            script.onload=callback;
            head.appendChild(script);
          }

          evalScript("file:///android_asset/firstScript.js", function () { // will be executed before the second
            evalScript("file:///android_asset/secondScript.js"); // will be executed after the first
          });
        </script>
      </body>
```

Yes, this looks very dirty - I'm not proud of it - but it works :)

**Comment by Bardiamist** [comment]
I faced with it.
I created repro https://github.com/Bardiamist/injectedjs and I see issue already exist here.

**Comment by allan-simon** [comment]
I confirm it still exist (with the same device it sometimes execute before all script, sometime after the script in <head> but before the script in <body> etc. sounds like there's a missing /lock or sync issue causing the injection execution to be based purely on luck in android )  , @Titozzz  @chiaramooney  can this issue be reopened ?

Also do you mind if I open a PR in the documentation to warn about this current issue waiting for it to solved?

**Comment by syntag** [comment]
Experiencing the same issue here on Android 9. `injectedJavaScriptBeforeContentLoaded ` works as intended on Android API >= 28, but not anything lower.

**Comment by EduardoNogueira** [comment]
I also can confirm that this is still an issue, it seems that the `injectedJavaScriptBeforeContentLoaded` prop isn't working properly for webviews with real hosted websites, more details [here](https://github.com/react-native-webview/react-native-webview/pull/1099#issuecomment-600360207). Does anyone know a workaround that doesn't require changing the website source code?

**Comment by allan-simon** [comment]
still searching for solution (a documentation warning could be enough )

**Comment by Bardiamist** [comment]
> still searching for solution (a documentation warning could be enough )

My workaround as old as the world

```
const wait = async (ms: number) => new Promise((resolve) => {
  setTimeout(resolve, ms);
});

const initOnReady = async () => {
  while (tradingViewWindow.injectedSettings == null) {
    // eslint-disable-next-line no-await-in-loop
    await wait(100);
  }
  ...
};
```

**Comment by hkar19** [comment]
if you are the same person (like me) running React native webview@9.4.0, and wondering why `injectedJavaScriptBeforeContentLoaded` did not run in android, please apply this diff below.

The idea is:
- the props passed to RNCWebview was not handled in android, so we handle it ourselves by copying the codes from master (currently `11.18.1`) and apply it where we needed it.
- we wanted this script to run `onPageStarted`

`react-native-webview+9.4.0.patch`
```diff
--- a/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
+++ b/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
@@ -396,6 +396,12 @@ public class RNCWebViewManager extends SimpleViewManager<WebView> {
     ((RNCWebView) view).setInjectedJavaScript(injectedJavaScript);
   }
 
+  @ReactProp(name = "injectedJavaScriptBeforeContentLoaded")
+  public void setInjectedJavaScriptBeforeContentLoaded(WebView view, @Nullable String injectedJavaScriptBeforeContentLoaded) {
+    ((RNCWebView) view).setInjectedJavaScriptBeforeContentLoaded(injectedJavaScriptBeforeContentLoaded);
+  }
+
+
   @ReactProp(name = "messagingEnabled")
   public void setMessagingEnabled(WebView view, boolean enabled) {
     ((RNCWebView) view).setMessagingEnabled(enabled);
@@ -747,6 +753,9 @@ public class RNCWebViewManager extends SimpleViewManager<WebView> {
       super.onPageStarted(webView, url, favicon);
       mLastLoadFailed = false;
 
+      RNCWebView reactWebView = (RNCWebView) webView;
+      reactWebView.callInjectedJavaScriptBeforeContentLoaded();
+
       dispatchEvent(
         webView,
         new TopLoadingStartEvent(
@@ -1000,6 +1009,8 @@ public class RNCWebViewManager extends SimpleViewManager<WebView> {
   protected static class RNCWebView extends WebView implements LifecycleEventListener {
     protected @Nullable
     String injectedJS;
+    protected @Nullable
+    String injectedJSBeforeContentLoaded;
     protected boolean messagingEnabled = false;
     protected @Nullable
     String messagingModuleName;
@@ -1081,10 +1092,15 @@ public class RNCWebViewManager extends SimpleViewManager<WebView> {
       injectedJS = js;
     }
 
+    public void setInjectedJavaScriptBeforeContentLoaded(@Nullable String js) {
+      injectedJSBeforeContentLoaded = js;
+    }
+
     protected RNCWebViewBridge createRNCWebViewBridge(RNCWebView webView) {
       return new RNCWebViewBridge(webView);
     }
 
+
     protected void createCatalystInstance() {
       ReactContext reactContext = (ReactContext) this.getContext();
 
@@ -1135,6 +1151,14 @@ public class RNCWebViewManager extends SimpleViewManager<WebView> {
       }
     }
 
+    public void callInjectedJavaScriptBeforeContentLoaded() {
+      if (getSettings().getJavaScriptEnabled() &&
+        injectedJSBeforeContentLoaded != null &&
+        !TextUtils.isEmpty(injectedJSBeforeContentLoaded)) {
+        evaluateJavascriptWithFallback("(function() {\n" + injectedJSBeforeContentLoaded + ";\n})();");
+      }
+    }
+
     public void onMessage(String message) {
       ReactContext reactContext = (ReactContext) this.getContext();
       RNCWebView mContext = this;

```

**Comment by TheAlmightyBob** [comment]
Reopening because:
1. The multiple folks chiming in on this issue here
2. The original PR (#1099) itself acknowledged that the solution didn't seem 100% reliable
3. While I haven't been able to repro any problems myself, I tossed an experiment in an app for others to try and there were indeed some failures.

That said, it's unclear to me if there's a possible "fix" here or if this is just an Android WebView limitation we need to warn folks about.

I did see this comment (https://github.com/react-native-webview/react-native-webview/pull/1099#issuecomment-611215560) suggesting an alternative approach, but that seems quite complex/hacky/risky for general use. Could be a useful workaround (via [custom Android component](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Custom-Android.md)) for folks who really need it though.

**Comment by TheAlmightyBob** [comment]
'sup bot. Still a thing.

**Comment by frags51** [comment]
We are observing that this sometimes does not work for iOS as well. Has it been observed by anyone else?

**Comment by TheAlmightyBob** [comment]
I've never seen nor heard of it failing on iOS

**Comment by Electornic** [comment]
It is still doesn't work sometimes..

**Comment by thenxkk** [comment]
Similar issues here, On Android the Javascript injected via injectedJavaScriptBeforeContentLoaded/injectedJavaScript partly never runs.
Some javascript code about window.localStorage.setItem("xxx","xxx") didn't work but other code like alert('xxx') work

Device: Samsung Galaxy A34 5G
OS: Android
OS version: android 9
react-native version: 0.71.13
react-native-webview version: 13.6.2

**Comment by thenxkk** [comment]
> Similar issues here, On Android the Javascript injected via injectedJavaScriptBeforeContentLoaded/injectedJavaScript partly never runs. Some javascript code about window.localStorage.setItem("xxx","xxx") didn't work but other code like alert('xxx') work
> 
> Device: Samsung Galaxy A34 5G OS: Android OS version: android 9 react-native version: 0.71.13 react-native-webview version: 13.6.2

OS version: android 13

**Comment by TheAlmightyBob** [comment]
Reopening for now, but I can't keep doing that forever, and it's worth noting that version `13.6.0` adds a new `injectJavaScriptObject` specifically for Android as another option for _some_ scenarios affected by this.

@thenxkk I'm not aware of any issues with the normal `injectedJavaScript` feature not running on Android. You should probably open a separate issue for that and investigate further.

**Comment by ivankdev** [comment]
@TheAlmightyBob what could you say about this issue https://github.com/react-native-webview/react-native-webview/issues/3377

**Comment by ReedVivid** [comment]
This is still an issue on 13.8.6. injectedJavaScriptBeforeContentLoaded only works 50% of the time on Android.

**Comment by Ishaan-flyfin** [comment]
this issue was happening to us only when launching the app for the first time in android

after spending lot of time on it we realised that in android `injectedJavaScript` gets called after web code gets executed and in ios `injectedJavaScript` was getting called before webcode was executed

before fix eg:

app code: this is what we were injecting in webview
```
 const injectedJSCodeOnMount = `
  window.localStorage.setItem('token', '${token}');
  window.localStorage.setItem('mweb', 'true');
  `;
```
web code: this is how we were reading it in web
```
 useEffect(() => {
    const token = localStorage.getItem('token');
    const mWeb = localStorage.getItem('mweb') === 'true';
    if (token && mWeb) {
      axios.defaults.headers.common.Authorization = `Token ${token}`;
      dispatch(saveToken(token));
    }
  }, []);
```

for android the token was coming as empty in web while reading and in iOS token was coming as expected

-------

Solution
- we dispatched an event as soon as `injectedJavaScript` get called
- we added a listener in web to handle the event sent from app

eg
App code: 
```
const sendEventToWeb = (event: WebEvent, data = '') =>
  `(function() {
    ${
      Platform.OS === 'ios' ? 'window' : 'document'
    }.dispatchEvent(new MessageEvent('${event}', {data: ${JSON.stringify(
    data,
  )}}));
  })()`;


  const injectedJSCodeOnMount = `
  window.localStorage.setItem('token', '${token}');
  window.localStorage.setItem('mweb', 'true');
  ${sendEventToWeb('SAVE_WEB_VIEW_DATA'};
  `;
```

Web code:
```
  const saveTokenFromWebView = useCallback(() => {
    const token = localStorage.getItem('token');
    const mWeb = localStorage.getItem('mweb') === 'true';

    if (token && mWeb) {
      axios.defaults.headers.common.Authorization = `Token ${token}`;
      dispatch(saveToken(token));
    }
  }, []);

  /**
   * this handles if JS code gets injected before web code runs
   * eg: in case of iOS
   */
  useEffect(() => {
    saveTokenFromWebView();
  }, [saveTokenFromWebView]);

  /**
   * this handles if JS code gets injected after web code runs
   * eg: in case of Android
   */
  useEffect(() => {
    document.addEventListener('SAVE_WEB_VIEW_DATA', saveTokenFromWebView);

    return () => {
      document.removeEventListener('SAVE_WEB_VIEW_DATA', saveTokenFromWebView);
    };
  }, [saveTokenFromWebView]);
```
the web code handles for Js getting injected before/after reading on web

contributors
- [@Sachin](https://github.com/sachin-pandey-flyfin)
- [@Ishaan](https://github.com/Ishaan-flyfin)

**Comment by Ishaan-flyfin** [comment]
this issue was happening to us only when launching the app for the first time in android

after spending lot of time on it we realised that in android `injectedJavaScript` gets called after web code gets executed and in ios `injectedJavaScript` was getting called before webcode was executed

before fix eg:

app code: this is what we were injecting in webview
```
 const injectedJSCodeOnMount = `
  window.localStorage.setItem('xyz', '${xyz}');
  window.localStorage.setItem('abc', 'true');
  `;
```
web code: this is how we were reading it in web
```
 useEffect(() => {
    const xyz = localStorage.getItem('xyz');
    const abc = localStorage.getItem('abc') === 'true';
    if (xyz && abc) {
     // use xyz and abc
    }
  }, []);
```

for android the xyz was coming as empty in web while reading and in iOS xyz was coming as expected

-------

Solution
- we dispatched an event as soon as `injectedJavaScript` get called
- we added a listener in web to handle the event sent from app

eg
App code: 
```
const sendEventToWeb = (event: WebEvent, data = '') =>
  `(function() {
    ${
      Platform.OS === 'ios' ? 'window' : 'document'
    }.dispatchEvent(new MessageEvent('${event}', {data: ${JSON.stringify(
    data,
  )}}));
  })()`;


  const injectedJSCodeOnMount = `
  window.localStorage.setItem('xyz', '${xyz}');
  window.localStorage.setItem('abc', 'true');
  ${sendEventToWeb('SAVE_WEB_VIEW_DATA'};
  `;
```

Web code:
```
  const saveDataFromWebView = useCallback(() => {
    const xyz = localStorage.getItem('xyz');
    const abc = localStorage.getItem('abc') === 'true';

    if (xyz && abc) {
      // use xyz and abc here
    }
  }, []);

  /**
   * this handles if JS code gets injected before web code runs
   * eg: in case of iOS
   */
  useEffect(() => {
    saveDataFromWebView();
  }, [saveDataFromWebView]);

  /**
   * this handles if JS code gets injected after web code runs
   * eg: in case of Android
   */
  useEffect(() => {
    document.addEventListener('SAVE_WEB_VIEW_DATA', saveDataFromWebView);

    return () => {
      document.removeEventListener('SAVE_WEB_VIEW_DATA', saveDataFromWebView);
    };
  }, [saveDataFromWebView]);
```
the web code handles for Js getting injected before/after reading on web

contributors
- [@Sachin](https://github.com/sachin-pandey-flyfin)
- [@Ishaan](https://github.com/Ishaan-flyfin)
