### ISSUE TITLE
Blank screen after opening a popup window

### ISSUE THREAD

**Issue by fats2005** [react-native-webview/react-native-webview#1614]
**Bug description:**

The Webview is failing to redirect after pressing a Pay button in a checkout process. The behavior of the button in a desktop browser is to open a popup window, that goes initially to an `about:blank` page and immediately redirects to the payments page. 

In the Webview, after pressing the button, the Webview goes to the `about:blank` in the same tab (I guess this is expected into the Webview) but it doesn't redirect to the payments page.

**To Reproduce:**
1. Open eBay Australia in the Webview

```js
<WebView
  source={{uri: 'https://www.ebay.com.au/'}}
  onNavigationStateChange={(syntheticEvent) => {
    console.log(syntheticEvent);
  }}
/>
```
2. Pick any product and make all the checkout process until the Payment method.
3. Pick `Afterpay` method and then press the button `Pay with Afterpay`.

**Expected behavior:**
After pressing the `Pay with Afterpay` button, the popup window should open the Afterpay page to proceed with the payment. I have noticed that this button works fine on other webpages.

**Screenshots/Videos:**
![webview issue-min (1)](https://user-images.githubusercontent.com/2784390/92204871-92b67880-eed8-11ea-9129-bc87e69b189d.gif)

**Environment:**
 - OS: iOS and Android
 - OS version: All versions
 - react-native version: 0.63.2
 - react-native-webview version: Tested on `9.4.0` and `10.8.3` and I got the same result

Also tested on a new project and got the same result 😢

**Comment by muthuspark** [comment]
@fats2005 were you able to find a resolution for this issue?

**Comment by fats2005** [comment]
@muthuspark No - I didn't. As workaround, I created a deny list to open this website using the external browser.

**Comment by ArturTimoxin** [comment]
@fats2005 Hi, how it is possible? Could you give an example, please?

**Comment by fats2005** [comment]
Hi @ArturTimoxin, we have a list of stores, any store has a URL prop, that is used to open the In-App browser, a `storeId` that we use as an identifier,  and some other data that comes from an endpoint, so when the user presses the store tile,  there is function who validate the id against a deny list to decide if the Store should be open in the In-App browser or in the external browser: Something like this:

```js
const isDeniedURL = (storeId) => {
  const denyListIds = ["1234"];
  return _.includes(denyListIds, storeId);
};

const openUrl = () => {
  const { url, id } = this.props
  if ( !isDeniedURL(id))) {
     navigation.navigate("InAppBrowser", { url });
   } 
   return Linking.openURL(trimmedUrl);
}

return (
 <TouchableOpacity onPress={openUrl}>
    ...
  </TouchableOpacity>
)
```

So, when the user presses the Store tile, the `openUrl` method evaluates first if the ID is part of the deny list to decide where to open the URL.

**Comment by aniketbiswas** [comment]
@ArturTimoxin , did you solve this I'm facing the same issue.

**Comment by LinhNguyen1059** [comment]
Hi, I also facing same issue, anyone fixed it?

**Comment by AyishmAzeem** [comment]
Hi, @ArturTimoxin
Did you find the solution to the problem?

**Comment by kueda** [comment]
Here's a weird workaround that helped me but I don't know why: set `onOpenWindow={() => true}`
