### ISSUE TITLE
Android - net::ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by slingercode** [react-native-webview/react-native-webview#1619]
**Bug description:**

When trying the example of usage Android returns an error `Encountered an error loading page {"canGoBack": false, "canGoForward": false, "code": -2, "description": "net::ERR_NAME_NOT_RESOLVED", "loading": false, "target": 855, "title": "Webpage not available", "url": "https://reactnative.dev/"}`
Searching on Google i saw something about `AppRegistry` if this screen its going to be my root page, but is not my case, and trying on iOS everything is working just fine

**To Reproduce:**

Try the example of usage in a functional component
```javascript
import React, {useRef, useState} from 'react';
import {SafeAreaView} from 'react-native';
// More imports

const HomeScreen = () => {
  // More stuff
  return (
    <SafeAreaView>
      <WebView source={{uri: 'https://reactnative.dev/'}} />
    </SafeAreaView>
  );
};
```

**Expected behavior:**

**Screenshots/Videos:**

_iOS (working)_
![Simulator Screen Shot - iPhone 11 - 2020-09-07 at 13 31 35](https://user-images.githubusercontent.com/12452210/92411698-92072780-f10e-11ea-8a1e-a868f0f18e90.png)

_Android (not working)_
![Screenshot_1599503315](https://user-images.githubusercontent.com/12452210/92411688-8451a200-f10e-11ea-961d-55ed0cf58fdd.png)

**Environment:**
 - OS: macOS
 - OS version: 10.15.6
 - react-native version: 0.61.5
 - react-native-webview version: 10.8.3

**Comment by lklepner** [comment]
I'm experiencing this problem as well.

**Comment by milesibastos** [comment]
The emulator has no access to internet, so try it:

```sh
emulator -avd Nexus_5_API_28 -dns-server 8.8.8.8
```

**Comment by joseygordev** [comment]
Has anyone find a solution ?

**Comment by dechoiliev** [comment]
The problem in my case was is disabled a wifi connectivity on external device.

**Comment by joseygordev** [comment]
still searching for solutions...

**Comment by mrlego** [comment]
same problem here, i wish there is a fix for this T_T"

**Comment by shimangdian** [comment]
That's still a problem, when i downloadFile, this problem is become

**Comment by nikoWah** [comment]
I encountered this error sometimes when switching back and forth from Webview screen to different screens. In my testing, I was repeatedly clicking into Screen with WebView and going back to previous page. 

Is this a problem when the Component unmounts?

**Comment by yorickshan** [comment]
same problem here, any solution?

**Comment by coolswood** [comment]
same error

**Comment by cuongtranduc** [comment]
I got the same problem, seems problem with chrome resolving dns host

**Comment by Devessier** [comment]
I had the same issue on my Mac, and it turned out that I did not have access to internet inside my Android simulator.
I followed those instructions and now it works perfectly: https://stackoverflow.com/a/49332186.

**Comment by cizar** [comment]
I'm having the same issue on Android but with certain domain names. On iOS it always works.

For example, the domain [gestion.marquezyasociados.ar](https://gestion.marquezyasociados.ar) fails but [www.marquezasoc.com](https://www.marquezasoc.com) works perfectly fine.

I've checked both domains...

```bash
❯ ~ dig www.marquezasoc.com
...
;; ANSWER SECTION:
www.marquezasoc.com.	30232	IN	A	190.210.227.54

❯ ~ dig gestion.marquezyasociados.ar 
...
;; ANSWER SECTION:
gestion.marquezyasociados.ar. 171 IN	CNAME	https://front.rcemr2jat5uia.us-east-1.cs.amazonlightsail.com.
```

The weird part is that the second DNS lookup is an URL, I've never seen this kind of response. But apparently it is perfectly valid for most browsers, even with the included Chrome in Android.

Could this be the problem?

**Environment:**

- OS: macOS 12.0.1
- Android (emulated): 8.0.0
- react-native: 0.66.3
- react-native-webview: 11.15.0

**Comment by zhangyanni666** [comment]
+1

**Comment by shafqatbari** [comment]
someone found any solution? Please share

**Comment by trinanda** [comment]
I solve this error when I active internet connection on my mobile device

**Comment by lalitkumarext** [comment]
Hii, 

i'm also facing this same issue .

**Comment by fondue-tech** [comment]
Encountered the same issue.

**Comment by kayawemo** [comment]
am facing the same issue.

**Comment by alimsadeghi1** [comment]
Same error

**Comment by xclidongbo** [comment]
same issue

**Comment by tcs-aarora** [comment]
facing same issue, can anyone please  suggest something.

**Comment by suculent** [comment]
Still the same issue. This is probably a DNS issue and it was not a good idea to use the .dev TLD.

It does not work even after adding an IP for reactnative.dev to /etc/hosts.

```
sychram@vertical:~$ ping 104.21.6.202
PING 104.21.6.202 (104.21.6.202): 56 data bytes
64 bytes from 104.21.6.202: icmp_seq=0 ttl=53 time=25.342 ms
64 bytes from 104.21.6.202: icmp_seq=1 ttl=53 time=22.361 ms
^C
--- 104.21.6.202 ping statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 22.361/23.852/25.342/1.490 ms
sychram@vertical:~$ ping 172.67.135.63
PING 172.67.135.63 (172.67.135.63): 56 data bytes
64 bytes from 172.67.135.63: icmp_seq=0 ttl=53 time=78.928 ms
64 bytes from 172.67.135.63: icmp_seq=1 ttl=53 time=22.438 ms
^C
--- 172.67.135.63 ping statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 22.438/50.683/78.928/28.245 ms
sychram@vertical:~$ ping reactnative.dev


^C
```

**Comment by waohwaohwaoh** [comment]
My problem was that I was connected to the VPN. If you use a vpn like me, then first connect to the vpn and only then run the emulator, I hope this solution will help someone

**Comment by suculent** [comment]
I had a `dev` file in `/etc/resolver` causing this issue.

**Comment by waqaramjad** [comment]
Any update for solution ?

**Comment by bilmapay** [comment]
For most case in android you have to check the internet connectivity from the simulator if the wifi is connected but there is no internet connectivity this error will persist. 

**Solution**
1. Try to close the simulator 
2. make sure you internet connection is active and is working 
3. re-open the simulator 

This was how I got mine working

**Comment by juaal12** [comment]
Any update or solution? It is happening to me on my physical device. Same implementation I use for android I am using it on my iOS device and it is working fine.

**Comment by sagupta1001** [comment]
> Any update or solution? It is happening to me on my physical device. Same implementation I use for android I am using it on my iOS device and it is working fine.

+1 happening on a Physical Android device.
React-native version: 0.70.5
React Native webview: 11.13.0

**Comment by Dylan0916** [comment]
> I had the same issue on my Mac, and it turned out that I did not have access to internet inside my Android simulator. I followed those instructions and now it works perfectly: [stackoverflow.com/a/49332186](https://stackoverflow.com/a/49332186).

work for me, thanks

**Comment by Gaccoo** [comment]
Same issue on a physical Android device. Works fine on ios. Can`t find a solution.

**Comment by sonnguyen2000-github** [comment]
Try .trim() the uri

**Comment by littlepoolshark** [comment]
Encountered this problem both on virtual machine and physical device, anyone can solve it?

**Comment by bilmapay** [comment]
You could use a UI logger for the website that way you can monitor what's
happening by inspecting the UI logger. You can checkout this library:
https://www.npmjs.com/package/electrode-ui-logger

**Comment by sunnywilson93** [comment]
you can simulate this by reducing internet speed on Android emulator. 
You can tackle this using onError property of react-native-webview

**Comment by ayyam** [comment]
i am having a same problem, react native - Webview and navigate to different website NOT LOADS,

**Comment by qammarsajjad** [comment]
I am also facing issue fetching data through api my console showing this error

**Comment by ThaJay** [comment]
In my case, it really was a DNS issue because the REST API did not provide IPv6 addresses. The Problem occurred as well in Android Firefox and Android Opera besides react-native-webview which was reason to look further.

It was solved by the API team when they enabled IPv6, so it seems react-native-webview does not re-try a lookup in IPv4 space after a IPv6 lookup has failed. This seems to be the same behaviour that Firefox Android & Opera Android exhibit so this would not be a bug, but due to outdated development practises.

Thanky you for your patience and I hope this information helps someone.

**Comment by billxie1988** [comment]
this problem in my case is cause by the different file path on iOS and Android 
for example the iOS works fine but Android not well
fix it by change the source
```
source={require('./tpl.html')}
to
```
```
source= {Platform.OS === 'ios' ? require('./tpl.html') : { uri: 'file:///android_asset/tpl.html' }}
```

**Comment by arnabdotpy** [comment]
> this problem in my case is cause by the different file path on iOS and Android for example the iOS works fine but Android not well fix it by change the source
> 
> ```
> source={require('./tpl.html')}
> ```
> 
> to
> 
> ```
> source= {Platform.OS === 'ios' ? require('./tpl.html') : { uri: 'file:///android_asset/tpl.html' }}
> ```

This works, but in addition to this if you have a local file make sure to include the file in a folder called `assets` inside `android/app/src/main/` then the files will be accessible during the preview build.

Hope this helps :)
