### ISSUE TITLE
react-native webview custom font-family not working

### ISSUE THREAD

**Issue by lamaj411** [react-native-webview/react-native-webview#1620]
I am using react-native webview to display some web content in my react-native app. and my app font-family and webview font-family is different. I want to change webview font-family from app.

Is there any method to change font-family of webview (custom-font), please help me.. Thanks

**Comment by agnislav** [comment]
@lamaj411 , you can hande it by changing the WebView HTML from you app. Just add proper CSS instructions and it should work.

**Comment by lamaj411** [comment]
@agnislav my html is coming from a url and i want to change its font family(font-family.ttf from local), is there any solution?

**Comment by agnislav** [comment]
@lamaj411 got it. Then, I'd try using https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#injectedjavascript and do something like https://stackoverflow.com/a/524721
