### ISSUE TITLE
onNavigationStateChange: Unable to prevent navigation on android, working on iOS

### ISSUE THREAD

**Issue by alancwoo** [react-native-webview/react-native-webview#1625]
**Bug description:**

I'm trying to intercept a navigation change. On iOS, this works correctly where `ref.current.stopLoading()` prevents the WebView from navigating. On Android, it goes ahead and navigates (if at least partially) before `stopLoading()` takes effect.

**To Reproduce:**

I've made a fresh repo that exhibits this behaviour: https://github.com/alancwoo/react-native-webview-iss-1625

```
const App: () => React$Node = () => {
  const [url, setUrl] = useState('https://github.com/react-native-community/react-native-webview')
  const [key, setKey] = useState(0)

  const webViewRef = useRef(null)
  return (
    <>
      <StatusBar barStyle="dark-content" />
      <SafeAreaView style={{ flex: 1, width: '100%' }}>
        <WebView
          key={key}
          ref={webViewRef}
          source={{ uri: url }}
          style={{ flex: 1, width: '100%' }}
          onNavigationStateChange={(event) => {
            if (event.url !== url) {
              webViewRef.current.stopLoading()
              Alert.alert('stopped')
            }
          }}
        />
      </SafeAreaView>
    </>
  );
};
```

**Expected behavior:**

Android should behave the same as on iOS, and should halt loading before transitioning.

**Screenshots/Videos:**

Android Start:
![image](https://user-images.githubusercontent.com/1481890/92644308-70ab6480-f2e3-11ea-942b-dcda6e4353be.png)

Tap on 'Sign Up' (Loads signup page before stopping and showing alert):
![image](https://user-images.githubusercontent.com/1481890/92644341-7a34cc80-f2e3-11ea-9961-e61bfadc71aa.png)

iOS (Correctly stops loading and shows alert):
![image](https://user-images.githubusercontent.com/1481890/92644215-4ce81e80-f2e3-11ea-92cd-95ca11cab07e.png)

**Environment:**
 - OS: Mac OS
 - OS version: 10.15.6
 - react-native version: 0.63.2
 - react-native-webview version: ^10.8.3

**Comment by TheAlmightyBob** [comment]
Why can't you use `onShouldStartLoadWithRequest`?

**Comment by ausshadu** [comment]
Any updates on this?

**Comment by runryan** [comment]
Only works for the uri passed into WebView. Any other route from the uri page does not trigger `onNavigationStateChange` called.

**Comment by ausshadu** [comment]
Still searching for solutions

**Comment by swathi2378** [comment]
any update on this issue, i am facing the same in Android

**Comment by TheAlmightyBob** [comment]
@ausshadu @swathi2378 Same question as above, why can't you use `onShouldStartLoadWithRequest`?

**Comment by AtmasApps** [comment]
@TheAlmightyBob That worked for me. Thanks. I'm using a physical Android v9 phone. A $20 disposable quality phone, so not really special hardware..

Also I noticed the URL https://reactnative.dev/docs/webview indicates a platform of iOS. Perhaps it's not consistently supported on Android..? Maybe this is what others are seeing?

`
          <WebView
            ...
           onShouldStartLoadWithRequest={(req) => {

              if ("https://myspecialUrl" == req.url) {
                return false;
              } 

              return true;
            }}
`

**Comment by TheAlmightyBob** [comment]
@AtmasApps That documentation you linked is for the old WebView that was bundled into React Native back in the day, not the version here. It is years out of date, hence the deprecation warning at the top.

https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#onshouldstartloadwithrequest is the correct documentation.

**Comment by AtmasApps** [comment]
I see the banner now that you point it out. Before I think I CTRL-F'd right by it. With the new docs/code showing full cross platform compatibility, I can't imagine a reason this bug would need to stay open. Anyhow, just wanted to mention your solution worked for me, so I would encourage the others who stumble on this page to follow it. Also I like the newer docs. Better sample to be had there.

Thanks for sharing.

**Comment by alancwoo** [comment]
After updating:
react-native-webview: `10.8.3` > `11.0.2`
react-native: `0.6.2` > `0.6.4`

I can confirm that on android, `onShouldStartLoadWithRequest` is behaving correctly now:

```
      <SafeAreaView style={{ flex: 1, width: '100%' }}>
        <WebView
          key={key}
          ref={webViewRef}
          source={{ uri: url }}
          style={{ flex: 1, width: '100%' }}
          onShouldStartLoadWithRequest={(event) => {
            if (event.url !== url) {
              // webViewRef.current.stopLoading()
              Alert.alert('Prevent loading')
              return false
            } else {
              return true
            }
          }}
        />
      </SafeAreaView>
```

**Comment by swathi2378** [comment]
> @ausshadu @swathi2378 Same question as above, why can't you use `onShouldStartLoadWithRequest`?

onShouldStartLoadWithRequest doesnt trigger in first time in android as per the documentation. "On Android, is not called on the first load." I am getting the whitescreen for the first time in android.

**Comment by ausshadu** [comment]
@alancwoo 

react-native-webview: ^11.2.1
react-native: 0.63.4

I tried using `onShouldStartLoadWithRequest ` didn't work 😕

**Comment by DevAhmad7** [comment]
work with me
```
onLoadProgress={(e) => {
          const state = e.nativeEvent;
          setCanGoBack(state.canGoBack)
}}
```
![Screenshot (168)](https://user-images.githubusercontent.com/55281583/108544559-51335180-72ef-11eb-92b5-8a5f141d8d19.png)

**Comment by HerickRaposo** [comment]
I need close webview and navigate to loogin page , how can i do this?

**Comment by charlescampista** [comment]
> @TheAlmightyBob That worked for me. Thanks. I'm using a physical Android v9 phone. A $20 disposable quality phone, so not really special hardware..
> 
> Also I noticed the URL https://reactnative.dev/docs/webview indicates a platform of iOS. Perhaps it's not consistently supported on Android..? Maybe this is what others are seeing?
> 
> `<WebView onShouldStartLoadWithRequest={(req) => { if ("https://myspecialUrl" == req.url) { return false; } return true; }} />`


☝️ This one has worked well for me!

**Comment by blueberry6401** [comment]
What if I want to prevent only navigation? For example
Current page is A, user click a link and navigate to B, I want to prevent that.
Logging onShouldStartLoadWithRequest, there is many logs for url between A and B, like hotjar for example.
Using onLoadProgress or onNavigationStateChange, I cannot prevent page to load. Things I can do is call stopLoading and call goBack after that, which is very tricky and not working all the time.

**Comment by HerickRaposo** [comment]
``Would you use onShouldStartLoadWithRequest proprety calling a function returning true or false, in method action you would put condition to verify if the url is equals the url that you need block . For exemple:


```
<WebView
...
 onShouldStartLoadWithRequest={(event)=>{
            return action(event.url)
        }}/>

function voltar(url){
    setNewUrl(url)
    if (url == 'https://google.com.br/login') {
      logOut();
      return false;
    } else if (url.includes(`http://google.com.br/`)){
      if (Platform.OS === 'ios' ) {
        Linking.openURL(url);
        return false;
      } else {
        return true;
      }
    }  else if (url.includes('leitorqrcode.xhtml')) {
      const uuid = url.split("?").pop().split('=').pop();
      setuuid(uuid);
      setIsQrScanner(true)
      setModalVisible(true);
      return false;
    }  else if (url.includes('leitorBarcode.xhtml')) {
      const uuid = url.split("?").pop().split('=').pop();
      setuuid(uuid);
      setIsQrScanner(false)
      setModalVisible(true);
      return false;
    } else {
      return true;
    }
  }
```
With this you just define that you wish load or not load the url

**Comment by SaileshKumar** [comment]
> @AtmasApps That documentation you linked is for the old WebView that was bundled into React Native back in the day, not the version here. It is years out of date, hence the deprecation warning at the top.
> 
> https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#onshouldstartloadwithrequest is the correct documentation.

When I tested this, it seems like the function is only run when changing URLs with a new domain, but not for navigation within a site. Is that true? Like blah.com/home vs blah.com/profile

I want to prevent navigation within the webview and handle it natively for certain situations like that, but onNavigationStateChange seems to run after the site is loaded and onShouldStartLoadWithRequest not at all since it's the same domain

**Comment by TheAlmightyBob** [comment]
@SaileshKumar 

> When I tested this, it seems like the function is only run when changing URLs with a new domain, but not for navigation within a site. Is that true? Like blah.com/home vs blah.com/profile

That is not true, unless you've found a bug (if so, please open a separate issue and provide a repro). We've long been using `onShouldStartLoadWithRequest` for precisely the scenario you describe.

**Comment by TheAlmightyBob** [comment]
@SaileshKumar There was nothing special we had to do. I can't speak to how `onNavigationStateChange` behaves since I've never used that... `onShouldStartLoadWithRequest` has always suited our needs.

My only guess is that perhaps the site you're testing with isn't doing "real" top-level navigations... as I know Android won't trigger `onShouldStartLoadWithRequest` for nested frames (but iOS will, I'm not sure which platform you're testing or if you've noticed a difference there).

**Comment by SaileshKumar** [comment]
> @SaileshKumar There was nothing special we had to do. I can't speak to how `onNavigationStateChange` behaves since I've never used that... `onShouldStartLoadWithRequest` has always suited our needs.
> 
> My only guess is that perhaps the site you're testing with isn't doing "real" top-level navigations... as I know Android won't trigger `onShouldStartLoadWithRequest` for nested frames (but iOS will, I'm not sure which platform you're testing or if you've noticed a difference there).

Got it, I'll keep poking around then. Was testing on iOS simulator, will see what I find. Helpful to know that particular use case is working for you

**Comment by Natett** [comment]
facing same issue , any update ?

**Comment by HenryHaoson** [comment]
it will only be called with non-HTTP(S) schemes for iframes in Android.
[doc](https://developer.android.com/reference/android/webkit/WebViewClient#shouldOverrideUrlLoading(android.webkit.WebView,%20android.webkit.WebResourceRequest))

[code](https://chromium.googlesource.com/chromium/src/+/c9319955d9cd479f998628f93032d7ac4a111b9d/android_webview/browser/aw_content_browser_client.cc#630)

**Comment by rodolphoasb** [comment]
Be carefull with Next.js `Link` component. It will not trigger onShouldStartLoadWithRequest. It needs to be an `<a>`.

**Comment by bhavesh-lw** [comment]
@rodolphoasb : Did you resolve issue. We are facing same issue. Is there any work around or alternate?

**Comment by HarlicWork** [comment]
There is another props called onOpenWindow that intercept when open new window from webview. works on iOS and Android.
[Link](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#onopenwindow)
