### ISSUE TITLE
WebGL Support

### ISSUE THREAD

**Issue by jkwik** [react-native-webview/react-native-webview#1626]
**Overview**
We're using react native `WebView` to render web pages for online games and are developing our application for the macOS, iOS and Android. A number of our vendors use unity and consequently webgl to render their applications and this doesn't seem to render properly (at all) in WebView.

I've tested that these webgl applications work in my native browser (Safari).

**Workarounds**
I'm aware that there are packages out there capable of rendering unity projects (https://www.npmjs.com/package/react-native-unity-view), however because we are loading webpages that utilize unity, we don't have direct access to the unity bundles or builds so webgl support through WebView is our only path forward.

**Potential Solution**
After some searching the only promising lead I can find for macOS is listed in this thread: https://stackoverflow.com/questions/13659133/enable-webgl-in-the-mac-os-application-on-webkit which I haven't given a go yet but could potentially be a fix.

**Related Posting**
I noticed a recent similar posting here: https://github.com/react-native-community/react-native-webview/issues/1621 however this only details support for windows. I was wondering if there would be support for all platforms.

**Comment by SabreRunner** [comment]
I'm trying the same thing right now and this is still issue. Can this be fixed?

**Comment by hungdev** [comment]
im also getting this error.

**Comment by ahujsak** [comment]
still searching.

**Comment by gfaraj** [comment]
Has anyone figured this out yet?

**Comment by p0w1nd** [comment]
I'm also interested in this.

**Comment by hari-mohan-choudhary** [comment]
I'm also looking same things
