### ISSUE TITLE
Webview doesn't send the session cookie when it downloads an attachment

### ISSUE THREAD

**Issue by ata555** [react-native-webview/react-native-webview#1629]
**Bug description:**

I have a web page that contains an attachment, when i click on it to start downloading, webview download manager doesn't send the cookies so the request is redirected to the login page and the login page is downloaded instead of the actual file.

I have tried to manually download the file through RNFetchBlob and manually setting the session cookie, it worked, but
i can't obtain the session cookie using document.cookie because httpOnly flag is set on it.

do you have a solution for this problem? the actual file can't be downloaded unless the session cookie is sent, but webview download manager is not sending it.

**Expected behavior:**

Webview should send the session cookie when downloading a file that a Content-Disposition header is set on it 

**Environment:**
 - OS: Android
 - OS version:
 - react-native version: 0.63.2
 - react-native-webview version: 10.3.3

**Comment by ata555** [comment]
Android CookieManager can't read httpOnly cookies, that is why its not sending the session cookie.

**Comment by pcprinz** [comment]
Same problem here. 

I'm developing an application for my university. We have [Horde](https://www.horde.org/) as webmail and [Moodle](https://moodle.de/) as learning platform. In both services we need to download files (in common PDFs), but tough they are proteced by our Central Authentication System ([CAS](https://www.apereo.org/projects/cas)).

By accessing the services, the webview successfully sets the authentication cookies we prepared before, but by downloading files the cookies are not sent. So we end up with an error by downloading files.

**Comment by ata555** [comment]
I did set the httpOnly flag on session cookie to false, and i have wrote a code to manually download the file by overriding onShouldStartLoadWithRequest

`onStartDownloadAndroid(event: WebViewNavigation)  {
    if (event.url.match(/(\D)+\/[0-9]+\/[0-9]+/)) {
      this.downloadFile(event.url);
      return false;
    } else {
      return true;
    }
    
  }

async getFileName(url: string) {
    let contentDispositionHeader: any = "";
    let fileName: any = "Unnamed" + Date.now();
    await fetch(url, {method: 'GET'})
        .then(
            function(response) {
              contentDispositionHeader = response.headers.get('Content-Disposition');
              const regResult = /filename[^;=\n]*=(?:(\\?['"])(.*?)\1|(?:[^\s]+'.*?')?([^;\n]*))/i.exec(contentDispositionHeader) as string[];
              fileName = regResult[0].replace("filename = \" ", "");
            }
        )
        .catch(function(err) {
            console.log('Fetch Error', err);
        });
    return decodeURIComponent(fileName);
  }

async downloadFile(url: string) {
    //console.warn(this.cookies);
    ToastAndroid.show(Dict.jawwalWebView_fileDownloadStarted, ToastAndroid.SHORT);
    const fileName = await this.getFileName(url);
    let downloadDest = `${RNFetchBlob.fs.dirs.DownloadDir}/${fileName}`;
    RNFetchBlob
    .config({
        addAndroidDownloads : {
            useDownloadManager : true, // <-- this is the only thing required
            // Optional, override notification setting (default to true)
            notification : true,
            path: downloadDest,
            // Optional, but recommended since android DownloadManager will fail when
            // the url does not contains a file extension, by default the mime type will be text/plain
            //mime : 'text/plain',
            description : 'File downloaded by download manager.'
        }
    })
    .fetch('GET', url, { 'Cookie' : this.cookies })
    .then((resp) => {
      // the path of downloaded file
    });

    ToastAndroid.show(Dict.jawwalWebView_fileHasBeenDownloaded, ToastAndroid.SHORT);
  }`

**Comment by roeycohen** [comment]
A possible workaround for this issue may be detecting download links inside onShouldStartLoadWithRequest event,
then passing the request to the server with a new parameter asking for a temporary download token (e.g. jwt),
and then pass the tokenized URL to the browser using Linking.openURL.

I believe in some cases letting the device browser handling the downloads should be easier than using RNFetchBlob and handling storage and progress display, canceling download and etc.
