### ISSUE TITLE
Videos in a webview doesn't play

### ISSUE THREAD

**Issue by diogoamiranda** [react-native-webview/react-native-webview#1632]
**Bug description:**
It is not possible to play any video in a webview. I have already tried videos from youtube (embedded, iframe, in an html file), vimeo ... no video works, no image, no sound, just an inifinite loading. Opening the same link in the device's default browser, the video starts playing. Opening the same link through the webview the page is loaded but the video doesn't play. 

**Notes:**
 - I added `android:hardwareAccelerated="true"` in androidManifest and `<uses-permission android:name="android.permission.INTERNET"/>`
 - I created a **simple native example on android** using webview and any video **works without any problem**.
 - I implemented a **native ui component** that when mounted starts a webview **in an activity and it works**.
 - If i put the code bellow in the **Main Activity** of my app it also works.
```
@Override
  @CallSuper
  protected void onCreate(@Nullable Bundle savedInstanceState) {
      super.onCreate(savedInstanceState);

      webView = new WebView(this);
      setContentView(webView);

      WebSettings webSettings = webView.getSettings();
      webSettings.setJavaScriptEnabled(true);
      webSettings.setAllowFileAccess(true);

      webView.setWebViewClient(new WebViewClient() {
          @Override
          public boolean shouldOverrideUrlLoading(WebView view, String url) {
              return true;
          }
      });

      webView.setWebChromeClient(new WebChromeClient());
      webView.loadUrl("https://www.youtube.com/embed/TQsl9nxs_1o?autoplay=1");
  }
}
```

**Environment:**
 - Device: Fire TV Stick (Gen 2)
 - OS version: Fire OS 5
 - Android version : Android Level 22 (Android 5.1)
 - react-native version: 0.63.2
 - react-native-webview version: 10.8.3

**Comment by matamicen** [comment]
We have a similar problem with Android 7 & 8 versions and react-native-webview 10.3.2

The video audio is playing but the image is blackscreen, so no video  images. We tried different Video Players and still have the same problem.

And it is working on the device's default browser.

Any ideas?

Thnaks @Titozzz @jamonholmgren :)

**Comment by quyetthang122** [comment]
Hi guys, I have the same issue like @matamicen in Android, but it is working fine in IOS. Have you figured out a solution yet?

**Comment by Marinaarimany** [comment]
Hello, 
I have the same concerns on Android and react-native-webview is up to date. :/
Please help us

**Comment by Marinaarimany** [comment]
Hello @Titozzz 
Can you help us please ?

Thank you

Best regards

**Comment by Marinaarimany** [comment]
Hello, 
Here is my repository with the error : 
https://gitlab.com/MarinaAmy/webviewrn

Thank you

**Comment by quyetthang122** [comment]
Hi @Marinaarimany, I think you can use this one https://github.com/proyecto26/react-native-inappbrowser instead of react native webview. it does the same think with this webview library.

**Comment by Marinaarimany** [comment]
Hi @quyetthang122 !
First of all thank you for your answer it works wonderfully. However, I would like to know if we can remove the topbar where there is the link and the cross? thank you :)

**Comment by Marinaarimany** [comment]
@quyetthang122  
I saw that this library opens google chrome in a separate page while we want to have the webview integrated into the application

**Comment by Marinaarimany** [comment]
Still the same problem with version 10.10: /

**Comment by Marinaarimany** [comment]
set as below
mixedContentMode='always'

it works for me

**Comment by brayanarrieta** [comment]
Any update with this video issue I'm to put a youtube video but not works the components is just ignored

**Comment by veraldo** [comment]
@matamicen @quyetthang122 

I had this issue of only audio playing, it was happening with hardware acceleration disabled 🤔 so it was "fixed" by avoiding changing the default values of the androidHardwareAccelerationDisabled or androidLayerType props

**Comment by lexguy** [comment]
> mixedContentMode='always'

thanks.  also works for me

**Comment by mayureshpr** [comment]
setting androidLayerType={'hardware'} worked for me on android. IOS it works fine

**Comment by promit13** [comment]
I'm having this issue when I try to play spotify web playback in android. It works fine is ios. Can anyone help ?

**Comment by SurajMDurgad** [comment]
Having the same issue, tried everything mentioned above doesn't work on youtube videos.

**Comment by ShivamKJJW** [comment]
Just don't disable `androidHardwareAccelerationDisabled`. It will start playing videos.

**Comment by sidVaidya** [comment]
<WebView
                            mediaPlaybackRequiresUserAction={true}
                            androidLayerType= 'hardware'
                            mixedContentMode='always'
                            style={{ height: 240, width: 320, alignSelf: "center", alignContent: "center", }}
                            javaScriptEnabled={true}
                            source={{ uri: `https://www.youtube.com/embed/sFFwvr6l2mM?
=0&autoplay=0&showinfo=0&controls=0&fullscreen=0` }}
                        />
I have this code but only audio is playing video not visible

**Comment by ShivamKJJW** [comment]
> <WebView
> mediaPlaybackRequiresUserAction={true}
> androidLayerType= 'hardware'
> mixedContentMode='always'
> style={{ height: 240, width: 320, alignSelf: "center", alignContent: "center", }}
> javaScriptEnabled={true}
> source={{ uri: `https://www.youtube.com/embed/sFFwvr6l2mM? =0&autoplay=0&showinfo=0&controls=0&fullscreen=0` }}
> />
> I have this code but only audio is playing video not visible

No need to change layertype, contentMode. Remove those.

**Comment by sidVaidya** [comment]
@ShivamKJJW  ya tried without those params also but same result

**Comment by ShivamKJJW** [comment]
@sidVaidya I believe you are on latest update of webview. Exact same settings works for me. May be try using direct links of youtube instead of embed links.

**Comment by sidVaidya** [comment]
@ShivamKJJW yes i am on latest which version are you on?

**Comment by ShivamKJJW** [comment]
@sidVaidya I have last checked it on 11.4.5

**Comment by sidVaidya** [comment]
@ShivamKJJW ok i am on 11.4.6

**Comment by c-moyer** [comment]
I have the same issue when I try to view the W3 Schools HTML5 video tag example from an Amazon Fire Stick. 

````
import React, { Component } from 'react';
import { WebView } from 'react-native-webview';

class Player extends Component {
  componentDidMount(){
 
  }
  render() {
    return <WebView source={{ uri: 'https://www.w3schools.com/html/html5_video.asp' }} />;
  }
}

export default Player;
````

I've tried all of the recommendations in this thread but non worked. I'm using version `11.6.2`.

**Comment by brettins** [comment]
Video is not playing for us either.

**Comment by mirceaciu** [comment]
It might be device dependent, but with plenty of our devices:

- software acceleration mode = no video play (embeded youtube) tho progress bar is buffering + clean UI but less responsive
- hardware acceleration mode = video and audio OK + visible display artifacts when loading page with video 

no acceleration brings the same result as hardware acceleration.

**Comment by Nagato717** [comment]
Hi there, in my case it's showing `Video unavailable, Watch on Youtube` for youtube embed link, any solutions? Thanks in advance!!

**Comment by jzongker** [comment]
It appears to work ok in Android 10+ but fails with Android 9- which unfortunately is still used on Amazon Fire devices.  This is also true with the emulator on 9 vs 10.

**Comment by scott-augment** [comment]
Running into this issue as well. We've got some HTML content that includes a div and a script to build an STN video. The video builds fine and works, the issue is that it is a black screen on Android. Audio is present on iOS and Android. Tested Android devices are all 10+ (most are 11).

**Comment by darioduarte** [comment]
> setting androidLayerType={'hardware'} worked for me on android. IOS it works fine

it's works for me thi solution, thanks

**Comment by mmuminovic** [comment]
> 

This works for me also. Thanks 👍🏻

**Comment by Jahanzaib320** [comment]
> Posting here because my embedded YouTube videos were working on iOS but then not playing with sound on Android. They would play if it was muted, but wouldn't play with sound, even after they started playing, and unmute'ing would cause them to pause
> 
> So, in case anyone is on this issue, like me, looking for a solution I was able to fix it with the `mediaPlaybackRequiresUserAction={false}` prop (even though it is still requiring user action)

this is workable , thank you 💕

**Comment by Muhammad-Usama-lab** [comment]
My works fine on android 

 <WebView
        source={{uri: url}}
        javaScriptEnabled={true}
        domStorageEnabled={true}
        mediaPlaybackRequiresUserAction={false}
        androidLayerType={'hardware'}
        mixedContentMode="always"
        onLoadEnd={handleLoadEnd}
        onError={event => {
          console.log({event});
          setError(true);
          setLoading(false);
        }}
      />
      
      webview version: 
      "react-native-webview": "^13.6.3",
      
      Hope it helps 🙂

**Comment by swapnilsuccessive** [comment]
Hi @diogoamiranda we are facing same issue the video is working for youtube also the Vimeo videos is working on google tv but stuck on Fire TV Stick.

And tried everything above mentioned was there any particular fix that has worked.

**Comment by Muhammad-Usama-lab** [comment]
> Hi @diogoamiranda we are facing same issue the video is working for youtube also the Vimeo videos is working on google tv but stuck on Fire TV Stick.
> 
> And tried everything above mentioned was there any particular fix that has worked.

My works fine on android

<WebView
source={{uri: url}}
javaScriptEnabled={true}
domStorageEnabled={true}
mediaPlaybackRequiresUserAction={false}
androidLayerType={'hardware'}
mixedContentMode="always"
onLoadEnd={handleLoadEnd}
onError={event => {
console.log({event});
setError(true);
setLoading(false);
}}
/>

  webview version: 
  "react-native-webview": "^13.6.3"

**Comment by swapnilsuccessive** [comment]
Thanks @Muhammad-Usama-lab  but the issue is in vimeo videos in **Fire TV** only while everywhere it's working fine. for me as well. Also for me the youtube is also working fine in RN it's just the issue with Vimeo videos on react native similar to what @diogoamiranda was facing.

**Comment by MatteoPironi** [comment]
> Thanks @Muhammad-Usama-lab but the issue is in vimeo videos in **Fire TV** only while everywhere it's working fine. for me as well. Also for me the youtube is also working fine in RN it's just the issue with Vimeo videos on Fire TV similar to what @diogoamiranda was facing.

Hi, any update on this? I have the same problem on Fire TV
