### ISSUE TITLE
requireNativeComponent: "RNCWebView", cant get pods ? i dont know exactly what is the problem

### ISSUE THREAD

**Issue by onurcskun** [react-native-webview/react-native-webview#1633]
firstly, i wanted to create a sdk which using react-native-webview.
i created project with
`npx @react-native-community/bob create rn-test-sdk`
which has include base of a module and includes example folder bare react native app.

in example folder I run `yarn add '../'` to use test sdk
then I add react-native-webview to rn-test-sdk. It autolinked to project
in example project I did yarn install, pod install etc and it install test-sdk and react-native-webview itself too

when started example project the common error showed up .. requireNativeComponent: "RNCWebView" ...

any suggestion, any guideline ? i tried a lot of thing but i could not solve this issue :/

**Comment by i-m-aman** [comment]
Have you find any solution?

**Comment by onurcskun** [comment]
@i-m-aman nope :(

**Comment by onurcskun** [comment]
I found that nothing supports symlinks. So you can work with only the example folder in the library. 
About this error, you should also install react-native-webview to your target project.
example
`npm i test-library && npm i react-native-webview`
then, link it, etc. and it will work.
