### ISSUE TITLE
keyboardAppearance for WebView

### ISSUE THREAD

**Issue by thesved** [react-native-webview/react-native-webview#1634]
**The problem**
keyboardAppearance can be set on TextInput, I want to be able to set it on WebView too.

**Additional context**
I can catch when the keyboard is showing up, but I can't set its appearance.

**Comment by TheAlmightyBob** [comment]
A quick Googling suggests that iOS does not support this: https://developer.apple.com/forums/thread/120631

**Comment by sachinrekhi** [comment]
This post suggests a technique that does work for adding keyboardAppearance to WKWebView: https://stackoverflow.com/a/47949089/1533659

**Comment by personalizedrefrigerator** [comment]
Could someone please re-open this -- I'm still experiencing the issue!

**Comment by TheAlmightyBob** [comment]
@personalizedrefrigerator Have you tried the technique that @sachinrekhi linked?

**Comment by justinfauci** [comment]
For anyone else who ended up here looking for a solution to showing a dark mode keyboard in a webview, the solution was surprisingly simple. I just added an effect to the top of the component that loads my webview, making use of RN's Appearance module:

```
const WebViewComponent = () => {
useEffect(() => {
    if (Platform.OS === 'ios') {
      Appearance.setColorScheme('dark');
    }

    return () => {
      if (Platform.OS === 'ios') {
        Appearance.setColorScheme('light'); // or whatever your previous value was
      }
    };
  }, []);
  return <WebView source={{ uri: 'https://reactnative.dev/' }} style={{ flex: 1 }} />;
}
```

Now all keyboards shown within the WebView render in dark mode.
