### ISSUE TITLE
When i get local Storage . windown.localStorage i 've had  SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

### ISSUE THREAD

**Issue by tuankhanh45** [react-native-webview/react-native-webview#1635]
**Bug description:**

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS:
 - OS version:
 - react-native version:^0.62.2
 - react-native-webview version:^10.3.1

**Comment by AlexanderTserkovniy** [comment]
Has anyone been able to solve issue with this?

**Comment by jevarg** [comment]
If one day someone has the same issue, I just had it on Android. It was because in my case I had a string html source (which is passed to the webview using the `data://` scheme) and Android blocks access to the storage for that.
My solution was to set the `baseUrl` option to something starting with `http://` like so:
```typescript
// ...
<WebView
    originWhitelist={['*']}
    source={{ html: LoginTemplate, baseUrl: 'http://localhost' }} // <-- baseUrl example here
/>
// ...
```

**Comment by Neungzad** [comment]
> If one day someone has the same issue, I just had it on Android. It was because in my case I had a string html source (which is passed to the webview using the `data://` scheme) and Android blocks access to the storage for that. My solution was to set the `baseUrl` option to something starting with `http://` like so:
> 
> ```ts
> // ...
> <WebView
>     originWhitelist={['*']}
>     source={{ html: LoginTemplate, baseUrl: 'http://localhost' }} // <-- baseUrl example here
> />
> // ...
> ```

I almost give up. I really want to thank you for your solution @jevarg

**Comment by nlswtlr** [comment]
@jevarg just saved the day! 🙏
