### ISSUE TITLE
Webview working fine for all URL's. But, In my case I have a URL for Conference call. The Call should be view on Webview

### ISSUE THREAD

**Issue by ASakkeer** [react-native-webview/react-native-webview#1637]
I have to build the feature for conference call on Webview mode and I complete it. It is working for all other web URL's. 
Here is my Webview code for your reference:

`      <WebView
        source={source}
        style={style}
        renderLoading={() => this.renderLoadingIndicator()}
        renderError={(errorName) => this.renderErrorMessage(errorName)}
        startInLoadingState={startInLoadingState}
        userAgent={userAgent}
        onNavigationStateChange={({ url }) => onNavigationStateChange(url)}
        ref={(ref) => {
          this.webView = ref;
        }}
        onError={(event) => onError(event.nativeEvent)}
        injectedJavaScript={injectedJavaScript}
        onMessage={onMessage}
        allowsFullscreenVideo={allowsFullscreenVideo}
        allowsInlineMediaPlayback={allowsInlineMediaPlayback}
      />`

So, guys, this is my code. I have tried a lot of URLs in the source field. But, when I use my conference call URl for the source, It is working on Android perfectly and also It should work on IOS. Unfortunately, IOS Webview is loaded but the screen shows as empty.

I don't know if I have made any small mistake. If the question is wrong, just ping me. So that I can alter the question perfectly. 

Androis screenshot:
<img width="200" alt="Screenshot 2020-09-10 at 3 14 45 PM" src="https://user-images.githubusercontent.com/56513278/93069995-f3de0900-f69b-11ea-805b-15bd32f61518.png">

IOS Screenshot:
<img width="200" alt="File - September 10, 2020 2_49 PM" src="https://user-images.githubusercontent.com/56513278/93070053-06584280-f69c-11ea-9c9f-1d6d78aa0f1e.png">

**Comment by VinayakDeshpande11** [comment]
Try adding sharedCookiesEnabled={true} in the webview tag, this worked for me.
