### ISSUE TITLE
React Native Webview Expo Error Loading Page Err Code: -2

### ISSUE THREAD

**Issue by firzatullahd** [react-native-webview/react-native-webview#1638]
**Bug description:**

Hey I am new in react native, i am trying to put my website into an android app and it has worked so far, 
until **I disconnect from the internet it shows the following**
![Screenshot_1600143612](https://user-images.githubusercontent.com/57289351/93165487-67d4eb80-f746-11ea-887a-b638a3c7951c.png)

Code : 
`import React, { Component } from 'react';
import { View, Text } from 'react-native'
import { WebView } from 'react-native-webview';

export default class App extends Component {
  constructor(props) {
    super(props);

    this.state = {
      url: 'https://www.reactnative.dev',
    };
  }

  handleNavigationStateChange = navState => {
    console.log(navState);
  };

  render() {
    // this javascript will be injected on page load 
    const injectedJs = `
      window.postMessage(window.location.href);
    `;

    return (
      <WebView
        source={{ uri: this.state.url }}
        bounces={true}
        style={[
          {
            flex: 1
          },
        ]}
        injectedJavaScript={injectedJs}
        startInLoadingState
        scalesPageToFit
        javaScriptEnabledAndroid={true}
        javaScriptEnabled={true}
        onNavigationStateChange={this.handleNavigationStateChange}
        onMessage={event => {
          alert('MESSAGE >>>>' + event.nativeEvent.data);
        }}
        onLoadStart={() => {
          alert("LOAD START ");
        }}
        onLoadEnd={() => {
          alert('LOAD END');
        }}
        onError={err => {
          alert('ERROR ');
          alert(err);
          return (
            <View style={{ flex: 1, justifyContent: "center", alignItems: "center" }}>
              <Text>Internet Lost</Text>
            </View>
          );
        }}
      />
    );
  }
}
`

**Expected behavior:**
**I expected it to just show a screen that says internet lost**, and from there i hope that i can put button to refresh the screen when the internet connection is back online. 

I have tried to use [netinfo](https://github.com/react-native-community/react-native-netinfo), to check the internet connection and redirect it to other screen that i made, but it seems the problem is the webview.

**Environment:**
 - OS: Android
 - OS version: All Ver.
 - react-native version: "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz"
 - react-native-webview version: "9.4.0"

**Comment by babyrusa** [comment]
still happens :(

**Comment by alimsadeghi1** [comment]
And still happens :|

**Comment by pmprete** [comment]
still happens

**Comment by zilan830** [comment]
still happens

**Comment by IlyasKham999** [comment]
still happens
