### ISSUE TITLE
contentMode on Android

### ISSUE THREAD

**Issue by andre-gois** [react-native-webview/react-native-webview#1639]
Is there a way to add the contentMode prop to Android devices?

My goal is to render the content of the WebView in Desktop mode.

**Comment by Urvi1012** [comment]
I want same .

**Comment by Urvi1012** [comment]
**add userAgent in webview**

<WebView
              source={{ uri: "https://www.google.com/" }}
              userAgent={
                "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2564.109 Safari/537.36"
              }
              style={{ flex: 1 }}
            /> 

**above code works for me**

**Comment by MustafaNureAlam** [comment]
> **add userAgent in webview**
> 
> <WebView source={{ uri: "https://www.google.com/" }} userAgent={ "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2564.109 Safari/537.36" } style={{ flex: 1 }} />
> 
> **above code works for me**

Chrome/101.0

**Comment by sajeeldigitali** [comment]
Hi,
Thanks, @Urvi1012 

this string works on both Android and IOS

<Webview
userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
/>

do replace the Chrome version with the latest one, in my case **Chrome/105.0.0.0** is the latest

**Comment by SajeelHassan** [comment]
Hi,
Thanks, @Urvi1012 

this string works on both Android and IOS

```
<Webview
userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
/>
```

do replace the Chrome version with the latest one, in my case **Chrome/105.0.0.0** is the latest
