### ISSUE TITLE
Kotlin build warning

### ISSUE THREAD

**Issue by sam541** [react-native-webview/react-native-webview#1640]
**Bug description:**
App created using npx create-react-native-app is giving this error when I want to use webview on the project. This might not be an issue of this repository but I would like to learn what is the proper way to call Kotlin dependency and opening this issue to be an example if anyone else goes through the same error.

**In the "npm run android" output**
The Kotlin Gradle plugin was loaded multiple times in different subprojects, which is not supported and may break the build.
This might happen in subprojects that apply the Kotlin plugins with the Gradle 'plugins { ... }' DSL if they specify explicit versions, even if the versions are equal.
Please add the Kotlin plugin to the common parent project or the root project, then remove the versions in the subprojects.
If the parent project does not need the plugin, add 'apply false' to the plugin line.
See: https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl
The Kotlin plugin was loaded in the following projects: ':expo-error-recovery', ':react-native-webview'

**To Reproduce:**
Use npx create-react-native-app, execute "npm i react-native-webview", then "npm run android"

**Expected behavior:**
Project to run without Kotlin error 

**Screenshots/Videos:**

**Environment:**
 - OS: Windows 
 - OS version: 	10.0.19041 Build 19041
 - react-native version:"~0.62.2"
 - react-native-webview version:"9.4.0"

**Comment by allanlisboaweb** [comment]
Tenho o mesmo problema!

**Comment by markrickert** [comment]
I was able to get my build working by adding this to my `build.gradle` file:

```
classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.71'
```

https://github.com/react-native-webview/react-native-webview/issues/1280#issuecomment-633597530
