### ISSUE TITLE
allow getUserMedia() on local network (HTTP without ssl)

### ISSUE THREAD

**Issue by damieng57** [react-native-webview/react-native-webview#1641]
Hello

I have a webserver install on a phone to serve media only on a local network. On Chrome (Mobile or Desktop), I enabled 'unsafely-treat-insecure-origin-as-secure', choose my IP address and it works. But in a webview, getUserMedia() isn't allowed if the connection isn't secure (HTTPs). If you can implement a similar functionality, it will be great. Or maybe, tell me were I should search to find a solution.

Thank you very much.

**Comment by prcf** [comment]
I think only a wrap to solve this issue.
Something like create a false "secure context" on the HTTP conection.
Report me if you know this.
Thanks
