### ISSUE TITLE
Add event onLoadResource 

### ISSUE THREAD

**Issue by grovertb** [react-native-webview/react-native-webview#1645]
**Is your feature request related to a problem? If so, Please describe.**
Currently I need to capture the resources that the webview loads internally, for which the onLoadResource event needs to be implemented.

**Describe the solutions you came up with**
I have made the integration of the onLoadResource event in [my fork](https://github.com/grovertb/react-native-webview)

**Additional context**
I do not handle well the standard of how a new event should be integrated but with what I did it is working for android

I'm sorry for my English

**Comment by mir4a** [comment]
hey, @grovertb could you please create a PR with your implementation?
