### ISSUE TITLE
iOS 14 - Error loading page, Domain: NSURLErrorDomain, Error Code: -1202, Description: The certificate for this server is invalid.

### ISSUE THREAD

**Issue by dsherida** [react-native-webview/react-native-webview#1647]
I just ran into a cert validation issue when loading a local development server into my webview. Before I updated to iOS 14 this was not a problem and iOS 13.7 had no issues validating the self signed certs that I was using. Suddenly, after applying the iOS 14 update, I am no longer able to load my local web server in the webview using the same certs. 

Does anybody know if the TLS cert trust requirements have changed from iOS 13 to iOS 14?

The error I am getting contains the following info:

**Error loading page**
Domain: NSURLErrorDomain
Error Code: -1202
Description: The certificate for this server is invalid. You might be connecting to a server that is pretending to be "XX.X.X.XX" which could put your confidential information at risk.

Metro WARN:
```
Encountered an error loading page {"canGoBack": false, "canGoForward": false, "code": -1202, "description": "The certificate for this server is invalid. You might be connecting to a server that is pretending to be “10.0.1.10” which could put your confidential information at risk.", "didFailProvisionalNavigation": true, "domain": "NSURLErrorDomain", "loading": false, "target": 7, "title": "", "url": ""}
```

**Device:**: iPhone 11 Pro, iPhone 11 Pro Max
**iOS**: 14.0
**react-native**: 0.63.2
**react-native-webview**: 10.9.0

**Comment by janelin99** [comment]
I have the same issue. but it seems to happen only when VPN is on.

**Comment by FrancisLeigh** [comment]
Happening here as well over an https server hosted with caddy + docker. 
I navigated to my caddy instance' certificates folder and installed them onto my emulator... no dice - still getting `"An SSL error has occurred and a secure connection to the server cannot be made."`
```
react: 16.13.1 => 16.13.1
react-native: 0.63.2 => 0.63.2
```

**Comment by vstanese** [comment]
Having the same issue:
 - on iOS: Domain: NSURLErrorDomain, Error Code: -1202, Description: The certificate for this server is invalid...
 - on Android: Domain: undefined, Error Code: 3, Description: SSL error: The certificate authority is not trusted
This happens when trying to load a webpage that has self-signed SSL.

**Comment by jodybrewster** [comment]
Same thing with me, when I have the VPN on it won't work at all.  Self signed server.  When I turn off the VPN it works well.

**Comment by poltak** [comment]
This is still happening. My particular case is when trying to load any site lacking a valid SSL cert via `props.source.uri`. Did anyone make any progress with this?

**Comment by ivanjzr** [comment]
Still this issue, some times work sometimes not

**Comment by GuillaumeCLProdigy** [comment]
I'm also still encountering this error. I've got a weird local setup with Charles Proxy and SSL Proxying. On iOS (where I'm testing), it seems to stem from the fact that webviews don't handle self-signed certificates in the same way as Safari.

**Comment by thecodecafe** [comment]
I'm experiencing this as well since updating to React Native 0.64.0, it works fine on Android, but getting a -1003 error code on iOS 14, don't have any other version of iOS to test with.

**Comment by arifdroid** [comment]
> I'm experiencing this as well since updating to React Native 0.64.0, it works fine on Android, but getting a -1003 error code on iOS 14, don't have any other version of iOS to test with.

hello there, do you found the solution for this issue? getting it as well

**Comment by Champkinz** [comment]
Can we re open this, alot of people are facing this issue.

**Comment by elliotmrodriguez** [comment]
Another "me too" here, iOS 14.4 simulator, happened twice in the span of a couple hours.

**Comment by Champkinz** [comment]
Hey everyone, check if the SSL is expired on the URL you are using, if so there is nothing you can do much except to include a SSL or completely remove it.

**Comment by burak4ydin** [comment]
is there any solution?

**Comment by miteshdb** [comment]
I am looking for solution as well

**Comment by arifdroid** [comment]
try check your SSL certs on you domain

**Comment by harika-nammi** [comment]
Any solution?

**Comment by tousif-p99soft** [comment]
+1

**Comment by Faradey27** [comment]
> Any solution?

We did such trick https://github.com/react-native-webview/react-native-webview/issues/1834#issuecomment-1482454783
