### ISSUE TITLE
Disable Pinch to Zoom

### ISSUE THREAD

**Issue by mog3n** [react-native-webview/react-native-webview#1649]
**Is your feature request related to a problem? If so, Please describe.**
Hi, I'm trying to create a PWA of sorts by embedding my react app within a webview. Was wondering if we could disable pinch to zoom to create a more native-feeling experience. Even with `bounce={false}`, I am still able to pinch out to zoom out on iOS/iPadOS. Thank you!

**Comment by fortydegrees** [comment]
+1

**Comment by Strate** [comment]
Just add `<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>` in your html

**Comment by BruceSuperProgramer** [comment]
Code below will disable pinch to zoom if you injected it to WebView
const jsCode =
      "let meta = document.createElement('meta'); meta.setAttribute('name', 'viewport'); meta.setAttribute('content', 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0'); document.getElementsByTagName('head')[0].appendChild(meta);";

**Comment by mirceaciu** [comment]
injection the meta props in the html pages work for the initial loaded page but won't work if you navigate to a new page of the website.

**Comment by ecemac** [comment]
> Code below will disable pinch to zoom if you injected it to WebView const jsCode = "let meta = document.createElement('meta'); meta.setAttribute('name', 'viewport'); meta.setAttribute('content', 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0'); document.getElementsByTagName('head')[0].appendChild(meta);";

Unfortunately this doesn't work for me and I'm not sure why. I haven't tested this solution and `setBuiltInZoomControls` on Android yet, but I'm definitely having problems on iOS. I'm trying to disable zooming on a payment page.

**Comment by darshitnextgen** [comment]
> Work in only Android device.

**Comment by anand-netzoptimize** [comment]
> Just add `<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>` in your html

Does not work in iOS.

**Comment by lucassacheto** [comment]
For those who are looking for this in a while, what worked for me is adding `html, body {touch-action: pan-y;}` 
Hopefully, that helps you too. Cheers

**Comment by redkean** [comment]
this works for me.
```
html,
body,
* {
  touch-action: pan-y pan-x;
}
```
