### ISSUE TITLE
Add property to prevent keyboard from showing [$100]

### ISSUE THREAD

**Issue by mikob** [react-native-webview/react-native-webview#1650]
I need a boolean prop (perhaps called autoShowKeyboard) that controls whether the keyboard appears when a user focuses an input within the webview. Sometimes I need to disable the keyboard from showing automatically, other times I need to let it show. I don't have control over the content in the webview - it can be any website.

Note: using injectJS to, for example, put a "readonly" prop on the inputs won't work because the DOM content can change dynamically at any time - eg. if the website in the webview uses React, Vue or another SPA framework.

**Comment by mikob** [comment]
I have put $100 on bounty source for this issue. https://www.bountysource.com/issues/93085569-add-property-to-prevent-keyboard-from-showing Please let me know if this is not allowed and I will remove this comment!

**Comment by sanathusk** [comment]
Should the behavior be input specific or consistent across all the input within a webview? Is it ok to have a behavior where we can either disable all the inputs or enable all of them but not selectively?

**Comment by rares-pop-sage** [comment]
I have the same problem. Any solution anyone?
