### ISSUE TITLE
react-native-webview cache not working for iOS

### ISSUE THREAD

**Issue by rsiuli001** [react-native-webview/react-native-webview#1651]
**Bug description:**
I have implemented a PWA inside react-native-webview. When i'm running the application in Android, the pages are getting cached as expected and working offline as well but when i'm running the same in iOS, its throwing error when i'm trying to use the application offline.

**To Reproduce:**
1. Embed a PWA in webview.
2. Run the application using npx react-native run-ios

**Expected behavior:**
Expectation: Like Android in iOS also, when accessing offline, the webview should display the pages from cache. 

**Screenshots/Videos:**
![Image](https://user-images.githubusercontent.com/62182948/93850904-be08d800-fccc-11ea-9e7b-2efa4f476123.jpeg)

**Environment:**
 - OS: iOS
 - OS version: 14.0
 - react-native version: 0.63.2
 - react-native-webview version: 10.8.3

**Comment by niteshsyngenta11** [comment]
I am facing the same issue :( Can someone please help us with an alternative/workaround?

**Comment by cenaHara** [comment]
hi @niteshsyngenta11  Have you solved it yet ?

**Comment by lukw34** [comment]
Hi everyone  I use the latest version of the react-native-webview and I encounter the same issues. In the app it is multiple webviews that use the same static assets. On android everything is properly cached but on ios each webview send request for the assets

**Comment by coolswood** [comment]
+1

**Comment by olive49** [comment]
+1

**Comment by jnoorul** [comment]
+1

**Comment by webgev** [comment]
+1

**Comment by hamzaawais96** [comment]
+1

**Comment by albasitum** [comment]
+1

**Comment by psbdgr8** [comment]
Hey any update on this issue?

**Comment by MarcusPOliveira** [comment]
+1
using version 13.15.0 of react-native-webview
