### ISSUE TITLE
Error loading Page (Error code -2)

### ISSUE THREAD

**Issue by royalbhati** [react-native-webview/react-native-webview#1653]
**Bug description:**

Followed the steps in description, still getting  Error code -2

**To Reproduce:**
Make a new project and follow the steps in Readme

**Expected behavior:**

Webview should work

**Screenshots/Videos:**
<img width="344" alt="Screenshot 2020-09-23 at 5 56 44 PM" src="https://user-images.githubusercontent.com/11679543/94012300-37382600-fdc6-11ea-96b8-382d38e8d4d7.png">

**Environment:**
 - OS: Android
 - OS version: 10
 - react-native version: 0.62.2
 - react-native-webview version:10.9.0

**Comment by eladwianggraini5-prog** [comment]
Masih mencari solusi
