### ISSUE TITLE
Redirect bug on android.

### ISSUE THREAD

**Issue by timboektoe** [react-native-webview/react-native-webview#1654]
**Bug description:**
On android the latest version of react-native-webview at the time of writing (10.9.0) is not able to handle redirects correctly. If you point the webview to the uri: https://mijn.uwv.nl/ it should redirect you to a login page. Also if you click the button 'DigiD inloggen' you are not properly redirected. Clicking it brings you back to the original page. 

This bug has been reported earlier [1434](https://github.com/react-native-community/react-native-webview/issues/1434) and has also been mentioned as fixed in [1525](https://github.com/react-native-community/react-native-webview/pull/1525) But unfortunately it is not fixed.

Good to know that in this case there is a situation of multiple consecutive redirects.

**To Reproduce:**
- checkout [react-native-redirect-bug](https://github.com/timboektoe/react-native-webview-redirect-bug)
- npm i
- expo start
- run on android
- click 'DigiD inloggen' button (first button)
- you are not redirected to login page. 

(You can open page in desktop browser [here](https://mijn.uwv.nl/) to see desired behaviour

**Expected behavior:**
Expected to be redirected to login page

**Screenshots/Videos:**
https://parser-prod.aqopi.com/extension/redirect-bug.mp4

**Environment:**
- Android
 - react-native version: latest (or older)
 - react-native-webview version: 10.9.0

**Comment by timboektoe** [comment]
still searching for solutions

**Comment by Balasnest** [comment]
I am also facing this exact problem

**Comment by nhan-tran-cxa** [comment]
same here

**Comment by anhkieet** [comment]
Same here

**Comment by timboektoe** [comment]
> I am also facing this exact problem only in android. Its working fine in iOS.
> 
> @timboektoe Did you manage to get it work?

The bug still exists, we managed to do a workaround for the time being by setting headers manually:
https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#props-index

We detect whether custom header should be set using onShouldStartLoadWithRequest. Something like this:
```
private _handleOnShouldStartLoadWithRequestAndroid = (event: WebViewNavigation) => {
        const { url: newURL } = event;

        // Check uwv digid login is being loaded
        if (newURL !== UWV_LOGIN_URL) return true;

        // Set state with specific referer
        this.setState({
            source: {
                uri: newURL,
                headers: {
                    Referer: UWV_LOGIN_REFERER
                }
            }
        })

        // Stop loading (instead load through source)
        return false;
    }
```

Webview source prop then binds to state.source. This only works for GET requests.

**Comment by CaoThien96** [comment]
I am also facing this exact problem only in android. Its working fine in iOS. react-native-webview version: 11.0.2

**Comment by CaoThien96** [comment]
I Have Fix by upgrade to version laster and use props 
onShouldStartLoadWithRequest={request => true}

**Comment by princefishthrower** [comment]
Interestingly, I'm seeing the browser open on iOS only 😅

**Comment by i6mi6** [comment]
Any update on this? Same issue on android

**Comment by msidqi** [comment]
same issue on "react-native-webview": "13.6.4"

**Comment by sankong42** [comment]
still searching for solutions

**Comment by msidqi** [comment]
the solution I found was to make sure the redirection url is not a protocol-relative-url. For security reasons Android webview blocks them
