### ISSUE TITLE
Universal XSS in Android WebView

### ISSUE THREAD

**Issue by gnardini** [react-native-webview/react-native-webview#1655]
**Bug description:**
Today we got a vulnerability report from npm: https://www.npmjs.com/advisories/1560

I'm only creating this issue to track progress on it, I apologize in advance if this is not the right place or way to do so.

**To Reproduce:**
Run `yarn audit`

**Expected behavior:**
No vulnerabilities found

**Environment:**
 - OS: any
 - OS version: any
 - react-native version: 0.62.2
 - react-native-webview version: 10.8.3

**Comment by cristianoccazinsp** [comment]
> Remediation:
> Ensure users update their Android WebView system component via the Google Play Store to 83.0.4103.106 or higher to avoid this UXSS. 'react-native-webview' is working on a mitigation but it could take some time.

Does this mean the library doesn't really have anything to do with the vulnerability? It is just a bug with Android that unfortunately affects react-native.

**Comment by dmythro** [comment]
I suppose here's a PR, but not merged yet so waiting for it: #1663

**Comment by win-perlego** [comment]
We have also received a warning from Github, see attached screenshot. 

Can someone provide estimate for the fix #1663 to be merged in? Thank you so much. 

![Screenshot 2020-10-05 at 17 07 13](https://user-images.githubusercontent.com/47813441/95106268-35f4ea80-0730-11eb-8021-10a23450c224.png)

**Comment by sagranatus** [comment]
please update this module... how can I use webview? is there any other option?

**Comment by amardeepranu** [comment]
Any updates here?

**Comment by luutruong** [comment]
Upgraded to 11.0.0 still have this issue.

**Comment by Raphaelinyang** [comment]
as at today, i still have this issue

**Comment by awnoa** [comment]
Still searching for solutions

**Comment by alesandroortiz** [comment]
Per security advisory, 11.0.0 has a fix: https://github.com/react-native-webview/react-native-webview/security/advisories/GHSA-36j3-xxf7-4pqg

If your tooling is still indicating 11.0.0+ is vulnerable to this particular vulnerability, that is _incorrect_. Please comment which tool you are using and I will contact the appropriate vendor to correct their data.
