### ISSUE TITLE
Local HTML Rendering just printing plain text.

### ISSUE THREAD

**Issue by Enzodtz** [react-native-webview/react-native-webview#1658]
Hi, 

I'm trying to reproduce the example of a local file rendering, but my code is not being interpreted as html, it's just being printed as a raw text.

**To Reproduce:**

I just created a simple project, with `create-react-native-app HelloWorld`, installed, and linked react-native-webview. Then, modified the app.js to the following:

```
import React, {Component} from 'react';
import {View, Text, Alert, TextInput, Button} from 'react-native';
import WebView from 'react-native-webview';
const localHtmlFile = require('./home.html');

export default class LocalPageLoad extends Component<Props, State> {
    render() {
      return (
        <View>
            <View style={{ width: '100%', height: '100%' }}>
                <WebView source={localHtmlFile}/>
          </View>
        </View>
      );
    }
  }
```
Its the same code as the repo: `example/examples/local file` with just the file `./home.htmt` changed.

Here's home.html, just if needed:

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

</head>
<body>
    Hello World!    
</body>
</html>
```
**Expected behavior:**
The screen should just print 'Hello World'.

**Result:**
The screen printed the hole html code as plain text.

**Environment:**
 - OS: Windows 10 Pro
 - OS version: 2004 
 - react-native version: 0.63.2
 - react-native-webview version: ^10.7.0

Thanks for the attention.

**Comment by smk524198002** [comment]
`const source = Platform.OS === 'ios' ? require('../../../assets/html/echart.html') : { uri: 'file:///android_asset/html/echart.html' };
`
in android studio, put html file to assets folder，also put the html file to 'src/assets/xxxx.html'

**Comment by mofengfs** [comment]
> `const source = Platform.OS === 'ios' ? require('../../../assets/html/echart.html') : { uri: 'file:///android_asset/html/echart.html' }; `
> 在android studio中，将html文件放入资产文件夹，还将html文件放入'src / assets / xxxx.html'

So, your method only works for those using android studio?

**Comment by batorshih** [comment]
> > `const source = Platform.OS === 'ios' ? require('../../../assets/html/echart.html') : { uri: 'file:///android_asset/html/echart.html' }; `
> > 在android studio中，将html文件放入资产文件夹，还将html文件放入'src / assets / xxxx.html'
> 
> So, your method only works for those using android studio?

that working <3
