### ISSUE TITLE
[Android] onShouldStartLoadWithRequest not called on first load

### ISSUE THREAD

**Issue by psavage** [react-native-webview/react-native-webview#1661]
**Bug description:**
In Android, the `onShouldStartLoadWithRequest` callback is not called the first time that `shouldOverrideUrlLoading` is called on `RNCWebViewManager`. 

This bug was introduced in #1590 because the [first `lockIdentifier` value is 0](https://github.com/appfolio/react-native-webview/blob/773a3a4318e61f79589ca53b85a026006b1891af/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java#L64), but the callback is only invoked [if `lockIdentifier` is truthy](https://github.com/appfolio/react-native-webview/blob/773a3a4318e61f79589ca53b85a026006b1891af/src/WebView.android.tsx#L286).

**Environment:**
 - OS: Android
 - OS version: 
 - react-native version: 0.63.2
 - react-native-webview version: 10.9.0

**Comment by dwxw** [comment]
We have also discovered this issue.  We were finding the webview would load a request we didn't want it to the first time.  I can confirm that #1689 fixes the issue.

However we also found that the webview can take a long time to write the lock (1.5 seconds was the worst), especially on the emulator, would we consider increasing the default from 250ms or making it configurable?
