### ISSUE TITLE
allowingReadAccessToURL iOS without file:// uri

### ISSUE THREAD

**Issue by bgold0** [react-native-webview/react-native-webview#1664]
I had a question about [allowingReadAccessToURL](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#allowingreadaccesstourl).

It states that:
> This is only used in for WebViews that are loaded with a source.uri set to a 'file://'

If I set my `source.uri`to a website like `http://127.0.0.1/page.html` and then insert a DOM element like below, would it be able to read from the file system?

    <img src="file://some/path/to/image.png" />

Is there a way to make this happen? I'm trying to inject data into the DOM from a native iOS file upload from the camera without success.

**Comment by shawndoyle** [comment]
Having the same problem!

**Comment by shawndoyle** [comment]
Here's what my code looks like:
```
<WebView
  ref={ref => (this.webview = ref)}
  source={"someSource"}
  startInLoadingState={true}
  sharedCookiesEnabled={true}
  thirdPartyCookiesEnabled={true}
  originWhitelist={['*']}
  allowFileAccessFromFileURLs={true}
  allowFileAccess={true}
  allowUniversalAccessFromFileURLs={true}
  allowingReadAccessToURL={'file://'}
/>
```

And I'm trying to update the source of an image with a `file://` uri, something like this:

```
updateImageSrc = (fileUri) => {
  this.webview?.injectJavaScript(`
    document.querySelector("#test-image").src = "${fileUri}";
    true;
  `);
}
```
