### ISSUE TITLE
Mac OS compilation error - Unknown type name 'UIRefreshControl'

### ISSUE THREAD

**Issue by kyle-ssg** [react-native-webview/react-native-webview#1666]
**Bug description:**
Compilation fails on MacOS due to the RefreshUIControl.

**To Reproduce:**
Install react-native-webview on a clean react-native mac os project.

**Expected behavior:**

Compilation passes.

**Screenshots/Videos:**

![image](https://user-images.githubusercontent.com/8608314/94665785-828d8f80-0304-11eb-916f-bf7273ddcc7b.png)

**Environment:**
 - OS: Mac
 - OS version: 10.15.5
 - react-native version: 0.62.0
 - react-native-webview version: 10.9.1

**Comment by TheAlmightyBob** [comment]
https://github.com/react-native-webview/react-native-webview/pull/1636 should address this
