### ISSUE TITLE
webview not working on android version 4.x

### ISSUE THREAD

**Issue by mromid** [react-native-webview/react-native-webview#1667]
i try open a url in my webview , but going to this message >> webpage not available 

**Screenshots/Videos:**
![Screenshot 2020-09-30 133039](https://user-images.githubusercontent.com/22810402/94671870-4f0d2e00-0321-11eb-80b1-719e906f6fd3.png)

**Environment:**
 - OS: win
 - OS version: 10
 - react-native version: 0.62.2
 - react-native-webview version:10.9.1

**Comment by progfrosty** [comment]
Crashes for me on 4.x as well. 5.x is fine.
