### ISSUE TITLE
Render body regardless of http status code

### ISSUE THREAD

**Issue by pavelserbajlo** [react-native-webview/react-native-webview#1669]
**Bug description:**
When e.g. a 404 page is returned from the server, `onHttpError` event is triggered, but body of such response is not rendered. How can I ignore any such http error and let the webview render whatever the server wants to display as additional information to the status code? Pretty much like any other browser would do.

**To Reproduce:**
Try to load any page that returns e.g. 404 http status code.

**Expected behavior:**
Page to be loaded regardless of http status code.

**Environment:**
 - react-native version: 0.63.0
 - react-native-webview version: 10.8.2

**EDIT:**
After some further testing, the issue is not related to the http status code. The problem simply is that react-native-webview is unable to render my CRA app served from S3 via CloudFront. It can load the same page from my DEV machine, though. It can also load different pages without issues (e.g. `google.com`). I added listeners to pretty much every event react-native-webview offers, but I'm not seeing any errors or other pointers. The loaded page simply won't render, even though it loads. The same page also renders on iOS Safari without issue. Any pointers on how to debug this issue would be appreciated!

**Comment by ehtisham-ali-emumba** [comment]
Any update here, why page is not getting rendered in my case status code is 401?

**Comment by ehtisham-ali-emumba** [comment]
@pavelserbajlo any update on this?
