### ISSUE TITLE
Initial Webview load very slow, can we pre-cache?

### ISSUE THREAD

**Issue by jojofeng** [react-native-webview/react-native-webview#1670]
**Is your feature request related to a problem? If so, Please describe.**

Recently, on `10.9.0`, I've noticed that our Webview loads very slowly (on the order of ~8 seconds, when hitting a localhost address from my iOS simulator). This didn't seem to be a problem in the past, and neither the content we are loading nor our Webview component usage have changed. Is it possible there has been a regression? I have noticed that subsequent loads seem to be much faster (~1-2 seconds), which makes me think that the caching behavior is very helpful for performance.

**Describe the solutions you came up with**

I was wondering if you had any other solutions off the top of your head that might help performance. Alternatively, would it be possible to pre-cache/pre-load the page content before the Webview is rendered, so on initial render it could render from a cache and our users wouldn't have to wait 10 seconds for load? I would like to avoid doing something like rendering an invisible Webview on app load and displaying it when needed.

**Additional context**

Please let me know if there's any other information that might be helpful. Thanks!

**Comment by Balasnest** [comment]
Yeah. Me too facing the same. It's very slow for first time.

**Comment by Liqiankun** [comment]
```js
 <WebView cacheEnabled={false} />
``` 
This works for me.

**Comment by Dor256** [comment]
A prefetching mechanism would be a very good solution here.
Currently the only workaround that significantly improved performance was to render an invisible WebView sometime before rendering the actual WebView but this is rather nasty.

**Comment by jojofeng** [comment]
As an update, I implemented an invisible WebView that renders on app load, and is unrendered after it finishes loading. I don't like the solution (and have not committed it yet) but it seems to be working. Code looks something like this:

`{!loaded && <WebView  {...someProps} onLoad={() => { setLoaded(true); } />}`

Where `loaded` is some boolean state variable that is initialized to `false` (and thus allows the WebView to be rendered) and once the WebView has loaded (and the content has been cached) `loaded` is set to `true`, which removes the WebView from the page. I added some styling to my WebView component that makes the height 0 and (to be extra safe) makes the `opacity: 0`.

**Comment by jojofeng** [comment]
cc @Titozzz @jamonholmgren @alloy @TheAlmightyBob 

any thoughts here??

**Comment by haduy97** [comment]
> As an update, I implemented an invisible WebView that renders on app load, and is unrendered after it finishes loading. I don't like the solution (and have not committed it yet) but it seems to be working. Code looks something like this:
> 
> `{!loaded && <WebView {...someProps} onLoad={() => { setLoaded(true); } />}`
> 
> Where `loaded` is some boolean state variable that is initialized to `false` (and thus allows the WebView to be rendered) and once the WebView has loaded (and the content has been cached) `loaded` is set to `true`, which removes the WebView from the page. I added some styling to my WebView component that makes the height 0 and (to be extra safe) makes the `opacity: 0`.

Can you explain for more details or show how you work with code please ?

**Comment by alloy** [comment]
Sorry, I have no current insights on this. The one [rhetoric] question I would have is, do you have this problem on device too or only on the simulator? As the simulator cannot always be trusted for performance issues.

**Comment by Dor256** [comment]
> Sorry, I have no current insights on this. The one [rhetoric] question I would have is, do you have this problem on device too or only on the simulator? As the simulator cannot always be trusted for performance issues.

Experiencing this on device as well

**Comment by TheAlmightyBob** [comment]
I also have no insights and we have not experienced any such delays. Is this only iOS? Do you remember what the last version you were using was that didn't seem to have this problem?

Is it only the first load _in general_ that's slow, or the first load _of a specific site_? i.e., if you were to load google.com and then bing.com, would bing still be a "first load" and thus slow?

**Comment by Dor256** [comment]
> I also have no insights and we have not experienced any such delays. Is this only iOS? Do you remember what the last version you were using was that didn't seem to have this problem?
> 
> Is it only the first load _in general_ that's slow, or the first load _of a specific site_? i.e., if you were to load google.com and then bing.com, would bing still be a "first load" and thus slow?

Hey, I haven't actually tested that scenario but I'll try it and come back with results, however the initial load with the same site is marginally slower.

Another important note, some guys in our team temporarily downgraded to version `7.1.1` but it seems this issue was raised before the downgrade. In any case I'll check after we're back up to the latest version and also check the loading time with two different sites as you mentioned and report back.

**Comment by Balasnest** [comment]
In my current version **5.9.1**, Initial page loading is **much better** than the latest version. I am using 75% webview in my application. Especially the payment page. I don't want users to **hold ~ 8 sec** for the initial load.

**Comment by adimshev** [comment]
+1

**Comment by scchess** [comment]
+1 any solutions? In native Objective-C, the solution would to create an instance of `WKWebView` in `didFinishLaunchingWithOptions`. Initalize it but don't show it until needed.

We can't do this in React Native.

**Comment by walfly** [comment]
+1

**Comment by adimshev** [comment]
+1

**Comment by tatiang** [comment]
Curious how the web viewer loading time can be improved...

**Comment by TheAlmightyBob** [comment]
It would be helpful if somebody could share a sample app (e.g. via Expo Snack) that demonstrates this issue.

**Comment by fungmo** [comment]
+1

**Comment by Hirurgo** [comment]
+3

**Comment by coolswood** [comment]
+1

**Comment by olive49** [comment]
+1

**Comment by TaniaAG** [comment]
+1

**Comment by abdullahbayram** [comment]
+1

**Comment by chaudev** [comment]
I had this problem when the **website had sound**. Webview has **stopped** and wait for the audio to finish loading.

**Comment by Ibrahimkara92** [comment]
+1

**Comment by jorcus** [comment]
+1

**Comment by luluanacarla** [comment]
+1

**Comment by gabrielmirandat** [comment]
+1

**Comment by Michelalmeidasilva** [comment]
+1

**Comment by gtfunes** [comment]
+1

**Comment by huynguyen3tiki** [comment]
+1 
in-browser, the bundle will be loaded from cache.
and it's not in React Native Web View.
![image](https://user-images.githubusercontent.com/48898161/131316740-956f7633-e100-45c4-8908-72fe8c281d6b.png)

**Comment by ecauende** [comment]
+1

**Comment by Hamza-Ali333** [comment]
i m facing the same issue. Is anyone found the solution for that.? Please Share if yes

**Comment by diegoconcha** [comment]
I'm also facing the same issue. Can this be reopened?

**Comment by Hamza-Ali333** [comment]
> Yeah. Me too facing the same. It's very slow for first time.

Agreed

**Comment by ashishAmz** [comment]
Yes, facing issue on First Load.

**Comment by showtan001** [comment]
+1

**Comment by enter3017sky** [comment]
+1

**Comment by nakapon9517** [comment]
+1
It would be helpful if it is possible to preload with a process like this instead of loading after the screen is rendered.
```
webviewRef.current.preload(url)
```

**Comment by JohnRyanTsai** [comment]
Any solutions?

**Comment by hejun041** [comment]
+1

**Comment by oottoohh** [comment]
up

**Comment by rohitk1979** [comment]
Still facing the same problem. WebView appreciably slow on first load but faster thereafter.

**Comment by Aikenwu** [comment]
> Still facing the same problem. WebView appreciably slow on first load but faster thereafter.


If your first page is a native page, then it is recommended to initialize an empty webview and give it a URL to actually load, which is equivalent to initializing the webview. In this way, the subsequent webviews will open much faster. Be careful not to initialize multiple times, you can use react memo.
If your first page happens to be a webview page, then it's over. I also face such a problem. This is a double-edged sword. If you initialize it in advance, the app will be stuck on the startup page. If you don't initialize it in advance, the app will be stuck on the home page.

**Comment by zereight** [comment]
up

**Comment by saxenanickk** [comment]
Try using the following approach.

#### `WebView` page is the first screen
- Show Splash
- Create another screen similar to Splash on JS side and show a progress bar or any animation kind of UI until the page is loaded. You can get this using `onLoadEnd` callback of `WebView`
- Hide the animation UI and you're good to go

#### React Native screen is the first screen?
- Show Splash
- Create another screen similar to Splash on JS side and show a progress bar or any animation kind of UI until the page is loaded. You can get this using `onLoadEnd` callback of `WebView`
- Hide the animation UI and navigate back to React Native Screen
- You're good to go

---
I hope we get some proper solutions from the library maintainers soon.

**Comment by joumanam** [comment]
6 years later and this is still a problem! Did anyone find an actual legit solution?

**Comment by mpadel78** [comment]
> 6 years later and this is still a problem! Did anyone find an actual legit solution?

same issue. I wonder what native devs solve this issue with their webview. Maybe we can port some of that in this package.
