### ISSUE TITLE
Error running "pod install" on MacOS

### ISSUE THREAD

**Issue by qmatteoq** [react-native-webview/react-native-webview#1671]
**Bug description:**

I'm trying to install the react-native-webview module on a React Native project for MacOS, based on version 0.62.
When I run "pod install" to perform the auto-linking, however, the operation fails with the following error:

```
[!] CocoaPods could not find compatible versions for pod "react-native-webview":
  In Podfile:
    react-native-webview (from `../node_modules/react-native-webview`)

Specs satisfying the `react-native-webview (from `../node_modules/react-native-webview`)` dependency were found, but they required a higher minimum deployment target.
```

**To Reproduce:**

1) Add support for MacOS to a React Native 0.62 project, following [the steps here](https://microsoft.github.io/react-native-windows/docs/0.62/rnm-getting-started).
2) Run the following command to add react-native-webview:

```
yarn add react-native-webview
```

3) Move to the macos folder
4) Run the following command to perform the autolinking:

```
pod install
```

**Expected behavior:**

The autolinking operation completes succesfully.

**Environment:**
 - OS: MacOS
 - OS version: 10.15.7
 - react-native version: ^0.62.0-0
 - react-native-webview version: ^10.9.1"

**Comment by alloy** [comment]
@qmatteoq Looks like the issue is that the `react-native-webview` podspec still states the minimum macOS deployment target being `10.14`, whereas we adjusted RN macOS’ minimum deployment target to `10.13`: https://github.com/react-native-webview/react-native-webview/blob/2d2413191003477ca55433e037ab491b46be53f1/react-native-webview.podspec#L13

Can you send a PR that downgrades it to 10.13?

**Comment by LionelHoudelier** [comment]
I confirm the solution in nodes-modules/react-native-webview/react-native-webview.podspec: `s.platforms    = { :ios => "9.0", :osx => "10.14" }` replaced by: `s.platforms    = { :ios => "9.0", :osx => "10.13" }`
