### ISSUE TITLE
Camera for iOS is not working in inside webview

### ISSUE THREAD

**Issue by berajesh** [react-native-webview/react-native-webview#1672]
I tried to access the iOS camera within webview. but it's not working as expected. It's working fine in the Safari browser in iOS, Chrome browser in Android, and android webview. However, nothing happens inside webview in iOS. I granted required permissions like camera or audio, however, it still does not work.

**Comment by mjurkowski** [comment]
The same issue

**Comment by SimonBellucci** [comment]
On iOS-Devices camera access works only in native Safari and not in other Browsers (Chrome,...) or Apps that use an `UIWebView` or `WKWebView`. This is not a restriction of this component but of the limited WebRTC support by Apple.

This is still not resolved on iOS 14, if you want to stay updated on this topic, please refer to [this](https://bugs.webkit.org/show_bug.cgi?id=208667) thread.

**Comment by sathwik77** [comment]
@SimonBellucci So we don't have access to `getUserMedia` in Web View, but why does the docs say we can use `NSCameraUsageDescription` ? I was just wondering is there a way to open camera in IOS in web view?
![Screen Shot 2563-11-30 at 17 07 28](https://user-images.githubusercontent.com/26072324/100596511-d3cef500-332e-11eb-9024-eeaf3ac716c2.png)

**Comment by MarwaAbuEssa** [comment]
the same issue here

**Comment by jayan2019** [comment]
iOS 14.3 Supported

 https://developer.apple.com/forums/thread/88052

Hope this will help!

**Comment by wahaj-47** [comment]
https://user-images.githubusercontent.com/8758774/107483768-567ff600-6ba3-11eb-95e5-fd826340f9ab.mp4

For me the camera opens up if I pass in the prop mediaPlaybackRequiresUserAction={false}. However the webview treats it like a live broadcast and I end up with nothing but a black screen. The camera is still open in the background so if you point it to a QR code, it scans it.

**Comment by Zain228** [comment]
> 
> Attachment_1612945361.mp4
> 
> For me the camera opens up if I pass in the prop mediaPlaybackRequiresUserAction={false}. However the webview treats it like a live broadcast and I end up with nothing but a black screen. The camera is still open in the background so if you point it to a QR code, it scans it.
> 
> Edit: Adding the prop allowsInlineMediaPlayback and removing the mediaPlaybackRequiresUserAction prop seems to have fixed it.

Can you please show the code because i am doing all the things but not working

**Comment by wahaj-47** [comment]
> > Attachment_1612945361.mp4
> > For me the camera opens up if I pass in the prop mediaPlaybackRequiresUserAction={false}. However the webview treats it like a live broadcast and I end up with nothing but a black screen. The camera is still open in the background so if you point it to a QR code, it scans it.
> > Edit: Adding the prop allowsInlineMediaPlayback and removing the mediaPlaybackRequiresUserAction prop seems to have fixed it.
> 
> Can you please show the code because i am doing all the things but not working

Just add the props 
```
allowInlineMediaPlayback={true}
mediaPlaybackRequiresUserAction={false}
```
On iOS it doesn't work on older iOS versions so I just listen to URL change events and open up a scanner using react-native-barcode-scanner on the correct URL.

**Comment by Zain228** [comment]
> 
> 
> > > Attachment_1612945361.mp4
> > > For me the camera opens up if I pass in the prop mediaPlaybackRequiresUserAction={false}. However the webview treats it like a live broadcast and I end up with nothing but a black screen. The camera is still open in the background so if you point it to a QR code, it scans it.
> > > Edit: Adding the prop allowsInlineMediaPlayback and removing the mediaPlaybackRequiresUserAction prop seems to have fixed it.
> > 
> > 
> > Can you please show the code because i am doing all the things but not working
> 
> Just add the props
> 
> ```
> allowInlineMediaPlayback={true}
> mediaPlaybackRequiresUserAction={false}
> ```
> 
> On iOS it doesn't work on older iOS versions so I just listen to URL change events and open up a scanner using react-native-barcode-scanner on the correct URL.

Okay then how you send scanned data to web?

**Comment by anhvoduy** [comment]
Camera does not work as simple Web View for IOS, please help:

<img width="331" alt="Screen Shot 2021-06-17 at 12 59 05 AM" src="https://user-images.githubusercontent.com/21326032/122269400-5bfd9c00-cf07-11eb-9112-588e63e7ee77.png">

**Comment by HerickRaposo** [comment]
> > > Attachment_1612945361.mp4
> > > For me the camera opens up if I pass in the prop mediaPlaybackRequiresUserAction={false}. However the webview treats it like a live broadcast and I end up with nothing but a black screen. The camera is still open in the background so if you point it to a QR code, it scans it.
> > > Edit: Adding the prop allowsInlineMediaPlayback and removing the mediaPlaybackRequiresUserAction prop seems to have fixed it.
> > 
> > 
> > Can you please show the code because i am doing all the things but not working
> 
> Just add the props
> 
> ```
> allowInlineMediaPlayback={true}
> mediaPlaybackRequiresUserAction={false}
> ```
> 
> On iOS it doesn't work on older iOS versions so I just listen to URL change events and open up a scanner using react-native-barcode-scanner on the correct URL.

Could you display  how to do this for us? Please i need to do this in two times during execution webview, one time with QR scanner and other with barcode scanner. Please helpme.

**Comment by HerickRaposo** [comment]
Dont work here too. IOS 14

**Comment by jorgediegocrespo** [comment]
Hello.
I need to show the camera within a web but, using the WKWebView configuration that you mention, a modal view is opened with the camera.

Any solution for this problem?
Thank you.

**Comment by anhvoduy** [comment]
![image](https://user-images.githubusercontent.com/21326032/125965299-de06ab2b-5e49-4210-8440-2784738e9fd5.png)

hey guys, finally it works fine in IOS >= 14.6

**Comment by wahaj-47** [comment]
> ![image](https://user-images.githubusercontent.com/21326032/125965299-de06ab2b-5e49-4210-8440-2784738e9fd5.png)
> 
> hey guys, finally it works fine in IOS >= 14.6

What about the previous iOS versions? Is there a workaround?

**Comment by wmaca** [comment]
We are currently facing a similar problem, but not quite the same as the one reported here.

With `allowInlineMediaPlayback` enabled and `mediaPlaybackRequiresUserAction` disabled (this one was a problem on Android), after we ask for camera access on iOS, the camera simply does not load.

After we restart the app, the user is prompted with the webview's request to access the camera (not the SO one, but the one the browser does). And it works.

We would like to know why we need to restart the app in order to work.

**Comment by wmaca** [comment]
hi, @anhvoduy. It is on iOS only. But the camera works after the app is restarted.

I've created a [new issue](https://github.com/react-native-webview/react-native-webview/issues/2131), as it seems to be working properly after the reset, which was not the case here.

To Reproduce:

1. Render the webview.
2. Send a postMessage to ask native code to request camera permission.
3. Grant permission.
4. Webview's getMediaDevices() fail.

Here is the configuration: 

![image](https://user-images.githubusercontent.com/3537591/129066883-738a17b3-5525-4bc5-91ec-88d932df2c0b.png)

**Comment by eslambasher** [comment]
Up, does anyone have a solution please?

**Comment by nx** [comment]
> My use case is described on the linked issue. It happens when you grant the app level permission with the webview already created. The webview is unable to even access the list of media devices.

Thanks for clarifying, I understand now. That's indeed different form what I'm trying to do. I hope you'll find a solution and the issue gets resolved.

**Comment by muskan6898** [comment]
> ![image](https://user-images.githubusercontent.com/21326032/125965299-de06ab2b-5e49-4210-8440-2784738e9fd5.png)
> 
> hey guys, finally it works fine in IOS >= 14.6

Worked for me, thanks

**Comment by saranya-Godigit** [comment]
@muskan6898  I am facing the same issue in Andriod 
I had given permission as well before calling and I am getting error as getusermedia error not readable error

    "react-native-webview": "13.2.2",
    
    
    <WebView onLoadStart={()=>{console.log("Start")}}
  userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36" 
  source={{      
       uri: '', 

   }} 
  originWhitelist={['*']} 
  sharedCookiesEnabled={true}
  allowsInlineMediaPlayback 
  javaScriptEnabled 
  scalesPageToFit 
  allowInlineMediaPlayback={true}
   mediaPlaybackRequiresUserAction={false} 
   bounces={true}
   startInLoadingState
    javaScriptEnabledAndroid
     geolocationEnabled={true} 
     useWebkit 
     />
