### ISSUE TITLE
Webpage of Webview not rendered on macos (compatibiliy problem with macos Mojave 10.14.6)

### ISSUE THREAD

**Issue by LionelHoudelier** [react-native-webview/react-native-webview#1675]
Hi,
My webview works fine on each platform (android, web, ios, windows) but not on macos. 
The webview stays white with no content of the webpage. Although, functions onNavigationStateChange work and display the console.logs when the url changes for example.

**Environment:**
 - OS: macos
 - OS version: 10.14.6
 - react-native version: tried 62.0 or 62.2
 - react-native-webview version: tried with 10.0.0 or 10.9.2
- Ruby: 2.6.6
- XCode: 11.3.1

Does anyone have the same issue??

**Comment by valerius21** [comment]
Nope. How can I reproduce the bug? What site do you try to render?

**Comment by LionelHoudelier** [comment]
Thanks for your questions.
No site works. 
To reproduce:
- create a new test app (RN 0.62.2) via : `npm react-ult <testAppName>` (creates a basic RN app + windows and web implementations through reactxp framework) then
- install react-native-webview and a Webview in the starting view
- downgrade target platform in nodes-modules/react-native-webview/react-native-webview.podspec: s.platforms = { :ios => "9.0", :osx => "10.14" } replaced by: s.platforms = { :ios => "9.0", :osx => "10.13" } (otherwise `pod install` fails)
- tests with ios, windows, android (all OK for me)
- install requirements for react-native-macos on: https://microsoft.github.io/react-native-windows/docs/0.62/rnm-dependencies then
- install macos: `npx react-native-macos-init` following: https://microsoft.github.io/react-native-windows/docs/0.62/rnm-getting-started

Can the Ruby version be the problem. I've had to update it on my machine before installing the requirements for macos version?

**Comment by LionelHoudelier** [comment]
I precise: the webview is "displayed" but the screen remains blank with the apple spinning loading wheel. Just styles can be rendered (margin...etc). I tried a lot of changes but the problem looks to be in native side because javascript side works fine. It means React Native receives the connection answer (token, etc.). Just the rendering is not working.
Here my xcode log at reloading the view with the webview trying to render:

> 2020-10-07 14:11:32.651 [info][tid:main][RCTCxxBridge.mm:1099] Invalidating <RCTCxxBridge: 0x105f10de0> (parent: <RCTBridge: 0x600002901ea0>, executor: (null))
2020-10-07 14:11:33.440 [warn][tid:com.facebook.react.JavaScript][RCTModuleData.mm:290] RCTBridge required dispatch_sync to load RCTDevSettings. This may lead to deadlocks
2020-10-07 14:11:34.947711+0200 v0[25753:534838] [] nw_socket_handle_socket_event [C22:1] Socket SO_ERROR [61: Connection refused]
2020-10-07 14:11:34.949662+0200 v0[25753:553693] [] nw_connection_get_connected_socket [C22] Client called nw_connection_get_connected_socket on unconnected nw_connection
2020-10-07 14:11:34.949763+0200 v0[25753:553693] TCP Conn 0x600003728b40 Failed : error 0:61 [61]
2020-10-07 14:11:35.018 [warn][tid:com.facebook.react.JavaScript] Require cycle: node_modules/react-ult/dist/native-common/Animated.js -> node_modules/react-ult/dist/native-common/View.js -> node_modules/react-ult/dist/native-common/Animated.js

> Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
> 2020-10-07 14:11:35.022 [warn][tid:com.facebook.react.JavaScript] Require cycle: node_modules/react-ult/dist/native-common/App.js -> node_modules/react-ult/dist/native-common/RootView.js -> node_modules/react-ult/dist/native-common/App.js
> 
> Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
> 2020-10-07 14:11:35.147 [info][tid:main][RCTRootView.m:368] Running application v0 ({
>     initialProps =     {
>     };
>     rootTag = 31;
> })
> 2020-10-07 14:11:35.151 [warn][tid:com.facebook.react.JavaScript] RCTBridge required dispatch_sync to load RCTDevSettings. This may lead to deadlocks
> 2020-10-07 14:11:35.158 [info][tid:com.facebook.react.JavaScript] Running "v0" with {"rootTag":31,"initialProps":{}}
> 2020-10-07 14:11:37.123124+0200 v0[25753:503447] -[NSHTTPURLResponse valueForHTTPHeaderField:]: unrecognized selector sent to instance 0x60000028d5c0
> 2020-10-07 14:11:37.133764+0200 v0[25753:503447] [General] -[NSHTTPURLResponse valueForHTTPHeaderField:]: unrecognized selector sent to instance 0x60000028d5c0
> 2020-10-07 14:11:39.297839+0200 v0[25753:503447] [General] (
> 	0   CoreFoundation                      0x00007fff3eff8b79 __exceptionPreprocess + 256
> 	1   libobjc.A.dylib                     0x00007fff697913c6 objc_exception_throw + 48
> 	2   CoreFoundation                      0x00007fff3f07327b -[NSObject(NSObject) __retain_OA] + 0
> 	3   CoreFoundation                      0x00007fff3ef9a658 ___forwarding___ + 1478
> 	4   CoreFoundation                      0x00007fff3ef9a008 _CF_forwarding_prep_0 + 120
> 	5   v0                                  0x00000001003e5265 -[RNCWebView webView:decidePolicyForNavigationResponse:decisionHandler:] + 869
> 	6   WebKit                              0x00007fff4d7fd792 _ZN6WebKit15NavigationState16NavigationClient33decidePolicyForNavigationResponseERNS_12WebPageProxyEON3WTF3RefIN3API18NavigationResponseENS4_13DumbPtrTraitsIS7_EEEEONS5_INS_27WebFramePolicyListenerProxyENS8_ISC_EEEEPNS6_6ObjectE + 388
> 	7   WebKit                              0x00007fff4d87149a _ZN6WebKit12WebPageProxy29decidePolicyForResponseSharedEON3WTF3RefINS_15WebProcessProxyENS1_13DumbPtrTraitsIS3_EEEEyRKN7WebCore18SecurityOriginDataENS8_21PolicyCheckIdentifierEyRKNS8_16ResourceResponseERKNS8_15ResourceRequestEbyRKNS_8UserDataE + 738
> 	8   WebKit                              0x00007fff4d871186 _ZN6WebKit12WebPageProxy23decidePolicyForResponseEyRKN7WebCore18SecurityOriginDataENS1_21PolicyCheckIdentifierEyRKNS1_16ResourceResponseERKNS1_15ResourceRequestEbyRKNS_8UserDataE + 94
> 	9   WebKit                              0x00007fff4da5bb61 _ZN3IPC22callMemberFunctionImplIN6WebKit12WebPageProxyEMS2_FvyRKN7WebCore18SecurityOriginDataENS3_21PolicyCheckIdentifierEyRKNS3_16ResourceResponseERKNS3_15ResourceRequestEbyRKNS1_8UserDataEENSt3__15tupleIJyS4_S7_yS8_SB_bySE_EEEJLm0ELm1ELm2ELm3ELm4ELm5ELm6ELm7ELm8EEEEvPT_T0_OT1_NSJ_16integer_sequenceImJXspT2_EEEE + 92
> 	10  WebKit                              0x00007fff4da560b6 _ZN3IPC13handleMessageIN8Messages12WebPageProxy23DecidePolicyForResponseEN6WebKit12WebPageProxyEMS5_FvyRKN7WebCore18SecurityOriginDataENS6_21PolicyCheckIdentifierEyRKNS6_16ResourceResponseERKNS6_15ResourceRequestEbyRKNS4_8UserDataEEEEvRNS_7DecoderEPT0_T1_ + 102
> 	11  WebKit                              0x00007fff4d6ba504 _ZN3IPC18MessageReceiverMap15dispatchMessageERNS_10ConnectionERNS_7DecoderE + 126
> 	12  WebKit                              0x00007fff4d891720 _ZN6WebKit15WebProcessProxy17didReceiveMessageERN3IPC10ConnectionERNS1_7DecoderE + 24
> 	13  WebKit                              0x00007fff4d6ac088 _ZN3IPC10Connection15dispatchMessageENSt3__110unique_ptrINS_7DecoderENS1_14default_deleteIS3_EEEE + 108
> 	14  WebKit                              0x00007fff4d6aecdd _ZN3IPC10Connection24dispatchIncomingMessagesEv + 717
> 	15  JavaScriptCore                      0x00007fff423f7454 _ZN3WTF7RunLoop11performWorkEv + 228
> 	16  JavaScriptCore                      0x00007fff423f76e2 _ZN3WTF7RunLoop11performWorkEPv + 34
> 	17  CoreFoundation                      0x00007fff3ef5eadb __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
> 	18  CoreFoundation                      0x00007fff3ef5ea81 __CFRunLoopDoSource0 + 108
> 	19  CoreFoundation                      0x00007fff3ef4298b __CFRunLoopDoSources0 + 195
> 	20  CoreFoundation                      0x00007fff3ef41f53 __CFRunLoopRun + 1196
> 	21  CoreFoundation                      0x00007fff3ef41855 CFRunLoopRunSpecific + 459
> 	22  HIToolbox                           0x00007fff3e1921ab RunCurrentEventLoopInMode + 292
> 	23  HIToolbox                           0x00007fff3e191ee5 ReceiveNextEventCommon + 603
> 	24  HIToolbox                           0x00007fff3e191c76 _BlockUntilNextEventMatchingListInModeWithFilter + 64
> 	25  AppKit                              0x00007fff3c52a77d _DPSNextEvent + 1135
> 	26  AppKit                              0x00007fff3c52946b -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1361
> 	27  AppKit                              0x00007fff3c523588 -[NSApplication run] + 699
> 	28  AppKit                              0x00007fff3c512ac8 NSApplicationMain + 777
> 	29  v0                                  0x0000000100001842 main + 34
> 	30  libdyld.dylib                       0x00007fff6af563d5 start + 1
> 	31  ???                                 0x0000000000000003 0x0 + 3

**Comment by LionelHoudelier** [comment]
I published my test repo here: https://github.com/LionelHoudelier/test

**Comment by LionelHoudelier** [comment]
Actually now solved after MacOS update to 10.15.
