### ISSUE TITLE
error when run-android

### ISSUE THREAD

**Issue by ahmadpy888** [react-native-webview/react-native-webview#1676]
hi, i use

"react": "16.13.1",
"react-native": "0.63.2",
"react-native-render-html": "^4.2.4",
"react-native-webview": "^10.2.3",

app/build.gradle -> multiDexEnabled true

error when run-android

`[Tue Oct 06 2020 17:35:07.236]  ERROR    Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
[Tue Oct 06 2020 17:35:07.237]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
[Tue Oct 06 2020 17:35:07.238]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)`

**Comment by sourabhsainii** [comment]
Hii, @ahmadpy888 i'm also facing the same issue.Can you tell me if you were able to fix this error?
