### ISSUE TITLE
feat(android): Dark mode

### ISSUE THREAD

**Issue by Gregoirevda** [react-native-webview/react-native-webview#1677]
**Is your feature request related to a problem? If so, Please describe.**
Android doesn't support dark-theme media query

**Describe the solutions you came up with**
Bridge the interface in Android to set the dark mode
```
if(WebViewFeature.isFeatureSupported(WebViewFeature.FORCE_DARK)) {
    WebSettingsCompat.setForceDark(myWebView.getSettings(), WebSettingsCompat.FORCE_DARK_ON);
}
```

**Comment by vascofg** [comment]
+1

**Comment by jonhassall** [comment]
+1

**Comment by idlework** [comment]
+1

**Comment by velijv** [comment]
+1

**Comment by 925360166** [comment]
+1

**Comment by dapicester** [comment]
@925360166 @velijv @idlework @jonhassall @vascofg @Gregoirevda I see that there is a PR for this #2063.
Let's upvote on that!
