### ISSUE TITLE
[QUESTION] Why is there a performance gap between "regular" browser and react-native-webview?

### ISSUE THREAD

**Issue by exotexot** [react-native-webview/react-native-webview#1681]
Hello,

Can someone explain what the fundamental differences, between a conventional “browser” (e.g. Safari) and the browser component of react-native-webview? If I understand correctly, the both - in the case of iOS - are based on WKWebKit, which mean they should share a large part of their functionalities and also performance limits. How come though, that the performance of the react-native-webview perform so much worse than “normal” Safari? 

In my project I’m running https://www.pdftron.com/webviewer/demo/ through react-native-webview and it performs inferior compared to running it on Safari directly. Note: I’m using Catalyst to run my ios react native project on macOS. I had to learn the hard way that there are bugs such as: https://bugs.webkit.org/show_bug.cgi?id=195325 and that there is a memory limit of roughly 250mb.

Are there any known measures one can take to enhance the react-native-webview performance? If so which ones and how to change? If not, why is this the case? Where are the fundamental differences and how are they being reasoned?

**Comment by frankbolviken** [comment]
I guess you got the answer when nobody replied :O

**Comment by exotexot** [comment]
Well, not really.
As mentioned: I learned that there are severe constraints in terms of available memory to the browser.
And in the case of Windows, the react-native-webview component used an archaic html rendering engine, which will be replaced WebView2, which uses a Chromium based engine under the hood, with state of the art js/html rendering performance.

Yet, I guess that there are still performance constraints that I'm not aware of.
