### ISSUE TITLE
Problem with iOS redirection

### ISSUE THREAD

**Issue by SEdilson** [react-native-webview/react-native-webview#1682]
**Bug description:**
The expected redirect is not being done with iOS devices, with Android all the steps are followed correctly but with iOS some times it is either not parsing the params correctly or it is simply ignoring them.

**Expected behavior:**
Redirect to the routes configured.

**Environment:**
 - react-native version: 0.63
 - react-native-webview version: 10.3.3

**Comment by Kunalpaul12** [comment]
Can you please share the solution with us @edilson

**Comment by edilson** [comment]
@Kunalpaul12 unfortunately I couldn't find one with this lib. Had to switch to another one.

**Comment by fabriciosautner** [comment]
same problem
