### ISSUE TITLE
Android 11 not working borderRadius.

### ISSUE THREAD

**Issue by 345ml** [react-native-webview/react-native-webview#1687]
**Bug description:**

This appears to be a weird rendering bug.
I've surrounded the webview with a View with the following style to give it some rounding.
````
borderRadius: 10,
overflow: 'hidden'
````

And if you remove the borderRadius style, this works fine.
The problem doesn't reproduce on Android 10 and seems to be an issue that occurs on Android 11.

This also happens with production apps installed from the Play Store.

**To Reproduce:**

A code like this
```js
<View style={{ borderRadius: 10, overflow: 'hidden' }}>
  <WebView />
</View>
```

**Screenshots/Videos:**

No borderRadius
![ezgif-6-fcc53d0e551b](https://user-images.githubusercontent.com/8254811/95569426-6c559280-09da-11eb-8f52-f82b75ac8e69.gif)

Add borderRadius
![ezgif-6-661bec1d2432](https://user-images.githubusercontent.com/8254811/95570086-45e42700-09db-11eb-9a37-6da4deabe3a9.gif)

**Environment:**
 - OS: macOS
 - OS version: 10.15.6
 - react-native version: 0.61.5
 - react-native-webview version: 8.0.1 (and try 10.9.2)

**Comment by 345ml** [comment]
I checked today and this issue does not appear to be occurring during debugging.

However, I think it was occurring yesterday.
Because I did a borderRadius test.

Very strange.

**Comment by backmeupplz** [comment]
Same here. Any chance there are workarounds?

**Comment by caojianfeng** [comment]
+1

**Comment by caojianfeng** [comment]
I had resolve this by adding containerStyle
<WebView 
containerStyle={{borderRadius: 10}
..../>
