### ISSUE TITLE
Sending to web view not working

### ISSUE THREAD

**Issue by LuciferLat** [react-native-webview/react-native-webview#1688]
**Bug description:**
I'm trying to send string from react native to webView with help of ref like this: 
**this.webViewRef.postMessage('send to webView')**
At react side i'm listening with in didMount
document/window.addEventListener("message", function (event) {
    console.log('Check event listening data::', event.data);
});
i can't able to receive/listen in react web view when i send, but with empty payload it returns when didMount.

Checking with iOS simulator.

**To Reproduce:**
this.webViewRef.postMessage('send to webView')
 <WebView
                    ref={(ref) => this.webView = ref}
                    source={{ uri: this.state.webUrl }}
                    injectedJavaScript={run}
                    style={GlobalStyles.flex1}
                    onNavigationStateChange={this.onNavigationStateChange}
                    renderLoading={this.LoadingIndicatorView}
                    scalesPageToFit={true}
                    onLoad={this.onLoadWeb}
                    onError={this.onError}
                    useWebKit
                    startInLoadingState={true}
                    cacheEnabled={false}
                    allowUniversalAccessFromFileURLs
                    mixedContentMode='always'
                    originWhitelist={['*']}
                    javaScriptEnabled
                    javaScriptCanOpenWindowsAutomatically
                    domStorageEnabled
                    onMessage={this.onMessage}

**Expected behavior:**
Should send postMessage key to webView

**Environment:**
 - OS:  macOS 
 - OS version:10.15.6
 - react-native version: 0.63.2
 - react-native-webview version:^10.9.0
- Simulator: iOS simulator ipad pro 12.9 inch 13.6 os

**Comment by tero-paananen** [comment]
Try send message using `injectJavaScript`

```
var message = "hello";
this.webViewRef.injectJavaScript(getInjectableJSMessage(message));

function getInjectableJSMessage(message: any): string {
  return `(function() {document.dispatchEvent(new MessageEvent('message', {data: ${JSON.stringify(
    message
  )}}));})();`;
}
```

**Comment by ali27001** [comment]
onMessage not working for android.   I need to send value to mobile via web
web
```
  let sendMessageToNative = () =>{ 
        let url = window.location.href
        window.ReactNativeWebView && window.ReactNativeWebView.postMessage(url, '*')
    }
   sendMessageToNative() 
```
react native
```
<WebView

        allowsBackForwardNavigationGestures={true}
        originWhitelist={['*']}
        source={{ uri: 'x.com' }}
        startInLoadingState={true}
        javaScriptEnabledAndroid={true}
        javaScriptEnabled={true}
        onMessage={event => {
            console.log("eee", event.nativeEvent.data)
            alert('MESSAGE >>>>' + event.nativeEvent.data)
        }}

        ref={webviewRef}

        />
```

**Comment by tero-paananen** [comment]
Sorry, i cannot see where is the problem, currently this works for me

`window.ReactNativeWebView.postMessage("hello");`

**Comment by ali27001** [comment]
> Maalesef sorunun nerede olduğunu göremiyorum, şu anda bu benim için çalışıyor
> 
> `window.ReactNativeWebView.postMessage("hello");`

does it work on android? Is the code on the react native side the same as me? So, did you use postmassage on an external website and reach the message via react native?

**Comment by tero-paananen** [comment]
> > Maalesef sorunun nerede olduğunu göremiyorum, şu anda bu benim için çalışıyor
> > `window.ReactNativeWebView.postMessage("hello");`
> 
> does it work on android? Is the code on the react native side the same as me? So, did you use postmassage on an external website and reach the message via react native?

Works on iOS and Android. I can use also external websites. `originWhitelist={['http://', 'https://'];}`

**Comment by ali27001** [comment]
pretty odd. I just tried it again, it didn't work. It works on iOS. Doesn't work on Android. I even created a snack 
 > react native https://snack.expo.io/@ali27001/webview-example 
> Web example  > https://github.com/ali27001/webView-PostMessage-example/blob/master/index.html

**Comment by sahilneosofttech** [comment]
@ali27001 
its working as you suggested. thanks

**Comment by abhijithvijayan** [comment]
> Try send message using `injectJavaScript`
> 
> ```
> var message = "hello";
> this.webViewRef.injectJavaScript(getInjectableJSMessage(message));
> 
> function getInjectableJSMessage(message: any): string {
>   return `(function() {document.dispatchEvent(new MessageEvent('message', {data: ${JSON.stringify(
>     message
>   )}}));})();`;
> }
> ```

This works!! 

If anyone is having issues with getting the message, try this

```
 // listen events from react-native and trigger app status refetch
  React.useEffect(() => {
    function handleEvent(message) {
      console.log(message.data);
    }

    // This will only work for Android
    // https://stackoverflow.com/a/58118984
    document.addEventListener("message", handleEvent);

    return () =>
      document.removeEventListener("message", handleEvent);
  }, []);
```

**Comment by LuciferLat** [comment]
apologies for the late closing thread, issue was fixed. thank you

**Comment by winrid** [comment]
@LuciferLat  Sorry to comment on a closed issue but it looks like the type definitions have webview.postMessage, but this does not work. Is it intentional that postMessage from Native does not work? Should we remove that type def?
