### ISSUE TITLE
suppress alerts/confirms?

### ISSUE THREAD

**Issue by kurtgn** [react-native-webview/react-native-webview#1690]
Hi, is there a way to suppress javascript alerts and confirms on a loaded page?

I tried this

```
<WebView
       injectedJavaScriptBeforeContentLoaded={'window.confirm = function(){}; true;'}
       source={{ uri: 'https://mobo2apps.s3.amazonaws.com/webview_example.html' }}
 />
```

but apparently the JS in the source page gets run before my JS gets injected.

**Comment by kurtgn** [comment]
hi, still needing this :)

**Comment by namnm** [comment]
Any news?
