### ISSUE TITLE
stopLoading() cause website freeze

### ISSUE THREAD

**Issue by hieuvh3011** [react-native-webview/react-native-webview#1691]
**Bug description:**
Due to my client's request, I used webview to display some complex views from website. Recently, I need to intercept a user tapping on a link in my webview and open a browser bt `Linking`. I followed this [document](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Guide.md#controlling-navigation-state-changes). But there is a problem: after I used `this.webView.stopLoading()`, the website I embedded into the webview has been frozen. 

**Environment:**
 - OS: Android
 - OS version: 9
 - react-native version: 0.61.5
 - react-native-webview version: ^8.1.2

**Comment by mrtry** [comment]
Same Issue
