### ISSUE TITLE
THE POSSIBILITY OF INJECTING JAVASCRIPT CODE MORE THAN ONCE.

### ISSUE THREAD

**Issue by jose1937JS** [react-native-webview/react-native-webview#1693]
Hi, it would be wonderful if this library would can inject javascript code twice or more.
I'm trying to pass data to webView by pressing a button that calls this function. But, just works once :(

```javascript 
const data = "123"
function sendJsCode(){
    browserRef.current.injectJavaScript(`
        // do something with "${data}";
        true;
    `)
}
```

**Comment by cristianoccazinsp** [comment]
Platform? It works for me all the time.

**Comment by jose1937JS** [comment]
> Platform? It works for me all the time.

I was trying in android and it only worked once.
