### ISSUE TITLE
Downloading a URI starting with blob:http://... on android crashes the app

### ISSUE THREAD

**Issue by KA-32** [react-native-webview/react-native-webview#1694]
**Bug description:**
I have a webview on Android that attempts to download an embedded pdf file via a blob URL. However, the app crashes on such attempt. Please note 'https://www.example.com/5b2cccd0e4b0df92d975f9ae' this is not an actual url I am trying. Just given here to show the format. 

**To Reproduce:**
import React from 'react' ;
import { View } from 'react-native'; 
import { WebView } from 'react-native-webview';

const App = () => {
 return ( <View style={{ flex: 1 }}> 
<WebView source={{ uri: 'https://www.example.com/5b2cccd0e4b0df92d975f9ae' }} javaScriptEnabled domStorageEnabled /> 
</View> ) }

export default App;

**Expected behavior:**
Should download the pdf

**Screenshots/Videos:**
App is crashing

**Environment:**
 - OS: Android
 - OS version: 8.1.0
 - react-native version: 0.61.5
 - react-native-webview version: 8.1.2
<img width="717" alt="Screenshot 2020-10-12 at 11 21 29 AM" src="https://user-images.githubusercontent.com/8612565/95709824-1bb19400-0c7d-11eb-857a-9e233e6b0800.png">

**Comment by KA-32** [comment]
Same issue in react-native-webview: 10.9.2
<img width="1040" alt="Screenshot 2020-10-12 at 11 51 17 AM" src="https://user-images.githubusercontent.com/8612565/95712024-a0061600-0c81-11eb-88a9-7a9f5e5a34dd.png">

**Comment by hunght** [comment]
I think we go to the same issue with this on https://github.com/react-native-webview/react-native-webview/issues/295#issuecomment-532716315

**Comment by TheAlmightyBob** [comment]
Another previous duplicate: #1090

There's an open PR to stop the app from crashing: #1546

However the download would still fail.

**Comment by agnieszkabugla** [comment]
any ideas on how to fix that?
