### ISSUE TITLE
New WebView for Windows via WebView2 & WebUI 3 

### ISSUE THREAD

**Issue by tero-paananen** [react-native-webview/react-native-webview#1703]
Plannings to start implement use of latest `WebView2 via WebUI 3` on Windows

https://docs.microsoft.com/en-us/microsoft-edge/webview2/

https://microsoft.github.io/react-native-windows/docs/winui3
https://docs.microsoft.com/en-us/windows/apps/winui/winui3/

https://github.com/MicrosoftEdge/WebView2Samples/search?q=addhostobjecttoscript&unscoped_q=addhostobjecttoscript

- How should messaging between js and react native windows done if there is no AddWebAllowedObject in use? Try use AddHostObjectToScript https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.addhostobjecttoscript?view=WebView2-dotnet-0.9.628-prerelease

**Comment by tero-paananen** [comment]
I will wait that my 2 PRs are merged before i will try to implement any new WebView2

https://github.com/react-native-webview/react-native-webview/pull/1617
https://github.com/react-native-webview/react-native-webview/pull/1623

**Comment by tero-paananen** [comment]
About AddWebAllowedObject : For WebView2 - which will be included as part of WinUI 3 - you would be able to do something similar to AddWebAllowedObject by using https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2?view=webview2-0.9.622#addhostobjecttoscript. I'm not sure if there is a nicer WinRT API so you might need to use the COM API instead.

**Comment by tero-paananen** [comment]
Will we ever be able to pass complex objects into and out of our API's https://github.com/MicrosoftEdge/WebView2Feedback/issues/292

**Comment by exotexot** [comment]
Is there an update on this?
Really like to see react-native-webview using WebView2.

**Comment by tero-paananen** [comment]
Who manage do implement this?

**Comment by tero-paananen** [comment]
Discussion continues in https://github.com/microsoft/microsoft-ui-xaml/issues/5610
