### ISSUE TITLE
Add support for preventDefault when using onError method

### ISSUE THREAD

**Issue by nochkin** [react-native-webview/react-native-webview#1705]
I would like to propose a small feature request.

I would like to handle errors in my code. I tried to use the 'onError' method and tried to do syntheticEvent. preventDefault() to do that, but it still continued and I did not get the behaviour I wanted.

I propose to add `isDefaultPrevented()` in the onError method to support it.
The change does not affect the existing code unless someone does `preventDefault()`.

**Comment by nochkin** [comment]
Here is my proposed PR to make it happen:
https://github.com/react-native-webview/react-native-webview/pull/1706

**Comment by nochkin** [comment]
I provided a PR, but it's waiting for someone to approve it.

**Comment by nochkin** [comment]
The PR to resolve it was submitted already.
#1706

**Comment by nochkin** [comment]
Still waiting on merging the PR.

**Comment by nochkin** [comment]
The PR is opened and approved by one of the maintainers. Waiting to be merged.

**Comment by Titozzz** [comment]
I think it was solved by https://github.com/react-native-webview/react-native-webview/commit/279d6ae98c449b3c2d9ab2cc567f99bcc6e298b6.

But, to be fair, you fought admirably well against that Github bot, sorry 🤗
