### ISSUE TITLE
 Error opening URL:  [Error: Could not check if URL 'data:text/html;base64,PCFkb2N0eXBlIGh0b...

### ISSUE THREAD

**Issue by yingapp** [react-native-webview/react-native-webview#1708]
The above error occurs when loading dataurl in iframe.

iframe.src='data:text/html;base64,base64_encoded_data(size 1.89MB)'

[Tue Oct 15 2020 10:19:51.601]  WARN     Error opening URL: [Error: Could not check if URL 'data:text/html;base64,PCFkb2N0eXBlIGh0b
...
vYm9keT4NCg0KPC9odG1sPg==' can be opened: android.os.TransactionTooLargeException: data parcel size 1983200 bytes]

**Environment:**
 - OS:android
 - OS version:9
 - react-native version:0.63.2
 - react-native-webview version:^10.8.3

**Comment by castrolol** [comment]
I'm having the same issue, currently doens't have a way to intercept or just not crash the app? to I handle that request externally ?

**Comment by banyawat** [comment]
I found another workaround. Using this as HOC (https://www.npmjs.com/package/@formidable-webview/webshell) and then handle base64 link using onDOMLinkPress
