### ISSUE TITLE
iOS : SSL Pinning using custom certificate from Native  code

### ISSUE THREAD

**Issue by RajeshCentrica** [react-native-webview/react-native-webview#1710]
Hi,

We want to implement SSL pinning from Native iOS side so we require to override the RNCWebView.m class  **didReceiveAuthenticationChallenge** method. We are not able to override the below method because it’s not exposed to use outside of the class. 

Is it possible to make it didReceiveAuthenticationChallenge method as a class method and expose to use in AppDelegate class then we can override the and use a custom certificate for SSL pinning?

````
- (void)webView:(WKWebView *)webView
  didReceiveAuthenticationChallenge:(NSURLAuthenticationChallenge *)challenge
                  completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition disposition, NSURLCredential * _Nullable))completionHandler

````
**Trying to achieve:** When load URL on Webview we want to use a Custom certificate for SSL pinning.

Please let me know any other possibility to use custom SSL pinning from iOS native side.

**Comment by hanifmhd** [comment]
Hi,

is there any update about it?

**Comment by shalu-simformsolutions** [comment]
is there any update ?
