### ISSUE TITLE
Unable to scroll the content inside a WebView on react native windows using touch action

### ISSUE THREAD

**Issue by rahman2835** [react-native-webview/react-native-webview#1711]
**Bug description:**
Provide a detailed list of steps that reproduce the issue.

Unable to scroll the content inside a WebView on surface device using touch action.

**To Reproduce:**

1. create react-native-windows uwp app by using below steps.

npm install -g react-native-cli
react-native init ReactNativeWebViewDemo
cd ReactNativeWebViewDemo
Include "react-native-webview": "^10.9.2" in the package.json (in the dependencies)
npx react-native-windows-init --overwrite

2. Link the react-native-webview using below url.
https://github.com/react-native-webview/react-native-webview/blob/master/docs/Getting-Started.md

3. From the terminal : npm run start or yarn start

4. Open the app.js file and import webview from react-native-webview and add below logic.
import { WebView } from 'react-native-webview';

const App: () => React$Node = () => {
return (
<>
<WebView
source = {{ uri:
'https://www.google.com/?gws_rd=cr,ssl&ei=SICcV9_EFqqk6ASA3ZaABA#q=tutorialspoint' }}
/>
</>
);
};

5. run the app again or reload the app and try to scroll the content inside WebView using touch(surface device)

**Expected behavior:**
It should try to scroll the content inside a WebView. But its not scrolling using touch actions of surface device.

**Screenshots/Videos:**

**Environment:**

npx react-native --version: 4.13.0
npx react-native run-windows --info: System:
OS: Windows 10 10.0.18363
Binaries:
Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
npmPackages:
react: 16.13.1 => 16.13.1
react-native: 0.63.3 => 0.63.3
react-native-windows: ^0.63.0-0 => 0.63.5
Installed UWP SDKs:
10.0.17763.0
10.0.18362.0

**Comment by m4har** [comment]
yeah, me to use api 25, but if use api 29 working well
![Kapture 2020-10-28 at 14 51 24](https://user-images.githubusercontent.com/33221787/97407414-38142880-192d-11eb-9443-f11953526667.gif)

"react": "16.13.1",
 "react-native": "0.63.3",
"react-native-webview": "^10.8.3",

**Comment by exotexot** [comment]
Did you set scrollEnabled to true?

**Comment by JasonMerseItemis** [comment]
I'm having the same issue. (also on surface device)
@exotexot `scrollEnabled` had no effect on this.

**Comment by tbottke** [comment]
That is still a problem with touch enabled windows devices.

**Comment by rahman2835** [comment]
still no progress on this defect. Our app is now in Production. Any temporary help on this defect ?

**Comment by gnattu** [comment]
Seems like this does not only affect Windows, but on all Android with API level <28 as well.

**Comment by chiaramooney** [comment]
The issue for Windows stems from the perspective transform that exists at the root of RNW. Removing the perspective transform resolves the issue but that isn't a valid solution since we are reliant on the transform for other behavior. A workaround that should work for you is to disable perspective for your specific app via ReactRootView.IsPerspectiveEnabled this should resolve the WebView scrolling issue as long as your app isn't dependent on 3D animations. Ultimately we're looking to add the ability to declare requirements when it comes to perspective for community modules. At that point we will update WebView so it will work without adjustments.

**Comment by babyrusa** [comment]
I still have this issue on Android 29

whether it's this
```
 <WebView
        source={{uri: url}}
        onScroll={({nativeEvent}) => {
          if (isCloseToBottom(nativeEvent)) {
            setAccepted(true);
          }
        }}
        onLoadEnd={() => setIsLoading(false)}
        style={{flex: 1, height: 500}}
        javaScriptEnabled={true}
        domStorageEnabled={true}
        startInLoadingState={true}
        androidHardwareAccelerationDisabled={true}
        automaticallyAdjustContentInsets={false}
        startInLoadingState={true}
        scrollEnabled={true}
      />
```

or this

```
 <WebView
        source={{uri:url}}
        onScroll={({nativeEvent}) => {
          if (isCloseToBottom(nativeEvent)) {
            setAccepted(true);
          }
        }}
        onLoadEnd={() => setIsLoading(false)}
        style={{flex: 1}}
      />
```

it still scrolls very slowly and only moves like a few cm/inches then stops completely. It keeps highlighting the text instead of scrolling

**Comment by asklar** [comment]
since the original issue was filed about React Native Windows, and @chiaramooney investigated it and found the issue can be fixed by adding [this code](https://github.com/microsoft/react-native-gallery/blob/88601c3f9caa4b3fd5e496db81f7e89f2d7ba006/windows/rngallery/MainPage.cpp#L19) to app startup, I'm closing this issue. If you are still seeing this for other platforms, it's likely a separate issue, please file a new bug : )

**Comment by DouggyC** [comment]
this is still a problem on android

**Comment by joharkhan99** [comment]
I added the `scrollEnabled={true}` but it didn't worked. Then I added `nestedScrollEnabled={true}` and its working perfectly!

`<WebView
        source={{ uri: url }}
        scrollEnabled={true}
        nestedScrollEnabled={true}
      />`

**Comment by FH88** [comment]
> I added the `scrollEnabled={true}` but it didn't worked. Then I added `nestedScrollEnabled={true}` and its working perfectly!
> 
> `<WebView source={{ uri: url }} scrollEnabled={true} nestedScrollEnabled={true} />`

Mantul (Mantap Betul)
