### ISSUE TITLE
iOS 14.0.1 - Webview Process Terminated - Touch event

### ISSUE THREAD

**Issue by LilianAlvarez123** [react-native-webview/react-native-webview#1714]
**Bug description:**
Hello React Native Community !

The webview crashes after navigating a bit. I get a webview process terminated. The bug is only occuring when i compile directly the app from Xcode in debug mode. When I make an actual build throw CI/CD no bug are experienced.

**To Reproduce:**
Start an app with a simple webview, navigate with it inside a couple of websites and try to zoom in/out or press long inside the webview.

You need to use an iPhone device with iOS 14.0.1. The crash will occur and the webview reloads itself : "Webview Process Terminated".

![IMG_0036](https://user-images.githubusercontent.com/71655498/96977562-8a181100-151d-11eb-990c-b4f71e278c3b.jpg)

**Expected behavior:**
The webiew should not reloads itself. 

**Environment:**
 - OS: iOS
 - OS version: 14.0.1
 - react-native version: 0.61.5
 - react-native-webview version: 10.9.3

**Comment by Tomson-Wang** [comment]
Me Too

**Comment by pandya293** [comment]
I am facing same issue. Please post solution if you find?

**Comment by chenweigh** [comment]
same problem. 
the click event  cause on webView

**Comment by lumore** [comment]
Still having the same issue in IOS 14.4 simulator.
react-native-webview: 11.6.2,
