### ISSUE TITLE
window.ReactNativeWebView.postMessage does not work in iframe as expected (iOS)

### ISSUE THREAD

**Issue by abendi** [react-native-webview/react-native-webview#1718]
**Bug description:**

On physical iOS device `window.ReactNativeWebView.postMessage` does not work if postMessage is sent from an iframed website. On Android it works as expected.
**To Reproduce:**

Wrap html document that contains `window.ReactNativeWebView.postMessage` in an iframe and load the parent document in WebView. Invoke postMessage call in iframe and it won't reach WebView's `onMessage` callback.
**Expected behavior:**

According to documentation one might expect it to work, because on Android it works whether postMessage is sent from parent or iframed window.

**However** if you do `window.top.ReactNativeWebView.postMessage`, message is received for both iOS and Android. It looks to me as if on iOS `ReactNativeWebView` is only injected into topmost `window` object, whereas on Android it is injected into every window.

Not sure if it's intentional on iOS or just missing from documentation.
**Screenshots/Videos:**

**Environment:**
 - OS: iOS
 - OS version: 12.2
 - react-native version: 0.62.2
 - react-native-webview version: 10.3.1

**Comment by Hasnen-110** [comment]
Hey, I have been facing the same issue in ios. Have you found the solution yet? @abendi

**Comment by abendi** [comment]
@Hasnen-110 I changed the iframe's code so that it would proxy messages to WebView. Something along the lines of:
```
  proxySsoClientPostMessagesToWebView() {
    window.addEventListener('message', (event) => {
      if (event.origin !== YOUR_POSTMESSAGE_ORIGIN || !window.ReactNativeWebView) {
        return;
      }
      window.ReactNativeWebView.postMessage(JSON.stringify(event.data));
    });
  }
```

**Comment by Hasnen-110** [comment]
@abendi Thank you!
