### ISSUE TITLE
OriginWhitelist isn't working for deeplinks on Android

### ISSUE THREAD

**Issue by gabrielmoncea** [react-native-webview/react-native-webview#1719]
**Bug description:**

Adding the url scheme of the app in `originWhitelist` didn't prevent the WebView to throw the loading page error.
Having a deeplink inside a webview will always throw the following error on Android.

```
Encountered an error loading page {"canGoBack": true, "canGoForward": false, "code": -10, "description": "net::ERR_UNKNOWN_URL_SCHEME", "loading": false, "target": 163, "title": "Webpage not available", "url": "urbanair://whereTo"}
```

The workaround for this was to call `Linking.openURL()` and then `return false` inside `onShouldStartLoadWithRequest` when the `request.url` starts with the url scheme. The error will still show in the webview, but shortly after it opens the deeplink.

**To Reproduce:**

Add the apps deeplink inside the webview and then press it.

**Expected behavior:**

The webview should open the app directly through the deeplink.

**Screenshots/Videos:**

![IMG_4E6127203179-1](https://user-images.githubusercontent.com/39256258/97160599-4293be00-1785-11eb-98a0-2cfd6b029be5.jpeg)

**Environment:**
 - OS: MacOS
 - OS version: `10.15.7 (19H2)` 
 - react-native version: `0.63.3`
 - react-native-webview version: `10.9.3`

**Comment by nascode** [comment]
i seconded this. i tried to open whatsapp deeplink url.

**Comment by klandell** [comment]
Same issue here.

**Comment by amagnolo** [comment]
this might be related to #1741

**Comment by gabrielmoncea** [comment]
Don't close

**Comment by a613** [comment]
how can all these fundamental critical bugs go ignored so long...

**Comment by sasindroid** [comment]
Did anyone get a resolution to this please?

**Comment by amagnolo** [comment]
It seems that the project maintainers don't realize how impacting this bug is, in terms of people affected and issue severity.

**Comment by j-piasecki** [comment]
If I understood the issue correctly, this is intended behaviour. According to the [documentation](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#originwhitelist) if the origin is added to the whitelist, it is handled by the `Webview`, otherwise it is handled by the OS. Can you try removing the origin from whitelist to see if it solves the problem?
Do you have any use case where it is required to have the origin on the whitelist but it needs to be handled by the OS? If that is the case, you can try to use `Linking.openURL()` and `return false` in `onShouldStartLoadWithRequest` as suggested in the first post.

**Comment by gabrielmoncea** [comment]
Still searching for solutions

**Comment by kranthi1216** [comment]
Hi 
i am having issues with intent://app.......... url in Android where i need to open another app and get data back
currently showing error Unknown url scheme 
tried to set originWhitelist={['http://*', 'https://*', 'intent://*']}
added https scheme with host in Android manifest file and added queries with package name
also tried with react-native-send-intent
nothing resolves unknown url scheme error


Thank you

**Comment by patissier-boulanger** [comment]
+1

**Comment by pszemang** [comment]
here's a quick snipper how i handled this:

```
        <WebView
          originWhitelist={['https://', 'applink://']}
          source={{
            uri
          }}
          onShouldStartLoadWithRequest={(request) => {
            if (request.url.startsWith('applink')) {
              void Linking.openURL(request.url);
              return false;
            }
            return true;
          }}
        />
```

The main idea is to handle `applink` using webview instead of an OS and open deeplink using `Linking` api

for more info see:
https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#onshouldstartloadwithrequest
