### ISSUE TITLE
postMessage or onMessage not working android?

### ISSUE THREAD

**Issue by ali27001** [react-native-webview/react-native-webview#1723]
I need to send a message to react native through the website. It works as expected in ios when I do it as below. But it doesn't work on android

website code (x.com)
```
let sendMessageToNative = () =>{ 
        let url = window.location.href
        window.ReactNativeWebView && window.ReactNativeWebView.postMessage(url, '*')
    }
   sendMessageToNative() 

```
react native code 
```
<WebView

        allowsBackForwardNavigationGestures={true}
        originWhitelist={['*']}
        source={{ uri: 'x.com' }}
        startInLoadingState={true}
        javaScriptEnabledAndroid={true}
        javaScriptEnabled={true}
        onMessage={event => {
            console.log("eee", event.nativeEvent.data)
            alert('MESSAGE >>>>' + event.nativeEvent.data)
        }}

        ref={webviewRef}

        />
```
**Expected behavior:**
The url I sent on ios appears on the screen as an alert. This does not happen on Android. The same I sent in the string.the same must be on android

**Environment:**
 - OS: Android
 - OS version: Android Version 11 emilator or xiaomi mi 8 lite android version 10  
 - react-native version: 38
 - react-native-webview version: 9.4.0

**Comment by jbolotin** [comment]
Also experiencing this issue on android suddenly

**Comment by jbolotin** [comment]
@ali27001  I spent a long time today debugging this. I'm not sure what device / API level you're testing on, but for me, this almost certainly seems to be because the browser on the old device that I was testing with doesn't support es6. After I changed my `const` declarations to `var`, everything begins working as expected. In your case, if you try changing your `let` declaration to `var`, I'm curious if it would work. Btw I was testing on a very old Nexus One API 23 in case that's helpful

**Comment by ali27001** [comment]
@jbolotin I replaced my variable let on the website with var. And I tried it with the pixel 2xl api 30 device. It didn't work. When I come to the page sending the message, it stays on the white screen

**Comment by xhbisme** [comment]
I met the same problem，add onMesssge, got a white page on android

**Comment by xhbisme** [comment]
error reason is:  window.ReactNativeWebView is {} on android,

**Comment by fredjens** [comment]
Any updates on this? I am also experiencing this issue using the Pixel. Does it work on other Androids?

**Comment by fpena** [comment]
I created [an example repo](https://github.com/fpena/react-native-webview-post-message-example) where this can be reproduced. 

In iOS, an alert shows up because the website is call `callback` function.
In Android doesn't happen.

cc: @jamonholmgren

**Comment by asukiaaa** [comment]
I had similar questions but I could call `postMessage` on my Android device.

What I found.
- `window.ReactNative` become undefined if onMessage option does not be set for `WebView`.
- `window.ReactNative.postMessage` seems be undefined but I can call `window.ReactNative.postMessage('some message')`

My env:
- react-native 0.63.4
- react-native-webview: 
- Android 6.1 (Nexus5)

Codes that I tried.

Code in webview
```
const key = 'ReactNativeWebView'
alert(key + ' ' + JSON.stringify((window as any)[key]) + ' ' + JSON.stringify(((window as any)[key])?.postMessage));
(window as any)[key]?.postMessage('hi')
```

Case A: Code in native app
```tsx
<WebView
  // .. configs
  onMessage={(e) => Alert.alert(e.nativeEvent.data)}
/>
```

Case A: Result of alert on web view
```
ReactNativeWebView {} undefined
```


Case B: Code in native app (without onMessage option)
```tsx
<WebView
  // .. configs
  // onMessage={(e) => Alert.alert(e.nativeEvent.data)}
/>
```

Case B: Result of alert on web view
```
ReactNativeWebView undefined undefined
```



@fpena 
I think that your code should call ReactNativeWebView from window like this.
```js
  const injectedJS = 'function callback(){window.ReactNativeWebView.postMessage('some message');}';
```
`postMessage` seems support only string so if you should use `JSON.stringify` send information about object.
```js
  const injectedJS = 'function callback(){window.ReactNativeWebView.postMessage(JSON.stringify({key: 'sample ObjectKey'}));}';
```

https://github.com/fpena/react-native-webview-post-message-example/blob/1105ff07faba86ae0961893593260f8a295fafd5/App.js#L14

**Comment by inDivyanshu** [comment]
still searching for solutions

**Comment by ydv0121** [comment]
+1

**Comment by Sravansuhas** [comment]
++1

**Comment by niezicheng** [comment]
After trying all the above,  I still have this problem: it does not work normally on ios but not on android

**Comment by panda6412** [comment]
How's this issue going through, same here :(

**Comment by giacomoalonzi** [comment]
still searching for solutions

**Comment by DaywisonSilva** [comment]
still searching for solutions

**Comment by Tran-Huu-Tai-12-04-23** [comment]
It would be work when I transform number to string in android. The code like this ```const INJECTED_JAVASCRIPT = `
  setTimeout(() => {
    const height = document.body.scrollHeight;
    window.ReactNativeWebView.postMessage(height?.toString());
  }, 300);
  true;
`;```

**Comment by angel-luis** [comment]
Thank you for the insight @Tran-Huu-Tai-12-04-23. Fixed.

This works on iOS, but not on Android:
```
<script>
  window.ReactNativeWebView.postMessage(document.body.scrollHeight);
</script>
```

The fix is just add `.toString()` to any parameter passed to `postMessage()`.

The docs says explicitly that you have to set a string parameter in this method, but for some reason is skipped on iOS.
