### ISSUE TITLE
how to add react-native-webview in C# based uwp windows app 

### ISSUE THREAD

**Issue by SelvaraniAlagumuthu** [react-native-webview/react-native-webview#1724]
Hi,
I used react-native-webview in my app. i tried to manual link as mentioned in getting started guide,
Add the ReactNativeWebView project to your solution.

Open the solution in Visual Studio 2019
Right-click Solution icon in Solution Explorer > Add > Existing Project Select node_modules\react-native-webview\windows\ReactNativeWebView\ReactNativeWebView.vcxproj
windows/myapp/myapp.vcxproj
Add a reference to ReactNativeWebView to your main application project. From Visual Studio 2019:

Right-click main application project > Add > Reference... Check ReactNativeWebView from Solution Projects.

Modify files below to add the package providers to your main application project

pch.h
Add #include "winrt/ReactNativeWebView.h".

app.cpp
Add PackageProviders().Append(winrt::ReactNativeWebView::ReactPackageProvider()); before InitializeComponent();.

But my react-native windows app have C# here how can i add this package in my project
example :
using RNFS;
 protected override List<IReactPackage> Packages => new List<IReactPackage>
        {
            new MainReactPackage(),
new RNFSPackage(),
}

Please guide me for this.

**Comment by tero-paananen** [comment]
Try to read from here https://microsoft.github.io/react-native-windows/docs/native-modules

There is `App.xaml.cs` example that looks like this:

```
using Microsoft.ReactNative;

namespace SampleApp
{
    sealed partial class App : ReactApplication
    {
        public App()
        {
            /* Other Init Code */

            PackageProviders.Add(new Microsoft.ReactNative.Managed.ReactPackageProvider()); // Includes any modules in this project
            PackageProviders.Add(new NativeModuleSample.ReactPackageProvider());

            /* Other Init Code */
        }
    }
}
```

**Comment by tero-paananen** [comment]
Maybe it is something like this:

`PackageProviders.Add(new ReactNativeWebView.ReactPackageProvider());`

+ some `using ....`

**Comment by tero-paananen** [comment]
Examples are of course from `react-native-windows >= 0.62`

**Comment by SelvaraniAlagumuthu** [comment]
Hi..
i couldn't add react-native-webview package in my Application. In reference i added the ReactNativeWebveiw. but its showing the below error
i used react-native-window 0.59.0-rc.5 'E:\Gitworkspace\featureRebrandWindows\windows\Debug\ReactNativeWebView\ReactNativeWebView.winmd' could not be found

**Comment by tero-paananen** [comment]
> Hi..
> i couldn't add react-native-webview package in my Application. In reference i added the ReactNativeWebveiw. but its showing the below error
> i used react-native-window 0.59.0-rc.5 'E:\Gitworkspace\featureRebrandWindows\windows\Debug\ReactNativeWebView\ReactNativeWebView.winmd' could not be found

Use latest rn-webview only for apps >= 0.62

You have rn-windows 0.59 app so use `"react-native-webview": "^2.5.0",`

**Comment by SelvaraniAlagumuthu** [comment]
But react-native-webview 2.5.0 is not supported for windows ?..

**Comment by tero-paananen** [comment]
Sorry, you can import WebView from react-native-windows in javascript, i will check valid import later...

**Comment by SelvaraniAlagumuthu** [comment]
import { WebView } from 'react-native'; But windows 0.59.. is not supported i think
