### ISSUE TITLE
[android] - onShouldStartLoadWithRequest - form action=url method=post

### ISSUE THREAD

**Issue by krutkowski86** [react-native-webview/react-native-webview#1725]
**Bug description:**
On Android OS onShouldStartLoadWithRequest isn't called when using submit button on the following HTML (example). 
User is navigated but I can't handle how this URL is being opened while I would like it to be opened by OS web browser.

 ```
<form action="https://any-url.com" method="POST">
  <input name="test" value="testValue"/>
  <button type="submit">SUBMIT</button>
</form>
```

Is there any way to handle it and open OS web browser?

**Environment:**
 - OS: Android
 - react-native version: 0.62.*
 - react-native-webview version: 10.*

**Comment by krutkowski86** [comment]
+1 @tero-paananen any advice would be appreciated

**Comment by pioneer32** [comment]
+1 I can confirm we experience the same problem. We use 10.7.0

**Comment by Brma1048** [comment]
We still have this issue in version 11.23.1, please open again.

**Comment by bencagri** [comment]
still have the issue.

**Comment by chanwoong528** [comment]
still have issue
