### ISSUE TITLE
TypeScript: Make more types available via the main import

### ISSUE THREAD

**Issue by martinandert** [react-native-webview/react-native-webview#1734]
Currently I have to do this...

```ts
import { WebView, WebViewNavigation } from "react-native-webview";
import type { WebViewProgressEvent } from "react-native-webview/lib/WebViewTypes";
```

...in order to get my hands on the `WebViewProgressEvent` type. And then I need to configure ESLint to allow submodule imports for "react-native-webview".

But I'd rather do this instead:

```ts
import { WebView, WebViewNavigation, WebViewProgressEvent } from "react-native-webview";
```

Is there a chance all/most of the types found in `./lib/WebViewTypes.d.ts` can be exported in `./index.d.ts`, as was [done already for a few other types](https://github.com/react-native-webview/react-native-webview/blob/74872a1f02c43e425f19739b1b25f5fbe614ba1f/index.d.ts#L5)?

**Comment by martinandert** [comment]
> You have 7 days until this gets closed automatically

Adding a comment as it's still an issue.

**Comment by hermanho** [comment]
It is still an issue after 5 years.
