### ISSUE TITLE
Open the new RN container and return to the white screen again(打开新的RN容器再次返回白屏)

### ISSUE THREAD

**Issue by RmondJone** [react-native-webview/react-native-webview#1737]
**Bug description:**
Open the new RN container and return to the white screen again，Due to the following life cycle judgment error：
```java
    protected void cleanupCallbacksAndDestroy() {
      setWebViewClient(null);
      destroy();
    }
```

**Environment:**
 - OS: Android
 - OS version: Android7.1.1
 - react-native version: 0.61.4
 - react-native-webview version:10.10.0

**Comment by cd-butterfly** [comment]
RNCWebView 注释掉 onHostDestroy

**Comment by RmondJone** [comment]
> RNCWebView 注释掉 onHostDestroy

我知道啊，我就是反馈给他们，他们只考虑了单容器，没考虑多容器场景

**Comment by oliverdolgener** [comment]
We got the same problem. We're using React Navigation to navigate between multiple screens with WebViews. When navigating back to a screen with a previously loaded WebView the screen turns white. We rolled back to react-native-webview 10.8.0 where everything works fine
