### ISSUE TITLE
App crash when using with react-native-maps

### ISSUE THREAD

**Issue by tuonght93** [react-native-webview/react-native-webview#1738]
When I remove one in two every thing fine

This showing in logcat:
11-10 15:53:13.578  1793 22522 E GnssHAL_GnssInterface: gnssSvStatusCb: b: input svInfo.flags is 8
11-10 15:53:13.701 23844 23916 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 23916 (RenderThread), pid 23844 (tarindex.example)
11-10 15:53:13.808 22286 22312 E memtrack: Couldn't load memtrack module
11-10 15:53:14.183 24102 24102 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-10 15:53:14.183 24102 24102 F DEBUG   : Build fingerprint: 'google/sdk_gphone_x86/generic_x86:10/QSR1.190920.001/5891938:user/release-keys'
11-10 15:53:14.183 24102 24102 F DEBUG   : Revision: '0'
11-10 15:53:14.183 24102 24102 F DEBUG   : ABI: 'x86'
11-10 15:53:14.184 24102 24102 F DEBUG   : Timestamp: 2020-11-10 15:53:14+0700
11-10 15:53:14.184 24102 24102 F DEBUG   : pid: 23844, tid: 23916, name: RenderThread  >>> com.example <<<
11-10 15:53:14.184 24102 24102 F DEBUG   : uid: 10252
11-10 15:53:14.184 24102 24102 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
11-10 15:53:14.184 24102 24102 F DEBUG   : Cause: null pointer dereference
11-10 15:53:14.184 24102 24102 F DEBUG   :     eax a725e800  ebx c9611864  ecx c947b5c0  edx 0000001d
11-10 15:53:14.184 24102 24102 F DEBUG   :     edi bb92a698  esi a7314400
11-10 15:53:14.184 24102 24102 F DEBUG   :     ebp bb92a65c  esp bb92a5fc  eip 00000000
11-10 15:53:14.191 24102 24102 F DEBUG   : 
11-10 15:53:14.191 24102 24102 F DEBUG   : backtrace:
11-10 15:53:14.191 24102 24102 F DEBUG   :       #00 pc 00000000  <unknown>
11-10 15:53:14.191 24102 24102 F DEBUG   :       #01 pc 0286c771  /system/product/app/TrichromeLibrary/TrichromeLibrary.apk!libmonochrome.so (offset 0x66c000) (BuildId: ffe50d4377c82928759c1f40f1b35ba9f411454a)
11-10 15:53:14.307 23844 24084 E eglCodecCommon: glUtilsParamSize: unknow param 0x000088ef
11-10 15:53:14.308 23844 24084 E eglCodecCommon: glUtilsParamSize: unknow param 0x000088ef
11-10 15:53:14.442 23844 24084 E eglCodecCommon: glUtilsParamSize: unknow param 0x000088ef
11-10 15:53:14.442 23844 24084 E eglCodecCommon: glUtilsParamSize: unknow param 0x000088ef
11-10 15:53:14.578  1793 22522 E GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8
11-10 15:53:14.578  1793 22522 E GnssHAL_GnssInterface: gnssSvStatusCb: b: input svInfo.flags is 8
11-10 15:53:15.581  1793 22522 E GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8
11-10 15:53:15.581  1793 22522 E GnssHAL_GnssInterface: gnssSvStatusCb: b: input svInfo.flags is 8
11-10 15:53:15.920  1883  1883 E /system/bin/tombstoned: Tombstone written to: /data/tombstones/tombstone_08
11-10 15:53:16.065 22286 22372 E InputDispatcher: channel '5e9d8c2 package.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
11-10 15:53:16.280 22286 22312 E memtrack: Couldn't load memtrack module
11-10 15:53:16.285 22286 22312 E memtrack: Couldn't load memtrack module
11-10 15:53:16.290 22286 22312 E memtrack: Couldn't load memtrack module
11-10 15:53:16.290 22286 22312 E memtrack: Couldn't load memtrack module
11-10 15:53:16.293 22286 22312 E memtrack: Couldn't load memtrack module
11-10 15:53:16.293 22286 22312 E memtrack: Couldn't load memtrack module
11-10 15:53:16.295 22286 22312 E memtrack: Couldn't load memtrack module
11-10 15:53:16.296 22286 22312 E memtrack: Couldn't load memtrack module
11-10 15:53:16.297 22286 22312 E memtrack: Couldn't load memtrack module
11-10 15:53:16.323 22286 22312 E memtrack: Couldn't load memtrack module
11-10 15:53:16.323 22286 22312 E memtrack: Couldn't load memtrack module
11-10 15:53:16.324 22286 22312 E memtrack: Couldn't load memtrack module
11-10 15:53:16.332 22286 23040 E memtrack: Couldn't load memtrack module
11-10 15:53:16.350 22286 22312 E memtrack: Couldn't load memtrack module
11-10 15:53:16.353 22286 22312 E memtrack: Couldn't load memtrack module
11-10 15:53:16.354 22286 22312 E memtrack: Couldn't load memtrack module
11-10 15:53:16.355 22286 22312 E memtrack: Couldn't load memtrack module
11-10 15:53:16.357 22286 22312 E memtrack: Couldn't load memtrack module
11-10 15:53:16.363 22286 22312 E memtrack: Couldn't load memtrack module

**Comment by hueyAtFetchly** [comment]
https://github.com/react-native-webview/react-native-webview/issues/777

**Comment by ztaz311** [comment]
same issue

**Comment by shubham-mehta-dev** [comment]
Facing the same issue
