### ISSUE TITLE
Dependabot alerts: react-native-webview

### ISSUE THREAD

**Issue by Frabanz** [react-native-webview/react-native-webview#1739]
**Bug description:**

![grafik](https://user-images.githubusercontent.com/44829736/98651187-376e8f80-233a-11eb-8dd3-6a8137888619.png)

This vulnerability affects React Native apps which use a react-native-webview that allows navigation to arbitrary URLs, and when that app runs on systems with an Android WebView version prior to 83.0.4103.106.

Link to this Bug: [bugs.chromium.org](https://crbug.com/1083819)

**To Reproduce:**
`yarn add react-native-webview`
`npm i react-native-webview`

**Expected behavior:**
No security leak

**Environment:**
 - react-native version: 0.63.3
 - react-native-webview version: 10.10.2

**Comment by chris-griffin** [comment]
Dupe of https://github.com/react-native-webview/react-native-webview/issues/1655
