### ISSUE TITLE
onShouldStartLoadingWithRequest loading on android although set to false

### ISSUE THREAD

**Issue by marcelburda** [react-native-webview/react-native-webview#1741]
Since version 10.8.3, the onShouldStartLoadingWithRequest method on android doesn't seem to work properly.

--->

**To Reproduce:**
Put  
onShouldStartLoadWithRequest={(req) => {
                  return false;
                }}
into the webview and click. The webview will still load the page.

**Expected behavior:**
Stop loading

**Environment:**
 - OS: android
 - OS version: 10
 - react-native version: 0.63.3
 - react-native-webview version: 10.8.3+

**Comment by Trashpants** [comment]
+1, I seem to get this with certain domains even a console.log in the onShouldStartLoadWithRequest method doesn't work!

See if you change your domain to https://google.com and see if it works? it does for me this way!

Im trying to fire the request to https://appleid.apple.com/auth/authorize.... and it refuses to fire at all :(

**Comment by Pingou** [comment]
Same issue here... It used to work in v7.0.0

**Comment by devmod** [comment]
+1 also happens over here on android

**Comment by awkpagong** [comment]
+1 this is also happening for me (tested on Android 10, RN 62.2). I thought https://github.com/react-native-webview/react-native-webview/pull/1689 would fix it, but after installing version `11.0.2` `onShouldStartLoadWithRequest` is still not getting called. @jamonholmgren @Titozzz @TheAlmightyBob @inf123

**Comment by awkpagong** [comment]
> +1 this is also happening for me (tested on Android 10, RN 62.2). I thought #1689 would fix it, but after installing version `11.0.2` `onShouldStartLoadWithRequest` is still not getting called. @jamonholmgren @Titozzz @TheAlmightyBob @inf123

Update: actually I think my issue is because I have `setSupportMultipleWindows` set to `true` and the link I'm testing has `target="_blank"`. So maybe it's working as expected in my case? 🤔

**Comment by marcelburda** [comment]
@awkpagong I observed the same. Updating to 11.0.2 did not resolve the issue for me. I do not use supportMultipleWindows

**Comment by amagnolo** [comment]
the same happens with expo 40.0.0.
upgrading react-native-webview from 11.0.0 to 11.0.2 doesn't solve the issue.

**Comment by devmod** [comment]
Same thing over here- the update to 11.x did not fix this issue either.

**Comment by mit4dev** [comment]
Having the same issue on 10.10.2

**Comment by mynameisguy** [comment]
Had the same issue on 11.0.0
Adding onError option solved it for some reason

**Comment by gregoryfm** [comment]
@mynameisguy how you did it?
I've tested on 11.0.0 and 11.0.3 and still having the same issue.

**Comment by javierbustamante** [comment]
Same issue here!!!

**Comment by davidohlin** [comment]
Having the same issue using after updating to Expo SDK 40 and react-native-webview 11.0.0. I do not use `setSupportMultipleWindows`.

I've tried the following solutions which does **not** work:
* Returning to 10.8.2 
* Installing 11.0.x versions
* Adding onError option

**Comment by gregoryfm** [comment]
Still searching for solutions..

**Comment by hanifmhd** [comment]
hi is there any update about this?

**Comment by amagnolo** [comment]
This might be a duplicate of #1719

**Comment by j-piasecki** [comment]
This issue comes from the behavior of `WebViewClient` in `Android`. The `shouldOverrideUrlLoading` method is called only when the user clicks the link inside the `WebView`, not when setting the page via code, as described in https://stackoverflow.com/a/32711309/13006595.
To confirm that you can create an example containing a link and defining `onShouldStartLoadWithRequest` to always return false.
Maybe the rncWebView.sendDirectMessage(“onShouldStartLoadWithRequest”, event); should be somehow fired in setSource to mimic the behavior of iOS , but I am not too familiar with the code so just guessing.

**Comment by Estebank94** [comment]
As a workaround I did this:

```javascript
<WebView
      source={{
        uri: ...
      }}
      ref={(ref) => (webviewRef = ref)}
      originWhitelist={...}
      onShouldStartLoadWithRequest={handleNavigationStateChange}
      setSupportMultipleWindows={false}
      onError={() => {
        if (!error) {
          webviewRef?.reload();
          error = true;
        }
      }}
      renderError={() => <SpinnerLoading />}
/>
```

Basically if there's an error loading the page, reload it and then it should work.

**Comment by gregoryfm** [comment]
@Estebank94  I've tried that, and for me, it didn't work.

Most of the time, there's no error loading the page...

**Comment by klinzo** [comment]
So we still have this issue with react-native v0.66.4 and react-native-webview v11.17.0. I think it may be caused by taking too long to return `false` in `onShouldStartLoadingWithRequest`. I was able to fix it with a (not really nice) workaround saving the pressed url to the state and handling it in a `useEffect` hook:
``` ts
  const [pressedUrl, setPressedUrl] = useState<string | null>(null)

  useEffect(() => {
    const url = pressedUrl
    if (url) {
      setPressedUrl(null)
      // Do something with the url
    }
  }, [pressedUrl])

  const onShouldStartLoadWithRequest = useCallback(
      (event: WebViewNavigation): boolean => {
        setPressedUrl(event.url)
        return false
      },
      [resourceCacheUrl]
    )

  return (
      <WebView
        {...otherProps}
        onShouldStartLoadWithRequest={onShouldStartLoadWithRequest}
        setSupportMultipleWindows={false}
      />
  )
```

**Comment by KonstantinKostianytsia** [comment]
> So we still have this issue with react-native v0.66.4 and react-native-webview v11.17.0. I think it may be caused by taking too long to return `false` in `onShouldStartLoadingWithRequest`. I was able to fix it with a (not really nice) workaround saving the pressed url to the state and handling it in a `useEffect` hook:
> 
> ```ts
>   const [pressedUrl, setPressedUrl] = useState<string | null>(null)
> 
>   useEffect(() => {
>     if (pressedUrl) {
>       setPressedUrl(null)
>       // Do something with the url
>     }
>   }, [pressedUrl])
> 
>   const onShouldStartLoadWithRequest = (event: WebViewNavigation): boolean => {
>     setPressedUrl(event.url)
>     return false
>   }
> 
>   return (
>       <WebView
>         {...otherProps}
>         onShouldStartLoadWithRequest={onShouldStartLoadWithRequest}
>         setSupportMultipleWindows={false}
>       />
>   )
> ```

Thanks a lot, seems it was a problem for me on the Android. I added a workaround
```
if (hasSection) {
     setTimeout(() => {
       navigateToContent(item, {scrollToSectionId: sectionId}, true);
     }, 50);
} else {
     setTimeout(() => {
       navigateToContent(item, {}, true);
     }, 50);
}
return false;
```
