### ISSUE TITLE
Github action bot not working

### ISSUE THREAD

**Issue by aliazizi** [react-native-webview/react-native-webview#1743]
look at this issue #1473 and https://github.com/react-native-webview/react-native-webview/issues/1605, github-actions closed the issue. I add comment to prevent it but it's close it anyway

**Comment by aliazizi** [comment]
Is anybody there ? !

**Comment by aliazizi** [comment]
@Titozzz @jamonholmgren

**Comment by Titozzz** [comment]
I've updated it, should be good now.

**Comment by aliazizi** [comment]
Thanks

**Comment by aliazizi** [comment]
@Titozzz its still not working
look at here
https://github.com/react-native-webview/react-native-webview/issues/1473

**Comment by Titozzz** [comment]
It should update next time it runs

**Comment by aliazizi** [comment]
https://github.com/react-native-webview/react-native-webview/issues/1473#issuecomment-768198649 @Titozzz this posted write now

**Comment by Titozzz** [comment]
Bot only runs once a day
