### ISSUE TITLE
Android "choose and action" is not opening

### ISSUE THREAD

**Issue by AsocialCoder** [react-native-webview/react-native-webview#1745]
I would like choose camera when i click choose file button but directs me directly to the file directory, so "choose and action" popup isn't opening on android. IOS working well. how can i fix this?

<img width="569" alt="Screen Shot 2020-11-16 at 15 52 40" src="https://user-images.githubusercontent.com/16050880/99256266-3354dd00-2826-11eb-9b5a-8689019d8b58.png">

**Comment by mohamed-sultan** [comment]
@AsocialCoder how you managed that i'm unable to interact on android when press button

**Comment by mohamed-sultan** [comment]
for android i had to put the webview inside modal to make it works
