### ISSUE TITLE
Animated.event with onScroll on Android

### ISSUE THREAD

**Issue by bachlongkocanh** [react-native-webview/react-native-webview#1746]
There is a problem when I use Animated.event with onScroll.
**Bug description:**
-I used Animated.event with onScroll Webview, on ios it works but on android there's a problem. The animated element jerked up and down as I scrolled slowly. When I scroll quickly, it is ignored.
**Expected behavior:**
I want my animated element to move smoothly when I scroll like the ios side.
**Screenshots/Videos:**

![ezgif-7-c9772cd3a228](https://user-images.githubusercontent.com/28125294/99346168-91390180-28c6-11eb-8660-81225283759d.gif)

**Environment:**
 - OS: ANDROID
 - react-native version: 0.61.4
 - react-native-webview version: 10.9.0

**Comment by bachlongkocanh** [comment]
Still searching for solutions

**Comment by babyrusa** [comment]
I'm having this issue on Android but not IOS

```
<WebView
        source={{uri: url}}
        onScroll={({nativeEvent}) => {
          if (isCloseToBottom(nativeEvent)) {
            setAccepted(true);
          }
        }}
        onLoadEnd={() => setIsLoading(false)}
        style={{flex: 1}}
      />
```

**Comment by LinhNguyen1059** [comment]
Have you solved the problem? I'm also face issue like you. @bachlongkocanh
