### ISSUE TITLE
Does Webview render inside web browsers?

### ISSUE THREAD

**Issue by PunkmeisterDuy** [react-native-webview/react-native-webview#1752]
I encountered for a week trying to debug react-native-webview with expo as whenever I tried to test it with a web browser, there was no output. I just used my android phone to run the app and it worked the entire time. Does Webview not render inside web browsers?

**Comment by nabilfreeman** [comment]
Yes it works, but some websites will not allow you to embed inside a frame and webview won't work. The webviews in native iOS and Android ignore these rules.

**Comment by NickCarducci** [comment]
I am getting `View is not defined`: is this unexpected behavior? If it is, might you recommend (1) researching another package like `react-native-web-webview`, or (2) try to develop locally?
**env:**
I use `Codesandbox` as my cloud IDE.

````
{website !== "" && (
  <WebView
    style={{
      height: "100%",
      width: "100%"
    }}
    originWhitelist={[website]}
    title={website}
    //source={{ uri: website }}
    source={{
      html: `
    <!DOCTYPE html>\n
    <html>
      <head>
        <title>Hello World</title>
        <meta http-equiv="content-type" content="text/html; charset=utf-8">
        <meta name="viewport" content="width=320, user-scalable=no">
        <style type="text/css">
          body {
            margin: 0;
            padding: 0;
            font: 62.5% arial, sans-serif;
            background: transparent;
          }
        </style>
      </head>
      <body>
        <p>HTML content in transparent body.</p>
      </body>
    </html>
    `
    }}
    onLoadEnd={() => {
      window.alert("loaded " + website);
      this.setState({ loadedSite: website });
    }}
    //injectedJavaScript={String(js)}
  />
)}
````
