### ISSUE TITLE
Could not resolve project :react-native-webview

### ISSUE THREAD

**Issue by wulaizi** [react-native-webview/react-native-webview#1753]
**Bug description:**

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS:
 - OS version:
 - react-native version:
 - react-native-webview version:
`Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:releaseStagingRuntimeClasspath'.
   > Could not resolve project :react-native-webview.
     Required by:
         project :app
      > java.lang.NullPointerException (no error message)`

**Comment by wulaizi** [comment]
"react-native": "0.58.6",
  "react-native-webview": "^5.12.0"


Link the mobile phone in the debug environment and run normally,

This error is reported when packing

**Comment by AdeelTanveer** [comment]
Hi. I am still facing this issue.
