### ISSUE TITLE
Task fail for 'react-native-webview:compileReleaseJavaWithJavac'

### ISSUE THREAD

**Issue by joegoodall1** [react-native-webview/react-native-webview#1754]
Recently started to see a fail with the task `react-native-webview:compileReleaseJavaWithJavac
`

<img width="944" alt="Screenshot 2020-11-23 at 13 06 35" src="https://user-images.githubusercontent.com/8888799/99965486-d52b7b00-2d8c-11eb-812b-1e564bc0ca0f.png">

Does anybody know what may be causing this and/or the resolution?

**Comment by mm7mod** [comment]
+1 facing the same issue even with the latest react-native version ... it is a nightmare

**Comment by joegoodall1** [comment]
This is now fixed on our side. We had a patch targeting a different version of `react-native-webview` than the version we were using in the app, hence the errors.

**Comment by jaimincrest** [comment]
which version you used?
