### ISSUE TITLE
Module  is not a registered callable module (calling onShouldStartLoadWithRequest)

### ISSUE THREAD

**Issue by rutul089** [react-native-webview/react-native-webview#1756]
**Bug description:**
On click of any button or link in WebView I am getting this Invariant Violation: Module  is not a registered callable module (calling onShouldStartLoadWithRequest)

**Screenshots/Videos:**
![Screenshot_1606244966](https://user-images.githubusercontent.com/13690583/100140252-b4f7db00-2eb6-11eb-905f-1529a5f730fd.png)

**Environment:**
 - OS: Android
 - OS version: Android 10 ( Android Q)
 - react-native version: 0.61.4
 - react-native-webview version: 10.3.2

**Comment by jamiembrown** [comment]
I am still searching for a solution to this. My app closes as soon as any Webview opens, only on Android:

`E/unknown:DisabledDevSupportManager: Caught exception
    com.facebook.react.common.JavascriptException: Invariant Violation: Module  is not a registered callable module (calling onShouldStartLoadWithRequest), stack:
    exports@9:286
    value@27:3215
    <unknown>@27:747
    value@27:2610
    value@27:719
    value@-1
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:919)
E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.redacted.redacted, PID: 14852
    com.facebook.react.common.JavascriptException: Invariant Violation: Module  is not a registered callable module (calling onShouldStartLoadWithRequest), stack:
    exports@9:286
    value@27:3215
    <unknown>@27:747
    value@27:2610
    value@27:719
    value@-1`

Here's my Package.json:

`{
  "name": "Redacted",
  "version": "4.6.0",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@dudigital/react-native-zoomable-view": "^1.0.15",
    "@invertase/react-native-apple-authentication": "^2.1.0",
    "@react-native-community/async-storage": "^1.6.2",
    "@react-native-community/netinfo": "^4.4.0",
    "@react-native-community/push-notification-ios": "^1.0.3",
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-add-calendar-event": "^2.3.1",
    "react-native-cached-image": "*",
    "react-native-calendars": "^1.212.0",
    "react-native-cookies": "^3.3.0",
    "react-native-deep-linking": "^2.2.0",
    "react-native-drawer": "^2.5.1",
    "react-native-elements": "^3.1.0",
    "react-native-fast-image": "^7.0.2",
    "react-native-fbsdk": "^1.0.4",
    "react-native-fetch-polyfill": "^1.1.3",
    "react-native-firebase": "^5.6.0",
    "react-native-gesture-handler": "^1.9.0",
    "react-native-htmlview": "^0.15.0",
    "react-native-iap": "^4.6.3",
    "react-native-image-crop-picker": "^0.26.1",
    "react-native-image-resizer": "^1.0.1",
    "react-native-loading-spinner-overlay": "^1.0.1",
    "react-native-maps": "^0.27.1",
    "react-native-modal-selector": "^2.0.3",
    "react-native-picker-select": "^6.3.3",
    "react-native-pinch-zoom-image": "0.0.10",
    "react-native-push-notification": "^3.1.9",
    "react-native-reanimated": "^1.4.0",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-screens": "^2.17.1",
    "react-native-snap-carousel": "^3.8.1",
    "react-native-stack": "^1.0.0-alpha11",
    "react-native-svg": "^9.11.1",
    "react-native-swipe-gestures": "^1.0.4",
    "react-native-vector-icons": "^8.0.0",
    "react-native-video": "^5.0.2",
    "react-native-webview": "^10.10.2",
    "react-navigation": "^4.4.3",
    "react-navigation-drawer": "^2.6.0",
    "react-navigation-stack": "^2.10.0",
    "react-redux": "^7.1.1",
    "redux": "^4.0.4",
    "rn-fetch-blob": "^0.11.2"
  },
  "devDependencies": {
    "@babel/core": "^7.8.4",
    "@babel/runtime": "^7.8.4",
    "@react-native-community/eslint-config": "^1.1.0",
    "babel-jest": "^25.1.0",
    "babel-plugin-module-resolver": "^3.2.0",
    "eslint": "^6.5.1",
    "jest": "^25.1.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-test-renderer": "16.13.1"
  },
  "jest": {
    "preset": "react-native"
  }
}`

Here's the code that calls the Webview:

`    return (
            <View style={{flex: 1, backgroudColor: 'white'}}>
            <WebView
              scalesPageToFit={true}
              showsHorizontalScrollIndicator={false}
              source={{ uri: this.state.url }}
              style={{ flex: 1 }}
              onLoadProgress={e => this.setState({loadProgress: e.nativeEvent.progress})}
              ref={(webview) => { this.webview = webview; }}
              userAgent='A custom user agent'
              onShouldStartLoadWithRequest={this.onShouldStartLoadWithRequest} 
               />
            </View>
            )`

I haven't found a solution yet. If anyone has any ideas - however hacky - I'd be very grateful! This is the last part I need for the Android release.

**Comment by jamiembrown** [comment]
Ok - so I've solved my own problem already. Whatever you do, do not set the state in the `onShouldStartLoadWithRequest` function (particularly not a state change that updates the webview) as that will cause it to crash - only on Android, it's fine on iOS.

**Comment by Gjoshi3107** [comment]
I am getting the same error.
Did not have this issue in version 7.4.1, updated to version 11.3.1 and it started coming.
And i am not even using the onShouldStartLoadWithRequest prop as well..

Please help

**Comment by AliRehman7141** [comment]
Any update on it?

**Comment by sa-whyayala** [comment]
Also having this issue in v10.0.0

**Comment by MyshkaDashka** [comment]
After update _react-native_  and raise version _react-native-webview_ error still here. 

"react-native": "0.64.2",
 "react-native-webview": "^11.6.5",

**Comment by tungduonghgg123** [comment]
anyone still facing this?

**Comment by karthikkun** [comment]
in my case removing the  duplicate line `include ':react-native-webview'` in the `settings.gradle` has worked.

**Comment by eurekaffeine** [comment]
Same here. And I would like to provide some clues may help you.
The initial version of my project was `9.4.0` and it worked like a charm. However, the issue mentioned above occurred when I upgrade to `11.x.x`. After investigating and comparing differences between versions of `com.reactnativecommunity.webview.RNCWebViewManager#shouldOverrideUrlLoading()`, I found that it should be related to the synchronous code logic. And it could also solve @kg-currenxie 's inspection that why it failed to repro on debug mode, since it directly jumps to the former code logic then:
```
if (!isJsDebugging && rncWebView.mCatalystInstance != null) {
    // synchronous code logic which may raise the issue
}else {
    // former code logic which won't raise the issue 
}

```

Since the synchronous functionality is not fully supported in iOS, shall we revert to the former code logic to resolve the issue?https://github.com/react-native-webview/react-native-webview/pull/1479

**Comment by magom001** [comment]
Please reopen this thread. Older versions are not compatible with Android SDK 33 and the newer one fails in CI with the error mentioned in the description.

**Comment by Titozzz** [comment]
Hey y'all, what's your react-native version ?

**Comment by magom001** [comment]
> Hey y'all, what's your react-native version ?

0.66

**Comment by Nyoob** [comment]
> Hey y'all, what's your react-native version ?

react-native 0.68.2, having this issue after upgrading react-native-webview from 10.4.1 to current release (11.26.1)

**Comment by timotheepicard** [comment]
still searching for solutions
react-native 0.71.0
react-native-webview 13.8.1

**Comment by timotheepicard** [comment]
> Hey @timotheepicard, I have a pull request #2833 to workaround this issue which did resolve my problem at that time. Glad to know if it is still viable for your case.

I tried your PR with no success
