### ISSUE TITLE
Loading icon is not visible when page loads

### ISSUE THREAD

**Issue by Balasnest** [react-native-webview/react-native-webview#1757]
**Bug description:**
Loading icon is not visible whenever webview loads the page. It's completely blank white screen for ~5 sec.

**To Reproduce:**
It's happening in the latest version all the time.

**Expected behavior:**
Loader icon should visible till webview ready to render.

**Environment:**
 - react-native version: "0.63.2"
 - react-native-webview version: "10.9.2"

**Comment by HessiPard** [comment]
have this problem too

**Comment by HessiPard** [comment]
Simple workaround solution:
1- just remove `startInLoadingState` prop
2- Get Webview `ref` and add this in `componentDidMount`:
```
componentDidMount() {
  if (this._webView) {
	setTimeout(() => {
	   this._webView.reload();
	}, 1000);
  }
}```

**Comment by Abhishek-Sankey** [comment]
Also facing the same issue on Android. It's working on iOS

**Comment by snamstorm** [comment]
Am also facing this issue on Android

**Comment by anoopjangra90** [comment]
Add you own custom Loading spinner. Display Loading spinner when WebView start loading and dismiss after complete loading of WebView.
