### ISSUE TITLE
Can't load html in IOS assets folder 

### ISSUE THREAD

**Issue by Zakyyy** [react-native-webview/react-native-webview#1758]
**Bug description:**
I have been using old version of react native webview and I just use the source.uri to have 'assets/html/Web.bundle/loader.html' and then I can load an html file stored in the assets folder 
but after updating the package to version 10.x.x, I can't load the file, I am getting Error loading page 

**Expected behavior:**
The webview should load the html file stored in assets folder in IOS

**Screenshots/Videos:**
`<WebView
              ref={(webview) => this.webview = webview}
              scrollEnabled={false}
              source={{uri: 'assets/html/Web.bundle/loader.html'}}
              javaScriptEnabled={true}
              startInLoadingState
              useWebKit={true}
              injectedJavaScript={injectedJS}
              originWhitelist={['*']}
              allowFileAccess={true}
              onMessage={(event) => { }}
            />`

**Environment:**
 - OS:Mac OS X
 - OS version:10.15.6
 - react-native version:0.61.5
 - react-native-webview version:10.10.2

**Comment by huxiaoqiao** [comment]
no answers?

**Comment by huxiaoqiao** [comment]
I have the same problem,can someone help me?

**Comment by GabrielWatanabe** [comment]
I have the same problem
