### ISSUE TITLE
Android "SSL Error: Hostname Mismatch"

### ISSUE THREAD

**Issue by Hantex9** [react-native-webview/react-native-webview#1764]
**Bug description:**
When I use the WebView on expo with an external uri which I'm not the owner (I'm doing an SSO page), if I open on iOS everything works fine, but if I try on Android it gives me error code 2 and I can't open the webpage. I don't know how to solve this in a good way, I'm using react-native with expo sdk 39

**Screenshots/Videos:**
![image](https://user-images.githubusercontent.com/34343582/100468010-cf5ad000-30d3-11eb-9e70-605f2bbcde4c.png)

**Environment:**
 - OS: Android
 - OS version: latest
 - react-native version: latest with expo
 - react-native-webview version: latest

**Comment by diVid3** [comment]
Having the exact same issue

**Comment by lorenzomalla** [comment]
Having the exact same issue.
I tryed to comment and add the handler.proceed(); in the onSslErrorHandler method inside the class of library WebViewManager of ract-native-webview, but Google rejected the binary when I try to publish the app.

**Comment by Shriken** [comment]
Having the same issue. Worked with plenty of valid SSL domains, then got the same error on production suddenly :(

**Comment by Daidalos117** [comment]
@nicollecastrog did you solve this? Same here. Sudden errors on production.
