### ISSUE TITLE
webview iOS issue.

### ISSUE THREAD

**Issue by callmemonky** [react-native-webview/react-native-webview#1765]
**Bug description:**

So I am trying to open a website which utilizes webRTC. So inshort my website is not compatible in chrome iOS but works completely fine in safari browser in my iphone 11.

I was building a react-native app for iOS which basically renders that website through webview but its not working. I tried changing userAgent but still doesnt work. Same app works completely fine in androids and webview is working completely fine.

Is there anything that I am missing? Can I do something to switch to safari webview and open my website inside ?

**Expected behavior:**
I need my webRTC website to work in webview in iOS App exactly the same as it works in Android.

**Screenshots/Videos:**

Code Snippetts
![image](https://user-images.githubusercontent.com/25193916/100518361-140b6780-31b7-11eb-8120-8f4afabf9b7a.png)
Output
![image](https://user-images.githubusercontent.com/25193916/100518385-38674400-31b7-11eb-9a88-d99320910b50.png)

**Environment:**
 - OS: iOS
 - OS version: iOS 14
 - react-native version: 0.63.2
 - react-native-webview version: 10.10.2

**Comment by sathwik77** [comment]
You need to set userAgent for IOS in AppDelegate.m file 
```  NSString *deviceType = [UIDevice currentDevice].model;
  UIWebView *webView = [[UIWebView alloc] initWithFrame:CGRectZero];
  NSString *oldAgent = [webView stringByEvaluatingJavaScriptFromString:@"navigator.userAgent"];
  NSString *newAgent = [oldAgent stringByAppendingString:@" MYAPPNAME - iOS - "];
  newAgent = [newAgent stringByAppendingString:deviceType];
  NSDictionary *dictionnary = [[NSDictionary alloc] initWithObjectsAndKeys:newAgent, @"UserAgent", nil];
  [[NSUserDefaults standardUserDefaults] registerDefaults:dictionnary];```

**Comment by callmemonky** [comment]
Hey @sathwik77, but does webview on iOS support webrtc?

**Comment by sathwik77** [comment]
No, it does not. If you try to access something like `getUserMedia` from web view even by setting userAgent as Safari it does not work

**Comment by callmemonky** [comment]
> No, it does not. If you try to access something like `getUserMedia` from web view even by setting userAgent as Safari it does not work

Any alternative?

**Comment by sathwik77** [comment]
You can try using [WebBrowser](https://docs.expo.io/versions/v39.0.0/sdk/webbrowser/) and redirect back to app after user finishing his session with required result, adding it as a query param . Web Browser uses safari view controller, `getUserMedia` should work in it PROBABLY

**Comment by MarwaAbuEssa** [comment]
the same issue here

**Comment by DmitryMorlender** [comment]
same issue here, I use OAuth with SSO.
When I enter my credentials the webview gets stuck in loading instead of receiving a redirect.
