### ISSUE TITLE
Erro in path WebView

### ISSUE THREAD

**Issue by marlonacademi** [react-native-webview/react-native-webview#1769]
Good afternoon everyone,

Today I added the dependency for my project and as soon as the app compiled the console it gave this message:

Unable to resolve module `./lib/WebView` from `node_modules/react-native-webview/index.js`: 

in a previous analysis in index.js the path to this component ./lib/WebView.

As soon as I changed the path to ./src/WebView react native started to recognize the component.

You could evaluate if this is a mistake, or if an extra step is needed so that the react native recognizes the component.

**Comment by KrzysztofSakowski** [comment]
I have also encountered this issue. It was also reported in #1163.
 
@marlonacademi are you also experiencing this issue on Mac?
