### ISSUE TITLE
Embed Youtube video autoplay not working

### ISSUE THREAD

**Issue by micheilsgrey** [react-native-webview/react-native-webview#1770]
**Bug description:**
Youtube embedded player not working correctly in webview. Autoplay not working.

**To Reproduce:**

```typescript
           <WebView
            mediaPlaybackRequiresUserAction={false}
            allowsInlineMediaPlayback={true}
// this prop makes autoplay right after loaded but its not allow go fullscreen since its embed for pc web not mobile if i understand it correctly
            //userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36" 
            source={{
               uri: `https://www.youtube.com/embed/${video.id}?autoplay=1&modestbranding=1&playsinline=1`,
            }}
          />
```

**Expected behavior:**
Autoplay right after video loaded in webview.

**Screenshots/Videos:**
Example with prop `userAgent`: https://streamable.com/w43awn
Example with expected behaviour but autoplay not working: https://streamable.com/qq57kj

**Environment:**
 - OS: iOS
 - OS version: 14.2
 - react-native version: 0.63.2
 - react-native-webview version:^11.0.0

**Comment by mounirzarkan** [comment]
any idea when this would be fixed ?

**Comment by MrXyfir** [comment]
Is there a user agent that fixes both issues?

**Comment by micheilsgrey** [comment]
> Is there a user agent that fixes both issues?
> 
> Also if you don't _need_ fullscreen (of course it'd be nice to have...) you can disable the button by passing `&fs=0` into the webview URL.

I do need fullscreen.

**Comment by RaviMopo** [comment]
HI, I'm facing same issue any help?
