### ISSUE TITLE
can't load html in Documents folder on iOS

### ISSUE THREAD

**Issue by huxiaoqiao** [react-native-webview/react-native-webview#1771]
[warn][tid:com.facebook.react.JavaScript] 'Error opening URL: ', [Error: Unable to open URL: file:///Users/huxiaoqiao/Library/Developer/CoreSimulator/Devices/7F9A49F1-B67D-4CDB-813D-C78F9CBC6873/data/Containers/Data/Application/FCF5F1E5-C840-4C77-9285-B94618DA0DEF/Documents/CIMOM/dist/index.html?/App/Message]

**Environment:**
 - OS:
 - OS version:
 - react-native version:0.6.15
 - react-native-webview version:11.0.0

**Comment by gebo96** [comment]
Same problem here.
