### ISSUE TITLE
Can't customize or change InputAccessoryView language on IOS

### ISSUE THREAD

**Issue by MortadhaFadhlaoui** [react-native-webview/react-native-webview#1772]
Hello,

Thank you in advance for your help.

**Bug description:**
I can't find a way to customize or change InputAccessoryView language  on IOS,
The only option is to hideKeyboardAccessoryView.

**Screenshots/Videos:**
![image](https://user-images.githubusercontent.com/17456573/101339984-6c113080-387f-11eb-9731-2eff594c030e.png)

**Environment:**
 - OS: IOS
 - react-native version: 0.62.2
 - react-native-webview version: 9.4.0

**Comment by DanielFilinski** [comment]
Adding localization to info.plist helped me solve these problems.
<key>CFBundleLocalizations</key>
	<array>
		<string>ru</string>
	</array>
