### ISSUE TITLE
requestFocus() crashes on iOS

### ISSUE THREAD

**Issue by marcelburda** [react-native-webview/react-native-webview#1773]
Hello,

the bug here: [issue 1021](https://github.com/react-native-webview/react-native-webview/issues/1021)

is still open and needs fixing. When you call requestFocus, the app crashes and the method does not work.
With multiple webviews, I need to tap before I can interact with the webview.

--->

**To Reproduce:**
Call the function and see the error on iOS

**Expected behavior:**
Focusing the webview

**Screenshots/Videos:**
see linked ticket

**Environment:**
 - OS: iOS
 - OS version: 14.2
 - react-native version: 0.63.3
 - react-native-webview version: 10.8.2

**Comment by Slapbox** [comment]
Anybody get this working? Still a no for us, even with `11.2.3`. We still get an identical error. Can anyone provide any insight on this?
