### ISSUE TITLE
why nested url open in browser on android

### ISSUE THREAD

**Issue by Liqiankun** [react-native-webview/react-native-webview#1775]
**Bug description:**
Click nested link on rendered web. It be opened in browser not in current webview. It works on iOS.

**To Reproduce:**
```js
<WebView
     ref={webRef}
     style={styles.container}
     source={{
        uri
     }}
     cacheEnabled={false}
     startInLoadingState
     onLoadEnd={e => {
        const { nativeEvent } = e;
        canGoBack = nativeEvent.canGoBack;
     }}
     onShouldStartLoadWithRequest={request => {
        if (request.url.startsWith('http://url.com')) {
          return false;
        }
        return true;
      }}
     renderLoading={() => (
         <ActivityIndicator />
     )}
/>
```

**Expected behavior:**
Open nested link in current webview.

**Screenshots/Videos:**
![browser](https://user-images.githubusercontent.com/11532418/101437600-86184500-394b-11eb-9df4-83f6c4fd4cb2.gif)

**Environment:**
 - OS: macOS
 - OS version: 10.15.5
 - react-native version: 0.62.2
 - react-native-webview version: ^11.0.0

**Comment by chinashelll** [comment]
after 11.0.0 setSupportMultipleWindows will do this

**Comment by Liqiankun** [comment]
@chinashelll OK, let me disable this.

**Comment by Liqiankun** [comment]
@chinashelll It works. Thanks man!

**Comment by artsnr1** [comment]
@Liqiankun @chinashelll  thanks a lot. I was having the same issue and wasn't able to figure out the cause . I thought it was due to form's blank target or iframe or idk.
