### ISSUE TITLE
injectedJavaScript is not working in IOS

### ISSUE THREAD

**Issue by sraza295** [react-native-webview/react-native-webview#1779]
**Bug description:**
I am using "react-native-webview": "^10.10.2". I am using "injectedJavaScript" in webview, this property is working fine in android but not working in ios.

**Code**
import React, { Component } from 'react';
import { WebView } from 'react-native-webview'

class App extends React.Component {
  constructor(props) {
    super(props);
    
  }

  componentDidMount(){
    
  }

myScript = () =>
`
    window.document.getElementsByTagName("header")[0].style.display = "none";
`

  render() {
    return (
      <WebView source={{ uri: "https://www.helpmefund.org/campaigns" }}
          injectedJavaScript={this.myScript()}
      />
    );
  }
}

export default App;

**Environment:**
 - OS:IOS
 - OS version:14.2
 - react-native version:0.63.3
 - react-native-webview version:10.10.2

**Comment by TimJung** [comment]
Also experiencing this issue. Works fine in Android.

**Comment by TimJung** [comment]
Hey @sraza295 I was able to fix the issue I was having by adding:
`onMessage={(event) => {}}`
as a prop to the WebView.
Solution found here:
https://github.com/react-native-webview/react-native-webview/blob/4d8a76f3691479ef22b55e05c07921af99332395/docs/Guide.md
under "Communicating between JS and Native".

Not sure why or when that became required because it definitely used to work without it. But perhaps that's the solution for you as well.

**Comment by sraza295** [comment]
@TimJung still not working :(

**Comment by eleanors** [comment]
> @TimJung still not working :(

injectedJavaScript  这里要返回字符串  injectedJavaScript={"document.body.fontSize = '18px'"}
ios 在 webview 加上这个  onMessage={(event) => {}}

**Comment by potatoengineer** [comment]
I have the same issue, javascript isn't being injected on iOS.

```
...
    const SCRIPT = `
    const meta = document.createElement('meta');
    meta.setAttribute('content', 'width=device-width, initial-scale=1.0, maximum-scale=1.0');
    meta.setAttribute('name', 'viewport');
    document.head.appendChild(meta);
    true;
    `;
    return <WebView source={{uri: myURL}} javaScriptEnabled onMessage={(event) => {}} 
    injectedJavaScript={SCRIPT} />
```

**Comment by stijnvanderlaan** [comment]
Adding a empty ref & onMessage fixed this for me:
```
onMessage={(event) => {}}
ref={() => {}}
```

**Comment by gunwooa** [comment]
> Hey @sraza295 I was able to fix the issue I was having by adding: `onMessage={(event) => {}}` as a prop to the WebView. Solution found here: https://github.com/react-native-webview/react-native-webview/blob/4d8a76f3691479ef22b55e05c07921af99332395/docs/Guide.md under "Communicating between JS and Native".
> 
> Not sure why or when that became required because it definitely used to work without it. But perhaps that's the solution for you as well.

Thank you. Thanks to you, I solved it.
