### ISSUE TITLE
iOS cookies: Regardless of 'sharedCookiesEnabled' value, NS/WK cookies (unreliably) synced

### ISSUE THREAD

**Issue by sampok** [react-native-webview/react-native-webview#1780]
**Bug description:**
Syncing of cookies on iOS between 'React Native side' (NSHTTPCookieStorage) and WKWebView seems not to follow [the documented `sharedCookiesEnabled` behavior](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Guide.md#managing-cookies) on a real device. I'm observing some type of delayed 'auto-sync' between the two sides and `sharedCookiesEnabled` prop value doesn't really have any effect. I'm seeing the 'auto-updating' happening only on a real device, not on simulator, and there seems to be some unpredictability in the behavior.

I initially observed the behavior with an app having cookies set both by Fetch requests responses and by a website inside react-native-webview WKWebKit. To make a self-contained demo, I put together a simple demo using just react-native-cookies and local react-native-webview. When you set a cookie either for 'React Native side' (NSHTTPCookieStorage) or WKWebView side, the other side often (but not always) updates with delay. Whether `sharedCookiesEnabled` is true or false doesn't seem to have an effect on this.

**Screenshots/Videos:**

<details>
<summary>Screen recordings</summary>
<p>

Setting NS cookie with 'sharedCookiesEnabled' being either undefined or true: WK sometimes updating with a delay:

![nsSet](https://user-images.githubusercontent.com/1516075/101707178-b568a800-3a58-11eb-889c-c8f835d11bc3.gif)

Setting WK cookie: The same happening with NS cookie

![wkSet](https://user-images.githubusercontent.com/1516075/101707184-b8639880-3a58-11eb-968f-e1032590f482.gif)

</p>
</details>  

**To Reproduce:**
Repository: https://github.com/sampok/cookiesync

<details>
<summary>See App.js in the project:</summary>
<p>

```js
import React, {useState, useCallback} from 'react';
import {StyleSheet, View, Text, Button} from 'react-native';
import WebView from 'react-native-webview';
import CookieManager from '@react-native-community/cookies';

const url = 'https://test.com';
const name = 'test';

const App = () => {
  const [nsCookieValues, setNsCookieValues] = useState([]);
  const [wkCookieValues, setWkCookieValues] = useState([]);

  const clearCookie = useCallback(async (useWebKit) => {
    setNsCookieValues([]);
    setWkCookieValues([]);
    CookieManager.clearByName(url, name, useWebKit);
  }, []);

  const setCookie = useCallback(async (useWebKit) => {
    CookieManager.set(
      url,
      {name, value: 'set', expires: '2030-01-01T12:00:00.00Z'},
      useWebKit,
    );
    let i = 0;
    while (i++ < 30) {
      CookieManager.get(url).then((cookies) =>
        setNsCookieValues((prev) => [...prev, cookies[name]?.value]),
      );
      CookieManager.get(url, true).then((cookies) =>
        setWkCookieValues((prev) => [...prev, cookies[name]?.value]),
      );
      await new Promise((resolve) => setTimeout(resolve, 300));
    }
  }, []);

  return (
    <View>
      <View style={styles.container}>
        <WebView
          originWhitelist={['*']}
          source={{html: '<p style="background: #eee; height: 100%;">Page</p>'}}
          // sharedCookiesEnabled={true} // 'syncs' cookies with or without this
        />
      </View>

      <View style={styles.horizontal}>
        <View style={styles.half}>
          <Button title="Clear NS Cookie" onPress={() => clearCookie(false)} />
        </View>
        <View style={styles.half}>
          <Button title="Clear WK Cookie" onPress={() => clearCookie(true)} />
        </View>
      </View>

      <View style={styles.horizontal}>
        <View style={styles.half}>
          <Button title="Set NS Cookie" onPress={() => setCookie(false)} />
        </View>
        <View style={styles.half}>
          <Button title="Set WK Cookie" onPress={() => setCookie(true)} />
        </View>
      </View>

      <View style={styles.horizontal}>
        <View style={styles.half}>
          {nsCookieValues.map((value, i) => (
            <Text key={i}>{value ?? '-'}</Text>
          ))}
        </View>

        <View style={styles.half}>
          {wkCookieValues.map((value, i) => (
            <Text key={i}>{value ?? '-'}</Text>
          ))}
        </View>
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {height: 200, backgroundColor: '#eeeeee'},
  horizontal: {flexDirection: 'row'},
  half: {width: '50%', alignItems: 'center'},
});

export default App;

```

</p>
</details>  

**Expected behavior:**
Cookie behavior should be reliable, and it should be possible to configure the cookie to be shared (or not shared) using the `sharedCookiesEnabled` prop.

**Environment:**
 - iOS SDKs 14.2 and 13.7 tested, on iOS 14.2 and 13.7 iPhones
 - react-native version: 0.63.4
 - react-native-webview version: 11.0.2
 - react-native-cookies version: 5.0.1

**Comment by blwinters** [comment]
@sampok Have you learned anything more about this issue?

**Comment by sampok** [comment]
Not really. I remember trying to read react-native-webview and React Native source code to find out where the 'syncing' takes place, but couldn't figure it out. I ended up not needing a reliable cookie sync for now, so I moved on. But it'd be great to find out what's going on here.

**Comment by Codelica** [comment]
Seeing this as well.  We use an RN/Expo login form with background fetch calls that return session cookies.  Works great, but webview won't have the cookies for some some small (but indeterminate :( ) amount of time.  Would love to for a sync or at least know when the sync has been made :)

**Comment by Kamill90** [comment]
Any news on this? Ios cookies are still not synced.

**Comment by amagnolo** [comment]
It seems that cookies are synced but only after a delay of around 30 seconds. This is undocumented and unexpected. Anybody found a way to reduce the delay or a method to flush/sync cookies on demand?

**Comment by allan-simon** [comment]
@Titozzz  (or an other maintener) can this issue be reopened  ,  IMHO is of good quality (with a reproducer etc. ) and the problem is still existing , so it's better to have this issue as reference rather than more recent . lower quality ones ?

**Comment by allan-simon** [comment]
Also is there a way to sponsor/bug bounty this so that it get more eyeballs ?

**Comment by Titozzz** [comment]
I've reopened the issue, keep in mind that I don't have time to deal with most of the issues, however this has a pull request maybe addressing it and I always end up reviewing/ merging PRs. I'm in the middle of fabric migration right now so my focus is a bit shifted toward that.

Regarding how you can sponsor/bounty, I've got github sponsors set up, can't promise it will change much the time I can allocate to work on this but support is always appreciated 👍.

**Comment by thiavila-sigma** [comment]
@Titozzz it would be awesome if you merge to master a simple working version of the new arch working with Fabric.

I saw plenty of people getting errors as 'Unimplemented component' (as of myself)...
<img width="337" alt="image" src="https://user-images.githubusercontent.com/72762356/193394585-7e1356f0-9d75-474c-8271-f4084ec6f468.png">

**Comment by cpintos-sc** [comment]
This is an ongoing issue at least for me.

**Comment by DSp4wN** [comment]
Still an issue
