### ISSUE TITLE
Intercept response headers to bypass CORs

### ISSUE THREAD

**Issue by benkaiser** [react-native-webview/react-native-webview#1781]
I'm looking to build a React Native wrapper for my Progressive Web App (PWA) at https://next.kaiserapps.com . ([source code of website here](https://github.com/benkaiser/stretto))

Right now the progressive web app works but relies on having [a chrome extension installed](https://github.com/benkaiser/Stretto-Helper-Extension) to bypass cross origin requests to enable certain functionality. On Android this means installing Kiwi Browser (supports extensions) and running the PWA from there.

I should be able to replicate the same behavior with a webview so long as I can intercept the response headers and allow the cross origin requests. Here is an [example of accomplishing the task with a native Android application](https://stackoverflow.com/a/34034037).

Is there any plans to support intercepting requests made by the webview to add extra headers?

**Comment by KrzysztofSakowski** [comment]
@benkaiser I was able to intercept requests on Android following this guide: https://github.com/react-native-webview/react-native-webview/blob/master/docs/Custom-Android.md. Maybe it will help you.

**Comment by Bardiamist** [comment]
Maybe `allowUniversalAccessFromFileURLs` can help

**Comment by albert17** [comment]
@KrzysztofSakowski Do you have an example somewhere?

**Comment by KrzysztofSakowski** [comment]
> @KrzysztofSakowski Do you have an example somewhere?

Sorry @albert17, I no longer have access to this code.
