### ISSUE TITLE
Override onCreateInputConnection for webview on android

### ISSUE THREAD

**Issue by albinekb** [react-native-webview/react-native-webview#1783]
**Is your feature request related to a problem? If so, Please describe.**
Android keyboards are hard to support in rich text editors because of IME

**Describe the solutions you came up with**
https://developer.android.com/reference/android/text/InputType#TYPE_NULL
Setting input type to TYPE_NULL, should make the keyboard emulate keypresses

**Additional context**
There are some docs about custom android code, https://github.com/react-native-webview/react-native-webview/blob/master/docs/Custom-Android.md

But I don't understand how to override `public InputConnection onCreateInputConnection(EditorInfo outAttrs) {`

**Comment by bittu1028** [comment]
@albinekb  did you find the solution to overide ?

**Comment by albinekb** [comment]
Yes @bittu1028, I used https://www.npmjs.com/package/patch-package
It proved to be a very stable and easy solution to this issue. However I don't use it anymore since slate.js updated and now supports android better.

`react-native-webview+11.14.0.patch`
```
diff --git a/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java b/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
index 291ada3..b63bdb3 100644
--- a/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
+++ b/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
@@ -101,6 +101,10 @@ import java.util.Locale;
 import java.util.Map;
 import java.util.concurrent.atomic.AtomicReference;
 
+import android.text.InputType;
+import android.view.inputmethod.EditorInfo;
+import android.view.inputmethod.InputConnection;
+
 /**
  * Manages instances of {@link WebView}
  * <p>
@@ -1475,6 +1479,16 @@ public class RNCWebViewManager extends SimpleViewManager<WebView> {
     protected boolean nestedScrollEnabled = false;
     protected ProgressChangedFilter progressChangedFilter;
 
+    @Override
+    public InputConnection onCreateInputConnection(EditorInfo outAttrs) {
+      InputConnection connection = super.onCreateInputConnection(outAttrs);
+
+      outAttrs.imeOptions = EditorInfo.IME_ACTION_DONE;
+      outAttrs.inputType = EditorInfo.TYPE_NULL;
+
+      return connection;
+    }
+
     /**
      * WebView must be created with an context of the current activity
      * <p>

```
