### ISSUE TITLE
Only RNWebview can't make connect to my page

### ISSUE THREAD

**Issue by neostom432** [react-native-webview/react-native-webview#1784]
**Bug description:**
Our webpage is in Korea but my client is in China.
When client uses my page, only RNWebview can't make connection to my page

This is error message =========
Error loading page

Domain: NSURLErrorDomain
Error Code: -1005
Description: The network connection was lost.
==========================

I tried pure IOS native WKWebview and it worked but RNWebview made error with same logic.

I found some articles about how to handle 1005 error. Most of theme said it happened when using Connection:Keep-Alive but our webpage doesn't use Keep-Alive.

Is there anything I can try?

**To Reproduce:**
It is Tricky because you should in China to try reproduce this.
I use VPN to test this issue in Korea but issue is not happened.
I think this issues is happened when client is in China. 
 
**Expected behavior:**
As same as pure WKWebview, our page can be loaded.

**Screenshots/Videos:**

**Environment:**
 - OS: IOS
 - OS version: 14
 - react-native version: 0.63.3
 - react-native-webview version: 11.0.0

**Comment by arys** [comment]
@jeafgilbert @neostom432 did anyone found a solution?

**Comment by zj-landeed** [comment]
encountered the same issue, location US, so not a VPN issue
