### ISSUE TITLE
'React/RCTViewManager.h' file not found 

### ISSUE THREAD

**Issue by uripre** [react-native-webview/react-native-webview#1789]
Reopening a bug report for #1064 - the bug is still happening. I initialized the repo as described in "Contributing.md", but the example fails to run for me for both iOS and Android. 

Any thoughts about how to go about fixing that one?

@Titozzz @jamonholmgren

**Comment by NightWarrior** [comment]
Anyone still having this issue, check your `ios/Podfile.lock` file and search for React, mine was being set to 0.11.0 for some reason while i was on 0.63.4 react native version. The issue causing that was in `package.json` file under `resolutions`, i deleted the followings and it fixed itself 

```
"@react-native-community/cli": "3.0.0-alpha.2",
"@react-native-community/cli-platform-android": "3.0.0-alpha.2",
"@react-native-community/cli-platform-ios": "3.0.0-alpha.2",
"@react-native-community/cli-tools": "2.8.3"
```
