### ISSUE TITLE
Unable to catch blob download

### ISSUE THREAD

**Issue by stefanchiriac** [react-native-webview/react-native-webview#1790]
I'm trying to catch blob url downloads to handle them manually since android is not supporting them and crashes the app, but I can't find a way to do it.
onShouldStartLoadWithRequest seems like is being triggered only when the react app loads, but after that no longer triggers.
The code below just prints **http://10.0.2.2:9000/**, but never **blob**

```
 const onShouldStartLoadWithRequest = (navigator: any) => {
    const {url} = navigator;
    console.log(url);
    if (url.includes('blob:')) {
      console.log('blob');
      webview.stopLoading();
      return false;
    }
    return true;
  };

  return (
    <WebView
      ref={(ref: any) => setWebView(ref)}
      originWhitelist={['*']}
      source={{uri: 'http://10.0.2.2:9000/'}}
      style={{}}
      allowFileAccess={true}
      allowFileAccessFromFileURLs={true}
      allowUniversalAccessFromFileURLs={true}
      javaScriptEnabled={true}
      domStorageEnabled={true}
      mixedContentMode={'always'}
      onFileDownload={onShouldStartLoadWithRequest}
      onShouldStartLoadWithRequest={onShouldStartLoadWithRequest}
      onNavigationStateChange={onShouldStartLoadWithRequest}
    />
  );
```

**Environment:**
 - OS: Android Embeded api 29
 - react-native version: 0.63.3
 - react-native-webview version: 11.0.2

**Comment by worstpractice** [comment]
I don't know about _handling_ blob URLs on Android, but in order to (at the very least) _not crash_ when navigating to blob URLs, I used the following snippet in the past:

```TypeScript
const SimplifiedExample = () => {
  const webViewRef = useRef<WebView>(null);

  const handleNavigationStateChange = ({ url }: WebViewNavigation) => {
    if (!url) return;

    if (url.startsWith("blob")) {
      webViewRef.current?.stopLoading();
      console.log("Prevented blob url from loading");
    }
  };

  return (
  <WebView
    allowFileAccess
    allowFileAccessFromFileURLs
    allowUniversalAccessFromFileURLs
    onNavigationStateChange={handleNavigationStateChange}
    ref={webViewRef}
  />
  );
};
```

If it still crashes, I seem to recall that not showing a loading spinner/rendering an error screen helped.

Hope this helps.

**Comment by stefanchiriac** [comment]
Is still crashing even without loading spinner. But thanks anyway for the solution.

For now I'm just using #1817

**Comment by LeonidVeremchuk** [comment]
I have a workaround
You need to change **originWhitelist**
originWhitelist={['http://*', 'https://*', 'blob:https', ....etc, you need to react]}
