### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by shweta-itilite** [react-native-webview/react-native-webview#1791]
**Bug description:**
IN iOS navigation to url works fine. But in android it's throwing SSL Error. When I am changing the function **onReceivedSslError** inside "node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java. Instead of handle.cancel() putting handle.procedd() works but that is not the clean way to do. Please help me with this.  
<img width="428" alt="Screenshot 2020-12-10 at 3 14 57 PM" src="https://user-images.githubusercontent.com/70196395/102044839-b2293f80-3dfd-11eb-96e0-a7faf1a9f7f8.png">

**Environment:**
 - OS:Mac
 - OS version:
 - react-native version: 0.61.2
 - react-native-webview version: 10.10.0

**Comment by ahelord** [comment]
I'm in the same situation

**Comment by sebadiaz-arg** [comment]
I've same issue. It would be very useful a prop for webview component to avoid the SSL certificate check.

**Comment by tomhaycockwest** [comment]
Same here

**Comment by congnt148** [comment]
I have same issue

**Comment by Surangaup** [comment]
Same issue.

**Comment by Surangaup** [comment]
After wasting many many days, **I build the APK file. It works on real mobile**. (Actually, I couldn't connect and debug on the real mobile) so I suggest you for ignoring this one.

**Comment by gengshenghong** [comment]
I've same issue. It would be very useful a prop for webview component to avoid the SSL certificate check :(

**Comment by Enoooch** [comment]
#1834

**Comment by Abhishek-Sankey** [comment]
Any update on this?

**Comment by ArtToledo** [comment]
I have the same problem, is there any solution? Rewriting node_modules as local is not allowed by google when uploading the apk

**Comment by developeromI89** [comment]
This occurs in versions 11.0.0 >=.
I tried in 9.4.0 and its working fine

**Comment by 2manoj1** [comment]
any update?

**Comment by sinafbd** [comment]
+1

**Comment by sdinesmvc** [comment]
+1

**Comment by gowtham-orgfarm** [comment]
Have anybody found solution ?

**Comment by tousif-p99soft** [comment]
+1

**Comment by abdullah2316** [comment]
same issue.

**Comment by rahul3399** [comment]
Same issue +1

**Comment by chunghn** [comment]
> Can anyone please help me for this? Getting same issue. iOS working fine but on Android getting security issue by adding proceed() method instead of cancel(). By calling proceed() method able to access external link in webview but on running security scan , scan get failed and showing security error for this stmt.

Hi. I have the same situation, how do you fix that?

**Comment by Dror-Bar** [comment]
I managed to solve this by by ignoring SSL on specific, predefined URL (so there is less of a security risk):
Here is an example patch-package file:

```
diff --git a/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java b/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
index c9d43d5..0c9af95 100644
--- a/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
+++ b/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
@@ -907,11 +907,15 @@ public class RNCWebViewManager extends SimpleViewManager<WebView> {
         // This is desired behavior. We later use these values to determine whether the request is a top-level navigation or a subresource request.
         String topWindowUrl = webView.getUrl();
         String failingUrl = error.getUrl();
+        int code = error.getPrimaryError();
+        boolean valid = code == SslError.SSL_UNTRUSTED && topWindowUrl.startsWith("https://example.com");  // CHANGE URL
 
         // Cancel request after obtaining top-level URL.
         // If request is cancelled before obtaining top-level URL, undesired behavior may occur.
         // Undesired behavior: Return value of WebView.getUrl() may be the current URL instead of the failing URL.
-        handler.cancel();
+        if (!valid) {
+          handler.cancel();
+        }
 
         if (!topWindowUrl.equalsIgnoreCase(failingUrl)) {
           // If error is not due to top-level navigation, then do not call onReceivedError()
@@ -919,7 +923,6 @@ public class RNCWebViewManager extends SimpleViewManager<WebView> {
           return;
         }
 
-        int code = error.getPrimaryError();
         String description = "";
         String descriptionPrefix = "SSL error: ";
 
@@ -941,6 +944,10 @@ public class RNCWebViewManager extends SimpleViewManager<WebView> {
             description = "The certificate is not yet valid";
             break;
           case SslError.SSL_UNTRUSTED:
+            if (valid) {
+              handler.proceed();
+              return;
+            }
             description = "The certificate authority is not trusted";
             break;
           default:

```

**Comment by dionatawijaya** [comment]
I got this problem on lower Android and iOs and fixed by change the CA Issuer. Previously I use Let'sEncrypt and fixed after change it to Google Trust Service.
