### ISSUE TITLE
window.ReactNativeWebView.postMessage don't work on iOS 12.4.8

### ISSUE THREAD

**Issue by huffmanX** [react-native-webview/react-native-webview#1792]
This method window.ReactNativeWebView.postMessage don't work on iOS 12.4.8, but it works well on iOS 14.0.1.

web：
window.ReactNativeWebView.postMessage(JSON.stringify(params))

react-native-webview：
<WebView
              style={{overflow: 'scroll', overflowY: 'hidden'}}
              source={{uri: url}}
              ref={'wv'}
              allowsInlineMediaPlayback={true}
              androidHardwareAccelerationDisabled={true}
              mixedContentMode={'compatibility'}
              allowsFullscreenVideo={true}
              javaScriptEnabled={true}
              injectedJavascript={INJECTED_JAVASCRIPT}
              onMessage={this.onJSBridgeMessage}
            />

onJSBridgeMessage = (e) => {
  console.log('onJSBridgeMessage', e.nativeEvent.data)
  };

**Environment:**
 - iOS version:12.4.8
 - react-native version:0.63.3.
 - react-native-webview version:11.0.2

**Comment by vermadivyanshu** [comment]
The issue still exists
