### ISSUE TITLE
Loading local JQuery in webview is crashing on runtime

### ISSUE THREAD

**Issue by umarzaman-dev** [react-native-webview/react-native-webview#1793]
When i try to load jQuery through CDN in web view it is working fine but when i try to inject it in web view through injectedscript it starts to give error on runtime. My application will run offline and its a legacy app with alot of JQuery code. We are migrating from another framework.  Can any one confirm that JQuery is supported locally in web view or is there a bug ?

Environemnt is Expo Bare Workflow.

**Comment by Yahyaali1** [comment]
Might want to attach the debugger to [webview](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Debugging.md) to check if there is syntax error with inject code. Might also want to check if jquery is loaded beforehand.

**Comment by norbertmadyar** [comment]
@umarzaman-dev you fixed this bug?

**Comment by umarzaman-dev** [comment]
No, we have stopped using WebView due to this limitation. We have recreated complete application in React-Native.
