### ISSUE TITLE
On the difference between IOS and Android in monitoring PostMessage from RN

### ISSUE THREAD

**Issue by ClownWang-1217** [react-native-webview/react-native-webview#1794]
After testing, I found a phenomenon that the HTML of IOS application must be used
window.addEventListener  To listen for PostMessage from RN. In Android applications, HTML must be used window.document.addEventListener  To listen for PostMessage from RN.
Why does this happen,

**Environment:**
 - react-native version:0.59
 - react-native-webview version:11.0

**Comment by FourwingsY** [comment]
Same here! Just want to communicate with Web-RN with postMessage, but this is not that clear.
Thanks to @ClownWang-1217 , document bypass is still working.
