### ISSUE TITLE
WF: _WebFilterIsActive returning: NO

### ISSUE THREAD

**Issue by FernandesTeu** [react-native-webview/react-native-webview#1798]
**Bug description:**
Estou com esse erro na utilização da webview para IOS. NO Android funciona perfeitamente.
Quando clico no link para abri a webview ele carrega o arquivo html, mas não carrega o conteudo dinamico que foi injetado via javascript.

a mensagem abaixo é exibida no console:

`WF: _userSettingsForUser mobile: {
      filterBlacklist =     (
      );
      filterWhitelist =     (
      );
      restrictWeb = 1;
      useContentFilter = 0;
      useContentFilterOverrides = 0;
      whitelistEnabled = 0;
}`

`WF: _WebFilterIsActive returning: NO`

**Environment:**
 - OS: Iphone 11
 - OS version: IOS 14.2
 - react-native version: 16.9
 - react-native-webview version: 61.5

**Comment by dxwave** [comment]
Has anyone tested on iOS 14.5 beta 2?

**Comment by originLeeLi** [comment]
同样遇到这问题，界面卡死。

**Comment by karthikmandava7** [comment]
I'm also facing the same issue, any solutions found on this?

**Comment by jason-elwood** [comment]
Same issue here.

**Comment by mksmanish** [comment]
I am also facing the same issue, any solutions found on this?

**Comment by basilbai** [comment]
Same issue here.
