### ISSUE TITLE
[iOS] load cookie failed when only config sharedCookiesEnabled == true

### ISSUE THREAD

**Issue by DingSoung** [react-native-webview/react-native-webview#1801]
**Bug description:**

iOS not load cookie when only `sharedCookiesEnabled == true`, because `incognito` or `cacheEnabled` is `true` by default.
the  default `WKWebsiteDataStore.httpCookieStore` of WKWebViewConfiguration `setCookie` failed

custom wkwebview's webviewconfiguration to WKWebsiteDataStore.nonPersistent() is needed to setcookie successfully

**To Reproduce:**
```js
 <WebView
          sharedCookiesEnabled={true}
          //incognito={false}
          //cacheEnabled={false}
          source={uri}
          onMessage={}
        />
```

**Expected behavior:**
cookie should be loaded

**Environment:**
 - OS: iOS
 - OS version: 14
 - react-native version: 0.6.11
 - react-native-webview version: 11.0.2

**Comment by Aure77** [comment]
Same weird problem on iOS ! Can someone re open this issue ?
`cacheEnabled={false}` also disable `localStorage` persistence...

**Comment by DingSoung** [comment]
@afcastano 

to load cookies, you should set `cacheRnabled={false}` and `incognito={false}`

**Comment by Aure77** [comment]
@Titozzz / @asklar / @jamonholmgren : can you re-open this issue ? Sharing cookies & persist data should works together on iOS webview.
