### ISSUE TITLE
Type com.reactnativecommunity.webview.BuildConfig is defined multiple times

### ISSUE THREAD

**Issue by ccs1428** [react-native-webview/react-native-webview#1802]
Using below packages in current application.
    "@react-native-community/async-storage": "^1.11.0",
    "@react-native-community/masked-view": "^0.1.10",
    "react-native-webview": "^11.0.2",

**Bug description:**

While development its working fine, when i take signed build application build failed with below error, i was on this error last 3 days. Please help.

**To Reproduce:**
Error: /react-native-webview/android/build/.transforms/934255b0981cee25c1088e05728c95ca/classes/classes.dex, Type com.reactnativecommunity.webview.BuildConfig is defined multiple times: /Volumes/DATA/Development/Projects-github/Rejith UW/QubeMeetApp/Qubemeet/node_modules/react-native-webview/android/build/.transforms/934255b0981cee25c1088e05728c95ca/classes/classes.dex, /Volumes/DATA/Development/Projects-github/Rejith UW/QubeMeetApp/Qubemeet/android/app/build/intermediates/external_libs_dex/release/mergeExtDexRelease/classes3.dex

**Expected behavior:**
It should build.

**Screenshots/Videos:**

**Environment:**
 - OS: Big Sur
 - OS version: 11.0.1
 - react-native version: 0.62.2
 - react-native-webview version: Latest

**Comment by IamDixit** [comment]
Did anyone found the solution for this?
