### ISSUE TITLE
net::ERR_CACHE_MISS

### ISSUE THREAD

**Issue by MakMoinee** [react-native-webview/react-native-webview#1807]
Encountered an error loading page, Object {
  "canGoBack": false,
  "canGoForward": false,
  "code": -1,
  "description": "net::ERR_CACHE_MISS",
  "loading": false,
  "target": 15,
  "title": "Webview Example",
  "url": "https://www.google.com.ph/",
}

Custom Component (ContentView.js): 
`import React, { Component } from 'react';
import { WebView } from 'react-native-webview';
var oldURL = '';
class ContentView extends Component {
  webview = null;
  oldURL = '';
  render() {
    return (
      <WebView
        ref={ref => (this.webview = ref)}
        source={{ html: `<!DOCTYPE html>
        <html>
        
        <head>
            <title>Webview Example</title>
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
        </head>
        
        <style>
            .app {
                font-size: 30px;
            }
        </style>
        
        <body>
            <div class="container h-100 d-flex justify-content-center">
                <div class="jumbotron my-auto">
                    <center>
                        <div class="loader"></div>
                    </center>
                </div>
            </div>
        
            <style type="text/css">
                html,
                body {
                    height: 100%;
                }
        
                .container {
                    padding: 0px;
                }
        
                .display-3 {
                    font-size: 2.0rem;
                }
        
                .jumbotron {
                    background: #fff;
                }
        
                .loader {
                    border: 10px solid #f3f3f3;
                    border-radius: 50%;
                    border-top: 10px solid #09ae00;
                    margin-top: 200px;
                    width: 50px;
                    height: 50px;
                    -webkit-animation: 2s linear infinite;
                    /* Safari */
                    animation: spin 2s linear infinite;
                }
        
                /* Safari */
                @-webkit-keyframes spin {
                    0% {
                        -webkit-transform: rotate(0deg);
                    }
        
                    100% {
                        -webkit-transform: rotate(360deg);
                    }
                }
        
                @keyframes spin {
                    0% {
                        -webkit-transform: rotate(0deg);
                    }
        
                    100% {
                        -webkit-transform: rotate(360deg);
                    }
                }
            </style>
            <script type="text/javascript">
                setTimeout(function () {
                    window.location = "https://www.google.com.ph/"
                }, 1000);
            </script>
        </body>
        
        </html>` }}
        onNavigationStateChange={this.handleWebViewNavigationStateChange}
      />
    );
  }

  handleWebViewNavigationStateChange = newNavState => {

    const { url } = newNavState;
    console.log(newNavState);
    console.log('/n')
    if (!url) return;
    
    // // redirect somewhere else
    if (!url.includes('https://www.google.com.ph')) {
    //   const newURL = 'https://www.google.com.ph';
      const redirectTo = 'window.location = "' + oldURL + '"';
      this.webview.injectJavaScript(redirectTo);
    }else{
        oldURL = url
    }
  };
}
export function getOldUrl(){
    return oldURL;
}
export default ContentView`

ISSUE:
cannot load the page but in IOS it works fine

**Comment by Momoske** [comment]
Hey, did you manage to fix your issue? If so, can you please explain how? I'm having the same issue on Android but not iOS.

Seriously, OPs closing issues without giving an explanation should be a crime.

**Comment by MakMoinee** [comment]
For android, it will not work unless you build an apk and manually install it.

**Comment by Momoske** [comment]
Thanks a lot for the reply.

This is super weird, as it works perfectly fine on my test device (from 2014!) and my Android Studio emulator, but not my main device. I'll edit and report back if building the app fixes it for me, thanks again.
