### ISSUE TITLE
Website opening in portrait mode regardless of orientation

### ISSUE THREAD

**Issue by joshualimpj** [react-native-webview/react-native-webview#1808]
<WebView
  ref={webview => setWebview(webview)}
  source={{uri: `https://google.com`}}
/>

<img width="678" alt="Screen Shot 2021-01-03 at 11 50 30 PM" src="https://user-images.githubusercontent.com/23138695/103482891-77c02a80-4e1e-11eb-8266-c23aeb4c486d.png">

I initially thought it was my React website acting up, but it seems like every single website behaves like this. 

The rest of the pages on my App are all showing in landscape mode, apart from the webview.

Does anybody have an idea? Thank you

**Comment by joshualimpj** [comment]
"react-native-webview": "^10.8.2"
 "react-native": "0.61.5"

**Comment by cokealmonacid** [comment]
@joshualimpj Any news on this?

**Comment by JamieERead** [comment]
I'm having this exact issue, can this be reopened as it is still happening. 
The webview does not respect screen orientation change.

**Comment by ianvasco** [comment]
Having the same issue 
    "react-native": "0.67.2",
    "react-native-webview": "^11.18.2",

**Comment by pavel25437** [comment]
The same issue
"react-native": "0.70.0",
"react-native-webview": "11.23.1",

**Comment by sparcbr** [comment]
I also have this problem
