### ISSUE TITLE
Unable to detect PhoneNumber in dataDetectorTypes={['phoneNumber']}

### ISSUE THREAD

**Issue by kkadapa** [react-native-webview/react-native-webview#1816]
Hello we're using "react-native-webview": "^11.0.2", and our WebView is unable to detect Phone numbers even in iOS 14+ iPhones

Can someone kindly help?

```
<WebView
source={renderedOnce ? {uri: url} : reload}                                        
dataDetectorTypes={['phoneNumber']}
/>
```

**Comment by morpheis91** [comment]
This still an issue?  I would like to have it fixed if possible

**Comment by kkadapa** [comment]
Just wanted to follow-up and see if this issue is fixed.

**Comment by manosKas** [comment]
I'm interested too in this issue!

**Comment by fahry-mohammed** [comment]
Still its an issue in the Android OS
