### ISSUE TITLE
How to caputure the url of a page if its not refreshed (SPA like apps)

### ISSUE THREAD

**Issue by royalbhati** [react-native-webview/react-native-webview#1818]
I am able to capture url of webview using onNavigationStateChange but it only captures url when the page is refreshed but when the page is not refreshed the url is not captured

Is this possible if yes then how?

**Comment by Stevemoretz** [comment]
> I am able to capture url of webview using onNavigationStateChange but it only captures url when the page is refreshed but when the page is not refreshed the url is not captured
> 
> Is this possible if yes then how?

if onNavigationStateChange is not triggered you should, inject javascript and get the changes via javascript.
