### ISSUE TITLE
Question: How to "augment" the webview?

### ISSUE THREAD

**Issue by awkpagong** [react-native-webview/react-native-webview#1820]
**Is your feature request related to a problem? If so, Please describe.**

I'm trying to convert Facebook Pixel Events from my web app to Facebook App Events when inside my mobile app's webview. To do so Facebook requires you to augment the webview. See https://developers.facebook.com/docs/app-events/hybrid-app-events 

**Describe the solutions you came up with**

I am not sure how to do this... Is there a way to augment the react-native webview? Any help is greatly appreciated!

**Additional context**

Need a way to call `AppEventsLogger.augmentWebView(<YOUR_WEBVIEW_OBJECT>, <YOUR_ANDROID_CONTEXT>)` on Android and need a way to call `[FBSDKAppEvents augmentHybridWKWebView:<YOUR_WK_WEB_VIEW_OBJECT>];` on iOS.

**Comment by ouuyea** [comment]
I have the same question, has anyone coped with this task?
