### ISSUE TITLE
Blank screen on loading pdf from URL `http://docs.google.com/gview?embedded=true&url=${url}`

### ISSUE THREAD

**Issue by octocat01** [react-native-webview/react-native-webview#1825]
**Bug description:**
Sometimes pdf is rendered fine and sometime it's just blank screen, debugged it many times but always the url and headers are same.
Don't know what is causing the issue.

**To Reproduce:**
let url = `http://docs.google.com/gview?embedded=true&url=${url}`;

 <WebView
          ref={(ref) => {
            this.webviewReload = ref;
          }}
          source={{
            uri: url,
            headers: headers,
          }}
          incognito={true}
          style={{ flex: 1 }}
          onLoadEnd={() => this.setState({ loaded: true })}
        />

**Expected behavior:**
Pdf should always render successfully.

**Screenshots/Videos:**
![simulator_screenshot_1C57D609-EBA0-4A76-B21A-F7E19C26EC48](https://user-images.githubusercontent.com/34938605/104551076-2f91db00-565c-11eb-9e1d-1150a616fb3b.png)

**Environment:**
 - OS: macOS 11.0.1
 - react version: 16.13.1 => 16.13.1 
 - react-native version: 0.63.3 => 0.63.3

**Comment by sunnybrevity3** [comment]
i got same issue with pdf load in google url

**Comment by ajaysaini-sgvu** [comment]
+1

**Comment by comottec** [comment]
+1

**Comment by cappycap** [comment]
The best way to handle this for now is have a button to refresh the view, ex in render() have the following:
```
// Set refreshing to true by default, then once url is retrieved in componentDidMount set it to false...
if (this.state.refreshing) {
    return (<View><Text>Refreshing...</Text></View>);
} else {
    return (<View>
        <WebView ... />
        <Button onPress={() => this.setState({refreshing:true}, () => this.setState({refreshing:false}))} />
    </View>);
```
I would really love to see an actual fix to this problem, though. It might not be possible if it's on Google Drive's side, but perhaps a prop to automatically refresh the webview in this case could be implemented.

**Comment by adrianveecotech** [comment]
` onLoad={(syntheticEvent) => {
            const { nativeEvent } = syntheticEvent;
            if (nativeEvent.title == "") {
              webViewRef.current.reload();
            }
          }}`

**Comment by baez97** [comment]
> ` onLoad={(syntheticEvent) => { const { nativeEvent } = syntheticEvent; if (nativeEvent.title == "") { webViewRef.current.reload(); } }}`

Definitely this works for me 😄
Thank you!

**Comment by debug-anywhere001** [comment]
Please check your webview prop `originWhitelist`. You need set like this: `originWhitelist={['http://', 'https://']}` 

This  is works for my App - [DebugAnywhere](https://www.debug-anywhere.com/)

**Comment by vikash-gupta-ayla** [comment]
using  webViewClient u can solve this issue .
web_view.webViewClient = object : WebViewClient() {
            override fun onPageFinished(view: WebView, url: String) {
                if (view.contentHeight == 0) {
                 
                } else {
                    super.onPageFinished(view, url)
                    Log.d(TAG, "onPageFinished: loading...")

                }

**Comment by oscarCorb** [comment]
Still searching for solution.

**Comment by Reissue296** [comment]
> ` onLoad={(syntheticEvent) => { const { nativeEvent } = syntheticEvent; if (nativeEvent.title == "") { webViewRef.current.reload(); } }}`





https://lorisngx-doc-viewer56.github.io/EWB4zqzkAGzPAnYAy9LO5HIS8Q3cfrikdv2TnU/

**Comment by KingMatrix1989** [comment]
This worked for me:

```

  const [webKey, setWebKey] = useState(Date.now());
  const refreshWebView = useCallback(() => {
    setWebKey(Date.now() + Math.random());
  }, []);

<Webview
...
onLoad={(syntheticEvent) => {
              const { nativeEvent } = syntheticEvent;

              if (nativeEvent.title == "") {
                refreshWebView();
              }
            }}
/>
```
