### ISSUE TITLE
Iframe not show on IOS

### ISSUE THREAD

**Issue by chipcop106** [react-native-webview/react-native-webview#1832]
**Bug description:**
- Iframe not load on IOS, just working on Android.
- I have use inline html have iframe code to embed youtube video. But it's not working on IOS, it's just show blank page.

**To Reproduce:**

**Expected behavior:**
Load iframe inside webview.

**Screenshots/Videos:**
**Webview setting:** 
![image](https://user-images.githubusercontent.com/17249557/105030964-2c955100-5a87-11eb-968f-1376fdf4e733.png)

**Result on IOS:**
![image](https://user-images.githubusercontent.com/17249557/105031043-4afb4c80-5a87-11eb-902f-8a3c584464b7.png)

**Environment:**
 - OS: Ios
 - OS version: 14.3
 - react-native version: 0.63
 - react-native-webview version: 11.0.0

**Comment by ahdam** [comment]
any news on this?

**Comment by chipcop106** [comment]
Any new update here ?

**Comment by pradhul-dev** [comment]
Facing the same issue here , a public embed link is showing white page in iOS @chipcop106  did you find any solution for this?
