### ISSUE TITLE
Unable to embed tiktok video

### ISSUE THREAD

**Issue by buffaloDeveloper** [react-native-webview/react-native-webview#1837]
Trying to get the TikTok embed code to render correctly.  Here's an example of the embed code:

`<blockquote class=\"tiktok-embed\" cite=\"https://www.tiktok.com/@blaiseeeeeeeeeeeee/video/6893593227308322054\" data-video-id=\"6893593227308322054\" style=\"max-width: 605px;min-width: 325px;\" > <section> <a target=\"_blank\" title=\"@blaiseeeeeeeeeeeee\" href=\"https://www.tiktok.com/@blaiseeeeeeeeeeeee\">@blaiseeeeeeeeeeeee</a> <p>Can i have both?😂 <a title=\"foryou\" target=\"_blank\" href=\"https://www.tiktok.com/tag/foryou\">#foryou</a> <a title=\"couples\" target=\"_blank\" href=\"https://www.tiktok.com/tag/couples\">#couples</a> <a title=\"blaiseeeeeeeeeeee\" target=\"_blank\" href=\"https://www.tiktok.com/tag/blaiseeeeeeeeeeee\">#blaiseeeeeeeeeeee</a></p> <a target=\"_blank\" title=\"♬ original sound - dnek\" href=\"https://www.tiktok.com/music/original-sound-6893593271226927877\">♬ original sound - dnek</a> </section> </blockquote> <script async src=\"https://www.tiktok.com/embed.js\"></script>`

I've tried many of the options for this component, but can't seem to get the TikTok embed.js to execute.

```
<RNWebView
	source={ {html: media.videoEmbedHtml} }
/>
```

Note, it works fine with **react-native-web-webview**.

**Comment by scottkatzelnick** [comment]
Hi buffaloDeveloper,

Just in case you're still wondering how to get it to work, it took a ton of trial and error, but I finally got it working. It actually will work two ways, but the second is more in line with what you are after based on your OP.

**First Approach:**

Just use the WebView component from ```react-native-webview```  and instead of using the embed code, just put the URL of the post itself. If you want it to dynamically show posts you could return the TikTok user and video Id from your server or something like that, I just built a regex resolver that returns the user and Id from a user inputted share link, and then I use JavaScript string literals in the URL. 

Example 1:

```javascript
return (
  <WebView
    allowsInlineMediaPlayback: true, // self-explanntory
    scrollEnabled: false,  // self-explanntory
    allowsFullscreenVideo: false,  // not sure if this is applicable for the webview but don't want users causing weird bugs
    domStorageEnabled: true,  // for TikTok's caching purposes
    javaScriptEnabled: true,  // so the all-to-import script tag will run in the rendered HTML
    originWhitelist={['*']},  // Allows the requests content header to TikTok to accept any IP address, pretty much
    source={{url: `https://www.tiktok.com/@${props.user}/video/${props.tiktokId`}}
  />
)
```

**Second Approach:**

Since WebView content can come back dynamically sized and I prefer to use the embed code that TikTok gives us since the result is a nicely formed TikTok post. I am using a third-party library that fixes a lot of the ```react-native-webview```'s shortcomings. It's called ```@formidable-webview/webshell``` and it's really a great library. The link to their site is [here](https://formidable-webview.github.io/webshell/).

Pretty much you wrap the native WebView, apply some dynamically resizing methods, and apply the same props to the WebShell that I included in the WebView only example above. You can read through their site to see all of their options since they offer two-way communication between your app and the WebView, but my implementation looks something like the example below. The key to this method working is to include the baseUrl option of the source prop under the TikTok blockquote.

Example 2:

```javascript
import React from 'react'
// import { View, TouchableOpacity } from 'react-native'
import { WebView } from 'react-native-webview'
import useWebshell, {
  HandleHTMLDimensionsFeature,
  ForceResponsiveViewportFeature,
  ForceElementSizeFeature,
  useAutoheight,
} from '@formidable-webview/webshell'
import styled, { css } from 'styled-components/native'
import { fonts, colors } from '~/styles'
import { vw } from 'react-native-expo-viewport-units'
import { View } from 'react-native'

const Webshell = useWebshell(
  WebView,
  new HandleHTMLDimensionsFeature(),
  new ForceResponsiveViewportFeature({ maxScale: 1 }),
  new ForceElementSizeFeature({
    target: 'body',
    heightValue: 'auto',
    widthValue: 'auto',
  })
)

export default function InstagramPost(props) {
  if (!props.tiktokId) {
    return (
      <VideoPlaceholder>
        <VideoPlaceholderText>{props.placeholder}</VideoPlaceholderText>
      </VideoPlaceholder>
    )
  }

  const { autoheightWebshellProps } = useAutoheight({
    resetHeightOnViewportWidthChange: true,
    webshellProps: {
      ...props,
      //   style: { borderRadius: 15, overflow: 'hidden' },
      allowsInlineMediaPlayback: true,
      scrollEnabled: false,
      allowsFullscreenVideo: false,
      domStorageEnabled: true,
      originWhitelist: ['*'],
      javaScriptEnabled: true,
      source: {
        html: `<blockquote class="tiktok-embed" cite="https://www.tiktok.com/@${props.user}/video/${props.tiktokId}" data-video-id=${props.tiktokId} style="max-width: 768px !important; min-width: 200px !important;" > <section></section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>`,
        baseUrl: 'https://www.tiktok.com',
      },
    },
  })

  return (
    <View>
      <Webshell {...autoheightWebshellProps} />
    </View>
  )
}
```

Good luck!

**Comment by buffaloDeveloper** [comment]
@scottkatzelnick wow!  Thanks for the effort you put into these solutions.  Will check them out.

**Comment by scottkatzelnick** [comment]
Np problem. Lemme know if it still gives you trouble.

**Comment by DKetaki** [comment]
My answer is derived from @scottkatzelnick 's.

Please find below snippet. you can load the video with embedded code the key is you have to add baseURL in source. Thats it. 
```ruby
             < WebView 
                 ref={ref => (this.webview = ref)}
                 style ={{width: 500,height: 500}}
                 javaScriptEnabled={true}
                 scalesPageToFit={true}
                 viewportContent={`width=${Dimensions.get('window').width}, user-scalable=yes`}
                 scrollEnabled={this.state.height == 0}
                 onShouldStartLoadWithRequest={this.openExternalLink}
                 showsHorizontalScrollIndicator={false}
                 showsVerticalScrollIndicator={false}
                 scrollEnabledWithZoomedin={false}
                 allowsFullscreenVideo = {true}
                 allowsInlineMediaPlayback = {true}
                 androidHardwareAccelerationDisabled={false}
                 mixedContentMode='always'
                 source={{ 
                    baseUrl: 'https://www.tiktok.com',
                    html: content
              }} />
```


I have tested it in iOS version. and it works fine.

**Comment by fukemy** [comment]
I have problem when share tiktok url to my app, https://vt.tiktok.com/ZS8B8EMUF/ => the webview always display trends video, it's does not open exactly video

**Comment by ChristopherGabba** [comment]
The second approach with formiddable did work well. I am wondering if there is a way to inject javascript to programmatically unmute the tiktok video automatically after loading? I've also noticed with this approach, the tiktok video vs the webview loading is different. Basically you would think after the WebView prop onLoadEnd hits the tiktok video would autoplay, but it can actually be a few more seconds. Wondering if there is a way to get the tiktok video loading status...

**Comment by TanyaZhecheva** [comment]
@scottkz I used your first aproach, but the cookies consent always show.
I've tried adding    sharedCookiesEnabled={true} and thirdPartyCookiesEnabled={true} but they still show.
Any ideas how i can manage that?

**Comment by Zeeshan404** [comment]
Checkout this related package for iframe tiktok video https://github.com/zeeshan404/react-native-tiktok-iframe
