### ISSUE TITLE
multiple webview not supporting

### ISSUE THREAD

**Issue by maduraherath8** [react-native-webview/react-native-webview#1841]
**Bug description:**

In my webview im having a pgw with js enabled popup window.previously (5.12.0) it was woked by adding      `settings.setJavaScriptCanOpenWindowsAutomatically(true);`   in  RNCWebViewManager.java on react-native-webview manually.In the latest version of react-native-webview(11.2.0) introduces that property in the same way.but its not open new window. Or its opening under my original webview.Please help me to resolve this issue.

**To Reproduce:**

Try to open js enabled popup window in the react-native-webview.

**Expected behavior:**

Expected Popup windos is not showing.

**Screenshots/Videos:**

**Environment:**
 - OS: linux
 - OS version:
 - react-native version:  0.62.2
 - react-native-webview version:11.2.0

**Comment by redism** [comment]
I can confirm 9.4.0 is also working correctly. (11.0.2 version always opened up popup on chrome browser on android)
