### ISSUE TITLE
DRM protected streams won't play

### ISSUE THREAD

**Issue by crasyboy42** [react-native-webview/react-native-webview#1849]
**Bug description:**
I am having issues with DRM protected streams
When playing it gives the error "DRM: Keysystem Access Denied! -- key system access  unsupported keysystem or supportedConfigurations"

**To Reproduce:**
Use this url as source: https://www.npostart.nl/live/npo-1 and then click on the play icon
No parameters whatsover just the source

**Expected behavior:**
That the stream would simply play like it does in Chrome itself.

**Environment:**
 - OS: Android 
 - OS version: 7.0
 - react-native version: 0.63.3
 - react-native-webview version: 7.6.0

**Comment by mustafakameldev** [comment]
I'm having the same issue

**Comment by crasyboy42** [comment]
@mustafakameldev It should be working in the latest release from what i can see, if not check these changes that fixed it for me back in the day
https://github.com/react-native-webview/react-native-webview/pull/1862/commits/e115357d70ab900f1748671ebec78bc4c68dc30b

**Comment by chaudev** [comment]
I'm having the same problem, it's crazy that I can't find a solution either from DRM or react-native-webview. I have tried everything both on Android and IOS.

**Comment by ColtraneNadler** [comment]
Hey @chaudev did you manage to find a solution?
