### ISSUE TITLE
On Android, applicationNameForUserAgent only works on first request, not on further navigation

### ISSUE THREAD

**Issue by lucaong** [react-native-webview/react-native-webview#1851]
**Bug description:**

On Android, `applicationNameForUserAgent` sets the user agent on the first request, but further navigation requests use the default user agent.

**To Reproduce:**

  - Create an app that use the `WebView`, set `applicationNameForUserAgent` to something, say `MyApp/1.2.3`.
  - When the WebView opens, the user agent respects the given `applicationNameForUserAgent` in both iOS and Android (I did not test other platforms)
  - Now click on a link inside the WebView, to cause a navigation (full page reload, not a one-page app)
  - If a link is followed inside the WebView, so that another page is requested, this second request does not respect the `applicationNameForUserAgent` on Android (on iOS it does).

**Expected behavior:**

Any HTTP request performed by the WebView uses a user agent consistent with `applicationNameForUserAgent`

**Environment:**
 - OS: Android
 - react-native version: react-native@0.63.3
 - react-native-webview version: react-native-webview@10.10.2

**Comment by kylerc** [comment]
I'm also encountering this in an app we're also working with where the UA only is sent on the first load, but not on subsequent navigations on Android, but is sent on the first and all following navigations for iOS.  Not sure if anyone has found a workaround or solution for this?

**Comment by jackkinsella** [comment]
I can confirm this behavior still exists. (Not sure if it's meant as a bug or a feature)

One workaround is to detect `; wv)`  in the user agent since this automatically added by the Android webview https://developer.chrome.com/docs/multidevice/user-agent/

**Comment by fl-nishida** [comment]
This issue still exists on ver 15.70. any further update?
    "@react-native-firebase/analytics": "^15.7.0",
    "@react-native-firebase/app": "^15.7.0",
    "@react-native-firebase/auth": "^15.7.0",
    "@react-native-firebase/crashlytics": "^15.7.0",
    "@react-native-firebase/database": "^15.7.0",
    "@react-native-firebase/dynamic-links": "^15.7.0",
    "@react-native-firebase/messaging": "^15.7.0",
    "@react-native-firebase/remote-config": "^15.7.0",
