### ISSUE TITLE
How to open external links in the WebView (not in the browser)

### ISSUE THREAD

**Issue by ghost** [react-native-webview/react-native-webview#1853]
I just wanted to know if there's any way so that links (some of them which open in external browser) could be opened in the WebView only and not in the external browser. (Function based solution would be better!)

**Comment by christophby** [comment]
@ghost did you find a way to solve that?

**Comment by HritikR** [comment]
Use `setSupportMultipleWindows={false}` for opening link in the webview (not in external web browser)
