### ISSUE TITLE
React-Native-Windows not build

### ISSUE THREAD

**Issue by maribeiroleya** [react-native-webview/react-native-webview#1861]
I am creating a new react-native app. I only install the react-native, react-native-windows and react-native-webview. When i run the command npx react-native run-windows i receive the error:

Error This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is C:\....\windows\packages\Microsoft.Windows.CppWinRT.2.0.200729.8\build\native\Microsoft.Windows.CppWinRT.props.    ReactNativeWebView    C:\...\node_modules\react-native-webview\windows\WebViewBridgeComponent\WebViewBridgeComponent.vcxproj 

I need the solution for this problem, please.

Environment:
 - OS: windows 10
 - OS version: 19042.746
 - react-native version:0.63.4
 - react-native-webview version:11.2.1

**Comment by true-hamid** [comment]
We are facing the same issue as well

**Comment by aalbaharnah** [comment]
I was able to build my app after changing the solution platform in visual studio from `x64` to `x86`

** Environment**
 - OS: windows 10 pro
 - OS version: 18363.1316
 - react-native version: 0.63.4
 - react-native-webview version: ^11.2.3
 - react-native-windows: ^0.63.0-0
 - react-native-windows language: cs

**Comment by dd-apt** [comment]
I was only able to get this working by adding the WebViewBridgeComponent project to the main Windows app solution. At that point, the Nuget package required will be restored at build.

Note: even if you remove the project, locally it will still build after this (since nuget package is downloaded). However, it will not build on a different machine / CI build.

**Comment by harrisrobin** [comment]
Also facing this issue on windows:

![Error-message_mmr-huv](https://user-images.githubusercontent.com/3880008/108807346-0583e080-7559-11eb-832b-7b8b47e29f58.png)

This can be reproduced by simply trying to build the project with `11.2.3`. 
here's an example repo here:
https://github.com/harrisrobin/windows-react-native-webview-repro

**Comment by maribeiroleya** [comment]
The solution of @dd-apt works! @harrisrobin  if you are debugging you have to build x86.

**Comment by harrisrobin** [comment]
I can confirm @dd-apt 's solution works.

**Comment by VMBindraban** [comment]
This seems to be still the issue after 2 years with version 13.6.3. Can we document this somewhere?
