### ISSUE TITLE
Accessibility for content within the webview

### ISSUE THREAD

**Issue by anutting** [react-native-webview/react-native-webview#1863]
Can mobile screen readers traverse the content within the WebView, assuming the content is tagged correctly?

**Comment by AlanSl** [comment]
It looks like you can, so long as you **don't** pass the `accessible` prop on the `WebView`. 

If you do pass that prop as true, the whole WebView is treated as one item: on iOS it seems `accessibilityLabel` etc is applied correctly, but it seems to only have the label "WebView" on Android regardless of what accessibility is passed. 

If `accessible` prop is **not** true, then VoiceOver / TalkBack left and right swipes flick through the individual items within the web view as if they were part of the screen.

**Comment by sandeep-maikhuri** [comment]
Talkback always reads "Webview" in android for my case. Any luck with the issue?

**Comment by mitchdowney** [comment]
Just ran into the same issue as @sandeep-maikhuri. On Android Talkbalk always says "Webview". I tried setting `accessible={false}` and `importantForAccessibility='no'` but Talkback still says Webview.

Actually I just found [this StackOverflow answer](https://stackoverflow.com/questions/68039308/android-skip-focus-of-webview-and-go-straight-to-content-with-talkback), and according to his investigation the announcement can't be disabled. Seems to be an Android best practice to always announce for a user when they're entering a Webview.

**Comment by meatnordrink** [comment]
One potential wrinkle on this issue I've found, and thought I'd post in case it helps someone else at some point - 

I've observed, as I believe the OP described, Android Talkback fully failing to recognize _ANY_ content within a webview. When this happens, I've found that closing the app, and restarting it _with Android talkback already enabled_ addresses the issue. (i.e., if you open your app, _then_ enable Talkback - as you might if you're a dev just testing a feature - sometimes webview content will be entirely inaccessible to screen readers.)
