### ISSUE TITLE
Execution failed for task ':react-native-webview:compileDebugKotlin'

### ISSUE THREAD

**Issue by CaueFurui** [react-native-webview/react-native-webview#1865]
**Bug description:**

After installing the lib and building the project it fails with the following error:

**To Reproduce:**

Just install the lib with yarn, run react-native link and run the project with react-native run-android

**Expected behavior:**

Just build the application in the smartphone.

**Screenshots/Videos:**

![Screenshot_20210204_122035](https://user-images.githubusercontent.com/48840933/106955801-7ed7a280-6714-11eb-96b3-add3f226b128.png)

**Environment:**
 - OS: Ubuntu
 - OS version: 20.04
 - react-native version: 0.63.4
 - react-native-webview version: 11.2.1

**Comment by Talha-raj** [comment]
same still got Execution failed for task ':react-native-webview:compileDebugKotlin'.

**Comment by justinkx** [comment]
> I just run the command in the windows 10 , npm install --save react-native-webview already auto linking enabled just run the command below,
> 
> npx react-native start
> 
> npx react-native run-android
> 
> got the following error
> 
> react-native-webview:compileDebugKotlin FAILED

The solution in https://github.com/react-native-webview/react-native-webview/issues/2568#issuecomment-1172557823 worked for me
