### ISSUE TITLE
Webview always shows cache version 

### ISSUE THREAD

**Issue by rb162215** [react-native-webview/react-native-webview#1866]
In my ReactNative app i am using webview, after changeing content of webpage not reflecting in webview.

`<WebView
        userAgent={"android-app"}
        ref={(webview) => {
          this.myWebView = webview;
        }}
        style={{ width: Constant.FULL_WIDTH, height: Constant.FULL_HEIGHT }}
        ignoreSslError={true}
        bounces={false}
        cacheEnabled={false}
        source={{ uri: this.state.appURL  }}
        javaScriptEnabled={true}
        domStorageEnabled={true}
        renderLoading={this.ActivityIndicatorLoadingView}
        mediaPlaybackRequiresUserAction={true}
        onLoadEnd={() => this.onPageLoadFinish()}
        onLoadStart={() => this.onPageLoadStart()}
        onLoadingError={() => this.onPageLoadError()}
        onMessage={(event) => {
          this.onWebViewMessage(event);
        }}
      />`

when ever web page contain change, web-view should refresh its cache version. How to active this.
is there any configuration changes require?

**Comment by thientnc-galaxyone** [comment]
I'm using `incognito={true}`

**Comment by coolswood** [comment]
same issue
