### ISSUE TITLE
Crash in production - RNCWebView.m line 925

### ISSUE THREAD

**Issue by infapednekar** [react-native-webview/react-native-webview#1867]
Crash in production - RNCWebView.m line 925

**Bug description:**
We are getting a crash reported in crashlytics for iOS devices. Following is the stacktrace for the same. 

> RNCWebView.m line 925
-[RNCWebView webView:decidePolicyForNavigationAction:decisionHandler:]
Fatal Exception: NSInvalidArgumentException
*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]
0  CoreFoundation                 0x19bdd986c __exceptionPreprocess
1  libobjc.A.dylib                0x1b0d48c50 objc_exception_throw
2  CoreFoundation                 0x19be49e1c -[__NSCFString characterAtIndex:].cold.1
3  CoreFoundation                 0x19be56270 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:].cold.5
4  CoreFoundation                 0x19bcca550 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]
5  CoreFoundation                 0x19bcbcdd0 +[NSDictionary dictionaryWithObjects:forKeys:count:]
6  TSC                            0x105321a48 -[RNCWebView webView:decidePolicyForNavigationAction:decisionHandler:] + 925 (RNCWebView.m:925)
7  TSC                            0x104b8eca4 __72-[DTXWKWebView webView:decidePolicyForNavigationAction:decisionHandler:]_block_invoke + 324 (DTXWKWebView.m:324)
8  TSC                            0x104b8f2b4 +[DTXWKWebView webView:decidePolicyForNavigationAction:decisionHandler:canCallOriginal:callOriginal:] + 369 (DTXWKWebView.m:369)
9  TSC                            0x104b8eb30 -[DTXWKWebView webView:decidePolicyForNavigationAction:decisionHandler:] + 327 (DTXWKWebView.m:327)
10 WebKit                         0x1a857affc WebKit::NavigationState::NavigationClient::decidePolicyForNavigationAction(WebKit::WebPageProxy&, WTF::Ref<API::NavigationAction, WTF::DumbPtrTraits<API::NavigationAction> >&&, WTF::Ref<WebKit::WebFramePolicyListenerProxy, WTF::DumbPtrTraits<WebKit::WebFramePolicyListenerProxy> >&&, API::Object*)
11 WebKit                         0x1a8622090 WebKit::WebPageProxy::decidePolicyForNavigationAction(WTF::Ref<WebKit::WebProcessProxy, WTF::DumbPtrTraits<WebKit::WebProcessProxy> >&&, WebKit::WebFrameProxy&, WebKit::FrameInfoData&&, unsigned long long, WebKit::NavigationActionData&&, WebKit::FrameInfoData&&, WTF::Optional<WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType> >, WebCore::ResourceRequest const&, WebCore::ResourceRequest&&, IPC::FormDataReference&&, WebCore::ResourceResponse&&, WebKit::UserData const&, WTF::Ref<WebKit::WebPageProxy::PolicyDecisionSender, WTF::DumbPtrTraits<WebKit::WebPageProxy::PolicyDecisionSender> >&&)
12 WebKit                         0x1a8621154 WebKit::WebPageProxy::decidePolicyForNavigationActionAsyncShared(WTF::Ref<WebKit::WebProcessProxy, WTF::DumbPtrTraits<WebKit::WebProcessProxy> >&&, WTF::ObjectIdentifier<WebCore::PageIdentifierType>, WTF::ObjectIdentifier<WebCore::FrameIdentifierType>, WebKit::FrameInfoData&&, WebCore::PolicyCheckIdentifier, unsigned long long, WebKit::NavigationActionData&&, WebKit::FrameInfoData&&, WTF::Optional<WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType> >, WebCore::ResourceRequest const&, WebCore::ResourceRequest&&, IPC::FormDataReference&&, WebCore::ResourceResponse&&, WebKit::UserData const&, unsigned long long)
13 WebKit                         0x1a8620fb0 WebKit::WebPageProxy::decidePolicyForNavigationActionAsync(WTF::ObjectIdentifier<WebCore::FrameIdentifierType>, WebKit::FrameInfoData&&, WebCore::PolicyCheckIdentifier, unsigned long long, WebKit::NavigationActionData&&, WebKit::FrameInfoData&&, WTF::Optional<WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType> >, WebCore::ResourceRequest const&, WebCore::ResourceRequest&&, IPC::FormDataReference&&, WebCore::ResourceResponse&&, WebKit::UserData const&, unsigned long long)
14 WebKit                         0x1a88ebec0 WebKit::WebPageProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&)
15 WebKit                         0x1a8316cbc IPC::MessageReceiverMap::dispatchMessage(IPC::Connection&, IPC::Decoder&)
16 WebKit                         0x1a864b69c WebKit::WebProcessProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&)
17 WebKit                         0x1a82f9eec IPC::Connection::dispatchMessage(std::__1::unique_ptr<IPC::Decoder, std::__1::default_delete<IPC::Decoder> >)
18 WebKit                         0x1a82f9730 IPC::Connection::dispatchIncomingMessages()
19 JavaScriptCore                 0x1a602a504 WTF::RunLoop::performWork()
20 JavaScriptCore                 0x1a602b1ec WTF::RunLoop::performWork(void*)
21 CoreFoundation                 0x19bd5576c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
22 CoreFoundation                 0x19bd55668 __CFRunLoopDoSource0
23 CoreFoundation                 0x19bd54960 __CFRunLoopDoSources0
24 CoreFoundation                 0x19bd4ea8c __CFRunLoopRun
25 CoreFoundation                 0x19bd4e21c CFRunLoopRunSpecific
26 GraphicsServices               0x1b3852784 GSEventRunModal
27 UIKitCore                      0x19e78cfe0 -[UIApplication _run]
28 UIKitCore                      0x19e792854 UIApplicationMain
29 TSC                            0x1048f7eac main + 17 (main.m:17)
30 libdyld.dylib                  0x19ba0e6b0 start

**To Reproduce:**
Unable to reproduce in local environment

**Expected behavior:**
Webview should not create a crash

**Screenshots/Videos:**

**Environment:**
 - OS: iOS
 - OS version: 14
 - react-native version: 0.63.3
 - react-native-webview version: 11.0.0

**Comment by infapednekar** [comment]
Any update on this?

**Comment by mustafashaik7** [comment]
Any update on this as we are seeing the same crash in our app on Production and it can't be reproduced on debug builds.

**Comment by infapednekar** [comment]
The issue is still happening even with the latest version.

**Comment by meenunegi** [comment]
Any update on this crash. The issue is still happening even with the latest version. Crash is happening only in Prod build for ios, in debug build no crash is happening.

**Environment**:

OS: iOS
react-native version: 0.63.3
react-native-webview version : 11.17.2
