### ISSUE TITLE
Support for window.open with multiple windows, like a real browser

### ISSUE THREAD

**Issue by pkieltyka** [react-native-webview/react-native-webview#1868]
Hello, for a number of applications, we'd like to use `window.open` and properly have `window.postMessage` communication capabilities between the windows. 

This ticket is related to https://github.com/react-native-webview/react-native-webview/issues/1111 and I am reopening.

[edit: previously I had offered a bounty for this ticket to be solved, however I've managed to find a work-around and this is no longer urgent, so the bounty has expired]

**Comment by krunaldarji** [comment]
@pkieltyka are you trying to open popup window?

**Comment by pkieltyka** [comment]
@krunaldarji yes, open a popup window which would also be a react-native-webview and then have window.postMessage work between windows -- https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage

**Comment by pkieltyka** [comment]
btw, just to clarify my comment above -- the popup window (aka child window) does not have to be a "react-native-webview" window, it should just be of the same native-webview class on the respective platform, on iOS its WKWebview, and on Android its android.webkit.WebView.

I'm not super familiar with this repo's codebase or project -- but one idea / thought could be to polyfill / inject into both windows a new window.open() method on the parent side, and window.postMessage() on the child side. And then do messaging between those in the RN context. 

On the apple-side of RNCWebview, there is https://github.com/react-native-webview/react-native-webview/blob/dd315bcf87d7bdbbcf7e63f9afa17c8f59b368bc/apple/RNCWebView.m#L196-L205 -- I imagine something similar on Android side.

Another idea could be to use https://github.com/react-native-webview/react-native-webview/blob/dd315bcf87d7bdbbcf7e63f9afa17c8f59b368bc/docs/Reference.md#onshouldstartloadwithrequest and return false to prevent the loading of this request, then instead open a new RNWebView window, and setup the window.postMessage() messaging. The window.open() method which is injected in the parent window would have to flag to the onshouldstartloadwithrequest method that the url being opened is called from window.open(..), as I believe this handler will also be triggered when someone clicks an anchor link.

.. anyways just some thoughts anyways if others are thinking about it. Feel free to ignore my implementation suggestions above as Im not a mobile dev expert or have enough time to get into the weeds but wanted to share some high level thoughts.

thank you :)

**Comment by pkieltyka** [comment]
also.. to do bidirectional messaging you’ll have to support event listeners and postMessage on parent. But I do think can all be written to spec / standard of browsers and everything will interoperate and even can implement the usual security and domain checking. But transport would be just a class on RN side..

**Comment by nrajput05** [comment]
@pkieltyka were you able to resolve it ?
