### ISSUE TITLE
onShouldStartLoadWithRequest Not Working on Android

### ISSUE THREAD

**Issue by topherPedersen** [react-native-webview/react-native-webview#1869]
**Bug description:**
On Android, the onShouldStartLoadWithRequest method is not working. For example, we load a single page application from a third party website into our WebView, while navigating the single page application the onShouldStartLoadWithRequest method never executes. However, loading the same URL into a native Android WebView does cause the onShouldStartLoadWithRequest method to execute.

**To Reproduce**
Load a single page application into react-native-webview for Android and see if the onShouldStartLoadWithRequest method ever executes.

**Expected behavior:**
The onShouldStartLoadWithRequest method should be called just like it would if one were using a native android.webkit.WebView and android.webkit.WebViewClient. For example, I created a native Android WebView to experiment working with this particular single page application, and the onShouldStartLoadWithRequest method is called as expected. But this behavior is not matched when using react-native-webview. (Sorry I am not able to provide the exact link to the single page application as it's a proprietary, closed-source, and not publicly available)

**Environment:**
- OS: Android 9
- react-native version: 0.63.4
- react-native-webview version: 11.2.1 / 11.0.2

**Comment by mzain512** [comment]
I am facing the same issue. I have loading my website and `onShouldStartLoadWithRequest ` never calls on first launch and whenever I click on links in webpage. using v11.0.2

**Comment by rpander93** [comment]
Looks like #1855 that I reported some days ago

**Comment by davidohlin** [comment]
@mzain512 I missed it too, but the [documentation](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#onshouldstartloadwithrequest) for `onShouldStartLoadWithRequest` say:

> On Android, is not called on the first load.

>

**Comment by mzain512** [comment]
@davidohlin ok we can ignore the first launch. What about after that when we click on any of the links in webpage? On iOS I have handled external links through this callback but on android its not called and my implementation is failing.

**Comment by yuvapoojary** [comment]
Yes it is not working in single page web application.
And onNavigationStateChange is also not working .

**Comment by accprudolfs** [comment]
The same issue onShouldStartLoadWithRequest is not called at all on Android

**Comment by creativemind1** [comment]
Only few requests are loading and not all with `onShouldStartLoadWithRequest` (Android)
`"react-native-webview": "^8.1.1",`

**Comment by martinhellwig** [comment]
I had the same issue as you. For me specifying "setSupportMultipleWindows={false}" on the WebView fixed the problem. Maybe this will help.

**Comment by harshmaisheri** [comment]
> I had the same issue as you. For me specifying "setSupportMultipleWindows={false}" on the WebView fixed the problem. Maybe this will help.

will this allow external links like youtube / google maps to open external in the browser?

**Comment by pkieltyka** [comment]
still searching for solutions

**Comment by Estebank94** [comment]
still having the issue

**Comment by OrkhanAlikhanov** [comment]
It seems `onShouldStartLoadWithRequest` is not called when an iframe loads in android, but in iOS it's called returning false prevents iframe from loading. I had an embedded youtube video in the document

**Comment by mabc21** [comment]
Also still having problems with this

**Comment by Daha62** [comment]
the same

**Comment by jamalhassouni** [comment]
the same

**Comment by ftlno** [comment]
same

**Comment by Andycapn** [comment]
Same

**Comment by yberstad** [comment]
I had this issue before, as posted above. 

I have had another go at this, upgraded to RN 0.66.3 and react-native-webview 11.14.3.  
I have also set the setSupportMultipleWindows={false}. 

And from what from what I can see, it now works as expected?

**Comment by raldred** [comment]
This is expected as of v11
https://github.com/react-native-webview/react-native-webview/releases/tag/v11.0.0

If you're turning setting `setSupportMultipleWindows` to `false` ensure you have protecting inside your `onShouldStartLoadWithRequest` callback to limit navigation to expected URLs otherwise you're exposing your users to a risk of bad actors.

https://github.com/advisories/GHSA-36j3-xxf7-4pqg

**Comment by vitexikora** [comment]
I have set `setSupportMultipleWindows` to `false`, but `onShouldStartLoadWithRequest` is still NEVER called on my Android device. I tried with webview version ranging from 8 to 11...

**Comment by plat2eau** [comment]
Same problem

**Comment by viswen-k** [comment]
Same issue for me, onShouldStartLoadWithRequest works on iOS but not on android

**Comment by jihanarifia** [comment]
have the same problem  onShouldStartLoadWithRequest works on iOS but not on android

**Comment by ashishAmz** [comment]
yes, onShouldStartLoadWithRequest is not working on Android

**Comment by adias9** [comment]
I have experienced the same issue and even with `setSupportMultipleWindows={false}` it was not working for me.  

Through trial and error, I realized you can't have `injectedJavaScript` set and `setSupportMultipleWindows={false}` set otherwise the fix will not work. If you remove the `injectedJavaScript` prop then the fix should work.

**Comment by mgscreativa** [comment]
> I have experienced the same issue and even with `setSupportMultipleWindows={false}` it was not working for me.
> 
> Through trial and error, I realized you can't have `injectedJavaScript` set and `setSupportMultipleWindows={false}` set otherwise the fix will not work. If you remove the `injectedJavaScript` prop then the fix should work.
> 
> Hope this helps some others in debugging pray

Not even this gets the method running on my dev phone!

**Comment by ammarahm-ed** [comment]
Not working at all

**Comment by Gaphell** [comment]
This issue is still there. Returning `false` to `onShouldStartLoadWithRequest` in Android is not working as expected. Works fine in IOS.

**Comment by isik-finset** [comment]
still searching

**Comment by ammarahm-ed** [comment]
Maybe it will be possible to do with JSI as it supports synchronous invocation of functions in native code.

**Comment by mgscreativa** [comment]
> Maybe it will be possible to do with JSI as it supports synchronous invocation of functions in native code.

JSI is a headacche, it forces you to use Hermes which has a lot of issues for debugging, you have to use Flipper which is also buggy.

I tryes it las week in an Expo project I'm working on, even with an Expo Development Build it fails to debug!

**Comment by BFMarks** [comment]
still searching - should have built this actual app in native code </3

**Comment by anhduy5689h** [comment]
Do you have any solution?

**Comment by DanielOS7** [comment]
A hacky work around for an issue in my project was to return `true` when a condition passed in `shouldOverrideUrlLoading` in `node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java`

Example:


```
    @Override
    public boolean shouldOverrideUrlLoading(WebView view, String url) {
      final RNCWebView rncWebView = (RNCWebView) view;
      final boolean isJsDebugging = ((ReactContext) view.getContext()).getJavaScriptContextHolder().get() == 0;

      if (url.contains("......")) {
        return true;
      } 
      
     if (!isJsDebugging && rncWebView.mCatalystInstance != null) {
```

**Comment by ammarahm-ed** [comment]
Not stale

**Comment by ysshir** [comment]
I found that it is working in debug session. 
so I changed "RNCWebViewManager.java" like below and it looks working now.

```java
progressChangedFilter.setWaitingForCommandLoadUrl(true);
      ((RNCWebView) view).dispatchEvent(
        view,
        new TopShouldStartLoadWithRequestEvent(
          view.getId(),
          createWebViewEvent(view, url)));
      return true;
}
```

**Comment by ysshir** [comment]
I thought shouldOverrideUrlLoading isn't called on Android,
but actually it is, but the argument doesn't have "isTopFrame".

```
// wrong
// if (!event.isTopFrame || event.url.startsWith("about:")) {
//   return true;
// }

// correct
if (event.isTopFrame === false || event.url.startsWith("about:")) {
  return true;
}
```

**Comment by IngyuTae** [comment]
Adding `originWhitelist={['*']}` prop has solved the issue.

**Comment by mgscreativa** [comment]
Hi! is it solved yet?

**Comment by paulg0614** [comment]
Try setting setSupportMultipleWindows={false}
For whatever reason, onShouldStartLoadWithRequest is now called.

**Comment by shortsides** [comment]
still same issue on android

**Comment by fukemy** [comment]
bump

**Comment by atariandante** [comment]
`onShouldStartLoadWithRequest` prop still not working on Android. I found a work arround using the `injectedJavascript` prop to manually ignore requests. Suggestions are welcomed:

```
const requestInjector = `(function() {
  var xhrOpen = window.XMLHttpRequest.prototype.open;
  window.XMLHttpRequest.prototype.open = function(method, url) {
    if (url && url.toLowerCase().includes('/stories/reel/seen')) {
      console.log('Blocked API call:', url);
      return; // Exit the function to block the request
    }
    xhrOpen.apply(this, arguments);
  };

  var fetch = window.fetch;
  window.fetch = function(url) {
    if (url && url.toLowerCase().includes(DESIRE_REQUEST_PATH)) {
      console.log('Blocked API call:', url);
      return new Promise(function() {}); // Return an empty promise to block the request
    }
    return fetch.apply(this, arguments);
  };
})();`
```

Hope this helps

**Comment by fukemy** [comment]
> oid. I found a work arround using the `injectedJavascript` prop to manually ignore requests. Suggestions are welcomed:

Hi, do you have any android solution?

**Comment by Pingou** [comment]
@Titozzz Can we reopen?

**Comment by atariandante** [comment]
@fukemy This solution should work well on android/ios

**Comment by julian-jeong** [comment]
```
 setSupportMultipleWindows={false}
 originWhitelist={['*']}
```
I have tried this method, but the onShouldStartLoadWithRequest function still doesn't execute on Android 😭

 OS: Android 12
react-native version: 0.68.7
react-native-webview version: 11.26.1

**Comment by MarinaAmy** [comment]
Have you found a solution to this problem?

OS: Android 12
react-native version: 0.70.6
react-native-webview version: 13.2.3

**Comment by Osilos** [comment]
The problem is still there for me, **onShouldStartLoadingWithRequest** is not call on android.

I try it on new project

`export default function App() {
  return (
      <WebView source={{ 
            uri: '...'
          }}
          setSupportMultipleWindows={false}
          originWhitelist={['*']}

          onShouldStartLoadWithRequest={(request) => {
            console.log(request);
            return true;
          }}
    
      />
  );
}`

react-native version 0.71.3
react-native-webview version : 13.6.0

**Comment by uppyprj** [comment]
i have a solution for my own 
          <WebView
.....              
              onLoadEnd={this.webViewLoaded}
              onShouldStartLoadWithRequest={this.openExternalLink}
.....   
       />
on calling webViewLoaded a call  this.openExternalLink() and in this way i call openExternalLink for first time on loading webview

**Comment by anand-netzoptimize** [comment]
> The problem is still there for me, **onShouldStartLoadingWithRequest** is not call on android.
> 
> I try it on a new project, I never get the console.log.
> 
> ` export default function App() { return ( <WebView source={{ uri: 'url', }} setSupportMultipleWindows={false} originWhitelist={['*']}
> 
> ```
>       onShouldStartLoadWithRequest={(request) => {
>         console.log(request);
>         return true;
>       }}
> 
>   />
> ```
> 
> ); } `
> 
> react-native version 0.71.3 react-native-webview version : 13.6.0

It worked!!

**Comment by qq508852582** [comment]
it's 2025. Im still facing the issue.
and here's my summary, for SPA onShouldStartLoadWithRequest not triggered on Android.
but after i set source to google or something , onShouldStartLoadWithRequest triggered a lot if some link clicked.
here's my solution.
```js
          onNavigationStateChange={navState => {
            switch (navState.url) {
              case xxx1:
                clearToken();
                return false;
              case xxx2:
                webViewRef.current?.goBack();
                navigation.navigate(xxx);
                return false;
              default:
                return true;
            }
          }}
```

**Comment by Folktails** [comment]
@anand-dehru what is your react-native-webview? i use 13.12.3
