### ISSUE TITLE
Closing full screen video closes containing modal

### ISSUE THREAD

**Issue by jbrooks58** [react-native-webview/react-native-webview#1871]
**Bug description:**
So the fullscreen video shows correctly when inside a modal, but when the fullscreen video is closed the modal that contained the video is no longer visible and seems to have been closed/hidden. Is anyone else experiencing this behavior?

**To Reproduce:**
Open a modal that contains a video and enter full screen mode. Exit full screen mode and modal will now be closed as well.

**Expected behavior:**
full screen video should close, but containing modal should still be visible.

**Environment:**
 - OS: Android
 - react-native-webview version: 11.2.3

**Comment by cristianoccazinsp** [comment]
@jbrooks58  I was the author of a PR that allowed full screen videos to work inside Android Modals (https://github.com/react-native-webview/react-native-webview/pull/1748).  In theory, the modal should not be closed (but rather "re-opened"), can you share some code of what you're doing?  The change worked fine for me on all the devices I tested, but perhaps there's some edge case with the modal logic.

**Comment by jbrooks58** [comment]
> @jbrooks58 I was the author of a PR that allowed full screen videos to work inside Android Modals (#1748). In theory, the modal should not be closed (but rather "re-opened"), can you share some code of what you're doing? The change worked fine for me on all the devices I tested, but perhaps there's some edge case with the modal logic.

I found the issue. For some reason a View that was wrapping the Modal was the issue. Once I removed the wrapping View the issue is no longer present and everything is functioning as expected.

**Comment by cristianoccazinsp** [comment]
Hey, interesting!  I think I never tried wrapping the modal within another view. Perhaps that's an edge case I didn't consider.  If you have time, you could help me review the PR to try to find a better way to fix this.  I tried multiple things, but so far the only one that worked was the one I implemented (hiding/showing the Modal's root view).
