### ISSUE TITLE
iOS fullscreen Video - Breaks Dimensions API

### ISSUE THREAD

**Issue by cristianoccazinsp** [react-native-webview/react-native-webview#1872]
**Bug description:**

On iOS, if the webview opens a fullscreen video and the user rotates the device, `Dimensions.get('window')` (and callbacks) will return height/width switched around.  Oddly, `Dimensions.get('screen')` return the right values.

Works fine on Android.

**To Reproduce:**

Render a webview that has a video in it. Play the video full screen and rotate the device. Call `Dimensions.get('window')` on a timeout or an event listener and observe returned values when the device rotates.

**Expected behavior:**

react-native-webview should not interfere with the Dimensions API. 

**Screenshots/Videos:**

**Environment:**
 - OS: iOS
 - OS version: 14.3 and 14.4
 - react-native version: 0.62.2
 - react-native-webview version: 11.2.3

**Comment by imcber** [comment]
Same issue

**Comment by cristianoccazinsp** [comment]
Still looking for fixes.  It's on my list to test with new RN versions.

**Comment by cristianoccazinsp** [comment]
Still bugged

**Comment by cristianoccazinsp** [comment]
Still a bug.

**Comment by tavvfiq** [comment]
i still encounter this issue. is there any workaround?

**Comment by watchinharrison** [comment]
Still an issue, I'm encountering too

**Comment by watchinharrison** [comment]
I'm also seeing this issue, using `11.17.1`. 

I'm using `useWindowDimensions` to get updated widths, whilst it is triggered on orientation change when web view full screen video is rotated, the incorrect value is being passed, rotating the device when the video isn't playing will send the correct value down. 

Even using `Dimensions.get('window')` and forcing a rerender through checking on `ScreenOrientation` listener won't show the correct value. Event though I can see the orientation value change correctly.

Having to disable `allowsFullscreenVideo` in order to mitigate this issue as it causes huge layout issues.

**Comment by laeijebor** [comment]
Still seeing this issue with the latest - could this be reopened, please? In our case the only way to correct the issue is to open the web view in full screen again, then toggle the orientation again...

**Comment by laeijebor** [comment]
FWIW, we're currently using a very ugly hack similar to the below to set the dimensions to the known previous dimensions every second whilst the webview component is mounted, and again before it unmounts... It's the only way we've found to somewhat restore the balance:

```js
// Set prevDimensions to the known dimensions before the WebView component is mounted, 
// then in the Container for the VebView component:

const setDimensions = () => {
  const newDimensions = {width: Math.min(prevDimensions.width, prevDimensions.height), height: Math.max(prevDimensions.width, prevDimensions.height)};
  Dimensions.set({window: {...prevDimensions, ...newDimensions}});
}
React.useEffect(() => {
  const setDimensionsInterval = setInterval(() => {
    setDimensions();
  }, 1000)

  return () => {
    clearInterval(setDimensionsInterval)
    setDimensions();
    ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.PORTRAIT_UP);
  }
}, []);

  
```

**Comment by cristianoccazinsp** [comment]
@laeijebor nice work around!

We are also using an extremely ugly work around as follows (put in index.js). Basically, we know that `screen` never bugs, and that `window` returns swapped values when the bug happens. Using this information, the following can be implemented:

```
// Patch dimensions to handle wrong values when
// full-screen video is played on iOS and swaps values
// TODO: Review this once either RN or WebView fixes it.
if (Platform.OS === 'ios') {
  let oldGet = Dimensions.get;

  let newGet = (val) => {
    let res = oldGet(val);
    if (val == 'window') {
      let {width, height} = oldGet('screen');
      let isPortrait1 = width <= height;
      let isPortrait2 = res.width <= res.height;
      if (isPortrait1 != isPortrait2) {
        Object.assign(res, {
          width: res.height,
          height: res.width,
        });
      }
    }
    return res;
  };
  Dimensions.get = newGet;
}
```

But hey, please re open this as this is still a major pain in the neck.

**Comment by demedos** [comment]
still broken on 11.14.2. @Titozzz please reopen this

**Comment by alessioemireni** [comment]
+1
