### ISSUE TITLE
Cookie not being sent with resource requests

### ISSUE THREAD

**Issue by nikitawani07** [react-native-webview/react-native-webview#1875]
**Is your feature request related to a problem? If so, Please describe.**

We have a use case in which when we are loading a page in the webview, it itself does many resource requests and these resource requests require the cookie to be sent with them. When cookie is provided to react-native-webview, it only sends it for that url, but resource requests initiated by this page doesn't have cookie attached to it.

**Describe the solutions you came up with**

Whenever source is set to a new URL with additional headers, we pick up the headers and set it in webview configuration, so it's available to subsequent requests.

**Additional context**

Fix in iOS: https://github.com/react-native-webview/react-native-webview/pull/1803
Similar fix will be added for android as well.

**Comment by anoopjangra90** [comment]
It was Android System WebView issue. Go to Settings->Apps-> Android Web View and remove system updates.
