### ISSUE TITLE
Referer header is not passing to request

### ISSUE THREAD

**Issue by Ruth27-dev** [react-native-webview/react-native-webview#1876]
**Bug description:**

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS:
 - OS version:
 - react-native version:
 - react-native-webview version:

**Comment by timboektoe** [comment]
This is a very minimal description. Could you be more explicit?

**Comment by Ruth27-dev** [comment]
i am trying to post data with header (it is working with IOS but not working with android).
