### ISSUE TITLE
Show a Comma ( , ) when map array data

### ISSUE THREAD

**Issue by Alnsentry** [react-native-webview/react-native-webview#1877]
Can some one help me? i use .map for show data array in webview but .map does not just show data from array but comma ( , ) from array is also displayed

**Picture :**

![WhatsApp Image 2021-02-15 at 17 23 39](https://user-images.githubusercontent.com/35386499/107935572-24f89780-6fb4-11eb-9173-25333b424297.jpeg)

**Code :**

`<WebView
  style={{width:"100%",marginVertical:20}}
  originWhitelist={['*']}
  source={{ 
    html: `
`${ this.state.jenis == "Standart" ? 
            ``<div style="padding:10px 20px 40px 20px;width:21cm;border: 1px solid black;margin:auto">
              <div style="display: flex;">
                <div style="flex:1;margin-left: 30px">
                  <div style="text-align: center">
                    <h2 style="margin-bottom: 0">${this.state.information.company.name}</h2>
                    ${this.state.information.company.address} <br>
                    Telp : ${this.state.information.company.telp}  ${ this.state.information.company.website != "" ? "Website : " + this.state.information.company.website : ""  }`
                  </div>
                </div>
                `<div style="flex:1;text-align: right;margin-right: 50px">
                  <h1 style="padding-top: 20px">Surat Jalan</h1>
                </div>`
              </div>

              <hr style="margin-top:20px">

              <div style="display: flex;margin-top:20px">
                <table style="margin-right: 25%">
                  <tr>
                    <td style="vertical-align: top;padding-right: 10px">Tanggal</td>
                    <td style="vertical-align: top;padding-right: 10px">:</td>
                    <td>${day.toString() + " " + monthNames[month] + " " + date.toString()}</td>
                  </tr>
                  <tr>
                    <td style="vertical-align: top;padding-right: 10px">No Surat Jalan</td>
                    <td style="vertical-align: top;padding-right: 10px">:</td>
                    <td>${this.state.nomorSurat}/SJ/${date.toString()}</td>
                  </tr>
                  ${ this.state.info.invoice == true ?
                    `<tr>
                      <td style="vertical-align: top;padding-right: 10px">No Invoice</td>
                      <td style="vertical-align: top;padding-right: 10px">:</td>
                      <td>${this.state.dataInfo.invoice}</td>
                    </tr>` : ``
                  }
                  ${ this.state.info.kirim == true ?
                    `<tr>
                      <td style="vertical-align: top;padding-right: 10px">Dikirim Dengan</td>
                      <td style="vertical-align: top;padding-right: 10px">:</td>
                      <td>${this.state.dataInfo.kirim}</td>
                    </tr>` : ``
                  }
                  ${ this.state.info.polisi == true ?
                    `<tr>
                      <td style="vertical-align: top;padding-right: 10px">No Polisi</td>
                      <td style="vertical-align: top;padding-right: 10px">:</td>
                      <td>${this.state.dataInfo.polisi}</td>
                    </tr>` : ``
                  }
                </table>

                <table>
                  <tr>
                    <td style="vertical-align: top;padding-right: 10px">Penerima</td>
                    <td style="vertical-align: top;padding-right: 10px">:</td>
                    <td>${this.state.information.receiver.name}</td>
                  </tr>
                  <tr>
                    <td style="vertical-align: top;padding-right: 10px">Telepon</td>
                    <td style="vertical-align: top;padding-right: 10px">:</td>
                    <td>${this.state.information.receiver.telp}</td>
                  </tr>
                  <tr>
                    <td style="vertical-align: top;padding-right: 10px">Alamat</td>
                    <td style="vertical-align: top;padding-right: 10px">:</td>
                    <td width="200">${this.state.information.receiver.address}</td>
                  </tr>
                </table>
              </div>

              <div style="margin-top:20px">
                <table style="border:1px solid black;width: 100%;border-collapse: collapse;">
                  <tr style="text-align: left;border: 1px solid black;border-collapse: collapse;">
                    <th style="padding:10px">No</th>
                    <th>Nama Barang</th>
                    <th>Berat</th>
                    <th>Deksripsi</th>
                  </tr>
                  ${ 
                    this.state.data.map((data, index) => {
                      return `<tr style="flex:1">
                                <td style="vertical-align: top;padding: 10px 0 10px 10px">${index + 1}</td>
                                <td style="vertical-align: top;padding-top:10px">${data.barang == undefined || data.barang == "" ? "" : data.barang}</td>
                                <td style="vertical-align: top;padding-top:10px">${data.berat} kg</td>
                                <td style="vertical-align: top;padding: 10px 10px 10px 0">${data.keterangan == undefined || data.keterangan == "" ? "" : data.keterangan}</td>
                              </tr>`
                    })
                  }
                </table>
              </div>

              <div style="display: flex;margin-top:30px">
                <div style="flex: 1;text-align: center">
                  Dikirim oleh <br><br><br><br><br>
                  ${this.state.info.pengemudi == true && this.state.dataInfo.pengemudi}
                </div>

                <div style="flex: 1;text-align: center">
                  Diterima oleh <br><br><br><br><br>
                  
                </div>
              </div>
            </div>`
          :
            `<div style="border: 1px solid black;width: 70mm;margin:auto">
              <div style="padding:10px 10px 40px 10px;">
                <div style="width: 100%">
                  <h2 style="text-align: center">Surat Jalan</h2>
                </div>

                <div style="width: 100%">
                  <div style="text-align: center">
                    <h3 style="margin-bottom: 10px">${this.state.information.company.name}</h3>
                    ${this.state.information.company.address} <br>
                    Telp : ${this.state.information.company.telp} <br> ${ this.state.information.company.website != "" ? "Website : " + this.state.information.company.website : ""  }
                  </div>
                </div>

                <hr style="margin-top:20px;border-bottom:1px;border-top:0;border-style: dashed; border-color: #808080">

                <div style="">
                  <table style="margin-right: 0;width: 100%;border-collapse: collapse;">
                    <tr>
                          <td style="vertical-align: center;">Tanggal</td>
                          <td style="vertical-align: center;padding-right: 10px">:</td>
                          <td width="90px">${day.toString() + " " + monthNames[month] + " " + date.toString()}</td>
                        </tr>
                    <tr>
                      <td style="vertical-align: center;">No Surat</td>
                      <td style="vertical-align: center;padding-right: 10px">:</td>
                      <td width="90px">${this.state.nomorSurat}/SJ/${date.toString()}</td>
                    </tr>
                    ${ this.state.info.invoice == true ?
                      `<tr>
                        <td style="vertical-align: top;padding-right: 10px">No Invoice</td>
                        <td style="vertical-align: top;padding-right: 10px">:</td>
                        <td>${this.state.dataInfo.invoice}</td>
                      </tr>` : ``
                    }
                    ${ this.state.info.kirim == true ?
                      `<tr>
                        <td style="vertical-align: center;">Dikirim Dengan</td>
                        <td style="vertical-align: center;padding-right: 10px">:</td>
                        <td width="90px">${this.state.dataInfo.kirim}</td>
                      </tr>` : ``
                    }
                    ${ this.state.info.polisi == true ?
                      `<tr>
                        <td style="vertical-align: center;">No Polisi</td>
                        <td style="vertical-align: center;padding-right: 10px">:</td>
                        <td width="90px">${this.state.dataInfo.polisi}</td>
                      </tr>` : ``
                    }

                    <tr>
                      <td style="vertical-align: center;">Penerima</td>
                      <td style="vertical-align: center;padding-right: 10px">:</td>
                      <td width="90px">${this.state.information.receiver.name}</td>
                    </tr>
                    <tr>
                      <td style="vertical-align: center;">Telepon</td>
                      <td style="vertical-align: center;padding-right: 10px">:</td>
                      <td width="90px">${this.state.information.receiver.telp}</td>
                    </tr>
                  </table>
                    
                  <div style="margin-bottom: 5px">
                    Alamat <span style="margin-left: 18px">:</span>
                  </div>
                  ${this.state.information.receiver.address}
                </div>

                <div style="margin-top:20px">
                  <table style="border-top:1px;border-right:0;border-left:0;border-bottom:1px;border-style: dashed;border-color:#808080;width: 100%;border-collapse: collapse;">
                    ${ this.state.data.map((data, index) => {
                      return  ` <tr>
                                  <td style="vertical-align: top;padding: 10px 10px 5px 10px">${index + 1}</td>
                                  <td style="vertical-align: top;padding-top:10px;padding-bottom: 5px;font-weight:bold">${data.barang == undefined || data.barang == "" ? "" : data.barang}</td>
                                  <td style="vertical-align: top;padding-top:10px;padding-bottom: 5px">${data.berat} kg</td>
                                </tr>
                                <tr>
                                  <td style="padding-top: 0;margin-top: 0"></td>
                                  <td colspan="2" style="padding-top: 0;margin-top: 0">${data.keterangan == undefined || data.keterangan == "" ? "" : data.keterangan}</td>
                                </tr> `
                    })}
                  </table>
                </div>

                <div style="display: flex;margin-top:30px">
                  <div style="flex: 1;text-align: center">
                    Pengirim <br><br><br><br>
                    ${this.state.info.pengemudi == true && this.state.dataInfo.pengemudi}
                  </div>

                  <div style="flex: 1;text-align: center">
                    Penerima <br><br><br><br>
                  </div>
                </div>
              </div>
            </div>`
          }`
  }} 
/>`

thank you for attention sorry if my english is bad

**Comment by castalonirenz** [comment]
Up issue persist

**Comment by Akshat12042001** [comment]
Use join("") with the map to remove this comma's 

like this :- 

${ this.state.data.map((data, index) => {
                  return  ` <tr>
                              <td style="vertical-align: top;padding: 10px 10px 5px 10px">${index + 1}</td>
                              <td style="vertical-align: top;padding-top:10px;padding-bottom: 5px;font-weight:bold">${data.barang == undefined || data.barang == "" ? "" : data.barang}</td>
                              <td style="vertical-align: top;padding-top:10px;padding-bottom: 5px">${data.berat} kg</td>
                            </tr>
                            <tr>
                              <td style="padding-top: 0;margin-top: 0"></td>
                              <td colspan="2" style="padding-top: 0;margin-top: 0">${data.keterangan == undefined || data.keterangan == "" ? "" : data.keterangan}</td>
                            </tr> `
                }).join("")}
