### ISSUE TITLE
`WebView.propTypes` is `undefined`

### ISSUE THREAD

**Issue by ianbayne** [react-native-webview/react-native-webview#1879]
**Bug description:**
When creating a custom WebView, the [documentation](https://github.com/react-native-webview/react-native-webview/blob/4d8a76f3691479ef22b55e05c07921af99332395/docs/Custom-iOS.md#javascript-interface) states that

> To use your custom web view, you'll need to create a class for it. Your class must:
>
>  - Export all the prop types from WebView.propTypes

However, console-logging out `WebView.propTypes` I discovered that this is undefined. What is the correct way to export prop types from `WebView` then?

**To Reproduce:**
Import `WebView` and then console log its prop types.

**Expected behavior:**
I expect prop types for `WebView` to be defined.

**Environment:**
 - react-native version: 0.63.3

**Comment by TheAlmightyBob** [comment]
https://github.com/react-native-webview/react-native-webview/pull/1958 would remove that bit from the documentation, as I think it was just out of date. Did you actually need prop types for something, or were you just following the instructions from the documentation?

**Comment by ianbayne** [comment]
Thanks for the response, @TheAlmightyBob, and sorry for the lateness of my own. I was creating a custom `WebView` that would wrap `WebView`, but wanted to make sure it would accept only the same prop types as `WebView`. Something like the following:

```js
const CustomWebView = (props) => {
   ... do something
   return (
      <WebView />
   );
};

CustomWebView.propTypes = WebView.propTypes;
```

**Comment by TheAlmightyBob** [comment]
I think you'd want to use Typescript or Flow types for that. Once upon a time, I believe `propTypes` was connected to `requireNativeComponent` via the 2nd/3rd arguments, however that's no longer the case... it now only takes the one string parameter and I don't think does anything with `propTypes`.

**Comment by ianbayne** [comment]
Thanks for the response, @TheAlmightyBob. Understood 👍
