### ISSUE TITLE
React Native windows > 0.63 WebViewBridgeComponent with x64

### ISSUE THREAD

**Issue by aalbaharnah** [react-native-webview/react-native-webview#1883]
**Is your feature request related to a problem? If so, Please describe.**
I've been trying to build a Window 10 UWP C# application with `x64` as the processor architecture. However, the app cannot be build due to the mismatch between the processor architecture of react-native-webview project that is built on `x84` and the app.

this is the error that show up when the build fails

Severity | Code | Description | Project | File | Line | Suppression State
-- | -- | -- | -- | -- | -- | --
Error | MSB3271 | There was a mismatch between the processor architecture of the project being built "AMD64" and the processor architecture, "x86", of the implementation file "C:\Users\user\app\windows\Debug\WebViewBridgeComponent\WebViewBridgeComponent.dll" for "C:\Users\user\app\windows\Debug\WebViewBridgeComponent\WebViewBridgeComponent.winmd". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and implementation file, or choose a winmd file with an implementation file that has a processor architecture which matches the targeted processor architecture of your project. | ReactNativeWebView | C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets | 2084 |  

**Is it possible to have react-native-webview that is being built with `x64`?**

**Comment by asklar** [comment]
This should be possible; I see a potential bug in the RNW CLI that might be contributing to the confusion. After working around it on the CLI end (will send a PR to RNW CLI soon), I see the 64 app launch.

Can you try opening your app's solution in Visual Studio, selecting x64, and running by pressing F5?

**Comment by asklar** [comment]
May be related: https://github.com/microsoft/react-native-windows/issues/7440

**Comment by asklar** [comment]
@aalbaharnah are you still hitting this? can you check on the latest 0.64? we fixed something in the CLI that might help.

**Comment by aalbaharnah** [comment]
@asklar I was able to successfully build the application with the latest 0.64.
However, I got this error `Invariant Violation: requireNativeComponent: "RCTWebView" was not found in the UIManager.` which causes a crash in the app.
```
"react-native-webview": "^11.6.1"
"react-native-windows": "^0.64.7"
"react": "17.0.1"
"react-dom": "^16.13.1"
"react-native": "0.64.0"
```

```
Invariant Violation: requireNativeComponent: "RCTWebView" was not found in the UIManager.

This error is located at:
    in RCTWebView (at WebView.windows.js:180)
    in RCTView (at View.windows.js:52)
    in View (at WebView.windows.js:181)
    in WebView (at FillBranchInfoScreen.tsx:502)
    in RCTView (at View.windows.js:52)
```

**Comment by aalbaharnah** [comment]
@asklar Yes, I was able to build the app with the latest 0.64. Thanks!

```
"react-native-webview": "^11.4.3"
"react-native-windows": "^0.64.7"
"react": "17.0.1"
"react-native": "0.64.0"
```
