### ISSUE TITLE
External links for sharing the website does not open

### ISSUE THREAD

**Issue by daniel1up** [react-native-webview/react-native-webview#1884]
**Bug description:**
Hi there. I have added a website ([https://www.roomvo.com/my/vekoal/rooms/615c4480f40c40c4ba624a8c2f2f3f23](https://www.roomvo.com/my/vekoal/rooms/615c4480f40c40c4ba624a8c2f2f3f23)) inside `react-native-webview` that it is developed with Next.js. On this website are two buttons on the right menu drawer that shares on Facebook and Whatsapp by opening new tabs, but non of them is working inside `react-native-webview`. I hate tried to add some props that I think will help me but no success. Can anyone help me with this, please?

p.s
It has another problem with the download button. It crashes the app because is using data:base64 but I will open a new issue for that.

**To Reproduce:**
```
import React from 'react';
import { WebView } from 'react-native-webview'; 

const HomeScreen = props => { 
  return (
    <WebView source={{ uri: 'https://www.roomvo.com/my/vekoal/rooms/615c4480f40c40c4ba624a8c2f2f3f23' }} />
  );
};

export default HomeScreen;
```

**Expected behavior:**
I expect to open a new tab external on phone default browser.

**Environment:**
 - OS: Android
 - OS version: 9.0
 - Expo version: 4.1.0
 - Expo SDK version: 40.0.0
 - react-native version: 0.63
 - react-native-webview version: 11.0.0

**Comment by Salmankhan033** [comment]
@daniel1up have you fixed it?
