### ISSUE TITLE
WebSocket inside WebView?

### ISSUE THREAD

**Issue by benallfree** [react-native-webview/react-native-webview#1885]
Is there any reason a WebSocket wouldn't work? I get crickets, while the same code works from the main RN app.

```tsx
 <WebView
        originWhitelist={['*']}
        injectedJavaScript={`

var exampleSocket = new WebSocket('ws://localhost:3000')

exampleSocket.onopen = function (event) {
  window.ReactNativeWebView.postMessage("onopen")
}

exampleSocket.onerror = (e) => {
  window.ReactNativeWebView.postMessage('onerror')
}

exampleSocket.onmessage = (e) => {
  window.ReactNativeWebView.postMessage('onmessage')
}

        `}
        source={{ html: '<html><body></body></html>' }}
      />
```

**Comment by parkcoop** [comment]
I have the same issue, seems to have something to do with the way callbacks are handled

**Comment by benallfree** [comment]
Would love to hear from a maintainer on this issue :)

**Comment by revolunet** [comment]
Has anyone managed to use websockets in react-antive-webview ?

**Comment by PetterNo** [comment]
We have tried to use websockets in a react-native-webview, without success. Best not to auto-close this issue?

**Comment by ordinaryprobably** [comment]
I am having the same issue.

If I open the webview url in my macbook chrome, server catches the socket connection.

But nothing hits the server when I open it on my RN webview..

**Comment by maison-shibumi** [comment]
Why was this closed before getting a maintainer to respond? This is still a very valid issue that is not covered in any documentation whatsoever that I can find.

**Comment by ouya99** [comment]
Anyone successfully used websockets in react native webview? i have it running fine in browser, but connection disconnects and lags very quickly on webview

**Comment by Dxg125** [comment]
Its working on my side (tested with normal XML/Data-Requests and JS-SIP WebRTC) 
when adding `useWebView2={true}`

Broke it down to this, maybe it helps someone;
`  return (
    <WebView
      useWebView2={true}
      mixedContentMode={`always`}
      originWhitelist={[`https://*`, `wss://*`]}
      source={{ uri: src }}
    />
  );`

**Comment by maison-shibumi** [comment]
I was able to resolve this by updating iOS on my testing device to iOS 16+. There was a weird issue in iOS 15 with the way Safari handled WebSockets. I was seeing the web sockets work fine in the desktop browser but on mobile Safari they did not work. After updating to iOS 16+ the Web Sockets worked as they should.

Here is a Github issue referencing the issues with iOS 15 and RN WebView: https://github.com/react-native-webview/react-native-webview/issues/2281

**Comment by DominicTobias** [comment]
Websockets were working when loading exactly the same code from a remote URL but as soon as I moved it to local code in ios/android folder I got a websocket close 1006 event, including on iOS 16.4.

Nothing such as `originWhitelist=['*']` or `mixedContentMode='always'` or `useWebView2` helps, it just doesn't connect in iOS or Android with local files for some reason. Testing on `react-native-webview` 12.1.0 + 13.3.0

**Comment by mikicnemanja** [comment]
This worked for me:

```
const WebViewComponent = ({ navigation, webAppUrl, setIsWebViewLoading }) => {
  const handleWebMessageEvent = {
    ...
  }

  return (
    <WebView
      startInLoadingState={true}
      onLoad={() => setIsWebViewLoading(false)}
      incognito={false}
      scalesPageToFit={true}
      androidHardwareAccelerationDisabled={true}
      source={{
        uri: webAppUrl,
      }}
      onMessage={event => handleWebMessageEvent(event.nativeEvent.data)}
      useWebView2={true}
      mixedContentMode={'always'}
      originWhitelist={['*']}
    />
  );
};

export default WebViewComponent;
```

**Comment by Sharath-Dimaag** [comment]
Nothing worked for me? Did anyone find a solution to this issue?

**Comment by VamshiAlugoju** [comment]
did anyone find solution to this?

**Comment by Sharath-Dimaag** [comment]
> did anyone find solution to this?

It worked for me, I had some connection issue because of some wrong port. There is a way to debug webviews. Take a look at this, you can actually inspect webviews.

[Debugging WebViews](https://developer.chrome.com/docs/devtools/remote-debugging/webviews)

**Comment by mikicnemanja** [comment]
You might have an issue in the code of the application that is injected into the webview

**Comment by diegoleondev** [comment]
Has anyone solved this problem?

I'm using Expo WebView.
