### ISSUE TITLE
Support for React Native 0.64

### ISSUE THREAD

**Issue by danielwinkler** [react-native-webview/react-native-webview#1886]
According to the peer dependencies, react-native-webview does not support RN 0.64.
When trying to use it with the latest RC for react native (0.64.0-rc.3), the webview works nicely on Android but fails to compile on iOS on a fresh project.

    npx react-native init RN064 --version 0.64.0-rc.3
    cd RN064
    yarn add react-native-webview
    (cd ios; pod install)
    npx react-native run-ios

Resuls in

    The following build commands failed:
    	CompileC ~/Library/Developer/Xcode/DerivedData/RN064-asqxbveiinzdjyfjuanlqbaunxro/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Flipper.build/Objects-normal/x86_64/FlipperRSocketResponder.o /tmp/RN064/ios/Pods/Flipper/xplat/Flipper/FlipperRSocketResponder.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
    (1 failure)

It seems that rn 0.64 will soon be released as stable, it would be nice if react-native-webview would already be ready for it
https://github.com/react-native-community/releases/issues/214

**Comment by exotexot** [comment]
Maybe try to disable Flipper integration in your podfile

**Comment by jhlia0** [comment]
I solved this error after updating podfile.
```
use_flipper!({ 'Flipper' => '0.74.0' })
```

then run `pod install`

reference:
https://stackoverflow.com/questions/66118122/lexical-or-preprocessor-issue-event2-event-config-h-file-not-found

**Comment by danielwinkler** [comment]
Thanks a lot, for your help, 

    use_flipper!({ 'Flipper' => '0.74.0' })

fixed the error but unfortunately brought up another one, which is discussed already here
https://github.com/react-native-community/releases/issues/214#issuecomment-779920261

However, the very latest versions (~0.75.1) of flipper solved that issue in my case 

    use_flipper!({ 'Flipper' => '0.76.0' })
