### ISSUE TITLE
"RNCWebView" was not found in the UIManager

### ISSUE THREAD

**Issue by software3daerospace** [react-native-webview/react-native-webview#1889]
**Bug description:**

I am very badly struck in react-native-webview linking. Where I have ended up in this particular issue which is again very common issue and already reported in this forum. But the solution doesn't work in my case.

**To Reproduce:**

I followed this documentation (https://github.com/react-native-webview/react-native-webview/blob/master/docs/Getting-Started.md#2-link-native-dependencies) and properly setup.

**Expected behavior:**

Given source page without error 

**Screenshots/Videos:**

![image](https://user-images.githubusercontent.com/79135954/108834794-e45dd700-75ce-11eb-8847-68819b30d2a2.png)

**Environment:**

I am getting this issue in android.
 - OS:
 - OS version:
 - react-native version: "~0.63.4",
 - react-native-webview version: "^11.2.3",

**Comment by AnayoOleru** [comment]
@software3daerospace  were you able to fix this?

**Comment by stan-sack** [comment]
you need to reinstall your on the device or emulator after running `npm install --save react-native-webview` so that it has the new native code. I can't believe no one helped you with this.
