### ISSUE TITLE
How to pass and fetch data in React native webview

### ISSUE THREAD

**Issue by emanu7478** [react-native-webview/react-native-webview#1890]
I'am running JavaScript code in react native web view. Here I want to pass data inside script tag and also want to retrieve data from function inside the script tag. I' am stuck with this error. Will anyone suggest a solution to pass and retrieve data in react native web view.

     ` var HTML = <html>

     <meta name="viewport" content="width=device-width, initial-scale=1" />

      
     <script id="context" type="text/javascript" 
     src="https://sandbox-payments.open.money/layer"></script>

    <body>
    <script>

    Layer.checkout({
        token: "payment_token",
        accesskey: "access_key"
    },
    function(response) {
    
        if (response.status == "captured") {
                        
           // response.payment_token_id
           // response.payment_id

        } else if (response.status == "created") {

        } else if (response.status == "pending") {

        } else if (response.status == "failed") {

        } else if (response.status == "cancelled") {

        }
    },
    function(err) {
        //integration errors
    }
    );
    </script>
    </body>

     return(
         <WebView
         source={HTML}
        />
         )`

Here I want to fetch response data from function and also want to pass token to it

**Comment by aanalmehta-sa** [comment]
Hey, I am facing the same issue. Did you find any solution?
