### ISSUE TITLE
window.postMessage is firing multiple times in angular Onint function

### ISSUE THREAD

**Issue by sunilchilami** [react-native-webview/react-native-webview#1892]
I m working on angular 8 project and we sending post message to communicate with react native but issue we facing is for single load post message firing multiple message insted of sending one time on load or route change.

**window["ReactNativeWebView"] && window["ReactNativeWebView"].postMessage(JSON.stringify({"change": false}))
![Capture](https://user-images.githubusercontent.com/32094982/109134396-ffba1500-777b-11eb-90dc-265ce30c9c07.JPG)

i am sending post message to native & i used this above code in ngOnInIt or Route Change but messages are firing multiple times .that issue i m facing .that has to send single postmessage but each time throwing multi messages.please give me a solution thank you**

`  ngOnInit() {
      this.service.userDetails = JSON.parse(localStorage.getItem('userDetails'))
      window["ReactNativeWebView"] && window["ReactNativeWebView"].postMessage(JSON.stringify({"change": false}))
      console.log("notifyReact")
      if(this.service.userDetails==null)
        this.router.navigate(['healthworker/login'])
      else {
        this.getPatientList()
        this.getDoctorList()
      }
  }`

 

**Expected behavior:**

**Comment by alitsvin** [comment]
It's still the issue. But I found such solution: I generate some unique key for a message and handle it only once on the other side
