### ISSUE TITLE
Images not rendering from URL when source is HTML string

### ISSUE THREAD

**Issue by sridhareaswaran** [react-native-webview/react-native-webview#1896]
**Bug description:**
Images from URLs not loading when trying to set HTML string in the "source". The IMG tag is not loading when src is set to URL but works with base64. Also, images set as "background-image" aren't loading.

Here is my HTML string: [link](https://gist.github.com/sridhareaswaran/d350514d534c66729070b732c2700aab)

Here is my function to render the webview:

`const render_webview = (htmlSource) => {
    const insert_img_style = "
      setTimeout(() => {
        var sheet = document.createElement('style');
        sheet.innerHTML = ".image_resized { width: ${fullWidth}px !important; height: auto !important; object-fit: contain !important;} img { width: ${fullWidth}px !important; height: auto !important; object-fit: contain !important;}";
        document.body.appendChild(sheet);
    }, 500);"
 
    return (
      <WebView
        ref={webviewRef}
        style={{ marginTop: 20 }}
        source={{
          html: htmlSource,
        }}
        originWhitelist={["*"]}
        javaScriptEnabled
        injectedJavaScript={insert_img_style}
        domStorageEnabled
        allowFileAccessFromFileURLs
        allowUniversalAccessFromFileURLs
        startInLoadingState
        mixedContentMode="compatibility"
        ignoreSslError
        onNavigationStateChange={handleWebViewNavigationStateChange}
      />
    );
  };`

**Expected behavior:**
Images should be loaded from the URL like the one below.
![image](https://user-images.githubusercontent.com/9800626/109480367-723f3380-7aa1-11eb-8e8e-bd1efb16fa76.png)

**Screenshots/Videos:**
But the images are not loaded.
![image](https://user-images.githubusercontent.com/9800626/109480488-9438b600-7aa1-11eb-9f87-74f9e4a24dd3.png)

**Environment:**
 - OS: IOS
 - OS version: 10.14.6 Mojave
 - react-native version: 0.60.5
 - react-native-webview version: 6.9.0

**Comment by prashil-muzero** [comment]
same issue facing any solution on it ?

**Comment by castalonirenz** [comment]
anyone?
