### ISSUE TITLE
scalesPageToFit - ios

### ISSUE THREAD

**Issue by uri-inmanage** [react-native-webview/react-native-webview#1901]
Hi,

In Webview props I set the scalesPageToFit prop to false.
In android OS I get nice and good view of the webview.
but on IOS I get small view of the webview as shown in desktop, because this prop is not supported in IOS.
I tried to add the property contentMode={'mobile'} but no change.

is there any other prop that might do the job or is there anything else that could help?

**Environment:**
 - OS: Ios
 - OS version: *
 - react-native version: 0.63.4
 - react-native-webview version: 10.9.2, 11.0.0

**Comment by ajp8164** [comment]
I have this problem as well. The map we present is unreadable since the text is so tiny. Ideas welcomed.
