### ISSUE TITLE
Webview does not open universal/app links

### ISSUE THREAD

**Issue by mbr93** [react-native-webview/react-native-webview#1906]
**Bug description:**
In our app, we need to handle universal links and app links so that when we open such url from webview (or if we are being redirected), and we have installed the app that can handle such URL, we are redirected to the corresponding app.

For instance, for URL like https://oauth.tiaa.barclays.com/ we want to be redirected to the Barclays app if it's installed, and if not - such url should be handled by webview.
Currently, this is not happening - all the URLs are handled by the webview.

I've whitelisted the origins like so:
```
<WebView
   originWhitelist={["*"]}
   ...
/>
```

For android, I've tried to add intent to AndroidManifest.xml:
```
<intent-filter android:autoVerify="true">
    <action android:name="android.intent.action.VIEW" />
    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />
    <data android:scheme="https"
          android:host="www.oauth.tiaa.barclays.com"
          android:pathPrefix="/BarclaysPersonal/as/authorization.oauth2" /> // tried with and without pathPrefix
  </intent-filter>
```
but it does not have any effect on webview.

Are there any additional steps required for react-native-webview to support app2app redirection?

**Environment:**
 - OS: Android, iOS
 - OS version: all
 - react-native version: 0.63.2
 - react-native-webview version: 11.2.3, 10.8.3, 8.0.1

**Comment by blueberry6401** [comment]
@mbr93 did you solve this?

**Comment by fabriciosautner** [comment]
same problem
