### ISSUE TITLE
Redirecting user to another url if there is no response from the initial url for a certain period of time

### ISSUE THREAD

**Issue by Maharshi01** [react-native-webview/react-native-webview#1910]
Is it possible to redirect the user to another url if the initial url is not loaded yet for a certain period of time?
For example, the initial url is https://initialurl.com and it's not loaded for 10 sec and now after 10 sec i want to redirect user to another url which is https://anotherurl.com.

**Comment by timboektoe** [comment]
Yes, you could for example set a timeout that redirects the webview to https://anotherurl.com by resetting the uri of the webview. In case you receive an onLoad event for https://initialurl.com you cancel the timeout. Beware that setTimeout to 10 seconds does not guarantee at all that it will actually wait 10 seconds. In case you want to guarantee a minimum of 10 seconds before redirecting it might be a better approach to check timestamps using setInterval.
