### ISSUE TITLE
Redirect issue on iOS 12

### ISSUE THREAD

**Issue by sr1000** [react-native-webview/react-native-webview#1911]
I have a webview that loads our external provider's authentication page, makes a couple of redirects in the background and I'm listening for a specific callback redirect using **onNavigationStateChange** prop before taking the user to the app's home page. This works on Android and on iOS versions 13+ but doesn't work on iOS 12.4, for example.

It seems that some cookies/data gets lost when sending data from the webview to the back-end and back when running on iOS 12 (the result is just a blank screen). Has anyone ran into an issue like this and could provide some insight, please?

**Comment by timboektoe** [comment]
Hi I am the author of https://github.com/react-native-webview/react-native-webview/issues/1654 A few days ago we also noted some redirect issues on ios 13 with some of the sites we provide access to through react-native-webview. We were able to work around it by forcing the webview to reload the page for a second time  and then magically the redirects worked. 

The instability of the handling of redirects in the react-native-webview somewhat frightens me as it is very important our users can access these sites through our app. We also did tests with the native Android WebView and iOS WebView and did not stumble upon any problems with redirects. 

One of the problems we noted is that the referer header value is not set correctly upon redirects. We tried to workaround this problem by setting the referer headers manually, but this does not seem to work in all cases as some default Referrer-Policies seems to override this behaviour, but I have no idea how to circumvent this. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy

**Comment by xsaahil** [comment]
Hi, I am having this same issue where the Webview redirects multiple times for auth and fails to render the page. This works fine in Android. Anything we can do now except reloading the page again after which it works?

**Comment by makcim392** [comment]
Hi, I'm having the same issue using webview, it works fine in Android and it cannot redirect in IOS

**Comment by ArnoldRestrepo** [comment]
Hi, I'm having the same problem in out App, We need to make a couple of redirections with a web flow in the App, in Android works fine but in IOS the redirect not done and generates a blank page.

**Comment by menna-magdy-182** [comment]
I have the same issue, working fine on android but on iOS no

**Comment by CharlieBreval** [comment]
Same issue there, also seeing a blank page

Only workaround is telling to the client to update the OS

**Comment by CharlieBreval** [comment]
@Titozzz Sorry to bother you, maybe we should reopen this issue as it is still here. 
In the best case someone will fix it 🙏 , otherwise people can find why they have a blank page on ios 12 more easily
