### ISSUE TITLE
Cannot open intent on Android

### ISSUE THREAD

**Issue by TaekwanMin** [react-native-webview/react-native-webview#1912]
url looks like this
> intent://?xid=5798643#Intent;scheme=mpocket.online.ansimclick;package=kr.co.samsungcard.mpocket;end;

cannot be opened, even I added "intent://" to originWhiteList prop.
so I tried to open intent with "react-native-send-intent",
but seems like **shouldOverrideUrlLoading** in **RNCWebViewManager.java** does not accept intent link.

is there any solution to make it possible to open intent link?

here is my source code, console.logs and shouldOverrideUrlLoading

<img width="465" alt="Screen Shot 2021-03-11 at 5 39 55 PM" src="https://user-images.githubusercontent.com/51706290/110759312-cf509b80-8290-11eb-9320-a8c9f56bf4c9.png">

<img width="576" alt="Screen Shot 2021-03-09 at 10 47 31 AM" src="https://user-images.githubusercontent.com/51706290/110758910-636e3300-8290-11eb-9db7-19bf51256ccb.png">

![unnamed](https://user-images.githubusercontent.com/51706290/110758920-65d08d00-8290-11eb-9028-ac046208250d.png)

<img width="1840" alt="Screen Shot 2021-03-11 at 5 35 20 PM" src="https://user-images.githubusercontent.com/51706290/110758951-6e28c800-8290-11eb-827d-85521f804ab6.png">

**Environment:**
 - OS: macOS Big Sur
 - OS version: 11.2.1
 - react-native version: 0.63.4
 - react-native-webview version: 11.2.4

**Comment by Leleka14** [comment]
same problem, did u find a solution?

**Comment by camboYY** [comment]
i still face such issue

**Comment by arthurg91** [comment]
i still face such issue

**Comment by tkmin** [comment]
change originWhitelist

originWhitelist={[`http://*`, `https://*`, `intent://*`]}

**Comment by Rekha16** [comment]
> change originWhitelist
> 
> originWhitelist={['http://_', 'https://_', 'intent:*']}

I tried this for me not working

**Comment by tkmin** [comment]
> > change originWhitelist
> > originWhitelist={['http://_', 'https://_', 'intent:*']}
> 
> I tried this for me not working

are you using react-native-send-intent for android?
add below code at AndroidManifest.xml and try again.
```
<manifest>
   ...
    <permission android:name="android.permission.QUERY_ALL_PACKAGES" />
    <queries>
        <intent>
            <action android:name="android.intent.action.MAIN" />
        </intent>
    </queries>
</manifest>
```

**Comment by prakash2091** [comment]
Hi,

Do we have solution for this issue?

i still face the issue after adding originWhitelist={['http://','https://','intent:*']}

**Comment by kranthi1216** [comment]
Hi anyone have solution for this issue
i tried above but still facing same issue
can anyone help?

**Comment by patissier-boulanger** [comment]
+1

**Comment by tkmin** [comment]
> change originWhitelist
> 
> originWhitelist={['http://_', 'https://_', 'intent:*']}

eventually, my originWhitelist ends up with this below 0-<

`originWhitelist={['*']}`

**Comment by tkmin** [comment]
> change originWhitelist
> 
> originWhitelist={['http://_', 'https://_', 'intent:*']}

eventually, my originWhitelist ends up with this below 0-<

originWhitelist={['*']}

**Comment by ukcasso** [comment]
> > > change originWhitelist
> > > originWhitelist={['http://_', 'https://_', 'intent:*']}
> > 
> > 
> > I tried this for me not working
> 
> are you using react-native-send-intent for android? add below code at android/app/src/main/AndroidManifest.xml and try again.
> 
> ```
> <manifest>
>    ...
>     <permission android:name="android.permission.QUERY_ALL_PACKAGES" />
>     <queries>
>         <intent>
>             <action android:name="android.intent.action.MAIN" />
>         </intent>
>     </queries>
> </manifest>
> ```

this solution is dangerous
https://support.google.com/googleplay/android-developer/answer/10158779

you have to delete code line
`<permission android:name="android.permission.QUERY_ALL_PACKAGES" />`

add below code at android/app/src/main/AndroidManifest.xml and try again.
```
<manifest>
   ...
    <queries>
        <intent>
            <action android:name="android.intent.action.MAIN" />
        </intent>
    </queries>
</manifest>
```
