### ISSUE TITLE
Download issue: Downloaded file contains page HTML rather than actual content

### ISSUE THREAD

**Issue by rameshpatel79** [react-native-webview/react-native-webview#1914]
If the page shown in WebView contains a button that dynamically generates a file (e.g. PDF, CSV etc), the downloaded file contains the HTML of the page rather than actual data sent by server. Please note that this file is generated and returned as response so we do not have direct link to .PDF, .CSV etc files.

**To Reproduce:**
1. Very simple sample created here: https://snack.expo.io/@rameshpatell79/react-native-webview-download-error
2. Just open this snack on android expo app and allow storage permission (for download)
3. Click on Export Data button
4. View downloaded file content

**Expected behavior:**
The downloaded file should contain actual content sent by server rather than page html.

**Screenshots:**

Sample page containing download button: 
![image](https://user-images.githubusercontent.com/71537558/111020337-1e124880-83eb-11eb-9159-eabc3f7d6bbb.png)

Downloaded file contains page HTML rather than actual data:
![image](https://user-images.githubusercontent.com/71537558/111020347-31251880-83eb-11eb-88cd-d016bb36e0d4.png)

**Environment:**
For this sample: Snack
Actual: Expo: 40.0.0, React-native: 0.63, react-native-webview: 11.0.0

**Server Code:**
Below is the code (C#) that gets executed when button is clicked to create and download file. Please note that this is pseudo code created to demonstrate the issue. The actual website we are using, we have no control on it and do not know what code is written. So, there is no option of changing server/website code.

```
string attachment = "attachment; filename=temp.csv";
HttpContext.Current.Response.Clear();
HttpContext.Current.Response.ClearHeaders();
HttpContext.Current.Response.ClearContent();
HttpContext.Current.Response.AddHeader("content-disposition", attachment);
HttpContext.Current.Response.ContentType = "text/csv";
HttpContext.Current.Response.AddHeader("Pragma", "public");
// Prepare file content
HttpContext.Current.Response.Write(fileContent.ToString());
HttpContext.Current.Response.Flush();
HttpContext.Current.Response.Close();
```

**Comment by rameshpatel79** [comment]
Can someone look into this issue? This issue can be reproduced consistently with very simple steps as mentioned above.

**Comment by cshah-mn** [comment]
@Titozzz @jamonholmgren 
We have tried many things and nothing seems to be working. Our project is at a complete standstill due to this issue. 

If someone can direct us to other package or branch/commit which does not have this problem, that would also work for us provided that it is compatible with our environment.

**Comment by timboektoe** [comment]
@rameshpatel79  
It would be helpful to get insight in the actual js code that gets executed within the webview. As far as I can see it is scrambled. It might be the case that the cause of your problem is there.

**Comment by rameshpatel79** [comment]
@timboektoe 
Thank you for your reply. 

The actual JS code is very big and complex and that's why I created a very simple sample here: https://snack.expo.io/@rameshpatell79/react-native-webview-download-error which does not execute any JS code. It just loads one webpage which has a button which when clicked, causes issue (downloaded file contains page HTML rather than content sent by server). Any idea on what could cause this behavior?

Thanks you in advance! Last 9 days were very long as this issue has caused complete freeze for our project.

**Comment by timboektoe** [comment]
Hi @rameshpatel79 ,

Did you already debug your webview using? :
https://developer.chrome.com/docs/devtools/remote-debugging/webviews/

Interesting to see what actually happens.

I think as a workaround it should be possible to collect your document using the fetch api instead of using a form. You can then catch the result of your fetch and communicate it to your app using window.ReactNativeWebView.postMessage. In your app you can then listen for messages from your page using the onMessage event handler of webview. From there you can store the file. This approach could also be helpful if you want to stick to using forms: https://stackoverflow.com/questions/5384712/intercept-a-form-submit-in-javascript-and-prevent-normal-submission

Using the fetch workaround would be a last resort in my opinion, better first try to debug the webview.

**Comment by rameshpatel79** [comment]
Thanks @timboektoe for your detailed answer. We will try both the approaches you suggested. 

For the later approach (fetch api), I just wanted to mention that it is not the website that we have control over and it is highly secured finance domain website so not sure if intercepting form submit would work. I will keep you posted.

**Comment by timboektoe** [comment]
Hi @rameshpatel79 ,

I have some experience with downloading files from these kind of websites. While debugging the webview it is important to check the csp response headers of the page that you are loading, for example connect-src: none will forbid you to download a file using script. (in that case the fetch approach won't work) connect-src self however enables you to inject a script that downloads your file.

https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy

**Comment by rameshpatel79** [comment]
I am still searching for solution. Can someone try very simple reproducible sample: https://snack.expo.io/@rameshpatell79/react-native-webview-download-error

**Comment by rameshpatel79** [comment]
How can I reopen this issue?

**Comment by t3chcrazy** [comment]
Hey @rameshpatel79 , did you find a solution for it? I am also facing the same issue

**Comment by androsanta** [comment]
Hi, I have the same problem. I haven't found any workaround yet

**Comment by ohszehong** [comment]
I'm facing the same issue, may I know are there any solutions?
