### ISSUE TITLE
Redirect Bug on Android occurring within Expo context but not in Vanilla React Native App

### ISSUE THREAD

**Issue by timboektoe** [react-native-webview/react-native-webview#1917]
I made a very simple (Android) application to illustrate this problem. It's a WebView pointing to: https://www.uwv.nl/particulieren/mijnuwv/index.aspx . When I load this application in my expo app I click the first login button. Then a couple of redirects occur and you should be sent to a login screen, but instead of that the original page reloads itself due to to redirection issues with the react-native-webview. 

When I run this same application in the context of a Vanilla React Native app (using the same version of react-native-webview) this redirection bug does not occur and I am redirected to the login page without any problems.

How on earth is this possible? There should be no difference in functionality as I am using the same version of react-native-webview. 

**Environment:**
 - OS: Android
 - OS version: any
 - react-native version:
 - react-native-webview version: 11.2.4

**Comment by memon07** [comment]
any updates on this ?

**Comment by timboektoe** [comment]
No, still trying to find the cause. Any help would be appreciated

**Comment by memon07** [comment]
@timboektoe sure i am still finding a solution to this , i am facing the redirect issue with vanilla react native too

**Comment by safeandroidtv** [comment]
Hi, still no solution?

**Comment by memon07** [comment]
@safeandroidtv when i made an apk of my project (using expo cli ) , everything was working fine  , can you please try it once ?
