### ISSUE TITLE
Feature to scrollTo a position in the page

### ISSUE THREAD

**Issue by braincore** [react-native-webview/react-native-webview#1919]
Like the [scrollTo method for a ScrollView](https://reactnative.dev/docs/scrollview#scrollto), it'd be useful to be able to scroll to a specific part of a page without having to inject JS.

Currently, I'm recording the viewport position relative to the page using `onScroll` and would like to return a user to that exact position at a later time.

**Comment by mouhsnimohamed** [comment]
I have the same need, in my case I can't inject javascript into my webview

**Comment by castalonirenz** [comment]
Same issue

**Comment by dutescucristina** [comment]
It is necessary to have this feature.

**Comment by Goran-VRBANCIC** [comment]
Is there a way to just get/set the scroll value of the webview scroller ?
