### ISSUE TITLE
Encountered an error loading page {description: "net::ERR_INTERNET_DISCONNECTED"}

### ISSUE THREAD

**Issue by Rajan-Savaliya-spt** [react-native-webview/react-native-webview#1920]
**Bug description:**

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS:
 - OS version:
 - react-native version:
 - react-native-webview version:

**Comment by MoamberRaza** [comment]
Same Issues 
"react": "17.0.1",
    "react-native": "0.64.0",

Nothing is being displayed in webview. 
if i passed local string as html tag it shows but on passing URI  it doesn't .. 
Please fix it ASAP..

**Comment by Rajan-Savaliya-spt** [comment]
> Same Issues
> "react": "17.0.1",
> "react-native": "0.64.0",
> 
> Nothing is being displayed in webview.
> if i passed local string as html tag it shows but on passing URI it doesn't ..
> Please fix it ASAP..

i have a same issue .. you have a any solution....... i need help....

**Comment by MoamberRaza** [comment]
@Rajan 
I just open it because i were facing same issue,
 So it is request to the developers of this library kindly pls fix this issues ASAP as it is working with ios completely fine but not working with android 10 9 ... i have check it on emulator and real device.

**Comment by zhangyanni666** [comment]
I have the same question

**Comment by shivamXI** [comment]
This issue is still there in our production environment. Request you to please look into it and suggest a fix.
