### ISSUE TITLE
Incorrectly rendering select HTML tag options on Android 

### ISSUE THREAD

**Issue by KrzysztofSakowski** [react-native-webview/react-native-webview#1922]
**Bug description:**
When `select` HTML tag is clicked its options are rendered at the top of the screen instead of close to `select` tag. Please attached screenshots for details.

**To Reproduce:**

1. Open https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select in `react-native-webview`
2. Click on `select` HTML tag
3. Options are rendered at the top of the screen

**Expected behavior:**
Options are rendered close to `select` tag

**Screenshots:**

*Native Android WebView*
<img width="1231" alt="android_webview" src="https://user-images.githubusercontent.com/8568869/111474607-87b48e80-872c-11eb-9538-cefbe4cd1e30.png">

*react-native-webview version 11.2.5*:
<img width="1201" alt="latest_rn_webview" src="https://user-images.githubusercontent.com/8568869/111474621-8aaf7f00-872c-11eb-9c33-c33d022ae4d6.png">

**Environment:**
 - OS: `Android`
 - OS version:  `9`
 - react-native version: `0.63.4`
 - react-native-webview version: `11.2.5`

**Comment by KrzysztofSakowski** [comment]
Still searching for solutions.

**Comment by Diordrzy** [comment]
same problem 😫
