### ISSUE TITLE
webview unable to request api

### ISSUE THREAD

**Issue by gaoxuan-haxibiao** [react-native-webview/react-native-webview#1924]
**Bug description:** 
some mobile phone webview request api error : 
Request header field Authorization is not allowed by Access-Control-Allow-Headers in preflight response。
However, other mobile phones and browsers can request it normally

**Expected behavior:**  request successful

**Screenshots/Videos:**
![image](https://user-images.githubusercontent.com/36940267/111727027-09c7c300-88a5-11eb-9c9f-ad97cbebfbdc.png)

**Environment:**
 - OS:Android
 - OS version:7.1.1
 - react-native version:0.63.0
 - react-native-webview version:9.4.0
 - brand:OPPO A83t
 - android system webview:62.0.3202.84

**Comment by yabao-zy** [comment]
The same problem encountered in Telegram authorization

**Comment by togoog** [comment]
想问一下，该问题是如何解决的，感谢。
