### ISSUE TITLE
All post-robot messaging strategies failed

### ISSUE THREAD

**Issue by codingedgar** [react-native-webview/react-native-webview#1928]
**Bug description:**

Hi! I Implemented PayPal's [Smart Payment Button](https://developer.paypal.com/docs/checkout/integrate/) successfully in an older version of RN (0.46) without an issue, but today I made a new project with the latest expo-cli, installed `react-native-weview` and the button stop working.

It's showing me this error:

```
Error: Send request message failed for onInit() in https://www.sandbox.paypal.com

All post-robot messaging strategies failed:

0. The string did not match the expected pattern.
postMessage@[native code]
postrobot_post_message@
````
I'm not sure if there's something new I need to give permission in the webview, I gave all of these so far:
```
              javaScriptEnabled
              javaScriptCanOpenWindowsAutomatically
              mixedContentMode="always"
              thirdPartyCookiesEnabled={true}
              setSupportMultipleWindows={true}
              useWebKit={Platform.OS == 'ios'}
              domStorageEnabled
```

**To Reproduce:** 

I'm not sure how to duplicate this and let you reproduce it without giving paypal information, any ideas?

**Expected behavior:**

The webview had no issues with the same code in RN 0.46

**Screenshots/Videos:**

**Environment:**
 - OS: macOS
 - OS version: 11.2.3
 - react-native version: 0.63.3
 - react-native-webview version: 11.0.0

**Comment by codingedgar** [comment]
I just finished removing onMessage and still have the same problem

**Comment by onurio** [comment]
@codingedgar Any luck? facing the same issue.

**Comment by onurio** [comment]
solved it by adding `baseUrl: http://localhost` to the source as a parameter to WebView locally for it to work.
