### ISSUE TITLE
Feature Request: Can the entire content of an app be bundled to work offline with WebView?

### ISSUE THREAD

**Issue by inglesuniversal** [react-native-webview/react-native-webview#1929]
Use case scenario: We have high demand to create educational apps that need to have the entire content available to work offline (with no internet / wifi / network connection at all).

Can all the contents which pretty much comes down to HTML, CSS and JAVASCRIPT be placed inside an Expo App (without the need to eject it from Expo) and only make use of basic WebView features and perhaps some Expo API's that don't need an actual internet connection?

Thanks for your kind considerations.

**Comment by dangthaison91** [comment]
@inglesuniversal Have you resolve this issue? We are having the same requirement with our production web app.

**Comment by inglesuniversal** [comment]
Sadly no @dangthaison91 ... I have asked for options or ideas right here where the main code for webview resides and unfortunately no one has given me an option or slight possibility of how it can be done.

Other than that, there are others frameworks that can do that, but they are more like old school stuff by using cordova libraries. I hope that by keeping this topic and thread alive it can make the EXPO team realize that this is an important topic as well. 

#STAYSAFE

**Comment by brianwachira** [comment]
> Use case scenario: We have high demand to create educational apps that need to have the entire content available to work offline (with no internet / wifi / network connection at all).
> 
> Can all the contents which pretty much comes down to HTML, CSS and JAVASCRIPT be placed inside an Expo App (without the need to eject it from Expo) and only make use of basic WebView features and perhaps some Expo API's that don't need an actual internet connection?
> 
> Thanks for your kind considerations.

Hi @inglesuniversal , is it possible to run offline js from an ejected Expo app? That is what I am planning to do. If yes, could you maybe mention how I could achieve this?
