### ISSUE TITLE
iframe on iOS is not rendering content

### ISSUE THREAD

**Issue by BobbyWalker** [react-native-webview/react-native-webview#1933]
**Bug description:**
Our app is just a webview that displays our react website.   We have emails that are displayed to our users that are contained within an iframe, and it works as expected except on iOS.    On that platform the iframe is rendered, but the content is blank.   While I can switch to an Android device and see the content rendered as expected.

**Expected behavior:**
Content within the iframe should be rendered.   Here is a sample message body that We are using as the srcDoc:

`
<html>

<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
			<style type="text/css">
				* {
				padding:0;
				margin:0;
				}

				body {
				font-family:Helvetica;
				font-size:14px;
				line-height:21px;
				}

				.header {
				background-color:rgb(44, 152, 245);
				padding:1em;
				}

				.icon {
				margin-left:17px;
				}

				.text, .footer {
				font-size:14px;
				padding:2em;
				}
				
				.icon {
				height: 60px;
				}

			</style>
		</head>
	<body>
		<div class="header">
			<span class="logo">
				<img class="icon" src="https://tvcontent.blob.core.windows.net/teamviewer/mailtemplates/logo_inverted.png"/>
	</span>
		</div>
	<div class="text">
		<br /><br /> Hello Bobby Walker,<br />
		<br /> A new service case was created:
		<br />
		<br />Name:
		<b>Nicole</b>
		<br /> Session code:
		<b>s99-779-099</b><br />
		<b>2021-03-15 16:17:28 UTC</b>
		<br />
		<br />
		<a href="https://login.teamviewer.com/ShowServiceCase.aspx?code=s99779099">Open service queue</a><br />
		<br /> Email notifications about service cases can be changed in your
		<a href="https://login.teamviewer.com/nav/profile">profile settings</a> in the Management Console.<br />
		<br /> Regards<br />
Your TeamViewer Team<br />
------------------------------------<br />
<a href="https://www.teamviewer.com">www.teamviewer.com</a><br />
<br />
TeamViewer Germany GmbH * Bahnhofsplatz 2 * 73033 Goeppingen * Germany <br />
Tel. +49 (0)7161 60692 50 * Fax +49 (0) 7161 60692 79<br />
<br />
Registration AG Ulm HRB 534075 * CEO: Oliver Steil, CFO: Stefan Gaiser
	</div>
</body>

</html>
`

**Environment:**
 - OS: iOS
 - OS version:  14.x
 - react-native version: 0.63.2
 - react-native-webview version: 11.2.1

**Comment by lal12** [comment]
yeah I have the same issue. In my case I embedded an YouTube video. The iframe url is immediy opened in the browser, which displays the video, while the iframe stays blank in the webview.

**Comment by lal12** [comment]
Was reported before in #1832

**Comment by alexlamazing** [comment]
Facing the same issue. Any update or workaround for this?

**Comment by BobbyWalker** [comment]
> Facing the same issue. Any update or workaround for this?

I got it to work, I believe it was this line.

`originWhitelist={[*]}`

Added to the WebView.
