### ISSUE TITLE
React native 0.64.0 support

### ISSUE THREAD

**Issue by Chrischuck** [react-native-webview/react-native-webview#1935]
Issue was brought up a couple months ago here: [1886](https://github.com/react-native-webview/react-native-webview/issues/1886)

Wanted to resurface this since this is causing build issues when I attempt to upgrade.

```
error "react-native-webview#react-native@>=0.60 <0.64" doesn't satisfy found match of "react-native@0.64.0"
```

**Comment by swrobel** [comment]
As a note, I've been using with RN 0.64 throughout all of the RCs and haven't noticed any issues, although my use case is pretty simple.

**Comment by Chrischuck** [comment]
@swrobel Same, I used `package-patch` to allow 0.64. Again, we're using it for the simplest use case, but it would be nice to have legit support.

**Comment by MortezaHeydari97** [comment]
Hi, I've the same issue.
Please implement this feature as soon as possible.
So thanks !

**Comment by fabriziobertoglio1987** [comment]
I also experienced this issue. Removing `react-native-webview` from my project fixed the error on android.

**Comment by fabriziobertoglio1987** [comment]
experienced the same issue, and the reason was the minSdkVersion not bumped with the react-native-cli upgrade. Maybe an issue with react-native-cli?

https://react-native-community.github.io/upgrade-helper/?from=0.61.5&to=0.64.0

**Comment by DiegoCanedo** [comment]
Try to npm install react-native-webview@11.3.2

`npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: moovben@0.0.1
npm ERR! Found: react-native@0.64.0
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.64.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@">=0.60 <0.64" from react-native-webview@11.3.2
npm ERR! node_modules/react-native-webview
npm ERR!   react-native-webview@"11.3.2" from the root project`

**Comment by Oz-on** [comment]
To bypass this issue, you can try using `npm install --save --legacy-peer-deps react-native-webview`, which will omit peer-dependency however, this may cause some problems if the module is not prepared for the 0.64 version of react native.

**Comment by azlogs** [comment]
use `yarn add react-native-webview` instead of npm install react-native-webview
