### ISSUE TITLE
Latest Android crashing when re-open screen with WebView

### ISSUE THREAD

**Issue by pepemiso16** [react-native-webview/react-native-webview#1936]
**Current Behavior**

- What code are you running and what is happening?
Using react native navigation v5 with WebView (react-native-webview). For the latest version of Android phones, the WebView works, but if we close the app and re-open it the app is crashing when we go to the screen with WebView.

- Include a screenshot or video if it makes sense.
App is crashing

**Expected Behavior**
- The app should continue to display the WebView content

**How to reproduce**

- Run the app using latest version of Android phones, go to the screen that is using WebView
- Close the app and re-open it
- Go back to the screen with webview
- The app will then crash

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| Android                | 9.1.0
| @react-navigation/native       | 5.9.3
| react-native-webview | 11.3.1
| react-native                   | 0.63.3
| node                           | 15.8.0
| yarn                    | 1.22.10

P.S, I've tried to use **androidHardwareAccelerationDisabled={true}** and **animationEnabled: false** but still not working.

**Comment by TheAlmightyBob** [comment]
If you're just seeing this today, it's most likely the Android WebView crashing bug that was introduced by Google, and is affecting lots of apps (including GMail).

https://www.theverge.com/2021/3/22/22345696/google-android-apps-crashing-fix-system-webview
https://www.engadget.com/android-gmail-stop-running-webview-234125352.html
https://www.androidpolice.com/2021/03/22/surprise-app-crashes-are-plaguing-tons-of-android-users-heres-how-to-fix-them/

etc.

(the behavior you describe is identical to the WebView bug)

**Comment by anoopjangra90** [comment]
It was Android System WebView issue. Go to Settings->Apps-> Android Web View and remove system updates.

**Comment by pl4yradam** [comment]
I have tried the factory version and version 89, unfortunately, both crashing the app as well, removing <webview> the app will continue to work as expected.

**Comment by tanoto-the-explorer** [comment]
I also have this issue, I'm currently looking at react-native-webview documentation to see if I can specify the Android's WebView.

**Comment by memon07** [comment]
upgrading the version didn't resolve my problem . is there any other way for xiaomi's android ?
