### ISSUE TITLE
App crashes on Samsung Galaxy S6 (Android 7.0+) with `opacity: 0.99`

### ISSUE THREAD

**Issue by jd20** [react-native-webview/react-native-webview#1941]
**Bug description:**
Our app has a `WebView` wrapped in `View`, on which we set `opacity: 0.99`. On the Galaxy S6 (and a few other similar models, such as S6+, S6 Edge, etc...) with Android 7 or 8, the app will crash once the WebView renders.

If the OS is downgraded to Android 6, it stops crashing. If I change to `opacity: 1`, it also stops crashing. We've not seen crashes on any other devices.

**To Reproduce:**
This is the commit which introduced the crash to our app: https://github.com/jd20/react-native-signature-pad/commit/46ae4459514e14ef4bdc1f1872bc727dad8b4c77

Generally though, the WebView code looks like:

```tsx
    <View style={containerStyle} onLayout={onLayout}>
      {size && (
        <View style={size}>
          <WebView
            ref={setRef}
            automaticallyAdjustContentInsets={false}
            onMessage={onMessage}
            onLoadEnd={start}
            renderError={onError}
            renderLoading={loader}
            source={source}
            javaScriptEnabled={true}
            style={{
              ...StyleSheet.absoluteFillObject,
              backgroundColor,
              opacity: started ? 1 : 0,
            }}
          />
        </View>
      )}
    </View>
```

**Expected behavior:**
Not to crash.

**Environment:**
 - OS: Android
 - OS version: 7.0
 - react-native version: Any react-native version
 - react-native-webview version: 11.3.1

**Comment by superandrew213** [comment]
@jd20 when did you start seeing this? We started seeing this error on 22 March.

Do you have `overflow: 'hidden'` on parent View?

**Comment by jd20** [comment]
We are not using `overflow: 'hidden'` on the parent View (or anywhere else). We've been seeing the issue (only ever on S6 devices running Android 7 or higher) every since we added the `opacity: 0.99` fix (about 6 months ago).

**Comment by sr7354476** [comment]
I also faced same issue on Samsung Galaxy S7 series. Any solution you got @jd20 ?

**Comment by jd20** [comment]
Removing the `opacity: 0.99` seems to work fine. I've not seen crashes on any other devices so far, after removing it.

Still, if someone really did need to set `opacity: 0.99`, it'd be nice if `react-native-webview` didn't crash the app.

**Comment by avonipenti** [comment]
Has removing opacity caused any issues on Android 8+ as I see another issue in [Here](https://github.com/react-native-webview/react-native-webview/issues/1915)
I don't want to fix for Samsung while causing additional crashes for others.

**Comment by EricaLi123** [comment]
> Removing the `opacity: 0.99` seems to work fine. I've not seen crashes on any other devices so far, after removing it.
> 
> While that's a valid workaround, would be great to fix underlying issue, so if someone really did need to set `opacity: 0.99`, it wouldn't crash the app.

Do you mean that setting opacity fix some crashes but sometimes cause crash? Or just can't fix?
