### ISSUE TITLE
React-native-webview shows shrinked content on ios.

### ISSUE THREAD

**Issue by lavinagandhi14** [react-native-webview/react-native-webview#1942]
Hi People,

i am using react-native-webview in my application to show the html content. I am facing a weird behaviour with the plugin. 
I am getting a shrink image in the webview container in iOS(screen shot attached)  whereas in android it is working perfectly fine (occupying whole webview container).
In iOS, it is showing the same behaviour as it is showing on all the browsers. how can I make it work as android.

code: 
                  <WebView ref={WEBVIEW_REF => (WebViewRef = WEBVIEW_REF)} originWhitelist={['*']}
                    source={{ uri: 'URL COMING FROM BACKEND'}}
                   scalesPageToFit={Platform.OS !== 'ios'}
                   useWebKit={false}
                   contentMode={'mobile'}
                   style={{
                     marginTop: Platform.OS === 'ios'? 0: 15,
                    marginBottom: Platform.OS === 'ios'? 0: 15,
                    width: (window.width)<410 ? window.width-90 : 320 ,
                     aspectRatio: 1 / 1,
                     alignItems: 'center',
                     alignSelf: 'center',
                     flex:1,
                     justifyContent: 'center',
                     backgroundColor: 'transparent',
                     alignContent: 'center' 
                  }}
                    startInLoadingState={true}
                    javaScriptEnabled={Platform.OS === 'ios' ? true : false}
                    injectedJavaScript={INJECTEDJAVASCRIPT}
                    scalesPageToFit={Platform.OS === 'ios' ? true : false}
                    bounces={false}
                    scrollEnabled={false}
                    automaticallyAdjustContentInsets={true}
                />

Here are the versions for the plugins:
 "react": "16.13.1",
 "react-native": "0.63.4",
"react-native-webview": "11.2.3",
    
As the screenshot show,  I don't want this image to be shrinked.

![Simulator Screen Shot - iPhone 12 - 2021-03-26 at 19 28 10](https://user-images.githubusercontent.com/51702096/112643144-0cf51d00-8e6a-11eb-9508-dc5bf720a6e0.png)

Any kind of help would be really appreciated.

**Comment by RayKay91** [comment]
Try adding this to your html :<meta name="viewport" content="width=device-width, initial-scale=1">

**Comment by colbygarland** [comment]
Still searching for solutions on this, has anybody found a fix for it?

**Comment by BrandanDoesCode** [comment]
> Try adding this to your html : `<meta name="viewport" content="width=device-width, initial-scale=1">`

This fixed it thank you ! :)
