### ISSUE TITLE
iOS zoom issue when tapping text input field

### ISSUE THREAD

**Issue by potatoengineer** [react-native-webview/react-native-webview#1944]
**Bug description:**
The login screen is zoomed in correctly initially but when I tap a text field to enter username/password then tap away from it, it doesn't restore the original zoom. The right side is still clipped from view.

**To Reproduce:**
Create any webview with a sign up flow on iOS and tap on the text input.

**Expected behavior:**
Go back to original zoom view after tapping done on the keyboard or when tapping away from input field

**Code**
```
...
    const SCRIPT = `
    const meta = document.createElement('meta');
    meta.setAttribute('content', 'width=device-width, initial-scale=1.0, maximum-scale=1.0');
    meta.setAttribute('name', 'viewport');
    document.head.appendChild(meta);
    true;
    `;
    return <WebView source={{uri: myURL}} javaScriptEnabled onMessage={(event) => {}} 
    injectedJavaScript={SCRIPT} />
```

**Environment:**
 - OS: iOS
 - OS version: 14.4
 - react-native version: 0.64.0
 - react-native-webview version: 11.3.2

**Comment by MichaelPallister** [comment]
@potatoengineer I had a similar issue, setting the font size of the inputs explicitly to 16px stopped the zoom. Whilst it's not the behaviour you're wanting. It did mean I didn't have to worry about a user trying to zoom back out.

**Comment by muhamad-rizki** [comment]
try adding this on your html source page:
```
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
```
source: https://stackoverflow.com/a/46254706

**Comment by deleonjulio** [comment]
still searching for solutions
