### ISSUE TITLE
How can I access static file (like: js, css, .etc.)

### ISSUE THREAD

**Issue by tuan8797** [react-native-webview/react-native-webview#1948]
I've built a reactjs project and put the build folder into local device (IOS). In react native webview I put the path in source.
```
        <Webview
          ref={refWebview}
          source={{uri:`${RNFS.DocumentDirectoryPath}/build/index.html`}}
          onMessage={handleMessage}
          onLoadEnd={onLoadEnd}
          injectedJavaScript={sdk_js}
        />
``` 
But it don't render anything because it can not access static folder. How can I fix it. THANKS.

**Environment:**
 - OS: IOS, ANDROID
 - react-native version: 0.64.0
 - react-native-webview version: 11.3.2

**Comment by tuan8797** [comment]
> https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#allowFileAccessFromFileURLs

yes, I set allowFileAccessFromFileURLs, allowUniversalAccessFromFileURLs, allowingReadAccessToURL = true, but doesn't work for me.

**Comment by nikolasvasconcelos** [comment]
> > https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#allowFileAccessFromFileURLs
> 
> yes, I set allowFileAccessFromFileURLs, allowUniversalAccessFromFileURLs, allowingReadAccessToURL = true, but doesn't work for me.

With a html file, try using require and importing the whole html as source object:


       const MyHTML = require("path/to/html/file.html");
       [...]
       <Webview
          ref={refWebview}
          source={MyHTML}
          onMessage={handleMessage}
          onLoadEnd={onLoadEnd}
          injectedJavaScript={sdk_js}
        />


Hope it helps

**Comment by tuan8797** [comment]
thank you, I just found the solution. I fix it directly in native code.

**Comment by jonathanpalma** [comment]
@tuan8797 can you please share the solution?

**Comment by svpease** [comment]
> thank you, I just found the solution. I fix it directly in native code.

Can you share how you did that exactly?

**Comment by fukemy** [comment]
> thank you, I just found the solution. I fix it directly in native code.

plz share your solution
