### ISSUE TITLE
Videos not playing on android, only plays audio on Android. Works on iOS.

### ISSUE THREAD

**Issue by SurajMDurgad** [react-native-webview/react-native-webview#1954]
**Bug description:**

When ever you try to play a video whether it's Youtube, Vimeo, Dailymotion, it just plays audio, in place of video only black screen in displayed. You can hear the video playing but no visuals are displayed. It works perfectly fine on iOS.

**To Reproduce:**

```
import { WebView } from 'react-native-webview';

render() {
    return (
        <WebView source={{ uri: 'https://www.youtube.com/watch?v=X-x7eZOdBFM' }} />
    );
  }
```
**Expected behavior:**

Should play the video 🤷 

**Screenshots/Videos:**

![image](https://user-images.githubusercontent.com/13523678/114419900-75b1f880-9bd1-11eb-9884-af642cf03458.png)

https://user-images.githubusercontent.com/13523678/114420476-fbce3f00-9bd1-11eb-9680-29510506dbba.mov

**Environment:**
 - OS: Android
 - OS version: 10
 - react-native version: 0.63.2
 - react-native-webview version: 10.9.2 and 11.3.2

**Comment by SurajMDurgad** [comment]
@Titozzz @jamonholmgren Any idea why this might be happening?

**Comment by SurajMDurgad** [comment]
There was a bug on Android System Webview, which was resolved and it has nothing to do with the library.

**Comment by trithien98** [comment]
> There was a bug on Android System Webview, which was resolved and it has nothing to do with the library.

Hi, i have this issue, could you show me how to resolve it from Android System Webview.video work fine in ios and android when i play video have sound but i got black screen issue like you

**Comment by SurajMDurgad** [comment]
This issue was a bug with webview in android, nothing to do with react-native-webview. This issue was resolved. Ideally if you have set `android:hardwareAccelerated="true"` the videos should play.

**Comment by trithien98** [comment]
> This issue was a bug with webview in android, nothing to do with react-native-webview. This issue was resolved. Ideally if you have set `android:hardwareAccelerated="true"` in `Manifest.xml` the videos should play.

Thank you sir ! . i solve this problem for your solution

**Comment by aneena-thomas** [comment]
Hi @SurajMDurgad in which manifest I need to add this one android:hardwareAccelerated="true"? in library manifest or app manifest
