### ISSUE TITLE
Setting WKAppBoundDomains will block onMessage events

### ISSUE THREAD

**Issue by N3TC4T** [react-native-webview/react-native-webview#1956]
**Bug description:**

setting `WKAppBoundDomains` to the project and setting `limitsNavigationsToAppBoundDomains` prop to `false` will block getting `onMessage` events.

**To Reproduce:**

Add your domain to the `WKAppBoundDomains`
Don't set `limitsNavigationsToAppBoundDomains` prop or set it to `false`
Try to post a message to the webview with `postMessage`

**Expected behavior:**
To get the `onMessage` events after setting `WKAppBoundDomains` as the `limitsNavigationsToAppBoundDomains` prop is set's to false.

**Environment:**
 - OS: iOS
 - OS version: 14.4
 - react-native version: 0.64.0
 - react-native-webview version: 11.3.2

**Comment by somasekharkakarla** [comment]
setting WKAppBoundDomains to the project and setting limitsNavigationsToAppBoundDomains prop to false will block getting onMessage events.

**Comment by maclementED** [comment]
@N3TC4T Did you find a solution ? 
Im need to have both limitsNavigationsToAppBoundDomains to false and using onMessage
