### ISSUE TITLE
Cannot access encrypted media on Android webview.

### ISSUE THREAD

**Issue by promit13** [react-native-webview/react-native-webview#1957]
How can I enable support for encrypted media for webview on Android ? It works fine on ios webview.

**Environment:**
 - OS: Android
 - OS version: 10.0
 - react-native version: 0.64.0
 - react-native-webview version: 11.3.2

**Comment by asasouza** [comment]
Hi @promit13, how do you did make it work on iOS? And any news on Android?

**Comment by lllelll** [comment]
Hi @promit13, do you make it work on iOS?
