### ISSUE TITLE
WebView content shrinks on scroll and scroll is very laggy and slow

### ISSUE THREAD

**Issue by cw-sanjeev** [react-native-webview/react-native-webview#1965]
**Bug description:**
As attached in the below gif, when we scroll the webview, the webview shrinks then resizes for whatever reason. The scroll is also very slow and laggy, the app hangs for sometime as well. Loaded that same url on android native webview, its performance is great with no laggy or shrinking issue

**To Reproduce:**
Load any "heavy" url in react-native webview, when scrolling, the content shrinks and resizes. Gets laggy scroll and hangs.

**Expected behavior:**
Smooth scroll with no lag

**Screenshots/Videos:**
![Issue](https://user-images.githubusercontent.com/51712166/115881192-22f5fd80-a469-11eb-8abc-bd3c51615c09.gif)
https://user-images.githubusercontent.com/51712166/115881192-22f5fd80-a469-11eb-8abc-bd3c51615c09.gif

**Code**
<SafeAreaView style={{ flex: 1 }}>
          <KeyboardAvoidingView
            behavior={Platform.select({
              android: null,
              ios: "padding",
            })}
            style={{ flex: 1 }}
            enabled
          >
            <WebView
              androidHardwareAccelerationDisabled={true}
              ref={(ref) => (this.webView.ref = ref)}
              javaScriptEnabled={true}
              bounces={false}
              cacheEnabled={true}
              domStorageEnabled={true}
              allowFileAccess={true}
              source={{
                uri: this.url,
                headers: this.getHeaders(),
              }}
              onShouldStartLoadWithRequest={this.onShouldStartLoadWithRequest}
              onNavigationStateChange={this.onNavigationStateChange}
              automaticallyAdjustContentInsets={false}
              onMessage={this.onMessage}
              startInLoadingState={true}
              renderLoading={this.renderLoading}
              onError={this.onError}
              renderError={this.renderError}
              onLoadStart={this.onLoadStart}
              onLoadEnd={this.onLoadEnd}
            />
          </KeyboardAvoidingView>
        </SafeAreaView>

**Environment:**
 - OS: Samsung F41, Android
 - OS version: 10
 - react-native version: 0.60.5
 - react-native-webview version: 9.1.0

**Comment by HikaruKun** [comment]
same issue!
