### ISSUE TITLE
Webview pages error when Internet glitches. 

### ISSUE THREAD

**Issue by wflanagan** [react-native-webview/react-native-webview#1966]
Hello all,

This problem is something that’s been plaguing us for more than a year now. It's now bubbled up to the point of criticality with our customers. 

They're shocked at the poor quality of our application with significant webview components. And, it's all due to this bug. 

Let's describe the use case for review.

When a person is using any app built on this tech using WiFi, and they then switch to their phone’s Internet (everyone’s phone does this several times a day as they move from place to place), applications built on this tech “error.” Our customers see this, and complain about it. 

To be clear, it's not just on requests for new pages. It's also on a page that has already completed rendering. Let's say you've loaded a page that has an address on it. You leave the building to go hop in your car? Error. You walk from your car inside a location? Error. Any detection of a "blip" in internet immediately throws an error. 

This is NOT the same behavior as a web browser. Once the page is done rendering, if you leave it open, and you leave the building, the web browser doesn't immediately "error." It has all it needs to keep showing the page. 

The consequences of this are not good: 
- It creates a perception that the application is "unstable." 
- We get more error reports from end customers due to this issue. 
- We have to deal with unhappy customers, and an increased workload because of these errors. 
- The quality of our application is perceived to be lower.  People are less likely to renew their services with us. We make less money. 

What have you done to fix it? What about X?
- Yes, when the connection is re-established, the app will reload. But, again, the app shows an error, then corrects itself. This is NOT the behavior of a production app. 
- Yes, we’ve implemented custom logic that will show a nicer error than the one that shows by default. But it still shows this error. There's no way to "squash" it that we've found. 
- IOS/Android? Yes. Multiple including recently updated versions of this component? Yes. 

We are built on this tech. I never imagined that this bug would STILL be outstanding 1+ year later. Had we known this, we clearly would have gone a different route. 

Next, let's talk about bonuses to some simple caching capabilities in this component. 
- Having a stable "cache" would allow applications with webview components to feel faster, more stable, and well, higher quality. 
- Some applications could be implemented with simple layout changes to existing web  applications, making time to market faster and reducing the amount of code to maintain. 

Hopefully you can see how this issue makes the quality of applications built using this tech problematic. 

So, net, I'm asking for your help. 

We're more "web people" than "React component" people. It's hard for most of us to implement. And, yes, this is open source (which is thankless).  I know, as I maintain some core DB libraries. 

At a minimum, when you use this component, you expect it to behave similar to a web browser. It simply doesn't. Which is surprising for us, and I'm sure surprising for others. 

I could really use some guidance on this. Help? 

---- 
_Originally posted by @wflanagan as a comment (with updates and modifications) in an issue that references this that was closed because no one was whining about it: https://github.com/react-native-webview/react-native-webview/issues/1387#issuecomment-825878309_

**Comment by jamonholmgren** [comment]
(Also responded to your email to me, @wflanagan!)

Would you be able to provide a minimal app along with instructions on how to demonstrate this behavior? I spun up a minimal app and then disconnected and reconnected WiFi and wasn't able to reproduce the issue you're talking about. A minimal repro and steps to reproduce will be very helpful.

**Comment by wflanagan** [comment]
@jamonholmgren Thanks! I REALLY appreciate it. We'll build something minimal for you to test with. Give us 1 to 2 days.

**Comment by wflanagan** [comment]
@jamonholmgren We're working on this ourselves for now, as I think we have a handle on at least some of the problem. When I run to ground again I'll re-open.
