### ISSUE TITLE
Android Kotlin Gradle plugin compatibility with other libraries

### ISSUE THREAD

**Issue by cristianoccazinsp** [react-native-webview/react-native-webview#1968]
**Bug description:**

Hello,

When building for production, I'm getting the following warning/error:

```
The Kotlin Gradle plugin was loaded multiple times in different subprojects, which is not supported and may break the build. 
This might happen in subprojects that apply the Kotlin plugins with the Gradle 'plugins { ... }' DSL if they specify explicit versions, even if the versions are equal.
Please add the Kotlin plugin to the common parent project or the root project, then remove the versions in the subprojects.
If the parent project does not need the plugin, add 'apply false' to the plugin line.
See: https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl
The Kotlin plugin was loaded in the following projects: ':react-native-mlkit-ocr', ':react-native-webview'
```

I also have the following in build.gradle in order for both libraries to use the same version:

```
kotlinVersion="1.4.32"
```

Related library: https://github.com/agoldis/react-native-mlkit-ocr/issues/5

**Environment:**
 - OS: Android
 - OS version: Any
 - react-native version: 0.62.2
 - react-native-webview version: 11.4.0

**Comment by Piero87** [comment]
Hello,
I have the same problem with another library and react native webview:

`The Kotlin plugin was loaded in the following projects: ':react-native-ios-context-menu', ':react-native-webview'`

what is the problem? what we can do?

**Comment by KrisLau** [comment]
Same problem here
