### ISSUE TITLE
iOS: cache settings not being respected (changes not being reflected)

### ISSUE THREAD

**Issue by allthetime** [react-native-webview/react-native-webview#1975]
- react-native version: 0.63.25
 - react-native-webview version: 11.4.0

I have a webview with:
```
    <WebView
            source={{ uri: 'http://localhost:8080' }}     
            originWhitelist={['http://localhost']}
            cacheEnabled={false}
            cacheMode={"LOAD_NO_CACHE"}
    />
```

I am actively developing the website on localhost along side the app and making changes to a JS file.  They do not show up until I uninstall and reinstall my app.

The `clearCache` method only works on Android and is not available.

Is this intended behavior or is something wrong?

**Comment by wayne-tt** [comment]
Watch API docs. clearCache method is not support in ios.

**Comment by bfelbo** [comment]
> Watch API docs. clearCache method is not support in ios.

If that's the case, then shouldn't the docs be updated? Nothing in the docs related to `cacheEnabled` and `cacheMode` mention that it's not working on iOS.

**Comment by bfelbo** [comment]
@allthetime did you find a solution to this?

**Comment by bfelbo** [comment]
Found https://github.com/react-native-webview/react-native-webview/issues/1866#issuecomment-782562104. Adding `incognito={true}` works.
