### ISSUE TITLE
Google Pay button not working in Android devices

### ISSUE THREAD

**Issue by akhilsanker** [react-native-webview/react-native-webview#1976]
**Bug description:**

Using React Native Webview to pass a third party site which is using Stripe. They have Google Pay, however the Google Pay button does not appear using React Native Webview. If I take the third party website url and view it via Chrome on Android then Google Pay does appear. Is there something wrong with React Native Webview, or do I need to pass something from app to webview to make third party site work with Google pay appearing?

**Environment:**
 - OS: Android
 - OS version: Android 9
 - react-native version: 0.64
 - react-native-webview version: 11.2.3

**Comment by hussainimdad004** [comment]
Having same issue

**Comment by A-Tokyo** [comment]
Facing the same issue with https://github.com/A-Tokyo/react-native-stripe-checkout-webview

This trick https://github.com/A-Tokyo/react-native-stripe-checkout-webview#apple-pay-and-google-pay gets apple to work, but apparently google pay doesn't work

**Comment by A-Tokyo** [comment]
@hussainimdad004 Check this out for apple pay https://github.com/react-native-webview/react-native-webview/issues/920#issuecomment-810866297

**Comment by akhilsanker** [comment]
Hi,
Any updates?

Thanks

**Comment by A-Tokyo** [comment]
Still happening

**Comment by vargajacint** [comment]
Any update?

**Comment by JavoxirNazarov** [comment]
Having same issue

**Comment by master96** [comment]
is there any solution to get it working ? anyone tried this google pay in webview

**Comment by iconico** [comment]
I started a bounty in SO on this issue:
https://stackoverflow.com/questions/66003027/react-native-webview-stripe-google-pay

**Comment by BhavyaKoshiya** [comment]
> I started a bounty in SO on this issue: https://stackoverflow.com/questions/66003027/react-native-webview-stripe-google-pay

Did you manage to implement it?

**Comment by tux2nicolae** [comment]
Did anyone find a solution to this?
