### ISSUE TITLE
Can't open any url on android 5

### ISSUE THREAD

**Issue by aplinxy9plin** [react-native-webview/react-native-webview#1977]
**Bug description:**
Can't open any website on android 5
```
Encountered an error loading page, Object {
  "canGoBack": false,
  "canGoForward": false,
  "code": -1,
  "description": "net::ERR_CACHE_MISS",
  "loading": false,
  "target": 679,
  "title": "",
  "url": "https://google.com/",
}
at node_modules/react-native-webview/lib/WebView.android.js:167:12 in _this.onLoadingError
at [native code]:null in callFunctionReturnFlushedQueue
```
**Environment:**
 - OS: Android
 - OS version: 5
 - react-native version: ~0.63.4
 - react-native-webview version: ^11.3.2

**Comment by XPgan** [comment]
me too    
OS: Android vivox7 plus 
OS version: 5.1 
"react-native-webview": "^11.2.3",
react-native version: ~0.63.4



https://console.cloud.tencent.com/wetest/cloudphone/remote
以上链接可以帮助你调试真机



06-23 10:36:04.409 12342 12342 E AndroidRuntime: android.content.res.Resources$NotFoundException: String resource ID #0x2040003
06-23 10:36:04.409 12342 12342 E AndroidRuntime: 	at android.content.res.Resources.getText(Resources.java:318)
06-23 10:36:04.409 12342 12342 E AndroidRuntime: 	at android.content.res.VivoResources.getText(VivoResources.java:123)
06-23 10:36:04.409 12342 12342 E AndroidRuntime: 	at android.content.res.Resources.getString(Resources.java:404)
06-23 10:36:04.409 12342 12342 E AndroidRuntime: 	at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:694)
06-23 10:36:04.409 12342 12342 E AndroidRuntime: 	at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:618)
06-23 10:36:04.409 12342 12342 E AndroidRuntime: 	at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:631)
06-23 10:36:04.409 12342 12342 E AndroidRuntime: 	at com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:780)
06-23 10:36:04.409 12342 12342 E AndroidRuntime: 	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:619)
06-23 10:36:04.409 12342 12342 E AndroidRuntime: 	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:556)
06-23 10:36:04.409 12342 12342 E AndroidRuntime: 	at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:312)
06-23 10:36:04.409 12342 12342 E AndroidRuntime: 	at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:96)
06-23 10:36:04.409 12342 12342 E AndroidRuntime: 	at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:264)
06-23 10:36:04.409 12342 12342 E AndroidRuntime: 	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:123)
06-23 10:36:04.409 12342 12342 E AndroidRuntime: 	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:110)
06-23 10:36:04.409 12342 12342 E AndroidRuntime: 	at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
06-23 10:36:04.409 12342 12342 E AndroidRuntime: 	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:107)
06-23 10:36:04.409 12342 12342 E AndroidRuntime: 	at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:261)
06-23 10:36:04.409 12342 12342 E AndroidRuntime: 	at android.webkit.WebView.<init>(WebView.java:554)
06-23 10:36:04.409 12342 12342 E AndroidRuntime: 	at android.webkit.WebView.<init>(WebView.java:489)
06-23 10:36:04.409 12342 12342 E AndroidRuntime: 	at android.webkit.WebView.<init>(WebView.java:472)
06-23 10:36:04.409 12342 12342 E AndroidRuntime: 	at android.webkit.WebView.<init>(WebView.java:459)
06-23 10:36:04.409 12342 12342 E AndroidRuntime: 	at android.webkit.WebView.<init>(WebView.java:449)
06-23 10:36:04.409 12342 12342 E AndroidRuntime: 	at com.reactnativecommunity.webview.RNCWebViewManager$RNCWebView.<init>(RNCWebViewManager.java:1270)
06-23 10:36:04.409 12342 12342 E AndroidRuntime: 	at com.reactnativecommunity.webview.RNCWebViewManager.createRNCWebViewInstance(RNCWebViewManager.java:177)


这是我捕获到的日志反馈

**Comment by aplinxy9plin** [comment]
@XPgan Are u using expo? I solved it by eject project to react-native and got working apk. Expo does't working now.
