### ISSUE TITLE
Also support cacheMode on iOS

### ISSUE THREAD

**Issue by wayne-tt** [react-native-webview/react-native-webview#1979]
Thank you for making open source.

In Android, it was confirmed that the cached data was changed immediately following the http cache policy.

But there seems to be no logic followed by the http cache policy on iOS.

If you are okay, apply for iOS as well?

**Comment by wayne-tt** [comment]
Before this feature was added, I am going to use cacheEnabled props that are false.

**Comment by bfelbo** [comment]
See https://github.com/react-native-webview/react-native-webview/issues/1866#issuecomment-782562104. Adding `incognito={true}` works.
