### ISSUE TITLE
How to stop a video when the user scrolls past it or change screen

### ISSUE THREAD

**Issue by buffaloDeveloper** [react-native-webview/react-native-webview#1986]
Use case:  user is scrolling a page with a flatlist of videos.  They stop at a video they like and press play.  They get bored of watching the video and keep scrolling onward, but the video is still playing in the background because they didn't stop it.  How can I automatically stop the video from playing when the user scrolls past it?  
Thanks

```
function renderVideo(){
		if (Platform.OS === 'web'){
			return <WebView javaScriptEnabled={true} source={embedUri} style={{height: props.media.videoWebHeight}} />;
		}else{
			return <RNWebView source={embedUri} style={{height: props.media.videoMobileHeight}} />;
		}
	}
```

**Comment by FoolCoder** [comment]
i need to play and stop video on scroll in flatlist i cannot find anything to do
