### ISSUE TITLE
Android: Cannot read property  ‘importKey’ of undefined

### ISSUE THREAD

**Issue by christophby** [react-native-webview/react-native-webview#1987]
**Bug description:**
I'm getting **Cannot read property  ‘importKey’ of undefined** error only on Android, not on iOS.

**To Reproduce:**
Use `window.crypto.subtle.importKey` 

I'm using it inside my injected html-string
```
const htmlString = `<html>
  <script>
   // some function
   async function runCryptoStuff() {
     await window.crypto.subtle.importKey(...)
     // ...
   }
  </script>
  <body>...</body>
</html>`;

<WebView
  originWhitelist={['*']}
  source={{ html: htmlString }}
/>
```

**Expected behavior:**
* Runs without error on Android

According to the official SubtleCrypto [docs](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/importKey) it's only available in "_secure contexts_", which means _https_ or _localhost_. The html-string should be secure, shouldn't it?

**Environment:**
 - OS: Android
 - react-native version: 0.63.3
 - react-native-webview version: 11.4.4

**Comment by owencraston** [comment]
I am having the same issue now with version `11.13.0`. How did you resolve this?

**Comment by christophby** [comment]
@owencraston 
It's crazy. I used a [local web server](https://github.com/futurepress/react-native-static-server) to access the html code/file with a localhost url.
Not 100% sure but I think this did the trick.

**Comment by owencraston** [comment]
@christophby started patching by using react native webcrypto but I ended up getting better results just completely patching the module that was using these methods directly with patch-package.
