### ISSUE TITLE
granting RESOURCE_PROTECTED_MEDIA_ID

### ISSUE THREAD

**Issue by cstranex** [react-native-webview/react-native-webview#1990]
**Bug description:**
Trying to use EME results in an exception that no supported configurations are available. Investigation leads to PermissionRequest.RESOURCE_PROTECTED_MEDIA_ID not being granted. I can make a slight change to RNCWebViewManager.js:1142 for the permission to be granted:
```
      for (int i = 0; i < permissions.size(); i++) {
        if (permissions.get(i).equals(PermissionRequest.RESOURCE_PROTECTED_MEDIA_ID)) {
          grantedPermissions.add(PermissionRequest.RESOURCE_PROTECTED_MEDIA_ID);
        }
        if (ContextCompat.checkSelfPermission(mReactContext, permissions.get(i)) != PackageManager.PERMISSION_GRANTED) {
          continue;
        }
```

I am not sure how the permission checking is supposed to work but I can't see where else to grant the `RESOURCE_PROTECTED_MEDIA_ID` permission without moving the code as above.

**To Reproduce:**
- Install react-native-webview
- Create a page that makes use of EME
- See exception

**Expected behavior:**
EME should be initialized

**Environment:**
 - OS: Android
 - react-native version: 0.63.3
 - react-native-webview version: 11.4.4

**Comment by tijs** [comment]
I'm also having this issue. I can do a patch like @cstranex but there seems to be no, obvious, way to actually set the permissions for a webview?

**Comment by spector32** [comment]
Same here
