### ISSUE TITLE
Webview does not deeplink to open Custom URL Scheme on iOS

### ISSUE THREAD

**Issue by focalsolution** [react-native-webview/react-native-webview#1993]
**Bug description:**
On iOS, the following code does not redirect to open Custom URL Scheme.
However, if I change the Custom URL `MyApp://` to `https://`, it can open the link just fine.
```
<WebView
  source={{ html:
    `
    <html>
      <body>
        <script type='text/javascript'>
          window.location.href='MyApp://'
        </script>
      </body>
    </html>
    `
  }}
/>
```

**Expected behavior:**
WebView can open Custom URL (or open MyApp in other word)

**Environment:**
 - OS: iOS
 - OS version: 14.5.1
 - react-native version: 0.62.2
 - react-native-webview version: 11.2.3

**Comment by vipu-sa** [comment]
I am also having an issue loading HTML using webView in release apk. During development, it works fine. I am using seats.io to show the chart using webView in android and ios app.

https://github.com/matheuschagas/seatsio-react-native

I am using it like this...

```
 <View
        style={{ flex: 1, backgroundColor: 'yellow', alignSelf: 'stretch' }}>
        <WebView
          ref={(r) => (this.webRef = r)}
          originWhitelist={['*']}
          source={{ html: this.html() }}
        
          style={{ width: 320, height: 300, backgroundColor: 'lightblue' }}
          domStorageEnabled={true}
          javaScriptEnabled={true}
          injectedJavaScriptBeforeContentLoaded={this.pipeConsoleLog()}
          onMessage={this.handleMessage.bind(this)}
        />
      </View>
```
and html function is like this...

```
 html() {
    return `
            <html lang="en">
            
            <head>
            <title>seating chart</title>
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <script src="https://cdn-na.seatsio.net/chart.js"></script>
            </head>
            <body>
            <script>
            let promises = [];
            let promiseCounter = 0;
            
            const resolvePromise = (promiseId, data) => {
                promises[promiseId](data)
            }
                </script>
                <div id="chart"></div>
                <script>
                let chart = new seatsio.SeatingChart(${this.configAsString()}).render();
                </script>
               
            </body>
            </html>
        `;
  }
```

Need help on this. Thanks in advance.

**Comment by focalsolution** [comment]
I later fond out that we need to specify the Custom URL in Info.plist for the key **LSApplicationQueriesSchemes** in order to make this work on iOS. 

Just want to share here in case it might be useful for others.

**Comment by ddl-elo** [comment]
hi @focalsolution 

I happen to stumble upon same issue,

this is my custom URL (a deeplink):
`myapp://open-browser/https://mydaily.dev/JOURNAL/home?id=123e4567-e89b-12d3-a456-426655440000&source=01&channel_id=HOME`

I'm trying to redirect from webview by using deeplink custom URL but it seems not redirecting it.
I already made sure the web returns the deeplink custom URL and I tried on Safari it works ok.

my expected behavior is
when I'm on iOS WebView and click this _button_ inside the webview, it will redirect/open Custom URL (or open myapp in other word).

I tried to specify the Custom URL including the `myapp://open-browser/` in Info.plist for the key **LSApplicationQueriesSchemes** like you said, but the webview still not redirecting it.

Any ideas you might share? please

**Comment by sixty-four-bit** [comment]
Having same issue. Anyone has an update on this.

**Comment by focalsolution** [comment]
@ddl-elo 

Can you try with `myapp` (no ://) in the array of `LSApplicationQueriesSchemes` ?

**Comment by sixty-four-bit** [comment]
@focalsolution  tried following doesn't work.

if i put this link on safari it works.
org.reactjs.native.example.myapp://about/
But from webview its returns NSURLErrorDomain 1002.

my actual intention is 
-when the auth from azure b2c is successful it redirects to 
msauth.org.reactjs.native.example.myapp://auth 
I want to handel it in a react native component



My current info.plist has this 
```
<key>LSApplicationQueriesSchemes</key>
		<array>
			
			<string>msauth.org.reactjs.native.example.myapp</string>
			<string>org.reactjs.native.example.myapp</string>
		</array>

<dict>
				<key>CFBundleURLSchemes</key>
				<array>
					<string>org.reactjs.native.example.myapp</string>
<string>msauth.org.reactjs.native.example.myapp</string>
				</array>
			</dict>
```

**Comment by yorickshan** [comment]
> I later find out that we need to specify the Custom URL in Info.plist for the key **LSApplicationQueriesSchemes** in order to make this works on iOS.
> 
> Just want to share here in case it might be useful for others.

thx

**Comment by fabriciosautner** [comment]
same problem

My info.plist:
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>LSApplicationQueriesSchemes</key>
  <array>
      <string>com.xxxxxxx://garmin/success</string>
  </array>
</dict>
</plist>`

**Comment by fabriciosautner** [comment]
same problem

My info.plist:
```
      <plist version="1.0">
         <dict>
             .....
             <key>LSApplicationQueriesSchemes</key>
             <array>
                  <string>com.xxxxxxx://garmin/success</string>
             </array>
            .......
         </dict>
      </plist>
```

**Comment by raosan** [comment]
If anyone still have the issue and stuck here, i just make it works by setting the `originWhitelist` as explained here [here](https://stackoverflow.com/questions/64169029/how-to-open-intent-link-in-browser-from-webview-on-react-native)

```
originWhitelist={['https://*', 'myapp://*']}
```
