### ISSUE TITLE
Android error: RNCWebViewManager is not abstract and does not override abstract method createViewInstance

### ISSUE THREAD

**Issue by Luckygirlllll** [react-native-webview/react-native-webview#1995]
**Bug description:**

Android error: RNCWebViewManager is not abstract and does not override abstract method createViewInstance

**To Reproduce:**

Install latest version of react-native-webview

**Expected behavior:**

I can run Android app.

**Screenshots/Videos:**

<img width="610" alt="Screenshot 2021-05-20 at 11 04 10" src="https://user-images.githubusercontent.com/10096433/118951836-b5e86180-b95b-11eb-8674-4b5ce822ea2e.png">
<img width="791" alt="Screenshot 2021-05-20 at 11 04 21" src="https://user-images.githubusercontent.com/10096433/118951871-bda80600-b95b-11eb-8c9b-3e22bc19dec4.png">

**Environment:**
 - OS: Android
 - OS version: all
 - react-native version: 0.63.4
 - react-native-webview version: 11.4.6

**Comment by Hanv2itedu** [comment]
Same issue.

**Comment by ferasabufares** [comment]
Same her any fix???????????

**Comment by gcandal** [comment]
> Same her any fix???????????

Use 11.4.5 or wait for it to get fixed.

**Comment by ferasabufares** [comment]
defaultConfig {
multiDexEnabled true //Add this line
}

add this fix the problem

**Comment by azuken** [comment]
Rollback to 11.4.4 or 11.4.5 does not fix the problem. I cannot build my app anymore. I've clean gradle and node_modules files, same.

**Comment by azuken** [comment]
Quick fix : 

In `RNCWebViewManager.java` replace all `ReactContext` type occurences in **overrieded methods** (`addEventEmitters` and `createViewInstance`) by `ThemedReactContext`.

**Comment by abdbodara** [comment]
Nothing happened

**Comment by gcandal** [comment]
> Rollback to 11.4.4 or 11.4.5 does not fix the problem. I cannot build my app anymore. I've clean gradle and node_modules files, same.

I doubt it doesn't. The error was introduced here:
- https://github.com/react-native-webview/react-native-webview/releases/tag/v11.4.6
- https://github.com/react-native-webview/react-native-webview/pull/1994/files

... which is exactly the same fix you suggest.

**Comment by abdbodara** [comment]
I'm using version 11.4.2 and still showing the error, I highly doubt it's the version problem

**Comment by Luckygirlllll** [comment]
I can't build app anymore as well, even if rollback to lower versions of react-native-webview.

**Comment by ngocvu576** [comment]
same issue

**Comment by se09deluca** [comment]
> > Same her any fix???????????
> 
> Use 11.4.5 or wait for it to get fixed.

For the moment using versions 11.4.4 or 11.4.5 resolves the issue in my project 👌🏻 

Hope it will fixed soon also in latest package's version

**Comment by wouterds** [comment]
Can confirm that downgrading to `11.4.5` does resolve the issue.

For those saying it doesn't work, make sure you actually **pin** to that version like this

```
...
"react-native-webview": "11.4.5",
...
```


This won't work

```
...
"react-native-webview": "^11.4.5",
...
```

**Comment by franciscofernandez0** [comment]
> 
> 
> Can confirm that downgrading to `11.4.5` does resolve the issue.
> 
> For those saying it doesn't work, make sure you actually **pin** to that version like this
> 
> ```
> ...
> "react-native-webview": "11.4.5",
> ...
> ```
> 
> This won't work
> 
> ```
> ...
> "react-native-webview": "^11.4.5",
> ...
> ```

This was my problem.

**Comment by vuletuanbt** [comment]
> Can confirm that downgrading to `11.4.5` does resolve the issue.
> 
> For those saying it doesn't work, make sure you actually **pin** to that version like this
> 
> ```
> ...
> "react-native-webview": "11.4.5",
> ...
> ```
> 
> This won't work
> 
> ```
> ...
> "react-native-webview": "^11.4.5",
> ...
> ```

I confirm that it works

**Comment by razatekarra** [comment]
> > Can confirm that downgrading to `11.4.5` does resolve the issue.
> > For those saying it doesn't work, make sure you actually **pin** to that version like this
> > ```
> > ...
> > "react-native-webview": "11.4.5",
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This won't work
> > ```
> > ...
> > "react-native-webview": "^11.4.5",
> > ...
> > ```
> 
> I confirm that it works

thank's it work!

**Comment by apoorv-1310** [comment]
"react-native-webview": "^11.4.5", worked for me

**Comment by Titozzz** [comment]
fixed... sorry 😓

**Comment by azuken** [comment]
New error with version `11.6.1`:

```
node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java:1214: error: method onPermissionRequest(PermissionRequest) is already defined in class RNCWebChromeClient
    public void onPermissionRequest(final PermissionRequest request) {
```

**Comment by Titozzz** [comment]
Fix released 😐
