### ISSUE TITLE
Error: method does not override or implement a method from a supertype

### ISSUE THREAD

**Issue by tapz** [react-native-webview/react-native-webview#1998]
**Bug description:**
```
node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java:172: 
error: method does not override or implement a method from a supertype
  @Override
```

**To Reproduce:**
Just update and try to compile

**Expected behavior:**
No errors

**Screenshots/Videos:**

**Environment:**
 - OS: MacOS
 - OS version: 11.3.1
 - react-native version: 0.64.1
 - react-native-webview version: 11.4.6

**Comment by christopherklint97** [comment]
#1995 is a related error. Have you tried the tips in the discussion?

**Comment by Titozzz** [comment]
Fixed, sorry 😓

**Comment by Pawanagdev** [comment]
Hello, 

I followed the above-mentioned solution and downgraded it to 11.4.5. Now, I get a new error:
"react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java:277: error: cannot find symbol
view.getSettings().setAppCachePath(ctx.getCacheDir().getAbsolutePath());"

I got an answer for the above error in the resolved issues section saying to upgrade the module to 11.22.7 that in turn throws the previous error:
"error: method does not override or implement a method from a supertype
  @Override"

Seems like its a catch22 situation. Please help

Environment:

OS: MacOS
OS version: 12.5
react-native version: 0.60.0
react-native-webview version: 11.4.5 or 11.22.7
