### ISSUE TITLE
Task :react-native-webview:compileDebugJavaWithJavac FAILED 

### ISSUE THREAD

**Issue by Lekhrajk** [react-native-webview/react-native-webview#2000]
**Bug description:**

I have tried this solution 
buildscript {
    ext {
        …
        buildToolsVersion = "29.0.3"
        compileSdkVersion = 29
        …
    }
…
}
but it is not solving problem i am getting this error again and again

**Environment:**
 - OS: Android
 - OS version: Android 10.0 (Pixel 3 API 29 Simulator)
 - react-native version: 0.63.4
 - react-native-webview version:11.4.6

**Comment by vauruk** [comment]
i have a the same problem

**Comment by pedroksty** [comment]
same problem

**Comment by KaueCesar** [comment]
here too

**Comment by natimks** [comment]
Using version 11.4.5 solved this situation in my project....

**Comment by Titozzz** [comment]
Hello I reverted the PR that broke everything
Sorry again and have a great day :)
You can use the latest now

**Comment by Lekhrajk** [comment]
i am still getting that error also it is showing this
node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\RNCWebViewManager.java:1214: error: method onPermissionRequest(PermissionRequest) is already defined in class RNCWebChromeClient

**Comment by Lekhrajk** [comment]
> Using version 11.4.5 solved this situation in my project....
> "react-native-webview": "11.4.5"

This worked for me
