### ISSUE TITLE
How can i debug on windows?

### ISSUE THREAD

**Issue by markrookie** [react-native-webview/react-native-webview#2003]
I render a webview to display my website on windows desktop application, but i encounter some bugs, are there any options to debug?

**Comment by asklar** [comment]
It depends on what part you're looking to debug. For the native side, you'd debug using Visual Studio. For the JS side, you'd debug using web debugging / direct debugging.

**Comment by markrookie** [comment]
Thanks asklar, i was trying to debug on the JS side, i am going to try web debugging / direct debugging

**Comment by markrookie** [comment]
I can debug webview content after install Microsoft Edge DevTools Preview
