### ISSUE TITLE
getUserMedia() hangs if source = { html }

### ISSUE THREAD

**Issue by nightness** [react-native-webview/react-native-webview#2004]
**Bug description:**
I've been trying to build out an example of how to use WebRTC using WebView's so it's Expo Go compatible, using a static html file for the WebView; trying both 'html' and 'uri' sources... iOS version works if source is a URI but I wasn't able to get Android URI's working... Neither iOS or Android work when using 'html' in the source prop; getUserMedia() hangs if source = { html }. But oddly react-native-web-webview doesn't have permission if NOT using 'html'.

**To Reproduce:**
Check out my example on GitHub... It works for iOS, but WebView permissions (for Camera and Audio) on Android is denied. I assume the problem because no user interaction is initiated to enable permission. With Android using URI's the permission check doesn't show and times out... but on Android and iOS with html source, it doesn't show and also doesn't seem to timeout.
https://github.com/nightness/expo-webrtc-example

**Environment:**
- Expo Go and React Native Web
- Expo 41

**Comment by nightness** [comment]
I suspect the problem is because the Android WebView and URI's is because there is no interaction with the user to ask permission, so the permission request times out with a permission denied.

**Comment by abcdefghiraj** [comment]
WebRTC requires communication over a secure channel. Html source definitely won't work. Serving the page via https should work for android. It doesn't work for me on iOs with the latest iOs version though.

**Comment by Flam3rboy** [comment]
@nightness you could bypass it by loading any https site and then overriding the innerHTML of the body with your desired content
