### ISSUE TITLE
Task :react-native-webview:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by Enragedsaturday** [react-native-webview/react-native-webview#2005]
**Bug description:**
Upon building I fail with the following error message:

The Kotlin Gradle plugin was loaded multiple times in different subprojects, which is not supported and may break the build. 
This might happen in subprojects that apply the Kotlin plugins with the Gradle 'plugins { ... }' DSL if they specify explicit versions, even if the versions are equal.
Please add the Kotlin plugin to the common parent project or the root project, then remove the versions in the subprojects.
If the parent project does not need the plugin, add 'apply false' to the plugin line.
See: https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl
The Kotlin plugin was loaded in the following projects: ':react-native-store-review', ':react-native-webview'

> Task :react-native-webview:compileDebugJavaWithJavac FAILED

I am on rn 0.63 
buildToolsVersion = "29.0.2"
  minSdkVersion = 21
  compileSdkVersion = 29
  targetSdkVersion = 29

**To Reproduce:**
If needed I can make a repository but my code is proprietary so... I'd imagine any project with RN Webview and react-native-store-review may have the same issue.

**Expected behavior:**
Successful build

**Environment:**
 - OS: Mac OS
 - OS version: Big Sur 11.3.1
 - react-native version: .63
 - react-native-webview version: 11.6.1
build.gradle for webview:
`buildscript {
  ext.getExtOrDefault = {name ->
    return rootProject.ext.has(name) ? rootProject.ext.get(name) : project.properties['ReactNativeWebView_' + name]
  }

  // The Android Gradle plugin is only required when opening the android folder stand-alone.
  // This avoids unnecessary downloads and potential conflicts when the library is included as a
  // module dependency in an application project.
  if (project == rootProject) {
    repositories {
      mavenCentral()
      google()
      jcenter()
    }

    dependencies {
      classpath("com.android.tools.build:gradle:3.6.0")
      classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:${getExtOrDefault('kotlinVersion')}")
    }
  } else {
    repositories {
      mavenCentral()
      jcenter()
    }

    dependencies {
      classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:${getExtOrDefault('kotlinVersion')}")
    }
  }
}

def getExtOrIntegerDefault(name) {
  return rootProject.ext.has(name) ? rootProject.ext.get(name) : (project.properties['ReactNativeWebView_' + name]).toInteger()
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
  compileSdkVersion getExtOrIntegerDefault('compileSdkVersion')
  buildToolsVersion getExtOrDefault('buildToolsVersion')
  defaultConfig {
    minSdkVersion getExtOrIntegerDefault('minSdkVersion')
    targetSdkVersion getExtOrIntegerDefault('targetSdkVersion')
    versionCode 1
    versionName "1.0"
  }
  buildTypes {
    release {
      minifyEnabled false
    }
  }
  lintOptions {
    disable 'GradleCompatible'
  }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
}

repositories {
  mavenCentral()
  jcenter()
  google()

  def found = false
  def defaultDir = null
  def androidSourcesName = 'React Native sources'

  if (rootProject.ext.has('reactNativeAndroidRoot')) {
    defaultDir = rootProject.ext.get('reactNativeAndroidRoot')
  } else {
    defaultDir = new File(
      projectDir,
      '/../../../node_modules/react-native/android'
    )
  }

  if (defaultDir.exists()) {
    maven {
      url defaultDir.toString()
      name androidSourcesName
    }

    logger.info(":${project.name}:reactNativeAndroidRoot ${defaultDir.canonicalPath}")
    found = true
  } else {
    def parentDir = rootProject.projectDir

    1.upto(5, {
      if (found) return true
      parentDir = parentDir.parentFile

      def androidSourcesDir = new File(
        parentDir,
        'node_modules/react-native'
      )

      def androidPrebuiltBinaryDir = new File(
        parentDir,
        'node_modules/react-native/android'
      )

      if (androidPrebuiltBinaryDir.exists()) {
        maven {
          url androidPrebuiltBinaryDir.toString()
          name androidSourcesName
        }

        logger.info(":${project.name}:reactNativeAndroidRoot ${androidPrebuiltBinaryDir.canonicalPath}")
        found = true
      } else if (androidSourcesDir.exists()) {
        maven {
          url androidSourcesDir.toString()
          name androidSourcesName
        }

        logger.info(":${project.name}:reactNativeAndroidRoot ${androidSourcesDir.canonicalPath}")
        found = true
      }
    })
  }

  if (!found) {
    throw new GradleException(
      "${project.name}: unable to locate React Native android sources. " +
        "Ensure you have you installed React Native as a dependency in your project and try again."
    )
  }
}

def kotlin_version = getExtOrDefault('kotlinVersion')

dependencies {
  //noinspection GradleDynamicVersion
  implementation 'com.facebook.react:react-native:+'
  implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
}
`
build.gradle for react-native-storeview 
`buildscript {
  // Buildscript is evaluated before everything else so we can't use getExtOrDefault
  def kotlin_version = rootProject.ext.has('kotlinVersion') ? rootProject.ext.get('kotlinVersion') : project.properties['RNStoreReview_kotlinVersion']

  repositories {
    google()
    jcenter()
  }

  dependencies {
    classpath 'com.android.tools.build:gradle:3.2.1'
    // noinspection DifferentKotlinGradleVersion
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
  }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

def getExtOrDefault(name) {
  return rootProject.ext.has(name) ? rootProject.ext.get(name) : project.properties['RNStoreReview_' + name]
}

def getExtOrIntegerDefault(name) {
  return rootProject.ext.has(name) ? rootProject.ext.get(name) : (project.properties['RNStoreReview_' + name]).toInteger()
}

android {
  compileSdkVersion getExtOrIntegerDefault('compileSdkVersion')
  buildToolsVersion getExtOrDefault('buildToolsVersion')
  defaultConfig {
    minSdkVersion getExtOrIntegerDefault('minSdkVersion')
    targetSdkVersion getExtOrIntegerDefault('targetSdkVersion')
    versionCode 1
    versionName "1.0"

  }

  buildTypes {
    release {
      minifyEnabled false
    }
  }
  lintOptions {
    disable 'GradleCompatible'
  }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
}

repositories {
  mavenCentral()
  jcenter()
  google()

  def found = false
  def defaultDir = null
  def androidSourcesName = 'React Native sources'

  if (rootProject.ext.has('reactNativeAndroidRoot')) {
    defaultDir = rootProject.ext.get('reactNativeAndroidRoot')
  } else {
    defaultDir = new File(
            projectDir,
            '/../../../node_modules/react-native/android'
    )
  }

  if (defaultDir.exists()) {
    maven {
      url defaultDir.toString()
      name androidSourcesName
    }

    logger.info(":${project.name}:reactNativeAndroidRoot ${defaultDir.canonicalPath}")
    found = true
  } else {
    def parentDir = rootProject.projectDir

    1.upto(5, {
      if (found) return true
      parentDir = parentDir.parentFile

      def androidSourcesDir = new File(
              parentDir,
              'node_modules/react-native'
      )

      def androidPrebuiltBinaryDir = new File(
              parentDir,
              'node_modules/react-native/android'
      )

      if (androidPrebuiltBinaryDir.exists()) {
        maven {
          url androidPrebuiltBinaryDir.toString()
          name androidSourcesName
        }

        logger.info(":${project.name}:reactNativeAndroidRoot ${androidPrebuiltBinaryDir.canonicalPath}")
        found = true
      } else if (androidSourcesDir.exists()) {
        maven {
          url androidSourcesDir.toString()
          name androidSourcesName
        }

        logger.info(":${project.name}:reactNativeAndroidRoot ${androidSourcesDir.canonicalPath}")
        found = true
      }
    })
  }

  if (!found) {
    throw new GradleException(
            "${project.name}: unable to locate React Native android sources. " +
                    "Ensure you have you installed React Native as a dependency in your project and try again."
    )
  }
}

def kotlin_version = getExtOrDefault('kotlinVersion')

dependencies {
  // noinspection GradleDynamicVersion
  api 'com.facebook.react:react-native:+'
  implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
  implementation 'com.google.android.play:core:1.8.0'
  implementation 'com.google.android.play:core-ktx:1.8.1'

}
`

I know that I have to make some changes in here and have attempted but really have no clue what I'm doing. Help would be appreciated.

**Comment by Dverybest** [comment]
I'm having the same issue
> Task :react-native-webview:compileDebugJavaWithJavac FAILED

**Comment by atulfind** [comment]
I'm also getting same issue.

**Comment by Darkiring** [comment]
Same issue

Install an older version and it worked fine.
In this way they can do it:

`npm i react-native-webview@11.4.3`

You can replace 11.4.3 with any previous version: [(https://github.com/react-native-webview/react-native-webview/releases)]

**Comment by NguyenPhatBG** [comment]
@DaniAkash @atulfind It's also work for me 👯

**Comment by daogurtsov** [comment]
> **Bug description:**
> Upon building I fail with the following error message:
> 
> The Kotlin Gradle plugin was loaded multiple times in different subprojects, which is not supported and may break the build.
> This might happen in subprojects that apply the Kotlin plugins with the Gradle 'plugins { ... }' DSL if they specify explicit versions, even if the versions are equal.
> Please add the Kotlin plugin to the common parent project or the root project, then remove the versions in the subprojects.
> If the parent project does not need the plugin, add 'apply false' to the plugin line.
> See: https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl
> The Kotlin plugin was loaded in the following projects: ':react-native-store-review', ':react-native-webview'
> 
> > Task :react-native-webview:compileDebugJavaWithJavac FAILED
> 
> I am on rn 0.63
> buildToolsVersion = "29.0.2"
> minSdkVersion = 21
> compileSdkVersion = 29
> targetSdkVersion = 29
> 
> **To Reproduce:**
> If needed I can make a repository but my code is proprietary so... I'd imagine any project with RN Webview and react-native-store-review may have the same issue.
> 
> **Expected behavior:**
> Successful build
> 
> **Environment:**
> 
> * OS: Mac OS
> * OS version: Big Sur 11.3.1
> * react-native version: .63
> * react-native-webview version: 11.6.1
>   build.gradle for webview:
>   `buildscript {
>   ext.getExtOrDefault = {name ->
>   return rootProject.ext.has(name) ? rootProject.ext.get(name) : project.properties['ReactNativeWebView_' + name]
>   }
> 
> // The Android Gradle plugin is only required when opening the android folder stand-alone.
> // This avoids unnecessary downloads and potential conflicts when the library is included as a
> // module dependency in an application project.
> if (project == rootProject) {
> repositories {
> mavenCentral()
> google()
> jcenter()
> }
> 
> ```
> dependencies {
>   classpath("com.android.tools.build:gradle:3.6.0")
>   classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:${getExtOrDefault('kotlinVersion')}")
> }
> ```
> 
> } else {
> repositories {
> mavenCentral()
> jcenter()
> }
> 
> ```
> dependencies {
>   classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:${getExtOrDefault('kotlinVersion')}")
> }
> ```
> 
> }
> }
> 
> def getExtOrIntegerDefault(name) {
> return rootProject.ext.has(name) ? rootProject.ext.get(name) : (project.properties['ReactNativeWebView_' + name]).toInteger()
> }
> 
> apply plugin: 'com.android.library'
> apply plugin: 'kotlin-android'
> 
> android {
> compileSdkVersion getExtOrIntegerDefault('compileSdkVersion')
> buildToolsVersion getExtOrDefault('buildToolsVersion')
> defaultConfig {
> minSdkVersion getExtOrIntegerDefault('minSdkVersion')
> targetSdkVersion getExtOrIntegerDefault('targetSdkVersion')
> versionCode 1
> versionName "1.0"
> }
> buildTypes {
> release {
> minifyEnabled false
> }
> }
> lintOptions {
> disable 'GradleCompatible'
> }
> compileOptions {
> sourceCompatibility JavaVersion.VERSION_1_8
> targetCompatibility JavaVersion.VERSION_1_8
> }
> }
> 
> repositories {
> mavenCentral()
> jcenter()
> google()
> 
> def found = false
> def defaultDir = null
> def androidSourcesName = 'React Native sources'
> 
> if (rootProject.ext.has('reactNativeAndroidRoot')) {
> defaultDir = rootProject.ext.get('reactNativeAndroidRoot')
> } else {
> defaultDir = new File(
> projectDir,
> '/../../../node_modules/react-native/android'
> )
> }
> 
> if (defaultDir.exists()) {
> maven {
> url defaultDir.toString()
> name androidSourcesName
> }
> 
> ```
> logger.info(":${project.name}:reactNativeAndroidRoot ${defaultDir.canonicalPath}")
> found = true
> ```
> 
> } else {
> def parentDir = rootProject.projectDir
> 
> ```
> 1.upto(5, {
>   if (found) return true
>   parentDir = parentDir.parentFile
> 
>   def androidSourcesDir = new File(
>     parentDir,
>     'node_modules/react-native'
>   )
> 
>   def androidPrebuiltBinaryDir = new File(
>     parentDir,
>     'node_modules/react-native/android'
>   )
> 
>   if (androidPrebuiltBinaryDir.exists()) {
>     maven {
>       url androidPrebuiltBinaryDir.toString()
>       name androidSourcesName
>     }
> 
>     logger.info(":${project.name}:reactNativeAndroidRoot ${androidPrebuiltBinaryDir.canonicalPath}")
>     found = true
>   } else if (androidSourcesDir.exists()) {
>     maven {
>       url androidSourcesDir.toString()
>       name androidSourcesName
>     }
> 
>     logger.info(":${project.name}:reactNativeAndroidRoot ${androidSourcesDir.canonicalPath}")
>     found = true
>   }
> })
> ```
> 
> }
> 
> if (!found) {
> throw new GradleException(
> "${project.name}: unable to locate React Native android sources. " +
> "Ensure you have you installed React Native as a dependency in your project and try again."
> )
> }
> }
> 
> def kotlin_version = getExtOrDefault('kotlinVersion')
> 
> dependencies {
> //noinspection GradleDynamicVersion
> implementation 'com.facebook.react:react-native:+'
> implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
> }
> `build.gradle for react-native-storeview `buildscript {
> // Buildscript is evaluated before everything else so we can't use getExtOrDefault
> def kotlin_version = rootProject.ext.has('kotlinVersion') ? rootProject.ext.get('kotlinVersion') : project.properties['RNStoreReview_kotlinVersion']
> 
> repositories {
> google()
> jcenter()
> }
> 
> dependencies {
> classpath 'com.android.tools.build:gradle:3.2.1'
> // noinspection DifferentKotlinGradleVersion
> classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
> }
> }
> 
> apply plugin: 'com.android.library'
> apply plugin: 'kotlin-android'
> 
> def getExtOrDefault(name) {
> return rootProject.ext.has(name) ? rootProject.ext.get(name) : project.properties['RNStoreReview_' + name]
> }
> 
> def getExtOrIntegerDefault(name) {
> return rootProject.ext.has(name) ? rootProject.ext.get(name) : (project.properties['RNStoreReview_' + name]).toInteger()
> }
> 
> android {
> compileSdkVersion getExtOrIntegerDefault('compileSdkVersion')
> buildToolsVersion getExtOrDefault('buildToolsVersion')
> defaultConfig {
> minSdkVersion getExtOrIntegerDefault('minSdkVersion')
> targetSdkVersion getExtOrIntegerDefault('targetSdkVersion')
> versionCode 1
> versionName "1.0"
> 
> }
> 
> buildTypes {
> release {
> minifyEnabled false
> }
> }
> lintOptions {
> disable 'GradleCompatible'
> }
> compileOptions {
> sourceCompatibility JavaVersion.VERSION_1_8
> targetCompatibility JavaVersion.VERSION_1_8
> }
> }
> 
> repositories {
> mavenCentral()
> jcenter()
> google()
> 
> def found = false
> def defaultDir = null
> def androidSourcesName = 'React Native sources'
> 
> if (rootProject.ext.has('reactNativeAndroidRoot')) {
> defaultDir = rootProject.ext.get('reactNativeAndroidRoot')
> } else {
> defaultDir = new File(
> projectDir,
> '/../../../node_modules/react-native/android'
> )
> }
> 
> if (defaultDir.exists()) {
> maven {
> url defaultDir.toString()
> name androidSourcesName
> }
> 
> ```
> logger.info(":${project.name}:reactNativeAndroidRoot ${defaultDir.canonicalPath}")
> found = true
> ```
> 
> } else {
> def parentDir = rootProject.projectDir
> 
> ```
> 1.upto(5, {
>   if (found) return true
>   parentDir = parentDir.parentFile
> 
>   def androidSourcesDir = new File(
>           parentDir,
>           'node_modules/react-native'
>   )
> 
>   def androidPrebuiltBinaryDir = new File(
>           parentDir,
>           'node_modules/react-native/android'
>   )
> 
>   if (androidPrebuiltBinaryDir.exists()) {
>     maven {
>       url androidPrebuiltBinaryDir.toString()
>       name androidSourcesName
>     }
> 
>     logger.info(":${project.name}:reactNativeAndroidRoot ${androidPrebuiltBinaryDir.canonicalPath}")
>     found = true
>   } else if (androidSourcesDir.exists()) {
>     maven {
>       url androidSourcesDir.toString()
>       name androidSourcesName
>     }
> 
>     logger.info(":${project.name}:reactNativeAndroidRoot ${androidSourcesDir.canonicalPath}")
>     found = true
>   }
> })
> ```
> 
> }
> 
> if (!found) {
> throw new GradleException(
> "${project.name}: unable to locate React Native android sources. " +
> "Ensure you have you installed React Native as a dependency in your project and try again."
> )
> }
> }
> 
> def kotlin_version = getExtOrDefault('kotlinVersion')
> 
> dependencies {
> // noinspection GradleDynamicVersion
> api 'com.facebook.react:react-native:+'
> implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
> implementation 'com.google.android.play:core:1.8.0'
> implementation 'com.google.android.play:core-ktx:1.8.1'
> 
> }
> `
> 
> I know that I have to make some changes in here and have attempted but really have no clue what I'm doing. Help would be appreciated.

For me downgrade to 11.4.5 worked fine

**Comment by Titozzz** [comment]
Just released a new version
