### ISSUE TITLE
method onPermissionRequest(PermissionRequest) is already defined in class RNCWebChromeClient

### ISSUE THREAD

**Issue by SaravananSubramanian** [react-native-webview/react-native-webview#2010]
Just start seeing this starting a few days ago:

node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java:1214: error: method onPermissionRequest(PermissionRequest) is already defined in class RNCWebChromeClient
    public void onPermissionRequest(final PermissionRequest request) {

**To Reproduce:**
Install react-native-webview on new RN project

There does appear to be two methods with the same method signature in the source code of this plugin:

https://github.com/react-native-webview/react-native-webview/blob/master/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java

**Expected behavior:**
Should build correctly

**Environment:**
 - OS: MacOS
 - OS version: 10:!5.7
 - react-native version: 0.64
 - react-native-webview version: ^11.6.1

**Comment by SaravananSubramanian** [comment]
Notice that there is a PR waiting for this

**Comment by cross19xx** [comment]
Shouldn't we wait until the PR is merged before closing this issue?

**Comment by SaravananSubramanian** [comment]
Thanks. Yeah, I thought about it. I think the PR that is open attempts to address #1239 and #2001 which should address my issue as well (I think mine would then be considered duplicate).
