### ISSUE TITLE
Can't make a signed build

### ISSUE THREAD

**Issue by bhardwajMehul** [react-native-webview/react-native-webview#2011]
Throws the error while making a signed build in android studio =>
error: method onPermissionRequest(PermissionRequest) is already defined in class RNCWebChromeClient

**Environment:**
 - OS:MacOS
 - OS version:10.15.7
 - react-native version:0.63.4
 - react-native-webview version:11.6.1

**Comment by aleppos** [comment]
Same issue.

**Comment by makenova** [comment]
I also have the same issue.
Looks like the duplicate was introduced to `RNCWebViewManager.java` in `v11.5.0`.

I thought `v11.4.7` would work without issue since it does not have the duplicate but I get a different build failure on that version.

**Comment by bhardwajMehul** [comment]
@aleppos @makenova I downgraded to version 11.3.2, it works fine for me.

**Comment by Titozzz** [comment]
Fixed in 11.6.2
