### ISSUE TITLE
file downloads as file.bin

### ISSUE THREAD

**Issue by smahdink** [react-native-webview/react-native-webview#2012]
When I try to download a file through the webview the file gets downloaded as file.bin despite being a pdf file. the content is correct though and renaming the file makes it usable.
any solutions?
thanks

**Comment by smahdink** [comment]
more info:
expo sdk:41
built with: expo build:android
only react-native-webview library was used

here is the app.js code:
```
import { StatusBar } from 'expo-status-bar';
import * as React from 'react';
import { WebView } from 'react-native-webview';

export default class App extends React.Component {
  render() {
    return <WebView source={{ uri: 'https://jozvedar.pythonanywhere.com' }} style={{ marginTop: 20 }} />;
  }
}

```

**Comment by ahsanparacha02** [comment]
> When I try to download a file through the webview the file gets downloaded as file.bin despite being a pdf file. the content is correct though and renaming the file makes it usable.
> any solutions?
> thanks

same issue i m facing, did u get any solution ?

**Comment by smahdink** [comment]
@ahsanparacha02  No unfortunately, I switched to externally handling links.

**Comment by obie3** [comment]
Hi @smahdink  how did you handle it externally?

**Comment by cybercris** [comment]
Any updates?

**Comment by smahdink** [comment]
@cybercris  Sorry haven't checked it recently.

**Comment by obie3** [comment]
ok I was able solve mine, the issue in my was wrong server config, the header config for the server handling had content-type set to 
application/octet-stream instead of application/pdf.
follow this link for mime types 
https://www.sitepoint.com/mime-types-complete-list/?utm_source=pocket_mylist

**Comment by cybercris** [comment]
> I was able to solve mine, the issue in my case was the wrong server config, the header config for the server handling had content-type set to application/octet-stream instead of application/pdf.
> follow this link for mime types
> https://www.sitepoint.com/mime-types-complete-list

Indeed my application is sending application/octet-stream in headers, but the problem is not only in PDF's files... .xls, .odt, etc, they all download as file.bin. In this case i have to change headers for each extension file?

**Comment by smahdink** [comment]
@obie3 Good, but what about uploads?

**Comment by KaiserSosay** [comment]
Still Searching

**Comment by riteshsingh1** [comment]
still searchning

**Comment by de-conf** [comment]
still searchning

**Comment by LucPSC** [comment]
Hi people,

Has anyone found the solution ? I'm stuck...
Thank

**Comment by de-conf** [comment]
> Hi people,
> 
> Has anyone found the solution ? I'm stuck... Thank

set you web server  Content- type

**Comment by LucPSC** [comment]
I'v already checked and I cannot set my Content-Type on 'application/pdf' for example, I download different types of files (.pdf, .txt, .xlsx...)

**Comment by yorickshan** [comment]
same issue

**Comment by anujmpec** [comment]
any update on this ?

**Comment by smahdink** [comment]
I don't know, I dont work on it anymore. If you find anything please post
here.

در تاریخ دوشنبه 12 ژوئن 2023،‏ 16:17 anujmpec ***@***.***>
نوشت:

**Comment by etomeni** [comment]
Still searching....

**Comment by kkul** [comment]
We are still facing this issue.

**Comment by cloudkore** [comment]
Fixed it! WebView now download files in their original extension.

**_Just wanted to drop a quick update on the recent improvements we made regarding file downloads — especially those annoying .bin files. After a bunch of trial and error, the final tweak made a big difference. We stopped relying blindly on URLUtil.guessFileName (which often throws .bin as a fallback when it doesn't know the actual type) and instead used MimeTypeMap.getExtensionFromMimeType() to grab the real extension based on the MIME type. If that still gave us a generic MIME like application/octet-stream, we then checked the URL itself to see if it included something like .pdf or .zip and used that. Basically, we built a hierarchy: prioritize MIME-derived extensions, fall back to the URL if needed, and only use .download as a last resort — not .bin. We also improved how we pull filenames from headers (including UTF-8 encoded ones with filename*=), and separated concerns cleanly in the code — one part handles name extraction, the other handles extension guessing, and they’re combined at the end. Bonus: it now deals better with multi-part extensions like .tar.gz, so we don’t mess them up while appending._**



            setDownloadListener { url, userAgent, contentDisposition, mimeType, contentLength ->
                val filename = determineFileNameAndExtension(url, contentDisposition, mimeType)

                val request = DownloadManager.Request(Uri.parse(url)).apply {
                    setTitle(filename)
                    setDescription("Downloading $filename")
                    setMimeType(mimeType)
                    addRequestHeader("User-Agent", userAgent)
                    setNotificationVisibility(DownloadManager.Request.VISIBILITY_VISIBLE_NOTIFY_COMPLETED)
                    setDestinationInExternalPublicDir(Environment.DIRECTORY_DOWNLOADS, filename)

                    val cookies = CookieManager.getInstance().getCookie(url)
                    if (cookies != null) {
                        addRequestHeader("Cookie", cookies)
                    }

                    allowScanningByMediaScanner()
                }

                try {
                    val dm = getSystemService(Context.DOWNLOAD_SERVICE) as DownloadManager
                    dm.enqueue(request)
                    Toast.makeText(this@MainActivity, "Downloading $filename", Toast.LENGTH_SHORT).show()
                } catch (e: Exception) {
                    Toast.makeText(this@MainActivity, "Download failed: ${e.message}", Toast.LENGTH_LONG).show()
                }
            }

            loadUrl("https://test")
        }
    }

    private fun extractFilenameFromContentDisposition(contentDisposition: String?): String? {
        if (contentDisposition.isNullOrBlank()) return null

        var matcher = Regex("filename\\*=(.+)", RegexOption.IGNORE_CASE).find(contentDisposition)
        matcher?.let {
            try {
                val encodedValue = it.groupValues[1]
                val parts = encodedValue.split("''")
                if (parts.size == 2) {
                    return URLDecoder.decode(parts[1], "UTF-8")
                }
            } catch (e: Exception) {}
        }

        matcher = Regex("filename=\"([^\"]+)\"|filename=([^;]+)", RegexOption.IGNORE_CASE).find(contentDisposition)
        matcher?.let {
            val filename = it.groupValues[1].ifEmpty { it.groupValues[2] }
            return try {
                URLDecoder.decode(filename, "UTF-8")
            } catch (e: Exception) {
                filename
            }
        }
        return null
    }

    private fun determineFileNameAndExtension(url: String, contentDisposition: String?, mimeType: String?): String {
        var baseName: String? = null

        baseName = extractFilenameFromContentDisposition(contentDisposition)

        if (baseName.isNullOrBlank()) {
            baseName = URLUtil.guessFileName(url, null, null)
        }

        baseName = try {
            URLDecoder.decode(baseName, "UTF-8")
        } catch (e: Exception) {
            baseName
        }

        if (baseName.isNullOrBlank()) {
            baseName = "downloaded_file"
        }

        val extensionFromMimeType = MimeTypeMap.getSingleton().getExtensionFromMimeType(mimeType)

        val urlPathExtension = Uri.parse(url).lastPathSegment?.let {
            val lastDot = it.lastIndexOf('.')
            if (lastDot != -1 && lastDot < it.length - 1) {
                it.substring(lastDot + 1).toLowerCase()
            } else {
                null
            }
        }

        var finalExtension: String? = null

        if (!extensionFromMimeType.isNullOrBlank() && !extensionFromMimeType.equals("bin", ignoreCase = true)) {
            finalExtension = extensionFromMimeType
        } else if (!urlPathExtension.isNullOrBlank() && !urlPathExtension.equals("bin", ignoreCase = true)) {
            if (MimeTypeMap.getSingleton().hasExtension(urlPathExtension) ||
                listOf("pdf", "zip", "rar", "docx", "xlsx", "pptx", "jpg", "jpeg", "png", "gif", "mp4", "mp3", "txt", "html", "htm", "xml", "json", "csv").contains(urlPathExtension)) {
                finalExtension = urlPathExtension
            }
        }

        val nameWithoutExistingExtension: String
        val currentBaseNameLastDotIndex = baseName.lastIndexOf('.')
        if (currentBaseNameLastDotIndex != -1 && currentBaseNameLastDotIndex < baseName.length - 1) {
            val potentialLastPartExt = baseName.substring(currentBaseNameLastDotIndex + 1).toLowerCase()
            if (potentialLastPartExt == "gz" || potentialLastPartExt == "bz2" || potentialLastPartExt == "xz" || potentialLastPartExt == "zip" || potentialLastPartExt == "tar") {
                 val secondLastDotIndex = baseName.substring(0, currentBaseNameLastDotIndex).lastIndexOf('.')
                 if (secondLastDotIndex != -1 && baseName.substring(secondLastDotIndex + 1, currentBaseNameLastDotIndex).matches(Regex("[a-zA-Z0-9]+"))) {
                     nameWithoutExistingExtension = baseName.substring(0, secondLastDotIndex)
                 } else {
                     nameWithoutExistingExtension = baseName.substring(0, currentBaseNameLastDotIndex)
                 }
            } else {
                 nameWithoutExistingExtension = baseName.substring(0, currentBaseNameLastDotIndex)
            }
        } else {
            nameWithoutExistingExtension = baseName
        }

        val finalFilename = if (!finalExtension.isNullOrBlank()) {
            "$nameWithoutExistingExtension.$finalExtension"
        } else {
            val fallbackGenericExtension = "download"
            "$nameWithoutExistingExtension.$fallbackGenericExtension"
        }

        return finalFilename
    }

    private fun requestPermissionsIfNeeded() {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.Q) {
            if (ContextCompat.checkSelfPermission(
                    this, Manifest.permission.WRITE_EXTERNAL_STORAGE
                ) != PackageManager.PERMISSION_GRANTED
            ) {
                ActivityCompat.requestPermissions(
                    this,
                    arrayOf(Manifest.permission.WRITE_EXTERNAL_STORAGE),
                    101
                )
            }
        } else {
        }
    }

    override fun onBackPressed() {
        if (webView.canGoBack()) webView.goBack()
        else super.onBackPressed()
    }
}
