### ISSUE TITLE
onPermissionRequest implemented multiple times

### ISSUE THREAD

**Issue by KestasVenslauskas** [react-native-webview/react-native-webview#2013]
https://github.com/react-native-webview/react-native-webview/blob/4e07183a2d742c47df217545f4a1a99271c39b46/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java#L1154

On android there is 2 implementations for onPermissionRequest method which does not compile...
Error:
```
method onPermissionRequest(PermissionRequest) is already defined in class RNCWebChromeClient
    public void onPermissionRequest(final PermissionRequest request) {
                ^
```

**Comment by dariaminakova** [comment]
Have the same issue

**Comment by matt-oakes** [comment]
Caused by this commit: https://github.com/react-native-webview/react-native-webview/commit/9f6037e4b23535633e84bfc8b31434f90870727d

**Comment by badararain** [comment]
Having Same issue 
![Uploading Screenshot 2021-05-24 at 4.59.15 PM.png…]()

**Comment by Titozzz** [comment]
Sorry 😐

**Comment by matt-oakes** [comment]
Thank you @Titozzz! v11.6.2 works perfectly 👍

**Comment by Titozzz** [comment]
Sorry for the bugs guys 😔 thanks @matt-oakes for testing

**Comment by badararain** [comment]
> Sorry for the bugs guys 😔 thanks @matt-oakes for testing

thanks for fixing it.
