### ISSUE TITLE
Fail/Crash to open app after installing react-native-webview dependency

### ISSUE THREAD

**Issue by VitorPaludetto** [react-native-webview/react-native-webview#2014]
**Bug description:**

I installed the latest version of the lib and when I run `yarn react-native run-android` everything goes fine, but I can't get my app to open on the emulator after it. It keeps crashing. If I remove react-native-webview dependency my app opens normally. 
I've tried to install older versions of the lib but the same happens.
I already wiped the emulator settings and cleared cache to see if it would work, but with no success.

**Screenshots/Videos:**

App Crashing when react-antive-webview is installed.
![appCrashBetter](https://user-images.githubusercontent.com/29387670/119383023-3af3b380-bc99-11eb-8be4-06efcddd8057.gif)

App opens when I remove the dependency
![appWorking](https://user-images.githubusercontent.com/29387670/119383103-53fc6480-bc99-11eb-9ae9-baf85b62af39.gif)

**Environment:**
 - OS: Android
 - OS version: 11
 - react-native version: 0.63.4
 - react-native-webview version: 11.6.2

**Comment by AlexPeret** [comment]
hi,

I've started facing the same problem after adding _minHeight_ attribute to the style property, like this:

```
<WebView
    ...
    style={{backgroundColor: 'transparent', flex: 1, minHeight: '300px'}}
    ...
 />
```

replacing the minHeight's value to a number works fine:

```
<WebView
    ...
    style={{backgroundColor: 'transparent', flex: 1, minHeight: 300}}
    ...
 />
```

**Environment:**
- OS: Android
- OS version: 11
- react-native: 0.63.4
- react-native-webview: ^11.4.3

**Comment by alexcbluk** [comment]
I have a very similar android specific issue with version: `^11.6.4`
Like yourself, I have ONLY installed the package via `yarn add react-native-webview` and my detox tests have been failing with the following error:

```
DetoxRuntimeError: Failed to run application on the device

    HINT: Most likely, your main activity has crashed prematurely.

    Native stacktrace dump: java.lang.NoSuchMethodError: No direct method <init>(ILjava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V in class Lkotlin/jvm/internal/FunctionReferenceImpl; or its super classes (declaration of 'kotlin.jvm.internal.FunctionReferenceImpl' appears in /data/app/~~tVQXRextVO2nUllF1-6L6g==/com.whichmobileapp-R1eVS54uc89qIOHE9sUwbg==/base.apk)
```

What makes it even more confusing is that I haven't even started using the `< WebView />` component anywhere in the code base.

Environment:

OS: Android
MacOS 10.15.7
react-native: 0.64.2
react-native-webview: ^11.6.4

**Comment by alexcbluk** [comment]
To resolve the issue I had with detox, I had to use a lower version of the `kotlin-gradle-plugin` which can be found in `android/settings.gradle`
```
classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.71'
```
