### ISSUE TITLE
Webview fails to open certain links, only in Production builds

### ISSUE THREAD

**Issue by dickfickling** [react-native-webview/react-native-webview#2015]
**Bug description:**

Certain web pages, specifically those navigated to from a text field autocomplete, fail to render after clicking on the link, and only on production builds from TestFlight / the App Store.

This is a wild bug, and I've spent way too long trying to figure out what's going on. Hoping somebody reading this can point me in the right direction. I know I'm asking for free tech support here so if you want to close this issue & tell me to go elsewhere I'll understand.

**To Reproduce:**

Because this bug only seems to appear in production builds from the App Store, I'm not sure how to provide a repro. I'm mostly posting this issue in hopes that somebody else has seen and solved this problem before me.

**Expected behavior:**
When I search Google and tap on an autocomplete suggestion, I expect the search results to populate.

**Screenshots/Videos:**

I realize my description above is confusing to follow. Hopefully this video clears things up a bit.

The first 10 seconds of this video are in a local build of the app, installed to my phone. The latter 10 seconds are from the version of the app from the app store. Notice that tapping the "sephora" suggestion in the first app shows search results from sephora, whereas tapping "sephora" in the second one shows a blank screen. This is reproducible on Amazon as well.

https://user-images.githubusercontent.com/1130084/119392376-adff2900-bc9d-11eb-84f2-91950439f8cb.mov

**Environment:**
 - OS: iOS
 - OS version: 14.5
 - react-native version: 0.63.3
 - react-native-webview version: 11.3.1

**Comment by dickfickling** [comment]
Solved: We were finding ourselves in a weird situation where:
1. user clicks on auto-suggested search term in google
2. google pushes a new temporary url to navigation state while loading search results
3. onNavigationStateChange is called and we update our internal state's currentUrl param to be the temp url
4. new url is passed as a prop to the webview (`source={{ uri: currentUrl }}`), which should be fine because it's the URL we just got from the webview, but this causes google to stop loading the search results
5. wait forever in despair

**Comment by v-almonacid** [comment]
@dickfickling it still looks like a bug IMO, specially if it only happens on production. What version are you on?
I think I'm facing the same issue.

**Comment by cokealmonacid** [comment]
> @dickfickling it still looks like a bug IMO, specially if it only happens on production. What version are you on?
> I think I'm facing the same issue.

any solution on this cousin?

**Comment by dickfickling** [comment]
it's really not a bug -- by updating the source URI for the webview, we were forcing it to reload the page, and due to the way Google loads search results async in the background, we were breaking their page. Perhaps the only bug is that it seemed to work in debug builds.

**Comment by v-almonacid** [comment]
@dickfickling yeah, my bad.

@cokealmonacid it actually works fine, I just did a mistake. Sorry cousin 😆
