### ISSUE TITLE
Youtube video on iOS always playing in full screen mode

### ISSUE THREAD

**Issue by aneena-thomas** [react-native-webview/react-native-webview#2018]
Youtube video on iOS always playing in full-screen mode while clicking the play button.
working fine in android
**Environment:**
 - OS version:14
 - react-native version: 0.63.4
 - react-native-webview version: 11.6.2

**Comment by wrsulliv** [comment]
@aneena-thomas  Were you ever able to resolve this?  I'm having the same problem

**Comment by aneena-thomas** [comment]
@wrsulliv  Actually, I have used some other package for iOS. And for android, I am using the web view for showing the youtube video, try this,

source={{  uri: `${source}?=0&autoplay=0&showinfo=0&controls=0&fullscreen=0` }}

**Comment by wrsulliv** [comment]
@aneena-thomas Thanks for the reply!  I was able to get it working with:

```typescript
<WebView
   allowsInlineMediaPlayback={true}
   allowsFullscreenVideo={ false }
   source={{uri: `https://www.youtube.com/embed/${videoId}?playsinline=1`}}
 />
```

It started working for me when I added `?playsinline=1`

**Comment by aneena-thomas** [comment]
@wrsulliv Ok.

**Comment by arun1989** [comment]
it helped to fix issue when i added 

  allowsFullscreenVideo={true}

**Comment by DAMHONGDUC** [comment]
in my case, this work
mediaPlaybackRequiresUserAction={true}

**Comment by DAMHONGDUC** [comment]
there are two thing:

```
<WebView>
     ...
     allowsInlineMediaPlayback={true}
     ...
     source={{
          html: `
                    ...
                    <video 
                         ... 
                         playsInline 
                         ... 
                    ></video> 
                    ...
               `
     }}
</WebView>
```
