### ISSUE TITLE
Redirect url not detected on android

### ISSUE THREAD

**Issue by cokealmonacid** [react-native-webview/react-native-webview#2022]
Need to detect a success or error url when im trying to login on a web through a webview.
With the current flow, when i try to login on this form through the webview, the webview detect differents urls and one of them is /ok or /nok (i know, pretty cool way to valdiate a user). im using onNavigationStateChange to detect this urls.

On iOS works pretty well, with onNavigationStateChange detect the specific url and with that decide the next action.
But on Android, after the login, with the navigationStateChange, receives a few differents urls but no ones with /ok or /nok.

Been trying differents methods, onLoadStart, onShouldStartLoadWithRequest, etc. But non of these works.
Any help?

**Environment:**
 - OS: Android
 - react-native version: 0.62
 - react-native-webview version: 10.7

**Comment by cokealmonacid** [comment]
Updating to the latest version dont make this work, any solution?
try to add network_security_config.xml to AnroidManifest but dont work.
Uses onLoad, onLoadStart, onLoadEnd, onLoadProgress and nothing.
Try it #1900 solutions and nothing. 

This is a related issue #939 (close?)

**Comment by AlbertVilaCalvo** [comment]
Same here, I have `onNavigationStateChange`, `onLoad`, `onLoadEnd` and `onShouldStartLoadWithRequest`. They all work fine in iOS. On Android they work sometimes.

I don't see a pattern though because some redirects work and others don't:
- https://zara.es does not work. Site is redirected to https://www.zara.com/es/
- https://zalando.com works. Site is redirected to https://m.zalando.es/mujer-home/

**Comment by fpena** [comment]
Same here, experiencing the same with version `11.6.4`.

**Comment by fpena** [comment]
This worked me in Android using `onLoadProgress` instead. I tested it and it doesn't work for iOS, so duplicated logic needs to be added to `onNavigationStateChange` too. cc: @cokealmonacid

**Comment by cokealmonacid** [comment]
Finded a solution that works fine on my case, the problem is this method on android 
https://github.com/react-native-webview/react-native-webview/blob/e33eea6dcf43b43e96b3a2dfffc689fbd54e98ea/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java#L897

To solve this, override the shouldOverrideUrlLoading method like this:

```
public boolean shouldOverrideUrlLoading(WebView view, String url) {
         view.loadUrl(url);
          return true;
}
```

Need to keep testing this but seems to works pretty well.
PS: I know, we are forcing android to load everything but strictly on my case, this is the solution.

**Comment by saahiil-pny** [comment]
> Finded a solution that works fine on my case, the problem is this method on android
> 
> https://github.com/react-native-webview/react-native-webview/blob/e33eea6dcf43b43e96b3a2dfffc689fbd54e98ea/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java#L897
> 
> To solve this, override the shouldOverrideUrlLoading method like this:
> 
> ```
> public boolean shouldOverrideUrlLoading(WebView view, String url) {
>          view.loadUrl(url);
>           return true;
> }
> ```
> 
> Need to keep testing this but seems to works pretty well.
> PS: I know, we are forcing android to load everything but strictly on my case, this is the solution.

Hi, I have tried adding this but still, I am not getting the URL change when in a SPA. Works for iOS though.

**Comment by SudoPlz** [comment]
To work around that issue I did this:

```
const SHOULD_SWIZZLE_ON_STATE_CHANGE = Platform.OS === 'android';
  onLoadProgress = (event: WebViewProgressEvent) => {
    if (SHOULD_SWIZZLE_ON_STATE_CHANGE && event.nativeEvent.progress === 1) {
      this.props.onNavigationStateChange(event.nativeEvent);
    }
  }
```

so basically I fire my `onNavigationStateChange` listener when `onLoadProgress` (which is the only event fired by rn webview actually) completes.

**Comment by sixty-four-bit** [comment]
Any solution to this?

**Comment by fpena** [comment]
@sixty-four-bit this worked for me 

https://github.com/react-native-webview/react-native-webview/issues/2022#issuecomment-862921683

**Comment by sixty-four-bit** [comment]
@fpena, HI Mate,  Thanks for the suggestion.  Not working for me . Can you please post some details on this .

**Comment by ThakurBallary** [comment]
> To work around that issue I did this:
> 
> ```
> const SHOULD_SWIZZLE_ON_STATE_CHANGE = Platform.OS === 'android';
>   onLoadProgress = (event: WebViewProgressEvent) => {
>     if (SHOULD_SWIZZLE_ON_STATE_CHANGE && event.nativeEvent.progress === 1) {
>       this.props.onNavigationStateChange(event.nativeEvent);
>     }
>   }
> ```
> 
> so basically I fire my `onNavigationStateChange` listener when `onLoadProgress` (which is the only event fired by rn webview actually) completes.

This worked for my use case.

@SudoPlz thank you :)

**Comment by Alt-er** [comment]
@SudoPlz  thanks

**Comment by tr3v3r** [comment]
@cokealmonacid  works for me but also I've managed to received redirect URL using `onShouldStartLoadWithRequest` method.

**Comment by SamiChab** [comment]
For me none of `onShouldStartLoadWithRequest` or `onLoadProgress` work in production mode. It works fine only in dev mode.
`react-native: 0.63.3`
`react-native-webview: 11.23.1`

**Comment by elli-10xers** [comment]
Maybe try turning off JS debugger while testing the redirection? Taking a look at the code, there's an if condition of `if (!isJsDebugging && ...)` that might cause the `shouldOverrideUrlLoading` to not work as expected.

We're also facing this issue on android, and just turning off the debugger seems to work for now, haven't tested on iOS though but since there's no code change I think it shouldn't affect iOS

`"react-native": "0.64.4"`
`"react-native-webview": "^11.17.1"`
