### ISSUE TITLE
Disable Scroll inside HTML content so that it'll take outer screen's scroll

### ISSUE THREAD

**Issue by hrishiakhade** [react-native-webview/react-native-webview#2024]
Hello , 

As you can see in the screenshot, I have Image and HTML content on one screen.   I  have already added scroll on this screen but HTML content has its own scroll. (refer ss, you can see a scroll bar) . Hence I am not able to scroll this entire page . Is there any way to disable HTML content scroll so that it takes all the space of my scrollable page  ? 

<ScrollView 
           contentContainerStyle={[styles.container, { backgroundColor: colors.COLOR_FFFFFF }]}
>
                    {this.renderImage()}
                    {this.renderContent(this.state?.articleContent)}
 </ScrollView>

renderContent = (data) => {
         {
            return (
                    <WebView
                          source={{ html: `<head><meta name="viewport" content="width=device-width, initial-scale=1.0"></head>` + 
                         data?.contents }}
                        containerStyle={{ padding: 8, paddingTop: 0, backgroundColor: 'white' }}
                        automaticallyAdjustContentInsets={false}
                        useWebKit={false}
                        originWhitelist={['*']}
                        dataDetectorTypes={'link'}
                        bounces={false}
                        onShouldStartLoadWithRequest={event => {
                            if (!/^[data:text, about:blank]/.test(event.url)) {
                                openArticleURL(event.url)
                                return false
                            } else {
                                if (Platform.OS === 'ios') {
                                    return true
                                } else {
                                    openArticleURL(event.url)
                                    return false
                                }
                            }
                        }}
                        //style={{ flex: 1 }}
                    />
            )
        }
    }

![image](https://user-images.githubusercontent.com/20705523/119981028-c2fbf500-bfda-11eb-8d80-1c1924e9e16a.png)

**Environment:**
 - react-native version:0.63.2
 - react-native-webview version:11.3.2

**Comment by TheAlmightyBob** [comment]
Have you tried setting `scrollEnabled` to `false`?

**Comment by hrishiakhade** [comment]
@TheAlmightyBob Yes , I tried , It did not work

**Comment by cristianoccazinsp** [comment]
I think you should set a fixed height View (do not use ScrollView) and let the webview scroll by itself.

Alternatively, make sure the HTML content has it's own scroll (e.g., <div> with scroll and 100% height), and use a View (not ScrollView) combined with `scrollEnabled=false`.  I'm using exactly this for a rich text editor and it is working fine.

**Comment by johnsonfash** [comment]
const injectScript = `
    document.body.style.overflow = 'hidden';
  `;
  
  <WebView  injectedJavaScript={injectedJavaScript} javaScriptEnabled={true} />

**Comment by bondansebastian** [comment]
> const injectScript = `document.body.style.overflow = 'hidden';`;

Man it's 2025 and you saved me! @johnsonfash
