### ISSUE TITLE
The Kotlin Gradle plugin was loaded multiple times in different subprojects

### ISSUE THREAD

**Issue by KrisLau** [react-native-webview/react-native-webview#2026]
**Bug description:**
Getting this error on build: 
```
The Kotlin Gradle plugin was loaded multiple times in different subprojects, which is not supported and may break the build. 
This might happen in subprojects that apply the Kotlin plugins with the Gradle 'plugins { ... }' DSL if they specify explicit versions, even if the versions are equal.
Please add the Kotlin plugin to the common parent project or the root project, then remove the versions in the subprojects.
If the parent project does not need the plugin, add 'apply false' to the plugin line.
See: https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl
The Kotlin plugin was loaded in the following projects: ':react-native-pager-view', ':react-native-webview'
```
I looked through old bug reports and it looks like it was fixed in build 10.0.0 but I'm on ^11.4.3 and I'm still getting the error. Not sure if this error only appeared because of expo's unimodules or if I just never noticed it before.  Another open bug report with the same issue is #1968 and a closed one is #2005. #2005 solution seems to be to use an older version but what would I need to if I want the latest version?

**To Reproduce:**
1. Install react-native-pager-view, and react-native-webview.
2. Build the app & run react-native run-android

**Expected behavior:**
No build errors

**Screenshots/Videos:**
![image](https://user-images.githubusercontent.com/46275463/120012625-5c101900-bfa5-11eb-8eb9-7e8700893834.png)

**Environment:**
 - OS: Android
 - OS version: Pixel 3a API 30
 - react-native version: ^0.64.0
 - react-native-webview version: ^11.4.3

**Comment by cristianoccazinsp** [comment]
I'm getting the same when combined with https://github.com/agoldis/react-native-mlkit-ocr

**Comment by KrisLau** [comment]
Does anyone have any input on this and insight on whether it will cause any problems?

**Comment by azkakhairul09** [comment]
i getting same error

**Comment by meeran22** [comment]
getting same error

**Comment by AR-Rana** [comment]
Still searching for solutions

**Comment by pierroo** [comment]
Same error for me; did any of you guys find a solution to this kotlin version issue?
@KrisLau @azkakhairul09 @meeran22 @AR-Rana

**Comment by tecnoloco** [comment]
Same error here, is there a workaround?

**Comment by Bavaria93** [comment]
Mesmo aqui

**Comment by vincentRouget** [comment]
+1

**Comment by DevKalebe** [comment]
O erro continua para mim

**Comment by Firas1993** [comment]
same here when installing react_native_mqtt or react-native-mqtt
