### ISSUE TITLE
Is javascript injection secure?

### ISSUE THREAD

**Issue by roeycohen** [react-native-webview/react-native-webview#2027]
Hi! first thing first, 10q for this great project :)

I'm wondering if using the following methods/props is secure:
injectJavaScript
injectedJavaScript
injectedJavaScriptBeforeContentLoaded

The idea is passing authentication token (which is stored in a secure storage) to the webview so it can make authenticated ajax calls to the server,
But I'm worried about XSS that might run the following code and extract the token:
`$('script').html()`

if not, do you know other approaches?
10q!

**Comment by roeycohen** [comment]
Other Options I thought about:
- Creating HTTP only session cookie - problem, Android won't delete the cookie at all, IOS will delete it when the application is minimized.
- Using HTTP only cookie with short expiry and every few minutes extend it - problem, the cookie might not be deleted from the webview storage when the application closes.
- Using shouldInterceptRequest/CustomeSchemeHandler - doesn't seem to be supported by react-native-webview,

I'm clueless here... :(

**Comment by alakdam07** [comment]
Seems like the package owners does not care about issues :D
