### ISSUE TITLE
 injectedJavaScript cannot detect the queryselector's classname 

### ISSUE THREAD

**Issue by alakdam07** [react-native-webview/react-native-webview#2029]
I am using [react-native-webview](https://github.com/react-native-webview/react-native-webview) package for the WebView. In my WebView link, I want to hide nav and footer from my WebView. I used google chrome's inspect and then target the class name of the nav bar and made variable where I added the display `none` and pass this variable to WebView's props ` injectedJavaScript` but seems like my style does not work. 

I shared my code in [Exop-snacks](https://snack.expo.io/@alakdam/webview-injectedjavascript).

```

import React from "react";
import styled from "styled-components/native";

import { WebView } from "react-native-webview";
import { View } from "react-native";
const weburl = "https://www.s-kaupat.fi/sivu/usein-kysytyt-kysymykset";

const Container = styled.View`
  flex: 1;
`;

const WebScreen = () => {
  const jsCode = `
      document.querySelector('.cBIlxL').style.display = 'none';
      document.querySelector('.footer').style.display = 'none';
    `;
  return (
    <Container>
      <WebView
        source={{
          uri: weburl,
        }}
        startInLoadingState={true}
        renderLoading={() => <View />}
        // injectedJavaScript require passing onMessage function
        // eslint-disable-next-line @typescript-eslint/no-empty-function
        onMessage={() => {}}
        injectedJavaScript={jsCode}
        javaScriptEnabled={true}
      />
    </Container>
  );
};

export default WebScreen;

```

**Comment by gwmccull** [comment]
@alakdam07 did you figure out a solution? I'm running into the same issue and it seems to have just started recently

**Comment by alakdam07** [comment]
The package owners don’t reply on any issues that’s why I closed it. Pointless to keep open issue.

**Comment by gwmccull** [comment]
as far as I could tell, my issue was related to the DOM nodes not existing when the injected JS is run. My hacky solution was to wrap the whole thing with a `setTimeout`
