### ISSUE TITLE
not resuming from last url from which webview exit. it is opening default  default source uri provided.

### ISSUE THREAD

**Issue by rnqayush** [react-native-webview/react-native-webview#2038]
Webview is not resuming from last url from which it exit. it is opening default source uri provided.
![webview issue](https://user-images.githubusercontent.com/74084740/120968780-ebc47d00-c786-11eb-8b86-ad0624016084.png)

**Comment by MasterTeus** [comment]
Wrap the webView as a child of a Modal, so every time the modal is unmounted the WebView will restart with the chosen url

`<Modal visible={toggleModal}>
  <WebView  />
</Modal>
`
