### ISSUE TITLE
renderLoading isn't called when webview loads new page

### ISSUE THREAD

**Issue by sanpoChew** [react-native-webview/react-native-webview#2039]
**Bug description:**

`renderLoading` isn't called unless `startInLoadingState` is set to true, and even then only once. It isn't called when the webview starts loading a new page because `viewState` doesn't get updated.

Adding a `setState` call to the `onLoadingStart` method setting `viewState` to `LOADING` gives us the desired behaviour. I am happy to open a PR with this change.

**To Reproduce:**

set the `renderLoading` prop and navigate to a linked page within the webview, the loader does not render.

**Expected behavior:**

I would expect `renderLoading` to be called every time the webview is in a loading state, maybe I am wrong in this assumption?

**Environment:**
 - OS: iOS
 - OS version: 14
 - react-native version: 0.63.4
 - react-native-webview version: 11.6.2

**Comment by sennett** [comment]
Solution I found was to render the webview completely:

```
const [renderWebview, setRenderWebview] = useState(true);

useEffect(() => {
  setRenderWebview(false);

  let t = setTimeout(() => {
    setRenderWebview(true);
  }, 1);

  return () => clearTimeout(t);
}, [webviewUri]);

return {renderWebview && (
  <WebView
    source={{
      uri: webviewUri
    }}
    startInLoadingState
    renderLoading={() => <Loading />}
  />
)}
```
