### ISSUE TITLE
Collecting cookies in a webview requires the use of App Tracking Transparency on iOS

### ISSUE THREAD

**Issue by helloagain-dev** [react-native-webview/react-native-webview#2040]
A website requests cookies from the user, which is in conflict with apples app transparency framework.

Is there any way to solve this on the app side without getting rid of the cookie request all together?

```
We noticed your app accesses web content you own where you collect cookies. However, you do not use App Tracking Transparency to request the user's permission before collecting data used to track.

Collecting cookies is a form of tracking. Starting with 14.5, apps on the App Store need to receive the user’s permission through the AppTrackingTransparency framework before collecting data used to track them.
```

**Comment by cristianoccazinsp** [comment]
Have you found a way around this? Do you really need to request tracking permission to use a simple webview?

**Comment by helloagain-dev** [comment]
@cristianoccazinsp couldn't find a way around it yet. This is the official Apple response and attached is a screenshot from the webview asking for cookies.

```
Guideline 5.1.2 - Legal - Privacy - Data Use and Sharing


We noticed your app accesses web content you own where you collect cookies. However, you do not use App Tracking Transparency to request the user's permission before collecting data used to track.

Collecting cookies is a form of tracking. Starting with 14.5, apps on the App Store need to receive the user’s permission through the AppTrackingTransparency framework before collecting data used to track them.

Next Steps

Follow these steps to resolve this issue:

1. If you haven't already, update your app privacy information in App Store Connect to disclose that you track users. You must have the Account Holder or Admin role to update app privacy information.
2. Implement App Tracking Transparency.
3. Request permission using App Tracking Transparency before collecting data used to track the user. When you resubmit, indicate in the Review Notes where the permission request is located.
4. If the user does not allow tracking, do not collect cookies for tracking purposes.

You may also choose to remove the tracking functionality from your app, including tracking that occurs when accessing web content.

Resources

- Tracking is linking data collected from your app with third-party data for advertising purposes, or sharing the collected data with a data broker. Learn more about tracking.
- See Frequently Asked Questions about the new requirements for apps that track users.
- Learn more about designing appropriate permission requests.

Please see attached screenshot for details.
```
![screenshot](https://user-images.githubusercontent.com/29772229/121198703-a2e9f280-c872-11eb-90ce-f4095d105f53.png)

**Comment by cristianoccazinsp** [comment]
So does your website actually collect tracking information? How does Apple infer that cookies from your browser are for tracking purposes?

**Comment by helloagain-dev** [comment]
It does not collect tracking information, just a session id for the shop (delete when the browser is closed) and the information whether the cookie banner was already clicked or not. 

Unfortunately, I have no idea how Apple assumes that cookies are used for tracking purposes.

**Comment by MoOx** [comment]
Just facing the same issue with Apple. I was thinking that we could "just" disable cookies...
I found 2 props for this `thirdPartyCookiesEnabled` (android only) and `sharedCookiesEnabled`(but this one seems disabled by default). So I have no idea how to fix this iOS problem.

@cristianoccazinsp @helloagain-dev what workaround did you used to publish your app?

**Comment by helloagain-dev** [comment]
@MoOx the workaround we had so far for one app was to inject a custom javascript into the webview that just hides the cookie modal. However, this is far from a useful solution.
We are managing quite a lot of apps and this rejection keeps popping up

**Comment by MoOx** [comment]
If I understand correctly this post https://webkit.org/blog/10882/app-bound-domains/ I see 2 solutions:

# Stop using react-native-webview (that uses WKWebView) 

Rely on `SafariViewController` instead, in practise that means use [react-native-inappbrowser-reborn](https://www.npmjs.com/package/react-native-inappbrowser-reborn)

# Or use App-Bound Domains without domains

> To opt-in to App-Bound Domains, [the app] only needs to add an empty WKAppBoundDomains key to their `Info.plist`.

```xml
<plist version="1.0">
<dict>
<key>WKAppBoundDomains</key>
</dict>
```

Read carefully the post above to be sure about what I interpret :)

**Comment by ristkof** [comment]
We ran into this issue and tried our luck with the second option: app-bound domains, as per [hybrid app](https://webkit.org/blog/10882/app-bound-domains/) example, but we still got the answer that we need to answer App Tracking Transparency.

Does anyone have different experiences? Anybody got past app tracking transparency with app-bound domains?

**Comment by dejavu1987** [comment]
+1
