### ISSUE TITLE
Camera and microphone permissions does not work for iframe inside webview 

### ISSUE THREAD

**Issue by suraj-desai** [react-native-webview/react-native-webview#2042]
**Bug description:**

I am trying to access camera and microphone of a certain website in iframe inside webview but the permissions are not granted for it.

**To Reproduce:**

1. access any website that uses camera and microphone eg.https://webcamera.io/  in iframe inside webview.

**Expected behavior:**

should be able to use/access camera and microphone

**Environment:**
 - OS:Ubuntu
 - OS version: 18.04
 - react-native version:0.63.0
 - react-native-webview version: 11.6.2

**Comment by techiespace** [comment]
Even I'm facing the same issue. Is there any workaround for this?

**Comment by techiespace** [comment]
Still searching for solutions. Isn't this a common use case? Am I missing something obvious?

**Comment by Erickinhou** [comment]
Same Issue

**Comment by techiespace** [comment]
Giving the bot some activity.

**Comment by ddennis** [comment]
Giving the bot some activity.

**Comment by pranav-js** [comment]
solution please?
