### ISSUE TITLE
React native webview make app crash on ios 13.7

### ISSUE THREAD

**Issue by thainquet** [react-native-webview/react-native-webview#2045]
**Bug description:**
React native webview is seemed to be the cause of crashing app on ios 13.7.
Please note that i am working on M1 mac mini so i need to run ```arch -x86_64 pod install``` instead of ```npx pod-install``` when installing package.
**To Reproduce:**
1. ```npx react-native init test```
2. ```cd test && yarn add react-native-webview && cd ios && arch -x86_64 pod install```
3. Change code inside ```App.js```:
```
import React, { useState } from 'react'
import { SafeAreaView, TouchableOpacity, Text, View } from 'react-native'
import WebView from 'react-native-webview'

export default function App() {
  const [load, setLoad] = useState(false)

  return (
    <SafeAreaView style={{
      flex: 1
    }}>
      <TouchableOpacity style={{
        flex: 1
      }}
        onPress={() => setLoad(!load)}
      >
        <Text>Open</Text>
      </TouchableOpacity>
      <View style={{
        flex: 1
      }}>
        {load && <WebView
          source={{
            uri: 'https://reactnative.dev'
          }}
        />}
      </View>
    </SafeAreaView>
  )
}
```
4. Open ```test.xcworkspace```, choose the target is iPhone 11 Pro Max (14.5) then press ```Run``` to make sure every works fine.
5. Stop building, switch target to iPhone 11 Pro Max (13.7) then press ```Run``` and this bug occurs.
**Expected behavior:**
react-native-webview should not break the app.
**Screenshots/Videos:**
(step 4): 
![Screen Shot 2021-06-09 at 17 56 35](https://user-images.githubusercontent.com/23478524/121342644-0bf16900-c94c-11eb-8787-b1b260be32bb.png)
(step 5):
![Screen Shot 2021-06-09 at 17 58 22](https://user-images.githubusercontent.com/23478524/121342872-4a872380-c94c-11eb-8abd-54b3aa550e26.png)
![Screen Shot 2021-06-09 at 17 58 52](https://user-images.githubusercontent.com/23478524/121342928-5b379980-c94c-11eb-8f8b-71bb64a53c18.png)
**Environment:**
 - OS: MacOS
 - OS version: MacOS BigSur 11.2
 - react-native version: 0.64.2
 - react-native-webview version: 11.6.2

**Comment by jorgeruvalcaba** [comment]
I'm facing the same issue, @thainquet have you resolved it?

**Comment by thainquet** [comment]
not yet @jorgeruvalcaba ....
