### ISSUE TITLE
can not load local image on IOS

### ISSUE THREAD

**Issue by hujingyuki** [react-native-webview/react-native-webview#2050]
**Bug description:**

I have use require func to set source attribute，just like `source={require('../index.html')}`. this html will load local image from CachesDirectoryPath, which src is like `file:///var/data/.../cache/../img.png`. Now html is successfully loaded,but image can't show as expect.
I have check other issues about this, there is no official answer， every question is closed due to timeout.
PS: image source is downloaded form server to cache directory.

**To Reproduce:**

cause code is privacy, sorry for can not provide it.

**Expected behavior:**

can display image rightly.

**Screenshots/Videos:**

**Environment:**
 - OS: ios
 - OS version: 13.7
 - react-native version: 0.62.1
 - react-native-webview version: 11.6.2

**Comment by TheAlmightyBob** [comment]
Are you using https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#allowingReadAccessToURL ?

**Comment by HackedBeat** [comment]
@hujingyuki the only way to make it work, which I found, is using base64 links for images. You can get base64 code on the app side, and then pass it to the webview.

**Comment by vhonLopez** [comment]
Encountered this issue right now. Do you have any solutions?

**Comment by vhonLopez** [comment]
I'm having issues in displaying my local image 

just like this <img src="file:///data/user/0/com.company_name/files/RNFetchBlobTmp_ja301cv3cauidw6i95ne" width=576 height=738>

does anyone having this issue also?

**Comment by vhonLopez** [comment]
i'm using react-native webview btw and fetchBlob

**Comment by TheAlmightyBob** [comment]
@vhonLopez Same question as above, are you using https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#allowingReadAccessToURL?

**Comment by Timson020** [comment]
@TheAlmightyBob 
how to set it path ？

like it ? 
```
const html = `
<html>
<header>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
</header>
<body style='width: 100%; height: 100%'>
	<h1>Hello world</h1>
	<img src='file:///Users/timson/Library/Developer/CoreSimulator/Devices/4FC3A354-2592-4CA7-A31D-48B717073C77/data/Containers/Data/Application/B6DA59F5-F3AD-4310-B439-F8C5E10F8F0F/Library/Caches/ExponentAsset-c734baf87100d32fc09b7df065428255.jpeg' style='width: 200px; height: 200px; background: blue' />
	<img src='/Users/timson/Library/Developer/CoreSimulator/Devices/4FC3A354-2592-4CA7-A31D-48B717073C77/data/Containers/Data/Application/B6DA59F5-F3AD-4310-B439-F8C5E10F8F0F/Library/Caches/ExponentAsset-c734baf87100d32fc09b7df065428255.jpeg' style='width: 200px; height: 200px; background: red' />
	<img src='http://i.imgur.com/uwrbErh.png' style='width: 200px; height: 200px;' />
</body>
</html>

<script>

</script>
`

<WebView 
    source={{ html: `` }}
    originWhitelist={[ '*' ]}
    javaScriptEnabled={true}
    domStorageEnabled={true}
    allowFileAccess={true}
    allowFileAccessFromFileURLs={true}
    allowUniversalAccessFromFileURLs={true}
    allowingReadAccessToURL='file://' />
```

**Comment by TheAlmightyBob** [comment]
I think you'd want to set it to `/Users/timson/Library/Developer/CoreSimulator/Devices/4FC3A354-2592-4CA7-A31D-48B717073C77/data/Containers/Data/Application/B6DA59F5-F3AD-4310-B439-F8C5E10F8F0F/Library/Caches/`, but I'm not an expert on this

**Comment by hamzaawais96** [comment]
I am facing the same issue. Any update on it?

**Comment by Timson020** [comment]
what's your problem ?
@hamzaawais96

**Comment by Timson020** [comment]
```
const source = Platform.OS === 'ios' ? { uri: 'static.bundle/index.html' } : { uri: 'file:///android_asset/static.bundle/index.html' }
const path = Platform.OS === 'ios' ? '*' : 'file:///android_asset/static.bundle'

<WebView
  ref={webviewRef}
  style={style.container}
  source={source}
  scrollEnabled={false}
  originWhitelist={['*']}
  javaScriptEnabled={true}
  domStorageEnabled={true}
  allowFileAccess={true}
  allowFileAccessFromFileURLs={true}
  allowUniversalAccessFromFileURLs={true}
  allowingReadAccessToURL={path}
```

it is my webview props

you can try it

**Comment by samchencode** [comment]
I am generating my HTML using EJS templates and passing in an html string as the source instead of a file URI for the source file. However, the HTML contains images with src being a file URI. I tried `allowReadAccessToURL` on IOS and it didn't work probably since I'm not using a uri source.

**Comment by samchencode** [comment]
As a workaround, I'm reading the images as base64 and embedding them into the html. I guess another option is to save the HTML and use the file URI as the source to use `allowReadAccessToURL`. Hoping the extra size the b64 takes won't a performance problem.

**Comment by suwu150** [comment]
I am facing the same issue. Any update on it?

**Comment by gaoxiaosong1113** [comment]
I am facing the same issue.

**Comment by ykcho5** [comment]
Same issue.
