### ISSUE TITLE
can not access camera on web view for IOS

### ISSUE THREAD

**Issue by anhvoduy** [react-native-webview/react-native-webview#2055]
I can not access camera on web view for IOS

<img width="966" alt="Screen Shot 2021-06-17 at 12 35 08 AM" src="https://user-images.githubusercontent.com/21326032/122266923-86018f00-cf04-11eb-9d91-9ff8a6f4d942.png">

**Comment by anhvoduy** [comment]
![image](https://user-images.githubusercontent.com/21326032/122908677-9c816d80-d37e-11eb-8121-c03fd113e4d3.png)

Finally it works on my app with simple code like this image

**Comment by gsantiago** [comment]
@anhvoduy did you need to change the Info.plist file?
