### ISSUE TITLE
Scroll position of ScrollView jumps to WebView when pressed (Android)

### ISSUE THREAD

**Issue by mtnptrsn** [react-native-webview/react-native-webview#2057]
**Bug description:**
When pressing a WebView inside a scrollable ScrollView, the scroll position jumps down to the WebView.

**To Reproduce:**
1. Install Expo
2. Clone repo: https://github.com/mtnptrsn/scrollview-webview-bug
3. Run `yarn start` in root
4. Scan QR code with expo
5. Before scrolling, click on the WebView

The first time you press, it will jump down slightly.

**Expected behavior:**
When clicking a WebView inside a ScrollView, it should not change the scroll position of the parent ScrollView.

**Screenshots/Videos:**
https://user-images.githubusercontent.com/684179/122516743-6d31d000-d00f-11eb-9814-7574d23c9bc2.mp4

**Environment:**
 - OS: Android
 - OS version: 11
 - react-native version: 41.0.0
 - react-native-webview version: 11.2.3

**Comment by bashen1** [comment]
same issue

**Comment by drager** [comment]
Yeah, can confirm that this happens for me as well. Even in the latest release of react-native-webview (11.14.0).

**Comment by amirkhanzada-iinv** [comment]
Same issue

**Comment by steffenkleinle** [comment]
Experiencing the same issue, did anyone find a solution? Still present in latest version (12.0.2).
