### ISSUE TITLE
the video can't be played in full screen mode on Android

### ISSUE THREAD

**Issue by wuxiangqi** [react-native-webview/react-native-webview#2059]
**description:**
the video in webpage can't be played in full screen mode on Android, IOS is feasible.

**Environment:**
 - OS:
 - OS version:
 - react-native version:0.63.3
 - react-native-webview version:^10.3.3

**Comment by mtimofiiv** [comment]
Had this same issue. What you're looking for is to add the [`allowsFullscreenVideo` prop](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#allowsfullscreenvideo) to your `WebView`, like so:

```jsx
<WebView
  allowsFullscreenVideo
  source={...}
/>
```

It's an android-only thing, so that's why it worked on iOS.

**Comment by wuxiangqi** [comment]
> 有同样的问题。您正在寻找的是将[`allowsFullscreenVideo`道具](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#allowsfullscreenvideo)添加到您的`WebView`，如下所示：
> 
> ```js
> < WebView  allowedFullscreenVideo  source = { ... }  / >
> ```
> 
> 这是一个仅限 android 的东西，所以这就是它在 iOS 上工作的原因。

It works great for me.
