### ISSUE TITLE
how can i change the language of the webview? 

### ISSUE THREAD

**Issue by AmirDoreh** [react-native-webview/react-native-webview#2061]
we want to load the url through wanted language (we know that the website has support for other languages) , how can we manage to get to that ?

**Comment by Marian0** [comment]
Hi, I'm having this same issue. I wonder if there is any way to pass the user language (locale).

For example if you have a file input is always shown in english on my side:

![image](https://user-images.githubusercontent.com/624592/134500850-2703a919-7d95-476c-90e4-3fc1601cbe96.png)

If you change the device language you will still see this in english but if you load the url of the webview in a normal browser it looks correctly.

**Comment by AmirDoreh** [comment]
i have found its solution .
you need to pass the language as header like:
```
 source={{ uri: ig_uri,headers: {
          "Accept-Language": `${language}`,
        } }}
```

@Marian0

**Comment by kassemitani** [comment]
@AmirDoreh i tried adding the Accept-Language in the headers and didn't work for me. 

@Marian0 did it work for you?

**Comment by AmirDoreh** [comment]
it should work fine if they did not change anything after their update @kassemitani

**Comment by Marian0** [comment]
I've just tested it and it is still not working. Language is always english no matter what I put in `"Accept-Language"`. 
I tested :

- `ES`
- `ES-es`
- `DE`

Btw, only tested on ios and using Expo. I'll do it later on android if I have time with expo and by compiling an APK. 🤔

cc: @AmirDoreh @kassemitani

**Comment by AmirDoreh** [comment]
did you use it as : `es` `en` `tr` ?
@Marian0

**Comment by kassemitani** [comment]
@Marian0 you just need to add to the `Info.plist` the languages supported 

```
<key>CFBundleLocalizations</key>
	<array>
		<string>en</string>
		<string>de</string>
		<string>es</string>
	</array>
```

**Comment by saeid-elio** [comment]
This didn't work for me. I have in my Info.plist:

````
  <key>CFBundleLocalizations</key>
  <array>
    <string>de</string>
  </array>
````

And my phone's default language is German, but still Webview system text is in English!

**Comment by saeid-elio** [comment]
None of the above solutions worked for me. What finally solved the problem on iOS for me was changing the language in `Xcode` > `Localizations` from English to German and marking it as default language. This added following to my `Info.plist` and Xcode updated my `project.pbxproj` accordingly. After that all system text in webview were displayed in correct language.

````
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>

````

**Comment by OscarSith** [comment]
> i have found its solution . you need to pass the language as header like:
> 
> ```
>  source={{ uri: ig_uri,headers: {
>           "Accept-Language": `${language}`,
>         } }}
> ```
> 
> [@Marian0](https://github.com/Marian0)

It works, thanks
