### ISSUE TITLE
> I added in `android/build.gradle`

### ISSUE THREAD

**Issue by malvnewt** [react-native-webview/react-native-webview#2066]
> I added in `android/build.gradle`
> 
> ```
> buildscript {
>     ext {
>         ...
>         kotlinVersion = "1.3.72"
>     }
>     dependencies {
>         ...
>         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
>     }
> }
> ```
> 
> That helped but I waiting guide from maintainers.
> 
> **EDIT FROM MAINTAINER**: this won't be required in versions > 10.1.0, you might want to remove it if you don't wanna risk importing 2 different versions for no reason.
> BTW this was a good workaround, thanks 😄

I used that:

buildscript {
    ext {
        ...
        kotlinVersion = "1.3.72"
    }
    dependencies {
        ...
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
    }
}

and 
react-native install react-native-webview@10.1.0

Thanks a lot @Bardiamist

_Originally posted by @rnmontufar in https://github.com/react-native-webview/react-native-webview/issues/1407#issuecomment-635777143_

**Comment by axeljeremy7** [comment]
which kotlin version this library use ? I am using and declaring kotlin_version = '1.4.10'
