### ISSUE TITLE
React Native WebView missing session cookies on iOS

### ISSUE THREAD

**Issue by aiyuchen** [react-native-webview/react-native-webview#2067]
**Bug description:**
My WebView should display a web page that has a cookie authentication. The page expects a session-id cookie acquired on login. To authenticate I send the login request to the website using fetch().

When the login is successful I can see that proper cookies are received. On success, I'm starting the WebView.

**It works perfectly on Android but not on iOS.**

I tested it on iOS 9 and iOS 11 simulators, and on an iOS 11 device.

To sum up the question: **Why cookies I've got with fetch aren't passed to WebView on iOS only.**

```
<WebView 
    source = {{
        uri: url,
    }}
    onLoadEnd={() => {
        CookieManager.getAll().then((cookies) => {
            console.log('CookieManager.getAll =>', cookies);
        });
    }}
/>

```
<img width="443" alt="wecom-temp-a706fb57dbf1f2cf9a23f28ea1d1fe9e" src="https://user-images.githubusercontent.com/578141/123535171-d5418e00-d754-11eb-8e6c-3a053ed77267.png">

**Environment:**
 - OS:  IOS
 - OS version:   14.4.2
 - react-native version:   0.64
 - react-native-webview version:  ^11.4.3

**Comment by gabrielmirandat** [comment]
I am facing the same problem, works great in android, seems the sid cookie is missing in ios

**Comment by aiyuchen** [comment]
@gabrielmirandat I used `getAllCookies` to get cookies from wkwebview, like this 
https://qastack.cn/programming/33156567/getting-all-cookies-from-wkwebview

```
if (@available(iOS 11.0, *)) {
  [webView.configuration.websiteDataStore.httpCookieStore
      getAllCookies:^(NSArray<NSHTTPCookie *> *_Nonnull cookies) {
        NSURLRequest *request =
            [[NSURLRequest alloc] initWithURL:self.URL]; //your URL
        NSURLSession *session = [NSURLSession sharedSession];
        NSURLSessionDataTask *task = [session
            dataTaskWithRequest:request
              completionHandler:^(NSData *responseData, NSURLResponse *response,
                                  NSError *error) {
                //Do Something
              }];
        [task resume];
        [session.configuration.HTTPCookieStorage storeCookies:cookies forTask:task];
      }];
}
```

**Comment by tkmin** [comment]
@aiyuchen where should I put the codes..? I'm so lost right now, could you help me, please?

**Comment by tkmin** [comment]
I resolved this issue by matching userAgent, hope it would be helpful to someone.

APP_NAME: your app name
`
// at WebView tag
<WebView
  ...
  userAgent={"USER_AGENT" + ` - ${APP_NAME} - iOS`
/>
`

in my case, I used react-native-device-info for USER_AGENT
I set my userAgent with this library + React's useState
`
// somewhere in code
import { useState } from 'react';
import DeviceInfo from 'react-native-device-info';

const [userAgent, setUserAgent] = useState('');
const userAgentSuffix = isAndroid ? ' - APP_NAME - android' : ' - APP_NAME - ios';
DeviceInfo.getUserAgent().then(agent => {
          setUserAgent(agent + userAgentSuffix);
        });
`

and most importantly, in AppDelegate.m, inside **didFinishLaunchingWithOptions**, right before return YES;
I added those code
`
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
...
  NSString *deviceType = [UIDevice currentDevice].model;
  UIWebView *webView = [[UIWebView alloc] initWithFrame:CGRectZero];
  NSString *oldAgent = [webView stringByEvaluatingJavaScriptFromString:@"navigator.userAgent"];
  NSString *newAgent = [oldAgent stringByAppendingString:@" - APP_NAME - ios"];
  newAgent = [newAgent stringByAppendingString:deviceType];
  NSDictionary *dictionnary = [[NSDictionary alloc] initWithObjectsAndKeys:newAgent, @"UserAgent", nil];
  [[NSUserDefaults standardUserDefaults] registerDefaults:dictionnary];

  return YES;
}

`

resources:
https://stackoverflow.com/questions/36590207/set-user-agent-with-webview-with-react-native/51388781
https://stackoverflow.com/questions/49038243/react-native-webview-missing-session-cookies-on-ios

**Comment by caralin3** [comment]
@cgfeel Where/which file do you add that getAllCookies code?
