### ISSUE TITLE
Allow cookies to be cleared

### ISSUE THREAD

**Issue by aliraza-noon** [react-native-webview/react-native-webview#2071]
**Is your feature request related to a problem? If so, Please describe.**

Yes I am doing oauth integration in my app when user logs out from the app I would like to clear the cookies from the webview

**Describe the solutions you came up with**

Allow users to delete cookies

**Additional context**

N/A

**Comment by aliraza-noon** [comment]
not stale

**Comment by aliraza-noon** [comment]
This issue is still there

**Comment by aliraza-noon** [comment]
not stale, please can someone look into it

**Comment by Yarkhan** [comment]
This worked for me. Maybe worth mentioning in the docs somewhere?
```
// as seen in https://stackoverflow.com/a/61825519
const RCTNetworking = require('react-native/Libraries/Network/RCTNetworking')
RCTNetworking.clearCookies(() => { })
```
