### ISSUE TITLE
HLS is not supported using VideoJS in webview

### ISSUE THREAD

**Issue by DevineDecrypter** [react-native-webview/react-native-webview#2075]
**Bug description:**

I'm using webview in a project and in said webview , i use [**VideoJS's CDN**](https://vjs.zencdn.net/7.11.4/video.min.js) to use the `<Video />` .
The goal I'm trying to achieve is playing HLS video`s in webview , and when i give the source of video this type '_application/x-mpegURL_' , it gives the error below :

**The media could not be loaded, either because the server or network failed or because the format is not supported.**

So , I tried checking my network to make sure everything was alright , and it was. then I changed the type to '_video/mp4_' and it started playing !
Then I bumped into another problem which occurred when I tried to use a 720p or 1080p m3u8 link as the video source, the problem here was that I could hear the video playing , but could not see anything ! 

**To Reproduce:**

to reproduce this issue follow these steps:

- start a react-native project using `npx react-native init WebViewTest`
- install react-native-webview using the guide [here](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Getting-Started.md).
- import webview and paste the code below and run it.

`<Webview 
    javaScriptEnabled={true}
    source={{
                html: '
             <!DOCTYPE html>
              <html>
                <head>
                  <meta charset="UTF-8" />
                  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
                  <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
                  />
                  <title>Document</title>
                  <link href="https://vjs.zencdn.net/7.11.4/video-js.css" rel="stylesheet" />
                </head>
                <body style="background-color: transparent">
                    <video
                      id="my-video"
                      class="video-js"
                      preload="auto"
                    ><source src="http://demo.unified-streaming.com/video/tears-of-steel/tears-of-steel.ism/.m3u8" type="application/x-mpegURL"></source></video>
                  <script src="https://vjs.zencdn.net/7.11.4/video.min.js"></script>
                </body>
              </html>  
             ',
              }}
            />`

**Expected behavior:**

A solution to play HLS videos in webview with videojs with no problem .

**Screenshots/Videos:**
![image](https://user-images.githubusercontent.com/19501692/123981743-ba328080-d9d7-11eb-9cc1-320ca3ed19ff.png)

**Environment:**
 - OS: AndroidTV
 - OS version: 10 (API level 29)
 - react-native version: react-native-tvos@^0.63.4-0
 - react-native-webview version: ^11.4.0

**Comment by valeri-terziyski** [comment]
Hey 👋, I also have the same issue. Have you found a solution?

**Comment by Impre-visible** [comment]
Hey, I also have the same issue and I want to know if anyone has found a solution ?
Thanks

**Comment by ArGeoph** [comment]
@DevineDecrypter Not sure if it's useful, but you should be able to enable inline media playback by just adding this prop to WebView: 
`allowsInlineMediaPlayback={true}`
