### ISSUE TITLE
WebView crashes app on Android when clicking a link that attempts to download an image.

### ISSUE THREAD

**Issue by Dor256** [react-native-webview/react-native-webview#2078]
**Bug description:**
I have a `WebView` that at some point presents a link that attempts to download an image.
On iOS everything works fine and the `WebView` redirects to a page where the image is shown, I am able to intercept this with `onShouldStartLoadWithRequest` and push a custom native screen.

However, on Android, the app simply crashes after tapping the link. Also, `onShouldStartLoadWithRequest` is not called on Android and so I am unable to intercept the link to prevent this crash.

When looking at the logs with `adb logcat` I can see the following error:
`java.lang.IllegalArgumentException: Can only download HTTP/HTTPS URIs: data:image/jpeg;base64,/9j/4A...`

Is there any way to work around this and prevent the crash?

**Expected behavior:**
`onShouldStartLoadWithRequest` should be called when clicking links that attempt to download files.

**Environment:**
 - OS: Android
 - OS version: 11.0
 - react-native version: 0.64.0
 - react-native-webview version: 11.0.2 & latest

**Comment by Rajan-Savaliya-spt** [comment]
android webview pdf downalod item app craze and close the app happed: i want to downalod anyfile from the webview in android device any solution for that....

**Comment by remberluyckx** [comment]
Anyone have a solution for this problem?
