### ISSUE TITLE
Configure project :react-native-webview Adding a Configuration as a dependency is a confusing behavior which isn't recommended. This behaviour has been deprecated and is scheduled to be removed in Gradle 8.0.  

### ISSUE THREAD

**Issue by sumeetghimire** [react-native-webview/react-native-webview#2083]
**Bug description:**

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS:
 - OS version:
 - react-native version:
 - react-native-webview version:

**Comment by sumeetghimire** [comment]
I am trying to generate apk in react native build failed when I did gradlew --warning-mode all I got this detail how to solve anyone help me out

**Comment by afizboltz** [comment]
same here .. having same warning .. anyone resolved this ?
