### ISSUE TITLE
webview geolocation permissions prompt

### ISSUE THREAD

**Issue by minwooj123** [react-native-webview/react-native-webview#2086]
Invoking geolocation to a Java script within the URL called to Webview does not prompt for location tolerance
2 permissions set below
AndroidManifest.xml <--- add permissions
geolocationEnabled={true}

**Comment by mirceaciu** [comment]
I can confirm this, I have included in `AndroidManifest.xml `

```
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
```

WebView receives the prop `geolocationEnabled={true}` and the built`react-native` app asks for location access on load.

Websites that are loaded via WebView and use the Geolocation API will not ask for location access by opening the user prompt.

**Comment by KonstantinGreat** [comment]
I use _navigator.geolocation.getCurrentPosition_ in website and get promt in english (iphone settings in russian), its a testflight install. Is it possible to see native language ?

**Comment by KonstantinGreat** [comment]
it was about **CFBundleDevelopmentRegion**
```
"infoPlist": {
        "CFBundleDevelopmentRegion": "ru"
      }
```
dont know about language on prod , may be it will be ok, but now here is no magic thanks god
