### ISSUE TITLE
All videos show as black screen, audio only, on Android

### ISSUE THREAD

**Issue by aneena-thomas** [react-native-webview/react-native-webview#2088]
@Titozzz @dulmandakh  All videos show as black screen, audio only, on Android #290

vesrion: 11.6.2

**Comment by HankinsPan** [comment]
same issues

**Comment by devinsg** [comment]
which android version ? can you copy your code here ?

**Comment by sdserage** [comment]
Can we please get this open? My team is running into the same issue.

**Comment by aguli-moeving** [comment]
I am facing the same issue. The videos play when in full screen but when show a black screen otherwise.

**Comment by heeween** [comment]
<application android:allowBackup="true"
    android:icon="@mipmap/appicon"
    android:label="@string/app_name"
    android:usesCleartextTraffic="true"
    android:hardwareAccelerated="true"
    android:supportsRtl="true"></application>

It is the android:hardwareAccelerated="true" attribute fix the black screen in my side. You can try it.
