### ISSUE TITLE
history.replaceState pushes to history stack instead of replacing

### ISSUE THREAD

**Issue by doylio** [react-native-webview/react-native-webview#2089]
**Bug description:**
The `history.replaceState` method should replace the current position in the history stack without reloading the page.  Instead, it pushes a new entry to the stack.

**Example:**
Initial history state:    `["/", "/foo"]`
Expected result after replaceState:  `["/", "/bar"]`
Actual result after replaceState:   `["/", "/foo", "/bar"]`

**To Reproduce:**
Inside webview, run the following:
1. `window.history.pushState(null, null, "/page1")`
2. `window.history.pushState(null, null, "/page2")`
3. `window.history.replaceState(null, null, "/page3")`
4. `window.history.back()` should return to /page2

**Expected behavior:**
It should replace the current history position with the new url

In the above example, it should return to `/page1`

**Environment:**
 - OS: iOS & Android
 - OS version: iOS 14.4
 - react-native version: ^0.63.4
 - react-native-webview version: ^11.6.4

**Comment by yorickshan** [comment]
same issue
