### ISSUE TITLE
can't use localstorage, The operation is insecure.

### ISSUE THREAD

**Issue by rainst** [react-native-webview/react-native-webview#2093]
**Bug description:**

I am trying to set a variable in a Webview locaLstorage but I keep getting this error: `The operation is insecure.`
**To Reproduce:**

this is how I am using my test Webview:
````
<WebView
  style={{ height: 500, width: "100%", backgroundColor: "blue" }}
  originWhitelist={["*"]}
  sharedCookiesEnabled={true}
  domStorageEnabled={true}
  source={{
    html:'<!DOCTYPE html><html><body>Test</body></html>',
   }}
   injectedJavaScript={`
     try {
        window.ReactNativeWebView.postMessage('init');
        localStorage.setItem('key', 'value');
        window.ReactNativeWebView.postMessage('done');
      }
      catch (e) {
        window.ReactNativeWebView.postMessage('error ' + e.message);
      }
      true;
    `}
    onMessage={(event) => {
      console.log("message from webview", event.nativeEvent.data);
    }}
  />
````
and these are the messages posted back to the native layer:
````
message from webview init
message from webview error The operation is insecure.
````
**Expected behavior:**
I am expectingto see the following messages:
````
message from webview init
message from webview done
````

I have been stuck here for hours, thank you in advance for any suggestion! 

**Environment:**
 - OS: IOS
 - OS version: 14.5
 - react-native version: 0.63.2
 - react-native-webview version: 11.2.3

**Comment by BaLaLaLs** [comment]
I have the same problem

**Comment by linonetwo** [comment]
solution https://github.com/react-native-webview/react-native-webview/issues/1635#issuecomment-1021425071
