### ISSUE TITLE
ms-appdata:// scheme fails on Windows

### ISSUE THREAD

**Issue by tero-paananen** [react-native-webview/react-native-webview#2097]
`ms-appdata://` request uri fails on Windows. Bug is because this change in `void ReactWebViewManager::UpdateProperties` https://github.com/react-native-webview/react-native-webview/commit/d352d147bdffbc4b55196541749363de32a0cc2c#diff-01cdb2f5fdeb0c4347619341b1b4730bbe607ae7fa5c49a8c5922a451a891ae1

I try to fix this. Seems that old call `webView.Navigate(winrt::Uri(to_hstring(uriString)));` can handle `ms-appdata://` scheme.

**Environment:**
 - OS: Windows 10
 - react-native version: 0.62.2
 - react-native-webview version: 11.6.5

**Comment by tero-paananen** [comment]
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview?view=winrt-20348

We should use `WebView.Navigate` method when using `ms-appdata`

**Comment by asklar** [comment]
@tero-paananen looks like the fix is to special case these two prefixes and use the Navigate api in those cases? If so, feel free to send a PR.
CC @chiaramooney fyi.

**Comment by tero-paananen** [comment]
https://github.com/react-native-webview/react-native-webview/pull/2098
