### ISSUE TITLE
Package doesnt compile with react-native-windows

### ISSUE THREAD

**Issue by marcosrdz** [react-native-webview/react-native-webview#2100]
Fails to compile on x64/Debug

<img width="1035" alt="Screen Shot 2021-07-21 at 2 25 00 PM" src="https://user-images.githubusercontent.com/4793122/126540438-b060394e-0d64-4757-86f2-c539a6360b66.png">

**Comment by asklar** [comment]
@marcosrdz can you please clarify what version of react-native-windows you are using, etc?
Please make sure you run autolinking from the command line first: `yarn react-native autolink-windows`, and verify the generated autolinkedNativeModules.g.* files include the webview projects

**Comment by asklar** [comment]
fyi @chiaramooney

**Comment by SurajMDurgad** [comment]
Hey I just cross verified it does add the relative code to `AutolinkedNativeModules.g.cpp`
![Screenshot (2)](https://user-images.githubusercontent.com/13523678/130191904-d67028ab-153b-4431-85b4-5eaad6de21d1.png)

**Comment by SurajMDurgad** [comment]
Cleaning the build are rebuilding helped me resolve this issue, I'm pretty new to windows app developement.
