### ISSUE TITLE
enableApplePay using state

### ISSUE THREAD

**Issue by johannb75** [react-native-webview/react-native-webview#2104]
**Bug description:**
I need to enable Apple Pay for my app. But I still need to inject some JS.
For that, I want to enable Apple Pay only when a specific payment endpoint is reached.
Strangely, when I enable it, nothing changes.

**To Reproduce:**
I have an `applePayEnabled` state which is set to `false` by default and using `onNavigationStateChange` I check the URL and set the state to `true` if it is the payment URL:
```tsx
const [applePayEnabled, setApplePayEnabled] = useState<boolean>(false);

<RNWebView
	source={{ uri: siteUrl }}

	injectedJavaScript={INJECTED_JS}
	onMessage={onWebViewMessage}

        // @ts-expect-error
	enableApplePay={applePayEnabled}
	onNavigationStateChange={({ url }) => {
		// enable apple pay if url contains word "sberbank.ru"
		const isPaymentStep: boolean = url.includes("sberbank.ru");
		setApplePayEnabled(isPaymentStep);
	}}
/>
```

**Expected behavior:**
Apple Pay should be enabled when state changes

**Environment:**
 - react-native-webview version: 11.6.2

**Comment by johannb75** [comment]
Anyone ?

**Comment by antila3567** [comment]
+1
