### ISSUE TITLE
CustomHeaderWebView not working

### ISSUE THREAD

**Issue by jadfls** [react-native-webview/react-native-webview#2108]
**Bug description:**
Tried the example for setting custom headers on subsequent page navigations that is described at https://github.com/react-native-webview/react-native-webview/blob/master/docs/Guide.md#working-with-custom-headers-sessions-and-cookies

It seems to work for example.com. Unfortunately, it does not work for other pages I tried.

**To Reproduce:**
Use the example code from the documentation. Try https://github.com or https://www.google.com
`
const CustomHeaderWebView = (props) => {
  const { uri, onLoadStart, ...restProps } = props;
  const [currentURI, setURI] = useState(props.source.uri);
  const newSource = { ...props.source, uri: currentURI };

  return (
    <WebView
      {...restProps}
      source={newSource}
      onShouldStartLoadWithRequest={(request) => {
        // If we're loading the current URI, allow it to load
        if (request.url === currentURI) return true;
        // We're loading a new URL -- change state first
        setURI(request.url);
        return false;
      }}
    />
  );
};

<CustomHeaderWebView
  source={{
    uri: 'https://github.com',
    headers: {
      'my-custom-header-key': 'my-custom-header-value',
    },
  }}
/>;
`

**Expected behavior:**
Normal working WebView that passes header with every request

**Environment:**
 - OS: iOS
 - OS version: 14
 - react-native version: 0.64.2
 - react-native-webview version: 11.6.5

**Comment by ou2s** [comment]
I think I have the same bug with react-native-webview version 11.13.0.

@jadfls how do you check the headers? Via Safari WebView debugging?

**Comment by jadfls** [comment]
@ou2s yes with Safari WebView debugging. And I also hosted my own website to check headers.

**Comment by rt1909** [comment]
Any update on this issue?

**Comment by zmnv** [comment]
>It seems to work for example.com. Unfortunately, it does not work for other pages I tried.
I have this problem too.

  "react-native-webview": "11.15.0",
  "react-native": "0.67.4",
  "react": "17.0.2",

still searching for solutions

**Comment by zmnv** [comment]
Event onShouldStartLoadWithRequest doesn't fires when you navigating inside SPA (simple React). The same result for Next.js because it uses client side scripts (you can disable it).
