### ISSUE TITLE
injectedJavaScriptBeforeContentLoaded can't pass props to "window"

### ISSUE THREAD

**Issue by Bardiamist** [react-native-webview/react-native-webview#2111]
**Bug description:**
Some users of my app have problems with WebView init.

I noticed that app can't extract prop from "window" on Android 8, 8.1 and 9.0.

I tested and it worked as expected on:
Android 5.0, 6.0, 7.0, 10.0, 11.0

Most strange thing: worked as expected on my ZTE device (Android 8.1).

**To Reproduce:**
You can clone project https://github.com/Bardiamist/injectedjs
And run it in Android 8.0 or 8.1 emulator

**Expected behavior:**
'window.injectedSettings' should be 'Hello' string

**Environment:**
 - OS: Android
 - OS version: 8.0 (and 8.1 and 9.0)
 - react-native version: 0.64.0 (also tried on 0.64.2)
 - react-native-webview version: 11.6.5 (also tried to revert to 11.3.2 but not helped)

**Comment by guodong000** [comment]
Me too...
It looks like only appears in the emulator.
