### ISSUE TITLE
Issue when log in embed facebook and youtube

### ISSUE THREAD

**Issue by trithien98** [react-native-webview/react-native-webview#2115]
**Bug description:**

Hi everyone, I am facing an error related to account login on platforms like facebook and youtube. When I login with youtube and facebook to embedded website from webview link these errors appear . The page loading login to foverer in google platform **"One moment please..."** , and facebook platform is **"Please close this tab"** Hope you guys can help me deal with it
My code is 
`<WebView
          javaScriptEnabled={true}
          originWhitelist={['*']}
          onMessage={(e) => getMessage(e)}
          userAgent="Mozilla/5.0 (Linux; Android 4.1.1; Galaxy Nexus Build/JRO03C) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.166  Safari/535.19"
          useWebKit
          bounces={true}
          allowsInlineMediaPlayback={true}
          mediaPlaybackRequiresUserAction={false}
          source={{
            uri :"https://drrabbittutor.com/",
          }}
          ref={webview}
          style={styles.webView}
          onNavigationStateChange={handleNavigationChange}
          mixedContentMode="always"
          allowsFullscreenVideo={true}
          allowFileAccessFromFileURLs={true}
          allowingReadAccessToURL={true}
          allowsBackForwardNavigationGestures={true}
          allowUniversalAccessFromFileURLs={true}
          domStorageEnabled={true}
          setSupportMultipleWindows={true}
          javaScriptCanOpenWindowsAutomatically={true}
          thirdPartyCookiesEnabled={true}
          allowFileAccess={true}
        />`

**To Reproduce:**

**Expected behavior:**

Expected to user can login facebook and youtube from webview

**Screenshots/Videos:**

![Screenshot_2021-07-29-16-53-05-587_espm bethune shop](https://user-images.githubusercontent.com/59986655/127478283-92e91ff0-588c-4124-a55b-2f3cff47cd41.jpg)
![Screenshot_2021-07-29-17-40-21-934_espm bethune shop](https://user-images.githubusercontent.com/59986655/127478290-9c26e229-acb6-4732-bd78-aee2ab638cb6.jpg)

**Environment:**
 - OS:MacOs
 - OS version:11.2.1 
 - react-native version:0.62.2
 - react-native-webview version:9.0.1

**Comment by rpavlovs** [comment]
Facing same issue with Apple login

**Comment by trithien98** [comment]
I think the problem from login facebook and apple need for each sdk for mobile version, I currently using webview userAgent for web version facebook will know it and block for login, you can change userAgent for mobile version or if not solve issue. I have 2 options for solve this problem, the first is using platform sdk , ex : facebook has lib for react-native sdk is fbsdk, the second if stituation i want in inheriant web version is using lib react-native-inapp-browers. Maybe it for help you
