### ISSUE TITLE
iOS autofill not working 

### ISSUE THREAD

**Issue by khalloud** [react-native-webview/react-native-webview#2117]
**Bug description:** iOS autofill not being triggered in webview. Whenever a form is displayed the standard autofill suggestions for iOS/Safari are not triggered

**To Reproduce:** Open a website and try to log in or fill a form

**Expected behavior:** You get a suggestion in the keyboard "X1123@youremail.com"

**Screenshots/Videos:**
![IMG_B9F6C9537E27-1](https://user-images.githubusercontent.com/9153162/127785913-df078f88-5691-4150-9d7a-31dd96677fb4.jpeg)
<img width="446" alt="Screen Shot 2021-08-02 at 12 32 16 AM" src="https://user-images.githubusercontent.com/9153162/127785926-47000206-ffc1-40be-9b21-01e8b8dda977.png">

**Environment:**
 - OS: iOS
 - OS version: 14.5
 - react-native version: 0.64.0
 - react-native-webview version: 11.3.1

**Comment by pedralho** [comment]
Is it not working at all, or just taking a loooong time to load?
In my case, in some cases, it takes about 30 seconds to open the suggestion list.

Another question: do you get the same results in a regular password field (not in a webview)?

**Comment by khalloud** [comment]
No it never loads at all. It recognizes it's a field and it suggests looking in passwords. But it never autosuggests the specific login username and password for this site. Check out the attached image. 
![IMG_10185DD81656-1](https://user-images.githubusercontent.com/9153162/132756601-45ef4e59-0eae-4e3c-a9d6-2f37817e18ee.jpeg)

**Comment by khalloud** [comment]
And yes outside of webview it does work. As in it autosuggests username XXXX and password YYYY for this app. Tested it on another RN app too.

**Comment by romualdbrisson** [comment]
+1

**Comment by khalloud** [comment]
Did anyone find a solution for this?

**Comment by djibarian** [comment]
Having exactly the same problem.

**Comment by djibarian** [comment]
Solution: https://stackoverflow.com/questions/58530929/how-do-i-turn-on-the-webview-autocomplete-for-an-login-form-in-ionics-capacitor

**Comment by seanleblancicdtech** [comment]
Which solution in that link did you use @djibarian ?

**Comment by djibarian** [comment]
@seanleblancicdtech Setting up the App Site Association.

**Comment by indapublic** [comment]
@djibarian article about ionic. You mean it works for RN too?

**Comment by djibarian** [comment]
@indapublic  Yes I don't use Ionic, only React Native, and it works properly if you set up the App Site Association accordingly.

**Comment by seanleblancicdtech** [comment]
Okay, good to know about App Site Association for iOS. For Android, do similar steps have to be taken? The autofill of user/passwords is not happening there, either.

**Comment by djibarian** [comment]
For Android I didn't do anything special and it worked for me. Perhaps because the Application Id or the Package Name matches the website domain.

**Comment by indapublic** [comment]
Just checked with App Site Association and doesn't work for me. Autofill dialog didn't recognise domain

**Comment by seanleblancicdtech** [comment]
> @indapublic Yes I don't use Ionic, only React Native, and it works properly if you set up the App Site Association accordingly.

Did you have to do steps 7 and 8, and how did you do those in React Native? 

Meaning, these:

>7.  Now you have to open the ios/ folder in XCode. You can do this manually or by using the command npx cap open ios. There you click on App in the left side bar and then again on App under Targets. Then select the Signing & Capabilities tab.
> 8. Add a new Associated Domains Capability and then add the domain applinks:example.com for Deep Link support and webcredentials:example.com for auto-populating passwords. Replace example.com with the domain name of your website.
> Edit: I have also added the Autofill Credential Provider capability.

**Comment by indapublic** [comment]
#2644 #2269 Seems like this feature doesn't work?

**Comment by abz-denys-z** [comment]
Is there a solution today that allows you to use autofill in your own application, without specifying trusted domains?

And judging from [this answer](https://developer.apple.com/forums/thread/723273?answerId=742159022#742159022), there is a solution, but how can it be integrated into the current implementation?
