### ISSUE TITLE
SSL error handler app rejected in google play

### ISSUE THREAD

**Issue by FishDP** [react-native-webview/react-native-webview#2118]
**Bug description:**

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS:
 - OS version:
 - react-native version:
 - react-native-webview version:

**Comment by denisoliveira** [comment]
It's not from `react-native-webview`, a different 3d party aar lib.

### Steps to find de library

- Generate an APK from your project
- Decompile the APK with [apktool](https://ibotpeaches.github.io/Apktool/) 
```bash
apktool d YOUR_APP.apk
```

- Enter in the generated directory
```bash
cd YOUR_APP
```

- Find the handle action
```bash
grep -ri 'Landroid/webkit/SslErrorHandler;->' .
```

- You search for results like:
```smali
invoke-virtual {p2}, Landroid/webkit/SslErrorHandler;->proceed()V  
```

- Identify the project and fix or replace the library
