### ISSUE TITLE
setClientAuthenticationCredential code examples

### ISSUE THREAD

**Issue by philpettican** [react-native-webview/react-native-webview#2130]
Does anyone have any code examples of how to use the **setClientAuthenticationCredential** setter?

Thanks

**Comment by philpettican** [comment]
Still searching for solutions

**Comment by philpettican118** [comment]
Still searching for solutions

**Comment by philpettican118** [comment]
Still searching for solutions

**Comment by hardik-rajpal** [comment]
@philpettican Out of curiosity is @philpettican118  a bot account that replies to this thread every two months?

**Comment by philpettican** [comment]
@hardik-rajpal , no, @philpettican118 is my work account.

**Comment by hardik-rajpal** [comment]
Coolio.
