### ISSUE TITLE
webapp in IOS not showing anything

### ISSUE THREAD

**Issue by edenmeshulam** [react-native-webview/react-native-webview#2133]
**Bug description:**
In IOS, Im trying to show web app like : "https://www.air-dr.com/webapp/#home" ,
Nothing happend, in android everything works.
I saw an error in xcode:
[1425:32597] WF: _userSettingsForUser : (null)
[1425:32597] WF: _WebFilterIsActive returning: NO

**Environment:**
 - OS: IOS
 - OS version: 14.5
 - react-native version: 0.64.1
 - react-native-webview version: latest

**Comment by varunnaagaraj** [comment]
Not entirely sure if its the same issue. I see something similar on iOS 15 and react-native version 0.63.x
And its happening only on iOS. 
I use the react native webview component to load up my log in screen on the Mobile application. With the latest Safari on iOS update in iOS 15, there is a need to make the webview load in a secure context. I use https://<hostname> to load the webview.

But when I try to use window.crypto.subtle.generateKey function, the method throws an exception saying undefined is not an object (evaluating 'a.subtle()[f]')

Is there some way I can load the webview in a secure context other than just having a https session?

Link from Apple team: https://trac.webkit.org/changeset/279628/webkit

**Comment by timboektoe** [comment]
I loaded https://www.air-dr.com/webapp/#home in my safari browser on laptop and received a notification that the page wants to access my location. Not sure whether these kind of features are well enough supported in WebView. I noticed that a simple alert('hello world') can crash the WebView.

**Comment by timboektoe** [comment]
> window.crypto.subtle

Did you check also with:
https://developer.mozilla.org/en-US/docs/Web/API/Window/isSecureContext

**Comment by edenmeshulam** [comment]
SOLVED:
after i add this to info.plist:
`	<key>NSCameraUsageDescription</key>
	<string>Take pictures for certain activities</string>
	<key>NSPhotoLibraryUsageDescription</key>
  	<string>Select pictures for certain activities</string>
	<key>NSMicrophoneUsageDescription</key>
    <string>Need microphone access for recording videos</string>`
problem solved

**Comment by erisvaldojunior** [comment]
Same here for a brand new project (iOS 14.5, RN 0.65.1). Adding those permissions on info.plist don't help.

**Comment by parthkanani93** [comment]
> SOLVED:
> after i add this to info.plist:
> ` <key>NSCameraUsageDescription</key> <string>Take pictures for certain activities</string> <key>NSPhotoLibraryUsageDescription</key> <string>Select pictures for certain activities</string> <key>NSMicrophoneUsageDescription</key> <string>Need microphone access for recording videos</string>`
> problem solved

I tried but it does not work.
