### ISSUE TITLE
getUserMedia error first time without asking permission

### ISSUE THREAD

**Issue by mubasharrasheed** [react-native-webview/react-native-webview#2138]
**Bug description:**
At the app start, I ask for permissions for the camera and those permission does save in the setting and I can access the camera through the picture capture plugin. Meanwhile, within the same session when I try to access the webView it throws an error of permission not granted by getUserMedia. Although once you kill the app and come back to that page again, everything works as expected. That's the issue with the first time only that after getting permission you need to kill the app to make camera permission work in web view. The issue on IOS, android seems fine. 

So may be WebView not syncing permissions of the app in real-time? And get that once the app is restarted.

**To Reproduce:**
Get IOS camera permission from react-native-permission and after the permissions load web view without killing the app.

**Expected behavior:**
It should work first time same as when we restart the app forcefully.

**Comment by mubasharrasheed** [comment]
@imownbey @alloy @tijs @bryanstearns  guys I have a pending delivery due to this little issue. Can you please take a look and fix?

**Comment by mubasharrasheed** [comment]
@DiogoAlexandro did any solution worked for you?

**Comment by DiogoAlexandro** [comment]
Hi, the any solution that i got was put one view that appears on the first open of the app, like a welcome message, so the request permissions appears and on the next opens the request and the view dont appears.

**Comment by mubasharrasheed** [comment]
yeah I did the same @DiogoAlexandro , but strange there is no real solution for this

**Comment by mubasharrasheed** [comment]
Still searching for the solution

**Comment by mubasharrasheed** [comment]
Still searching for the solution

**Comment by mubasharrasheed** [comment]
Still searching for the solution
