### ISSUE TITLE
Is there a way to detect when cookies are changed

### ISSUE THREAD

**Issue by billypon** [react-native-webview/react-native-webview#2141]
I use react-native-cookies with react-native-webview, now I can get cookies at any time.
But I don't know when cookies are changed.

**Is your feature request related to a problem? If so, Please describe.**

I need to know when cookies are changed, because I have someting to do.

**Describe the solutions you came up with**

Add a cookie update event, tell me which url/cookie is changed.
Or add a response event, so that I can get response headers.

**Additional context**

**Comment by billypon** [comment]
still searching for solutions

**Comment by ScreamZ** [comment]
@billypon Did you find any ?
