### ISSUE TITLE
remove usages of jcenter()

### ISSUE THREAD

**Issue by dlwo159** [react-native-webview/react-native-webview#2142]
WARNING:: Please remove usages of jcenter() Maven repository from your build scripts and migrate your build to other Maven repositories.
This repository is deprecated and it will be shut down in the future.
See http://developer.android.com/r/tools/jcenter-end-of-service for more information.
Currently detected usages in: project ':react-native-webview'

**Comment by Bibazavr** [comment]
@Titozzz , this is important - jcenter shut down soon

![image](https://user-images.githubusercontent.com/51177449/134893379-0d2ab3a4-946e-4b77-8065-4d486a932cf5.png)

**Comment by Titozzz** [comment]
Please create a PR and @ me there

**Comment by Bibazavr** [comment]
i guess this issue may closed after new release?
