### ISSUE TITLE
在react-native-toast-hybrid中使用webview时发现，第二次路由进入页面webview无法正常工作

### ISSUE THREAD

**Issue by weijintao92** [react-native-webview/react-native-webview#2143]
我初步诊断得出的结论是，第一次退出后，webView会跟着页面被销毁。  第二次，进去的时候，webView还没有销毁完。   我就又要让它干活  。

**Comment by sunzhongliangde** [comment]
没碰到过，可以描述一下具体的使用场景吗，以及webview的哪些功能无法正常工作
