### ISSUE TITLE
react-native-windows has been ignored because it contains invalid configuration

### ISSUE THREAD

**Issue by mdehghani65** [react-native-webview/react-native-webview#2146]
after adding react-native-webview to a fresh react-native and react-native-windows project and running npx react-native run-windows I recieve the following warning:

warn Package react-native-windows has been ignored because it contains invalid configuration. Reason: Cannot find module '@react-native-community/cli/package.json'
Require stack:
- C:\dad65\dadhesab\node_modules\@react-native-windows\cli\lib-commonjs\healthChecks.js
- C:\dad65\dadhesab\node_modules\@react-native-windows\cli\lib-commonjs\index.js
- C:\dad65\dadhesab\node_modules\react-native-windows\react-native.config.js
- C:\dad65\dadhesab\node_modules\cosmiconfig\node_modules\import-fresh\index.js
- C:\dad65\dadhesab\node_modules\cosmiconfig\dist\loaders.js
- C:\dad65\dadhesab\node_modules\cosmiconfig\dist\index.js
- C:\dad65\dadhesab\node_modules\react-native\node_modules\@react-native-community\cli\build\tools\config\index.js
- C:\dad65\dadhesab\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\install\install.js
- C:\dad65\dadhesab\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\index.js
- C:\dad65\dadhesab\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js
- C:\dad65\dadhesab\node_modules\react-native\cli.js
info Run "react-native --help" to see a list of all available commands.

**Environment:**
 - OS:Edition Windows 10 Pro
Version 20H2
Installed on ‎5/‎23/‎2021
OS build 19042.1165
Experience Windows Feature Experience Pack 120.2212.3530.0

 - react-native version: 0.65
 - react-native windows version: 0.65
 - react-native-webview version: 11.13

I tried removing node_modules folder and package-json.lock and npm install but no luck

**Comment by chrisglein** [comment]
There's the react-native-windows CLI and the community CLI, and the former depends on the latter. But based on the error that may not be happening correctly?

Given the path (`react-native\node_modules@react-native-community\cli`) it looks like it wasn't hoisted up to be a shared dependency. What version is that CLI?

Can you capture this extra environment information?
1. `npx react-native --version`:
2. `npx react-native info`:

Do you have a repo captured that demonstrates this?

**Comment by mdehghani65** [comment]
> There's the react-native-windows CLI and the community CLI, and the former depends on the latter. But based on the error that may not be happening correctly?
> 
> Given the path (`react-native\node_modules@react-native-community\cli`) it looks like it wasn't hoisted up to be a shared dependency. What version is that CLI?
> 
> Can you capture this extra environment information?
> 
> 1. `npx react-native --version`:
> 2. `npx react-native info`:
> 
> Do you have a repo captured that demonstrates this?

I dont have a repo unfortunately. this is the output of the commands above:
1. 6.0.0
2. info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 AMD A10-5800K APU with Radeon(tm) HD Graphics
    Memory: 2.80 GB / 7.20 GB
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Version  3.0.0.0 AI-171.4443003
    Visual Studio: 16.9.31205.134 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.65.0 => 0.65.0
    react-native-windows: 0.65.1 => 0.65.1
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by chrisglein** [comment]
react-native-windows appears to define the core CLI as a dev dependency, not a real dependency. That sounds familiar - I'm trying to find an issue on that repo. We may not be seeing this because yarn might be covering it up (looks like you have yarn but aren't using it for this, which might be the difference).

**Comment by mdehghani65** [comment]
> react-native-windows appears to define the core CLI as a dev dependency, not a real dependency. That sounds familiar - I'm trying to find an issue on that repo. We may not be seeing this because yarn might be covering it up (looks like you have yarn but aren't using it for this, which might be the difference).

yes, I always use npm instead of yarn

**Comment by chiaramooney** [comment]
@mdehghani65 Are you still hitting this issue? A couple of follow-up questions: 
- Was the RNW app building successfully before you added the react-native-webview project?
- Did you add the react-native-webview dependency via `yarn add` or another method?

**Comment by mdehghani65** [comment]
> @mdehghani65 Are you still hitting this issue? A couple of follow-up questions:
> 
> * Was the RNW app building successfully before you added the react-native-webview project?
> * Did you add the react-native-webview dependency via `yarn add` or another method?

I have not experimented again yet. I will do so in the following few months , when I will prepare an new update for my app.
yes the RNW app is successfuly building before adding react-native-webview project.
I don't use yarn . I always use npm instead.

**Comment by chiaramooney** [comment]
Ok just tried to repro and was successfully able to build an app. Here were my steps:

1. npx react-native init test --template react-native@^0.65.0
2. cd test
3. npx react-native-windows-init --overwrite
4. npm i react-native-webview --save
5. npx react-native run-windows

Closing issue for now, but if when you try again you run into issues let us know.
