### ISSUE TITLE
Unable to use custom CA with WebView on Android simulator 

### ISSUE THREAD

**Issue by mav2287** [react-native-webview/react-native-webview#2147]
**Bug description:**
In our testing environment we use certs we sign with our own CA certificate. I was able to successfully install our CA cert on iOS and visit pages in the react native WebView without issue. On the Android Emulator I still get an error even after installing the customer CA. I know it is working and installed, because Chrome uses the CA and honors it, but when attempting to visit the page through the WebView I get the following: 
```
Error loading page
Domain: undefined
Error Code: 3
Description: SSL error: The certificate authority is not trusted
```

**To Reproduce:**
Setup a simple app with a WebView, open the app and point the WebView at a page with a ssl cert signed with the custom CA cert.

**Expected behavior:**
The custom CA should be used and the error should not appear.

**Environment:**
 - OS: macOS
 - OS version: 11.5.2
 - react-native version: 17.0.2
 - react-native-webview version: 11.13.0
- Android emulator info:  sdk_gphone_x86-userdebug 10 QSR1.210802.001 7603624 dev-keys

**Comment by mav2287** [comment]
Still running into this issue. Is anyone dealing with it as well?

**Comment by neroneroffy** [comment]
I solve this issue by edit the RNCWebVIewManager.java. Go to `node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java`

* find `onReceivedSslError` method
* change `handler.cancel()` to `handler.proceed()`;

then rebuild your app，the SSL error still exist, but you can access the site

**Comment by mav2287** [comment]
That's would allow for testing, but if does address the fact that if a CA has been added there shouldn't be an error thrown when accessing urls signed with that CA.

**Comment by cyberphone** [comment]
This may be the "right" solution:
https://developer.android.com/training/articles/security-config

**Comment by cyberphone** [comment]
It actually works but it is pretty quirky since react doesn't compile without a `cleartextTrafficPermitted` attribute as well.

I did certainly not find it myself: https://stackoverflow.com/questions/60328951/react-native-android-does-not-build-when-i-add-networksecurityconfig-tag

```xml
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
  <base-config cleartextTrafficPermitted="true">
    <trust-anchors>
       <certificates src="system"/>
       <certificates src="user"/>
    </trust-anchors>
  </base-config>
</network-security-config>
```

I would consider adding a network-security-config to the default "init" process.

**Comment by SrBrahma** [comment]
I have a question maybe not exactly about it, but I can't find people to help me:

I am using a Payment Gateway. In client, I only need to tokenize() the user credit card info then send it to my server. It requires that I use HTTPS+SSL, so I am using Firebase Hosting to host the the page, as it has both requirements by default. I use WebView, as the tokenize() is in a <script/> tag. Inside this js script, it makes a call to their server with the user credit card and returns the token. I then return the token to RN with `window.ReactNativeWebView.postMessage`.

Does it is all I need to keep it safe? Or I would need to use install SSL in my app / ssl-pinning somehow?

**Comment by cyberphone** [comment]
The HTTPS support in WebView is fine.  I don't fully understand the flow here.  Doesn't the payment gateway need authentication as well?

**Comment by SrBrahma** [comment]
> The HTTPS support in WebView is fine. I don't fully understand the flow here. Doesn't the payment gateway need authentication as well?

It only needs my Public Token to tokenize the card. The user x tokenized card association and then the payment will then be done in my server.

Well, I just tested using the prod token on the Firebase deployed html (on localhost didn't work as I expected, it complained about not being https/ssl) with a test card and it worked, returned the tokenized test card.

That's all? Already secure? I am still afraid that I may be missing something.


For some reason, the warn on catch is being raised when the site is on the WebView:

(unminified gateway client code)

```js
try {
    const { advancedFraudPrevention: e } = Ct(this, St);
    if (!e) return Promise.resolve();
    const t = await (async () => {
        try {
            const e = await L.fetch("/devices/widgets", { method: "POST", body: JSON.stringify({ section: "open_platform_V2", view: "checkout" }) }),
                t = await e.json(),
                n = document.createElement("script");
            return n.appendChild(document.createTextNode(t.widget.replace(/<script\b[^<]*">/gi, "").replace(/<\/script>[\s\S]*/gi, ""))), document.head.appendChild(n), Promise.resolve(t.session_id);
        } catch (e) {
            return Promise.reject(e);
        }
    })();
    return r.i.setDeviceProfile(t), Promise.resolve();
} catch (e) {
    return console.warn("DeviceProfile could not be loaded", e), Promise.resolve();
}
```

I ain't quite sure why the error is being raised and if it's vital for me. But well, it's about advancedFraudPrevention, so must be. But I don't think this related to HTML+SSL but to another WebView thing.

**Comment by mav2287** [comment]
This does not relate to this issue and should be opened as a new issue.

**Comment by noSweatSuperDry** [comment]
> I solve this issue by edit the RNCWebVIewManager.java. Go to `node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java`
> 
> * find `onReceivedSslError` method
> * change `handler.cancel()` to `handler.proceed()`;
> 
> then rebuild your app，the SSL error still exist, but you can access the site

In v 13.6.3, To make this change you have to go node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewClient.java.

**Comment by mrzslr** [comment]
> I solve this issue by edit the RNCWebVIewManager.java. Go to `node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java`
> 
> * find `onReceivedSslError` method
> * change `handler.cancel()` to `handler.proceed()`;
> 
> then rebuild your app，the SSL error still exist, but you can access the site

any solution for iOS?

**Comment by TSB1999** [comment]
@mav2287 Hi - How were you able to install the CA Cert on ios?

**Comment by mav2287** [comment]
> @mav2287 Hi - How were you able to install the CA Cert on ios? 

You have to download the public CA cert and install it as trusted on the machine. This blog post on my website explains the whole process https://www.mytechylife.com/2020/06/26/getting-chrome-to-recognize-a-self-signed-certificate/

**Comment by nnWhisperer** [comment]
@mav2287 just downloading and installing it as trusted on the machine doesn't work in android. It seems like it doesn't recognize the SSL certificates registered to the system.
