### ISSUE TITLE
onFileDownload not firing on iOS

### ISSUE THREAD

**Issue by hklee93** [react-native-webview/react-native-webview#2152]
**Bug description:**
As per #1214, I'm setting `Content-Disposition: 'attachment'` in the header from the server side, but when I try to download the image file, it gets rendered rather than firing onFileDownload callback. Looks like if I try to download from this page (https://pixabay.com/photos/sea-sunset-outdoors-dusk-ocean-6543041/) it works fine, but doesn't work if I try to serve the file myself. Not sure what I'm missing. 

**To Reproduce:**
On the frontend, I'm trying to download an image file
```
<a href="http://localhost:8000/download" download>Download</a>
```
And on the backend, sending an image file with header setup
```
app.get('/download', async (req, res) => {
  const file = `${__dirname}/logo192.png`;
  res.set({'Content-Type': 'image/png', 'Content-Disposition': 'attachment'});
  res.download(file);
})
```

**Expected behavior:**
`onFileDownload` should be fired instead of rendering the image directly on the view

**Environment:**
 - OS: iOS 
 - OS version: 13.4
 - react-native version: 0.62.1
 - react-native-webview version: 11.4.2

**Comment by zabojad** [comment]
@hklee93 I'm having the same issue... How did you solve it?
