### ISSUE TITLE
Any hack/option to bypass CORS?

### ISSUE THREAD

**Issue by cristianoccazinsp** [react-native-webview/react-native-webview#2155]
**Is your feature request related to a problem? If so, Please describe.**

We are trying to implement a MotionJPEG viewer, and so far using a WebView was the easiest option.  However, the camera that streams MotionJPEG requires a POST request; therefore, it falls into CORS validation, and it of course does not return CORS headers.

I wonder if anyone has explored any implementation to have the webview ignore CORS checks, or at least intercept responses to add CORS headers.

**Describe the solutions you came up with**

For Android, response interceptors do seem possible. But I couldn't find anything for iOS.

**Additional context**

**Comment by DominicTobias** [comment]
Browsers provide a way when starting, it would be ideal if webview did too. React native itself does not check CORS so it's more in line with native behaviour too
