### ISSUE TITLE
addEventListener inside of WebView do not work

### ISSUE THREAD

**Issue by AlacranBlanco** [react-native-webview/react-native-webview#2161]
**Bug description:**

Hello

Apparently the WebView doesn't recognize the "EventListener" that take place inside of it, what I want to do is to get the selected text once the user has finished selecting it, I'm trying to do it with a "touchend" event. 

I can get the text as long as I tap/touch the WebView but not when I am selecting it

My code: 

` contents.window.addEventListener("touchend", function(e){
            let selectedText = e.view.window.getSelection().toString();
            alert(selectedText)
          e.preventDefault();
      });`

**To Reproduce:**

- Selecting text

**Expected behavior:**

- Get the selected text once the user has finished

**Screenshots/Videos:**

![WhatsApp Image 2021-09-17 at 1 44 11 AM](https://user-images.githubusercontent.com/51062435/133739639-d904bd95-2bb0-4dfd-93cb-8ef140172336.jpeg)

**Environment:**
 - OS: -
 - OS version: -
 - react-native version: "16.13.1"
 - react-native-webview version: "11.13.0"

**I appreciate any help. Thank you**

**Comment by Ak10990** [comment]
What is the fix done here for Android ? @AlacranBlanco

**Comment by jhon-hst** [comment]
1+

**Comment by rawatnaresh** [comment]
@AlacranBlanco Did you find any solutions?

**Comment by kravchenko-anton** [comment]
1+
