### ISSUE TITLE
print not working on mobile (android)

### ISSUE THREAD

**Issue by regoughicham** [react-native-webview/react-native-webview#2162]
**Bug description:**

Hello

I did the build for the android mobile version (apk) using react native webview and I noticed that the print does not work, when I launch the print nothing happens. 

**To Reproduce:**
Try to print a document on android app (webview android app)

**Expected behavior:**
Get the mobile print.

**Environment:**
 - OS:
 - OS version:
 - react-native version: 16.13.1
 - react-native-webview version: 11.13.0

**Comment by saqibkafeel** [comment]
why this issue is closed still not resolved
