### ISSUE TITLE
injectJavascript or InjectedJavascript not working. 

### ISSUE THREAD

**Issue by Rabi27** [react-native-webview/react-native-webview#2163]
**Bug description:**

**Expected behavior:**

**Environment:**
 - OS: Linux Mint
 - OS version: 20
 - react-native version:0.65.1
 - react-native-webview version:^11.13.0

**Comment by AxayDixit** [comment]
Same here. It was working fine till last Thursday. Suddenly it isn't. Strange behaviour.

**Comment by mishkeTz** [comment]
Does't work on macOS Big Sur
Version: 11.5.2

**Comment by AxayDixit** [comment]
@mishkeTz I'm trying on android. My react native & webview version is also the same.

**Comment by mishkeTz** [comment]
At the end passing onMessage prop to the component solved the problem. I don't know if and why it would be required.
`onMessage={(event) => {}}`

**Comment by AxayDixit** [comment]
> At the end passing onMessage prop to the component solved the problem. I don't know if and why it would be required.
> `onMessage={(event) => {}}`
> 
> Full code example:
> `<WebView ref={webViewRef} source={{ uri }} injectedJavaScript={injectedJavaScript} javaScriptEnabled={true} domStorageEnabled={true} sharedCookiesEnabled={true} originWhitelist={['*']} onMessage={(event) => { console.log('On message: ', event); }} />`

Hey I have all these props set. The problem with my code was I was loading some other data in onLoad() function of the webview. I tried commenting the code and everything is working fine. I still wonder how it was working for all these days. Anyway, thanks for the replies!!

**Comment by Rabi27** [comment]
My code for webview. InjectedJavascript nor InjectJavascript tends to work. Is there something I'm doing wrong?
`const WebViewElement = ({ url }) => {
  const webviewRef = useRef(null);
  const INJECTED_JAVASCRIPT = `(function() {
      document.getElementByClassName("Topbar_container__1oZu7")[0].style.display = "none";
      const meta = document.createElement('meta');
      meta.setAttribute('content', 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no');
      meta.setAttribute('name', 'viewport');
      document.getElementsByTagName('head')[0].appendChild(meta);
      true;
    })();`;

  return (
    <SafeAreaView style={styles.flexContainer}>
      <WebView
        source={{ uri: url }}
        style={{ flex: 1 }}
        ref={webviewRef}
        userAgent="Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; AS; rv:11.0) like Gecko"
        injectedJavaScript={INJECTED_JAVASCRIPT}
        javaScriptEnabled={true}
        domStorageEnabled={true}
        renderLoading={ActivityIndicatorElement}
        startInLoadingState={true}
        sharedCookiesEnabled={true}
        onMessage={(event) => {
          console.log("On message: ", event);
        }}
      />
    </SafeAreaView>
  );
};
`

**Comment by coolswood** [comment]
The same problem only on IOS 15
