### ISSUE TITLE
On Android, the 'incognito' prop for react-native-webview does not work.

### ISSUE THREAD

**Issue by gt-hub** [react-native-webview/react-native-webview#2167]
On iOS, the 'incognito' property works flawlessly, however it does not appear to operate on Android. Our expectation is for WebView to not store any data . Can you let me know if I'm missing anything here.

**Our usage:**  
```
<WebView
            cacheEnabled={false}
            source={{uri: sourceUrl}}
            onNavigationStateChange={this.onNavigationStateChange}
            incognito={true}
/>
```

**Comment by unknownFrequency** [comment]
+1

**Comment by tomtargosz** [comment]
Seeing the same issue as well

**Comment by nathanwkwong** [comment]
I had the same situation mentioned above for android. I added another 3 props to the WebView component: thirdPartyCookiesEnabled, domStorageEnabled and geolocationEnabled with all false, then there is no cached data now after reopening the webview on android.

**Comment by BadrBelhiti** [comment]
Same issue for Android while using `incognite={true}` when expecting **Local Storage** to be empty. Apparently, you have to use `domStorageEnabled={false}` for Local Storage.

**Comment by NekyaDev** [comment]
> Same issue for Android while using `incognite={true}` when expecting **Local Storage** to be empty. Apparently, you have to use `domStorageEnabled={false}` for Local Storage.

Thank you very much **domStorageEnabled={false}**, worked perfectly!
