### ISSUE TITLE
Opening pkpass file shows raw content

### ISSUE THREAD

**Issue by stephan-la** [react-native-webview/react-native-webview#2168]
**Bug description:**
When I open a pkpass file in a webview, I receive the raw file content instead of having it opened like if I am accessing the url in the browser. Did I miss anything?

**To Reproduce:**
Just add a webview and navigate to an pkpass file (mine has no .pkpass ending, its a dynamic url)

<WebView
        source={{ uri: 'URLHERE }}
        style={{}}
        allowUniversalAccessFromFileURLs={true}
        javaScriptEnabled={true}
        mixedContentMode={'always'}
      />

**Expected behavior:**
Open the pkpass dialog for adding it into the wallet.

**Environment:**
 RN 60.5

**Comment by andystanley** [comment]
Has anyone found a workaround for this? Running into the same issue

**Comment by ljorgens** [comment]
Im getting a similar issue, specifically with Ticketmaster Add To Wallet Function

**Comment by guiled** [comment]
Any info about it ?

**Comment by ianjamieson** [comment]
One simple way to do it is to force your links to open outside of the webview and then it means that Safari will handle opening the `.pkpass` file.

Some snippets from my code


```javascript
import * as WebBrowser from "expo-web-browser";
const onShouldStartLoadWithRequest = useCallback(
    (request: ShouldStartLoadRequest) => {
      if (shouldOpenInExternalBrowser(request.url)) {
        void WebBrowser.openBrowserAsync(request.url);
        return false;
      }
      return true;
    },
    [handleCrossTabLink]
  );
```

```jsx
<BaseWebView
        ...
        onShouldStartLoadWithRequest={onShouldStartLoadWithRequest}
        ...
```


```javascript
const isPkpassUrl = (pathname: string): boolean =>
  pathname.toLowerCase().endsWith(".pkpass");

export const shouldOpenInExternalBrowser = (url: string): boolean => {
  const raw = url.trim();

  if (!raw || !isHttpUrl(raw)) {
    return false;
  }

  let parsed: URL;
  try {
    parsed = new URL(raw);
  } catch {
    return false;
  }

  const { host, pathname = "/" } = parsed;

  if (isPkpassUrl(pathname)) {
    return true;
  }
};
```
