### ISSUE TITLE
iOS 15 - Webview slower and crashes when using canvas

### ISSUE THREAD

**Issue by cristianoccazinsp** [react-native-webview/react-native-webview#2169]
**Bug description:**

Following the iOS 15 update, all my webviews that use a canvas to render stuff (possibly large stuff) became extremely inefficient and slow.

Basically, what used to work very smoothly with 60fps, out of a sudden lags a lot, and even trying to render large canvas objects ends up in a "Webview Process Terminated" warn from this library.

Here's a report about bad performance as well with iOS 15, perhaps we will need to add a new iOS flag to handle this: https://developer.apple.com/forums/thread/684843

Furthermore, I would like to propose that the `"Webview Process Terminated"` warning is removed from the native side if a handler was defined.

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS: iOS
 - OS version: 15.0
 - react-native version: 0.65.1
 - react-native-webview version: 11.13.0

**Comment by gilsonviana-modus** [comment]
I'm also experiencing this issue.

**Comment by zainwebhr** [comment]
Same issue.

**Comment by cristianoccazinsp** [comment]
Any updates with this? I've been trying to find info on various apple sites, but nothing.

**Comment by einestadtgbr** [comment]
have same problem... :-(

**Comment by maddy10s** [comment]
any update on this?

**Comment by tongjinfeng** [comment]
have same problem， Is there any better way to solve it besides reload webview again

**Comment by jbibbo** [comment]
We too are experiencing significant performance degradation when our canvas-based,  react-native app is running on ios15.

Environment:

OS: iOS
OS version: 15.1
react-native version: 0.66.4
react-native-webview version: 11.17.0

**Comment by einestadtgbr** [comment]
Did you already check that https://github.com/openlayers/openlayers/issues/12908#issuecomment-1023572875 ?

**Comment by einestadtgbr** [comment]
We are still searching for a solution for that...

**Comment by pseudonem** [comment]
We are still searching for solutions!

**Comment by eldonaldo** [comment]
Is there any update on this?

**Comment by davidtom** [comment]
Joining in. Seems like we're experiencing this issue using PDF.js in a Webview. Any updates would be appreciated.

**Comment by bbminhtri** [comment]
Can we reopen this issue? Still having it with iOS 16 and PixiJS's Tilemap

**Comment by mvn-cuongle-dn** [comment]
I facing this issue while draw canvas on Webview, any solution for this one ?

**Comment by chelssw** [comment]
Still facing issues with this ticket, is there a resolution?
