### ISSUE TITLE
IOS webview is not caching website

### ISSUE THREAD

**Issue by qasim-appiskey** [react-native-webview/react-native-webview#2170]
**Bug description:**
I am using react native webview to display a pwa site. On android once the page is loaded I can turn off the internet and restart the app and it will work without internet. But on ios if turn off the internet I get no internet error from webview.

**To Reproduce:**
```js
import React from 'react';
import {WebView} from 'react-native-webview';

const CSS =
  'img.ng-tns-c7-0,mf-locale-selector,mf-sharing-fab,.mat-focus-indicator.mat-icon-button.mat-button-base,mf-cookie-consent-bar{display: none !important;}';

  const INJECTED_JAVASCRIPT = `
(function() {
  const style = document.createElement('style');
  style.type = 'text/css';
  style.innerHTML = '${CSS}';
  document.head.appendChild(style);
})();
true;`;

export default function App() {
  return (
    <WebView
      useWebKit
      originWhitelist={['*']}
      bounces={false}
      source={{uri: 'https://qiblafinder.withgoogle.com/'}}
      geolocationEnabled={true}
      allowsInlineMediaPlayback={true}
      mediaPlaybackRequiresUserAction={false}
      injectedJavaScript={INJECTED_JAVASCRIPT}
      onMessage={() => {}}
      cacheEnabled={true}
      cacheMode={'LOAD_CACHE_ELSE_NETWORK'}
      sharedCookiesEnabled={true}
      pullToRefreshEnabled={true}
      setBuiltInZoomControls={false}
    />
  );
}
```

**Expected behavior:**
Once the page is loaded in webview it should not require internet to load again. It should load from cache. I check in Safari and it is working as expected in Safari without internet.

**Screenshots/Videos:**
**Without Internet**
![IMG_0011](https://user-images.githubusercontent.com/89781650/134418329-517b20fb-9a7a-4781-bb49-02bc7bbf1aa6.PNG)

**Environment:**
 - OS: ios
 - OS version: 14.7.1
 - react-native version: 0.64.2
 - react-native-webview version: 10.10.2

**Comment by tomekponiatowicz** [comment]
@jamonholmgren Hi, is there any ETA for that fix?

**Comment by tomekponiatowicz** [comment]
@Titozzz @jamonholmgren Are there any updates on this issue?

**Comment by yaroslavnikiforov** [comment]
I have the same issue on iOS. Page loading time is always the same on iOS. On android seems that cache works, as when you open the page next time it loads much faster.

**Comment by teteeee** [comment]
I have the same issue. Android is work well but iOS is not working.
`react-native-webview@11.6.2`

**Comment by glrahulborah** [comment]
Got the same issue with `"react-native-webview": "^10.10.2"`. Caching works fine on Android but iOS always fetches it from the network.

**Comment by kitolog** [comment]
https://github.com/react-native-webview/react-native-webview/issues/869#issuecomment-1172404246
