### ISSUE TITLE
System dialogs are shown in wrong language (locale)

### ISSUE THREAD

**Issue by Marian0** [react-native-webview/react-native-webview#2171]
I have an image uploader on a website, if you access it using a normal browser the language on the system dialog upload UI is shown in the users's language but if you try the same using `react-native-webview` it is always shown in english.

![image](https://user-images.githubusercontent.com/624592/134502294-b34546b0-3888-45f6-b715-c71d23b1e8cb.png)

I didn't found in the documentation something to pass the users' language and I've also seen some other related issues:

https://github.com/react-native-webview/react-native-webview/issues/2061
https://github.com/react-native-webview/react-native-webview/issues/1458
https://github.com/react-native-webview/react-native-webview/issues/1772

Any thoughts ? 

Thank you!

**Comment by kassemitani** [comment]
@Marian0 @Cosmitar you just need to add to the `Info.plist` the languages supported 

```
<key>CFBundleLocalizations</key>
	<array>
		<string>en</string>
		<string>de</string>
		<string>es</string>
	</array>
```

**Comment by quitran97** [comment]
@Marian0 Do you have any solution for this? I got the same issue with the webview and file input type too. I changed device language but it was still showing English.

**Comment by saeid-elio** [comment]
Same for me, permission dialogs are always in English!
