### ISSUE TITLE
SSL Error Handler 

### ISSUE THREAD

**Issue by Pandit2903** [react-native-webview/react-native-webview#2174]
i am facing Rejection while uploading app on Google Play Store due to SSL Error Handler
<html>
<body>
<p style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Hello Google Play Developer,</p><p style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">We rejected <b>WebExample</b>, with package name <b>com.webexample</b>, for violating our<span> </span><a href="https://notifications.google.com/g/p/AD-FnEwARvbWJw6zi6_QUP9ZBXQgJF4PbMY6qtMfpkoeUbOqKVx8dk2MZzWlaktIDtRCM6orJdp-VCEGAguI8EVzNp_sR6YscfoxslwguaV-6MZUq9i_eC004OXMFU8oGBYigjalSi5UqkDkdw" rel="noopener" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://notifications.google.com/g/p/AD-FnEwARvbWJw6zi6_QUP9ZBXQgJF4PbMY6qtMfpkoeUbOqKVx8dk2MZzWlaktIDtRCM6orJdp-VCEGAguI8EVzNp_sR6YscfoxslwguaV-6MZUq9i_eC004OXMFU8oGBYigjalSi5UqkDkdw&amp;source=gmail&amp;ust=1632575923917000&amp;usg=AFQjCNEC9-NldDOvfUVXz_EXd_oNM__vrg" style="color: rgb(17, 85, 204);">Device and Network Abuse</a><span> </span>or<span> </span><a href="https://notifications.google.com/g/p/AD-FnEzvpCxBYsfCfNpLgKJ-AJ3QU0cGc0fX88HVLP4NAjl11_X80HzQcxj_RK4SPty-K5U0vpkg_n_Ub7LkqYBbPdv4FS3I-9dO0rKiLMjBiAFFq9i0k1aIHodNy5uwBSiIyHk-_xPG" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://notifications.google.com/g/p/AD-FnEzvpCxBYsfCfNpLgKJ-AJ3QU0cGc0fX88HVLP4NAjl11_X80HzQcxj_RK4SPty-K5U0vpkg_n_Ub7LkqYBbPdv4FS3I-9dO0rKiLMjBiAFFq9i0k1aIHodNy5uwBSiIyHk-_xPG&amp;source=gmail&amp;ust=1632575923917000&amp;usg=AFQjCNG1H1l7fNjyWzX_0ldknos8WmcsrA" style="color: rgb(17, 85, 204);">User Data</a><span> </span>policy. If you submitted an update, the previous version of your app is still available on Google Play.</p><p style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">This app uses software that contains security vulnerabilities for users or allows the collection of user data without proper disclosure.</p><p style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Below is the list of issues and the corresponding APK versions that were detected in your recent submission.<span> </span><strong style="font-weight: bold !important;">Please upgrade your app(s) as soon as possible and increment the version number of the upgraded APK.</strong></p><p style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></p>

Vulnerability | APK Version(s) | Past Due Date
-- | -- | --
SSL Error HandlerFor more information on how to address WebView SSL Error Handler alerts, please see this Google Help Center article. | 1025 | August 31, 2021

<p style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Please follow the given steps to deactivate non-compliant app bundles or APK</p><ol style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="margin-left: 15px;">Sign in to your<span> </span><a href="https://notifications.google.com/g/p/AD-FnEzKEdE_cp44Mjn2mhzZ-zoaefyxbiz-N92EXCPt_I8N0wtM0aXFwh2PaFZ77c9l2loROkagIWWWkGwXJb6FxmnC0xI" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://notifications.google.com/g/p/AD-FnEzKEdE_cp44Mjn2mhzZ-zoaefyxbiz-N92EXCPt_I8N0wtM0aXFwh2PaFZ77c9l2loROkagIWWWkGwXJb6FxmnC0xI&amp;source=gmail&amp;ust=1632575923917000&amp;usg=AFQjCNEQejhMvEIw4Pv85dYDkjahn3m58Q" style="color: rgb(17, 85, 204);">Play Console</a><span> </span>and go to the track with the policy issue (Internal / Closed / Open testing / Production).</li><li style="margin-left: 15px;">Click "Manage track" and "Create new release"<ol><li style="margin-left: 15px;">If the release with the violating app bundles / APKs are in a draft state, discard the release.</li><li style="margin-left: 15px;">Otherwise, add the policy compliant version of app bundles / APKs.</li><li style="margin-left: 15px;">Make sure the<span> </span><strong style="font-weight: bold !important;">non-compliant version</strong><span> </span>is under the Not Included section of this release.</li><li style="margin-left: 15px;">Enter a release name and click Save. Once saved, click "Review release" and then proceed to roll out the release to 100%.</li></ol></li><li style="margin-left: 15px;">If the non-compliant versions are released to multiple tracks, repeat step 5 in each track.</li></ol><p style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">To confirm you’ve upgraded correctly, submit the updated version of your app to the Play Console and check back after five hours to make sure the warning is gone.</p><p style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">While these vulnerabilities may not affect every app that uses this software, it’s best to stay up to date on all security patches. Make sure to update any libraries in your app that have known security issues, even if you're not sure the issues are relevant to your app.</p><p style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Apps must also comply with the<span> </span><a href="https://notifications.google.com/g/p/AD-FnEysgF0Ofb0Rm-zCgGiu0Ir3BniTzFzveTIAndqLdmIJKiRPPbcJWAxPEcRBHdEVQX6LBRaIY6L-VCIpIA-L2s15YBIGZ6UIuPPVjb5QoF3lKFccDyRRIA7ZMUQAVYhSawVy4w7uyA" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://notifications.google.com/g/p/AD-FnEysgF0Ofb0Rm-zCgGiu0Ir3BniTzFzveTIAndqLdmIJKiRPPbcJWAxPEcRBHdEVQX6LBRaIY6L-VCIpIA-L2s15YBIGZ6UIuPPVjb5QoF3lKFccDyRRIA7ZMUQAVYhSawVy4w7uyA&amp;source=gmail&amp;ust=1632575923917000&amp;usg=AFQjCNGN4P5kLADLSboTTufToUjf0vKSLw" style="color: rgb(17, 85, 204);">Developer Distribution Agreement</a><span> </span>and<span> </span><a href="https://notifications.google.com/g/p/AD-FnEwIyXn5EWGf8xbXQ3l-P4M20p3rAMCWAp8SuKof54QA_vvrfeNQNt-o4UoFdz_2TYqpoV4avsS9m8PjVjdh-0LLfmawLcLhBAt__ha-9AaV8kJx4eBEjI4O9PQAk_w" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://notifications.google.com/g/p/AD-FnEwIyXn5EWGf8xbXQ3l-P4M20p3rAMCWAp8SuKof54QA_vvrfeNQNt-o4UoFdz_2TYqpoV4avsS9m8PjVjdh-0LLfmawLcLhBAt__ha-9AaV8kJx4eBEjI4O9PQAk_w&amp;source=gmail&amp;ust=1632575923918000&amp;usg=AFQjCNEhn-B-RXvFkojN4PRpv5hBq2T-Kg" style="color: rgb(17, 85, 204);">Developer Program Policies</a>.</p><p style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">If you feel we have made this determination in error, please reach out to our<span> </span><a href="https://notifications.google.com/g/p/AD-FnEy4HtW6u1rhfWdNkdOFYWe7cCBpVXTh-yAhAb1NTOjjjczubu_kFqu65H9vfJuuNbz2YNA7AT20VXxIUS3pxntc4HoQhvLCyY8MfYwR7AU1S6fxy4ojxNFA-OpXIiFm1kd4G7OGMvx4pPMV" rel="noopener" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://notifications.google.com/g/p/AD-FnEy4HtW6u1rhfWdNkdOFYWe7cCBpVXTh-yAhAb1NTOjjjczubu_kFqu65H9vfJuuNbz2YNA7AT20VXxIUS3pxntc4HoQhvLCyY8MfYwR7AU1S6fxy4ojxNFA-OpXIiFm1kd4G7OGMvx4pPMV&amp;source=gmail&amp;ust=1632575923918000&amp;usg=AFQjCNFrCed3lC0lsrYS142XHdpKUyK7EA" style="color: rgb(17, 85, 204);">developer support team</a>.</p><p style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Best,</p><p style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">The Google Play Team</p>
</body>
</html>

package.json :
"react": "16.9.0",
"react-native": "0.61.4",
"react-native-webview": "11.6.1",

**Comment by alihamza1214** [comment]
Still looking for solution... facing same issue
