### ISSUE TITLE
Disabling Magnifier on OS version 15+ in iOS

### ISSUE THREAD

**Issue by amanBhawsar** [react-native-webview/react-native-webview#2177]
**Bug description:**
Magnifier is appearing on OS version 15+ on iOS on doing a long press on Webviews. Any way to disable it ?

**To Reproduce:**
Long press within any webview on iOS, OS version 15 (latest) -> Magnifier appears

**Expected behavior:**
Need a way to control whether Magnifier should be shown or not. As for most of the use cases, it is not required.

**Screenshots/Videos:**
https://user-images.githubusercontent.com/40451824/134856219-15031589-4b01-444a-93ac-28885aa096f9.mov

**Environment:**
 - OS: iOS
 - OS version: 15+
 - react-native version: 0.63.3
 - react-native-webview version: 8.1.2

**Comment by cristianoccazinsp** [comment]
Wondering the same, extremely annoying.

**Comment by cristianoccazinsp** [comment]
Keep open please.

**Comment by 98gzi** [comment]
Any updates on this?

**Comment by Nebula-Developer** [comment]
Any updates two years later?
