### ISSUE TITLE
[iOS] OutOfMemory crashes when opening a webview in Production

### ISSUE THREAD

**Issue by antonio5mins** [react-native-webview/react-native-webview#2179]
Hey guys, thank you for reading this in advance.

**Bug description:**
We use this package to load different web views when a user clicks on a button. Sometimes when you click on the button the **app just freezes** and you can't click in any other parts of the app.
In production this throws `OutOfMemory. The OS most likely terminated your app because it overused RAM.` error (caught by sentry) causing the **app to crash**. In dev there are no errors in metro, xcode, etc...

I replicated this error using the Xcode profiler and there are **no memory spikes**.
This only happens when launching this web view (does not happen in the rest of the app) what indicates that the memory leak is not on our side.
**In Android this never occurs**.

**To Reproduce:**
No every easy to reproduce, since it does not happen all the time.

**Expected behavior:**
App not to crash/freeze and show web view

**Environment:**
 - OS: iOS
 - OS version: 14.8
 - react-native version: 0.65.0
 - react-native-webview version: 11.13.1

**Comment by KornobisTI** [comment]
Hey, did you find a solution for that? We are facing the same issue

**Comment by urtheone** [comment]
We are facing the same issue,when open webview, switch the app to the background, wait a minute, and then come back, the app freezes.
OS: iOS
OS version: 13.3
react-native version: 0.67.3
react-native-webview version: 11.17.2

**Comment by TonchoLozev** [comment]
> We are facing the same issue,when open webview, switch the app to the background, wait a minute, and then come back, the app freezes.
> 
> OS: iOS
> 
> OS version: 13.3
> 
> react-native version: 0.67.3
> 
> react-native-webview version: 11.17.2

Could you try using the prop "onContentProcessDidTerminate"

https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#oncontentprocessdidterminate

**Comment by lelukas** [comment]
I'm facing the same issue. Sometimes the ios app freezes.
