### ISSUE TITLE
Android 10+: net::ERR_ACCESS_DENIED when accessing local file.

### ISSUE THREAD

**Issue by ianvasco** [react-native-webview/react-native-webview#2180]
**Bug description:**
When trying to open a local file with url like `"url": "content://com.android.providers.downloads.documents/document/msf%3A21789"`, it's showing the following error:
```
{"code": -1, "description": "net::ERR_ACCESS_DENIED"}
```
It's indeed requesting permission for `PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE`  and checking if it has been granted. 

This is also in our Android Manifest

```
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />
```

I'm also using 

```
    <application
        ...
        android:usesCleartextTraffic="true"
        >
```

For RN side, I'm passing `allowFileAccess={true}` prop to WebView component. Also I tried other suggestions from closed issues like setting a state for `renderOnce` to prevent loading a wrong uri.

***Build Gradle***
```
        buildToolsVersion = "28.0.3"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
```

**Environment:**
 - OS: Android
 - OS version: 10+
 - react-native version: 0.63.2
 - react-native-webview version: 11.13.1

**Comment by imsugat** [comment]
Hi @ianvasco,
I am also facing this issue. Have you fixed this?

**Comment by evgenijchul** [comment]
try adding this, when uploading files with a library like react-native-fs:

```
...
 source={{
             ...
             uri: webViewFile **|| undefined**,
            ...
}}
...
```

**Comment by fukemy** [comment]
you need using RNFetchBlob to convert into cache file path first
