### ISSUE TITLE
Potential breaking change

### ISSUE THREAD

**Issue by arazabishov** [react-native-webview/react-native-webview#2185]
In [v11.13.1](https://github.com/react-native-webview/react-native-webview/releases/tag/v11.13.1) you've bumped RN requirements from v62 to v65 without bumping the major version of RNW. RNW consumers that use unpinned versions, for example, v^11.4.2, can receive an incompatible version without realizing that.

Feel free to close this if the change was intended and RNW is still compatible with RN v64.

Update: FYI, it seems removing jcenter repo can break consumers of older RN versions ([one](https://github.com/react-native-async-storage/async-storage/pull/681), [two](https://github.com/react-native-async-storage/async-storage/pull/680))

**Comment by tido64** [comment]
cc @Titozzz

**Comment by chiaramooney** [comment]
Issue has now been resolved.
