### ISSUE TITLE
Blank screen rendering html or url content in android

### ISSUE THREAD

**Issue by shahanija** [react-native-webview/react-native-webview#2187]
I have a problem of display of webview with static/dynamic  html/url content, it shows the content one time, and on reload it shows a white screen 

<View
        style={{
          flex: 1,
          padding: 20,
        }}>
        <WebView
          ref={ref => {
            this.webview = ref;
          }}
          originWhitelist={['*']}
          source={{ html : card.html ,
           baseUrl: ""}}
          onLoadStart={(syntheticEvent) => { }}
        />
      </View>

Even this `onLoadStart` is not triggered when issue occurs. I tried with static url, static html as well. 
Tried placing the webview directly in the class instead of rendering from a separate component. 

None of the worked for me . 

**Screenshots**
Expected behaviour and the content is loaded on first render .
![Screenshot_20211006-124348__01](https://user-images.githubusercontent.com/10346318/136157327-a8045d7d-a604-4639-ad7f-dbdb6cd40fde.jpg)

And this one is the screen what I get when I reopen the screen.
![Screenshot_20211006-124400__01](https://user-images.githubusercontent.com/10346318/136157391-7bcbdd77-9215-4cb7-8bc1-7a9df8522804.jpg)

**To Reproduce:**
Open the screen which render webview. 
Close and reopen it again

**Expected behavior:**
To display the html or url content instead of a white screen

**Environment:**
 
 - React-native : 0.62.2
 - React-native-webview:11.14.0

 - Platform: android
 - OS: windows 10

**Comment by aamir-ans** [comment]
@shahanija Have you tried cacheEnabled={false} along with cacheMode={'LOAD_NO_CACHE'} ?

**Comment by shahanija** [comment]
Hi @aamir-ans 
I was having memory issue for loading this webview. I was rendering webview in a carousel which had more than 20 items in it. When I handled the `initialNumToRender` , it worked fine. Now it's loading the content in the webview for each item
