### ISSUE TITLE
Crash caused by RNCWebViewManager.java line 710 (java.lang.NullPointerException)

### ISSUE THREAD

**Issue by ZeroPie** [react-native-webview/react-native-webview#2190]
**Bug description:**
Crashlytics shows regular Android crashes caused by:

```Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'int android.app.Activity.getRequestedOrientation()' on a null object reference

com.reactnativecommunity.webview.RNCWebViewManager.setupWebChromeClient (RNCWebViewManager.java:710)
com.reactnativecommunity.webview.RNCWebViewManager.setAllowsFullscreenVideo (RNCWebViewManager.java:574)
java.lang.reflect.Method.invoke (Method.java)
com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp (ViewManagersPropertyCache.java:87)
com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty (ViewManagerPropertyUpdater.java:136)
com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps (ViewManagerPropertyUpdater.java:56)
com.facebook.react.uimanager.ViewManager.updateProperties (ViewManager.java:49)
com.facebook.react.uimanager.NativeViewHierarchyManager.createView (NativeViewHierarchyManager.java:270)
com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute (UIViewOperationQueue.java:186)
com.facebook.react.uimanager.UIViewOperationQueue$1.run (UIViewOperationQueue.java:911)
com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches (UIViewOperationQueue.java:1028)
com.facebook.react.uimanager.UIViewOperationQueue.access$2600 (UIViewOperationQueue.java:48)
com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded (UIViewOperationQueue.java:986)
com.facebook.react.bridge.GuardedRunnable.run (GuardedRunnable.java:31)
```

**To Reproduce:**

Cannot reproduce it myself but firebase Crashlytics show regular crashes for active users.

**Expected behavior:**
Not Crash

**Screenshots/Videos:**

![Screenshot 2021-10-07 at 14 25 04](https://user-images.githubusercontent.com/8741666/136449438-54f0ed24-20a4-42c7-91a4-697f239f6093.png)

**Environment:**
 - OS: Android 
 - OS version: Android 11
 - react-native version: ^0.63.4
 - react-native-webview version: ^11.2.0

Related: https://github.com/react-native-webview/react-native-webview/pull/2025

**Comment by ZeroPie** [comment]
Bump

**Comment by ZeroPie** [comment]
Workaround:

Patch your local RNCWebViewManager.java


``` node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java

protected void setupWebChromeClient(ReactContext reactContext, WebView webView) {
    if (reactContext == null || reactContext.getCurrentActivity() == null) {
      Log.e("RNCWebViewManager setupWebChromeClient()", "Cannot call reactContext.getCurrentActivity()");
      return;
    }
```

Use https://github.com/ds300/patch-package

Update to "react-native-webview": "^11.14.0",

and on your android/build.gradle update your buildToolsVersion to at least 29
buildscript {
    ext {
        buildToolsVersion = "29.0.3"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
....
}
}

**Comment by ds8k** [comment]
> ```
> protected void setupWebChromeClient(ReactContext reactContext, WebView webView) {
>     if (reactContext == null || reactContext.getCurrentActivity() == null) {
>       Log.e("RNCWebViewManager setupWebChromeClient()", "Cannot call reactContext.getCurrentActivity()");
>       return;
>     }
>     ...
>  }
> ```

In addition to this, you have to import `android.util.log` in order to run the above log, otherwise your app won't build.
