### ISSUE TITLE
onLoadEnd not triggering for media Urls.

### ISSUE THREAD

**Issue by ibtisamarif831** [react-native-webview/react-native-webview#2198]
**Bug description:**
So, I am opening a URL in webView that only has video media. For this url, onLoadEnd does not trigger on IOS but works fine on android. For IOS, the system media player pops up and video plays in that in fullscreen and after you close the fullscreen, the webview keeps showing the activity indicator. 

**To Reproduce:**
Here is the snack link that reproduces it.
https://snack.expo.dev/vHVzlCg0J

**Expected behavior:**
onLoadEnd Should Fire

**Screenshots/Videos:**

**Environment:**
 - OS:MacOS
 - OS version:IOS
 - react-native version:0.63.4
 - react-native-webview version:10.7
- But the problem is on the latest version as well.

**Comment by raj-upadhyay** [comment]
still searching for solutions.

**Comment by kj71** [comment]
Same issue. Any updates on this?
