### ISSUE TITLE
webview show blank page when not used for some time in iOS

### ISSUE THREAD

**Issue by uganof** [react-native-webview/react-native-webview#2199]
Hi, I come immediately to the problem: 
application that uses webview page, when it is not used for some time and is put in the background, when you return to the foreground the webview component displays a blank page.

From what I could guess Ios (more evident in version 15) when it needs memory it does something and deletes the contents of the WebView

By method reload(), everything returns to normal but I would like to avoid reloading at each change of app state.

Is there a way to know when Ios has "blanked" the webview component?

**Environment:**
 - OS: Ios
 - OS version: 15.0.1
 - react-native version: 0.65.1
 - react-native-webview version: 11.13.0

**Comment by ramniwaseasyeat** [comment]
@uganof did you find any solution on it?

**Comment by pelicarno** [comment]
onContentProcessDidTerminate() event I believe might be called when it happens, not 100% sure yet as its difficult to reproduce this issue.

**Comment by uganof** [comment]
Hi, thanks to @pelicarno,
I have tested onContentProcessDidTerminate() event and solved my problem.

**Comment by xavier-villelegier** [comment]
I can confirm reloading when `onContentProcessDidTerminate` fixes the issue (still not sure why it crashes in the first place though)

```jsx
  onContentProcessDidTerminate = () => this.webView.reload()

  render() {
    return (
      <WebView
        …
        ref={(webView) => this.webView = webView}
        onContentProcessDidTerminate={this.onContentProcessDidTerminate}
      />
    )
  }
```

**Comment by hosseintalebi** [comment]
Thanks for the suggestion of `onContentProcessDidTerminate`. It fixed the issue for us. Do we know what caused the termination of the webview? We noticed this happing on iOS 15+. I would appreciate any insight regarding the root cause of this issue.

**Comment by sviatoslav-lebediev** [comment]
> ... I would appreciate any insight regarding the root cause of this issue.

maybe this article can help https://blog.embrace.io/bug-of-the-month-blank-webviews/

**Comment by cnmade** [comment]
I found he same bug for IOS , i resolved by add some configure, see also:
https://stackoverflow.com/a/63477843

**Comment by mattdamon108** [comment]
> > I can confirm reloading when `onContentProcessDidTerminate` fixes the issue (still not sure why it crashes in the first place though)
> > ```js
> >   onContentProcessDidTerminate = () => this.webView.reload()
> > 
> >   render() {
> >     return (
> >       <WebView
> >         …
> >         ref={(webView) => this.webView = webView}
> >         onContentProcessDidTerminate={this.onContentProcessDidTerminate}
> >       />
> >     )
> >   }
> > ```
> 
> do you have a code snippet of how to do it in functional component?

```js
const onContentProcessDidTerminate = () => this.webView.reload()

return (
  <WebView
    …
    ref={(webView) => this.webView = webView}
    onContentProcessDidTerminate={onContentProcessDidTerminate}
  />
)
```

**Comment by allan-simon** [comment]
I think it should be put in the documentation ?  We spend a week tracking this issue to finally found this link

**Comment by mparramont** [comment]
For whoever is having this issue on Android, a possible solution using `onRenderProcessGone` is mentioned here: https://github.com/react-native-webview/react-native-webview/issues/2225#issuecomment-1006214441
