### ISSUE TITLE
record audio through webview

### ISSUE THREAD

**Issue by hanaechahid** [react-native-webview/react-native-webview#2201]
Hello, 
I am trying to record audio through the webview  but I am facing the next error: 
`NotAllowedError: permission denied` so I can't record it. however, permission already granted

a snippet of my code: 
```
document.getElementById("record-zone").addEventListener("click", function(e){
if (navigator.mediaDevices && navigator.mediaDevices.getUserMedia) {
    navigator.mediaDevices.getUserMedia ({ audio: true })
       .then(function(stream) {
        const mediaRecorder = new MediaRecorder(stream);
        mediaRecorder.start();
       })
       .catch(function(err) {
          console.log('The following getUserMedia error occurred: ' + err);
       }
    );
 } else {
    console.log('getUserMedia not supported on your browser!');
 }
});
```
above code is injected in my webview: 
```
javaScriptEnabled={true}
injectedJavaScript={jscode}
```
do you have any  idea how it works?
 
react: "16.8.3",
react-native: "0.59.10",
react-native-webview: "^5.12.1"

**Comment by airomo45** [comment]
I have been having the same issue did you figure out how to solve this @hanaechahid ?

**Comment by pablohenriqueop** [comment]
Add this lines to your AndroidManifest.xml

 ```
     <uses-permission android:name="android.permission.RECORD_AUDIO"/>
     <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
     <uses-permission android:name="android.permission.AUDIO_CAPTURE" />
 ```

**Comment by PreciousNiphemi** [comment]
@pablohenriqueop  please what of ios cases? 


> Add this lines to your AndroidManifest.xml
> 
> ```
> <uses-permission android:name="android.permission.RECORD_AUDIO"/>
> <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
> <uses-permission android:name="android.permission.AUDIO_CAPTURE" />
> ```

**Comment by lessquo** [comment]
Add [NSMicrophoneUsageDescription](https://developer.apple.com/documentation/bundleresources/information_property_list/nsmicrophoneusagedescription) to your `Info.plist`.

Example:
```
<key>NSMicrophoneUsageDescription</key>
<string>This application requires microphone access to record audio.</string>
```
