### ISSUE TITLE
Webview scroll issue in Android

### ISSUE THREAD

**Issue by jgalianoz** [react-native-webview/react-native-webview#2206]
**Bug description:**
Webview scrolls not working in Android.

```
import { WebView as RNWebView } from 'react-native-webview';
<RNWebView
  source={{ uri: url }}
  originWhitelist={['*']}
  mediaPlaybackRequiresUserAction
  startInLoadingState={true}
  onLoadStart={onLoadStart}
  onLoad={onLoad}
  incognito={incognito}
  hideKeyboardAccessoryView={true}
  renderLoading={() => <Loader visible variant="light" />}
/>
```
The Webview is inside of a `View`

**Environment:**
 - OS: Android
 - OS version: 9
 - react-native version: 0.66.0
 - react-native-webview version:11.6.5

**Comment by Fede-Gomez** [comment]
hi same issue, i see when scroll in horizontal appear one event with one field saying responderIgnoreScroll. Scroll vertical it's not a problem but vertical stop the scroll.
Some idea?
I put inside ScrollView but not working

**Comment by QendresaB3** [comment]
Same issue, the scroll doesn't work properly in android, it "kinda" jumps up if you scrolling down and the other way around.  
Using the webview with these properties, and tried to wrap it up with ScrollView but didn't work.
`<WebView
        incognito
        ref={webViewRef}
        injectedJavaScript={...}
        showsVerticalScrollIndicator={false}
        showsHorizontalScrollIndicator={false}
        androidHardwareAccelerationDisabled={true}
        cacheEnabled={false}
        cacheMode="LOAD_NO_CACHE"
        onLoad={() => setData()}
        onNavigationStateChange={...}
        source={{ uri: `http://localhost:3000/${user?.id}` }}
        onMessage={...}
        key={webKey}
        onContentProcessDidTerminate={...}
      />`

Environment:
OS: Android
OS version: 9

**Comment by kartavyaparekh96** [comment]
Same issue

**Comment by sdumjahn** [comment]
I have the same issue

**Comment by jgalianoz** [comment]
My problem was that it had elements above the WebView that blocked scrolling and taps within the WebView.

**Comment by bennysalewski** [comment]
> Same issue, the scroll doesn't work properly in android, it "kinda" jumps up if you scrolling down and the other way around. Using the webview with these properties, and tried to wrap it up with ScrollView but didn't work. `<WebView incognito ref={webViewRef} injectedJavaScript={...} showsVerticalScrollIndicator={false} showsHorizontalScrollIndicator={false} androidHardwareAccelerationDisabled={true} cacheEnabled={false} cacheMode="LOAD_NO_CACHE" onLoad={() => setData()} onNavigationStateChange={...} source={{ uri: `...` }} onMessage={...} key={webKey} onContentProcessDidTerminate={...} />`
> 
> Environment: OS: Android OS version: 9

I have the same issue. Sometimes you scroll down and then it starts to scroll up to top. Then are stuck and cannot scroll down. Eventuelle you get free and can scroll down.

Environment: Android 11 Realme 7 5g

**Comment by nvijaya24** [comment]
If WebView inside ScrollView just remove ScrollView that will work

**Comment by dcisneros2** [comment]
Issue is still occurring. It randomly jumps back up after I scroll down the first time.

**Comment by meenunegi** [comment]
any solution for the mentioned issue. 
React Native: '0.66.3'
Webview - '11.17.2'

**Comment by meenunegi** [comment]
> QendresaB3

Is any solution or workaround have you found to resolve the issue that you mentioned above?

**Comment by NemyaNation** [comment]
???

**Comment by NemyaNation** [comment]
still searching for solutions

**Comment by afras21** [comment]
having the same issue, any work around for this?

**Comment by afras21** [comment]
> Same issue, the scroll doesn't work properly in android, it "kinda" jumps up if you scrolling down and the other way around. Using the webview with these properties, and tried to wrap it up with ScrollView but didn't work. `<WebView incognito ref={webViewRef} injectedJavaScript={...} showsVerticalScrollIndicator={false} showsHorizontalScrollIndicator={false} androidHardwareAccelerationDisabled={true} cacheEnabled={false} cacheMode="LOAD_NO_CACHE" onLoad={() => setData()} onNavigationStateChange={...} source={{ uri: `...` }} onMessage={...} key={webKey} onContentProcessDidTerminate={...} />`
> 
> Environment: OS: Android OS version: 9

Had exactly same issue and got a fix now. 
in android manifest change `android:hardwareAcclerated="false"` to
`android:hardwareAccelerated="true"`
