### ISSUE TITLE
How to download blob url like blob://https://xyz.com/56477621239-90898721-9878954

### ISSUE THREAD

**Issue by iranu** [react-native-webview/react-native-webview#2207]
**Bug description:**

I need to download a pdf file which is blob url. I have implemented normal method but finds nothing into it. It is downloading a blank file.

**To Reproduce:**

  const { dirs } = RNFetchBlob.fs;
            RNFetchBlob.config({
              fileCache: true,
              addAndroidDownloads: {
              useDownloadManager: true,
              notification: true,
              mediaScannable: true,
              title: `test.png`,
              path: `${dirs.DownloadDir}/test.png`,
              },
            })
              .fetch('GET', nativeEvent.url.slice(5), {})
              .then((res) => {
                console.log('The file saved to ', res.path());
              })
              .catch((e) => {
                console.log(e)
              });

**Expected behavior:**

It should download the file png or pdf, which is coming in blob.

**Screenshots/Videos:**

**Environment:**
 - OS:Mac
 - OS version:Big Sur
 - react-native version:64
 - react-native-webview version:11>

**Comment by Aure77** [comment]
I think you post your issue on the wrong project. See https://github.com/joltup/rn-fetch-blob/issues

**Comment by MuhammadRafeh** [comment]
@iranu ?
