### ISSUE TITLE
[iOS] User's installed certificate for web authentication 

### ISSUE THREAD

**Issue by CMiguelRB** [react-native-webview/react-native-webview#2212]
Hi all,

I'm working in an app which requires to authenticate via WebView to a third party's authentication server. This authentication works using a certificate (profiles on iOS) installed in the phone.

I could figure the Android part before seeing @zLounas [#2016 pull request](https://github.com/react-native-webview/react-native-webview/pull/2160), we did practically the same. Now a dialog pops up letting the user to choose the right certificate installed on the device for the authentication process. But I'm not an iOS developer, so I'm a bit lost about how to handle this problem.

Any clues on how to handle this on iOS?

**Describe the solutions you came up with**
Implementing the same thing @zounasL did for Android in the #2160 pull request for iOS (Objective C).

**Comment by zounasL** [comment]
I might be wrong but i believe this is already supported. iOS handles those certificate request in didReceiveAuthenticationChallenge method
