### ISSUE TITLE
#import <React/RCTWebView.h> file not found

### ISSUE THREAD

**Issue by hawjefferson** [react-native-webview/react-native-webview#2213]
Hi!

I'm new to React-native and I'm trying to follow the steps here to implement a custom webview. I 'm getting this error on the #import <React/RCTWebView.h>  'React/RCTWebview.h' file not found.

I also check the file path node_modules/react-native/React/Views folder and I can't see the said header file there. 

is this expected? If not, would you be able to provide/recommend me a fix on how can this be solved? Thanks!

![image](https://user-images.githubusercontent.com/47293714/138886680-0a6e724a-1774-405d-a8e1-63bc3c7a7209.png)

**Comment by EHRdev** [comment]
Same error here :(

**Comment by javidmammad** [comment]
same here

**Comment by adrianm86** [comment]
same here
