### ISSUE TITLE
Inject Javascript into all iFrames and reloaded pages

### ISSUE THREAD

**Issue by n1mda** [react-native-webview/react-native-webview#2215]
**Bug description:**
I am trying to inject JavaScript onto all pages that a user visits using a WebView, as well as all iframes that those pages include. My problem is that JavaScript is only injected once, so if the user reloads the page or if the iframe reloads itself programatically the new pages do not get any injected javascript.

I see this because JavaScript is injected into the main page as well as iframes, but `window.location` in the iframes is `about:blank`, and then when the iframe eventually loads the real page, the JavaScript is no longer injected (Likely because the iframe has navigated from `about:blank` to an actual page). If I use `this.webviewRef.injectJavaScript()` any code is only injected to the main page, and not the iframes.

**To Reproduce:**
```javascript
overrideJs = `
    console.log = window.top.ReactNativeWebView.postMessage;
    const whereAmI = window.location;
    console.log('Hello from inside:\t' + whereAmI);

    setTimeout(function() {
      log.info('Running after 1000ms in ' + whereAmI);
    }, 1000);

    true;
  `
```

This is the output from the console:
```
Hello from inside:    https://www.somepage.com/foobar
Hello from inside:    about:blank
Running after 1000ms in https://www.somepage.com/foobar
```

As you can see the log statement after 1000ms in `about:blank` is missing, because the iframe has loaded the actual page.

```
<WebView
        ref={(r) => this.webviewRef = r}
        source={{ uri: 'https://www.somepage.com/foobar' }}
        onMessage={this.messageEvent}
        injectedJavaScript={overrideJs}
        injectedJavaScriptForMainFrameOnly={false}
        allowUniversalAccessFromFileURLs={true}
      />
```

**Expected behavior:**
Ability to inject JavaScript onto all pages visited, including iframes.

**Environment:**
 - OS: iOS Simulator
 - OS version: iOS15
 - react-native version: 17.0.1
 - react-native-webview version: 11.14.1

**Comment by jamninetyfive** [comment]
same here . have you sloved
