### ISSUE TITLE
User-Agent Issue in-case of Android

### ISSUE THREAD

**Issue by InterMilesGithub** [react-native-webview/react-native-webview#2219]
**Bug description:**
- We are facing an intermittent user-agent issue in case of Android. On iOS it is working fine.
- We have integrated third party payment SDK on website end. 
- We are using custom user-agent (e.g. APP) when we open any web url from react-native-webview(mWeb) to identify whether request is coming from react-native-webview(mWeb) or Desktop browser.
- Here in this case from react-native-webview(mWeb) when redirection happens from our internal domain to payment SDK domain the custom user agent (e.g APP) is changing to default user-agent (e.g Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36). This is fine.
- But once the payment is done and when redirection happens from Payment domain to our internal domain the user-agent is NOT reseting to custom user-agent(e.g APP). This is happening intermittently (1 out of 10 times).

We are suspecting that payment SDK is explicitly changing the user-agent to default user-agent. Post that we are expecting react-native-webview to respect the value for user-agent prop once payment SDK completes the payment.

**Expected behavior:**
- The react-native-webview should not change user-agent automatically.

**Environment:**
 - OS: Android 
 - OS version: Android 9 (Android Pie) & Above
 - react-native version: 0.64.2
 - react-native-webview version: 11.6.5

**Comment by prarabdhb** [comment]
Can confirm this behaviour. We are also facing the same issue on Android.

**Comment by firozanawar** [comment]
I am facing the same issue. I am using Android native WEBVIEW and i am setting User-Agent by appending on default one but for my many 30% user it is coming as default user-agent.
`val ua = settings.userAgentString
settings.userAgentString = "$ua AppContainer/10.5.10 /${BuildConfig.VERSION_NAME}"`
so ideally this should comes as user-agent with my string appended but for 30% user i am getting as a below
`Mozilla/5.0 (Linux; Android) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/55.0.2883.91 Mobile Safari/537.36`
This is super critical to us please help here.

**Comment by prarabdhb** [comment]
Any update on this issue? This is a critical issue for us right now.

**Comment by jackkinsella** [comment]
We are running into something similar: What we're experiencing is almost as if our custom userAgent is only sent on the first request. After that, it reverts to the default.

**Comment by MiryangJung** [comment]
any update?
