### ISSUE TITLE
webview show blank page when not used for some time in android

### ISSUE THREAD

**Issue by WuPan1018** [react-native-webview/react-native-webview#2225]
System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 58.70 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /Users/jionwu/.rvm/rubies/ruby-2.5.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 23, 26, 27, 28, 29
      Build Tools: 26.0.3, 27.0.3, 28.0.0, 28.0.0, 28.0.3, 29.0.2, 30.0.2
      System Images: android-26 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_191 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Android 7.0 uses WebView to load and work normally. After running for a period of time, the screen is blank. The web page is built by a Websoket and can be used normally in the browser

**Comment by hanifmhd** [comment]
It also happens on iOS

**Comment by prasad-11-cairs** [comment]
This issue is only in Android, but not in iOS

**Comment by akzn** [comment]
do you mean  "not used for some time" are when its on background for some time and then comeback to foreground?
if yes, I tested with `onRenderProcessGone()` for android spesific and it works for me.
https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#onrenderprocessgone

**Comment by tkmin** [comment]
@akzn like this..?

<WebView
  ...
  onRenderProcessGone={() => this.webViewRef.reload()}
  ...
/>

**Comment by akzn** [comment]
@tkmin yes. Tho in my case its webViewRef.ref.current.reload().

**Comment by mparramont** [comment]
For whoever is having this issue on iOS, a possible solution using `onContentProcessDidTerminate` is mentioned here: https://github.com/react-native-webview/react-native-webview/issues/2199#issuecomment-964156583
