### ISSUE TITLE
openFileChooser Overwrite error

### ISSUE THREAD

**Issue by BaLaLaLs** [react-native-webview/react-native-webview#2227]
**Bug description:**
Executing `npm run android ` on my computer, I got some errors
![image](https://user-images.githubusercontent.com/23353559/140619117-7571fc6a-13dc-4443-b036-f85a0f8ff459.png)

![image](https://user-images.githubusercontent.com/23353559/140619188-a12b1724-6b77-4316-9d7a-a50cca1b5421.png)

When I change the method to public，`npm run android` is work。

![image](https://user-images.githubusercontent.com/23353559/140619197-9fc7c0e9-0312-4a25-a999-896fe5ef4246.png)

**Environment:**
 OS: macOS 11.2.3
 react-native: 0.66.2
 react-native-webview version: 11.14.2

**Comment by 1280103995** [comment]
Still having this problem on the new version.

```
protected void openFileChooser(ValueCallback<Uri> filePathCallback
      
Attempting to assign lower access rights; formerly public
```
