### ISSUE TITLE
react native webview iOS not keep session cookies when app killed from background then webview automatically logout 

### ISSUE THREAD

**Issue by naveenr1592** [react-native-webview/react-native-webview#2228]
**Bug description:**

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS: iOS
 - OS version:13.1
 - react-native version: 64.1
 - react-native-webview version: 11.14.2

**Comment by gauravrami** [comment]
@naveenr1592  **did you find any solution??**

**Comment by tkmin** [comment]
I have a same issue

**Comment by ANTARES-KOR** [comment]
Is there any solution to this? Any options from react-native-webview didn't resolve this issue.

My webview implementation is this
```typescript
        <WebView
          onMessage={handlePostMessage}
          geolocationEnabled={true}
          decelerationRate={"normal"}
          incognito={false}
          cacheEnabled={true}
          thirdPartyCookiesEnabled={true}
          sharedCookiesEnabled={true}
          style={{ flex: 1 }}
        />
```

**Comment by allan-simon** [comment]
is related to https://github.com/react-native-webview/react-native-webview/issues/1780 ?

**Comment by allan-simon** [comment]
I can confirm the issue is still there

**Comment by minsu-zip** [comment]
I had the same problem.

We fixed the issue by specifying the Expires or Max-Age of the cookie.

iOS has the problem of losing cookies without Expires or Max-Age that exist in web views in the background during memory cleanup.

- I was able to find out from the cookie test on iOS safari.
- I haven't tested it in all versions of iOS, but it happens in iOS 15 and later.

**Comment by RohanDhalpe05** [comment]
This worked in my Rails app.
When my webview based app is killed and reopened, the user session is lost and they must log in again. In the browser, the session persists across tab/window closes.

Add config/initializers/session_store.rb (new file):

```
# frozen_string_literal: true

Rails.application.config.session_store :cookie_store, expire_after: 14.days
```
This sets an explicit expiry on the session cookie so it persists across app restarts until the session expires or the user logs out.

The necessary WebView settings (sharedCookiesEnabled, thirdPartyCookiesEnabled, domStorageEnabled, cacheEnabled) are already configured, so the mobile app does not require any changes.
