### ISSUE TITLE
Custom WebViews

### ISSUE THREAD

**Issue by Runkunkun** [react-native-webview/react-native-webview#2229]
Hello,

is there a way to create a custom WebViews for iOS like with https://reactnative.dev/docs/custom-webview-ios ? I need to implement extra logic into the controller and have no idea how to do it.
If anybody has a idea how to do it i would be very gratefull.

**Comment by TheAlmightyBob** [comment]
That still works, the document was migrated here: https://github.com/react-native-webview/react-native-webview/blob/master/docs/Custom-iOS.md
