### ISSUE TITLE
iOS 15 cannot disable input focus/pinch/double tap zoom despite initial-scale=1.0, maximum-scale=1.0

### ISSUE THREAD

**Issue by LogicAnalysis** [react-native-webview/react-native-webview#2231]
**Bug description:**
On iOS 15, and possibly other platforms, the device allows zooming of the page on double tap, and automatically zooms on an input when the user clicks it. This is despite injecting the following script:

const meta = document.createElement('meta');
meta.setAttribute('content', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0');
meta.setAttribute('name', 'viewport');
document.head.appendChild(meta);

Additionally, I am using the following options:

scalesPageToFit={ false }
scrollEnabled={ false }
bounces={ false }
automaticallyAdjustContentInsets={ false }

**To Reproduce:**
Have any webview with an input on iOS15. Upon clicking the input, the view will zoom into the input automatically. Additionally, double tapping on an element in the webview will cause it to scroll.

**Expected behavior:**
With the JS injected using injectedJavaScript, and the options I'm using, the webview should not allow any zooming, and especially not when the user simply clicks an input.

**Environment:**
 - OS: iOS
 - OS version: 15.0
 - react-native version: 0.66.1
 - react-native-webview version: 11.14.2

**Comment by LogicAnalysis** [comment]
I managed to find a workaround (not ideal) by simply adding the meta tag directly in the project's header:

`<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0"/>`

This tells me that the injectedJavaScript method for inserting that meta tag is not working as intended. I was using the following method: injectedJavaScript={ injectScript } with the following injectScript constant:

`	const injectScript = `
		const meta = document.createElement('meta');
		meta.setAttribute('content', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0');
		meta.setAttribute('name', 'viewport');
		document.head.appendChild(meta);
	`;
`

**Comment by Jojr** [comment]
@LogicAnalysis I'm having the same problem. Did you solve that by running on ios15?

**Comment by LogicAnalysis** [comment]
> 

I did manage to fix it, but I can't even begin to tell you how. This is the code I'm using, if that's of any use to you:

```
<TouchableWithoutFeedback onPress={ Keyboard.dismiss }>
						<View style={{ height: '100%', width: '100%', backgroundColor: colors.main.main_background }}>
							<WebView
								ref={ viewRef }
								source={{
									uri: INTERNAL_ADDRESS,
									headers: { Authorization: state.token }
								}}
								originWhitelist={ ['*'] }
								style={{ overflow: 'scroll', backgroundColor: main_background_color }}
								scalesPageToFit={ false }
								scrollEnabled={ true }
								mixedContentMode={ 'compatibility' }
								thirdPartyCookiesEnabled={ true }
								domStorageEnabled={ true }
								startInLoadingState={ true }
								renderLoading={ () => (
									<View style={{ height: '100%', width: '100%', backgroundColor: main_background_color, alignItems: 'center', justifyContent: 'center' }}>
										<ActivityIndicator size='large' color='#FF0000' />
									</View>
								)}
								allowUniversalAccessFromFileURLs={ true }
								onMessage={ (e) => handleMessage(JSON.parse(e.nativeEvent.data)) }
								bounces={ false }
								automaticallyAdjustContentInsets={ false }
								injectedJavaScript={ injectScript }
								onLoadEnd={ () => sendToken() }
								javaScriptEnabled={ true }
								hideKeyboardAccessoryView={ true }
								allowsLinkPreview={ false }
							/>
						</View>
					</TouchableWithoutFeedback>
```

A lot of that might not be useful to you, but I'm not sure which change actually did the trick. You can get rid of the JS features if you're not using those. There are a few variables in there which you'll have to substitute as well.

**Comment by ridvanaltun** [comment]
> By process of elimination it seems to be a combination of adding the meta tag and an `onMessage` handler (even if it's a no-op) that fixes it.

I'm using latest version (v13.10.5), this issue still exist and same workaround works

**Comment by hungtranauthentia** [comment]
> I managed to find a workaround (not ideal) by simply adding the meta tag directly in the project's header:
> 
> `<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0"/>`
> 
> This tells me that the injectedJavaScript method for inserting that meta tag is not working as intended. I was using the following method: injectedJavaScript={ injectScript } with the following injectScript constant:
> 
> ` const injectScript = " const meta = document.createElement('meta'); meta.setAttribute('content', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0'); meta.setAttribute('name', 'viewport'); document.head.appendChild(meta); "; `
> 
> This obviously now impacts the entire site, rather than just the page I'm loading in the webview. Also, one requires access to the site itself in order to use this workaround. Like I said earlier; not ideal.

This workaround works for me too
