### ISSUE TITLE
Module is not a registered callable module(calling onMessage) 

### ISSUE THREAD

**Issue by charlesYun** [react-native-webview/react-native-webview#2232]
This is a serious problem. When will it be solved? The latest 11.14.2 release still has the same problem

**Comment by charlesYun** [comment]
"react-native": "^0.62.3",  "react-native-webview": "^11.14.2",No more questions

**Comment by huangzhizhen** [comment]
> 这是一个严重的问题。什么时候能解决？最新的 11.14.2 版本仍然有同样的问题



> 这是一个严重的问题。什么时候能解决？最新的 11.14.2 版本仍然有同样的问题

我也遇到这个问题了，    "react-native-webview": "5.0.1",    "react-native": "0.59.10",不知道怎么解决
