### ISSUE TITLE
disable long press

### ISSUE THREAD

**Issue by JacksenLaw** [react-native-webview/react-native-webview#2238]
Because the bottom line will automatically select some text，so，Can you provide a way to disable the long press event？

**Comment by gbhrdt** [comment]
You can solve it with some custom CSS:

```
const customCss = '* { -webkit-user-select: none; } input, textarea { -webkit-user-select: initial; } body { user-select: none !important; overflow-x: hidden !important; }';

const customJs = `
      (function() {
        setTimeout(function() {
          try {
            var s = document.createElement('style');
            s.innerHTML = '${customCss.replace(/'/g, "\\'").replace(/(\r\n|\n|\r)/gm, '')}';
            document.head.appendChild(s);
          } catch (e) {  }
        }, 0); 
      })();`;

<WebView
  injectedJavaScriptBeforeContentLoaded={Platform.OS === 'ios' ? customJs : undefined}
  injectedJavaScript={Platform.OS === 'android' ? customJs : undefined}
...
/>
```

**Comment by chriswgreen-lineup** [comment]
Had a similar issue rendering a custom canvas within a webview and getting the copy prompt on long hold. Solution for me was to simply insert the following within the styles of the rendered html. 

* {
    -webkit-user-select: none;
  }

**Comment by rohit75** [comment]
> Had a similar issue rendering a custom canvas within a webview and getting the copy prompt on long hold. Solution for me was to simply insert the following within the styles of the rendered html.
> 
> * {
>   -webkit-user-select: none;
>   }

Can you please explain where to add this code?

**Comment by MarufSharifi** [comment]
> Had a similar issue rendering a custom canvas within a webview and getting the copy prompt on long hold. Solution for me was to simply insert the following within the styles of the rendered html.
> 
> * {
>   -webkit-user-select: none;
>   }

Could you please describe where should we add this styles?
