### ISSUE TITLE
Local HTML file on Android

### ISSUE THREAD

**Issue by victorcrbt** [react-native-webview/react-native-webview#2239]
**Bug description:**
Loading a local HTML file with a script that renders the content inside an iframe returns only the error **net::ERR_BLOCKED_BY_RESPONSE**, instead of loading the actual content of the page.

Don't know if it is actually a bug, or something specific to the Android implementation of the Webview. On iOS the same content works fine.

**To Reproduce:**
Load a local HTML file that renders an iframe that loads the content of an external URL.

**Expected behavior:**
Expected the content to load sucessfully.

**Environment:**
 - OS: Android Emulator
 - OS version: 11
 - react-native version: 0.64.2
 - react-native-webview version: 11.14.2

**Comment by abdullahkhan70** [comment]
Do you mean do you want to show your local HTML page through this library? If so, then you have to make HTML file and then require it into the source prob.

**Comment by victorcrbt** [comment]
Not really. I already managed to show the content of the file. It is just that the file I'm using, renders an iframe which loads content from another domain and returns me that error. 

I'm already in touch with the company that is providing us the content of this page (which is a chatbot) to check if there is something that they can do on their side.

**Comment by Umar-Farooq-Shafi** [comment]
same issue. @victorcrbt How did you fix it?
