### ISSUE TITLE
Provide official documentation on how to load local html/css/js files on IOS

### ISSUE THREAD

**Issue by VanCoding** [react-native-webview/react-native-webview#2241]
Hi and thank you very much for this useful library!

In our app, we need to integrate a statically built webpage, consisting of html/css/js and some other files.

For android, this was no problem, we just had to put all the files under android/app/src/main/assets/www and then set source.uri of the webview to file:///android_asset/www/MYHTMLFILE.html.

For iOS this does not work, and after hours of research, I still couldn't find out how to make it work.
So it would be very nice, if there was some official documentation on how to correctly do this on both android and iOS.
Since this is a webview component and local files are probably a very common use case, I think it would make sense to document it here and save other people a lot of time.

I'd do the documentation, but since I have no idea how to do it on iOS, I can't :(

**Comment by georgewwindsor** [comment]
bump
