### ISSUE TITLE
Input field not selectable on Android

### ISSUE THREAD

**Issue by potatoengineer** [react-native-webview/react-native-webview#2243]
**Bug description:**
On Android, tapping the search bar does nothing. It will not focus and as a result, the keyboard does not appear and I cannot type anything in order to search. This works on iOS.

**To Reproduce:**
Here is my code:
```javascript
import React from 'react';
import WebView from 'react-native-webview';

const PDFViewer = () => (
  <WebView source={{ uri: 'https://online.flippingbook.com/view/309034/' }} />
);

export default PDFViewer;
```
**Expected behavior:**
After tapping the top right magnifying glass icon to navigate to the search screen, tapping the search bar should allow a user to type something in to search.

**Screenshots/Videos:**
Here is a snack: https://snack.expo.dev/5lMl7Wel8?

**Environment:**
 - OS: Android
 - OS version:
 - react-native version: 0.63.4
 - react-native-webview version: confirmed on 11.6.2 and also on 11.13.0

**Comment by abdullahkhan70** [comment]
I in fact tried to do it through the Natively, but still, it is showing the same error. I think we can not do anything, because there is no id or class associated with the search input field.

**Comment by ahmadcitrusbits** [comment]
Any update? I am facing the same issue on Android with a payment gateway iframe, Everything works fine on iOS, But on Android, the input isn't focused.

**Comment by ahmadcitrusbits** [comment]
Hey, @potatoengineer  I fixed this issue by providing nestedScrollEnabled = true that works for android.

**Comment by TaylorPringleNZME** [comment]
Hey @potatoengineer, did you find a solution to this issue?
