### ISSUE TITLE
MenuItems doesn't work on Android

### ISSUE THREAD

**Issue by phuongpt** [react-native-webview/react-native-webview#2244]
**Bug description:**
I can't see `menuItems` works on Android, or I'm missing something??

**Expected behavior:**
`menuItems` should work as on iOS

**Environment:**
 - react-native-webview version: `11.14.1`
 - Android 10

**Comment by abdullahkhan70** [comment]
> **Bug description:** I can't see `menuItems` works on Android, or I'm missing something??
> 
> **Expected behavior:** `menuItems` should work as on iOS
> 
> **Environment:**
> 
> * react-native-webview version: `11.14.1`
> * Android 10

Can you elaborate even more? What exactly do you want?

**Comment by phuongpt** [comment]
@abdullahkhan70  sorry I think I found out the answer here https://github.com/react-native-webview/react-native-webview/pull/2101. Thanks for your response^^
