### ISSUE TITLE
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined

### ISSUE THREAD

**Issue by darshandec** [react-native-webview/react-native-webview#2247]
**Bug description:**
onPress of my <Pressable/> the user navigation.navigate('MyView') but when the MyView screen loads (a functional component), the control doesn't go inside it's useEffect hook, but instead goes to it's return() and throws the following error:

Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

**To Reproduce:**
Create a screen with a WebView component, a Header component, and a button component

`import React, { useState, useEffect } from 'react';
import { View } from 'react-native';
import { WebView } from 'react-native-webview';
import HeaderBack from '../../component/HeaderBack';
import { getAxiosInstance } from '../../globs/ajax-proxy';

const MyView = props => {
  const { navigation } = props;
  console.log('navigation', navigation);
  const [myHTML, setMyHTML] = useState('');

  const htmlContent = `<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body>${myHTML}</body></html>`;

  useEffect(() => {
    console.log('inside MyView');
    const url = //call an api that returns some html in response
    getAxiosInstance()
      .get(url)
      .then(res => {
        console.log('res in MyView ==>', res.status);
        if (res.status) {
          setMyHTML(res.data.description);
          console.log('res after MyView ==>', res);
        } else if (!res.data) {
          console.log('no res');
        }
      })
      .catch(err => {
        console.log('api err==>', err);
      });
  }, []);

  return (
    <View style={flex : 1}>
        <HeaderBack header="My WebView" goBack={navigation.goBack} />
        <WebView
        originWhitelist={['*']}
        source={{ html: htmlContent }}
        renderLoading={defaultLoader}
        startInLoadingState={true}
        textZoom={100}
      />
    </View>
  );
};

export default MyView;
`

**Expected behavior:**
The WebView should display the html content which comes as part of an api call made in the useEffect hook. The screen has a WebView component, a Header component, and a button component.

**Screenshots/Videos:**
![image](https://user-images.githubusercontent.com/73519505/142979855-c2c46091-dfcc-46c2-bce5-9399d3ee606b.png)

**Environment:**
 - OS: Windows
 - OS version: Windows 10 Pro
 - react-native version: 0.64.2
 - react-native-webview version: ^11.13.0

**Comment by neemssoni** [comment]
still searching for solutions
