### ISSUE TITLE
Webview showing not secure popup when making a payment

### ISSUE THREAD

**Issue by LinhNguyen1059** [react-native-webview/react-native-webview#2248]
**Bug description:**

The payment method of website show me the browser not secure popup when I making a payment.
After I press `Pay with Afterpay` button in checkout page, it shown `Don't see the secure payment browser?` popup like image below, then reload the web.

It works on website browser, but not in RNWebView. Actually, When I pressed `Pay with Afterpay` on Website browser, it open a new tab with `about:blank` url, then redirect to `Afterpay` payment.

At first I tested on `11.0.0` version, then I upgrade to `11.14.3` but same issue.

Here is my WebView code:

```
const onShouldStartLoadWithRequest = ({ url }) => {
  if (
    url &&
    url.split("://")[0] !== "http" &&
    url.split("://")[0] !== "https"
  ) {
    if (isIOS) {
      Linking.openURL(url);
      return false;
    }
  }
  return true;
};

<WebView
  source={{uri: 'https://www.ebay.com.au'}}
  bounces={false}
  originWhitelist={["*"]}
  startInLoadingState={true}
  onShouldStartLoadWithRequest={onShouldStartLoadWithRequest}
  automaticallyAdjustContentInsets={false}
  domStorageEnabled={false}
  javaScriptEnabled={false}
  enableApplePay
  userAgent="Mozilla/5.0 (iPhone; CPU iPhone OS 14_0_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Mobile/15E148 Safari/604.1"
  sharedCookiesEnabled
/>
```

**To Reproduce:**

1. Create app that uses WebView
2. Go to [https://www.ebay.com.au](url) and pick any product then make all the checkout process until the Payment method.
3. Select `Afterpay` method then press `Pay with Afterpay` button

![New Project (1)](https://user-images.githubusercontent.com/69496694/146746018-539b3df4-41e5-4772-8579-78b9b3df1b79.gif)

**Expected behavior:**

After pressing `Pay with Afterpay`, should show the popup process of Afterpay then continue to complete the payment.

**Environment:**
 - OS: iOS
 - OS version: iOS 15.0
 - react-native version: 0.64.2
 - react-native-webview version: 11.14.3

**Comment by ecemac** [comment]
I'm having a similar issue where I try to pay with a credit card and with 3D Secure option. Everything works fine on all browsers and Android devices. I tried [this](https://stackoverflow.com/questions/42645946/ios-ssl-error-page-not-loading-in-wkwebview-but-loads-in-safari) solution but no luck. Any help would be appreciated.

**Comment by LinhNguyen1059** [comment]
Still need help :)

**Comment by ecemac** [comment]
> Still need help :)

For me,  I was setting the URL's on state as they changed, and it worked fine when I didn't set them on state.

**Comment by LinhNguyen1059** [comment]
Have you config anything else? @ecemac 

Cuz I don't have setState like you, but it still show that popup

**Comment by ecemac** [comment]
@LinhNguyen1059 nope, nothing else. You can try adding the following to your Info.plist if you already haven't:

`<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>	
	</dict>`

**Comment by lonewolfaka9** [comment]
+1

**Comment by Tech-LR** [comment]
+1

**Comment by saadsinpk** [comment]
+1

**Comment by Hadevs** [comment]
+1
