### ISSUE TITLE
macOS issue

### ISSUE THREAD

**Issue by jbcullis** [react-native-webview/react-native-webview#2250]
Steps to reproduce:
npx react-native init test --template react-native@^0.64.0
cd test
npx react-native-macos-init
npx react-native run-macos

So far, this works

npm install --save react-native-webview
cd macos 
pod install
cd ../
npx react-native run-macos 

** Many, many errors produced but if you open up Xcode you get:
<img width="279" alt="Screen Shot 2021-11-24 at 12 49 18 AM" src="https://user-images.githubusercontent.com/27532334/143182291-4ae14fdc-8d10-44b6-b016-fcf706102edd.png">

**Comment by Kyukishi** [comment]
same here,
using react-native@0.66.3 on macOS 12 with xcode 13.1
