### ISSUE TITLE
Android) navigator.mediaDevices is returning cameras with empty labels.

### ISSUE THREAD

**Issue by ruben-stripe** [react-native-webview/react-native-webview#2253]
**Bug description:**
In Android, `navigator.mediaDevices` is returning cameras with empty labels.

**To Reproduce:**
snack: https://snack.expo.dev/@ruben-stripe/react-native-webview__mediadevices_label

**Expected behavior:**
the same code from the browser I am receiving labels for the camera, but if I run it from inside a WebView in Android devices it is returning empty labels

**Environment:**
 - OS: Android
 - OS version: 12
 - react-native version: 0.65.1
 - react-native-webview version: 11.13.0

**Comment by lhr000lhr** [comment]
any updates?
