### ISSUE TITLE
WebView is incompatible with CSP?

### ISSUE THREAD

**Issue by cyberphone** [react-native-webview/react-native-webview#2260]
With Content Security Policy (CSP) you can protect Web pages from being infected by inline scripts.  Using `postMessage()` you can still communicate with an embedded IFRAME which is quite useful.  Using such a scheme with WebView does not seem to be possible, since WebView requires injected JavaScript in order to communicate.  I guess WebView doesn't care about CSP either?

**Comment by OneOfOne** [comment]
CSP is just a hint, it's up to the browser / webview component to honor it.
