### ISSUE TITLE
Cache is not getting cleared in android even after LOAD_NO_CACHE and cacheEnabled setting to false

### ISSUE THREAD

**Issue by rohitatcoffee** [react-native-webview/react-native-webview#2263]
**Bug description:**
Cache is not getting cleared in android even after 

**To Reproduce:**
Run on android 
`<WebView
                            onLoad={() => this.hideLoader()}
                            source={{
                                uri: this.state.source
                            }}
                            sharedCookiesEnabled={true}
                            cacheEnabled={false}
                            cacheMode={'LOAD_NO_CACHE'}
                        />`

**Expected behavior:**
Clear cache

**Environment:**
 - OS: Android 
 - OS version: OS 11
 - react-native version: "0.62.0"
 - react-native-webview version:"11.14.2"

**Comment by nirav-infostretch** [comment]
We are facing same issue. 

We are using this method to clear cache on Logout
      this.webview.clearCache(true);
      this.webview.clearHistory();

This was working react-native-webview : 8.0.6 version
After upgrading to 11.6.5 version, this is not working

**Below is env details**
react-native-webview : 11.6.5
react-native : 0.64.2
react : 17.0.1
node : 12.22.6
npm : 6.14.15

buildToolsVersion = "29.0.3"
minSdkVersion = 21
compileSdkVersion = 30
targetSdkVersion = 30
supportLibVersion = "28.0.0"

**Comment by rohitatcoffee** [comment]
I found the issue was on web pages. Fixed. I am closing this issue.

**Comment by tragicmj** [comment]
Still facing the same issue. Website is instagram

**Comment by rohitatcoffee** [comment]
> Still facing the same issue. Website is instagram

Try this code...

<WebView key={this.state.key} onLoad={() => this.hideLoader()} source={{ uri: this.state.source }} sharedCookiesEnabled={true} cacheEnabled={false} cacheMode={'LOAD_NO_CACHE'} clearHistory={true} javaScriptEnabled onMessage={this.onMessage.bind(this)} />
