### ISSUE TITLE
react-native-webview:compileDebugKotlin

### ISSUE THREAD

**Issue by h-assefi** [react-native-webview/react-native-webview#2266]
**Bug description:**
First time to use webview and just added it to my project.
I get the same error after every solution I checked on internet. But, I get no progress

Task :react-native-webview:compileDebugKotlin FAILED

 What went wrong:
Execution failed for task ':react-native-webview:compileDebugKotlin'.
> Could not resolve all artifacts for configuration ':react-native-webview:debugCompileClasspath'.
   > Failed to transform core-1.1.0.jar (androidx.core:core:1.1.0) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Could not find core-1.1.0.jar (androidx.core:core:1.1.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/core/core/1.1.0/core-1.1.0.jar

When I look for the link provided in the error log I get 404 Error.

**Environment:**
 - OS: Windows
 - OS version: 10
 - react-native version: 65
 - react-native-webview version: 11.15

**Comment by h-assefi** [comment]
I did a lot of tests and figured out that it was the gradle compatibility issue.
it appears  that my gradle version was 4.2.2 and after changing it to 3.6.0 with gradle wrapper of version 6.0.1 it works find now.
hope it helps

**Comment by TheEZIC** [comment]
> I did a lot of tests and figured out that it was the gradle compatibility issue. it appears that my gradle version was 4.2.2 and after changing it to 3.6.0 with gradle wrapper of version 6.0.1 it works find now. hope it helps

I have same issue now. Can you please provide more information how you change gradle wrapper version?

**Comment by h-assefi** [comment]
@TheEZIC 
for modifying gradel wrapper version go to '**android -> gradle -> wrapper -> gardle-wrapper.properties**' directory 
and for altering gradle version just modify below line in '**android -> build.gradle**' file.
```
dependencies {
        classpath("com.android.tools.build:gradle:3.6.0")
...
}
```

**Comment by Bilal-Abdeen** [comment]
The solution worked for me [#2568](https://github.com/react-native-webview/react-native-webview/issues/2568#issuecomment-1172557823)
