### ISSUE TITLE
iOS onMessage not called after postMessage in react-native-webView v11.14.2

### ISSUE THREAD

**Issue by SushilSharma12** [react-native-webview/react-native-webview#2267]
**Bug description:**

Earlier I was using react-native-webview v11.0.2 and everything was working fine. But due to some apple pay related requirement I had to upgrade version to 11.14.2.
After injecting JS using this function `this.webview.injectJavaScript(js)` the onMessage is not called in iOS. Android is working fine.

**To Reproduce:**

In 11.14.2 version, after I inject this JS 
`window.ReactNativeWebView.postMessage(document.documentElement.innerHTML)`
`using this.webview.injectJavaScript(js);` function, the onMessage is not called.

**Expected behavior:**

I am collecting some data in onMessage and then handling navigation. The onMessage should call.

**Environment:**
 - OS: iOS
 - OS version: 
 - react-native version: 0.60.2
 - react-native-webview version: 11.14.2

**Comment by hkar19** [comment]
strangely, it also happenend in:
- react-native version: 0.64.2
- react-native-webview version: 9.0.2

**Comment by SushilSharma12** [comment]
@hkar19 Were you find a solution to this?

**Comment by hkar19** [comment]
I don't know if i fixed the issue and whether my "solution" will fix yours, but i used `injectedScript` props to inject js, and strangely the issue went just like that. 
My code was just like when the bug arose, so maybe there's something wrong in my rendering process
