### ISSUE TITLE
Chrome or Safari Autofill Not Working

### ISSUE THREAD

**Issue by anutting** [react-native-webview/react-native-webview#2269]
**Bug description:**

An address, log in, or credit card form in the Chrome or Safari browser will prompt the user for autocomplete suggestions saved in their browser. The RNWebview, which uses these browsers, should also prompt the user for these autocomplete suggestions. 

**To Reproduce:**

Open a site with a log in or form in the browser and compare the autocomplete suggestions to the same page opened in the WebView.

**Expected behavior:**

A prompt for autofill suggestions

**Screenshots/Videos:**

**Environment:**
 - OS: iOS / Android
 - OS version: 15 / 12
 - react-native version: 0.66.1
 - react-native-webview version: 11.14.2

**Comment by lapis160** [comment]
I'm waiting for the feature as well
