### ISSUE TITLE
EME / DRM keysystems are not supported

### ISSUE THREAD

**Issue by GorgWorgington** [react-native-webview/react-native-webview#2271]
**Bug description:**
Navigator.requestMediaKeySystemAccess() exists which indicates that DRM support is enabled, but none of the keysystems are detected.

**To Reproduce:**
[This repository](https://github.com/GorgWorgington/spotifyWPReactNative/tree/bugreport) has a WebView in Components/SpotifyWebView/index.js which currently sources from "https://bitmovin.com/demos/drm" which indicates which types of drm are supported. Just start the app with `npm run android` and scroll down the page.

**Expected behavior:**
The page should indicate that at least one drm mode is supported.

**Environment:**
 - OS: Android
 - OS version: 11 (virtual machine), 9 (physical phone)
 - react-native version: 0.66.3
 - react-native-webview version: 11.15.0

**Comment by bulkinav** [comment]
Hi developers! Please consider this issue.

**Comment by timohofmeijer** [comment]
I’m having the same issue on my Android test device (Oppo A15). I’m wondering if the issue is specific to certain Android devices. On my iPhone DRM protected streams from both Spotify and Apple Music play without problems.

**Comment by spector32** [comment]
This is still an issue

**Comment by ColtraneNadler** [comment]
@timohofmeijer did you manage to find a solution?

**Comment by ColtraneNadler** [comment]
@spector32 find a solution?

**Comment by spector32** [comment]
@ColtraneNadler Nope. The only thing to do was to build this repo manually with patched parts that requires the `Encrypted Media Extensions`
