### ISSUE TITLE
Google Pay Not Working

### ISSUE THREAD

**Issue by dan-betmate** [react-native-webview/react-native-webview#2278]
We have a react-native-webview that shows a google pay button
When the google pay button is pressed 
Then the web browser is opened
and we are shown an error message "Unexpected developer error, please try again later"

![image](https://user-images.githubusercontent.com/71024249/145041673-2fc728f2-abcd-4612-97fb-39472d0447d0.png)

![image](https://user-images.githubusercontent.com/71024249/145041746-b76e74b3-94f2-4852-ac9e-58bc80b2b0e5.png)

I have ran the app so the user does not go to a react-native-webview and instead goes to the google chrome browser, and google pay worked. However this is an un-ideal flow as the app loses context of where the user is up to, and the user has to make their own way back to the app. 

Expected flow:
User presses google pay button in react-native-webview 
and google pay window opens from the button of the webview
![image](https://user-images.githubusercontent.com/71024249/145042787-d6b02ec7-3e6c-4564-a4d3-855536ac45ad.png)

**Comment by master96** [comment]
@dan-betmate  did you find any solution for this ?

**Comment by dan-betmate** [comment]
@master96 I did not unfortunately. I also closed this issue prematurely, it might be worth reopening it if you are also having the same issue.

**Comment by akhilsanker** [comment]
@dan-betmate ,

Have you solved this problem. I am facing the same now/

Thanks

**Comment by zain-khalid** [comment]
@dan-betmate @akhilsanker 
Have you solved this problem? I am facing the same issue.

**Comment by dan-betmate** [comment]
@zain-khalid  I did not unfortunately, we have paused looking for a solution for this for a while now.

**Comment by Wsm2018** [comment]
@dan-betmate Were you able to resolve this issue ? I am facing this same issue now.

**Comment by zain-khalid** [comment]
The issue isn't resolve. The solution that I implemented is integrate GooglePay SDK and handle GooglePay SDK from WebView. This works fine on my side.

**Comment by dinhbang** [comment]
I have the same issue. Who have any solutions to fix it?

**Comment by nickmcsimpson** [comment]
I'm having the exact same problem trying to get a web based Google Pay checkout workflow working in a Webview. I'm using a payment provider's SDK rather than using Google Pay directly in our web app and it pops the native browser just like the example above. Reaching out to the SDK providers, they said:

``` 
I've seen that error come up before with a merchant, and it turns out that they do not have pop ups enabled for that web browser. Do you have any extensions, apps, or programs that could potentially be blocking pop ups from happening?
```

I thought enabling the Webview to use `javaScriptCanOpenWindowsAutomatically={true}` would resolve this, but alas, it doesn't seem to have fixed anything. Would love to know if this has been solved for this Webview component.

**Comment by talhatsk** [comment]
anyone found the solution ?

**Comment by dmengelt** [comment]
Hi all. We are currently looking into supporting Google Pay for Android WebViews.

**Comment by hucki** [comment]
> Hi all. We are currently looking into supporting Google Pay for Android WebViews.

Hi @dmengelt, Thanks for letting us know. We are also facing the same problem in our eCommerce platform.
Can you point us to the actual issue in google pay, so we can follow the progress? And maybe also get some insights regarding the restrictions that prevent Google Pay working in Android Webview.

**Comment by dmengelt** [comment]
@hucki there are mainly two reasons why Google Pay does not work in an Android WebView:
- no [Payment Request API](https://caniuse.com/payment-request) support
- limited `window.open()` support

At the moment there is no publicly available issue you can follow. Let me try to organize this.

**Comment by hucki** [comment]
Hi @dmengelt 

thanks for your swift reply and the insights provided. We really appreciate this and are looking forward to being able to track progress on this issue. We added the Info provided to our internal documentation.

**Comment by dmengelt** [comment]
@hucki here you go: https://crbug.com/381849264

**Comment by lukeseo23** [comment]
@dmengelt will this fix be specific for Google Pay? We're looking into using [Google SPA](https://www.checkout.com/docs/payments/authenticate-payments/google-secure-payment-authentication) via the WebView component but need PaymentRequest API support as well. Wondering if that fix targeted for H1 2025 will possibly fix the issue

**Comment by dmengelt** [comment]
No this fix is not specific to Google Pay. As you mentioned, SPA relies on the PR API as well and therefore it will start to work within WebViews once we release the fix.

**Comment by willhowlett** [comment]
I notice the Chromium issue has been updated with some preliminary testing instructions, don't know if that is useful for this feature or if it's still too premature: https://issues.chromium.org/issues/381849264#comment10

Very excited to find this issue and discover that the feature may be available at some point (we're keen to avoid the native SDK route for our setup if possible)

**Comment by dmengelt** [comment]
following the test instructions is something this project could do to test everything. however, for Google Pay its still a bit premature. I will try to keep this issue updated once Google Pay can be tested as well 🙂

FYI we also published a blog post in the meantime: https://developer.chrome.com/docs/android/payments-in-webviews

**Comment by willhowlett** [comment]
Thankyou @dmengelt, that's really appreciated

**Comment by dmengelt** [comment]
alright. support for Google Pay is now also available. Please see the following guide:

https://developers.google.com/pay/api/android/guides/recipes/using-android-webview

**Comment by willhowlett** [comment]
That's great @dmengelt thankyou so much1

I'm assuming the next step will be for someone to make a PR against react-native-webview to support this new functionality? Maybe a new feature request is needed

**Comment by dmengelt** [comment]
@willhowlett that is correct!

**Comment by dmengelt** [comment]
something like this: https://github.com/dmengelt/react-native-webview/commit/eb1d17662decdd1bf78e254f69c37daead071b40

Let me know if I should create a PR.

**Comment by willhowlett** [comment]
@dmengelt a PR would be great! you're amazing. I was thinking of having a go but I'm not an android developer (I'm just a user of react-native-webview). Your branch above looks understandable and logical to me though (maybe something in the `paymentRequestEnabled` prop docs explaining this is needed for Google Pay support would be helpful)

**Comment by erwanlpfr** [comment]
I was doing the same right now, you got me! :D 
I'm not sure a PR would be accepted knowing the version is still an alpha.
But we still can use the branch as a dep.

I'm having troubles testing it, do you have any tricks or debug pages to test it ?

**Comment by dmengelt** [comment]
alright. I created #3763 

@erwanlpfr Check the [User device requirements](https://developers.google.com/pay/api/android/guides/recipes/using-android-webview#userrequirements) and [Early testing](https://developers.google.com/pay/api/android/guides/recipes/using-android-webview#early-testing) sections in the docs.

**Comment by willhowlett** [comment]
This may indicate a lack of knowledge on my part, but when trying to get the new functionality working in Expo (simply loading the test page https://rsolomakhin.github.io/pr/gp2-test/) it appears that window.PaymentRequest is not available

I appreciate this may be beyond the scope of this issue, but does anyone know if there are any additional configuration changes that would be needed within Expo to get the functionality working?

I have done a full build (i.e. I'm not just using Expo Go)

Many thanks

**Comment by dmengelt** [comment]
@willhowlett did you have a look at the [official docs](https://developers.google.com/pay/api/android/guides/recipes/using-android-webview)?

If you did, could you let me know the following:
- Google Play services version
- Chrome and Chrome WebView version

**Comment by willhowlett** [comment]
> [@willhowlett](https://github.com/willhowlett) did you have a look at the [official docs](https://developers.google.com/pay/api/android/guides/recipes/using-android-webview)?
> 
> If you did, could you let me know the following:
> 
> * Google Play services version
> * Chrome and Chrome WebView version

@dmengelt well now I feel foolish! I had read the docs (honest!) and thought I had updated Android System WebView. But when I just checked again it had an update available. After updating it now works, which is amazing! I could have sworn I'd already updated it

Thanks again!
