### ISSUE TITLE
iOS 15: iOS Websocket changes break webview's websocket functionality

### ISSUE THREAD

**Issue by dawnmist** [react-native-webview/react-native-webview#2281]
**Bug description:**
In iOS 15, Apple have set their new NSURLSession Websocket implementation as the default websocket to use within WKWebView. Unfortunately, this implementation has some bugs that are breaking the ability to actually connect websockets to multiple servers worldwide. Apple have been informed, but do not comment on the issue or whether they are actually working on fixing the problems that have been caused.

A summary of the issue can be seen at: https://developer.apple.com/forums/thread/685403

Turning off the permessage-deflate option on the websocket allows the socket to actually connect, but it frequently disconnects when receiving data from the server (i.e. connections often last only 3 seconds before disconnecting on the next message received). The thread on the issue with Apple states that there is a processing error for messages that are split across multiple websocket frames that causes the client's websocket to disconnect.

Is there a way to revert the webview to using the old Apple custom websocket implementation for websockets instead of the new NSURLSession Websocket when compiling the react-native app?

**Environment:**
 - OS: iOS
 - OS version: 15
 - react-native version: 0.61.4
 - react-native-webview version: 7.5.1

I am happy to put the work in to upgrade our react-native/react-native-webview versions if there is a known bugfix/workaround in the newer versions for this issue.

**Comment by nverwer** [comment]
It looks like Apple is not going to fix this. However, you can turn off NSURLSession, I found these instructions [https://cockpit-project.org/running/safari] useful, but disable “NSURLSession WebSocket” instead of enable.

Short summary:

 1. Open the Settings app
 2. Scroll down and tap on “Safari”
 3. Scroll down to the bottom and tap on “Advanced”
 4. Tap on “Experimental Features” at the bottom
 5. Scroll down until you see “NSURLSession WebSocket”
 6. Disable “NSURLSession WebSocket”

**Comment by dawnmist** [comment]
Modifying user devices for all people using the application is not a viable option, which is why we have been looking for an application-level modification rather than asking every user to make modifications to their device.

**Comment by andrewleong** [comment]
+1

**Comment by rahulazmeera** [comment]
ours is in same situation. We are leveraging aws iot for communication which internally uses websocket (in WebView), this is broken when the apple device is configured to use proxy and works fine if we remove the proxy.  platform: iOS 15.2, React-Native app.  This was working fine until 14.8 iOS. please let us know if any workaround available.

**Comment by zsinba** [comment]
+1

**Comment by wongtszchiu** [comment]
+1

**Comment by SkylarkingMonkey** [comment]
Has anyone found a solution to this?

**Comment by maison-shibumi** [comment]
+1 this is a big problem

**Comment by deepak-vanco** [comment]
any updat on this issue?

**Comment by ZerototoFive** [comment]
该问题有任何更新吗？
