### ISSUE TITLE
Pass WebView cookie to Safari

### ISSUE THREAD

**Issue by RyanLinXiang** [react-native-webview/react-native-webview#2284]
Dear all,

I have a few PDF files on my website, which should be opened in the browser. In WebView these files should not be opened in WebView directly (as they will get stuck and there is no way to navigate back) but by Safari externally. The tricky thing is that I need to send cookies to Safari so that authentification can be done - otherwise the files won't be accessed. My question is: is that possible? 

I tried the following with React Native Cookies which does not work:

```
<WebView
            source={{
              url,
              headers: {
                Cookie: `authToken=${this.state.cookie}`, // cookie is read from React Native Cookies manager
              }
            }}
            sharedCookiesEnabled
/> 
```

When Safari opens the link - the cookie info is not passed along.

**Comment by girish-floorzap** [comment]
Hi Ryan, I am also facing the same issue for ios. Please help me if you have found any solution for your problem.
