### ISSUE TITLE
Keyboard is overlapping input on iOS with KeyboardAvoidingView

### ISSUE THREAD

**Issue by theofournier** [react-native-webview/react-native-webview#2285]
**Bug description:**

The keyboard is overlapping an input inside a `WebView` on iOS only, with the property `scrollEnabled` set to `false` and wrapping the `Webview` inside a `KeyboardAvoidingView` component. 

The `KeyboardAvoidingView` component is doing his job by adding bottom-padding and the web page has a scrollview that allow the user to scroll when the screen shrinks, but the web page is not automatically scrolling to display the input when the keyboard is displaying.

The Android app has no issue, it is not using the `KeyboardAvoidingView` component and it has `android:windowSoftInputMode="adjustResize"` inside the `AndroidManifest`.

**To Reproduce:**

The code looks like this :

```jsx
<KeyboardAvoidingView
  behavior={isIos ? 'padding' : null}
  enabled={isIos}
>
    <WebView
          androidLayerType={'hardware'}
          hideKeyboardAccessoryView={true}
          domStorageEnabled={true}
          cacheEnabled={true}
          overScrollMode={'never'}
          scrollEnabled={false}
          originWhitelist={['*']}
          source={{
            html: `
            <html>
              <head>
                <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0" />
              </head>
              <body>
                <div style="overflow: auto; height: 100%">
                  <div style="height: 500px">
                    <p>Start</p>
                  </div>
                  <input />
                </div>
              </body>
            </html>
          `,
          }}
        />
</KeyboardAvoidingView>
```

**Expected behavior:**
The webpage should automatically scroll to display the input when the keyboard open on iOS.

**Screenshots/Videos:**
On iOS:

<img src="https://user-images.githubusercontent.com/25389865/146038257-9d50d4e1-e816-4aee-87aa-c8aaf2038ee7.gif" width="250" >

On Android (how it should work):

<img src="https://user-images.githubusercontent.com/25389865/146038495-9bf95931-97ad-4aaa-9302-ceaf91e732e5.gif" width="250" >

**Environment:**
 - OS: iOS
 - OS version: iOS 14
 - react-native version: 0.64.2
 - react-native-webview version: 11.13.0

**Comment by TheAlmightyBob** [comment]
Your code sets `scrollEnabled` to `false`. From the [docs](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#scrollenabled):
> Setting this to false will prevent the webview from moving the document body when the keyboard appears over an input.

Have you tried setting it to `true`?

**Comment by theofournier** [comment]
@TheAlmightyBob 
Thanks for your reply !

Yes, when I set it to `true`, the screen is moving well. But then, 2 scroll bars appear: the one from the `WebView` component and the one from the web page.

<img src="https://user-images.githubusercontent.com/25389865/148611056-9dde2361-dcdc-4630-9865-9b87c19a7424.gif" width="250" >

And I only want the web page handling the scroll, not the component.

**Comment by TheAlmightyBob** [comment]
That seems like more of an issue with the web page to me, although I'm not an expert there. But the few times I've seen this sort of thing in the past, it was an issue with the web page (which meant it was somebody else's problem so I don't know any more than that).

Unless you have the WebView wrapped in a ScrollView and you're seeing the scrollbar from _that_...?

**Comment by abdurrehmaan** [comment]
Hi, I m facing the same issue, but not in react native, I m testing my web app on different devices using browserstack, and on android devices, when i use to add comment, keyboard overlaps the text field, How can I fix this issue in react js
![image](https://user-images.githubusercontent.com/29798155/211184173-fc5ef683-c7d3-414d-807e-193a92703602.png)

**Comment by MarcusPOliveira** [comment]
@theofournier any solution to this problem?
