### ISSUE TITLE
How to Inject dynamic vars into React Native's WebView's injectedJavaScript string?

### ISSUE THREAD

**Issue by shivika24** [react-native-webview/react-native-webview#2289]
How to use dynamic variables inside injectedJavaScript? 

const name = 'shivika'; 
const myScript = `
console.log('*****',${name})
 true`
 
 <WebView source={{uri: 'uri'}} injectedJavaScript={myScript} />

**Comment by TheAlmightyBob** [comment]
I don't understand the question. Does the code in your example not work?
