### ISSUE TITLE
window.ReactNativeWebView.postMessage(data) and onMessage doesn't work on release apk mode. [only works in debug mode]

### ISSUE THREAD

**Issue by jose1937JS** [react-native-webview/react-native-webview#2292]
**Bug description:**

Hello, i'm trying to send data from my web page to my react native app through this library, using a phone phisical android and it only perfectly works in debug mode. **When i build it for production, it doesn't work**, `window.ReactNativeWebView.postMessage(data)` does nothing.

**Expected behavior:**
Capure the data sent from my web page in release apk mode

**Screenshots/Videos:**
Code from my web page
![Screenshot at 2021-12-19 14-40-24](https://user-images.githubusercontent.com/20506655/146687164-a74c3784-b0e2-43d7-a9fd-7e4dd242d60e.png)

code from my RN app
![Screenshot at 2021-12-19 14-56-43](https://user-images.githubusercontent.com/20506655/146687301-13c23977-aeea-44a0-b123-0699812608b1.png)

**Environment:**
 - OS: android
 - OS version:  8.1.1
 - react-native version: 0.63.4
 - react-native-webview version: 11.15.0 => I was trying another version 9.0.2 and it didn't work either

**Comment by tero-paananen** [comment]
let message = "hello";
`webView.injectJavaScript(getInjectableJSMessage(message));` 


```
function getInjectableJSMessage(message) {
  return 
    `(function() {document.dispatchEvent(new MessageEvent('message', {data: ${JSON.stringify(
      message
    )}}));})();`
}
```

Try `injectJavaScript` to inject `new MessageEvent`

**Comment by jose1937JS** [comment]
> let message = "hello"; `webView.injectJavaScript(getInjectableJSMessage(message));`
> 
> ```
> function getInjectableJSMessage(message) {
>   return 
>     `(function() {document.dispatchEvent(new MessageEvent('message', {data: ${JSON.stringify(
>       message
>     )}}));})();`
> }
> ```
> 
> Try `injectJavaScript` to inject `new MessageEvent`

Thanks for answering @tero-paananen. That method wouldn't work because I need to send data from the web to react native, and that way I can't access the data I'm going to send

**Comment by isaac-tcs** [comment]
I'm having same issue. In my case, I'm trying to get events from iframe video but it only works on browser and not on react native via webview.

```javascript
    window.onmessage = function (event) {
      if (event.data.event == "play") {
        alert('lll');                                     // this won't fire
        sendEvent(event.data.event, event.data.data);
      }
      if (event.data.event == "pause") {
        sendEvent(event.data.event, event.data.data);
      }
      if (event.data.event == "ready") {
        sendEvent(event.data.event, event.data.data);
      }
      if (event.data.event == "timeupdate") {
        sendEvent('playing', event.data.data);
      }
      if (event.data.event == "ended") {
        sendEvent('end', event.data.data);
      }
    };

    const sendEvent = (evt, data) => {
      // Passes events through the bridge
      console.log("event", evt);
      var payload = {
        name: evt,
        data: data,
      };
      window.ReactNativeWebView.postMessage(JSON.stringify(payload));
    };
```

```javascript
  const INJECTEDJAVASCRIPT =
    "const meta = document.createElement('meta'); meta.setAttribute('content', 'width=device-width, initial-scale=1, maximum-scale=0.99, user-scalable=0'); meta.setAttribute('name', 'viewport'); document.getElementsByTagName('head')[0].appendChild(meta);";

<WebView
      allowsFullscreenVideo={true}
      onLoadEnd={() => console.log('live load enddddddddddddddddd')}
      source={{
        html: LivePlayer(videoId),
      }}
      javaScriptEnabled={true}
      ref={ref}
      onMessage={onBridgeMessage}
      bounces={false}
      scrollEnabled={false}
      scalesPageToFit={scalesPageToFit}
      onError={error => console.error(error)}
      style={[
        {
          marginTop: -8,
          marginLeft: -10,
        },
        style,
      ]}
      containerStyle={containerStyle}
      setBuiltInZoomControls={false}
      setDisplayZoomControls={false}
      automaticallyAdjustContentInsets
      onNavigationStateChange={a => console.log(a?.url)}
      injectedJavaScript={INJECTEDJAVASCRIPT}
    />
```

**Comment by tero-paananen** [comment]
One issue in your code that i noticed is that Windows WebView does not have injectedJavaScript prop it is function that you can call after WebView is loaded by webView.injectedJavaScript

**Comment by incleaf** [comment]
I faced the same issue. After a few hours of debugging, I figured it out it was because of ProGuard.
ProGuard obfuscated the onMessage method in the release build. I fixed it by updating ProGuard rules to keep the method names.

**Comment by aubert-creation** [comment]
> I faced the same issue. After a few hours of debugging, I figured it out it was because of ProGuard. ProGuard obfuscated the onMessage method in the release build. I fixed it by updating ProGuard rules to keep the method names.

hey @incleaf,
Can you explain how you updating ProGuard rules ?

**Comment by nabinkumarn** [comment]
Hello, has anyone fixed this, for me onMessage is working but onNavigationStateChange returns empty url data when proguard is enabled on android. iOS is working fine. I have tried to use several ways to add proguard rules
`# React Native WebView
-keep class com.reactnativecommunity.webview.** { *; }
-keepclassmembers class com.reactnativecommunity.webview.** { *; }
`
But this is not working.

**Comment by nazmeln** [comment]
Hey @nabinkumarn,
Any luck with adding proguard rules for this package?

**Comment by nabinkumarn** [comment]
> Hey @nabinkumarn, Any luck with adding proguard rules for this package?

No, i had to disable proguard. Updated react native to enable hermes, worked on other security concerns and disabled proguard.
