### ISSUE TITLE
Need onfiledownload for Android

### ISSUE THREAD

**Issue by putuoka** [react-native-webview/react-native-webview#2294]
in my case i need to download a pdf file via webview and then call back function when file successfully downloaded. this code is working fine in IOS but i can't find for Android.

<webview
...
onFileDownload={({ nativeEvent: { downloadUrl, canGoBack } }) => {
                    Linking.openURL(downloadUrl)
                        .then(() => {
                            if (canGoBack) {
                                wv.current.goBack()
                            } else {
                                if (props.navigation.canGoBack()) {
                                    props.navigation.goBack()
                                } else {
                                    props.navigation.replace('Main')
                                }
                            }
                        })
                        .catch((er) => {
                            Alert.alert('Failed to open Link: ' + er.message)
                        })
                }}
...
/>

**Comment by jihanarifia** [comment]
I need this too :(
