### ISSUE TITLE
White screen on iOS + injectJavaScript does not work in that state

### ISSUE THREAD

**Issue by skvariljan** [react-native-webview/react-native-webview#2298]
**Bug description:**

When we leave our app in the background mode on iOS for a white and then bring it back to the active state, the webview fails to render the content and renders only a white screen. This issue is non-deterministic, happens only from time to time and not on all devices.

We found out that restarting the app or calling `reload()` method of the webview resolves the issue. The main problem is how to detect this state. We figured out that when a blank screen is shown, `injectJavaScript` does not work at all, i.e. even `injectJavaScript('alert("Test");')` does not work (alert is not shown).

So we are currently trying to detect this state by sending a message from within the webview when the app is taken back to the 'active' state by calling `injectJavaScript('window.ReactNativeWebView.postMessage("app.healthCheck");')`. We set a 1s timeout and if this message is not received by the `onMessage` handler, we reload the webview.

Is there a better way to fix this issue?

**To Reproduce:**

It's hard to reproduce, completely non-deterministic. Happens only from time to time on iOS.

**Expected behavior:**

The app is in the same state as it was before bringing it to the background state, i.e. webview paints the content of the current URL, not a blank page.

**Environment:**
 - OS: iOS
 - OS version: 15.2
 - react-native version: 17.0.2
 - react-native-webview version: 11.15.0

**Comment by emin93** [comment]
We had the same issue and fixed it by handling `onContentProcessDidTerminate` and re-mounting the WebView when the app becomes active again.

https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#oncontentprocessdidterminate

**Comment by skvariljan** [comment]
@emin93 Thank you pointing me in that direction, it's much simpler this way. We're currently testing that solution, seems to be working so far.

**Comment by fatihyildizhan** [comment]
Thanks @emin93 

This could be a bad practice but solved my issue.

```
const [isReloaded, setIsReloaded] = React.useState(false);
const webViewRef = React.useRef<WebView>(null);

<WebView
      ref={webViewRef}
      style={{ flex: 1 }}
      onLoadStart={() => Loading.show('Loading')}
      onLoadEnd={() => {
        Loading.hide();
        if(!isReloaded) {
          webViewRef.current?.reload()
          setIsReloaded(true);
        }
      }}
      originWhitelist={["https://*"]}
      source={{ uri: url }}
      startInLoadingState={true}
    />
```

**Comment by mabakach** [comment]
I had the same problem 

As a work arround I reload the web view every time the view gets the focus or the app returns from inactive or background state to foreground state. On my phone the problem occoured every time after the app was in the background for a longer time (half an hour or more)

**Environment**
- OS: iOS
- OS version: 15.1
- react-native: 0.62.3
- react-native-webview: 11.2.3

**Comment by skvariljan** [comment]
@mabakach Try the solution described by @emin93 , works fine in our case so far. Reloading a webview seems to sufficient instead of creating a new instance.

**Comment by damianimashaun** [comment]
I had the white screen issue, and this solution worked for me;
i) `webViewRef.current.stopLoading()` when app goes to the background,
ii) `webViewRef.current.requestFocus()` when app comes to foreground.

**Comment by dgbelidji** [comment]
Hello, i have the same issue on IOS when i reload i get a white screen. I didn't understand how fixed it with the `onContentProcessDidTerminate `, can i have more explanation please ?

**Comment by skvariljan** [comment]
@dgbelidji This is a minimum working example:

`import React, { useRef } from 'react'
import { WebView } from 'react-native-webview'

const App = () => {
    const webViewRef = useRef()

    return (
        <WebView
            source={{ uri: 'https://www.google.com/' }}
            onContentProcessDidTerminate={() => webViewRef.current.reload()}
            ref={webViewRef}
        />
    )
}`

**Comment by dgbelidji** [comment]
Thank you for your answer, but i still not understand when the content did terminate ? i have to close the webview ?

**Comment by dgbelidji** [comment]
Okay i see, so i think my problem is a little bit different because i just want to reload the webview when i do some action like change settings on that or after highlight. In that case the `onContentProcessDidTerminate ` props will not healped me right ? For example how can i reload the webview by clicking on a button ?

**Comment by skvariljan** [comment]
@dgbelidji Very similar to the example above, something like the code below should do it.

I would recommend you to read a documentation of webview and some tutorials for react native. This is a very different problem indeed, please open a new thread for your questions, so we don't mix it together. Thank you.

```
import React, { useRef } from 'react'
import { Text, TouchableOpacity } from 'react-native'
import { WebView } from 'react-native-webview'

const App = () => {
    const webViewRef = useRef()

    return (
        <>
            <WebView source={{ uri: 'https://www.google.com/' }} ref={webViewRef}/>
            <TouchableOpacity onPress={() => webViewRef.current.reload()}>
                <Text>Reload</Text>
            </TouchableOpacity>
        </>
    )
}
```

**Comment by dgbelidji** [comment]
#2357 https://github.com/react-native-webview/react-native-webview/issues/2357#issue-1120510838

**Comment by vishva-shukla** [comment]
> @dgbelidji The `onContentProcessDidTerminate` property is a callback you pass to webview which is called on iOS when the native content rendering process gets terminated (due to low memory or whatever reason iOS finds to terminate it). You can do whatever you want in the callback, like reloading the webview, which brings the content process back to life.
> 
> You can read the docs here: https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#oncontentprocessdidterminate

I hope this solution is not going into an infinite loop right

**Comment by jstoone** [comment]
After a lot of searching I've found a reliable way of reproducing the termination callbacks. It does require you to run the app in a simulator, but personally I like this better than opening 20-ish apps on my physical device and hoping not to actually crash/terminate the app itself.

Solution background
1. The simulator has a process ID on your computer
2. Each process of the simulator is a sub-process on your computer
3. You can utilize `pgrep` to find the launched simulator and any running instances of `WebKit.WebContent'
4. After finding the processes, you can utilize `kill` to terminate them, and thereby trigger `onContentProcessDidTerminate`.

Here's my Gist:
https://gist.github.com/jstoone/c7b5a37dedc7cd2bab3696ca387e85f0

I hope this helps someone in the future. ❤️

**Comment by MatthiasDh** [comment]
Seem to be having a very very similar issue, but onContentProcessDidTerminate does not get called in our instance. Any ideas?

**Comment by smohadjer** [comment]
Would cookies get lost when webview is terminated? I have a problem that webview loses cookies after it has been in background for some time like an hour or so.
