### ISSUE TITLE
Android - WebView renders incorrectly on large heights

### ISSUE THREAD

**Issue by flashjames** [react-native-webview/react-native-webview#2299]
**Bug description:**
Webview doesnt render full page, i.e. after a certain point scrolled the screen is just white and it's always at the same height it stops rendering.

I've tested with my local chrome/firefox and emulating mobile device, and it doesnt happen there.

Basically same issue, as this closed issue that was never solved:
https://github.com/react-native-webview/react-native-webview/issues/2129

**To Reproduce:**
```
import React from "react";
import { WebView } from "react-native-webview";
import { View } from "react-native";

  const webViewContent = {
    borderBottomColor: colors.paleGray,
    borderBottomWidth: 1,
    flex: 1,
    flexDirection: "row",
    opacity: 0.99,
    paddingHorizontal: 0,
    paddingVertical: 20,
    margin: 0,
    height: 5000,  //4500 works
    width: "100%"
  },

  const html = "This is a test".repeat(100)

  export default Content = () => {
    return (
        <WebView
          style={webViewContent}
          source={{ uri: "https://lyko.com/sv/yves-saint-laurent?sortBy=popularity&count=72&p_category=1073744429__CatalogContent&infinitescroll=1"}}
        />
    )
  };`
```

**Expected behavior:**
Keep rendering page.

**Environment:**
 - OS: Android - same on multitude of devices
 - OS version: Android - same on multitude of devices
 - react-native version: "react-native": "0.64.3",
 - react-native-webview version: "react-native-webview": "11.15.0",

**I've searched this project's github issues, both closed and open, the keywords I used is:**
- render
- blank

***The intresting issues***
- **coming**

**Things tried and doesnt work**
- setting androidLayerType="hardware" or androidLayerType="software" or androidLayerType="none"
as mentioned here: https://github.com/react-native-webview/react-native-webview/issues/2129#issuecomment-897580591
- <WebView style={{width: Dimensions.get('window').width, height: Dimensions.get('window').height}}/>
as mentioned here: https://github.com/react-native-webview/react-native-webview/issues/1426#issuecomment-738488835
- <WebView containerStyle = {{marginTop: 20, width: Dimensions.get('window').width, height: Dimensions.get('window').height}}/>
- as mentioned here: https://github.com/react-native-webview/react-native-webview/issues/1426#issuecomment-846459044

I've also set all these attributes on webview, and no errors reported.
```
onContentProcessDidTerminate={(syntheticEvent) => {
    const { nativeEvent } = syntheticEvent;
    console.warn('Content process terminated, reloading', nativeEvent);
    this.refs.webview.reload();
  }}
            onError={(syntheticEvent) => {
    const { nativeEvent } = syntheticEvent;
    console.warn('WebView error: ', nativeEvent);
  }}
             onRenderProcessGone={syntheticEvent => {
    const { nativeEvent } = syntheticEvent;
    console.warn(
      'WebView Crashed: ',
      nativeEvent.didCrash,
    );
  }}
```

**Possible solution** 
Talked about here:
- https://github.com/react-native-webview/react-native-webview/issues/482#issuecomment-481335056
- https://coderedirect.com/questions/108874/android-webview-renders-blank-white-view-doesnt-update-on-css-changes-or-html

Will be trying these asap i.e. working on implementing this, so far only used react-native libraries and not made changes to them, so will be learning how to make native library changes and getting that code to run.

**Extra**
Logs from the device for the app (nothing interesting it seems): https://pastebin.com/KrWmLZKc

**Screenshots/Videos:**
![Screenshot from 2021-12-25 17-21-10](https://user-images.githubusercontent.com/359702/147390229-e3e97563-92db-4448-bfc9-3c6946b5c8a4.png)

**Comment by flashjames** [comment]
I tested on native android webview and the bug was still present, i.e. the bug is specific to native android webview and not react-native-webview library.

What finally fixed the bug on the page was injecting this css code:
```

img {
    -webkit-transform: none !important;
    will-change:unset !important;transition: none !important;
    transform: none !important;
}
```

Found clues in these links:
- https://developer.mozilla.org/en-US/docs/Web/CSS/will-change
- https://stackoverflow.com/questions/16517464/remove-applied-css-transformation
- https://stackoverflow.com/questions/8840580/force-dom-redraw-refresh-on-chrome-mac
- https://stackoverflow.com/a/14871911/337587
- This didnt work: https://stackoverflow.com/a/13500453/337587

**Comment by putuoka** [comment]
it's been 6 month and i have similar issue. sadly injecting css code didn't work for me :(

btw @flashjames solution is only or local html source. for url source can use injectedJavaScriptBeforeContentLoaded props

**Comment by ViktorOsadchyi** [comment]
@flashjames Unfortunately your solution didn't work for me.
in sentry we see rare reports of android crashes, androidHardwareAccelerationDisabled was added for this, however, with this props, large content is no longer displayed

**Comment by flashjames** [comment]
@ViktorOsadchyi I had more bugs on android  webview(for example not getting back/forward work well), so I switched to firefox/mozilla developed: GeckoView - https://mozilla.github.io/geckoview/ for the android part of the app.

**Comment by putuoka** [comment]
> @ViktorOsadchyi I had more bugs on android webview(for example not getting back/forward work well), so I switched to firefox/mozilla developed: GeckoView - https://mozilla.github.io/geckoview/ for the android part of the app.

How do you use GeckoView in react native?
