### ISSUE TITLE
Webview Header cookie is not working in ios

### ISSUE THREAD

**Issue by girish-floorzap** [react-native-webview/react-native-webview#2301]
I wanted to implement cookie base authentication in webview, so I have send cookie in header as mentioned in the document and it working fine in android as well. But it is not working in ios.

below is my code

<WebView
                    javaScriptEnabled
                    originWhitelist={['*']}
                    sharedCookiesEnabled={true}
                    domStorageEnabled={true}
                    startInLoadingState={true}
                    scalesPageToFit={true}
                    thirdPartyCookiesEnabled={true}                    
                   source={{
                     uri: url,
                    headers: {
                        Cookie: `CookieName=${authCookie}:domain=domainName:path=/;`,
                    },
                }}
                />

As this same code is working for android, it should also work for ios. Please let me know if I have to implement any other alternative for ios.

**Environment:**
 - OS: Mac OS
 - OS version: 11.6.1
 - react-native version: 0.63.3
 - react-native-webview version: 11.2.3

Thank you.

**Comment by nikhilthakur001** [comment]
Same issue, cookies working fine on android, but not on iOS. Any update?

**Comment by guanyuan** [comment]
Same issue, cookies working fine on android, but not on iOS. Any update?
It's ok before.I don't know when it is broken.
