### ISSUE TITLE
IOS WebView White Screen Issue

### ISSUE THREAD

**Issue by billy220** [react-native-webview/react-native-webview#2302]
**Bug description:**
When the webview's height is set to 100%, all resources are loaded and rendering is confirmed in the debugger, but only a white screen is shown on the screen when you reach a back from a specific screen.
When the screen is scrolled, the screen appears normally.

If the height of the WebView is set to a value other than 100%, such as 99.9% or 100.1%, the phenomenon does not occur.

Has anyone ever experienced this issue? The solution was to set the height to 99% as above, but I want to know the cause.

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**
![image](https://user-images.githubusercontent.com/96406881/147531344-27b045fa-b787-4bde-8e1b-9741c284daca.png)
![image](https://user-images.githubusercontent.com/96406881/147531380-1f4bc533-de26-41f4-960c-2d029982f215.png)
All resource loaded but not seen

**Environment:**
 - OS: iOS
 - OS version: iPhone 13 mini(All version also)
 - react-native version: 0.65.1
 - react-native-webview version: 11.13.0

**Comment by tinyCoder32** [comment]
Same here.

**Comment by fatihyildizhan** [comment]
I have the same issue for iOS and Android. It was working until this month. I didn't change package.json

```
"react-native-webview": "^10.9.2",
"react": "16.13.1",
"react-native": "^0.63.4",
"typescript": "^4.4.4"
```

**Comment by fatihyildizhan** [comment]
#2298 You may check the solution from here https://github.com/react-native-webview/react-native-webview/issues/2298#issuecomment-1003744214

**Comment by terryhendrix1990** [comment]
This is due to the content process being stopped in IOS (most likely), perhaps this may help:
https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#oncontentprocessdidterminate

**Comment by serhii-kucherenko** [comment]
onContentProcessDidTerminate⬆
Function that is invoked when the WebView content process is terminated.

Type	Required	Platform
function	No	iOS and macOS WKWebView
iOS Web views use a separate process to render and manage web content. WebKit calls this method when the process for the specified web view terminates for any reason. The reason is not necessarily a crash. For instance, since iOS WebViews are not included in the total RAM of the app, they can be terminated independently of the app to liberate memory for new apps the user is opening. It's not unexpected to have WebViews get terminated after a while in the background.

Example:

<WebView
  source={{ uri: 'https://reactnative.dev' }}
  onContentProcessDidTerminate={(syntheticEvent) => {
    const { nativeEvent } = syntheticEvent;
    console.warn('Content process terminated, reloading', nativeEvent);
    this.refs.webview.reload();
  }}
/>

**Comment by HyopeR** [comment]
Hello. I was having a problem with this recently.

I was trying to show my documents via webview with **https://docs.google.com/gview**. However, it did show up sometimes. Sometimes I was seeing a **white blank screen**.

After examining various solutions, I realized that we can do this.

````
const webViewRef = useRef();

<WebView
   ref={webViewRef}
   syle={flex: 1}
   source={{uri: uri}}
   onLoadEnd={data => {
      const {nativeEvent} = data;
      const {title} = nativeEvent;

      if (!title.trim()) {
         webViewRef.current?.stopLoading();
         webViewRef.current?.reload();
      }
   }}
/>
````

What we're doing here is basically checking the title of the requested page. And refreshing the page if it failed to fetch the title.

**Comment by TzachPony** [comment]
I resolved the issue by setting the `refreshControlLightMode` prop to false. 
You can find more details about this prop in the [React Native WebView documentation](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#refreshControlLightMode).
