### ISSUE TITLE
[Question] Webview font size is auto adjusting as system font size

### ISSUE THREAD

**Issue by urinipni** [react-native-webview/react-native-webview#2303]
I wrote a simple webpage. This page only contains `marquee` element.
```
<style>
  #text {
      padding: 0;
      font-size: 65vh;
  }
</style>
<marquee behavior="scroll" scrollamount="50" id="text">hello world</marquee>
```

And I wraped this page as a webview in React Native.

```
export default function App() {
  return (
    <WebView 
      source={{ uri: `https://marquee-page-url.com`}}
    />
  );
}
```

It works like the below image. It works perfectly.
![KakaoTalk_Photo_2021-12-28-23-30-33 002](https://user-images.githubusercontent.com/60772837/147576499-c23b477e-59f3-4f5b-8ac3-b54a26989728.jpeg)

But if I change system (Android's) font size, than it works wrong. The font is too big.
![KakaoTalk_Photo_2021-12-28-23-30-33 001](https://user-images.githubusercontent.com/60772837/147576547-7ec39856-8f3d-415a-9b75-553b0bf1f3ba.jpeg)

I'm suspecting that system font size is effecting webview's font size. I want webview's font size to be fixed. How to do this?

**Comment by TheAlmightyBob** [comment]
Have you tried [textZoom](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#textzoom)?

**Comment by urinipni** [comment]
@TheAlmightyBob Thanks. it works! Maybe next time I should look at props list :)

**Comment by echagnas** [comment]
Hi, just tested, but works only on Android... not iOS.

**Comment by TheAlmightyBob** [comment]
@echagnas My understanding is that scaling to the system font size is simply not a feature of the iOS webview and would need to be addressed by the web page (or there are some possible workarounds out there using javascript injection)

**Comment by anniewey** [comment]
@TheAlmightyBob Are u able to scale based on system font size in iOS?

**Comment by TheAlmightyBob** [comment]
@anniewey Not currently. My team is exploring options there but hasn't yet landed on one, and currently it looks like the options involve changing the original web content and/or using Javascript injection... i.e. there doesn't seem to be a feature of the WebView itself for it.

**Comment by devinkg** [comment]
> Have you tried [textZoom](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#textzoom)?

This worked for me in Android, Thanks.
