### ISSUE TITLE
How to use urls within urls

### ISSUE THREAD

**Issue by puneetkansal04** [react-native-webview/react-native-webview#2306]
import React, { Component } from 'react';
    import { StyleSheet, Text, View } from 'react-native';
    import { WebView } from 'react-native-webview';
    
    // ...
    class MyWebComponent extends Component {
      render() {
        return <WebView source={{ uri: 'https://reactnative.dev/' }} />;
      }
    }

I am using this above code and i want to add some keys in the url like and some keys in this to process it. Like below

https://reactnative.dev/?daj
https://reactnative.dev/?meni

So this is working fine. But for initial url So i want that when i click on any link this url and this creates a new url like

https://reactnative.dev/docs/getting-started

so i want that it will add some keys in this like above 

?daj

So i am not getting how can i do with this url to url moving within webview. Please check and let me know. Thanks

**Comment by TheAlmightyBob** [comment]
You can handle `onShouldStartLoadWithRequest`, cancel the original load, and load your desired modified URL instead.
