### ISSUE TITLE
Video in iframe autoplay issue

### ISSUE THREAD

**Issue by natalliakaranevich** [react-native-webview/react-native-webview#2307]
**Bug description:**
Video still autoplay in inline mode with `mediaPlaybackRequiresUserAction={true}` with iframes

**To Reproduce:**
I have provided iframe with video as a `source` into `WebView` (for example https://cdn.iframe.ly/Zh7QLJ5?app=1)

```
<head>
<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\" />
<style>
  body { margin: 0; padding: 0 }
  .iframely-responsive {
      top: 0; left: 0; width: 100%; height: 0;
      position: relative; padding-bottom: 56.25%;
  }
  .iframely-responsive>* {
      top: 0; left: 0; width: 100%; height: 100%; position: absolute; border: 0;
  }
</style>
<script src=\"https://cdn.iframe.ly/embed.js\"></script>
</head>
<body>
<div>
  <div style=\"left: 0; width: 100%; height: 0; position: relative; padding-bottom: 87.6%;\">
    <iframe src=\"https://cdn.iframe.ly/Zh7QLJ5?app=1\" style=\"top: 0; left: 0; width: 100%; height: 100%; position: absolute; border: 0;\" allowfullscreen></iframe>
  </div>
</div>
</body>
```

**Expected behavior:**
Video is not plays before user actions

**Screenshots/Videos:**

https://user-images.githubusercontent.com/30589332/147737536-007aa3d9-77d1-42d0-8b30-3a8901d9edc8.mov

**Environment:**
 - OS: IOS
 - OS version: 14.5
 - react-native version: 0.64.1
 - react-native-webview version: 11.15.0

**Comment by MetaBenji** [comment]
@natalliakaranevich did you ever find a solution?  I'm having the same issue with videos auto playing on iOS

**Comment by jamaghafoor** [comment]
Still waiting for the solution
