### ISSUE TITLE
react-native-webview and json fetch session are different

### ISSUE THREAD

**Issue by apsuva** [react-native-webview/react-native-webview#2310]
Before the webview was removed from the React Native core, session was shared on all pages when I logged in webview. example json fetch was working with webview session. now all pages sessions work differently . how can I fix that?

**Comment by TheAlmightyBob** [comment]
Have you tried [sharedCookiesEnabled](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#sharedCookiesEnabled)?
