### ISSUE TITLE
[SOLVED] Linking.openURL [Possible Unhandled Promise Rejection]

### ISSUE THREAD

**Issue by mgscreativa** [react-native-webview/react-native-webview#2317]
**Bug description:**
My website has a WhatsApp floating button and when clicking it, I was able to open the WhatsApp native application from that button, but I'm getting a warning in the metro console.

Trying to open **Linking.openURL(url)** from **onNavigationStateChange** WebView prop, I get warning Possible **Unhandled Promise Rejection**

The URL I'm trying to open is **whatsapp://send?phone=XXXXXXXXX**

```
      <WebView
            ref={(ref) => (this.webview = ref)}
            originWhitelist={['https://', 'whatsapp://']}
            source={{ uri: 'https://xxx.xxxx.xxx/' }}
            onNavigationStateChange={this.handleWebViewNavigationStateChange}
            onMessage={(event: WebViewMessageEvent) => {
              alert(event.nativeEvent.data);
            }}
      />

handleWebViewNavigationStateChange = (newNavState: WebViewNavigation) => {
    console.log('nav state changed');

    if (url.startsWith('whatsapp://')) {
      this.webview.stopLoading();
      Linking.openURL(url);
    }
  };
```

**Environment:**
 - OS: Linux Mint 20.3
 - react-native version: 0.64.3
 - react-native-webview version: 11.15.0

**Comment by TheAlmightyBob** [comment]
You're calling `Linking.openURL`, which returns a Promise, without awaiting it. If that fails, it would result in an unhandled promise rejection. Have you tried checking its result?

**Comment by TheAlmightyBob** [comment]
(Also I'd recommend using `onShouldStartLoadWithRequest`, from which you can return `false` to stop the load, instead of `onNavigationStateChange` for this use case... though I doubt that's related to your issue)

**Comment by mgscreativa** [comment]
> You're calling `Linking.openURL`, which returns a Promise, without awaiting it. If that fails, it would result in an unhandled promise rejection. Have you tried checking its result?

Thanks a lot! How should I listen to the promise result with **then**?

**Comment by TheAlmightyBob** [comment]
However you like dealing with promises. You could use `async`/`await` and wrap it in a `try`/`catch`, or use `.then`/`.catch`.

I'm personally a fan of using [`no-floating-promises`](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-floating-promises.md) to help avoid these types of issues.

**Comment by mgscreativa** [comment]
Thanks a lot, did a quick override like this, will get it better when have more spare time!

```
      Linking.openURL(url)
        .then(() => null)
        .catch(() => null);
    }
```
