### ISSUE TITLE
Not able to perform click event in iOS webview

### ISSUE THREAD

**Issue by NamrataDwivedi** [react-native-webview/react-native-webview#2319]
**Bug description:**

I am able to perform click event in all the urls in my app, but not https://www.pocketcfoapp.com/privacy-policy. This is working fine in Android.

**To Reproduce:**

1. Open this url in iOS app using react-native-webview.
2. Click on Terms of Use.

**Expected behavior:**

It should work in both platforms in same way.

**Screenshots/Videos:**

![Simulator Screen Shot - iPhone 11 - 2022-01-11 at 14 17 51](https://user-images.githubusercontent.com/19549471/148910366-35e4077f-8c9b-41de-8234-ed4dde753008.png)

**Environment:**
 - OS: iOS
 - OS version: 11.4.1
 - react-native version: 0.63.2
 - react-native-webview version: 7.0.5

**Comment by clemensmol** [comment]
I'm sorry, but this looks more like a bug in your site's js code. The Privacy and Terms link are not working right in Safari (sometimes they do work on the first click, sometimes it takes a second click). If I disable javascript in Safari, both links work correct.

Maybe I'm missing something. Why do you think it is a bug of React Native Webview?

**Comment by NamrataDwivedi** [comment]
Hi @clemensmol, Thanks for the quick response. I checked in Safari many times and it is working fine. Checked in Responsive Design mode as well. I think it is react-native-webview issue because I have enabled javascript for webview and still it is not working. Since I am still in debugging mode I am not sure where could be the issue. 

Please find my webview code for your reference : 
`  <WebView
              ref={this.myRef}
              source={{ uri: this.props.navigation.getParam("weburl") }}
              startInLoadingState={true}
              javaScriptEnabled={true}
              domStorageEnabled={true}
              startInLoadingState={false}
              scalesPageToFit={true}
              onNavigationStateChange={(navState) => {
                console.log("WebViewTest onNavigationStateChange " + JSON.stringify(navState));
              }}
              javaScriptCanOpenWindowsAutomatically={true}
              onShouldStartLoadWithRequest={(request) => {
                console.log("WebViewTest onShouldStartLoadWithRequest " + JSON.stringify(request))
                return true;
              }}
              renderError={(errorName) => <Error name={errorName} />}
              onContentProcessDidTerminate={(syntheticEvent) => {
                const { nativeEvent } = syntheticEvent;
                console.warn('WebViewTest Content process terminated, reloading', nativeEvent);
              }}
              contentMode={"mobile"}
              pullToRefreshEnabled={true}
              sharedCookiesEnabled={true}
              allowsLinkPreview={true}
              allowFileAccess={true}
              onRenderProcessGone={syntheticEvent => {
                const { nativeEvent } = syntheticEvent;
                console.warn(
                  'WebViewTest WebView Crashed: ',
                  nativeEvent.didCrash,
                );
              }}
            />`

What do you think could be wrong in site's js code ?

**Comment by NamrataDwivedi** [comment]
Hi, there was an issue in the site only. Closing this ticket.
