### ISSUE TITLE
Send messages to the app without injecting Javascript

### ISSUE THREAD

**Issue by astronomyf** [react-native-webview/react-native-webview#2321]
**Bug description:**
I need to add Apple Pay to the WebView but reading from the [documentation](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#enableapplepay), it's not possible to do so without sacrificing the injection methods. Since I'm relying on it to send notification tokens down to the website (as well as some other variables), I'd really need a way to do so. 

In the docs, it says:
`If you are required to send message to App , webpage has to explicitly call webkit message handler and receive it on onMessage handler on react native side`

But from what I understand this way can only communicate from the webpage to the webview and not viceversa.

Any solution to this?

**Environment:**
 - OS: iOS
 - OS version: 15.0
 - react-native version: 0.64.2
 - react-native-webview version: 11.14.2

**Comment by alitsvin** [comment]
RN -> WebView: `webViewRef.postMessage('Your message')` and
`window.addEventListener('message', (event) => event.data)` to receive messages inside webview

WebView -> RN: `window.ReactNativeWebView.postMessage('your message)` in your web inside web view and prop `onMessage={(event} => event.nativeEvent.data` to handle messages from web

**Comment by cipriancalinrad** [comment]
hello @alitsvin, i'm using enableApplePay prop and i want to catch an event from webpage when a deposit is made with succes, as i understood, i can't insert JS in page, i added on webpage 	`window.webkit.messageHandlers.ReactNativeWebView.postMessage('Hello')` but i don't get any event on onMessage props. do you know how i can fix it? 

thanks!

**Comment by chenjiangui** [comment]
> RN -> WebView: `webViewRef.postMessage('Your message')` and `window.addEventListener('message', (event) => event.data)` to receive messages inside webview
> 
> WebView -> RN: `window.ReactNativeWebView.postMessage('your message)` in your web inside web view and prop `onMessage={(event} => event.nativeEvent.data` to handle messages from web

why me invoke `webViewRef.postMessage('Your message')`, `window.addEventListener('message', (event) => event.data)` dosn't recive anything.
