### ISSUE TITLE
In android while creating APK gives this error : operator (<) in file node_modules/react-native-webview/lib/WebView.android.js at 438:20

### ISSUE THREAD

**Issue by rinpatva14** [react-native-webview/react-native-webview#2324]
**Bug description:**

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS:
 - OS version:
 - react-native version:
 - react-native-webview version:

**Comment by GowthamG11** [comment]
Please check this url
https://github.com/facebook/react-native/issues/15513#issuecomment-322824346

**Comment by annkiitagrawaal-gep** [comment]
Hi @GowthamG11 the suggested fix did not work. I did not understand the connection. We have a release day after tomorrow. We need help urgently

**Comment by beisert1** [comment]
Same issue here, happening on iOS as well. This error started happening suddenly this week. We are on version 11.4.5

**Comment by annkiitagrawaal-gep** [comment]
hi guys just change "metro-react-native-babel-preset": "^0.66.2" and it will work

**Comment by AlirezaNoien** [comment]
any update for this?

**Comment by amanraj0505** [comment]
i am getting the same issue after recent update, and above solutions are not working for me? anyone ?
https://github.com/react-native-webview/react-native-webview/issues/2337

**Comment by amanraj0505** [comment]
@AlirezaNoien ?

**Comment by annkiitagrawaal-gep** [comment]
> hi guys just change "metro-react-native-babel-preset": "^0.66.2" in package.json and it will work

@AlirezaNoien @amanraj0505 check this out

**Comment by AlirezaNoien** [comment]
Hey @annkiitagrawaal-gep, I already use "metro-react-native-babel-preset": "^0.66.2" and the latest version of react-native-webview(11.17.0) but I getting the same issue yet! :(

**Comment by AlirezaNoien** [comment]
> > hi guys just change "metro-react-native-babel-preset": "^0.66.2" in package.json and it will work
> 
> @AlirezaNoien @amanraj0505 check this out

Would you please share your package.json and bable.config.js files with us?

**Comment by developingsofts** [comment]
i am getting same issue since two weeks, but no solution. Do you have ayn idea @annkiitagrawaal-gep 
I have tried all the solutions.
