### ISSUE TITLE
iOS build getting the error: node_modules/react-native-webview/lib/WebView.ios.js: Unexpected token: operator (<) in file node_modules/react-native-webview/lib/WebView.ios.js 

### ISSUE THREAD

**Issue by karthinidc** [react-native-webview/react-native-webview#2325]
error node_modules/react-native-webview/lib/WebView.ios.js: Unexpected token: operator (<) in file node_modules/react-native-webview/lib/WebView.ios.js at 416:20. Run CLI with --verbose flag for more details.

Unexpected token: operator (<) in file node_modules/react-native-webview/lib/WebView.ios.js

Build failed in the App center build - iOS - Getting the above error. 
In code local build getting success.

**Expected behavior:**
Build need get success in the App center

**Environment:**
 - OS: iOS 
 - OS version: 12.+
 - react-native version: 0.59.9
 - react-native-webview version:10.2.1

**Comment by developer-appdam** [comment]
Same here. What it's going on?

**Comment by karthinidc** [comment]
I getting the iOS build issue - as mentioned above.

**Comment by GowthamG11** [comment]
Please check this url
https://stackoverflow.com/questions/45725376/react-native-starter-project-bundling-fails-with-unexpected-token-error

**Comment by karthinidc** [comment]
Hi, @GowthamG11  Above they downgrade the package version. Similarly, I downgrade the version to 10.0.0 and upgraded to 10.10.2 but got the same error.

**Comment by beisert1** [comment]
We are having same issue, this started happening suddenly this week without any changes on our end. Using react-native-webview version 11.4.5

**Comment by tanveerahmaddar** [comment]
i got the same issue today suddenly. i tried many things but finally it worked after changing the version of metro-react-native-babel-preset from 0.58.0 to 0.66.0

**Comment by developer-appdam** [comment]
> i got the same issue today suddenly. i tried many things but finally it worked after changing the version of metro-react-native-babel-preset from 0.58.0 to 0.66.0

Just tested this, works like charm!! Thanks a lot

**Comment by bolee** [comment]
> i got the same issue today suddenly. i tried many things but finally it worked after changing the version of metro-react-native-babel-preset from 0.58.0 to 0.66.0

Thanks!!!

**Comment by friederbluemle** [comment]
A quick FYI for the future reader: The first version of `metro-react-native-babel-preset` that fixes this error is `0.59.0`.

Of course it's possible to update to `0.66.2`, or even the recently released version `0.67.0` - But in general it's a good idea to keep dependencies aligned. As OP mentioned, the version of `react-native` that was used here is `0.59.9`, which (at the time) contained `metro-react-native-babel-preset@^0.54.1`. This version of react-native is quite old, so an upgrade is probably recommended, but that's a separate discussion.

The more interesting question would be _why_ is this suddenly becoming a problem.

**Comment by ss-zf-520** [comment]
> i got the same issue today suddenly. i tried many things but finally it worked after changing the version of metro-react-native-babel-preset from 0.58.0 to 0.66.0

Ok, thank you very much！
