### ISSUE TITLE
WebView isn't navigable with bluetooth keyboard

### ISSUE THREAD

**Issue by ZeiRashed** [react-native-webview/react-native-webview#2326]
It used to be possible to navigate into and through a WebView using a  Bluetooth keyboard (iOS). However, I'm not able to focus on the WebView or any of the components in it anymore. This is for version 11.14.2. 

Keyboard navigation is a core accessibility scenario, so it's important to be able to focus on the content within the WebView with both TalkBack (this scenario is handled) and a Bluetooth keyboard. Is there any way to bring the old behavior back?

**Comment by Rojdestv** [comment]
@ZeiRashed im having the same issue, how were you able to allow Bluetooth keyboard (iOS) navigation with webview?
Downgrading the package to 11.14.0 did not fix it.

**Comment by taenri** [comment]
This is still an issue, even with a normal keyboard using a MacOS app. Please re-open.
