### ISSUE TITLE
Support onDownloadError for unsupported downloads

### ISSUE THREAD

**Issue by karthikiyengar** [react-native-webview/react-native-webview#2335]
**Is your feature request related to a problem? If so, Please describe.**

It is currently not possible to pass control back to the user in case of unsupported URLs (e.g due blob as scheme). As it stands, the Android app crashes in these cases, whereas the iOS app displays an alert message (see below)

https://user-images.githubusercontent.com/8260207/150133067-f749749f-9c9a-4b68-b1b9-4118c4673c37.mp4

**Describe the solutions you came up with**

https://github.com/react-native-webview/react-native-webview/pull/2328 has been opened as a first step to mitigate the crash on Android. We can then extend the API surface with `onDownloadError`, where the user is passed the `url` of the failed download so that they can handle it as they please.

**Additional context**

https://github.com/react-native-webview/react-native-webview/pull/2091 attempts to add a similar API.

**Comment by jihanarifia** [comment]
had the same issue :(, can somebody to help?
