### ISSUE TITLE
error node_modules/react-native-webview/lib/WebView.android.js: Unexpected token: operator (<) in file node_modules/react-native-webview/lib/WebView.android.js at 417:20. Run CLI with --verbose flag for more details.

### ISSUE THREAD

**Issue by amanraj0505** [react-native-webview/react-native-webview#2337]
**Bug description:**
Build in android is failing after recent update with the following error.
error node_modules/react-native-webview/lib/WebView.android.js: Unexpected token: operator (<) in file node_modules/react-native-webview/lib/WebView.android.js at 417:20. Run CLI with --verbose flag for more details.

package.json:
{
    "name": "I******p",
    "version": "0.0.1",
    "private": true,
    "scripts": {
        "android": "react-native run-android",
        "ios": "react-native run-ios",
        "start": "react-native start",
        "test": "jest",
        "lint": "eslint ."
    },
    "dependencies": {
        "@react-native-community/async-storage": "^1.8.1",
        "@react-native-community/masked-view": "^0.1.6",
        "jwt-decode": "^2.2.0",
        "moment": "^2.24.0",
        "native-base": "^2.13.8",
        "react": "16.9.0",
        "react-native": "0.61.5",
        "react-native-actionsheet": "^2.4.2",
        "react-native-azure-auth": "^1.6.1",
        "react-native-base64": "^0.0.2",
        "react-native-dialog": "^5.6.0",
        "react-native-file-viewer": "^2.1.1",
        "react-native-geocoding": "^0.4.0",
        "react-native-geolocation-service": "^4.0.0",
        "react-native-gesture-handler": "^1.5.3",
        "react-native-i18n": "^2.0.15",
        "react-native-linear-gradient": "^2.5.6",
        "react-native-localization": "^2.1.6",
        "react-native-media-queries": "^0.3.0",
        "react-native-modal": "^11.5.6",
        "react-native-permissions": "^2.1.5",
        "react-native-reanimated": "^1.7.0",
        "react-native-render-html": "^4.2.0",
        "react-native-responsive-screen": "^1.3.0",
        "react-native-safe-area-context": "^0.6.2",
        "react-native-screens": "^2.0.0-alpha.25",
        "react-native-simple-toast": "^1.0.0",
        "react-native-status-bar-height": "^2.5.0",
        "react-native-vector-icons": "^6.6.0",
        "react-native-webview": "^8.0.1",
        "react-navigation": "^4.0.10",
        "react-navigation-stack": "^2.0.15",
        "react-navigation-tabs": "^2.6.2",
        "react-redux": "^7.1.3",
        "redux": "^4.0.5",
        "redux-thunk": "^2.3.0",
        "rn-fetch-blob": "^0.12.0",
        "rn-placeholder": "^3.0.0",
        "rn-sliding-up-panel": "^2.4.0"
    },
    "devDependencies": {
        "@babel/core": "7.7.7",
        "@babel/runtime": "7.7.7",
        "@react-native-community/eslint-config": "0.0.5",
        "babel-jest": "24.9.0",
        "eslint": "6.8.0",
        "jest": "24.9.0",
        "metro-react-native-babel-preset": "0.56.3",
        "react-test-renderer": "16.9.0"
    },
    "jest": {
        "preset": "react-native",
        "setupFiles": [
            "./jest-setup.js"
        ]
    }
}

**To Reproduce:**
yarn install
cd android
./gradlew clean
cd ..
npx react-native run-android

**Environment:**
 - OS: android
 - OS version: 10
 - react-native version: 0.61.5
 - react-native-webview version: ^8.0.1

**Comment by amanraj0505** [comment]
error node_modules/react-native-webview/lib/WebView.ios.js: Unexpected token: operator (<) in file node_modules/react-native-webview/lib/WebView.ios.js at 412:20. Run CLI with --verbose flag for more details.
Error: Unexpected token: operator (<) in file node_modules/react-native-webview/lib/WebView.ios.js at 412:20


also in ios

**Comment by annkiitagrawaal-gep** [comment]
@amanraj0505 change the version of metro-react-native-babel-preset to ^0.66.2 in package.json

**Comment by amanraj0505** [comment]
was able to solve the issue thanks
