### ISSUE TITLE
Images from a http:// URL do not load even with mixedContentMode="always" enabled in release variant

### ISSUE THREAD

**Issue by garytsnaptravel** [react-native-webview/react-native-webview#2338]
**Bug description:**
Images from a http:// URL do not load even with `mixedContentMode="always"` enabled in `variant=release`, but works fine in the debug variant. Instead of showing the image, there is a blank white box instead and briefly flashes "untagged" at the top left corner.

Previously I did not have the `mixedContentMode` attribute so images did not load, which is expected.

**Expected behavior:**
Images should load and display properly even in http mode.

**Environment:**
 - OS: Android
 - OS version: 11
 - react-native version: 0.61.5
 - react-native-webview version: 8.0.5, later tried 11.17.0 but encountered the same issue

**Comment by baesumin** [comment]
+1

**Comment by GuySerfaty** [comment]
+1

**Comment by gongchengxiang** [comment]
+1 , I actually see it also on iOS & android

**Comment by gongchengxiang** [comment]
it works in rn-0.67.1 & webview-11.17.0,

**Comment by xiaoqiang1999** [comment]
+1, react-native-webview 13.10.2, rn 0.73.5

**Comment by MartinPavlik** [comment]
+1
