### ISSUE TITLE
Android build issue with react-native 0.67

### ISSUE THREAD

**Issue by thanhcuong1990** [react-native-webview/react-native-webview#2339]
**Bug description:**
I've just upgrade to react-native 0.67 with gradle-7.2.  When I try to run on Android it throw an error below:
```
Could not resolve compiler classpath. Check if Kotlin Gradle plugin repository is configured in project ':react-native-webview'.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':react-native-webview:compileDebugKotlin'.
> Could not resolve all dependencies for configuration ':react-native-webview:kotlinCompilerClasspath'.
   > Using insecure protocols with repositories, without explicit opt-in, is unsupported. Switch Maven repository to redirect to a secure protocol (like HTTPS) or allow insecure protocols. See https://docs.gradle.org/7.2/dsl/org.gradle.api.artifacts.repositories.UrlArtifactRepository.html#org.gradle.api.artifacts.repositories.UrlArtifactRepository:allowInsecureProtocol for more details. 
```

**Environment:**
 - OS: Android
 - OS version: Android 11
 - react-native version: 0.67
 - react-native-webview version: 11.17.0

**Comment by thanhcuong1990** [comment]
This issue is related with other packages. Closed!

**Comment by fariskhan563** [comment]
@thanhcuong1990 please can you tell how did you resolved above issue, as I'm facing the same, thank you

**Comment by JeremyBradshaw7** [comment]
@thanhcuong1990 the errors are certainly reported on react-native-webview, I'm getting the same with RN 0.67. What "other packages" do you say are at fault?

**Comment by lutakyn** [comment]
I'm getting similar issues. Can someone explain better
