### ISSUE TITLE
Javascript in Webview loads on iOS but not on Android

### ISSUE THREAD

**Issue by viswen-k** [react-native-webview/react-native-webview#2342]
I have the below setup to run the script which works as expected on iOS but shows up blank on Android.

How can I resolve this issue?

```
<WebView
        onShouldStartLoadWithRequest={onRouteChange}
        javaScriptEnabled={true}
        injectedJavaScript={`(${ReportJS})()`}
        injectedJavaScriptForMainFrameOnly={true}
        onMessage={onMessage}
        onLoadStart={onLoadStart}
        style={styles.webview}
        ref={webViewRef}
        originWhitelist={['*']}
        source={{
          html: `
            <body>
              <script>${startupJS}</script>
            </body>
        `,
        }}
      />
```

**Bug description:**
Android virtual device does not load javascript

**Expected behavior:**
Android virtual device to load javascript

**Environment:**
 - react-native version: 0.63.3
 - react-native-webview version: 11.17.0
 - Android: 10

**Comment by javidmammad** [comment]
did you fix that?

**Comment by viswen-k** [comment]
Not yet, still working on this issue. I've attempted changing dependency versions but no change in result.

**Comment by viswen-k** [comment]
Running injectedJavascript file within the page instead of using an external file resolved my issue
