### ISSUE TITLE
When try to make release  android Build.error node_modules/react-native-webview/lib/WebView.android.js: Unexpected token: operator (<) in file node_modules/react-native-webview/lib/WebView.android.js at 417:20. Run CLI with --verbose flag for more details.

### ISSUE THREAD

**Issue by isthisshivam** [react-native-webview/react-native-webview#2343]
**Bug description:**

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**
![image](https://user-images.githubusercontent.com/33997503/150752012-4e2118b4-f38e-40dc-a5e5-f15389507e7a.png)

**Environment:**
 - OS:
 - OS version:
 - react-native version:'0.62.0',
 - react-native-webview version:'10.0.0'

**Comment by ashwindatye** [comment]
> metro-react-native-babel-preset

This solution worked for me

**Comment by vaniapsk** [comment]
> @isthisshivam change "metro-react-native-babel-preset" to "^0.66.2" in package.json

this also worked for me. I had to do `npx jest --clearCache` after changing to "^0.66.2"
