### ISSUE TITLE
Crash/close on download

### ISSUE THREAD

**Issue by rnexpo** [react-native-webview/react-native-webview#2348]
Hello,

I have implemented the react-native-webview package without any problems and using it to wrap a website in the app.
Everything is working nice until I download files. The downloads are triggered in the website and then the app closes without any error or notification.
Can you please help me with this issue?

Thanks!

**Comment by SaadBinWaheed-empglabs** [comment]
Same on Android. No error log. 
Downloading logic on web:
```
   link.download = "filename.png";
   link.href = document.getElementById("canvas").toDataURL();
   link.click();
```
Following permission added
`    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
`

**Comment by TheAlmightyBob** [comment]
@SaadBinWaheed-empglabs Are you testing with the latest version? `11.17.1` included a fix for downloading unsupported URLs crashing on Android.

(though I'll add that there was a pretty clear error when that happened, so if that's your issue then you might want to work on improving your crash reporting... Flipper is pretty handy for locally debugging crashes)

**Comment by SaadBinWaheed-empglabs** [comment]
The crash was fixed when I upgraded to the latest package, but now the base64 PNG isn't downloading either ( wasn't downloading before either). 
Getting these logs:
```
W/RNCWebViewManager: Unsupported URI, aborting download
W/RNCWebViewManager: java.lang.IllegalArgumentException: Can only download HTTP/HTTPS URIs: 
data:image/png;base64,.... {PNG ENCODING}
```

**Comment by whoislewys** [comment]
Just ran into this bug
`onMessage` functionality should not be needed for a file download

**Comment by TheAlmightyBob** [comment]
@whoislewys You're getting a crash using a version newer than `11.17.1`? Can you share the specific error/stack?

**Comment by raffidil** [comment]
I still have this issue on Android, I don't get any logs neither web side nor RN side. 
My `react-native-webview` version is 11.22.3.

My JS code in the web-page is: 
```js
      var a = document.createElement("a"); //Create <a>
      a.href = dataURL; //Image Base64 Goes here
      a.download = "Image.png"; //File name Here
      a.click();
```

**Comment by TheAlmightyBob** [comment]
@raffidil 

> I don't get any logs neither web side nor RN side

Does "RN side" include native Android logcat (or Flipper)? That seems _very_ unusual that an Android app would crash without logging anything.

**Comment by vitexikora** [comment]
I have the same issue - my use case is identical to @raffidil 
Upon clicking the link (programatically, or even a basic link with the data uri in href) does nothing at all. Only logcat reported an error.

Logcat report:

```
W RNCWebViewManagerImpl: Unsupported URI, aborting download
W RNCWebViewManagerImpl: java.lang.IllegalArgumentException: Can not handle uri:: data:text/x-vcard;charset=utf-8;base64,QkVHSU46VkNBUkQKVkVSU0lPTjozLjAKRk47Q0hBUlNFVD1VVEYtODpBbmnEjWthCk47Q0hBUlNFVD1VVEYtODo7QW5pxI1rYTs7OwpFTUFJTDtDSEFSU0VUPVVURi04O3R5cGU9V09SSyxJTlRFUk5FVDprYWRsY2tvdmFAc292YW5ldC5jegpURUw7VFlQRT1XT1JLLFZPSUNFOis0MjA5OTk4ODg3NwpUSVRMRTtDSEFSU0VUPVVURi04OkN2acSNaXRlbGthIGLEm2x1aApPUkc7Q0hBUlNFVD1VVEYtODpHWiBNZWRpYVwsIGEucy4KUkVWOjIwMjMtMTItMDZUMTY6Mzc6NDEuNjMwWgpFTkQ6VkNBUkQK
W RNCWebViewManagerImpl:         at android.app.DownloadManager$Request.checkUri(DownloadManager.java:787)
W RNCWebViewManagerImpl:         at android.app.DownloadManager$Request.<init>(DownloadManager.java:770)
W RNCWebViewManagerImpl:         at com.reactnativecommunity.webview.RNCWebViewManagerImpl.createViewInstance$lambda-1(RNCWebViewManagerImpl.kt:97)
W RNCWebViewManagerImpl:         at com.reactnativecommunity.webview.RNCWebViewManagerImpl.$r8$lambda$gH_tTZLrblOtKn53LKimRKV1Rps(Unknown Source:0)
W RNCWebViewManagerImpl:         at com.reactnativecommunity.webview.RNCWebViewManagerImpl$$ExternalSyntheticLambda0.onDownloadStart(Unknown Source:9)
W RNCWebViewManagerImpl:         at WV.D6.handleMessage(chromium-TrichromeWebViewGoogle6432.aab-stable-604516433:483)
W RNCWebViewManagerImpl:         at android.os.Handler.dispatchMessage(Handler.java:106)
W RNCWebViewManagerImpl:         at android.os.Looper.loopOnce(Looper.java:211)
W RNCWebViewManagerImpl:         at android.os.Looper.loop(Looper.java:300)
W RNCWebViewManagerImpl:         at android.app.ActivityThread.main(ActivityThread.java:8401)
W RNCWebViewManagerImpl:         at java.lang.reflect.Method.invoke(Native Method)
W RNCWebViewManagerImpl:         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
W RNCWebViewManagerImpl:         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```

**Comment by TheAlmightyBob** [comment]
@vitexikora Thank you for the logcat output. The behavior you describe is expected. The fix that was made was only to prevent apps from crashing when trying to download unsupported URIs, not to actually make the downloads work.
