### ISSUE TITLE
Jest Failure - SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by Erik-Schlegel** [react-native-webview/react-native-webview#2349]
**Bug description:**

Jest tests on pages containing this webview fail with the message "SyntaxError: Cannot use import statement outside a module"

**To Reproduce:**

- spin up a fresh react-native app
- import and add a webview to app.js
- run `npm run test`

**Expected behavior:**

Expecting default tests to complete without issue

**Screenshots/Videos:**

<img width="553" alt="Screen Shot 2022-01-27 at 12 02 31 AM" src="https://user-images.githubusercontent.com/27722995/151316758-b0868fcb-5a4d-459a-b5f4-5f38421e7cbd.png">
<img width="680" alt="Screen Shot 2022-01-27 at 12 03 37 AM" src="https://user-images.githubusercontent.com/27722995/151316804-a5234087-8dc7-4952-b5ce-af7fd151ccdf.png">

**Environment:**
 - OS: Mac
 - OS version: Monterrey / 12.1
 - react-native version: 66.4
 - react-native-webview version: 11.17.1

**Comment by tkbeal** [comment]
I am having this issue as well

**Comment by christophpurrer** [comment]
@Erik-Schlegel / @tkbeal :
I came across the same issue when updating from rn-macOS from 0.63 to 0.66.
Our Jest tests stopped working when using:
```import WebView from 'react-native-webview';```

I came up with the following work-around
1.) add the following snippet to jest.config.js
```
  moduleNameMapper: {
    'react-native-webview': '<rootDir>/src/__mocks__/WebView.js',
  },
```
2.) create the corresponding file with this content:
```
export default function WebView() {
  return null;
}
```

NOTE: The webView still works in the app, just the Jest UTs were failing.
Would love to here if there is a better/long term fix
