### ISSUE TITLE
File download on Android doesn't understand "filename*=UTF-8''" nor basic auth

### ISSUE THREAD

**Issue by djibarian** [react-native-webview/react-native-webview#2353]
**Bug description:**
Downloading a file in Android where the filename is defined with this alternate format `Content-Disposition: attachment; filename*=UTF-8''...` makes the filename being ignored, using the URL pathname instead. Additionally, basic auth is ignored.

**To Reproduce:**

**Expected behavior:**
Filename and basic auth should be properly handled, as it is in the standalone browser.

**Screenshots/Videos:**

**Environment:**
 - OS: Android
 - OS version:
 - react-native version:
 - react-native-webview version:

**Comment by piechoo** [comment]
Just ran into this bug, still an issue

**Comment by Andre-at-LaCapitale** [comment]
Same for us :-/ still an issue

**Comment by UNIDY2002** [comment]
I made a fix in #2767 which has been included in version 11.25.1. You may try it out and leave feedbacks if the problem remains.
