### ISSUE TITLE
Expo Support

### ISSUE THREAD

**Issue by ragasjohn** [react-native-webview/react-native-webview#2355]
Hello there,

I am getting the following warning using expo for a react native app I am creating

Some dependencies are incompatible with the installed expo package version:
 - react-native-webview - expected version: 11.13.0 - actual version installed: 11.17.1
 - Your project may not work correctly until you install the correct versions of the packages.
To install the correct versions of these packages, please run: expo install [package-name ...] 

The project is working fine but I am wondering if I will have issues going forward

**Comment by brunoprietog** [comment]
Use expo install instead of yarn install
