### ISSUE TITLE
WebRTC doesn't work on macos catalyst

### ISSUE THREAD

**Issue by SamuelScheit** [react-native-webview/react-native-webview#2356]
I've got WebRTC working on ios with react-native-webview, however I get the following error on macos:

**Bug description:**
When I compile my app to Mac Catalyst the following properties ``RTCPeerConnection``, ``navigator.mediaDevices`` and ``navigator.getUserMedia`` are ``undefined`` in the webview, which are needed for WebRTC to work.

**To Reproduce:**
I've got the following WebView component:
```jsx
<WebView
	ref={webview}
	source={{ uri: "https://example.org" }}
	mediaPlaybackRequiresUserAction={false}
	allowsInlineMediaPlayback={true}
	mediaCapturePermissionGrantType="grant"
	onLoadEnd={async () => {
		webview.current.injectJavaScript(`
			console.log(
				window.navigator.mediaDevices,
				window.navigator.getUserMedia,
				window.RTCPeerConnection
			);
		`);
	}}
/>;
```
and if you inspect the webview with remote dev tools you can see that all those properties are undefined on macos catalyst, even tho they are working on ios.

**Expected behavior:**
The above properties should be defined

**Environment:**
 - OS: macOS Monterey 
 - OS version: 12.1
 - react-native version: 0.66.4
 - react-native-webview version: 11.15.0

Other properties:
``isSecureContext`` = ``true``
``UserAgent`` = ``Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko)``

**Comment by Flam3rboy** [comment]
still searching for solutions

**Comment by Flam3rboy** [comment]
still searching for solutions

**Comment by Flam3rboy** [comment]
still searching for solutions

**Comment by mtperessoni** [comment]
See: https://github.com/react-native-webview/react-native-webview/issues/2571#issuecomment-1227738685

The problem can be your user agent. I was with a problem like yours. I got camera and microphone permissions, but the microphone audio was not sent through the webview.

**Comment by Desintegrator** [comment]
same issue

**Comment by kumarutsavrobosoft** [comment]
setting this prop mediaPlaybackRequiresUserAction to true helped and it works smoothly now for me.

**Comment by kumarutsavrobosoft** [comment]
mediaPlaybackRequiresUserAction={false} worked for me

**Comment by denmorgenshtern** [comment]
same issue  
macOS 13.5.1 (22G90)
Safari 17.0 (18616.1.24.11.5, 18616)

**Comment by git-achern19** [comment]
@SamuelScheit Did you ever end up finding a work around or way to do this? I am currently encountering this issue and its been quite a headache.

**Comment by SamuelScheit** [comment]
@git-achern19 No, I gave up for now.

However I've migrated to react-native-webrtc for iOS and hope that support for catalyst will be added soon.
