### ISSUE TITLE
[IOS] Get blank page after each reload 

### ISSUE THREAD

**Issue by danidji** [react-native-webview/react-native-webview#2357]
Hi everyone, i open this issue because i try to reload the webview on IOS when i change some settings of my webview component, like backgroundColor or font size, but on IOS when i reload, i get a blank page without my content. 

Here one example of where i call my refresh function : 

![image](https://user-images.githubusercontent.com/73373221/151955477-3b90b877-f480-47f9-b19f-b9c56f672efe.png)

and here is my refresh function : 

![image](https://user-images.githubusercontent.com/73373221/151955592-e2247b19-1c91-41a9-a1e2-d81f499d7fda.png)

Everything works fine on Android. 

On the webview inspector, i noticed that after reloading the html isn't reloaded : 

![image](https://user-images.githubusercontent.com/73373221/152043451-7c099327-d66f-4144-ad6d-a5eeeeb66507.png)

Here is my webview component : 

![image](https://user-images.githubusercontent.com/73373221/152124057-9bea2008-4fe0-4c8b-b3ba-cdc808ba4d4d.png)

I injected javascript before content is loaded and maybe my issue come from here, because when i reload the javascript isn't reinjected. But if is that i don't understand why is it working perfectly in Android ad not in IOS. 

Any idea of how fix it ? 

thanks for help !!

**Comment by choijiho0021** [comment]
same problem.
use url like source={url : "www.google.com") -> google page -> reload() -> google page
use html like htlml={html: "<html> ...... "} -> html page ->  reload() -> blank page

**Comment by SavannahHowell** [comment]
I am having the same problem.
I'm using html as the source. Any time reload() is called, it renders a blank screen in the WebView (iOS only, Android worked fine). In the meantime, I'm trying to rework my code to not need the reload() function.

**Comment by danidji** [comment]
Someone help me find a solution for this, he use an unique Key props on the webview component that is generate after each reload.  Like That : 
```
const [webviewKey, setWebviewKey] = useState(randomString(10));

function refresh() {
  setWebviewKey(randomString(10));
  ...
}

 <WebView
	ref={webview}
	key={webviewKey}
        {...otherProps}
/>
```

I don't really understand why this works, but this fixed my problem. Hope this will work for both of you

**Comment by erheron** [comment]
Bumped into this, and we do not know what's causing this
Adding `incognito` prop seems to help.

People above suggested setting a random `key` prop, but I wouldn't advise it, since it effectively forces React to re-create a component (i.e. unmount and mount again), which is not the same as re-rendering

**Comment by AlanWen2016** [comment]
if SPA reload itself,  how can I  set an unique Key props on the webview?
