### ISSUE TITLE
How to update user agent ?

### ISSUE THREAD

**Issue by prashant828** [react-native-webview/react-native-webview#2363]
Some websites don't allow access by saying "out dated browser both android/ios".
How can I update the user agent so that webview uses relatively latest browser ?

**Comment by joelemanoel** [comment]
Você pode definir um UserAgent:
```js
<WebView 
     userAgent='Mozilla/5.0 (Linux; Win64; x64; rv:46.0)r Gecko/20100101 Firefox/68.0''
/>
```
This UserAgent works for my to WhatsApp Web.

**Comment by TheAlmightyBob** [comment]
Updating the user agent (which you can do as @joelemanoel demonstrated) won't change the actual WebView version being used, only the version that it claims to be. I suppose if that's what those sites are using to detect whether things are "out dated," then you could use that to fool them... but if they're actually using feature detection or something, it wouldn't make any difference.

I've never seen that error before though so have no idea what the sites you're trying to use are expecting.
