### ISSUE TITLE
Integrate back button in web view to go back to app

### ISSUE THREAD

**Issue by linus-komnick** [react-native-webview/react-native-webview#2365]
At the moment in order to come back to the app from the web view, I listen to changes in the URL. On top of that it would also be nice if there was a back button somewhere in the web view, to switch back to the app. 

Is this something that already exists or what method is the preferred method to leave the web view and come back to the app?

**Comment by TheAlmightyBob** [comment]
Not quite sure what you mean by "back to the app"... the WebView is embedded in your app. I think a preferred method would be to use something like React Navigation, especially if you want a back button to go to the previous screen in the app.

**Comment by linus-komnick** [comment]
@TheAlmightyBob thx for your reply! For some reason I thought that maybe there was a built-in back button which you could activate and listen to via the properties on the WebView component. In the same sense as you can listen to url changes. But since that's not the case I'll create my own back button xD

**Comment by TheAlmightyBob** [comment]
Depending on what exactly you're trying to do, you could also check out something like https://github.com/proyecto26/react-native-inappbrowser. It's very limited in terms of integrating with your app, but if you were just trying to open a web page in a separate screen and then allow going "back to the app" it could be of interest.
