### ISSUE TITLE
Access methods of the web application opened in webview 

### ISSUE THREAD

**Issue by noumanmoeen** [react-native-webview/react-native-webview#2367]
I have a web application opened in webview in my mobile application and I want to access a method that is exposed by my web application. I think on the web it can be done by iframe.contentwindow() but I am not sure how this can be done using webview

**Comment by wbobeirne** [comment]
You'll want to use `onMessage` and `postMessage` for this: https://github.com/react-native-webview/react-native-webview/blob/master/docs/Guide.md#the-windowreactnativewebviewpostmessage-method-and-onmessage-prop
