### ISSUE TITLE
WebView out of view crashes when navigating (only on android)

### ISSUE THREAD

**Issue by thanhnvpk01168** [react-native-webview/react-native-webview#2370]
This is the information I can share:
react-native-webview: "^11.17.2"
react-native: "0.67.2"
react-native-gesture-handler: "^2.2.0"
react-native-reanimated: "^2.4.1"
react-native-screens: "^3.10.2"
<img width="1163" alt="Screen Shot 2022-02-12 at 8 35 14 PM" src="https://user-images.githubusercontent.com/58645779/153713532-0a6d54fc-1625-465f-882f-b5bf756b2d9f.png">
https://user-images.githubusercontent.com/58645779/153713513-b06cf22f-eafd-459f-9b9c-5cd68f84cf43.mp4

https://user-images.githubusercontent.com/58645779/153713588-2ee06a3a-f9b2-40fd-9ca3-78c88478032f.mp4

**Comment by pqv2210** [comment]
I have same issue, how can you fix this?

**Comment by ElfenLiedGH** [comment]
> @thanhnvpk01168 I have same issue, how can you fix this?

https://github.com/react-native-webview/react-native-webview/issues/1838#issuecomment-937479438

**Comment by ElfenLiedGH** [comment]
> @thanhnvpk01168 I have same issue, how can you fix this?

or better 

https://github.com/react-native-webview/react-native-webview/issues/811#issuecomment-748611465
