### ISSUE TITLE
Listen event in webapp loaded in webview

### ISSUE THREAD

**Issue by cuongdo926** [react-native-webview/react-native-webview#2372]
Hello, I have a react native app that needs to call ```webviewRef.current.postMessage``` to send data into the web app in webview. I used ```document.addEventListener('message', handleMessage)``` to listen to events in webapp and it only works in android but ios.
If I change to ```window.addEventListener('message', handleMessage)```, the event is fired in an infinite loop in both android and ios. I use ```react-native-webview: ^11.17.2```
Does anybody know how to make it work?

**Comment by TheAlmightyBob** [comment]
You can't inject javascript to invoke `handleMessage` directly?

I actually didn't realize `postMessage` still existed, considering the Readme has long claimed that it would be removed in the future...

**Comment by ahmettopal** [comment]
any solutions ? I have the same problem too. I am showing iframe as webView and I want to add eventlistener to this iframe

**Comment by kosbog** [comment]
```
const ComponentName = () => {
    ....
    ....
    
    const handlePostMessageListener = useCallback((message) => {
      ...do your stuff here
    }, []);
    
    useEffect(() => {
        // Add listener to catch messages
        window.addEventListener("message", handlePostMessageListener);
        return () => {
           window.removeEventListener('message', handlePostMessageListener)
        }
     }, [handlePostMessageListener]);
}
```
