### ISSUE TITLE
Web view not changing url even on clearing cache

### ISSUE THREAD

**Issue by preetikat240486** [react-native-webview/react-native-webview#2373]
I'm working with react native web view where in we load a website maintaining session in web view using a token. When I login to the app and move the user to web vie two load the site as per user login, session is maintained by a url sent in api response and app loads well but when I logout i.e. navigate to login screen and log back in with a new user, the old user session is still maintained. How can we clear that? I have tried clearing cache, clearing url and assigning value again, but none works. Sharing my code for web view
`const reload=()=>{
if (url !== route.params.url) {
  handleUrlChange(route.params.url)//Changing url for web view as per route from login
}
 setLoading(true);}

useFocusEffect(
React.useCallback(() => {
  reload()
  return () => {
  };
}, []));

const clearLocalStorage = () => {
handleCookieStorage(true), () => {
  setTimeout(() => {
    handleCookieStorage(false);
  }, 2000);
};};

const logoutUserClearInfo = () => {
setURl(‘’)//Clearing url for web view while logging out
clearLocalStorage()
ClearCache.getAppCacheSize((value, unit) => {
  console.log("cache size", value, unit) // check size
  ClearCache.clearAppCache(data => {
    //alert(data) // will alert the new size
  });
})
AsyncStorage.getAllKeys()
    .then(keys => AsyncStorage.multiRemove(keys))
  navigation.canGoBack() ? (
    navigation.navigate('Authentication') 
 ) : navigation.navigate('Authentication') }

const jsCode = `window.ReactNativeWebView.postMessage(document.documentElement.innerHTML);(function(){
${isCookieClear?`window.localStorage.clear(); window.sessionStorage.clear();`:''}})();`;

<WebView scalesPageToFit
    startInLoadingState = {true}
    ref = {webViewRef}
    originWhitelist={['*']}
    style={styles.container} source={{ uri: url  }} onLoadStart={() => (reload())} onLoadEnd={() => (setLoading(false))}
    javaScriptEnabled={true}
    domStorageEnabled={true}
    setSupportMultipleWindows={false}
    automaticallyAdjustContentInsets={false}
    allowsFullscreenVideo={true}
    injectedJavaScript={jsCode}
    thirdPartyCookiesEnabled = {false}
    onMessage={event => {
       if (event.nativeEvent.data === 'stoprefresh'){
          handleStopRefresh(true)
          console.log('STOP REFRESH', stopRefresh)
        }
    }}
    onScroll = {onScroll}
    incognito = {true}
    allowsLinkPreview = {false}
    allowUniversalAccessFromFileURLs={true}
    onShouldStartLoadWithRequest={(event) => {
      if (!event || !event.url) {
        return true;
      }
        if (event.url.includes('Logout')) {
          webViewRef.current.stopLoading();
          setLoading(false);
          Alert.alert(
            "AppName",
            "Are you sure you want to logout?",
            [
              {
                text: "No",
                onPress: () => console.log("Cancel Pressed"),
                style: "cancel"
              },
              { text: "Yes", onPress: () => { logoutUserClearInfo() }
              }
            ]
          );
          return false
         }            
         else {
          return true
        }
      }}
    />`
**Environment:**
 - OS: Mac os Monterey
 - OS version: 12.2
 - react-native version: ~0.63.4
 - react-native-webview version: ^11.16.0

**Comment by TheAlmightyBob** [comment]
What platform?

**Comment by preetikat240486** [comment]
> What platform?

Both Android and iOS
