### ISSUE TITLE
Moniting `document.title` change?

### ISSUE THREAD

**Issue by likeSo** [react-native-webview/react-native-webview#2378]
**Is your feature request related to a problem? If so, Please describe.**

I need sync `document.title` to my React Navigation's title in **real time**, but `injectedJavaScript="window.postMessage(document.title)"` can only works one time

**Describe the solutions you came up with**

Add a callback that is called every time `document.title` changed

**Additional context**

On iOS, we can observe `WKWebview.title` to detect every time the title changes;

**Comment by TheAlmightyBob** [comment]
That's not a bad idea, looks like [Android has a similar notification](https://developer.android.com/reference/android/webkit/WebChromeClient#onReceivedTitle(android.webkit.WebView,%20java.lang.String)) (PRs welcome :) ). In the meantime, I'm not sure if this would work, but _possibly_ you could inject javascript that overrides the `title` property (similar to https://stackoverflow.com/a/35512224) and posts a message whenever the setter is called?

**Comment by HuPeng333** [comment]
you can inject the script like this: 

```TypeScript
const nav = useNavigation()
const script = `
    let _documentTitle = document.title;
    window.ReactNativeWebView.postMessage(_documentTitle)
    Object.defineProperty(document, 'title', {
      set (val) {
        _documentTitle = val
        window.ReactNativeWebView.postMessage(_documentTitle)
      },
      get () {
        return _documentTitle
      }
    });
  `

const onPostMsg = ({ nativeEvent }: WebViewMessageEvent) => {
  nav.setOptions({ title: nativeEvent.data })
}

return (
  <WebView
    injectedJavaScript={script}
    source={{ uri: route.params.url }}
    onMessage={onPostMsg}
  />
)
```

**Comment by HuPeng333** [comment]
I found a another way to listen `document.title`:
```TypeScript
const nav = useNavigation()
const script = `
  const titleDom = document.getElementsByTagName('title')[0]
  const observer = new MutationObserver(() => {
    window.ReactNativeWebView.postMessage(document.title)
  })
  observer.observe(titleDom, {
    childList: true
  })
  window.ReactNativeWebView.postMessage(document.title)
  `

const onPostMsg = ({ nativeEvent }: WebViewMessageEvent) => {
  // title can be used here
  nav.setOptions({ title: nativeEvent.title })
  // you can also use data
  // nav.setOptions({ title: nativeEvent.data })
}

return (
  <WebView
    injectedJavaScript={script}
    source={{ uri: route.params.url }}
    onMessage={onPostMsg}
  />
)
```

see [MutationObserver](https://developer.mozilla.org/zh-CN/docs/Web/API/MutationObserver)

**Comment by zhaoxm2016** [comment]
document.title in componentDidMount not work
