### ISSUE TITLE
Cannot open intent on Android

### ISSUE THREAD

**Issue by prakash2091** [react-native-webview/react-native-webview#2384]
**Bug description:**
Cannot open intent on Android
I tried with originWhitelist={['http://','https://','intent:*']} and did not help

**To Reproduce:**
Dynamic url is redirecting to -->
intent://forms.gle/ASDFA#Intent;package=com.google.android.gms;action=com.google.firebase.dynamiclinks.VIEW_DYNAMIC_LINK;scheme=https;S.browser_fallback_url=https://fallbackurl

**Expected behavior:**
fallback url to be loaded since intent not present

**Comment by woongbaera89** [comment]
Use "onShouldStartLoadWithRequest" to know any requests of webview. 

```

      <WebView 
        onShouldStartLoadWithRequest={(event) => {
          if (event.url.startsWith("intent:") ) {
            //handle intent scheme
            // ...

            // prevent page history
            return false;
          } 
          return true;
        }}
      />
```

**Comment by kranthi1216** [comment]
Hi i am using same url which starts with intent:// but showing unknown url scheme
can help how to resolve this?

**Comment by lguardado-da** [comment]
same

**Comment by woongbaera89** [comment]
@kranthi1216  @lguardado-da  
You should also use thirdparty library for start activity. 
(https://developer.android.com/training/basics/firstapp/starting-activity)


Here is my expo code example for parsing to varient of intent scheme 
```
import { startActivityAsync } from "expo-intent-launcher";

...
      <WebView 
        onShouldStartLoadWithRequest={(event) => {
    if (event.url.startsWith("intent:") ) {
      //handle intent scheme ( 'intent://{appScheme}#Intent; ...' )
      const intents = url.split("#Intent;");
      const path = intents[0] || "";
      const query = intents[1] || "";
      const params = {};
      query.split(";").map((each) => {
        if (each.includes("=")) {
          const pairs = each.split("=");
          params[pairs[0]] = pairs[1];
        }
      });
      const scheme = params?.scheme;
      const packageName = params?.package;
      const data = path.replace("intent://", `${scheme}://`);
      await startActivityAsync("android.intent.action.VIEW", {
        data, 
        packageName,
      });

      // prevent page history
      return false;
    } 
    return true;
  }}
/>
```

**Comment by lguardado-da** [comment]
> @kranthi1216 @lguardado-da You should also use thirdparty library for start activity. (https://developer.android.com/training/basics/firstapp/starting-activity)
> 
> Here is my expo code example for parsing to varient of intent scheme
> 
> ```
> import { startActivityAsync } from "expo-intent-launcher";
> 
> ...
> <WebView 
>   onShouldStartLoadWithRequest={(event) => {
>     if (event.url.startsWith("intent:") ) {
>       //handle intent scheme ( 'intent://{appScheme}#Intent; ...' )
>       const intents = url.split("#Intent;");
>       const path = intents[0] || "";
>       const query = intents[1] || "";
>       const params = {};
>       query.split(";").map((each) => {
>         if (each.includes("=")) {
>           const pairs = each.split("=");
>           params[pairs[0]] = pairs[1];
>         }
>       });
>       const scheme = params?.scheme;
>       const packageName = params?.package;
>       const data = path.replace("intent://", `${scheme}://`);
>       await startActivityAsync("android.intent.action.VIEW", {
>         data, 
>         packageName,
>       });
> 
>       // prevent page history
>       return false;
>     } 
>     return true;
>   }}
> />
> ```

Hey @woongbaera89 thanks for the reply, do you know of any option for react-native cli?

**Comment by woongbaera89** [comment]
@lguardado-da 
In case of bare react-native project, try to use '[react-native-send-intent](https://github.com/lucasferreira/react-native-send-intent#example--open-app-with-data)'

There are various options for launching another activity, especially "Open App with Data" and "Open Chrome Intent" will be helpful to you.

**Comment by lguardado-da** [comment]
> @lguardado-da In case of react-native cli project, try to use [react-native-send-intent](https://github.com/lucasferreira/react-native-send-intent#example--open-app-with-data)
> 
> There are various options for launching another activity, especially "Open App with Data" and "Open Chrome Intent" will be helpful to you.

Thank you so much! I'll give it a try and let you know how it goes

**Comment by lguardado-da** [comment]
Just in case it helps, I was able to do the trick by setting `undefined` as the WebView userAgent, that way the service is not redirecting me to `intent://` and I'm able to use the responsive version within the WebView.

**Comment by mmkhmk** [comment]
> Just in case it helps, I was able to do the trick by setting `undefined` as the WebView userAgent, that way the service is not redirecting me to `intent://` and I'm able to use the responsive version within the WebView.

Thanks @lguardado-da , you saved my day. I hope we will find better solution.

**Comment by lguardado-da** [comment]
> > Just in case it helps, I was able to do the trick by setting `undefined` as the WebView userAgent, that way the service is not redirecting me to `intent://` and I'm able to use the responsive version within the WebView.
> 
> Thanks @lguardado-da , you saved my day. I hope we will find better solution for that.

Great to hear that!!
Yesterday my team was getting issues again with MercadoPago so they were working on fixing the WebView again 😄

**Comment by omodauda** [comment]
> https://developer.android.com/training/basics/firstapp/starting-activity

onshouldStartLoadwithRequest can't return a Promise. 
So, there's no way to use await with startActivityAsync from expo-intent-launcher
@woongbaera89
