### ISSUE TITLE
React-Native webview component not persisting cookies in Auth0 hosted page

### ISSUE THREAD

**Issue by harrylincoln-virginred** [react-native-webview/react-native-webview#2388]
**Background:**
I have a GTM (with Tealium) script [placed in the head](https://developers.google.com/tag-platform/tag-manager/web#custom_web_installations) of an [auth0 hosted page](https://auth0.com/docs/authenticate/login/auth0-universal-login).

This auth0 hosted page is called from a Web client, and a React Native client - both using [auth0's sdk method](https://auth0.com/docs/libraries/auth0js#initialization) `webAuth.authorize()`.

**Call from Web client (expected behaviour):**
- User auths from client
- redirect to hosted auth0 page
- GTM inited and fires some events
👌

The cookies look good and are persisting here.

**Call from React Native client (no cookies present in [WebView](https://github.com/react-native-webview/react-native-webview) redirect):**
- User auths from client
- Webview component pops in-built browser to sign in, navigating to the same auth0 page
- no cookies are present (none at all)
- GTM does not fire
👎

**Versions of deps:**
ios version: "12.1"
react-native-webview: "^8.0.4"
react-native: "0.63.3"
react-native-auth0: "^2.6.0"

**What the React-Native WebView component looks like:**

`<WebView
    ref={webViewRef}
    source={{ uri: source }}
    sharedCookiesEnabled
    thirdPartyCookiesEnabled
    domStorageEnabled
  />`

**Checks:**
- Standard Safari settings to enable third-party cookies

**Thoughts:**
There must be something wrong with the WebView?

**Comment by amagnolo** [comment]
could this be a cookie sync delay issue as described in #1780 ?

**Comment by jensdev** [comment]
@harrylincoln-virginred I have a similar issue. Did you manage to get it working?

**Comment by TommyTheTribe** [comment]
Still have the problem, can't use sso because web browser view opened by authorize() method has no access to cookies. If I copy the link in my web browser, I'm automatically logged in

**Comment by sanjaya1996** [comment]
Any update on this one ? Same issue on our project, SSO not working in react-native-webview component. SSO working fine if I visit the webpage using browser.

**Comment by jheurtin** [comment]
Hey I'm upping this one, I'm having the same issue with a similar usecase

**Comment by jensdev** [comment]
@jheurtin Did you manage to find a solution?

**Comment by SanjayConverge** [comment]
Same issue here. Do you have any update @harrylincoln-virginred  @jensdev  @TommyTheTribe ?

**Comment by sanjaya1996** [comment]
For anyone still experiencing this issue:
Had a long debug session with Auth0 team themselves and it appears to be a bug on Auth0's side that occurs when Organizations are enabled. The error is intermittent — it works at times and fails at others. We've recently reported the issue to the Auth0 production team and are currently awaiting their response.
Hope this helps !
