### ISSUE TITLE
[Webview2 Microsoft Windows] Implements postMessage and inject javascript in Webview2

### ISSUE THREAD

**Issue by kristofb** [react-native-webview/react-native-webview#2390]
[Webview2 implementation for Windows issue](Ref issue: https://github.com/react-native-webview/react-native-webview/issues/1848)

**We need Webview2 to implements javascript injection in order to communicate from ReactNative to the web view content.**
[injectJavascript](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#injectjavascriptstr)

**postMessage / onMessage**
We also need Webview2 component to support « window.postMessage » and the react native Webview2 to support « onMessage », to have a two way bridge communication channel.
[onMessage reference](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#onmessage)

(depends on implementation of AddWebAllowedObject API)

**Comment by asklar** [comment]
For `injectJavaScript`, we can already use the [ExecuteScriptAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.executescriptasync) functionality in corewebview2

For `postMessage`, we can already use the [PostWebMessageAsString](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.postwebmessageasstring) and [PostWebMessageAsJson](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.postwebmessageasstring) functionality. Then the JS code that implements postMessage for Windows needs to call `window.chrome.webview.postMessage(...)`

**Comment by exotexot** [comment]
@tero-paananen I just felt like tagging you. :)

**Comment by chiaramooney** [comment]
Implementation in progress. PR should be out soon.

**Comment by exotexot** [comment]
Hmm
