### ISSUE TITLE
[Webview2 Microsoft Windows] Drag and Drop files from Windows to Webview2

### ISSUE THREAD

**Issue by kristofb** [react-native-webview/react-native-webview#2393]
Ref issue: https://github.com/react-native-webview/react-native-webview/issues/1848

We need Webview2 to forward file drop events to the Webview2 content, so it can handle the file reception. Those files will be dragged from Windows.

**Comment by kristofb** [comment]
still searching for solutions

**Comment by asklar** [comment]
@david-risney is there something in wv2 that makes this possible already today?
cc @chiaramooney

**Comment by david-risney** [comment]
WebView2 has [drag and drop APIs](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2experimentalcompositioncontroller3?view=webview2-1.0.1248-prerelease) (for the composition controller that WinUI2 and WinUI3 WebView2 controls use) but I don't offhand know the state of them or if WinUI2 or WinUI3 WebView2 controls use those APIs. I'll need to get more info.

**Comment by david-risney** [comment]
Talking with folks, it sounds like WebView2 drag and drop should be working, but there are still issues specifically with the WinUI2/3 WebView2 drag and drop support that are in progress. I couldn't find a corresponding github issue (if you're interested in that you might ping the WinUI folks)

**Comment by kristofb** [comment]
Hello,
is there some progress on this issue?
