### ISSUE TITLE
[ANDROID] Problem with injecting javascript into Webview

### ISSUE THREAD

**Issue by hesan-aminiloo** [react-native-webview/react-native-webview#2394]
Hi, I have a variable called `code` and I'm injecting it into the Webview using` injectJavaScript` method but it works only once.
As I update the `code` variable I call this method again but it's not working on android.

**Comment by MyNameIsOka** [comment]
Has there been any progress on this? I am running into the same problem.

**Comment by ste7en** [comment]
I guess this is an intended behaviour. If you need to inject JS code at each navigation state change you need to do it manually, intercepting the change and injecting `code` using a ref to your WebView.
