### ISSUE TITLE
Custom request headers only apply to first request

### ISSUE THREAD

**Issue by jasperkuperus** [react-native-webview/react-native-webview#2396]
**Bug description:**

The source prop for WebView allows to pass additional custom headers. These headers are successfully sent along on the **first request** sent by the webview.

However. When e.g. the loaded pages performs an XMLHTTP request, or a follow up page that is loaded, the headers are **not** sent along.

I do realise this is a repost of an existing issue. The original issue is however closed and does not get any attention from the maintainers, while this is still an active issue that multiple people run into. So, sorry for opening a new issue. But, I believe it is an open issue, and not a closed issue as the other issue makes believe: https://github.com/react-native-webview/react-native-webview/issues/4

**Environment:**
 - OS: macOS
 - OS version: 11.5.2
 - react-native version: 0.67.3
 - react-native-webview version: 11.17.2

**Comment by ste7en** [comment]
If you need it to work on iOS, setting these props will solve the issue. I'm still working on the Android counterpart though.

```jsx
<WebView
  injectedJavaScriptBeforeContentLoaded={`
    XMLHttpRequest.prototype.open = (function(open) {
      return function(method,url,async) {
        open.apply(this,arguments);
        this.setRequestHeader('header1', 'value1');
        this.setRequestHeader('header2', 'value2');
      };
    })(XMLHttpRequest.prototype.open);
  `}
  injectedJavaScriptBeforeContentLoadedForMainFrameOnly={false}
  injectedJavaScriptForMainFrameOnly={false}
  source={...}
/>
```

**Comment by jasperkuperus** [comment]
> If you need it to work on iOS, setting these props will solve the issue. I'm still working on the Android counterpart though.
> 
> ```js
> <WebView
>   injectedJavaScriptBeforeContentLoaded={`
>     XMLHttpRequest.prototype.open = (function(open) {
>       return function(method,url,async) {
>         open.apply(this,arguments);
>         this.setRequestHeader('header1', 'value1');
>         this.setRequestHeader('header2', 'value2');
>       };
>     })(XMLHttpRequest.prototype.open);
>   `}
>   injectedJavaScriptBeforeContentLoadedForMainFrameOnly={false}
>   injectedJavaScriptForMainFrameOnly={false}
>   source={...}
> />
> ```

This actually works in my specific situation! Thanks a lot.

**Comment by ste7en** [comment]
> This actually works in my specific situation! Thanks a lot. This does however not solve the issue present in the other ticket that I referenced.

It's a pity that this so widely-used package isn't well maintained and we're still facing these issues. However, in my case I had to change authentication mechanism in favour of Cookie-based authentication.

**Comment by AMoktar** [comment]
are there any solutions ?

**Comment by MarcoTesta-EP** [comment]
+1

**Comment by KawaljeetRepublic** [comment]
@ste7en you got any solution for android?

**Comment by ste7en** [comment]
> @ste7en you got any solution for android?

No, haven't worked on it anymore.

**Comment by MarcoTesta-EP** [comment]
I bypassed the problem using the UserAgent instead of the custom header, UserAgent is always sent for all requests.

**Comment by ste7en** [comment]
> I bypassed the problem using the UserAgent instead of the custom header, UserAgent is always sent for all requests.

Interesting. Did you manage to pass other headers using User-Agent ?

**Comment by MarcoTesta-EP** [comment]
> > I bypassed the problem using the UserAgent instead of the custom header, UserAgent is always sent for all requests.
> > @MarcoTesta-EP
> > Interesting. Did you manage to pass other headers using User-Agent ?

I had to customize the website calls if they came from an app, so I thought to use the custom headers, but because of this bug I tried to use the user-agent and that worked for all the calls. So if you need to have such a custom behavior you can use user-agent...

**Comment by ste7en** [comment]
Cool! Thanks

**Comment by atticusliu** [comment]
> > > I bypassed the problem using the UserAgent instead of the custom header, UserAgent is always sent for all requests.
> > > @MarcoTesta-EP
> > > Interesting. Did you manage to pass other headers using User-Agent ?
> 
> I had to customize the website calls if they came from an app, so I thought to use the custom headers, but because of this bug I tried to use the user-agent and that worked for all the calls. So if you need to have such a custom behavior you can use user-agent...

@MarcoTesta-EP How specifically did you use user-agent to solve the problem with the Webview? Are you referring to using (react-native-user-agent)[https://github.com/bebnev/react-native-user-agent], or were you simply populating the `userAgent` field in the Webview component?

**Comment by MarcoTesta-EP** [comment]
Hello @atticusliu, I'm populating the userAgent field in the WebView component and using it to have different behaviour in the website (if called in a browser or by the WebView) instead of using the customer header...
I needed to display some pages of the website into the app, but I wanted to remove the header, footer, menu, change some styles... to have the same look and feel of the other app pages. Using the userAgent I know that the calls are done by the WebView and so I can customize the website output.

**Comment by parthindia47** [comment]
For confirmation of others as well are you referring to :
`applicationNameForUserAgent={'MyCustomApp/1.1.0'}`
?

**Comment by MarcoTesta-EP** [comment]
> For confirmation of others as well are you referring to : `applicationNameForUserAgent={'MyCustomApp/1.1.0'}` ?
> 
Correct, I0m referring to applicationNameForUserAgent

**Comment by Michael-Ivlev** [comment]
still got this problem
