### ISSUE TITLE
Displaying a PDF within the Webview

### ISSUE THREAD

**Issue by bjspi** [react-native-webview/react-native-webview#2397]
**Bug description:**
I have a WebView Container for my Webpage. Within my webpage, I link specific PDFs, just as a direct link via `<a href="...pdf">My Link</a>`

How can I force the WebView to display the PDF upon clicking it? Right now, the link is opened in my default browser and from there being downloaded as file. 
As the Webview is, e.g. on Android, based on Chromium, I'd expect Chromium just to show the PDF within the Webview / APP natively.

**To Reproduce:**
Nothing special required, just a pure Webview and a HTML Page with a linked PDF.

**Expected behavior:**
As the Webview is, e.g. on Android, based on Chromium, I'd expect Chromium just to show the PDF within the Webview / APP natively.

**Environment:**
 - OS: Android 11
    "react": "17.0.1",
    "react-native": "0.64.3",
    "react-native-safe-area-context": "3.3.2",
    "react-native-web": "0.17.1",
    "react-native-webview": "11.15.0"

Thank you so much!

**Comment by TheAlmightyBob** [comment]
@bjspi PDF viewing is not a feature of the Android Webview or even of the Chrome browser on Android.

**Comment by bjspi** [comment]
@TheAlmightyBob Thanks Caleb, I was pretty sure PDFs are nowadays natively supported, but alright, you proved me wrong.
Can you give me a slight hint how to enable / implement it, which library could be used together with Expo and React-Native / Webview?

Thanks so much!

**Comment by TheAlmightyBob** [comment]
@bjspi I'm not personally aware of any such library (that doesn't mean none exist though, just that I can't help you), we just let third-party apps handle it for us, as there are many of those (when I try to open a PDF on my personal phone I get a list of ~8 different apps to choose from!)

**Comment by shouse** [comment]
@bjspi It looks like this might solve your issue: https://github.com/wonday/react-native-pdf.  Untested here, but seems viable.

**Comment by eyale** [comment]
There is no correct way to view pdf on Android, webview download file immediately and any pdf package displays only first screen of it

**Comment by GodoyMS** [comment]
You can use Google docs as a viewer proxy:

import { WebView } from 'react-native-webview';
const yourPdfURL="https://example/document.pdf"
      <WebView
   source={{ uri: `https://docs.google.com/gview?embedded=true&url=${yourPdfURL)}` }}
    style={{ width:"100%",height:"100%"}}
  />

**Comment by alveentino** [comment]
> You can use Google docs as a viewer proxy:
> 
> import { WebView } from 'react-native-webview'; const yourPdfURL="https://example/document.pdf" <WebView source={{ uri: `https://docs.google.com/gview?embedded=true&url=${yourPdfURL)}` }} style={{ width:"100%",height:"100%"}} />

but its only support https, not http, please help

**Comment by siiiido** [comment]
@GodoyMS Thanks! It's very helpful!!

**Comment by sarthakpranesh** [comment]
> You can use Google docs as a viewer proxy:
> 
> import { WebView } from 'react-native-webview'; const yourPdfURL="https://example/document.pdf" <WebView source={{ uri: `https://docs.google.com/gview?embedded=true&url=${yourPdfURL)}` }} style={{ width:"100%",height:"100%"}} />

This saved my day, thanks @GodoyMS 
I suppose this works well for most common use cases of viewing PDF in the WebView and should be documented somewhere if not already (I might have missed it). Will be happy to add it if someone can point where this should be.

**Comment by ariq-d** [comment]
> You can use Google docs as a viewer proxy:
> 
> import { WebView } from 'react-native-webview'; const yourPdfURL="https://example/document.pdf" <WebView source={{ uri: `https://docs.google.com/gview?embedded=true&url=${yourPdfURL)}` }} style={{ width:"100%",height:"100%"}} />

With this I can open the PDF succesfully, but how do I open the PDF at a certain page? In desktop browser with 'url.pdf#page=19' works, but not using this solution, any idea how?

**Comment by jeanniton-mnr** [comment]
You can embed a simple React app (not react-native app) inside a WebView. Then, you can display your PDF using the [`react-pdf`](https://projects.wojtekmaj.pl/react-pdf/) package.
    
`react-pdf` seems to be good for display PDF in mobile and desktop browser.
