### ISSUE TITLE
Not able to close a popup inside a WebView

### ISSUE THREAD

**Issue by nairsajjal** [react-native-webview/react-native-webview#2400]
**Bug description:**

While creating a web view with a pop-up inside it, we are not able to close the web view using the command 'window.close()'

**To Reproduce:**

Create a web view with a button which opens up a pop-up. In our case this pop-up is being opened by javascript code itself, so the behaviour is not mutable from react-native side. Opening of popup is being done by the javascript command, window.open()
Once the pop-up is opened the code to close that pop-up comes from javascript itself, which is - 'window.close()', However this code is not executed, as it has the following warning- 'Can't close the window since it was not opened by JavaScript'
Even the window.opener object is not accessible while debugging.
We have tried using the web view in native(swift) code, but everything works fine in that scenario.
**Expected behavior:**

The pop-up window gets closed

**Environment:**
 - OS: MacOS
 - OS version: Montrey(12.2.1 )
 - react-native version:0.67.3
 - react-native-webview version:11.17.2

**Comment by nrajput05** [comment]
Having the same issue as well. Running the same example on native iOS code, the pop-up's window.opener value has the correct location from where it was opened. On executing window.close() on this popup the control goes back to the parent page.

Although from native code we do have to handle delegates to create and close this popup.

`extension ViewController: WKUIDelegate {
    func webView(_ webView: WKWebView, createWebViewWith configuration: WKWebViewConfiguration, for navigationAction: WKNavigationAction, windowFeatures: WKWindowFeatures) -> WKWebView? {
        
        popupWebView = WKWebView(frame: view.bounds, configuration: configuration)
        popupWebView!.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        popupWebView!.navigationDelegate = self
        popupWebView!.uiDelegate = self
        view.addSubview(popupWebView!)
        return popupWebView
    }
    func webViewDidClose(_ webView: WKWebView) {
        if webView == popupWebView {
            popupWebView?.removeFromSuperview()
            popupWebView = nil
        }
    }
}`

**Comment by alessioemireni** [comment]
same here
