### ISSUE TITLE
NSURLErrorDomain - 1001

### ISSUE THREAD

**Issue by sw1tchmx** [react-native-webview/react-native-webview#2402]
![nsurlerrordomain](https://user-images.githubusercontent.com/33660133/157306422-89b76155-fbaa-4b04-98b6-f23718097a21.jpeg)

**Bug description:**
Shows this error sometimes not always

**To Reproduce:**

Open the app 
(some times)

**Environment:**
 - OS: iOS
 - OS version: 14.4.2
 - react-native version: v0.64.0
 - react-native-webview version: 11.15.0

**Comment by sw1tchmx** [comment]
NSURLErrorTimedOut

**Comment by danielazhao** [comment]
It's happening this issue in my app. 

**Environment:**
-  "react-native-webview": "^11.23.1"
- "react-native": "0.64.3"
- iOS: 15.5

@sw1tchmx  did you manage to fix it?
