### ISSUE TITLE
 Your project does not reference "UAP,Version=v10.0" framework. Add a reference to "UAP,Version=v10.0" in the "TargetFrameworks" property of your project file and then re-run NuGet restore.

### ISSUE THREAD

**Issue by Nemtes** [react-native-webview/react-native-webview#2412]
**Bug description:**
I created a new React Native project using the React Native Webview master to test the integration of Webview2.

After adding React Native windows, the webview and performing the steps described in Getting Started, I get an error that the UAP version is missing from the targetframeworks.

**To Reproduce:**
- setup new react native project
- add react native windows
- add react native webview
- try to build it with visual studio 2019

**Expected behavior:**
Build project with error

**Screenshots/Videos:**
![image](https://user-images.githubusercontent.com/1634909/159754922-0835ff03-808f-44b9-8f72-3bb8005fdf36.png)

**Environment:**
 - OS: Windows
 - OS version: Windows 10 Pro - 19042.1526
 - react-native version: 0.68.0-rc.2
 - react-native-webview version: Master

**Comment by chiaramooney** [comment]
This is a product of the use of PackageReference in 0.68. For the rc2 candidate you will need to add a directory.build.props file at the root of the repo with the following contents:

<?xml version="1.0" encoding="utf-8"?>
<Project>

  <PropertyGroup Label="NuGet" Condition="'$(MSBuildProjectExtension)' == '.vcxproj'">
    <ResolveNuGetPackages>false</ResolveNuGetPackages>
  </PropertyGroup>

</Project>

**Comment by Nemtes** [comment]
@chiaramooney Thanks a lot - that solved the problem for me!

**Comment by francisco-mural** [comment]
This save my day, thank you @chiaramooney

**Comment by giregk** [comment]
I'd like to bring a precision : you need to place that file in the directory node_modules/react-native-windows ! otherwise it does not help

**Comment by kevinvangelder** [comment]
I tried adding this in the project root and the node_modules/react-native-windows root but still got the same error. It's also present in the project.vcxproj file.

**Comment by Walia8416** [comment]
@chiaramooney please explain in detail still facing exact same error,
