### ISSUE TITLE
Crash in Production - RNCWebView.m -[RNCWebView webView:decidePolicyForNavigationAction:decisionHandler:]

### ISSUE THREAD

**Issue by e-pradeep** [react-native-webview/react-native-webview#2414]
Fatal Exception: NSInvalidArgumentException
CoreFoundation                 0x119180 __exceptionPreprocess
libobjc.A.dylib                0x59f8 objc_exception_throw
CoreFoundation                 0x92bec _CFArgv
CoreFoundation                 0x1a898 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]
0xb474 +[NSDictionary dictionaryWithObjects:forKeys:count:]
0x7e6618 -[RNCWebView webView:decidePolicyForNavigationAction:decisionHandler:] + 1142 (RNCWebView.m:1142)
0x29dfdc __72-[DTXWKWebView webView:decidePolicyForNavigationAction:decisionHandler:]_block_invoke + 324 (DTXWKWebView.m:324)
[DTXWKWebView webView:decidePolicyForNavigationAction:decisionHandler:canCallOriginal:callOriginal:] + 369 (DTXWKWebView.m:369)
[DTXWKWebView webView:decidePolicyForNavigationAction:decisionHandler:] + 327 (DTXWKWebView.m:327)
WebKit                         0x170e28 (Missing UUID 3a7b114aadeb3ae2b02caf882114d8ef)
WebKit                         0x1d7ddc (Missing UUID 3a7b114aadeb3ae2b02caf882114d8ef)
WebKit                         0x1d8480 (Missing UUID 3a7b114aadeb3ae2b02caf882114d8ef)
WebKit                         0x1d8344 (Missing UUID 3a7b114aadeb3ae2b02caf882114d8ef)
WebKit                         0x3e5d08 (Missing UUID 3a7b114aadeb3ae2b02caf882114d8ef)
WebKit                         0x3db820 (Missing UUID 3a7b114aadeb3ae2b02caf882114d8ef)
WebKit                         0x39ea0 (Missing UUID 3a7b114aadeb3ae2b02caf882114d8ef)
WebKit                         0x1f9918 (Missing UUID 3a7b114aadeb3ae2b02caf882114d8ef)
WebKit                         0x2da30 (Missing UUID 3a7b114aadeb3ae2b02caf882114d8ef)
WebKit                         0x2a96c (Missing UUID 3a7b114aadeb3ae2b02caf882114d8ef)
WebKit                         0x2a78c (Missing UUID 3a7b114aadeb3ae2b02caf882114d8ef)
JavaScriptCore                 0x3c348 (Missing UUID 482a2273da6131d5acd040111251e194)
(Missing UUID 482a2273da6131d5acd040111251e194)
__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
 __CFRunLoopDoSource0
__CFRunLoopDoSources0
 __CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
(main.m:17)
start

**Environment**:

OS: iOS
react-native version: 0.63.3
react-native-webview version : 11.17.2

_Originally posted by @meenunegi in https://github.com/react-native-webview/react-native-webview/issues/1867#issuecomment-1075992219_

**Comment by e-pradeep** [comment]
@jeveloper 
1.  Not a registered device with apple - I am able to reproduce the issue in iOS simulator as well
  iPhone 11 (15.4) ,Xcode version-13.3
2. All the necessary permissions are already present, if any specific permission required related to web view. can you provide here
Also this crash is happening only in random devices

**Comment by jeveloper** [comment]
@e-pradeep 
Sorry, that wasn't helpful i guess. 
I would definitely bump RN to 0.68 (you're likely safe from 0.63) and this lib as well.
Are you even getting a page loaded?

**Comment by e-pradeep** [comment]
Sometimes web view page try to load but there are cases when on navigating to web view itself the app crashes. Tried in RN 0.66.3 as well.

while going through react-native-webview package, there is the potential for request.URL and request.mainDocumentURL to be nil 
[- (void)  webView:(WKWebView *)webView
  decidePolicyForNavigationAction:(WKNavigationAction *)navigationAction
  decisionHandler:]
