### ISSUE TITLE
[iOS 15.4] [iOS] Webview not working properly only on iOS 15.4

### ISSUE THREAD

**Issue by andrespaggy** [react-native-webview/react-native-webview#2422]
**Bug description:**
I'm reporting an issue with a strange behaviour on this library. It happens only on iOS 15.4
I don't know if it depends entirely on this library, but when I try to open a webview, it sends to server more than one request to the page. It means when the request includes authentication, server will respond with 500 error.

**To Reproduce:**
Try to open a webview on a site page that requires authentication.

**Expected behavior:**
I expect to be logged in on the site page inside the webview.

**Environment:**
 - OS: only iOS
 - OS version: only 15.4
 - react-native version: 0.63
 - react-native-webview version: 11.17.2 (but with older versions too)

**Comment by YoFiq** [comment]
Im using auth0 authentification in Webview, and after updating ti 15.4 it stopped working correctly
its opens url as expected but after submitting login and passwor it should redirect to authentification page
But instead i have just blank screen

on Android DeepLinks stopped working from Webview

**Comment by martnd** [comment]
Try allowing popups/redirects in the phone browser. I currently have this issue and am trying to find a way to allow redirects regardless of the setting.  About to try the 'javaScriptCanOpenWindowsAutomatically' flag

**Comment by ezra-dyck-rocketrez** [comment]
We had this issue with a mobile app built in Xamarin and the solution was to add the following snippet to the Info.plist for each domain that was having this issue:
```
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSExceptionDomains</key>
    <dict>
        <key>{domain}</key>
	<dict>
	    <key>NSExceptionRequiresForwardSecrecy</key>
	    <false/>
	</dict>
    </dict>
</dict>
```
We couldn't figure out if this was an issue with our servers or something with the new version of WebView, but this fixed it.

**Comment by bryanltobing** [comment]
is there any update on this?

**Comment by golanshy** [comment]
I'm wondering if this was resolved with the latest iOS updates or is it still an issue. The latest iOS now is 16.5.1c.
