### ISSUE TITLE
Isolated WebView

### ISSUE THREAD

**Issue by joelemanoel** [react-native-webview/react-native-webview#2423]
HI guys,

I would like to know if it is possible to isolate the webviews?
Today when I try to use the same website several times in different Webviews it returns the same content as the previous one.

Thanks.

**Comment by takanorihirai** [comment]
have you tried configuring webview to turn off cache?
https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#incognito
https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#cacheEnabled
https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#cacheMode

or tried to add dummy parameter for pretending other url ?

```
let url = 'https://example.com/?dummy_date='.new Date().getTime();
```

**Comment by joelemanoel** [comment]
> have you tried configuring webview to turn off cache? https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#incognito https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#cacheEnabled https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#cacheMode
> 
> or tried to add dummy parameter for pretending other url ?
> 
> ```
> let url = 'https://example.com/?dummy_date='.new Date().getTime();
> ```

I need to isolate several WhatsApp Web, mainly because they write data to IndexedDB and other data.

**Comment by lennartkloock** [comment]
Why is this closed? Any solution to this?

**Comment by lennartkloock** [comment]
I just found a working solution by using [react-native-cookies](https://github.com/react-native-cookies/cookies). You save the cookies yourself and clear and load them whenever the user switches the focused WebView.
