### ISSUE TITLE
Keyboard dismisses automatically after its opened

### ISSUE THREAD

**Issue by MustafaZouari** [react-native-webview/react-native-webview#2425]
**Bug description:**

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS: MacOS
 - OS version: MacOS Monterey
 - react-native version:"react-native": "0.64.1",
 - react-native-webview version:    "react-native-webview": "^11.6.5",

**Comment by kjurkovicafinitos** [comment]
I am having this exact issue, spent almost 5 hours trying to figure out what is going on until I saw this isssue being opened. @MustafaZouari did you have any luck fixing it?

**Comment by write2lloyd** [comment]
Same issue here.
"react-native": "0.64.2",
"react-native-webview": "11.17.1",

**Comment by paramsinghvc** [comment]
Same issue!
```
<WebView
	source={{ uri: "https://google.com" }}
	// onNavigationStateChange={handleNavigationStateChange}
	userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"
/>
```
```
"react-native-webview": "11.23.0",
```

https://user-images.githubusercontent.com/4329912/183458577-01944e07-c82b-4f63-9451-0fe1a5dcb7d2.mp4

**Comment by nguyenduclong-ict** [comment]
Same issue!
how to fix it

**Comment by nguyenduclong-ict** [comment]
I found solution, error seem from react-navigation old version, because i try without Router everything work well
Updated react-navigation to lastest version will fix error 
Here is all dependencies i updated:
```
 "@react-navigation/native": "^6.0.11",
 "@react-navigation/native-stack": "^6.7.0",
 "react": "18.0.0",
 "react-native": "0.69.4",
 "react-native-safe-area-context": "^4.3.1",
 "react-native-screens": "^3.15.0",
 "react-native-webview": "^11.23.0"
```

**Comment by paramsinghvc** [comment]
Don't remember it's been a year and I've moved to flutter 😅

**Comment by manish-GH** [comment]
The solution is to go to the AndroidManifest file and update `android:windowSoftInputMode="adjustPan"`. Later use `KeyboardAvoidingView` if required
