### ISSUE TITLE
v11.18.0 iOS autolinking

### ISSUE THREAD

**Issue by blazlew** [react-native-webview/react-native-webview#2426]
**Bug description:**

iOS autolinking doesn't work. I downgraded to 11.17.2 and it works

**To Reproduce:**

run: 
```sh
yarn add react-native-webview && cd ios && pod install
```

**Expected behavior:**

Native dependency gets installed

**Environment:**
 - OS: macOS
 - OS version: 12.2.1
 - react-native version: 0.67.2
 - react-native-webview version: 11.18.0

**Comment by b3itgustaf** [comment]
Trying to manually link the package exposes the error:

➜  Frontend.MobileApp git:(master) ✗ npx react-native link react-native-webview
warn Package react-native-webview has been ignored because it contains invalid configuration. Reason: Cannot find module 'react-native-test-app/package.json'

**Comment by jdvvaghelaoffice** [comment]
> Trying to manually link the package exposes the error:
> 
> ```
> warn Package react-native-webview has been ignored because it contains invalid configuration. Reason: Cannot find module 'react-native-test-app/package.json'
> ```

Got the same issue

**Comment by TheAlmightyBob** [comment]
This should be fixed in 11.18.1 via #2413
