### ISSUE TITLE
windows project broke on installing the library

### ISSUE THREAD

**Issue by francisco-mural** [react-native-webview/react-native-webview#2435]
**Bug description:**
Installing `react-native-webview` on a react native windows project makes it stop building

**To Reproduce:**
Windows 10

* `npx react-native init react_native_project`
* `cd react_native_project`
* `npx react-native-windows-init --overwrite`
* if you run here `npm run windows` it works flawlessly
* `npm install react-native-webview`
* `npm run windows` 

**Expected behavior:**
Starts the dev app as before

**Screenshots/Videos:**
```
C:\Users\myuser\workspace\react_native_project\node_modules\react-native-windows\Mso\dispatchQueue\dispatchQueue.h(728,17): error C2607: static assertion failed [C:\Users\myuser\workspace\react_native_project\node_modules\react-native-windows\Microsoft.ReactNative\Microsoft.ReactNative.vcxproj]

C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets(486,5): error MSB4181: The "CompileXaml" task returned false but did not log an error. [C:\
Users\myuser\workspace\react_native_project\node_modules\react-native-windows\Microsoft.ReactNative\Microsoft.ReactNative.vcxproj]

Done Building Project "C:\Users\myuser\workspace\react_native_project\node_modules\react-native-windows\Microsoft.ReactNative\Microsoft.ReactNative.vcxproj" (default targets) -- FAILED.
Done Building Project "C:\Users\myuser\workspace\react_native_project\node_modules\react-native-webview\windows\ReactNativeWebView\ReactNativeWebView.vcxproj" (default targets) -- FAILED.
Done Building Project "C:\Users\myuser\workspace\react_native_project\windows\react_native_project\react_native_project.vcxproj" (default targets) -- FAILED.
Done Building Project "C:\Users\myuser\workspace\react_native_project\windows\react_native_project.sln" (default targets) -- FAILED.
```

**Environment:**
 - OS: Windows 11
 - OS version: 22000.556
 - react-native version: tried with 0.68 and 0.67.4 (same result)
 - react-native-webview version: 11.18.1
 - "react-native-windows":  0.68.0-preview.8 and 0.67.6 (same result)

**Comment by francisco-mural** [comment]
> @francisco-mural Could you try building in VS and paste in the error messages you're getting there, so we can get a little more info!
This is what I have from Visual Studio output on build (not sure if this is exactly what you meant @chiaramooney , please let me  know if more detail is need.

| Severity | Code                                                                                                                    | Description                                                                                                                                                                                                                                                                                                                                                                                                                                        | Project              | File                                                                                                                                       | Line | Suppression State |
|----------|-------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------|--------------------------------------------------------------------------------------------------------------------------------------------|------|-------------------|
| Warning  | MSB4011                                                                                                                 | "C:\Users\fgutierrez\workspace\react_native_project\windows\ExperimentalFeatures.props" cannot be imported again. It was already imported at "C:\Users\fgutierrez\workspace\react_native_project\windows\react_native_project\react_native_project.vcxproj (4,3)". This is most likely a build authoring error. This subsequent import will be ignored.                                                                                            | react_native_project | 4                                                                                                                                          |      |                   |
| Warning  | MSB4011                                                                                                                 | "C:\Users\fgutierrez\workspace\react_native_project\windows\ExperimentalFeatures.props" cannot be imported again. It was already imported at "C:\Users\fgutierrez\workspace\react_native_project\node_modules\react-native-webview\windows\ReactNativeWebView\ReactNativeWebView.vcxproj (3,3)". This is most likely a build authoring error. This subsequent import will be ignored.                                                              | ReactNativeWebView   | 4                                                                                                                                          |      |                   |
| Warning  | MSB4011                                                                                                                 | "C:\Users\fgutierrez\workspace\react_native_project\node_modules\react-native-windows\Microsoft.ReactNative.Cxx\Microsoft.ReactNative.Cxx.vcxitems" cannot be imported again. It was already imported at "C:\Users\fgutierrez\workspace\react_native_project\node_modules\react-native-webview\windows\ReactNativeWebView\ReactNativeWebView.vcxproj (72,5)". This is most likely a build authoring error. This subsequent import will be ignored. | ReactNativeWebView   | 9                                                                                                                                          |      |                   |
| Warning  | MSB4011                                                                                                                 | "C:\Users\fgutierrez\workspace\react_native_project\windows\ExperimentalFeatures.props" cannot be imported again. It was already imported at "C:\Users\fgutierrez\workspace\react_native_project\node_modules\react-native-webview\windows\ReactNativeWebView\ReactNativeWebView.vcxproj (3,3)". This is most likely a build authoring error. This subsequent import will be ignored.                                                              | ReactNativeWebView   | 4                                                                                                                                          |      |                   |
| Warning  | MSB4011                                                                                                                 | "C:\Users\fgutierrez\workspace\react_native_project\node_modules\react-native-windows\Microsoft.ReactNative.Cxx\Microsoft.ReactNative.Cxx.vcxitems" cannot be imported again. It was already imported at "C:\Users\fgutierrez\workspace\react_native_project\node_modules\react-native-webview\windows\ReactNativeWebView\ReactNativeWebView.vcxproj (72,5)". This is most likely a build authoring error. This subsequent import will be ignored. | ReactNativeWebView   | 9                                                                                                                                          |      |                   |
| Warning  | MSB4011                                                                                                                 | "C:\Users\fgutierrez\workspace\react_native_project\windows\ExperimentalFeatures.props" cannot be imported again. It was already imported at "C:\Users\fgutierrez\workspace\react_native_project\node_modules\react-native-webview\windows\ReactNativeWebView\ReactNativeWebView.vcxproj (3,3)". This is most likely a build authoring error. This subsequent import will be ignored.                                                              | ReactNativeWebView   | 4                                                                                                                                          |      |                   |
| Warning  | MSB4011                                                                                                                 | "C:\Users\fgutierrez\workspace\react_native_project\node_modules\react-native-windows\Microsoft.ReactNative.Cxx\Microsoft.ReactNative.Cxx.vcxitems" cannot be imported again. It was already imported at "C:\Users\fgutierrez\workspace\react_native_project\node_modules\react-native-webview\windows\ReactNativeWebView\ReactNativeWebView.vcxproj (72,5)". This is most likely a build authoring error. This subsequent import will be ignored. | ReactNativeWebView   | 9                                                                                                                                          |      |                   |
| Warning  | MSB4011                                                                                                                 | "C:\Users\fgutierrez\workspace\react_native_project\windows\ExperimentalFeatures.props" cannot be imported again. It was already imported at "C:\Users\fgutierrez\workspace\react_native_project\node_modules\react-native-webview\windows\ReactNativeWebView\ReactNativeWebView.vcxproj (3,3)". This is most likely a build authoring error. This subsequent import will be ignored.                                                              | ReactNativeWebView   | 4                                                                                                                                          |      |                   |
| Warning  | MSB4011                                                                                                                 | "C:\Users\fgutierrez\workspace\react_native_project\node_modules\react-native-windows\Microsoft.ReactNative.Cxx\Microsoft.ReactNative.Cxx.vcxitems" cannot be imported again. It was already imported at "C:\Users\fgutierrez\workspace\react_native_project\node_modules\react-native-webview\windows\ReactNativeWebView\ReactNativeWebView.vcxproj (72,5)". This is most likely a build authoring error. This subsequent import will be ignored. | ReactNativeWebView   | 9                                                                                                                                          |      |                   |
| Error    | This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them. | For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is C:\Users\fgutierrez\workspace\react_native_project\windows\packages\Microsoft.UI.Xaml.2.7.0\build\native\Microsoft.UI.Xaml.targets.                                                                                                                                                                                                                   | ReactNativeWebView   | C:\Users\fgutierrez\workspace\react_native_project\node_modules\react-native-webview\windows\ReactNativeWebView\ReactNativeWebView.vcxproj | 186  |                   |
| Warning  | MSB4011                                                                                                                 | "C:\Users\fgutierrez\workspace\react_native_project\windows\ExperimentalFeatures.props" cannot be imported again. It was already imported at "C:\Users\fgutierrez\workspace\react_native_project\windows\react_native_project\react_native_project.vcxproj (4,3)". This is most likely a build authoring error. This subsequent import will be ignored.                                                                                            | react_native_project | 4                                                                                                                                          |      |                   |
| Warning  | MSB4011                                                                                                                 | "C:\Users\fgutierrez\workspace\react_native_project\windows\ExperimentalFeatures.props" cannot be imported again. It was already imported at "C:\Users\fgutierrez\workspace\react_native_project\windows\react_native_project\react_native_project.vcxproj (4,3)". This is most likely a build authoring error. This subsequent import will be ignored.                                                                                            | react_native_project | 4                                                                                                                                          |      |                   |
| Warning  | MSB4011                                                                                                                 | "C:\Users\fgutierrez\workspace\react_native_project\windows\ExperimentalFeatures.props" cannot be imported again. It was already imported at "C:\Users\fgutierrez\workspace\react_native_project\windows\react_native_project\react_native_project.vcxproj (4,3)". This is most likely a build authoring error. This subsequent import will be ignored.                                                                                            | react_native_project | 4                                                                                                                                          |      |                   |
| Error    | MIDL1001                                                                                                                | [msg]cannot open input file [context]Error opening or processing WinMD c:\users\fgutierrez\workspace\react_native_project\windows\x64\debug\reactnativewebview\reactnativewebview.winmd. HRESULT 0x80070003.                                                                                                                                                                                                                                       | react_native_project | C:\Users\fgutierrez\workspace\react_native_project\windows\react_native_project\midlrt                                                     | 1    |                   |
| Error    | MIDL5157                                                                                                                | [msg]An invalid winmd file was specified for import [context]: C:\Users\fgutierrez\workspace\react_native_project\windows\x64\Debug\ReactNativeWebView\ReactNativeWebView.winmd                                                                                                                                                                                                                                                                    | react_native_project | C:\Users\fgutierrez\workspace\react_native_project\windows\react_native_project\App.idl                                                    | 1    |                   |
| Warning  | MIDL2214                                                                                                                | [msg]semantic check incomplete due to previous errors                                                                                                                                                                                                                                                                                                                                                                                              | react_native_project | C:\Users\fgutierrez\workspace\react_native_project\windows\react_native_project\App.idl                                                    | 4    |                   |

**Comment by francisco-mural** [comment]
More hints: 
* the windows package installed is `Microsoft.UI.Xaml.2.8.0-prerelease.210927001` not `2.7.0`
* Changing `node_modules\react-native-webview\windows\ReactNativeWebView\ReactNativeWebView.vcxproj` to use `2.8.0-prerelease.210927001` instead of `$(WinUIPackageVersion)` fails in other place (I don't know where to set env variable TBH)

**Comment by francisco-mural** [comment]
Help us @chiaramooney , you are my only hope.

**Comment by hellodinhhoa** [comment]
I've meet the same issue. 
@francisco-mural you can try config linking manually follow article here: [https://github.com/react-native-webview/react-native-webview/blob/master/docs/Getting-Started.md#windows]
I've tried but not found any

**Comment by hellodinhhoa** [comment]
i've try with new version merged but still build failed for ReactNativeWebView on Visual Studio 2022
My systems information: 
![image](https://user-images.githubusercontent.com/48798162/165690299-782261f1-5e8b-4681-9692-3aa5ec70f7a3.png)

**Comment by hellodinhhoa** [comment]
hi @francisco-mural 
I've tried with version 11.17.2 and another dependencies at bellow, It's work normally. 
![image](https://user-images.githubusercontent.com/48798162/165700884-9d4103bc-9872-4a28-8e5c-a5bf02232242.png)

**Comment by asklar** [comment]
thanks for confirmin @hellodinhhoa!
@francisco-mural let me know if you're still blocked after the latest fix.

**Comment by francisco-mural** [comment]
> hi @francisco-mural I've tried with version 11.17.2 and another dependencies at bellow, It's work normally. ![image](https://user-images.githubusercontent.com/48798162/165700884-9d4103bc-9872-4a28-8e5c-a5bf02232242.png)

But the version of this issue is `^11.18.1` (I am testing `11.18.2` it is still failing), please follow the steps to reproduce this issue with the same scenario.

**This issue is still there**, the latest stable release of this package is breaking the windows launch.

> thanks for confirmin @hellodinhhoa! @francisco-mural let me know if you're still blocked after the latest fix.

following original steps it doesn't work on my machine:

- `npx react-native init react_native_project`
- `cd react_native_project`
- `npx react-native-windows-init --overwrite`
- `npm install react-native-webview`
- `npm run windows`

Rebuilding  `ReactNativeWebView` in VS 2022 (inside `react_native_project.sln`) I have this error

| Severity | Code                                                                                                                    | Description                                                                                                                                                                                                                      | Project            | File                                                                                                                                       | Line | Suppression State |
|----------|-------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------|--------------------------------------------------------------------------------------------------------------------------------------------|------|-------------------|
| Error    | This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them. | For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is C:\Users\fgutierrez\workspace\react_native_project\windows\packages\Microsoft.UI.Xaml.2.7.0\build\native\Microsoft.UI.Xaml.targets. | ReactNativeWebView | C:\Users\fgutierrez\workspace\react_native_project\node_modules\react-native-webview\windows\ReactNativeWebView\ReactNativeWebView.vcxproj | 184  |                   |
|

**Comment by chiaramooney** [comment]
Will take a look today! @francisco-mural Just to confirm since I don't see it in your repo steps did you update ExperimentalFeatures to use  <WinUI2xVersion>2.8.0-prerelease.210927001</WinUI2xVersion>?

**Comment by hellodinhhoa** [comment]
My steps that work for me:

- npx react-native init react_native_project
- cd react_native_project
- npx react-native-windows-init --overwrite
- npm install react-native-webview
- update your app's windows\ExperimentalFeatures.props to use <WinUI2xVersion>2.8.0-prerelease.210927001</WinUI2xVersion>
- yarn windows --logging
- => to see error Missing Nuget Package
- just open your solution on VS 2022 for auto download Nuget Package
- yarn windows --logging

**Comment by francisco-mural** [comment]
> * ust open your solution on VS 2022 for auto download Nuget Package

Thank you very much this works very nice. 

Sorry about the delayed response

**Comment by thienphuoc** [comment]
1. Open the solution and Right click on the ReactNativeWebView project.
2. Manage NuGet Packages...
3. Update version to 2.7 as the image below.

![image](https://user-images.githubusercontent.com/17909394/207800551-3f26669a-03df-4c19-92e9-be80ba2d779c.png)
