### ISSUE TITLE
Android: Links to websites whose apps are installed on the device don't open

### ISSUE THREAD

**Issue by ovbm** [react-native-webview/react-native-webview#2438]
**Bug description:**

If I try to open a link to say youtube.com, but I have the youtube app installed on the test-device, the link won't open. Linking.canOpenUrl will return false. External links that are not whitelisted but without apps on device work fine.

I have two unsatisfactory "solutions" for the problem:

1.  Adding the package name of the specific app to AndroidManifest.xml
```
<queries>
   <package android:name="com.google.android.youtube" />
</ queries>
```

2. Adding the QUERY_ALL_PACKAGES permission
`<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" />`

Solution Nr. 1 is bad, because I can't anticipate which apps a user has. Nr 2 is bad because it will be flagged as a privacy issue.
Any ideas how to approach this?

**To Reproduce:**
AndroidManifest: https://github.com/orbiting/app/blob/main/android/app/src/main/AndroidManifest.xml

**Expected behavior:**
I expect links that are excluded from the whitelist to open in an external browser OR the app that captures the url via deeplinking.

**Environment:**
 - OS: Android
 - OS version: Android 11
 - react-native version: 0.64.2
 - react-native-webview version: 11.18.1

**Comment by dubchoi** [comment]
I'm encountering the same issue. Still looking for a workaround!

**Comment by ThalesBMC** [comment]
Any solution for this?

**Comment by ovbm** [comment]
The solution to this issue was fixing a configuration error ind AndroidManifest.xml. We had to define a wildcard to the host of the https: intent scheme: 

```
<intent>
     <action android:name="android.intent.action.VIEW" />
     <data android:scheme="https" android:host="*" />
 </intent>
```

**Comment by aymkin** [comment]
In my case I try to open the DeepLink `bunq://x-bunk-app/token-qr-request-ideal?token=xxxxxxx`, or can be any other bank app installed on the user's device. But pressing those deep links in the web view does not give any positive result. I just can see a warning in the console `Can't open URL: ....`

Looking for solution

**Comment by Azeem00786** [comment]
@aymkin 
Add the following line inside the web-view component:
originWhitelist={['*']}
Then, you can listen all scheme inside onShouldStartLoadWithRequest method and pass the URL with linking. hope this will work.

**Comment by BlueprintGreg** [comment]
Not working for me either.

**Comment by abraaoz** [comment]
> [@aymkin](https://github.com/aymkin) Add the following line inside the web-view component: originWhitelist={['*']} Then, you can listen all scheme inside onShouldStartLoadWithRequest method and pass the URL with linking. hope this will work.

This is the solution for "open app" button on any YouTube video page loaded inside webview:

```ts
import { Linking, TouchableOpacity } from "react-native";

<WebView
      ...props
      originWhitelist={["*"]}
      onShouldStartLoadWithRequest={({ url }) => {
        if (url.startsWith("intent://m.youtube.com/")) {
          Linking.openURL(url.replace("intent://", "https://"));
          return false;
        } else {
          return true;
        }
      }}
/>
```
