### ISSUE TITLE
Encrypt cookies received from server that are located in /data/data/appfolder/app_webview/Cookies in plain text.

### ISSUE THREAD

**Issue by BrunoKarriqi** [react-native-webview/react-native-webview#2441]
Security team found out that all cookies received from server are located in appfolder/app_webview/Cookies in plain text. 

Is it possible to encrypt this cookie (or all cookies) that are stored in that directory in plain text?

Can you guys please help me, i've stuck for days with this issue?

**Comment by ste7en** [comment]
Can you provide more information to replicate the issue?

**Comment by BrunoKarriqi** [comment]
> Can you provide more information to replicate the bug?

I have to login from a webview in my app and after login react-native-webview stores a jsessionid cookie as a plain text on that directory i have said above

**Comment by lutfi-haslab** [comment]
please open again
