### ISSUE TITLE
APK files are downloaded but cannot be installed directly nor from the my download folder

### ISSUE THREAD

**Issue by amitpatil77** [react-native-webview/react-native-webview#2445]
**Bug description:**
When I download apk file from url which is opened with react-native-webview then file is downloaded successfully but when I click on downloaded file then my Download Manager is not able to install that file (Without any error/ action Download Manager  is dismissed). I need to separately install that file in File Manager and then it is installed.

When I download apk file with external browser then I am able to download and install directly.

**To Reproduce:**

1. Open url (which should have feature to dowload apk file) in webview with react-native-webview in React Native app.
2. File will be downloaded with Download Manager. Wait till file is download.
3. Click on downloaded file in notification tray.
4. Not able to install apk file directly.

**Expected behavior:**

Downloaded file should be installed directly from Download Manager in notification tray.

**Screenshots/Videos:**

https://user-images.githubusercontent.com/53294547/163172328-a42cfe53-6e47-4136-a000-17fffcea38f6.mp4

**Environment:**
 - OS: Android
 - OS version: 30
 - react-native version: 0.63.4
 - react-native-webview version: 10.4.0

**Comment by Symous** [comment]
@amitpatil77 Hi, friend, is there any solution?
