### ISSUE TITLE
Feature Request: Allow webview to access microphone while loading external URL to record or dictate on device

### ISSUE THREAD

**Issue by inglesuniversal** [react-native-webview/react-native-webview#2446]
Actual use case, would allow the following page to work inside WebView:

https://www.google.com/intl/en/chrome/demos/speech.html

NOTE: If there is a better and more stable approach or suggestion please let me know. 

Regards

**Comment by vinayn-mend** [comment]
@inglesuniversal Any update on this? The microphone is not detecting if the webview is invoking microphone access. Need to reload the site to access the mic here. That was the issue right ?

**Comment by Zhou-Bill** [comment]
i have the same question, how to solve?
