### ISSUE TITLE
React Native Webview not loading scripts in production build -iOS

### ISSUE THREAD

**Issue by Joshig99** [react-native-webview/react-native-webview#2448]
Hi, i have html file with scripts, i need to display it in React native screen so i used react-native-webview, it is working fine in ios debug build but not working in ios production build getting blank screen

    <html >
         <meta name="viewport" content="width=device-width, initial-scale=1" />
            <body onload="loader();">

            <script>
               window.fwSettings = {
                  'widget_id': 7300********
               };
            !function () { 
              if ("function" != typeof window.FreshworksWidget)
              { 
                 var n = function () {
                  n.q.push(arguments) 
                  }; 
                    n.q = [],
                  window.FreshworksWidget = n } }() 
            </script>
            <script type='text/javascript' 
                 src='https://widget.freshworks.com/widgets/7*********.js' async defer></script>
            <script>
            function loader() {
               FreshworksWidget('hide', 'launcher');
               FreshworksWidget('open');
             };
           </script>
       </body>
    </html>

i placed this html page in Webview like this

    
         <WebView
            source={kbHTML}
            javaScriptEnabled={true}
           domStorageEnabled={true}
           originWhitelist={['*']}
           scalesPageToFit={false}
           startInLoadingState={true}
           automaticallyAdjustContentInsets={false}
            containerStyle={{
               flex: 1,
              width: '100%',
              height: '100%'
            }}
    
          style={{
             flex: 1,
             height: height,
             width: width,
          resizeMode: 'cover',
      }}

    />

its working fine in ios debug mode but not working in ios production build..getting blank screen.

 - react-native-webview: "^11.18.1", 
 - react-native: "0.64.2"
- IOS

**Comment by peterklingelhofer** [comment]
I can confirm that I am also running into this issue. It doesn't seem that scripts will run from a local HTML file.

**Comment by danXNU** [comment]
You need to add this prop 'allowingReadAccessToURL' to allow the native web view to read files in the directory you want.

https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#allowingReadAccessToURL

https://github.com/react-native-webview/react-native-webview/pull/771

**Comment by Egehanozsoy** [comment]
Any updates on this? still not working on my end @danXNU
