### ISSUE TITLE
Removing/deleting webview.

### ISSUE THREAD

**Issue by tomyates** [react-native-webview/react-native-webview#2449]
I have a webview that is playing video. When I navigate to a new page, or even wrap the webview in a conditional display to hide it, the webview is still active - the audio continues to play.
How do I completely remove the webview from memory? Or do I need to do something slightly hacky like change the url to a blank page?

**Comment by the-mad** [comment]
I'm facing the same issue. Any news about that ?

**Comment by the-mad** [comment]
I found that if you change the location of the webview when the user navigate in your app, it stops the audio playing in the webview. Here is an example if this could help someone : 
`const Component = ({ style }) => {
    const ref = useRef();
    const navigation = useNavigation();

    /**
     * This function is called before the navigation action.
     * Here, if you change the location of your webview, it will stop the audio.
     */
    const clearAudioHack = useCallback(() => {
        if (ref.current) {
            const pause = `
                window.location.href = "https://whatever-site.com";
            
                true;
            `;
            ref.current.injectJavaScript(pause);
        } else {
            console.warn("No ref on the webview...");
        }
    }, [ref.current]);

    /**
     * Listener on the navigation.
     *
     */
    useEffect(() => {
        if (navigation) {
            return navigation.addListener("beforeRemove", clearAudioHack);
        }
    }, [navigation]);

    return <WebView style={style} ref={(instance) => (ref.current = instance)} source={{ uri: "https://..." }} />;
};`
