### ISSUE TITLE
WhatsApp app opens automatically in iOS but not in latest Android (11 and 12), using a web uri

### ISSUE THREAD

**Issue by afilp** [react-native-webview/react-native-webview#2453]
**Bug description:**

The following URL does NOT open the WhatsApp app automatically in Android 11 and Android 12 (while it DOES in iOS and Android 10 and below):
https://api.whatsapp.com/send?phone=9005370455720&text=Please%20send%20us%20your%20details

Instead, it shows the following message:
`“looks like you don’t have whatsapp installed”`
(while we do have the whatsapp app installed)

Interestingly, it opens the WhatsApp app in a version of our app that uses **an older version of react-native-webview** (and react-native): 
"react-native-webview": "^10.10.2"

**To Reproduce:**

Just use this URI to see that the WhatsApp app opens automatically in iOS but not in latest Android (11 and 12):
https://api.whatsapp.com/send?phone=9005370455720&text=Please%20send%20us%20your%20details

**Expected behavior:**

The WhatsApp app should open automatically in latest Android (11 and 12), like it does for all IOS versions and Android 10-.

**Environment:**
 - OS:  Android
 - OS version: 11 & 12
 - react-native version:  "^0.66.1",
 - react-native-webview version:  "^11.14.2"

**Comment by amingsc** [comment]
meet the same issue, 
test with this uri:
https://y.music.163.com/m/song?app_version=8.7.55&id=1364400123&uct=jvo9gcfEZ26Mjrz55/IF4g%3D%3D&dlt=0846

**Comment by afilp** [comment]
@amingsc Thanks a lot, we tried that but still no luck... it did not change anything.

**Comment by afilp** [comment]
Is there something else we should do in order for the WhatsApp to open automatically from within the WebView? (as it used to work?). in iOS it works, but not in latest Android.

**Comment by SaharTo** [comment]
Not working for me too.. is there another solution?

**Comment by SaharTo** [comment]
[Solved] - In my case the WhatsApp link works fine outside of the application and on the web. **but** when I'm using it inside the application webView it's not working and show me screen that says "WhatsApp is not install on this phone" although it is. 

So I look for the WhatsApp api domain to give it permission on my app.. 

solution: 
Inside the AndroidManifestt.xml add this: 

<queries>
    <intent>
      <action android:name="android.intent.action.VIEW" />
      <data android:scheme="https" android:host="api.whatsapp.com"/>
    </intent>
  </queries>

It will allow the app to enter this domain.. 🫡🤓

**Comment by elamranisouhail** [comment]
Not working for me too.. is there another solution?

**Comment by elamranisouhail** [comment]
> 

It's work Good but , My app webview still like this 

![image](https://user-images.githubusercontent.com/16343292/221798955-607c37ed-b2bb-47bc-8949-132d565d2b24.png)
