### ISSUE TITLE
[ANDROID] Deep link under WebVew not worked

### ISSUE THREAD

**Issue by abgaryanharutyun** [react-native-webview/react-native-webview#2454]
**Bug description:** Im tryin to open other application from WebView but it not works it say Cant open `bankId://` url 

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS: Andorid 
 - OS version: Latest
 - react-native version:
 - react-native-webview version:

**Comment by mouhsnimohamed** [comment]
I am having the same issue, did you found any solution for this?

**Comment by abgaryanharutyun** [comment]
Nope, instead of web view I started use web browser for Android, it solved my issue. @mouhsnimohamed

**Comment by mouhsnimohamed** [comment]
@abgaryanharutyun did you get the same error in IOS? for me it wasn't! here is what I got
 
**ANDROID**
errorDomain:  undefined
errorDesc:  **ERR_UNKNOWN_URL_SCHEME**
errorCode:  **-10**

**IOS**
errorDesc: **unsupported URL**
errorCode: **-1002**
errorDomain: **NSURLErrorDomain**

**Comment by mouhsnimohamed** [comment]
I finally fix this by allowing intent in originwhitelist prop

**originWhitelist={['https://*', 'intent://*']}**

**Comment by abgaryanharutyun** [comment]
@mouhsnimohamed now it worked correctly on IOS, issue related only for Andorid, but I solved the issue, for andorid i just opening browser instead of WebView
