### ISSUE TITLE
'WebView' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by felixnotermans** [react-native-webview/react-native-webview#2457]
**Bug description:**

Whenever using the webview library in a tsx component it shows an error:
```
'WebView' cannot be used as a JSX component.
  Its instance type 'WebView<{ source: { uri: string; }; style: { marginTop: number; }; }>' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'React.ReactNode' is not assignable to type '...node_modules/@types/react-native/node_modules/@types/react/index").ReactNode'.
        Type '{}' is not assignable to type 'ReactNode'.
```

**To Reproduce:**

Just setup an App.tsx file and try to use the react-native-webview library:

```
import { Component } from 'react';
import WebView from 'react-native-webview';

class MyWeb extends Component {
  render() {
    return (
      <WebView
        source={{ uri: 'https://infinite.red' }}
        style={{ marginTop: 20 }}
        
      />
    );
  }
}

```
It seems like there is a type mismatch.

**Expected behavior:**

WebView should be usable as a JSX element

**Screenshots/Videos:**

<img width="971" alt="image" src="https://user-images.githubusercontent.com/8666510/165124821-fbaecfc2-3386-483a-8623-2afa48d063a9.png">

**Environment:**
 - OS: Mac OS
 - OS version: 12.13.1
 - react-native version: 0.64.3
 - react-native-webview version: 11.18.1

**Comment by chinieer** [comment]
+1

**Comment by ger88555** [comment]
Apparently [this is a recent **React** problem present on **yarn** projects](https://stackoverflow.com/a/71828113).

You should check the answer on the link for a detailed explanation of the problem, but here's the steps to fix it:

1. Manually add a `"resolutions"` stanza at the end of your `package.json` file pointing to the last versions of `react@^17` and `react-dom@^17` types:

```
"resolutions": {
  "@types/react": "17.0.2"
},
```

2. Run the `yarn` command and wait.

3. Your linter should no longer show this warning.

**Comment by SBS-jtemplin** [comment]
This is still a problem. The solutions in ger88555's stackoverflow link had no effect

npm version: 6.14.17
react-native version: 0.67.2
react-native-webview version: 11.26.1
react-native-windows: 0.67.9
