### ISSUE TITLE
[Android] strange wide space on the top when scroll with html <figure> tag

### ISSUE THREAD

**Issue by dieptang** [react-native-webview/react-native-webview#2462]
**Bug description:**
- I am using Webview for render the html content, and my html have special tag <figure>, when add it to html, I saw very strange space at the top, but I remove the <figure>, it has gone.

**To Reproduce:**
- It's very easy, please add follow this html to the content of webview:

`Bà Nà Hill là “chốn bồng lai tiên cảnh” trong cách gọi của các du khách. Cách thành phố Đà Nẵng từ phía trung tâm hơn 20 km. Khu du lịch nằm trong vị trí đặc địa tại huyện Hòa Vang, thành phố Đà Nẵng. Tính đến hiện tại, Sun World Bà Nà Hill là tổ hợp vui chơi, nghỉ dưỡng hấp dẫn bậc nhất Việt Nam do Sun World quản lý. Mỗi năm, nơi đây đều được phát triển thêm các dịch vụ thú vị để gia tăng thêm trải nghiệm cho khách du lịch. Thật quả không ngoa khi nói đây là điểm đến không thể bỏ lỡ khi tới Đà Nẵng.
<figure class="wp-block-image size-large"><img class="wp-image-10250 aligncenter" src="https://flane.vn/wp-content/uploads/2022/04/le-hoi-tour-ba-na-hills.jpg" alt="Sun World Bà Nà Hill luôn rộn ràng, náo nhiệt (ảnh: sưu tầm)" /><figcaption><em>Sun World Bà Nà Hill luôn rộn ràng, náo nhiệt (ảnh: sưu tầm)</em></figcaption></figure>
Những trải nghiệm không thể bỏ lỡ tại Bà Nà có thể tóm gọn trong 3 từ khóa: giải trí- ẩm thực- nghỉ dưỡng. Đặc biệt hơn cả là trải nghiệm hệ thống cáp treo nổi tiếng, từng mang về rất nhiều kỉ lục thế giới. Vô vàn các điểm tham quan, công trình kiến trúc độc đáo sẽ khiến bạn đi mãi không hết. Cùng khám phá ngay cùng <a href="https://flane.vn">Flane</a> nào!
<h3>Giờ hoạt động của Cáp treo Bà Nà Hill</h3>
Đến Bà Nà Hill mà bỏ qua cáp treo là không được rồi. Đây là hệ thống cáp treo được bình chọn là 1 trong top 10 tuyến cáp treo ấn tượng nhất thế giới. Hệ thống gồm 5 tuyến cáp treo. Với công suất có thể vận chuyển hơn 6.000/ giờ, được đầu tư theo công nghệ hiện đại bậc nhất. Đây chính là niềm tự hào của người dân Đà Nẵng, cũng như của Việt Nam khi có công trình ấn tượng trong top thế giới.`

Sorry, it was not display, I added whole html on attach file

**Expected behavior:**
- It should sroll as normally

**Screenshots/Videos:**
![image](https://user-images.githubusercontent.com/7411097/165287696-601cf83c-ea12-4715-96c3-8cec6ec55d11.png)
[htmlcontent.zip](https://github.com/react-native-webview/react-native-webview/files/8562621/htmlcontent.zip)

**Environment:**
 - OS: Android
 - OS version:  Android 11, Android 12
 - react-native version: 0.67
 - react-native-webview version: last version 11
 - I put Webview inside <Scrollview>

**Comment by buidinhmanh14799** [comment]
minh cũng gặp trường hợp tương tự
