### ISSUE TITLE
Intercepting when data is posted

### ISSUE THREAD

**Issue by erik-kallen** [react-native-webview/react-native-webview#2463]
I am implementing a redirect flow for payments. This consists of an unknown number of page loads, but the flow ends when the user is returned to my site.

I am currently doing it like this:

```
<WebView
    ...
    onShouldStartLoadWithRequest={r => {
        if (new URL(r.url).host === 'mysite.com') {
            props.onReturn(r.url);
            return false;
        } else {
            return true;
        }
    }
/>
```

This works fine when the user is returned to my site with a regular GET. However, some payment methods return the user with a POST back to my site (so `r.navigationType === 'formsubmit'`).

Would it be possible to add a feature to get access to the data that is about to be submitted in the `onShouldStartLoadWithRequest` event?

Or is there another way to figure out what is about to be posted?

**Comment by LuisMesquita** [comment]
Hi, I'm facing a similar issue with my project. Did you manage to find a workaround for it?

**Comment by erik-kallen** [comment]
Nope, I did some horrendous backend hack to fix it.

**Comment by erik-kallen** [comment]
IIRC, what I did was to set the User-Agent header to something special, and then when backend detects that user-agent it just returns

```
<html><script>window.ReactNativeWebView.postMessage(...)</script></html>
```

Horrendous, but it might be an idea.

**Comment by LuisMesquita** [comment]
@erik-kallen Thanks for the help! In my scenario, we're dealing with a third-party payment process, so doing some workaround on the Backend is not possible. But thank you for the help anyway!

**Comment by erik-kallen** [comment]
That's exactly what I did. The payment process will always end back on your site, and if you do it so that page returns the HTML I suggested, it should work.
