### ISSUE TITLE
How to cache a large file? I have a 8M file and will download it every time, it is normal in the browser

### ISSUE THREAD

**Issue by linxianxi** [react-native-webview/react-native-webview#2464]
other files are cached. I don't know why 207 B isn't cached, it used xhr,but it doesn't matter, right
<img width="144" alt="image" src="https://user-images.githubusercontent.com/47104575/165425562-4ca42661-4cd5-4e13-8272-f67369fd1a8f.png">

These two links say there is an upper limit of 20M, is there any way to change it？
https://stackoverflow.com/questions/54573169/webview-not-caching
https://stackoverflow.com/questions/71704544/android-webview-cache-aggressiveness

**Comment by ShiftWatchOut** [comment]
Any solution on caching a large file?
