### ISSUE TITLE
Explain A Clear Way To Navigate In the Webview and Provide Example Codes In Function Components

### ISSUE THREAD

**Issue by AnatuGreen** [react-native-webview/react-native-webview#2466]
Hi, 

There is no clear explanation of how to navigate inside the web pages that load in a webview and it frustrated me.
I had to research for hours before seeing something. [This guide](https://dev.to/mukeshmandiwal/webview-data-flow-with-webviews-in-a-react-native-app-and-navigation-4396)

It will be great for a clear explanation here in the docs. The navigation I am referring to is inside the Webview itself, if I land on the home page of a website, then click on a link to go to another page and then another, when I then click my phone's back button or swipe on the left or right sides of the screen, I expect to be taken one step backward on the webview, not exiting the app or going back to the initial route of the main stack navigation I am using.

I could not get `allowsBackForwardNavigationGestures` to work. I placed it in my Webview and even tried `allowsBackForwardNavigationGestures = {true}`. Still did not work.

And please provide examples with functional components as well as class components.

**Comment by peterklingelhofer** [comment]
I believe `allowsBackForwardNavigationGestures` only works on iOS.

[Here](https://github.com/peterklingelhofer/stream-app) is a working example of these with both iOS (swipe gestures) and Android (back button).

I agree, having some of this stuff in the docs is crucial, especially with the ubiquity of functional components these days.

**Comment by JustinRohweller** [comment]
Just to save some time:
```
const webViewRef = useRef<WebView>(null);
    const onAndroidBackPress = (): boolean => {
        if (webViewRef.current) {
          webViewRef.current.goBack();
          return true; // prevent default behavior (exit app)
        }
        return false;
    };

    useEffect((): (() => void) | undefined => {
        if (Platform.OS === 'android') {
            BackHandler.addEventListener('hardwareBackPress', onAndroidBackPress);
            return (): void => {
                BackHandler.removeEventListener('hardwareBackPress', onAndroidBackPress);
            };
        }
    }, []);

**Comment by peterklingelhofer** [comment]
@AnatuGreen, I've implemented this here, if you'd like to take a look:

https://github.com/react-native-webview/react-native-webview/pull/2609

**Comment by AnatuGreen** [comment]
> @AnatuGreen, I've implemented this here, if you'd like to take a look:
> 
> #2609

Hi Peter, Thank you. I am looking into it now.
