### ISSUE TITLE
Pull to refresh is not working on android with react native webview

### ISSUE THREAD

**Issue by muskan273** [react-native-webview/react-native-webview#2468]
**Bug description:**

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS:
 - OS version:
 - react-native version:
 - react-native-webview version:

**Comment by muskan273** [comment]
Hi I got the solution for this issue, You can also try. I tried to implement pull to refresh webview with android native code and it's working for me.
you can use the below package to enable refresh with webview on android https://github.com/muskan273/react-native-webview

**Comment by muskan273** [comment]
you can use the below package to enable refresh with webview on android https://github.com/muskan273/react-native-webview

**Comment by muskan273** [comment]
Use the package to enable refresh with webview on android https://github.com/muskan273/react-native-webview

**Comment by snaptravel-eng** [comment]
@muskan273 would you be able to help merge this into the main project? We're happy to help sponsor the work. Thanks

**Comment by YAMMOUNII** [comment]
still not working  on android
