### ISSUE TITLE
Weview doesn't shirnk when keyboard is appeared on IOS

### ISSUE THREAD

**Issue by tult98** [react-native-webview/react-native-webview#2471]
**Bug description:**
The height of webview doesn't reduce when I open up the keyborad on IOS 

**To Reproduce:**

I used a `KeyboardAvoidingView` wrap my `Webview` like this 
```
<KeyboardAvoidingView
  behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
  style={isKeyboardOpen ? {
  backgroundColor: 'rgba(0,0,0,0.3)',
  position: 'absolute',
  left: webViewConfig.x,
  top: webViewConfig.show ? y : deviceHeight,
  width: deviceWidth - webViewConfig.x,
  height: deviceHeight - y - keyboardHeight,
  } : {
  backgroundColor: 'rgba(0,0,0,0.3)',
  position: 'absolute',
  left: webViewConfig.x,
  top: webViewConfig.show ? y : deviceHeight,
  width: deviceWidth - webViewConfig.x,
  height:
  deviceHeight - y
  }}
>
  // webivew here
</KeyboardAvoidingView>
```
I even make the height of `KeyboardAvoidingView` is dynamically change when the keyboard is hidden/appeared. 

**Expected behavior:**

Please check the image below. I'd like to make the red section is dissapeared. Or at least make the content of webview fit into the container's space (which is `KeyboardAvoidingView` component) and make it unable to scroll down.

**Screenshots/Videos:**

![Image from iOS](https://user-images.githubusercontent.com/29749097/166857952-bf6786b2-ab46-43a7-83e2-95060032d437.png)
I add `style={{ backgroundColor: 'red' }}` into Weview. As you can see that the webview's content is shirnked as exepected but the red bacground still appear. I'd like to remove it.

**Environment:**
 - OS: IOS
 - OS version: 15.4.1
 - react-native version:  0.64.2
 - react-native-webview version: 11.2.3

**Comment by Sean-lxy** [comment]
> 

try to add `scrollEnabled={false}` in webview component

**Comment by Sean-lxy** [comment]
@tult98 

try to add `scrollEnabled={false}` in webview component

**Comment by tult98** [comment]
> @tult98
> 
> try to add `scrollEnabled={false}` in webview component

Thanks, it solved problem
