### ISSUE TITLE
webview on keyboard display time twice app display 

### ISSUE THREAD

**Issue by xic911appasaheblakade** [react-native-webview/react-native-webview#2472]
Like if user going background side then 50% display app side and 50% web side

<img width="205" alt="Screenshot 2022-05-05 at 1 05 39 PM" src="https://user-images.githubusercontent.com/100779984/166880381-ec88618d-440c-4448-bb47-cd7549f6e127.png">

**Comment by appasaheb4** [comment]
facing issue android side
