### ISSUE TITLE
onMessage not working inside WebView after add enableApplePay

### ISSUE THREAD

**Issue by in-html** [react-native-webview/react-native-webview#2473]
Hello! 
I want to use Apple Pay inside WebView. When I add enableApplePay prop, onMessage event stops working on my site.
I can send data from site to native app but I can't send data from app to WebView.
Is there a way to use this or is it not possible?

**Comment by shahzaib803** [comment]
same issue still 
dose not working still

**Comment by meoner** [comment]
I tried version 10.9.2. My problem is fixed.
