### ISSUE TITLE
File Input Not Working on react-native-macos

### ISSUE THREAD

**Issue by 17Amir17** [react-native-webview/react-native-webview#2476]
**Bug description:**
I created a simple website with nothing but an input element
index.html:
```html
<body>
    <label>
        Click Here
        <input type="file" />
    </label>
</body>
```
app.js:
```jsx
const App = () => {
  return <WebView source={{uri: 'http://127.0.0.1:5500/index.html'}} />
};
```

I then run the native macos app and the input does not work
On safari/chrome/ios/android it does.

**Expected behavior:**
The choose file modal should open

**Environment:**
 - OS: macOs
 - OS version: 12.3.1 
 - react-native: "0.68.2",
 - react-native-macos: "^0.66.0-0",
 - react-native-webview: "^11.18.2"

**Comment by amilich** [comment]
Hello! Need help
