### ISSUE TITLE
iOS: Did not receive response to shouldStartLoad in time, defaulting to YES

### ISSUE THREAD

**Issue by chukiatt** [react-native-webview/react-native-webview#2477]
in iOS i got this error

Did not receive response to shouldStartLoad in time, defaulting to YES

**Comment by gorkmbs** [comment]
#124 this issue is closed but the problem is still continuing.

**Comment by NicolasNinoViancha** [comment]
Hello, this blog details the error and a possible solution.
https://beenlog.tistory.com/14
