### ISSUE TITLE
`onClick` events not registering on Android devices

### ISSUE THREAD

**Issue by TMiller00** [react-native-webview/react-native-webview#2478]
**Bug description:**
`onClick` events do not register on Android devices

We are implementing a WebView in both a React Native and Expo Managed Workflow project that uses some external Javascript to generate a form. iOS can handle all `onClick` events without issue. However, Android `onClick` events do not - maybe 1 out of 25 rapid clicks can perform the expected behavior. `onTouch` events work, however the library we're using uses `onClick` events under the hood.

To further complicate things, this only occurs in Android devices. In the Android simulator, `onClick` events work fine.

**Expected behavior:**
`onClick` events register as they do on iOS

**Environment:**
 - OS: Android
 - OS version: Android 12
 - react-native version: `0.64.3`
 - react-native-webview version: `11.15.0`

**Comment by stefoid** [comment]
I second this.  hyperlinks inside webviews on android are clickable with a mouse on the android emulator, but on a device, it doesnt work reliably.

I believe from experimentation, if you touch very quickly it does work - what I mean is not to hammer the link, but to touch it just one time, by touching down and then lift your finger off very very quickly.  then it seems to work.  but that is way quicker than a normal person would touch the link.

**Comment by lul-g** [comment]
I am having the same click issue on a login text box where it does not work at all but clicking fast as @stefoid described works, but no user will click that fast. Scrolling does not work in WebViews either. I am on expo 54.0.8.

**Comment by lul-g** [comment]
i added the following to the webview and it worked
`javaScriptEnabled
domStorageEnabled
nestedScrollEnabled={true}`
