### ISSUE TITLE
can't get geolocation with react-native-webview and android

### ISSUE THREAD

**Issue by AMoktar** [react-native-webview/react-native-webview#2481]
**Bug description:**
Hello guys, thnaks for this great package.
I cant get geolocation with android 
and it is working fine with ios.

I've set :
`<WebView geolocationEnabled={true} .../>`

I'm using expo managed and I've added permissions 
```
"ACCESS_FINE_LOCATION",
"ACCESS_COARSE_LOCATION",
"FOREGROUND_SERVICE "
```

I've tested this with android physical device and also with android emulator, 
I've make sure the location is enabled .
I also tried to get permission with in the app before the webview is loaded, but not working 

**Environment:**
 - react-native version: 0.68.1
 - react-native-webview version: 11.18.1

Thanks

**Comment by Tapesh-Kumar** [comment]
Is there any update in this issue? 
I'm still facing this issue.

"react-native": "0.70.5",
"react-native-webview": "11.23.1"

**Comment by ClementCHA** [comment]
Any update on this? 🫠
