### ISSUE TITLE
focus is not gained on webview content when switch control is on (iOS)

### ISSUE THREAD

**Issue by moddatherrashed** [react-native-webview/react-native-webview#2483]
**Bug description:**
After making our app accessible compliant, we noticed that the Voice Over screen reader does not behave as the Switch Control screen reader on iOS.

The switch control screen reader does ignore the content of the webview and focuses on the webview as a whole, on android it works just fine, so it seems like it is an iOS issue.

**To Reproduce:**
- Go to the settings > Accessibility > Switch Control
- Turn the Switch Control on
- Go back to the app with a screen that has a webview
- Move the focus to the webview
- Observe that the focus is not gained on the content of the webview

**Environment:**
 - OS: macOS
 - OS version: 12.1
 - react-native version: 0.66.0
 - react-native-webview version: 11.14.2

**Comment by mjdelbianco** [comment]
same here!
