### ISSUE TITLE
Support new architectures and Fabric render system RN 0.68

### ISSUE THREAD

**Issue by xrustic2020** [react-native-webview/react-native-webview#2486]
Would love to see support for the new react 0.68 architecture and the new Fabric rendering system

**Comment by thiavila-sigma** [comment]
Hey, any updates on this?
I'm getting 'Unimplemented component' on my WebView because of the Fabric support...
<img width="334" alt="image" src="https://user-images.githubusercontent.com/72762356/193393287-7ec0c96f-5eaf-49a2-8b6d-3d212633e057.png">

**Comment by Titozzz** [comment]
cc #2686

**Comment by BraveEvidence** [comment]
Check this I have managed to work web view with new architecture https://www.youtube.com/watch?v=Rq-mAjkG2ME&list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i&index=1
