### ISSUE TITLE
Error react-native-webview

### ISSUE THREAD

**Issue by Lucas-Andrade-pc** [react-native-webview/react-native-webview#2488]
Hello, could anyone help me with this error?

React Native
"react-native-webview": "^11.18.2"

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-webview:bundleLibResDebug'.
> Unable to delete file 'C:\Users\lucas.oliveira\Desktop\app\aptalk-mobile\node_modules\react-native-webview\android\build\intermediates\library_java_res\debug\res.jar'

**Comment by ylevygithub** [comment]
Hi everyone ! Can someone help me ? I don't have error with WebView but it just doesnt work. I don't know why it displays a blank page in place of showing me slack.com. Here is my code :

App.js : 

import { StyleSheet, Text, View } from 'react-native';

import ContentView from './ContentView';

export default function App() {
  return (
      <ContentView />
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    justifyContent: 'center',
  },
});

ContentView.js : 

import React from 'react';
import { View } from 'react-native';
import { WebView } from 'react-native-webview';

const styles = {
  container: {
    flex: 1,
  }
};

const ContentView = () => {
  <View style={styles.container}>
    <WebView source={{ uri: 'https://slack.com' }} 
      javaScriptEnabled={true}
      domStorageEnabled={true}
      startInLoadingState={true}
    />
  </View>
};

export default ContentView;


Please help me :)
