### ISSUE TITLE
on New Window Request

### ISSUE THREAD

**Issue by ManuDavril31** [react-native-webview/react-native-webview#2502]
Hello, how are you, I am working with the React Native WebView library, I would like to know how to implement the following:
The website that I am visiting from the webview when completing a form and pressing the continue button, generates another window to display the information that I require, but the window does not load, rather the form is reloaded.
The method is like an onNewWindowRequest.

**Comment by chrisHasBeenTaken** [comment]
any update here, I am working on the same thing in Windows
