### ISSUE TITLE
Website appearing as blank screen 

### ISSUE THREAD

**Issue by Sahilthakur7** [react-native-webview/react-native-webview#2503]
**Bug description:**

When trying to load my website through webview, getting blank white screen. All other websites are loading perfectly well except mine - https://app.ourcryptotalk.com . Device - iOS using expo.

**To Reproduce:**

Set https://app.ourcryptotalk.com as the uri on the Webview Component.

**Expected behavior:**

Website to appear as a webview.

**Comment by alef-carvalho** [comment]
up

**Comment by gulsher7** [comment]
+1

**Comment by KuiGoan** [comment]
+1

**Comment by jsellam** [comment]
The same on adhoc build but not on dev build with the bundler running

**Comment by mainguyenhoi** [comment]
+1

**Comment by zenkhas** [comment]
I had same issue. But I found that my WebView was ScrollView that was causing this. adding flex:1 to ScrollView worked.

**Comment by anuragkumarjsk** [comment]
in my case i want to render html from local a file in the webview, i use 
```
const local_html = require('../../localHtml.html');
<Webview source={local_html} />
```
This works for  ios but for android, it shows the contents of the localHtml file, i.e. the source code itself inside the webview.

is this the expected behavior?

in order to make it work for android i had to pass the html as a string.
```
const contents = `<html>All html source code </html>`
something like :  <Webview source={{html: contents}} />
```
However, the javascript code inside the script tag doesnot work 

can someone help

**Comment by Norfeldt** [comment]
plz dont' close this issue.. its still here

**Comment by zirho** [comment]
When you put WebView in a ScrollView `flex: 1` does not even work.

```
      <ScrollView style={{ flex: 1 }}>
        <WebView
          style={{ flex: 1 }}
          source={{ uri: 'https://---/privacy-policy.html' }}
        />
      </ScrollView>
```
This does not work at all

**Comment by donghuiqiu** [comment]
> When you put WebView in a ScrollView `flex: 1` does not even work.
> 
> ```
>       <ScrollView style={{ flex: 1 }}>
>         <WebView
>           style={{ flex: 1 }}
>           source={{ uri: 'https://---/privacy-policy.html' }}
>         />
>       </ScrollView>
> ```
> 
> This does not work at all
> 
> You should use regular View since WebView takes care of scrolling itself. but it is also possible to put a scroll view around it then, you should give absolute height value for the case. Then it works.

Hello! I have  2 or more links put in WebView tag , so I need to put 2 or more WebView tags in ScrollViews ,setting WebView scrollEnabled for false , How to make it works?
