### ISSUE TITLE
In-app-browser gets message "YOUR BROWSER IS NOT SUPPORTED" when visiting certain websites such as adidas and reebok

### ISSUE THREAD

**Issue by MohammedAK1991** [react-native-webview/react-native-webview#2515]
**Bug description:**

The react-native-webview in app browser when visiting certain websites like adidas, reebok from Spain, the browsing experience gets blocked because the website asks you to update the browser to the latest version of chrome, firefox etc

**To Reproduce:**
Just open the webpage https://www.adidas.es like you open any normal url in the in-app-browser
In react-natice this is the configuration we used

`<WebView 
        ref={webView}
        allowsFullscreenVideo={false}
        allowsInlineMediaPlayback={true}
        mediaPlaybackRequiresUserAction={true}
        onNavigationStateChange={handleWebViewNavigationStateChange}
        scalesPageToFit={true}
        source={{ uri: https://www.adidas.es }} />`

**Expected  @behaviour:**

The in-app-browser must open the website like in any normal browser
I updated the in-app-browser version to the latest and also tried setting different userArgents but it did not work.
I am out of ideas on how to fix this and this is urgent

**Screenshots/Videos:**
![Image from iOS](https://user-images.githubusercontent.com/57530004/171150199-ab5aeef6-b923-4813-82bd-312be1dfa04d.png)

**Environment:**
 - OS: Iphone/ iphone simulator
 - OS version: latest
 - react-native version: ^0.67.2
 - react-native-webview version: ^11.18.2

**Comment by saltyfoam** [comment]
We have a related problem due to userAgent not being supported on Windows so we can't set something appropriate there.

**Comment by MohammedAK1991** [comment]
is there a workaround for this ?
We also found that paypal does not work on the in-app-browser either.
Please provide an update

**Comment by MrRio** [comment]
We found a good workaround is just to set your own userAgent that looks similar to the out the box Safari on iOS and Chrome on Android.

**Comment by MohammedAK1991** [comment]
nice!! can you let us know what userAgent you used exactly?
@MrRio

**Comment by MohammedAK1991** [comment]
wow that worked perfectly... i had tried just a random userAgent before, which is why i think it wasnt working.
- For ios i used `'Mozilla/5.0 (iPhone; CPU iPhone OS 15_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/102.0.5005.87 Mobile/15E148 Safari/604.1'` 
You can also go https://www.whatismybrowser.com/detect/what-http-headers-is-my-browser-sending on ur phone to see what the userAgent looks like

**Comment by mbritton** [comment]
I am desperate for this solution. It is affecting work. My work involves two major mobile apps that support my company's entire business model.

**Comment by mbritton** [comment]
I may have found a solution. Below is my code so anyone having this problem can learn from it.

`const LinkTesterWebviewScreen = ({ route }: any) => {
  const [isLoading, setIsLoading] = useState(true);
  const [url, setUrl] = useState(route.params.url);
  const webViewRef = useRef(null);
  const customUserAgent =
    'Mozilla/5.0 (iPhone; CPU iPhone OS 15_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/102.0.5005.87 Mobile/15E148 Safari/604.1';

  const onNavigationStateChange = (navState: any) => {
    setTimeout(() => {
      setUrl(navState.url);
    }, 2000);
  };

  return (
    <SafeAreaView style={!isLoading && styles.container}>
      {isLoading && <LinkTesterSkeleton />}
      <WebView
        ref={webViewRef}
        androidLayerType="software"
        incognito
        onLoad={() => setIsLoading(false)}
        onNavigationStateChange={onNavigationStateChange}
        javaScriptEnabled={true}
        userAgent={customUserAgent}
        sharedCookiesEnabled={false}
        style={{ flex: 1 }}
        source={{
          uri: url,
        }}
      />
    </SafeAreaView>
  );
};`
