### ISSUE TITLE
onMessage props function is not working on TestFlight

### ISSUE THREAD

**Issue by serverDusrn** [react-native-webview/react-native-webview#2516]
Simulator is fine.
Dom has postMessage function and call this function but webview onMessage callback function is not working on TestFlight.

react-native: 0.65.1
react-native-webview: 11.13.0

**Comment by serverDusrn** [comment]
When I install it to the device via xcode and USB connection it works fine, 
but when I install it to the device via testflight it doesn't work.

**Comment by serverDusrn** [comment]
I really don't know what the problem is.
Is it an iOS version issue?

**Comment by chhornponleu** [comment]
I don't think you can call `window.postMessage` directly.
Use `window.ReactNativeWebView.postMessage` as stated [here](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#onmessage)
