### ISSUE TITLE
Youtube videos do not play in webview [iOS ONLY]

### ISSUE THREAD

**Issue by aditya-keri-betterhalf** [react-native-webview/react-native-webview#2525]
**Bug description:**
Youtube videos do not play in the webview in iOS only, no issues on Android. The same youtube url on Safari plays without any issue.
I've tried this on a brand new react native project as well, same issue. I've seen this issue on both the below react native versions : 
**0.66.4** and **0.68.2**

Additional info :
The following type of urls have this issue :
https://www.youtube.com/c/BetterhalfTVSubscribe
https://www.youtube.com/
https://m.youtube.com

But the following type of urls open the video in full screen mode and play correctly : 
https://www.youtube.com/watch?v=p5wtoUn71RM
https://youtu.be/p5wtoUn71RM

**To Reproduce:**
1. Create a new react native project.
2. Import webview
3. Add : 
```
<WebView source={{uri: 'https://youtube.com'}} />
```

**Expected behavior:**
Video plays.

**Screenshots/Videos:**
![image](https://user-images.githubusercontent.com/90186621/172124704-0bbb70c6-f29d-4f98-a1af-7fc74147d4fd.png)

**Environment:**
 - OS: MacOS
 - OS version: 12.1
 - react-native version: 0.68.2"
 - react-native-webview version: 11.21.1

**Comment by dotdotgod** [comment]
It seems to be a info.plist configuration problem.

I solved it by adding this item to info.plist

```
<key>NSAppTransportSecurity</key>
<dict>
	<key>NSExceptionDomains</key>
	<dict>
		<key>googlevideo.com</key>
		<dict>
			<key>NSExceptionAllowsInsecureHTTPLoads</key>
			<true/>
			<key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
			<true/>
			<key>NSIncludesSubdomains</key>
			<true/>
		</dict>
	</dict>
</dict>
```

**Comment by aqos156** [comment]
I am still having the same issue. Even when I make these plist changes and even when I completely disable ATS using `NSAllowsArbitraryLoads`. Any other ideas?

**Comment by SergiOnGit** [comment]
The same here. Has anyone managed to make youtube embed work iOS?
