### ISSUE TITLE
Download of a blob url doesn't work on Android

### ISSUE THREAD

**Issue by LuanEdCosta** [react-native-webview/react-native-webview#2526]
**Bug description:**
I'm generating a blob URL of an audio and putting it into a link tag `<a>` with the `download` attr. It works well on the browser, but when I click the link on the React Native Webview nothing happens (no errors).

I thought that it was a permission problem, so I added the WRITE_EXTERNAL_STORAGE to AndroidManifest and requested the permission when the app starts, but it didn't work.

**To Reproduce:**
```javascript
// Create a blob URL and pass it to a link tag
// Try to download the audio on the Webview
const blob = new Blob([], { type: 'audio/webm' })
const url = URL.createObjectURL(blob)

<a href={url} download="audio.mp3">Click to Download</a>
```

**Expected behavior:**
The audio must be downloaded to the user's phone.

**Screenshots/Videos:**
App.tsx
![image](https://user-images.githubusercontent.com/36794274/172194765-81733e74-058c-49c4-9ec8-05695d648211.png)

AndroidManifest.xml
![image](https://user-images.githubusercontent.com/36794274/172194992-ea14ac13-4bc9-47a2-9311-3d7564213f3d.png)

**Environment:**
 - react-native version: 0.67.4
 - react-native-webview version: 11.17.2

**Comment by LuciKritZ** [comment]
> Did you solve it, @LuanEdCosta ?

+1

**Comment by LuanEdCosta** [comment]
No, I didn't find a solution. But I also haven't tried it with the latest version of `react-native` and `react-native-webview` yet.

**Comment by xsorren** [comment]
+1 pls helppp

**Comment by wahidshadab** [comment]
+1

**Comment by farellsujanto** [comment]
+1

**Comment by anazaim77** [comment]
+1

**Comment by wahidshadab** [comment]
+1

**Comment by MuhammadRafeh** [comment]
Any solution?

**Comment by jhontech32** [comment]
any solutions?

**Comment by devmuhnnad** [comment]
I have spent hours to find a solution, it turned out that react native doesn't support such a feature 😢

Finally, I had to use native Android with Kotlin, using webChromeClient library,
it worked like magic 🌟 it provides many features to have almost full control over the WebView,
I wrote an implementation to support blob downloading, if someone interested, I could upload the project for you.

**Comment by gabrielsme** [comment]
> I have spent hours to find a solution, it turned out that react native doesn't support such a feature 😢
> 
> Finally, I had to use native Android with Kotlin, using webChromeClient library, it worked like magic 🌟 it provides many features to have almost full control over the WebView, I wrote an implementation to support blob downloading, if someone interested, I could upload the project for you.

I'm interested. Thanks

**Comment by devmuhnnad** [comment]
GOOD NEWS! 

I am working on implementing this feature, so React-native-webview will support Blob download 🔥

The PR is coming in few days, stay around 🔥

**Comment by raviraj-tudip** [comment]
Hi All,

I'm encountering the same issue—I'm unable to download a PDF associated with a blob URL. This problem has been open for quite long time, and we haven't found a solution yet. Could someone please offer assistance?

**Comment by gauravrana0-nagarro** [comment]
try this if it helps in case of video, this solution is working for blob pdf file.
[https://github.com/react-native-webview/react-native-webview/issues/3445#issuecomment-2349318406](url)
