### ISSUE TITLE
App store private api issue [Invalid binary in testflight]

### ISSUE THREAD

**Issue by srithar21** [react-native-webview/react-native-webview#2527]
Hi All,

I am getting the below issue when submitting the app in the testflight.

**To Reproduce:**
 "react-native-webview": "^11.6.5",

**Expected behavior:**

**Screenshots/Videos:**

<img width="771" alt="Screen Shot 2022-06-06 at 2 11 51 PM" src="https://user-images.githubusercontent.com/1001455/172241131-3f4c2f5b-f9f6-44f0-a971-f380541de559.png">

**Environment:**
 - OS: IOS
 - OS version:15.4
 - react-native version: 0.67.2
 - react-native-webview version: "^11.6.5",

**Comment by srithar21** [comment]
Hi All,

Can you please fix this issue?.

**Comment by stevehanson** [comment]
I am also affected by this and have been unable to submit a new build to TestFlight today. After pushing to TestFlight, I get an email rejection with:

> TMS-90338: Non-public API usage - The app references non-public selectors in {app name}: estimatedProgress, initWithFrame:configuration:, isMainFrame, isPassthrough, navigationType, onSuccess:, removeValuesForKeys:completion:, setNavigationDelegate:, setProcessPool:, targetFrame, userContentController, websiteDataStore. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

I am on react-native-webview version 11.13.0. I've been on that same version for months and was able to successfully release a build to TestFlight as recently as this past Thursday. I'm not sure what changed between then and today.

**Comment by tdinckaya** [comment]
I'm having the same problem. What should we do about it?

ITMS-90338: Non-public API usage - The app references non-public selectors in {appname}: estimatedProgress, initWithFrame:configuration:, isMainFrame, isPassthrough, navigationType, onSuccess:, relativeSize, removeValuesForKeys:completion:, setNavigationDelegate:, setProcessPool:, spanArray, spanArray_Count, underline, userContentController, websiteDataStore. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

**Comment by tdinckaya** [comment]
> I am also affected by this and have been unable to submit a new build to TestFlight today. After pushing to TestFlight, I get an email rejection with:
> 
> > TMS-90338: Non-public API usage - The app references non-public selectors in {app name}: estimatedProgress, initWithFrame:configuration:, isMainFrame, isPassthrough, navigationType, onSuccess:, removeValuesForKeys:completion:, setNavigationDelegate:, setProcessPool:, targetFrame, userContentController, websiteDataStore. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/
> 
> I am on react-native-webview version 11.13.0. I've been on that same version for months and was able to successfully release a build to TestFlight as recently as this past Thursday. I'm not sure what changed between then and today.
> 
> React Native: 0.66.3 React Native Webview: 11.13.0 OS: macOS Monterey 12.4 XCode: 13.3 Target platform: iOS Hermes: off

I sent the release on Saturday without any problems. I can't understand what is not suitable right now.

**Comment by TechSupportPlugnotes** [comment]
Maybe the cause was the current update service as account, Code-level support, ect, https://developer.apple.com/system-status/, before 5PM i could send to tesflight , and now during this update i receive directly also the same error as @ulyssesrr

**Comment by LupulescuAlexandru** [comment]
What seemed to be working for me was to delete [if (!navigationAction.targetFrame.isMainFrame)](https://github.com/react-native-webview/react-native-webview/blob/master/apple/RNCWebView.m#L312). I know it's a pretty bad patch because it might break the target="_blank" functionality for some, but it's worth trying until things get resolved.

The error is really weird because at least the method _initWithFrame:configuration:_ is [definitely a public API](https://developer.apple.com/documentation/webkit/wkwebview/1414998-initwithframe?language=objc).

**Comment by stevehanson** [comment]
This worked for me, too!

> delete [if (!navigationAction.targetFrame.isMainFrame)](https://github.com/react-native-webview/react-native-webview/blob/master/apple/RNCWebView.m#L312). I know it's a pretty bad patch because it might break the target="_blank" functionality for some, but it's worth trying until things get resolved.

**Comment by erotundo** [comment]
I staying checking the code as crazy guy, i uploaded a testflight version half hour before the maintenance . Hopefully this temporal patch can works. Thanks!

**Comment by erotundo** [comment]
> What seems to be working for me is to delete [if (!navigationAction.targetFrame.isMainFrame)](https://github.com/react-native-webview/react-native-webview/blob/master/apple/RNCWebView.m#L312). I know it's a pretty bad patch because it might break the target="_blank" functionality for some, but it's worth trying until things get resolved.
> 
> The error is really weird because at least the method _initWithFrame:configuration:_ is [definitely a public API](https://developer.apple.com/documentation/webkit/wkwebview/1414998-initwithframe?language=objc).

Works! You are a crack!

**Comment by ccheney** [comment]
This patch worked for us, take note of @LupulescuAlexandru's warning above

```patch
diff --git a/node_modules/react-native-webview/apple/RNCWebView.m b/node_modules/react-native-webview/apple/RNCWebView.m
index 63b19ea..8678a19 100644
--- a/node_modules/react-native-webview/apple/RNCWebView.m
+++ b/node_modules/react-native-webview/apple/RNCWebView.m
@@ -309,9 +309,9 @@ - (BOOL)canPerformAction:(SEL)action withSender:(id)sender
  */
 - (WKWebView *)webView:(WKWebView *)webView createWebViewWithConfiguration:(WKWebViewConfiguration *)configuration forNavigationAction:(WKNavigationAction *)navigationAction windowFeatures:(WKWindowFeatures *)windowFeatures
 {
-  if (!navigationAction.targetFrame.isMainFrame) {
-    [webView loadRequest:navigationAction.request];
-  }
+  // if (!navigationAction.targetFrame.isMainFrame) {
+  //   [webView loadRequest:navigationAction.request];
+  // }
   return nil;
 }
 

```

**Comment by TheAlmightyBob** [comment]
Thanks for all the investigation here. Has anybody tried replacing `isMainFrame` with `mainFrame`?

Judging by https://developer.apple.com/documentation/webkit/wkframeinfo/1503096-mainframe?language=objc, it seems like perhaps `isMainFrame` _is_ indeed supposed to be private and `mainFrame` is the public version...?

**Comment by mbiang** [comment]
Getting a similar error message.

> ITMS-90338: Non-public API usage - The app references non-public selectors in ComGofullstackChildrenofthe20sStaging: callWithArguments:, createRequest, determineAppInstallationAttributionWithCompletionHandler:, estimatedProgress, frameInfo, identityToken, initWithFrame:configuration:, initWithURL:configuration:, initWithURL:entersReaderIfAvailable:, isMainFrame, lookupAdConversionDetails:, onSuccess:, setNavigationDelegate:, setProcessPool:, setRequestedOperation:, setRequestedScopes:, spanArray, spanArray_Count, toDouble, toString, userContentController, viewManager, websiteDataStore. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

Commenting out the following line and then building in expo `expo build:ios` doesn't seem to work for me.

`// if (!navigationAction.targetFrame.isMainFrame) {
//   [webView loadRequest:navigationAction.request];
// }`

in node_modules/react-native-webview/apple/RNCWebView.m

**Comment by azozaya** [comment]
> Thanks for all the investigation here. Has anybody tried replacing `isMainFrame` with `mainFrame`?

Tested and getting same error.

**Comment by TheAlmightyBob** [comment]
@mbiang @azozaya I think the `isMainFrame` thing _was_ our hope of a quick resolution.... is the error from Apple still mentioning `isMainFrame` even though you're not using it anymore??

**Comment by azozaya** [comment]
@TheAlmightyBob Yes, I got exactly the same error.

**Comment by RayHughes** [comment]
> @mbiang @azozaya I think the `isMainFrame` thing _was_ our hope of a quick resolution.... is the error from Apple still mentioning `isMainFrame` even though you're not using it anymore??

I think `CocoaAsyncSocket` is causing issues too

**Comment by TheAlmightyBob** [comment]
`mainFrame` definitely doesn't look private based on the docs, so it's feeling like something's broken on Apple's end...

**Comment by mbiang** [comment]
@RayHughes @TheAlmightyBob @azozaya it does seem like it may be an issue on Apple's end.   Lots of other reports out there 

- https://github.com/ionic-team/capacitor/issues/5661
- https://github.com/facebook/react-native/issues/33789#issuecomment-1147928476
- https://github.com/flutter/flutter/issues/105471

Oh the joys of working on mobile engineering.  We have a major release happening this week, and I guess the last round of bug fixes likely won't make it out :)

**Comment by TechSupportPlugnotes** [comment]
> Getting a similar error message.
> 
> > ITMS-90338: Non-public API usage - The app references non-public selectors in ComGofullstackChildrenofthe20sStaging: callWithArguments:, createRequest, determineAppInstallationAttributionWithCompletionHandler:, estimatedProgress, frameInfo, identityToken, initWithFrame:configuration:, initWithURL:configuration:, initWithURL:entersReaderIfAvailable:, isMainFrame, lookupAdConversionDetails:, onSuccess:, setNavigationDelegate:, setProcessPool:, setRequestedOperation:, setRequestedScopes:, spanArray, spanArray_Count, toDouble, toString, userContentController, viewManager, websiteDataStore. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/
> 
> Commenting out the following line and then building in expo `expo build:ios` doesn't seem to work for me.
> 
> ```
> // if (!navigationAction.targetFrame.isMainFrame) {
> //   [webView loadRequest:navigationAction.request];
> // }
> ```
> 
> in node_modules/react-native-webview/apple/RNCWebView.m
> 
> I was just able to submit this exact same build friday. Any hope of a quick resolution to this one?

Maybe write this ?

`- (WKWebView *)webView:(WKWebView *)webView createWebViewWithConfiguration:(WKWebViewConfiguration *)configuration forNavigationAction:(WKNavigationAction *)navigationAction windowFeatures:(WKWindowFeatures *)windowFeatures
{
  //if (!navigationAction.targetFrame.isMainFrame) {
    //[webView loadRequest:navigationAction.request];
  //}
    if (navigationAction.targetFrame == nil) {
        [webView loadRequest:navigationAction.request];
    }
  return nil;
}`

I found a part of this solution in link from code => https://stackoverflow.com/questions/25713069/why-is-wkwebview-not-opening-links-with-target-blank/25853806#25853806

My app build and pass to upload, and she working normaly but i'm not sure that was correct because i'm just an javascript developper.

**Comment by matinzd** [comment]
It seems that this started happening from yesterday's maintenance after WWDC. 
Until now, it seems that it is nothing specific to this library at the moment, as it is a broader issue across other third-party modules too.

**Comment by BennSandoval** [comment]
"The issue has been resolved on the app validation backend. Please try resubmitting. Sorry for the trouble."
by Developer Tools Engineer https://developer.apple.com/forums/thread/127678?page=6

-Confirmed on my project
