### ISSUE TITLE
Getting user location fails when user only grants approximate location on Android

### ISSUE THREAD

**Issue by ayau** [react-native-webview/react-native-webview#2530]
**Bug description:**
onGeolocationPermissionsShowPrompt is currently hardcoded to request `ACCESS_FINE_LOCATION` only. Even if `<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />` is defined in the Manifest, Android still asks if the user wants to give Approximate (coarse) or precise (fine) location. If the user chooses approximate, the location request fails, saying user denied permission.

**To Reproduce:**
* Add `<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />` to Android Manifest.
* Set `geolocationEnabled={true}` on webview
* Trigger getting location in javascript with `window.navigator.geolocation.getCurrentPosition((position) => {})`
* Android will prompt user to select either approximate or precise location. Select approximate location
* `getCurrentPosition` fails with the error that user denied permission.

**Expected behavior:**
onGeolocationPermissionsShowPrompt should support both ACCESS_FINE_LOCATION and ACCESS_COARSE_LOCATION depending on which one is granted

**Screenshots/Videos:**
<img width="286" alt="image" src="https://user-images.githubusercontent.com/1381132/172445589-076791ba-0562-4382-8e45-3c3caeb021b5.png">

**Environment:**
 - OS: Android
 - OS version: Android 12 (API 31)
 - react-native version: 0.68.1
 - react-native-webview version: 11.18.1

**Comment by liquidvisual** [comment]
Did you ever figure this out? I've been banging my head over this bug for years.
