### ISSUE TITLE
iOS: Unable to open new Window/Pop-up.

### ISSUE THREAD

**Issue by kantipudikesava** [react-native-webview/react-native-webview#2533]
1. I am seeing white screen while opening new window/pop-up in iOS devices. 
2. In android i am able to see the new window/pop-up.
3. I have enabled javaScriptEnabled & javaScriptCanOpenWindowsAutomatically.

Can anyone help me to resolve this issue in iOS devices. 

Thank you.

**Comment by xiaoxiong470** [comment]
I had the same problem. If you have solved  the problem,please tell me. Thanks very much

**Comment by sudharsanvishnu** [comment]
how to open new window inside webview for android ? @kantipudikesava

**Comment by jfries289** [comment]
This should not be closed. This has suddenly become a major issue for us as we need to be able to use the Firebase popup for authentication (due to 16.1 Firebase issues), and popup is failing to show. Just getting a blank screen.

**Comment by jaic231** [comment]
any solutions?
