### ISSUE TITLE
Warning: dispatchCommand was called with a ref that isn't a native component. Use React.forwardRef to get access to the underlying native component

### ISSUE THREAD

**Issue by Robiullah2244** [react-native-webview/react-native-webview#2538]
**Bug description:** Initially loaded the view of the source URL. But when clicking on a link it shows this warning and it does not load the new view

**To Reproduce:** Load a webview and click a link on the website

**Expected behavior:** Should go to the new link

**Environment:**
 - OS: Android
 - OS version: 8.1.0
 - react-native version: 0.66.4
 - react-native-webview version: 11.22.0

**Comment by Titozzz** [comment]
Thanks I will take a look asap

**Comment by Titozzz** [comment]
@Robiullah2244 I fixed it from my phone, let me know if that works for you

**Comment by Robiullah2244** [comment]
> @Robiullah2244 I fixed it from my phone, let me know if that works for you

@[Titozzz](https://github.com/Titozzz) Yes, fixed in version 11.22.1. Thank you so much.

**Comment by Titozzz** [comment]
Thanks for the feedback 😊

**Comment by vaibhavthapliyal31** [comment]
Try this instead : Mock console.error calls to prevent warnings 
```
beforeAll(() => {
  jest.spyOn(global.console, 'error').mockImplementation(() => {});
});
afterAll(() => {
  global.console.error.mockRestore();
});
test('my test case title', () => {
  // the tests
});
```
