### ISSUE TITLE
General Question: Which prop or setting is required for Background Audio Playback while using WebView?

### ISSUE THREAD

**Issue by inglesuniversal** [react-native-webview/react-native-webview#2539]
use case:  

I loaded in an HTML5 audio player and ran a test on both Android and iOS devices, using Expo SDK 45. The audio will play normally and will advance to next audio track as long as the screen is turned on. If the screen fades out on either platform (Android or iOS), the audio track may play for a few seconds more and not skip forward to the next track even if played until the end of the track.

Any ideas or suggestions how to fix this issue?

Thanks

**Comment by thaindgit** [comment]
Any update of this?

**Comment by inglesuniversal** [comment]
Hi @thaindgit I'm patiently waiting on a reply about this issue as well.

What I can tell you though, my quickest fix for this was to simply enable the KeepAway API through the following Expo library. I hope it is useful to you.

https://docs.expo.dev/versions/latest/sdk/keep-awake/

**Comment by thaindgit** [comment]
> 
Thanks for your quick response.
According to [this](https://github.com/react-native-webview/react-native-webview/issues/1034) we can use [injectedJavaScript](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#injectedjavascript) to do this, but we can encounter a problem with PlayStore on android if playing youtube's video in background.
