### ISSUE TITLE
Socket.io inside webview does not work

### ISSUE THREAD

**Issue by ordinaryprobably** [react-native-webview/react-native-webview#2540]
**Bug description:**
I have a react app that runs on web browser. It has a chat feature that uses socket.io. The feature works perfectly on web. However when I open it in my RN webview, server-side socket does not seem to catch any connection from the client.
I saw that [somebody issued similar problem](https://github.com/react-native-webview/react-native-webview/issues/1885) here but it is closed without any solution.
I am using expo to build my app. 
If any of you had a similar experience, please share how you solved it.

**Environment:**
 - OS: Mac OS
 - OS version: 12
 - react-native version: 0.68.2
 - react-native-webview version: 11.18.1

**Comment by balkrushnag** [comment]
Same issue being faces by us for Razorpay payment gateway. It is not working in the react-native-webview but working on web browser.

**Comment by edugrip** [comment]
1. How to reproduce this? 
2. Can you show some error logs? Use this: 
var socket = io();
socket.on('popup', function(msg){
    console.log("hello: ", msg)
});
socket.on('connection', function() {
    console.log("client connected");
});

socket.on('connect_error', function(err) {
    console.log("client connect_error: ", err);
});

socket.on('connect_timeout', function(err) {
    console.log("client connect_timeout: ", err);
});
3. @balkrushnag  shouldn't you consider creating a separate issue for this?

**Comment by balkrushnag** [comment]
> 1. How to reproduce this?
> 
>     2. Can you show some error logs? Use this:
>        var socket = io();
>        socket.on('popup', function(msg){
>        console.log("hello: ", msg)
>        });
>        socket.on('connection', function() {
>        console.log("client connected");
>        });
> 
> 
> socket.on('connect_error', function(err) { console.log("client connect_error: ", err); });
> 
> socket.on('connect_timeout', function(err) { console.log("client connect_timeout: ", err); }); 3. @balkrushnag shouldn't you consider creating a separate issue for this?

@edugrip I was waiting for reply from razorpay support. Now they solved the issue. It was not related to webview.

**Comment by balkrushnag** [comment]
> Facing same issue for Razorpay payment gateway. It is not working in the react-native-webview but working on web browser.

This is solved for me, it was issue with razorpay server, not webview.

**Comment by ordinaryprobably** [comment]
@edugrip I am sorry for not providing the code. I was already too tired of changing code until realizing that socket does not work (or not the way it does on other web browsers) on WebView. 

To tell how I resolved the issue was by making a new RN screen for chatroom that connects to the socket. So, if the user wants to start a chat with somebody and the user is on App, it sends 
```
if (window.isNativeApp) {
      const link = {
        type: "CHATROOM",
        userId: user.id,
        roomId: chatroom.roomId,
        friendId: chatroom.id,
        friendImage: chatroom.image,
        friendName: chatroom.name,
      };

      window.ReactNativeWebView.postMessage(`${JSON.stringify(link)}`);
    }
```
and on RN side, it handles the message like this.
```
  const handleMessage = ({ nativeEvent }) => {
    const messageFromWebView = nativeEvent.data;

    if (messageFromWebView === "navigationStateChange") {
      return setNavState(nativeEvent);
    }

    const parsedMessage = JSON.parse(messageFromWebView);

    if (parsedMessage.type === "CHATROOM") {
      navigation.navigate("ChatRoom", {
        userId: parsedMessage.userId,
        roomId: parsedMessage.roomId,
        friendId: parsedMessage.friendId,
        friendImage: parsedMessage.friendImage,
        friendName: parsedMessage.friendName,
      });
    }
  };
```
The socket code you suggested looks partially different from what I wrote, but I have to say that I cannot rollback the code and apply yours.
