### ISSUE TITLE
The dropdown list show white text on Android

### ISSUE THREAD

**Issue by ngohuy0972** [react-native-webview/react-native-webview#2542]
Hello guys!
I have problems when I use the web-view in my project.
Anyone else has the same as this problem, please share the solution with me
Thank you so much!

**Bug description:**
The text of all the dropdown lists is a white color.

**To Reproduce:**

- Step 1: Open the W3school in the WebView.
- Step 2: Touch the dropdown list.
- Step 3: Show the dropdown list with white text.

**Expected behavior:**
Show black text. _(This issue just shows on the Android devices)_

**Screenshots/Videos:**
![Screenshot_20220615-164125_STG ](https://user-images.githubusercontent.com/49360277/173787967-ea4e9b71-525a-4d52-ae0e-5da27fa382fa.jpg)

**Environment:**
 - OS: _MacOS montery 12.4_
 - OS version: _All versions Android_
 - react-native version: _0.65.1_
 - react-native-webview version: _11.22.2_

**Comment by jsw0184** [comment]
@ngohuy0972 Any solutions for this?
