### ISSUE TITLE
React Native IOS , Can not disable video autoplay

### ISSUE THREAD

**Issue by Manoj201** [react-native-webview/react-native-webview#2544]
Can not disable video autoplay on react native IOS

**Environment:**
 - OS: IOS

**Comment by hojunin** [comment]
me either. `allowsInlineMediaPlayback` check property to true and `playinlines` property video tag doesn`t work too. did you resolve it?

**Comment by hojunin** [comment]
<img width="833" alt="implement" src="https://user-images.githubusercontent.com/18079523/174565758-82ecc1a7-ac1e-4894-9eba-efc8e98ee129.png">

above code is in WebView.ios.tsx.
i think several properties are not delivered to Native WebView Module isn`t it?

**Comment by adamalexander** [comment]
@hojunin any luck?

**Comment by Manoj201** [comment]
Still having issues, Is anyone have a solution?

**Comment by Manoj201** [comment]
Also, If we going to play that video again its coming another warning,

<img width="355" alt="image" src="https://user-images.githubusercontent.com/5594092/174679324-8dbfec28-c11f-444d-af45-03056c91a90b.png">

**Comment by hojunin** [comment]
what it makes problem is, we pass several properties to `react-native-webview` but `react-native-webview` does not to ios Native module(WKWebview)

so, i make [pull request](https://github.com/react-native-webview/react-native-webview/pull/2548) but not merged yet. 

check two things can help.

1. change version : [issue link](https://github.com/react-native-webview/react-native-webview/issues/1035)
2. initialize mandatorily :  open your_project/ios/your_project.xcworkspace and root, Pods/Development Pods/react-native-web. edit variable to constant (ex. _allowsInlineMediaPlayback -> YES)

![스크린샷 2022-06-21 오전 9 15 47](https://user-images.githubusercontent.com/18079523/174691804-45e46391-f559-407f-870e-7ff4c1d8cc5f.png)

![스크린샷 2022-06-21 오전 9 18 30](https://user-images.githubusercontent.com/18079523/174691867-6196297a-f00f-4f5c-b183-adab0d21d750.png)

**Comment by hojunin** [comment]
@adamalexander 

it`s good to resolve problem. 😆
but this way would be dangerous. 

my [pull request](https://github.com/react-native-webview/react-native-webview/pull/2548) is merged and released `react-native-webview` 11.22.3 will be doing well.

so rollback that mandatory initialize and update your react-native-webview to latest version(11.22.3). 

@Manoj201 this issue is resolved. we could close issue 🚀

**Comment by adamalexander** [comment]
@hojunin You are a gentleman and a scholar. 😆

**Comment by danilaberentsev** [comment]
can confirm, can't prevent video autoplay/open in fullscreen on IOS, react-native-webview@^11.22.4
is there any solutions? I tried @hojunin solution but no luck

**Comment by adamalexander** [comment]
@danilaberentsev Do you have version 11.22.33?

**Comment by hojunin** [comment]
@danilaberentsev 
check the html element that play video is `<video/>` and that tag has property `playsinlines`. 
if these condition has no problem, react-native-webview (11.22.33 above) do well.

**Comment by danilaberentsev** [comment]
I have 11.22.4 version of package checked it in yarn.lock
https://api.pro-appetit.com/storage/files/000/000/000/sample-5s(16).mp4 here's the video I'm trying to render
i don't think i can change anything regarding html since it just plain file link

**Comment by hojunin** [comment]
@danilaberentsev 

the reason why is the video tag in your link doesn`t have property` playsInline`. without this property set `true`, IOS always use ios native player

this is your video.

<img width="361" alt="스크린샷 2022-06-30 오전 9 06 23" src="https://user-images.githubusercontent.com/18079523/176565833-fa69fd75-8ee8-4496-85de-4a255eb83ed7.png">

and what video tag has to be is below.

<img width="325" alt="스크린샷 2022-06-30 오전 9 09 44" src="https://user-images.githubusercontent.com/18079523/176566111-fd4ed65b-bacc-497e-8bc5-5950fc028e7a.png">

**Comment by danilaberentsev** [comment]
Please, correct me if I'm wrong, but isn't it default tag by browser itself rendering direct video link?
If so I have no control over it, and if anything it should not have impact on webview at all?
I mean it's just uri of video file, not a video player...
