### ISSUE TITLE
Library has compilation issue with Android sdk 33 

### ISSUE THREAD

**Issue by AndroidDev08** [react-native-webview/react-native-webview#2547]
**Bug description:**
Lib Compilation issue on Android sdk 33 

**To Reproduce:**
Issue can be reproduced by simply using the existing lib and targeting the **compileSdkVersion = 33**

**Expected behavior:**
App should build.

**Screenshots/Videos:**

RNCWebviewManager has compilation issues

react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java:277: error: cannot find symbol
        view.getSettings().setAppCachePath(ctx.getCacheDir().getAbsolutePath());
                          ^
  symbol:   method setAppCachePath(String)
  location: class WebSettings

react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java:279: error: cannot find symbol
        view.getSettings().setAppCacheEnabled(true);
                          ^
  symbol:   method setAppCacheEnabled(boolean)
  location: class WebSettings

**Environment:**
 - OS: Android
 - OS version: 13 (api level 33) 
 - react-native version: 0.68.1
 - react-native-webview version: Reproducible with latest and older versions (11.22.2,  11.2.3 tried this versions for test)

**Comment by abanoubdev** [comment]
I have also the same issue with android 13 native implementation
while i migrated it to 33 ,setAppCacheEnabled and setAppCachePath can not be resolved
Is there any replacement for them ?

**Comment by sohanshettyv** [comment]
Any alternative api for setAppCacheEnabled and setAppCachePath in android 13 version?

**Comment by artyorsh** [comment]
These methods [were deprecated on Android SDK level](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/webkit/WebSettings.java#1158). They are no-op in Android 13 and it seems they are safe to simple be dropped from the RN app code base. As per the docs:
```
Consider using Service Workers instead. See https://web.dev/appcache-removal/ for more information.
```

**Comment by bukshi** [comment]
Hi, any work around on this bug? still can find a way for this..

**Comment by julianD77** [comment]
@bukshi This was resolved in 11.22.7 and so should no longer be a problem if you just update to the latest [version](https://github.com/react-native-webview/react-native-webview/releases/)

> 🎉 This issue has been resolved in version 11.22.7 🎉
> 
> The release is available on:
> 
> * [npm package (@latest dist-tag)](https://www.npmjs.com/package/react-native-webview/v/11.22.7)
> * [GitHub release](https://github.com/react-native-webview/react-native-webview/releases/tag/v11.22.7)
> 
> Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot 📦🚀

**Comment by PradoGuilherme** [comment]
> 🎉 This issue has been resolved in version 11.22.7 🎉
> 
> The release is available on:
> 
> * [npm package (@latest dist-tag)](https://www.npmjs.com/package/react-native-webview/v/11.22.7)
> * [GitHub release](https://github.com/react-native-webview/react-native-webview/releases/tag/v11.22.7)
> 
> Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot 📦🚀

This worked for me! Tks!

**Comment by yogendrajs** [comment]
after updating to `v11.22.7` and also tried the latest version `v13.x`, while building the Android version, I got the following error, any idea?
```
Unable to resolve module ./RNCWebViewNativeComponent from 'node_modules/react-native-webview/lib/WebView.android.js'
```

**Comment by tungthanh1497** [comment]
> 

Can you give me detailed instructions on resetting the metro bundler cache?

**Comment by tungthanh1497** [comment]
> after updating to `v11.22.7`, while building the Android version, I got the following error, any idea?
> 
> ```
> Unable to resolve module ./RNCWebViewNativeComponent from 'node_modules/react-native-webview/lib/WebView.android.js'
> ```
> 
> Edit: this was due to the metro bundler cache issue, fixed by resetting the cache!

Can you give me detailed instructions on resetting the metro bundler cache?

**Comment by yogendrajs** [comment]
> Can you give me detailed instructions on resetting the metro bundler cache, please?

@tungthanh1497 yeah, try running `npm start -- --reset-cache`
