### ISSUE TITLE
Google pay button is not showed

### ISSUE THREAD

**Issue by iyyappanrock535** [react-native-webview/react-native-webview#2550]
The Google pay button is not shown. I'm have integrated the stripe google pay button in my react app. And set the react app url in my mobile app webview, But the google pay button not showed. The chrome and other browser I call the react app URL it's working Good

**Comment by mohamed-arradi** [comment]
If it is about "Google Pay not working" it might make sense as Google Pay is not compatible with WebView. You need to use native bridge. 

Here below the notes from Google (source: https://developers.google.com/pay/api/web/support/faq)

`Does the Google Pay API integration work in WebViews?`

 `For Android apps which use WebViews, you must invoke platform specific Android Google Pay APIs. See [Binding JavaScript code to Android code](https://developer.android.com/guide/webapps/webview#BindingJavaScript) for examples.`

**Comment by zain-khalid** [comment]
Facing same issue with google pay.
