### ISSUE TITLE
react native firebase messaging().onMessage not triggered when WebView component exist

### ISSUE THREAD

**Issue by james104** [react-native-webview/react-native-webview#2551]
**Bug description:**
react native firebase messaging().onMessage not triggered when WebView component exist
Is there anything from WebView component may block the network usage or something like that?

**To Reproduce:**
Apply messaging().onMessage and WebView component on the same page

**Expected behavior:**
onMessage can be triggered

**Environment:**
 - OS: Android
 - OS version: 12
 - react-native version: 0.67.4
 - react-native-webview version: 11.22.2

**Comment by lyseiha** [comment]
+1

**Comment by lyseiha** [comment]
+1
