### ISSUE TITLE
React-native Webview doesn't support the ogg format audio 

### ISSUE THREAD

**Issue by NensiKasundra** [react-native-webview/react-native-webview#2552]
Hello Team,

Thank you for this webview to load all the web content quickly. 

I am unable to load the .ogg format audio file in webview. .mp3 and .wav are working properly. 
```

         <WebView
                ref={webViewDocRef}
                javaScriptEnabled={true}
                domStorageEnabled={true}
                scalesPageToFit={false}
                source={{
                 uri: `https://upload.wikimedia.org/wikipedia/commons/archive/c/c8/20110814131356%21Example.ogg`
               }}
         />

```
This code will display alpha numeric content in the webview.

[**Environment:**]([url](url))
 - OS: iOS
 - OS version: 15.5
 - react-native version: 0.67.2
 - react-native-webview version: 11.17.2

**Comment by TheAlmightyBob** [comment]
iOS WKWebView does not support .ogg. You'll need to find another solution.

**Comment by adityar-r** [comment]
@TheAlmightyBob which format does iOS WKWebView support, do we have an documentation?
