### ISSUE TITLE
Implement Android's WebView `setAcceptFileSchemeCookies` to allow cookies in locally loaded sites

### ISSUE THREAD

**Issue by WiXSL** [react-native-webview/react-native-webview#2556]
Use case:

I'm loading a bundled web project inside a `WebView` using `src: file:///android_asset/`.
Upon running, the project communicate with a remote php site that manages user sessions via `document.cookie`.
Currently, this is not working with a `WebView` since `document.cookie` is empty because `document.location` is of type file://.

For what I've research, This can be achived by implementing [setAcceptFileSchemeCookies](https://developer.android.com/reference/android/webkit/CookieManager.html#setAcceptFileSchemeCookies(boolean)) in the project.

Thank you for your work in the WebView!

**Comment by mirsylvain** [comment]
It seems that setAcceptFileSchemeCookies is deprecated but [WebViewAssetLoader](https://developer.android.com/reference/androidx/webkit/WebViewAssetLoader) is used instead. Do you manage to add it to the webview component ?

Thank you

**Comment by WiXSL** [comment]
@mirsylvain,
Yes, I manage to implement `setAcceptFileSchemeCookies` in my project by following the [docs](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Custom-Android.md).
But that only solve the PHP session cookie to be set automatically in document.cookie.
I can't send the cookie to the server, so for now I'm not using file:// protocol, I'm calling the raw website directly.

**Comment by WiXSL** [comment]
I believe this has been implemented #2897
