### ISSUE TITLE
'injectJavaScript' method not working on Android in v11.22.0 or greater

### ISSUE THREAD

**Issue by svroomen** [react-native-webview/react-native-webview#2557]
I have a WebView setup to communicate with the app rendered inside of it. Everything works fine in `v11.21.2`. But it stops working in `v11.22.0` or greater. I saw one error in my app when running Jest tests related to the new version of `react-native-webview`, but nothing blows up. 

The WebView itself seems to load just fine when running the app, but its blank.  After trying to debug through the issue, I realized that communications from the HTML inside the WebView were being recieved by the WebView, but messages from the host/WebView were not getting to the HTML app inside the WebView. 

It looks like the `injectJavaScript` command is not working on Android anymore. It works fine on iOS.

I cannot upgrade to the new version until that works again.

**This is the line of code I am using to send messages to the nested app which no longer seems to work on Android.**

```
// post messages to the WebView. webViewRef is the WebView reference saved on the class instance.
this.webViewRef.injectJavaScript(`window.postMessage(${JSON.stringify(payload)}, '*');`);
```

**This is the error I saw when running Jest tests for Android only. iOS/Web tests passed.**

```
TypeError: Cannot read property 'isFileUploadSupported' of undefined
```

**Again, this only happens when upgrading to v11.22.0 or greater.**

**Comment by tradebulls** [comment]
Are you using React.createRef to create a reference, if yes then try this.webViewRef.current.injectJavaScript

**Comment by svroomen** [comment]
> Are you using React.createRef to create a reference, if yes then try this.webViewRef.current.injectJavaScript

I am not using `React.createRef` in this instance. It is being stored in a piece of state.

Regardless of whether it is being stored in another ref, or in state, that line, and the rest of the code works with `react-native-webview@11.21.2`. It does not work in `react-native-webview@^11.22.0` on **Android**. It works fine on iOS.

When I logged the stored ref in the console, I saw all the method signatures on the object. No errors are being raised when calling it either, it just does nothing on Android.

As far as I can tell when looking through the commits for that version, a fair amount of refactoring was done with the `injectJavaScript` method along with other things. I am fairly positive it has something to do with the package change.

**Comment by TheAlmightyBob** [comment]
Do other commands work? e.g. `reload`, `goBack`?

**Comment by rafaelmaeuer** [comment]
I was also facing `TypeError: Cannot read property 'isFileUploadSupported' of undefined` after updating react-native-webview above `v11.22.0`.

The corresponding change (remove static from function definition) was made in:
https://github.com/react-native-webview/react-native-webview/pull/2508/files#diff-8576be466ba1cccbe7c11ba839c58655910cfcea677ad1de381d2a5194089ad8R209

However this causes jest to fail when testing the library, as it requires `NativeModules` to be mocked.
With help of [react-native/issues/28839#issuecomment-625453688](https://github.com/facebook/react-native/issues/28839#issuecomment-625453688) I was able to write a jest-mock, for tests to pass.

Here is the snippet (put it in `__mocks__/react-native.js`):

```js
jest.mock('react-native', () => {
	// use original implementation, which comes with mocks out of the box
	const ReactNative = jest.requireActual('react-native')

	// mock modules/components created by assigning to NativeModules
	ReactNative.NativeModules.RNCWebView = {
		// mock for react-native-webview (android)
		isFileUploadSupported: jest.fn(),
	}

	return ReactNative
})
```

**Comment by svroomen** [comment]
@rafaelmaeuer Since we use some imports inside our `jestSetupFile.js` I ended up having to put that code snippet inside that file. But aside from that difference it worked perfectly. 

Jest tests are passing without issues now.

**Comment by rkenmi** [comment]
Can confirm that on v11.22.x `ref.injectJavaScript()` doesn't work on Android. Downgrading from v11.22.x to v11.18.1 fixes it. On a side note, the `injectedJavaScript` prop on `<WebView/>` works fine on either version.

```javascript
export default function App() {
  const pageRef = useRef(null);
  return (
    <View style={styles.container}>
      <WebView
        onMessage={() => {}}
        ref={pageRef}
        source={{uri: 'https://reactnative.dev/'}}>
      </WebView>
      <Button title={'Title'} onPress={() => {
        if (pageRef !== null) {
          pageRef.current.injectJavaScript("alert('hi')");
        }
      }}/>
      <StatusBar style="auto" />
    </View>
  );
}
```

**Comment by svroomen** [comment]
Just bumping this in the hopes its not forgotten.

**Comment by TheAlmightyBob** [comment]
@svroomen Can you or others share a Snack that repros this? I actually looked into it fairly recently but it worked fine for me so I assumed it had already been fixed or wasn't really an issue.

**Comment by svroomen** [comment]
@TheAlmightyBob What version of react-native are you using? I have a suspicion that maybe we are not on the same one or something.

I guess a quick background, I have a package that uses the WebView to render an app which is then used inside another app. Inside the packages project I have a test app to make sure it all works before publishing it and using it in other apps.

Just today I updated my test app from Expo 45 - Expo 46. Which interestingly enough broke the WebView on Android again in the same way that upgrading to v11.22.0+ did. I did some more thorough testing this time around and even verified on a basically blank WebView pointing at google that `injectJavaScript` was not working. But other commands like `reload/goBack` and such were. I also triple checked the communication setup between the host app and the WebView app. Everything was working as expected. `injectedJavaScript` also kept working when things were broken.

**(1) This is what I was using originally when it broke when upgrading react-native-webview:**

```
    "expo": "^45.0.0",
    "react": "17.0.2",
    "react-native": "0.68.2",
    "react-native-webview": "11.22.0"
```
**(2) This is what I was using when it broke again after upgrading Expo:**

```
    "expo": "^46.0.0",
    "react": "^18.0.0",
    "react-native": "^0.69.5"
    "react-native-webview": "11.21.2"
```

What seems to have fixed it for me in my test app is to use Expo 46 and upgrade to react-native-webview 11.23.0.

After I did that, it started working on Android/iOS without issues.

**(3) What I have now that seems to work:**

```
    "expo": "^46.0.0",
    "react": "^18.0.0",
    "react-native": "^0.69.5"
    "react-native-webview": "11.23.0"
```
I still have to finish upgrading the main host app so that I can verify the package and WebView work there. If it does, I think that is the solution to my issue.

**Comment by TheAlmightyBob** [comment]
@svroomen I tested with React Native 0.66.4 (though I wouldn't expect that to make a difference here), with both `react-native-webview` 11.21.1 & 11.23.1.

It's very odd to me that you had issues with 11.21.2... that was before the "breaking" change of 11.22.0, which is the only thing I could imagine being related to this issue.

**Comment by svroomen** [comment]
> @svroomen I tested with React Native 0.66.4 (though I wouldn't expect that to make a difference here), with both `react-native-webview` 11.21.1 & 11.23.1.
> 
> It's very odd to me that you had issues with 11.21.2... that was before the "breaking" change of 11.22.0, which is the only thing I could imagine being related to this issue.

I am also very confused about how it broke on 11.21.2. I was honestly just guessing at the react-native version maybe doing something. It was the only other global change that I think could affect the WebView package. Either way, I did just confirm today that Expo 46 paired with `react-native-webview@11.23.0` fixes the whole issue for me in my host app.

Not sure if anyone else who was experiencing this issue managed to find a different (or real) solution.

**Comment by svroomen** [comment]
Since this is working after the expo upgrade I am closing this.

**Comment by CoatedMoose** [comment]
I am currently using expo 47 (bare), RN 70, and seeing this issue on react-native-webview 11.26.0.

Applying the change by @rafaelmaeuer ([here](https://github.com/react-native-webview/react-native-webview/issues/2557#issuecomment-1175130704)), I can get the tests passing again.
