### ISSUE TITLE
Bad performance when scroll up/down

### ISSUE THREAD

**Issue by minhchienwikipedia** [react-native-webview/react-native-webview#2561]
**Bug description:**

When we use Webview to open a website, we just compare it with another browser, do you guys have any idea to improve performance? 
**To Reproduce:**

Open any website and scroll up/down, especially on the android devices we can see it lagging too much
**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS: any
 - OS version: any
 - react-native version: 0.66.4
 - react-native-webview version: 11.14.2

**Comment by jrobinsonadrenaline** [comment]
Still trying to solve this as well. Anyone have ideas?
