### ISSUE TITLE
Task :react-native-webview:compileDebugJavaWithJavac FAILED with LATEST REACT-NATIVE VERSION: 0.69.0 (ANDROID)

### ISSUE THREAD

**Issue by ravi123saxena** [react-native-webview/react-native-webview#2564]
buildscript {
    ext {
        buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31

 "dependencies": {
    "react": "18.0.0",
    "react-native": "0.69.0",
    "react-native-webview": "^11.22.3"
  },

**Comment by iamiota** [comment]
For a temporary fix:
update `android/build.gradle`  to
17 line `classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.21")`
25 line `classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.21")`

**Comment by alysonvilela** [comment]
Same issue.

After updating @iamiota temporary fix, I receive this message
```
❯ yarn android
yarn run v1.22.19
$ react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 968 file(s) to forward-jetify. Using 8 workers...
info JS server already running.
info Installing the app...

6 actionable tasks: 2 executed, 4 up-to-date

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file 'C:\Users\alysonvn\dev\new_app_corretor\android\app\build.gradle' line: 18

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find method classpath() for arguments [org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.21] on project ':app' of type org.gradle.api.Project.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':app'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 9s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file 'C:\Users\alysonvilela\dev\myapp\android\app\build.gradle' line: 18

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find method classpath() for arguments [org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.21] on project ':app' of type org.gradle.api.Project.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':app'.
```

**Comment by iamiota** [comment]
@alysonvilela 
The updated file path is `${your project path}/node_modules/react-native-webview/android/build.gradle`
NOT `${your project path}/android/build.gradle`

**Comment by rajeevverma076** [comment]
Any update?

 What went wrong:
A problem occurred configuring project ':react-native-webview'.
> Could not determine the dependencies of null.
   > Could not resolve all task dependencies for configuration ':react-native-webview:classpath'.
      > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.0.
        Required by:
            project :react-native-webview
         > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.0.
            > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.6.0/kotlin-gradle-plugin-1.6.0.pom'.
               > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.6.0/kotlin-gradle-plugin-1.6.0.pom'.
                  > The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. See: https://docs.gradle.org/7.3.3/userguide/build_environment.html#gradle_system_properties
                     > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by TingC92233** [comment]
@rajeevverma076  same issue 😭。。Does anyone have a solution？？？
