### ISSUE TITLE
Webview Slower Than Accessing Via Web Browser 

### ISSUE THREAD

**Issue by putuoka** [react-native-webview/react-native-webview#2566]
in same network & internet connection do open the link from PC browser at the same time open the webview with apps from android device & emulator but this time open the webview apps first than link in PC browser. result is the link in the PC browser load first while webview from apps still loading although we open it first it still load behind. different is very huge around 6-15 sec delay

**Expected behavior:**
the load time should be the same in browser PC and webview apps

**Environment:**
 - OS: Android
 - OS version: Android Emulator & Real device android version 11
 - react-native version: "0.63.4",
 - react-native-webview version: "^11.22.2",

**Comment by minhchienwikipedia** [comment]
I think it's the same here #2561 
Can we find a way to improve performance?

**Comment by ashirkhan94** [comment]
same issue for me , any update
 thanks

**Comment by keerthipativinaykumar** [comment]
one solution : enable dom storage in react native webview and use webviews with cdns urls from backend its really as fast as in chrome browser     

1. collapsable={false}
2. cacheEnabled={false}
3. cacheMode={'LOAD_NO_CACHE'}
4. domStorageEnabled={true}

i have tried this and improved webview performance not only latest devices but also every version of android devices

**Comment by minhchienwikipedia** [comment]
Thank @keerthipativinaykumar I'll try it

**Comment by 17Amir17** [comment]
@keerthipativinaykumar How does `collapsable={false}` help? Couldn't find in API Reference

**Comment by Daha62** [comment]
This solution doesn't work

**Comment by co2nut** [comment]
Tried, does not seems to work as well.
