### ISSUE TITLE
Can't open URL about:srcdoc on IOS 

### ISSUE THREAD

**Issue by Manoj201** [react-native-webview/react-native-webview#2567]
I'm facing an issue in IOS devices, showing a warning can't open the URL about:srcdoc . I have attached the screenshot below.

Here is my code block,
  ```
<WebView
        source={{uri: url}}
        mediaPlaybackRequiresUserAction={false}
        androidLayerType="hardware"
        mixedContentMode="always"
        textZoom={100}
        decelerationRate={0.998}
        allowsInlineMediaPlayback={true}
        injectedJavaScript={INJECTED_SCRIPTS}
        cacheEnabled
        onShouldStartLoadWithRequest={req => {
          if (req.url.startsWith('about')) {
            return false;
          }
          return true;
        }}
        style={{height: scrollViewHeight}}
        ref={webviewRef}
      />
```

I have handled this using,
```
onShouldStartLoadWithRequest={req => {
          if (req.url.startsWith('about')) {
            return false;
          }
          return true;
        }}

```
but it's not fixing the issue. 

**Screenshots/Videos:**
<img width="390" alt="image" src="https://user-images.githubusercontent.com/5594092/175899480-34ad3bf7-bcd0-41ea-86ec-6c95af7eafd6.png">

**Environment:**
 - OS: IOS
   "react-native-webview": "^11.22.3",

**Comment by Manoj201** [comment]
Hello.. Is anyone having this issue?

**Comment by BenMcLoughlin** [comment]
For me the warning goes away when I pass in the prop: 

`originWhitelist={['*']}`

then it might look like this: 
```
export default function App() {
  return (
    <WebView
      originWhitelist={['*']}
      source={{ uri: 'https://www.google.com' }}
    />
  );
}
```

**Comment by Manoj201** [comment]
Thank you @BenMcLoughlin, Yes, It works...

**Comment by samcamps** [comment]
added the prop but doesn't fix the issue...

**Comment by AnatuGreen** [comment]
@BenMcLoughlin Worked! Thanks. Although the explanation of what the prop does as seen in VS code is really not clear. I would love to know why exactly it solved the issue.

**Comment by orkylish** [comment]
if anyone is still encountering this issue after trying this solution above:

`export default function App() {
  return (
    <WebView
      originWhitelist={['*']}
      source={{ uri: 'https://www.google.com' }}
    />
  );
}`

you may wish to try specifying specific origins like this

`export default function App() {
  return (
    <WebView
      originWhitelist={['http://', 'https://', 'about:']}
      source={{ uri: 'https://www.google.com' }}
    />
  );
}`

In my case while using react-native-webview v13.10.5, * wildcard seemed not to be allowing requests to URLs with custom schemes like about:srcdoc. Warnings in console while loading page may help to determine the scheme
