### ISSUE TITLE
Execution failed

### ISSUE THREAD

**Issue by Talha-raj** [react-native-webview/react-native-webview#2568]
**Bug description:**

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS:
 -OS version:
 - react-native version: OS version: 
 - react-native version: 0.69.0
 - react-native-webview version: 11.22.3

**Comment by kyle-ssg** [comment]
Try the following in android/build.gradle, it works for me 

```
buildscript {
    ext {
        kotlinVersion = "1.6.21"  // <---
```

**Comment by Talha-raj** [comment]
> Try the following in android/build.gradle, it works for me
> 
> ```
> buildscript {
>     ext {
>         kotlinVersion = "1.6.21"  // <---
> ```

damm thanks its woked for me also

**Comment by emyduke** [comment]
Thanks, it worked for me

**Comment by Biplovkumar** [comment]
add this in to /android/build.gradle

```
def REACT_NATIVE_VERSION = new File(['node', '--print',"JSON.parse(require('fs').readFileSync(require.resolve('react-native/package.json'), 'utf-8')).version"].execute(null, rootDir).text.trim())

allprojects {

//...


configurations.all {
    resolutionStrategy {
        // Remove this override in 0.65+, as a proper fix is included in react-native itself.
        force "com.facebook.react:react-native:" + REACT_NATIVE_VERSION
    }
    }

}
```

**Comment by oneil-marcelo** [comment]
Thanks @Biplovkumar
It's work for me!

**Comment by colantuomo** [comment]
@Biplovkumar solution worked for me too!

**Comment by PrasadFeker** [comment]
Thanks @Biplovkumar
Worked for me.

**Comment by kulpubekov** [comment]
@Biplovkumar build was successfully created, but the application open and close immediately.

**Comment by brunoscardoso** [comment]
> 

same here :/

**Comment by kingzee100** [comment]
Worked!

**Comment by oneil-marcelo** [comment]
@kulpubekov Try these configuration

`buildscript {
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 24
        compileSdkVersion = 30
        targetSdkVersion = 30
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.5.4")
        classpath ("com.google.gms:google-services:4.3.3")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

def REACT_NATIVE_VERSION = new File(['node', '--print',"JSON.parse(require('fs').readFileSync(require.resolve('react-native/package.json'), 'utf-8')).version"].execute(null, rootDir).text.trim())
allprojects {
    repositories {
        google()
        mavenLocal()
        mavenCentral()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        maven { url 'https://www.jitpack.io' }
    }
    configurations.all {
    resolutionStrategy {
        // Remove this override in 0.65+, as a proper fix is included in react-native itself.
        force "com.facebook.react:react-native:" + REACT_NATIVE_VERSION
    }
    }
}`

**Comment by gabrielorei1234** [comment]
> add this in to /android/build.gradle
> 
> ```
> def REACT_NATIVE_VERSION = new File(['node', '--print',"JSON.parse(require('fs').readFileSync(require.resolve('react-native/package.json'), 'utf-8')).version"].execute(null, rootDir).text.trim())
> 
> allprojects {
> 
> //...
> 
> 
> configurations.all {
>     resolutionStrategy {
>         // Remove this override in 0.65+, as a proper fix is included in react-native itself.
>         force "com.facebook.react:react-native:" + REACT_NATIVE_VERSION
>     }
>     }
> 
> }
> ```

i was facing a lot of errors when a build the app and this command specifying the version of react resolve, thanks!

**Comment by juniordnts** [comment]
> add this in to /android/build.gradle
> 
> ```
> def REACT_NATIVE_VERSION = new File(['node', '--print',"JSON.parse(require('fs').readFileSync(require.resolve('react-native/package.json'), 'utf-8')).version"].execute(null, rootDir).text.trim())
> 
> allprojects {
> 
> //...
> 
> 
> configurations.all {
>     resolutionStrategy {
>         // Remove this override in 0.65+, as a proper fix is included in react-native itself.
>         force "com.facebook.react:react-native:" + REACT_NATIVE_VERSION
>     }
>     }
> 
> }
> ```

I tried this, and it worked for me... But now the OneSignal is not working properly. The library doesnt catch any error, but im not receiving any notification.
