### ISSUE TITLE
InjectJavaScript on Android(no one of existing issues could help)

### ISSUE THREAD

**Issue by Mr-LYY** [react-native-webview/react-native-webview#2569]
**Bug description:**
Hi, everyone! I'm trying to send data from RN to Web, it works fine on iOS, but does nothing for Android. I've spent 16 hours to read everything that is written here in issues and all over the internet and tried every variant, but Android doesn't want to work.

Reciving data from Web works also fine for both iOS and Android, trouble is only with sending to Web from Android. I tried IIFE, strings, JSON.stringify, all kinds of injects, postMessages, everything that I found. I'm done and look forward to your help!)

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**
My Web hook
![image](https://user-images.githubusercontent.com/75062125/175968567-3c12a901-c1bb-49b5-b9c3-ef45f8d0ac20.png)

My RN code(It's just final variant I've stopped on, i tried many of other ones)
![image](https://user-images.githubusercontent.com/75062125/175965006-ede6b994-1fcc-47b0-a095-0e9c14d24234.png)

My WebView Component
![image](https://user-images.githubusercontent.com/75062125/175965227-ace52984-4db0-456c-b983-c6832f1d348e.png)

**Environment:**
 - OS: Android
 - OS version: Android 12
 - react-native version: "0.68.2"
 - react-native-webview version: "11.22.3"

**Comment by TheAlmightyBob** [comment]
Small note:

> react-native-webview version: "0.17.7"

There was never such a version AFAIK. The current version is 11.22.4.

**Comment by Mr-LYY** [comment]
> Small note:
> 
> > react-native-webview version: "0.17.7"
> 
> There was never such a version AFAIK. The current version is 11.22.4.

Yep, thanks! I corrected the issue. My version actually is 11.22.3

**Comment by Mr-LYY** [comment]
> [TheAlmightyBob](/TheAlmightyBob)

@TheAlmightyBob any ideas? Maybe you have 100% working example of injecting JS? Which works both for iOS and Android

**Comment by Mr-LYY** [comment]
@TheAlmightyBob Thank you, sir! Im gonna try to use some previous versions next time, because for now, Ive already rewritten everything into Web code to avoid comunication between RN and WebView using JS

**Comment by Mr-LYY** [comment]
Hi, I solved my problem with in another way, not using JSinjections. But, I can see in comments that changing library version gonna help. So, yes, close this issue. Thank you
