### ISSUE TITLE
ios  load local photo not work.

### ISSUE THREAD

**Issue by chenweigh** [react-native-webview/react-native-webview#2570]
###  Environment
```
"react": "17.0.1",
"react-native": "0.64.3"
"react-native-webview": "^11.18.2"
```

### Code
```
const Web = props => {
  const {navigation} = props;
  //ios src
  var imgSrc = 'ph://EF3C7694-3020-467E-B91F-6949B79F84CB/L0/001';
  // var imgSrc = "file:///var/mobile/Containers/Data/Application/D39C545B-8A0E-48DD-930E-842C3A212698/Documents/IMG_0319.JPG"

  // android src
  // var imgSrc = 'file:///storage/emulated/0/DCIM/tb_image_share_1656165598962.jpg';

  var viewHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta name="viewport" content="user-scalable=1.0,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0">
            <style></style>
        </head>
        <body>
            <img src="${imgSrc}"  style="width:100px;height:100px; background-color:yellow;"/>
        </body>
    </html>`;

  return (
    <View style={{flex: 1}}>
      <Header
        style={{}}
        title={'测试Web'}
        onLeftPress={() => {
          navigation.goBack();
        }}
      />
      <WebView
        style={{flex: 1, backgroundColor: 'red'}}
        useWebKit={false}
        originWhitelist={['*']}
        dataDetectorTypes={'none'}
        domStorageEnabled={false}
        bounces={false}
        javaScriptEnabled={true}
        source={{html: viewHTML}}
        allowFileAccess={true}
      />
    </View>
  );
};

export default Web;
```

### Problem
> the image is success on android, but not work on ios.

How to fix it ? I need help.

**Comment by zedelashvililevani** [comment]
@chenweigh How did you fixed it?

**Comment by suwu150** [comment]
@chenweigh any update?

**Comment by chenweigh** [comment]
> @chenweigh any update?

```js
<WebView
     style={{flex: 1, height: 200, backgroundColor: 'red'}}
     originWhitelist={['*']}
     source={{uri: htmlPath}}
     //1. open switch
     allowFileAccess={true}
     //2. config Path, for example: DocumentDirectoryPath, CachesDirectoryPath，TemporaryDirectoryPath...
     allowingReadAccessToURL={RNFS.DocumentDirectoryPath}
 />
```
The above can be achieved.

**Comment by tokkozhin** [comment]
it works for ios simulator, but not for real device(

**Comment by web-iou** [comment]
> > @chenweigh any update?
> 
> ```js
> <WebView
>      style={{flex: 1, height: 200, backgroundColor: 'red'}}
>      originWhitelist={['*']}
>      source={{uri: htmlPath}}
>      //1. open switch
>      allowFileAccess={true}
>      //2. config Path, for example: DocumentDirectoryPath, CachesDirectoryPath，TemporaryDirectoryPath...
>      allowingReadAccessToURL={RNFS.DocumentDirectoryPath}
>  />
> ```
> 
> The above can be achieved.

what is your htmlPath?   if you write html string into fs. RNFS.DocumentDirectoryPath?

**Comment by chenweigh** [comment]
> > > @chenweigh any update?
> > 
> > 
> > ```js
> > <WebView
> >      style={{flex: 1, height: 200, backgroundColor: 'red'}}
> >      originWhitelist={['*']}
> >      source={{uri: htmlPath}}
> >      //1. open switch
> >      allowFileAccess={true}
> >      //2. config Path, for example: DocumentDirectoryPath, CachesDirectoryPath，TemporaryDirectoryPath...
> >      allowingReadAccessToURL={RNFS.DocumentDirectoryPath}
> >  />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The above can be achieved.
> 
> what is your htmlPath? if you write html string into fs. RNFS.DocumentDirectoryPath?

the htmlPath as : `file://${RNFS.DocumentDirectoryPath}/${hash}.html`
