### ISSUE TITLE
App creates temp file. Sensitive information should never be written into a temp file when scan Vulnerabilities

### ISSUE THREAD

**Issue by VoDucDuoc** [react-native-webview/react-native-webview#2573]
**Bug description:**
Client send me a report when scan check Vulnerabilities on apk file

report in RNCWebViewModule.java file

**Screenshots/Videos:**
![image](https://user-images.githubusercontent.com/66680244/176422436-61e04b20-946a-4bee-84d6-0e1d005f69e3.png)

**Environment:**
 - OS: Android
 - react-native version: 0.64.2
 - react-native-webview version: 11.6.5

There is any solution for this report

**Comment by ChathuZenith** [comment]
still searching for solutions

**Comment by dhkrishna1993** [comment]
Hi @ChathuZenith 

Hope your doing well.
The above issue is resolved or still it is going on ?

I am also facing same issue with react-native-webview 
If anyone found the solution please let us know how to resolve the above issue.

Thanks
