### ISSUE TITLE
duplicate symbol '_CUSTOM_SELECTOR'

### ISSUE THREAD

**Issue by andreialecu** [react-native-webview/react-native-webview#2574]
Ref: https://github.com/react-native-webview/react-native-webview/pull/2101

https://github.com/react-native-webview/react-native-webview/blob/a0f1e2641a733777e124e8396ee3b86ec4f3deb8/apple/RNCWebView.m#L26

The `react-native-selectable-text` library has an identical one:

https://github.com/Astrocoders/react-native-selectable-text/blob/master/ios/RNSelectableTextView.m#L28

This results in:
```
duplicate symbol '_CUSTOM_SELECTOR' in:
    .../react-native-selectable-text/libreact-native-selectable-text.a(RNSelectableTextView.o)
    .../react-native-webview/libreact-native-webview.a(RNCWebView.o)
ld: 1 duplicate symbol for architecture arm64
```

_Originally posted by @andreialecu in https://github.com/react-native-webview/react-native-webview/issues/2101#issuecomment-1169848352_

**Comment by seanerge** [comment]
same issue

**Comment by ntcong91** [comment]
+1

**Comment by TarasBurdeniuk** [comment]
+1

**Comment by congnguyenblog** [comment]
+1 waiting

**Comment by luco** [comment]
+1 here
