### ISSUE TITLE
Throwing an exception by void WinRTHttpResource::ClearCookies()

### ISSUE THREAD

**Issue by gangli66** [react-native-webview/react-native-webview#2581]
When I debug my app with react-native-windows, there is an abort message that throwed an exception by void WinRTHttpResource::ClearCookies() because its body of the function ClearCookies() is like this:

void WinRTHttpResource::ClearCookies() noexcept /*override*/ {
  assert(false);
  // NOT IMPLEMENTED
}

however, after I touch "continue", the home page of my app appeared.
But when I open the page including webview, it throws an another exception by __GSHandlerCheck_EH4. The break happens
at the point below:

    GSUnwindInfo = *(PULONG)GSHandlerData;
    if (IS_DISPATCHING(ExceptionRecord->ExceptionFlags)
        ? (GSUnwindInfo & UNW_FLAG_EHANDLER)
        : (GSUnwindInfo & UNW_FLAG_UHANDLER))
    {
        Disposition = __CxxFrameHandler4(    <----------------------------Here is the abort point
            ExceptionRecord,
            EstablisherFrame,
            ContextRecord,
            DispatcherContext
        );
    }
    else
    {
        Disposition = ExceptionContinueSearch;
    }

**Environment:**
 - OS: Win11
 - OS version: 21H2 22000.739
 - react-native version: 0.68.2
 - react-native-webview version: 11.21.1

**Comment by gangli66** [comment]
I hava fixed this issue by modifying the version of the react-native. When I used 0.67 and it ran normally.

**Comment by asklar** [comment]
@gangli66 since this is not an issue with the WebView component, but with HTTP support in React Native itself, could you please file this issue in the [react-native-windows repo](https://github.com/microsoft/react-native-windows/)? CC @JunielKatarn  FYI

**Comment by JunielKatarn** [comment]
I'll follow up in the eventual react-native-windows issue.
My first intuition is that we should emit a JavaScript error (red box) indicating those methods are unimplemented, instead of asserting.
