### ISSUE TITLE
requestFocus does not work

### ISSUE THREAD

**Issue by linxianxi** [react-native-webview/react-native-webview#2582]
I used 11.22.4

**Comment by tom-at-pixel** [comment]
+1. Occasionally works, but most of the time not. Tried different versions and same thing everywhere.

**Comment by tom-at-pixel** [comment]
I think I figured out how to make it work consistently. You need to set the prop`keyboardDisplayRequiresUserAction={false}` which allow the WebView to steal focus and activate the keyboard without the user having to explicitly press on it.
