### ISSUE TITLE
When native postMessage to web, method of iOS and android is unmatched

### ISSUE THREAD

**Issue by zerosrat** [react-native-webview/react-native-webview#2586]
**Bug description:**

When calling `webView.postMessage()`, the dispatchEvent method of iOS and android is differnt as below.
android: `document.dispatchEvent(event)`

https://github.com/react-native-webview/react-native-webview/blob/6b8e4f3f5f3cc006ebca8cb3c7ab692805824685/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java#L758

iOS: `window.dispatchEvent(event)`

https://github.com/react-native-webview/react-native-webview/blob/a68df8526527a8fa5a21f62eea1d60e956a833db/apple/RNCWebView.m#L909

As a result, developer need to addEventListener on both of `document` and `window` target which is redundant
```
docuemt.addEventListener('message', cb)
window.addEventListener('window', cb)
```

So, is it right to modify android file to change document into window?

**Comment by tkmin** [comment]
https://github.com/react-native-webview/react-native-webview/issues/356#issuecomment-1290912572
