### ISSUE TITLE
Call of injected JS function doesn't work on android

### ISSUE THREAD

**Issue by EJohnF** [react-native-webview/react-native-webview#2587]
**Bug description:**

In app we are using Webview to access `mapkit`. As a result we need to call a JS function inside webview many times. 
Before we were injecting full-function code together with its call. 

E.g. this was before

```
export const getBoundsScript = (query: string) => `
function getBounds() {
  mapkit.init({
    language: "en",
    authorizationCallback: function(done) {
      log("Authentication succeeded");
      done("${Config.APPLE_MAP_TOKEN}");
    },
  });
  search = new mapkit.Search({
    language: "en",
    includeQueries: false,
    includePointsOfInterest: false,
    getsUserLocation: true,
  });
  search.search("${query}", function (error, data) {
    if(data){const boundingRegion = data.places.map((place) => ({region: place.region.toBoundingRegion()})); window.ReactNativeWebView.postMessage(JSON.stringify(boundingRegion[0]));}
  });
}
getBounds();
true;
`;
```
and `webview.current?.injectJavaScript(getBoundsScript(boundsQuery));` to call it.

Now I changed it to (injected on start):
```
function getBounds(query) {
  mapkit.init({
    language: "en",
    authorizationCallback: function(done) {
      log("Authentication succeeded");
      done("${Config.APPLE_MAP_TOKEN}");
    },
  });
  search = new mapkit.Search({
    language: "en",
    includeQueries: false,
    includePointsOfInterest: false,
    getsUserLocation: true,
  });
  search.search(query, function (error, data) {
    if(data){const boundingRegion = data.places.map((place) => ({region: place.region.toBoundingRegion()})); document.ReactNativeWebView.postMessage(JSON.stringify(boundingRegion[0]));}
  });
}
```

And call it: `webview.current?.injectJavaScript('getBounds("${boundsQuery}"); true');`

So that function code is always injected, and only call is being injected for every request. 

Here is WebView component:
```
<WebView
        ref={webview}
        style={styles.container}
        androidHardwareAccelerationDisabled
        javaScriptEnabled={true}
        domStorageEnabled={true}
        androidLayerType={'hardware'}
        mixedContentMode="always"
        source={source}
        injectedJavaScript={initializeScript(debug)}
        onMessage={onMessage}
      />
```

This new approach works well on iOS. But not on android. I tried to debug, and it seems to me that injected JS function `getBounds` is not being called at all. 

No errors are being sent by `onError` callback. 

Maybe someone can advice about either this optimisation even make sense? 

**Expected behavior:**
The same behavior on android and ios

**Environment:**
 - OS: Android
 - OS version: 10, API 29
 - react-native version: 0.68
 - react-native-webview version: 11.17.1 (and tried 11.22.4)

**Comment by adamivancza** [comment]
still an issue

**Comment by McFlyssss** [comment]
Same here. inject is working fine on iOS but not on Android

**Comment by paul-orchid** [comment]
The issue was solved for me here: https://github.com/react-native-webview/react-native-webview/issues/554#issuecomment-541611367

I.e. change 
`injectedJavaScript={initializeScript(debug)}`

to this:
`onLoad={() => { webview.current?.injectJavaScript(initializeScript(debug));}}`

**Comment by shineon9** [comment]
> The issue was solved for me here: [#554 (comment)](https://github.com/react-native-webview/react-native-webview/issues/554#issuecomment-541611367)
> 
> I.e. change `injectedJavaScript={initializeScript(debug)}`
> 
> to this: `onLoad={() => { webview.current?.injectJavaScript(initializeScript(debug));}}`

I have the same problem, injectJavascript() is not working on android, also with latest version 11.26.0.
The fix proposed by @paul-orchid is not working for me, beause I have to call a javascript function at runtime, and not at the load of the page.

**Comment by h-assefi** [comment]
any progress ? 
I have the same problem

**Comment by ElongeR-12** [comment]
Still have the same issue? InjectedJavaScript works fine on local and with builded APK but nothing when I build app bundle for Google play store. The app is published in Google play store with InjectedJavaScript not running

**Comment by JunDev76** [comment]
It was solved by deleting the existing react-native-webview version and reinstalling it with 13.3.0 version :)

**Comment by VitorHRD** [comment]
For me the solution was simple, just pass your javascript content into the injectedJavaScriptBeforeContentLoaded property
My WebView :

<WebView
         startInLoadingState={true}
         renderLoading={() => (
           <Loader
             containerStyles={{
               justifyContent: "flex-start",
               paddingTop: RFValue(40),
             }}
           />
         )}
         source={{ uri: url }}
         style={{ width: WIDTH, height: HEIGHT }}
         injectedJavaScript={injectJS}
         javaScriptEnabled={true}
         mixedContentMode={"compatibility"}
         originWhitelist={["*"]}
         injectedJavaScriptBeforeContentLoaded={injectJS}
      />
