### ISSUE TITLE
How to load local html css, js file in the webview on IOS

### ISSUE THREAD

**Issue by thanhnvpk01168** [react-native-webview/react-native-webview#2589]
It's not working.
Can you help me, thanks advance

<img width="448" alt="Screen Shot 2022-07-06 at 6 02 25 PM" src="https://user-images.githubusercontent.com/58645779/177536083-c094cb2d-4114-4152-8d6e-84c551679d1f.png">
<img width="207" alt="Screen Shot 2022-07-06 at 6 03 29 PM" src="https://user-images.githubusercontent.com/58645779/177536254-42e896a6-43c2-43bb-89e9-01f810f10bb0.png">

<img width="504" alt="Screen Shot 2022-07-06 at 6 05 02 PM" src="https://user-images.githubusercontent.com/58645779/177536479-a34b458b-26b6-4d8e-8dda-812ab8e9facc.png">

**Comment by fukemy** [comment]
hi, did u found any solution? I have same issues
https://stackoverflow.com/questions/73976707/react-native-file-cannot-be-loaded-as-its-extension-is-not-registered-in-assetex

**Comment by fukemy** [comment]
https://stackoverflow.com/a/76170855/2527109
