### ISSUE TITLE
Unable to create layer for RNCWebViewManager$RNCWebView in api level 21,23,26 and 29 versions of android

### ISSUE THREAD

**Issue by keerthipativinaykumar** [react-native-webview/react-native-webview#2596]
recatnative webview working fne in highr versions of sndroid devices but when it comes to lower version of android devices some of the devices are getting crashes with app when using react native webview

**Bug description:**

when declaring dynamic webview height its getting crash on android devices 

procedure for reproduce on only some android devices like samsung and huwai mobiles majorly

call the webview with a web page inject javascript to that page using react native webview and then set height with useState from onmessage with parsingint the values from message then assigning webview height with a wrapping on view on top of webview and setting height for view which increases webview height dynamically after successful load

 Fatal exception
java.lang.IllegalStateException: Unable to create layer for RNCWebViewManager$RNCWebView
     FATAL EXCEPTION: main
Process: com.vinaykumarkeerthipati, PID: 1056
java.lang.IllegalStateException: Unable to create layer for RNCWebViewManager$RNCWebView
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:143)
	at android.os.Looper.loop(Looper.java:122)
	at android.app.ActivityThread.main(ActivityThread.java:5538)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Expected behavior:**

I want to clear the issue in api level 26 and 29 devices in andorid

**Environment:**
 - OS: android
 - OS version: API Level 26 and 29 versions
 - react-native version: 0.68.2
 - react-native-webview version: 11.22.0

**Comment by fdobre** [comment]
I am having the same error in Android API level 26

**Comment by fdobre** [comment]
In my case crash seems to be related to any Youtube, Instagram, Facebook, Twitter embed and it can be replicated only in Android 8 Samsung devices. I cannot replicate the issue in the emulator.

**Comment by fdobre** [comment]
`07-12 13:18:36.928 E/AndroidRuntime(21764): FATAL EXCEPTION: main
07-12 13:18:36.928 E/AndroidRuntime(21764): FATAL EXCEPTION: main
07-12 13:18:36.928 E/AndroidRuntime(21764): Process: fr.airweb.psg.dev, PID: 21764
07-12 13:18:36.928 E/AndroidRuntime(21764): java.lang.IllegalStateException: Unable to create layer for RNCWebViewManager$RNCWebView, size 1080x9661 exceeds max size 8192
07-12 13:18:36.928 E/AndroidRuntime(21764): 	at android.os.MessageQueue.nativePollOnce(Native Method)
07-12 13:18:36.928 E/AndroidRuntime(21764): 	at android.os.MessageQueue.next(MessageQueue.java:325)
07-12 13:18:36.928 E/AndroidRuntime(21764): 	at android.os.Looper.loop(Looper.java:142)
07-12 13:18:36.928 E/AndroidRuntime(21764): 	at android.app.ActivityThread.main(ActivityThread.java:6938)
07-12 13:18:36.928 E/AndroidRuntime(21764): 	at java.lang.reflect.Method.invoke(Native Method)
07-12 13:18:36.928 E/AndroidRuntime(21764): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
07-12 13:18:36.928 E/AndroidRuntime(21764): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
07-12 13:18:36.928 E/AndroidRuntime(21764): FATAL EXCEPTION: main
07-12 13:18:36.928 E/AndroidRuntime(21764): FATAL EXCEPTION: main
07-12 13:18:36.928 E/AndroidRuntime(21764): Process: fr.airweb.psg.dev, PID: 21764
07-12 13:18:36.928 E/AndroidRuntime(21764): java.lang.IllegalStateException: Unable to create layer for RNCWebViewManager$RNCWebView, size 1080x9661 exceeds max size 8192
07-12 13:18:36.928 E/AndroidRuntime(21764): 	at android.os.MessageQueue.nativePollOnce(Native Method)
07-12 13:18:36.928 E/AndroidRuntime(21764): 	at android.os.MessageQueue.next(MessageQueue.java:325)
07-12 13:18:36.928 E/AndroidRuntime(21764): 	at android.os.Looper.loop(Looper.java:142)
07-12 13:18:36.928 E/AndroidRuntime(21764): 	at android.app.ActivityThread.main(ActivityThread.java:6938)
07-12 13:18:36.928 E/AndroidRuntime(21764): 	at java.lang.reflect.Method.invoke(Native Method)
07-12 13:18:36.928 E/AndroidRuntime(21764): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
07-12 13:18:36.928 E/AndroidRuntime(21764): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
07-12 13:18:36.928 E/AndroidRuntime(21764): FATAL EXCEPTION: main
07-12 13:18:36.928 E/AndroidRuntime(21764): FATAL EXCEPTION: main
07-12 13:18:36.928 E/AndroidRuntime(21764): Process: fr.airweb.psg.dev, PID: 21764
07-12 13:18:36.928 E/AndroidRuntime(21764): java.lang.IllegalStateException: Unable to create layer for RNCWebViewManager$RNCWebView, size 1080x9661 exceeds max size 8192
07-12 13:18:36.928 E/AndroidRuntime(21764): 	at android.os.MessageQueue.nativePollOnce(Native Method)
07-12 13:18:36.928 E/AndroidRuntime(21764): 	at android.os.MessageQueue.next(MessageQueue.java:325)
07-12 13:18:36.928 E/AndroidRuntime(21764): 	at android.os.Looper.loop(Looper.java:142)
07-12 13:18:36.928 E/AndroidRuntime(21764): 	at android.app.ActivityThread.main(ActivityThread.java:6938)
07-12 13:18:36.928 E/AndroidRuntime(21764): 	at java.lang.reflect.Method.invoke(Native Method)
07-12 13:18:36.928 E/AndroidRuntime(21764): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
07-12 13:18:36.928 E/AndroidRuntime(21764): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
07-12 13:18:36.928 E/AndroidRuntime(21764): Process: fr.airweb.psg.dev, PID: 21764
07-12 13:18:36.928 E/AndroidRuntime(21764): java.lang.IllegalStateException: Unable to create layer for RNCWebViewManager$RNCWebView, size 1080x9661 exceeds max size 8192
07-12 13:18:36.928 E/AndroidRuntime(21764): 	at android.os.MessageQueue.nativePollOnce(Native Method)
07-12 13:18:36.928 E/AndroidRuntime(21764): 	at android.os.MessageQueue.next(MessageQueue.java:325)
07-12 13:18:36.928 E/AndroidRuntime(21764): 	at android.os.Looper.loop(Looper.java:142)
07-12 13:18:36.928 E/AndroidRuntime(21764): 	at android.app.ActivityThread.main(ActivityThread.java:6938)
07-12 13:18:36.928 E/AndroidRuntime(21764): 	at java.lang.reflect.Method.invoke(Native Method)
07-12 13:18:36.928 E/AndroidRuntime(21764): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
07-12 13:18:36.928 E/AndroidRuntime(21764): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`

**Comment by fdobre** [comment]
I found that the crash shows for Android 8 Samsung and Huawei only for big height webviews included in scroll views when `androidLayerType` is `hardware` no matter what the content is.
Limitting the webview height to 2720 fixed the crash. The error was `Unable to create layer for RNCWebViewManager$f, size 1080x9661 exceeds max size 8192` I noticed 2720 x 3 = 8190<8192. Any height bigger than 2720 crashed.

**Comment by keerthipativinaykumar** [comment]
> Setting the `androidLayerType` to `software` seems to fix the crash but then I have only blank content in the webview.

thanks for reply but it won't resolve the issue until mobile webview is capable of creating layer as software accelration, it was not working in conditions of android versions

**Comment by niloufarMakhzani** [comment]
any update?
All the solutions I found is limitedet to specific versions of android, I need a solution for SDKVersion 21 and above

**Comment by keerthipativinaykumar** [comment]
I got this error because of reading web view height dynamically using injected javascript and through on message we place the height given by web view to view that is wrapped upon web view in react native so I have modified by moving out for reading height of web view through injecting javascript and using freefloat for web view without given fixed height to the web view but giving fixed height to views upon webview and not giving fixed to web view solved my issue

**Comment by cauyyl** [comment]
Api level 30 also faces this issue.
