### ISSUE TITLE
goBack() not working on pop up pages iOS

### ISSUE THREAD

**Issue by colemvi-Jhancock** [react-native-webview/react-native-webview#2600]
**Bug description:**

While canGoBack is returning as true, goBack() does not go to the previous page on iOS when navigating to a page that would traditionally "pop up" in a browser.

**To Reproduce:**

Go to page that would pop up in a browser and attempt to execute the goBack() function

**Expected behavior:**

Either the canGoBack state would return false, or the goBack function would work as expected.

**Screenshots/Videos:**

**Environment:**
 - OS: iOS
 - OS version: 15.5
 - react-native version: 68.1
 - react-native-webview version: 11.22.7

**Comment by shindenitish** [comment]
facing the same issue
