### ISSUE TITLE
WebView cookies are empty after being sent through custom header

### ISSUE THREAD

**Issue by PaulFlatlooker** [react-native-webview/react-native-webview#2605]
**Bug description:**

I am using [expo](https://docs.expo.dev/get-started/installation/).

After sending a custom cookie through the WebView as described in the [guide](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Guide.md#managing-cookies), the webview's cookies are empty when sent to the React Native code.

**To Reproduce:**

```
npx create-expo-app react-native-webview-custom-header
cd react-native-webview-custom-header
yarn add react-native-webview
``` 

Then replace code in `App.js` with this code:
```
import React from 'react';
import { Button, SafeAreaView } from 'react-native';
import { WebView } from 'react-native-webview';

const POST_COOKIES = `
window.ReactNativeWebView.postMessage(document.cookie);
true;
`

function App() {
  let webview = null;

  const onMessage = async (event) => {
    const { data } = event.nativeEvent;
    console.log('data: ', data)
  }

  const postCookies = () => {
    if(webview){
      webview.injectJavaScript(POST_COOKIES);
    } else {
      console.log('no webview')
    }
  }

  return (
    <SafeAreaView style={{ flex: 1 }}>
      <WebView
        ref={(ref) => (webview = ref)}
        source={{ uri: 'http://example.com/',
          headers: {
            Cookie: 'cookie1=asdf;cookie2=dfasdfdas',
          },
        }}
        originWhitelist={['*']}
        onMessage={onMessage}
        sharedCookiesEnabled={true}
        thirdPartyCookiesEnabled={true}
        javascriptEnabled={true}
      />
      <Button
        title="post cookies"
        onPress={() => postCookies()}/>
    </SafeAreaView>
  );
}

export default App;
```

Then
 ```
yarn ios
```

Once the emulator is loaded, click on "post cookies" button.

**Expected behavior:**

The server logs show: `data: cookie1=asdf;cookie2=dfasdfdas`

**Observed behavior:**

The server logs show that the cookies are empty: `data:`

**Screenshots/Videos:**

![Screenshot 2022-07-18 at 17 54 38](https://user-images.githubusercontent.com/51907486/179553399-cce3fc0d-8df6-436a-be20-3115c01f01d7.png)

**Environment:**
 - OS: macOS
 - OS version: 12.0.1
 - react-native version: 0.68.2
 - react-native-webview version: 11.22.7

**Comment by PaulFlatlooker** [comment]
I observe the same problem when running the app from a react-native project (without expo) with Simulator, on iPhone 13 (iOs 15.5)

**Comment by KawaljeetSBagga** [comment]
I am facing issues when sending headers while making a POST request. My webpage is not authenticated and I receive a warning in the logs saying `WebView: source.headers is not supported when using POST. `

Any solutions here?
@PaulFlatlooker

**Comment by MattiL** [comment]
> I am facing issues when sending headers while making a POST request. My webpage is not authenticated and I receive a warning in the logs saying `WebView: source.headers is not supported when using POST. `
> 
> Any solutions here?

You can first fetch the webpage outside WebView and then pass the content to WebView via source.html.

**Comment by tfreitas90** [comment]
When I add more than one cookie, only the first appears in the webview cookies (using safari and iOS simulator). Is this normal? 
```
 headers: {
            Cookie: 'cookie1=asdf;cookie2=dfasdfdas',
          },
```

I can add a lot more using this: 
```
webViewRef?.current?.injectJavaScript(`
    (function() {
        document.cookie = "cookie1=C;"
        document.cookie = "cookie2=B"
        document.cookie = "cookie3=A"
    })();true;
  `);
```

**Comment by tfreitas90** [comment]
> When I add more than one cookie, only the first appears in the webview cookies (using safari and iOS simulator). Is this normal?
> 

Recently I found out that, using the latest lib version, it's possible to have the cookies on the header by doing the following (only iOS):
```
          source={{
            uri: currentURL,
            headers: {
              cookie:
                'cookie1 = value1; Expires=Wed, 13 Mar 2024 17:16:14 GMT;, cookie2 = utl;, cookie3 = aaaa',
            },
          }}
          sharedCookiesEnabled
```
So, I guess the documentation may be wrong? Also, for android does not work, but i still need to investigate more...

**Comment by aplyd** [comment]
@tfreitas90 did you ever find an android solution for this?
