### ISSUE TITLE
opening safari on iOS while using react-native 0.69.1

### ISSUE THREAD

**Issue by loupmasneri** [react-native-webview/react-native-webview#2607]
Hello!
I have upgraded my project to

- *React 18.2.0*
- *react-native 0.69.1*
- *react-native-webview ^11.22.7*

But react-native-webview open the uri directly on safari while on android it open correctly a webpage inside the application.

Does anyone face the same issue ?

Thank you for your help.

**Comment by matinzd** [comment]
This is so weird. Can you send some example application that we can try?

**Comment by loupmasneri** [comment]
I just created a react-native app with typescript template and try to add react-native-webview and while launching on iOS this is what happened

**Comment by JavierMontano-ab-inbev** [comment]
i have the same issue

**Comment by astriskit** [comment]
If somebody comes here, having similar issue, I had given a template-string'ed (`${someVar}*`) in the `originWhiteList`. And removing the prop altogether got jumping from app to safari resolved.
