### ISSUE TITLE
`window.history` does not work when using `source={html, baseUrl}` on iOS

### ISSUE THREAD

**Issue by Ldoppea** [react-native-webview/react-native-webview#2608]
**Bug description:**
Hi,

I'm not sure if this is a `react-native-webview` bug or if it is related to native `WKWebview` component.

When I use `source={html, baseUrl}` in the WebView, then on iOS the history is not working anymore.

If I do a `window.history.push`, the navigation occurs, but then `window.history.back()` will not do anything.

The same code using `source={uri}` would work.

I made some research on internet and it seems like this happens when `WKWebview.loadHTMLString()` is called.
I found some solutions for the old `UIWebview` component but I found none for the new `WKWebview`. Some people mention `WKBackForwardListItem` as something to investigate but this seems to be a dead-end (however I'm not a native iOS developper so maybe I'm wrong)

On Android this works fine

Is that a bug? Or an expected behaviour? Are there any solutions for doing what I want? Any fix I can try to implement?

Thanks

**To Reproduce:**

Repository to reproduce the bug: https://github.com/Ldoppea/rn-webview-history-bug

The code is in `App.js` and creates a WebView using `localSource = { html, baseUrl }`:
- Run the app is iOS
- Inspect the WebView from Safari
- `window.location` returns `https://www.swansontec.com/temp/history/a.html` and `window.history.length` returns `1`
- Click on `push a#n`
- `window.location` returns `https://www.swansontec.com/temp/history/a.html#1` and `window.history.length` returns `1`
- Click on `back`
- `window.location` returns `https://www.swansontec.com/temp/history/a.html#1` and `window.history.length` returns `1`

**Expected behavior:**
- Run the app is iOS
- Inspect the WebView from Safari
- `window.location` returns `https://www.swansontec.com/temp/history/a.html` and `window.history.length` returns `1`
- Click on `push a#n`
- `window.location` returns `https://www.swansontec.com/temp/history/a.html#1` and `window.history.length` returns `2`
- Click on `back`
- `window.location` returns `https://www.swansontec.com/temp/history/a.html` and `window.history.length` returns `2`

Note that if you replace `<WebView source={localSource} />` by `<WebView source={realSource} />` (using `realSource = { url: 'some_uri' }`), then the expected behaviour is observed

**Environment:**
 - OS: iOS
 - OS version: 15.5 (and also 14.5)
 - react-native version: 0.69.2 (and also 0.66.4)
 - react-native-webview version: 11.18.2

**Comment by iegik** [comment]
try use `source={{ html, baseUrl }}` instead of `source={html, baseUrl} `
