### ISSUE TITLE
How to run React JS build in React-Native Webview?

### ISSUE THREAD

**Issue by bachlongkocanh** [react-native-webview/react-native-webview#2616]
I created complete offline ReactJS web application and I want to run it from android application from Web View using React-Native.

I followed the following procedure to do so:
1. I created a compiled ReactJS web application got the build using the following command:
```
npm run build
```
2. Then I created react-native project and placed the `build` folder with following architecture
![image](https://user-images.githubusercontent.com/28125294/181670850-a3bc5706-f1f1-47d0-a24b-54f8acb50dbf.png)
3. I updated App.js with the following content:
```
import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View, WebView} from 'react-native';
import {roscon} from "./build/index.html";

type Props = {};
export default class App extends Component<Props> {
  render() {
    return (
      <View style={{height: 300, width: 300,overflow:'hidden' }}>
          <WebView
            source={{uri: roscon}}
            scalesPageToFit={true}
            domStorageEnabled={true}
            javaScriptEnabled={true}
            startInLoadingState={true}
          />
      </View>
    );
  }
}
```
After running this code I expected it to run my ReactJS Web application, instead I got white screen.

Can you please tell what can be the causing issues and how i can make my ReactJS Web App run on react-native?

Note: I was able to run generated `build` folder using npm command:
```
serve -s build
```
But I still can't figure out how to port it to react-native project as WebView

**Comment by damian165-cpu** [comment]
Have you found a solution?

**Comment by bachlongkocanh** [comment]
Hi. @damian165-cpu, you can open a web server in React Native by https://github.com/bachlongkocanh/saaf-rn-web-server.
