### ISSUE TITLE
Text is cut off on Samsung Galaxy A71 device

### ISSUE THREAD

**Issue by brettins** [react-native-webview/react-native-webview#2618]
**Bug description:**
Text added to the webview takes on the correct height except on a Samsung Galaxy A71 device, where the height be too small and some text will be cut off.

Changing the system font size larger or smaller does not fix the issue.  

Text looks fine on all other devices, this seems to be an interaction with Samsung's "One UI" setup.

**To Reproduce:**
1. Create a project with a webview and some text
2. Open the project on a Samsung Galaxy A71 device
3. Observe that the text is cut off.

**Expected behavior:**
That all of the contents of the webview are shown to the user.

**Environment:**
 - OS: Android
 - OS version: One UI - 4.1, Android 12
 - react-native version:  0.67.3
 - react-native-webview version:11.17.2

**Comment by brettins** [comment]
This is still an issue.

**Comment by Mihai-github** [comment]
+1

**Comment by tonynereus** [comment]
Facing same issue the on my Samsung A 71 the ending of some texts keeps getting chiped out
