### ISSUE TITLE
Android favicon request intercept 

### ISSUE THREAD

**Issue by manosKas** [react-native-webview/react-native-webview#2621]
**Is your feature request related to a problem? If so, Please describe.**
only on Android, every webview request (for a uniquely generated html file on my server) was sending an extra redundant GET request for the favicon (/favicon.ico) which was resolving with 404 from the server. For many reasons it wasn't possible to solve this from server side, so i needed to handle it from the client and I couldn't find anything on this library's API to prevent this request or inject with javascript by link a small image as the favicon before the request.

**Describe the solutions you came up with**
Adding the following _(in class RNCWebViewClient at react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java:903)_

`@Override
public WebResourceResponse shouldInterceptRequest(WebView view, WebResourceRequest request) {
  if(!request.isForMainFrame() && request.getUrl().getPath().endsWith("/favicon.ico")) {
          try {
                return new WebResourceResponse("image/png", null, null);
            } catch (Exception e) {
                e.printStackTrace();
            }
     }
     return null;
}`

**Additional context**
This could be done as is. Fixed and only to intercept specifically the favicon request, or it can be added as an extra prop of the webview to provide a multipurpose configuration for whatever request you need to intercept.

**Comment by zowebs** [comment]
Hello, did you come up with a solution for this issue?
