### ISSUE TITLE
How to delete webview cache only on iOS?

### ISSUE THREAD

**Issue by gangli66** [react-native-webview/react-native-webview#2625]
**Bug description:**

 Property incognito={true} will clear cache and local storage on iOS, but I want to remain local storage and clear cache only, 
just as it does on Android.

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS: iOS
 - OS version: 15.5
 - react-native version: 0.68
 - react-native-webview version: 11.21.1

**Comment by mdeliadi** [comment]
Any news on this, please? I've the same issue. Thanks!

**Comment by OneHatRepo** [comment]
same issue

**Comment by yangxyo** [comment]
+1

**Comment by rf1804** [comment]
For iOS https://www.npmjs.com/package/react-native-webview-ios-cache-clear
For android https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#clearCachebool

@gangli66 @harishsn @mdeliadi @jfisher37 @OneHatRepo @yangxyo @sallesma
