### ISSUE TITLE
failed to apply kotlin-android plugin and compileSdkVersion is not specified

### ISSUE THREAD

**Issue by Whitelistedd** [react-native-webview/react-native-webview#2628]
**Bug description:**

sorry am new to creating apps with react native so i might sound dumb but
am not exactly sure why but the error/bug is happening is when i try to run npm run android
**To Reproduce:**

**Expected behavior:**

i expect it to successfully go through the build process of the android app
**Screenshots/Videos:**

![image](https://user-images.githubusercontent.com/100237232/183646253-06f36b5d-fefa-445c-beb9-f73f3302dc57.png)

**Environment:**
 - OS: Android
 - OS version: 11
 - react-native version: 0.67.2
 - react-native-webview version: 11.23.0

**Comment by rendrixa** [comment]
same issue

**Comment by CarlaPaiva** [comment]
Same issue here. Any workaround available?

**Comment by ownsupernoob2** [comment]
still searching for solutions

**Comment by amdrade** [comment]
same issue
