### ISSUE TITLE
(Android) basicAuthCredential has no effect

### ISSUE THREAD

**Issue by yannickpschroeder** [react-native-webview/react-native-webview#2630]
I tried to send credentials via `basicAuthCredential` property.  There are no cookies or Authorization headers set on outgoing requests. This was only tested on Android.

**To Reproduce:**
I used [webhook](https://webhook.site) to track incoming requests. I copied the url and entered it as source to my webview.
```
<WebView
    source={{uri: `https://webhook.site/UR_HASH`}}
    basicAuthCredential={{
        username: 'test',
        password: '12345'
    }}     
/>
```

**Expected behavior:**
I expected to see a Authorization header. Same like when i use cURL `curl 'https://test:12345@webhook.site/UR_HASH'` : [Screenshot](https://ibb.co/7J3M7z2)

**Screenshots/Videos:**
[Screenshot](https://ibb.co/RjWTC7y)

**Environment:**
 - OS: Android emulator
 - OS version: 11
 - react-native version: "0.68.2"
 - react-native-webview version: "11.22.3"

**Comment by iwashi1t** [comment]
@yannickpschroeder  Try again with a server configured for Basic Authentication instead of webhook.site, the authentication logic will not be executed unless a 401 is returned.
