### ISSUE TITLE
Function onLoadEnd was not work on IOS

### ISSUE THREAD

**Issue by Mr-Rith** [react-native-webview/react-native-webview#2632]
<WebView
              style={styles.WebView}
              source={{uri: url}}
              originWhitelist={['*']}
              showsVerticalScrollIndicator={false}
              injectedJavaScript={injectedJavaScript}
              onLoadEnd={() => setLoadContent(false)}
            />

**Comment by tero-paananen** [comment]
Maybe it fails into `onError` ?

**Comment by tero-paananen** [comment]
Try `originWhitelist={['http://', 'https://']}`

**Comment by CMLCNL** [comment]
System:
    OS: macOS 12.6
    CPU: (10) x64 Apple M1 Pro
    Memory: 22.35 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.17.4 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.14 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
    
    
    same issue
