### ISSUE TITLE
File picker doesn't work on macOS

### ISSUE THREAD

**Issue by Ava7788** [react-native-webview/react-native-webview#2633]
**Bug description:**
I am using react-native-macos to build a react native macOS app. It is an all-webview app that RN is just a wrapper to render pages on the app.
There is an upload documents function on the website that expects to open the mac file finder(system folder) and allow the user to choose one file to upload. However, no action after clicking the button. Users can only drag or drop files to there
This function works on the website and ios platform. 

**Expected behavior:**

After clicking the button, expect to popup the mac file finder and allow users to select a file to upload.

**Screenshots/Videos:**

<img width="511" alt="Screen Shot 2022-08-11 at 3 57 42 pm" src="https://user-images.githubusercontent.com/110361291/184072607-885b2f19-ff6e-4551-a6c5-2e2611dbaa4f.png">

**Environment:**
 - OS:macOS
 - OS version:12.5
 - react-native version:"0.69.1"
 -  react-native-macos version:"^0.66.0-0"
 - react-native-webview version:"^11.22.7"

**Comment by banwarCoeus** [comment]
@Ava7788 Were you able to find a solution for it? I am facing this same issue.

**Comment by Ava7788** [comment]
> @Ava7788 Were you able to find a solution for it? I am facing this same issue.

No, I don't find any solution about it...

**Comment by ninohoglund** [comment]
This worked for me:
https://bitcoden.com/answers/how-do-i-get-the-file-open-dialog-to-work-when-called-through-a-swiftui-wkwebview-inside-a-macos-native-app

**Comment by amilich** [comment]
@ninohoglund can you explain how you implemented the solution above?

**Comment by amilich** [comment]
Resolved!
