### ISSUE TITLE
WebView2 and Edge DevTools debugging

### ISSUE THREAD

**Issue by tero-paananen** [react-native-webview/react-native-webview#2634]
After enabling `WebView2`  for example into https://github.com/react-native-webview/react-native-webview/blob/37c8d34df602d8c693ad261ac99b87b5cd2d4b57/example/examples/NativeWebpage.tsx#L16

WebView component does not exists anymore in Edge DevTools app.

```
<View style={{ height: 400 }}>
        <WebView
          useWebView2
          source={{ uri: 'https://infinite.red' }}
          style={{ width: '100%', height: '100%' }}
        />
      </View>
```

**Environment:**
I am running example from master (11.23.0). 
react: 17.0.2 => 17.0.2
react-native: 0.68.2 => 0.68.2
react-native-windows: 0.68.4 => 0.68.4

**Comment by tero-paananen** [comment]
I managed to enable debugging with this helper function

```
winrt::fire_and_forget ReactWebView2::EnableDebug() {
        co_await m_webView.EnsureCoreWebView2Async();
        m_webView.CoreWebView2().OpenDevToolsWindow();
    }
```

which i choose to call from `ReactWebView2::OnCoreWebView2Initialized`

**Comment by tero-paananen** [comment]
How you are managed to debug WebView2?
What would be final good solution?

**Comment by asklar** [comment]
I redirected Tero to https://github.com/MicrosoftEdge/WebView2Feedback where the webview2 experts live and can advise, as this repo just uses the control.

**Comment by tero-paananen** [comment]
> I redirected Tero to https://github.com/MicrosoftEdge/WebView2Feedback where the webview2 experts live and can advise, as this repo just uses the control.

Maybe i want only know how you debug WebView2 on your app development. I think that i do not give any feedback as basic feature like debugging WebView2 i hope that it will get better.

**Comment by tero-paananen** [comment]
This is best solution what i have found so far and seems to work somehow

**Comment by tero-paananen** [comment]
https://github.com/MicrosoftEdge/WebView2Feedback/issues/2726
