### ISSUE TITLE
How to set default browser for Webview

### ISSUE THREAD

**Issue by manitalti** [react-native-webview/react-native-webview#2636]
I want to set any browser e.g. Chrome as default browser for WebView to open any web application. How can we do that?
Please let me know if there is any possibility to set custom browser for WebView.

**Comment by TheAlmightyBob** [comment]
I don't understand the question. If you mean you want to use the Chrome WebView, [that's not a thing anymore](https://www.xda-developers.com/google-chrome-no-longer-webview-provider-android-10/).

**Comment by webdevsumit** [comment]
I am using the signup with Google feature in my React native app and I want to open a WebView to signup but I am getting a problem there it is asking to login to my Google account I don't want that. I want to connect the WebView with Chrome.

how can I do that?

**Comment by TheAlmightyBob** [comment]
@webdevsumit It sounds like you want to use https://github.com/proyecto26/react-native-inappbrowser instead of `react-native-webview`

**Comment by UmarbekSaidov** [comment]
I am using the signup with Google feature in my React native app and I want to open a WebView to signup but I am getting a problem there it is asking to login to my Google account I don't want that. I want to connect the WebView with Chrome.

how can I do that?
