### ISSUE TITLE
Mix audio inside WebView with other background music playing apps

### ISSUE THREAD

**Issue by tharwi** [react-native-webview/react-native-webview#2639]
I'm trying to play a video inside an iframe in a WebView. When the video starts playing, the music playing from other background apps such as Spotify will stop. But when the video is muted the background music will keep playing without any issue. 

Is there any way I can mix or duck sound inside Web View with other apps?

**Comment by mitchdowney** [comment]
@tharwi I'd love to know if there is an answer for this too.

**Comment by mahmksoft** [comment]
Any solution?

**Comment by tharwi** [comment]
> @tharwi I'd love to know if there is an answer for this too.



> Any solution?

Had to use react-native-video to implement the player
