### ISSUE TITLE
Autofill

### ISSUE THREAD

**Issue by IZSkiSurfer** [react-native-webview/react-native-webview#2644]
Bug description:

An address, log in, or credit card form in the Chrome or Safari browser will prompt the user for autocomplete suggestions saved in their browser. The RNWebview, which uses these browsers, should also prompt the user for these autocomplete suggestions.

To Reproduce:

Open a site with a log in or form in the browser and compare the autocomplete suggestions to the same page opened in the WebView.

Expected behavior:

A prompt for autofill suggestions

**Comment by abz-denys-z** [comment]
Is there a solution today that allows you to use autofill in your own application, without specifying trusted domains?

And judging from [this answer](https://developer.apple.com/forums/thread/723273?answerId=742159022#742159022), there is a solution, but how can it be integrated into the current implementation?
