### ISSUE TITLE
On ios App closes on back button pressed ?

### ISSUE THREAD

**Issue by dipkrao07** [react-native-webview/react-native-webview#2645]
**Bug description:**

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS:
 - OS version: 15.0
 - react-native version: 0.62
 - react-native-webview version:8.0.2

**Comment by TheAlmightyBob** [comment]
What back button? iOS doesn't have a back button.

**Comment by dipkrao** [comment]
as the error solved now , the error is that i put the web view container in the navigator components from where it get default back header or these header fails in ios on back button pressed.
