### ISSUE TITLE
Error: method does not override or implement a method from a supertype

### ISSUE THREAD

**Issue by Pawanagdev** [react-native-webview/react-native-webview#2646]
Hello, 

I followed the solution mentioned in #1995 to downgrade it to 11.4.5. Now, I get a new error:
"react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java:270: error: cannot find symbol
view.getSettings().setAppCachePath(ctx.getCacheDir().getAbsolutePath());
                          ^
  symbol:   method setAppCachePath(String)
  location: class WebSettings"

I got an answer for the above error in the resolved issues section saying to upgrade the module to 11.22.7 that in turn throws the previous error:
"error: method does not override or implement a method from a supertype
  @Override"

Seems like it's a catch22 situation. Please help

Environment:

OS: macOS
OS version: 12.5
Android Studio version: 4.1.3 (compileSdkVersion 33)
react-native version: 0.60.0
react-native-webview version: 11.4.5 or 11.22.7

**Comment by aminhdev** [comment]
> i am facing the same issue as well but iam using v0.59.9 of react native

You can remove some deprecated methods here then create patch
https://github.com/react-native-webview/react-native-webview/pull/2583/files

**Comment by tuanduc2904** [comment]
> > i am facing the same issue as well but iam using v0.59.9 of react native
> 
> You can remove some deprecated methods here then create patch https://github.com/react-native-webview/react-native-webview/pull/2583/files

it not working for react-native v0.59.9


> i am facing the same issue as well but iam using v0.59.9 of react native

@Swaroop-Ananda  You have solution fix it?

**Comment by Swaroop-Ananda** [comment]
> > i am facing the same issue as well but iam using v0.59.9 of react native
> 
> You can remove some deprecated methods here then create patch https://github.com/react-native-webview/react-native-webview/pull/2583/files

Thanks for the solution. But we already were  on our way of migrating react-native to 0.63. Migrating to 0.64 fixed the issue

**Comment by Swaroop-Ananda** [comment]
> > > i am facing the same issue as well but iam using v0.59.9 of react native
> > 
> > 
> > You can remove some deprecated methods here then create patch https://github.com/react-native-webview/react-native-webview/pull/2583/files
> 
> it not working for react-native v0.59.9
> 
> > i am facing the same issue as well but iam using v0.59.9 of react native
> 
> @Swaroop-Ananda You have solution fix it?

As mentioned above you can try out  solution given by @aminhdev .  If it doesnt work better to migrate to higher version of react native.
