### ISSUE TITLE
TypeError: null is not an object (evaluating '_reactNative.NativeModules.RNCWebView.isFileUploadSupported')

### ISSUE THREAD

**Issue by mike-niemand** [react-native-webview/react-native-webview#2648]
Trying WebView and have installed:

"react": "^17.0.2",
"react-native": "^0.69.4",
"react-native-webview": "^11.23.0",

When compiling it throws:  TypeError: null is not an object (evaluating '_reactNative.NativeModules.RNCWebView.isFileUploadSupported')

I've tried various methods to work around this but to no avail. 

Anyone have an ideas?

**Comment by usfslk** [comment]
I am having the same issue
OS: Android
  "react-native-webview": "^11.23.0"
    "react-native": "0.67.2",

**Comment by usfslk** [comment]
Same issue in Android when Chrome is installed, uninstall chrome and it works, ridiculous

**Comment by tstephen22** [comment]
I was running into the same error, I solved it by importing and adding the package to the ReactInstanceManager in my ReactConfig file as shown: 

<img width="855" alt="Screenshot 2022-09-09 at 13 18 17" src="https://user-images.githubusercontent.com/78868509/189348623-03c0fb51-0809-4785-a545-c926a66a7dea.png">

I don't know much about linking but I'm assuming the auto-linking isn't adding this line when linking the package to the android side.

**Comment by davidjuhyung** [comment]
You need to have `react-native-webview` to use the editor. Once I installed it and follow the instruction for Android, I did not see this `isFileUploadSupported` error anymore.

https://github.com/react-native-webview/react-native-webview/blob/master/docs/Getting-Started.md

**Comment by roxlu** [comment]
You might have done this already, but make sure to run `npx react-native run-android` after installing `react-native-webview`.

**Comment by taoqf** [comment]
To everyone after me, you came to this issue it's because you have more than 2 versions in your node_modules, remove one if you can will resolve the dependencies. I believe this is the issue with react-native auto link.

**Comment by xulihang** [comment]
This error also happens using an old Android 8 device.

**Comment by kaushaki-kumari** [comment]
> To everyone after me, you came to this issue it's because you have more than 2 versions in your node_modules, remove one if you can will resolve the dependencies. I believe this is the issue with react-native auto link.

how can remove ?
