### ISSUE TITLE
WebView doesnt load css and js from local websites

### ISSUE THREAD

**Issue by damian165-cpu** [react-native-webview/react-native-webview#2649]
I have built a website with nextjs and saved it two times. Once with the next export bundle and once i just saved the website via my browser. If i now load these into webview like this the app will only load the html.
I am trying to display my local website in native since days but it just doesnt work. I am thinking about using a local webserver so that i can load via localhost. But this is so overkill. Is there reallly no good way to just display your websites???

```
<WebView
        style={{width: '100%', height:'100%'}}
        source={{uri: 'file:///android_asset/mom/index.html'}} //'file:///android_asset/out/index.html'
        OriginWhitelist={['*']}
        injectedJavaScript={global.webInject}
        baseUrl={'///android_asset/out/index.html'}
        allowFileAccessFromFileURLs={true}
        allowUniversalAccessFromFileURLs={true}
        allowFileAccess={true}
        domStorageEnabled={true}
        nLoad={console.log("loaded!")}
        javaScriptEnabled={true}
        nativeConfig //=???
        startInLoadingState={true}
        scalesPageToFit={false}
      /> 
```

**Comment by thanhtrankma** [comment]
What is your solution?
