### ISSUE TITLE
Camera and microphone permissions doesn't work for iframe inside webview

### ISSUE THREAD

**Issue by mtperessoni** [react-native-webview/react-native-webview#2650]
Reopening some old issue: https://github.com/react-native-webview/react-native-webview/issues/2042
I was using WebView and i faced the same problem. Webview doesn't show the permission modal on iframe inside webview. If i render the iframe page directly on webview, it works. But using iframe inside the page rendered by webview the permission doesn't work.
The problem still ocurring in 11.23.0 package.

**Bug description:**

I am trying to access camera and microphone of a certain website in iframe inside webview but the permissions are not granted for it.

**To Reproduce:**

access any website that uses camera and microphone eg.https://webcamera.io/ in iframe inside webview.

**Expected behavior:**

should be able to use/access camera and microphone

**Environment:**

- OS:Ubuntu
- OS version: 18.04
- react-native version:0.63.0
- react-native-webview version: 11.6.2

**Comment by mayfairr** [comment]
+

**Comment by ratz6** [comment]
When I open https://simpl.info/getusermedia/sources/ on Chrome in Android, I'm able to see the camera and switch between front and back camera's too. But when I open the same uri on webView , it works fine on iOS but on android the camera stucks in some devices and in some devices I'm not able to toggle between front and back Cam (where frontCam is the first Camera Id and backCam is the last camera id)

**Comment by alfoadd** [comment]
Any update on this? Has anybody found a solution?

**Comment by mtperessoni** [comment]
still searching for solutions

**Comment by rafaferry** [comment]
how is your iframe code?

to get webcam working inside an iframe I had to use this code:

```
<iframe
    allowusermedia
    src="[your src]"
    allow="camera [your src];microphone [your src];display-capture [your src]"
  ></iframe>
```
