### ISSUE TITLE
userAgent/applicationForUserAgent does not work in react-native-windows

### ISSUE THREAD

**Issue by gangli66** [react-native-webview/react-native-webview#2651]
**Bug description:**

I use WebView in my react-native-windows project and I set userAgent='myapp' and applicationForUserAgent='myapp'.
But in the web which the webview load, it is still Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.22000
**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS:Win10
 - OS version:
 - react-native version:0.67
 - react-native-webview version:11.21.1

**Comment by AstonKhor** [comment]
I also see this issue, but it is specific to android webview

**Comment by gangli66** [comment]
> I also see this issue, but it is specific to android webview

It can be set normally on android and ios, but can not on windows.

**Comment by gangli66** [comment]
Any updates?
