### ISSUE TITLE
alert does not show in react-native-windows

### ISSUE THREAD

**Issue by gangli66** [react-native-webview/react-native-webview#2652]
**Bug description:**

I wrote alert in my web source. It can show on android or ios platform with react-native-webview.
But it does not show on windows tablet platform.
**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS:Win10
 - OS version:
 - react-native version:0.67
 - react-native-webview version:11.21.1

**Comment by chrisglein** [comment]
There have been cases where alert is known to work. It does have a hookup for alert that's supposed to be working. Can you include a code snippet of what you're trying to do?

**Comment by chiaramooney** [comment]
A good test  would be to try and see if you can get a Flyout component to work to see if alerts are even allowed on a Windows tablet in/out of tablet mode

**Comment by gangli66** [comment]
> 

Yes, in tablet mode. Alert written in react native can be showed, but written in web can not be showed by webview.
