### ISSUE TITLE
Unable to load Dailymotion-Video-Player embedded script for Android in React Native

### ISSUE THREAD

**Issue by Nouman-Javaid** [react-native-webview/react-native-webview#2653]
This is my code to run dailymotion player script in react native environment, given the playerId and dailymotion Video id.

`const source = {
    html: 
      `<body> <script src="https://geo.dailymotion.com/player/${playerId}” data-video=${dailymotionVideoId}></script>  </body>`
  };

 		<WebView
                  overScrollMode= {'never'}
                  source={source}
                  allowsFullscreenVideo={true}
                  allowsInlineMediaPlayback={true}
                  javaScriptEnabled={true}
                  domStorageEnabled={true}
                  scalesPageToFit={false}
                  startInLoadingState={true}
                  nestedScrollEnabled={true}
                  style={{backgroundColor: 'black'}}                
                  />`

**Problem:**
However, this scripts works fine on IOS and video is being played while in case of Android this player does not even seems to load on screen render. So is there a way around to fix the issue for android

**Comment by jimmi-joensson** [comment]
@Nouman-Javaid This does not seem to be an issue with dailymotion but rather a broader issue with Webview for Android. None of my webviews are currently loading correctly.

I'm using it in an Expo managed application, are you as well?

Here is my current versions:
```
{
  ...
  dependencies: {
    "expo": "^45.0.0",
    "react-native-webview": "11.23.0",
  }
}
```

**Comment by jimmi-joensson** [comment]
@Nouman-Javaid Okay I got all my webviews working again 🎉 

My `react-native-webview` version was too new.

Using `expo install react-native-webview` the version was lowered from `11.23.0"` to `11.18.1` and that fixed all loading issues! 👏
