### ISSUE TITLE
Error Code: 3 SSL Error : The certificate authority is not trusted in React Native Web View ( Android )

### ISSUE THREAD

**Issue by ChanaChampsoft** [react-native-webview/react-native-webview#2655]
I released a production Android app this week(20.08.2022) but had trouble with the SSL Error Handler. ( "react-native-webview": "^11.0.2" )
![Captur1e](https://user-images.githubusercontent.com/106720824/186932316-a9e6a16e-333b-4125-8770-7ef3b0fb8dcd.PNG)

As a solution, I have to allow trusted URLs to avoid the error
![webview](https://user-images.githubusercontent.com/106720824/186932636-1d92912c-b610-4dc6-abf3-e63ee6e3c8bc.png)

But after the production release got a reply saying that list of issues and the corresponding APK versions were detected in your recent submission.
![Capture](https://user-images.githubusercontent.com/106720824/186933301-4e70221d-5c36-4db1-98cd-ffc403cac69c.PNG)

Is there a way to navigate the URL, as any normal browser would allow?

**Comment by camboYY** [comment]
i face the same issue

**Comment by harika-nammi** [comment]
@ChanaChampsoft & @camboYY Did you check in real device? because i am also facing same issue in emulator (android). But in real device it's working fine.

**Comment by robert-go** [comment]
Same issue
worked on simulator
but not working on real Google Pixel 4A

**Comment by phanvanphuhn** [comment]
any solution? Re open pls

**Comment by alfredarcifa** [comment]
Follow up. I have the same issue.

**Comment by brunocdeveloper** [comment]
Same issue.

**Comment by kimjisub** [comment]
I encountered the same issue on React-Native 0.71.7 and React-Native-WebView 12.0.2.

This issue arises when trying to render a website that uses a certificate which does not have a chain configured to a trusted root certificate. You can verify this issue at https://www.sslshopper.com/ssl-checker.html. If you own the web page in question, replacing the SSL certificate would be the fundamental solution.

**Comment by kranthi1216** [comment]
Hi i am also facing this issue can any one help how to resolve.

**Comment by chunghn** [comment]
looking for updates

**Comment by vassilispanagou** [comment]
same here

**Comment by AdamSheaHewett** [comment]
This issue is far from solved

**Comment by remberluyckx** [comment]
I have the same problem, this is still not solved

**Comment by noSweatSuperDry** [comment]
In v 13.6.3, To make this change you have to go node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewClient.java.   
   
    _```
@Override
    public void onReceivedSslError(final WebView webView, final SslErrorHandler handler, final SslError error) {
        // onReceivedSslError is called for most requests, per Android docs: https://developer.android.com/reference/android/webkit/WebViewClient#onReceivedSslError(android.webkit.WebView,%2520android.webkit.SslErrorHandler,%2520android.net.http.SslError)
        // WebView.getUrl() will return the top-level window URL.
        // If a top-level navigation triggers this error handler, the top-level URL will be the failing URL (not the URL of the currently-rendered page).
        // This is desired behavior. We later use these values to determine whether the request is a top-level navigation or a subresource request.
        String topWindowUrl = webView.getUrl();
        String failingUrl = error.getUrl();

        // Cancel request after obtaining top-level URL.
        // If request is cancelled before obtaining top-level URL, undesired behavior may occur.
        // Undesired behavior: Return value of WebView.getUrl() may be the current URL instead of the failing URL.
        handler.proceed();
```_

**Comment by kelvgraf** [comment]
I am facing this problem.
What is the impact of making this change to the lib source code?

**Comment by noSweatSuperDry** [comment]
> I am facing this problem. What is the impact of making this change to the lib source code?

Modification of Webview

In v 13.6.3, To make this change you have to go node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewClient.java.

Find ssLerrorhandle, then change to handle.cancel() to handle.proceed(). It works

**Comment by kelvgraf** [comment]
It worked!
What are the side effects of this change?

**Comment by markalanevans** [comment]
How is this closed?

Why is it that just setting

```JS
<base-config cleartextTrafficPermitted="true">
    <trust-anchors>
        <certificates src="system" />
        <certificates src="user" />
    </trust-anchors>
</base-config>
```

As descriped here: https://developer.android.com/privacy-and-security/security-config#base-config

And the installing your self signed CA cert doesn't work?

shouldn't adding "user" fix this?

**Comment by markalanevans** [comment]
Yes you can edit the RNCWebViewClient.java file but seems wrong.

**Comment by ridaelfagrouch** [comment]
any update hare, i get the same issue

**Comment by sealoyal2024** [comment]
Any progress? I have changed to `handle.cancel()` to `handle.proceed()` in `RNCWebViewClient.java`,  and then It not been solved.

**Comment by hisamafahri** [comment]
Same issue here, any solution? 👀

**Comment by chris-lsn** [comment]
> How is this closed?
> 
> Why is it that just setting
> 
> ```js
> <base-config cleartextTrafficPermitted="true">
>     <trust-anchors>
>         <certificates src="system" />
>         <certificates src="user" />
>     </trust-anchors>
> </base-config>
> ```
> 
> As descriped here: https://developer.android.com/privacy-and-security/security-config#base-config
> 
> And the installing your self signed CA cert doesn't work?
> 
> shouldn't adding "user" fix this?

It does work for me after applying the changes and adding the custom rootca certificate.

**Comment by mvjuravlev** [comment]
It might be a problem with certificate configuration on web-server you trying to reach.
In my case there was no SSL certificate chain.
So solutions like
`handler.proceed();`
or
`<base-config cleartextTrafficPermitted="true" />`
can only be temporary. 
The best way in that case is contact with domain owner to fix this.

**Comment by xiaoxuehai** [comment]
> 在 v 13.6.3 中，要进行此更改，您必须转到 。默认情况下，它的 handler.cancel（） .将其更改为 proceed（）。`node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewClient.java`
> 
> ```
> ```@Override
> public void onReceivedSslError(final WebView webView, final SslErrorHandler handler, final SslError error) {
>     String topWindowUrl = webView.getUrl();
>     String failingUrl = error.getUrl();
> 
>    handler.proceed(); // cancel ```
> ```

Could you please explain how to re-construct after the modification is completed? My attempt to restart the project did not have the desired effect.

**Comment by vtech-apps** [comment]
> You can use, usesCleartextTraffic from [expo-build-properties](https://docs.expo.dev/versions/latest/sdk/build-properties/#pluginconfigtype) config plugin

@mrakesh0608 
The solution worked when we applied in in Feb, however we are getting the same error on few devices (of different brands). Is there anything else we need to do in order to avoid `Error Code: 3 SSL Error`?

Also, you alternatively suggested to use `react-native-webview+13.12.5.patch`, can you guide on how to use this and bring it to expo project?

Thanks in advance...

@brentvatne

**Comment by mcastets** [comment]
For those wondering how to apply and keep the patch: you need a solution like [patch-package](https://www.npmjs.com/package/patch-package)
