### ISSUE TITLE
Garbled Characters From Assets Resource

### ISSUE THREAD

**Issue by tkow** [react-native-webview/react-native-webview#2656]
**Bug description:**
[Garbled Characters From Assets Resource Issue](https://github.com/react-native-webview/react-native-webview/issues/1464)
is continuing.

**To Reproduce:**

I made [reproduced repository](https://github.com/tkow/expo-webview-test).

**Expected behavior:**

Correct decoded characters should be displayed.

**Screenshots/Videos:**

## Source

```ts
import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View } from 'react-native';
import WebView from 'react-native-webview'
import exampleHtml from './assets/test.html'
import { SafeAreaView } from 'react-native-safe-area-context'

export default function App() {
  return (
    <SafeAreaView edges={['bottom']} style={styles.container}>
      <WebView
        style={styles.container}
        source={exampleHtml}
      />
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    marginTop: 10,
    backgroundColor: 'white',
  },
});
```

## Actual File
```html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8" />
  </head>
  <body>
    テスト
  </body>
</html>

```

## As displaying
![スクリーンショット 2022-08-29 17 34 20](https://user-images.githubusercontent.com/7004725/187160598-c0a60e62-80fc-4266-a0a8-2f842e482757.png)

## supplementation

This may be related to metro preset or transformer. I confirmed custom metro transformer receive file data as string instead of buffer, string conversion may happen and cause garble characters with encoding data lost inside transpile process,  If do so, it's not webview problem but, metro or react native assets' management system problem.

**Comment by TheAlmightyBob** [comment]
I copied your sample project to an Expo snack. I couldn't get the Assets folder to work, but loading your sample HTML as a string into the WebView worked as expected.

https://snack.expo.dev/xxM58ZEpu

So I think you're right that "it's not webview problem but, metro or react native assets' management system problem"

If you could load your HTML in the WebView via local filepath (i.e. `source={{uri: 'file://...'`) rather than via `import`/`require`, you might have better luck.

**Comment by tkow** [comment]
@TheAlmightyBob Thank you for your advice. I resolved this issue in heavy-handed way that makes custom transformer  though not all kind of files can be completely handled. So I close this thread.

**Comment by ChenBri** [comment]
Still occurs. Any fix?
