### ISSUE TITLE
pdf, doc ,xls files not viewable on android

### ISSUE THREAD

**Issue by shivani805** [react-native-webview/react-native-webview#2660]
**Bug description:**
 files like doc, pdf are getting downloaded whenever we hit url in webview on android , for fixing this issue i added a prefix of google doc in url **https://docs.google.com/viewerng/viewer?url=${url}** -- still most of the times it shows blank page

**Expected behavior:**
it should be viewable also 

**Environment:**
 - OS: Android
 - react-native version: 0.64.2
 - react-native-webview version: 11.3.1

**Comment by TheAlmightyBob** [comment]
This is a duplicate of #2397, #1342, #714, #891 (and perhaps others I missed)

The Android WebView doesn't support viewing PDFs.

There are some alternatives offered in those linked issues, such as using `react-native-pdf`.
