### ISSUE TITLE
parent ScrollView is not scrolling when we reach the end/top of webView(child)

### ISSUE THREAD

**Issue by arqummalik1** [react-native-webview/react-native-webview#2663]
**Bug description:**
outer ScrollView is not scrolling when we reach the end/top of webView

Code : 
<ScrollView>
<ScrollView>
                                   <View style={Exstyles.displayHtml}>
                                      
                                      <WebView source={{ html: item.body }} 
                                      style={{ width: Dimensions.get('window').width, height: Dimensions.get('window').height/3 }}
                                      automaticallyAdjustContentInsets = {true}
                                      scalesPageToFit = {true}
                                      scrollEnabled={false}
                                      overScrollMode = "content"
                                      nestedScrollEnabled = {true}
                                      pagingEnabled={true}
                                      allowsLinkPreview={true}
                                      originWhitelist={['httttttps://*', 'gittttt://*']}
                                      />
                                    </View>
</ScrollView>
</ScrollView>

**To Reproduce:**

we we scroll inside the webview , once we reach the end/top of scrollView the outer scroll view i.e parent scrollView is not scrolling .
we have to click on the parent to make it slide.

**Expected behavior:**

Once we reach the end/ top of scrolling webView the outer scrollView should slide .

https://user-images.githubusercontent.com/55286684/188082486-820bf3ca-11d4-4f24-81f6-a310bb9de4ea.mp4

**Screenshots/Videos:**

**Environment:**
 - react-native version: 0.68.3
 - react-native-webview version: 11.23.0

**Comment by TheAlmightyBob** [comment]
This would be a cool feature. Unfortunately I'm not sure if there's much that can be done from the `react-native-webview` side.... my _hunch_ is that this would be more the domain of `react-native-gesture-handler`.... but there might be work required to make the two compatible. Not sure. I could be wrong about any or all of this.

**Comment by bharanidharan95** [comment]
Same issue. Any Fixes ?

**Comment by arqummalik1** [comment]
> Same issue. Any Fixes ?

no fixes till now

**Comment by guohejun** [comment]
Same issue. Any Fixes now?

**Comment by MiteshKalal7** [comment]
still searching for a solution.

**Comment by bharanidharan95** [comment]
Still facing same problem

**Comment by JP6720** [comment]
i am facing same issue

**Comment by somasekharkakarla** [comment]
same issue

**Comment by EduFrazao** [comment]
Same issue here. Any workarounds?

**Comment by pd185197** [comment]
Any workaround?
