### ISSUE TITLE
Inconsistent onNavigationStateChange behaviour between iOS and Android for SPAs

### ISSUE THREAD

**Issue by markwilcox** [react-native-webview/react-native-webview#2667]
**Bug description:**
When navigating on an SPA that modifies the URL (history) without making any request, iOS will trigger the `onNavigationStateChange` event and Android will not.

Investigating the cause of this it seems that the iOS implementation deliberately injects JavaScript with a history shim using the pushState API. This posts back messages that are intercepted and used to trigger an `onLoadingFinish`, that in turn generates the `onNavigationStateChange`.

This injected history shim is simply not present on Android. The pushState API did not used to be available pre-Android 5.0, but should be in all versions currently supported by React Native.

This being missing on Android is problematic for custom hardware back handling with SPAs in web views.

Can we add this history shim functionality to match on Android? There have been reports of problems with this functionality on Android in the past but they were closed due to inactivity.

If this is desirable, but no-one is able to pick this up soon, would you be open to a contribution implementing it?

**To Reproduce:**
Point webview at an SPA and an `onNavigationStateChange` handler.

**Expected behavior:**
Same behaviour on each platform.

**Environment:**
Tested on:
 - OS: iOS and Android
 - OS version: iOS 15.5, Android 13
 - react-native version: 0.70.0
 - react-native-webview version: 11.23.1

**Comment by edvansts** [comment]
I'm facing same issues, any fixes?

**Comment by jcarioti** [comment]
We've actually patched our usage of web view for this problem: 

```
@@ -930,6 +940,17 @@ public class RNCWebViewManager extends SimpleViewManager<WebView> {
       }
     }
 
+    @Override
+    public void doUpdateVisitedHistory(WebView webView, String url, boolean isReload) {
+      super.doUpdateVisitedHistory(webView, url, isReload);
+
+      if (!mLastLoadFailed) {
+        RNCWebView reactWebView = (RNCWebView) webView;
+
+        emitFinishEvent(webView, url);
+      }
+    }
+
     @Override
     public void onPageStarted(WebView webView, String url, Bitmap favicon) {
       super.onPageStarted(webView, url, favicon);
```

**Comment by markwilcox** [comment]
You can also inject JavaScript that shims the History API like they do on iOS, but entirely from the JS side, then track whether you can go back in the `onMessage` handler. That's what I'm doing while waiting for some response on whether a PR (like the patch above) would be accepted.

**Comment by idrissakhi** [comment]
i am having the same issue on android, some of the redirections on SPA are not at all intercepted. and some times detected but randomly

**Comment by menna-magdy-182** [comment]
Same Issue on android
 react-native-webview 11.23.1

**Comment by Kasea** [comment]
Anything? Been changing my node_modules to include the patch @jcarioti mentioned and it's been working, but it's not hard to ship a faulty build and especially not if someone other than me is building it.

If there is some niche edge case scenario that it doesn't account for, I haven't encountered it yet, but it's way better than how it is today.

**Comment by anatooly** [comment]
As for me trable on _blank href, fix it like this:
```
const INJECTED_JS = `
setTimeout(() => {
  Array.from(document.querySelectorAll('a[target="_blank"]'))
       .forEach(link => link.removeAttribute('target'));
}, 1500)

true
`
```
without timeout not work

**Comment by krzysztofnowak** [comment]
This fix is still needed

**Comment by harryfino** [comment]
Just wanted to reiterate what [krzysztofnowak](https://github.com/krzysztofnowak) said. This fix is still needed. I updated to [12.1.0](https://github.com/react-native-webview/react-native-webview/releases/tag/v12.1.0) and I'm still having the same issues with this.

**Comment by harryfino** [comment]
Reporting back again: I can confirm that this has been fixed (at least in my case). I found out that I was calling `webView.current.reload()` in part of my code when the `expoPushToken` was changing (I was injecting it into the webview and reloading so the code had the latest), and this line was causing the `goBack()` to fail after the first url change. After removing that, everything started working as I expected (and how it's documented). I was successfully able to use `onNavigateStateChange` to check to see if `canGoBack` was set to true or not, etc.

Best of luck to the rest of you waiting on this fix! 🤞

**Comment by krzysztofnowak** [comment]
Issue still exists in 13.5.1

**Comment by HolySamosa** [comment]
As stated above, as of at least 13.5.1 this is still a problem.

**Comment by mihaf70** [comment]
Fix is still needed. Issue exist in the 13.6.4 version.

**Comment by HolySamosa** [comment]
Presently I'm unable to test the latest release, but there doesn't appear to be a fix yet.

**Comment by krzysztofnowak** [comment]
Latest version 13.8.6 causes weird infinite reloading page in my case, so this issue is not fixed

**Comment by krzysztofnowak** [comment]
Is there any fix planned for this issue?

**Comment by alirezaaminii** [comment]
Is there any fix planned for this issue?

**Comment by AlirezaZandi** [comment]
I was able to listen to url changes in a spa web app using this injected JS script:
```js
//Injected JS script 
(function() {
  const sendUrlChangeMessage = () => {
    const data = {
      type: 'URL_CHANGED',
      payload: window.location.href
    };
    window.ReactNativeWebView.postMessage(JSON.stringify(data));
  };

  const originalPushState = history.pushState;
  const originalReplaceState = history.replaceState;

  // Override history.pushState
  history.pushState = function() {
    originalPushState.apply(history, arguments);
    sendUrlChangeMessage();
  };

  // Override history.replaceState
  history.replaceState = function() {
    originalReplaceState.apply(history, arguments);
    sendUrlChangeMessage();
  };

  // Listen to the popstate event (e.g., for back button)
  window.addEventListener('popstate', function() {
    sendUrlChangeMessage();
  });
})();
```

**Comment by alirezaaminii** [comment]
@AlirezaZandi I found this issue and the problem is solved easily, https://github.com/react-native-webview/react-native-webview/pull/3133
