### ISSUE TITLE
Dropdown text not visible on android

### ISSUE THREAD

**Issue by sanukumarNS** [react-native-webview/react-native-webview#2668]
**Bug description:**
The drop downs in web view don't have a readable text on android. This issue was also reported in #2542 but closed without a solution.

**To Reproduce:**
1. Open the W3school in the WebView.
2. Touch the dropdown list.
3. Show the dropdown list with white text.

**Expected behavior:**
Show black text. (This issue just shows on the Android devices)

**Screenshots/Videos:**
![173787967-ea4e9b71-525a-4d52-ae0e-5da27fa382fa](https://user-images.githubusercontent.com/55175763/189318624-f4f0ddc5-6a8c-4a0d-9ebd-8461e8bc3c5b.jpg)

**Environment:**
- OS: MacOS montery 12.4
- OS version: All versions Android
- react-native version: 0.64.0
- react-native-webview version: 10.8.3

**Comment by TheAlmightyBob** [comment]
@sanukumarNS Can you provide a specific repro? I'm not sure what "Open the W3School" means

**Comment by sanukumarNS** [comment]
@TheAlmightyBob It's weird, when I create a new project it starts working but not with the same configuration on the project I'm working on. Seems like that's not a problem with the library, closing this for now.

**Comment by Eliasdbr** [comment]
Came here trying to find the direct cause of that behavior. As sankumarNS said, this library is not the cause.

In my case, I had an android theme set to default, at android/app/res/values/styles.xml:
I think what happened to me, is that I have the dark theme in my device, so it was drawing white text, despite having my React Native app forced to the light theme.
The thing is, this component isn't from React Native, it is Android Native, so if you don't have set the styles correctly, you may encounter situations like this.

In my android/app/res/values/styles.xml, I had this:

```
...
<style name="AlertDialogTheme" parent="Theme.AppCompat.Dialog.Alert">
...
```
So I changed it to this:
```
...
<style name="AlertDialogTheme" parent="Theme.AppCompat**.Light**.Dialog.Alert">
...
```
I hope this helps someone in the future...
