### ISSUE TITLE
error: method grantFileDownloaderPermissions in class RNCWebViewModule cannot be applied to given types

### ISSUE THREAD

**Issue by fido93** [react-native-webview/react-native-webview#2669]
My react native webview previous version was 11.15.0 and some android user get android blank screen however ios working well, after update to react native webview 11.23.0 it showing warning message

`error: method grantFileDownloaderPermissions in class RNCWebViewModule cannot be applied to given types;
        if (module.grantFileDownloaderPermissions()) {`

**Environment:**
 - OS: android
 - OS version: android
 - react-native version: 0.67.2
 - react-native-webview version: 11.23.0

**Comment by TheAlmightyBob** [comment]
@fido93 Where are you seeing this warning message? In Android Studio? When building? In the log when running the app?

What Android version are you targeting?

Are you setting the [downloadingMessage](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#downloadingMessage) or [lackPermissionToDownloadMessage](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#lackpermissiontodownloadmessage) properties on the `WebView`?
