### ISSUE TITLE
How to get token receive callback function to receive token Object Json string with web view

### ISSUE THREAD

**Issue by ballza95** [react-native-webview/react-native-webview#2671]
I'm need get token receive callback function to receive with web view.

My web view input value and pass button send data call post api.

Image example token receive callback by Inspect with network google chrome.

Thank you.

<img width="957" alt="Screen Shot 2565-09-12 at 11 14 30" src="https://user-images.githubusercontent.com/32051406/189573732-d6c51939-72d8-4cb7-8658-49615c9d5622.png">

**Comment by DeepakSharma04** [comment]
anyone got solution..??

**Comment by bondPiyapan** [comment]
@DeepakSharma04 
I'm use XMLHttpReques.
[https://stackoverflow.com/questions/60620388/react-native-get-internal-api-call-data-from-url-of-the-webview](url)
Solution 1
