### ISSUE TITLE
How to use JavascriptInterface ?

### ISSUE THREAD

**Issue by bondPiyapan** [react-native-webview/react-native-webview#2677]
I would like to know how to connect to web view using JavascriptInterface.

Thank you.

**Comment by TheAlmightyBob** [comment]
https://github.com/react-native-webview/react-native-webview/blob/master/docs/Guide.md#communicating-between-js-and-native

**Comment by ballza95** [comment]
> https://github.com/react-native-webview/react-native-webview/blob/master/docs/Guide.md#communicating-between-js-and-native

You have example same android use by addJavascriptInterface(object, key) ?

Example android : 

`
webview.addJavascriptInterface(this, "Key")

@JavascriptInterface
fun someMethod(body: Key) {
    .......
}
`

Thank you.

**Comment by TheAlmightyBob** [comment]
I don't understand the question. You're wanting to use Kotlin instead of React Native?

**Comment by bondPiyapan** [comment]
@TheAlmightyBob 
No i'm not use Kotlin instead React Native

I'm need example use addJavascriptInterface use key same android  in react native webview not injectedJavaScript or do you have any way to make web view return value using key?

**Comment by TheAlmightyBob** [comment]
`addJavascriptInterface` is a native Android feature that `react-native-webview` uses behind the scenes.

It is exposed for you to use in React Native via `window.ReactNativeWebView.postMessage`, which is described here: https://github.com/react-native-webview/react-native-webview/blob/master/docs/Guide.md#the-windowreactnativewebviewpostmessage-method-and-onmessage-prop

**Comment by Slapbox** [comment]
@TheAlmightyBob I was under the impression `addJavascriptInterface` allowed sending objects directly (without serializing/deserializing them on either side of the bridge.) But as I understand it we need to stringify anything we want to send across the bridge. Am I misunderstanding somewhere?

**Comment by TheAlmightyBob** [comment]
@Slapbox You are not misunderstanding. `addJavascriptInterface` is a native Android-specific function that allows sending native Android Java/Kotlin objects, not React Native objects. Stringification is necessary because of React Native. If you're willing to dive into Java/Kotlin code you can use that function directly.
