### ISSUE TITLE
$500 Bounty - Official SwipeRefreshLayout for Android (PTR for iOS already solved)

### ISSUE THREAD

**Issue by dave-d-h** [react-native-webview/react-native-webview#2678]
--->
**Is your feature request related to a problem? If so, Please describe.**

Hi folks!

I work at a tech company and we'd like to have the below feature in 1265 (already supported for iOS) to also be "officially" supported for Android as well (in react-native-webview)

https://github.com/react-native-webview/react-native-webview/pull/1265 (this is the iOS feature) 
https://github.com/react-native-webview/react-native-webview/issues/2468 (this is the issue we want to solve to also support this for Android)

Technically, someone got 2468 "working-ish" - but it's some random forked code, and we'd prefer a version that could be merged back into the main open source project / codebase 👍

$500 in it for the person who can solve and merge into main project!
 

**Describe the solutions you came up with**

**Additional context**

**Comment by muskan273** [comment]
https://github.com/react-native-webview/react-native-webview/pull/2787
Fixed the SwipeRefreshLayout for webview (android platform) and generated a pull request.
Waiting for review.
