### ISSUE TITLE
ERROR: TypeError: Cannot read property 'isFileUploadSupported' of null

### ISSUE THREAD

**Issue by aymank900** [react-native-webview/react-native-webview#2679]
**Bug description:**
Hi
i'm still new with react native 
when i install WebView into my device an error appears 

**"ERROR  Error: Requiring module "node_modules\react-native-webview\index.js", which threw an exception: TypeError: Cannot read property 'isFileUploadSupported' of null, js engine: hermes     
 ERROR  TypeError: Cannot read property 'WebView' of undefined, js engine: hermes"**

everything is fine in the emulator  !!

**Environment:**
 - OS: Android
 - OS version: Android 12
 - react : 18.1.0
 - react-native version: 0.70.1
 - react-native-webview version: 11.23.1

**Comment by TheAlmightyBob** [comment]
This looks the same as https://github.com/react-native-webview/react-native-webview/issues/2648?
