### ISSUE TITLE
Arbitrary scheme not working on iOS NSURLErrorDomain

### ISSUE THREAD

**Issue by davidjonsson** [react-native-webview/react-native-webview#2681]
I have a link with a custom scheme "swish://" that would normally open the Swish application. However on iOS I get NSURLErrorDomain, error code -1002 "unsupported URL"

Ive added the url to Info.plist under
```
<key>LSApplicationQueriesSchemes</key>
<array>
<string>swish</string>
</array>
```

Ive added originWhiteList={['swish://*', 'https://*']} to the WebView

Strange thing is onNavigationStateChange logs

 ```
LOG  {"canGoBack": false, "canGoForward": false, "loading": true, "navigationType": "other", "target": 1909, "title": "", "url": "about:blank"}
 LOG  {"canGoBack": false, "canGoForward": false, "loading": false, "target": 1909, "title": "", "url": "about:blank"}
 LOG  {"canGoBack": false, "canGoForward": false, "loading": false, "navigationType": "click", "target": 1909, "title": "", "url": "swish://asd?b=c"}
```

and then it fails with

`Encountered an error loading page {"canGoBack": false, "canGoForward": false, "code": -1002, "description": "unsupported URL", "didFailProvisionalNavigation": true, "domain": "NSURLErrorDomain", "loading": false, "target": 1909, "title": "", "url": "about:blank"}`

so it is complaining about 'about:blank' ... I have no idea how to get around this. Entering "swish://" into safari opens the application as expected.

the html is basically

`<a href='swish://asd?b=c'>SWISHhHH</a>` (ive tried with various changes to that link to test if something else is wrong)

Anyone have any clue what Im missing?

**Comment by TheAlmightyBob** [comment]
I don't think `WKWebView` provides automatic support for that. I'd _guess_ that a solution would be to implement a handler for `onShouldStartLoadWithRequest`, check for your desired scheme, add code to open the application, and return `false` so it doesn't continue trying to load that scheme in the webview.

**Comment by psbdgr8** [comment]
@TheAlmightyBob any fix for this?

**Comment by TheAlmightyBob** [comment]
@psbdgr8 Just the same suggestion that I posted above.
