### ISSUE TITLE
onMessage is not working When applePayEnabled

### ISSUE THREAD

**Issue by urwa786** [react-native-webview/react-native-webview#2687]
**Bug description:**

**To Reproduce:**
<View style={{ flex: 1 }}><WV
      enableApplePay={true}
      source={{uri: `${SHOPPER_BASE_URL}${checkoutRes?.id}&paymentBrand=${brandType}`}}
      automaticallyAdjustContentInsets={false}
      onMessage={_onMessage}
      renderLoading={() => (
        <ActivityIndicator
          style={{
            position: 'absolute',
            color: theme.colors.primary,
            top: height / 2,
            left: width / 2,
          }}
          size="large"
        />
      )}
  /></View>)}

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS:
 - OS version:
 - react-native version:
 - react-native-webview version:

**Comment by TheAlmightyBob** [comment]
Without access to your website's code, it seems unlikely that others would be able to help here.

I trust you're following [the docs](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#enableApplePay) and have your website explicitly calling `window.webkit.messageHandlers.ReactNativeWebView.postMessage`?

**Comment by adamaveray** [comment]
Just ran into this same issue. From my limited testing it appeared the `injectedJavaScriptBeforeContentLoaded` JS was not injected at all when `applePayEnabled={true}` was set in addition to message handlers not working correctly.

**Comment by adamaveray** [comment]
@TheAlmightyBob My mistake, thank you for taking the time to point that out! The [linked Safari release notes](https://developer.apple.com/documentation/safari-release-notes/safari-13-release-notes#Payment-Request-API) there say the underlying WKWebView behaves the opposite way where injecting JavaScript will disable Apple Pay, while this library disables injected JS when enabling Apple Pay, which may be a source of confusion. Looks like [there's a warning](https://github.com/react-native-webview/react-native-webview/blob/master/apple/RNCWebView.m#L1278-L1281) on the ObjC-side of things, so would the maintainers be open to a PR to also emit a JS-side console warning when attempting to both enable Apple Pay and set an injected script so it's visible in the React Native console output too?

For anyone else ending up on this issue, as explained above messages sent via the full `window.webkit.messageHandlers.ReactNativeWebView.postMessage()` method do still work with Apple Pay enabled while the `window.ReactNativeWebView.postMessage()` shortcut does not work, in line with the documentation.

**Comment by TheAlmightyBob** [comment]
@adamaveray 

> would the maintainers be open to a PR to also emit a JS-side console warning when attempting to both enable Apple Pay and set an injected script so it's visible in the React Native console output too?

Huh. Actually my understanding is that `RCTLogWarn` _is_ supposed to show a React Native warning. Curious.

**Comment by SushilSharma12** [comment]
@adamaveray @TheAlmightyBob I am still facing this issue. Even after update the script to
```
    window.webkit.messageHandlers.ReactNativeWebView.postMessage(document.documentElement.innerHTML)
    true;
```
I am getting this warning in console
"Cannot run javascript when apple pay is enabled"
