### ISSUE TITLE
Is it possible to load sourcemaps if the Webview is loading local HTML?

### ISSUE THREAD

**Issue by Slapbox** [react-native-webview/react-native-webview#2690]
Building from Webpack, I tried `inline-source-map` but the Webview seems not to be able to cope with the memory requirements.

I tried `source-map` but it seems like you can't load a sourcemap if there's not at least one `.js` file loaded - but we inline all our JS into the HTML.

Are there any options I'm overlooking? Or can the memory limit be overcome? The total file size when trying to load with `inline-source-map` is about 23mb.

**Comment by Slapbox** [comment]
Not stale.

**Comment by Slapbox** [comment]
Not stale.

**Comment by Slapbox** [comment]
Still not stale.

**Comment by Slapbox** [comment]
Not stale.

Probably not possible, but not stale.

**Comment by Slapbox** [comment]
Not stale.

**Comment by abanobmikaeel** [comment]
Anything on this? I've been struggling through this and my best bet has been porting over 500000 lines of js into an index.html file which is super not ideal
