### ISSUE TITLE
Android 13, videos playing in the webview freezes but audio continues. Not happening on older versions of android. mediaPlaybackRequiresUserAction used to be the solution for older versions.

### ISSUE THREAD

**Issue by sandy428** [react-native-webview/react-native-webview#2694]
**Bug description:**

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS:
 - OS version:
 - react-native version:
 - react-native-webview version:

**Comment by sandy428** [comment]
Any update on this?

**Comment by LukasBombach** [comment]
We have hand-written Kotlin code and a WebView and run into the same issue

**Comment by MaiconLeffa** [comment]
Does anybody know how to handle this?

**Comment by CraigDunn** [comment]
It's the latest update of Android System Webview - yes, the one from Google LLC in the PlayStore.
I uninstalled that and gUM camera video no longer freezes in the webview.

**Comment by Minishlink** [comment]
We also found that this is an issue that appeared with an update from Android System Webview, likely around September 23rd.
I'm not entirely sure, but one way to mitigate this is to make sure the webview is not unmounted and remounted in a short amount of time.

**Comment by kumarutsavrobosoft** [comment]
setting this prop mediaPlaybackRequiresUserAction to true helped and it works smoothly now for me.

**Comment by kumarutsavrobosoft** [comment]
mediaPlaybackRequiresUserAction={false} worked for me

**Comment by vika0392** [comment]
Same issue happening on Galaxy 22, Android 12. Uninstalling Android System Webview seems to resolve the issue, however it's not possible to instruct every user of our product to do so. Hope there is an update on this issue

**Comment by itsdenispavlovic** [comment]
Any update?

**Comment by k6c8e4** [comment]
Maybe it's late, but try to reinstall system webview. After this operation all is working like a charm on my side :/
https://play.google.com/store/apps/details?id=com.google.android.webview

**Comment by LukeAskew** [comment]
@Minishlink Do you have a link to the change that you suspect caused the issue?

**Comment by Minishlink** [comment]
@LukeAskew No, sorry, we ended up using hls.js on android instead of using a simple html video element

**Comment by krisidmisso** [comment]
@Minishlink can you share more info on how you implemented that? Did use head scripts to import `hls.js` or did you import it from a local file(how)?

**Comment by Minishlink** [comment]
@krisidmisso we use HLS only on Android as there is no need on iOS. Like this for loading HLS, where we fallback to a local file (in `android/src/app/main/assets`) if the network request failed. But you might choose another strategy (always local) depending on your use case

```html
<script src="https://cdn.jsdelivr.net/npm/hls.js@1/dist/hls.light.min.js"></script>
<script>
if (!window.Hls) {
  document.write('<script src="file:///android_asset/hls.light.js"><\\/script>');  
}
</script>
```
