### ISSUE TITLE
Calling View methods on another thread than the UI thread

### ISSUE THREAD

**Issue by vinitgundeti** [react-native-webview/react-native-webview#2695]
**Bug description:**
Getting error message of Calling View methods on another thread than the UI thread

**To Reproduce:**
Whenever the webview loads it is crashing with the above mentioned error

**Expected behavior:**
Webview should load instead of crashing

**Screenshots/Videos:**
![Screenshot_2022-10-03-13-04-43-47_99c04817c0de5652397fc8b56c3b3817](https://user-images.githubusercontent.com/47896506/193532897-570628f1-c5f2-4852-8e92-4682263072aa.jpg)

**Environment:**
 - OS: Mac
 - OS version: 12.6
 - react-native version: 0.67.4
 - react-native-webview version: 11.23.1

**Comment by marcshilling** [comment]
Same issue. Seemingly just started happening randomly with no code changes....

**Comment by cassde** [comment]
same here, didn't change any code and started getting this error. Does anyone know how to fix this or any workarounds?

**Comment by TheAlmightyBob** [comment]
What platform/version are you seeing this on?

**Comment by cassde** [comment]
It happens on the android emulator:
 "react-native-webview": "11.23.0",
![image](https://user-images.githubusercontent.com/114942549/193651455-1a2f96f3-19b8-4f53-a06d-29d54b309a92.png)

**Comment by TheAlmightyBob** [comment]
I'm unable to repro. Can you share a sample app or snack?

**Comment by vinitgundeti** [comment]
My issue is resolved by downgrading the @react-native-firebase packages version. It's weird but worked.

<img width="913" alt="Screenshot 2022-10-04 at 12 23 30 PM" src="https://user-images.githubusercontent.com/47896506/193753825-b4c21121-5e8b-47ac-ba1d-1802856334d9.png">

**Comment by marcshilling** [comment]
@vinitgundeti @cassde are either of your web views within a React Native `<Modal>` component? Seems isolated to those instances in my app...

**Comment by cassde** [comment]
mine started to work randomly too, without any change to the code.

**Comment by vinitgundeti** [comment]
closing the issue
