### ISSUE TITLE
Not able to open 3rd party app(UAE Pass mobile app) from react-native-Webview

### ISSUE THREAD

**Issue by VivekSingh1988** [react-native-webview/react-native-webview#2696]
**Bug description:** Not able to open 3rd party app(UAE Pass mobile app) from react-native Webview

**To Reproduce:** Not able to reproduce error or warning

**Expected behavior:** I want to open 3rd party app and login into the  3rd party app and get the response in react-native-webview callback so that we can handle 3rd party login app response through web-view callback in my application.

**Environment:**
 - OS: Android/iOS
 - OS version: Android 12 .o above and iOS 11 above
 - react-native version: 0.65
 - react-native-webview version: latest version

**Comment by ausshadu** [comment]
Hi @VivekSingh1988 any update on the above issue? Were you able to proceed?

**Comment by VivekSingh1988** [comment]
> Hi @VivekSingh1988 any update on the above issue? Were you able to proceed?

No updates Ausshadu..

**Comment by Marwan-Daghbadj** [comment]
Hi @VivekSingh1988 , @ausshadu , @TheAlmightyBob , @imownbey , @alloy ,
i know its long time but maybe someone will need it
go to the react-native-webview > src > WebViewShared.tsx
find the function "const createOnShouldStartLoadWithRequest"
replace with this
const createOnShouldStartLoadWithRequest = (
  loadRequest: (
    shouldStart: boolean,
    url: string,
    lockIdentifier: number,
  ) => void,
  originWhitelist: readonly string[],
  onShouldStartLoadWithRequest?: OnShouldStartLoadWithRequest,
) => {
  return ({ nativeEvent }: ShouldStartLoadRequestEvent) => {
    let shouldStart = true;
    const { url, lockIdentifier } = nativeEvent;

    if (!passesWhitelist(compileWhitelist(originWhitelist), url)) {
      if (onShouldStartLoadWithRequest)
        onShouldStartLoadWithRequest(nativeEvent);
      // Linking.canOpenURL(url).then((supported) => {
      //   if (supported) {
      //     return Linking.openURL(url);
      //   }
      //   console.warn(`Can't open url: ${url}`);
      //   return undefined;
      // }).catch(e => {
      //   console.warn('Error opening URL: ', e);
      // });
      shouldStart = false;
    } else if (onShouldStartLoadWithRequest) {
      shouldStart = onShouldStartLoadWithRequest(nativeEvent);
    }
    loadRequest(shouldStart, url, lockIdentifier);
  };
};
this wayt you'll receive the event from your webview
in your webview add this
<WebView
          source={{
            uri,
          }}
          onShouldStartLoadWithRequest={({url}) => {
            console.log('url.......', url);
            if (url.startsWith('uaepass://')) {
              url = url.replace('uaepass://', 'uaepassstg://');// if you in staging 
              // do the stop from the uaepass document website
              
              return false;//to stop the navigating
              }
             else{
             return true;//to continue the navigating
             }
/>

if you need help just ask me
