### ISSUE TITLE
Redirection Issue in Web View for Android

### ISSUE THREAD

**Issue by e-pradeep** [react-native-webview/react-native-webview#2699]
**Bug description:**
On android devices with the the latest version of react-native-webview package, we have observed an issue that while scrolling through the web view even after loading the page completely the web-view is redirecting back (kicking the user out of the web view)

The issue happens If the user quickly scrolls down the web view or while slowly scrolling through the web page.

**Environment:**

OS: Android
react-native version: 0.66.3
react-native-webview version: v11.23.1 - latest

**Comment by TheAlmightyBob** [comment]
I don't understand what you mean by "redirecting back (kicking the user out of the web view)". "Redirecting" sounds like something that would happen within the WebView (going to a different URL), but "kicking the user out of the web view" sounds like something outside the scope of `react-native-webview`...?
