### ISSUE TITLE
Customize toast message "Downloading..." on file download (android only)

### ISSUE THREAD

**Issue by alexmercier25** [react-native-webview/react-native-webview#2700]
When I download a file within the WebView, it says "Downloading...". I would like to be able to replace this message with the localized version.

**To reproduce:**
- set `allowUniversalAccessFromFileURLs` to **true**
- Set the `source` to any web page that has a download link
- Add the domain (can be a S3 domain) to `originWhitelist`

**Comment by TheAlmightyBob** [comment]
Great news! You can!

https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#downloadingMessage
