### ISSUE TITLE
Important || Request for updating gradle.properties for android

### ISSUE THREAD

**Issue by Abhishektaurus** [react-native-webview/react-native-webview#2702]
Hello @jamonholmgren  & Team,

I request you to update the android's gradle.properties versions of kotlin & SDK. I am stuck with the error in your dependency gradle file that kotlin & SDK version needs to be upgraded as I am upgrading the Android SDK to version 32 in the organization's product where your library plays an important part.
I would be needing your help to resolve the above issue. I hope to get the solution as soon as possible.
Thank you in advance !!

**Comment by Abhishektaurus** [comment]
Can you please help me to resolve the issue ?? @jamonholmgren

**Comment by BharatBhushan2907** [comment]
@jamonholmgren please help me as well, I got the same requirement

**Comment by sudhanshusirohia** [comment]
Any update here, facing same issue
