### ISSUE TITLE
I May Know Why onShouldStartLoadWithRequest prop Not Work in Android

### ISSUE THREAD

**Issue by Juanjuanquanliu** [react-native-webview/react-native-webview#2705]
**Bug description:**
if I use WebView in JS:
```js
<WebView
        source={{ uri: url }}
        onShouldStartLoadWithRequest={(request)=>{
          console.log(request);
          return true;
        }}
      />
```
I cannot receive the **onShouldStartLoadWithRequest** in JS. and if I have ` <a href="https://example.com" target="_blank" />`in H5, it jump to browser directly. Then I debug in Android and find it doesn't go to **shouldOverrideUrlLoading** in WebViewClient. Then I find some solutions in [#1869](https://github.com/react-native-webview/react-native-webview/issues/1869). One is to set **setSupportMultipleWindows** as **false** in JS. It works well.

And I find the implementations of setSupportMultipleWindows in Android(RNCWebChromeClient) works like this:

1. if we allow setSupportMultipleWindows, in Android, it will create a new WebView but not RNCWebView
```java
  protected static class RNCWebChromeClient extends WebChromeClient implements LifecycleEventListener {
    ...
    @Override
    public boolean onCreateWindow(WebView view, boolean isDialog, boolean isUserGesture, Message resultMsg) {

      final WebView newWebView = new WebView(view.getContext());
      final WebView.WebViewTransport transport = (WebView.WebViewTransport) resultMsg.obj;
      transport.setWebView(newWebView);
      resultMsg.sendToTarget();

      return true;
    }
}
```
2. the new WebView is not th RNCWebView we create in JS, so the RNCWebView's RNCWebChromeClient doesn't work.
3. when we meet `<a href="https://example.com" target="_blank" />`， if WebView doesn't set WebViewClient, it will jump to browser to handle something.

above steps may explain why onShouldStartLoadWithRequest in JS not work and why it jumps to browser.

**Environment:**
 - OS: Android
 - react-native version: 0.69.2
 - react-native-webview version: 11.23.1

**Comment by TheAlmightyBob** [comment]
Thanks @Juanjuanquanliu . What you describe sounds like the expected behavior, as per the documented changes in https://github.com/react-native-webview/react-native-webview/releases/tag/v11.0.0

But others may have missed those release notes as well, so I appreciate your bringing attention to it. Do you think adding a note about that to the documentation for `onShouldStartLoadWithRequest` would help reduce confusion in the future? I'm not sure where else we could put that information where people would be likely to see it...

(Also, if https://github.com/react-native-webview/react-native-webview/pull/2640 were to be completed/merged, that might help with some of these use cases.. it still wouldn't trigger `onShouldStartLoadWithRequest`, but it would raise a new event instead)

**Comment by Juanjuanquanliu** [comment]
yeah, it isn't a bug. I didn't see the type dicussion, sorry. I think it actually needs to add a note to the documentation for `onShouldStartLoadWithRequest`, this prop is used frequently. The action whether we jump to browser or do other things may be handled or determined by frontend. [#2640](https://github.com/react-native-webview/react-native-webview/pull/2640) can solve the problem but seems to make the `onShouldStartLoadWithRequest` useless and I think .

**Comment by TheAlmightyBob** [comment]
> https://github.com/react-native-webview/react-native-webview/pull/2640 can solve the problem but seems to make the `onShouldStartLoadWithRequest` useless

`onShouldStartLoadWithRequest` is still used for navigation within the WebView (i.e., if the web page isn't asking to open a new window).

**Comment by fukemy** [comment]
> Thanks @Juanjuanquanliu . What you describe sounds like the expected behavior, as per the documented changes in https://github.com/react-native-webview/react-native-webview/releases/tag/v11.0.0
> 
> But others may have missed those release notes as well, so I appreciate your bringing attention to it. Do you think adding a note about that to the documentation for `onShouldStartLoadWithRequest` would help reduce confusion in the future? I'm not sure where else we could put that information where people would be likely to see it...
> 
> (Also, if #2640 were to be completed/merged, that might help with some of these use cases.. it still wouldn't trigger `onShouldStartLoadWithRequest`, but it would raise a new event instead)

Hi, I tried to set `setSupportMultipleWindows` to `false` but `onShouldStartLoadWithRequest` still not called for android

**Comment by dembal1990** [comment]
Same issue with v13.12.2 on Android
