### ISSUE TITLE
InjectedJavascript doesn't work properly on Windows

### ISSUE THREAD

**Issue by garder500** [react-native-webview/react-native-webview#2706]
**Bug description:**
The injectedJavascript props doesn't work properly on Windows, so any script i put in it doesn't work... 

I really need this functionnality, because without it, it can't work properly

**To Reproduce:**

Just put a regular function like sending a message to the React native side

And see, that nothing is executed 

**Expected behavior:**
Message should be sent to the React native side

**Screenshots/Videos:**

**Environment:**
 - OS: Window
 - OS version: 10.0.19044
 - react-native version: 0.70.2
 - react-native-webview version: 11.23.1

**Comment by tero-paananen** [comment]
`injectedJavaScript`  is not supported on Windows.

Example has this kind of postMessage in use
https://github.com/react-native-webview/react-native-webview/blob/c14dcc2617429ca53b91de18eac07ed7b119c239/example/examples/Messaging.tsx#L54

I inject this js into WebView `window.postMessage = function(data, origin) { window.ReactNativeWebView.postMessage(String(data)); };` calling `this.webViewRef.injectJavaScript()` 

and send message injecting message using my helper `getInjectableJSMessage` via `this.webViewRef.injectJavaScript()`

```
export function getInjectableJSMessage(message: any): string {
  return getSafelyInjectableJs(
    `(function() {document.dispatchEvent(new MessageEvent('message', {data: ${JSON.stringify(
      message
    )}}));})();`
  );
}
```
