### ISSUE TITLE
Support for XCODE 14 & Android November deadline

### ISSUE THREAD

**Issue by dwkd** [react-native-webview/react-native-webview#2707]
Can we get a compatiblity update for iOS and Android new deployment target requirements:

- XCode 14 requires [IPHONEOS_DEPLOYMENT_TARGET >= 11](https://developer.apple.com/support/xcode)
- Android has a [November deadline for targetSdkVersion of 31](https://developer.android.com/google/play/requirements/target-sdk?authuser=1)

Thank you

**Comment by TheAlmightyBob** [comment]
Have you actually run into problems with `react-native-webview` after updating your app to those targets?

**Comment by dwkd** [comment]
seems to work after upgrading to RN 0.68.4
