### ISSUE TITLE
Invariant Violation: nodeHandle expected to be non-null

### ISSUE THREAD

**Issue by iamrohitagg** [react-native-webview/react-native-webview#2708]
I am calling
```
ref.reload()
```
But I am getting `Invariant Violation: nodeHandle expected to be non-null`. Also, this error is only on Android for me.
I am showing local html file
```
source={{
                uri: isAndroid
                  ? 'file://' +
                    dirs.DocumentDir +
                    '/bundled-assets/assets/ChannelTemplates/' +
                    pub.channelsArray[0].channelViewTemplate
                  : newURI,
              }}
```
Library version used     "react-native-webview": "^11.17.2",

**Comment by TheAlmightyBob** [comment]
I haven't seen that before and without a sample repro it's hard to know what's happening, but if you search you'll find a few past mentions of that error that may be related to your situation, such as #1828.

**Comment by iamrohitagg** [comment]
I was replacing my current screen using `navigation.replace('screenName')`.
I was getting error when I was reloading the webView and replacing current screen simultaneously. I applied check like this
```
if (ref && ref.webViewRef && ref.webViewRef.current) {
        ref.reload();
      }
```
