### ISSUE TITLE
How to disable swipe navigation (backforward) on react-native-webview(2) for windows

### ISSUE THREAD

**Issue by gangli66** [react-native-webview/react-native-webview#2709]
**Bug description:**

I use webview2 to load my web site and it will back to forward page when I touch it and move rightforwards.
I know webview2 provides a property isSwipeNavigationEnabled, but how can I set it to false in a react-native project?
**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS: Win10
 - OS version: 22000.1098
 - react-native version: 0.68
 - react-native-webview version: 11.23.1

**Comment by chrisglein** [comment]
You're looking for this? [IsSwipeNavigationEnabled](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2settings.isswipenavigationenabled?view=webview2-dotnet-1.0.1370.28). That's accessible from the core WebVew2 API but not necessarily the [WinUI WebView2 wrapper](https://learn.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.webview2?view=winui-2.8). So this isn't straightforward to expose.

Is there a comparable on Android/iOS/etc? (as in should this be a general RN webview property or is it just Windows specific?)

**Comment by asklar** [comment]
in native code, you might be able to do this by getting the webview2 control's [CoreWebView2](https://learn.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.webview2.corewebview2?view=winui-2.8), then getting its [CoreWebView2Settings](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/winrt/microsoft_web_webview2_core/corewebview2?view=webview2-winrt-1.0.1054.31#settings) object and then setting the IsSwipeNavigationEnabled. So basically something like: 
```cpp
webview2.CoreWebView2().Settings().IsSwipeNavigationEnabled(false);
```

**Comment by gangli66** [comment]
> You're looking for this? [IsSwipeNavigationEnabled](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2settings.isswipenavigationenabled?view=webview2-dotnet-1.0.1370.28). That's accessible from the core WebVew2 API but not necessarily the [WinUI WebView2 wrapper](https://learn.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.webview2?view=winui-2.8). So this isn't straightforward to expose.
> 
> Is there a comparable on Android/iOS/etc? (as in should this be a general RN webview property or is it just Windows specific?)

Thanks for you answer.
Maybe IsSwipeNavigationEnabled(false) could help me, however, I don't know in which cpp I should use it and how to get the settings. 
Or any other method can do this?
On Android/iOS there is no this issue. It seems like that it only occurs on windows.

**Comment by gangli66** [comment]
> in native code, you might be able to do this by getting the webview2 control's [CoreWebView2](https://learn.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.webview2.corewebview2?view=winui-2.8), then getting its [CoreWebView2Settings](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/winrt/microsoft_web_webview2_core/corewebview2?view=webview2-winrt-1.0.1054.31#settings) object and then setting the IsSwipeNavigationEnabled. So basically something like:
> 
> ```c++
> webview2.CoreWebView2().Settings().IsSwipeNavigationEnabled(false);
> ```

Thanks for you answer.
In which cpp/function should I write it? 
I have got settings of webview2 in UpdateProperties of ReactWebView2Manager.cpp but it seems that I can't use it straightly.
