### ISSUE TITLE
No discovery after installation RN-webview

### ISSUE THREAD

**Issue by liuhui1999** [react-native-webview/react-native-webview#2715]
**Bug description:**
The RN project failed to initialize and install the react-native-webview component

**To Reproduce:**

npx react-native init AwesomeTSProject --template react-native-template-typescript

yarn add react-native-webview
**Expected behavior:**
no error

**Screenshots/Videos:**
![image](https://user-images.githubusercontent.com/71832496/197695241-e1fdfd71-6e9a-4ec1-83ae-21838dd18cb6.png)
![image](https://user-images.githubusercontent.com/71832496/197695242-72b0b9c7-84c6-4215-8153-833d84dcfd83.png)

**Environment:**
 - OS:no
 - OS version:no
 - react-native version:0.70.3
 - react-native-webview version:^11.0.1
 -   "react": "18.1.0",
 - windows:win10 64

**Comment by liuhui1999** [comment]
![image](https://user-images.githubusercontent.com/71832496/197695401-4c8d2abd-c62f-4467-b03b-94fb98c817b7.png)
![image](https://user-images.githubusercontent.com/71832496/197695419-44bdb096-e471-4daa-b600-02366954fdf9.png)
![image](https://user-images.githubusercontent.com/71832496/197695426-9ff28160-cd2e-4c06-a9bd-82e2ff6dcea9.png)

**Comment by TheAlmightyBob** [comment]
This appears to be a duplicate of #2648
