### ISSUE TITLE
Android crashes while opening WebView

### ISSUE THREAD

**Issue by vaxo41nba** [react-native-webview/react-native-webview#2716]
**Bug description:**
I use WebView throughout my whole app but in one particular occasion it returns me the error that you are seeing on the screenshot. I send a request to the server and after it returns data I update source of the WebView component accordingly. Again, I do it in several different screen, but only this is problematic and only on Android.

**To Reproduce:**
Reusable WebView component:
`<Modal
      presentationStyle="pageSheet"
      visible={!!webViewObj}
      animationType="slide"
    >
      <TouchableOpacity activeOpacity={0.99} style={styles.flex}>
        <TouchableOpacity style={styles.close} onPress={closeWebView}>
          <Image source={images.Close} />
        </TouchableOpacity>
        <WebView
          nestedScrollEnabled
          originWhitelist={['*']}
          allowsFullscreenVideo
          allowsInlineMediaPlayback
          allowFileAccess
          allowFileAccessFromFileURLs
          allowUniversalAccessFromFileURLs
          javaScriptEnabled
          domStorageEnabled
          startInLoadingState
          {...props}
        />
      </TouchableOpacity>
    </Modal>`

This is imported component:
`<AppWebView
          onNavigationStateChange={onNavigationStateChange}
          source={{ uri: webViewObj?.actionUrl }}
        />`

The block which is responsible for getting webview data:
`const handleAddCard = async () => {
    const params = {
      currency: code,
      redirectUri: 'cryptal.com',
      provider: depositProvider,
    };
    const webViewObj = await addCard(params);
    dispatch({ type: 'SET_APP_WEBVIEW_OBJ', webViewObj });
  };`

**Expected behavior:**
WebView must be opened without any problem

![This is an image](https://i.ibb.co/swXDXXr/webview-crash.jpg)

**Comment by Ulan4eg** [comment]
Same problem.
Android 9. build-tools sdk31.

**Comment by nandirb** [comment]
is there any update?

**Comment by vaxo41nba** [comment]
> is there any update?

not at all. problem remains.

**Comment by anderCM** [comment]
I have same error
