### ISSUE TITLE
ios - SecTrustGetCertificateAtIndex deprecated

### ISSUE THREAD

**Issue by neaRRRRR** [react-native-webview/react-native-webview#2721]
**Is your feature request related to a problem? If so, Please describe.**

In apple folder, RNCWebView.m file has using SecTrustGetCertificateAtIndex Security API which is deprecated. Is there anyway to replace it?

**Comment by EthanArbuckle** [comment]
Hi RN Team! I'd like to add some additional details of the change that should be implemented.

As noted above, `SecTrustGetCertificateAtIndex` has been deprecated in iOS 15.0, with `SecTrustCopyCertificateChain` introduced as the replacement. Note that `SecTrustCopyCertificateChain` is only available on iOS 15+.

`RNCWebView` uses the deprecated API here: https://github.com/react-native-webview/react-native-webview/blob/master/apple/RNCWebView.m#L965

This recommended code change will use the newer API on iOS 15+ while still maintaining compatibility with older releases: 

```
SecCertificateRef serverCertificate = NULL;
if (@available(macOS 12.0, iOS 15.0, *)) {
    CFArrayRef certs = SecTrustCopyCertificateChain(trust);
    serverCertificate = (SecCertificateRef)CFArrayGetValueAtIndex(certs, i);
    CFRelease(certs);
} else
{
    serverCertificate = SecTrustGetCertificateAtIndex(trust, i);
}
```
Apple documentation for deprecated [`SecTrustGetCertificateAtIndex`](https://developer.apple.com/documentation/security/1395987-sectrustgetcertificateatindex?language=objc)
Apple documentation for [`SecTrustCopyCertificateChain`](https://developer.apple.com/documentation/security/3747134-sectrustcopycertificatechain?language=objc)
