### ISSUE TITLE
menuItems are not always relevant and should be hidden

### ISSUE THREAD

**Issue by zanemcca** [react-native-webview/react-native-webview#2726]
**Bug description:**
The highlight menu can be opened without any text selected sometimes which changes the expected menuItems. For instance if you have extra menuItems to add text decorations like strikethrough then they will only be relevant if you have text selected. 

I think a general approach to fix this would be to add a `shouldShow` property to the menuItems. It could be a function that lets us dynamically control which menuItems should show at which times.

**To Reproduce:**
Follow the same setup as https://github.com/react-native-webview/react-native-webview/issues/2725. Namely steps 1-2. Once that is complete open the app and longpress in the input field.

**Expected behavior:**
The select menu should show without the text decoration menuItems.

**Screenshots/Videos:**
<img width="522" alt="Screen Shot 2022-11-03 at 11 00 46 AM" src="https://user-images.githubusercontent.com/3848969/199799553-cd86947d-9f57-4b2f-8e34-c3397c4a0ce7.png">

**Environment:**
 - OS: iOS
 - OS version: 15.5
 - react-native version: 0.70.1
 - react-native-webview version: 11.23.1

**Comment by tbwork** [comment]
Shit，no one to response? did you solve this problem? bro.

**Comment by zanemcca** [comment]
@tbwork I did not. I believe we just do not support menu items currently.
