### ISSUE TITLE
On windows, URLs with hashtags are getting cut off at the hash and not loaded with the hash.

### ISSUE THREAD

**Issue by sp1665** [react-native-webview/react-native-webview#2728]
**Bug description:**

On navigation, when getting the URL from the event it gets cut off at the hash. This only happens on windows, for iOS and Android the url is full. 

**To Reproduce:**
Load a webview on Windows and then set up a navigation event. In this event print out a URL that should have information after a hash but you will find it doesn't.

**Expected behavior:**
Want the full URL with the information after the hashtag.

**Environment:**
 - OS: Windows
 - OS version: 10
 - react-native version: 0.70.3
 - react-native-webview version: 11.23.1

**Comment by chrisglein** [comment]
Are you on WebView or WebView2?
(trying to determine if this is a long-standing issue or something new to the transition to WebView2)

**Comment by sp1665** [comment]
This is on webview2

**Comment by sp1665** [comment]
@chrisglein Any update on this?

**Comment by chrisglein** [comment]
@chiaramooney Can you do a quick check to see if there's any custom parsing happening here in the community module implementation for Windows or if this is being truncated in the Windows WebView2 part of things.
