### ISSUE TITLE
Error: XXX cannot be loaded as its extension is not registered in assetExts

### ISSUE THREAD

**Issue by JaLe29** [react-native-webview/react-native-webview#2729]
I am having same problem like other users:

https://github.com/react-native-webview/react-native-webview/issues/1394
https://github.com/react-native-webview/react-native-webview/issues/1271
https://github.com/react-native-webview/react-native-webview/issues/1178
https://github.com/react-native-webview/react-native-webview/issues/746

I didnt found any solution.

Can some one help me to fix this issue?

I would like to "build" my react app using react-native-webview **loaded from assets folder**, not from website url.

Thank you in advice.

**Comment by sahajarora1286** [comment]
Hi, were you able to find any resolution to this?

**Comment by JaLe29** [comment]
no

**Comment by sahajarora1286** [comment]
I was able to use Webpack's InlineHtml plugin to get the javascript
injected in my index.html.

**Comment by Girish-GAP** [comment]
I am still experiencing an issue. Do you have any solutions for a local JS file?

**Comment by abanobmikaeel** [comment]
Same, any solutions for this?

**Comment by Girish-GAP** [comment]
If you can't find a solution, a workaround is to simply inject JS directly into the HTML file—it's a workaround that should do the trick.

**Comment by klolo** [comment]
Any solution for running html in webview with multiple js and css dependency?

**Comment by Krucial92** [comment]
Hello anyone can answer this???? Seen multiple threads of this same issue spanning over multiple years, is this possible or not?

I have a react app built with Vite (and using Expo with RNW), so my index.html file loads a number of assets e.g:

```
<script type="module" crossorigin src="./release/c8c7169/entry.309fd138.js"></script>
<link rel="modulepreload" crossorigin href="./release/c8c7169/assets/chunk.dcdad224.js">
<link rel="modulepreload" crossorigin href="./release/c8c7169/assets/chunk.4bfd8a8d.js">
<link rel="modulepreload" crossorigin href="./release/c8c7169/assets/chunk.9a8cc493.js">
<link rel="modulepreload" crossorigin href="./release/c8c7169/assets/chunk.0fe0003e.js">
<link rel="modulepreload" crossorigin href="./release/c8c7169/assets/chunk.963b6e1c.js">
<link rel="modulepreload" crossorigin href="./release/c8c7169/assets/chunk.28fd7992.js">
<link rel="stylesheet" href="./release/c8c7169/assets/index-8840de93.css">
```

I cannot embed all of this into the index.html file, and I don't want to load these assets over the network from CDN. How can I get this working to load this app from the local file system?? Suggestions??

@klolo did you manage to get this working? thanks

**Comment by nullCode666** [comment]
who can solve this problem？this problem has existed for long time ！！！
