### ISSUE TITLE
Geolocation permissions not forwarded

### ISSUE THREAD

**Issue by lehmannphi** [react-native-webview/react-native-webview#2731]
When using the geolcoation api in a react-native-webview, I am asked twice whether the app is allowed to use my current location.

![image](https://user-images.githubusercontent.com/114735332/200327840-ec4bfc64-88e7-4363-b2cd-4afa567463ef.png)
![image](https://user-images.githubusercontent.com/114735332/200327883-9db214d4-33a6-406a-90c4-12ddc3288f68.png)

**Comment by vchhetry** [comment]
Issue is in Android 13, any help ?

**Comment by ClementCHA** [comment]
Any update on this? 🫠
