### ISSUE TITLE
reload not working first load page in android 

### ISSUE THREAD

**Issue by kwangjaeyoo** [react-native-webview/react-native-webview#2735]
If reload() is called after the webview is loaded for the first time, nothing happens .
android not working / ios working 

reload() in android works when you navigate the web to another page.

this is my webview 

 const webviewRef = useRef<WebView>(null);
 const [webviewUrl, setWebviewUrl] = useState('');

  const reload = () => {
    console.log('reloadURL !! ' + webviewUrl );
    webviewRef.current?.reload();
  };

 <WebView
          source={{
            uri: webviewUrl,
            headers: {
              HTTP_HEADER_NETWORK_STATE_KEY: network,
              HTTP_HEADER_WINDOW_SIZE:
                Math.round(windowWidth) + 'x' + Math.round(windowHeight),
            },
          }}
          ref={webviewRef}
          applicationNameForUserAgent={' ' + getUserAgent()}
          allowsBackForwardNavigationGestures={true}
          onShouldStartLoadWithRequest={request => {
            console.log(
              'onShouldStartLoadWithRequest =>' + JSON.stringify(request),
            );
            return true;
          }}
          onLoadStart={({nativeEvent}) => {
            console.log('onLoadStart ' + nativeEvent.url);
          }}
          onLoadProgress={({nativeEvent}) => {
            console.log('progress ' + nativeEvent.progress);
          }}
          onLoadEnd={({nativeEvent}) => {
    console.log('onLoadEnd ' + nativeEvent.url);
          }}
          startInLoadingState={true}
          renderLoading={loadingImage}
          javaScriptEnabled={true}
          originWhitelist={['*']}
          injectedJavaScript={injectedJavascript}
          onMessage={handleMessage}
          onNavigationStateChange={handleWebViewNavigationStateChange}
        />

my log 
====> first loading 
 LOG  webview load() https://www.google.com?__langcd=ko
 LOG  webviewUrl => https://www.google.com?__langcd=ko
 LOG  progress 0.10000000149011612
 LOG  onLoadEnd url=> https://www.google.com/?__langcd=ko
 LOG  handler webview loading true
 LOG  progress 0.10000000149011612
 LOG  onLoadStart https://www.google.com/?__langcd=ko
 LOG  handler webview loading true
 LOG  progress 0.27000001072883606
 LOG  progress 0.800000011920929
 LOG  progress 1
 LOG  onLoadEnd url=> https://www.google.com/?__langcd=ko
 LOG  progress 1
 LOG  reloadURL !! https://www.google.com?__langcd=ko                              <==== reload() press

=====> call reload() nothing show

after click link other page and reload()     l

progress 0.10000000149011612
 LOG  onLoadStart https://www.google.com/history/optout?hl=ko&sa=X&ved=0ahUKEwiA7MmaqqD7AhUOt1YBHfDuD9EQsLsECAU
 LOG  progress 0.23000000417232513
 LOG  progress 0.38999998569488525
 LOG  progress 0.47999998927116394
 LOG  progress 1
 LOG  onLoadEnd url=> https://www.google.com/history/optout?hl=ko&sa=X&ved=0ahUKEwiA7MmaqqD7AhUOt1YBHfDuD9EQsLsECAU
 LOG  progress 1
 LOG  onLoadEnd url=> https://www.google.com/history/optout?hl=ko&sa=X&ved=0ahUKEwiA7MmaqqD7AhUOt1YBHfDuD9EQsLsECAU
 LOG  WebTabScreen tabPress
 LOG  reloadURL !! https://www.google.com?__langcd=ko                                  <==== reload() press
 LOG  WebTabScreen tabPress 2
 LOG  progress 0.10000000149011612
 LOG  onLoadStart https://www.google.com/history/optout?hl=ko&sa=X&ved=0ahUKEwiA7MmaqqD7AhUOt1YBHfDuD9EQsLsECAU
 LOG  progress 0.23000000417232513
 LOG  progress 0.38999998569488525
 LOG  progress 1
 LOG  progress 1
 LOG  onLoadEnd url=> https://www.google.com/history/optout?hl=ko&sa=X&ved=0ahUKEwiA7MmaqqD7AhUOt1YBHfDuD9EQsLsECAU

**Environment:**
 - OS: mac
 - OS version: 12.5.1
 - react-native version: 0.70.5
 - react-native-webview version: 11.23.1

**Comment by kwangjaeyoo** [comment]
I don't think this is the case.
When I build it again, it works fine.

**Comment by tkmin** [comment]
> I don't think this is the case. When I build it again, it works fine.

how did you resolve this issue?
just build an aab file and then distribute again..?
