### ISSUE TITLE
Accessibility: Expose scaling content methods and properties for WKWebView

### ISSUE THREAD

**Issue by kmb64** [react-native-webview/react-native-webview#2737]
Currently, there is no way to increase the text size or zoom content within the react-native-webview on iOS.

Suggestion is to expose the following WKWebView methods via props so a mechanism like the text zoom feature in Safari can be achieved.

WKWebView methods:

<img width="828" alt="Screenshot 2022-11-08 at 10 31 24 pm" src="https://user-images.githubusercontent.com/1438484/200836098-b004f79a-27a3-472c-abcc-8b28b81bdb2f.png">

Text zoom control in Safari:
<img width="406" alt="Screen Shot 2022-10-27 at 12 02 18 pm" src="https://user-images.githubusercontent.com/1438484/200836314-f708e5dc-4e2f-45a1-9c74-fafdfdf53c4d.png">

[Related accessibility discussion](https://github.com/react-native-webview/react-native-webview/discussions/2440)

**Comment by TheAlmightyBob** [comment]
I don't know how the Safari Text Zoom feature is implemented, but we tried messing with `WKWebView`'s `PageZoom` and it does _not_ behave the same.
