### ISSUE TITLE
Cache remove function without incognito

### ISSUE THREAD

**Issue by kvlknctk** [react-native-webview/react-native-webview#2740]
Hi, We need to take advantage of the webview cache feature. Users who have logged in can log in without having to enter a password again. Incognito tab destroys all these features. We need to clear the webview cache when the user logs out of the application.

the incognito tab suggestion is ridiculous in this scenario.

Many developers are having problems with this issue.

https://github.com/react-native-webview/react-native-webview/issues/737
https://github.com/react-native-webview/react-native-webview/issues/2625

**Comment by liaoliao666** [comment]
100% agree this feature request

**Comment by mmkhmk** [comment]
Same here!

**Comment by obernardovieira** [comment]
Here as well

**Comment by KrisLau** [comment]
does the `cacheEnabled` prop not already do this? or do you want to be able to programmatically clear it? https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#cacheenabled'

or do you want to be able to programmatically clear it? They already have that but only for android 
https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#clearcachebool

**Comment by obernardovieira** [comment]
I need to programmatically clear it. Working with iOS as well.

**Comment by rf1804** [comment]
For iOS https://www.npmjs.com/package/react-native-webview-ios-cache-clear
For android https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#clearCachebool

@kvlknctk @mmkhmk @sallesma @17Amir17 @liaoliao666 @obernardovieira @KrisLau
