### ISSUE TITLE
Media stops playing once WebRTC is publishing (iOS)

### ISSUE THREAD

**Issue by tomyates** [react-native-webview/react-native-webview#2741]
We are using the WebView to play a video (which is being used as a texture in a scene we're rendering). 
If we publish audio from a RN component (not the webview), I believe iOS thinks its "on a phone call" and pauses media playback in the webview. 

Is there anyway to prevent the WebView from being "paused"? Am I right in my assumption that this is what is happening?

Order is important - if I create the WebRTC connection first, and then load the webview, then media plays back fine, but unfortunately, if a users WebRTC connection drops, and I have to reconnect them, the webview pauses again.

Any ideas at all would be useful. Thanks!

**Comment by tomyates** [comment]
Just wanted to add some more information - this is not down to WebRTC in particular, it's to with recording from the mic.
So it's when the microphone because active the webview pauses.

**Comment by gregoryalary** [comment]
Hey @tomyates, I know this is super old but do you remember if you ended up finding a workaround for this? Thanks a lot 🙏
