### ISSUE TITLE
i have error while add WebView in my project

### ISSUE THREAD

**Issue by kamrantg** [react-native-webview/react-native-webview#2742]
hi. i have error while add WebView in my project.
import {Text, View} from 'react-native';
import WebView from 'react-native-webview';

export const Home = () => {
    return (
        <View>
            <WebView source={{ uri: 'https://reactnative.dev/' }} />
        </View>
    );
};

my error in my output react native:
react native WebView does not support this platform

**Comment by TheAlmightyBob** [comment]
What platform are you running on?

**Comment by kamrantg** [comment]
android

**Comment by TheAlmightyBob** [comment]
What are the versions of React Native and React Native Webview? Can you share a sample project that reproduces the issue?

That error suggests that React Native does not think that it is running on Android.

**Comment by victor9000** [comment]
I'm getting the same error running on web using `npm run web`

**Comment by lucianohorta** [comment]
Same error for me: "React Native WebView does not support this platform."
I tried to "npx expo install react-native-community/react-native-webview" to no avail. 
Webview is deprecated now in React Native? I'm using Expo.

**Comment by Acetoshi** [comment]
I had this issue and when running npx expo start, i get : 
```
Starting project at [...]
Starting Metro Bundler
The following packages should be updated for best compatibility with the installed expo version:
  react-native-webview@13.12.2 - expected version: 13.8.6
```
