### ISSUE TITLE
Webview in Android 12 is performing really poorly and in some phone's it would crash the app

### ISSUE THREAD

**Issue by MajkellVZ** [react-native-webview/react-native-webview#2744]
**Bug description:**
The app is running really poorly, this is quite noticeable in the scrolling which is really sluggish. Moreover is really hard to navigate on other pages/screens as it is really slow and the app is uses the navigation of the web app no library has been installed for that. Tried all potential solutions suggested in the issues but nothing is working, like `overScrollMode="never"` and opacity set to 0.99 with overflow hidden.

**To Reproduce:**
using an OnePlus or Samsung on Android 12. it's reproducable only in production. it's not possible to reproduce it in the emulators or in devices running through IDE's

**Expected behavior:**
Expect to run as smooth as the web app

**Environment:**
 - OS: Android
 - OS version: 12
 - react-native version: 0.69.7
 - react-native-webview version: 11.16.0

**Comment by kinghoddy** [comment]
I'm having this same issue.
It works fine on google pixel emulator. But not responding to clicks and gestures on physical devices mostly samsung

I'm using it in a functional component

**Comment by eth-jashan** [comment]
@kinghoddy facing the same issue, is there any fix over this ?

**Comment by kinghoddy** [comment]
> @kinghoddy facing the same issue, is there any fix over this ?

@eth-jashan  The only solution I have is to display the webview in a screen not a Modal
