### ISSUE TITLE
Link to LinkedIn opens inside Webview

### ISSUE THREAD

**Issue by ThomasAlexMann** [react-native-webview/react-native-webview#2749]
**Bug description:**
I am using React Native webview to load my website. The website has a similar concept to link tree where you can add links to social medias etc. I want external links to open outside the React Native App In the system.  I have setup my webView like this, google is in the whitelist for ReCAPTCHA.  

```
<WebView
     source={{uri: webViewUri}}
     originWhitelist={[
         'https://www.meelook.com',
         'https://www.google.com',
     ]}
/>
```

There are about 20 social medias you can add at the moment and all open outside the React Native app either in a browser or in the native app for the link e.g. twitter app, reddit app etc

LinkedIn however isn't doing this. 
When I don't have the LinkedIn App installed, clicking a LinkedIn Link opens outside the React Native App in a web browser which is what I want. When I do have the LinkedIn App installed it opens inside the React Native webview. 
This is only a problem for me on android,  iOS is working as desired. 

ALSO - had the same problem with Flickr but this fixed itself randomly. 

**To Reproduce:**
click a LinkedIn Link e.g. "https://www.linkedin.com/in/mee-look-53543a193/" when inside a React Native Webview and you have the LinkedIn App installed. 

Link in the website is just a standard ```<a />``` tag.
```<a href="https://www.linkedin.com/in/mee-look-53543a193/" target="_blank" class="btn btn-meelook my-2">Visit profile</a>```

**Expected behavior:**
It opens the Link in the LinkedIn app. 

**Environment:**
 - Phone: Google Pixel 4 XL
 - OS version: Android 13
 - react-native version: 0.69.0
 - react-native-webview version: 11.23.1

I know this is a bit if a niche problem but any insight would be greatly appreciated.

**Comment by GKyomen** [comment]
Same problem here. Any updates?

**Comment by ThomasAlexanderMann** [comment]
@GKyomen Yes I found a solution. I can't remember where I found the solution.

Add this prop to your webview ```setSupportMultipleWindows={false}```. Without this prop the next part won't work. 

Add a handler for onShouldStartLoadWithRequest to your webview.

 ``` 
onShouldStartLoadWithRequest={
    handleOnShouldStartLoadWithRequest
} 
```

```
 const handleOnShouldStartLoadWithRequest = (event) => {
        if (
            event.url.startsWith('https://www.mysite.com') ||
            event.url.startsWith('https://www.google.com/recaptcha/')
        ) {
            return true;
        } else {
            // open with Linking (external)
            Linking.openURL(event.url);
            return false;
        }
    };
```
