### ISSUE TITLE
Android - capture image from webview

### ISSUE THREAD

**Issue by MiteshJabuani** [react-native-webview/react-native-webview#2750]
"react-native-webview": "^11.23.1",

![issue_webview](https://user-images.githubusercontent.com/34374930/203017470-baa9ae1e-c03e-4945-ae7b-d7930d1e4735.jpeg)

I am getting this error in android while capturing image from webview

Android Manifest file:

-     <uses-permission android:name="android.permission.CAMERA" />
-     <uses-permission android:name="android.permission.INTERNET" />
-     <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
-     <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
-     <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
-     <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
-     <uses-permission android:name="android.permission.RECORD_AUDIO"/>
-     <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
-     <uses-permission android:name="android.permission.VIDEO_CAPTURE" />
-     <uses-permission android:name="android.permission.AUDIO_CAPTURE" />

give this permission and  in webview added these properties

          mediaPlaybackRequiresUserAction={false}
          geolocationEnabled={true}
          mediaCapturePermissionGrantType="grantIfSameHostElsePrompt"
          allowsInlineMediaPlayback
          javaScriptEnabled={true}
          domStorageEnabled

**Comment by TheAlmightyBob** [comment]
Have you implemented logic to request the camera permission?

https://github.com/react-native-webview/react-native-webview/blob/master/docs/Guide.md#camera-option-availability-in-uploading-for-android

**Comment by MiteshJabuani** [comment]
Yes, but not getting any success

**Comment by MiteshJabuani** [comment]
Is anyone? Who has the demo for capturing images from react-native-webview then please share an example here(without expo use).
