### ISSUE TITLE
[android] When relead from standby, webview loading and network speed very slow

### ISSUE THREAD

**Issue by LaDMasC** [react-native-webview/react-native-webview#2752]
I have a react native webview application with next.js in vercel.

When the user presses the home button and opens the application again after a certain period of time, webview reload the page.
in this time, webview loading is very slow, and network speed also. before app force close and reopen.

**Expected behavior:**
first loading, and second loading are both have a same performance

**Environment:**
 - OS: android
 - OS version: 12
 - react-native version: 0.68.1
 - react-native-webview version: 11.18.1

**Comment by TheAlmightyBob** [comment]
This doesn't sound related to react-native-webview? Do you have a minimal repro? Have you inspected the network traffic?

**Comment by minemos** [comment]
same here
