### ISSUE TITLE
Multiple events after 1 postMessage

### ISSUE THREAD

**Issue by albert17** [react-native-webview/react-native-webview#2753]
**Bug description:**
`postMessage` generates multiple events

**To Reproduce:**
https://github.com/react-native-webview/react-native-webview/blob/master/docs/Guide.md#communicating-between-js-and-native

**Expected behavior:**
I would expect `postMessage` to only cause 1 event.

**Screenshots/Videos:**
<img width="226" alt="image" src="https://user-images.githubusercontent.com/14819628/203316810-70c146c1-23c9-49db-a4bf-1234bfab4a32.png">

**Environment:**
 - OS: Windows
 - OS version: 11
 - react-native version: 0.69.3
 - react-native-webview version: 11.22.4

**Comment by TheAlmightyBob** [comment]
Can you share a sample project (or Expo Snack) reproducing the issue?
