### ISSUE TITLE
Change color Vimeo embed

### ISSUE THREAD

**Issue by Ellathet** [react-native-webview/react-native-webview#2754]
In the [@vimeo/playe](https://github.com/vimeo/player.js), we have a function: `setColor("someColor")`. But using the WebView in react-native, the iframe has't no function to change this. Is there a function or a handler to do this in `react-native-webview`?

**To Reproduce:**
```js
  <WebView
    showsHorizontalScrollIndicator={false}
    showsVerticalScrollIndicator={false}
    scrollEnabled={false}
    containerStyle={{ backgroundColor: '#000000' }}
    javaScriptEnabled
    scalesPageToFit={false}
    allowsFullscreenVideo
    source={{
     uri: "https://player.vimeo.com/video/<video-link>"
    }}
    />
```

**Environment:**
 - OS: Android
 - OS version: 12
 - react-native version: 0.62
 - react-native-webview version: 11.2

**Comment by TheAlmightyBob** [comment]
I'm not sure what "iframe" you're referring to, but I'm guessing you'd want to use Javascript injection.

**Comment by Ellathet** [comment]
O sorry, maybe it wasn't so clear, the iframe, is the [embed](https://developer.vimeo.com/player/sdk/basics), available by vimeo itself. I hadn't connected the dots that I could edit through the DOM, I will try and come back with news, may thanks!
