### ISSUE TITLE
in iOS hash signs within provided source.uri are escaped to %23

### ISSUE THREAD

**Issue by tobikl1** [react-native-webview/react-native-webview#2755]
**Bug description:**

When loading a source.uri with query and hash part in iOS the hash sign gets urlEncoded to "%23" before load and then everything after is added to the last queryParam as data.

As on iOS `onShouldStartLoadWithRequest` is fired even on initial load of website i can see in there that event.url has already been changed from `https://dev.example.com/?lang=en#someConfigToBeUsedByWebapp=true` to `https://dev.example.com/?lang=en%23someConfigToBeUsedByWebapp=true`

In my specific case i am trying to call jitsi webview and provide some config to the room being joined like `userInfo.email`. These have to be appended to the url in the form `${JITSI_SERVER}/${roomName}#userInfo.email=${userEmail}&userInfo.avatar=${userAvatarUrl}` and so on.

But in order to change the language within the webview i also have to append the query param `lang=${language}` which gives me a url with both query params and hash portion of the url

**To Reproduce:**
```jsx
<WebView
  source={{uri: 'https://dev.example.com/?lang=en#someConfigToBeUsedByWebapp=true'}}
  onShouldStartLoadWithRequest={(e) => console.log(e.url)}
/>
```

**Expected behavior:**
The url to be loaded in iOS should not have escaped the hash sign.

**Environment:**
 - OS: iOS
 - OS version: 14.5
 - react-native version: 0.67.5
 - react-native-webview version: 11.23.0

**Comment by TheAlmightyBob** [comment]
Have you tried using `decodeURIComponent`?

**Comment by tobikl1** [comment]
I worked around it by injecting the hash parameters in iOS as javascript before load and setting only the url without hash parameters as source.uri

```jsx
const injectedJavascript = useMemo(() => {
    if (Platform.OS === 'ios') {
      return `(function() {
        try {
          location.hash = '${hashParams}'; // hashParams = '#config=value&config2=value2'
          // window.ReactNativeWebView.postMessage(JSON.stringify(window.location));
        } catch(e) {
          window.ReactNativeWebView.postMessage(JSON.stringify({message: e.toString()}));
        }
      })()`;
    }
    return undefined;
  }, [hashParams]);

const source = useMemo<WebViewSource>(() => {
    if (Platform.OS === 'ios') {
      return { uri: baseUrl };
    }
    return { uri: baseUrl + hashParams };
  }, [baseUrl, hashParams]);

return (
    <SafeAreaView style={styles.safeAreaView}>
      <View style={styles.innerContainer}>
        <WebView
          source={source}
          allowsBackForwardNavigationGestures={false}
          allowsInlineMediaPlayback={true}
          injectedJavaScriptBeforeContentLoaded={injectedJavascript}
          mediaCapturePermissionGrantType={'grant'}
          mediaPlaybackRequiresUserAction={false}
          userAgent={userAgent}
          onShouldStartLoadWithRequest={onShouldStartLoadWithRequest}
        />
      </View>
    </SafeAreaView>

```

**Comment by alexfoxy** [comment]
I have also encountered this issue. It seems to only happen if your hash string contains "#" characters.

**Comment by luke358** [comment]
same issue
