### ISSUE TITLE
Capture Audio PlaybackState from WebView

### ISSUE THREAD

**Issue by enzomanuelmangano** [react-native-webview/react-native-webview#2756]
First of all, thank you very much for the work you're doing with this awesome package. 

I wanted to ask if, given the existing functionality of the package it is possible to know if there is a **video/audio** currently playing in the WebView.

**Comment by kumarutsavrobosoft** [comment]
> First of all, thank you very much for the work you're doing with this awesome package.
> 
> I wanted to ask if, given the existing functionality of the package it is possible to know if there is a **video/audio** currently playing in the WebView.

setting this prop mediaPlaybackRequiresUserAction to true helped and it works smoothly now for me.

**Comment by kumarutsavrobosoft** [comment]
mediaPlaybackRequiresUserAction={false} worked for me

> First of all, thank you very much for the work you're doing with this awesome package.
> 
> I wanted to ask if, given the existing functionality of the package it is possible to know if there is a **video/audio** currently playing in the WebView.
mediaPlaybackRequiresUserAction={false} worked for me

**Comment by Lucile-Peltier** [comment]
Hello, I am having the same problem. 
I want to detect audio/video playing from the webview, but cannot find a props that enable me to know that.
