### ISSUE TITLE
[android]Why does it read clipboard every time when I open an app with react-native-webview?

### ISSUE THREAD

**Issue by loz1986** [react-native-webview/react-native-webview#2757]
**Bug description:**

The react-native-webview reads clipboard every time when user opens an app with the WebView component.
Consider user privacy, user will be confused about it. 
Can the reading clipboard feature be disabled? Or read the clipboard unless user operates "copy" and "paste".

Thanks!

**To Reproduce:**

All codes are:
<img width="432" alt="image" src="https://user-images.githubusercontent.com/88711315/203684572-7a309f34-f69f-40b6-b71f-4a94dc1f852e.png">

Copy some text to clipboard from the other app,  and then open the react-native-webview app, then the react-native-webview app will read clipboard.

<img width="340" alt="image" src="https://user-images.githubusercontent.com/88711315/203686583-75056454-d7c1-432b-946b-ae0f9f1a7812.png">

**Expected behavior:**

The app should not read clipboard unless user operate "copy" and "paste".

**Screenshots/Videos:**

As above.

**Environment:**
 - OS: Android
 - OS version: 12
 - react-native version: 0.70.6
 - react-native-webview version: 11.24.0

**Comment by TheAlmightyBob** [comment]
Can you share a repro? I've never seen this before, and the only clipboard-related logic in react-native-webview is if it thinks you're returning from some sort of file picker that was requested by the web content... possibly it's confused in your situation, but hard to be sure without a repro (also I unfortunately don't know what the original use case for that code was and what changing it might break..).

The clipboard logic was introduced in https://github.com/react-native-webview/react-native-webview/pull/60, but none of the lengthy discussion in that PR seems to mention it.

**Comment by loz1986** [comment]
Uploaded to:  https://github.com/loz1986/mockwebview

It was builded from scratch:

`npx react-native init mockwebview`

`npm install --save react-native-webview`

`cd ios`
`pod install`

And then change the content of App.js to:

<img width="431" alt="image" src="https://user-images.githubusercontent.com/88711315/204127846-27208820-6842-4eca-ad81-045b4ad0f86a.png">

Or change to inline HTML as below which is basic example from Getting-Started document(https://github.com/react-native-webview/react-native-webview/blob/master/docs/Getting-Started.md), it does not affect the result.

<img width="439" alt="image" src="https://user-images.githubusercontent.com/88711315/204122552-cd806b20-4a77-43d8-a3b3-358964474e1f.png">

There is no the other codes expect react-native and react-native-webview.  Android device is MIUI 13 of XiaoMi(Android Version is 12) which has clipboard protection feature.  If any app reads clipboard it will be alert warnings.  It seems react-native-webview read the clipboard when the react-native-webview is rendered.

I tried to test react-native-webview@2.9.0 and react-native-webview@2.10.0 (https://github.com/react-native-webview/react-native-webview/pull/60#issuecomment-440619930), but it had some dependency problems. @TheAlmightyBob Do you Know which react-native version should I use to install version 2.x.x of react-native-webview?  Thanks!

**Comment by TheAlmightyBob** [comment]
> Do you Know which react-native version should I use to install version 2.x.x of react-native-webview? Thanks!

I don't... and I could imagine that might get tricky considering how old it is. The `package.json` says React Native `0.57`, so you could try that, but I wouldn't be surprised if there are more dependency issues than just that. I think an easier path would be to edit/debug the code of the latest version (e.g. comment-out the relevant logic in `onActivityResult` or `getSelectedFiles`) to see if that makes the difference.
