### ISSUE TITLE
Getting Permission Error while using react-speech-navigation in react native webview 

### ISSUE THREAD

**Issue by lakshaybansal25** [react-native-webview/react-native-webview#2758]
**Bug description:**

Getting Permission Error while using react-speech-navigation in react native webview 
I am implementing to record audio inside react native webview inside our app.
It works fine in the browser. But when i am using  webview in android app , the app crashes with the error:
Requires MODIFY_AUDIO_SETTINGS and RECORD_AUDIO. No audio device will be available for recording while using audio in react native webview

**To Reproduce:**

Use React Speech Navigation module in react native webview.

**Expected behavior:**

It should work fine

**Screenshots/Videos:**

App crashes  when clicking on Listen Continuously.
<img width="1680" alt="Screen Shot 2022-11-24 at 12 57 24 PM" src="https://user-images.githubusercontent.com/100129072/203719867-5d797ded-01e8-45e4-8f23-030895ec418c.png">

**Environment:**
 - OS: Android 11
 - OS version:Android 11 phone
 - react-native version:
 - react-native-webview version:latest

**Comment by TheAlmightyBob** [comment]
Is your app requesting those permissions?

**Comment by lakshaybansal25** [comment]
Yes, it is requesting those permissions. I have added in AndroidManifest.xml

**Comment by kumarutsavrobosoft** [comment]
mediaPlaybackRequiresUserAction={false} worked for me
