### ISSUE TITLE
RNC WebView is not fabric compatible yeat

### ISSUE THREAD

**Issue by mMarcos208** [react-native-webview/react-native-webview#2759]
**Bug description:**

RNC WebView is not fabric compatible yeat

**To Reproduce:**
set newArchEnabled=true in gradle.properties

```
import React from 'react';
import {View, ActivityIndicator} from 'react-native';
import {detailsStyles} from './detailsStyles';
import {WebView} from 'react-native-webview';
import {colorPalette} from '../../utils/colorPalette';

export const DetailScreen = () => {
  return (
    <View style={detailsStyles.container}>
      <WebView
        scalesPageToFit={false}
        scrollEnabled
        source={{uri: 'https://github.com/mMarcos208/react-native-youtube'}}
        startInLoadingState={true}
        renderLoading={() => (
          <ActivityIndicator size="large" color={colorPalette.silverTree} />
        )}
      />
    </View>
  );
};
```

**Expected behavior:**
show me page

**Screenshots/Videos:**
![Captura de tela de 2022-11-24 11-42-11](https://user-images.githubusercontent.com/14351491/203810904-3025e338-1b8f-4585-9dad-98da97d12b44.png)

**Environment:**
 - OS: ubuntu
 - OS version: 20.04
 - react-native version: 0.70.6
 - react-native-webview version: ^11.24.0

**Comment by TheAlmightyBob** [comment]
@Titozzz is working on it: #2686

**Comment by haithem-rihane** [comment]
I'm facing the same issue
![image](https://user-images.githubusercontent.com/2827416/225323685-c4e5c9e9-87c4-4ed3-b2bc-5bb51d0d5ccf.png)

**Comment by TheAlmightyBob** [comment]
This was auto-closed by the bot but is still in-progress
