### ISSUE TITLE
Html doesn`t work on android device (example LocalPageLoad.tsx)

### ISSUE THREAD

**Issue by JaLe29** [react-native-webview/react-native-webview#2760]
On android device the html rendering doesnt work
```
const html = require('./assets/web/index.html'); 

export default (): any => <WebView source={html} />;
```

Show only html code instead of real html rendering.

```
"react-native-webview": "11.23.0"
```

Example code is your example: https://github.com/react-native-webview/react-native-webview/blob/master/example/examples/LocalPageLoad.tsx

**Comment by TheAlmightyBob** [comment]
This looks like a duplicate of https://github.com/react-native-webview/react-native-webview/issues/428 and https://github.com/react-native-webview/react-native-webview/issues/518, and is documented as "not working" in https://github.com/react-native-webview/react-native-webview/blob/master/docs/Guide.md#loading-local-html-files.

It looks like that example was added for Windows, where I _assume_ the feature does work...

**Comment by JaLe29** [comment]
But are there any plans for a fix?

**Comment by TheAlmightyBob** [comment]
Not that I'm aware of, but we're always open to pull requests. There also appear to be a couple suggested workarounds in those links.
