### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by silviomedice** [react-native-webview/react-native-webview#2763]
**Bug description:**
When I try to compile i am getting those erros. 
Can you guys help me ?

node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java:725: error: method does not override or implement a method from a supertype
  @Override
  ^

node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java:785: error: incompatible types: String cannot be converted to int
    super.receiveCommand(root, commandId, args);

   ext {
        buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
    }

**Environment:**
 - OS: Ubuntu 
 - OS version: 20.04.1
 - react-native version: 0.60.6
 - react-native-webview version: 11.23.1

**Comment by TheAlmightyBob** [comment]
I believe `react-native-webview` `11.22.0+` requires at least React Native version `0.61.0`. Please try upgrading React Native or downgrading React Native Webview.
