### ISSUE TITLE
Webview PDF reader with `window.print()`

### ISSUE THREAD

**Issue by GabrielGomesBarbosa** [react-native-webview/react-native-webview#2764]
**Bug description:**
Webview is not open a PDF reader like android chrome browser, i showing a page which contains a `window.print()` inside that, and when i press in the print button, nothing happens.

**To Reproduce:**
Show a page that contains `window.print()` function inside the browser and show it on the webview, when press it not happens.

**Expected behavior:**
Open the PDF reader default from browser.

**Screenshots/Videos:**
Example working version from Chrome Browser:

Page Button (Imprimir):

<img src="https://user-images.githubusercontent.com/37483241/204377118-e651ed4e-855d-4e7d-b5d9-5b507aca6606.jpg" width="200" />

PDF Reader:

<img src="https://user-images.githubusercontent.com/37483241/204377256-42bf49b8-6f16-48df-943f-17b5f59fe7dc.jpg" width="200" />
<img src="https://user-images.githubusercontent.com/37483241/204377272-eb8b0bd9-bc6a-49f7-943a-b497af5c11ed.jpg" width="200" />

**Environment:**
 - OS: Windows
 - OS version: 8
 - react-native version: 0.70.6
 - react-native-webview version: 11.25.0

**Comment by GabrielGomesBarbosa** [comment]
Can someone please help me, how can i open this PDF Reader ?

**Comment by TheAlmightyBob** [comment]
Please see https://github.com/react-native-webview/react-native-webview/issues/2660#issuecomment-1236601706
