### ISSUE TITLE
Android: Application attempted to call on a destroyed WebView

### ISSUE THREAD

**Issue by andreialecu** [react-native-webview/react-native-webview#2769]
**Bug description:**

<img width="1193" alt="Screenshot 2022-12-03 at 13 00 54" src="https://user-images.githubusercontent.com/697707/205437542-3cdac0a2-0c15-441d-a237-c996aa665b5c.png">

**To Reproduce:**

It appears that there can be a race condition when a WebView is disposed of, and a `postMessage` comes in shortly after.

In particular, if the webview is nested inside a Reanimated Animated.View, it appears that Reanimated for some reason disposes the webview on mount, then remounts it. 

This can result in this stack trace:
<img width="767" alt="Screenshot 2022-12-03 at 13 05 14" src="https://user-images.githubusercontent.com/697707/205437723-c4502a82-6d67-4fcb-97bb-a62b06d6579e.png">

Notice how Reanimated calls dropView.

A message still goes through the `onMessage` handler shortly after, logging the warning above, and we also get some `useEffect` warnings about changing state after the component dismounted from the app.

I believe the issue is related to this line:
https://github.com/react-native-webview/react-native-webview/blob/0817524326a882107ed1994d3861212b382f054d/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java#L1803

Not properly nulling out `mRNCWebViewClient` here because of the `if`:
https://github.com/react-native-webview/react-native-webview/blob/0817524326a882107ed1994d3861212b382f054d/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java#L1623-L1629

I'll follow up with a PR to fix this shortly.

**Expected behavior:**

No warning and proper disposal.

**Screenshots/Videos:**

**Environment:**
 - OS:
 - OS version:
 - react-native version:
 - react-native-webview version: 11.25.0

**Comment by andreialecu** [comment]
I've been also seeing random blank webviews on Android, and I believe this also fixes that issue. 🤔 

Originally reported in #2683

**Comment by solitarysp** [comment]
@andreialecu Is there a good solution yet?
