### ISSUE TITLE
Actively maintained?

### ISSUE THREAD

**Issue by amilich** [react-native-webview/react-native-webview#2773]
Hey all - do we need new maintainers for this project?

We've been working with https://github.com/react-native-webview/react-native-webview/pull/2733 for a while now, and would love for it to get merged. Not even sure how we can solicit feedback or run tests.

**Comment by TheAlmightyBob** [comment]
It's semi-actively maintained. It's a big project and I think help would be welcome. I've been reviewing/merging other PRs, but admit I didn't look at yours because I don't know anything about the MacOS (or Windows) side of things...

**Comment by amilich** [comment]
Got it, thank you! I've found a bunch of issues on this topic so hopefully we can get it sorted. Let me know if we can find anyone else who might be able to contribute.
