### ISSUE TITLE
How to test Webview with react-native-testing-library?

### ISSUE THREAD

**Issue by udaisshekhawat** [react-native-webview/react-native-webview#2775]
### Discussed in https://github.com/react-native-webview/react-native-webview/discussions/2689

<div type='discussions-op-text'>

<sup>Originally posted by **fabiendem** September 29, 2022</sup>
Hello,

I am struggling to find good examples of tests while using the `react-native-webview` and  `react-native-testing-library` under jest.

How do you usually test components which render a webview? Especially, how do you simulate the successful loading of the webpage in the context of the test renderer?

Thanks!</div>

**Comment by TheAlmightyBob** [comment]
Depends what exactly you're trying to do. I don't have time to put together a full example (though that's not a bad idea for a documentation addition), but to "simulate the successful loading" I'd think that you could use `react-native-testing-library`'s `fireEvent` to simulate `onLoadEnd`.

**Comment by udaisshekhawat** [comment]
Thanks for your reply @TheAlmightyBob 

Actually,  I am looking for some tests using @testing-library/react-native, such as validation onNavigationStateChange.

When I try to print the screen.debug(), the onNavigationStateChange is missing. It will be great if you can guide on this.

Thanks

**Comment by TheAlmightyBob** [comment]
I would need to see an example. It's still not clear to me what you're trying to do.

**Comment by Praveen-CP** [comment]
@udaisshekhawat have you found any solution here?
