### ISSUE TITLE
Error evaluating injectedJavaScript: This is possibly due to an unsupported return type. Try adding true to the end of your injectedJavaScript string.

### ISSUE THREAD

**Issue by Eredoqo** [react-native-webview/react-native-webview#2778]
Hi, i am having issue with react native vebview while inject JavaScript, tried to lower or upgrade version but same error, in Android the inject JavaScript works fine.

Error evaluating injectedJavaScript: This is possibly due to an unsupported return type. Try adding true to the end of your injectedJavaScript string. Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={WKJavaScriptExceptionLineNumber=2, WKJavaScriptExceptionMessage=SyntaxError: Unexpected identifier 'Object'. Expected either a closing ']' or a ',' following an array element., WKJavaScriptExceptionColumnNumber=0, WKJavaScriptExceptionSourceURL=http://localhost:8081/assets/assets/widget/widget.html?platform=ios&hash=815212bdd93227914de6d10265637aa5, NSLocalizedDescription=A JavaScript exception occurred}

The bug is consistent of not loading webView in IOS 16.1 when i upgrade from 15.

To Reproduce:
--------------
async function initAppAsync(online) {
  await Promise.all([
    console.log("---- START LOADING ----"),
    DB.init(),
    fetchKpiDictionary(online),
    Asset.loadAsync(require("./assets/widget/widget.html")),
    Font.loadAsync({
      // This is the font that we are using for our tab bar
      ...Ionicons.font,
      // We include SpaceMono because we use it in HomeScreen.js. Feel
      // remove this if you are not using it in your app
      "space-mono": require("./assets/fonts/SpaceMono-Regular.ttf"),
      "roboto-regular": require("./assets/fonts/Roboto-Regular.ttf"),
      "roboto-medium": require("./assets/fonts/Roboto-Medium.ttf"),
      cairo: require("./assets/fonts/Cairo-SemiBold.ttf"),
      "roboto-italic": require("./assets/fonts/Roboto-Italic.ttf"),
      "roboto-bold": require("./assets/fonts/Roboto-Bold.ttf")
    }),
    console.log("---- FINISH LOADIN ----")
  ]);
}
------

**Environment:**
 - OS: IOS
 - OS version: IOS 16.1
 - react-native version: 0.67.3
 - react-native-webview version: 11.17.1

**Comment by TheAlmightyBob** [comment]
Is the code in the "to reproduce" section the script that you are trying to inject?

I recommend using the Safari dev tools if you haven't already... can sometimes help pinpoint injected javascript errors. Although if it's really just one giant `Promise.all` call it might struggle... would probably be worth breaking that apart for debugging, commenting out bits to try to narrow down the offending portion, etc.
