### ISSUE TITLE
postMessage from webViewRef not working on android

### ISSUE THREAD

**Issue by bmeeder22** [react-native-webview/react-native-webview#2779]
**Bug description:**
When calling `WebViewRef.current.postMessage(message);` on android the message is not sent to the website running in the WebView. This works on IOS. 

**To Reproduce:**
Create a website that listens for `window.onMessage`

**Expected behavior:**
That postMessage sends a message to the WebView the same on both IOS and Android

**Environment:**
 - OS: Android
 - OS version: Android 15
 - react-native version: `66.5.0`
 - react-native-webview version: `11.16.0`

I have tried the solutions presented in Issue #356

Incuding:
- Using `document` instead of `window`
- Using `window.addEventListener('message', onMessage, true)`

Here is our current website code: 
```
window.addEventListener('message', handleReceivedMessage, true);
document.addEventListener('message', event =>
  handleReceivedMessage(event)
);
```

Neither of these events are firing when calling `WebViewRef.current.postMessage(message);` in our react native app

**Comment by mohitarora777** [comment]
@bmeeder22 why u closed this ? Did u find the exact issue ?

**Comment by nullCode666** [comment]
why close this？

**Comment by utyfua** [comment]
I did encounter it a while ago and I am using `WebViewRef.current.injectJavaScript` to bypass the issue.

[My implementation](https://github.com/utyfua/ipc-bus-promise-ts/blob/b4e4c7deccdb6c9a1f7b3ada63ae60aa1a6e3880/src/transports/reactNative/webView.ts#L26).

**Comment by utyfua** [comment]
@trajano I believe its [`targetOrigin`](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage#targetorigin)

**Comment by trajano** [comment]
Ah so it's a web standard method https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage

**Comment by utyfua** [comment]
@trajano Typically, you need to handle specific responses for specific requests. The key distinction in my approach is that I provide a layer enabling the use of async/await to manage responses from the other side. Initially, this started with handling Node.js child processes as part of [pool-manager](https://github.com/utyfua/pool-manager-ts). However, when tasked with porting a few mobile apps, I decided to abstract the logic into a separate package. Unfortunately, the documentation is quite limited, but it serves its purpose for me.

**Comment by trajano** [comment]
yeah taking some inspiration from yours I may do it later, but instead of me managing the WebView as part of the whole, I was going to just pass in a ref to a WebView but still keep my IpcWebView API in place for the most part.  I liked how you used event emitter API as well as in my case I don't abstract that yet.
