### ISSUE TITLE
contentMode doesn't work on iPad running iOS 16

### ISSUE THREAD

**Issue by aknad** [react-native-webview/react-native-webview#2781]
**Bug description:**
I'm using [contentMode="mobile"](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#contentMode) to force mobile content on iPad and show fullscreen videos that with the desktop interface it's not possible to do
It works fine on iPad with iOS 14.5 but with iOS 16 it stopped to work (not tested on iOS 15)
I also forced an user agent but it doesn't work

**Expected behavior:**
with this option iPad should shows the mobile interface and it's possibile to use fullscreen mode with videos

**Screenshots:**
iOS 14.5
![ios14](https://user-images.githubusercontent.com/7056879/207913306-944e3f2d-5627-4922-8b81-b76f84951985.jpg)

iOS 16.1
![ios16](https://user-images.githubusercontent.com/7056879/207913345-9d498ea3-bd99-407b-b9cc-c61092acfb81.jpg)

**Environment:**
 - OS: iOS
 - OS version: 16.1
 - react-native version: 0.67.5
 - react-native-webview version: 11.26.0

**Comment by TheAlmightyBob** [comment]
The `contentMode` prop is still "working" in that it's still being applied correctly by `react-native-webview`, and I see it changing behavior on iOS 16.1.

I'm not familiar with your full-screen video scenario. It seems most likely to me that Apple has simply changed the behavior such that `contentMode` no longer does what you want in that particular case, and there may not be anything that `react-native-webview` can do about it...
