### ISSUE TITLE
UI elements not responding to user inputs on iOS

### ISSUE THREAD

**Issue by Konntroll** [react-native-webview/react-native-webview#2783]
I'm loading a page with some input fields and buttons but on iOS:

- Tapping in any input field doesn’t cause the cursor to appear or the keyboard to show.
- Tapping any buttons in the UI, except for text editor buttons, has no effect, although the buttons register the interaction, i.e. their colour changes.
- Tapping the text editor buttons works, and doing so causes the cursor to appear in the associated textarea and the keyboard to show. This lets me enter / edit text in that textarea, but all the other UI elements remain unresponsive as before.

The same works fine on Android.

I don't know what causes the issue, much less how to reproduce it outside of my application, so I don't quite expect a solution but rather ideas as to what could be the cause because I'm out of those.

**Comment by TheAlmightyBob** [comment]
That sounds weird and I have no thoughts on what the problem is, but in terms of generally debugging things like this, my thoughts are (maybe you've already tried):
1. is this a page you can load in Safari, rather than in your WebView?
2. Have you tried attaching the Safari DevTools?

**Comment by Konntroll** [comment]
I did try it in Safari and it works fine there. I also fiddled with Safari DevTools for some time. What I discovered so far is that reloading the page there fixes the problem. Not sure why.

**Comment by TheAlmightyBob** [comment]
> What I discovered so far is that reloading the page there fixes the problem

Does reloading via `react-native-webview` help? Does _deferring_ the load (i.e. initially configure the WebView with just "about:blank" or something and then switch to your desired content) help?

**Comment by Konntroll** [comment]
This ended up being a non-issue after all. In my endless briliance, I tried the form I have in Safari on a Mac instead of in iOS. Sure enough, in iOS not only Safari but also Chrome had the same problem, so the matter had nothing to do with the webview.

For posterity: If you've encountered a similar problem, check if you are altering the height of your inputs somehow. Especially if you are doing so in a hook that runs repeatedly. That was the root of it in my case.
