### ISSUE TITLE
Execution failed for task ':react-native-webview:compileDebugKotlin'.

### ISSUE THREAD

**Issue by AhmadAl-Ghalban** [react-native-webview/react-native-webview#2784]
**Bug description:**
when run app in android return this error Execution failed for task ':react-native-webview:compileDebugKotlin'.

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS:mac os
 - OS version:12.6
 - react-native version:64.0
 - react-native-webview version:11.26.0

**Comment by TheAlmightyBob** [comment]
Can you provide the full build log and a sample app that reproduces the issue?

**Comment by czjdrj** [comment]
I have the same problem......


Environment:
"react-native-webview": "^11.2.4"
"react-native": "0.63.4"


when run app in android return the same error:
Task :react-native-webview:compileDebugKotlin FAILED
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
......

**Comment by TheAlmightyBob** [comment]
@czjdrj Same question as above.

**Comment by marwan2** [comment]
Same issue also: Task :react-native-webview:compileDebugKotlin FAILED

**Comment by TheAlmightyBob** [comment]
@marwan2 Same question as above.
