### ISSUE TITLE
onLoadStart event is returning page url instead of page title

### ISSUE THREAD

**Issue by micpob** [react-native-webview/react-native-webview#2793]
**Bug description:**
As per [documentation](url), onLoadStart returns a SyntheticEvent wrapping a nativeEvent with these properties:
canGoBack
canGoForward
loading
target
title
url

But the title returned is the page url (which is already returned in the url field), not the page title.

**Expected behavior:**
the method should return the webpage title

**Screenshots/Videos:**

**Environment:**
 - OS: Windows
 - OS version: 11
 - react-native version: 0.69.6
 - react-native-webview version: 11.23.0

**Comment by TheAlmightyBob** [comment]
I think the documentation just needs to be updated. It makes sense that the WebView wouldn't know the page title before loading the page... though I'm somewhat curious if there's any difference between platforms. You only tested on Windows?

**Comment by micpob** [comment]
I tested it while using an Android phone and Expo on Windows.
Also onLoadProgress has a similar behaviour: when it fires the title value is empty, then it gets filled with the page url and finally with the proper page title.
I think it would be better if the title value stays empty until available, to fill it with the url value and then change it seem like a behaviour prone to generate issues.

**Comment by TheAlmightyBob** [comment]
> I think it would be better if the title value stays empty until available

This is why I said I was curious if there is a difference between platforms. `react-native-webview` does not have logic to return the URL instead of the page title, so if that's the behavior you are seeing then that's how the native WebView on the platform you're testing with behaves. It's possible that some platforms do return empty strings... I'm not sure.
