### ISSUE TITLE
Embedded WebBrowser just like expo's

### ISSUE THREAD

**Issue by SupriyaPKalghatgi** [react-native-webview/react-native-webview#2794]
I have local html file to be rendered in an embedded webview
I was looking for the same look and feel as that of Expo's WebBrowser

https://user-images.githubusercontent.com/95462949/210719844-01b4f121-29bd-4e87-a142-71ef8953e10b.mp4

**Comment by TheAlmightyBob** [comment]
@SupriyaPKalghatgi I think you want this project instead: https://github.com/proyecto26/react-native-inappbrowser

**Comment by SupriyaPKalghatgi** [comment]
@TheAlmightyBob Forgot to mention that, my project is purely Expo

**Comment by TheAlmightyBob** [comment]
@SupriyaPKalghatgi Ah, I missed that it's a local file. Then I think you'll need to build an equivalent of that screen yourself using your preferred navigation framework (I assume React Navigation).

Such a UI is outside the scope of this library. The API is there so you can implement forward/back buttons... unfortunately I don't know of a way to implement the text zoom control. And of course native Android has a different UI, dunno if that would be a concern.

**Comment by SupriyaPKalghatgi** [comment]
@TheAlmightyBob I got this working with react navigation's `modal` presentation
https://reactnavigation.org/docs/modal
