### ISSUE TITLE
[QUESTION] How to share user session in React Native App and WebView component

### ISSUE THREAD

**Issue by karel-suchomel-ed** [react-native-webview/react-native-webview#2796]
I have an application that shares the backend with the web. This application has basic email/password login that returns Access Token which is sent as a header for any other requests. The application also has a screen that is a WebView which displays the web version of this app.

My problem is that I don't know how to share user session between the RN app and the WebView. When the user logs in to the application it should also log him into the WebView page and if the user logs out it should log him out of the WebView as well.

Can we inform the WebView that the user has logged in and that he should be logged in to the WebView as well?

I tried sending the Authorization header in the WebView source but it doesn't work. [https://github.com/react-native-webview/react-native-webview/blob/master/docs/Guide.md#working-with-custom-headers-sessions-and-cookies](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Guide.md#working-with-custom-headers-sessions-and-cookies)

**Comment by TheAlmightyBob** [comment]
I think this will vary by application, how such things are being managed... in general it sounds like you're thinking along the right lines. Is the header all that is needed, or are there also cookies? You might try using something like Fiddler to verify that the headers are being sent as you expect.

**Comment by karel-suchomel-ed** [comment]
I figured that the session is meant to work with Cookies. Currently, I'm having an issue with updating the PHPSESSID cookie to the new token value. It seems, that if the Cookie already exists its value cannot be updated.
