### ISSUE TITLE
Websockets do not work in WebView - iOS and Android

### ISSUE THREAD

**Issue by maison-shibumi** [react-native-webview/react-native-webview#2798]
**Bug description:**
Websockets do not appear to work in WebView. When I access my application from the desktop browser (the app `WebView` is pointed at), Websockets connect and work fine. However, they do not respond or connect when you are accessing that same app from just the RN `WebView`.  You can set up a socket natively, but the application is not native, it is only connected through the `WebView`.  

Is there any documentation in `react-native-webview` that even speaks to this? I don't remember anything about it when initially looking at the docs, and going back to do a quick page search on these docs: [React Native WebView Guide](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Guide.md) shows no mention of 'websockets, websocket, socket' etc. 

Anyone else run into this? And if so - what was your solution? It seems I might have to implement the socket service natively, and then pipe its response through the `WebView` messaging system, to our app within the `WebView`. 

**To Reproduce:**
Connect to your web app via `WebView`. If your web app relies on Websockets, they will not work inside of RN `WebView`. 

**Expected behavior:**
Websockets work from within a `WebView`.

**Screenshots/Videos:**

**Environment:**
 - OS: MacOS
 - OS version: Monterrey
 - react-native version: `0.69.6`
 - react-native-webview version: `11.23.0`

**Comment by TheAlmightyBob** [comment]
What platform(s) are you testing on?

**Comment by lorsk** [comment]
+1 on this. I am running  

"react": "18.2.0",
"react-native": "0.71.3",

Not working on Android

**Comment by maison-shibumi** [comment]
> What platform(s) are you testing on?

Hi there, sorry to respond so late - I am just getting back to this issue. I am testing on both iOS and Android. Having trouble still. The sockets work in the mobile browser, but in the native app via `WebView` I am still seeing socket issues. Nothing in the web app that relies on socket services work.

**Comment by maison-shibumi** [comment]
> +1 on this. I am running
> 
> "react": "18.2.0", "react-native": "0.71.3",
> 
> Websockets not working on Android. Same web app works in the chrome browser on the android device

Any headway on this problem? It is both iOS and Android for my problem.

**Comment by TheAlmightyBob** [comment]
Sorry, I don't really know anything about this. I just asked about platform because it sounded like the sort of issue that might be platform-specific.

**Comment by arindambiswas1** [comment]
> > +1 on this. I am running
> > "react": "18.2.0", "react-native": "0.71.3",
> > Websockets not working on Android. Same web app works in the chrome browser on the android device
> 
> @lorsk Any headway on your problem? It is both iOS and Android for me. I am not sure what to do at this point - it seems to be an underlying issue with `WebView`. The socket service my app uses works completely fine in a mobile or desktop web browser. My only thoughts are to duplicate the socket services over into React Native... but that would be an utter PITA.

did you find any workaround?

**Comment by Sharath-Dimaag** [comment]
@lorsk @arindambiswas1 Did you guys get the fix for this? I badly need sockets to be working inside the webview.

**Comment by jibinbajuMTN** [comment]
The same issue is happening for me as well, and it’s still not working. Could you please reopen the request/ticket and resolve this as soon as possible? Thank you!
