### ISSUE TITLE
RNCWebView.isFileUploadSupported Error on Expo EAS Android Build SDK 47

### ISSUE THREAD

**Issue by jdpagley** [react-native-webview/react-native-webview#2804]
Hello everyone! I apologize if this is not the correct place to post this bug. I wasn't sure where to report it. If there is a better place to post this please let me know :).. Thanks for any help!

**Bug description:**

The Expo Supported version of this package `11.23.1` is throwing an error and not moving past the splash screen. This started happening after upgrading from Expo SDK 45 to Expo SDK 47. on EAS Android Build.

This module works just fine in Expo Go but when I load my app in the actual Android build I get the error below:
```
  TypeError: null is not an object (evaluating '_reactNative.NativeModules.RNCWebView.isFileUploadSupported')
```

**To Reproduce:**

**Step 1:** Run `npx create-expo-app my-app` and `cd my-app` (sdk 47)
**Step 2:** Install react-native-webview `npx expo install react-native-webview`. Yarn is used as the package manager.
**Step 2:**  Add WebView like the example below to the main App.js file: 
```
import * as React from 'react';
import { WebView } from 'react-native-webview';

export default function App() {
  return (
    <WebView
      style={{width: 100, height: 100}}
      source={{ uri: 'https://expo.dev' }}
    />
  );
}
```
**Step 3:** Create EAS Android  (I recommend using the following in your EAS profile: `{ "developmentClient": true, "distribution": "internal" }`. This will make it easier to see the error message.)

**Step 4:** (If using developmentClient build) Start expo locally `npx expo start` and open in Android Build. (NOTE: react-native-webview works fine in Expo Go, it only throws the error when loading it in an actual build.)

**Expected behavior:**

App should load past the splash screen.

**Screenshots/Videos:**

The following error happened after loading my app in the Android Build
<img width="2730" alt="image" src="https://user-images.githubusercontent.com/4016177/211800170-1ba75e89-57d8-4b83-ae04-47ceb7b2ed34.png">

**Environment:**
 - OS: Mac
 - OS version: 12.5
 - react-native version: 0.70.5
 - react-native-webview version: 11.23.1
 - Expo CLI Version: 0.4.11
 - EAS CLI Version: 3.2.1
 - Node Version: 14.21.0
 - Yarn Version: 1.22.19

**Comment by TheAlmightyBob** [comment]
Have you already looked at #2648?

**Comment by jdpagley** [comment]
@TheAlmightyBob Yeah I did take a look at that issue. I didn't have multiple versions. I was actually able to resolve it by upgrading my node and npx version.

I had another developer from the community go through the same steps to reproduce but it worked for them. I guessed it had something to do with my environment and not the module. This caused me to look into what version of node, npx, yarn, etc. so I moved to Node v18+ (I was previously on Node 14) and that upgraded me to NPX v8.19.2. After that I went through the same steps it worked!!!

I concluded that it was an issue with my environment, even though I don't understand exactly why.

**Comment by vickz84259** [comment]
To anyone else who comes across this issue, the conclusion I've arrived at is that there's an issue with Expo's autolinking. For the company I work for, our library depends on `react-native-webview`. So our users have it as a transitive dependency. [Expo should autolink transitive dependencies](https://docs.expo.dev/modules/autolinking/#how-is-it-different-from-react-native-autolinking). However this does not seem to be the case when making release builds.

Builds made with: `eas build --platform android` or `npx expo run:android --variant release` would all crash with the above error showing up in logcat. However in our case, after running: `npx expo install react-native-webview` in order to have it as a direct dependency, everything worked just fine.
