### ISSUE TITLE
goBack() doesn't work as expected on Android

### ISSUE THREAD

**Issue by Tamimjabr** [react-native-webview/react-native-webview#2810]
**Bug description:**

goBack() doesn't work as expected on Android. it works perfectly on iOS but not on Android. The webview is just not responding for goBack

**To Reproduce:**

use react-native-webview v11.26.0 and Android device. Try to goBack after your first navigation (it works sometimes when you have navigated many times between pages)

Notice that it works perfectly on react-native-webview v11.18.1 but this version is not compatible with RN  v0.70.6 therefore I am stuck with an old RN version to get this functionality 

**Environment:**
 - OS: Mac
 - OS version: 13.1 (22C65)
 - react-native version: v0.70.6
 - react-native-webview version: v11.26.0

**Comment by TheAlmightyBob** [comment]
> it works perfectly on react-native-webview v11.18.1

Does that mean it broke with 11.18.2? Or are the two versions you mention the only ones you tested?

**Comment by Tamimjabr** [comment]
I only tested those two versions

**Comment by TheAlmightyBob** [comment]
I'm unable to repro this issue using the sample app. If you could provide a repro (e.g. Expo Snack) that would be helpful. If you could narrow down in which version you're seeing a regression, that would also be helpful. 11.22.0 might be a reasonable starting point, as I know there were some breaking changes there.

The sample app didn't already have a demo for this, but I just quickly threw in this code to test it, which worked as expected on iOS & Android:

```jsx
type Props = {};

export default class Messaging extends Component<Props> {
  constructor(props) {
    super(props);
    this.webView = React.createRef();
  }

  private handleLoadEnd = (eventData) => {
    console.log(eventData.nativeEvent);
  };

  private goBack = () => {
    this.webView.current.goBack();
  };

  render() {
    return (
      <View style={{ flex: 1 }}>
        <Button title="back" onPress={this.goBack} />
        <WebView
          ref={this.webView}
          source={{ uri: 'https://infinite.red' }}
          onLoadEnd={this.handleLoadEnd}
        />
      </View>
    );
  }
}
```

The console log of the load event is to see whether `canGoBack` is `true` or `false`, which might be worth paying attention to in your case to see if that property is being set as expected.

**Comment by Tamimjabr** [comment]
Thank you for your answer. I will try to submit a public repo to reproduce the error because the one I am working on is a private one.

do you know which is the lowest version that is compatible with RN v0.70.6?

**Comment by TheAlmightyBob** [comment]
I'm unaware of there having been previous incompatibility or what might have changed in that compatibility.

**Comment by davilico05** [comment]
goBack() on Android isn't working to me either

https://github.com/react-native-webview/react-native-webview/issues/2631#issuecomment-1378391751

**Comment by TheAlmightyBob** [comment]
@davilico05 As I said above, a repro project would help (and/or try debugging it? e.g. is `receiveCommand` in `RNCWebViewManager.java` being invoked?).

Since both of you are using React Native 0.70.6 and the example project is still on 0.68 (for now), I tried spinning up a brand new React Native 0.70.6 project and simply replacing the App component with

```jsx
const App: () => Node = () => {
  const webViewRef = React.useRef();

  const goBack = () => {
    webViewRef.current.goBack();
  };

  return (
    <View style={{flex: 1}}>
      <Button title="Back" onPress={goBack} />
      <WebView
        ref={webViewRef}
        source={{uri: 'https://infinite.red'}}
      />
    </View>
  );
};
```

But `goBack` still worked as expected on Android 10 & 12 emulators.

**Comment by grigorigoldman** [comment]
Hey @TheAlmightyBob I could not reproduce this issue on an emulator but on a physical Android device (I'm using Samsung Galaxy S20 Ultra), it is produceable.

**Comment by TheAlmightyBob** [comment]
Just tried on a Galaxy S10. `goBack` still worked.

**Comment by ollie37** [comment]
> @davilico05 As I said above, a repro project would help (and/or try debugging it? e.g. is `receiveCommand` in `RNCWebViewManager.java` being invoked?).
> 
> Since both of you are using React Native 0.70.6 and the example project is still on 0.68 (for now), I tried spinning up a brand new React Native 0.70.6 project and simply replacing the App component with
> 
> ```js
> const App: () => Node = () => {
>   const webViewRef = React.useRef();
> 
>   const goBack = () => {
>     webViewRef.current.goBack();
>   };
> 
>   return (
>     <View style={{flex: 1}}>
>       <Button title="Back" onPress={goBack} />
>       <WebView
>         ref={webViewRef}
>         source={{uri: 'https://infinite.red'}}
>       />
>     </View>
>   );
> };
> ```
> 
> But `goBack` still worked as expected on Android 10 & 12 emulators.

please can I get your full code

**Comment by TheAlmightyBob** [comment]
I suppose I _could_ publish the repo if you _really_ want, but it was really just:
1. `npx react-native init GoBackTest --version 0.70.6`
2. `yarn add react-native-webview`
3. Paste the code above into `App.js`
4. `npx react-native run-android`

That was it, no other changes. (well, other than obvious things like adding an import for the WebView)

**Comment by ollie37** [comment]
> I suppose I _could_ publish the repo if you _really_ want, but it was really just:
> 
> 1. `npx react-native init GoBackTest --version 0.70.6`
> 2. `yarn add react-native-webview`
> 3. Paste the code above into `App.js`
> 4. `npx react-native run-android`
> 
> That was it, no other changes. (well, other than obvious things like adding an import for the WebView)

please do a repo

**Comment by TheAlmightyBob** [comment]
@ollie37 The code you shared never invokes `goBack` (i.e. you're missing the button from my example)... I assume that was just a copy/paste error?

**Comment by ollie37** [comment]
> @ollie37 The code you shared never invokes `goBack` (i.e. you're missing the button from my example)... I assume that was just a copy/paste error?

import * as React from 'react';
import { WebView } from 'react-native-webview';
import { StyleSheet } from 'react-native';
import Constants from 'expo-constants';

const App: () => Node = () => {
  const webViewRef = React.useRef();

  const goBack = () => {
    webViewRef.current.goBack();
  };

  return (
    <View style={{flex: 1}}>
      <Button title="Back" onPress={goBack} />
      <WebView
        ref={webViewRef}
        source={{uri: 'https://infinite.red'}}
      />
    </View>
  );
};
export default App

@TheAlmightyBob  this is still not working, can you just do a snack.expo.dev and let me see please. I will appreciate that

**Comment by TheAlmightyBob** [comment]
@ollie37 Your last message is the same exact code again which never calls `goBack`...?

> can you just do a snack.expo.dev and let me see please.

Here you go: https://snack.expo.dev/46Nfdhh0N

**Comment by ollie37** [comment]
> @ollie37 Your last message is the same exact code again which never calls `goBack`...?
> 
> > can you just do a snack.expo.dev and let me see please.
> 
> Here you go: https://snack.expo.dev/46Nfdhh0N

@TheAlmightyBob thank you

**Comment by MRAOmio** [comment]
Hello folks! We are having the same issue. As someone mentioned, ref.current.goBack works fine on iOS and my Android emulator (nexus 5x Android 10 arm64-v8a) but it does not work on my testing device (google pixel 2, android 11). My app is using ` "react-native-webview": "11.22.7"` and  `"react-native": "0.66.4". `

While debugging, I can see that `webviewref.current.goBack` does exist (I thought it might just not be there) but executing it does nothing. In our implementation we have a simple logic to decide if we want to navigate within the webview or away from it into a new native activity, but I don't think that is related to this at all, since on iOS the same code works perfectly. A simplified example of our usage:
```
const webviewPage = () => {
  // this array gets items when you navigate forward within the webview
  const navigationStack = [];

  const goBack = () => {
    navigationStack.pop();

    if (navigationStack.length === 0) {
      // navigate away from this page into a new native activity
    } else {
      webViewRef.current?.goBack();
    }
  };
  return (
    <>
      <MobileHeader handleBackClick={goBack} />
      <WebView ref={webViewRef} />
    </>
  );
};
```

**Comment by TheAlmightyBob** [comment]
@MRAOmio As I've said in previous messages, you might check if `canGoBack` is true in navigation events, and whether the native Android code is being invoked (via `receiveCommand`)

(and in your particular example, `canGoBack` might eliminate the need to keep your own `navigationStack... unless you have other reasons for tracking that)

**Comment by MRAOmio** [comment]
Hi @TheAlmightyBob thanks for answering so quickly. I checked, accessing `canGoBack` through `onNavigationStateChange` and that function only gets invoked when I load the webview the first time (and `canGoBack = false`). When i navigate forward it doesn't get invoked again. 

I was thinking it could have to do with the way we do navigation? Again, it'd be strange that it works for iOS/Android emulators and not for Android devices, since the web rendered within the webview is the same. But how does this `onNavigationStateChange` work? What is it listening to?

**Comment by TheAlmightyBob** [comment]
I don't know how `onNavigationStateChange` works (I've never used it... I use `onShouldStartLoad`/`onLoadEnd` for similar purposes), nor do I have an idea of what would be special with Android devices... but that certainly does seem like a clue. Would be worth trying other web pages if you haven't already, to check the "way we do navigation" theory...

**Comment by DIGITALSQUAD** [comment]
I tested versions 11.21.2 and 11.22.0.
11.21.2 works fine, but 11.22.0 does not, so the breaking changes in that version may be the issue.
Also, #2826 is the same.

**Comment by TheAlmightyBob** [comment]
@DIGITALSQUAD Have you tried debugging or do you have a repro to share?

**Comment by DIGITALSQUAD** [comment]
@TheAlmightyBob This is an excerpt from my code. I've tested on my physical device.  
```
class HomeScreen extends Component {
  constructor(props) {
    super(props)
    this.state = {
      refreshing: false,
    }
    this.webViewRef = React.createRef()
  }
  async componentDidMount() {
    BackHandler.addEventListener('hardwareBackPress', this.handleBackPress.bind(this))
  }

  componentWillUnmount() {
    BackHandler.removeEventListener('hardwareBackPress', this.handleBackPress.bind(this))
  }

  refreshWebView() {
    this.setState({ refreshing: false }, () => {
      this.webViewRef.current.reload()
    });
  }

  handleBackPress() {
    this.webViewRef.current.goBack()
    return true
  }

  render() {
    return (
          <ScrollView
            refreshControl={
              <RefreshControl
                refreshing={this.state.refreshing}
                onRefresh={this.refreshWebView.bind(this)}
              />
            }>
            <WebView
              ref={this.webViewRef}
            />
          </ScrollView>
    )
  }
}
```

**Comment by MRAOmio** [comment]
In case our fix helps somebody else: We think that in our case this bug was related to using react-router navigation in our website (loaded inside the webview). The workaround we found was to append an event listener within the page, that would do a goBack action on react-router when the RN back button was clicked outside the webview. This is working on android and ios, using the latest version of react-native-webview. Thank you @TheAlmightyBob for your support!

**Comment by TheAlmightyBob** [comment]
@DIGITALSQUAD Excerpt is insufficient (e.g. it doesn't even set the source of the WebView?). Would need a full app or Expo Snack.

**Comment by fkesheh** [comment]
Hey, I found out that there is an issue on  Android System Webview that is messing up with the goBack().  On my galaxy S22, If I get the latest version from Google Store it just doesn't work, if I uninstall it and get the OS vanilla one it works perfectly.

**Comment by fkesheh** [comment]
I found out the issue on my case was because the page that I had issues with was using history.pushState with a fallback to redirect if pushState was not available. Probably an older version of the Webview pushstate was not supported and it is.

**Comment by majugurci** [comment]
For me it was also not working with web-view version 11. Just upgraded the web-view to version 12.0.2 and now it is working fine on Android.

**Comment by dangnguyen1004** [comment]
i still get the error

**Comment by xclidongbo** [comment]
react native version 0.63. Can  update to webview version 12 ?
