### ISSUE TITLE
`injectJavascript` not working for android 10 and below after upgrading react native to 0.70.6

### ISSUE THREAD

**Issue by MajkellVZ** [react-native-webview/react-native-webview#2812]
After upgrading react native to 0.70.6 the `injectJavascript` started not working for android version 10 and below meanwhile for the versions from 11 to 13 seems to work just fine.
The the javascript is expected to be injected as does for android 11+ versions.

**Environment:**
 - OS: android
 - OS version: 10 and below
 - react-native version: 0.70.6
 - react-native-webview version: 11.18.1

**Comment by TheAlmightyBob** [comment]
Is this related to https://github.com/react-native-webview/react-native-webview/issues/2810?

**Comment by MajkellVZ** [comment]
I have tried up to 11.26.0 and those would break the injector for all android versions. but what I noticed is that optional chaining would break an injected function and this started happening with the new react native version (0.70.6)

**Comment by TheAlmightyBob** [comment]
> optional chaining would break an injected function

What do you mean?

**Comment by MajkellVZ** [comment]
I had functions that would use optional chaining:
`window?.example?.ecc..`. This functions would not work
when switched to 
`window && window.example && window.example.ecc`
would work as it should.

**Comment by Tamimjabr** [comment]
> After upgrading react native to 0.70.6 the `injectJavascript` started not working for android version 10 and below meanwhile for the versions from 11 to 13 seems to work just fine. The the javascript is expected to be injected as does for android 11+ versions.
> 
> **Environment:**
> 
> * OS: android
> * OS version: 10 and below
> * react-native version: 0.70.6
> * react-native-webview version: 11.18.1

don't you get an error trying to use this version with latest version of RN?

**Comment by MajkellVZ** [comment]
nope, just the javascript would stop being injected

**Comment by TheAlmightyBob** [comment]
Your `window` example suggests that you are referring to the script being injected that uses optional chaining (as opposed to React Native code).... which suggests that it _is_ being injected in both cases, but just isn't running as expected. Which is indeed strange, but possibly there's an error being reported that would provide more clues?

**Comment by MajkellVZ** [comment]
there wasn't an issue reported, but maybe after having to stringify the functions due to hermes enabling those functions holding optional chaining broke. but still not quite sure it would happen to android 10 and below

**Comment by TheAlmightyBob** [comment]
I can't imagine how Hermes would have any effect on injected Javascript...
