### ISSUE TITLE
Problem with Content Security Policy

### ISSUE THREAD

**Issue by iamrohitagg** [react-native-webview/react-native-webview#2816]
**Bug description:**

The webview works perfectly for me on iOS 14 and 16. But I am getting errors related to Content Security Policy on iOS 15.
**To Reproduce:**

<WebView
              ref={webRef}
              originWhitelist={["*"]}
              source={{
                uri:"https://clickcoop.it/app/registration",
              }}
              style={s.webView}
              onNavigationStateChange={handleNavStateChange}
              renderError={() => (
                <View style={[s.rootStyle, { alignItems: "center" }]}>
                  <Text>There was error in loading: {webUrl}</Text>
                </View>
              )}
            />
**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS: iOS
 - OS version: 14
 - react-native version: "0.64.0"
 - react-native-webview version:"11.4.0"

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=Rq-mAjkG2ME&list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i&index=14
