### ISSUE TITLE
onShouldStartLoadWithRequest refresh page when returning false on Android

### ISSUE THREAD

**Issue by alexchaoss** [react-native-webview/react-native-webview#2819]
**Bug description:**

We have a SPA and when we return false to intercept a clicked link in our page, the WebView reloads the page after 15-30 seconds. 

There are no events being fired when the page reloads, I tested with all the callbacks and nothing comes up. I was not able to reproduce it on iOS.

Just returning false with nothing else in onShouldStartLoadWithRequest also triggers the refresh.

**To Reproduce:**

With an Android device or emulator, and using a SPA inside the WebView, return false in onShouldStartLoadWithRequest when clicking a link and wait 15-30 seconds. 

**Expected behavior:**

The WebView should not refresh.

**Environment:**
 - OS: Android
 - OS version: 13
 - react-native version: 0.68.5
 - react-native-webview version: 11.25.1

**Comment by TheAlmightyBob** [comment]
Please share a sample project or Expo Snack that repros the issue (I tried to repro this myself and was unable to).
