### ISSUE TITLE
mediaCapturePermissionGrantType="grant" does not work

### ISSUE THREAD

**Issue by RominHalltari** [react-native-webview/react-native-webview#2824]
`mediaCapturePermissionGrantType="grant"` does not do what it is supposed to do. Every time the app restarts and the webview needs the permission, a permission prompt appears. Also tried other values like `grantIfSameHostElsePrompt`, same problem.

**To Reproduce:**

My webview needs orientation and motion permission. I also made sure the app has this permission already. Still, the webview prompts the user every time for permission. 

**Screenshots/Videos:**

**Environment:**
 - OS: iOS
 - OS version: iOS 16.0
 - react-native version: 0.70.3 (old architecture)
 - react-native-webview version: 11.23.1

**Comment by TheAlmightyBob** [comment]
If you debug with XCode, is `_mediaCapturePermissionGrantType` set to the expected value in `requestMediaCapturePermissionForOrigin`? Curious if it's not getting set correctly, or if there's a race condition and it's being set after that method is invoked...

**Comment by RominHalltari** [comment]
@TheAlmightyBob it seems to be set correctly. I can't find any issue in the library's code, everything I've tried has resulted in the same problem.

**Comment by ThorstenBux** [comment]
> @TheAlmightyBob it seems to be set correctly. I can't find any issue in the library's code, everything I've tried has resulted in the same problem.

Hi @RominHalltari have you found a solution for this? I'm facing the same issue: https://github.com/react-native-webview/react-native-webview/issues/2942
