### ISSUE TITLE
On Android devices, reload() do not work on the first web page.

### ISSUE THREAD

**Issue by DIGITALSQUAD** [react-native-webview/react-native-webview#2826]
**Bug description:**
When an app is just launched and the first web page loaded, pull to refresh calls refreshWebView function, but keeps showing a loading indicator and does not load the web page. 
But after moved to another page and pull to refresh works fine.
This issue causes on Android 13, 12, 11, and maybe other versions.
Closed at #2735 but does not work. 

**To Reproduce:**
Show the first page and try to reload it.

**Expected behavior:**
Reload the page.

**Environment:**
 - OS: macOS 
 - OS version: 12.6.1 Monterey
 - react-native version: 0.66
 - react-native-webview version: 11.26.0

**Source code**
```
class HomeScreen extends Component {
  constructor(props) {
    super(props)
    this.state = {
      refreshing: false,
    }
    this.webViewRef = React.createRef()
  }
 
  refreshWebView() {
    this.setState({ refreshing: false }, () => {
      this.webViewRef.current.reload()
    });
  }

  render() {
    const { navigation } = this.props;
    return (
          <ScrollView
            contentContainerStyle={{ flex: 1 }}
            refreshControl={
              <RefreshControl
                refreshing={this.state.refreshing}
                onRefresh={this.refreshWebView.bind(this)}
              />
            }>
            <WebView
              ref={this.webViewRef}
            />
          </ScrollView>
    )
  }
}
```

**Comment by DIGITALSQUAD** [comment]
This isssue is same as #2810

**Comment by tkmin** [comment]
It is not working for me, on the first web page.
But when I move to other pages and goBack(),
refresh works.

my environments are
"react": "18.2.0",
"react-native": "0.73.4",
"react-native-webview": "^13.8.1"
"@react-navigation/native": "^6.1.10",
"@react-navigation/native-stack": "^6.9.18",

Eventually, I replaced my refresh code as below
`webViewRef.current?.injectJavaScript('window.location.reload();true;');`
