### ISSUE TITLE
Android :- Home page URL Loaded but not loaded the full url

### ISSUE THREAD

**Issue by AdminDevo** [react-native-webview/react-native-webview#2827]
**Bug description:**
When i am load url "https://www.hoopladigital.com"  working fine but When i am trying to load full url ("https://www.hoopladigital.com/browse/ebook/popular?page=1") this is not loading and displaying the message "seems to unsupported browser"
--->

**Environment:**
 - OS: android
 - OS version: 11, 12
 - react-native-webview version: 11.26.0

Please Help me, Thanks in Advance.
++ @react-native-community-bot
@Thibault Malbranche
@TheAlmightyBob

**Comment by TheAlmightyBob** [comment]
Sounds like Hoopla doesn't support WebViews. You might be able to trick it by overriding the [user agent](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#useragent) to pretend to be a supported browser. Of course it's up to you to figure out what Hoopla is looking for.

**Comment by TheAlmightyBob** [comment]
Note that of course it's possible that the check is intentional and Hoopla will not work properly in a WebView.

**Comment by AdminDevo** [comment]
> Sounds like Hoopla doesn't support WebViews. You might be able to trick it by overriding the [user agent](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#useragent) to pretend to be a supported browser. Of course it's up to you to figure out what Hoopla is looking for.

Hoopla main page loaded on webview and also we can navigate related page its working fine but if we direct pass complete url then not opened.
I have also tried with **applicationNameForUserAgent={'DemoApp/1.1.0'}**  but not loaded.

**Comment by TheAlmightyBob** [comment]
`applicationNameForUserAgent={'DemoApp/1.1.0'}` isn't going to convince Hoopla that you're a web browser.

**Comment by TheAlmightyBob** [comment]
Don't know, your questions are specific to Hoopla, which I'm unfamiliar with.
