### ISSUE TITLE
WARN: Error opening URL blocks error methods.

### ISSUE THREAD

**Issue by danniolsen** [react-native-webview/react-native-webview#2835]
**Bug description:**
When passing an invalid uri/url the webView sends back a WARN: Error opening URL:  [Error: Unable to open URL ...
This seams to block the rest of the webView methods such as:
  - onError
  - onHttpError
  - onRenderError

**To Reproduce:**
pass an invalid url/uri or an empty string. ''

**Expected behavior:**
Expecting the webView to run one of the following error methods:
  - onError
  - onHttpError
  - onRenderError

**Environment:**
 - OS: Ios / Android
 - OS version: ios 16, Android 12/13
 - react-native version: 
 - react-native-webview version: ^11.22.7

**Comment by bynite** [comment]
Not opening an URL cannot lead to one of these errors. This is an expected behaviour.
You could check validity before passing it to the web view by using a regex for example.

**Comment by chishing96** [comment]
originWhitelist={['blob:']}
