### ISSUE TITLE
webview not work on android 9

### ISSUE THREAD

**Issue by tuan2603** [react-native-webview/react-native-webview#2836]
url not working 

uri = https://majesty.staging-salon-pos.d3salonsolution.com

<WebView
        originWhitelist={['*']}
        javaScriptEnabled={true}
        source={{ uri }}
        onMessage={event => this.handleMessage(event)}
        domStorageEnabled={true}
        startInLoadingState={true}
        onError={mes => {
          console.log('err', mes);
        }}
        // mixedContentMode="compatibility"
      />

please help me. thank you so much

**Comment by TheAlmightyBob** [comment]
This appears to be a problem with the website, not this library. That URL doesn't load in Chrome on Android 9 either.

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=Rq-mAjkG2ME&list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i&index=14
