### ISSUE TITLE
Webview does not render local content without internet connection

### ISSUE THREAD

**Issue by svvarik** [react-native-webview/react-native-webview#2838]
**Bug description:**

Webview won’t render local content without internet connection. The “No internet connection” error pops up. 

**To Reproduce:**

1. Turn on airplane mode (to emulate no internet signal)
2. Navigate to second screen using Go to ScreenTwo button. 
3. Error appears

[Repository with re-created issue](https://github.com/svvarik/sample-rn-webview-app)
[Expo Snack](https://snack.expo.dev/Nik9DjVVp) (Note, you can't use the web option, and will need to run it in the emulators). 

**Expected behavior:**

I expect the HTML file to render since it is a local file. 

**Screenshots/Videos:**

<img src="https://user-images.githubusercontent.com/32785634/215930092-c4ccb9dd-fd0b-4360-8022-c8dc25a89758.PNG" alt="screenshot" width="250"/>

**Environment:**
 - OS: iOS / Expo Go app
 - OS version: 16.1
 - react-native version: Expo’s version
 - react-native-webview version: Expo’s version

**Comment by TheAlmightyBob** [comment]
Please share a sample app that repros the issue.

**Comment by svvarik** [comment]
Added a sample app with the issue, as well as an Expo snack.

**Comment by TheAlmightyBob** [comment]
@svvarik This appears to be an issue with the use of Expo, not with `react-native-webview`. I'm not too familiar with the details of how Expo works, but it seems that with the way things are hosted it's no longer able to access the file from the dev machine. The issue no longer repro'd for me after using `npx expo prebuild -p ios` (and didn't repro in the first place for a non-Expo app).

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=Rq-mAjkG2ME&list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i&index=14

**Comment by Ozantunaa** [comment]
I check if there is internet using netinfo and if there is no internet, I show no internet on the screen, then webview works if there is internet

**Comment by cbbfcd** [comment]
oh~ it's not an issue with the use of Expo.
