### ISSUE TITLE
While selecting a file  to upload from webview app get crash for Android

### ISSUE THREAD

**Issue by pdc-2022** [react-native-webview/react-native-webview#2840]
No error is displayed and app crash 

**Environment:**
 - OS:  Android
 - OS version:
 - react-native version:  "0.68.1"
 - react-native-webview version: "^11.26.1"

**Comment by pdc-2022** [comment]
> Have you checked logcat for errors?

yes, but  nothing is getting logged . 
do we need to add any tags for file upload at our end

**Comment by TheAlmightyBob** [comment]
Odd. I'm not familiar with file upload, I just thought if there's a crash there should be something in logcat.

**Comment by TheAlmightyBob** [comment]
The example app does include file upload selection support (which I've tested without issue on Android), so you could check that for reference.

**Comment by pdc-2022** [comment]
In the given example, we are passing a custom html but in my case i am redirecting it to 3rd party url where while uploading its getting crashed.
