### ISSUE TITLE
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.

### ISSUE THREAD

**Issue by AlexsanderSoares** [react-native-webview/react-native-webview#2841]
Hello.

I had the following compilation issue on React Native 0.69.7:
``` 
The Android Gradle plugin supports only kotlin-android-extensions Gradle plugin version 1.6.20 and higher.
The following dependencies do not satisfy the required version:
project ':react-native-webview' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.0
```

Environment:

OS: "Android"
OS version: "10.0.0"
react-native version: "0.69.7"
react-native-webview version: "^11.26.1"
Gradle Plugin Version: "7.3.0"
Gradle Version: "7.4.0"

**Comment by TheAlmightyBob** [comment]
Duplicate of https://github.com/react-native-webview/react-native-webview/issues/2808

As noted here, you should be able to fix this via your own app's build.gradle file: https://github.com/react-native-webview/react-native-webview/pull/2805#issuecomment-1411033687
