### ISSUE TITLE
tvOS 12.4 is not compatible with react-native-webview 11.23.1

### ISSUE THREAD

**Issue by Maxhoppr** [react-native-webview/react-native-webview#2843]
Hello I'm facing an issue while trying to run my app on Apple TV simulator.

I've added this to my Podfile:

`pod 'react-native-webview', :path => '../node_modules/react-native-webview'`

But when I'm trying to run npx pod-install I got this error:

```
Command `pod install` failed.
└─ Cause: The platform of the target `TestApp-tvOS` (tvOS 12.4) is not compatible with `react-native-webview (11.23.1)`, which does not support `tvOS`.
```

Is this library supposed to support Apple TV?

Thank you

**Comment by TheAlmightyBob** [comment]
@Maxhoppr My understanding is that tvOS does not support WebViews, so that would mean this library cannot be used with it.
