### ISSUE TITLE
Background image in webView is not showing.

### ISSUE THREAD

**Issue by xcelance** [react-native-webview/react-native-webview#2844]
**Bug description:**  The background image is not showing that is in my site.

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

![sss](https://user-images.githubusercontent.com/16537585/216252063-d1038eeb-bc04-40d3-a537-d6ab9ed65cfb.png)
web 

![Screenshot_1675320430](https://user-images.githubusercontent.com/16537585/216252104-8a98d211-ed39-4fc6-a653-15c61e6d9a69.png)
mobile

**Environment:**
 - OS:  Ubuntu 
 - OS version:  18.04.6
 - react-native version:  0.70.4
 - react-native-webview version:  11.23.1

**Comment by TheAlmightyBob** [comment]
Please provide a repro

**Comment by xcelance** [comment]
Due to some legal things I cannot do so, can you please let me know what is the main cause for such a issue?

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=Rq-mAjkG2ME&list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i&index=14

**Comment by iamnynvk** [comment]
added in webview props : 

androidLayerType="hardware"

Then check
