### ISSUE TITLE
Unable to render WebView2

### ISSUE THREAD

**Issue by SBS-jtemplin** [react-native-webview/react-native-webview#2846]
**Bug description:**
When attempting to use WebView2 by setting useWebView2={true}, the app throws the following Render Error:  
`requireNativeComponent: "RCTWebView2" was not found in the UIManager`

**To Reproduce:**
```
import React, { ReactElement } from 'react';
import { View } from 'react-native';
import { WebView } from 'react-native-webview';


export const Chart = (): ReactElement => {
    
    const html = `
    <!DOCTYPE html>
    <html>
      <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1">
      </head>
      <body>
        <p id="hello">Hello WebView</p>
      </body>
    </html>
    `

    return (
        <View
            style={{ flex: 1 }}>
            <WebView
                useWebView2={true}
                source={{ html: html }}
            />
        </View>
    )
}
```

**Expected behavior:**
A WebView with functioning javascript.

**Screenshots/Videos:**  

**Environment:**
 - OS: windows
 - OS version: 10.0.19044 Build 19044
 - react-native version: 0.67.2
 - react-native-webview version: 11.26.1
 - react-native-windows version: 0.67.9

**Comment by chrisglein** [comment]
> react-native-windows version: 0.67.9

WebView2 is only supported on versions 0.68+. Can you update to resolve this?

https://github.com/react-native-webview/react-native-webview/blob/master/docs/Getting-Started.md#3-webview2-support

**Comment by SBS-jtemplin** [comment]
Updating will be complicated, but I was able to create a fresh project with version 0.68 and the WebView2 works correctly.  
Thanks!
