### ISSUE TITLE
Webview showing blank screen

### ISSUE THREAD

**Issue by Amitchoudhary92** [react-native-webview/react-native-webview#2849]
Hello everyone, I am working on Android app and we have webLogin (login in android app through web url) first time webview load the url without any issue. when i logout from the app, and close the app (remove from recent open app) and then i again try to login webview show me blank screen. When i clear app cache and app data then again webview load url without any issue. I tried a lot of things but doesn't work is any one please help me with this.

Thanks

**Comment by TheAlmightyBob** [comment]
Debugging the web content via Chrome Devtools might yield clues.

Since you say clearing the app cache/data helps, you could try calling `clearCache` on the WebView. Stale cookies might also be a culprit, so you could look into clearing those.

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=Rq-mAjkG2ME&list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i&index=14
