### ISSUE TITLE
Can't open url: blob:https://threejs.org/b590809b-2189-444b-909d-9423cc3e4072

### ISSUE THREAD

**Issue by snake89322** [react-native-webview/react-native-webview#2850]
**Bug description:**

uri: https://threejs.org/examples/#webgl_animation_keyframes
warning: Can't open url: blob:https://threejs.org/b590809b-2189-444b-909d-9423cc3e4072

page can not work normally.

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS: IOS 
 - OS version: iPadOS 16.3
 - react-native version:0.70.5
 - react-native-webview version:11.26.1

**Comment by anhtuank7c** [comment]
This is weird but could you confirm again after add this props to the WebView `originWhitelist={['*']}` @snake89322

**Comment by tubackkhoa** [comment]
> 
Info.plist
<key>LSApplicationQueriesSchemes</key>
<array>
<string>blob</string>

App.tsx
<WebView originWhitelist={['http://', 'https://', 'blob:']}

**Comment by anhtuank7c** [comment]
@tubackkhoa What a support 🎉  
I don't actually dig that deep for this case, thanks for the explanation.
