### ISSUE TITLE
allowsOnlyLandscapeInFullscreen not working on android

### ISSUE THREAD

**Issue by atjab** [react-native-webview/react-native-webview#2852]
I'm not sure version of react-native-webview can use allowsOnlyLandscapeInFullscreen. How to allow screen landscape only webview play video fullscreen on android.

"react-native": "0.70.6",
"react-native-webview": "^11.26.0",

**Comment by TheAlmightyBob** [comment]
`allowsOnlyLandscapeInFullscreen` is not a property of this library.

There was once a PR to add it (#2196), but it was not merged.

**Comment by atjab** [comment]
How to allow screen rotate only webview play video fullscreen on android. Can it possible ? Thank for your advice.

**Comment by TheAlmightyBob** [comment]
You could look into patching the changes from that PR, or make [native customizations](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Custom-Android.md).

I'm not familiar with either the PR or the behavior you're trying to achieve though.
