### ISSUE TITLE
getUserMedia not showing prompt on Android

### ISSUE THREAD

**Issue by henlamk** [react-native-webview/react-native-webview#2854]
**Bug description:**
When opening a page that uses camera and microphone, the user is not requested to grant device permissions. 

**To Reproduce:**
Open this page in a webview: https://webrtc.github.io/test-pages/src/audio-and-video/

**Expected behavior:**
The user should be requested to grant device permissions and a video should be displayed. 

**Environment:**
 - OS: Pixel 
 - OS version: Android 10
 - react-native version: 0.70.5
 - react-native-webview version: 11.23.1

**Comment by TheAlmightyBob** [comment]
You need to add the relevant permissions to your app's Android manifest.

e.g.
```
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.RECORD_AUDIO"/>
```

**Comment by henlamk** [comment]
Thank you very much. 
I am fairly new to react-native/expo, so in hope that this helps somebody else: 
First, I had to run the prebuild command to generate a proper Android project structure. 
Then I added these to the Android Manifest
```
  <uses-permission android:name="android.permission.CAMERA"/>
  <uses-permission android:name="android.permission.MICROPHONE" />
  <uses-permission android:name="android.permission.RECORD_AUDIO"/>
```
And requested said permissions before accessing the webview. 
Last, I added this property 
`mediaPlaybackRequiresUserAction={false}`
so the video can start right away.

**Comment by TheAlmightyBob** [comment]
@henlamk Thank you for sharing!

**Comment by saranya-Godigit** [comment]
mediaPlaybackRequiresUserAction={false} - this not work in react-native-cli @henlamk   if its fixed 
Can you please help me on this

**Comment by saranya-Godigit** [comment]
mediaPlaybackRequiresUserAction={false} - this not work in react-native-cli @henlamk if its fixed
Can you please help me on this

**Comment by Keddib** [comment]
> Thank you very much. I am fairly new to react-native/expo, so in hope that this helps somebody else: First, I had to run the prebuild command to generate a proper Android project structure. Then I added these to the Android Manifest
> 
> ```
>   <uses-permission android:name="android.permission.CAMERA"/>
>   <uses-permission android:name="android.permission.MICROPHONE" />
>   <uses-permission android:name="android.permission.RECORD_AUDIO"/>
> ```
> 
> And requested said permissions before accessing the webview. Last, I added this property `mediaPlaybackRequiresUserAction={false}` so the video can start right away.

@henlamk How did you asked for permissions ? can you show us a code example

**Comment by henlamk** [comment]
@Keddib Sorry I cannot
