### ISSUE TITLE
SSL Error: The certificate authority is not trusted

### ISSUE THREAD

**Issue by brunocdeveloper** [react-native-webview/react-native-webview#2856]
I'm facing issues with ssl error when navigating to an uncertified uri on android and ios. I'm using react-native-webview: ^11.23.0. Is there any way around the problem?

![tempFileForShare_20230215-142218](https://user-images.githubusercontent.com/72170223/219241107-76a6aed6-9178-4b3e-a49c-a6c2bd1b362a.jpg)

**Comment by vishal-tiwari001** [comment]
[https://github.com/react-native-webview/react-native-webview/issues/2147#issuecomment-968672220 check this out](url)
