### ISSUE TITLE
Mutual TLS

### ISSUE THREAD

**Issue by fr-an-k** [react-native-webview/react-native-webview#2857]
With mutual TLS it's possible to ensure which client and server can connect, at the TLS level. Commonly needed for API calls.

I'm stuck on this, since it doesn't really seem possible in React Native or Webview.
In Node.js you can customize the https call.

This would require Webview's onReceivedClientCertRequest method to be implemented for javascript, which then provides the certificate to a Java callback, as far as I understand.

**Comment by fr-an-k** [comment]
Related to #2765

**Comment by fr-an-k** [comment]
Here is an example in Kotlin: https://github.com/diebietse/mtls-android/tree/master/app/src/main/java/com/diebietse/mtlsandroidexample

**Comment by pa-bouly** [comment]
Hello @fr-an-k , did you find any solution? please

**Comment by fr-an-k** [comment]
No, for now you'll have to do it another way or implement it yourself similar to the example.

**Comment by pa-bouly** [comment]
ok :/ Thanks for your quick answer!
