### ISSUE TITLE
Webview is not download automatically. Both ios and android

### ISSUE THREAD

**Issue by atjab** [react-native-webview/react-native-webview#2858]
The webview not download file automatically to device.  In html, I use a link tag and set attribute as download. In webview ios, just open and preview that file but not download automatically. At the same time, android nothing happened and reload page. I should fix in web script for download or it possible to setting or something in native app via webview ?

"react-native": "0.70.6",
"react-native-webview": "^11.26.0",

    <Webview
        javaScriptEnabled={true}
        domStorageEnabled={true}
        allowFileAccessFromFileURLs={true}
        allowUniversalAccessFromFileURLs={true}
        allowFileAccess={true}
        originWhitelist={['*']}
        mixedContentMode={'always'} 
    />

In my web script

    const downloadFileFromObjectUrl = (source, filename) => {
        const downloadUrl = window.URL.createObjectURL(source)
        const link = document.createElement('a')
        link.href = downloadUrl
        link.setAttribute('download', filename)
        document.body.appendChild(link)
        link.click()
        link.remove()
    }

Thank everyone for suggestion.

**Comment by TheAlmightyBob** [comment]
For iOS, that is the expected behavior. You'd need to implement [`onFileDownload`](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#onFileDownload)

For Android, that's not necessarily expected, but we'd need a sample project or Expo Snack that repros the issue. (or you could debug the Android code yourself, if you search for "download" it shouldn't be hard to find places to put a breakpoint)

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=Rq-mAjkG2ME&list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i&index=14

**Comment by linonetwo** [comment]
I can confirm Android is not downloading when click a link like

```
<a href="blob:http://localhost/cf8ae139-a28c-43ec-9943-86ff2e0d10d0" download="filename"></a>
```

**Comment by Zaidjani** [comment]
I also need a solution , same problem i am facing

**Comment by alexviar** [comment]
If you've come across this looking for a reason why the download fails, this should help clarify things.

URLs starting with `blob://` (those created using `URL.createObjectURL`) only work within the WebView’s context. They’re not accessible from the outside. So if you try to download a file using one of these URLs from outside the WebView, it won’t work.

You have two ways to deal with this:

**Option 1: Avoid using blob:// altogether**

Ideally, the file content should be available as a regular HTTP URL so you can handle it outside the WebView.

**Option 2: Download the file inside the WebView and send it out**

If you can’t avoid using blob://, you can inject JavaScript into the WebView to fetch the file internally and then send its content to the native side using postMessage. Example:

```Javascript
const url = 'blob://...';
webView.injectJavaScript(`
  (function() {
    fetch('${url}')
      .then(response => response.blob())
      .then(blob => {
        const reader = new FileReader();
        reader.onloadend = () => {
          const base64String = reader.result.split(',')[1];
          window.ReactNativeWebView.postMessage(JSON.stringify({ 
            type: 'SAVE_FILE', 
            payload: {
              data: base64String,
              mimeType: blob.type
            }
          }));
        };
        reader.readAsDataURL(blob);
      });
  })();
  true;
`);
```
