### ISSUE TITLE
AR Quick Look not opening USDZ files

### ISSUE THREAD

**Issue by Matiassimone** [react-native-webview/react-native-webview#2860]
I want to re open this issue that still persist in the last version of react-native-webview :
https://github.com/react-native-webview/react-native-webview/issues/1242

Bug description:

This webview implementation does not open correctly [AR Quick Look](https://developer.apple.com/documentation/arkit/previewing_a_model_with_ar_quick_look) URLs containing reference to USDZ files. Instead of previewing the 3D model, it opens the zip file in binary format, which is not what is intended.

This is probably due to the use of WKWebView instead of SFSafariViewController, since [this reference](https://webkit.org/blog/8421/viewing-augmented-reality-assets-in-safari-for-ios/) states that AR Quick Look does not work with WKWebView.

To Reproduce:
https://github.com/aviggiano/ar-quick-look-bug

Expected behavior:

Opening an AR preview of the 3D model, similarly to what happens on [Safari](https://developer.apple.com/augmented-reality/quick-look/)

Screenshots/Videos:
![image](https://user-images.githubusercontent.com/28985499/219383026-0c78d653-ab25-47f9-b615-923761b991eb.png)

**Comment by nicomanzato** [comment]
I have the same issue, has anyone found a solution for this?

**Comment by TheAlmightyBob** [comment]
@Matiassimone 
> This is probably due to the use of WKWebView instead of SFSafariViewController, since [this reference](https://webkit.org/blog/8421/viewing-augmented-reality-assets-in-safari-for-ios/) states that AR Quick Look does not work with WKWebView.

If that's the case, then this will never be supported by this library. The entire purpose of `react-native-webview` on iOS is to be a wrapper around WKWebView. If you need `SFSafariViewController`, then you should use https://github.com/proyecto26/react-native-inappbrowser instead.

**Comment by EArminjon** [comment]
Any solution ?
