### ISSUE TITLE
Delay to inject CSS using webview

### ISSUE THREAD

**Issue by dutradotdev** [react-native-webview/react-native-webview#2862]
**Bug description:**
This is not a bug.

I want to know if there is a way to improve the performance of the react-native-webview in my situation.
I am using a WebView to create a View with blur and everything is working as expected, you can check my approach here: https://gist.github.com/dutradotdev/50c82763fc621ab3c1bd5ba02180ce0d

But when I render the webview i notice a delay, i would like to know if there is a way to improve this performance to remove this delay, add a cache or something like this

**To Reproduce:**
https://gist.github.com/dutradotdev/50c82763fc621ab3c1bd5ba02180ce0d

**Expected behavior:**
Decrease the render delay

**Screenshots/Videos:**

https://user-images.githubusercontent.com/25035327/219874047-f609e31e-21e0-44b7-bce1-2c20af498952.mov

**Environment:**
 - OS: macOS
 - OS version: 13
 - react-native version: 0.70.5
 - react-native-webview version: ^11.26.1

**Comment by krushalikevadiya** [comment]
Same issue for me in Android only.View is injecting after 2 mins.can anyone please help me.

**Comment by dutradotdev** [comment]
hey @TheAlmightyBob do you know if there is some optimization/performance guide to help us in our use case?

**Comment by TheAlmightyBob** [comment]
@dutradotdev Sorry, I have no ideas on this one, other than to maybe always render the WebView but translate it offscreen until you need it? WebView seems a very heavy component for this use case though, I'm surprised there's not a better option (but I see that your gist says you already researched alternatives)
