### ISSUE TITLE
nsurlerrordomain code=-1004 error

### ISSUE THREAD

**Issue by ozergul** [react-native-webview/react-native-webview#2863]
**Bug description:**

Hi everyone. I am using this wonderful library and it gives error I attached below only at ios. I checked documentations but couldn't find the reason why this error occurs. Are there any body experienced this? (Note: android works without no problem)

**Screenshots/Videos:**

![image](https://user-images.githubusercontent.com/8460954/219898620-f0d72b22-eaa2-46e7-bdee-97da9ac01be5.png)

**Environment:**
 - OS: ios
 - OS version: all
 - react-native version:
 - react-native-webview version:

**Comment by nolife08021** [comment]
@ozergul did you found any solution for this?

**Comment by ozergul** [comment]
I logged onError and saw that an URL while redirection gives 500 error. So react-native-webview gives this -1004 error if some server gives 500.

<img width="438" alt="image" src="https://user-images.githubusercontent.com/8460954/222681286-e8190315-b920-4339-b83e-b1169f11510d.png">

**Comment by tingofurro** [comment]
I am having a similar issue. Unfortunately for me, the App Store Review team is having this issue, which I am not able to reproduce at all in simulation or on physical iPhone.
@ozergul , you are saying that the problem comes from the server giving an error code 500, and you didn't have to change anything on the App side to get it to work? But how could it be working for Android and not iOS? (the server is the same, no?)

@nolife08021  did you find a solution to the problem?

**Comment by ozergul** [comment]
@tingofurro our problem was related with third party payment processor. They have had very simple bug on their backends (related with useragent)
That's why app was broken on Ios but not Android

I would prefer adding some logs to backend to understand why the web page broken for App Store Review team

Or see my above message. Log onError with sentry or something else and you will see exactly which page is broken

**Comment by tingofurro** [comment]
For future lost souls, it was in fact a DNS problem, where Apple's testing environment does not follow Dynamic DNS (no-ip or ddns.net).

**Comment by ednjv** [comment]
hi @tingofurro thanks! do you have by any chance the source of where apple states this about their testing environment not following up Dynamic DNS?

and what's the solution for that case?

**Comment by tingofurro** [comment]
hey @ednjv, I never found the information in their documentation, I just tested it empirically.
I changed my domain name to point to a static IP directly, and when I resubmitted with no other change, I got through to the next step (which were other problems), but eventually got the app accepted!

I hope this helps :)
