### ISSUE TITLE
Support deep linking

### ISSUE THREAD

**Issue by nsauter** [react-native-webview/react-native-webview#2864]
**Is your feature request related to a problem? If so, Please describe.**
I want to implement a few links and need values from the webpage when the callback to the app happens. Currently im using safari (on ios) but i would find it cleaner if a browser view inside the app would to that.

**Additional context**
The current 'problem' is, that i want to authenticate users of my app via oauth. Therefore the user needs to login to the service in a browser and the browser then calls back to a url. to make this experience as clean as possible i would suggest to implement deep linking and callbacks directly to the app via webview inside the app.

**Comment by TheAlmightyBob** [comment]
It's not clear what you're asking for this library to do. If your intent is to perform OAuth authentication in a WebView, my understanding is that OAuth explicitly doesn't support that due to security concerns. 

https://github.com/proyecto26/react-native-inappbrowser might be a better fit for your use case.

**Comment by nsauter** [comment]
Basically i just want to grab the callback of OAuth and process it further in my react-native app. But it seems like there is no option to communicate with the browser. I will take a look at this.

**Comment by TheAlmightyBob** [comment]
If you mean deep linking back to the app from the browser, that's more of a general [React Native](https://reactnative.dev/docs/linking) & app configuration feature, unrelated to `react-native-webview`.

**Comment by nsauter** [comment]
But can this workflow be archived with react-native-webview?

**Comment by TheAlmightyBob** [comment]
> But can this workflow be archived with react-native-webview?

I might still be misunderstanding, but it doesn't sound like the workflow you're describing involves WebViews at all?

**Comment by nsauter** [comment]
Maybe im just not experienced enough to describe my problem and what i want to archive. I'm going to try that and wont bother you further.

**Comment by Teut2711** [comment]
For me too, I have to perform Oauth via Keycloak. After getting the auth_token, I need to redirect from webview to app but it rather opens the redirect verified deep link in webview.

```
import React, {useEffect, useState} from 'react';
import {NODE_ENV} from '@env';
import WebView from 'react-native-webview';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {Linking} from 'react-native';
import {useRoute, RouteProp} from '@react-navigation/native';
import {ActivityIndicator} from 'react-native-paper';
import jwtDecode from 'jwt-decode';

interface IClientAttrs {
  id: string;
  secret: string;
  loginRedirectTo: URL;
  logoutRedirectTo: URL;
  scopes: string;
}

interface IRequestOptions {
  method: string;
  headers: Headers;
  body: string;
  redirect: string;
}

interface IKeycloakAuth {
  keycloakBaseUrl: URL;
  realmName: string;
  clientAttrs: IClientAttrs;
}

interface IWebViewState {
  url: string;
  [key: string]: any;
}

function extractCodeFromUrl(url: string): string | null {
  const regex = /[?&]code=([^&#]*)/i;
  const match = regex.exec(url as string);
  if (match) {
    return decodeURIComponent(match[1]);
  }
  return null;
}

async function getAcessToken(
  keycloakBaseUrl: URL,
  realmName: string,
  client: IKeycloakAuth['clientAttrs'],
  code: string,
) {
  const myHeaders: Headers = new Headers();
  myHeaders.append('Content-Type', 'application/x-www-form-urlencoded');

  const urlencoded: URLSearchParams = new URLSearchParams();
  urlencoded.append('grant_type', 'authorization_code');
  urlencoded.append('client_id', client.id);
  urlencoded.append('client_secret', client.secret);
  urlencoded.append('code', code.toString());
  urlencoded.append(
    'redirect_uri',
    client.loginRedirectTo as unknown as string,
  );

  const requestOptions: IRequestOptions = {
    method: 'POST',
    headers: myHeaders,
    body: (urlencoded as URLSearchParams).toString(),
    redirect: 'follow',
  };
  try {
    const response = await fetch(
      `${keycloakBaseUrl}/realms/${realmName}/protocol/openid-connect/token`,
      requestOptions,
    );
    const result = await response.json();
    return result;
  } catch (error) {
    console.log('Could not receive access token: ', error);
  }
}
type ParamList = {
  KEYCLOAK: {
    logout: boolean;
  };
};

const asyncStoreWrapper = async (key, data) => {
  const existingItem = await AsyncStorage.getItem(key);
  if (existingItem !== null) {
    await AsyncStorage.removeItem(key);
  }

  await AsyncStorage.setItem(key, JSON.stringify(data));
};

const KeycloakAuth = ({
  keycloakBaseUrl,
  realmName,
  clientAttrs,
}: IKeycloakAuth) => {
  const {params}: RouteProp<ParamList, 'KEYCLOAK'> = useRoute();

  const handleOnShouldStartLoadWithRequest = (event: any) => {
    if (
      event.url.startsWith(clientAttrs.loginRedirectTo as unknown as string)
    ) {
      Linking.openURL('energymetrics://dashboard');
      return false;
    } else {
      return true;
    }
    //TODO: Remove this when deep links work properly
  };
  const handleWebViewStateChange = async (webViewState: IWebViewState) => {
    try {
      //TODO: Improve error handling
      const {url}: {url: string} = webViewState;

      if (url && (url.startsWith('http://') || url.startsWith('https://'))) {
        const code = extractCodeFromUrl(url);
        if (code) {
          let authResponse;
          authResponse = await getAcessToken(
            keycloakBaseUrl,
            realmName,
            clientAttrs,
            code,
          );
          if (NODE_ENV === 'production') {
            console.info('Auth response from keycloak is :', authResponse);
          }
          await asyncStoreWrapper('keycloak', authResponse);
          if (authResponse.id_token) {
            const userInfo = jwtDecode(authResponse.id_token) as Record<
              string,
              any
            >;
            await asyncStoreWrapper('user', userInfo);
          }
        }
      }
    } catch (error) {
      console.log(error);
    }
  };
  const [authUrl, setAuthUrl] = useState<null | string>(null);

  useEffect(() => {
    const getAuthUrl = async () => {
      let url;
      if (params?.logout) {
        url = getLogoutURL(keycloakBaseUrl, realmName, clientAttrs);
      } else {
        url = getLoginURL(keycloakBaseUrl, realmName, clientAttrs);
      }
      setAuthUrl(url);
    };

    getAuthUrl();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  if (authUrl === null) {
    return <ActivityIndicator animating={true} color={'#990000'} />;
  }
  //not required as of now since idToke is being parsed to get user identity
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const userInfoEndpoint = `${keycloakBaseUrl}/realms/${realmName}/protocol/openid-connect/userInfo`;

  return (
    <WebView
      source={{
        uri: authUrl as string,
      }}
      cacheEnabled={false}
      style={{flex: 1}}
      onNavigationStateChange={handleWebViewStateChange}
      javaScriptEnabled
      onShouldStartLoadWithRequest={handleOnShouldStartLoadWithRequest}
    />
  );
};
export default KeycloakAuth;

function getLoginURL(
  keycloakBaseUrl: URL,
  realmName: string,
  clientAttrs: IClientAttrs,
) {
  const responseType = 'code'; // Use 'code' for Authorization Code flow
  const authEndPoint = `${keycloakBaseUrl}/realms/${realmName}/protocol/openid-connect/auth`;

  const authUrl = `${authEndPoint}?client_id=${
    clientAttrs.id
  }&redirect_uri=${encodeURIComponent(
    clientAttrs.loginRedirectTo as unknown as string,
  )}&response_type=${responseType}&scope=${encodeURIComponent(
    clientAttrs.scopes,
  )}`;
  return authUrl;
}

function getLogoutURL(
  keycloakBaseUrl: URL,
  realmName: string,
  clientAttrs: IClientAttrs,
) {
  const authEndPoint = `${keycloakBaseUrl}/realms/${realmName}/protocol/openid-connect/logout`;
  const authUrl = `${authEndPoint}?client_id=${
    clientAttrs.id
  }&post_logout_redirect_uri =${encodeURIComponent(
    clientAttrs.logoutRedirectTo as unknown as string,
  )}`;
  return authUrl;
}
```
 I found a stackoverflow solution which tells to use "handleOnShouldStartLoadWithRequest " but what's happening is with this I get redirected to the app after oauth but then I get back to the keycloak component. The verified http based deep link opens up in web view otherwise. If someone sees some other error in my code that's causing it or can tell why verified deep link is not working please share the problem in the code.
Thanks

**Comment by VonJie** [comment]
> 

It's work for my project!
Thanks!

**Comment by VonJie** [comment]
> For me too, I have to perform Oauth via Keycloak. After getting the auth_token, I need to redirect from webview to app but it rather opens the redirect verified deep link in webview.
> 
> ```
> import React, {useEffect, useState} from 'react';
> import {NODE_ENV} from '@env';
> import WebView from 'react-native-webview';
> import AsyncStorage from '@react-native-async-storage/async-storage';
> import {Linking} from 'react-native';
> import {useRoute, RouteProp} from '@react-navigation/native';
> import {ActivityIndicator} from 'react-native-paper';
> import jwtDecode from 'jwt-decode';
> 
> interface IClientAttrs {
>   id: string;
>   secret: string;
>   loginRedirectTo: URL;
>   logoutRedirectTo: URL;
>   scopes: string;
> }
> 
> interface IRequestOptions {
>   method: string;
>   headers: Headers;
>   body: string;
>   redirect: string;
> }
> 
> interface IKeycloakAuth {
>   keycloakBaseUrl: URL;
>   realmName: string;
>   clientAttrs: IClientAttrs;
> }
> 
> interface IWebViewState {
>   url: string;
>   [key: string]: any;
> }
> 
> function extractCodeFromUrl(url: string): string | null {
>   const regex = /[?&]code=([^&#]*)/i;
>   const match = regex.exec(url as string);
>   if (match) {
>     return decodeURIComponent(match[1]);
>   }
>   return null;
> }
> 
> async function getAcessToken(
>   keycloakBaseUrl: URL,
>   realmName: string,
>   client: IKeycloakAuth['clientAttrs'],
>   code: string,
> ) {
>   const myHeaders: Headers = new Headers();
>   myHeaders.append('Content-Type', 'application/x-www-form-urlencoded');
> 
>   const urlencoded: URLSearchParams = new URLSearchParams();
>   urlencoded.append('grant_type', 'authorization_code');
>   urlencoded.append('client_id', client.id);
>   urlencoded.append('client_secret', client.secret);
>   urlencoded.append('code', code.toString());
>   urlencoded.append(
>     'redirect_uri',
>     client.loginRedirectTo as unknown as string,
>   );
> 
>   const requestOptions: IRequestOptions = {
>     method: 'POST',
>     headers: myHeaders,
>     body: (urlencoded as URLSearchParams).toString(),
>     redirect: 'follow',
>   };
>   try {
>     const response = await fetch(
>       `${keycloakBaseUrl}/realms/${realmName}/protocol/openid-connect/token`,
>       requestOptions,
>     );
>     const result = await response.json();
>     return result;
>   } catch (error) {
>     console.log('Could not receive access token: ', error);
>   }
> }
> type ParamList = {
>   KEYCLOAK: {
>     logout: boolean;
>   };
> };
> 
> const asyncStoreWrapper = async (key, data) => {
>   const existingItem = await AsyncStorage.getItem(key);
>   if (existingItem !== null) {
>     await AsyncStorage.removeItem(key);
>   }
> 
>   await AsyncStorage.setItem(key, JSON.stringify(data));
> };
> 
> const KeycloakAuth = ({
>   keycloakBaseUrl,
>   realmName,
>   clientAttrs,
> }: IKeycloakAuth) => {
>   const {params}: RouteProp<ParamList, 'KEYCLOAK'> = useRoute();
> 
>   const handleOnShouldStartLoadWithRequest = (event: any) => {
>     if (
>       event.url.startsWith(clientAttrs.loginRedirectTo as unknown as string)
>     ) {
>             Linking.openURL(event.url);
> 
>       return false;
>     } else {
>       return true;
>     }
>     //TODO: Remove this when deep links work properly
>   };
>   const handleWebViewStateChange = async (webViewState: IWebViewState) => {
>     try {
>       //TODO: Improve error handling
>       const {url}: {url: string} = webViewState;
> 
>       if (url && (url.startsWith('http://') || url.startsWith('https://'))) {
>         const code = extractCodeFromUrl(url);
>         if (code) {
>           let authResponse;
>           authResponse = await getAcessToken(
>             keycloakBaseUrl,
>             realmName,
>             clientAttrs,
>             code,
>           );
>           if (NODE_ENV === 'production') {
>             console.info('Auth response from keycloak is :', authResponse);
>           }
>           await asyncStoreWrapper('keycloak', authResponse);
>           if (authResponse.id_token) {
>             const userInfo = jwtDecode(authResponse.id_token) as Record<
>               string,
>               any
>             >;
>             await asyncStoreWrapper('user', userInfo);
>           }
>         }
>       }
>     } catch (error) {
>       console.log(error);
>     }
>   };
>   const [authUrl, setAuthUrl] = useState<null | string>(null);
> 
>   useEffect(() => {
>     const getAuthUrl = async () => {
>       let url;
>       if (params?.logout) {
>         url = getLogoutURL(keycloakBaseUrl, realmName, clientAttrs);
>       } else {
>         url = getLoginURL(keycloakBaseUrl, realmName, clientAttrs);
>       }
>       setAuthUrl(url);
>     };
> 
>     getAuthUrl();
>     // eslint-disable-next-line react-hooks/exhaustive-deps
>   }, []);
> 
>   if (authUrl === null) {
>     return <ActivityIndicator animating={true} color={'#990000'} />;
>   }
>   //not required as of now since idToke is being parsed to get user identity
>   // eslint-disable-next-line @typescript-eslint/no-unused-vars
>   const userInfoEndpoint = `${keycloakBaseUrl}/realms/${realmName}/protocol/openid-connect/userInfo`;
> 
>   return (
>     <WebView
>       source={{
>         uri: authUrl as string,
>       }}
>       cacheEnabled={false}
>       style={{flex: 1}}
>       onNavigationStateChange={handleWebViewStateChange}
>       javaScriptEnabled
>       onShouldStartLoadWithRequest={handleOnShouldStartLoadWithRequest}
>     />
>   );
> };
> export default KeycloakAuth;
> 
> function getLoginURL(
>   keycloakBaseUrl: URL,
>   realmName: string,
>   clientAttrs: IClientAttrs,
> ) {
>   const responseType = 'code'; // Use 'code' for Authorization Code flow
>   const authEndPoint = `${keycloakBaseUrl}/realms/${realmName}/protocol/openid-connect/auth`;
> 
>   const authUrl = `${authEndPoint}?client_id=${
>     clientAttrs.id
>   }&redirect_uri=${encodeURIComponent(
>     clientAttrs.loginRedirectTo as unknown as string,
>   )}&response_type=${responseType}&scope=${encodeURIComponent(
>     clientAttrs.scopes,
>   )}`;
>   return authUrl;
> }
> 
> function getLogoutURL(
>   keycloakBaseUrl: URL,
>   realmName: string,
>   clientAttrs: IClientAttrs,
> ) {
>   const authEndPoint = `${keycloakBaseUrl}/realms/${realmName}/protocol/openid-connect/logout`;
>   const authUrl = `${authEndPoint}?client_id=${
>     clientAttrs.id
>   }&post_logout_redirect_uri =${encodeURIComponent(
>     clientAttrs.logoutRedirectTo as unknown as string,
>   )}`;
>   return authUrl;
> }
> ```
> 
> I found a stackoverflow solution which tells to use "handleOnShouldStartLoadWithRequest " but what's happening is with this I get redirected to the app after oauth but then I get back to the keycloak component. The verified http based deep link opens up in web view otherwise. If someone sees some other error in my code that's causing it or can tell why verified deep link is not working please share the problem in the code. Thanks

It's work for my project!
Thanks!
