### ISSUE TITLE
Prompt for Auth not showing when the status code of the URL is 401

### ISSUE THREAD

**Issue by kuby** [react-native-webview/react-native-webview#2870]
**Bug description:**
I have an application, which uses basic OAuth authentication. When I want to login, there is a third party provider which takes care of the login - the app will be redirected to a URL which should show the basic Auth prompt (which contains an input for username and password), because of the standard behavior of the browser when it gets a 401 directly in the URL we want to open. At least this is the standard behavior on a regular browser (desktop or mobile version as well).

When trying to access this from the mobile app, this prompt is never shown, the error is caught by the `onHttpError` handler. Even if I ignore this error, the prompt never pops up.

Is there a way to somehow work around this and allow the prompt to actually be displayed?

**To Reproduce:**
Open a URL from WebView which returns 401 in its header.

**Expected behavior:**
The login prompt is shown.

**Screenshots/Videos:**
![image](https://user-images.githubusercontent.com/8900327/220667719-f0682f65-1028-4450-b3ea-f0174411d914.png)

**Environment:**
 - OS: macOS Monterey
 - OS version: 12.4
 - react-native version: 0.66.4
 - react-native-webview version: 11.17.1

**Comment by clausndk** [comment]
I can reproduce this on Android using the test website:
https://authenticationtest.com/HTTPAuth/

The dialog works fine on desktop browsers, and even both native Safari and Chrome on iOS and Android devices. Edge on iOS also works.
Multiple versions of Android is tested on, not working, and also newest iOS today.

**Comment by nunocaseiro** [comment]
+1

**Comment by kuby** [comment]
Can we re-open this? The issue is still valid and it seems like more people would like to see this resolved.

**Comment by iamsee** [comment]
any solution? need help pls

**Comment by kilaniamine96** [comment]
This issue should be re-opened it's important

**Comment by vasteez** [comment]
+1

**Comment by fempyrean** [comment]
This issue has been stale for a while, but for anyone still facing this issue: there is a way to pass the authencation credentials to the WebView. Check out this issue: #2630. 

Note that this will only work if the website you're trying to access uses `Basic Authentication`.
