### ISSUE TITLE
Abi37_0_0.host.exp.exponent.modules.api.components.webview.RNCWebViewManager cannot be cast to abi30_0_0.com.facebook.react.uimanager.ViewGroupManager

### ISSUE THREAD

**Issue by eamankwah250** [react-native-webview/react-native-webview#2871]
**Bug description: Abi37_0_0.host.exp.exponent.modules.api.components.webview.RNCWebViewManager cannot be cast to abi30_0_0.com.facebook.react.uimanager.ViewGroupManager

**To Reproduce: code works in IOS but I get this error when I try android

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS: Android
 - OS version: latest version 
 - react-native version: 0.68.2
 - react-native-webview version: 11.18.1

**Comment by eamankwah250** [comment]
![Uploading D80FF376-4276-45FB-8D2E-FD309C9A3B2B.jpeg…]()

**Comment by TheAlmightyBob** [comment]
Please try a more recent version of `react-native-webview`. And, if you still get the error, please share a sample project that reproduces the issue.

**Comment by eamankwah250** [comment]
I was able to resolve the issue by placing the Webview component inside a
view rather than a SafeAreaView

**Comment by floresvfer** [comment]
Check and Try this
https://github.com/react-native-webview/react-native-webview/issues/1372#issuecomment-1487785231
