### ISSUE TITLE
Why WebRTC live video is getting freezes in webview react native?

### ISSUE THREAD

**Issue by Minhaj-beep** [react-native-webview/react-native-webview#2872]
**Bug description:**

If I touch the screen then only video plays. I have already set mediaPlaybackRequiresUserAction={false} but it didn't work. 

`
<View style={styles.TopContainer}>
          <AppBar props={AppBarContent}/>
          {
            url !== null ?
                <WebView 
                  style={{height:'100%', width:'100%', backgroundColor:"red"}} 
                  source={{ uri: url }} 
                  // allowsInlineMediaPlayback={true} 
                  mediaPlaybackRequiresUserAction={false}
                  mediaCapturePermissionGrantType="grantIfSameHostElsePrompt"
                  // allowsProtectedMedia={true}
                  // allowsAirPlayForMediaPlayback={true}
                  // startInLoadingState
                  // scalesPageToFit
                  // javaScriptEnabled={true}
                  // userAgent={'Mozilla/5.0 (Linux; An33qdroid 10; Android SDK built for x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.185 Mobile Safari/537.36'}
                />
            : null
          }
    </View>
`

I have tried to set different props related to media but nothing is working. Kindly provide a solution. Thank you!

**Environment:**
 - OS: Android
 - OS version: Version 12
 - react-native version:  0.70.5
 - react-native-webview version: ^11.25.0

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=Rq-mAjkG2ME&list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i&index=14

**Comment by putuoka** [comment]
> This will help https://www.youtube.com/watch?v=Rq-mAjkG2ME&list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i&index=14

Hi, can this help my issue? https://github.com/react-native-webview/react-native-webview/issues/2834
