### ISSUE TITLE
Stripe checkout not working in iOS

### ISSUE THREAD

**Issue by Cesaario** [react-native-webview/react-native-webview#2877]
**Bug description:**

Hi! I'm creating a native app using react-native-webview that wraps a Bubble application. When proceeding to checkout in an iOS device, the screen quickly blinks like it is loading something but nothing happens.

Another point that is worth noticing is that when I open the app, I'm redirected to a stripe checkout URL that opens in my browser. It does not happen in an Android device.

**Expected behavior:**

This process works in an Android device. When proceeding to checkout, it opens a popup where I can enter my credit card information.

**To Reproduce:**

Here is the code that i'm using to render the webview.

I had to add "userAgent" with that value because the checkout was not working in my Android device. Adding the userAgent as suggested in this strackoverflow answer (https://stackoverflow.com/a/48225733/10628833) solved the problem. I thought that it could also be the cause of the bug in the iOS device, but even after removing the userAgent prop, the behavior is the same.

The ```onShouldStartLoadWithRequest``` prop was added to open external links in the browser instead of in the webview. I did as was suggested in this another stackoverflow anser (https://stackoverflow.com/a/54115883/10628833) and it also worked correctly. I don't think it is the cause of the problem because stripe should not be trying to open a new url when I proceed to checkout, it should just open a popup. In my android device, when debugging the function in this prop, the function is not called when I try to checkout.

```typescript
import React from 'react';
import {WebView} from 'react-native-webview';
import {
  ActivityIndicator,
  Linking,
  StyleSheet,
  View,
  Platform,
} from 'react-native';
import useDoubleBackToClose from './useDoubleBackToClose';

export default function App() {
  const URI = "my uri";

  useDoubleBackToClose('Aperte duas vezes para sair');

  const renderLoading = () => {
    return (
      <View style={styles.loadingContainer}>
        <ActivityIndicator size="large" color="#36CD72" />
      </View>
    );
  };

  return (
    <WebView
      setBuiltInZoomControls={false}
      geolocationEnabled
      startInLoadingState
      renderLoading={renderLoading}
      userAgent="Mozilla/5.0 (iPhone; CPU iPhone OS 13_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148"
      source={{uri: URI}}
      onShouldStartLoadWithRequest={request => {
        if (request.url !== URI) {
          Linking.openURL(request.url);
          return false;
        }
        return true;
      }}
    />
  );
}

const styles = StyleSheet.create({
  loadingContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#292929',
    height: '100%',
  },
});

```

**Environment:**
 - react-native version: 0.71.2
 - react-native-webview version: 11.26.1

**Comment by TheAlmightyBob** [comment]
Is it possible that Stripe is trying to use Apple Pay?

**Comment by bilal-prog** [comment]
This is a really serious issue, all my apps can not display the stripe checkout url on IOS 
"react-native-webview": "11.26.0"
"react-native": "0.69.4"
