### ISSUE TITLE
storage access popup alert don't show

### ISSUE THREAD

**Issue by Salmankhan033** [react-native-webview/react-native-webview#2878]
Hi 
I wrap a website, The website used storage and a camera I added
 

```
<uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.RECORD_AUDIO"/>
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.VIDEO_CAPTURE" />
```

<WebView
          source={{uri: 'url'}}
          javaScriptEnabled={true}
          ref={webViewRef}
          mediaPlaybackRequiresUserAction={false}
          //For the Cache
          domStorageEnabled={true}
          //View to show while loading the webpage
          renderLoading={() => <ActivityIndicatorElement />}
          //Want to show the view or not
          startInLoadingState={true}
          geolocationEnabled={true}
          scalesPageToFit
          allowsInlineMediaPlayback={true}
          javaScriptEnabledAndroid={true}
        />

but the popup alert does not show,  is there any solution to show a prompt or alert?
    when I check the app setting the storage permission is off but still, it takes an image from the storage.
    How to handle it? 
    Thanks

**Comment by TheAlmightyBob** [comment]
> the storage permission is off but still, it takes an image from the storage

Sounds like you don't actually need the permission then?

If you [check the docs](https://developer.android.com/reference/android/Manifest.permission#READ_EXTERNAL_STORAGE), the storage permission has gone through a few changes in different Android versions, and is no longer used in the latest release.

**Comment by Salmankhan033** [comment]
> > the storage permission is off but still, it takes an image from the storage
> 
> Sounds like you don't actually need the permission then?
> 
> If you [check the docs](https://developer.android.com/reference/android/Manifest.permission#READ_EXTERNAL_STORAGE), the storage permission has gone through a few changes in different Android versions, and is no longer used in the latest release.

I want the app asks for permission when opening the camera or storage.
I think google and apple store will not approve without asking for permissions

**Comment by TheAlmightyBob** [comment]
If you needed to ask for permission and didn't, it wouldn't be giving you access.

**Comment by Neha0595** [comment]
In react-native-webview for storage permission prompt they added below check 

> if (Build.VERSION.SDK_INT > Build.VERSION_CODES.P) {
      return true;
    } 

> boolean result = ContextCompat.checkSelfPermission(getCurrentActivity(), Manifest.permission.WRITE_EXTERNAL_STORAGE) == PackageManager.PERMISSION_GRANTED;
    if (!result && Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
      PermissionAwareActivity activity = getPermissionAwareActivity();
      activity.requestPermissions(new String[]{Manifest.permission.WRITE_EXTERNAL_STORAGE}, FILE_DOWNLOAD_PERMISSION_REQUEST, getWebviewFileDownloaderPermissionListener(downloadingMessage, lackPermissionToDownloadMessage));
    }

So If your SDK version is greater than 28, it will not show a permission prompt, as storage permission is not required for Android Q (Android 10) and above. However, this will only work correctly if **react-native-webview** sets the usage of the public directory for storage, using Scoped Storage. In their DownloadManager, they did not set this, so without storage permission, the system is not able to write to external storage.
