### ISSUE TITLE
problem in "react-native": "0.71.4", "react-native-webview": "^11.26.1"

### ISSUE THREAD

**Issue by alibayramnazhad** [react-native-webview/react-native-webview#2884]
info JS server already running.
info Installing the app...
> Task :app:checkDebugAarMetadata FAILED
10 actionable tasks: 2 executed, 8 up-to-date

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform webkit-1.4.0.aar (androidx.webkit:webkit:1.4.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not find webkit-1.4.0.aar (androidx.webkit:webkit:1.4.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/webkit/webkit/1.4.0/webkit-1.4.0.aar

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 7m 36s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform webkit-1.4.0.aar (androidx.webkit:webkit:1.4.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not find webkit-1.4.0.aar (androidx.webkit:webkit:1.4.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/webkit/webkit/1.4.0/webkit-1.4.0.aar

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 7m 36s

    at makeError (E:\ReactNative\RkaTracker\2\rka\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:174:9)
    at E:\ReactNative\RkaTracker\2\rka\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:278:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runOnAllDevices (E:\ReactNative\RkaTracker\2\rka\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:82:7)
    at async Command.handleAction (E:\ReactNative\RkaTracker\2\rka\node_modules\@react-native-community\cli\build\index.js:108:9)
info Run CLI with --verbose flag for more details.

**Comment by TheAlmightyBob** [comment]
Please share a sample project that reproduces the issue.

**Comment by alibayramnazhad** [comment]
hi,
i create a simple project with npx react-native init xxx
an then install and run it to test, it is ok. after installing webview is not run and  gooing to give error

**Comment by TheAlmightyBob** [comment]
I have done the same and it built and ran fine. Please share the sample project that has the error.

**Comment by emmarq** [comment]
I was experiencing very similar behavior. After a build step involving react-native-webview, the whole build failed. Searching for the error including the code causing the StackOverflow, (only two methods recursively calling each other) it apparently pointed to a problem with gradle. that error was fixed in version 7.6. After updating gradle to 7.6.1, another error appeared (you know what that means, progress 🎉 ) 

So this bug could be a gradle one, hiding another bug. https://github.com/gradle/gradle/issues/21997
