### ISSUE TITLE
UIMenuController changed to UIEditMenuInteraction on iOS 16

### ISSUE THREAD

**Issue by JVPizzini** [react-native-webview/react-native-webview#2885]
On the latest iOS, Apple has changed UIMenuController.

**menuItems** ins't working on iOS 16+

It was been reported here:
https://github.com/react-native-webview/react-native-webview/issues/934#issuecomment-1416515205

**Comment by danilo900** [comment]
This appear to be resolved on this commit:

https://github.com/react-native-webview/react-native-webview/pull/2610/commits/836d2a2e6e076bff7e1ee76e85e2c852c38ad92a

Thanks @naveennazimudeen
