### ISSUE TITLE
Webview & a webpage's MediaSession

### ISSUE THREAD

**Issue by tingofurro** [react-native-webview/react-native-webview#2886]
If a webview is playing an `audio` or `video` file, and the page provides "MediaSession" (https://developer.mozilla.org/en-US/docs/web/api/mediasession) attributes, are these taken into account by natively, as in will there be a notification for control on the lock screne by the user allowing play/pause?

Thanks for your help, I am not able to confirm is this is possible or not.

**Comment by indjeto** [comment]
I have the same issue.

**Comment by smlparry** [comment]
I too have this issue. Seems like on iOS this is working as expected, but on Android there are no media controls available in the notification drawer or the Lock Screen

Is there something (a prop?) we need to enable this functionality?

**Comment by namgaxilem** [comment]
Same here, any ideas?

**Comment by HazAnwar** [comment]
In case someone comes across this in the future, the standalone Chrome on Android does support the W3C JavaScript `MediaSession` API out of the box but the Android Chrome WebView currently does **NOT** (according to [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/Media_Session_API#browser_compatibility)).

[A feature request has been raised on the Chromium tracker](https://issues.chromium.org/issues/40611412) but it appears it doesn't have much traction.

I suspect you'll have to spin up a [native `MediaSession`](https://developer.android.com/reference/android/media/session/MediaSession) yourself and manually map controls and metadata.
