### ISSUE TITLE
安卓release显示白屏

### ISSUE THREAD

**Issue by octopus3** [react-native-webview/react-native-webview#2887]
android切换到Release版，打开页面会打不开网页，但是debug的包能打开对应网页
请问这种是什么情况呢？

**Comment by octopus3** [comment]
我试过给webview加了个背景色红色，发现release的版本会有一瞬间是红色，然后变成白色
我是用它来打开这两个网页：http://funfamily.online/terms.html     http://funfamily.online/privacy.html
当然也试过用它来打开其他网页，结果发现都是一瞬间红色然后就会变白

**Comment by octopus3** [comment]
logcat 有返回
`'webview error ==> ', { dispatchConfig: { registrationName: 'onLoadingError' },
                                                                                                      _targetInst: 
                                                                                                       { tag: 5,
                                                                                                         key: 'webViewKey',
                                                                                                         elementType: 'RNCWebView',
                                                                                                         type: 'RNCWebView',
                                                                                                         stateNode: 
                                                                                                          { _nativeTag: 645,
                                                                                                            _children: [],
                                                                                                            viewConfig: 
                                                                                                             { directEventTypes: 
                                                                                                                { topLoadingError: { registrationName: 'onLoadingError' },
                                                                                                                  topRenderProcessGone: { registrationName: 'onRenderProcessGone' },
                                                                                                                  topMessage: { registrationName: 'onMessage' },
                                                                                                                  topShouldStartLoadWithRequest: { registrationName: 'onShouldStartLoadWithRequest' },
                                                                                                                  topLoadingProgress: { registrationName: 'onLoadingProgress' },
                                                                                                                  topLoadingFinish: { registrationName: 'onLoadingFinish' },
                                                                                                                  topHttpError: { registrationName: 'onHttpError' },
                                                                                                                  topScroll: { registrationName: 'onScroll' },
                                                                                                                  topLoadingStart: { registrationName: 'onLoadingStart' },
                                                                                                                  topAccessibilityAction: { registrationName: 'onAccessibilityAction' },
                                                                                                                  topMomentumScrollEnd: { registrationName: 'onMomentumScrollEnd' },
                                                                                                                  topContentSizeChange: { registrationName: 'onContentSizeChange' },
                                                                                                                  topScrollBeginDrag: { registrationName: 'onScrollBeginDrag' },
                                                                                                                  topClick: { registrationName: 'onClick' },
                                                                                                                  topSelectionChange: { registrationName: 'onSelectionChange' },
                                                                                                                  topMomentumScrollBegin: { registrationName: 'onMomentumScrollBegin' },
                                                                                                                  topScrollEndDrag: { registrationName: 'onScrollEndDrag' },
                                                                                                                  topLayout: { registrationName: 'onLayout' },
                                                                                                                  onGestureHandlerEvent: { registrationName: 'onGestureHandlerEvent' },
                                                                                                                  onGestureHandlerStateChange: { registrationName: 'onGestureHandlerStateChange' } },
                                                                                                               NativeProps: 
                                                                                                                { applicationNameForUserAgent: 'String',
                                                                                                                  allowFileAccessFromFileURLs: 'boolean',
                                                                                                                  onTouchCancel: 'boolean',
                                                                                                                  cacheEnabled: 'boolean',
                                                                                                                  allowUniversalAccessFromFileURLs: 'boolean',
                                                                                                                  onStartShouldSetResponder: 'boolean',
                                                                                                                  rotation: 'number',
                                                                                                                  padding: 'mixed',
                                                                                                                  onTouchStart: 'boolean',
                                                                                                                  elevation: 'number',
                                                                                                                  paddingTop: 'mixed',
                                                                                                                  javaScriptEnabled: 'boolean',
                                                                                                                  flex: 'number',
                                                                                                                  transform: 'Array',
                                                                                                                  onStartShouldSetResponderCapture: 'boolean',
                                                                                                                  urlPrefixesForDefaultIntent: 'Array',
                                                                                                                  onPointerMoveCapture: 'boolean',
                                                                                                                  basicAuthCredential: 'Map',
                                                                                                                  importantForAccessibility: 'String',
                                                                                                                  renderToHardwareTextureAndroid: 'boolean',
                                                                                                                  onContentSizeChange: 'boolean',
                                                                                                                  marginBottom: 'mixed',
                                                                                                                  showsHorizontalScrollIndicator: 'boolean',
                                                                                                                  cacheMode: 'String',
                                                                                                                  paddingVertical: 'mixed',
                                                                                                                  marginLeft: 'mixed',
                                                                                                                  bottom: 'mixed',
                                                                                                                  borderStartWidth: 'number',
                                                                                                                  paddingBottom: 'mixed',
                                                                                                                  onResponderTerminationRequest: 'boolean',
                                                                                                                  accessibilityRole: 'String',
                                                                                                                  scaleY: 'number',
                                                                                                                  allowFileAccess: 'boolean',
                                                                                                                  textZoom: 'number',
                                                                                                                  alignSelf: 'String',
                                                                                                                  scaleX: 'number',
                                                                                                                  borderTopWidth: 'number',
                                                                                                                  onPointerLeave: 'boolean',
                                                                                                                  incognito: 'boolean',
                                                                                                                  borderLeftWidth: 'number',
                                                                                                                  accessibilityCollection: 'Map',
                                                                                                                  borderRightWidth: 'number',
                                                                                                                  injectedJavaScript: 'String',
                                                                                                                  onResponderEnd: 'boolean',
                                                                                                                  lackPermissionToDownloadMessage: 'String',
                                                                                                                  onResponderTerminate: 'boolean',
                                                                                                                  showsVerticalScrollIndicator: 'boolean',
                                                                                                                  geolocationEnabled: 'boolean',
                                                                                                                  marginEnd: 'mixed',
                                                                                                                  onPointerLeaveCapture: 'boolean',
                                                                                                                  translateX: 'number',`

**Comment by TheAlmightyBob** [comment]
logcat 看起来不完整。 看不到出错信息。还有吗？

http://funfamily.online 不用TLS。你也试过https吗？可能需要`android:usesCleartextTraffic="true"` (https://flutter-developer.medium.com/android-how-to-allow-all-network-connection-types-http-and-https-bacac8809621)

debug 已经有，因为React Native Packager需要，但是release没有。

**Comment by octopus3** [comment]
Android发出来的信息能复制出来的就是以上的内容了，我可以再尝试一下按你设置的来做

**Comment by octopus3** [comment]
我在AndroidManifest中的application上添加了这个属性`android:usesCleartextTraffic="true"`之后发现可以打开了
