### ISSUE TITLE
enableApplePay props make onNavigationStateChange not working well

### ISSUE THREAD

**Issue by samuelBenh** [react-native-webview/react-native-webview#2894]
Hello,

I am usign a shopify checkout webview in my react native application. This webview contain Apple pay button so i have to add the enableApplePay props. I also need to handle url change to report the payment step to my analytics.

i am using the onNavigationStateChange props to handle the url modification during the checkout process

When i have the enableApplePay props active, the onNavigationStateChange only report my first url but not when the url is changing.

Someone know how to fix this problem please ?

Thanks

**Comment by sahilkashyap64** [comment]
@eazzyLEE  **onNavigationStateChange** was not getting the url change, **onLoadProgress** was able to get the changes
```
onLoadProgress={({ nativeEvent }) => {
           console.log("onLoadProgress url",nativeEvent.url);  
           if(nativeEvent.url.includes('thank-you')){
           //NAVIGATE TO SOME SCREEN
           } 
          }}
```

**Comment by danyalutsevich** [comment]
this issue still exist in webview 13.6.4

i dont want to use onLoadProgress because it can be called multiple times

**Comment by art3mHQ** [comment]
As for react-native-webview@13.8.6 onLoadProgress also not working as well as onNavigationStateChange looks like NavigationStateChange not fired up one time, then if in success screen i press goback it catches the change
