### ISSUE TITLE
Debug build v11.26.1

### ISSUE THREAD

**Issue by yoshida-git-ai** [react-native-webview/react-native-webview#2895]
aar succeeds but APK fails
What is the solution?

**Comment by TheAlmightyBob** [comment]
Please share exact error logs and a sample project that reproduces the error

**Comment by yoshida-git-ai** [comment]
Little has changed since I downloaded v11.26.1

apply plugin: 'com.android.application'
//apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

something like this

`C:\Users\yoshida\Desktop\react-native-webview-11.26.1\android>gradle assembleDebug
Starting a Gradle Daemon, 5 incompatible Daemons could not be reused, use --status for details
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: 予期しない要素(URI:""、ローカル:"base-extension")です。予期される要素は<{}codename>,<{}layoutlib>,<{}api-level>です
> Task :stripDebugDebugSymbols FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':stripDebugDebugSymbols'.
> No version of NDK matched the requested version 20.0.5594570. Versions available locally: 17.2.4988734, 18.1.5063045, 20.1.5948944, 21.1.6352462, 21.4.7075529

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 6s
24 actionable tasks: 1 executed, 23 up-to-date
`

**Comment by yoshida-git-ai** [comment]
Successful APK generation
I was short of NDK

Now, where can I change the URL of the web to be displayed?

**Comment by TheAlmightyBob** [comment]
https://github.com/react-native-webview/react-native-webview/blob/master/docs/Guide.md#basic-url-source

**Comment by yoshida-git-ai** [comment]
thank you
i read that link
I have successfully completed a release build as well
android-release-unsigned.apk

But URL which file?
I just want to try the changes first
\Desktop\react-native-webview-11.26.1\src
?

**Comment by TheAlmightyBob** [comment]
I'm sorry I don't understand the question.

**Comment by yoshida-git-ai** [comment]
Is the Basic URL Source already a file somewhere?

Or do you create the file yourself?

Build was successful, sorry im new to RN

**Comment by TheAlmightyBob** [comment]
I don't know what "file" you're referring to. The "Basic URL Source" example shows how to load content from the internet via URL. If you instead wanted to load your own local custom HTML content, then of course you would create that.

**Comment by yoshida-git-ai** [comment]
Inside src there are some index files

For example, to display the top page of Github when the app is started, write it in index.js?
Or another new file?

**Comment by TheAlmightyBob** [comment]
It sounds like you're just asking how to organize your React Native code? That's up to, and there are lots of great resources/examples for getting started with React Native. This issue thread is not the best place.

**Comment by yoshida-git-ai** [comment]
It's about the basics, like you said.
However I was looking for a way to apply it to this project
But thank you for your kind guidance anyway
