### ISSUE TITLE
Multiple isolated sessions using react-native-webview

### ISSUE THREAD

**Issue by SergGrey1992** [react-native-webview/react-native-webview#2901]
I am trying to create a React Native app where a user can be logged in to two or more Facebook or Instagram accounts simultaneously (within different webviews) and easily toggle between them within the React Native app. This requires each webview to have its own session/cookies and not share them with the other open webviews.

The default behavior of react-native-webview is for webviews to share their cookies with the other webviews.

I have tried the following, but when I log into Facebook on one webview, then I refresh the other webview, the other webview is also logged in. (For now I am only concerned with getting this working on iOS devices. I am testing this using RN and an iPhone 11)

<WebView
                    incognito={true}
                    cacheEnabled={false}
                    useSharedProcessPool={false}
                    thirdPartyCookiesEnabled={false}
                    sharedCookiesEnabled={false}
                    originWhitelist={['*']}
                    source={{
                        uri: 'https://www.facebook.com/login',
                    }}
                    style={{ width: '100%', height: '100%' }}
                    onNavigationStateChange={(e) => {
                        console.log('e', e)
                    }}
                />

**Comment by Shubham-raut** [comment]
Similar issue on android. All webviews have same data store including canGoBack state. 
Looks loke they are following Singleton pattern.

**Comment by erickne** [comment]
@SergGrey1992 Did you make it work?

**Comment by kgulpinar** [comment]
There is still a issue
