### ISSUE TITLE
navigator.mediaDevices.getUserMedia not working with insecure (http) urls

### ISSUE THREAD

**Issue by veeyka** [react-native-webview/react-native-webview#2902]
hi.
i have a webview addressed to a http url and its says getUserMedia is undefined . before this my address was a secure url (https) and it was ok since my url was an https address . is there any solution to fix this with an http url ? because my destination page url is accessing camera and mic . i know that chrome is allowing secure websites to use camera and mic . but there are many ppl using chrome and i need to fix it with chrome .
do i have to only use a https server or there is an solution ?

**Comment by jawebb-school** [comment]
These are relatively old responses, so I don't know if they still work, but there is a stackoverflow thread with some possible solutions: https://stackoverflow.com/questions/34165614/navigator-mediadevices-getusermedia-is-not-working-and-neither-does-webkitgetuse 

In general, I don't think you can get around using getusermedia in an insecure format... It would be best to use HTTPS instead of HTTP.

**Comment by Chuong1928** [comment]
ds

**Comment by Chuong1928** [comment]
sdfsdf

**Comment by Chuong1928** [comment]
asdsada

**Comment by Chuong1928** [comment]
asdsada

**Comment by Chuong1928** [comment]
bay Đà Lạt

**Comment by Chuong1928** [comment]
từ từ nói

**Comment by Chuong1928** [comment]
Đây là Đài Tiếng nói Việt Nam thám tử Hà Nội câu đấy mà sửa một từ nhỏ có xóa câu đấy nó không Tôi khỏe ai đâu mà xóa được cái thế thôi phần mềm số điện thoại hết pin rồi

**Comment by Chuong1928** [comment]
tuyến xe buýt Đà Nẵng

**Comment by Chuong1928** [comment]
aaaaaaaaaaaaaaaaaaaa asdasd

**Comment by Chuong1928** [comment]
ádasdasdas

**Comment by Chuong1928** [comment]
This is Voice of Vietnam Radio from Hanoi reset Việt Nam Việt Nam cho con nít Việt Nam cho con nít tiếng Việt dịch ra tiếng Anh nó bấm gì nó nghe nó nói nó phải nói tiếng Anh chứ ngôn ngữ nói khác nhau cái gì phát nhảy Tường có lúc bấm vào voice chat đây thì lại có một ô chọn

**Comment by Chuong1928** [comment]
SÁ

**Comment by adisonmasih** [comment]
Always use SSL Certificates. They don't only help you but even your users!
There are many Organisations like [Let's Encrypt](https://letsencrypt.org/) which provide SSLCs for free.
