### ISSUE TITLE
webview very slow on android

### ISSUE THREAD

**Issue by sGabunia** [react-native-webview/react-native-webview#2904]
Bug description:
I have whole app in  webview. It loads in 3-4 seconds on ios, but loads 40 seconds on android. It is not normal. What can be the problem? On mobile browser on android it loads in 3-4 seconds

**Environment:**
 - OS: Android;
 - OS version: 11;
 - react-native version: 0.71.4
 - react-native-webview version: 11.26.0
 - "expo": "^48.0.0",

**Comment by batuhanorhanakinon** [comment]
Hi @sGabunia , do you use **renderLoading**  props?

**Comment by sGabunia** [comment]
@batuhanorhanakinon 
> Hi @sGabunia , do you use **renderLoading** props?

Yes
