### ISSUE TITLE
Prevent the page from asking for access to geolocation

### ISSUE THREAD

**Issue by afzdev13** [react-native-webview/react-native-webview#2907]
Today I use the webview that directs to a page whose code I cannot change and it always asks for the geolocation, this feature should continue to work if the page is accessed directly through the browser but not when through our app that uses the webview on that page. This has caused discomfort for many users.

It could have a parameter that always denies or accepts geolocation, thus avoiding this discomfort in users

**Comment by vchhetry** [comment]
Facing same issue in Android 13, works for lower version.
