### ISSUE TITLE
Hello. Is there a property or setting for setPluginState on Android? If so, I can't seem to find it. Any help would be appreciated.

### ISSUE THREAD

**Issue by Louis3dts** [react-native-webview/react-native-webview#2910]
**Bug description:**

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS:
 - OS version:
 - react-native version:
 - react-native-webview version:

**Comment by TheAlmightyBob** [comment]
That setting was deprecated by Android many years ago...?
