### ISSUE TITLE
Execution failed for task ':react-native-webview:compileDebugJavaWithJavac'. on RN 0.71.5 and webview 12.0.0

### ISSUE THREAD

**Issue by firehand33** [react-native-webview/react-native-webview#2912]
**Bug description:**

/Users/danferd.lan/Workspace/SMH/node_modules/react-native-webview/android/src/oldarch/com/reactnativecommunity/webview/RNCWebViewManager.java:32: error: duplicate class: com.reactnativecommunity.webview.RNCWebViewManager
public class RNCWebViewManager extends SimpleViewManager<RNCWebView> {
       ^
/Users/danferd.lan/Workspace/SMH/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java:132: error: cannot find symbol
  protected WebViewConfig mWebViewConfig;
            ^
  symbol:   class WebViewConfig
  location: class RNCWebViewManager
/Users/danferd.lan/Workspace/SMH/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java:147: error: cannot find symbol
  public RNCWebViewManager(WebViewConfig webViewConfig) {
                           ^
  symbol:   class WebViewConfig
  location: class RNCWebViewManager
/Users/danferd.lan/Workspace/SMH/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java:141: error: cannot find symbol
    mWebViewConfig = new WebViewConfig() {
                         ^
  symbol:   class WebViewConfig
  location: class RNCWebViewManager
/Users/danferd.lan/Workspace/SMH/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java:227: error: method grantFileDownloaderPermissions in class RNCWebViewModule cannot be applied to given types;
        if (module.grantFileDownloaderPermissions()) {
                  ^
  required: String,String
  found: no arguments
  reason: actual and formal argument lists differ in length
/Users/danferd.lan/Workspace/SMH/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java:228: error: method downloadFile in class RNCWebViewModule cannot be applied to given types;
          module.downloadFile();
                ^
  required: String
  found: no arguments
  reason: actual and formal argument lists differ in length
/Users/danferd.lan/Workspace/SMH/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java:256: error: cannot find symbol
        view.getSettings().setAppCachePath(ctx.getCacheDir().getAbsolutePath());
                          ^
  symbol:   method setAppCachePath(String)
  location: class WebSettings
/Users/danferd.lan/Workspace/SMH/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java:258: error: cannot find symbol
        view.getSettings().setAppCacheEnabled(true);
                          ^
  symbol:   method setAppCacheEnabled(boolean)
  location: class WebSettings
/Users/danferd.lan/Workspace/SMH/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java:262: error: cannot find symbol
      view.getSettings().setAppCacheEnabled(false);
                        ^
  symbol:   method setAppCacheEnabled(boolean)
  location: class WebSettings
/Users/danferd.lan/Workspace/SMH/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java:411: error: cannot find symbol
    view.getSettings().setAppCacheEnabled(!enabled);
                      ^
  symbol:   method setAppCacheEnabled(boolean)
  location: class WebSettings
/Users/danferd.lan/Workspace/SMH/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java:958: error: no suitable method found for startPhotoPickerIntent(ValueCallback<Uri[]>,Intent,String[],boolean)
      return getModule(mReactContext).startPhotoPickerIntent(filePathCallback, intent, acceptTypes, allowMultiple);
                                     ^
    method RNCWebViewModule.startPhotoPickerIntent(ValueCallback<Uri>,String) is not applicable
      (actual and formal argument lists differ in length)
    method RNCWebViewModule.startPhotoPickerIntent(ValueCallback<Uri[]>,String[],boolean) is not applicable
      (actual and formal argument lists differ in length)
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/danferd.lan/Workspace/SMH/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
11 errors

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS: macOS
 - OS version: 13.2
 - react-native version: 0.71.5
 - react-native-webview version: 12.0.0

**Comment by WoLewicki** [comment]
Did you try and clear all the caches @firehand33 ?

**Comment by firehand33** [comment]
ya...tried

./android/gradlew clean -p ./android/
npm start -- --reset-cache
rm -rf ~/.gradle/caches/
rm -rf ~/.gradle/daemon/

**Comment by Titozzz** [comment]
Did you update from 11 or clean new install directly to 12 ? @firehand33

**Comment by firehand33** [comment]
It worked after delete node_modulea. Thanks you.

**Comment by alepmustaqim03** [comment]
I got this error even tho i clean and delete node module its happen on latest version here the error :

> Task :react-native-webview:compileDebugJavaWithJavac FAILED
851 actionable tasks: 659 executed, 192 up-to-date
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/convep_office/Desktop/upgrade_version_station/jland_owner/node_modules/@react-native-community/cameraroll/android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/convep_office/Desktop/upgrade_version_station/jland_owner/node_modules/@react-native-community/async-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
warning: unknown enum constant Mode.LOCAL
  reason: class file for com.facebook.infer.annotation.Nullsafe$Mode not found
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 warning
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/convep_office/Desktop/upgrade_version_station/jland_owner/node_modules/@react-native-firebase/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/convep_office/Desktop/upgrade_version_station/jland_owner/node_modules/@react-native-firebase/crashlytics/android/src/main/java/io/invertase/firebase/crashlytics/ReactNativeFirebaseCrashlyticsModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/convep_office/Desktop/upgrade_version_station/jland_owner/node_modules/react-native-add-calendar-event/android/src/main/java/com/vonovak/AddCalendarEventModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/convep_office/Desktop/upgrade_version_station/jland_owner/node_modules/react-native-add-calendar-event/android/src/main/java/com/vonovak/AddCalendarEventModule.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/convep_office/Desktop/upgrade_version_station/jland_owner/node_modules/react-native-image-resizer/android/src/main/java/fr/bamlab/rnimageresizer/ImageResizerModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/convep_office/Desktop/upgrade_version_station/jland_owner/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/convep_office/Desktop/upgrade_version_station/jland_owner/node_modules/react-native-image-picker/android/src/main/java/com/imagepicker/Utils.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/convep_office/Desktop/upgrade_version_station/jland_owner/node_modules/react-native-orientation-locker/android/src/main/java/org/wonday/orientation/OrientationModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/convep_office/Desktop/upgrade_version_station/jland_owner/node_modules/react-native-print/android/src/main/java/com/christopherdro/RNPrint/RNPrintModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/convep_office/Desktop/upgrade_version_station/jland_owner/node_modules/react-native-quick-actions/android/src/main/java/com/reactNativeQuickActions/AppShortcutsModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/convep_office/Desktop/upgrade_version_station/jland_owner/node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/VirtualView.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/Users/convep_office/Desktop/upgrade_version_station/jland_owner/node_modules/react-native-webview/android/src/oldarch/com/reactnativecommunity/webview/RNCWebViewManager.java:26: error: duplicate class: com.reactnativecommunity.webview.RNCWebViewManager
public class RNCWebViewManager extends ViewGroupManager<RNCWebViewWrapper> {
       ^
/Users/convep_office/Desktop/upgrade_version_station/jland_owner/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java:107: error: cannot find symbol
  protected WebViewConfig mWebViewConfig;
            ^
  symbol:   class WebViewConfig
  location: class RNCWebViewManager
/Users/convep_office/Desktop/upgrade_version_station/jland_owner/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java:116: error: cannot find symbol
  public RNCWebViewManager(WebViewConfig webViewConfig) {
                           ^
  symbol:   class WebViewConfig
  location: class RNCWebViewManager
/Users/convep_office/Desktop/upgrade_version_station/jland_owner/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java:110: error: cannot find symbol
    mWebViewConfig = new WebViewConfig() {
                         ^
  symbol:   class WebViewConfig
  location: class RNCWebViewManager
/Users/convep_office/Desktop/upgrade_version_station/jland_owner/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java:190: error: incompatible types: Intent cannot be converted to String[]
        return getModule(reactContext).startPhotoPickerIntent(filePathCallback, intent, acceptTypes, allowMultiple);
                                                                                ^
/Users/convep_office/Desktop/upgrade_version_station/jland_owner/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java:250: error: method grantFileDownloaderPermissions in class RNCWebViewModule cannot be applied to given types;
        if (module.grantFileDownloaderPermissions()) {
                  ^
  required: String,String
  found: no arguments
  reason: actual and formal argument lists differ in length
/Users/convep_office/Desktop/upgrade_version_station/jland_owner/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java:251: error: method downloadFile in class RNCWebViewModule cannot be applied to given types;
          module.downloadFile();
                ^
  required: String
  found: no arguments
  reason: actual and formal argument lists differ in length
/Users/convep_office/Desktop/upgrade_version_station/jland_owner/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java:770: error: incompatible types: String cannot be converted to WritableMap
      dispatchEvent(this, new TopMessageEvent(this.getId(), message));
                                                            ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/convep_office/Desktop/upgrade_version_station/jland_owner/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
8 errors

> There is something fishy going on on your side
> 
> > /Users/danferd.lan/Workspace/SMH/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java:132: error: cannot find symbol
> > protected WebViewConfig mWebViewConfig;
> > ^
> 
> That file doesn't exist on 12.0.0 and shouldn't be there.
> 
> Maybe try cleaning your node_modules
