### ISSUE TITLE
[Issue] [IOS] Incorrect auto-fill behavior with one-time-code in iOS WebView.

### ISSUE THREAD

**Issue by A-Yatsyk** [react-native-webview/react-native-webview#2913]
### **Hi**

**We are experiencing an issue with the auto-fill feature on iOS WebView when using one-time-code. After the first successful auto-fill of the code, subsequent attempts to auto-fill the code fail, and the user is presented with incorrect suggestions ("Passwords").**

**Current behavior:**
- Open the page with the one-time password (for the first time).
- After receiving the code, the auto-fill suggestion for the previously sent code is shown correctly.
- Open the same page with the one-time-code field (subsequent times)
- The auto-fill suggestion for the previously sent code is ignored and replaced with the suggestion to fill in a saved password ("Passwords"), making it impossible to auto-fill the one-time-code again unless the app is reinstalled.

**Expected behavior:**
The auto-fill suggestion for the one-time code that was received should always be presented for fields of this type, regardless of the number of times the page is opened.

<img width="806" alt="Screenshot 2023-04-03 at 14 11 39" src="https://user-images.githubusercontent.com/20336643/229493259-b503e171-a521-4c9b-9c62-0b71c42fe025.png">

**In any case, the suggestion does not match the field type and should not offer auto-filling of the password for a field with a one-time password type, etc.**

**How does this affect our application:**
A user installs the application, logs in to the application, and then undergoes additional 2FA verification with a one-time password via SMS on the WebView form. The first verification is carried out according to the rules with the suggestion to auto-fill the code from the SMS. Later, the user logs in again after restarting the application, etc., but auto-filling using the one-time password no longer works as it should or as it did the first time because there is only a "passwords" suggestion on the keyboard for auto-filling.

Fragment of HTML code:

```
<form class="form" action="{some action here}" method="post">
    <input type="number" pattern="[0-9]*" inputmode="numeric" placeholder="Enter code" autofocus="" autocomplete="one-time-code" data-val="true" data-val-maxlength="" data-val-maxlength-max="10" id="Code" name="Code" value="">
</form>
```

Environment:

OS: iOS
OS version: 16.4
react-native version: 0.70.4
react-native-webview version: 11.26.1

**Comment by oleksandr-dziuban** [comment]
Same for our app, OTP SMS code is showing only once on input with autocomplete="one-time-code".
Once form submitted, for the next sessions (and next attempts to get SMS code on keyboard) we just can see a `Passwords` button only on keyboard.

Does someone have any ideas how to fix that behaviour?

Thanks

**Comment by wanted-o** [comment]
We have the same behavior in our app, could anyone take a look on the issue?

Thanks!

**Comment by Titozzz** [comment]
Can you try reproducing this in safari directly ?

**Comment by A-Yatsyk** [comment]
@Titozzz Hello
No, works fine on Safari (as expected)

**Comment by oleksandr-dziuban** [comment]
No, Safari browser work fine.
It's only related to WebView engine

**Comment by alinaashortiya** [comment]
Hello, I'm facing exactly the same issue in the app,  could you please take a look at this issue?
