### ISSUE TITLE
Inspection of Web Content not working with iOS 16.4+

### ISSUE THREAD

**Issue by AwesomeAndrewMK** [react-native-webview/react-native-webview#2914]
**Bug description:**

With iOS 16.4 comes a WebKit update which requires to enable the possibility to inspect the app for debugging WebView via Safari, by default it's false. So now debugging isn't working.

Please see details on the official [WebKit resource](https://webkit.org/blog/13936/enabling-the-inspection-of-web-content-in-apps/)

**To Reproduce:**

* Run React Native iOS app with WebView and any web page
* Open Safari -> in Menu bar select Develop -> Your device (Simulator - iPhone 14 Pro... - iOS 16.4)
* See "No Inspectable Applications"

**Expected behavior:**

The web page should be available for inspection

**Screenshots/Videos:**

<img width="775" alt="Screenshot 2023-04-03 at 18 12 50" src="https://user-images.githubusercontent.com/42909164/229552620-3cabc908-d819-4b9f-8f6e-99cc52f02cf0.png">

**Environment:**
 - OS: iOS
 - OS version: 16.4
 - react-native version: 0.70.7 or higher
 - react-native-webview version: 11.26.0 or higher

**Comment by Titozzz** [comment]
Will probably regroup with this: https://github.com/react-native-webview/react-native-webview/pull/2896

**Comment by alexfoxy** [comment]
I am also experiencing this problem

**Comment by vladanyes** [comment]
same for me

**Comment by zakharchenkoAndrii** [comment]
same 😕

**Comment by gfaraj** [comment]
Any updates to this?

**Comment by cah-adrian-perez** [comment]
I'm currently using an older version of `react-native-webview` and a temporary workaround that I've been using for local development is to edit a swift file in my node_modules that sets the inspectable property right after `_webView` is allocated.

For example,

https://github.com/react-native-webview/react-native-webview/blob/681aac4fe7e35834264daa01b67a9893c4a9ebe7/apple/RNCWebViewImpl.m#L416

```swift
_webView = [[WKWebView alloc] initWithFrame:self.bounds configuration: wkWebViewConfig]; 
_webView.inspectable = YES;
```

**Comment by munsangu** [comment]
I also experienced this problem. I solved it by adding the code below (iOS 14 Version, Swift 5.x Version, WKWebView)
`
if #available(iOS 16.4, *) {
   webView.isInspectable = true
}
`

**Comment by Aure77** [comment]
https://webkit.org/blog/13936/enabling-the-inspection-of-web-content-in-apps/

**Comment by krini** [comment]
Would be nice to get this to work.

**Comment by valerykonst** [comment]
Same problem :(

**Comment by Titozzz** [comment]
https://github.com/react-native-webview/react-native-webview/pull/2937#issuecomment-1585635913

**Comment by annewanghy** [comment]
it works now, thank you so much!
