### ISSUE TITLE
iOS build error: 'foundation/Foundation.h' file not found

### ISSUE THREAD

**Issue by Romick2005** [react-native-webview/react-native-webview#2915]
![image](https://user-images.githubusercontent.com/17779660/229819302-053b2f8b-a9cb-4185-a57c-e34dd9e8e819.png)

Suggested fix: 
Replace 
[`#import <foundation/Foundation.h>`](https://github.com/react-native-webview/react-native-webview/blob/b22d25f5a986f7c0ea705f1a363cf227efaeea33/apple/RNCWebViewDecisionManager.h#L1)
 with
`#import <Foundation/Foundation.h>`

**Comment by Titozzz** [comment]
Will fix !
