### ISSUE TITLE
infinite loading on Android when triggering a reload while having a custom userAgent set

### ISSUE THREAD

**Issue by dawidvdh** [react-native-webview/react-native-webview#2918]
Hi! found a rather strange bug on Android when using a custom userAgent and reloading via the ref.

**Bug description:**

When supplying a custom userAgent to the webview and triggering a reload via a webview ref it will result in the webview continuously loading.

**To Reproduce:**

I have created [an MRE here](https://github.com/dawidvdh/webview-android-reload-mve) however the code snippet would simply be:

```
function App(): JSX.Element {
  const webViewRef = useRef<WebView>(null);
  return (
    <SafeAreaView style={{flex: 1}}>
      <Button
        title="reload"
        onPress={() => {
          webViewRef.current?.reload();
        }}
      />
      <WebView
        ref={webViewRef}
        source={{uri: 'https://reactnative.dev/'}}
        userAgent="Mozilla/5.0 (iPhone; CPU iPhone OS 14_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1"
        style={{flex: 1}}
      />
    </SafeAreaView>
  );
}
```

**Expected behavior:**

The expected behaviour is that even with a custom userAgent provided to the WebView one would be able to reload the WebView with out it getting stuck in a loading loop.

**Screenshots/Videos:**

**Environment:**
 - OS: macOS
 - OS version:  13.2.1
 - react-native version: 0.71.6
 - react-native-webview version: 12.0.1

**Comment by TheAlmightyBob** [comment]
I cannot access your "MVE" link (nor am I sure what "MVE" means). Please share an accessible repro.

I tried using reload/userAgent/Android in an Expo Snack and it behaved as expected: https://snack.expo.dev/nEDTGH5hH

**Comment by dawidvdh** [comment]
Hey! MVE typically means Minimal Viable Example but perhaps that's no longer a relevant term... maybe is MR (minimal repo) now? Nevertheless, you are correct I accidentally placed an incorrect link, and have now updated it. 

I have tested on two physical Android devices and both times the behaviour was the same as described above, let me know if you get the same behaviour from the repo I have shared or if I am just doing something silly.

**Comment by dereklucas** [comment]
I have run into the same thing. Removing the user agent fixed it immediately. I'll see if I can reproduce it in a snack.

**Comment by dereklucas** [comment]
Video of the bug, but it really is just as described.
https://user-images.githubusercontent.com/1444472/234112614-ff598358-b46a-4834-b95e-742e5e8960a6.mov

**Comment by dereklucas** [comment]
I was able to work around this by using `webViewRef.current.injectJavaScript('window.location.reload(true)');` 😭
I've added that and a user agent toggle to the reproduction: https://snack.expo.dev/@dereklucas/android-custom-useragent-infinite-reload-reproduction

**Comment by kristerkari** [comment]
We have been able to reproduce the same bug with just a minimal test case on Android (Honor 20/YAL-L21) with using `<Webview />`, setting the `userAgent`, and calling `webViewRef.current?.reload()`.

Like said above, it only seems to happen when the `userAgent` is set.

**Comment by dannyhw** [comment]
I have this problem even without setting the userAgent, only for android but it just never stops loading when I call reload.

**Comment by allanzi** [comment]
> I was able to work around this by using `webViewRef.current.injectJavaScript('window.location.reload(true)');` 😭 I've added that and a user agent toggle to the reproduction: https://snack.expo.dev/@dereklucas/android-custom-useragent-infinite-reload-reproduction

Thanks @dereklucas, this workaround worked for me!

**Comment by dereklucas** [comment]
I’ll test and see if it’s resolved, but I don’t have any reason to think it’s changed.

**Comment by muhammadarsal** [comment]
Its still happening

**Comment by dereklucas** [comment]
I’ll test with the newest react native when it comes to expo, but I have to assume it’s still happening

**Comment by roniemartinez** [comment]
This is still happening, removing the custom user agent fixed it.

**Comment by edw-nmv** [comment]
Any updates? Its still happening

**Comment by CristinaBloqhouse** [comment]
Hi! It's happening to me too, any solution?

**Comment by dab-code** [comment]
Still happening. Have worked around it by using the `injectJavaScript` solution given by @dereklucas. Hoping for a solution :crossed_fingers:

**Comment by tkmin** [comment]
wow,
removing userAgent works on android
#2826

**Comment by datachanturia** [comment]
Still hapening

**Comment by dawidvdh** [comment]
Been over a year now so Incase anyone runs into this, we settled on the following solution:

```
  const reload = useCallback(() => {
    if (Platform.OS === 'android') {
      return webViewRef.current?.injectJavaScript('window.location.reload()')
    }

    return webViewRef.current?.reload()
  }, [])
```

Previously we has also incremented the `key` prop of the webview on android which forced the webview to remount and effectively reload the page.
