### ISSUE TITLE
Right operand of 'in' is not and object

### ISSUE THREAD

**Issue by firehand33** [react-native-webview/react-native-webview#2919]
**Bug description:**
Getting this, "Right operand of 'in' is not and object" error after upgrading my existing project from RN 0.67.5 and webview version 9.0.2 to RN 0.71.6 and webview version 12.0.1.

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**
![Simulator Screen Shot - iPhone 13 - 2023-04-06 at 08 44 50](https://user-images.githubusercontent.com/6487857/230245208-cddbae2a-42ca-45bd-85f9-3b4cbc9f5950.png)

**Environment:**
 - OS: macOS
 - OS version: 13.2
 - react-native version: 0.71.6
 - react-native-webview version: 12.0.1

**Comment by TheAlmightyBob** [comment]
Please share a sample project that reproduces the error. There are too many variables with an upgrade like that.

**Comment by whitelizard** [comment]
I have the same. I need to downgrade to 0.69 to get rid of the error.

**Comment by whitelizard** [comment]
When I switch the input field to not being "outlined" the error disappears!
(I'm using react-native-paper)

**Comment by nimeshmaharjan1** [comment]
> When I switch the input field to not being "outlined" the error disappears! (I'm using react-native-paper)

Im getting this issue too i did not get this what do you mean by switchting the input field to not being "outliend"?

The below code is giving me the error
```
<TextInput
          mode="flat"
          label="Email"
          //   value={text}
          //   onChangeText={text => setText(text)}
        />
```

**Comment by pencilcheck** [comment]
I am using react native ui lib from wix, and all their textfield is outlined and giving me the same error...
