### ISSUE TITLE
Cannot convert null value to object

### ISSUE THREAD

**Issue by SamWaldock** [react-native-webview/react-native-webview#2920]
Since the major update of 12.0.0 I'm receiving this error: `Cannot convert null value to object`.
It's most likely due to an undefined uri getting passed to the Webview. The parameter accepts undefined so this should not be an issue. The reason why I pass undefined is due to [another issue](https://github.com/react-native-community/react-native-webview/issues/656) from years ago that hasn't been fixed yet.

This is my current code:
```
const [renderedOnce, setRenderedOnce] = useState(false);
const webViewRef = useWebViewRef();

<WebView
        style={styles.webViewContainer}
        ref={webViewRef}
        originWhitelist={['file://']}
        forceDarkOn={theme.key === ColorTheme.Dark}
        allowingReadAccessToURL={RNFS.DocumentDirectoryPath}
        allowFileAccess
        allowFileAccessFromFileURLs
        url={renderedOnce ? uri : undefined}
        hideNavigation
        onLoad={() => setRenderedOnce(true)}
/>
```

**Comment by judare** [comment]
You can try

`source={renderedOnce ? { uri: uri } : { uri: null }}`

instead of url prop

**Comment by bobwatcherx** [comment]
i have error like that

my code
```
import React, { useState } from 'react';
import { WebView } from 'react-native-webview';
import { ActivityIndicator,StyleSheet,View } from 'react-native';
import { useAssets } from 'expo-asset';

function App() {
  const [html, error] = useAssets(require('./assets/html/index.html'));
  const [isLoading, setIsLoading] = useState(true);

  const webViewProps = {
    javaScriptEnabled: true,
    androidLayerType: 'hardware',
    originWhitelist: ['*'],
    allowFileAccess: true,
    domStorageEnabled: true,
    mixedContentMode: 'always',
    allowUniversalAccessFromFileURLs: true,
    onLoad: () => {
      setIsLoading(false);
    },
    source: html,
  };

  return (
    <>
      {isLoading ? (
        // Tampilkan tampilan pembuka selama WebView memuat
        <ActivityIndicator style={styles.activityIndicator} size="large" />
      ) : null}
      <WebView {...webViewProps} />
    </>
  );
}

const styles = StyleSheet.create({
  activityIndicator: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
});

export default App;
```
```
 ERROR  TypeError: Cannot convert null value to object

This error is located at:
    in Unknown (created by App)
    in App (created by withDevTools(App))
    in withDevTools(App)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent), js engine: hermes
 ERROR  TypeError: Cannot convert null value to object

This error is located at:
    in Unknown (created by App)
    in App (created by withDevTools(App))
    in withDevTools(App)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent), js engine: hermes
```

**Comment by laurent22** [comment]
Once these issues are discovered, I wish they were listed under "Breaking changes".

**Comment by Esarhaddon** [comment]
Looks like this is still an issue on 13.2.2

**Comment by Esarhaddon** [comment]
> You can try
> 
> `source={renderedOnce ? { uri: uri } : { uri: null }}`
> 
> instead of url prop

For some `{ uri: null }` may work on iOS but cause an error on Android, whereas `{ uri: undefined }` seems to work on both platforms. Found this solution [here](https://github.com/react-native-webview/react-native-webview/issues/2995#issuecomment-1585733265).

**Comment by thiagomarti** [comment]
i have the same problem in mi proyect

`import { View, ScrollView, Text, Image, StyleSheet, TextInput, Button, FlatList } from 'react-native';
import React, { useEffect, useState } from 'react';
import { useNavigation } from '@react-navigation/native';
import { NavigationContainer } from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import { TouchableOpacity } from 'react-native';
import SQLite from 'react-native-sqlite-storage';

// Abre o crea la base de datos
const db = SQLite.openDatabase(
    { name: 'miBaseDeDatos.db', location: 'default' },
    () => {
      console.log('Base de datos abierta');
      // Ahora puedes realizar operaciones en la base de datos
    },
    (error) => {
      console.error('Error al abrir la base de datos', error);
    }
  );  

const Stack = createNativeStackNavigator();

export default function App() {
  return (
    <NavigationContainer independent={true}>
      <Stack.Navigator>
        <Stack.Screen
          name="Resto"
          component={FormularioRest}
          options={{ headerShown: false }}
        />
        <Stack.Screen
          name="Food"
          component={FormularioFood}
          options={{ headerShown: false }}
        />
        <Stack.Screen
          name="Menu"
          component={CrearMenu}
          options={{ headerShown: false }}
        />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

function FormularioRest() {
  const [restoName, setRestoName] = useState('');
  const [itemPrice, setItemPrice] = useState('');

  const navigation = useNavigation();

  const Iralmenu = () => {
    navigation.navigate('Menu');
  }

  const agregarItemAlinfo = () => {
    const newItem = {
      nombre: restoName,
      mesas: parseFloat(itemPrice),
    };

    // Ejecutar una consulta SQL para insertar el nuevo restaurante
    db.transaction((tx) => {
      tx.executeSql(
        'INSERT INTO restaurantes (nombre, mesas) VALUES (?, ?)',
        [newItem.nombre, newItem.mesas],
        () => {
          console.log('Restaurante insertado con éxito');
        },
        (error) => {
          console.error('Error al insertar el restaurante', error);
        }
      );
    });

    setRestoName('');
    setItemPrice('');
  };


  return (
    <View style={styles.container}>
      <Image
        source={require('../assets/images/logo-restoapp.png')}
        style={styles.logo}
      />
      <TextInput
        placeholder="Nombre del Restaurante"
        value={restoName}
        onChangeText={(text) => setRestoName(text)}
        style={styles.input}
      />
      <TextInput
        placeholder="Cantidad de mesas"
        value={itemPrice}
        onChangeText={(text) => setItemPrice(text)}
        keyboardType="numeric"
        style={styles.input}
      />
      <TouchableOpacity style={styles.crear} onPress={Iralmenu}><Text style={styles.botontext}>+ Crear Menu</Text></TouchableOpacity>
      <TouchableOpacity style={styles.crear} onPress={agregarItemAlinfo}><Text style={styles.botontext}>Crear Restaurant</Text></TouchableOpacity>
    </View>
  );
}

function CrearMenu() {
  const navigation = useNavigation();

  return (
    <ScrollView style={{ backgroundColor: "white" }}>
      <View style={styles.botones}>
        <Image
          source={require('../assets/images/logo-restoapp.png')}
          style={styles.logo}
        />
        <Text style={styles.title}>Crea tu Menu</Text>
        <TouchableOpacity style={styles.boton} onPress={() => navigation.navigate('Food', { Categoria: 'Entradas' })}><Text style={styles.botontext}>Entradas</Text></TouchableOpacity>
        <TouchableOpacity style={styles.boton} onPress={() => navigation.navigate('Food', { Categoria: 'Carnes' })}><Text style={styles.botontext}>Carnes</Text></TouchableOpacity>
        <TouchableOpacity style={styles.boton} onPress={() => navigation.navigate('Food', { Categoria: 'Pescados' })}><Text style={styles.botontext}>Pescados</Text></TouchableOpacity>
        <TouchableOpacity style={styles.boton} onPress={() => navigation.navigate('Food', { Categoria: 'Milanesas' })}><Text style={styles.botontext}>Milanesas</Text></TouchableOpacity>
        <TouchableOpacity style={styles.boton} onPress={() => navigation.navigate('Food', { Categoria: 'Pastas' })}><Text style={styles.botontext}>Pastas</Text></TouchableOpacity>
        <TouchableOpacity style={styles.boton} onPress={() => navigation.navigate('Food', { Categoria: 'Ensaladas' })}><Text style={styles.botontext}>Ensaldas</Text></TouchableOpacity>
        <TouchableOpacity style={styles.boton} onPress={() => navigation.navigate('Food', { Categoria: 'Tartas' })}><Text style={styles.botontext}>Tartas</Text></TouchableOpacity>
        <TouchableOpacity style={styles.boton} onPress={() => navigation.navigate('Food', { Categoria: 'Hamburguesas' })}><Text style={styles.botontext}>Hamburguesas</Text></TouchableOpacity>
        <TouchableOpacity style={styles.boton} onPress={() => navigation.navigate('Food', { Categoria: 'Pizzas' })}><Text style={styles.botontext}>Pizzas</Text></TouchableOpacity>
        <TouchableOpacity style={styles.boton} onPress={() => navigation.navigate('Food', { Categoria: 'Panchos' })}><Text style={styles.botontext}>Panchos</Text></TouchableOpacity>
        <TouchableOpacity style={styles.boton} onPress={() => navigation.navigate('Food', { Categoria: 'Vegetarianos/veganos' })}><Text style={styles.botontext}>Vegetarianos/veganos</Text></TouchableOpacity>
        <TouchableOpacity style={styles.boton} onPress={() => navigation.navigate('Food', { Categoria: 'Asado' })}><Text style={styles.botontext}>Asado</Text></TouchableOpacity>
        <TouchableOpacity style={styles.boton} onPress={() => navigation.navigate('Food', { Categoria: 'Menú-infantil' })}><Text style={styles.botontext}>Menú-infantil</Text></TouchableOpacity>
        <TouchableOpacity style={styles.boton} onPress={() => navigation.navigate('Food', { Categoria: 'Postres' })}><Text style={styles.botontext}>Postres</Text></TouchableOpacity>
        <TouchableOpacity style={styles.boton} onPress={() => navigation.navigate('Food', { Categoria: 'Bebidas' })}><Text style={styles.botontext}>Bebidas</Text></TouchableOpacity>
        <TouchableOpacity style={styles.boton} onPress={() => navigation.navigate('Food', { Categoria: 'Gaseosas' })}><Text style={styles.botontext}>Gaseosas</Text></TouchableOpacity>
        <TouchableOpacity style={styles.boton} onPress={() => navigation.navigate('Food', { Categoria: 'Bebidas-alcoholicas' })}><Text style={styles.botontext}>Bebidas-alcoholicas</Text></TouchableOpacity>
        <TouchableOpacity style={styles.crear} onPress={() => navigation.goBack()} ><Text style={styles.botontext}>Listo</Text></TouchableOpacity>
      </View>
    </ScrollView>
  )
}

function FormularioFood({ route }) {
  const { Categoria } = route.params;
  const [menu, setMenu] = useState([]);
  const [itemName, setItemName] = useState('');
  const [itemPrice, setItemPrice] = useState('');
  const [isEditing, setIsEditing] = useState(false);
  const [selectedItemId, setSelectedItemId] = useState(null);
  const navigation = useNavigation();

  useEffect(() => {
    // Ejecutar una consulta SQL para obtener los elementos de menú de la categoría
    db.transaction((tx) => {
      tx.executeSql(
        'SELECT * FROM menu WHERE categoria = ?',
        [Categoria],
        (_, results) => {
          const menuItems = [];
          for (let i = 0; i < results.rows.length; i++) {
            const row = results.rows.item(i);
            menuItems.push({
              id: row.id,
              nombre: row.nombre,
              precio: row.precio,
            });
          }
          setMenu(menuItems);
        },
        (error) => {
          console.error('Error al obtener elementos de menú', error);
        }
      );
    });
  }, [Categoria]);

  const agregarItemAlMenu = () => {
    const newItem = {
      nombre: itemName,
      precio: parseFloat(itemPrice),
    };

    // Ejecutar una consulta SQL para insertar el nuevo elemento en el menú
    db.transaction((tx) => {
      tx.executeSql(
        'INSERT INTO menu (nombre, precio, categoria) VALUES (?, ?, ?)',
        [newItem.nombre, newItem.precio, Categoria],
        (_, result) => {
          console.log('Elemento de menú insertado con éxito');
          // Actualizar el estado para reflejar el nuevo elemento en el menú
          setMenu([...menu, { id: result.insertId, ...newItem }]);
        },
        (error) => {
          console.error('Error al insertar elemento de menú', error);
        }
      );
    });

    // Limpiar los campos de entrada
    setItemName('');
    setItemPrice('');
  };

  const editarItemEnMenu = () => {
    const updatedItem = {
      nombre: itemName,
      precio: parseFloat(itemPrice),
    };

    if (selectedItemId !== null) {
        // Ejecutar una consulta SQL para actualizar el elemento en el menú
        db.transaction((tx) => {
          tx.executeSql(
            'UPDATE menu SET nombre = ?, precio = ? WHERE id = ?',
            [updatedItem.nombre, updatedItem.precio, selectedItemId],
            (_, result) => {
              console.log('Elemento de menú actualizado con éxito');
              // Actualizar el estado para reflejar el elemento editado en el menú
              const updatedMenu = menu.map((item) =>
                item.id === selectedItemId ? { id: item.id, ...updatedItem } : item
              );
              setMenu(updatedMenu);
              setIsEditing(false);
              setSelectedItemId(null);
            },
            (error) => {
              console.error('Error al actualizar elemento de menú', error);
            }
          );
        });
      } else {
        console.error('selectedItemId es null, no se puede actualizar el elemento.');
      }

    // Limpiar los campos de entrada
    setItemName('');
    setItemPrice('');
  };

  const eliminarItemDelMenu = (itemId) => {
    // Ejecutar una consulta SQL para eliminar el elemento del menú
    db.transaction((tx) => {
      tx.executeSql(
        'DELETE FROM menu WHERE id = ?',
        [itemId],
        (_, result) => {
          console.log('Elemento de menú eliminado con éxito');
          // Actualizar el estado para reflejar la eliminación del elemento
          const updatedMenu = menu.filter((item) => item.id !== itemId);
          setMenu(updatedMenu);
        },
        (error) => {
          console.error('Error al eliminar elemento de menú', error);
        }
      );
    });
  };

  const handleEditItem = (item) => {
    // Preparar el formulario para la edición
    setIsEditing(true);
    setSelectedItemId(item.id);
    setItemName(item.nombre);
    setItemPrice(item.precio.toString());
  };

  return (
    <View style={styles.container}>
      <Text style={styles.title}>{Categoria}</Text>
      <TextInput
        placeholder="Nombre del artículo"
        value={itemName}
        onChangeText={(text) => setItemName(text)}
        style={styles.input}
      />
      <TextInput
        placeholder="Precio"
        value={itemPrice}
        onChangeText={(text) => setItemPrice(text)}
        keyboardType="numeric"
        style={styles.input}
      />
      {isEditing ? (
        <Button title="Editar Producto" onPress={editarItemEnMenu} />
      ) : (
        <Button title="Agregar al menú" onPress={agregarItemAlMenu} />
      )}
      <FlatList
        data={menu}
        keyExtractor={(item) => item.id.toString()} // Usar toString() para evitar errores
        renderItem={({ item }) => (
          <View style={styles.item}>
            <Text>{item.nombre}</Text>
            <Text>Precio: ${item.precio.toFixed(2)}</Text>
            <Button title="Editar" onPress={() => handleEditItem(item)} />
            <Button title="Eliminar" onPress={() => eliminarItemDelMenu(item.id)} />
          </View>
        )}
      />
      <Button
        title="Volver"
        onPress={() => navigation.goBack()} // Vuelve a la pantalla anterior
      />
    </View>
  );
}

const styles = StyleSheet.create({
    container: {
        paddingTop: 50,
        backgroundColor: 'white',
        flex: 1,
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    input: {
        width: '80%',
        borderWidth: 1,
        borderColor: '#ccc',
        padding: 10,
        marginBottom: 20,
    },
    logo: {
        marginBottom: 40,
    },
    item: {
        marginBottom: 8,
    },
    botones: {
        marginTop: 50,
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
    },
    boton: {
        justifyContent: 'center',
        alignItems: 'center',
        width: 350, 
        height: 60,
        backgroundColor: '#6CCCFC',
        borderWidth: 1,
        borderColor: "black",
        borderRadius: 20,
        marginBottom: 4,
    },
    botontext: {
        color: 'white',
    },
    title: {
        fontSize: 30,
        paddingBottom: 30,
        
    },
    crear: {
        marginTop: 20,
        marginBottom: 50,
        backgroundColor: '#6CCCFC',
        height: 50,
        width: 150,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
    },
});`

**Comment by Shemonti** [comment]
I also got this error
this is my code:
`import React, { useEffect, useState } from 'react';
import { View, Text, ScrollView, StyleSheet, Alert } from 'react-native';
import { fetchData } from '../../Config'; // Adjust the import path as needed
import { initDB, executeQuery } from '../components/dtbase'; // Adjust the import path as needed

const ColumnInfoScreen = () => {
  const [posts, setPosts] = useState([]);

  useEffect(() => {
    const loadData = async () => {
      try {
        const db = await initDB();

        // Create table if it doesn't exist
        await executeQuery(db, `CREATE TABLE IF NOT EXISTS posts (
          userId INTEGER,
          id INTEGER PRIMARY KEY,
          title TEXT,
          body TEXT
        )`, []);

        // Fetch data from API
        const response = await fetch('https://jsonplaceholder.typicode.com/posts');
        const postsData = await response.json();

        // Insert fetched data into the SQLite table
        for (let post of postsData) {
          await executeQuery(db, `INSERT OR REPLACE INTO posts (
            userId, id, title, body
          ) VALUES (?, ?, ?, ?)`, [
            post.userId,
            post.id,
            post.title || '',
            post.body || ''
          ]);
        }

        // Retrieve data from SQLite table
        const results = await executeQuery(db, 'SELECT * FROM posts', []);
        const storedPosts = [];
        for (let i = 0; i < results.rows.length; i++) {
          storedPosts.push(results.rows.item(i));
        }
        setPosts(storedPosts);

      } catch (error) {
        console.log('Error fetching data', error);
      }
    };

    loadData();
  }, []);

  return (
    <ScrollView style={styles.container}>
      {posts.map((post, index) => (
        <View key={index} style={styles.postContainer}>
          <Text style={styles.title}>{post.title}</Text>
          <Text style={styles.body}>{post.body}</Text>
        </View>
      ))}
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
  },
  postContainer: {
    marginBottom: 15,
  },
  title: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  body: {
    fontSize: 14,
    color: '#666',
  },
});

export default ColumnInfoScreen;
`
