### ISSUE TITLE
[Windows] Clicking Links Does Not Trigger `onShouldStartLoadWithRequest`

### ISSUE THREAD

**Issue by 17Amir17** [react-native-webview/react-native-webview#2925]
**Bug description:**
I have a react-native-windows project that contains a webview pointing to my website.
When the user clicks on links in the website I expect it to trigger `onShouldStartLoadWithRequest` and then I can decide if to navigate inside the webview or if I should open the link externally. 
On react-native-windows `onShouldStartLoadWithRequest` is not fired and the link is opened in a separate window (separate window but still part of the app)

**To Reproduce:**
Run windows example with `useWebview2` set to true and click on any link, 
a new window will be opened and `onShouldStartLoadWithRequest` or `onNavigationStateChange` will not be fired

**Environment:**
 - OS: Windows 10 Enterprise
 - OS version: 19045.2364
 - react-native version: 0.71
 - react-native-webview version: 12.0.2
 - react-native-windows version: 0.71.5

**Comment by frankcalise** [comment]
Also experiencing this

```
"react-native": "0.71.8",
"react-native-webview": "12.0.2",
"react-native-windows": "0.71.15"
```

**Comment by 17Amir17** [comment]
@frankcalise I think it's simply not implemented :/ So maybe not a bug but feature request
