### ISSUE TITLE
Could not read cookie on android 

### ISSUE THREAD

**Issue by 4mit** [react-native-webview/react-native-webview#2926]
**Bug description:**

I'm using  webview with React Native and using an external script that reads cookies 
after the script is loaded and when I tried to read the cookie im getting the below error 
Even if i don't use an external script and try to use document.cookie it throws below error 

However it works on ios 

**Uncaught DOMException: Failed to read the 'cookie' property from 'Document': Access is denied for this document.**

**To Reproduce:**
To reproduce it  create a very minimal react native project and try using  web view and also try using an external script that reads cookie inside 

```
<WebView
       mixedContentMode="compatibility"
       javaScriptEnabled={true}
       domStorageEnabled={true}
       thirdPartyCookiesEnabled={true}
       sharedCookiesEnabled={true}
       originWhitelist={['*']}
        style={{width: 300}}
        source={{
          html: `
          <!DOCTYPE html>
            <html>
            <head>
                <title>hello</title>
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <script src=""></script>
                **/*EVEN IF YOU USE ANY EXTERNAL SCRIPT AND JUST TRY document.cookie IT FAILS*/**
            </head>
            <body>
                Testing
                <div id="video-player-container">                    
                    <div id="video-player-global">Loading .....</div>                    
                </div>
                
                <script type="text/javascript">                   
                    console.log(document.cookie);                                       
                </script>
            </body>
            </html>`,
        }}
      />
    </SafeAreaView>
```

**Expected behavior:**
Script should not break cookie value should be logged

**Screenshots/Videos:**
![Screenshot 2023-04-14 at 16 41 46](https://user-images.githubusercontent.com/19636777/232029005-c974b85a-272f-46c6-a66a-1baabffd81d5.png)

**Environment:**
 - OS: using android studio emulator tried on actual device as well 
 - OS version: mac | android 13 
 - react-native version:"react-native": "0.71.4",
 - react-native-webview version:"react-native-webview": "^11.26.1"

**Comment by TamasMezo** [comment]
Hey @4mit,
What worked for me => just add a baseUrl to the source prop, does not really matter what, you can even use the example below:
source={{ baseUrl: 'https://*', html }}
Looks like if baseurl is added, WebView will use a different method to load the html content.

**Comment by Harikarthyk** [comment]
When I give a base URL with the same HTML content, it works, but when the same HTMl is embedded as tags while accessing cookies, errors occur. This happens only for Android.

In my case, I need to embed and cannot use baseUrl.

Is there any way to achieve this?
