### ISSUE TITLE
onNavigationStateChange doesn't trigger url if it contains `intent://...`

### ISSUE THREAD

**Issue by claudioviola** [react-native-webview/react-native-webview#2928]
**Bug description:**
onNavigationStateChange doesn't trigger url if the link pressed in the web pages has `intent://...` as protocol.

**To Reproduce:**
https://snack.expo.dev/@bigpurple/react-native-webview-test (remind to pick Android as platform)

**Expected behavior:**
Link with intent prefix is regularly caught in onNavigationStateChange

More details
`intent://...` is the android protocol to perform a request for opening an app. As long as I don't catch the "intent" url I can't perform any other action in my app

**Environment:**
 - "expo": "^47.0.13",
 - "expo-linking": "~3.3.0",
 - "react-native-webview": "^11.26.1",

**Comment by TheKohan** [comment]
got the same with `blob:` urls, any ideas ?

**Comment by claudioviola** [comment]
> got the same with `blob:` urls, any ideas ?

I solved thanks to `originWhitelist={['*']}`
It was suggested in others reported similar issues 

In my case in the html page I've a button with a deep link, and I've to handle the pressing of this button and perform the opening of another app by using `Linking.openURL(link);`

Hope this help

**Comment by MuhammadRafeh** [comment]
Did you guys find any solution?

**Comment by claudioviola** [comment]
@MuhammadRafeh did you try by adding the prop `originWhitelist={['*']}`?

**Comment by MuhammadRafeh** [comment]
@claudioviola yes I have already added that.
