### ISSUE TITLE
Clearing cache / cookie on IOS / Android

### ISSUE THREAD

**Issue by samuelgja** [react-native-webview/react-native-webview#2932]
### Clearing cache / cookie on IOS / Android
Hey gyus, I have few questions about clearing **cache** and **cookie**. I know there is still open discussion but no answer, also I have additional question.
Related here: #2740, #2625 and here #737

1. Is there any plan to implement **clean cookies / cache** for both platforms?
2. Why clear cache method is inside `Webview` react ref and not in global lib scope as function? When you describe:
["Note that the cache is per-application, so this will clear the cache for all WebViews used"](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#clearCachebool). Makes no sense to have this method in webview component ref 🧐
3. I do not consider incognito mode as clearing cache option.

**Additional context**
If there is no time to implement this fix / feature in near future I can look at it and maybe create PR.

**Comment by TheAlmightyBob** [comment]
I don't think anybody is currently looking into this, so you are welcome to!

[`react-native-cookies`](https://github.com/react-native-cookies/cookies) already supports clearing iOS WebView _cookies_... I don't think it touches the _cache_, but the implementation may be similar

**Comment by rf1804** [comment]
For iOS https://www.npmjs.com/package/react-native-webview-ios-cache-clear
For android https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#clearCachebool

@samuelgja @TheAlmightyBob

**Comment by TheAlmightyBob** [comment]
@rf1804 Why create a separate package for that? Also, the link from NPM to GitHub is broken... is the package not open-source?

**Comment by rf1804** [comment]
> @rf1804 Why create a separate package for that? Also, the link from NPM to GitHub is broken... is the package not open-source?

@TheAlmightyBob 
I found out so many people are looking for this feature and plenty of issues were created but still no response on that, so created 1 as i also needed in my project.

Yes it is open source, can you retry? the link

**Comment by TheAlmightyBob** [comment]
The link works now.
