### ISSUE TITLE
Jest fails on v12.0.2

### ISSUE THREAD

**Issue by rarenatoe** [react-native-webview/react-native-webview#2934]
**Bug description:**

When running a Jest test involving WebView, It runs fine on 11.26.0, however when upgrading to 12.0.2, I get this error:
```
Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNCWebView' could not be found. Verify that a module by this name is registered in the native binary.

      at invariant (node_modules/invariant/invariant.js:40:15)
      at Object.getEnforcing (node_modules/react-native/Libraries/TurboModule/TurboModuleRegistry.js:41:12)
      at Object.<anonymous> (node_modules/react-native-webview/lib/NativeRNCWebView.js:2:36)
      at Object.<anonymous> (node_modules/react-native-webview/lib/WebView.ios.js:63:1)
 ```

**To Reproduce:**

Write a test such as

```
import { render } from '@testing-library/react-native'
import React from 'react'

import { WebView } from 'react-native-webview'

describe('WebView', () => {
  it('Test passes', () => {
    render(<WebView />)
    expect(true).toBeTruthy()
  })
})

```

**Expected behavior:**

It passes or give any other error

**Environment:**
 - OS: Mac
 - OS version: Ventura 13.3.1
 - react-native version: 0.70.9
 - react-native-webview version: 12.0.2
 - jest version: 27.5.1

**Comment by Dr0pG** [comment]
same here

**Comment by TheAlmightyBob** [comment]
This was discussed in the original v12 MR here: https://github.com/react-native-webview/react-native-webview/pull/2686#issuecomment-1414603408

And answered here: https://github.com/react-native-webview/react-native-webview/pull/2686#issuecomment-1425865443

It's possible that a documentation update would help...

**Comment by DominicTobias** [comment]
> This was discussed in the original v12 MR here: [#2686 (comment)](https://github.com/react-native-webview/react-native-webview/pull/2686#issuecomment-1414603408)
> 
> And answered here: [#2686 (comment)](https://github.com/react-native-webview/react-native-webview/pull/2686#issuecomment-1425865443)
> 
> It's possible that a documentation update would help...

Perhaps a mention here too, as an existing user this is what I check: https://github.com/react-native-webview/react-native-webview/releases/tag/v12.0.0

**Comment by nvodoor1** [comment]
Running into this bug as well.

**Comment by hemantdelta** [comment]
Same issue with react-native ^0.61.4 version. Please help how will it work in case of old architecture.

**Comment by patlux** [comment]
Workaround:

```js
jest.mock('react-native/Libraries/TurboModule/TurboModuleRegistry', () => {
  const turboModuleRegistry = jest.requireActual(
    'react-native/Libraries/TurboModule/TurboModuleRegistry',
  )
  return {
    ...turboModuleRegistry,
    getEnforcing: (name) => {
      if (name === 'RNCWebView') {
        return null
      }
      return turboModuleRegistry.getEnforcing(name)
    },
  }
})
```

**Comment by TheAlmightyBob** [comment]
@Yurii-Lutsyk `RNBootSplash` is a separate library unrelated to `react-native-webview`.

Sounds like this is a general problem with React Native TurboModules though, not specific to `react-native-webview`.

**Comment by DeepUmbrella** [comment]
@TheAlmightyBob  so,it's looks like need mock the module, right? or react-native-view team fix it.

**Comment by ghorbani-m** [comment]
In some situation we need to define default export too:
```
jest.mock('react-native-webview', () => {
  const { View } = require('react-native')
  return {
    __esModule: true,
    default: View,
    WebView: View,
  }
})
```

**Comment by basbase** [comment]
When you are testing code that calls the methods of the WebView ref you need to mock more:

```javascript
jest.mock('react-native-webview', () => {
  const React = require('react');
  const {View} = require('react-native');

  const refOverride = {
    goBack: jest.fn(),
    goForward: jest.fn(),
    reload: jest.fn(),
    stopLoading: jest.fn(),
    injectJavaScript: jest.fn(),
    requestFocus: jest.fn(),
    postMessage: jest.fn(),
    clearFormData: jest.fn(),
    clearCache: jest.fn(),
    clearHistory: jest.fn(),
  };
  const MockWebView = React.forwardRef((props, ref) => {
    React.useEffect(() => {
      ref.current = refOverride;
    }, []);
    return <View {...props} ref={ref} />;
  });

  return {
    __esModule: true,
    WebView: MockWebView,
    default: MockWebView,
  };
});
```
