### ISSUE TITLE
react native webview injectedjavascript prop changes reflecting late in android

### ISSUE THREAD

**Issue by KSNMURTHY08** [react-native-webview/react-native-webview#2939]
**Bug description:**

I want to inject the javascript so used the injectedJavascript. The changes are effective in iOS as it loads within a second but the same in android it is taking around one and half minute. If i have a small html it loads with no isue but if the html is having big content it is creating this issue.
**To Reproduce:**

Below is the code I am using 

const jsCode = `document.querySelector("body").style.color = "#814936"; document.querySelector("body").style.background = '#F9F0DE';`;
 
  return (
    <SafeAreaView style={{flex:1}}>
      <WebView
      ref={() => {}}
      style={{flex: 1}}
      originWhitelist={['*']}
      //source={require('./anil.html')}
      source={{uri:'file:///android_asset/index.xhtml'}}
      javaScriptEnabled={true}
      domStorageEnabled={true}
      injectedJavaScript={jsCode}
      onMessage={(event) => {}}
      />
    </SafeAreaView>
  );

**Expected behavior:**

Want to load the  injected javascript changes to load in android as soon as possible.

**Screenshots/Videos:**

**Environment:**
 - OS: Android
 - OS version: 13
 - react-native version: 0.71.6
 - react-native-webview version: ^12.0.2

**Comment by KSNMURTHY08** [comment]
I am checking this in emulator

**Comment by MelanieJourne** [comment]
@Hasan-aga thanks you, you save my life
