### ISSUE TITLE
Motion sensor permissions are asked repetitively 

### ISSUE THREAD

**Issue by ThorstenBux** [react-native-webview/react-native-webview#2942]
Hi there, 
I'm new to RN and react-native-webview. However, I've worked on several project in RectJS. 
**Bug description:**
I'm reporting this issue cause I'm including a ReactJS project into a ReactNative app using the react-native-webview.
The Web page will use the motion sensor so I've setup the ReactNative App to request permissions and expect the permissions to be available to the WebView, however, this doesn't seem to be the case.

**To Reproduce:**

- Create a ReactNative App
- Install react-native-permissions (https://github.com/zoontek/react-native-permissions)
- Request access to the motion sensor using the react-native-permissions library
```
          RNPermissions.request(PERMISSIONS.IOS.MOTION)
            .then(status => {
              console.log('request(MOTION)', status);
            })
            .catch(error => {
              console.error(error);
            });
```
- Allow access to the sensor 
- Launch the WebView and trigger sensor readings

**Expected behavior:**
Expected: No permission dialog to come up because I have just granted access to the motion sensor.

**Screenshots/Videos:**

https://user-images.githubusercontent.com/16772796/234722782-f76aa2cc-ab05-4dcc-ad1a-7a5e5a410e16.mp4

GitHub repo with demo: https://github.com/ThorstenBux/reactNativeMotion

**Environment:**
 - OS: iOS Iphone 14 Pro (actual device not simulator)
 - OS version: 16.2.1
 - react-native version: 0.71.7
 - react-native-webview version: 12.0.2

**Comment by ThorstenBux** [comment]
Hi guys, was anyone able to reproduce? Any pointers into what is going on?

**Comment by priyanshi-vindaloo** [comment]
yes I am also facing this issue.
