### ISSUE TITLE
Padding property in style prop not applied

### ISSUE THREAD

**Issue by smatoox** [react-native-webview/react-native-webview#2946]
**Bug description:**

Padding in style prop not applied.
When I add paddingTop in `style` prop, style is not visible.
It works in `containerStyle` only.

I need to use padding inside webview to increase the distance from top of scroll.

What is the right approach to get the result ?

Thanks for your help.

**To Reproduce:**

```
    <WebView
      startInLoadingState
      onScroll={handleScrollViewScroll}
      source={{uri: formatWebViewUrl(currentUrl)}}
      onShouldStartLoadWithRequest={handleShouldStartLoad}
      injectedJavaScript={injectedScript}
      allowsFullscreenVideo={false}
      allowsInlineMediaPlayback={true}
      style={{
        paddingTop: parentHeaderHeight,
      }}
    />
```

**Environment:**
 - OS: android
 - OS version: android 12
 - react-native version:  0.66.3
 - react-native-webview version: 12.0.2

**Comment by kevinvangelder** [comment]
I am having the same issue.

**Comment by LaGregance** [comment]
Still an issue in 2024. Any news ?
