### ISSUE TITLE
does react native webview support intercepting all resource requests?For example, js, css, etc

### ISSUE THREAD

**Issue by homels-kong** [react-native-webview/react-native-webview#2947]
I want to create an offline package solution in React Native. I want to intercept all requests through React Native webview to determine if there are resources available locally。

**Comment by dimianstudio** [comment]
You should register service-worker for you web app and handle it all there.

**Comment by FilipChalupa** [comment]
Have you resolved this issue? I'm still strugling with service worker inside Apple webview not serving offline content.

**Comment by vladrozhnev** [comment]
If anyone needs this functionality, I did that.
https://github.com/vladrozhnev/react-native-interception-webview

**Comment by arnaudambro** [comment]
hey @vladrozhnev 
is it good for caching assets so that we can use offline ?
