### ISSUE TITLE
Android: userAgent disables goBack to first url

### ISSUE THREAD

**Issue by jadfls** [react-native-webview/react-native-webview#2949]
**Bug description:**
On Android: When userAgent is set then goBack does not work anymore to the first url. It does work on subsequent pages but you can never go back to the very first.

**To Reproduce:**
```
<WebView
  ref={(ref) => (this.webview = ref)}
  userAgent={'custom-string'}
  source={{ uri: 'https://infinite.red'}}
/>
```

1. Create a button to trigger this.webview.goBack()
2. Now have the first webpage opened (https://infinite.red)
3. Click a link and try to go back => does not work
4. Click a link and another link and try to go back => does work once. but cannot go back to very first page

Note: if you omit userAgent or if you set userAgent to empty string '', then it works as expected.

**Expected behavior:**
With custom userAgent set, that you can navigate and goBack as without custom userAgent set. You can go back to the very first page as well

**Screenshots/Videos:**

**Environment:**
 - OS: Android
 - OS version: Android 12
 - react-native version: 0.66.x
 - react-native-webview version: 12.0.2

**Comment by Yangnnnn** [comment]
same issue, looking for a solution

**Comment by marcelo-soares-souza** [comment]
same issue here!

**Comment by ooyo** [comment]
same issue here! works on emulator, but not on physical Android devices

**Comment by Asad520** [comment]
I'm facing the same issue for `applicationNameForUserAgent` prop. Is any fix available?

**Comment by alexanderblackh** [comment]
Can confirm this is an issue still.

**Comment by sudesh-poojari** [comment]
Facing same issue with custom userAgent. Where history back doesn't work for first url.

Is there any work around for this.

**Comment by sparkertime** [comment]
I am so relieved to find this Github issue. I thought I was going crazy!

I am seeing similar behavior to what @SteffenSr noted - there seems to be some interaction in our app between `applicationNameForUserAgent ` and `injectedJavascript` that causes this. If I remove either entirely, no problem.

However, initial testing seems to be that we can switch `applicationNameForUserAgent` to `userAgent` and the problem goes away. I need to do more testing to have much confidence in that though.

**Comment by gronxb** [comment]
Hello. I solved the problem and made a pull request.

I need your attention.

**Comment by asbaghel08** [comment]
I am not able to go back in webview after a location access pop appears. Although not using userAgent

**Comment by Mookiies** [comment]
This issue also affects navigation done via `window.history.back()`. It is not limited to the webview's `goBack()` API.

**Comment by GriffinSauce** [comment]
It looks like this issue is still here, it was intermittent for us and switching from `userAgent` to `applicationNameForUserAgent` seems to have solved it but still it's quite problematic.

**Comment by gronxb** [comment]
@GriffinSauce You're right, this issue should be reopened.

https://github.com/react-native-webview/react-native-webview/pull/3133#issuecomment-1803188672

Try as-is as a quick fix from this link.
My PR is for this, but it hasn't been merged.

**Comment by bononwj** [comment]
Interesting. It works when setting injectedJavaScript, injectedJavaScriptBeforeContentLoaded, applicationNameForUserAgent at the same time
