### ISSUE TITLE
Unable to download blob file

### ISSUE THREAD

**Issue by MuhammadRafeh** [react-native-webview/react-native-webview#2951]
**Bug description:**
I am unable to download blob urls using this module.

**To Reproduce:**
in order to reproduce we can put any blob url in the source url webview component

**Expected behavior:**
It must download the blob url and call some function in order to know what has been downloaded

**Screenshots/Videos:**

**Environment:**
 - OS: Android, iOS
 - OS version: almost latest
 - react-native version: 0.71.7
 - react-native-webview version: 12.0.2

**Comment by dineshnadimpalli** [comment]
+1

can be reproduced by accessing [this]("https://codepen.io/DineshNadimpalli/pen/gOBdMWe") codepen link on webview

**Comment by jordoh** [comment]
According to [this StackOverflow discussion](https://stackoverflow.com/questions/59083340/how-to-download-files-in-wkwebview) there are some additional delegates necessary for handling downloads. 

I can verify that `decidePolicyForNavigationAction` is called in RNCWebView when the blob URL link is clicked (either via user interaction or javascript `link.click()`), with a URL that looks like: `blob:file:///c45de352-c734-46ca-8473-ce4551a89e59`. With the default `WKNavigationActionPolicyAllow` decision there, `decidePolicyForNavigationResponse` is called with the same (blob) URL, which is not very useful there (can't be accessed outside the WKWebView).

**Comment by dingcxx** [comment]
> According to [this StackOverflow discussion](https://stackoverflow.com/questions/59083340/how-to-download-files-in-wkwebview) there are some additional delegates necessary for handling downloads.
> 
> I can verify that `decidePolicyForNavigationAction` is called in RNCWebView when the blob URL link is clicked (either via user interaction or javascript `link.click()`), with a URL that looks like: `blob:file:///c45de352-c734-46ca-8473-ce4551a89e59`. With the default `WKNavigationActionPolicyAllow` decision there, `decidePolicyForNavigationResponse` is called with the same (blob) URL, which is not very useful there (can't be accessed outside the WKWebView).

Android working well？

**Comment by jordoh** [comment]
> Android working well？

Nope - on Android the blob URL doesn't get opened/saved when using `link.click()` (or equivalent via `dispatchEvent`) nor when setting `window.location = blobURL`. There's likely an equivalent download handler for Android's webview.

**Comment by dingcxx** [comment]
> > Android working well？
> 
> Nope - on Android the blob URL doesn't get opened/saved when using `link.click()` (or equivalent via `dispatchEvent`) nor when setting `window.location = blobURL`. There's likely an equivalent download handler for Android's webview.

I choose  web bridge

**Comment by WANG-Lisa** [comment]
I tried branch code of blob-download-feature in react-native-webview repo, when download blob, it shows error
"Refused to connect to 'blob:xxxxx" because it violates the following Content Security Policy directive: "default-src *". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback. Note that '*' matches only URLs with network schemes ('http', 'https', 'ws', 'wss'), or URLs whose scheme matches `self`'s scheme. The scheme 'blob:' must be added explicitly.

**Comment by remberluyckx** [comment]
Anyone have an idea how to open a blob url inside a webview?

**Comment by gauravrana0-nagarro** [comment]
try this [https://github.com/react-native-webview/react-native-webview/issues/3445#issuecomment-2349318406](url)

**Comment by VariabileAleatoria** [comment]
> [https://github.com/react-native-webview/react-native-webview/issues/3445#issuecomment-2349318406](url)
your link is broken

**Comment by asurare** [comment]
> > [https://github.com/react-native-webview/react-native-webview/issues/3445#issuecomment-2349318406](url)
> 
> your link is broken

Correct link : https://github.com/react-native-webview/react-native-webview/issues/3445#issuecomment-2349318406
