### ISSUE TITLE
Initial webview rendering is too slow

### ISSUE THREAD

**Issue by anas-araid** [react-native-webview/react-native-webview#2962]
Whenever I clear the app and launch it again, the loading speed becomes incredibly slow. 

I'm wondering why this happens and how we can make it faster, similar to how it loads quickly when opened in a browser. Unlike the fast and instantaneous loading in a browser, the app takes a significantly longer time to load in a webview every time.

Is there any solution/workaround that improves the loading performance?

**Comment by ColeTownsend** [comment]
I've still found this to be true with cacheEnabled.
