### ISSUE TITLE
How to extend the web view in new architecture

### ISSUE THREAD

**Issue by Shawnge** [react-native-webview/react-native-webview#2964]
How to extend the web view with native code  in new architecture without forking React Native or duplicating all the existing web view code.

**Comment by TheAlmightyBob** [comment]
If you're referring to techniques like https://github.com/react-native-webview/react-native-webview/blob/master/docs/Custom-iOS.md, this should still work with the latest version using the *old* architecture (though some tweaks may be necessary). However, it's not officially supported with the new architecture and we expect that some customizations may not be possible there.

I _personally_ suspect it may still work if you're making _native-only_ changes (i.e. not adding new properties/functions to the React Native side), but AFAIK nobody's actually tried this yet.

I think the other alternative approach would be to patch the library.
