### ISSUE TITLE
Camera issue on WebView in expo

### ISSUE THREAD

**Issue by Arm0216** [react-native-webview/react-native-webview#2965]
**Title**
When I open camera for scanning government ID by using Persona webview, the app is stopping and I see black screen.

**To Reproduce:**
I open camera for scanning government ID by using Persona webview, the app is stopping and I see black screen.
here is a link of persona:
https://withpersona.com/
Steps:
1. installed webview in expo
2. create component for persona id identifiaction webview
Code : `<WebView
                key={webviewKey}
                ref={webviewRef}
                useWebKit
                onError={verifyAccount}
                originWhitelist={['*']}
                mediaCapturePermissionGrantType={"grant"}
                domStorageEnabled={true}
                allowsInlineMediaPlayback={true}
                onContentProcessDidTerminate={reload}
                onMessage={handleAuthentication}
                source={{uri: `https://inquiry.withpersona.com/verify?is-webview=true&environment=sandbox&template-id=${id}&redirect-uri=${url}&reference-id=${referenceId}&fields[email-address]=${email}`}}
            />`
3. open webview on ios.
4. navigated to camera screen for scanning government ID.

Expected result: The camera screen is opened successfully
Actual result: The screen is stoped and show black screen after few minutes

**Screenshots/Videos:**
![image](https://github.com/react-native-webview/react-native-webview/assets/79023467/ae3a090d-d65b-4b85-8b41-f6b5574c09b6)

**Environment:**
 - OS: IOS
 - OS version: 16.4.1 (a)
 - react-native version: 0.71.7
 - react-native-webview version: 12.0.2
 - expo version: 48.0.0

**Comment by dannielnavasget** [comment]
Hello, I’m experiencing the same issue and would like to know if you found a solution for the black screen in your WebView.

**Comment by coluccini** [comment]
I was experiencing the same thing. Based on the logs, I saw it was a issue related to lack of permission for launching the camera.

After I add this to app.json (and rebuild) this stopped happening:

```
"ios": {
  "infoPlist": {
    "NSCameraUsageDescription": "This app uses the camera to create your profile picture"
  }
},
```
