### ISSUE TITLE
Webview is using an old version of chrome

### ISSUE THREAD

**Issue by shareef-dweikat** [react-native-webview/react-native-webview#2971]
I get this warning when entering https://app.alexlab.co/swap website using WebView.
 How can i solve it? Is there a way to update chrome? I am using  "react-native-webview": "12.1.0"
 Platform: Android 11
 react-native version: "0.70.8"
 
<img src="https://github.com/react-native-webview/react-native-webview/assets/10628302/9dc5995c-379e-4c4e-88b5-7466fa5423ff" width=250 height=500 />

**Comment by shareef-dweikat** [comment]
It turned out the package is using chrome installed in my Android mobile. I just had to update my browser.

**Comment by TheAlmightyBob** [comment]
`react-native-webview` does not specify the version to use. It uses whatever is installed on the device. You can find Android System WebView in the Play Store.
