### ISSUE TITLE
Colour definitions in SVG content do not render correctly

### ISSUE THREAD

**Issue by sitomani** [react-native-webview/react-native-webview#2972]
**Bug description:**

React-native-webview on Android devices renders colors incorrectly in SVG content in an scenario where the webview is used to show a html page that displays rather complex diagnostics diagram (in svg) in an iframe element. The colors specified in fill/stroke attributes for <svg:rect>, <svg:text>, <svg:line> get messed up (see attached images). Even the colors within bitmaps displayed in <svg:image> element get similarly mispresented.

**To Reproduce:**

IDK - it is not possible to share the implementation in question, because it won't work without live VPN websocket connection. This issue might have something to do with the namespacing, but I am not getting 1:1 result. I can see however, that when using the `svg:` prefix on element names, the rendering works differently for example content like:

```
<html><head/><body><svg viewbox="0 0 60 30" width="60" height="30" xmlns="http://www.w3.org/2000/svg"><g type="Label" z="98" x="0" w="60" y="0" h="30" id="b4c1ef1c-fb99-11ed-80e0-39a77bb78a03">
  <rect x="0" y="0" z="98" width="60" height="30" fill="rgb(0,100,0)" stroke="rgb(49,46,46)" stroke-width="0"></rect>
  <text x="0" y="0" z="98" width="60" height="30" dx="30" dy="15" text-anchor="middle" dominant-baseline="central" font-size="20px" font-weight="bold" fill="rgb(255,0,0)">TEST</text>
</g></svg></body></html>
```

**Expected behavior:**

Color definitions given in the SVG code (or colors in png bitmaps) are rendered correctly. Now there seems to be an unknown filter/mask applied to the colour definition that turns every colour a bit different.

**Screenshots/Videos:**

Screenshots from Chrome inspect, app running in real device (Pixel 7)

Original color specification for a problematic element (#000000). Displays as #FFFFFF
![original_color](https://github.com/react-native-webview/react-native-webview/assets/2254053/7cf3e54f-b5c1-4266-9b18-6611956f14c5)

Adjusting the background color for rect fill to #FF0000. Displays as #FF130E
![ff0000_color](https://github.com/react-native-webview/react-native-webview/assets/2254053/9b6b8bc7-52e4-42ca-b3ce-bd8586717a19)

Adjusting the background color for rect fill to #00FF00. Displays as #014608
![00ff00_color](https://github.com/react-native-webview/react-native-webview/assets/2254053/87bbfc69-ec35-4776-8093-388607006a43)

Adjusting the background color for rect fill to #0000FF. Displays as #E49AF6
![0000ff_color](https://github.com/react-native-webview/react-native-webview/assets/2254053/65464ae1-c3d9-4c8e-91a0-96b42d921233)

Adjusting the background color to have zero for alpha channel (fully transparent). Alpha control works as a workaround for this particular scenario, but not applicable for cases where the wanted color is not the background color of the view. 
![00000000_color](https://github.com/react-native-webview/react-native-webview/assets/2254053/2d288025-9b19-4ec3-b7d1-f0a2529c231e)

**Environment:**
 - OS: Android
 - OS version: 13
 - react-native version: 0.68.2
 - react-native-webview version: 12.1.0

**Comment by TheAlmightyBob** [comment]
This does not sound related to `react-native-webview`. Do you see the expected colors in Chrome on Android and in a native (not React Native) app with WebView?

**Comment by sitomani** [comment]
I've checked the following setups:

react-native-webview in a RN app on iOS: **OK**
Native Android app using Webview on Android: **OK**
Chrome browser on Android: **OK**
react-native-webview in a RN app on Android: **NOT OK** (colors are not right)

I have also installed the Android System Webview Beta just to test if would fix the issue, but I'm getting same behaviour on the offically released 113.0.5672.131 and the beta version 114.0.5735.58. In all the android configurations (Chrome, Native app with Webview work correctly, RN app with `react-native-webview` fails)

**Comment by sitomani** [comment]
I've checked the following setups:

react-native-webview in a RN app on iOS: **OK**
Native Android app using Webview on Android: **OK**
Chrome browser on Android: **OK**
react-native-webview in a RN app on Android: **NOT OK** (colors are not right)

I have also installed the Android System Webview Beta just to test if would fix the issue, but I'm getting same behaviour on the offically released 113.0.5672.131 and the beta version 114.0.5735.58. In all the android configurations (Chrome, Native app with Webview work correctly, RN app with `react-native-webview` fails)

**Comment by TheAlmightyBob** [comment]
Huh, strange. Thanks for confirming that you checked those other scenarios.

The only thing that I can imagine _might_ be related would be the [`androidLayerType`](https://github.com/react-native-webview/react-native-webview/blob/master/src/WebViewTypes.ts#L935) property, as the Android documentation for that does mention color filters. I don't know much about it myself though, and I would have _expected_ that the default behavior would be the same as your native app using WebView.... but maybe worth trying?

**Comment by sitomani** [comment]
I tested passing `androidLayerType` in the component declaration, and tried both "software" and "hardware" for the value; that did not have any effect on the result.

However (!!) I got it working by just changing `forceDarkOn` from `true` to `false`.

**Comment by TheAlmightyBob** [comment]
Nice! I actually started to suggest messing with `forceDarkOn` in my last message, but then stopped myself because that seemed crazy, especially since it should default to `false` and is deprecated by Android...
