### ISSUE TITLE
Android: "Web page not available" not emitting onError/onLoadEnd

### ISSUE THREAD

**Issue by patlux** [react-native-webview/react-native-webview#2976]
**Bug description:**

There are some circumstances which displays the "web page not available" error page in the web view but not emitting `onError` and `onLoadEnd`. 

It's not possible to display a custom error page if this happens.

**To Reproduce:**

1. Setup webview
2. Setup a proxy/vpn which allows you to block the url you are provided to the webview. Note: This is just for reproducing the error in a reliable way. In a real world the error can occur in the following circumstances: Network broken (weak internet connection, connected to a wifi hotspot which block certain websites, etc.) ...
3. Block the url
4. You should now see the `Web page not available` error but not receive the events `onError` and `onLoadEnd`

**Expected behavior:**

Still emit the `onError`-event.

**Screenshots/Videos:**

![CleanShot 2023-06-01 at 09 24 00](https://github.com/react-native-webview/react-native-webview/assets/4481570/e3557059-3e0b-4b2d-a1a6-2034c6c86a7f)

**Environment:**
 - OS: Android
 - OS version: Android 12
 - react-native version: v0.71
 - react-native-webview version: 11.26.1 and 12.1.0 tested

**Debugging**:

I already tried to debug the error but it seems that the errors handlers are not called at all:

<img width="1072" alt="CleanShot 2023-06-01 at 09 16 21@2x" src="https://github.com/react-native-webview/react-native-webview/assets/4481570/8af03d13-5306-4da7-a6b9-03d299ae7c10">

**Comment by tmarek** [comment]
+1

**Comment by lethanh9398** [comment]
+1 the same error

**Comment by JonHome** [comment]
same to me , like android bugs

**Comment by fukemy** [comment]
any solution?
