### ISSUE TITLE
Execution failed for task ':react-native-webview:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by mishenThakshana** [react-native-webview/react-native-webview#2979]
I'm using React Native 0.71.8. and web view version 12.2.0. I'm getting the following error,

```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-webview:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 55s

    at makeError (D:\Hexxion\PlatinumAccess\PlatinumAccessApp\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:174:9)
    at D:\Hexxion\PlatinumAccess\PlatinumAccessApp\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:278:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runOnAllDevices (D:\Hexxion\PlatinumAccess\PlatinumAccessApp\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:82:7)
    at async Command.handleAction (D:\Hexxion\PlatinumAccess\PlatinumAccessApp\node_modules\@react-native-community\cli\build\index.js:108:9)
info Run CLI with --verbose flag for more details.
```

**Comment by mishenThakshana** [comment]
By downgrading to 12.1.0 will solve this problem. Just remove ^ , and keep it like this,

`"react-native-webview": "12.1.0"`

**Comment by jakubparlej** [comment]
> By downgrading to 12.1.0 will solve this problem. Just remove ^ , and keep it like this,
> 
> `"react-native-webview": "12.1.0"`

Downgrading to 12.1.0 worked for me. It looks like 12.2.0 update maked this build error.

**Comment by mlazari** [comment]
This is likely a duplicate of https://github.com/react-native-webview/react-native-webview/issues/2978

**Comment by mganandraj** [comment]
Hello everyone .. This is caused by https://github.com/react-native-webview/react-native-webview/commit/75e7801a6255b37f6887d29d10b9ba688e051416 which I merged a couple of days ago to mitigate large number of crashes reported in some OEM devices. 

The motivation behind the fix was to leverage the change https://android-review.googlesource.com/c/platform/frameworks/support/+/1978527 which added a workaround to the androidx.core module to avoid stripping the File provider metadata.

The fix to androidx.core is available from https://developer.android.com/jetpack/androidx/releases/core#core-1.8.0-alpha06 (which was released more than an year ago) onwards. Could you folks upgrade to this version to avoid the crash ? Transitive dependency can be explicitly resolved as @mlazari suggested above https://github.com/react-native-webview/react-native-webview/issues/2978#issuecomment-1573469986

Thanks !

**Comment by Thomasosho** [comment]
> By downgrading to 12.1.0 will solve this problem. Just remove ^ , and keep it like this,
> 
> `"react-native-webview": "12.1.0"`

This worked quite well

**Comment by mganandraj** [comment]
I'm looking into making the usage of the new construction conditional on the availability of the new version of android modules .. Please hold on.

**Comment by gavrichards** [comment]
I had to downgrade to `11.26.1` because of this issue, but I've just tried `13.3.1` and it built and ran without problem on Android (and on iOS).

**Comment by Thomasosho** [comment]
> I had to downgrade to `11.26.1` because of this issue, but I've just tried `13.3.1` and it built and ran without problem on Android (and on iOS).

Yes on 13.3.1 it worked quite well

**Comment by mlazari** [comment]
@gavrichards Yes, the change that was causing it was reverted in [12.2.1](https://github.com/react-native-webview/react-native-webview/compare/v12.2.0...v12.2.1)

**Comment by gavrichards** [comment]
> 



> @gavrichards Yes, the change that was causing it was reverted in [12.2.1](https://github.com/react-native-webview/react-native-webview/compare/v12.2.0...v12.2.1)

Thanks, I'm mentioning it here because this issue is still open.
