### ISSUE TITLE
Postmessage behaviour different on ios and android

### ISSUE THREAD

**Issue by jccazeaux** [react-native-webview/react-native-webview#2980]
**Bug description:**
Hi,

We noticed a difference in postMessage implementation between Android and iOS:

- Android:
On a postMessage, a MessageEvent is created and dispatched on document:
```
              "try {" +
              "event = new MessageEvent('message', data);" +
              "} catch (e) {" +
              "event = document.createEvent('MessageEvent');" +
              "event.initMessageEvent('message', true, true, data.data, data.origin, data.lastEventId, data.source);" +
              "}" +
              "document.dispatchEvent(event);" +
```
- iOS:
On a postMessage, a MessageEvent is created and dispatched on window:
```
window.dispatchEvent(new MessageEvent('message', %@));
```

In the web pages onpened in webview, the message cannot be listened the same way if sent by an ios device or android device. If it is sent by an ios device, we can listen to the message with a classic `window.addEventListener(message, myHandler)`. If it is sent by android, this won't work. We must listen either
* on document : `document.addEventListener(message, myHandler)`
* on window, but on capture phase : `window.addEventListener(message, myHandler, true)`

According to Mozilla developper documentation (https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage#the_dispatched_event) the correct way to listen is
```
window.addEventListener(message, myHandler, false)
```

PostMessage should be created the same way on iOS and Android. IMHO it should use the `window.postMessage` function to ensure it will be properly listenable by web application opened in webview.

**To Reproduce:**
Open a html page in a webview, listen to message different ways:
```javascript
<html>
  <head>
    <script>
       
       window.addEventListener("message", function(message) { alert("Message received on window : " + message); });
    </script>
  </head>
</html>
```

Send a postMessage on ios or android

**Expected behavior:**
Alert should appear on ios and android. It will only on ios

**Environment:**
 - OS: any
 - OS version: any
 - react-native version: 0.72
 - react-native-webview version: >= 11.23

**Comment by TheAlmightyBob** [comment]
There was a previous PR related to this (https://github.com/react-native-webview/react-native-webview/pull/2684), but I appreciate that you provided a lot more explanation than was given there.

But, as I said there, the `postMessage` API has long been considered deprecated in favor of `injectJavascript`. Is there a reason you can't use that?

**Comment by jccazeaux** [comment]
Hi, I did not find this PR during my research. I did no know about the deprecation. The documentation does not say it (I read this https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#postmessagestr)
Thank you for the information, I will use `injectJavascript`

**Comment by TheAlmightyBob** [comment]
Yeah the main README used to warn about `postMessage` but that was recently removed during some other cleanup... not certain why.

And the documentation you linked looks wrong/confusing, as the `WebView` `postMessage` method is not related to `onMessage`... it seems to be instead describing the `window.ReactNativeWebView.postMessage` that you can call from injected javascript.

**Comment by jccazeaux** [comment]
Indeed I did not understand the relation with `onMessage`. It makes more sense if it actually describes  `window.ReactNativeWebView.postMessage`

The warning or a deprecation notice would be helpful.

**Comment by k2xl** [comment]
```
const isAndroid = /Android/i.test(navigator.userAgent);
      const whereToAddListener = isAndroid ? document : window;
      whereToAddListener.addEventListener('message', ...
      ```
      
      Documenting for my future self (and any others). This worked for me.
