### ISSUE TITLE
How to hide the Url address bar?

### ISSUE THREAD

**Issue by neeteshraj** [react-native-webview/react-native-webview#2981]
I wan to hide the url address bar that is being rendered in my login screen. My login screen is to be rendered in a web view. How do i do it?

import React, { useEffect } from 'react';
import { View, Button, Alert, } from 'react-native';
import { authorize, AuthorizeResult } from 'react-native-app-auth';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { WebView } from 'react-native-webview';

const config = {
  clientId: 'Intranet_App',
  redirectUrl: 'http://192.168.18.75:8081',
  scopes: [
    'address',
    'email',
    'offline_access',
    'openid',
    'phone',
    'Portal',
    'profile',
    'role',
  ],
  serviceConfiguration: {
    authorizationEndpoint:
      'https://mbl-intranetsso.server247.info/Account/Login',
    tokenEndpoint: 'https://mbl-intranetsso.server247.info/connect/token',
    revocationEndpoint:
      'https://mbl-intranetsso.server247.info/connect/revocation',
    issuer: 'https://mbl-intranetsso.server247.info',
    jwksUri:
      'https://mbl-intranetsso.server247.info/.well-known/openid-configuration/jwks',
  },
};

const App: React.FC = () => {
  // co

  useEffect(() => {
    const loadWebView = async () => {
      try {
        const result: AuthorizeResult = await authorize(config);
        console.log(result);
        // Save the login token to AsyncStorage
        await AsyncStorage.setItem('loginToken', result.accessToken);
        // Handle the authentication result
      } catch (error) {
        console.error(error);
        // Handle the error
      }
    };

    loadWebView();
  }, []);

  return (
    <View style={{
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    }}>
      <WebView
        scalesPageToFit={true}
        source={{ uri: 'https://mbl-intranetsso.server247.info/Account/Login' }} // Replace with your WebView URL
        style={{ flex: 1, width: '100%'}}
      />
    </View>
  );
};

export default App;

![Screenshot_20230602_180542_Chrome](https://github.com/react-native-webview/react-native-webview/assets/37995777/115997ec-090e-4241-ad3b-09bb2e8d1d1f)

**Comment by TheAlmightyBob** [comment]
The WebView does not have an address bar. Your screenshot is of a Chrome Tab, not `react-native-web-view`.

Looks like that's coming from `react-native-app-auth`, which uses Chrome Tabs.
