### ISSUE TITLE
Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNCWebView' could not be found. Verify that a module by this name is registered in the native binary., js engine: hermes

### ISSUE THREAD

**Issue by Ghad1ee2r3** [react-native-webview/react-native-webview#2983]
I got this error when I run project of react native on IOS but on Android working fine

React Native Version : 
react-native-cli: 2.0.1
react-native: 0.71.8

I am using Expo 

How can I solve this issue , please ?

**Comment by MuazzezA** [comment]
Hello, I had the same problem. After installing the package, I couldn't build it. Let me explain how I solved it to you.
I deleted the "node_modules" folder.
I ran the command `yarn add react-native-webview@12.1.0`
Then I ran `yarn`
Finally, I ran `yarn start --reset-cache`

I hope the solution works for you 🥳

**Comment by vzts** [comment]
duplicate: https://github.com/react-native-webview/react-native-webview/issues/2959

**Comment by Ghad1ee2r3** [comment]
Thanks 
Downgrading to 11 version worked as mentioned in #2959 .
by using this command : yarn add react-native-webview@11

**Comment by bthiruven** [comment]
We're running react-native - 064 version and we had the same issue when we update the react-native-webview to 13.3.0. It looks like that react-native-webview is not linked correctly and what i found was to link the react-native-webview manually which throwed the "error source 7 does not have lambda expression", then we got to include the JAVA version 1.8 as compile options in react-nativew-webview like the one below and include it as a patch
```
 compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
}	
```

**Comment by Wilmela** [comment]
> duplicate: #2959

Can you please through more light on how to fix this? I am on expo managed workflow.

**Comment by Wilmela** [comment]
> We're running react-native - 064 version and we had the same issue when we update the react-native-webview to 13.3.0. It looks like that react-native-webview is not linked correctly and what i found was to link the react-native-webview manually which throwed the "error source 7 does not have lambda expression", then we got to include the JAVA version 1.8 as compile options in react-nativew-webview like the one below and include it as a patch
> 
> ```
>  compileOptions {
>         sourceCompatibility JavaVersion.VERSION_1_8
>         targetCompatibility JavaVersion.VERSION_1_8
> }	
> ```

Did you do this in a bare workflow or expo managed workflow?

**Comment by dondxniel** [comment]
@Wilmela, were you able to fix this? I'm using the expo managed workflow and all the solutions I can find are for bare react native cli based apps.

**Comment by soundaraj** [comment]
> We're running react-native - 064 version and we had the same issue when we update the react-native-webview to 13.3.0. It looks like that react-native-webview is not linked correctly and what i found was to link the react-native-webview manually which throwed the "error source 7 does not have lambda expression", then we got to include the JAVA version 1.8 as compile options in react-nativew-webview like the one below and include it as a patch
> 
> ```
>  compileOptions {
>         sourceCompatibility JavaVersion.VERSION_1_8
>         targetCompatibility JavaVersion.VERSION_1_8
> }	
> ```

How to manually linked?

**Comment by keitanamazue** [comment]
app.json
add
  "expo": {
 "jsEngine": "jsc"

**Comment by ivanvgarcia** [comment]
> @Wilmela, were you able to fix this? I'm using the expo managed workflow and all the solutions I can find are for bare react native cli based apps.

after installing the library try rebuilding your app `npx expo run:ios`

**Comment by Haukez** [comment]
Hey,
I use React Native in Expo. When running in development build mode it does not work, but when I use expo go it starts working. So I rebuild my likely outdated dev build with 'eas build --profile development --platform android' or you can do it locally and then the new build will worked again. Hope that helps

**Comment by opmat** [comment]
> Hey, I use React Native in Expo. When running in development build mode it does not work, but when I use expo go it starts working. So I rebuild my likely outdated dev build with 'eas build --profile development --platform android' or you can do it locally and then the new build will worked again. Hope that helps

Thanks @Haukez , this solved it for me

**Comment by franklinatdn** [comment]
After you install webview, you need to rebuild the apk with command `eas build -p android --profile development-android --local --output=xx.apk` then `adb install xx.apk`.

**Comment by ItaloVCosta** [comment]
If you are having this problem, just update you [expo](https://docs.expo.dev/workflow/upgrading-expo-sdk-walkthrough/). Usually an error appers when runnig your expo, like:
![Screen Shot 2024-01-11 at 19 38 27](https://github.com/react-native-webview/react-native-webview/assets/92797526/0b4f0e38-405c-48d7-a2a9-242f8226fb3e)

**Comment by shivammalhotra859** [comment]
i have downgraded react-native-webview package from 13.12.0 to 13.8.6, its working now

**Comment by olawalejuwonm** [comment]
> i have downgraded react-native-webview package from 13.12.0 to 13.8.6, its working now

I did that and it doesn't work

**Comment by simontoulouze** [comment]
Upgrading to 13.12.5 worked for me 👍

**Comment by TheForsakenSpirit** [comment]
`npx expo run:android ` - helped me.
