### ISSUE TITLE
Background images not loading in Android System WebView on actual TV device - any solutions?

### ISSUE THREAD

**Issue by jvishwesh** [react-native-webview/react-native-webview#2986]
I am facing one issue with Android System Webview. When updated to the latest version it is not loading any background images. It was working till early March. Earlier I thought it was due to Fabric Canvas JS but on later investigation found that when we uninstall the update for Android System Webview it is working as expected. I have tested with multiple versions of Android System Webview which I am mentioning below. This issue occurs only in Android TV's actual devices. Not in simulator

```
Android System Webview ==> 109.0.5414.80-541408013 ==> Working as expected
Android System Webview ==> 110.0.5481.154-548115403 ==> Working as expected
Android System Webview ==> 111.0.5563.58-556305803 ==> Break ==> March 22, 2023
```

Issue: I have a React native app in which I am using a WebView to load the website.

```
<WebView
    cacheEnabled={false}
    cacheMode='LOAD_NO_CACHE'
    source={{ uri: url }}     //URL for Website which is develop in React JS
    javaScriptEnabled={true}
    domStorageEnabled={true}
    geolocationEnabled={true}
    style={{ width: widthPercentageToDP(100), height: heightPercentageToDP(120) }}
    javaScriptCanOpenWindowsAutomatically={true}
    originWhitelist={['https://*', 'git://*', 'http://*']}
    mediaPlaybackRequiresUserAction={false}
/>
```

Inside the website, I am using fabric canvas js to load specific data

Website Code

```
let canvas = new fabric.Canvas();
canvas.setDimensions(this.state.canvasDimensions);
canvas.loadFromJSON(JSON.stringify(canvasJson), async function () {
    this.setState({
        imgURL: canvas.toDataURL({
            format: 'png'
        })
    })
})

render() {
    return(
        <img crossOrigin='anonymous' src={imgURL} style={{ height: 100, width: 100 }} />
    )
}
```

I have tried converting the image to a blob image. It is not working. I tried some custom image display packages.

**Comment by lilililee** [comment]
WebView add `mixedContentMode={ 'always'}` try again.

**Comment by jvishwesh** [comment]
> WebView add `mixedContentMode={ 'always'}` try again.

Hi @lilililee 
I have tried the above solution still have the same issue.

**Comment by duygutumer** [comment]
Have you found anything yet?

**Comment by jvishwesh** [comment]
> Have you found anything yet?

No, I haven't found anything yet other than uninstalling the latest update for Android System WebView

**Comment by lilililee** [comment]
Maybe you images size is too large，For example, the width exceeds 1920.
