### ISSUE TITLE
Browser does not support error while rendering Jitsi-meet video(iFrame)

### ISSUE THREAD

**Issue by sushantjadhav111** [react-native-webview/react-native-webview#2988]
**Bug description:**
Jitsi-meet video (iFrame ) with webview doesn't supported by browser, shows error expected to render meeting portal.

 <WebView
          renderers={renderers}
          WebView={WebView}
          originWhitelist={['*']}
          source={{
            html: `<iframe src=${url} allow="geolocation; microphone; camera; display-capture; display" style="width:100%;height:100%;" webkitallowfullscreen="true" mozallowfullscreen="true" allowfullscreen="true"></iframe>`,
          }}
        /> 
...
also tried 
...
<WebView
          startInLoadingState={true}
          scalesPageToFit={true}
          mixedContentMode="compatibility"
          source={{uri:url}}
           renderers={renderers}
          WebView={WebView}
        />

...
**Screenshots/Videos:**
![Simulator Screen Shot - iPhone 13 - 2023-06-06 at 16 54 45](https://github.com/react-native-webview/react-native-webview/assets/71134943/25f1c10f-fda0-4b71-9d14-3aa431e5eef7)

**Environment:**
 - OS:Monterey
 - OS version:12.6
 - react-native version:0.69.4
 - react-native-webview version:12.2.0

**Comment by akiannillo** [comment]
Have you solved this somehow?
