### ISSUE TITLE
jQuery event is not working on android version

### ISSUE THREAD

**Issue by Wings1986** [react-native-webview/react-native-webview#2992]
Here is html file used:

const links = document.querySelectorAll("a[href]");
[].forEach.call(links, (link) =>
  link.addEventListener("click", (e) => {
    e.preventDefault();
    let target = e.target;

    const title = target.text;       <---   got title= "Continue"
    const hrefUrl = target.href;     **<--- hrefUrl is empty**

 });

Here is react native code

<WebView
    ref={webViewRef}
    originWhitelist={["*"]}
    source={{ html: currentPage.html }}
    bounces={false}
    setSupportMultipleWindows={true}
    showsHorizontalScrollIndicator={false}
    showsVerticalScrollIndicator={false}
    javaScriptEnabled={true}
    startInLoadingState={true} // when starting this component
    javaScriptEnabledAndroid={true}
    scalesPageToFit={true}
    injectedJavaScript={window.isNativeApp = true; window.myPath = '${currentPage?.liquid?.page_current_url}';}
    mixedContentMode="compatibility"
    onNavigationStateChange={handleWebViewNavigationStateChange}
    onMessage={handleMessage}
/>

I got hrefUrl is empty on android version. but got correct value on iOS version
What is the solution?

**Comment by wflanagan** [comment]
I work with @Wings1986 as well. It's possible that the #2985 ticket is a similar thing? That some pages wouldn't "work" could be a clickable link issue?

**Comment by Masab-M** [comment]
had same issue on single first home page hamburger menu script is not working after build but work fine in expo and simulator
