### ISSUE TITLE
Crash: Error while updating property 'source' of a view managed by: RNCWebView

### ISSUE THREAD

**Issue by laurent22** [react-native-webview/react-native-webview#2995]
Upgraded from react-native-webview 11.26.1 to 12.4.0 and since then I'm getting this crash when the webview is opened:

> Error while updating property 'source' of a view managed by: RNCWebView
>
> null
>
> null

If that can make a difference the source is first set to `undefined` in our code, then soon after to `{"baseUrl": "file:///data/user/0/net.cozic.joplin/files/", "uri": "file:///data/user/0/net.cozic.joplin/files/NoteEditor.html?r=36630425"}`

- It doesn't happens on iOS
- It happen on Android

**Comment by laurent22** [comment]
Ok, found the issue, it's because when the source is null, our code set it to `{ uri: null }`. That works on iOS but crashes on Android. However when setting it to `{ uri: undefined }` it works without crashing.

So that's another breaking change in version 12. Perhaps it should be documented?

**Comment by Titozzz** [comment]
That's very unexpected, let me have a look

**Comment by Titozzz** [comment]
Probably that line: https://github.com/react-native-webview/react-native-webview/blob/master/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManagerImpl.kt#L384

It's expecting that if there is a "uri" field it will parse the string

**Comment by webraptor** [comment]
Anyone found a solution for this? getting it on android as well, on version 12.0.2, trying to load a local file. iOS has no issues

**Comment by Faseeh-Abbas-Khan** [comment]
@Titozzz I still am unable to resolve this issue on android.
Its working fine on IOS but not on android. Please look in to this

**Comment by Faseeh-Abbas-Khan** [comment]
@webraptor were you able to solve this?

**Comment by Faseeh-Abbas-Khan** [comment]
@laurent22 were you able to solve this?

**Comment by hakkikonu** [comment]
```
<WebView
    mediaPlaybackRequiresUserAction={true}
    source={{uri: url || undefined}}
/>
```

**Comment by drewm1192** [comment]
> ```
> <WebView source={{uri: url || undefined}} />
> ```

This worked for me. Thank you.

**Comment by prechy123** [comment]
> > ```
> > <WebView source={{uri: url || undefined}} />
> > ```
> 
> This worked for me. Thank you.

Where do i put this

**Comment by drewm1192** [comment]
> > > ```
> > > <WebView source={{uri: url || undefined}} />
> > > ```
> > 
> > 
> > This worked for me. Thank you.
> 
> Where do i put this

Here is an example of how I am using this. This is its own component and I call it in another component. 

```
  return (
    <>
      <SafeAreaView style={styles.safeContainer}>
        <TouchableOpacity
          onPress={() => navigation.navigate('Main')}
          style={styles.button}
        >
          <Text style={styles.submitText}>Close</Text>
        </TouchableOpacity>
      </SafeAreaView>
      {(!webviewUrl && !shouldShowWebView) || !isVisible && (
        <View style={[styles.loadingPage, {zIndex: 10}]}>
          <ActivityIndicator size={'small'} color={greenBackgroundColor}/>
          <Text style={styles.loadingText}>Connecting to WebView...</Text>
        </View>
      )}
      {webviewUrl && shouldShowWebView && (
        <WebView
          source={{ uri: webviewUrl }} 
          injectedJavaScript={...} // JS provided to me by the creator of the web view I am using
          onNavigationStateChange={_onNavigationStateChange} // a method I implemented
          onMessage={_onMessage} // a method I implemented
          thirdPartyCookiesEnabled={true}
          userAgent={...} // provided by the creator of the web view I am using
          mediaPlaybackRequiresUserAction={true}
        />
      )}
    </>
  );
```

**Comment by prechy123** [comment]
I have fixed this, turns out when I updated expo cause of SDK 52, I didn't install it's dependencies but thanks tho

**Comment by prechy123** [comment]
> > > > ```
> > > > <WebView source={{uri: url || undefined}} />
> > > > ```
> > > 
> > > 
> > > This worked for me. Thank you.
> > 
> > Where do i put this
> 
> Here is an example of how I am using this. This is its own component and I call it in another component. 
> 
> ```
>   return (
>     <>
>       <SafeAreaView style={styles.safeContainer}>
>         <TouchableOpacity
>           onPress={() => navigation.navigate('Main')}
>           style={styles.button}
>         >
>           <Text style={styles.submitText}>Close</Text>
>         </TouchableOpacity>
>       </SafeAreaView>
>       {(!webviewUrl && !shouldShowWebView) || !isVisible && (
>         <View style={[styles.loadingPage, {zIndex: 10}]}>
>           <ActivityIndicator size={'small'} color={greenBackgroundColor}/>
>           <Text style={styles.loadingText}>Connecting to WebView...</Text>
>         </View>
>       )}
>       {webviewUrl && shouldShowWebView && (
>         <WebView
>           source={{ uri: webviewUrl }} 
>           injectedJavaScript={...} // JS provided to me by the creator of the web view I am using
>           onNavigationStateChange={_onNavigationStateChange} // a method I implemented
>           onMessage={_onMessage} // a method I implemented
>           thirdPartyCookiesEnabled={true}
>           userAgent={...} // provided by the creator of the web view I am using
>           mediaPlaybackRequiresUserAction={true}
>         />
>       )}
>     </>
>   );
> ```

I have fixed this, turns out when I updated expo cause of SDK 52, I didn't install it's dependencies but thanks tho
