### ISSUE TITLE
Build failed on Android with newArchEnabled

### ISSUE THREAD

**Issue by thanhloc-17** [react-native-webview/react-native-webview#2996]
**Bug description:**
I enabled newArchEnabled and build app on Android, there's a problems:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/app/node_modules/react-native-webview/android/build.gradle' line: 88

* What went wrong:
A problem occurred evaluating project ':react-native-webview'.
> Ambiguous method overloading for method java.io.File#<init>.
  Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
        [class java.lang.String]
        [class java.net.URI]
```
**To Reproduce:**
1. Enabled newArchEnabled=true on ./gradle.properties
2. Run ./gradlew clean or build android

**Temporarily fix:**
1. Open file node_modules/react-native-webview/android/build.gradle
2. Change:
`def codegenPath = findNodeModulePath(projectDir, "react-native-codegen")`
to
` def codegenPath = findNodeModulePath(projectDir, "@react-native/codegen")`
It work well

**Environment:**
 - OS: MacOS
 - react-native version: 0.72.0-rc.5
 - react-native-webview version: 13.2.0
 - Expo: 49.0.0-alpha.3

**Comment by Titozzz** [comment]
https://github.com/react-native-webview/react-native-webview/pull/2997

**Comment by yogesh-babu-potnuri** [comment]
newArchEnabled=true
Node.js v23.10.0

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-webview:generateCodegenArtifactsFromSchema'.
> Process 'command 'node'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 6s
error Failed to install the app. Command failed with exit code 1: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
No modules to process in combine-js-to-schema-cli. If this is unexpected, please check if you set up your NativeComponent correctly. See combine-js-to-schema.js for how codegen finds modules.
/Users/sespl/Desktop/OLMS/olms-2/mobile/node_modules/react-native/node_modules/@react-native/codegen/lib/generators/components/GenerateEventEmitterCpp.js:311 throw new Error( ^ Error: Received invalid event property type StringLiteralUnionTypeAnnotation at /Users/sespl/Desktop/OLMS/olms-2/mobile/node_modules/react-native/node_modules/@react-native/codegen/lib/generators/components/GenerateEventEmitterCpp.js:311:17 at Array.map (<anonymous>) at generateSetters (/Users/sespl/Desktop/OLMS/olms-2/mobile/node_modules/react-native/node_modules/@react-native/codegen/lib/generators/components/GenerateEventEmitterCpp.js:260:6) at generateEvent (/Users/sespl/Desktop/OLMS/olms-2/mobile/node_modules/react-native/node_modules/@react-native/codegen/lib/generators/components/GenerateEventEmitterCpp.js:333:7) at /Users/sespl/Desktop/OLMS/olms-2/mobile/node_modules/react-native/node_modules/@react-native/codegen/lib/generators/components/GenerateEventEmitterCpp.js:386:25 at Array.map (<anonymous>) at /Users/sespl/Desktop/OLMS/olms-2/mobile/node_modules/react-native/node_modules/@react-native/codegen/lib/generators/components/GenerateEventEmitterCpp.js:386:12 at Array.map (<anonymous>) at generate (/Users/sespl/Desktop/OLMS/olms-2/mobile/node_modules/react-native/node_modules/@react-native/codegen/lib/generators/components/GenerateEventEmitterCpp.js:383:8) at Object.generate (/Users/sespl/Desktop/OLMS/olms-2/mobile/node_modules/react-native/node_modules/@react-native/codegen/lib/generators/RNCodegen.js:212:9) Node.js v23.10.0 FAILURE: Build failed with an exception. * What went wrong:
Execution failed for task ':react-native-webview:generateCodegenArtifactsFromSchema'.
Any permant solution that can be avoid

**Comment by omatt** [comment]
@yogesh-babu-potnuri I patched the react-native-webview package with https://github.com/react-native-webview/react-native-webview/issues/3737#issuecomment-2878181942 and it fixed the issue for me.

newArchEnabled=true
"react-native": "0.77.1",
"react-native-webview": "13.13.4",
