### ISSUE TITLE
Browser don't support shown in IPhone, when iFrame embedded through react-native-render-html inside webview

### ISSUE THREAD

**Issue by sushantjadhav111** [react-native-webview/react-native-webview#3004]
**Bug description:**
Browser don't support message shown in IPhone, when iFrame embedded through react-native-render-html inside webview
Code:
<RenderHTML
        contentWidth={width}
        renderers={renderers}
        WebView={WebView}
        source={{
          html: `<iframe src=${url} allow="geolocation; microphone; camera; display-capture; display" style="width:100%;height:100%;" webkitallowfullscreen="true" mozallowfullscreen="true" allowfullscreen="true"></iframe>`,
        }}
        customHTMLElementModels={{iframe: iframeModel}}
        defaultWebViewProps={{
          scalesPageToFit: true,
          startInLoadingState: true,
          originWhitelist: ['*'],
          javaScriptEnabled: true,
          viewportContent:
            'width=device-width, height=device-height, user-scalable=no',
          style: {
            width: Dimensions.get('window').width,
            height:  height,
          },

          automaticallyAdjustContentInsets: false,
        }}
        renderersProps={{
          iframe: {
            scalesPageToFit: true,
            removeBodySpacing: true,
            injectedCSSStyles: 'style',
            webViewProps: {
              containerStyle: {
                flex: 0,
                height: height,
              },
              javaScriptEnabled: true,
              scalesPageToFit: true,
              mediaCapturePermissionGrantType: true,
              allowsInlineMediaPlayback: true,
              mediaPlaybackRequiresUserAction: false,
              originWhitelist: ['*'],
              scrollEnabled: true,
              androidHardwareAccelerationDisabled: true,
              useWebKit: false,
              sharedCookiesEnabled: true,
            },
          },
        }}
      />

**Expected behavior:**
Video conferencing view should be render inside webview

**Environment:**
 - OS: iOS
 - OS version:12.6
 - react-native version:69.4
 - react-native-webview version:11.26.1
 - react-native-render-html version:5.1.0

**Comment by linonetwo** [comment]
@sushantjadhav111 be aware of your markdown syntax.
