### ISSUE TITLE
ignoreSilentHardwareSwitch: property does not work, audio

### ISSUE THREAD

**Issue by qaverill** [react-native-webview/react-native-webview#3010]
**Bug description:**
Hello! I have a react-native app using react-native-webview (love it by the way, it's a life saver!) to play audio, and suddenly after updating to iOS 16.4 it stopped working when the device's silent switch is turned on. It worked prior to 16.4, but now it does. I've tried setting `ignoreSilentHardwareSwitch` to true, but it still doesn't work. Please help!

**To Reproduce:**
- make webview that plays audio
- set `ignoreSilentHardwareSwitch` to true
- run, and trigger the sound to play in the app
- turn the silent switch off, sound plays
- turn the silent switch on... sound does not play

**Expected behavior:**
when`ignoreSilentHardwareSwitch` is set to true, all audio from the webview should still play on the device, regardless of the silent switch

**Environment:**
 - OS: iOS
 - OS version: 16.4
 - react-native version: 0.71.11
 - react-native-webview version: 13.2.2

**Comment by shukla12manish** [comment]
Hi @qaverill I am facing the same issue. Have you got any resolution for the same or is there any other way to solve this issue.

**Comment by smourey** [comment]
Hi @qaverill and @shukla12manish, I am facing the same issue too... Have you found any other way to solve this issue? Thank you.

**Comment by Furciferrr** [comment]
the same issue. any updates?

**Comment by dunajevas** [comment]
any updates on this?

**Comment by zhen1007** [comment]
Any update? It's blocking issue.

**Comment by qaverill** [comment]
still having this problem, reopening

**Comment by mycloudvip** [comment]
Welcome to the new year! I guess no update on that as well. It would be acquard to ask the user to unmute the phone after my welcome screen does play audio, since it is launched from within the code with "expo-av". Hope there's a fix soon!

**Comment by bertrandmc** [comment]
For anyone struggling with this lately, this was the only solution that worked for me 
https://www.audjust.com/blog/unmute-web-audio-on-ios

> iOS has odd behavior when you try to play audio using the [Web Audio API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API) with the ringer switch off (set to mute/on vibrate): for some reason, there will be no audible playback. But if you try to play a regular but of audio using the audio element it works. If you play both at the same time, you will hear both audio sources. So one way we can fix this is to play a blank bit of sound which will unblock playback. Below is a code snippet as example:

```
import { start } from "tone";

let hasUnblocked = false;
export function unblockPlayback() {
	if (hasUnblocked) return;
	hasUnblocked = true;

	// unblock playback when iOS is set to silent
	const audio = document.createElement("audio");
	audio.setAttribute("x-webkit-airplay", "deny");
	audio.preload = "auto";
	audio.loop = true;
	audio.src = emptyMp3FileSrc;
	audio.play();

	// have Tone.js unblock playback on interaction
	start();
}
```
