### ISSUE TITLE
Changing from dark -> light mode does not propagate to web view until a manual screen rotation

### ISSUE THREAD

**Issue by jcarioti** [react-native-webview/react-native-webview#3013]
**Bug description:**
Changing the system theme from light -> dark does not propagate to RN WebViews on Android until a device rotation. After rotating the device, the WebView will correct itself and display the correct theme that matches the system. 

**This seems to be only affecting my Galaxy S devices**, my Pixel devices are working as expected.

**To Reproduce:**
Create a barebones React Native app with the latest and greatest of everything, add a single WebView to the root of the project, navigate the web view to `https://www.getbootstrap.com`, make sure the Bootstrap website has the "Auto Theme" enabled so it follows the system, and toggle back and forth between dark and light mode via the OS UI. As you toggle back and forth, notice that dark -> light works as expected, but light -> dark results in the WebView theme being out of sync with the system theme.

**Expected behavior:**
As the system theme changes, the WebView theme changes without needing a manual intervention.

**Screenshots/Videos:**
https://github.com/react-native-webview/react-native-webview/assets/4457848/2c6420dc-afb4-4e1b-8f39-4a7288bed6b7

I start the video by making sure that the Bootstrap website is using the "Auto" theme. Notice after the light -> dark transition that the website is still in light mode until the device rotates right around the 28 second mark.

**Environment:**
 - OS: Android (Samsung)
 - OS version: 13
 - react-native version: 0.71.11
 - react-native-webview version: 13.2.2

**Comment by jcarioti** [comment]
Some extra info: I decided to try the standalone Chrome browser from the Galaxy S21, and it reacts to the theme changes appropriately every time. So it seems to be something specific to this WebView implementation that's causing the issue.

**Comment by jcarioti** [comment]
No one else having this issue?

**Comment by 205g0** [comment]
I have this issue too, on Android and iOS

**Comment by jcarioti** [comment]
> I have this issue too, on Android and iOS

I was only seeing it on Android - specifically Samsung devices. You're seeing it across platforms?

**Comment by 205g0** [comment]
everywhere, moved to Swift since

**Comment by squio** [comment]
We just discovered this in our production app and it is a real blocker because we now get black text on black backgrounds due to some unfortunate combination of configuration so yes, this definitely is a bug 😢

**Comment by 205g0** [comment]
@Titozzz any news on this issue?

**Comment by squio** [comment]
Apart from this issue I noticed that the `setForceDark` property does not work in recent Android

Additionally:

- Media queries don't work: `window.matchMedia('(prefers-color-scheme: dark)')`
- The WebView's background has become transparent by default (not bad IMO but still a change)

I reports about the removal of `setForceDark` in this issue:  #3253

As a work around we now call `injectJavaScript` with `document.body.classList.add('dark');` and adapted the html / css in the WebView acordingly; this will most likely not work for 3rd party content however

**Comment by jcarioti** [comment]
I think setForceDark has been deprecated, which was right around the time this issue started for me.

**Comment by daniharo** [comment]
This is not fixed yet. Webview in Android gets stuck in light mode.

**Comment by freakingeek** [comment]
Still not working
Android 12
