### ISSUE TITLE
Scroll position of ScrollView jumps to WebView when pressed

### ISSUE THREAD

**Issue by vigneshrajs** [react-native-webview/react-native-webview#3014]
**Bug description:**
When pressing a WebView inside a scrollable ScrollView, the scroll position jumps down to the WebView.

**To Reproduce:**
 - Install React Native version 0.71.3 and React Native webview Version 11.25.0
 - Place webview inside ScrollView.
 
The first time you press, it will jump down slightly.

**Expected behavior:**
When clicking a WebView inside a ScrollView, it should not change the scroll position of the parent ScrollView.

**Environment:**
 - OS: Android
 - OS version: >11
 - react-native version: 0.71.3
 - react-native-webview version: 11.25.0

**Comment by knakandakare** [comment]
Same issue here

**Comment by sanduluca** [comment]
I have same issue. 
It was also reported here: #2360 #2057 
I also reported this issue in another repo ( here: https://github.com/iou90/react-native-autoheight-webview/issues/259 ) but it seems to be a problem with WebView



**Bug description:**
Content jumps to top on first time press/click

**To Reproduce:**

**To test on real device**
1. Open the screen
2. Press the webview content

**Source (static HTML or url):**
https://snack.expo.dev/VhrGR3bC5

1. Scan qr code and open app on a real android device
2. Press any area below first white section
To reproduce start from 1

**Expected behavior:**
No jump when press webview content

**Screenshots/Videos:**

https://github.com/iou90/react-native-autoheight-webview/assets/56228534/6155f52b-e469-4eaf-a105-fe863665b3b5


**Environment:**
 - OS: Android
 - OS version: 12
 - react-native version: 0.71.7
 - react-native-webview version: ^12.0.2
 - react-native-autoheight-webview version: ^1.6.5

**Comment by TheAlmightyBob** [comment]
It looks like the auto-scrolling is a behavior of the React Native ScrollView.

The only thing I imagine could be done from the `react-native-webview` side would be to set `focusable` to `false`... but I think that only makes sense if your WebView content is completely noninteractive? If that _is_ your scenario, you could try hacking/patching in that change to see if it helps.

**Comment by sanduluca** [comment]
> It looks like the auto-scrolling is a behavior of the React Native ScrollView.
> 
> The only thing I imagine could be done from the `react-native-webview` side would be to set `focusable` to `false`... but I think that only makes sense if your WebView content is completely noninteractive? If that _is_ your scenario, you could try hacking/patching in that change to see if it helps.

The `focusable={false}` on <WebView /> doesn't seem to help with content jump. Tried on the snack I provided above.

**Comment by TheAlmightyBob** [comment]
> focusable={false} on <WebView /> doesn't seem to help with content jump

I'm not sure the `focusable` property is actually hooked up (in fact I wonder if it's a mistake that `WebViewSharedProps` extends `ViewProps`...). I think this would require changing the native Android code.

**Comment by steffenkleinle** [comment]
Sadly we are still searching for solutions

**Comment by huanguolin** [comment]
same issue here

**Comment by sh-shamsan** [comment]
Same issue here

**Comment by steffenkleinle** [comment]
We are still looking for solutions

**Comment by steffenkleinle** [comment]
We are sadly still experiencing this :/

**Comment by steffenkleinle** [comment]
This sadly still happens :/

**Comment by lvmtam** [comment]
This sadly still happen with me too :/

**Comment by ashlyWeiting** [comment]
I added the following code to my project, which can temporarily solve the problem. However, if there are two WebViews with a focused state within a ScrollView, this solution will not work. Therefore, I am looking for alternative methods.

```
<WebView
  ref={ref => {
    if (Platform.OS === 'android') {
      ref?.requestFocus();
    }
  }}
```

**Comment by KubilayMobile** [comment]
Still happening

**Comment by samuel-apps** [comment]
Alright, this may be an unpopular opinion, but I had to fix this today and by god would I fix it. So here's the band-aid I crafted, it relies on a `ref` to the `ScrollView`, a `ref` to the `WebView` and a `boolean` state signifying whether the `WebView` content was loaded.

```typescript
  // Prevent initial touch jumping ([REDACTED]-78)
  //#region Here be dragons. Thou art forewarned.
  /**
   * When an element in a ScrollView is focused, the ScrollView
   * will scroll to it. And, of course, a WebView is focusable.
   * And, OF COURSE, you can't make it unfocusable. A N D O F
   * C O U R S E , you can't prevent a ScrollView from scrolling
   * to a focused element.
   * 
   * Whether this is a bug or a feature has apparently been the
   * subject of heated debate for years. Either way, [REDACTED] 
   * doesn't appreciate it, and neither do we.
   * 
   * So, to prevent the scrollview from unexpectedly jumping with
   * the first light touch, we focus the scrollview ourselves.
   * 
   * If I'm going down, I'm going down on my own terms.
  **/
  useEffect(() => {
    webViewRef.current?.requestFocus();
    scrollViewRef.current?.scrollTo({ x: 0, y: 0, animated: false });
  }, [loaded]);
  //#endregion
```

Yes, I write novels in my comments, you try remaining sane for nearly 20 years in this industry. 

Anyway, long story short; Focus the `WebView` before the user does it, and reset the scroll position immediately after. The user shouldn't see any of this, and since the `WebView` is now focused it can't be focused again until you unfocus it. And if you for whatever reason need to unfocus it... Good luck, buddy.

**Comment by ashlyWeiting** [comment]
I found a temporary, quick, and forceful way to solve the issue. 

Add the following content to `node_modules/android/src/main/java/com/reactnativecommunity/webview/RNCWebView.java`:

```java
    @Override
    public boolean requestFocus(int direction, Rect previouslyFocusedRect) {
        if (this.focusEnabled == false) {
            return false;
        }
        return super.requestFocus(direction, previouslyFocusedRect);
    }    
```

However, this will cause input or textarea elements inside the WebView to lose the ability to focus and bring up the keyboard. 

So, I forked a project:  
[https://github.com/ashlyWeiting/react-native-webview](https://github.com/ashlyWeiting/react-native-webview)  
You can modify it based on your needs to control whether the WebView can be focused or not.

Here’s an example:

```javascript
const webViewScript = `
  (function() {
    const inputs = document.getElementsByTagName('input');
    const textareas = document.getElementsByTagName('textarea');
    const focusableElements = [...inputs, ...textareas];
    window.ReactNativeWebView.postMessage(focusableElements.length > 0 ? 'allow-focus' : 'disallow-focus');
  
    return true;
  })();
`;

const [focusEnabled, setFocusEnabled] = useState<boolean>(false);

const onMessage = (event: WebViewMessageEvent) => {
  const message = event.nativeEvent.data;
  if (message === 'allow-focus') {
    setFocusEnabled(true);
  } else if (message === 'disallow-focus') {
    setFocusEnabled(false);
  }
}

<WebView
  focusEnabled={focusEnabled}
  injectedJavaScript={webViewScript}
/>
```

Although it’s not the best solution, I hope it helps those who urgently need to resolve this issue.

**Comment by duck123ducker** [comment]
Here are some experiences from native Android developers. Unfortunately, the ScrollView component in React Native does not expose this property, so there isn't much we can do.😥

> Due to focus issues, you only need to add one property to the child controls of ScrollView: android:descendantFocusability = "blocksDescendants"
> 
```
<LinearLayout
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:descendantFocusability="blocksDescendants"
    android:orientation="vertical">
```
> The API description is as follows: android:descendantFocusability
> 
> Defines the relationship between the ViewGroup and its descendants when looking for a View to take focus.

**Comment by steffenkleinle** [comment]
#3575 fixes the issue for us. This fork already includes the fix: https://github.com/birdofpreyru/react-native-webview

**Comment by cguino** [comment]
I made a patch based on https://github.com/birdofpreyru/react-native-webview
I did some fixes as the code android did not compile 
Also I'm not sure everything is needed ... 


[react-native-webview+13.12.5.patch](https://github.com/user-attachments/files/18153140/react-native-webview%2B13.12.5.patch)

**Comment by kubmir** [comment]
This issue is happening again for me on Android 15. It looks fine for older Androids but as soon as I click to web view on Android 15 it scrolls to the top of the screen -> in a same way as described in the video above.

**Comment by birdofpreyru** [comment]
@kubmir I've just tested it for Android 15, on Emulator, using my fork of the library and its Example app (the `WEBVIEWINSIDESCROLLVIEW` test inside it) &mdash; I don't see the problem re-appearing.
