### ISSUE TITLE
After a "pinch to zoom" action, every "drag" with a single finger acts as a "zoom" action

### ISSUE THREAD

**Issue by lorenzolaricchia** [react-native-webview/react-native-webview#3019]
**Bug description:**
On Android only, after a "pinch to zoom" action, every "drag" with a single finger acts as a "zoom" action (like I'm using still two fingers).

**To Reproduce:**
- Android platform
- Add WebView inside a component. As `uri` use a page in which it is possible to make a "pinch to zoom" action, like `maps.google.com`.
- Try to zoom in with a "pinch to zoom" action.
- Try to drag with a single finger in any direction (A zoom-in zoom-out action will be triggered even if you're using one finger).

**Expected behavior:**
It should be possible to execute the "zoom in" and "zoom out" action as expected (like on iOS, where it works perfectly).

**Screenshots/Videos:**
_Private project_

**Environment:**
 - OS: Android
 - OS version: >11
 - react-native version: 0.71.7
 - react-native-webview version: 13.2.2

**Comment by francesco-cerio** [comment]
Hello, i'm experiencing the same issue with the same Environment. Is there any solution?

**Comment by TheAlmightyBob** [comment]
Have you tried older versions? I don't have the latest running right now (and it seems Expo doesn't support 12+? 😕 ), but this behaves as expected for me with 11.26.1
