### ISSUE TITLE
Crash when having multiple webviews after version 13.0.0

### ISSUE THREAD

**Issue by ororsatti** [react-native-webview/react-native-webview#3020]
**Bug description:**
Theres a crash when webview on multiple tabs.
I suspect the issue got in on PR #2930 ,since using earlier versions works.

I am not sure what the solution is here, maybe mark it as unsafe that you have to pass a prop to get it ?
**To Reproduce:**
Here's a repo I created: [webview-memory-leak](https://github.com/ororsatti/webview-memory-leak)

**Screenshots/Videos:**

https://github.com/react-native-webview/react-native-webview/assets/109456266/42682df5-940f-42a4-92eb-541d8df90ae5

**Environment:**
 - OS: iOS
 - OS version: doesnt matter
 - react-native version: 0.72
 - react-native-webview version: 13.0.0

**Comment by TheAlmightyBob** [comment]
Are you using something to detect an actual memory leak here? The repo you linked just mentions a crash. I've experienced an occasional crash with version 13 but I don't _think_ it's a leak... in my experience it happens "randomly," including sometimes on only the second WebView (or perhaps cleaning up the first? I'm still not certain of the cause)...

**Comment by ororsatti** [comment]
> Are you using something to detect an actual memory leak here? The repo you linked just mentions a crash. I've experienced an occasional crash with version 13 but I don't _think_ it's a leak... in my experience it happens "randomly," including sometimes on only the second WebView (or perhaps cleaning up the first? I'm still not certain of the cause)...

Good point, I didn't use anything to identify that its a memory leak, the error logs and the stack trace of iOS led me to believe it was, but I am not sure for certain it is.

I'd be happy to help debugging this.
Also changing the title.
