### ISSUE TITLE
on Message not called on Windows platform

### ISSUE THREAD

**Issue by SnehilPatidar** [react-native-webview/react-native-webview#3023]
Hello,
 I have implemented a video player using Webview.
 I have inject below injectJavaScript :- 
 
  webViewRef.current.injectJavaScript = `
    const video = document.getElementById('norcatVideo');

    function sendMessage() {
      window.ReactNativeWebView.postMessage(video.currentTime.toString());
    } 
    //For showing progress slider
    video.addEventListener('timeupdate', sendMessage);

    function sendVideoloadMessage() {
      // Get video duration, width, and height
      var duration = this.duration;
      var width = this.videoWidth;
      var height = this.videoHeight;
      

      //For setting the duration, height and widht of the video
      window.ReactNativeWebView.postMessage(JSON.stringify({ duration, width, height }));
    }

    document.querySelector('video').addEventListener('loadedmetadata', sendVideoloadMessage);

    document.querySelector('video').addEventListener('ended', function() {
    // Post a message back to the WebView when the video ends
    window.ReactNativeWebView.postMessage(JSON.stringify({event :'VideoEnded'}));
    });
  `;
  
 I don't get any message on onMessage on Windows platform but it works fine on MacOS

**Environment:**
 - OS: Windows 
 - React-native-windows version: 0.68.30
 - react-native version:  0.68.0
 - react-native-webview version: 11.26.1

**Comment by chiaramooney** [comment]
I believe `injectJavascript` is not implemented on Windows for WebView or WebView2

**Comment by wirthwhiledev** [comment]
I ended up finding a solution related to this problem. 

 I was unable to send a stringify-ed object using JSON.stringify with window.ReactNativeWebView.postMessage. 

example (this did not work)
`window.ReactNativeWebView.postMessage(JSON.stringify({event :'VideoEnded'}));
`

However, if I double stringify-ed my object then the postMessage succeeded...not super clear why


example (this DID work)
`const wrapper = JSON.stringify(JSON.stringify({event :'VideoEnded'}));
window.ReactNativeWebView.postMessage(wrapper)
`

I had to deal with this double string crap on the "backend" but at least my messages were getting across. 

OS: Windows
React-native-windows version: 0.71.4
react-native version: 0.71.5
react-native-webview version: 12.0.2

**Comment by chiaramooney** [comment]
ping to reopen

**Comment by rafaelmonroy** [comment]
noticing the PR that was merged causes my app to crash when accessing the screen that has the webview 

```
          <WebView
            ref={webViewRef}
            mixedContentMode="always"
            startInLoadingState={true}
            sharedCookiesEnabled
            nestedScrollEnabled
            cacheEnabled
            useWebView2
            style={webviewDimensions}
            source={{ uri: formattedUrl }}
            onMessage={({ nativeEvent: { data } }) => {
              console.log('data', data)
            }}
            onError={({ nativeEvent: error }) => {
              console.log('error',error)
              setConnectionError(true)
            }}
            onLoadEnd={getDeviceInfo}
          /> 
```

nothing else changed in my project other than installing the new 13.7.0 v 

when downgrading to v 13.6.4, app works as expected

**Comment by chiaramooney** [comment]
Thanks, I'll alert the PR author.

**Comment by chiaramooney** [comment]
The author wasn't able to repro the crash locally. Do you have a stack trace I could provide them with? @rafaelmonroy

**Comment by rafaelmonroy** [comment]
@chiaramooney I do not, the app crashes without error, it actually also crashes my visual studio code when building through there. One thing I noticed is that I don't experience any issues when I remove the useWebView2 flag. I am wondering if its maybe a an env issue. Is there any updated documentation for running webview using the WebView2 on a C# project?

**Comment by chiaramooney** [comment]
We've caught the culprit of the bug. A fix should be on the way shortly.
