### ISSUE TITLE
Kotlin version issue ,react native build is failing

### ISSUE THREAD

**Issue by ashirkhan94** [react-native-webview/react-native-webview#3024]
After upgrade gradle version from 7.3.3 to 7.5
we getting below issue
```
The Android Gradle plugin supports only kotlin-android-extensions Gradle plugin version 1.6.20 and higher.
The following dependencies do not satisfy the required version:
project ':react-native-webview' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.0
```
The project `build.gradle` contain `kotlin_version = '1.6.20'`
but in `react-native-webview` contain `ReactNativeWebView_kotlinVersion=1.6.0`

<img width="1041" alt="Screenshot 2023-06-26 at 12 24 32 PM" src="https://github.com/react-native-webview/react-native-webview/assets/52521541/7b08f192-1f26-4c03-bf7b-38abe4044f80">

 - OS: macOS
 - OS version:13.2
 - react-native version: 66.3
 - react-native-webview version: 13.2.2

I saw some same issues but those are closed

**Comment by Garguy** [comment]
Same issue here with React Native 71 and WebView 13.2.2

**Comment by salimkt** [comment]
Same issue here also

**Comment by mohzameer** [comment]
I forked and updated ReactNativeWebView_kotlinVersion to my project version.
https://github.com/react-native-webview/react-native-webview/blob/master/android/gradle.properties

I sent a PR https://github.com/react-native-webview/react-native-webview/pull/3035

**Comment by esalaza** [comment]
I went with a [patch-package](https://www.npmjs.com/package/patch-package) in the meantime (for `12.4.0`):

```patch
diff --git a/node_modules/react-native-webview/android/build.gradle b/node_modules/react-native-webview/android/build.gradle
index b38e813..55f8031 100644
--- a/node_modules/react-native-webview/android/build.gradle
+++ b/node_modules/react-native-webview/android/build.gradle
@@ -9,7 +9,7 @@ buildscript {
         gradlePluginPortal()
     }
     dependencies {
-        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:${safeExtGet('kotlinVersion')}")
+        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.20"
         classpath("com.android.tools.build:gradle:7.0.4")
     }
 }
```

**Comment by markholland** [comment]
Ideally this library should decide what kotlin version it needs. We're not writing any kotlin so doesn't make sense for our project to set one. Will have to go with the patch until resolved.

**Comment by remi-sustainablechoice** [comment]
having this issue still, any progress?

**Comment by mohzameer** [comment]
@remi-sustainablechoice Temporary fix until library update: apply patch-package or fork and apply the kotlin version.

**Comment by nicolas-meilan** [comment]
try to add `kotlinVersion = "1.7.20"` to `android/build.gradle - buildscript.ext`

**Comment by hengkx** [comment]
having this issue still, any progress?
