### ISSUE TITLE
Crash on Huawei P30: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x30 in tid 25540 (RenderThread)

### ISSUE THREAD

**Issue by aureosouza** [react-native-webview/react-native-webview#3026]
**Bug description:**
Crashing when opening WebView component on Huawei P30 (still has Google Play Services), no stack trace available. Other devices are ok.

**To Reproduce:**
Just try rendering a simple <WebView /> component.

**Expected behavior:**
We are expecting to be able to use the WebView, if it's not technically possible for this device at least no crash, maybe some try/catch would help.

**Environment:**
 - OS: Android
 - OS version: 12
 - react-native version: 0.71.8
 - react-native-webview version: 13.2.2

**Comment by nikitpanchal** [comment]
Same error here , Crashing in all android devices

**Comment by TIGER272** [comment]
Same error here

**Comment by TIGER272** [comment]
textZoom is creating crash in our case

**Comment by ShaoGongBra** [comment]
me

**Comment by onatvaris** [comment]
https://github.com/facebook/react-native/issues/32547#issuecomment-962009710

you can try. I have observed that such problems are solved with the ```androidLayerType```  parameter.

**Comment by mscloud-1** [comment]
I solved with the webviewDebuggingEnabled parameter.
