### ISSUE TITLE
The native video window opens in full-screen mode.

### ISSUE THREAD

**Issue by ValyaBabenkov** [react-native-webview/react-native-webview#3028]
How to prevent a native modal window from opening

My code
 ```
<WebView
                mediaPlaybackRequiresUserAction={false}
                allowsInlineMediaPlayback
                source={{ uri: currentItem?.url, ...authHeader() }}
            />
```

**Environment:**
 - react-native version: 0.70.5
 - react-native-webview version: 11.26.1

![Simulator Screen Shot - iPhone 14 Pro - 2023-06-30 at 11 03 36](https://github.com/react-native-webview/react-native-webview/assets/53038415/55168c19-9719-4410-89ae-27218ea524bd)

**Comment by tivadarbocz** [comment]
Is there any update on this issue? I'm experiencing the same.

**Comment by hannojg** [comment]
I think you almost had it right you just need to change `mediaPlaybackRequiresUserAction={true}` to **true**

**Comment by SliverYuki** [comment]
Is there any new progress on this issue? I have encountered the same situation.
