### ISSUE TITLE
Underline and Strikethrough having conflicts using it.

### ISSUE THREAD

**Issue by AugustoAleGon** [react-native-webview/react-native-webview#3036]
**Bug description:**

- Using the webview on the library `react-native-pell-rich-editor` I have found that underline and strikethrough styles have conflicts with each other, causing that the rich editor doesn't work as expected.

This bug is opened by this comment https://github.com/wxik/react-native-rich-editor/issues/127#issuecomment-847632668 

**To Reproduce:**

- Create a bare bone React Native project.
- Install `react-native-web-view` and `react-native-pell-rich-editor`.
- After applying bold and italic with underline the style is being applied correctly.
- After press Strikethrough the styles are being applied correctly.
- After press underline there is a condition one or the other, so both gets removed.

This is the example code:

```
import React from 'react';
import {
  SafeAreaView,
  StyleSheet,
  Text,
  ScrollView,
  KeyboardAvoidingView,
  Platform,
} from 'react-native';
import {actions, RichEditor, RichToolbar} from 'react-native-pell-rich-editor';

const handleHead = ({tintColor}) => <Text style={{color: tintColor}}>H1</Text>;

const App = () => {
  const richText = React.useRef();

  return (
    <SafeAreaView>
      <ScrollView>
        <KeyboardAvoidingView
          behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
          style={styles.wrapperContainer}>
          <Text>Description:</Text>
          <RichEditor
            ref={richText}
            onChange={descriptionText => {
              console.log('descriptionText:', descriptionText);
            }}
          />
        </KeyboardAvoidingView>
      </ScrollView>

      <RichToolbar
        editor={richText}
        actions={[
          actions.setBold,
          actions.setItalic,
          actions.setUnderline,
          actions.heading1,
          actions.insertOrderedList,
          actions.insertBulletsList,
          actions.setStrikethrough,
        ]}
        selectedButtonStyle={{backgroundColor: '#1E1E1E'}}
        iconMap={{[actions.heading1]: handleHead}}
      />
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  wrapperContainer: {
    flex: 1,
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
});

export default App;

```

**Expected behavior:**

- After press Strikethrough the styles are being applied correctly.
- After press underline there is a condition one or the other, one should persist.

**Screenshots/Videos:**

https://github.com/react-native-webview/react-native-webview/assets/14319083/5d61876a-77f9-4a04-b81a-c18f7acefe98

**Environment:**
 - OS: OSX
 - OS version: 13.4.1
 - react-native version: "react-native": "0.70.9",
 - react-native-webview version: "react-native-webview": "^12.0.2"

**Comment by TheAlmightyBob** [comment]
This does not seem related to `react-native-webview`.

I don't know what this sentence means:

> belongs to the bug of the bottom of webview and cannot be solved

But I don't think it was intended to suggest that this was a `react-native-webview` problem.
