### ISSUE TITLE
react-native-webview not loading pdf js in a separate window

### ISSUE THREAD

**Issue by Manikandan707** [react-native-webview/react-native-webview#3038]
I am facing an issue with react-native-webview and I'm wondering if you have any comments or thoughts on how to fix it.

**Bug description:**

When opening the same URL in a desktop browser, the webpage opens a PDF in a separate window. However, when integrating the same URL into react-native-webview, the result is a blank screen.

The react-native-webview library is not opening a new window from that website. It is showing a blank screen.

**Questions:**

1) Is it possible to render webpages that open in a new window in react native web view?
2) Is it feasible to achieve this?

**Environment:**
 - OS: iOS/Android
 - OS version: iOS 16.x / Android 13
 - react-native version: 0.64.x
 - react-native-webview version: 7.x

**Comment by TheAlmightyBob** [comment]
Is this for iOS, Android, both? Note that Android WebViews do not have PDF support.

**Comment by TheAlmightyBob** [comment]
Re: opening things in new windows, no that is not a built-in feature. However, https://github.com/react-native-webview/react-native-webview/pull/2640 would at least add an event that would tell your app that a new window is desired, and so you could do it yourself from there.

(you _may_ already be able to do it yourself depending on whether the request is going through the `shouldStartLoad` event, but that wouldn't tell you if a new window was requested, you'd have to know based on URL or something)

(also, if the web page is using `window.open`, you could theoretically use javascript injection to override that to send a custom message to your app... it may seem a little hacky, but I can say from experience that it does work)

**Comment by Manikandan707** [comment]
> Is this for iOS, Android, both? Note that Android WebViews do not have PDF support.

Yes. Its happening in both iOS and Android.
