### ISSUE TITLE
 ERROR  TypeError: undefined is not a function, js engine: hermes (RNCWebViewModule.shouldStartLoadWithLockIdentifier undefined)

### ISSUE THREAD

**Issue by ile** [react-native-webview/react-native-webview#3039]
**Bug description:**

I created an app with create-expo-app, with this in App.tsx:

```typescript
import { WebView } from 'react-native-webview';

export default function App() {
  return (
    <WebView source={{ uri: 'https://mydomain.com/login' }} style={{ flex: 1 }} />
  );
}

```

When I log in to my app with Android, I get this error:

![image](https://github.com/react-native-webview/react-native-webview/assets/433707/97e6b030-4ca1-4567-aef3-51a1703bce0c)

![image](https://github.com/react-native-webview/react-native-webview/assets/433707/7ff4f415-36a1-4747-a799-d9f5b11f864b)

This part of the code is in https://github.com/react-native-webview/react-native-webview/blob/master/src/WebView.android.tsx#L72: 

```typescript
  const onShouldStartLoadWithRequestCallback = useCallback((shouldStart: boolean,
    url: string,
    lockIdentifier?: number) => {
    if (lockIdentifier) {
      RNCWebViewModule.shouldStartLoadWithLockIdentifier(shouldStart, lockIdentifier);
    } else if (shouldStart && webViewRef.current) {
      Commands.loadUrl(webViewRef.current, url);
    }
  }, []);
```

This same error seems to be here: https://github.com/facebook/react-native/issues/37116

**Environment:**
 - OS: Ubuntu 
 - OS version: 22.04.2
 - react-native version: react-native@0.71.8
 - react-native-webview version: react-native-webview@13.2.2

**Comment by ile** [comment]
The commit for this part of the code seems to be this https://github.com/react-native-webview/react-native-webview/commit/5558e28feab2e8bd881450f155e642cf1e66caad by @Titozzz

**Comment by TheAlmightyBob** [comment]
The title calls out "js engine: hermes". Does it work if you disable hermes?

**Comment by ile** [comment]
> The title calls out "js engine: hermes". Does it work if you disable hermes?

I added this to app.json in Expo app:

```json
{
  "expo": {
    "jsEngine": "jsc",
  }
}
```

And it really did seem to help, no error anymore.

**Comment by ile** [comment]
> The title calls out "js engine: hermes". Does it work if you disable hermes?

I added this to app.json in Expo app:

```json
{
  "expo": {
    "jsEngine": "jsc",
  }
}
```

But no help, still the same error.

**Comment by shmaltz** [comment]
Same error here.

**Comment by TheAlmightyBob** [comment]
What version of Expo are you using? Have you tried previous versions of `react-native-webview`?

I noticed that Expo Snack version 48 seems unhappy with versions 12 and up of `react-native-webview`... not certain if that's related though.

**Comment by upcodes1** [comment]
Any solution for this one? I'm stuck with it, upgraded to expo 49 and started getting this.

**Comment by moosthuizen42** [comment]
> What version of Expo are you using? Have you tried previous versions of `react-native-webview`?
> 
> I noticed that Expo Snack version 48 seems unhappy with versions 12 and up of `react-native-webview`... not certain if that's related though.

I encountered a similar issue (same error, different stack trace) using react-native@0.71.8 and expo@48.0.16.

Changing `react-native-webview@13.2.2` -> `react-native-webview@11.26.1` solved my issue.

**Comment by ShineKidd** [comment]
1. check your version
 ```
 "react-native-webview": "13.12.3",
```
    
   2. disable newArchEnabled
```
     [
        "expo-build-properties",
        {
          "ios": {
            "newArchEnabled": false
          },
        }
      ],
```

**Comment by hwangyunjeong1** [comment]
```
     [
        "expo-build-properties",
        {
          "ios": {
            "newArchEnabled": false
          },
        }
      ],
```
@ShineKidd Which file should I add this to?

**Comment by ShineKidd** [comment]
app.json

Using Expo build RN App. 

Expo SDK51

**Comment by Krucial92** [comment]
Can we get this working with newArchEnabled & without downgrading the RNW dependency?
