### ISSUE TITLE
Downloaded local image won't display in webview

### ISSUE THREAD

**Issue by robertgonzales** [react-native-webview/react-native-webview#3040]
**Background**:
I have an app that allows users to download media and then they can come back later and view this media even while offline. To do this, the app downloads the media assets using Expo's FileSystem API and then uses React Native WebView to render html with all media urls pointing at the local downloaded assets. 

Previously I was using the WebView exported from React Native itself but I recently updated the app to use this React Native WebView package. I have been unable to get this functionality to work, despite examples and props that suggest this should be possible.

**Bug description:**
Downloaded image asset does not display in WebView. I've triple checked that the local image path itself is valid and I believe the WebView itself is preventing local assets from loading. I am hoping I have just missed some configuration of props, but I have tried everything in the documentation without success so I believe this is a bug.

**To Reproduce:**
At its core, here's what I'm trying to do:
```js
const html = `
<html>
  <body>
    <img src="file:///.../image.jpg" />
  </body>
</html>
`
<WebView
  style={{ flex: 1 }}
  source={{ html }}
  originWhitelist={["*"]}
  mixedContentMode="always"
  allowingReadAccessToURL="*"
  javaScriptEnabled={true}
  allowFileAccess={true}
  allowFileAccessFromFileURLs={true}
  allowUniversalAccessFromFileURLs={true}
/>
```

I've made a repo with real code here: https://github.com/robertgonzales/webview-downloaded-image
(In addition to React Native WebView, this repo uses Expo and Expo FileSystem to download the image).

**Expected behavior:**
Image with a valid local path should render in the WebView.

**Screenshots/Videos:**
<img width="1511" alt="Screenshot 2023-07-07 at 4 37 05 PM" src="https://github.com/react-native-webview/react-native-webview/assets/7729885/b69f3f30-4c2a-474b-a0a4-d4e1bad5ed1e">
^ Here I'm inspecting the document that's loaded in the WebView. To demonstrate that I have a valid path I've clicked the image url and it opens successfully in Preview. But in the WebView thats running in the iOS Simulator the image is not displaying.

**Environment:**
 - OS: iOS
 - OS version: iOS 16.0
 - react-native version: 0.71.8
 - react-native-webview version: 11.26.0

**Comment by TheAlmightyBob** [comment]
This looks like the same Expo-specific issue as #2838

**Comment by robertgonzales** [comment]
Hmm, that issue is only reproduced when internet connection is offline. In this case I am keeping an internet connection but referencing a locally saved file.

**Comment by robertgonzales** [comment]
Found the issue. It's this line: `allowingReadAccessToURL="*"`

Sort of stumbled into this by commenting out some of the props randomly and it worked.

Removing that prop fixes it. I think I originally copied that prop from a StackOverflow answer. The [documentation](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#allowingreadaccesstourl) isn't super clear what kind of string it expects, but it looks like `"*"` is not a valid value.

**Comment by TheAlmightyBob** [comment]
> that issue is only reproduced when internet connection is offline

Ah, you're right, sorry.

Thanks for sharing the solution!

Apple's documentation has a _little_ more detail on that property: https://developer.apple.com/documentation/webkit/wkwebview/1414973-loadfileurl?language=objc

**Comment by faridbelhiteche** [comment]
Hello, I may have found a way to bypass this offline issue, but I cannot really explain why. 

After struggling for hours, I simply added ```source={{ html, **baseUrl: ""** }}``` to my source prop out of despair, and it worked !

It seems that this baseUrl prop cannot be undefined on iOs, otherwise, you can't browse local assets inside the webview.

_I am currently using (13.8.6)_
