### ISSUE TITLE
12.4.0 New Arch destroyWebView causes app to crash

### ISSUE THREAD

**Issue by billnbell** [react-native-webview/react-native-webview#3043]
**Bug description:**
Using RN 0.72.1 New Arch, I am getting a crash when leaving the webview.... it is calling 

destroyWebView() and crashing.

**To Reproduce:**
Open WebView and close it.

#ifdef RCT_NEW_ARCH_ENABLED
- (void)destroyWebView;
#endif

might be causing it.

**Expected behavior:**
No crash

**Screenshots/Videos:**
N/A

**Environment:**
 - OS: IOS 
 - OS version: 16.0
 - react-native version: 0.72.1
 - react-native-webview version: 12.4.0

**Comment by TheAlmightyBob** [comment]
Please share a sample project/snack that repros the issue. I've just been actively working on testing/fixing iOS New Arch issues and didn't see what you're describing.

**Comment by billnbell** [comment]
When using a modal, I am closing the modal and then the error I see it in WebView destroyWebView.

I think to repo it you need a modal wrapping the webview. I did see others complaining about react-native-reanimated and modals, but I don't get error on that.

```
import CookieManager from '@react-native-cookies/cookies';
import { useFocusEffect } from '@react-navigation/native';
import jwtDecode from 'jwt-decode';
import { useCallback, useMemo, useRef, useState } from 'react';
import { Linking, StyleSheet, TouchableOpacity, useWindowDimensions, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import Icon from 'react-native-vector-icons/MaterialIcons';
import { WebView, WebViewNavigation } from 'react-native-webview';
import { TokenData } from 'types';
import useAsyncEffect from 'use-async-effect';

import { getAuthInfo, setAuthInfo } from '~api/authInfo';
import { getGatewayConfiguration } from '~api/configuration-api';
import { gatewayPostNoBearer } from '~api/gateway-api';
import { genEnv } from '~config/genEnv';
import { log } from '~logging.config';
import { logCustomEvent } from '~utils/common';

import Theme from '../styles/Theme';
import LoadingSpinner from './LoadingSpinner';
import ModalHeaderWebview from './member/modal/ModalHeaderWebview';

const { sourceUrl, cookieDomain } = genEnv();

const componentStyles = (paddingBottom: number) =>
  StyleSheet.create({
    footer: {
      paddingHorizontal: 4,
      paddingBottom,
      flexDirection: 'row',
      justifyContent: 'space-around',
      backgroundColor: Theme.colors.webviewBackground,
    },
  });

const formatURL = (endpoint: string) => {
  let newUrl: string | string[] = endpoint;
  if (endpoint.includes('membercommunity')) {
    const updateUrl = endpoint.split('membercommunity');
    if (updateUrl.length > 0) {
      newUrl = sourceUrl + updateUrl[updateUrl.length - 1];
    }
  }
  return newUrl;
};

const getTokenExp = (token: string) => {
  const decode: { exp: number } = jwtDecode(token);
  return new Date(decode.exp * 1000 + 60 * 60 * 1000).toISOString();
};

type WebviewModalPropsTypes = 'web' | 'thesource' | 'pdf' | 'directsource';

// eslint-disable-next-line @typescript-eslint/consistent-type-definitions
interface WebviewModalProps {
  route: {
    params: {
      endpoint: string;
      type: WebviewModalPropsTypes;
      customEvent?: string;
      title?: string;
    };
  };
}

const fetchConfig = async () => {
  const res = await getGatewayConfiguration();
  return res && res.data ? res.data.communityCookie : null;
};

const setCookieManager = async (itoken: string, url: string) => {
  try {
    if (url.startsWith('https://community')) {
      const communityCookie = await fetchConfig();
      if (communityCookie) {
        await CookieManager.clearAll();
        await CookieManager.set(url, {
          name: communityCookie.name,
          value: communityCookie.content,
          domain: '..domain.com',
          path: '/',
          secure: true,
          expires: getTokenExp(itoken),
        });
      }
    } else {
      await CookieManager.clearAll();
      const config = {
        name: 'newCookie',
        value: itoken,
        domain: cookieDomain,
        path: '/',
        secure: true,
        expires: getTokenExp(itoken),
      };
      log.info(config, url);
      await CookieManager.set(url, config);
    }
  } catch (e) {
    log.error('setCookieManager', e);
  }
};

function isValidHttpUrl(value: string) {
  let url;

  try {
    url = new URL(value);
  } catch (_) {
    return false;
  }

  return url.protocol === 'http:' || url.protocol === 'https:';
}

const WebviewModal = (props: WebviewModalProps): JSX.Element => {
  const { route } = props;
  const { type, endpoint, customEvent, title } = route.params;
  const skipTitle = !!(type === 'directsource');
  const iType = type === 'thesource' || type === 'directsource' ? 'source' : type;
  const iCustomEvent = customEvent;
  const [hasToken, setHasToken] = useState<boolean>(false);
  const [isLoading, setLoading] = useState<boolean>(false);
  const webViewRef = useRef<WebView>(null);
  const [canGoBack, setCanGoBack] = useState<boolean>(false);
  // const [keyBoardDidShow, setKeyBoardDidShow] = useState<boolean>(false);
  const [canGoForward, setCanGoForward] = useState<boolean>(false);
  let rUrl = formatURL(endpoint || sourceUrl);
  if (!rUrl || rUrl.length === 0) {
    log.error(`rUrl cannot be empty as URL for WebviewModal ${type}`);
    rUrl = sourceUrl;
  }
  if (!isValidHttpUrl(rUrl)) {
    log.error(`rUrl not valid as URL for WebviewModal ${type} ${rUrl}`);
  }
  const [currentUrl, setCurrentUrl] = useState<string>(rUrl);

  const { width } = useWindowDimensions();
  const { bottom } = useSafeAreaInsets();
  const bottomIndent = skipTitle ? 0 : bottom;
  const styles = componentStyles(bottomIndent);

  const headerTitle = (): string => {
    if (title && title.length > 0) {
      return title;
    }
    return iType === 'source' ? 'The Source' : `${rUrl}`;
  };

  const render = () => {
    let value = false;
    if (hasToken) {
      value = true;
    }
    return value;
  };

  useAsyncEffect(async () => {
    log.debug('Use Effect Run WebviewModal');
    try {
      if (!hasToken) {
        const auth = getAuthInfo();
        if (auth !== null) {
          const response = await gatewayPostNoBearer<TokenData>('/user/token', {
            ...getAuthInfo(),
            grant: 1,
          });
          if (response.status && response.status === 200 && response.data) {
            const newToken = response.data;
            setAuthInfo(newToken);
            await setCookieManager(newToken.token, rUrl);
            setHasToken(true);
          } else {
            log.info('WebviewModal did not setAuthInfo');
          }
        }
      }
    } catch (e) {
      log.error('WebvieModal Unable to retrieve Token', e);
    }
  }, [rUrl, iType, type, hasToken]);

  useFocusEffect(
    useCallback(() => {
      log.debug('useFocusEffect Run');
      if (iCustomEvent) {
        logCustomEvent(iCustomEvent, {
          type: type || '',
          endpoint: endpoint || '',
          customEvent: customEvent || '',
          title: title || '',
          rUrl: rUrl || '',
          currentUrl: currentUrl || '',
          iType: iType || '',
          hasToken,
        });
      }
      // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [iCustomEvent, endpoint])
  );

  const goBack = () => {
    const enableGoBack = webViewRef && canGoBack && webViewRef.current;
    if (enableGoBack) {
      webViewRef.current?.goBack();
    }
  };

  const goForward = () => {
    const enableGoForward = webViewRef && canGoForward && webViewRef.current;
    if (enableGoForward) {
      webViewRef.current?.goForward();
    }
  };

  const reload = () => {
    const enableReload = webViewRef && webViewRef.current;
    if (enableReload) {
      webViewRef.current?.reload();
    }
  };

  const clickOpenBrowser = async () => {
    try {
      const canOpen = await Linking.canOpenURL(currentUrl);
      if (canOpen) {
        await Linking.openURL(currentUrl);
      }
    } catch (err) {
      log.error(`clickOpenBrowser not valid url ${type} ${currentUrl}`);
    }
  };

  const Footer = () =>
    useMemo(
      () => (
        <View style={styles.footer}>
          <TouchableOpacity onPress={goBack} disabled={!canGoBack}>
            <Icon
              name="chevron-left"
              style={{
                color: Theme.colors.dimGrey,
                fontSize: 40,
              }}
            />
          </TouchableOpacity>
          <TouchableOpacity onPress={goForward} disabled={!canGoForward}>
            <Icon
              name="chevron-right"
              style={{
                color: Theme.colors.dimGrey,
                fontSize: 40,
              }}
            />
          </TouchableOpacity>
          <LoadingSpinner visible={isLoading} centered={false} />
          <TouchableOpacity onPress={reload}>
            <Icon
              name="refresh"
              style={{
                color: Theme.colors.dimGrey,
                fontSize: 40,
              }}
            />
          </TouchableOpacity>
          <TouchableOpacity onPress={clickOpenBrowser}>
            <Icon
              name="open-in-browser"
              style={{
                color: Theme.colors.dimGrey,
                fontSize: 40,
              }}
            />
          </TouchableOpacity>
        </View>
      ),
      // eslint-disable-next-line react-hooks/exhaustive-deps
      [isLoading, currentUrl, canGoBack, canGoForward]
    );

  const handleWebViewNavigationStateChange = (newNavState: WebViewNavigation) => {
    setCanGoBack(newNavState.canGoBack);
    setCanGoForward(newNavState.canGoForward);
    setCurrentUrl(newNavState.url || 'https://thesource.exclusiveresorts.com');
  };

  // do not move the activity indicator out of the box - since it will mess up popups
  return (
    <View
      style={{
        flex: 1,
        marginTop: 0,
        justifyContent: 'space-between',
      }}
    >
      {!skipTitle && <ModalHeaderWebview type={iType} title={headerTitle()} />}
      {render() ? (
        <View style={{ flex: 1 }}>
          <WebView
            nestedScrollEnabled
            source={{ uri: rUrl || 'https://exclusiveresorts.com/' }}
            key={`${rUrl}${new Date().getHours()}`}
            javaScriptEnabled
            onMessage={() => {}}
            sharedCookiesEnabled
            pullToRefreshEnabled
            allowsInlineMediaPlayback
            thirdPartyCookiesEnabled
            ref={webViewRef}
            style={{
              flex: 1,
              width,
            }}
            mixedContentMode="compatibility"
            onNavigationStateChange={handleWebViewNavigationStateChange}
            onLoadStart={() => {
              setLoading(true);
            }}
            onLoadEnd={() => {
              setLoading(false);
            }}
          />
        </View>
      ) : null}
      <Footer />
    </View>
  );
};

export default WebviewModal;
```

**Comment by billnbell** [comment]
OK If I remove the destroyWebView I don't have the issue anymore!!

```
// Reproduce the idea from here: https://github.com/facebook/react-native/blob/8bd3edec88148d0ab1f225d2119435681fbbba33/React/Fabric/Mounting/ComponentViews/InputAccessory/RCTInputAccessoryComponentView.mm#L142
- (void)prepareForRecycle {
    [super prepareForRecycle];
    // [_view destroyWebView];
}
```

**Comment by billnbell** [comment]
OK this works better and cleans up memory:

```
// Reproduce the idea from here: https://github.com/facebook/react-native/blob/8bd3edec88148d0ab1f225d2119435681fbbba33/React/Fabric/Mounting/ComponentViews/InputAccessory/RCTInputAccessoryComponentView.mm#L142
- (void)prepareForRecycle {
    [super prepareForRecycle];
    [_view removeFromSuperview];
}
```

I am unsure why we have `[_view destroyWebView];` when it does not work. I am using use_frameworks!, and new Arch. I am pretty sure everyone will have the same issue.

**Comment by billnbell** [comment]
Actually putting in `[_view removeFromSuperview];` makes the next time I call it not work. So it is better to not put it in.

**Comment by billnbell** [comment]
OK see my patch: https://github.com/react-native-webview/react-native-webview/issues/3044

**Comment by billnbell** [comment]
PR: https://github.com/react-native-webview/react-native-webview/pull/3045

**Comment by TheAlmightyBob** [comment]
Still looking for a repro. That code snippet is not sufficient.

It's likely that some cleanup is still necessary in `prepareForRecyle` and more investigation would be required to determine exactly which part of `destroyWebView` is problematic.

**Comment by billnbell** [comment]
It literally cannot find the property ! When I moved it to `[_view removeFromSuperview];` it find the function, but clears too much and the next call to WebView does not load.

**Comment by abdallahrida** [comment]
++

**Comment by abdallahrida** [comment]
> OK If I remove the destroyWebView I don't have the issue anymore!!
> 
> ```
> // Reproduce the idea from here: https://github.com/facebook/react-native/blob/8bd3edec88148d0ab1f225d2119435681fbbba33/React/Fabric/Mounting/ComponentViews/InputAccessory/RCTInputAccessoryComponentView.mm#L142
> - (void)prepareForRecycle {
>     [super prepareForRecycle];
>     // [_view destroyWebView];
> }
> ```

from where ?

**Comment by abdallahrida** [comment]
same issue is happening with me

**Comment by billnbell** [comment]
> > OK If I remove the destroyWebView I don't have the issue anymore!!
> > ```
> > // Reproduce the idea from here: https://github.com/facebook/react-native/blob/8bd3edec88148d0ab1f225d2119435681fbbba33/React/Fabric/Mounting/ComponentViews/InputAccessory/RCTInputAccessoryComponentView.mm#L142
> > - (void)prepareForRecycle {
> >     [super prepareForRecycle];
> >     // [_view destroyWebView];
> > }
> > ```
> 
> from where ?

See my PR/FORK or Patch.

node_modules/react-native-webview/apple/RNCWebView.mm

**Comment by TheAlmightyBob** [comment]
> It literally cannot find the method !

Curious. Perhaps a debugger would reveal if `_view` is not what's expected (i.e. is it not actually pointing to an instance of `RNCWebViewImpl`?)...? Does having it call `removeFromSuperview` actually invoke the relevant function in `RNCWebViewImpl` (which the `#ifdef` _should_ have turned into `destroyWebView`)?

**Comment by billnbell** [comment]
Yep calling removeFromSuperview in the Xcode debugger gets to the function properly. But calling destroyWebView just fails.

You would think that removeFromSuperview would work. But on my next call to WebView it has some bad properties from the removeFromSuperview and it does not actual help calling this. Not sure what part of the code is messing with it though.

**Comment by billnbell** [comment]
Also the #ifdef RCT_NEW_ARCH_ENABLED is still defined, just set to 0.

Shouldn't it just be `#if RCT_NEW_ARCH_ENABLED` like we have in other places?

**Comment by billnbell** [comment]
Yeah 
```
-#ifdef RCT_NEW_ARCH_ENABLED
+#if RCT_NEW_ARCH_ENABLED
```

and
```
-#ifndef RCT_NEW_ARCH_ENABLED
+#if !RCT_NEW_ARCH_ENABLED
```

**Comment by billnbell** [comment]
The error I get when adding destroyWebView:
```
Thread 1: "-[RNCWebViewImpl destroyWebView]: unrecognized selector sent to instance 0x7fbf7991be00"
```

**Comment by billnbell** [comment]
I also have a screen shot, still cannot call destroyWebView.

![image](https://github.com/react-native-webview/react-native-webview/assets/25377089/528ec180-0bee-4439-9964-e7d3b03780ba)

**Comment by billnbell** [comment]
I also check to see if both are there at that breakpoint:

![image](https://github.com/react-native-webview/react-native-webview/assets/25377089/87081e66-f31b-4597-a033-a8519500838e)

**Comment by TheAlmightyBob** [comment]
> Shouldn't it just be #if RCT_NEW_ARCH_ENABLED like we have in other places?

What other places? I don't see any instances of that.

_However..._

> the #ifdef RCT_NEW_ARCH_ENABLED is still defined, just set to 0

Perhaps that is indeed related! It's 1 or undefined for me. If you're setting it to 0, it sounds like your intent is _not_ to use the new architecture, but the problem is that you're still getting new architecture code? I'm actually surprised it even compiled in that case...

> why do we need to call it destroyWebView?

How is the name relevant? I didn't do the new arch refactor, but I suspect the intent of renaming was to _stop_ the cleanup from happening as part of `removeFromSuperview`.

In your screenshot of the `_view` in the debugger, you have the `RCTView` expanded... if you collapse that, do the fields look like a valid `RNCWebViewImpl` instance?

**Comment by billnbell** [comment]
Can you change the #ifdef to #if since many people are using RCT_NEW_ARCH_ENABLED=0 and RCT_NEW_ARCH_ENABLED=1 ?

Then I can retest.

**Comment by billnbell** [comment]
I agree that we can just comment use 

```
// Reproduce the idea from here: https://github.com/facebook/react-native/blob/8bd3edec88148d0ab1f225d2119435681fbbba33/React/Fabric/Mounting/ComponentViews/InputAccessory/RCTInputAccessoryComponentView.mm#L142
- (void)prepareForRecycle {
    [super prepareForRecycle];
}
```

And everything works well with USE_FRAMEWORKS.

```
cd ios && NO_FLIPPER=1 USE_FRAMEWORKS=static RCT_NEW_ARCH_ENABLED=1 pod install --repo-update && cd ..
yarn ios
```

**Comment by billnbell** [comment]
Maybe we just go with this interim and later look for long term solution ?

**Comment by TheAlmightyBob** [comment]
> many people are using RCT_NEW_ARCH_ENABLED=0

Do you know why? Is that recommended somewhere?

I see React Native's own code also using `#ifdef RCT_NEW_ARCH_ENABLED`, so it seems like setting it to 0 wasn't intended to be a supported scenario...

**Comment by billnbell** [comment]
Good point, I was looking at a few other packages and they do it that way. `#if and #if !` but I will remove the definition in my pod setup.

**Comment by billnbell** [comment]
> > Shouldn't it just be #if RCT_NEW_ARCH_ENABLED like we have in other places?
> 
> What other places? I don't see any instances of that.
> 
> _However..._
> 
> > the #ifdef RCT_NEW_ARCH_ENABLED is still defined, just set to 0
> 
> Perhaps that is indeed related! It's 1 or undefined for me. If you're setting it to 0, it sounds like your intent is _not_ to use the new architecture, but the problem is that you're still getting new architecture code? I'm actually surprised it even compiled in that case...
> 
> > why do we need to call it destroyWebView?
> 
> How is the name relevant? I didn't do the new arch refactor, but I suspect the intent of renaming was to _stop_ the cleanup from happening as part of `removeFromSuperview`.
> 
> In your screenshot of the `_view` in the debugger, you have the `RCTView` expanded... if you collapse that, do the fields look like a valid `RNCWebViewImpl` instance?

Yep! Looks valid to me, but still does not find `[_view destroyWebView];` I am trying to see why.
