### ISSUE TITLE
onLoadEnd not called for AJAX (react-router-dom) page navigation

### ISSUE THREAD

**Issue by jpodpro** [react-native-webview/react-native-webview#3053]
**Bug description:**
Our app uses `react-router-dom` to do most of our nagivation. After upgrading webview from 11.0.0 to 13.2.2 the `onLoadEnd` handler is not called for a router route change. As such our loading indicator is stuck spinning even when the page is loaded.

**To Reproduce:**
Create an app with a button to do a simple react-router-dom page nav. Note that `onLoadStart` works but `onLoadEnd` does not.

**Environment:**
 - OS: Android 13, Pixel 7
 - react-native version: 0.72.3
 - react-native-webview version: 13.2.2

**Comment by TheAlmightyBob** [comment]
That's a big version jump. If you're seeing a change in behavior, it would help if you could try versions in-between to narrow down when that change might have occurred.

**Comment by jpodpro** [comment]
ok i did some version checking and have more information:

starting in version 12.1.0 `onLoadStart` is called for AJAX/SPA-type route changes. prior to that version (12.0.3 and lower) neither `onLoadStart` or `onLoadEnd` were fired for these events, 

i tried my best to inspect the full synthetic event object passed to these handlers to see if i could differentiate between page requests and route change requests but nothing stood out.

**Comment by jpodpro** [comment]
if the loading state is the only relevant information required, i've discovered a workaround using the `onNavigationStateChange` handler. the passed object contains a `loading` property that is correct for both full page and AJAX loads.

**Comment by jpodpro** [comment]
IOS:

the `onNavigationStateChange` behavior is different on ios (thanks guys). instead of `onLoadStart`, only `onLoadEnd` is called for XHR requests. in addition, the `loading` property for `onNavigationStateChange` does not behave the same way and is basically never true. 

i would have hoped after years of dev this package would mature to consistent stability. guess not.

**Comment by jpodpro** [comment]
pretty frustrating after answering the question and providing even more detail i get ... 🦗 🦗 🦗 

this issue is not resolved and this project can barely be called active. i would caution anyone else to reconsider using this package as i have seen very little engagement over the years.

**Comment by TheAlmightyBob** [comment]
> pretty frustrating after answering the question and providing even more detail i get

Sorry, the additional info you provided told me that this issue was more complicated than it initially sounded and not a simple regression. I'm not familiar with this type of navigation myself (and I've never even used `onNavigationStateChange`). I had hoped that somebody else might still see it and have an idea, but seems not.

Note that this project is community-maintained... it depends on folks such as yourself to figure out issues and submit PRs.

I'll reopen this for now, but that won't prevent the bot from coming along again later.
