### ISSUE TITLE
How to properly scale the content inside a webview

### ISSUE THREAD

**Issue by Irfanwani** [react-native-webview/react-native-webview#3054]
Is there any short way to scale the content inside a webview. I tried using the scale property in webview style but that doesn't work. Though i can use css in the inline html, but that is a lot of work as the html is coming from my backend as i will have to parse it, add css (check manually where the tags start, where to put the styles etc etc).

**Comment by manosKas** [comment]
Have you tried injecting this:

`<head>
...
    <meta name="viewport" content="width=device-width, initial-scale=1" />
...
</head>`

**Comment by manosKas** [comment]
check out [vw and vh](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units#numbers_lengths_and_percentages) units that are relative to various device sizes
