### ISSUE TITLE
Itms-90809: deprecated API usage appears again in IOS upload build

### ISSUE THREAD

**Issue by junaid-junnu** [react-native-webview/react-native-webview#3057]
**Apple Store connect**:

ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability.

react-native-webview team giving all related solutions. I'm trying but not working.
kindly give me a proper solution for this issue I am stocking for a few days.

Thanks

**Comment by jimsideout** [comment]
Same issue.

**Comment by TheAlmightyBob** [comment]
You're using the latest version of `react-native-webview`? This library hasn't used `UIWebView` in years.

**Comment by junaid-junnu** [comment]
@TheAlmightyBob > You're using the latest version of `react-native-webview`? This library hasn't used `UIWebView` in years.
yes, now facing an issue after the build creates a `UIWebView` issue.
I'm using this version:
"react": "^18.2.0",
"react-native": "0.64.4",
"react-native-webview": "11.17.2",

**Comment by TheAlmightyBob** [comment]
I recommend searching your codebase (including all 3rd-party iOS pods) for `UIWebView`. It's quite possible/likely that the issue is unrelated to `react-native-webview`.

**Comment by junaid-junnu** [comment]
@TheAlmightyBob Yes,  you are right that the issue is unrelated to react-native-webview.
I've resolved this issue.
There was a problem with the package version "wrap react-native-webview".
