### ISSUE TITLE
Webview can not download image file

### ISSUE THREAD

**Issue by rajibulanam** [react-native-webview/react-native-webview#3064]
**Bug description:**
Hi, 
I am using html file to create image and download.
These are my HTML Image creation java script.

```
      var link = document.createElement("a");
      link.download = "image.png";
    
      canvas.toBlob(function(blob){
        link.href = URL.createObjectURL(blob);
        console.log(blob);
        console.log(link.href);
        link.click();
      },'image/png');
```
The site link is [https://test.bdanam.com/index3.html?data=0](https://test.bdanam.com/index3.html?data=0)
When I use mobile browser I can download the image but when I use the webview, I can not download the image.
From the site I take a picture and download to the mobile.

This is my React Native Webview Code.
```
<WebView
        source={{ uri: 'https://test.bdanam.com/index3.html?data=0' }}
        originWhitelist={['*']}
        mixedContentMode={'always'}
        scalesPageToFit={true}
        allowsInlineMediaPlayback={true}
        allowsFullscreenVideo={true}
        allowFileAccess={true}
        domStorageEnabled={true}
        startInLoadingState={true}
        allowUniversalAccessFromFileURLs={true}
        javaScriptEnabled={true}
        mediaPlaybackRequiresUserAction={false}
        {...platformProps}
        style={{ flex: 1 }}
      />
```

I can not download the image from React Native.
I follow this method. [https://github.com/react-native-webview/react-native-webview/blob/master/example/examples/Downloads.tsx](https://github.com/react-native-webview/react-native-webview/blob/master/example/examples/Downloads.tsx)

**To Reproduce:**
Open the Webview from the site and take picture, no image start download. [https://test.bdanam.com/index3.html?data=0](https://test.bdanam.com/index3.html?data=0)
But from mobile browser can download.
![Screenshot_1690199577](https://github.com/react-native-webview/react-native-webview/assets/114012898/8b2d6cd8-4864-4a75-a1cd-46784de6e891)

**Environment:**
 - OS: Android
 - OS version: Emulator API 34
 - react-native version: 0.71.11
 - react-native-webview version: 13.2.2

**Comment by TheAlmightyBob** [comment]
You put "Windows" as the OS, but assuming that you mean Android, it sounds like you're running into the lack of support for blob downloads.

You could look at https://github.com/react-native-webview/react-native-webview/pull/3022

**Comment by rajibulanam** [comment]
Hi, 
According to your advice, I have implemented the blobDownloadingEnabled.
Below is my ReactNative code.
```
      <View style={{ height: 520 }}>
        <WebView

          source={{ uri: 'https://test.bdanam.com/index3.html?data=0' }}
          startInLoadingState={true}
          javaScriptEnabled
          blobDownloadingEnabled
          allowFileAccess
          domStorageEnabled
          mixedContentMode='always'
          allowUniversalAccessFromFileURLs
          originWhitelist={['https:*', 'blob:*']}
          {...platformProps}
        />
      </View>
```
It is not working. Please guide me. I have updated the OS information.

**Comment by TheAlmightyBob** [comment]
I did not work on that PR and cannot guide you.

**Comment by rajibulanam** [comment]
Any one who is expert please guide me.

**Comment by TheAlmightyBob** [comment]
Since that change hasn't been merged into the library yet, the only expert would be the author of the PR.

**Comment by rajibulanam** [comment]
thanks

**Comment by gauravrana0-nagarro** [comment]
try this [https://github.com/react-native-webview/react-native-webview/issues/3445#issuecomment-2349318406](url)

**Comment by MohammedThansheef** [comment]
still issue exists

**Comment by gomdolkim** [comment]
the issue still exists
