### ISSUE TITLE
onOpenWindow event not working as expected

### ISSUE THREAD

**Issue by jayon-niravel** [react-native-webview/react-native-webview#3065]
I tested with the latest release but could not open the window inside webview (using android). Can you suggest what I am doing wrong here?

 
```
return <WebView
source={{
 uri: `some_randome_url`
}}
            javaScriptCanOpenWindowsAutomatically={true}
            originWhitelist={['*']}
            onOpenWindow={(syntheticEvent) => {
            const { nativeEvent } = syntheticEvent;
            const { targetUrl } = nativeEvent
            console.log('Intercepted OpenWindow for', targetUrl)
            }}
        />;
```
        
        
        The URL "some_randome_url" have below line in the html
        `<a href="https://www.google.com" target="_blank">testing link</a>`
        
        
        Clicking on above link, opens it on external browser and not inside the webview window.
        
        

//version
"react-native-webview": "13.3.0"
"react": "18.2.0",
 "react-native": "0.71.3",

**Comment by o-alexandrov** [comment]
Btw, `javaScriptCanOpenWindowsAutomatically` is optional, `onOpenWindow` works with and without it.
I tested your setup w/ `react-native@0.72.3`; `window.open` and an anchor tag with `href` property in HTML both invoke `onOpenWindow` in ReactNative.

Can you try bumping `react-native` version to latest?

**Comment by jayon-niravel** [comment]
[AwesomeProject.zip](https://github.com/react-native-webview/react-native-webview/files/12149011/AwesomeProject.zip)
unzip this folder and do an npm install
its an expo project, you can do 'npx expo start' to run
Let me know if this works for you. I dont have a working URL handy, so using the w3c for quick test

**Comment by jayon-niravel** [comment]
I am looking to open the URL inside the webview window itself and not in external browser.

**Comment by jayon-niravel** [comment]
@o-alexandrov :

add onClick w/ window.open in the web process and log whether anchor tag is really clicked?=> **yes I have tried with both anchor tag and window.open()** 
bump react-native version to 0.72.3?=> **Upgraded version but still same results**
test whether the issue happens for both Android and iOS? In the description, you mentioned you tested for Android only.=> **Same issue for android & IOS**

**Comment by o-alexandrov** [comment]
@jayon-niravel thank you, for the reproducible example, please consider to:
1. create a repo, instead of sharing a zip file
2. the example should be minimal, as it'd most probably help you to identify the issue (since it works on my end)

For the example, please consider to:
1. either run: `npx create-react-native-app` or `npx react-native init Example`
2. push this initial state (from step 1) of the repo to GitHub
3. add `react-native-webview` & an example with `onOpenWindow`
4. either report back here that the repo is working for you, or please push changes from step 3 to GitHub and let me know here also

**Comment by jayon-niravel** [comment]
@o-alexandrov : Have your tried via npx create-expo-app AwesomeProject?
https://reactnative.dev/docs/environment-setup?platform=ios&guide=quickstart

I will upload to github shortly.Thanks!

**Comment by Ldoppea** [comment]
I'm not used to Expo, I tried to reproduce on [Expo Snack](https://docs.expo.dev/) (from the project on [their doc](https://docs.expo.dev/versions/latest/sdk/webview/))

But when I try to ugrade react-native-webview to 13.3.0 I get this error.
![image](https://github.com/react-native-webview/react-native-webview/assets/1884255/ecedbd76-ee89-47b1-b847-af13824c18d3)

The app will still run but it seems to use the older version. Is it possible that you are in the same situation?

Is Expo supposed to be compatible with latest react-native-webview version?

**Comment by o-alexandrov** [comment]
You need expo@49, if you use it with react-native@0.72

**Comment by jayon-niravel** [comment]
@o-alexandrov @Ldoppea 
I have added this repo: https://github.com/jayon-niravel/webview_react_native

Look at the image below, when I click on the "Try it" button, it does not load the window inside the webview at all.
![image](https://github.com/react-native-webview/react-native-webview/assets/21982126/386b14ad-52d5-4dcb-8dae-8ce73f7386ca)

**Comment by TheAlmightyBob** [comment]
@jayon-niravel 

> when I click on the "Try it" button, it does not load the window inside the webview at all

You haven't implemented any code to do so...? All I see is this logging code.

```
            onOpenWindow={(syntheticEvent) => {
            const { nativeEvent } = syntheticEvent;
            const { targetUrl } = nativeEvent
            console.log('Intercepted OpenWindow for', targetUrl)
            }}
```

Your screenshot shows that the log is being written and thus the event is working as expected.

**Comment by jayon-niravel** [comment]
@TheAlmightyBob : How can I open the window inside the webview?
I assumed it will do automatically. Should I use the react linking?

**Comment by jayon-niravel** [comment]
I would need to open the `targetUrl` inside webview window and then close it. Can you suggest how to proceed

**Comment by TheAlmightyBob** [comment]
You can update the `source` property of the WebView.

The purpose of `onOpenWindow` was to give control to intercept the request and implement app-specific custom handling.

**Comment by jayon-niravel** [comment]
Thanks! But I wanted to launch the `targetUrl ` as a popup window and then close it.
Closing the popup window will return back to the parent page (where the `window.open()` was called)

**Comment by TheAlmightyBob** [comment]
> But I wanted to launch the targetUrl  as a popup window and then close it.

I don't understand. Before you said you wanted to

> open the window inside the webview

Those are completely different behaviors.

**Comment by jayon-niravel** [comment]
So you mean there is no way to open the `targetUrl` inside the webview window?

**Comment by jayon-niravel** [comment]
So this is what I am looking for:

1. Source URL (Parent) loaded inside the webview window.
2. User clicks on button to open an external window (window.open("target_url", "_blank")) as a popup.
3. Open the "target_url" in an external window retaining the parent page.
4. Closing the external window will close the popup and then return back to the parent page (retaining the loading state).

So the issue is, if I open the target_url, it always opens up in external mobile browser instead of the webview.
How can I open it inside the webview itself?

**Comment by TheAlmightyBob** [comment]
Opening "inside the webview itself" would mean updating the `source` property. But it sounds like that's not what you want, because you want a popup instead, you just don't want to leave the app. You can implement a popup yourself with another `WebView` instance, or you could use something like https://github.com/proyecto26/react-native-inappbrowser

**Comment by jayon-niravel** [comment]
how can I load `webview` inside of an `webview` ?

**Comment by TheAlmightyBob** [comment]
You cannot. But you can have two WebViews in your mobile app.

**Comment by jayon-niravel** [comment]
Thanks for the response @TheAlmightyBob 
Appreciate your help 💯 !!

**Comment by Vedu1996** [comment]
onOpenWindow is not working as expected for me as well.

I am loading a website which has a relative href with target blank
`<a href="/route-2" target="_blank">Link</a>` 

When I log the syntheticEvent.nativeEvent.targetUrl in the function I pass to `onOpenWindow`,  it is an empty string

**Comment by TheAlmightyBob** [comment]
@Vedu1996 Please open a separate issue and provide a sample that reproduces the problem

**Comment by Rache-lBronfman** [comment]
@TheAlmightyBob When I tried to use multiple web-views I had a problem sharing the token between them, the second web-view opened me without registration, how can I share this data between the windows?

**Comment by TheAlmightyBob** [comment]
@Rache-lBronfman Unfortunately, that's a limitation of this approach. It's as if you opened the new WebView in a separate browser.. the two don't know about each other.

_Theoretically_, I believe https://github.com/react-native-webview/react-native-webview/pull/2469 could be leveraged to support "real" `window.open` support, however that's a massive/complex WIP PR.

In the meantime, I worked around this in my own app by using Javascript injection to implement a custom bridge between the WebViews.

**Comment by chakrihacker** [comment]
Can you share a gist of your implementation please @TheAlmightyBob

**Comment by TheAlmightyBob** [comment]
@chakrihacker Only just saw this so not sure if you're still interested. I can't really share the exact code, not so much because it's secret but more because the details are a little complicated and span a lot of files.

But the basic idea is that, instead of the traditional `window.open` and `postMessage` calls, the web content should invoke `window.ReactNativeWebView.postMessage` to send messages to the app to say "please open this URL in a new WebView" and "please deliver this message to the other WebView."

(I originally did a hacky implementation where the javascript injection actually replaced `window.open` to do this without the web content needing to be updated, but since we own the web content in our case we decided it was better to make changes there and be more explicit about the behavior)

**Comment by Aikenwu** [comment]
@TheAlmightyBob According to your description, can I think that two Webviews are created for my application, and the event communication between the two Webviews is passed through my App Native code, which requires me to build an intermediate layer to bridge the two Webviews. For this purpose, they can only use the window.ReacNativeWebview.PostMessage method.
So in the end, it comes back to the problem itself. It is impossible to use React Native Webview to implement the real window.open method, just like this question https://github.com/react-native-webview/react-native-webview/issues/1868
