### ISSUE TITLE
Android onMessage gets called only when screen is focused

### ISSUE THREAD

**Issue by felipecamposfabel** [react-native-webview/react-native-webview#3067]
**Bug description:**
On Android, if the webview is on a stack screen that is not in focus, all messages sent to the webview are called only when the screen with the webview gets focused again. On iOS, messages are sent even if the webview is not on a focused screen.

**To Reproduce:**
Using react-navigation/native, create a stack with two screens.
- The first screen should have a simple html webview with a script like this:
```
<WebView
   source={{
   html: "<script>document.addEventListener('message', (event) => {window.ReactNativeWebView.postMessage('Received message event');});</script>",
    }}
   ref={webViewRef}
   onMessage={({nativeEvent: {data}}) => console.log(data)}
/>
```
- Add a button to the first screen that navigates to the second screen, and make sure that the second screen has the webview's reference (can be via navigate parameters, react context, redux...).
- On the second screen, add a button that runs the following code:
`webviewRef.current.postMessage('Hello from React Native!');`
- The same behavior happens if you use `injectJavascript` method.
- On android, the message **"Received message event"** is logged only when you go back to the first screen. If you press the button more than once, all the messages are printed, like they were delayed. On iOS, the messages are printed right away.
- If testing on iOS, with `postMessage` method, remember to change `document.addEventListener` to `window.addEventListener` since they behave differently.

**Expected behavior:**
The messages on Android should behave the same way as on iOS. Not sure if this is an Android native thing.

**Environment:**
 - react-native version: tested on  0.71.7 - 0.72.0
 - react-native-webview version: tested on 12.0.2 and 13.2.2

**Comment by TheAlmightyBob** [comment]
I previously encountered this issue and worked around it by disabling `react-native-screens`.

I do not know what a "real" fix would entail, whether there's something this library could do or if it's just a `react-native-screens` issue.

**Comment by felipecamposfabel** [comment]
@TheAlmightyBob Thanks for the insight. It led me to this https://reactnavigation.org/docs/stack-navigator/#detachpreviousscreen when using **non-native** stack navigators, and `detachPreviousScreen` works.

I then tested it on Android and it works with **native** stacks as well if you set `presentation` to `transparentModal` (since there's no `detachPreviousScreen`). It's a good enough workaround for me. But got me thinking that this has to do with visibility somehow.

**Comment by abhi5movva** [comment]
I am still experiencing this issue on iOS. The solution provided below did not work for me.
I then tested it on Android and it works with native stacks as well if you set presentation to transparentModal (since there's no detachPreviousScreen). It's a good enough workaround for me. But got me thinking that this has to do with visibility somehow.
