### ISSUE TITLE
Content is not properly visible on IOS

### ISSUE THREAD

**Issue by Salmankhan033** [react-native-webview/react-native-webview#3069]
The web view is working fine in Android but in ios 12 and so on the web view content is not properly visible, On the ios model Below 12 is working perfectly.
Sometimes it worked fine on all devices but normally it did not work.
I am using :
react-native-webview: 13.3.0,
react: 18.2.0
react-native: 0.72.3,
Here is the web link you can check 
https://myshop.orderlemon.com/login
Not properly visible, also on some times the QR image did not show
<img src="https://github.com/react-native-webview/react-native-webview/assets/58082294/4bc565c8-6ce4-40e0-9444-1f94f3468335" alt="Drawing"  width="150" height="300"/> 
<img src="https://github.com/react-native-webview/react-native-webview/assets/58082294/3570329b-f102-417c-8a01-6fe46f2c6dcd" alt="Drawing"  width="150" height="300"/> 

When properly visible on different devices 
<img src="https://github.com/react-native-webview/react-native-webview/assets/58082294/a8b18ee4-2cbc-4c60-a7ca-95f5f8be2d48" alt="Drawing"  width="150" height="300"/> 

Thanks!

**Comment by pcamarajr** [comment]
You haven't provided too much details about your implementation, but I was facing something similar right now. Are you passing the `onMessage` function to the WebView? If not, try to pass any function on it and test it again.

**Comment by PBeloborodov** [comment]
same problem

**Comment by hvq1919** [comment]
sam problem

**Comment by Salmankhan033** [comment]
Here is the complete code of the WebView.
still same issue, some time it load perfect and some time not.
it only occur with the first page


```
 <WebView
            source={{ uri: initialLink, headers }}
            javaScriptEnabled={true}
            ref={webViewRef}
            mediaPlaybackRequiresUserAction={false}
            //For the Cache
            domStorageEnabled={true}
            //View to show while loading the webpage
            renderLoading={() => <ActivityIndicatorElement />}
            onContentProcessDidTerminate={() => webViewRef.current.reload()}
            //Want to show the view or not
            startInLoadingState={true}
            geolocationEnabled={true}
            scalesPageToFit
            allowsInlineMediaPlayback={true}
            javaScriptEnabledAndroid={true}
            allowFileAccess={true}
            originWhitelist={['*']}
            onError={() => setOnError(true)}
            injectedJavaScript={INJECTED_JAVASCRIPT}
            injectedJavaScriptBeforeContentLoaded={`
    window.onerror = function(message, sourcefile, lineno, colno, error) {
      // alert("Message: " + message + " - Source: " + sourcefile + " Line: " + lineno + ":" + colno);
      return true;
    };
    true;
  `}
            onLoad={sendPlatformSpecsToWebView}
            style={{ alignItems: 'center' }}
            onMessage={event => { }}
            limitsNavigationsToAppBoundDomains={true}
            onShouldStartLoadWithRequest={event => {
              const { url } = event;

              if (url.startsWith('https://api.whatsapp.com/send/')) {
                // Open WhatsApp externally

                Linking.openURL(url);
                return false; // Prevent the WebView from loading the URL
              }

              if (
                url.endsWith('.xlsx') ||
                url.endsWith('.csv') ||
                url.endsWith('.zip')
              ) {
                // Define headers to suggest a download
                const headers = {
                  'Content-Disposition':
                    'attachment; filename="' +
                    url.substring(url.lastIndexOf('/') + 1) +
                    '"',
                  'Content-Type': 'application/octet-stream',
                };

                // Open the URL externally to trigger the download
                Linking.openURL(url, { headers })
                  .then(() => {
                    // Handle success if needed
                  })
                  .catch(error => {
                    // Handle error if needed
                  });

                return false; // Prevent the WebView from loading the URL
              }
              return true; // Load other URLs normally
            }}
            userAgent="Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Mobile/15E148 Safari/604.1"
          />
```

**Comment by Salmankhan033** [comment]
any solution?

**Comment by Salmankhan033** [comment]
@hvq1919  @PBeloborodov  and @pcamarajr  Have you fixed it ?
please assist

**Comment by PBeloborodov** [comment]
@Salmankhan033 
This may be a strange solution, but it worked for me. 
const emptyBackground = useMemo(
    () =>
      Platform.OS === 'ios' ? {uri: imagePath} : {html: emptyHtml, baseUrl: ''},
    [emptyHtml, imagePath],
  );

    <WebView
      ref={r => {
        refWebView.current = r;
      }}
      originWhitelist={['*']}
      source={renderedOnce ? {html: filterHtml, baseUrl: ''} : emptyBackground}
      style={renderedOnce ? styles.webView : {opacity: 0}}
      allowFileAccess={true}
      allowUniversalAccessFromFileURLs={true}
      allowsInlineMediaPlayback={true}
      mediaPlaybackRequiresUserAction={false}
      onLoad={updateSource}
      onMessage={event => {
        setFilterPhoto(event.nativeEvent.data);
      }}
      startInLoadingState={true}
      renderError={errorName => <View style={styles.loaderContainer} />}
      renderLoading={() => <View style={styles.loaderContainer} />}
      javaScriptEnabled={true}
      domStorageEnabled={true}
      allowFileAccessFromFileURLs={true}
      overScrollMode={'never'}
      removeClippedSubviews={true}
      scrollEnabled={false}
      nestedScrollEnabled
    />

**Comment by Salmankhan033** [comment]
> @Salmankhan033 This may be a strange solution, but it worked for me. const emptyBackground = useMemo( () => Platform.OS === 'ios' ? {uri: imagePath} : {html: emptyHtml, baseUrl: ''}, [emptyHtml, imagePath], );
> 
> ```
> <WebView
>   ref={r => {
>     refWebView.current = r;
>   }}
>   originWhitelist={['*']}
>   source={renderedOnce ? {html: filterHtml, baseUrl: ''} : emptyBackground}
>   style={renderedOnce ? styles.webView : {opacity: 0}}
>   allowFileAccess={true}
>   allowUniversalAccessFromFileURLs={true}
>   allowsInlineMediaPlayback={true}
>   mediaPlaybackRequiresUserAction={false}
>   onLoad={updateSource}
>   onMessage={event => {
>     setFilterPhoto(event.nativeEvent.data);
>   }}
>   startInLoadingState={true}
>   renderError={errorName => <View style={styles.loaderContainer} />}
>   renderLoading={() => <View style={styles.loaderContainer} />}
>   javaScriptEnabled={true}
>   domStorageEnabled={true}
>   allowFileAccessFromFileURLs={true}
>   overScrollMode={'never'}
>   removeClippedSubviews={true}
>   scrollEnabled={false}
>   nestedScrollEnabled
> />
> ```

Thanks for your good response :)
Could you send me your complete code/file Then I will compare it with my code 
Thanks :)
