### ISSUE TITLE
New Architecture Support and use_frameworks! not compiling

### ISSUE THREAD

**Issue by simonarcher** [react-native-webview/react-native-webview#3074]
**Bug description:**

I am migrating my app project to use the new architecture and Im noticing that my app does not compile (for iOS, haven't tested Android yet) when Im also using `use_frameworks!`

Im getting the error 
`'react/utils/ContextContainer.h' file not found`
when compiling. (see screenshot)

 Is there any work around for this currently? Or is it just not supported/working? And if thats the case, is a fix for this actively known to be in the works?

Blocking me from using the new architecture and trying to figure out how to move forward. Any help would or advice would be greatly appreciated!

**To Reproduce:**
The easiest way to replicate this behaviour is creating a brand new React Native app with the new architecture flag (using the [guide](https://reactnative.dev/docs/the-new-architecture/use-app-template) ), then in the pod file add
`use_frameworks! :linkage => :static`
then try compile in Xcode.
The issue should be immediately visible.

**Expected behavior:**

**Screenshots/Videos:**

![Screenshot 2023-07-28 at 12 49 29](https://github.com/react-native-webview/react-native-webview/assets/10696147/9a976984-5268-468a-a274-f231408505f6)

**Environment:**
 - OS: `iOS`
 - OS version:
 - react-native version: `0.72.3`
 - react-native-webview version: `13.3.0`

**Comment by billnbell** [comment]
see https://github.com/react-native-webview/react-native-webview/issues/3044
