### ISSUE TITLE
The Android Gradle plugin supports only kotlin-android-extensions Gradle plugin version 1.6.20 and higher.

### ISSUE THREAD

**Issue by xha123** [react-native-webview/react-native-webview#3077]
**Bug description:**
Android Studio build failed

Building the project via Android Studio prompts that the kotlin version does not meet the project requirements.
**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

![e55568f2-7b6a-4e48-a439-1ddc1460e8be](https://github.com/react-native-webview/react-native-webview/assets/25577710/a3339d53-528a-4484-845c-374aa13a4c08)
**Environment:**
 - OS:Android
 - OS version:13
 - react-native version:0.71.8
 - react-native-webview version:13.3.1
 - Android:        
        minSdk 26
        targetSdk 33

**Comment by gbalduzzi** [comment]
How did you solve? I'm having the same issue

**Comment by parthkanani93** [comment]
same issue +1
