### ISSUE TITLE
[ios]IOS storage video is not displayed

### ISSUE THREAD

**Issue by PBeloborodov** [react-native-webview/react-native-webview#3078]
I am shooting video on a video camera then trying to pass to webview url with address to internal storage. 
<WebView
        ref={r => {
          refWebView.current = r;
        }}
        originWhitelist={['*']}
        source={renderedOnce ? {html: videoHtml} : {html: '<div></div>'}}
        allowFileAccess={true}
        allowUniversalAccessFromFileURLs={true}
        onLoad={updateSource}
        onLoadStart={() => {
          setIsLoading(true);
        }}
        onMessage={event => {
          layerLoaded?.({duration: 5});
          setStopVideo(event.nativeEvent.data === 'true');
          setIsLoading(event.nativeEvent.data === 'true');
        }}
        javaScriptEnabled={true}
        allowsFullscreenVideo={true}
        scalesPageToFit={true}
        domStorageEnabled={true}
        allowFileAccessFromFileURLs={true}
        allowingReadAccessToURL="file://"
        overScrollMode={'never'}
        removeClippedSubviews={true}
        scrollEnabled={false}
        nestedScrollEnabled
        mediaCapturePermissionGrantType={'grant'}
      />
The player doesn't start. 
In the markup, I use 
<video muted autoplay width=250 control>
            <source 
            src="${url}" 
            type='video/ogg; codecs="theora, vorbis"' />
            <source
            src="${url}"
              type='video/mp4; codecs="avc1.42E01E, mp4a.40.2"'
            />
            <source 
            src="${url}"
            type='video/webm; codecs="vp8, vorbis"' />
</video>

**Environment:**
 - OS: ios
 - OS version: 16.5
 - react-native version: 0.67.5
 - react-native-webview version: 13.2.2

**Comment by PBeloborodov** [comment]
The file path comes in this form 
file:///private/var/mobile/Containers/Data/Application/2BAEBD6F-0FB8-41E1-AF7B-1597F0FFA95C/tmp/ReactNative/7DC9828D-4AC5-4EC0-AF38-684B4A963118.mp4

**Comment by gaoxiaosong1113** [comment]
I also encountered the same problem

file:///var/mobile/Containers/Data/Application/4A077ECF-5B35-431F-A9F1-4AA5DFF72CC7/Documents/BA6010B9-2D67-4205-80B6-6F72C46EBD0E.jpg

allowFileAccessFromFileURLs={true}
allowUniversalAccessFromFileURLs={true}
// useWebkit
//1. open switch
allowFileAccess={true}
//2. config Path, for example: DocumentDirectoryPath, CachesDirectoryPath，TemporaryDirectoryPath...
allowingReadAccessToURL={RNFS.DocumentDirectoryPath}

也无法使用
