### ISSUE TITLE
android playstore app rejection SSL Error Handler

### ISSUE THREAD

**Issue by Larens94** [react-native-webview/react-native-webview#3079]
**Bug description:**
android playstore app rejection

Hi all, I'm having this problem and can't post because google reports a problem on com.reactnativecommunity.webview.RNCWebViewClient

SSL Error Handler
For more information on how to address WebView SSL Error Handler alerts, please see this Google Help Center article.

com.reactnativecommunity.webview.RNCWebViewClient

Sincerely

**Screenshots/Videos:**
![ssl_error_react-native-web-view](https://github.com/react-native-webview/react-native-webview/assets/32598073/ca60029d-9084-4cf1-b6de-69944bd5ff8d)

**Environment:**
 - react-native version: "react-native": "0.70.6"
 - react-native-webview version: "react-native-webview": "^13.2.2"

Sincerely

**Comment by TheAlmightyBob** [comment]
Can you share the link to the help center article?

**Comment by Larens94** [comment]
> Can you share the link to the help center article?

Hello, here: https://support.google.com/faqs/answer/7071387

Even after the alert, the application was accepted for open tests on the playstore console.

I don't know if it will cause problems for production.

Sincerely

**Comment by parth-koshta** [comment]
Hello,
Any update here?
We've got a deadline to fix this by Nov 8.
I see handler.cancel() is implemented by the library, but not sure why exactly google is raising this alert during review.

**Comment by Larens94** [comment]
Please review the application for this problem. What do we have to do?

**Comment by kabottin0** [comment]
hi everybody, i have the same issue, Please tell me how to fix......

**Comment by Larens94** [comment]
> Hello, Any update here? We've got a deadline to fix this by Nov 8. I see handler.cancel() is implemented by the library, but not sure why exactly google is raising this alert during review.



> Hello, Any update here? We've got a deadline to fix this by Nov 8. I see handler.cancel() is implemented by the library, but not sure why exactly google is raising this alert during review.

the docs is clear and it seems like there is something wrong with the library.
but I saw that the handler.cancel(); there is.

There are also other suggestions:

link: https://support.google.com/faqs/answer/7071387

Additional details
To correct the issue, please update your apps code to invoke SslErrorHandler.proceed() whenever the certificate presented by the server meets your expectations, and invoke SslErrorHandler.cancel() otherwise. Please have the following points in mind while checking the validity of the certificate:
An app may be flagged if it does not contain sufficient checks for certificate validity; for instance, just checking the return value of getPrimaryError is not sufficient to establish the validity of the certificate.

It is not safe to ignore most SSL errors returned by SslError.getPrimaryError. Please note that getPrimaryError returns the most severe error in a set of errors, so if getPrimaryError() != SSL_UNTRUSTED is true, the connection may still contain an SSL_UNTRUSTED error in the set of errors.

If you are using a 3rd party library that's responsible for this, please notify the 3rd party and work with them to address the issue.


Sincerely

**Comment by Larens94** [comment]
> Can you share the link to the help center article?

Hi, I checked to see if there are other libraries in the application that use RNCWebViewClient but the only one I see is react-native-webview.

How can we solve this problem?

Sincerely
