### ISSUE TITLE
Web view slowness

### ISSUE THREAD

**Issue by amolshende-tudip** [react-native-webview/react-native-webview#3080]
When I updated the react-native-webview package from "11.22.7" to the latest one which is 13.3.1. Then the webview become very slow. It is laking so much time to load.
"react-native": "0.67.5",

**Comment by TheAlmightyBob** [comment]
What platform?

Please share a sample that reproduces the issue

**Comment by amolshende-tudip** [comment]
It is happening on Android,
Just install the latest webview package and try to make the UPI payment flow by passing my URL. Then it is keep loading. Take more time to load

**Comment by amitk-shukla** [comment]
@TheAlmightyBob 
Is there any further update here? We are using this and on our side it is slow.

**Comment by TheAlmightyBob** [comment]
@amitk-shukla There is no update because no sample repro was provided.

**Comment by mrzslr** [comment]
The same issue, happening on Android devices, not all but can be reproduced on Samsung S 24.

`react-native-webview: 13.8.6`
`react-native: 0.72.4`
