### ISSUE TITLE
bypass SSL in react-native-webview v12.4.0 

### ISSUE THREAD

**Issue by alvesronald** [react-native-webview/react-native-webview#3084]
Is there any way to bypass SSL in react-native-webview in version 12.4.0 (Android and IOS)?

    "react-native": "0.71.11",
    "react-native-webview": "12.4.0",

**Comment by Nithinmon-D** [comment]
> 

any solutions

**Comment by Chromacry** [comment]
any solutions?

**Comment by b3itgustaf** [comment]
+1

"react-native": "^0.71.6",
"react-native-webview": "^13.6.0",

**Comment by b3itgustaf** [comment]
So, there is a static `setCustomCertificatesForHost` in the native code for IOS. 
But its not exposed through the `.tsx` files. Is this some WIP for assigning our own self-signed certificates?

![image](https://github.com/react-native-webview/react-native-webview/assets/38074304/2ed54608-70a5-4dfb-85d5-ccd49843c994)

**Comment by Daidalos117** [comment]
Anyone find solution?
