### ISSUE TITLE
display address bar in the WebView Component. 

### ISSUE THREAD

**Issue by jhusdero** [react-native-webview/react-native-webview#3086]
**Bug description:**

I would like to show the address bar in the WebView component, reason is our application needs to call a payment gateway and the 3rd party has requested us to show the address the bar (which in turn shows the `lock` icon where by users can view the certificate details). From their explanation this is to protect the user from fraud cases.

Looking through the docs or issues here, it looks like the address bar is completely not shown? Am I wrong? Could I be missing something?

**To Reproduce:**

Calling the WebView component with any url as the source, will not display the address bar

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS:Mac
 - OS version: 13.2.1
 - react-native version: "0.64.2"
 - react-native-webview version: "^11.26.1"

**Comment by TheAlmightyBob** [comment]
WebViews do not have address bars. You can implement your own, or use something like https://github.com/proyecto26/react-native-inappbrowser instead.

**Comment by TheAlmightyBob** [comment]
(I labeled this "feature request" just because displaying an address bar would be a "new feature," however it's unlikely that this library would ever include an address bar)

**Comment by jhusdero** [comment]
Thanks for the information @TheAlmightyBob . I will give https://github.com/proyecto26/react-native-inappbrowser a go

**Comment by NoahSimajji** [comment]
Any updates on this? @jhusdero 
I tried use react-native-inappbrowser but cant find this feature too

**Comment by TheAlmightyBob** [comment]
> I tried use react-native-inappbrowser but cant find this feature too

If you're looking for a traditional browser editable address bar, then I don't think you'll find that. But @jhusdero was specifically asking about the **lock icon**, which _should_ display when using `react-native-inappbrowser`.
