### ISSUE TITLE
After upgrading Android SDK to version 33

### ISSUE THREAD

**Issue by dingsq820** [react-native-webview/react-native-webview#3087]
After upgrading Android SDK to version 33, the methods 【view.getSettings().setAppCachePath(ctx.getCacheDir().getAbsolutePath());】 and 【view.getSettings().setAppCacheEnabled(true)】 in android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java cannot be used anymore, resulting in an error stating that the methods do not exist.

**Comment by TheAlmightyBob** [comment]
Please upgrade. This library removed those APIs over a year ago: https://github.com/react-native-webview/react-native-webview/pull/2583
