### ISSUE TITLE
Destroy the webview instance completely and return a new one?

### ISSUE THREAD

**Issue by amanzrx4** [react-native-webview/react-native-webview#3088]
We're having issues with webview cookies & sessions for a while, react-native-cookies is not consistent with clearing sessions. What we want is to completely destroy the previous webview user session and return a new one on navigating to `X` screen. Is there any way to achieve that?

**Comment by riddhi-24** [comment]
Hey @amanzrx4,

We're also encountering a similar issue. What we want is whenever the web view loads it should create a fresh new session every time. Have you found any fix or workaround for this? Your insights would be really helpful for us.

**Comment by lapwil** [comment]
Hi any answers to this ? I'm currently encountering the same issue and can't find a way around it 😕
