### ISSUE TITLE
Is it possible to disable the right swipe operation when the gesture is turned on

### ISSUE THREAD

**Issue by baixjian** [react-native-webview/react-native-webview#3091]
On an Apple device, when I add the allowsBackForwardNavigationGestures property, I can turn on gestures, slide right to return to the previous page, and slide left to enter the next page. Is there any way to monitor the direction of the gesture or the API can disable the left slide operation? Thank you very much

                <WebView
                    useWebKit
                    automaticallyAdjustContentInsets={true}
                    decelerationRate="normal"
                    scrollEnabled={true}
                    javaScriptEnabled={true}
                    domStorageEnabled={true}
                    originWhitelist={['*']}
                    onNavigationStateChange={this.handleWebViewNavigationStateChange}
                    allowsBackForwardNavigationGestures={true}
                    allowFileAccessFromFileURLs={true}
                    allowFileAccess={true}
                    allowUniversalAccessFromFileURLs={true}
                    allowingReadAccessToURL={'file://'}
                    showsHorizontalScrollIndicator={false}
                    showsVerticalScrollIndicator={false}
                />
                

    handleWebViewNavigationStateChange = (newNavState) => {
        console.error(newNavState);
    }

**Comment by TheAlmightyBob** [comment]
No, Apple does not support that.

**Comment by baixjian** [comment]
Thank you
