### ISSUE TITLE
on react-native-windows the mouse pointer disappears occasionally

### ISSUE THREAD

**Issue by exotexot** [react-native-webview/react-native-webview#3093]
**Bug description:**
on react-native-windows the mouse pointer disappears occasionally

**To Reproduce:**
Use react-native-webview 13.3.1, 
on react-native-windows 0.71.x,
enable webview2, 
open any site, 
move around with the pointer, click around

**Expected behavior:**
mouse pointer should be visible at all times.
or at least follow behaviour defined in css

**Screenshots/Videos:**

https://github.com/react-native-webview/react-native-webview/assets/10153413/c4291d40-a567-4b55-ac16-43d13ebf6328

**Environment:**
 - OS: Windows
 - OS version: 11
 - react-native version: 0.71.12
 - react-native-webview version: 13.3.1

**Comment by exotexot** [comment]
@chiaramooney @asklar do you have an idea why the webview2 version used in react-native-webview is so old? 

When in try to upgrade the webview version in the Nuget Manager it crashes my build. Even after cleaning and rebuilding.

**Comment by Dxg125** [comment]
After a painful manual update (yes i edited the packages, shame on me) to
  Microsoft.UI.Xaml = 2.8.5, 
  Microsoft.Windows.CppWinRT = 2.0.230706.1, (i needed that too)
  Microsoft.Web.WebView2 = 1.0.1901.177

The mouse stays in my WebView.
Seems a WebView Update really does resolve the missing mouse pointer.

My Versions are;
    "react": "18.2.0",
    "react-native": "0.72.3",
    "react-native-webview": "12.4.0",
    "react-native-windows": "0.72.1",

**Comment by chiaramooney** [comment]
I believe the Webview package version was whatever was available at the time WebView2 support was added to this module (approx 1 year ago). WinUI 2.8 was not released yet so we were reliant on the prerelease version which uses an older WebView2. I'll slate some time to update to the module to a higher WinUI version.

**Comment by chiaramooney** [comment]
Another option is to upgrade your app's version of WinUI. If you edit the WinUI2xVersion as shown here https://microsoft.github.io/react-native-windows/docs/customizing-sdk-versions to 2.8.5 and update your app's packages.config file to include Microsoft.UI.Xaml 2.8.5 this should allow your app to use WinUI2.8.5 and the updated webview2. Closing issue for now. Reopen if issue persists.
