### ISSUE TITLE
Failed to call into JavaScript module method RCTEventEmitter.receiveEvent()

### ISSUE THREAD

**Issue by ZaietsIhor** [react-native-webview/react-native-webview#3096]
**Bug description:**
When we reload an app, the error occurs:
Invariant Violation: Failed to call into JavaScript module method RCTEventEmitter.receiveEvent(). Module has not been registered as callable. Bridgeless Mode: false. Registered callable JavaScript modules (n = 10): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, HMRClient, AppRegistry.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes

**To Reproduce:**
This bug reproduces only on ios.
Create react native app, implement react native webview and reload an app. Note, that webview component must be on your screen when you press reload.
If you remove react-native-webview or move to another screen, everything works ok.

**Expected behavior:**
There are no errors.

**Screenshots/Videos:**
<img width="435" alt="image" src="https://github.com/react-native-webview/react-native-webview/assets/134282146/0a42d163-9004-4ed5-af99-6d07799c5497">

<img width="569" alt="image" src="https://github.com/react-native-webview/react-native-webview/assets/134282146/f4d5aa2f-597c-4572-91bc-11ba8230cc7f">

**Environment:**
 - OS: Iphone 14, IOS
 - OS version: 16.0
 - react-native version: 0.72.3
 - react-native-webview version: 13.2.3, but the same error at the newest version

**Comment by TheAlmightyBob** [comment]
Please share a sample project that reproduces the issue. I tried following the instructions and see no error.

**Comment by cpintos-sc** [comment]
This is not closed or stale @TheAlmightyBob

**Comment by neeteshraj** [comment]
facing the same issue.

**Comment by sbaiahmed1** [comment]
still having this issue

**Comment by HeXiuLian** [comment]
This error occurs when jumping from a container that originally loads RN offline packages to another container that originally loads RN offline packages. If the container that originally loads RN offline packages jumps to the native page and then jumps to another container that originally loads RN offline packages, it will display normally，reactnative(0.72.5)
![3011725503707_ pic_副本](https://github.com/user-attachments/assets/26e58a14-c0e7-40ee-9adb-afb38894ea0d)

**Comment by dhcmega** [comment]
same problem!
thanks.
