### ISSUE TITLE
Build fails on a clean project: `fatal error: 'butter/map.h' file not found`

### ISSUE THREAD

**Issue by Sherlock92** [react-native-webview/react-native-webview#3097]
**Bug description:**
Build is failing on a clean react native for macos project with WebView. I'm happy to work on this if needed but any pointers would be greatly appreciated.

**To Reproduce:**

Set up a new react native for macos project
- npx react-native@latest init WebViewTest --template "react-native@^0.71.0"
- cd WebViewTest && npx react-native-macos-init

Install react-native-webview
- yarn add react-native-webview
- cd macos && pod install && cd ..
- npx react-native run-macos

The build will fail with the following error:

```
WebViewTest/macos/Pods/Headers/Public/ReactCommon/react/bridging/Object.h:13:10: fatal error: 'butter/map.h' file not found
#include <butter/map.h>
         ^~~~~~~~~~~~~~
1 error generated.
```

**Expected behavior:**
Build to succeed

**Environment:**
 - OS: MacOS Monterey
 - OS version: 12.3.1
 - react-native version: 0.71.12
 - react-native-webview version: 13.3.1

**Comment by pxpeterxu** [comment]
I ran into this while trying to contribute, and believe it's related to an outdated Xcode build folder.

Running the below commands fixed it for me:

```sh
rm -rf example/ios/build
rm -rf example/ios/Pods
```

Based on https://github.com/software-mansion/react-native-reanimated/issues/3823#issuecomment-1346687536
