### ISSUE TITLE
再次打开webview怎么能让里面的函数重新执行呢？

### ISSUE THREAD

**Issue by BianXuerui** [react-native-webview/react-native-webview#3098]
因为我的需求是可以在两个地方进入webview
如果第一个地方进入了webview
在第二个地方再进入webview，则会进入第一个地方进入的webview的页面（这里期望是进入webview的初始页面）

**Comment by TheAlmightyBob** [comment]
有没有示例代码？不明白“进入webview“。

**Comment by jamninetyfive** [comment]
你的需求描述存在不清晰。
Your requirement description is unclear.

你是想复用webview页面?
Do you want to reuse webview pages?

**Comment by icefee** [comment]
use  ref.injectJavaScript

**Comment by linonetwo** [comment]
试试加 key，让 react 重新渲染，或者其它强制卸载组件的方法，比如靠 router 之类的库来强制卸载组件
