### ISSUE TITLE
Webview with `html` source crashes when navigating to previous screen on iOS

### ISSUE THREAD

**Issue by mrzachnugent** [react-native-webview/react-native-webview#3099]
**Bug description:**
- Given a web view on a screen of its own with `html` as its source
- When navigating back the previous screen
- Then, on occasion, it crashes the app without any logs

**To Reproduce:**
Minimal reproduction repo: https://github.com/mrzachnugent/react-native-webview-crash-minimal
1. Launch the app in an iOS simulator
2. Press on `Open modal WebView` button
3. Once the web view screen is open, navigate back to the previous screen
4. Repeat steps 2 and 3 until the app crashes

**Expected behavior:**
The behavior that I expected was that the app would not crash when going back and forth between screens.

**Screenshots/Videos:**

https://github.com/react-native-webview/react-native-webview/assets/63797719/a6cdf1bf-d0a0-47c0-8d04-07b9b381c25a

**Environment:**
 - OS: iOS
 - OS version: 16.2
 - react-native version: 0.72.3
 - react-native-webview version: 13.2.2

Thank you 🙂

**Comment by TheAlmightyBob** [comment]
Please update to a newer version of `react-native-webview` and test again. Version `13.2.2` had a known crashing bug on iOS.

**Comment by mrzachnugent** [comment]
@TheAlmightyBob Thanks for the quick response. Unfortunately, I get the same behaviour with the newest version.


https://github.com/react-native-webview/react-native-webview/assets/63797719/20addb9d-cdab-438a-9554-b1b0be5b5ac1


I updated `react-native-webview` to version `13.3.1`, I deleted the `package-lock.json` and the `node_modules`, ran `npm i` and cleaned the expo cache. I tried the latest version in my main app and I get the same results.

**Comment by TheAlmightyBob** [comment]
Are you using the new or old architecture?

**Comment by mrzachnugent** [comment]
> Are you using the new or old architecture?

The old architecture. 
<br />
It's a "managed expo app" that does not support the new architecture.

**Comment by vitalik1921** [comment]
I have the same issue and the same versions of RN and the WebView
