### ISSUE TITLE
android onNavigationStateChange return unexpected canGoBack result

### ISSUE THREAD

**Issue by Stephen-Song** [react-native-webview/react-native-webview#3100]
**Bug description:**
I'm using react-native-webview. The initial url is https://sushi.com, and then click enter App in the upper right corner of the webview. His url becomes https://sushi.com/swap but in Android's onNavigationStateChange The canGoBack of the returned information is false, try to call webview.current.goBack on the current page, but it does not work, use webview.current.injectJavascript(`
window.history.back();

true;
`) also does not work

All the above operations are working perfectly in the iOS environment

**To Reproduce:**
set initial url https://sushi.com then and then click enter App in the upper right corner of the webview. 

**Screenshots/Videos:**
https://github.com/react-native-webview/react-native-webview/assets/58379214/c64090d8-925c-4bcf-8faf-337c3a900a36

**Expected behavior:**
android trigger event onNavigationStateChange and return canGoBack  true, and webview.current.goBack() can go back to previous website

**Environment:**
 - OS: Android
 - OS version: any version can reproduce it
 - react-native version: 0.71.8
 - react-native-webview version: 13.0.0

**Comment by TheAlmightyBob** [comment]
This doesn't look related to `react-native-webview`. Have you tested in a browser? I see the same behavior in Chrome on Android.

**Comment by Stephen-Song** [comment]
> This doesn't look related to `react-native-webview`. Have you tested in a browser? I see the same behavior in Chrome on Android.
@TheAlmightyBob Thanks for replying me.  I found that the android chrome doesn't have back button for going back,but u can use hardwarebackpress to go back the previous website.Here comes the reaction in three main browser in android, I will appreciate it if u reply me again.
**chrome:** 
https://github.com/react-native-webview/react-native-webview/assets/58379214/1c43dedf-524e-4041-9efb-dbb666c2ee5a
**android firefox:**
https://github.com/react-native-webview/react-native-webview/assets/58379214/955a0a55-ee4c-4e75-bb39-25cd7c1a00b8
**android edge**
https://github.com/react-native-webview/react-native-webview/assets/58379214/98760aac-6663-41a5-9959-56646fa1f057

**Comment by Stephen-Song** [comment]
> @Stephen-Song Can you provide the code or all the props you are using with your Webview?

@Asad520  Thanks for replying me. Here comes the simple code i use in my webview, in the emulator the acting is more wired than in the real android phone, The former does not trigger onNavigationStateChange at all when switching urls.  u can try it in both ios simulator and android emulator. Please give me a hand, thank u again.

https://snack.expo.dev/@stephen_song/react-native-webview-android-bug?platform=android

**Comment by TheAlmightyBob** [comment]
>  I found that the android chrome doesn't have back button for going back, but u can use hardwarebackpress to go back the previous website

My apologies, you are correct. I could _swear_ Android Chrome used to display a back button as well.... but a quick googling suggests I might be crazy and imagined it 😞

**Comment by Stephen-Song** [comment]
> > I found that the android chrome doesn't have back button for going back, but u can use hardwarebackpress to go back the previous website
> 
> My apologies, you are correct. I could _swear_ Android Chrome used to display a back button as well.... but a quick googling suggests I might be crazy and imagined it 😞

Do you have any idea or suggestion on how to solve it😭？

**Comment by Asad520** [comment]
@Stephen-Song I couldn't make it work with expo. It was giving weird behaviors. However, I tried with one of my react-native-cli projects on react-native: 0.71.7 and react-native-webview: 12.1.0 and it behaved as desired. It could be related to [issue#2949](https://github.com/react-native-webview/react-native-webview/issues/2949) but I'm not sure. Let me know if it helps in any way

https://github.com/react-native-webview/react-native-webview/assets/47941595/c6fb12ad-4859-4c2f-be6b-5a83f66a12aa

**Comment by Stephen-Song** [comment]
> @Stephen-Song I couldn't make it work with expo. It was giving weird behaviors. However, I tried with one of my react-native-cli projects on react-native: 0.71.7 and react-native-webview: 12.1.0 and it behaved as desired. It could be related to [issue#2949](https://github.com/react-native-webview/react-native-webview/issues/2949) but I'm not sure. Let me know if it helps in any way
> 
>  Screen.Recording.2023-08-17.at.12.25.05.PM.mov

> @Stephen-Song I couldn't make it work with expo. It was giving weird behaviors. However, I tried with one of my react-native-cli projects on react-native: 0.71.7 and react-native-webview: 12.1.0 and it behaved as desired. It could be related to [issue#2949](https://github.com/react-native-webview/react-native-webview/issues/2949) but I'm not sure. Let me know if it helps in any way
> 
>  Screen.Recording.2023-08-17.at.12.25.05.PM.mov

@Asad520 Thank u for relating relative issue to me. it works when i remove useragent !

about the useagent issue, i think we set initial url about:blank would temporarily fix it, then use useEffect or componentDidMount to set the true url.

but it can go back at the initial true url, i think onNavigationStateChange={
   webviewRef.current?.injectJavaScript(`window.ReactNativeWebView.postMessage(JSON.stringify({data: window.history.length}))`)
}
then handleMessage from webview, if the history length === 2, just disable the go back button.

it is a transitional and temporary solutions, the real fix has to wait for the react-native-webview official to see how to fix it.

**Comment by gronxb** [comment]
Hello, I think this PR will solve the problem.
I need your attention.

If the issue is urgent, you can use it as a `patch-package`. Let me know if you need an example.

https://github.com/react-native-webview/react-native-webview/pull/3106
