### ISSUE TITLE
[Android][New Arch] Crashes an app in dev mode if `injectedJavaScriptBeforeContentLoaded` is used

### ISSUE THREAD

**Issue by birdofpreyru** [react-native-webview/react-native-webview#3101]
**Bug description:**
WebView crashes an app on Android if new architecture (Fabric) is enabled, and the app is build in development mode.

**To Reproduce:**
- Init a new RN app in the standard way:
  ```sh
  npx react-native@latest init AwesomeProject
  ```
- Enabled new arch for Android in `/android/gradle.properties`, by changing `newArchEnabled` to be `true`.
- Install `react-native-webview` by
  ```sh
  npm install --save react-native-webview
  ```
- Replace `App.tsx` content by this example:
  ```tsx
  import React from 'react';
  import {WebView} from 'react-native-webview';
  
  const BEFORE_CONTENT_INJECTION = `(
    function() {
    }
  )();`;
  
  function App(): JSX.Element {
    return (
      <WebView
        injectedJavaScriptBeforeContentLoaded={BEFORE_CONTENT_INJECTION}
        source={{uri: 'https://reactnative.dev/'}}
        style={{flex: 1}}
      />
    );
  }
  
  export default App;
  ```
- Run the dev server, and deploy the app to Android simulator, or a real device, in dev mode:
  ```sh
  npm start
  npm run android
  ```
  See it crashes on start-up.
- Note, it does not crash in release mode, if deployed by
  ```sh
  npm run android -- --mode=release
  ```
- Note, it does not crash if the line `injectedJavaScriptBeforeContentLoaded={BEFORE_CONTENT_INJECTION}` is commented out from `App.tsx`.

**Expected behavior:**
Expected to work without crashes.

**Screenshots/Videos:**

**Environment:**
 - OS: Ubuntu
 - OS version: 22.04.3 LTS
 - react-native version: 0.72.4
 - react-native-webview version: 13.3.1

**Comment by birdofpreyru** [comment]
I believe, I've narrowed it down to, presumably, some issue with React Native itself:
- The error prior to the crash I see in `adb logcat` logs reads:
  ```
  08-15 16:54:34.612 10074 10123 E ReactNative: /root/react-native/packages/react-native/ReactCommon/react/renderer/core/RawPropsKeyMap.cpp:88: function at: assertion failed (lower - 1 <= upper)
  08-15 16:54:34.612 10074 10123 F ReactNative: /root/react-native/packages/react-native/ReactCommon/react/renderer/core/RawPropsKeyMap.cpp:88: function at: assertion failed (lower - 1 <= upper)
  ```
- Looking at `RawPropsKeyMap.cpp`, I noticed that there is a limit on the maximum property name (`kPropNameLengthHardCap`), which is set equal 64 in RN code (and it is more than `injectedJavaScriptBeforeContentLoaded`, which is 38 symbols).
- However, just out of desperation I tried, what happens if I just replace in my codebase (and in all npm packages) the string fragment `njectedJavaScriptBeforeContentLoaded` by `ShortTest` &mdash; surprise-surprise, after such replacement my test app does not crash anymore. Gonna ask for advice in RN repo.

**Comment by birdofpreyru** [comment]
After some more troubleshooting (see https://github.com/facebook/react-native/issues/39019) it seems to me that there is probably a hard limit of max 256 props on a component, violated by **RNCWebView**, and not gracefully caught and reported by RN &mdash; effectively it will work fine when using any prop with name shorter than `injectedJavaScriptBeforeContentLoaded`, somehow it does not crash in release mode when using `injectedJavaScriptBeforeContentLoaded`, although it already hits the limit, and it probably will crash anyway with props with larger names.

Thus, I guess, **RNCWebView** must be refactored, to group most of properties into an options object, that can be passed to the native via a single component prop.

**Comment by kingkongqn4444** [comment]
the same issues with the latest version of react native and react-native-webview

**Comment by birdofpreyru** [comment]
Perhaps up-voting https://github.com/reactwg/react-native-releases/discussions/85#discussioncomment-6738837 will help to see the patch released rather sooner than later ;)

**Comment by kuchbhihosaktahai** [comment]
https://www.youtube.com/watch?v=Rq-mAjkG2ME&list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i&index=2

**Comment by birdofpreyru** [comment]
RN 0.72.5 is out today, it seems to have fixed the problem &mdash; my app using RN WebView now works with new arch on Android without crashing.
