### ISSUE TITLE
goBack() is not working in IOS popup

### ISSUE THREAD

**Issue by steve-smith93** [react-native-webview/react-native-webview#3110]
**Bug description:**
We have add WebVew in react-native IOS app popup. Also a button to navigate back to history pages. But the goBack function is not working proper. The page URL is showing navigation state change but the page have no changes instaed some images are missing.

**To Reproduce:**
Add a webview in IOS react-native app POPUP. Add a button to navigate back to history pages. On back button press method use function webviewref.current.goBack().

**Expected behavior:**
The history page needs to loaded when press back button

**Environment:**
 - OS: IOS
 - OS version: 12^
 - react-native version:0.71.2
 - react-native-webview version:12.0.2

**Comment by steve-smith93** [comment]
Please share if there any alternate solution exist

**Comment by Asad520** [comment]
Hi @steve-smith93 this could be related to [issue#2949](https://github.com/react-native-webview/react-native-webview/issues/2949). Can you try removing userAgent-related props if you use any? If it is related to this then I can share some methods to overcome this bug
