### ISSUE TITLE
[Windows] Not opening links in new window

### ISSUE THREAD

**Issue by jdschin** [react-native-webview/react-native-webview#3113]
**Bug description:**

Im developing a react native app for windows (UWP), using react-native-webview on one screen. On some devices (mostly company managed) the web view does not open links that have "target="_blank"" set. Those links should be opened in a new App Window. This does work on non company managed devices, so Im assuming that this has to do something with a company policy etc.. But I cant tell what to change in order to get this to work. Is anyone experiencing something similar?

**To Reproduce:**

Use the web view like shown below and click on a link, that opens a new tab (Visit W3Schools!).

```
<WebView
    source={{uri: "https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_a_target"}}
    useWebView2={true}
/>

```

**Expected behavior:**

A new App Window opens

**Environment:**
 - OS: Windows 10 Enterprise
 - OS version: 10.0.19045 Build 19045
 - react-native version: 0.71.4
 - react-native-webview version: 13.2.2

**Comment by jdschin** [comment]
Im also experiencing this on a non managed device. The difference between my device and the test notebook is just the enabled developer mode.

**Comment by chiaramooney** [comment]
This may be a behavior of the WebView2 control in general. I would check to see if this behavior repros on a plain non-RNW UWP app. If so, this is likely an issue you will have to file with the WinUI or WebView team.

**Comment by chiaramooney** [comment]
ping to keep open
