### ISSUE TITLE
[Windows] 2.8.0-prerelease.210927001 needed for WinUI2xVersion

### ISSUE THREAD

**Issue by jdschin** [react-native-webview/react-native-webview#3114]
**Bug description:**
react-native-webview requires the exact WinUI2 version 2.8.0-prerelease.210927001. This cant be changed (at least I did not find a way how) and leads to a build error.

**To Reproduce:**
Use  react-native-webview and set the following in ExperimentalFeatures.props

`
<WinUI2xVersion>2.8.5</WinUI2xVersion>
`

**Expected behavior:**
Version 2.8.5 of WinUi2 is used

**Environment:**
 - OS: Windows
 - OS version: Windows 11
 - react-native version: 0.71.4
 - react-native-webview version: 13.2.2

**Comment by chiaramooney** [comment]
Here is an app running using react-native-webview using WinUI2.8 https://github.com/microsoft/react-native-gallery (this app is on v0.72 which uses WinUI2.8 by default). Note in addition to editing your app's ExperimentalFeatures.props file, you may also need to change the Microsoft.UI.Xaml version in your app's packages.config file.

Closing for now. Can reopen if you are still running into issues.

**Comment by JakobKrummeichAndrena** [comment]
I saw that the version in ExperimentalFeatures.props for this package is still at` 2.8.0-prerelease.210927001`. Is this how it should be? And does adding `<package id="Microsoft.UI.Xaml" version="2.8.0" targetFramework="native"/>` to the app's ExperimentalFeatures.props overwrite this then?

**Comment by chiaramooney** [comment]
Yea that's correct! Currently the WebView package is using WinUI 2.8 pre-release by default. At some point we will update the package to use WinUI 2.8 by default. However, when you add the react-native-webview package to your RNW app the version of WinUI used will be consistent across the app and that version number will be determined by the app's set WinUI version. There is a default WinUI version set for each RNW version but you can also adjust your app's WinUI version by altering the ExperimentFeatures file (See here for more info: https://microsoft.github.io/react-native-windows/docs/customizing-sdk-versions) Adjusting your app's WinUI version will then change the WinUI version used to build the webview module in your app.

**Comment by JakobKrummeichAndrena** [comment]
Hello @chiaramooney, thank you for your reply! 
I have a follow-up question regarding this. We are using a dependency (@react-native-async-storage) whose `TargetPlatformMinVersion` is lower than needed for WinUI 2.8.0. What is the recommended way to use WinUI 2.8.0 and this dependency? Currently, we solved it by using a `Directory.Build.props` overwriting `TargetPlatformMinVersion`.

**Comment by chiaramooney** [comment]
Ah I see! We've updated a couple community modules already to have a more updated minversion, but if you want to upgrade that module as well this will be the only change needed: https://github.com/react-native-webview/react-native-webview/pull/2955/files. The maintainer should be responsive to a PR.
