### ISSUE TITLE
[iOS] Opening webview crashes app

### ISSUE THREAD

**Issue by mlsbez** [react-native-webview/react-native-webview#3115]
Hello, I'm having a hard time with webviews on my app, all iOS users are facing this issue: the app closes/crashes when they open an webview. It used to show the error to the user: **"error loading page domain nsurlerrordomain "error code -1004" description could not connect to the server"**  but after we commented the line "DataMiModule.registerSdStateChangeListner();" the app crashes (only on physical devices, on the simulator the webview works fine). I'd appreciate if someone could help me!

**Environment:**
 - OS: iOS
 - OS version: 16.6 (all iOS users actually)
 - react-native version: 0.63.3
 - react-native-webview version:  ^10.9.2

**Comment by anshhTID** [comment]
Integrated the basic webview, 
1. Unable to open webview 
2. Crashes/hangs Apps everytime trying to do it on button perss.

platform: iOS

**Comment by ibrahimPorgin** [comment]
You need to set permission to use camera (in xcode capabilities)
