### ISSUE TITLE
Error loading page Domain: NSURLErrorDomain Error Code:-1004 Description: Could not connect to the server

### ISSUE THREAD

**Issue by toyehuang** [react-native-webview/react-native-webview#3125]
**Bug description:**
According to my user feedback, when I visited a domain name page I gave through webview on my ios mobile phone,webview suddenly gave an error message as shown in the following during the visit:

 **Error loading page**
 Domain: NSURLErrorDomain 
Error Code:-1004 
Description: Could not connect to the server

wath happen? 

At first, the user was able to access normally, but later in the process, this prompt suddenly popped up

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS: ios
 - OS version: ios 15.6 (but not 100%)
 - react-native version: 0.70.5
 - react-native-webview version: ^11.23.1

**Comment by TheAlmightyBob** [comment]
Sounds like the phone couldn't connect to the server.
