### ISSUE TITLE
Can't Control Volume in WebView HTML Video

### ISSUE THREAD

**Issue by ChristopherGabba** [react-native-webview/react-native-webview#3127]
**Bug description:**
I'm using a video html element in a react-native-webview and volume can't be adjusted, it is always maximum. It is always on a maximum (1.0 is default for HTML video). 

**To Reproduce:**
Just a basic web view
 
```
      <WebView
            ref={webViewRef}
            containerStyle={{
               width: '103%',
               height: '100%',
               marginLeft: -10,
            }}
            style={{
                 marginTop: -20
           }}
            scrollEnabled={false}
            startInLoadingState
            renderLoading={() => <ActivityIndicator />}
            source={{
                html:
                    `<div style="width: 102%; max-width: 102%; height: 105%; align-items: center; padding-left: 10px; border: none;">
                        <video id="video" style="width: 100%; height: auto;" playsinline>
                        <source src="https://www.youtube.com/watch?v=sSsTR8qqDl4" type="video/mp4">
                        </video>
                    </div>
                `
            }}
            originWhitelist={['*']}
            allowsInlineMediaPlayback={true}
            allowsFullscreenVideo={false}
            onLoadEnd={()=> setPlay(true)}
            onContentProcessDidTerminate={webViewRef.current?.reload}
        />
```

I then inject javascript like so:

```
   const [play, setPlay] = useState(false);
    useEffect(() => {
        if (play) {
            if (webViewRef.current) {
                webViewRef.current.injectJavaScript(`setTimeout(() => { document.getElementById('video').play(); }, 50);`);
                webViewRef.current.injectJavaScript(`setTimeout(() => { document.getElementById('video').volume = 0.2; }, 50);`);
            }
        }
    }, [play])
```

Note: I also tried the react-native-youtube-iframe package which uses react native web view and the same result. The volume prop provided does not work. I tried downgrading to a version 11 react native web view as an experiment and I had the same behavior. I also submitted an issue there: https://github.com/LonelyCpp/react-native-youtube-iframe/issues/305. 

**Expected behavior:**
The video plays just fine, but the volume doesn't change at all. I've tried videos from multiple different sources and it's the same story. I have tried 4 or 5 different methods proposed here:
https://stackoverflow.com/questions/7582385/is-there-a-way-to-set-the-default-html5-video-volume 

**Screenshots/Videos:**
None needed, video plays fine.

**Environment:**
 - OS: iPhone 11
 - OS version: 16.6
 - react-native version: "0.72.4"
 - react-native-webview version: "13.2.2"
 - expo:  "^49.0.7" using dev client

**Comment by Rajveer07** [comment]
if the problem is only with ios or with android too ?

**Comment by ChristopherGabba** [comment]
I have not tried it on android, but will try it and let you know.

**Comment by EmpeeDubs** [comment]
Also having this issue with iOS. Mute works okay, but seems like webview doesnt want to change the volume for the video.

**Comment by ChristopherGabba** [comment]
Please re-open this issue as it is still not working.

**Comment by AkanBerkant** [comment]
Nobody can figure it out

**Comment by zaferatli** [comment]
its related ios feature, not allowed to set js video object volume. 
<img width="1887" alt="Ekran Resmi 2024-11-02 21 38 42" src="https://github.com/user-attachments/assets/d65f8231-592e-4008-9eef-9f5e98b6b980">

**Comment by ChristopherGabba** [comment]
@zaferatli my problem is not the physical volume but in balancing volume between two sources. Let's say I have music in the background and I'm using a Webview. I want to adjust the audio balance between those two sources and I can't at the moment. The main volume is a whole other thing in this situation. The`expo-video` package allows this flexibility so I am not sure why it wouldn't work with this webview but I guess I'm not a knowledgeable iOS developer.

**Comment by zaferatli** [comment]
Its so normal, iOS prohibited to change video volume on html content but you can deal with other packages.

**Comment by AkanBerkant** [comment]
What a nonsense this is. Why can't we change the sound of any YouTube or HTML video in mobile applications? For example, there are 2 sounds on the screen. Each voice should be unique. If I connect the sound of the video to the sound of the phone, this time I am also interfering with the sound below.
