### ISSUE TITLE
RNCWebViewManagerImpl.kt : Type mismatch: inferred type is String? but String was expected

### ISSUE THREAD

**Issue by techDPM** [react-native-webview/react-native-webview#3131]
**Bug Description**:
RNCWebViewManagerImpl.kt : Type mismatch: inferred type is String? but String was expected

**Issue Summary**:
When attempting to run the latest version of React Native WebView, an error occurs in the RNCWebViewManagerImpl.kt file. The error message states, "Type mismatch: inferred type is String? but String was expected." This error is specifically related to code on line 337, which is responsible for loading a URL into the WebView component using the args.getString(0) method.

**Steps to Reproduce**:

Upgrade to the latest version of React Native WebView.
Attempt to use the WebView component to load a URL by calling webView.loadUrl(args.getString(0)).
**Expected Behavior**:
The URL should be loaded into the WebView without any type mismatch errors, as it did in the previous version of React Native WebView.

**Actual Behavior**:
An error occurs with the following message: "Type mismatch: inferred type is String? but String was expected," pointing to the line of code mentioned above.

**Environment**:
React Native WebView Version: ^13.5.1
its heepend is android with gradle 7.0.2

**Comment by HassanAbbasAtTkxel** [comment]
I got the same issue, any solution to this problem.

**Comment by thijs-qv** [comment]
Came across this while using 13.6.2 on an older version of React Native. You can edit the source file and cast the value to String:
In `node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManagerImpl.kt` at line 340 change
`webView.loadUrl(args.getString(0))` to `webView.loadUrl(args.getString(0) as String)`.
