### ISSUE TITLE
Webview is very laggy during scroll and click actions

### ISSUE THREAD

**Issue by damodharanj** [react-native-webview/react-native-webview#3136]
**Bug description:**

Webview is very laggy during scroll and click actions

**Environment:**
 - OS:
 - OS version:
 - react-native version: 0.72.4
 - react-native-webview version:13.6.0

**Comment by TheAlmightyBob** [comment]
This is not actionable. Where are you seeing this? Do you have a sample project to share?

**Comment by damodharanj** [comment]
Found the issue. 
It was the from the following warning
`tried to use permissions api while not attached to an activity`

When I removed unwanted permission (Bluetooth admin & connect) from the app webview is smooth.
