### ISSUE TITLE
react native webview support speech to text microphone is not showing the text when speech is occurring

### ISSUE THREAD

**Issue by anthonywu2000** [react-native-webview/react-native-webview#3138]
react native webview doesn't seem to support speech to text microphone is not showing the text when speech is occurring. Anyone know how to resolve this?

**Comment by faisalkhan1690** [comment]
Add this in info.plist
	<key>NSSpeechRecognitionUsageDescription</key>
	<string>Description of why you require the use of the speech recognition</string>
