### ISSUE TITLE
Error compiling project 

### ISSUE THREAD

**Issue by TulioMeran** [react-native-webview/react-native-webview#3145]
Hi, 

i'm getting this error when i run the command **./gradlew build** in my project

**\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\RNCWebView.java:167:
Error: Cast from Callback2 to Callback requires API level 23 (current min is 21) [NewApi]
        return super.startActionMode(new ActionMode.Callback2()**

**Environment:**
 - OS: Android
 - OS version: Android 13
 - react-native version: 0.72.4
 - react-native-webview version: 13.3.0 and lalest version also

**Comment by mattpmoreno** [comment]
@TulioMeran If you havent already solved this, I was able to update android/build.gradle :: buildscript.ext.minSdkVersion to 23, which gets rid of the error you reported.
