### ISSUE TITLE
WebView not opening google form shortened link.

### ISSUE THREAD

**Issue by ashwinsquadstack** [react-native-webview/react-native-webview#3151]
**Bug description:**
When I am passing google form shortened link in the source of the webView it is throwing the error 
`Can't open url: intent://forms.gle/ugQnQwE3gZ2NJ4Ni6#Intent;package=com.google.android.gms;action=com.google.firebase.dynamiclinks.VIEW_DYNAMIC_LINK;scheme=https;S.browser_fallback_url=https://docs.google.com/forms/d/e/1FAIpQLSePuQoiRHJVRD30B-wUyw5ATp6KqmODryVeBq1XAxLr2Y9RLQ/viewform%3Fusp%3Dsend_form;end;`
 while when i am passing full URL it is successfully opening the URL inside of webView

**To Reproduce:**
Just pass any google form shortened link in the source of the webVIew for example `https://forms.gle/zsinYML6MVy437Nm6`

**Expected behavior:**
It should open Google forms's shortened URL in the WebView.

**Screenshots/Videos:**
<img width="329" alt="Screenshot 2023-09-20 at 3 30 58 PM" src="https://github.com/react-native-webview/react-native-webview/assets/126559970/a99f143a-e930-458c-928c-88a66afb17b2">
<img width="320" alt="Screenshot 2023-09-20 at 3 30 44 PM" src="https://github.com/react-native-webview/react-native-webview/assets/126559970/30b87eb0-a3be-4198-86a3-8c4309ae9caa">

**Environment:**
 - OS: MACOS 
 - OS version: 12.5
 - react-native version: 0.70.10
 - react-native-webview version: 11.23.1

**Comment by zaferatli** [comment]
When i try i access google. You need upgrade you env. 

[Image]()

My env.

```
System:
  OS: macOS 13.5.2
  CPU: (8) x64 Apple M2
  Memory: 24.42 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.14.2
    path: ~/.nvm/versions/node/v16.14.2/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 8.5.0
    path: ~/.nvm/versions/node/v16.14.2/bin/npm
  Watchman:
    version: 2023.07.10.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.0
    path: /Users/zaferatli/.rvm/rubies/ruby-2.7.6/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.2
      - iOS 16.2
      - macOS 13.1
      - tvOS 16.1
      - watchOS 9.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2020.3 AI-203.7717.56.2031.7678000
  Xcode:
    version: 14.2/14C18
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.20
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/zaferatli/.rvm/rubies/ruby-2.7.6/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
  
  
    "react": "18.2.0",
    "react-native": "0.72.4",
    "react-native-webview": "^13.2.2"
```

**Comment by ashwinsquadstack** [comment]
> When i try i access google. You need upgrade you env.
> 
> [Access image](https://github.com/react-native-webview/react-native-webview/assets/54990817/416ea9b5-86c6-4564-8506-7b547ed938e7)
> 
> My env.
> 
> ```
> System:
>   OS: macOS 13.5.2
>   CPU: (8) x64 Apple M2
>   Memory: 24.42 MB / 16.00 GB
>   Shell:
>     version: "5.9"
>     path: /bin/zsh
> Binaries:
>   Node:
>     version: 16.14.2
>     path: ~/.nvm/versions/node/v16.14.2/bin/node
>   Yarn:
>     version: 1.22.19
>     path: /usr/local/bin/yarn
>   npm:
>     version: 8.5.0
>     path: ~/.nvm/versions/node/v16.14.2/bin/npm
>   Watchman:
>     version: 2023.07.10.00
>     path: /usr/local/bin/watchman
> Managers:
>   CocoaPods:
>     version: 1.12.0
>     path: /Users/zaferatli/.rvm/rubies/ruby-2.7.6/bin/pod
> SDKs:
>   iOS SDK:
>     Platforms:
>       - DriverKit 22.2
>       - iOS 16.2
>       - macOS 13.1
>       - tvOS 16.1
>       - watchOS 9.1
>   Android SDK: Not Found
> IDEs:
>   Android Studio: 2020.3 AI-203.7717.56.2031.7678000
>   Xcode:
>     version: 14.2/14C18
>     path: /usr/bin/xcodebuild
> Languages:
>   Java:
>     version: 11.0.20
>     path: /usr/bin/javac
>   Ruby:
>     version: 2.7.6
>     path: /Users/zaferatli/.rvm/rubies/ruby-2.7.6/bin/ruby
> npmPackages:
>   "@react-native-community/cli": Not Found
>   react:
>     installed: 18.2.0
>     wanted: 18.2.0
>   react-native:
>     installed: 0.72.4
>     wanted: 0.72.4
>   react-native-macos: Not Found
> npmGlobalPackages:
>   "*react-native*": Not Found
> Android:
>   hermesEnabled: true
>   newArchEnabled: false
> iOS:
>   hermesEnabled: true
>   newArchEnabled: false
>   
>   
>     "react": "18.2.0",
>     "react-native": "0.72.4",
>     "react-native-webview": "^13.2.2"
> ```

Was the google form link which you tried to open was a full link or shortened URL of Google Form?

**Comment by zaferatli** [comment]
i tried with this url: https://forms.gle/zsinYML6MVy437Nm6

**Comment by ashwinsquadstack** [comment]
Then may be it is the issue of the version which I am using I did not try the higher version.

**Comment by getsettalk** [comment]
i have same issue so google docs and google form link not opening
