### ISSUE TITLE
Memory leak issues with version 13.6.0

### ISSUE THREAD

**Issue by TheRogue76** [react-native-webview/react-native-webview#3152]
**Bug description:**
Memory leak issues with version 13.6.0

**To Reproduce:**
reproduction repo : https://github.com/TheRogue76/rnwwmemoryleak
Steps:
1. Create a new empty project
2. Add RNWW
3. Add a component that shows a web view with a url when state is true and removes it when it is false
4. Profile the output with something like Xcode instruments

**Expected behavior:**
1. Releasing the memory once the view is unmounted
2. Lower memory usage, (I'm not familiar with WKWebview's normal usage, so i could be wrong, but 500 mb with nothing attached sounds a bit much and feels like it might be related to something else, but if i am wrong, please let me know)

**Screenshots/Videos:**
<img width="1397" alt="Screenshot 2023-09-20 at 13 32 21" src="https://github.com/react-native-webview/react-native-webview/assets/40071952/2ff65723-5f1c-4dfc-a3e7-41d8140bc05e">
<img width="1397" alt="Screenshot 2023-09-20 at 13 32 24" src="https://github.com/react-native-webview/react-native-webview/assets/40071952/4ff32651-a0b4-4961-9d20-6e5b908d7eee">

**Environment:**
 - OS: MacOS
 - OS version: 13.5.2
 - react-native version: 0.72.4
 - react-native-webview version: 13.6.0

**Comment by TheRogue76** [comment]
Not actively searching, since i am not using React Native very actively anymore, but if anyone sees anything or has ideas, please contribute

**Comment by TheRogue76** [comment]
Issue persists

**Comment by TheRogue76** [comment]
Let it get closed. I looked at the code to try to see if i could add some weak self references to the webview in the call back handlers and break the reference cycle, but i can not reason about the 1800 line file that is `RNCWebViewImpl.m`. If any maintainers see this issue down the line and want to know more about what i think the issue is, feel free to reach out.

**Comment by SaadBinWaheed-og** [comment]
Still happening.
