### ISSUE TITLE
Inconsistent onShouldStartLoadWithRequest behaviour

### ISSUE THREAD

**Issue by spezzino** [react-native-webview/react-native-webview#3153]
**Bug description:**
Internal state not updated when using onShouldStartLoadWithRequest to control the webview url externally and inject custom headers. Following the example outlined [in the Guide](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Guide.md#setting-custom-headers).

1. Initial url = /b
2. Webview fires onShouldStartLoadWithRequest with request.url = /b. Function returns true to continue to load
3. site issues a 302 redirect to /a. Webview fires onShouldStartLoadWithRequest with request.url = /a, this is different from the external state, so returns false and updates the external url.
4. External url (which is /a now) is passed onto the webview in the source prop, but nothing happens, a blank page is observed.

**To Reproduce:**
[Github repo](https://github.com/spezzino/rnwebview-sample)
Start the app and a blank page will appear. Check the logs to see how the state is updated

**Expected behavior:**
Webview loads the page after a 302 redirect when using onShouldStartLoadWithRequest

**Environment:**
 - OS: iOS
 - OS version: 17
 - react-native version: 0.72.4
 - react-native-webview version: 13.6.0

**Comment by yoannHertienne** [comment]
+1
