### ISSUE TITLE
Webview userAgent Prop breaks onShouldLoadWithRequest event request object

### ISSUE THREAD

**Issue by coderdark** [react-native-webview/react-native-webview#3155]
**Bug description:**
I am working on a project using a react native webview that renders a web page that uses Power bi and allows the user to download any Power Bi report (these are not static downloads but progressive). Currently we had to add the userAgent props to the react native webview for a secondary issue. Before adding the userAgent props, i was getting the full data of the report inside the onShouldLoadWithRequest request.url like this `blob:attachement/file; base64 data-here`. I then used the data to save the report.

After adding the userAgent props, the data coming to onShouldLoadWithRequest in the request object is now a blob url that looks like `blob:https://www.yourpage.com/98d987fd99s978d98ds98dss888ds8d98s0`. When i try to download the blob url i get a simple small (3K) html page, nothing of it is the data for the report.

**To Reproduce:**
Mac OS
- Add React Native Webview
- Point the webview to a power bi reports page
- Add an userAgent prop and include your user-agent string
- Click on the power BI report to download (not static download)
- Wait for the onShouldLoadWithRequest to provide a request object
- The request object will have a url property with `blob:https://www.yourpage.com/98d987fd99s978d98ds98dss888ds8d98s0`
- Try to read it with `react-native-blob-util`
- The file is not what is expected

**Expected behavior:**
The behavior i expect is for the onShouldLoadWithRequest request object to have a url property with `data:attachement/file; base64, data-of-file-here` which i can use to save the data with no problem.   It stops working when i add userAgent props and it converts the request.url to  `blob:https://www.yourpage.com/98d987fd99s978d98ds98dss888ds8d98s0` which does not work.

**Screenshots/Videos:**

**Environment:**
 - OS: iOS
 - OS version: 16
 - react-native version: 0.71.10
 - react-native-webview version: 13.5.1

**Comment by zaferatli** [comment]
i think you need to provide userAgent which you use and sample link for pdf. Then we can reproduce easliy.

**Comment by coderdark** [comment]
@zaferatli  the string for the user agent is the following: `'Mozilla/5.0 (iPad; U; CPU iPhone OS 3_2 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Version/4.0.4 Mobile/7B314 Safari/531.21.10'` I can't not provide a sample link since this is company data.   We are basically using a webview to render a page that uses `powerbi embed react` component and it provides download functionality.   This download is a `progressive download` not static.  When trying a static download, the download works with the same userAgent string.   Hope this helps.  I am at a lost understanding why a progressive download can change the request object of a onShouldStartWithRequest when using userAgent props.

**Comment by oneil-marcelo** [comment]
Hi @coderdark.
Are you using Looker from Google?
