### ISSUE TITLE
WebView not loading with static source when APK is built net:ERR_NAME_NOT_RESOLVED. Works perfectly fine in Expo Go

### ISSUE THREAD

**Issue by x-tba** [react-native-webview/react-native-webview#3166]
**Bug description:**
I'm creating a react native app with expo and I'm using a web view with static source (local html, js, css, etc files) which is stored in app to render a chart. This works perfectly fine in the expo go apps in both iOS and Android physical devices and emulators.

But when I built the Android APK and installed it I'm getting ERR_NAME_NOT_RESOLVED.

<img width="397" alt="ERROR" src="https://github.com/react-native-webview/react-native-webview/assets/142498770/6d772a1c-7f52-465a-95ec-b67d6a07169a">

I provide the main index file as below,

`const chartHtml = require("../../chartFiles/html/chart.html");`

and the web view is configured as below,

`.      <WebView`
`          ref={webViewRef}`
`          style={{ flex: 1 }}`
`          source={chartHtml}`
`          startInLoadingState`
`          originWhitelist={['*']}`
`        />`

I have tried passing the below props as well into the web view
          `allowFileAccess={true}`
          `domStorageEnabled={true}`
          `allowUniversalAccessFromFileURLs={true}`
          `allowFileAccessFromFileURLs={true}`
          `mixedContentMode="always"`

I have also provided the below build config in app.json to fix another ERR_Network

`"plugins": [
      [
        "expo-build-properties",
        {
          "android": {
            "usesCleartextTraffic": true
          }
        }
      ]
    ]`

**To Reproduce:**
Build APK and install.

**Expected behavior:**

Web view should work as expected with the static source. Works fine in expo go in both iOS and Android.

**Screenshots/Videos:**

Chart source structure, located in the root level and a copy is in /assets folder as well. 

<img width="260" alt="Chart source structure" src="https://github.com/react-native-webview/react-native-webview/assets/142498770/4f5e6e00-80ba-495c-9ed4-2ec75f455f7b">

Checked on two physical devices with Android 11 and 13. Also in an emulator with the APK with API 33 and 34.
Was not able to check on iOS as developer account restriction.

Not sure if this is related to this issue https://github.com/react-native-webview/react-native-webview/issues/2723

**Environment:**
 - OS: MacOS
 - OS version: 13.5
 - react-native version: 0.72.4
 - react-native-webview version: 13.2.2
 - expo: 49.0.7

**Comment by the-unknown** [comment]
Thanks, I was just about to write the same bug report!
So +1 for me on this. 

I am using Expo, too. And I have set "usesCleartextTraffic": true

**Comment by Sotaren** [comment]
I faced the same issue, using the same settings as x-tba, and got it working with
`source={{html: htmltext, baseUrl: ''}}`

But to load the htmltext as a string I had to use babel-plugin-content-transformer in babel.config.js with:

```
plugins: [
      ['content-transformer', {
        transformers: [
          {file: /\.raw.html$/,
            format: 'string'
          }],
      }],
```

and then
`import htmltext from '../myhtml.raw.html'`

**Comment by QuantumValhalla** [comment]
^ Seems to be related to this: https://github.com/expo/expo/issues/21072 

This may help: https://github.com/facebook/react-native/issues/18216#issuecomment-412569517

**Comment by jailbreakerVC** [comment]
Is there any updated fix for this issue? thanks
