### ISSUE TITLE
App stops when com.google.android.webview is updated

### ISSUE THREAD

**Issue by hanselsen** [react-native-webview/react-native-webview#3173]
**Bug description:**
My Android app keeps showing the sticky notification for a foreground service, but the react native service stopped working.
After a bug report dump from developer settings, I see this:

```
  package: com.myapp.mobile
    Historical Process Exit for uid=10549
        ApplicationExitInfo #0:
          timestamp=2023-10-05 01:05:58.005 pid=8310 realUid=10549 packageUid=10549 definingUid=10549 user=0
          process=com.myapp.mobile reason=10 (USER REQUESTED) subreason=21 (FORCE STOP) status=0
          importance=125 pss=231MB rss=209MB description=stop com.google.android.webview due to installPackageLI state=empty trace=null
        ApplicationExitInfo #1:
          timestamp=2023-10-04 20:20:05.759 pid=8440 realUid=99256 packageUid=10549 definingUid=10171 user=0
          process=com.google.android.webview:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:0 reason=13 (OTHER KILLS BY SYSTEM) subreason=17 (ISOLATED NOT NEEDED) status=0
          importance=300 pss=53MB rss=143MB description=isolated not needed state=empty trace=null
```

It seems to me that Android is updating com.google.android.webview and with that stopping the app.
Is there a way to work around this issue? Or maybe even a clean solution?

**To Reproduce:**
I am unable to reproduce it so far.

**Expected behavior:**
That the app is not killed when webview is stopped

**Screenshots/Videos:**
n/a

**Environment:**
 - OS: Android
 - OS version: 13
 - react-native version: 0.71.8
 - react-native-webview version: 11.26.0

**Comment by freeboub** [comment]
should be reproducible with following adb command:
adb shell am force-stop com.google.android.webview
BTW, There is following issue in react native to be handled prior to investigation of this issue https://github.com/facebook/react-native/issues/37211
I just tested a blank project: npx react-native@latest init AwesomeProject  (0.74.5) the app crashes with this reproduction step
