### ISSUE TITLE
[react-native@0.73.0-rc.2] iOS. Xcode 15 fails to build `react-native-webview@13.6.2`

### ISSUE THREAD

**Issue by o-alexandrov** [react-native-webview/react-native-webview#3177]
**Bug description:**

Xcode 15 fails to build `react-native-webview@13.6.2` used w/ `react-native@0.73.0-rc.2`.

**To Reproduce:**

```sh
VERSION=0.73.0-rc.2 && npx "react-native@$VERSION" init Example --version "$VERSION" --verbose --skip-install --directory="example"
cd example
npm i
npm i react-native-webview@13.6.2
bundle install; cd ios; RCT_NEW_ARCH_ENABLED=1 NO_FLIPPER=1 bundle exec pod install
```

Then, attempt to build the app in Xcode to see the few errors

**Environment:**
 - OS: MacOS
 - OS version: 14.0
 - react-native version: 0.73.0-rc.2
 - react-native-webview version: 13.6.2

**Comment by frannale** [comment]
react-native-webview@13.6.2 works fine in react native 0.70.13 with xCode 15, maybe is a compatibility problem with react-native@0.73.0-rc.2

**Comment by o-alexandrov** [comment]
`react-native-webview@13.6.2` works fine with `react-native@0.72.5` in Xcode 15.
This issue is not about the `<0.72.X` versions; it's a placeholder for `>=0.73.0`

**Comment by ravindraguptacapgemini** [comment]
@o-alexandrov were you able to fix those errors?

**Comment by o-alexandrov** [comment]
@ravindraguptacapgemini no
