### ISSUE TITLE
`webviewDebuggingEnabled` does not work when app is installed via TestFlight/App Store

### ISSUE THREAD

**Issue by thep-dr** [react-native-webview/react-native-webview#3179]
Hi maintainers 😊 

Thanks for building this awesome library! 

**Bug description:**
`WebviewDebugging` in Safari only works when I locally run Debug builds. When I build the app and ship it to my phone via TestFlight, it does not seem to be enabled. Is this a known limitation? 

**To Reproduce:**
Component:
```
<WebView source={{ uri: url }} webviewDebuggingEnabled />
```

Build a production version of an app using this component and verify that the `WebviewDebugging` does not seem to be enabled.

**Expected behaviour:**
Both Debug and Production versions of apps should have `WebviewDebugging` enabled if the `webviewDebuggingEnabled` is set to `true`.

**Environment:**
 - OS: iOS
 - OS version: 16.7.0 and 17.0.1
 - react-native version: 72.5
 - react-native-webview version: 13.6.2

**Comment by jlleblanc** [comment]
@thep-dr another thing I noticed just now: I am able to run the inspector with the simulator, regardless of whether `webviewDebuggingEnabled` is present.

**Comment by thep-dr** [comment]
Hi @jlleblanc 

Do you mean `webviewDebuggingEnabled={true}`? I have just tried that, but no luck.

The other thing is really surprising! I have just tried again, but I am only able to run the inspector if the `webviewDebuggingEnabled` is present. Are you running the same versions of `react-native` and `react-native-webview` as mentioned in the issue text?

**Comment by jlleblanc** [comment]
@thep-dr yes, that is what I meant. I have been doing a lot of TypeScript-only projects recently and mentally added a squiggly red underline under `webviewDebuggingEnabled` 😂 

I am using the same version of `react-native-webview`, but I am on React Native 71.

A side question I have is "is there any drawback to just leaving `webviewDebuggingEnabled` on in production?" I am considering doing that, but that is the one thing that gives me pause.

**Comment by thep-dr** [comment]
Makes sense 😆 

About drawbacks: tbh, I am not completely sure. My guess would be no, but I was planning on just giving it a shot and seeing the result.
