### ISSUE TITLE
[Windows] build error: This project references NuGet package(s) that are missing on this computer.

### ISSUE THREAD

**Issue by panthuncia** [react-native-webview/react-native-webview#3189]
**Bug description:**

Attempting to build & run this project in Windows with 'npx react-native run-windows', I get the error:

This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is C:\Users\matth\Sailbot\sailbot_telemetry_reactnative\windows\packages\Microsoft.UI.Xaml.2.8.0\build\native\Microsoft.UI.Xaml.targets.. Check your build configuration.

The console log has:

√ Restoring NuGet packages 
 √ Auto-linking...
in it, so I'm not quite sure what's wrong.

The folder "Microsoft.UI.XAML.2.8.0" is indeed missing in the packages folder- instead, there is "Microsoft.UI.Xaml.2.8.0-prerelease.210927001". It looks like NuGet is getting the wrong version? 

If I rename that folder to Microsoft.UI.XAML.2.8.0, I get a new problem- command ""C:\Users\matth\.nuget\packages\microsoft.windows.cppwinrt\2.0.211028.7\build\native\..\..\bin\"cppwinrt @"x64\Debug\SailbotTelemetry.vcxproj.cppwinrt_ref.rsp"" exited with code 1.

This also happens when building in visual studio.

On android, it runs successfully.
**To Reproduce:**

https://github.com/panthuncia/sailbot_telemetry_reactnative

or:

just attempt to set up the example project from react-native-webview

install npm, windows extension, and try to run the project on Windows

**Expected behavior:**

The project should build successfully, or indicate how to resolve the issue

**Screenshots/Videos:**

**Environment:**
 - OS: Windows 11
 - OS version: 22621.2428
 - react-native version: 0.72.6
 - react-native-webview version: 13.6.2
 - react-native-windows version: 0.72.14

**Comment by panthuncia** [comment]
Update: I got it to work by opening the visual studio solution and re targeting the NuGet packages to the versions that the error said were missing. Perhaps the defaults should be updated?

**Comment by vinaykumardetrix** [comment]
can you describe more about it, which helps me out in a detailed way to follow.

**Comment by rain9155** [comment]
I also encountered the same error，I resolved this error by modifying the “react-native-webview\windows\ReactNativeWebView\ReactNativeWebView.vcxproj” file，remove ImportGroup “ExtensionTargets” and target “EnsureNuGetPackageBuildImports”：
![image](https://github.com/react-native-webview/react-native-webview/assets/38580832/9dfa2404-bc65-45e3-a934-f9192338d54f)

**Comment by Adbhutashra** [comment]
Build failed with message C:\Users\91626\.nuget\packages\microsoft.windows.cppwinrt\2.0.211028.7\build\native\Microsoft.Windows.CppWinRT.targets(741,9): error MSB3073: The command ""C:\Users\91626\.nuget\packages\microsoft.windows.cppwinrt\2.0.211028.7\build\native\..\..\bin\"cppwinrt @"x64\Debug\Bingo.vcxproj.cppwinrt_ref.rsp"" exited with code 1. [C:\Users\91626\Downloads\Bingo-Mobile-App\Bingo-Mobile-App\windows\Bingo\Bingo.vcxproj]. Check your build configuration.

I am getting the same error please help me out.

**Comment by keerthipativinaykumar** [comment]
> Build failed with message C:\Users\91626\.nuget\packages\microsoft.windows.cppwinrt\2.0.211028.7\build\native\Microsoft.Windows.CppWinRT.targets(741,9): error MSB3073: The command ""C:\Users\91626\.nuget\packages\microsoft.windows.cppwinrt\2.0.211028.7\build\native\..\..\bin\"cppwinrt @"x64\Debug\Bingo.vcxproj.cppwinrt_ref.rsp"" exited with code 1. [C:\Users\91626\Downloads\Bingo-Mobile-App\Bingo-Mobile-App\windows\Bingo\Bingo.vcxproj]. Check your build configuration.
> 
> I am getting the same error please help me out.

Check this out it might help you out so follow this comment 
https://github.com/react-native-webview/react-native-webview/issues/3189#issuecomment-1871707735

**Comment by Adbhutashra** [comment]
@keerthipativinaykumar I have uninstall the webview dependency but still giving me this error and with webview I have tried that but the error remains same.

**Comment by sanjeev1379** [comment]
getting same error React Native Windows Project references NuGet package(s) that are missing on this computer.

```
× Building Solution: re to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=3221...
× Build failed with message 
node_modules\react-native-webview\windows\ReactNativeWebView\ReactNativeWebView.vcxproj(195,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, The missing file is \windows\packages\Microsoft.UI.Xaml.2.8.0\build\native\Microsoft.UI.Xaml.targets.. Check your build configuration.
Command failed.
```
how can we solve?
