### ISSUE TITLE
In android not showing map view perfect.

### ISSUE THREAD

**Issue by nikunj95749** [react-native-webview/react-native-webview#3191]
**Bug description:**
In ios showing perfect view but in android not showing perfect view.

**To Reproduce:** "<div id="myMap" `style="position:relative;width:100%;min-width:290px;height:600px;"></div>"`

**Expected behavior:**

**Screenshots/Videos:**

ANDROID screen shot
<img width="373" alt="Screenshot 2023-10-19 at 3 29 54 PM" src="https://github.com/react-native-webview/react-native-webview/assets/48313639/6298d945-6748-40cf-8f28-f362ff95dd58">

IOS screen shot
<img width="357" alt="Screenshot 2023-10-19 at 3 29 36 PM" src="https://github.com/react-native-webview/react-native-webview/assets/48313639/eccb50df-6397-4426-8636-3cfb48a6ee82">

**Environment:**
 - OS: Venture
 - OS version:  13.4.1
 - react-native version: "0.72.5"
 - react-native-webview version: "^13.6.2"

**Comment by pxpeterxu** [comment]
I think it's quite possible that this isn't an issue with react-native-webview, but the underlying browser implementations (Safari on iOS, Chrome/Chromium on Android). Can you try rendering the same on actual browsers?
