### ISSUE TITLE
[iOS] missing cookies on initial requests

### ISSUE THREAD

**Issue by Skizu** [react-native-webview/react-native-webview#3194]
**Bug description:**

`webView` is `nil` when calling `-[RNCWebViewImpl writeCookiesToWebView:completion:]` in `-[RNCWebViewImpl resetupScripts:]`. 

**To Reproduce:**

Have a WebView that makes a request with an auth cookie from ReactNative.

**Expected behavior:**

Request headers include cookies.

**Screenshots/Videos:**

N/A

**Environment:**
 - OS: iOS
 - OS version: 11+
 - react-native version: v0.71+
 - react-native-webview version: v12.0.0+

**Comment by MikhailMalinin-iOSDeveloper** [comment]
Same issue.
Your solution is not working

**Comment by Asad520** [comment]
Facing a similar issue. I'm trying to set cookies using injectJavascript`document.cookie = myJWT`. However, the webview is not able to read the cookie when the next request is sent and refreshes the token which messes up some scenarios. I tried the code in your PR but the same results.

**Comment by federico-agustin-diaz** [comment]
> Facing a similar issue. I'm trying to set cookies using injectJavascript`document.cookie = myJWT`. However, the webview is not able to read the cookie when the next request is sent and refreshes the token which messes up some scenarios. I tried the code in your PR but the same results.

Were you able to solve this issue?

**Comment by one-god** [comment]
Same issue.
