### ISSUE TITLE
Camera permissions get stuck when switching from the webview to another app.

### ISSUE THREAD

**Issue by FaizanChoudhary** [react-native-webview/react-native-webview#3197]
I'm reporting a critical bug in React Native's WebView. Camera permissions get stuck when switching from the webview to another app and back, requiring manual camera toggling for restoration. This is impacting user experience.

**Bug description:**
Using react-native-webview with react native cli when i switch app while using camera in webview to another camera-app then my camera of webview where im in a meeting is stucked & when i come back my camera remains stucked it does not get permission back by there own rather then i manual camera toggling for restoration 

**Expected behavior:**
The expected behavior is that camera permissions should automatically restore when returning to the webview, similar to how it functions in a web browser like Chrome.

**Comment by pjcape** [comment]
Hi, Did you find a solution ? Currently facing the same issue with an android device running android 12

**Comment by FaizanChoudhary** [comment]
> Hi, Did you find a solution ? Currently facing the same issue with an android device running android 12

No, I didn't waste much time on this. Instead, I changed my approach and am now using the SDK directly in my app, which resolved the issue for me.

**Comment by pjcape** [comment]
what sdk are u using directly in your app ?

**Comment by FaizanChoudhary** [comment]
> what sdk are u using directly in your app ?

Basically I was integrated different meeting portal sdks ( Teams, Zoom, RingCentral ) on web. For that I wanna use the web-view in my mobile app but due to some bugs I prefer to use there React Native SDKs directly in my app.
