### ISSUE TITLE
Session not persisting when i close app and open for iOS but works on Android

### ISSUE THREAD

**Issue by Elue-dev** [react-native-webview/react-native-webview#3203]
**Bug description:**
Session not persisting when i close app and open for iOS but works on Android.

So i am using `react-native-webview ` to show a Microsoft Sharepoint site. After a user logs in with a microsoft account, and closes the app, and then later reopens the app, it asks the user to login again, it dosen't cache the user's session (meanwhile on a regular browser it keeps me signed in). It does cache the email of the user, but the user always has to enter their password again to authenticate, which is bad for user experience especially considering the fact that it is a two-factor authentication process. This issue only occurs on iOS, on android it works perfectly, on android, the user logs in once and the session is cached for a long time.
Here is the code for the webview component:

```javascript
 <WebView
          source={{ uri: WEB_URL }}
          style={styles.webView}
          ref={webViewRef}
          onLoadStart={() => setLoading(true)}
          onLoad={() => setLoading(false)}
          onNavigationStateChange={handleNavigationStateChange}
          startInLoadingState={true}
          mediaPlaybackRequiresUserAction={false}
          allowFileAccess={true}
          domStorageEnabled={true}
          useWebKit={true}
          cacheEnabled={true}
          sharedCookiesEnabled={true}
          thirdPartyCookiesEnabled={true}
          pullToRefreshEnabled={true}
          showsHorizontalScrollIndicator={false}
          showsVerticalScrollIndicator={false}
          onContentProcessDidTerminate={reloadWebView}
          mediaCapturePermissionGrantType="grantIfSameHostElsePrompt"
          scalesPageToFit
          userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"
          ß
          cacheMode="LOAD_CACHE_ELSE_NETWORK"
          mixedContentMode="compatibility"
          incognito={false}
          geolocationEnabled={true}
          onError={(syntheticEvent) =>
            Alert.alert("Something went wrong. Please try reloading")
          }
          onRenderProcessGone={(syntheticEvent) => {
            const { nativeEvent } = syntheticEvent;
            reloadWebView();
            console.warn("WebView Crashed: ", nativeEvent.didCrash);
          }}
        />
```

**Expected behavior:**
What i expect is that once i login and close the app, reopening the app and the webview should still keep me logged in, just as it does in a regular browser.

I've been stuck on this issue for weeks, any help or alternative ways to achieve the same thing would be highly appreciated will be greatly appreciated

**Environment:**
 - react-native version: "0.72.6"
 - react-native-webview version: "13.2.2"

**Comment by Elue-dev** [comment]
> I'm experiencing a similar problem on IOS device, whereas Android device is functioning perfectly.

same thing happened to me, didn't find a solution, let me know if you did

**Comment by farazahmed** [comment]
Facing same issue since 6 months, no solution.

**Comment by kamaldeepj** [comment]
Hey is there any solution for this?

**Comment by DuduExlibris** [comment]
help!

**Comment by bjwie** [comment]
Im facing the same issue

**Comment by ltujiba** [comment]
Any update on this?

I'm facing the same issue

**Comment by shuo-hiwintech** [comment]
+1

**Comment by shuo-hiwintech** [comment]
What's the latest?

**Comment by shuo-hiwintech** [comment]
Solution:
1.Identify the cookies required by your website to stay logged in.
2.Store the cookies after a successful login:
`const cookies = await CookieManager.get(env.URL, true);
await AsyncStorage.setItem(asyncStorageKey, JSON.stringify(cookies));`
3.Set cookies when the app initializes:
`await Promise.all([
  CookieManager.set(env.URL, cookies?.memberID, true),
  CookieManager.set(env.URL, cookies?.memberPassword, true),
  CookieManager.set(env.URL, cookies?.memberSession, true),
]);`

**Comment by Night3y3** [comment]
It works for only for 2-3 instances of the app. After when the app is closed and re opened, app asks to login, any fix for that?
