### ISSUE TITLE
Sound in webview pauses background music e.g. Spotify (only on iOS)

### ISSUE THREAD

**Issue by AlbinNewSeed** [react-native-webview/react-native-webview#3205]
**Bug description:**
Sound in webview pauses background music e.g. Spotify (only on iOS). 
On Android it's working correctly (it doesn't pause music).

**To Reproduce:**
Start music e.g. using Spotify.
Create a webview app which plays a sound.
Run on iOS.

**Expected behavior:**
Expecting it to work as it does on Android (not interrupting music), or some configuration to manage this.

**Environment:**
 - OS: iOS
 - OS version: 17
 - react-native version: 0.71.10
 - react-native-webview version: 11.26.0

**Comment by suwu150** [comment]
any problems?
