### ISSUE TITLE
React Native WebView does not keep track of camera permission when app is closed or screen changes

### ISSUE THREAD

**Issue by felipe-miranda-marreiros** [react-native-webview/react-native-webview#3206]
**Bug description:**

I'm using AWS Liveness Face Detection that requires camera permission to work. On the first install, React Native WebView works correctly. It asks for camera permission and the face detection is done.

If the user closes the app or goes to another screen, the WebView does not recognize the camera permission anymore. I check the camera permission using [PermissionsAndroid](https://reactnative.dev/docs/permissionsandroid) and it returns "granted", but the WebView still can't show the camera, making the Liveness return CAMERA_ACCESS_ERROR.

Yes. the AWS Liveness is on HTTPS.

**Expected behavior:**

If the user already gave the permission to access the camera, WebView should keep track of it.

**Environment:**
 - OS: Android
 - OS version: 11
 - react-native version: 0.72.6
 - react-native-webview version: 13.6.2

```
<WebView
      source={{
        uri: ""
      }}
      style={{
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center'
      }}
      onMessage={livenessResponse}
      originWhitelist={['*']}
      mediaCapturePermissionGrantType="grantIfSameHostElsePrompt"
      mediaPlaybackRequiresUserAction={false}
      startInLoadingState
      allowsInlineMediaPlayback={true}
      allowsFullscreenVideo
      domStorageEnabled
      javaScriptEnabled
      scalesPageToFit
      pullToRefreshEnabled
```

**Comment by Ravshanichk** [comment]
Facing the same issues on some android devices. I am using webview for biometric authentication through webview with camera access. Additionally, i use react-native perission library to get access to camera, before getting to webview, all access are granted, but still camera does't appear in webview

Tested on  environment:
model: HUAWEI P30 lite
OS: Android
OS version: 10
react-native version: 0.70.14
react-native-webview version: 13.8.2
 react-native-permissions: 3.10.1

**Comment by felipe-miranda-marreiros** [comment]
> Facing the same issues on some android devices. I am using webview for biometric authentication through webview with camera access. Additionally, i use react-native perission library to get access to camera, before getting to webview, all access are granted, but still camera does't appear in webview
> 
> @felipe-miranda-marreiros Have you managed to solve this problem?
> 
> Tested on environment: model: HUAWEI P30 lite OS: Android OS version: 10 react-native version: 0.70.14 react-native-webview version: 13.8.2 react-native-permissions: 3.10.1

Hi. The problem disappeared after some time. Also, I think it was something to do with AWS Amplify (React) package. I'm using React Native 0.71.14.

Make sure you have: <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" /> on your AndroidManifest.xml as well.

**Comment by felipe-miranda-marreiros** [comment]
Also, this problem was only happening in development.

**Comment by pjcape** [comment]
Hi felipe, I am currently facing the same issue, I already have ```<uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />```  in android manifest. Did your problem disappear after upgrading your react native version ??

**Comment by pjcape** [comment]
@felipe-miranda-marreiros , could you please help me out

**Comment by felipe-miranda-marreiros** [comment]
> @felipe-miranda-marreiros , could you please help me out 

Sorry for the late responde. The problem disappeared after I upgrade my RN project and AWS Amplify. I'm also using the latest React Native Webview.

**Comment by pjcape** [comment]
Hi @felipe-miranda-marreiros , unfortunately even after upgrading my RN project from 0.66.5 to 0.74.2 and upgrading my react-native-webview to the most latest version. I am still facing the issue, whereby the webview does not keep track of camera permission. I am currrently using react-native-permissions 4.0.1, are you also using the most latest react-native-permissions version ?

**Comment by Ravshanichk** [comment]
@pjcape  Hello! I managed to fix this problem. The bug was in library react-native-vision-camera, i am using version 2.6.18 and in my application user must make a photo of card, after that camera was still active after unmounting, that why webview couldn't find camera. Hope this will help

**Comment by pjcape** [comment]
Hi @Ravshanichk , my application is a webRTC calling feature. Initially when the app is loaded and user gives permissions for camera and mic, I am able to call perfectly. However, when the app is in the background for 1 min, the camera and mic are no longer in user hence the green icon at the top disappears. However, when i come back to the app, the green icon only shows microphone is in use and not camera. I have also done console.log to check permission status for camera and it returns granted.

In my website server code, I have also prompted for audio and video:
```var constraints = {
    video: true,
    audio: true
}
navigator.mediaDevices.getUserMedia(constraints)
    .then(stream => {
    ```

**Comment by pjcape** [comment]
also this only happens on android. On ios, after the app is back into the foreground, it shows the green icon for camera and microphone and i am able to call perfectly as well

**Comment by felipe-miranda-marreiros** [comment]
> Hi @felipe-miranda-marreiros , unfortunately even after upgrading my RN project from 0.66.5 to 0.74.2 and upgrading my react-native-webview to the most latest version. I am still facing the issue, whereby the webview does not keep track of camera permission. I am currrently using react-native-permissions 4.0.1, are you also using the most latest react-native-permissions version ?

I'm not using React Native Permissions. I'm using Expo Camera and its own Request Permission hook. I also created a dedicated screen to ask permissions before sending the user to the webview.

**Comment by edenjiga** [comment]
Hi @pjcape were you able to solve the problem? im facing the same issue. for IOS its working properly but for android, i use the camera and try to open the same web page i do faces the issue
