### ISSUE TITLE
When clicking on an anchor link in local HTML in iOS, the ‘back’ button functionality does not work.

### ISSUE THREAD

**Issue by kosipov** [react-native-webview/react-native-webview#3208]
Displaying a downloaded HTML file in a WebView. It contains anchor links. I added a ‘Back’ button using goBack. However, when I click on an anchor link, the ‘Back’ button does not work. Everything works fine on Android. The ‘Back’ button also works when requesting a page through WebView.”

**Code**

```js
<WebView
        ref={webViewRef}
        originWhitelist={['*']}
        source={{
          html: material,
          baseUrl: baseUrl,
        }}
        startInLoadingState={true}
        renderLoading={behaviourOnLoading}
        automaticallyAdjustContentInsets={false}
        containerStyle={{backgroundColor: 'transparent'}}
        allowsBackForwardNavigationGestures={true}
        onNavigationStateChange={onNavigationStateChange}/>
```
**Environment:**
 - OS: iOS
 - OS version: 16.4
 - react-native version: 0.72.3
 - react-native-webview version:13.6.2

**Comment by faizannazir** [comment]
https://stackoverflow.com/questions/62862335/react-native-webview-why-is-the-goback-method-not-working
