### ISSUE TITLE
How to send data in react-native-webView header with case sensitive

### ISSUE THREAD

**Issue by Salmankhan033** [react-native-webview/react-native-webview#3213]
I want to send header data as  
```
  const headers = {
    App: 'true',
    platform: Platform.OS,
    userID: userID,
    Mathieu: 'Big Boss',
  };
```
```
 <WebView
            source={{uri: initialLink, headers}}
            javaScriptEnabled={true}
            ref={webViewRef}
            mediaPlaybackRequiresUserAction={false}
            domStorageEnabled={true}
            startInLoadingState={true}
            renderLoading={() => <ActivityIndicatorElement />}
            onContentProcessDidTerminate={() => webViewRef.current.reload()}
            onError={() => setOnError(true)}
          />
```

When I sent the data we got App and Mathieu in lower case I want to get these in PascalCase, same as I sent.
The issue only occurs in Android in iOS it works well. 
I am using  
 "react-native": "0.72.4",
"react-native-webview": "13.6.0",
issues are all Android devices and emulators. 

<img width="891" alt="Screenshot 2023-11-07 at 8 44 03 PM" src="https://github.com/react-native-webview/react-native-webview/assets/58082294/324e77c3-779c-438a-a331-ac143ab8a975">

**Comment by Asad520** [comment]
Hi @Salmankhan033, How did you access the headers that you passed in Webview?
