### ISSUE TITLE
Apple Pay issue on iOS less than 16

### ISSUE THREAD

**Issue by pranaynemavrize** [react-native-webview/react-native-webview#3215]
Hello everyone,

I am trying to integrate apple pay on web as solution.
As native is working fine but due to some requirements i need to integrate it on web , and i am hitting url from frontend and html file which is responsible for apple pay UI and apple session is hosting on server. 
That apple pay session is coming from a payment gateway converge.

**Bug description:**

on iOS 16,17 its working as expected but on iOS less than 16 its not working
as i am trying to use webview with url which is hosting apple pay as web in a html file its not working on iOS 15 and lesser while same this is working as expacted on ios 16 and above.

i have tried multiple things as i added prop enableApplePay without sending any other parameters also -

`<WebView
          source={{
            uri: paymentUrl,
            headers: headers,
          }}
          enableApplePay={true}
          automaticallyAdjustContentInsets={false}
          ></WebView>`

if i use enableApplePay then i am not seeing any error but if i use without this prop (enableApplePay) then i am seeing error as "Apple Pay not available" and in both case nothing happening on pressing of apple pay button which is rendered.

now for same code above i tried to use apple pay demo url code and its working as perfactly on ios 15

`<WebView
                    enableApplePay={true}
                    source={{uri: "https://applepaydemo.apple.com/"}}
                    automaticallyAdjustContentInsets={false}
                />`

**To Reproduce:**
Try to integrate apple pay web solution on ios 15

**Expected behavior:**
Apple Pay payment UI should come up on click of apple pay button

**Environment:**
 - OS: iOS
 - OS version: < 15
 - react-native version: 0.64.2
 - react-native-webview version: 11.23.1

**Comment by pettomartino** [comment]
@pranaynemavrize have you found a solution for this ?

**Comment by nemapranay** [comment]
Not yet

**Comment by rajneeshcyadav** [comment]
Do we have any update on this ? Its seems like closed , have anyone found a solution for this?

**Comment by UsamaAshraf82** [comment]
+1
