### ISSUE TITLE
Error Loading Page (ERR_CONNECTION_REFUSED)

### ISSUE THREAD

**Issue by nolife08021** [react-native-webview/react-native-webview#3216]
**Bug description:**
It happen in some user. 

**To Reproduce:**
It is a captcha webview link.

**Expected behavior:**
Able to view it

**Screenshots/Videos:**

<img width="197" alt="Screenshot 2023-11-08 at 9 23 07 PM" src="https://github.com/react-native-webview/react-native-webview/assets/49778835/e5cc6b4a-0e26-416d-8698-b7b4b988c222">

**Environment:**
 - OS: Android Nova 8 SEa
 - OS version: HarmonyOS 2.0.0
 - react-native version: 0.70.3
 - react-native-webview version: 11.23.1

**Comment by SherryLinn** [comment]
yarn html:dev

**Comment by jehillert** [comment]
If anybody is trying to run a `vite` react web app inside the webview, for local development you will get this error using the `@vitejs/plugin-react-swc` plugin. You need to use the regular dev server, so `@vitejs/plugin-react` instead. 

Also, if running on device:
`adb reverse tcp:3000 tcp:3000`

This is probably not necessary, but in the vite config: 
```
  server: {
    host: '127.0.0.1',  
    port: 3000,
  },
```

**Comment by SherryLinn** [comment]
您好！您发送的邮件我已收到。谢谢！

**Comment by Sumansourabh14** [comment]
How to fix this issue on an Expo managed project?

```
    "@dr.pogodin/react-native-fs": "^2.24.6",
    "@dr.pogodin/react-native-static-server": "^0.6.0-alpha.8",
    "@react-native-async-storage/async-storage": "1.21.0",
    "expo": "^50.0.0",
    "react": "18.2.0",
    "react-native": "0.73.6",
    "react-native-webview": "13.6.4",
```

**Comment by SherryLinn** [comment]
您好！您发送的邮件我已收到。谢谢！

**Comment by choijiho0021** [comment]
There was exactly the same error, and I solved it like this. The server solved it by changing the redirect response to 301 or 302 instead of 308.

Example.

Before.
redirect(s"https://localhost/auth/canc?resultCode=99999&resultMsg=Unknown+Error", StatusCodes.PermanentRedirect)

After.
redirect(s"https://localhost/auth/canc?resultCode=99999&resultMsg=Unknown+Error", StatusCodes.TemporaryRedirect)
