### ISSUE TITLE
[New Architecture-Fabric] yoga/style/Style.h not found for React Native 0.73.4 RC.4

### ISSUE THREAD

**Issue by ravindraguptacapgemini** [react-native-webview/react-native-webview#3218]
I am getting this compile time warning after upgrading app to react-native 0.73.0-rc.4.
<img width="1321" alt="Screenshot 2023-11-10 at 2 28 00 AM" src="https://github.com/react-native-webview/react-native-webview/assets/97147467/42a595d2-3368-4413-b301-f4bcdeb65048">

**Comment by ravindraguptacapgemini** [comment]
Please add this to Header Search Paths to pod project of react-ntive-webview

"${PODS_ROOT}/Headers/Private/Yoga"  non-recursive

**Comment by cpintos-sc** [comment]
Thanks @ravindraguptacapgemini for the fix, it worked perfectly

**Comment by grahammendick** [comment]
You can fix it by [migrating your podspec to `install_modules_dependencies`](https://reactnative.dev/docs/0.71/the-new-architecture/backward-compatibility-turbomodules#configure-the-turbo-native-module-dependencies)
```ruby
  if ENV['RCT_NEW_ARCH_ENABLED'] == '1' then
    install_modules_dependencies(spec)
  end

**Comment by salisuabubakar** [comment]
> You can fix it by [migrating your podspec to `install_modules_dependencies`](https://reactnative.dev/docs/0.71/the-new-architecture/backward-compatibility-turbomodules#configure-the-turbo-native-module-dependencies)
> 
> ```ruby
>   if ENV['RCT_NEW_ARCH_ENABLED'] == '1' then
>     install_modules_dependencies(s)
>   end
> ```

I tried it but it didnt work.
