### ISSUE TITLE
I used ref to operate webview, but got an error in ts

### ISSUE THREAD

**Issue by Vvaraz** [react-native-webview/react-native-webview#3222]
![image](https://github.com/react-native-webview/react-native-webview/assets/73987251/b73040d2-74cf-40b9-acef-36f455ebe379)
`No overload matches this call.
  Overload 1 of 2, '(props: (IOSWebViewProps & AndroidWebViewProps & WindowsWebViewProps) | Readonly<IOSWebViewProps & AndroidWebViewProps & WindowsWebViewProps>): WebView<...>', gave the following error.
    Type 'MutableRefObject<WebView<{}> | undefined>' is not assignable to type 'LegacyRef<WebView<{}>> | undefined'.
      Type 'MutableRefObject<WebView<{}> | undefined>' is not assignable to type 'RefObject<WebView<{}>>'.
        Types of property 'current' are incompatible.
          Type 'WebView<{}> | undefined' is not assignable to type 'WebView<{}> | null'.
            Type 'undefined' is not assignable to type 'WebView<{}> | null'.
  Overload 2 of 2, '(props: IOSWebViewProps & AndroidWebViewProps & WindowsWebViewProps, context: any): WebView<{}>', gave the following error.
    Type 'MutableRefObject<WebView<{}> | undefined>' is not assignable to type 'LegacyRef<WebView<{}>> | undefined'.ts(2769)`

so,what goes wrong with this code?

**Comment by Lilsax** [comment]
@Vvaraz how did u manage to solve this ?
