### ISSUE TITLE
Android WebView can't load website with Cloudflare for security reasons

### ISSUE THREAD

**Issue by lucaslcw** [react-native-webview/react-native-webview#3227]
**Bug description:**
Using the library when trying to at least load the website that is protected by Cloudflare, it does not load and says there is a security problem with the connection. On iOS, even if it shows Cloudflare it is possible to perform the CAPTCHA and access the content.

**To Reproduce:**
Use the lib and place a website that is protected by Cloudflare and try to access.

**Expected behavior:**
I would like to be able to access the website, even if the user is charged for performing the CAPTCHA, perhaps passing the user's session information to the webview to make the connection more secure.

**Screenshots/Videos:**
![image](https://github.com/react-native-webview/react-native-webview/assets/106099323/69750945-745c-4273-921c-ca73f1d3bf5b)

**Environment:**
 - OS: Android
 - OS version: 11
 - react-native version: 0.71.8
 - react-native-webview version: 11.26.0

**Comment by tanzeel152** [comment]
got any solution?

**Comment by tykoth** [comment]
I am facing a similar issue.
I have a website that uses cloudflare turnstile on login page, and developed an android app using a simple webview, but did not works on login page (the page with cloudflare turnstile)...

I've searched the docs for something like change the userAgent but nothing works yet.

**Comment by lucaslcw** [comment]
Well, I still haven't been able to find a solution for this. I tried to change the User Agent but without success.

**Comment by tykoth** [comment]
Any thoughts?

**Comment by alexk111** [comment]
Anyone succeeded? It looks like changing the User Agent will be not enough and CF probably uses some browser features not supported by the webview - based on [their statement](https://developers.cloudflare.com/waf/reference/cloudflare-challenges/#supported-browsers) that even not every browser will be able to pass their challenges.

**Comment by toshiossada** [comment]
any solution?

**Comment by sonywijaya** [comment]
This issue also persists on the iOS app. Our app was rejected because it runs human verification indefinitely.

![Image](https://github.com/user-attachments/assets/22efb0f9-69fa-47b9-9524-55a4e17bfca3)

![Image](https://github.com/user-attachments/assets/63926735-effa-4428-b287-b8e7e5f3b7d8)

**Comment by tommywong-dev** [comment]
A bit late to the thread, but you can allow the URL to be opened by setting the WebView whitelist with (*) wildcard. Not the best practice but use this approach if you are sure the URLs opened are safe.

```ts
<WebView
  ...
  originWhitelist={[*]}
/>
```
