### ISSUE TITLE
Android WebView navigation doesn't work as expected while navigating via injecting JavaScript to pages that uses react-router and history manipulation..

### ISSUE THREAD

**Issue by anihazra678** [react-native-webview/react-native-webview#3229]
## **Bug description:**

Forward navigations via injecting javascript such as `window.postMessage('router://<url_here>', location.origin);` works for pages having custom navigation implementation via 'react-router' and history manipulation. But none of the lifecycle events such as `onLoadStart`, `onLoadEnd`, or `onNavigationStateChange` get triggered. `webView.canGoBack()` always returns `false`, `webView.goBack()` results in a no-op but injecting back navigation scripts via history API i.e., `window.history.back()` works.

Works as expected in other platforms i.e., iOS

 ## **To Reproduce:**

- Navigate forward via injecting JS `window.postMessage('router://<url_here>', location.origin);`
- WebPage should have router navigation implemented using `react-router` and manipulation of the history stack.

## **Expected behavior:**

- Methods such as onNavigationStateChange should get triggered and that too with appropriate values i.e., `canGoBack: true`.
- The `goBack()` method should work as expected instead of relying on injecting JS to navigate back in the history stack.

**Screenshots/Videos:**

**Environment:**
 - OS: Android
 - OS version: 13, 14
 - react-native version: 0.71.0
 - react-native-webview version: 11.23.0

**Comment by naveedashfaq272** [comment]
@anihazra678 have you found any solution?? I am also facing same with my published app

**Comment by anihazra678** [comment]
@naveedashfaq272  
This is a native Android WebKit behavior that's responsible for this in the RN platform. Following up with the Android WebKit team here - [Issue](https://issuetracker.google.com/issues/311440496)

**Comment by brijeshc** [comment]
Any updates on this? Any workaround for android? Still facing this issue.

**Comment by hamza-choudhary** [comment]
even if you render google.com you are not able to click on menus click dont work you cannot freely move between pages
