### ISSUE TITLE
Could not find component config for native component

### ISSUE THREAD

**Issue by harrymash2006** [react-native-webview/react-native-webview#3233]
**Bug description:**
Getting the following error on React native: "0.73.0-rc.5" on android
node_modules/react-native-webview/lib/RNCWebViewNativeComponent.js: Could not find component config for native component

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS: Android
 - OS version: Android 11
 - react-native version: 0.73.0-rc.5
 - react-native-webview version: 13.6.2

**Comment by UNIDY2002** [comment]
Should be fixed by [v13.6.3](https://github.com/react-native-webview/react-native-webview/releases/tag/v13.6.3)

**Comment by irekrog** [comment]
@janvandertaelen did you find maybe solution for this?

**Comment by irekrog** [comment]
@janvandertaelen did you find a solution?

**Comment by irekrog** [comment]
I temporarily used this mock https://github.com/react-native-webview/react-native-webview/issues/2959#issuecomment-1695757917 and the tests passed, but as I mentioned, this is a temporary solution where we replaced the actual webview with a view

**Comment by UNIDY2002** [comment]
Please note that the original post doesn't specify that the error occurs in a Jest environment, so kindly refrain from giving a thumbs-down without that context.

It's worth emphasizing that mocking native components is a validated practice, and this discussion dates back to the early days when the new architecture was introduced (refer to https://github.com/react-native-webview/react-native-webview/pull/2686#issuecomment-1425865443).

Surprisingly, even in the React Native core, native modules are mocked, nevertheless it is transparent to applications. You can find relevant details in the React Native repository here: https://github.com/facebook/react-native/blob/main/packages/react-native/jest/setup.js#L165-L193.

**Comment by thomazcapra** [comment]
> Should be fixed by [v13.6.3](https://github.com/react-native-webview/react-native-webview/releases/tag/v13.6.3)

I can confirm, in the `v13.6.1` the error is happening, the `v16.6.3` everything works fine :). Thanks.

**Comment by siddarthkay** [comment]
I too faced this issue right after upgrading to react-native 0.73.1
https://github.com/react-native-webview/react-native-webview/releases/tag/v13.6.3 fixed it for me.

**Comment by ThomasHinfact** [comment]
I still face the issue on iOS, even after moving to `v13.6.3`

**Comment by delphinebugner** [comment]
Some note after trying to debug: 

- this was introduced in version `12.0.0` of the lib - aka the one where new archi was added
- I answered myself my second question about "why Flow parser" : in the babel-plugin-codegen, every file finishing by .js is parsed using flow 
- and here we try to parse `react-native-webview/lib/RNCWebViewNativeComponent.js` as its imported in `WebView.ios.js`, the component used in test

So the main question remains, why is babel-plugin-codegen called to parse this file and not "classic babel" plugin? As part of the parsing made by jest on every file at the beginning of the test function `jest/transform/build/ScriptTransformer.js:717` in the stacktrace I believe) ; and how to prevent it?

Note : I will probably use a simple mock of the JS Webview, as suggested above; even if I loose all of the default props in my snapshots (but i'm not sure I actually need them) ; but I'm still interested to understand why this is happening!

If needed, the mock I recommand - slightly different from above, no require & using forwardRef:

```typescript
// In file __mocks__/react-native-webview.ts at the root of the project
import React from 'react';

// eslint-disable-next-line react/display-name, @typescript-eslint/no-explicit-any
const WebView = React.forwardRef((props, ref: any) => {
  return React.createElement('MockWebView', { ...props, ref });
});

module.exports = { WebView };

```

**Comment by delphinebugner** [comment]
Okay with @ellouzeskandercs we found a solution 🥳 

### The investigation 
It's normal to call `babel-plugin-codegen` in test env - the way I'm figuring it, it's like a "second job" for this module, parsing `codegenNativeComponent` in test env and formatting it for jest

It relates to the following lines in `packages/react-native-babel-preset/src/configs/main.js:58` I think: 
```javascript
  if (
    !options.disableStaticViewConfigsCodegen &&
    (src === null || /\bcodegenNativeComponent</.test(src))
  ) {
    extraPlugins.push([require('@react-native/babel-plugin-codegen')]);
  }

``` 

Problem was, we were calling it on a js file and not the index.ts file of webview lib ; so the parsers were not working. 
We can see that in the error stack trace above

```
      at Object.require (node_modules/react-native-webview/index.js:1:1) // 🐞 why oh why do you take the JS??
      at Object.require (src/common/organisms/WebView/MyWebView.component.tsx:3:1) 
```

### The solution 

We needed to force jest to take the ts entry for react-native-webview; we did that using the `moduleNameMapper` in jest.config: 

```
// in jest.config.js
module.exports = {
 moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'], // ts is already priritized here
 moduleNameMapper: { 
    'react-native-webview': '<rootDir>/node_modules/react-native-webview/src/index.ts', // ✅ here those lines
  },
 ....
}
``` 

Second step, to avoid the "TurboModuleRegistry.getEnforcing(...): 'RNCWebView' could not be found" error, we added the mock of RNCWebView Native modules - the simplest of all : 

```typescript
// in __mocks__/react-native-webview.ts
import { NativeModules } from 'react-native';

NativeModules.RNCWebView = {};

module.exports = require('react-native-webview');
``` 

Mocking the Native Module is enough, even for a TurboModule after!

### Next steps 

No need for JS mock of the webview anymore, we're super happy 😊 

*But it's still a workaround with the `moduleNameMapper` * ; we first made the change directely in package.json of react-native-webview:

```diff
diff --git a/package.json b/package.json
index 4786f37..97f8c64 100644
--- a/package.json
+++ b/package.json
@@ -1,7 +1,7 @@
 {
   "name": "react-native-webview",
   "description": "React Native WebView component for iOS, Android, macOS, and Windows",
-  "main": "index.js",
+  "main": "src/index.ts",
   "main-internal": "src/index.ts",
  "react-native": "src/index.ts", // in our setup, this was'nt enough 😢 
``` 
It was working, but we could not keep it like that locally. Should we modify it for every one? I struggle imaginating the impact -  @UNIDY2002, @jamonholmgren & @abrieldonadel as author & reviewers of https://github.com/react-native-webview/react-native-webview/pull/3209, do you have any thoughts on it?

**Comment by UNIDY2002** [comment]
@delphinebugner Nice investigation! I think it is a valid solution, but since I am not the author of this package, so I cannot say for sure whether it might cause any unforseen effects.

**Comment by delphinebugner** [comment]
In fact, **we do not _need_** to call codegen babel plugin in test env; it can work with the workaround above, but should not it be better if it was not called at all? 

### The second potential way to fix 
There is a babel option `disableStaticViewConfigsCodegen` for react-native-babel-preset (see https://github.com/facebook/react-native/blob/6fbf042d937d9c073fd7c26aa70807ddf6c9f98a/packages/react-native-babel-preset/src/configs/main.js#L59) 

So with this setup, test passes too, without the maping JS <-> TS for webiew!

in babel.config.js : 
```
module.exports = {
  presets: ['module:@react-native/babel-preset'],
  env: {
    test: {
      presets: [
        [
          'module:@react-native/babel-preset',
          {
            disableStaticViewConfigsCodegen: true, // ✅ added
          },
        ],
      ],
    },
  },
``` 

### Next steps

I don't know if this should be merged somewhere or expanded - @dmytrorykun as author of https://github.com/facebook/react-native/pull/38227 introducing babel plugin codegen, do you have an advice on this?

**Comment by delphinebugner** [comment]
One day one solution: you can also force the resolution in test env to be the same as in metro - i.e taking "react-native" entry point before "main" for the lib (cf https://metrobundler.dev/docs/configuration/#resolvermainfields)

And then it works fine, as react-native points to index.ts in package.json thanks to https://github.com/react-native-webview/react-native-webview/pull/3209

```javascript
// resolver.js - see https://jestjs.io/docs/configuration#resolver-string
module.exports = (path, options) => {
  // Call the defaultResolver, so we leverage its cache, error handling, etc.
  return options.defaultResolver(path, {
    ...options,
    packageFilter: pkg => {
      return {
        ...pkg,
        main: pkg['react-native'] || pkg.main, // note: don't try to add 'browser' here, it makes babel break
      };
    },
  });
};

// jest.config: add in module.exports
resolver: '<rootDir>/src/jest/resolver.js',**
```

**Comment by hssdiv** [comment]
had that issue when building app locally after migrating to expo-v50
needed to add "/src"

import { WebView } from 'react-native-webview/src';

**Comment by dmytrorykun** [comment]
@UNIDY2002  I believe the underlying problem is that `react-native-webview` still uses `metro-react-native-babel-preset`. This dependency [has been renamed](https://reactnative.dev/blog/2023/12/06/0.73-debugging-improvements-stable-symlinks#babel-package-renames) to `@react-native/babel-preset`. The new dependency contains `@react-native/babel-plugin-codegen` that is responsible for generating view configs. And missing view configs will give this error:
```
XXX/node_modules/react-native-webview/lib/RNCWebViewNativeComponent.js: Could not find component config for native component
```

Please replace `metro-react-native-babel-preset` with `@react-native/babel-preset` (version ^0.73.20) here: https://github.com/react-native-webview/react-native-webview/blob/master/package.json#L62
and here: https://github.com/react-native-webview/react-native-webview/blob/master/babel.config.js#L6-L9

cc @delphinebugner

**Comment by dmytrorykun** [comment]
@UNIDY2002 I forgot the important part. You'll have to publish a new version of the package that is built using  `@react-native/babel-preset` to address the issue.

**Comment by UNIDY2002** [comment]
> Please replace `metro-react-native-babel-preset` with `@react-native/babel-preset` (version ^0.73.20) here: https://github.com/react-native-webview/react-native-webview/blob/master/package.json#L62 and here: https://github.com/react-native-webview/react-native-webview/blob/master/babel.config.js#L6-L9
> 
> I forgot the important part. You'll have to publish a new version of the package that is built using `@react-native/babel-preset` to address the issue.

I'm not so sure about the solution :thinking: As far as I know, this package is built with tsc, rather than babel, so editing `babel.config.js` might not influence the building process. (On the other hand, it seems that `metro-react-native-babel-preset` and `babel.config.js` are relevant to building the example app.)

Do correct me if I misunderstood anything :)

**Comment by hwekim** [comment]
> I still face the issue on iOS, even after moving to `v13.6.3`

@UNIDY2002 I am also getting same error from iOS with RN version 0.73.4

**Comment by o-alexandrov** [comment]
Just fyi, there's no issue when either running this locally or building for production, using:
- expo `50.0.8`
- react-native `0.73.4`
- react-native-webview `13.6.4`

Maybe, it's time to check whether the issue still exists for you @harrymash2006 ?

**Comment by nitzanashi** [comment]
I could still reproduce it on RN `0.73.4` and RNWV `13.6.4`

**Comment by evgenyshenets91** [comment]
so I found the root cause for me. After creating fresh expo project I make it work. expo 50.0.8 and rn-webview: 13.6.4.
Problem were in metro.config.js in resolvers object.

**Comment by o-alexandrov** [comment]
what Evgeny mentions is probably this part in a metro's config (what I mentioned as working for me locally and in production):
- [metro's docs on unstable_enablePackageExports](https://metrobundler.dev/docs/configuration/#unstable_enablepackageexports-experimental)

```
resolver: {
  unstable_enablePackageExports: true,
},
  ```

**Comment by olawalejuwonm** [comment]
Please i'm still facing this iisue with     "react-native": "0.73.4",     "expo": "^50.0.7",    "jest": "^29.3.1",
    "jest-expo": "~50.0.3",

**Comment by vlimag** [comment]
Im also facing same issue, tried all suggestions in this thread, not lucky.
- "react-native": "0.73.4",
- "expo": "~50.0.11",
- "react-native-webview": "13.6.4",

**Comment by evgenyshenets** [comment]
Share your metro config

**Comment by vlimag** [comment]
yeah realized the issue was due changes in metro.config that came from previous expo project.
keeping it clean (as default) fixed. thanks
