### ISSUE TITLE
The following build commands failed:   CompileC com.apple.compilers.llvm.clang.1_0.compiler (in target 'react-native-webview' from project 'Pods').    'react/utils/ContextContainer.h' file not found

### ISSUE THREAD

**Issue by akCodeBrew** [react-native-webview/react-native-webview#3237]
Please help i am new in react-native , while run project after installing  webview in ios it throws an below error.

**Bug description:**

2023-11-24 13:28:35.330 xcodebuild[51973:107127009] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
2023-11-24 13:28:44.796 xcodebuild[51973:107128086]  DVTPortal: Service '<DVTPortalViewDeveloperService: 0x144e5ae10; action='viewDeveloper'>' encountered an unexpected result code from the portal ('1100')
2023-11-24 13:28:44.796 xcodebuild[51973:107128086]  DVTPortal: Error:
Error Domain=DVTPortalServiceErrorDomain Code=1100 "Your session has expired. Please log in." UserInfo={payload={
    creationTimestamp = "2023-11-24T07:58:45Z";
    httpCode = 200;
    protocolVersion = QH65B2;
    requestUrl = "https://developerservices2.apple.com/services/QH65B2/viewDeveloper.action";
    responseId = "f1a76ac4-4fd1-416c-93aa-324af834c8c9";
    resultCode = 1100;
    resultString = "Your session has expired. Please log in.";
    userLocale = "en_US";
    userString = "Your session has expired. Please log in.";
}, NSLocalizedDescription=Your session has expired. Please log in.}
** BUILD FAILED **

The following build commands failed:
        CompileC /Users/admin/Library/Developer/Xcode/DerivedData/DemoProject-blolrmezpqveeoftwazzmuuubhsl/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/react-native-webview.build/Objects-normal/arm64/RNCWebView.o /Users/admin/Documents/Rect_Projects/Express-Minds/node_modules/react-native-webview/apple/RNCWebView.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'react-native-webview' from project 'Pods')
(1 failure)

**To Reproduce:**
Here is podfile 

![Screenshot 2023-11-24 at 2 39 12 PM](https://github.com/react-native-webview/react-native-webview/assets/151915009/00418a2f-0dd4-40ea-9070-ee83a8510623)

**Expected behavior:**
I am useing react native new architechture.
I am  useing '  RCT_NEW_ARCH_ENABLED=1 pod install --repo-update ' command to install pods . After insrtalling when i run run project i throws above error. 

Below thow error in Xcode : -

![Screenshot 2023-11-24 at 2 29 58 PM](https://github.com/react-native-webview/react-native-webview/assets/151915009/9cb02671-608a-4f4d-a38e-2de2754034a1)

**Environment:**
 - OS: MacOs M1
 - OS version: Venture 13.3.1 (22E261)
 - react-native-webview version: 13.6.2

System:
  OS: macOS 13.3.1
  CPU: (8) arm64 Apple M1
  Memory: 63.52 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.16.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 9.6.7
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.07.17.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.13.0
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    API Levels:
      - "30"
      - "31"
      - "33"
      - "34"
    Build Tools:
      - 30.0.2
      - 30.0.3
      - 33.0.0
      - 34.0.0
    System Images:
      - android-34 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 14.3/14E222b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.19
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.6
    wanted: 0.72.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: true

**Comment by bilaleren** [comment]
same issue!

**Comment by partikshadubb** [comment]
> same issue!

I solve this issue by disabling new architecture in ios during pod install.
use this for disabling : -----  cd ios && RCT_NEW_ARCH_ENABLED=0 pod install

**Comment by bilaleren** [comment]
@partikshadubb Thank you, I will try
