### ISSUE TITLE
Set custom userAgent using default user agent value

### ISSUE THREAD

**Issue by Aure77** [react-native-webview/react-native-webview#3240]
**Is your feature request related to a problem? If so, Please describe.**
In my firm, mobile app UA start with `${AppName}/${AppVersion} (${DEVICE_MODEL}; ${OS_NAME} ${OS_VERSION}; ${DEVICE_LOCALE})`

ex:
`MyApp/1.0.0 (iPhone 15,3; iPhone OS 16.2; fr-FR)`

We want to add "original" user agent string at the end of our custom user agent. 
ex:
`MyApp/1.0.0 (iPhone 15,3; iPhone OS 16.2; fr-FR) Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X)
AppleWebKit/603.1.23 (KHTML, like Gecko)
Version/10.0 Mobile/14E5239e Safari/602.1`

(I don't want to change order, because a lot of our backend processes check that UA start with ....)

**Describe the solutions you came up with**
I see `applicationNameForUserAgent` description, but UA format is static...
`userAgent` only accept string

My suggestion is to change `userAgent` to also handle a function. Ex:
```
userAgent={(defaultUA: string) => `MyApp/1.0.0 (iPhone 15,3; iPhone OS 16.2; fr-FR) ${defaultUA}` }
```

so
`userAgent: string | (defaultUA: string) => string`

**Comment by indjeto** [comment]
I need the same functionality also.
