### ISSUE TITLE
onShouldStartLoadWithRequest Not Working on Android

### ISSUE THREAD

**Issue by MUSHTHAK2899** [react-native-webview/react-native-webview#3241]
**Environment:**
 - react-native version:0.69
 - react-native-webview version:13.6.3

**Comment by temlabs** [comment]
I'm also having this issue in 0.73

**Comment by temlabs** [comment]
I get the error:

"Invariant Violation: Failed to call into JavaScript module method WebViewMessageHandler1.onShouldStartLoadWithRequest(). Module has not 
been registered as callable. Bridgeless Mode: false. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, HMRClient, AppRegistry, ReactFabric.
          A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes"
          
          
          Fabric is enabled for me
