### ISSUE TITLE
Usage of textInteractionEnabled breaks input fields / keyboard input

### ISSUE THREAD

**Issue by sniperosx** [react-native-webview/react-native-webview#3244]
**Bug description:**
Hello, I've noticed some problem in our latest app using react-native-webview. 
As soon as I set the _textInteractionEnabled_ flag to prevent the selection of static text (as it is possible under iOS/Android native), we get the problem that input fields can no longer be used. The text field still focuses, but text input is not possible despite the keyboard. The input is basically not transferred to the text field. This is quite easy to reproduce (see code attached). 

**To Reproduce:**
I don't think a separate repository is necessary here. As it is reproducible with a simple component. 

```typescript
export default WebViewTest = ({}) => {
  
  const htmlContent = `
  <!DOCTYPE html>
  <html>
  <head>
    <title>WebView Example</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

  </head>
  <body>
    <h1>WebView Example</h1>
    <p>Enter your text below:</p>
    <input type="text" id="textInput">
  </body>
  </html>
`;

  return (
    <WebView
      originWhitelist={['*']}
      textInteractionEnabled={false}
      source={{html: htmlContent}}
      style={{flex: 1}}
    />
  );
```

**Expected behavior:**
If I activate the textInteractionEnabled, the text should not be selectable, but input fields should still be usable. The behavior should be based on the native webview settings.

**Screenshots/Videos:**
https://github.com/react-native-webview/react-native-webview/assets/738515/b6aa4b0b-6b45-4c16-8ae3-d122abd70c28

**Environment:**
 - OS: iOS 
 - OS version: iOS 17
 - react-native version: 0.71.11
 - react-native-webview version:  13.6.3

**Comment by Jamesmin90** [comment]
I am having the same issue and need help as well
