### ISSUE TITLE
Docs only - `clearCache` is marked as `Android only`

### ISSUE THREAD

**Issue by amilich** [react-native-webview/react-native-webview#3248]
Release 13.5.1 mentions fixes to `clearCache` on iOS and 13.5.0 releases it. However, this method is marked as Android only in `index.d.ts`.

Is this intentional?

**Comment by amilich** [comment]
Bumping

**Comment by foxriver76** [comment]
I guess this is why it is also optional in the type definitions, should then be fixed too.  At https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#clearcachebool it also mentions explicit behavior for iOS
