### ISSUE TITLE
The following dependencies do not satisfy the required version: project ':react-native-webview' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.0

### ISSUE THREAD

**Issue by mateuschines** [react-native-webview/react-native-webview#3252]
**Bug description: The Android Gradle plugin supports only kotlin-android-extensions Gradle plugi
n version 1.6.20 and higher.
The following dependencies do not satisfy the required version:
project ':react-native-webview' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.0**

I need to use a lib that uses kotlin plugins

My build.gradle
kotlin_version = '1.7.21'

dependecies {
classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version")
}

**Environment:**
 - OS:
 - OS version:
 - react-native version: 0.72.6
 - react-native-webview version: 13.6.3

**Comment by koreymadden** [comment]
Same issue here.

**Comment by koreymadden** [comment]
I fixed this issue by adding my Kotlin version to my gradle.properties file as well. I added ```kotlinVersion=1.8.10``` but try with whatever version you are using.

**Comment by mateuschines** [comment]
This problem has not been resolved, I have already sent corrections to try to correct it, and the lib community does not accept the changes.

I changed the variable ReactNativeWebView_kotlinVersion=1.6.20 in gradle.properties
and corrected my error, but the lib owners do not accept the change!
Maybe I'm wrong, but it fixed my problem, however, it is not legal to change files within node modules. 🤕
