### ISSUE TITLE
Error on iOS devices due to sharedCookiesEnabled prop doesn`t work: Infinite loop on render.

### ISSUE THREAD

**Issue by juan-martin-ts** [react-native-webview/react-native-webview#3264]
*Bug description:*
Hello guys,
I have an error only on iOS devices because the third party's cookies don't work. I think prop `sharedCookiesEnabled` doesn't work.

I have tried the following things but they didn't work:
- Put this [link](https://www.whatismybrowser.com/detect/are-third-party-cookies-enabled) inside a webview
This website shows if third party cookies is enabled or not. On iOS is always shown 'No', but on Android devices is shown 'Yes'.
If you change `sharedCookiesEnabled` between true or false, it doesn't change.
- I have applied a NSCrossWebsiteTrackingUsageDescription on Info.plist
- I have changed the NSCrossWebsiteTrackingUsageDescription on the app settings between true or false.

Anyway, my main problem is as I'm working with microstrategy demo dashboard, when the html has been rendered, the webview is stuck on a loop due to this prop being broken.
I know it is because of that prop because in Chrome and android devices is working fine.

*To Reproduce:*
```
<WebView
    originWhitelist={['*']}
    source={{
      uri: 'https://www.whatismybrowser.com/detect/are-third-party-cookies-enabled',
    }}
    style={styles.webview}
    javaScriptEnabled
    thirdPartyCookiesEnabled={true}
    sharedCookiesEnabled={true}
 />
```
*Expected behavior:*
See the webpage on the app with '*Yes*' as a result of third-party cookies enabled on iOS devices.

*Environment:*
 - OS: iOS
 - OS version: 17.1
 - react-native version: ^0.72.6
 - react-native-webview version: ^13.6.2

I appreciate any help.
Thank you!

**Comment by juan-martin-ts** [comment]
Hi guys, any help?

**Comment by farazahmed** [comment]
i am facing the same issue since 6 months but no solution provided tested on 13.7.1 version.

**Comment by filmic** [comment]
`sharedCookiesEnabled` property has nothing to do with Third-Party Cookies.

It is needed for iOS 7 or older where cookies would have been stored in `NSHTTPCookieStorage` and `sharedCookiesEnabled` must be set on webviews to ensure access to them.

**Comment by juan-martin-ts** [comment]
So what's going on? Why I could see this website with "Yes" (as third-party-cookies enabled)?
I don't understand it..
