### ISSUE TITLE
make shouldInterceptRequest available for react native

### ISSUE THREAD

**Issue by Fuzzyma** [react-native-webview/react-native-webview#3265]
**Is your feature request related to a problem? If so, Please describe.**

Unfortunately injecting JS into frames is not possible on Android right now.
The hack that came up in the discussion was, to use shouldInterceptRequest as a workaround.
However, this is a native method and there is directly on the react side

**Describe the solutions you came up with**

It would be cool to be able to do something like this:

```tsx
<WebView
  shouldInterceptRequest={onRequest}
/>
```

**Additional context**

Ideally, we are able to return a custom response when intercepting

**Comment by rschoenbichler** [comment]
+1
