### ISSUE TITLE
WebView PHPSESSID cookie not working correctly on iOS

### ISSUE THREAD

**Issue by karel-suchomel-ed** [react-native-webview/react-native-webview#3267]
Hello, my application has a shared session between the app and page in WebView through the PHPSESSID cookie. In the app, I retrieve an access token, that has value for this cookie encoded in it. I use [react-native-cookie](https://github.com/react-native-cookies/cookies) package for managing this cookie.
After I set the cookie and load the WebView, on the initial page load the session is still not working, but after I redirect it starts working correctly. Do you have any idea, what can be the problem?

Also, it works when I hard-code a WebView reload after 500ms after load, but it is not a good solution.

I tried combining it with the headers attribute in source prop, where I also passed the PHPSESSID in the Cookie header and it works even strangely. The session is there after the initial page load, but after I redirect it doesn't work and after I redirect again, it works again :D 

Any suggestions are welcome.

I call this method after retrieving the access token after app startup if the user is already logged in or after login.

```
export async function setSessionCookie(token: AccessToken): Promise<Cookie | undefined> {
  const cookie = getCookieFromToken(token)
  if (cookie) {
    const country = getStoredCountry()
    const url = getStoreURL(country)
    await CookieManager.set(
      url,
      {
        name: 'PHPSESSID',
        value: cookie.sub
      },
      useWebKit
    )
    const cookies = await CookieManager.get(url, useWebKit)
    return cookies.PHPSESSID
  }

  return undefined
}
```

Then this is the webview.

```
const Example = ({source}: Props) => {
  const [isReady, setIsReady] = useState(false)
  const [currentURI, setCurrentURI] = useState(source.uri)
  const [cookieHeader, setCookieHeader] = useState('')
  const webViewRef = useRef<WebView>(null)
  const newSource = {
    ...source,
    uri: currentURI,
    headers: {
      Cookie: cookieHeader
    }
  }

  useFocusEffect(
    useCallback(() => {
      const getCookieHeader = async () => {
        const token = getUserAccessToken()
        if (token) {
          const cookie = await setSessionCookie(token)
          const cookiesString = cookie ? `${cookie.name}=${cookie.value}` : ''
          setCookieHeader(cookiesString)
        }
        setIsReady(true)
      }
      getCookieHeader()
      webViewRef?.current?.reload()
      return () => {
        setIsReady(false)
      }
    }, [])
  )

  if (!isReady) {
    return false
  }

  return (
    <Browser
      ref={webViewRef}
      source={newSource}
      applicationNameForUserAgent={APPLICATION_NAME}
      allowsBackForwardNavigationGestures
      sharedCookiesEnabled
      pullToRefreshEnabled
      textZoom={100}
      decelerationRate="normal"
      scalesPageToFit={false}
      setBuiltInZoomControls={false}
      autoManageStatusBarEnabled={false}
      {...otherProps}
    />
  )
}
```

**Environment:**
 - OS: iOS
 - OS version: 17.1.2
 - react-native version: 0.71.8
 - react-native-webview version: 13.6.8

**Comment by tmKnight01** [comment]
i  met the same problem , how do you resolved it ?  thanks your help
