### ISSUE TITLE
Microsoft login cookies Android vs iOS

### ISSUE THREAD

**Issue by rklomp** [react-native-webview/react-native-webview#3274]
**Bug description:**
Share cookies between webview and fetch under iOS is not working properly. Under android I dont have any issues and it is working as expected.

I have a webview to allow users to authenticate to microsoft online and after that use the same cookies to fetch data using axios.

Simplified my application looks like this
```js
    const [isMicrosoftLoggedIn, setIsMicrosoftLoggedIn] = useState(false);

    if (!isMicrosoftLoggedIn) {
        return <LoginWebview setIsMicrosoftLoggedIn={setIsMicrosoftLoggedIn} />;
    }

    return <MainScreen />;
```

```js
export default function LoginWebview({setIsMicrosoftLoggedIn}) {
    const [display, setDisplay] = useState(false);

    async function onLoad(event) {
        console.log("WebView onLoad:", event.nativeEvent.url);
       
        if (event.nativeEvent.url.startsWith(myappurl)) {
            setIsMicrosoftLoggedIn(true);
            setDisplay(false);
        } else {
            setDisplay(true);
        }
    }

    return (
        <Layout style={{ flex: 1 }}>
            <LoadingScreen
                text={"Checking Login Status..."}
                style={{ display: display ? "none" : "block" }}
            />
            <View style={{ flex: 1, display: display ? "block" : "none" }}>
                <WebView
                    source={{ uri: myappurl }}
                    userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/119.0.2151.97"
                    sharedCookiesEnabled={true}
                    thirdPartyCookiesEnabled={true}
                    onLoad={(event) => {
                        onLoad(event);
                    }}
                />
            </View>
        </Layout>
    );
}
```

In my MainScreen I use `axios.get` to fetch data.
On android this works. On iOS I get a redirect back to login.microsoftonline.com because of incorrect cookies.

If I remove my app and reinstall on the first time it will work properly. Killing the app and restarting will break it. The webview will have the correct cookies and pass the microsoft login and redirect back to `myappurl`, but the axios request will not have the correct cookies and will redirect back to login.microsoftonline.com.

I found several other similar issues, but no solution yet.
Any idea what could cause this and how to solve?

**To Reproduce:**

Should be reproducible with code above.

**Expected behavior:**

iOS and Android working the same.

**Screenshots/Videos:**

**Environment:**
 - OS: iOS using Expo
 - OS version:
 - react-native version: 0.72.6
 - react-native-webview version: 13.2.2

**Comment by rklomp** [comment]
Comparing `CookieManager.getAll()` to `CookieManager.getAll(true)` it turns out that for some reason not all WK cookies are synced to NS.  Cant figure out the reason for the cookies not syncing.

As a workaround I have updated my `onLoad` to sync the missing cookies. Not the nicest solution, but it works.
``` js
    async function onLoad(event) {
        console.log("WebView onLoad:", event.nativeEvent.url);

        if (event.nativeEvent.url.startsWith(myappurl)) {
            setDisplay(false);

            // Fix for ios cookie sync.
            if (Platform.OS === "ios") {
                let [nsCookies, wkCookies] = await Promise.all([
                    CookieManager.getAll(),
                    CookieManager.getAll(true),
                ]);

                let onlyInWK = cookieOnlyInLeft(wkCookies, nsCookies);

                for (i = 0; i < onlyInWK.length; i++) {
                    let element = onlyInWK[i];

                    await CookieManager.set(
                        "https://" + element.domain.replace(/^\.+/, ""),
                        element
                    );
                }
            }

            setIsMicrosoftLoggedIn(true);
        } else {
            setDisplay(true);
        }
    }
```

**Comment by rklomp** [comment]
Still using the workaround

**Comment by caralin3** [comment]
@rklomp What does your `cookieOnlyInLeft` function look like?

**Comment by rklomp** [comment]
Are you experiencing the same issue?
Bellw is my code. Let me know if this helps :)

```ts
import { type Cookie } from '@react-native-cookies/cookies'

export const isSameCookie = (a: Cookie, b: Cookie): boolean =>
  a.domain === b.domain &&
  a.name === b.name &&
  a.value === b.value &&
  a.expires === b.expires

// Get items that only occur in the left array,
// using the compareFunction to determine equality.
export const onlyInLeft = <T>(
  left: T[],
  right: T[],
  compareFunction: (a: T, b: T) => boolean
): T[] =>
  left.filter(
    (leftValue) =>
      !right.some((rightValue) => compareFunction(leftValue, rightValue))
  )

export function cookieOnlyInLeft(
  left: Record<string, Cookie>,
  right: Record<string, Cookie>
): Cookie[] {
  return onlyInLeft(Object.values(left), Object.values(right), isSameCookie)
}
```

**Comment by rklomp** [comment]
Still using this workaround

**Comment by rklomp** [comment]
Still the same...

**Comment by D-Lav** [comment]
Hey, I've experienced a similar issue in my react native app. While it is not the exact same issue as described here (incorrect cookie) it might be related, as it has to do with iOS handling cookies different than android. The android version works fine, but in the ios app, when I authenticate with a server and retrieve a session cookie, the following get request would fail due to the cookie not being sent properly. 

I still haven't found out what exactly is causing the issue, as when debugging the axios request and errors, I can clearly see that the cookie is part of the header. But for some reason the server responds to it as if it's handling an anonymous user request. After debugging further, I've found out that this happens only to the first request, right after authenticating. Therefore my workaround is to catch the failed request and send it again. After that, all requests are handled as expected. I don't understand why this helps, it is the same request with the same cookie, but it helps. 

I've unsuccessfully tried other things like setting timeouts before making the requests, setting the cookie manually in the cookie manager, sending the cookie manually in every request, using fetch instead of axios, changing same-site cookie settings in the server, changing cors settings.

**Comment by rklomp** [comment]
Keep open

**Comment by ravensroom** [comment]
@rklomp https://github.com/react-native-webview/react-native-webview/issues/3457 does this solve your problem?

**Comment by anshif10** [comment]
have same issue in ios

**Comment by rklomp** [comment]
> @rklomp #3457 does this solve your problem?

Thanks for pointing this out. I removed my workaround and it seems that #3470 indeed fixed this issue for me.
