### ISSUE TITLE
Loading for more than a minute for few urls only on iOS devices

### ISSUE THREAD

**Issue by anuragdixit1** [react-native-webview/react-native-webview#3282]
**Bug description:**
I have integrated react-native-webview in one of my project and using startInLoadingState which is behaving differently on Android and iOS devices. There are some urls for which it is loading for one or more than one minute only on iOS devices but it is loading for 2-3 seconds on android devices. I have tried to use custom loader and used onLoadEnd prop. In this case, the webpage is loaded but onLoadEnd is triggering after few min.

**To Reproduce:**
Try to use this:
 <WebView
    source={{uri: "---link---"}}
    originWhitelist={['*']}
    javaScriptEnabled={true}
    startInLoadingState={true}
  />
It will load in 3-4 seconds on Android but will take 1-2 min. on iOS devices.
**Expected behavior:**
It should behave similar on both android and iOS devices.

**Screenshots/Videos:**
<img width="449" alt="Screenshot 2024-01-10 at 5 52 48 PM" src="https://github.com/react-native-webview/react-native-webview/assets/123146093/d1048990-88fb-4aad-8f56-e3f7c1e9d01f">

**Environment:**
 - OS: iOS
 - OS version: 13.5.1
 - react-native version: 0.69.11
 - react-native-webview version: 13.2.2

**Comment by Slapbox** [comment]
I'm uncertain about the exact nature of the bug we're seeing but it seems possibly related. Our Webview contents seem not to load on iOS, but it works fine on Android and our code hasn't changed, only our React Native and React Native Webview versions.

**Comment by it-fh** [comment]
![image](https://github.com/user-attachments/assets/8f349aa5-842d-4894-8cfc-9110b343268c)
Same, I got a network error, I tried to fix it and it worked
