### ISSUE TITLE
iOS: UI issues after upgrade to iOS 17.2

### ISSUE THREAD

**Issue by sruthiramakrishnan-svmx** [react-native-webview/react-native-webview#3293]
Summary:
We are facing UI isssues, specifically in spacing between elements after upgrade to iOS 17.2. Issue was not happening till iOS 17.0. We are seeing additional spacing between elements now. Please see below screenshot for details

Screenshots:
<img width="1345" alt="Screenshot 2024-01-17 at 12 05 16 PM" src="https://github.com/react-native-webview/react-native-webview/assets/22495920/50639b17-a744-4458-8daf-a057964c737a">

**Environment:**
 - OS: iOS
 - OS version: 17.2
 - react-native version: 0.71.15
 - react-native-webview version: 13.3.1 (same issue seen on latest 13.6.4 as well)

**Comment by ahsanbhatti98** [comment]
Facing similar issue in ios 17+

**Comment by ahsanbhatti98** [comment]
still searching for solutions
