### ISSUE TITLE
Proxy logic in a Webview

### ISSUE THREAD

**Issue by nhhynd** [react-native-webview/react-native-webview#3294]
Hi,

I do not believe this feature is added yet, therefore I post this in the proposal board here. So please consider it a proposal too for something that would be neat if it is not existing yet.

Anyway,

I have not been able to find any way, by which I can achieve this in the webview (or in React Native in general). And there does not seem to be any post on it yet, so I hope it is okay that I ask (and/or suggest):

Is it possible to add any sort of http proxy to a webview? What I want to achieve is to route the webview browsing traffic through a proxy (that is running Privoxy), which can strip the HTTP content in the communication for the tracking scripts and ads.
I can do it on a full-fledged desktop browser, and through a global setting on the iphone which routes all traffic on the iphone for all apps through the proxy (the IP and port number of the proxy can be set in network settings on the iPhone).... That is not userfriendly though, since it needs to be done outside the app manually by the user, and the bandwidth usage skyrockets on the proxy compared to if only the webview in my app routed it.

Is it possible to have just the webview achieve this? I cannot seem to get access to any sort of underlying http client or anything in it, so I cannot do something hacky either :/

Hope to hear from you, whether it is possible to setup any proxy on the webview in any way :) Thanks!

Same issue ticket - 
https://github.com/react-native-webview/react-native-webview/issues/115

Use a HTTP Proxy with WkWebView - 
https://forums.developer.apple.com/forums/thread/110312?answerId=769001022#769001022

iOS 17 Proxy Configuration - 
https://developer.apple.com/documentation/network/proxyconfiguration

**Comment by nhhynd** [comment]
> is there any resolution on this ?

```javascript
      <WebView
        source={{
          uri: 'https://example.com',
          proxy: {
            uri: 'proxy-server.example.com',
            port: '3128',
            excludedDomain: 'excluded.target-domain.com',
          },
        }}
        basicAuthCredential={{
          username: 'username',
          password: 'password',
        }}
``` 

RNCWebViewManagerImpl.kt
```kotlin
...
                if (source.hasKey("headers")) {
                    if (newArch) {
                      val headerArray = source.getArray("headers");
                      for (header in headerArray!!.toArrayList()) {
...

add below line 
==========================================================

                if (source.hasKey("proxy")) {
                  val proxy = source.getMap("proxy")
                  val proxyUri = proxy!!.getString("uri");
                  val proxyPort = proxy!!.getString("port");
                  val proxyExcludedDomain = proxy!!.getString("excludedDomain")!!;

                  if (WebViewFeature.isFeatureSupported(WebViewFeature.PROXY_OVERRIDE)) {
                    val pcInstance = ProxyController.getInstance()
                    pcInstance?.let {
                      val pxConfig = ProxyConfig.Builder()
                        .addProxyRule(proxyUri + ":" + proxyPort)
                        .addBypassRule(proxyExcludedDomain)
                        .build()
                      it.setProxyOverride(pxConfig, object : Executor {
                        override fun execute(command: Runnable?) {
                          command?.run {
                          }
                        }
                      }) {
                        Log.e(TAG, "Failed to set proxy")
                      }
                    }
                  }
                }

==========================================================

...
                view.loadUrl(url!!, headerMap)
                return
``` 

RNCWebViewImpl.m
```objective-c
...
      [script appendString:@"})();\n"];

      WKUserScript* cookieInScript = [[WKUserScript alloc] initWithSource:script
                                                            injectionTime:WKUserScriptInjectionTimeAtDocumentStart
                                                         forMainFrameOnly:YES];
      [wkWebViewConfig.userContentController addUserScript:cookieInScript];
    }
  }
...

add below line
=============================================================
  NSString *proxyUri = [RCTConvert NSString:_source[@"proxy"][@"uri"]];
  NSString *proxyPort = [RCTConvert NSString:_source[@"proxy"][@"port"]];
  NSString *proxyExcludedDomain = [RCTConvert NSString:_source[@"proxy"][@"excludedDomain"]];
  NSString *username = [_basicAuthCredential valueForKey:@"username"];
  NSString *password = [_basicAuthCredential valueForKey:@"password"];

  const char *proxyUriCStr = [proxyUri UTF8String];
  const char *proxyPortCStr = [proxyPort UTF8String];
  const char *proxyExcludedDomainCStr = [proxyExcludedDomain UTF8String];
  const char *usernameStr = [username UTF8String];
  const char *passwordStr = [password UTF8String];

  if(proxyUri) {
    if (@available(iOS 17.0, *)) {
      nw_endpoint_t endpoint = nw_endpoint_create_host(proxyUriCStr, proxyPortCStr);
      nw_proxy_config_t proxyConfig = nw_proxy_config_create_http_connect(endpoint, nil);

      nw_proxy_config_add_excluded_domain(proxyConfig, proxyExcludedDomainCStr);

      if (username && password) {
        nw_proxy_config_set_username_and_password(proxyConfig, usernameStr, passwordStr);
      }

      wkWebViewConfig.websiteDataStore.proxyConfigurations = @[ proxyConfig ];
    } else {
      NSLog(@"The version must be higher than 17.0");
    }
  }
=============================================================
  
...
  if(_messagingEnabled){
    if (self.postMessageScript){
      [wkWebViewConfig.userContentController addScriptMessageHandler:[[RNCWeakScriptMessageDelegate alloc] initWithDelegate:self]
...
```

**Comment by seriousrhino** [comment]
Hey @nhhynd  thnx for this so did you rebuilt the WebView again, if so how are you using this in production ?

**Comment by sce9sc** [comment]
Is seem to work Thank you very much . The only thing is that I can pass the properties

```
 NSString *proxyUri = [RCTConvert NSString:_source[@"proxy"][@"uri"]];
  NSString *proxyPort = [RCTConvert NSString:_source[@"proxy"][@"port"]];
  NSString *proxyExcludedDomain = [RCTConvert NSString:_source[@"proxy"][@"excludedDomain"]];
```
source only contains the uri the rest vanish.

**Comment by nhhynd** [comment]
> It seem to work Thank you very much . The only thing is that I cannot pass the properties
> 
> ```
>  NSString *proxyUri = [RCTConvert NSString:_source[@"proxy"][@"uri"]];
>   NSString *proxyPort = [RCTConvert NSString:_source[@"proxy"][@"port"]];
>   NSString *proxyExcludedDomain = [RCTConvert NSString:_source[@"proxy"][@"excludedDomain"]];
> ```
> 
> source only contains the uri the rest vanish.

I modified the original post to distinguish between http and https.

**Comment by derlaft** [comment]
If you want to use the patches posted here, be aware of some pitfalls discovered after hours of debugging:

* on Android
    - `ProxyController` manages proxy configuration **for the current process**. If you have multiple instances of `<WebView>` you have to keep that in mind.
    - `setProxyOverride` sets the proxy. if you need to remove it, you need to call [clearProxyOverride](https://developer.android.com/reference/androidx/webkit/ProxyController#clearProxyOverride(java.util.concurrent.Executor,java.lang.Runnable))
    - if you paste it as it (after `source.hasKey("headers")` block), it won't work when you use it in `html` mode
* on ios
    - there was also something fun here... but I forgot

**Comment by ajubin** [comment]
Hi @derlaft , thanks for the fix  ❤️ 

I'm currently implementing it on ios and android, I will report issue and fix here in case of any
