### ISSUE TITLE
Scrolling not working when webview inside scrollview and user try to scroll scrollview pressing webview in android.

### ISSUE THREAD

**Issue by krunalinfynno** [react-native-webview/react-native-webview#3299]
I have implemented Webview to display html inside its parent scrollview but when i try to scroll down parent scrollview after touching the webview it does not scrolls the scrollview this only happens in android. 

i have attached video here,

https://github.com/react-native-webview/react-native-webview/assets/82360200/28b7eebd-4251-4929-bf5f-133de08e3f80

**Comment by Shivangigupta01** [comment]
what is the fix for this issue? I am encountering the same

**Comment by suwu150** [comment]
Any updates? @krunalinfynno @Shivangigupta01

**Comment by n-kumari** [comment]
Try setting `nestedScrollEnabled ` to false.

**Comment by pd185197** [comment]
What was the fix for it? @krunalinfynno
