### ISSUE TITLE
Webview not opening link - only on Android released versions

### ISSUE THREAD

**Issue by ancaaivanoaei** [react-native-webview/react-native-webview#3303]
**Bug description:**
I am encountering this strange issue, where the WebView is not opening the given link but only on Android released versions. (it works as expected in the debug and both debug & release for iOS). Instead, the WebView is displaying this error telling us something about the SSL certificate.

I already tried updating the react-native (to 0.70.0) & react-native-webview(13.6.4), and patching the package with the _handler.proceed()_ fix I have read about on other issues. In this case, the error is not longer displayed but instead the WebView remains in infinite loading (again only in Android, and only for the released .apk).

I must also mention that the WebView behaviour in the released .apk works perfectly fine on an emulator, and it opens the given link. So it also only reproduces on actual devices.

**Screenshots/Videos:**
![Screenshot_20240126-122051](https://github.com/react-native-webview/react-native-webview/assets/130561486/5e878cdd-ff27-4d3a-82ef-16dcc44cfce5)

**Environment:**
 - OS: Android
 - OS version: 11 (API 33)
 - react-native version: 0.69.0
 - react-native-webview version: 11.18.2

**Comment by hamdij0maa** [comment]
+1

**Comment by ceconcarlsen** [comment]
have u tried `incognito` prop?
