### ISSUE TITLE
[Android / New Arch] `injectJavaScript` and presumably other commands get executed twice

### ISSUE THREAD

**Issue by birdofpreyru** [react-native-webview/react-native-webview#3305]
**Bug description:**

I found that `injectJavaScript` code gets executed twice on Android with the New Arch. It happens because once it gets executed here (as a consequence of that command processing pattern):
https://github.com/react-native-webview/react-native-webview/blob/6960a1903c3c32e1e77be11e6370f1c384ed7ee4/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManagerImpl.kt#L334

then another time it gets executed here:
https://github.com/react-native-webview/react-native-webview/blob/6960a1903c3c32e1e77be11e6370f1c384ed7ee4/android/src/newarch/com/reactnativecommunity/webview/RNCWebViewManager.java#L444-L447

I guess, similar error might be there with other actions handled via that commands pattern.

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS:
 - OS version:
 - react-native version:
 - react-native-webview version:

**Comment by birdofpreyru** [comment]
@Titozzz was totally wrong here &mdash; of course all these methods get called directly with the new arch; and I see no reason why the shared implementation, as it is implemented, could shadow these.
https://github.com/react-native-webview/react-native-webview/blob/6960a1903c3c32e1e77be11e6370f1c384ed7ee4/android/src/newarch/com/reactnativecommunity/webview/RNCWebViewManager.java#L423-L450

**Comment by 17Amir17** [comment]
Just ran into this today

**Comment by birdofpreyru** [comment]
@17Amir17 you may consider to temporarily depend on my fork of the library, https://www.npmjs.com/package/@dr.pogodin/react-native-webview, which has this one and a few other issues fixed, as my PRs into the upstream version are pending the merge for a while now.

**Comment by 17Amir17** [comment]
Unfortunately I use this library as a peer dependency, so I'll have work around this in my case :(

**Comment by Nantris** [comment]
Any progress on this? I see @birdofpreyru submitted a PR to fix this.

**Comment by birdofpreyru** [comment]
:unamused:

**Comment by desonyuan** [comment]
+1

**Comment by Nantris** [comment]
New architecture is due to be the default in under 6 months now. Is there a plan to address this?

**Comment by szfdiwang** [comment]
I also encountered this problem, can anyone solve it?  Dont close it!

**Comment by birdofpreyru** [comment]
@szfdiwang it is solved in my fork &mdash; [react-native-webview](https://www.npmjs.com/package/@dr.pogodin/react-native-webview), which is currently on par with the upstream v13.10.3. Somehow the upstream maintainers never bothered to merge in my PR fixing this issue, nor a few others fixing other stuff, thus I aim to maintain and use my own fork ~with blackjack and hookers~ in the foreseeable future :shrug:.

**Comment by szfdiwang** [comment]
Although this solves the issue of executing twice on Android, I found that injectJavaScript has no response on iOS. Can you help me look at this issue again?

> @szfdiwang it is solved in my fork — [react-native-webview](https://www.npmjs.com/package/@dr.pogodin/react-native-webview), which is currently on par with the upstream v13.10.3. Somehow the upstream maintainers never bothered to merge in my PR fixing this issue, nor a few others fixing other stuff, thus I aim to maintain and use my own fork ~with blackjack and hookers~ in the foreseeable future 🤷.

https://github.com/react-native-webview/react-native-webview/issues/3305#issuecomment-2191958738

**Comment by birdofpreyru** [comment]
@szfdiwang can you be more specific on what do you do, and how exactly does it fail? Because, in principle, my own projects relying on [my fork of `react-native-webview`](https://www.npmjs.com/package/@dr.pogodin/react-native-webview) use `injectJavaScript` actively for their core functionality, and I saw no problems with it, not on iOS with new RN architecture (nor with the old one, I believe, although less sure).

**Comment by Eclipses-Saros** [comment]
didn't experienced this bug when I was using RN 0.72 or below. might be React Native bug.

I can't figure out detail, but I can debug it. as we call WebView ref methods, `Commands` will be called, which is **codegenNativeCommands** to call native methods.
```js
useImperativeHandle(
  ref,
  () => ({
    goForward: () =>
      webViewRef.current && Commands.goForward(webViewRef.current),
    goBack: () => webViewRef.current && Commands.goBack(webViewRef.current),
    reload: () => {
      setViewState('LOADING');
      if (webViewRef.current) {
        Commands.reload(webViewRef.current);
      }
    },
    stopLoading: () =>
      webViewRef.current && Commands.stopLoading(webViewRef.current),
    postMessage: (data: string) =>
      webViewRef.current && Commands.postMessage(webViewRef.current, data),
    injectJavaScript: (data: string) =>
      webViewRef.current &&
      Commands.injectJavaScript(webViewRef.current, data),
    requestFocus: () =>
      webViewRef.current && Commands.requestFocus(webViewRef.current),
    clearFormData: () =>
      webViewRef.current && Commands.clearFormData(webViewRef.current),
    clearCache: (includeDiskFiles: boolean) =>
      webViewRef.current &&
      Commands.clearCache(webViewRef.current, includeDiskFiles),
    clearHistory: () =>
      webViewRef.current && Commands.clearHistory(webViewRef.current),
  }),
  [setViewState, webViewRef]
);
```

```js
export const Commands = codegenNativeCommands<NativeCommands>({
  supportedCommands: [
    'goBack',
    'goForward',
    'reload',
    'stopLoading',
    'injectJavaScript',
    'requestFocus',
    'postMessage',
    'loadUrl',
    'clearFormData',
    'clearCache',
    'clearHistory',
  ],
});
```

as we call Commands method, RN sends signal and *receiveCommand* handles it.
```java
@Override
public void receiveCommand(@NonNull RNCWebViewWrapper reactWebView, String commandId, @Nullable ReadableArray args) {
    mRNCWebViewManagerImpl.receiveCommand(reactWebView, commandId, args);
    super.receiveCommand(reactWebView, commandId, args);
}
```

```kt
fun receiveCommand(viewWrapper: RNCWebViewWrapper, commandId: String, args: ReadableArray) {
  val webView = viewWrapper.webView
  when (commandId) {
    "goBack" -> webView.goBack()
    "goForward" -> webView.goForward()
    "reload" -> webView.reload()
    "stopLoading" -> webView.stopLoading()
    "postMessage" -> try {
      val eventInitDict = JSONObject()
      eventInitDict.put("data", args.getString(0))
      webView.evaluateJavascriptWithFallback(
        "(function () {" +
          "var event;" +
          "var data = " + eventInitDict.toString() + ";" +
          "try {" +
          "event = new MessageEvent('message', data);" +
          "} catch (e) {" +
          "event = document.createEvent('MessageEvent');" +
          "event.initMessageEvent('message', true, true, data.data, data.origin, data.lastEventId, data.source);" +
          "}" +
          "document.dispatchEvent(event);" +
          "})();"
      )
    } catch (e: JSONException) {
      throw RuntimeException(e)
    }
    "injectJavaScript" -> webView.evaluateJavascriptWithFallback(args.getString(0))
    "loadUrl" -> {
      if (args == null) {
        throw RuntimeException("Arguments for loading an url are null!")
      }
      webView.progressChangedFilter.setWaitingForCommandLoadUrl(false)
      webView.loadUrl(args.getString(0))
    }
    "requestFocus" -> webView.requestFocus()
    "clearFormData" -> webView.clearFormData()
    "clearCache" -> {
      val includeDiskFiles = args != null && args.getBoolean(0)
      webView.clearCache(includeDiskFiles)
    }
    "clearHistory" -> webView.clearHistory()
  }
}
```

from here, we can understand the flow. *Commands sends signal -> receiveCommand handles it*. for example, if we call goBack()...

![image](https://github.com/user-attachments/assets/9de3136f-1770-4867-974e-21730e8312fd)

![image](https://github.com/user-attachments/assets/6738044d-895f-4e6f-8589-1e6c6e03f1ca)

yes this is expected, but as soon as *super.receiveCommand()* called, react native ViewManager subclass handles it and suddenly **calls goBack() again!**

![image](https://github.com/user-attachments/assets/adeab77d-ce2f-4ec2-bb47-923e26f12919)

![image](https://github.com/user-attachments/assets/090a1b7a-f74b-47ab-b4e6-e98b5b5369fb)

since I don't know much about react native ui components works (https://reactnative.dev/docs/native-components-android#3-create-the-viewmanager-subclass), the quick way fix it is just remove view.getWebView() thingy in RNCWebViewManager.java.
