### ISSUE TITLE
View config getter callback for component RNCWebView must be a function (received undefined)

### ISSUE THREAD

**Issue by Shedna** [react-native-webview/react-native-webview#3308]
**Bug description:**
Hello ! I'm facing a weird issue with `Snack` and I don't know if it's the right place to talk about it.
I've done a very concise Snack, only display a Webview using `react-native-webview`  but I'm getting a weird error: `View config getter callback for component RNCWebView must be a function (received undefined)`. I get this error with `Expo 49` and `react-native-webview 13.2.2`.

Some hints :
- It's working fine with Expo 48 and react-native-webview 11.26.0
- If I copy paste this code and execute it locally (without Snack) it's working fine in any version. So my guess is an issue with Snack only and not Expo 49 nor react-native-webview.
- The thing is I'm stuck because I'd like to use Expo Go to run the Snack on my device but since Expo 48 support is dropped on Expo Go I have no way to run the Snack on my device...

**To Reproduce:**
[Snack](https://snack.expo.dev/@shedna42/bug-report-expo)

**Screenshots
![Screenshot 2024-01-29 at 10 22 00](https://github.com/react-native-webview/react-native-webview/assets/3352224/95678b45-a8d2-499d-a285-f7bb920af83c)

**Environment:**
 - Expo 49
 - react-native-webview 13.2.2

**Comment by dmytrorykun** [comment]
Likely related to this https://github.com/react-native-webview/react-native-webview/issues/3233#issuecomment-1924115639

**Comment by valent1n0** [comment]
Facing the exact same issue, I thought after upgrading the expo/react libraries I must change some config values, but as mentioned already, it doesn't work with a simple webview.

**Comment by pc-codings** [comment]
still searching

**Comment by fsobh** [comment]
still have this issue

**Comment by ahsanbhatti98** [comment]
still facing this issue

**Comment by pratiksha3101** [comment]
still searching
