### ISSUE TITLE
Prevent URL scheme/ Universal Links loading on iOS

### ISSUE THREAD

**Issue by shubhamverma27** [react-native-webview/react-native-webview#3310]
**Bug description:**

I am using webview for in-app browser-based web transactions.
However, on iOS if the related app which has similar URL mentioned in it's URL scheme/ Universal links, it triggers up the app installed on the phone.

**To Reproduce:**

Install MakeMyTrip app on your phone.
open https://www.makemytrip.com/hotels/ in a webview on ios rn app.
Go to checkout and cancel and come back, it will open up the MakeMyTrip app.

**Expected behavior:**

The redirection to MakeMyTrip app should not happen and URL schema handling to be ignored since everything needs to happen via the webview.

**Screenshots/Videos:**

**Environment:**
 - OS:
 - OS version:
 - react-native version:
 - react-native-webview version:

**Comment by remberluyckx** [comment]
Also having this problem, anyone have a solution?

**Comment by remberluyckx** [comment]
Found a solution, you can catch when the universal link is about to get opened with onShouldStartLoadWithRequest and then instantiate a new webview with this link. This will prevent the universal link from opening the app.
