### ISSUE TITLE
Video playing on Android emulator and debug apk. But not on Release apk. Showing black screen.

### ISSUE THREAD

**Issue by ManojKrB** [react-native-webview/react-native-webview#3311]
**Bug description:**
I am streaming a CCTV footage coming from WSS type. Video is playing fine in Android emulator and also debug apk. But after trying generating a release apk and testing on real physical device, it is showing black screen. 

I implemented steps which were mentioned in issue number: 1632 and issue number: 1954. 

I added android:usesCleartextTraffic="true" in AndroidManifest.xml

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS: Mac
 - OS version: 12.7.3
 - react-native version: 0.73.2
 - react-native-webview version: 13.6.4

**Comment by hamdij0maa** [comment]
+1
