### ISSUE TITLE
Error : Tried to register two views with the same name RNCWebView in Expo

### ISSUE THREAD

**Issue by misssim29** [react-native-webview/react-native-webview#3320]
I'm using the react native expo 49 sdk version. The library I'm using only expo router and installing and using webview library without any other library, but I get the error "Tried to register two views with the name RNCWebView" and the app will turn off as soon as I turn on expo go on the device. The following image appears to be a version problem, but it won't run if I change the version to 13.2.2 or 13.7.0, as instructed below.

<img width="648" alt="스크린샷 2024-02-06 오후 6 34 24" src="https://github.com/react-native-webview/react-native-webview/assets/65381839/79677643-6181-48bf-920d-36a00c69ae5f">

**Environment:**
 - react-native version: '0.72.6'
 - react-native expo version: '~49.0.18'
 - react-native-webview version: "13.2.2"

**Comment by miteshdevg** [comment]
same to you

**Comment by YUOrz233** [comment]
The cause of my issue is that a dependency's package.json has `"react-native-webview": "^11.13.0"` configured in dependencies, while my project's package.json has `"react-native-webview": "13.3.1"` configured in dependencies. This caused the automatic dependency resolution to register two webview versions for me:

You can use the ` npm list react native webview ` command to query all dependencies that use ` react native webview `
```
├─┬ mobile-components@2.1.70-beta2
│ └── react-native-webview@11.13.0
└── react-native-webview@13.3.1
```
Solution:
Configure the following in the project's package.json:

```
"overrides": {
    "react-native-webview": "13.3.1"
  },
```
