### ISSUE TITLE
TypeError: Cannot read property 'startLoadWithResult' of null, js engine: hermes

### ISSUE THREAD

**Issue by miteshdevg** [react-native-webview/react-native-webview#3322]
I am facing issues like the above image 
it's completely working in Android but when i click on button for open web view then shows me an error in IOS only for 
It shows me after updating my Expo version 

and if i' trying to update web view version then show me different different error 
Please help me for it.
![Screenshot 2024-02-09 at 6 32 53 PM](https://github.com/react-native-webview/react-native-webview/assets/124264146/8cdf4953-5e69-4369-aa2b-e171f45ed4e0)

**Comment by miteshdevg** [comment]
webview is not working so i used web browser view

**Comment by miteshdevg** [comment]
i'm facing same issue and i don't want to use web browser please help me to resolve it .

**Comment by Mrebai** [comment]
Update react-native-webview you the latest version

**Comment by miteshdevg** [comment]
> Update react-native-webview you the latest version

no bro it's not working it's show me different error like 


`
Invariant Violation: Tried to register two views with the same name RNCWebView, js engine: hermes
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:105:15 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:150:4 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:26:18 in handleError
at node_modules/expo/build/errors/ExpoErrorManager.js:27:16 in createErrorHandler
at node_modules/expo/build/errors/ExpoErrorManager.js:32:8 in <anonymous>
at node_modules/@react-native/js-polyfills/error-guard.js:51:16 in ErrorUtils.applyWithGuard
at http://192.168.1.20:19000/index.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:null in global

Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:105:15 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:150:4 in handleException
- ... 7 more stack frames from framework internals`

**Comment by evgenyshenets91** [comment]
same for me. any solutions?

**Comment by oscadev** [comment]
No updates?

**Comment by miteshdevg** [comment]
> No updates?

I CHANGED THE VERSION OF WEBVIEW

**Comment by miteshdevg** [comment]
it's not working properly

**Comment by miteshdevg** [comment]
@oscadev , @Mrebai and @evgenyshenets91
Have you found any solution.

**Comment by ombogdan** [comment]
same problem

**Comment by rahmanharoon** [comment]
any solution for this ?

**Comment by miteshdevg** [comment]
> any solution for this ?

Can you please create build APK and after test in real device , so issue should be resolved

**Comment by kennylevi** [comment]
Any solution to this

**Comment by kennylevi** [comment]
"react-native-webview": "~13.6.3",
 
 i just fixed it, update your lib with that exactly

**Comment by patrickfabbriafya** [comment]
I had an issue with the release version and for me the solution was to include 
`const path = require('node:path'); `
in the first line of metro.config.js

**Comment by JANjana21** [comment]
> "react-native-webview": "~13.6.3",
> 
> i just fixed it, update your lib with that exactly

thank you this worked for me!
