### ISSUE TITLE
When referenced, there is no injectJavaScript method in the WebView

### ISSUE THREAD

**Issue by RedouanEJeld** [react-native-webview/react-native-webview#3329]
**Bug description:**
I am using this project for showing webview and I need a real-time communication between the RN and WebView.
I am having problems using injectJavaScript with the WebView referenced. Here is my code.

**To Reproduce:**
[StackOverflow](https://stackoverflow.com/questions/78017770/react-native-webview-at-latest-version-doesnt-have-injectjavascript-in-its-refe)

And my codebase:

```typescript
import WebView from 'react-native-webview';

const ParentView = () => {
  const ref = useRef<WebView>(null);

  const wrapperContent = `
    <body><div>some content</div></body>
  `;

  const onButtonClick = () => {
    console.log(ref.current);
    ref.current.injectJavaScript(`alert("here"); true;`);
  }

  return <View>
    <WebView
        ref={ref}
        source={{html: webViewWrapperContent}}
        style={{width: '100%', height: '100%'}}
        showsVerticalScrollIndicator={false}
        showsHorizontalScrollIndicator={false}
        scrollEnabled={false}
        originWhitelist={['*']}
        sharedCookiesEnabled={true}
        javaScriptEnabled={true}
        domStorageEnabled={true}
        injectedJavaScript={`console.log("injected")`}
        javaScriptCanOpenWindowsAutomatically={true}
        onMessage={(event) => {}}
      />
    <Button onPress={onButtonClick}></Button>
  </View>
}
```

When the button is clicked, then it prints console like this:
![image](https://github.com/react-native-webview/react-native-webview/assets/158258667/c7b96777-3319-46ef-ac3c-22f4f64434d8)

But this console correctly prints "injected". Instead it is void of injectJavaScript method, and cannot call it either.

I am on React Native 0.68.2, and React Native Webview 11.23.1, and building web in windows machine.

If this cannot work with windows, then just quickly let me know so that I can run other workarounds, as I need to build this into iOS, Android and Web (no other choice here 😞)

I tried almost everything I could find with StackOverflow and this issues. For example:
https://stackoverflow.com/questions/63812054/react-native-ref-injectjavascript-on-webview-always-undefined
https://github.com/react-native-webview/react-native-webview/issues/2706

Also, I tried putting the injectJavaScript in setTimeout. Nothing worked.
I tried using postMessage (it exists in the reference object) but it didn't worked too when I added event listener to document and window in webview srcDoc.

**Expected behavior:**
I expect the WebView to show alert so that I can do consequent things with the code.

If I need to update React Native version, then let me know what will the minimum one, as I do not want to make a huge difference to my package.json 🥲 

**Environment:**
 - OS: Windows
 - OS version: 11, Version 22H2 (OS Build 22621.525)
 - react-native version: 0.68.2
 - react-native-webview version: 11.23.1 (I tried with the latest one too)

**Comment by tonyxqing** [comment]
I've found refs are a little weird in react native where you have to wrap the referenced method in a timeout with a delay of 0ms like so,
```
useTimeout(() => {
    ref.current.injectJavaScript(...);
}, 0)
```

Not sure why this works though.
