### ISSUE TITLE
Unit test issue: Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNCWebView' could not be found

### ISSUE THREAD

**Issue by UraFIZ** [react-native-webview/react-native-webview#3333]
**Bug description:**
Hello, the problem is the following: each time I want to test a react-native-webview with @testing-library/react-native I get this error "Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNCWebView' could not be found. Verify that a module by this name is registered in the native binary." or similar about "getEnforcing".

The workaround is to keep the react-native-webview.tsx file in the __mocks__ folder but it does not help me to test my functionality correctly.

**To Reproduce:**
Just try to do this 
`
import { render } from "@testing-library/react-native";
...
render(
      <WebView
        source={{ uri: webViewProps.appUrl }}
        ref={webViewProps.webviewRef}
        onMessage={webViewProps.invoke.listener}
      />
    );
`

**Expected behavior:**
To be able to test the exact functionality of react-native-webview like renderError, renderLoading

**Screenshots/Videos:**
<img width="1231" alt="image" src="https://github.com/react-native-webview/react-native-webview/assets/31358665/bde4d75a-b3d5-4942-baa9-661a5c589557">

**Environment:**
 - OS: mac
 - OS version: Sonoma 14.3.1
 - react-native version: 0.72.4
 - react-native-webview version: 13.2.2
 - @testing-library/react-native: ^12.4.2
 - @testing-library/jest-native: "^5.4.3"

**Comment by jose920405** [comment]
+1

**Comment by RamuMakkena** [comment]
+1

**Comment by anton-patrushev** [comment]
Was able to overcome this problem with the next workaround:

Put this snippet into your `jest.setup.js` file (or put this into your spec file locally)
```js

jest.mock('react-native-webview', () => {
  const MockWebView = () => '<RNWebView />';

  return {
    __esModule: true,
    WebView: MockWebView,
    default: MockWebView,
  };
});

```

**Comment by compwron** [comment]
I am having the same issue

**Comment by lewiscasewell** [comment]
This isn't a fix, it is a workaround - we are experiencing the same issue
version `13.12.5`

this is the compatible version with `expo 52.0.46`

Any ideas, can we reopen the issue
