### ISSUE TITLE
appp crash when use modal with supportedOrientations on iOS new arch

### ISSUE THREAD

**Issue by dioi2000** [react-native-webview/react-native-webview#3336]
appp crash when use modal with supportedOrientations on iOS new arch

if I delete react-native-webview, it's not happened

- sample code
[AwesomeProject.zip](https://github.com/react-native-webview/react-native-webview/files/14393361/AwesomeProject.zip)

 - OS: iOS
 - OS version: iOS 17.2
 - react-native version: 0.73.4
 - react-native-webview version: 13.8.1

**Comment by Martin2037** [comment]
same issue

**Comment by netmaxt3r** [comment]
see [rn issue](https://github.com/facebook/react-native/issues/43821)

**Comment by RalissonMattias** [comment]
The problem keeps happening:

- React Native: `0.74.3`
- React Native Web View: `13.10.5`

**Comment by netmaxt3r** [comment]
fix is not released on 0.74 probably on 0.75 see [discussion](https://github.com/facebook/react-native/issues/43821#issuecomment-2151869826)
