### ISSUE TITLE
Cookies not being sent to webview for iOS

### ISSUE THREAD

**Issue by caralin3** [react-native-webview/react-native-webview#3344]
**Bug description:**

Web view should be rendering a web page that has a cookie authentication. Instead it is rendering sign in page. This is happening on iOS after I upgraded to react native 0.73+. It was working properly before the upgrade.

I have both `thirdPartyCookiesEnabled={true}` and `sharedCookiesEnabled={true}` enabled. Also in `handleNavigationStateChange` I reset the cookies for iOS:

```
async function resetCookies() {
    const cookies = await CookieManager.getAll(Platform.OS === 'ios');
    Object.keys(cookies).forEach(key => {
      const cookie = cookies[key];
      if (cookie.domain === domain) {
        CookieManager.clearByName(url, cookie.name, Platform.OS === 'ios');
      }
    });
  }
```

**Expected behavior:**

Web view should render account page, not sign in page

**Environment:**
 - OS: Android, iOS
 - OS version: Android 34+, iOS 14+
 - react-native version: 0.73.6
 - react-native-webview version: 13.8.1

**Comment by thozh** [comment]
Adding this function fixed this issue for me when attempting to login with a webView in iOS

```ts
  const synchronizeCookiesiOS = async () => {
    if (Platform.OS === 'ios') {
      try {
        const allCookies = await CookieManager.getAll(true);
        for (const cookieKey of Object.keys(allCookies)) {
          const cookie = allCookies[cookieKey];
          if (cookie) {
            await CookieManager.set('https://' + cookie.domain, cookie);
          }
        }
      } catch (error) {
        console.error('Error synchronizing cookies:', error);
      }
    }
  };
  ```

**Comment by caralin3** [comment]
Thanks @thozh. When do you call the synchronize function? Do you call it in the `<WebView onLoad={} />` or the <WebView onNavigationStateChange={} />`?

**Comment by kiet-ap** [comment]
why you close this issue? fixed?

**Comment by kiet-ap** [comment]
@caralin3

**Comment by saeid-elio** [comment]
In my case this problem was due to sending a custom header in WebView. As soon as I remove the custom header the session cookie is sent again and Website authentication works in WebView.

**Comment by smohadjer** [comment]
In WebView 13.10.6 this problem has been fixed. See here: https://github.com/react-native-webview/react-native-webview/issues/3457

**Comment by andflett** [comment]
Can confirm 13.10.6 fixes this for us as well, unfortunately Expo is stuck at 13.8 at the moment, but hopefully they'll catch up at some point.

**Comment by saeid-elio** [comment]
@andflett That's why I decided not to use Expo in my project! ;)
