### ISSUE TITLE
Opening a page via injectJavaScript rewrites the last history frame

### ISSUE THREAD

**Issue by nikmedoed** [react-native-webview/react-native-webview#3354]
**Bug description:**
When I inject script for navigate to another page, the last page in history is replaced with a new one. This means that if I execute .goBack(), WebView opens not the previous page (-1), but the one that was in front of it (-2)

The following script variants performed a transition to a new page, and replaced the last one in the history:

```
const script = `window.open( '${url}', '_self'); `;

const script = `window.location.href = '${url}';`;

const script = `
history.pushState({}, '', '${url}');
history.go('${url}');
`;

const script = `
var link = document.createElement('a');
link.href = '${url}';
link.target = '_self';
document.body.appendChild(link);
link.click();
`;
```

**To Reproduce:**

Option 1
- Open any page in WebView
- Add any transition script to the page, for example ```const script = `window.location.href = '${url}';`;```
- Execute goBack()
- Discover that the WebView cannot go back

Option 2
- Open any page in WebView
- Make 2 clicks on links
- Inject script for ```const script = `window.location.href = '${url}';`;```
- Execute goBack()
- Catch that the WebView did not return to the previous page and return on the second page

**Expected behavior:**
goBack open previous page, if there was one.

**Environment:**
 - OS: android
 - OS version: android 12
 - react-native version: 0.73.5
 - react-native-webview version: 13.8.1

**Comment by nikmedoed** [comment]
Still relevant

**Comment by mrand15** [comment]
Still seeing this bug
