### ISSUE TITLE
loadUrl method for outside navigation and use native WebView history

### ISSUE THREAD

**Issue by nikmedoed** [react-native-webview/react-native-webview#3355]
**Is your feature request related to a problem? If so, Please describe.**
I'm facing a limitation with React Native WebView when trying to programmatically navigate within WebView while preserving the browsing history. Currently, WebView supports basic navigation like `goBack` and `goForward`, but there's no way to initiate a navigation from React Native code (e.g., from a drawer menu) that would integrate into WebView's history.

***Current Limitations:***
- Browsing history resets when setting a new `source` with `{uri: ...}`.
- Loss of WebView's native caching capabilities when managing history manually, causing full page reloads.
- Excessive memory usage with multiple WebView instances in navigation stacks.

**Describe the solutions you came up with**
Create `WebView.loadUrl(url)` method
- Uses native methods for opening web pages.
- Maintains the native history stack for navigations initiated from user component code, not limited to in-page link clicks.
- Preserves browsing history, addressing the issue of resetting.
- Enhances efficient usage of WebView's caching and memory, reducing full reloads and memory usage.

I've seen such a feature in native Android code. It would be highly beneficial if a similar implementation could be made available for iOS.

**Additional context**
This navigation method is essential for applications partially transitioning to native components. It's particularly important when terminal pages, like input forms, are rewritten with user-friendly native interfaces, while the root of the site remains web-based. The proposed `WebView.loadUrl(url)` method is invaluable for maintaining a browsing history that enables seamless navigation through the root web pages and access to advanced native interfaces for specific functionalities like forms. This approach is logical, as input forms often require more user experience adaptation compared to root sections of a website.

**Comment by roeycohen** [comment]
@nikmedoed 

too bad this was CR was closed... this function is already implemented on Android:
https://github.com/react-native-webview/react-native-webview/blob/5bc526fce5b9d6225df183bdf3d8cf542007d90a/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManagerImpl.kt#L342C10-L342C17

but sadly, not on IOS
https://github.com/react-native-webview/react-native-webview/blob/5bc526fce5b9d6225df183bdf3d8cf542007d90a/apple/RNCWebView.mm#L523
