### ISSUE TITLE
Can't open blob url inside webview

### ISSUE THREAD

**Issue by remberluyckx** [react-native-webview/react-native-webview#3357]
In my webview I open a page where there is a download button for a pdf. The pdf is downloaded through a blob url (blob:https://-------------/a2cb9bd4-4a7b-4e26-825d-024cdbb73d3c). When I tap this button nothing happens and I get no error. When I set the 
setSupportMultipleWindows={false} property of the webview and tap the button it asks if i want to leave the page and if i tap yes, i get an error saying Can't open url: blob:https://----------/a2cb9bd4-4a7b-4e26-825d-024cdbb73d3c.

I tried fetching the url with fetch() to get the blob data but the network request fails.

**Comment by CristinaBloqhouse** [comment]
It's happening to me too, please if someone has an answer.

**Comment by Devyadav3001** [comment]
my code run on android 11+ version but not run android 11 and lower than 11 
here is my code:--
import React from "react";
import { StyleSheet, Alert } from "react-native";
import WebView from "react-native-webview";
import { Container } from "../components";
import Colors from "../configs/Colors";
import Config from "../configs/Config";
import { LoginScreenProps } from "../navigation/NavigationTypes";
import { saveToken, saveUserData } from "../utils/Util";
import AppContext from "../context/AppContext";
const HTML = `<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<style>
			body {
				height: 100vh;
			}

			.loader-box {
			height: 100%;
			width: 100%;
			display: flex;
			justify-content: center;
			align-items: center;
			}

			.loader {
				border: 3px solid #f3f3f3;
				border-radius: 50%;
				border-top: 3px solid #00B4EB;
				width: 30px;
				height: 30px;
				-webkit-animation: spin 2s linear infinite;
				animation: spin 2s linear infinite;
			}

			@-webkit-keyframes spin {
				0% { -webkit-transform: rotate(0deg); }
				100% { -webkit-transform: rotate(360deg); }
			}

			@keyframes spin {
				0% { transform: rotate(0deg); }
				100% { transform: rotate(360deg); }
			}
		</style>
	</head>
	<body onload="document.forms['signInForm'].submit();">
		<div class="loader-box">
    		<div class="loader"></div>
			<form method="post" action="${Config.GOOGLE_VALIDATE_URL}" id="signInForm">
				<input type="hidden" name="applicationId" value="${Config.applicationId}"/>
				<input type="hidden" name="applicationSecret" value="${Config.applicationSecret}"/>
			</form>
    	</div>
	</body>
</html>
`;

type LoginStates = {
	isResponseReceived: boolean;
};

export default class Login extends React.Component<LoginScreenProps> {
	static contextType = AppContext;
	declare context: React.ContextType<typeof AppContext>;

	constructor(props: LoginScreenProps) {
		super(props);
	}

	onMessage = async (event: any) => {
		const data = event.nativeEvent.data;
		if (data) {
			const response = JSON.parse(data);

			if (typeof response === "object" && Object.keys(response).length > 0) {
				if (response.userName !== null && response.userName !== "") {
					saveToken({ token: response.token });
					this.context.setUserData(response);
					saveUserData(response);
				} else {
					Alert.alert(
						"Error",
						"You are not authorized to access this application"
					);
				}
			} else {
				Alert.alert(
					"Error",
					"You are not authorized to access this application"
				);
			}
		} else {
			Alert.alert("Error", "Something went wrong");
		}
	};

	render = (): JSX.Element => (
		<Container statusBarColor={Colors.white}>
			<WebView
				originWhitelist={["*"]}
				source={{
					html: HTML,
				}}
				incognito={true}
				onMessage={this.onMessage}
				onError={(error) => {}}
				style={[
					styles.container,
					{ paddingTop: Math.floor(Config.WINDOW_HEIGHT * 0.1) },
				]}
			/>
		</Container>
	);
}
const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: Colors.white,
	},
});

**Comment by andrew-bierman** [comment]
+1 Experiencing the same as you described. If anyone has a work around for this, that would be greatly appreciated

**Comment by Jitendra120901** [comment]
still searching solution
