### ISSUE TITLE
Uncaught DOMException: Failed to execute 'postMessage' on 'Window': Invalid target origin 'null' in a call to 'postMessage'.

### ISSUE THREAD

**Issue by sakisev** [react-native-webview/react-native-webview#3358]
**Bug description:**

Hello, I've been trying to integrate Marqeta in app, specifically their reveal card details widget https://www.marqeta.com/docs/developer-guides/using-marqeta-js#_card_data_tutorial, which requires rendering html and javascript code. I am using WebView to render it and every time I am getting an error
```
internal-marqeta.min.js:1 Uncaught DOMException: Failed to execute 'postMessage' on 'Window': Invalid target origin 'null' in a call to 'postMessage'.
```
and nothing gets rendered in either iOS, Android or web (the app uses react-native-web as well).

To my understanding this seems like a cross origin issue, I have set `originWhitelist={['*']}` in order to, if I understood correctly, whitelist all origin, but I am still getting the same error. 
I have also tried the properties `allowUniversalAccessFromFileURLs`, `allowFileAccessFromFileURLs`, `allowFileAccess` and `allowingReadAccessToURL`, which may have nothing to do with my issue.

I have tried rendering the widget in vanilla JS and it works fine, so I am quite lost as to what may be the cause of this issue.

Any help or suggestions would be highly appreciated

**Environment:**
 - OS: macOS
 - OS version: Sonoma 14.4
 - react-native version: 0.70.12
 - react-native-webview version: 13.8.1

**Comment by flawnn** [comment]
I have a similar issue - what did you do?
