### ISSUE TITLE
How to set Microsoft Edge as default browser for WEBVIEW

### ISSUE THREAD

**Issue by karthikkarunanithi91** [react-native-webview/react-native-webview#3364]
Can you please help us to setup Microsoft Edge as a default browser when opening a WebView.
Actually the website that we want to open in WebView, only works on Microsoft Edge.
That's why we want that WebView should use Microsoft Edge as its default.

Please let me know if its possible or not. And if possible then how can we do that?

**Comment by jgarplind** [comment]
As far as I'm aware, the WebView is considered a separate browser. I'm quite sure I have seen "Android WebView" as its own category on caniuse.com for example. (However, I don't see that right now).

That said, all Chromium browsers are quite similar, but if you really need Edge, you probably need to solve your problem without the help of this library.
