### ISSUE TITLE
Webview bridge maybe has some bug since v13.8.2

### ISSUE THREAD

**Issue by musicode** [react-native-webview/react-native-webview#3368]
First, I open a webview page, then I open a new webview page, when I close the new page, the bridge in the first page is not work.

`v13.8.1` is ok, but `v13.8.2` is not work.

os: android

**Comment by guo-pf** [comment]
you can try:       
`
const [resetOnMessage, setResetOnMessage] = useState(false);

useEffect(() => {
    const unsubscribe = navigation.addListener('focus', () => {
      if (Platform.OS === 'android'){
      setResetOnMessage(!resetOnMessage);
     }
    });
    return unsubscribe;
  }, []);

   const handleMessage = (event:  WebViewMessageEvent) => {
 
  };
<WebView
              source={{ uri: initUrl}}
              ... ...     
              onMessage={resetOnMessage ? resetHandleMessage : handleMessage}
             ... ...
          />
`

**Comment by RalissonMattias** [comment]
I face a similar problem, when I use Webview within Flatlist, only the last message is captured

**Comment by andreialecu** [comment]
Seems related to #3352 (/cc @Kudo 🫣)

**Comment by andreialecu** [comment]
I have not fully tested this, I was looking into recent changes, but my understanding is that this is what happens:
- if you have a single webview everything is fine
- if you navigate to a different screen, or some other webview is on the same screen, only the last added webview will be able to get notifications from `onMessage`

Looking at the changes in #3352 I'm not sure I understand the exact reason for switching the first parameter here to a constant: https://github.com/react-native-webview/react-native-webview/pull/3352#discussion_r1549718289

**Comment by gavrichards** [comment]
We use `onShouldStartLoadWithRequest` to load most webpages in a new screen in a stack, rather than in the same view. We've noticed that since 13.8.2 this no longer works on Android. RN 0.73.6.
Would this issue be related to that?

**Comment by farwayer** [comment]
I can confirm the problem with `onMessage` starting from 13.8.2 (several WebViews if it's important)

**Comment by ad-walker** [comment]
> We use `onShouldStartLoadWithRequest` to load most webpages in a new screen in a stack, rather than in the same view. We've noticed that since 13.8.2 this no longer works on Android. RN 0.73.6. Would this issue be related to that? Rolling back to 13.8.1 fixes it.

Running into the same issue, [when logging this block ](https://github.com/react-native-webview/react-native-webview/blob/74de1f43d50fd94785cae6cf491ef5a4970c7be8/src/WebView.android.tsx#L171C1-L193C7)it looks like the `messagingModuleName` equality check is failing on subsequent `onShouldStartLoadWithRequest`/`onMessage` requests.
