### ISSUE TITLE
React Native WebView don't have access to camera on some android devices

### ISSUE THREAD

**Issue by Ravshanichk** [react-native-webview/react-native-webview#3369]
**Bug description:**
Facing issues on some android devices with camera access. I am using webview for biometric authentication through webview with camera access. Additionally, i use react-native perission library to get access to camera, before getting to webview, all access are granted, but still camera does't appear in webview, so authentication is failed. After that api reject authentication with result "No camera detected"

**Expected behavior:**
Working and accessed camera displayed on webview

**Screenshots/Videos:**
![no_camera](https://github.com/react-native-webview/react-native-webview/assets/55016329/ed9b3e3a-2ad4-456e-b49b-0eed8e6a3ee6)

**Environment:**
 - OS: Android
 - OS version: 10
 - react-native version: 0.70.14
 - react-native-webview version: 13.8.2
 - model: HUAWEI P30 lite
 
```javasript
<WebView
        onShouldStartLoadWithRequest={onShouldStartLoadWithRequest}
        geolocationEnabled
        mediaPlaybackRequiresUserAction={false}
        mediaCapturePermissionGrantType="grant"
        javaScriptEnabled
        originWhitelist={['*']}
        allowsInlineMediaPlayback
        source={{ uri: url ?? '' }}
        scalesPageToFit
        startInLoadingState
        useWebKit
      />
``` 

Maybe connected with this issue #3206

**Comment by pjcape** [comment]
Hi did u fix the issue? Im facing the same :(

**Comment by pjcape** [comment]
@Ravshanichk , any luck ?

**Comment by simonho1025** [comment]
same here

**Comment by sebas5384** [comment]
same here

**Comment by stoodkev** [comment]
Any update on this?

**Comment by pmahdavii** [comment]
Same here!

**Comment by Keddib** [comment]
Same here

**Comment by Ravshanichk** [comment]
@Keddib @pmahdavii @stoodkev 
Hello!
Sorry for the late reply! It was so long ago.
So i managed to find what caused this problem. Before navigating to the webview screen for biometric authentication, I also had a camera screen open, using React Native Vision Camera. At that moment, when navigating with the camera still active, the camera component was being closed incorrectly, which caused the camera to be unavailable in the webview. So i had to close camera component by adding some time (setTimeout), before navigation to another screen. I recommend checking the logcat logs in Android Studio.
