### ISSUE TITLE
TypeScript support is broken starting from the `13.8.3` version

### ISSUE THREAD

**Issue by anton-patrushev** [react-native-webview/react-native-webview#3374]
**Bug description:**
Both the latest (at the moment) `13.8.4` and `13.8.3` versions have broken TypeScript support. Props are not typified on these versions.

**To Reproduce:**

install `13.8.4` or `13.8.3` into TS configured project
```zsh
yarn add react-native-webview@13.8.4

// OR

yarn add react-native-webview@13.8.3
```

I noticed that it doesn't have `.d.ts` files for each `js` file under `node_modules/react-native-webview/lib/` folder

Here is what it looks like on `13.8.4`
<img width="528" alt="image" src="https://github.com/react-native-webview/react-native-webview/assets/62186274/8369e74f-e9b6-4e61-9209-a67fd1616c6a">

And it leads to issues like this:
<img width="545" alt="image" src="https://github.com/react-native-webview/react-native-webview/assets/62186274/ca8dc6d7-5eef-4e25-a259-c4852d0cb34e">

**Expected behavior:**

It should have working TS support. So it should have TS support for `WebView` props.

Screenshot from the `13.8.2` version:
<img width="517" alt="image" src="https://github.com/react-native-webview/react-native-webview/assets/62186274/b13d64d3-8982-4777-b3a3-e8f9531ea6ec">

I believe it should have `.d.ts` file for each file under `node_modules/react-native-webview/lib/` folder:

Screenshot from the `13.8.2`version:
<img width="512" alt="image" src="https://github.com/react-native-webview/react-native-webview/assets/62186274/b49dbe3e-ab50-40c5-b2d6-7572dbad3aaa">

**Environment:**
 - OS: `iOS` (local machine — MacOS Sonoma 14.4.1)
 - OS version: `iOS 17.4`
 - react-native version: `0.72.12` (Fabric enabled)
 - react-native-webview version: `13.8.4`

**Comment by netmaxt3r** [comment]
I see types are moved to /index.d.ts ( better approach imho) , but `index.d.ts` is referencing  `./lib/WebViewTypes` which are pure js files without any type info. probably some ts build config issue, i am looking into permanent fix , meanwhile you can try below patch
```patch
diff --git a/node_modules/react-native-webview/index.d.ts b/node_modules/react-native-webview/index.d.ts
index 394b444..1cc0753 100644
--- a/node_modules/react-native-webview/index.d.ts
+++ b/node_modules/react-native-webview/index.d.ts
@@ -1,8 +1,8 @@
 import { Component } from 'react';
 // eslint-disable-next-line
-import { IOSWebViewProps, AndroidWebViewProps, WindowsWebViewProps } from './lib/WebViewTypes';
+import { IOSWebViewProps, AndroidWebViewProps, WindowsWebViewProps } from './src/WebViewTypes';
 
-export { FileDownload, WebViewMessageEvent, WebViewNavigation } from "./lib/WebViewTypes";
+export { FileDownload, WebViewMessageEvent, WebViewNavigation } from "./src/WebViewTypes";
 
 export type WebViewProps = IOSWebViewProps & AndroidWebViewProps & WindowsWebViewProps;
 
```

**Comment by netmaxt3r** [comment]
PR #3378 will fix typings , sourceMaps are still not linked let me know if sourcemap is required
