### ISSUE TITLE
[Android] Issue with injectedJavaScriptBeforeContentLoaded 

### ISSUE THREAD

**Issue by ivankdev** [react-native-webview/react-native-webview#3377]
Integrating webview in my RN app. I need to handle [Publitas API](https://publitas.github.io/docs/js.html#custom-product-action) by injected javascript code. This is minimal code snippet for repro.

```json
"react-native-webview": "^13.8.4",
```

```js
import { Alert } from 'react-native'
import WebView from 'react-native-webview'

const publitasInjectedJS = `
  console.log('publitasInjectedJS'); // called always
  
  window.viewerReady = function(api) {
    console.log('viewerReady'); // called sometimes
    // ... doing logic here
  };
  
  true;
`

export const App = () => {
  return (
    <WebView
      injectedJavaScript={publitasInjectedJS} // works well for iOS, never for Android
      injectedJavaScriptBeforeContentLoaded={publitasInjectedJS} // works sometimes for Android
      source={{ uri: 'https://view.publitas.com/delhaize-belgium/2023-w42-fr' }}
      onMessage={() => Alert.alert('postMessage')}
      cacheEnabled={false}
    />
  )
}
```

So on iOS default `injectedJavaScript` prop works well and method `viewerReady` is always called in time. 

But on Android side, `injectedJavaScript` doesn't work at all and `injectedJavaScriptBeforeContentLoaded` works like in 1 case of 20 page reloads. You can see actually that `viewerReady` not called at all most of the reloads.

<img width="273" alt="Screenshot 2024-04-03 at 02 05 26" src="https://github.com/react-native-webview/react-native-webview/assets/37651838/f13fa3b0-2e32-482f-b11e-111948c979db"> <img width="300" alt="Screenshot 2024-04-03 at 01 35 09" src="https://github.com/react-native-webview/react-native-webview/assets/37651838/23d2d97a-f1b9-4ec0-870a-f2dc70559cd1">

_____

What I also tried is 
```
  onLoad={() => webViewRef.current?.injectJavaScript(publitasInjectedJS)}
```
but no any visible changes with that approach

**Question:** Any clues how to make it work for Android properly?

**Comment by gronxb** [comment]
you can see this issue:
https://github.com/react-native-webview/react-native-webview/pull/1099

injectedJavaScriptBeforeContentLoaded is sometimes weird on Android. 

This is an alternate prop for that issue.
https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#injectedjavascriptobject

see https://github.com/react-native-webview/react-native-webview/pull/2960

**Comment by ivankdev** [comment]
> you can see this issue: #1099
> 
> injectedJavaScriptBeforeContentLoaded is sometimes weird on Android.
> 
> `injectedJavaScriptObject` is an alternate prop for this issue. https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#injectedjavascriptobject
> 
> see [#2960 (comment)](https://github.com/react-native-webview/react-native-webview/pull/2960#issuecomment-1715027083)

 @gronxb thanks for answer, but honestly I'm not sure how can passed object help here, when exactly function `window.viewerReady` not being called. All what I need is get viewerReady called in correct moment, no any data from js needed.

**Comment by gronxb** [comment]
Instead of passing the callback of viewReady from react native, why not call viewReady directly from inside the web, not from react native, and pass the necessary data to `injectedJavaScriptObject` and assign it?

**Comment by ivankdev** [comment]
@gronxb I cannot change the web part, it's dynamic url shared with mobile team
