### ISSUE TITLE
Can the Microphone Permission Request Message be Modified in WebView Browser

### ISSUE THREAD

**Issue by chlgkrws** [react-native-webview/react-native-webview#3380]
**Bug description:**
I have already taken the following steps:

Ensured that the mediaCapturePermissionGrantType setting prevents more than two permission request prompts from appearing.
I understand that the permissions for native apps and WebView browsers are different. Having requested permissions in the native app, I discovered that the browser still asks for permission when using the microphone. Therefore, I cannot utilize Info.plist's NSMicrophoneUsageDescription.

My iOS app was rejected during the review process for not having a clear message in the permission request. How can I change this message? Or, has anyone in a similar situation found an alternative solution to this issue?

**Screenshots/Videos:**
![image](https://github.com/react-native-webview/react-native-webview/assets/61148082/9587f3e8-dff0-42f0-b00e-87ddbda8ee5d)

**Environment:**
OS: iOS
OS version: 15
react-native version: 0.73.0
react-native-webview version: 13.6.4
model: iPhone 13 pro

**Comment by kcotias** [comment]
> **Bug description:** I have already taken the following steps:
> 
> Ensured that the mediaCapturePermissionGrantType setting prevents more than two permission request prompts from appearing. I understand that the permissions for native apps and WebView browsers are different. Having requested permissions in the native app, I discovered that the browser still asks for permission when using the microphone. Therefore, I cannot utilize Info.plist's NSMicrophoneUsageDescription.
> 
> My iOS app was rejected during the review process for not having a clear message in the permission request. How can I change this message? Or, has anyone in a similar situation found an alternative solution to this issue?
> 
> **Screenshots/Videos:** ![image](https://private-user-images.githubusercontent.com/61148082/319453180-9587f3e8-dff0-42f0-b00e-87ddbda8ee5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2ODgzMDUsIm5iZiI6MTcyNjY4ODAwNSwicGF0aCI6Ii82MTE0ODA4Mi8zMTk0NTMxODAtOTU4N2YzZTgtZGZmMC00MmYwLWIwMGUtODdkZGJkYThlZTVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDE5MzMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkMzNhZjRmOWI2NWViOWRmODU1MjAzMGE5NDdhZWZmN2RiYTExMDE4NmU4ODIzM2M5Y2JiMzQ0ZTY3MGY1ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NS4Y8H8FWdZY-CZyZior7wTTerub_vf9oLxLhtttmxw)
> 
> **Environment:** OS: iOS OS version: 15 react-native version: 0.73.0 react-native-webview version: 13.6.4 model: iPhone 13 pro

Hey man, were you able to solve this? I'm currently facing this issue, no clue on how to solve it :/

**Comment by gulsher7** [comment]
Hey, I'm facing the same issue. Has anybody solved this?
