### ISSUE TITLE
setJavaScriptEnabled() JavaScript was enabled in the WebView

### ISSUE THREAD

**Issue by karthikTVS** [react-native-webview/react-native-webview#3381]
Recently we scanned our app and they found JavaScript was enabled in WebView. But we never used this property to enable JavaScript. 

Issue :- JavaScript was enabled in the WebView. (Example: found 'setJavaScriptEnabled()’ in file 'com/reactnativecommunity/webview /RNCWebViewManager.java').

Kindly confirm that this won't get enabled until we enabled manually.

**Comment by jaya-shankar** [comment]
+1
