### ISSUE TITLE
invalid url causing crash in ios 

### ISSUE THREAD

**Issue by akshgods** [react-native-webview/react-native-webview#3384]
**Bug description:**

If we pass invalid url we are getting crash

actual url: https://www.hindustantimes.com/ht-img/img/2024/03/27/550x309/Akshay_Kumar_1711524357605_1711524357751.jpg

invalid url which causing crash:
 '%3Ca%20_blank%20href=https://www.hindustantimes.com/ht-img/img/2024/03/27/550x309/Akshay_Kumar_1711524357605_1711524357751.jpg'

Error handling functions not returning anything.

```
 onError={(e) => {
            console.log('onError:: ', e);

          }}
          onHttpError={(e) => {
            console.log('onHttpError:: ', e);

          }}
          renderError={(e) => {
            console.log('renderError:: ', e);
          }}

```

**To Reproduce:**

Reproduce is simple, just use this url in your webview url:

 `url={'%3Ca%20_blank%20href=https://www.hindustantimes.com/ht-img/img/2024/03/27/550x309/Akshay_Kumar_1711524357605_1711524357751.jpg'}`
 
 now open webview you will get application getting crash.

**Expected behavior:**

it should not get crashed , it will throw error in one of error handling function.

```
 onError={(e) => {
            console.log('onError:: ', e);

          }}
          onHttpError={(e) => {
            console.log('onHttpError:: ', e);

          }}
```

let me know what changes required or what we can do it to solved this?

**Environment:**
 - OS: Mac
 - OS version: 13.2.1 (22D68)
 - react-native version: "0.67.3"
 - react-native-webview version: "11.26.0"

**Comment by netmaxt3r** [comment]
@akshgods can you check issue is reproducible on latest version?

**Comment by akshgods** [comment]
@netmaxt3r yes confirmed with latest available version.
![Simulator Screen Shot - iPhone 14 - 2024-04-15 at 13 51 03](https://github.com/react-native-webview/react-native-webview/assets/26785665/b270385a-3034-4aff-9af6-279050c461e0)

<img width="630" alt="Screenshot 2024-04-15 at 1 52 53 PM" src="https://github.com/react-native-webview/react-native-webview/assets/26785665/c8a73fe1-96a1-4240-8cc0-0a5a7f88b3ce">

code to test:

```
<WebView source={{ uri: '3Ca%20_blank%20href=https://reactnative.dev/' }} 
       style={{ flex: 1 }}
       onError={(e) => {
        console.log('onError:: ', e);
      }}
      onHttpError={(e) => {
        console.log('onHttpError:: ', e);
      }}
      renderError={(e) => {
        console.log('renderError:: ', e);
      }}
       />
```

Environment:

OS: Mac
OS version: 13.2.1 (22D68)
"react-native": "0.73.6",
"react-native-webview": "^13.8.5"

**Comment by netmaxt3r** [comment]
I am getting different results. 

on iOS its just console.warn with ` Error opening URL:  [Error: Unable to open URL: ....`
![image](https://github.com/react-native-webview/react-native-webview/assets/1734518/64689be7-799e-4957-b99b-f1b138d4b2b5)
![Simulator Screenshot - iPhone 15 Pro - 2024-04-15 at 20 57 40](https://github.com/react-native-webview/react-native-webview/assets/1734518/7222b46f-f52a-457d-90b3-11e4065ae39b)


on Android it does call `onError` with `nativeEvent` ` {"canGoBack": false, "canGoForward": false, "code": -2, "description": "net::ERR_NAME_NOT_RESOLVED", "loading": false, "target": 3, "title": "", "url": "http://3ca%20_blank%20href%3Dhttps//reactnative.dev/"}` followed by two calls to `renderError` with null error
![image](https://github.com/react-native-webview/react-native-webview/assets/1734518/90d44610-c6b6-4439-82f5-66951719ad28)

In either case app does not crash

**Comment by akshgods** [comment]
@netmaxt3r in new version its not crashing right (confirm).

but how to handle that warning in ios?

**Comment by akshgods** [comment]
@netmaxt3r  i understand you code diffrence 

you used http:// in starting of url

just use this without http:

`source={{ uri: '3Ca%20_blank%20href=https://reactnative.dev/' }}`

**Comment by netmaxt3r** [comment]
@akshgods i havent added http protocol, it is added by android as the url is malformed it cannot detect the protocol, where as in ios it defaults to `file` protocol to relative path as seen in the warning 
```js
    return (
      <WebView source={{ uri: '3Ca%20_blank%20href=https://reactnative.dev/' }}
               style={{ flex: 1 }}
               onError={(e) => {
                 console.log('onError:: ', e.nativeEvent);
               }}
               onHttpError={(e) => {
                 console.log('onHttpError:: ', e);
               }}
               renderError={(e) => {
                 console.log('renderError:: ', e);
               }}
      />
    );
```

```json
  "dependencies": {
    "react": "18.2.0",
    "react-native": "0.73.6",
    "react-native-webview": "^13.8.5"
  }
```
