### ISSUE TITLE
Vertical scroll bar is not visible in android in webview but is visible in iOS

### ISSUE THREAD

**Issue by chetnaag95** [react-native-webview/react-native-webview#3387]
**Bug description:**
Vertical scroll bar is not visible in android emulator even if I add **showsVerticalScrollIndicator** attribute in webView. It is visible for iOS simulator

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS:
 - OS version:
 - react-native version:
 - react-native-webview version:

**Comment by thomasgwatson** [comment]
Well, that's a pity. I have this issue, but I don't want scroll bars to show up in EITHER but for some reason one vertical one is showing up in iOS...
