### ISSUE TITLE
Invariant Violation: Failed to call into JavaScript module method WebViewMessageHandler1.onMessage()

### ISSUE THREAD

**Issue by rhenandias** [react-native-webview/react-native-webview#3395]
**Bug description:**

[The minimum execution example in the documentation](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Guide.md#the-windowreactnativewebviewpostmessage-method-and-onmessage-prop) for the `window.ReactNativeWebView.postMessage` method does not work when using version ^13.

**To Reproduce:**

After installing the module with the following command `npm install react-native-webview`, the package installed is version `"react-native-webview": "^13.8.4"`, and with this package, the minimum example returns the following error:

```
Invariant Violation: Failed to call into JavaScript module method WebViewMessageHandler1.onMessage(). Module has not been registered as callable. Bridgeless Mode: false. Registered callable JavaScript modules (n = 12): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, HMRClient, AppRegistry, RCTEventEmitter, RNCWebViewMessagingModule.
          A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
```

The code provided in the documentation:

```javascript
import React, { Component } from 'react';
import { View } from 'react-native';
import { WebView } from 'react-native-webview';

export default class App extends Component {
  render() {
    const html = `
      <html>
      <head></head>
      <body>
        <script>
          setTimeout(function () {
            window.ReactNativeWebView.postMessage("Hello!")
          }, 2000)
        </script>
      </body>
      </html>
    `;

    return (
      <View style={{ flex: 1 }}>
        <WebView
          source={{ html }}
          onMessage={(event) => {
            alert(event.nativeEvent.data);
          }}
        />
      </View>
    );
  }
}
```

However, when downgrading to version 11 with the package `npm install react-native-webview@11` the version `"react-native-webview": "^11.26.1"` is installed, and with this version the same code works normally as expected.

**Environment:**
 - OS: Ubuntu
 - OS version: Ubuntu 20.04.6 LTS
 - react-native version: 0.73.6
 - react-native-webview version (working): 11.26.1
 - react-native-webview version (bug): 13.8.4
 - expo version: 50.0.14

**Comment by gaisdav** [comment]
same error

**Comment by AreebGhani** [comment]
`npm i react-native-webview@13.6.4`

It will work for me.

**Comment by gaisdav** [comment]
@AreebGhani yes, also for me, thank you!

**Comment by rhenandias** [comment]
@AreebGhani Can confirm, for me the `npm i version react-native-webview@13.6.4` also solved the problem, I'm following this more up-to-date version than ^11. Thanks!

**Comment by AreebGhani** [comment]
@rhenandias It seems there's a compatibility issue or a bug in the latest version (13.8.5) that may be fixed soon.

**Comment by smlparry** [comment]
Any update on this? or is there something I can do to get this running in the meantime?

I require the update introduced in 13.8.5 (which apparently also broke this 😢)

**Comment by Abdullah-z** [comment]
Getting the same error when using "react-native-webview" with "react-native-fusioncharts": "^5.2.3"

"expo": "~50.0.17",
"react": "18.2.0",
"react-native": "0.73.6",
"react-native-fusioncharts": "^5.2.3",
"react-native-webview": "13.6.4",

**Comment by JungHsuan** [comment]
Downgrading to version `react-native-webview@13.6.4` doesn't solve the issue for me.

**Comment by rhenandias** [comment]
The issue seems to be with compatibility with Expo. I needed other modules that weren't compatible with Expo, so I created a project in bare React Native, and the latest version works as expected.

**Comment by techneocareu** [comment]
We are having the same issue? 

My dependencies:
"dependencies": {
    "expo": "^51.0.2",
    "expo-status-bar": "~1.11.1",
    "react": "18.2.0",
    "react-native": "0.73.6",
    "react-native-webview": "13.6.4"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.45",
    "typescript": "^5.1.3"
  },
  
  Anyone have a solution?

**Comment by jlounds** [comment]
> EDIT: I've solved the issue npx expo install --fix

This worked for me as well. Thank you for sharing!

**Comment by OpsAhmad** [comment]
> EDIT: I've solved the issue npx expo install --fix

This working! Big Thanks!

**Comment by mk0116** [comment]
I ejected from expo but this error occurs very frequently.
version: 13.10.4

**Comment by hamidjavadi2amigos** [comment]
> EDIT: I've solved the issue npx expo install --fix

This resolved the issue! 
Thanks!

**Comment by eeasuper** [comment]
for me, I got a warning message after loading npm start telling me which webview version would work best with the expo version I have. After I changed by webview version to that, it worked.

**Comment by Emyboy** [comment]
> We are having the same issue?
> 
> My dependencies: "dependencies": { "expo": "^51.0.2", "expo-status-bar": "~1.11.1", "react": "18.2.0", "react-native": "0.73.6", "react-native-webview": "13.6.4" }, "devDependencies": { "@babel/core": "^7.20.0", "@types/react": "~18.2.45", "typescript": "^5.1.3" },
> 
> Anyone have a solution?
> 
> EDIT: I've solved the issue npx expo install --fix

This worked instantly. Thank you
