### ISSUE TITLE
Error: Text strings must be rendered within a <Text> component.

### ISSUE THREAD

**Issue by JoseVov** [react-native-webview/react-native-webview#3398]
**Bug description:**
Error: Text strings must be rendered within a <Text> component.

**To Reproduce:**
You install, import, and use it.

It's happening to me as the most basic mode

`<WebView source={{ uri: 'https://reactnative.dev/' }} style={{ flex: 1 }} />;`

**Expected behavior:**
Display the webview with the page provided instead of showing that error

**Screenshots/Videos:**

![simulator_screenshot_F22B0A54-680B-4D6E-BB72-FC512E66E2B6](https://github.com/react-native-webview/react-native-webview/assets/96314055/d6548dde-0151-493f-96dc-fa1bb87cbc6a)

https://github.com/react-native-webview/react-native-webview/assets/96314055/26b68066-6b21-4b7d-bbb4-5b7e20a0b68a

**Environment:**
 - OS: IOS
 - OS version: IOS 17
 - react-native version: 0.73.6
 - react-native-webview version: ^13.8.4

**Comment by vinamrahalgar** [comment]
Any idea on how to fix this

**Comment by JoseVov** [comment]
> Any idea on how to fix this

Check your JSX, I remember that I had an extra character in the JSX causing that.

**Comment by JoseVov** [comment]
Probably the `;`. Remove the `;` in this line -> `<WebView source={{ uri: mapURL }} />;`
