### ISSUE TITLE
Webview shows blank white page

### ISSUE THREAD

**Issue by SorooshDeveloper** [react-native-webview/react-native-webview#3410]
**Bug description:**

When implementing example in my project webview shows empty screen and with no errors!
webview library works ok in my project when i test it with other examples.

    "react-native-react-bridge": "^0.11.2",
    "react-dom": "^18.2.0",
    "react-native": "0.71.18",
    "react": "18.2.0",
    "react-native-webview": "^13.8.6",

![Screenshot 2024-04-23 at 3 12 26 PM](https://github.com/react-native-webview/react-native-webview/assets/163350653/e0e95d75-ae8c-42c9-b3df-ecfb708ecc5d)

**Comment by robpearmain** [comment]
I am getting the same problem after the app has been inactive

**Comment by swrobel** [comment]
Android, iOS, or both?

**Comment by robpearmain** [comment]
So far on an iOS device (iPhone and iPad), not on android

My workaround is on the event

onContentProcessDidTerminate

I set the url to null using state and then set it to the correct url after
a short timer, it then reloads correctly

**Comment by robpearmain** [comment]
It would be good to have maybe a option to reload on
onContentProcessDidTerminate with a maximum retries

**Comment by jonluca** [comment]
We're seeing this as well when the first screen the user sees is the webview. Is there a race condition somewhere? Not sure what its going on internally to make it render blank
