### ISSUE TITLE
modal display shrinked in ios with react-native-webview

### ISSUE THREAD

**Issue by oldschoolstarsman** [react-native-webview/react-native-webview#3413]
Using react-native-webview library I am encountering different behaviour on android and ios in regards to how a modal that contains input field that opened will be displayed.

The issue occurs when focusing on input field, as expected the keyboard opens but on ios the modal get squashed whereas on android the content is displaying fine.

See screenshot below:  
[android ios] 
![webview modal](https://github.com/react-native-webview/react-native-webview/assets/30653088/ea8cc368-22f8-4563-a01d-544cea69136a)

I wonder if there is a particular trick to adjust ios behaviour in this case?

We have such requirement to display some pages written in React.js (that we control) in the app via web-view and  so I have access to source code for this modal on the web which looks something like:

`.modal {   border-radius: 8px;   left: 50%;   max-height: 100%;   position: fixed;   top: 50%;   transform: translate(-50%,-50%);   width: calc(100% - 40px);   z-index: 995; }`

Environment:
OS: ios, any version
"react-native-webview": "13.2.2",
"react-native": "0.72.6",

I am a bit clueless where to look honestly. Looked up similar issues on stackoverflow and the library github repo but no luck.

I could inspect the same page on ios simulator on safari web inspector and play with properties but issue is not present
![view on safari](https://github.com/react-native-webview/react-native-webview/assets/30653088/20cd8ca1-c98a-4e65-936e-04f129664cab)

**Comment by thinh1991999** [comment]
Do you know how to resolve this issue yet?

**Comment by oldschoolstarsman** [comment]
> Do you know how to resolve this issue yet?

Nope 😞
