### ISSUE TITLE
Your browser does not seem to support WebGL

### ISSUE THREAD

**Issue by CandidlyRed** [react-native-webview/react-native-webview#3414]
**Bug description:**
When running html with javascript that requires WebGL, browser on phone gives the error "Your browser does not seem to support WebGL"

**To Reproduce:**

`<WebView originWhitelist={['*']}
      source={{ 
        html: `
        <head>
          
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />

          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@photo-sphere-viewer/core/index.min.css" />
          <style>
              html, body {
                  margin: 0;
                  padding: 0;
                  height: 100%;
                  overflow: hidden; /* Hide scroll bars */
              }

              #viewer {
                  width: 100%;
                  height: 100%;
                  margin: 0;
                  padding: 0;
              }

          </style>
      </head>

      
      <div id="viewer" style="width: 100%; height: 100%;"></div>

      <script type="importmap">
          {
              "imports": {
                  "three": "https://cdn.jsdelivr.net/npm/three/build/three.module.js",
                  "@photo-sphere-viewer/core": "https://cdn.jsdelivr.net/npm/@photo-sphere-viewer/core/index.module.js"
              }
          }
      </script>

      <script type="module">
          import { Viewer } from '@photo-sphere-viewer/core';

          const viewer = new Viewer({
              container: document.querySelector('#viewer'),
              panorama: 'https://picsum.photos/4000/3000',
              navbar: null,
          });
      </script>
      ` }} style={{ flex: 1 }} />`
Above is an example of a webview that uses html with a script that requires WebGL, when running it in the App, I get the error "Your browser does not seem to support WebGL"

**Expected behavior:**

My HTML runs fine in browser on my computer, but it fails to run in the webview on my phone. I'm not sure if this is unsupported, or if there's some kind of workaround available. I saw some previous issues that were closed- but there didn't seem to be a solution

**Screenshots/Videos:**

![Screenshot_20240425_002009_monogatari](https://github.com/react-native-webview/react-native-webview/assets/59667106/b69b0a62-42af-4650-932e-523c852770a9)
Ignore the back button, that is a component rendered without webview

**Environment:**
 - OS: MacOS
 - OS version:
 - react-native version: 0.73.7
 - react-native-webview version: ^13.8.6

**Comment by snhoby** [comment]
Any update regrading this? I am also trying to load 360 image but I am also getting the same error.
