### ISSUE TITLE
HTML select option dropdown menu positions are different compared to browser in WebView 

### ISSUE THREAD

**Issue by BhargavDev9** [react-native-webview/react-native-webview#3424]
I am rendering a html which contains select tag in react native webview.  when select menu is opened, the option menu is displayed on top of the screen irrespective of select element position. where as the expected behaviour is to display it as a dropdown menu below/above the select element or a pop with the backdrop in the centre of the screen.

![image](https://github.com/react-native-webview/react-native-webview/assets/128380281/6b438ba3-5774-499b-a725-f3280353937c)

when the same html is loaded in the web browser it is working as expected.

![image](https://github.com/react-native-webview/react-native-webview/assets/128380281/da72c244-c77c-48fc-8314-5fbe0e4e792e)

**To Reproduce:**

`        

<html>
          <body>
          
          <h1>The select element</h1>
          
          <p>The select element is used to create a drop-down list.</p>
          
          <form action="/action_page.php">
            <label for="cars">Choose a car:</label>
            <select name="cars" id="cars" style="margin-top:500">
              <option style = "background: red;" value="volvo">Volvo</option>
              <option style = "background: red;" value="saab">Saab</option>
              <option style = "background: red;" value="opel">Opel</option>
              <option style = "background: red;" value="audi">Audi</option>
            </select>
            <br><br>
            <input type="submit" value="Submit">
          </form>
          
          <p>Click the "Submit" button and the form-data will be sent to a page on the 
          server called "action_page.php".</p>
          
          </body>
          </html>`

**Environment:**
 - OS:Android
 - react-native version: 0.72.6
 - react-native-webview version: 13.5.1

**Comment by Sach454** [comment]
Hi @BhargavDev9 - I'm also exactly facing the same issue on Android tablet only, whereas on iPhone and Android mobile phones it's rendering as expected 

Any solution would be great to this issue...I have been stuck with this issue since last week

**Comment by makalaravikiran** [comment]
Hello @BhargavDev9, Same issue for me as well in android Tablet. Could not able to find any solution. It would be great if team look in to this issue and fix.

**Comment by BhargavDev9** [comment]
We are still waiting for support from community, issue still exist

**Comment by tmKnight01** [comment]
The issue still  exist ,  please follow up

**Comment by tmKnight01** [comment]
the issue still  exist , please follow up.

**Comment by bionanek-x** [comment]
hey this is issue still exists, so bumping

**Comment by saikoushikvarma** [comment]
Issue is still exists, any workaround for this issue?
