### ISSUE TITLE
[v13.10.0] Broken on Windows platform

### ISSUE THREAD

**Issue by birdofpreyru** [react-native-webview/react-native-webview#3434]
The following change by @rozele broke the library for Windows, because missing the closing `#endif`.

https://github.com/react-native-webview/react-native-webview/blame/fab94f1e51d003228543dcdb08de360e04d6edd7/windows/ReactNativeWebView/ReactWebViewManager.h#L5-L7

Perhaps, related to #3432.

It would be nice if you actually test changes before releasing them.

**Comment by shwanton** [comment]
Fixed in #3433
