### ISSUE TITLE
Bug: onShouldStartLoadWithRequest not preventing navigation to aliexpress:: links on iOS Prevent deep linking to third party applications Still not solved on IOS

### ISSUE THREAD

**Issue by obender** [react-native-webview/react-native-webview#3435]
In the iOS version of our app, onShouldStartLoadWithRequest from react-native-webview version 13.8.6 is failing to intercept and block navigation to URLs with the aliexpress:: scheme. Despite the configuration originWhitelist={["*"]} and setSupportMultipleWindows={false}, these specific URLs are causing the AliExpress app to launch. 

Notably, this functionality works as expected on Android, where all external links are correctly handled within the app. 
This discrepancy between platforms is critical as we aim to maintain uniform functionality across our app to ensure security and control over navigation.

**Comment by ChenReuven** [comment]
I struggle with the same issue :(

is there any solution for that?
