### ISSUE TITLE
Zoom issue in webview

### ISSUE THREAD

**Issue by SolankiYogesh** [react-native-webview/react-native-webview#3437]
**Bug description:**

When clicking on an input field within the webview, the page zooms in unexpectedly.

**To Reproduce:**

Link to repository: sorry its private repo

Steps to reproduce:
1. Open the app containing the webview.
2. Navigate to the page with the input field.
3. Click on the input field.

**Expected behavior:**

The page should not zoom in when focusing on the input field within the webview.

**Screenshots/Videos:**

![Zoom Issue](https://github.com/react-native-webview/react-native-webview/assets/70507671/8bae8f6b-b9ca-4d68-8b06-b5dc6be7e0be)

**Environment:**
 - OS: IOS
 - OS version: IOS 17.2
 - react-native version: 0.73.8
 - react-native-webview version: 13.8.7

**Comment by dmille** [comment]
I'm also having this issue. Only happens on iOS, not Android

**Comment by SolankiYogesh** [comment]
@dmille add below code in head and style tag

```
// head 

   <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0" />
```

```
// css file

 @media only screen and (max-device-width: 414px) and (orientation: portrait) and (-webkit-min-device-pixel-ratio: 2) {
            /* Adjust font size for inputs on iOS devices */
            .flex-input {
                font-size: 16px !important;
            }
        }
        @media screen and (-webkit-min-device-pixel-ratio:2) { 
            select,
            textarea,
            input {
              font-size: 16px !important;
            }
          }
```

**Comment by dmille** [comment]
@SolankiYogesh Thank you!!
