### ISSUE TITLE
On Android device not able to auto play video in full screen for embed iframe video url

### ISSUE THREAD

**Issue by Sanket8304** [react-native-webview/react-native-webview#3438]
**Bug description:**

I've been using the react-native-webview for playing Youtube and Vimeo playbacks on my mobile app. In iOS it works fine but in android it behaves a bit different. I want to make my android to play on fullscreen when pressed on play. iOs it's default behaviour is correct.

**Environment:**
 - react-native version: 0.73.4
 - react-native-webview version: 13.8.4

**Comment by webjinlong** [comment]
I also encountered this problem, have you solved it?

**Comment by Acetann** [comment]
I found the error, in the Webview.android.tsx file of react-native-webview in the node_modules, there's a props called "allowsFullscreenVideo" which is set to false by default and is never changed, so I replaced it with true and it works perfectly.

If you want to patch the library, use patch-package ;)
