### ISSUE TITLE
Setting connection timeout value

### ISSUE THREAD

**Issue by fe-jcorreia** [react-native-webview/react-native-webview#3448]
I'm currently working on a webview that opens a page with a slow loading time (~3min) and I'm getting timeout from the webview when trying to open it. I tested on safari browser, tested on android and other browsers, the page really takes time to load but does not give timeout. My issue has to do only with the webview on iOS, when the loading time takes too long seems like the webview is triggering timeout.

```
Encountered an error loading page {"canGoBack": false, "canGoForward": false, "code": -1001, "description": 
"The request timed out.", "didFailProvisionalNavigation": true, "domain": "NSURLErrorDomain", 
"loading": false, "target": 3337, "title": "", "url": ""}
```

My android webview takes ~3min to show data in screen, my iOS gives the timeout error ~1min after loading starts. This does not occur on safari browser.

I want to know if there is a way to set the timeout value on the webview.
This issue is based on https://github.com/react-native-webview/react-native-webview/issues/1182

**Environment:**
 - react-native version: 0.72.6
 - react-native-webview version: 13.10.2

**Comment by bvanderdrift** [comment]
There's a workaround available at https://github.com/react-native-webview/react-native-webview/issues/1182#issuecomment-2218079255. Not ideal, but could be used in times of need.

**Comment by phuocnguyenncc** [comment]
@fe-jcorreia Have you resolved yet? I just had the same case
