### ISSUE TITLE
same error after upgrading to Expo SDK 51 from 49 and rendering `RichEditor` from `react-native-pell-rich-editor`

### ISSUE THREAD

**Issue by hoangann2000** [react-native-webview/react-native-webview#3449]
same error after upgrading to Expo SDK 51 from 49 and rendering `RichEditor` from `react-native-pell-rich-editor`

_Originally posted by @mcsrk in https://github.com/react-native-webview/react-native-webview/issues/3426#issuecomment-2123922513_

**Comment by UmairHhc** [comment]
same error after upgrading to Expo SDK 51 from 49 and rendering `RichEditor` from `react-native-pell-rich-editor`
