### ISSUE TITLE
The keyboard is shaking (invisible/visible) on Android only

### ISSUE THREAD

**Issue by duykhanh0409** [react-native-webview/react-native-webview#3454]
**Bug description:**

Currently, when I use React native webView to show our webView page, this web has some input form and for Android when user tries to fill in the input, the keyboard shakes (invisible/visible) and the user can't use keyboard, when I using that web on external browser like Chrome it work well, so it means this issue not come from the web, we only faced it when using internal browser webView, try multiple like wapper it with keyboardAvoidingView and try some another props of webView but I can't make it work. I would be very happy if someone could help me with this issue

**To Reproduce:**

Can open simple webView component
Pass this webView link to reproduce. The link is just have reproduce the issue with input form https://app.weshake.io/payment/request/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTY3ODMzNzB9.V7XZUQBMUE5t0HTGr23QjJqTUNi9FBn8DnH2vJ4ffIk?token=24MSae86GUr7fZ2973541716783370713

**Expected behavior:**

My Expectation is the keyboard can show normal and user can fill in their input

**Screenshots/Videos:**

![image](https://github.com/react-native-webview/react-native-webview/assets/51994010/a16723ba-5574-4005-9e56-ded68dd44a0e)

![image](https://github.com/react-native-webview/react-native-webview/assets/51994010/0e481c23-b816-40ee-8c81-0151892827dc)

**Environment:**
 - OS:Android
 - OS version: 13
 - react-native version: 0.71.8
 - react-native-webview version: 13.2.2

https://github.com/react-native-webview/react-native-webview/assets/51994010/3ce52755-ac8e-4e59-a336-c69240214af8

**Comment by KhanhNguyen49** [comment]
Hi I'm still met this issue, can anyone help me ? Thank you

**Comment by akankshaingle** [comment]
Has anyone managed to fix this issue?
