### ISSUE TITLE
Migrate Windows to New Architecture

### ISSUE THREAD

**Issue by chiaramooney** [react-native-webview/react-native-webview#3456]
Migrate Windows platform for the react-native-webview control to use the new architecture. 

## Implementation Considerations
Using WinUI or Not:
- Waiting for WinUI usage within RNW running on Fabric to be supported and then we can use the WinUI2 WebView/WebView2 control. Note WinUI3 does not include WebView2.
- Migrating the module to use WebView2 directly from edge instead of the wrapped WebView2 from WinUI. 

Control Offerings:
- Will the module continue to support both WebView and WebView2 on Fabric or just WebView2?

**Comment by KGGrande** [comment]
Would also like to see this
