### ISSUE TITLE
WebView with react native gesture handler not working as expected.

### ISSUE THREAD

**Issue by zainlinux1989** [react-native-webview/react-native-webview#3465]
I am facing an issue, Web View wrapped with GestureDetector.  pan gesture is working fine on iOS but it is not working on Android.
i want to close web view with a left to swipe right, and web view scroll must be enabled. 

**Environment:**
 - OS: MAC OS 
 - OS version: 14.5
 - react-native version: 0.73.6
 - react-native-webview version: 13.9.1
 - react-native-gesture-handler: 2.16.0

**Comment by isaac-israel-aquant** [comment]
hey I have the same issue here

**Comment by delmaass** [comment]
See https://github.com/software-mansion/react-native-gesture-handler/discussions/2277#discussioncomment-14779159
