### ISSUE TITLE
Open X-Twitter with WebView

### ISSUE THREAD

**Issue by ductridev** [react-native-webview/react-native-webview#3473]
**X-Twitter is said that the browser is not support, so is there any ways we can handle this?**

**Describe the solutions you came up with**
I want to open a post from X-Twitter inside my app - only inside my app, but X-Twitter is limit the browser can use their platform, so the function I want to make is impossible right now? Is there any way to bypass it?

**Additional context**
Pass the homepage's URL of X-Twitter to WebView then the message will come.

**Comment by zane-commeatio** [comment]
I think it has to do with useragent

i use this and it happen to me also

```ts
userAgent={
    Platform.OS === "android"
        ? "Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.6478.122 Mobile Safari/537.36"
        : "AppleWebKit/602.1.50 (KHTML, like Gecko) CriOS/56.0.2924.75"
}
```

does someone have a user agent that is not blocked by Twitter ?

**Comment by ductridev** [comment]
@zane-commeatio I fixed the problem with this hook:
```import { useEffect, useState } from 'react'
import DeviceInfo from 'react-native-device-info'

export const useUserAgent = () => {
    const [userAgent, setUserAgent] = useState<string>("")

    useEffect(() => {
        setUserAgent(DeviceInfo.getUserAgentSync())
    }, [])

    return userAgent
}
```
Then in WebView component:
`userAgent={useUserAgent()}`

**Comment by serhii-rubel** [comment]
> [@zane-commeatio](https://github.com/zane-commeatio) I fixed the problem with this hook:
> 
> ```
> import DeviceInfo from 'react-native-device-info'
> 
> export const useUserAgent = () => {
>     const [userAgent, setUserAgent] = useState<string>("")
> 
>     useEffect(() => {
>         setUserAgent(DeviceInfo.getUserAgentSync())
>     }, [])
> 
>     return userAgent
> }
> ```
> 
> Then in WebView component: `userAgent={useUserAgent()}`

getUserAgentSync is only supported on Android, but I have the issue on iOS. So, I've used asynchronous method getUserAgent which is available on both platforms. And yes it fixes the issue.

Updated variant looks like that:

```
export const useUserAgent = () => {
    const [userAgent, setUserAgent] = useState("")

    useEffect(() => {
      DeviceInfo.getUserAgent().then(userAgent => {
        setUserAgent(userAgent)
      })
    }, [])

    return userAgent
}

// extract in a component
const userAgent = useUserAgent();

// pass as WebView prop
userAgent={userAgent}

```
