### ISSUE TITLE
iOS Orientation Change Zoom Bug

### ISSUE THREAD

**Issue by kwb020312** [react-native-webview/react-native-webview#3477]
I am not good at English, so I organize my writing through a translator, so there may be some inappropriate expressions.

**Bug description:** 
If you lay your iOS mobile device horizontally, the screen will be forced to enlarge by a certain size if you have had any gestures such as zooming in or out at least once since the app was launched.

This is zoomed in to a specific size because there is a history of zooming in and out even if the mobile device is vertically upright.

After searching for a long time, I found that this was before iOS 6 and has since been fixed.

But I still get that bug in my web view.

**To Reproduce:** First of all, since we are working on a project by a public institution, we cannot link the repository, but the method of reproduction is very simple. 

1. Install the react-native-webview library (react-native-webview": "^13.10.2")
2. Enter a specific URL (I don't care if it's Google or YouTube)
3. Zoom in or out of the screen and lie down in landscape mode

If you proceed with this process, it will be magnified at the same magnification regardless of any magnification before the change of direction.

**Expected behavior:** The magnification of the screen that was viewed in portrait mode must be magnified

**Screenshots/Videos:** 

If you have done more than one zooming gesture before laying your phone horizontally

https://github.com/react-native-webview/react-native-webview/assets/46777310/a5c2d9ea-9528-4dc3-b4c8-6854e38a2a00

If you haven't done the zooming gesture before lying down the phone

https://github.com/react-native-webview/react-native-webview/assets/46777310/5e2f6d8a-03d9-4655-b57e-92ba321ee757

**Environment:**
 - OS: iOS
 - Device: iPhone XR
 - OS version: iOS 17.5.1
 - react-native version: 0.74.1
 - react-native-webview version: ^13.10.2

**Comment by Dxg125** [comment]
Im currently also struggling with this issue, for the time beeing im using this workaround: 

`$(window).on(`orientationchange`, () => {
 /* Reset Meta Zoom */
 if (window.isiOS()) {
  let AllowZoom = `yes`;
  let ViewPort  = $(`meta[name="viewport"]`);
  ViewPort.attr(`content`, `width=device-width, minimum-scale=1.0, initial-scale=1.0, maximum-scale=1.0, user-scalable=${AllowZoom}`);
  setTimeout(() => {
   ViewPort.attr(`content`, `width=device-width, minimum-scale=1.0, initial-scale=1.0, user-scalable=${AllowZoom}`);
  }, 1);
 }
});`

**Comment by 1880akshay** [comment]
I am facing the same issue. Why is this issue closed?
