### ISSUE TITLE
webview does not work in webview tester app in ios

### ISSUE THREAD

**Issue by quanpham88** [react-native-webview/react-native-webview#3480]
I am using this app to test my webapp in webview
https://apps.apple.com/tr/app/webview-tester/id1661004679

try to very simple below code to test it
<WebView source={{ uri: 'https://www.google.co.jp/' }} />

However when I use Webkit webview to open it, I got "React native webview does not support this platform" error.

**Comment by 01miaom** [comment]
I think it is not supported to open on the expo web. You can use a mobile phone or emulator.

**Comment by segicm** [comment]
@quanpham88 Have you resolved this? I'm experiencing the same issue on my iOS device.
