### ISSUE TITLE
Webflow loads very slowly on react-native-webview iOS

### ISSUE THREAD

**Issue by taipham1803** [react-native-webview/react-native-webview#3482]
**Bug description:**

Our webflow site ([Usage Limits for Starter Plan](https://www.plot.so/usage-limits-for-starter-plan)) loads very slowly on react-native-webview (iOS), it takes about 10-15 seconds to load, sometimes it gets stuck for up to 30 seconds. However, when loading using the phone’s default browser (safari, chrome), it loads very quickly.

**To Reproduce:**

```
<WebView
    incognito
    ref={webviewRef}
    style={{ flex: 1 }}
    onNavigationStateChange={onNavigationStateChange}
    javaScriptEnabled
    injectedJavaScript={injectedJavaScriptForDebugging}
    cacheEnabled
    domStorageEnabled
    cacheMode="LOAD_CACHE_ELSE_NETWORK"
    androidLayerType="hardware"
    onMessage={onMessage}
    renderLoading={() => <View />}
    injectedJavaScriptForMainFrameOnly
    mediaPlaybackRequiresUserAction
    source={{ uri: `https://www.plot.so/usage-limits-for-starter-plan` }}
    enableApplePay
    automaticallyAdjustContentInsets={false}
  />
```

**Expected behavior:**

It should load as quickly as it opens on a mobile browser

**Screenshots/Videos:**

https://github.com/react-native-webview/react-native-webview/assets/23112684/63303ce0-cce0-49d6-83cb-12207cefd2fc

**Environment:**
 - OS: Mac
 - OS version: 14.5 (23F79)
 - react-native version: 0.73.1
 - react-native-webview version: 13.6.4

**Comment by VirtualDOMinic** [comment]
Hey @taipham1803 , did you manage to find a solution to this?
