### ISSUE TITLE
Google OAuth account selection page is blank

### ISSUE THREAD

**Issue by fairjm** [react-native-webview/react-native-webview#3487]
**Bug description:**
My website has an existing registration and login system. I want to implement app login using an embedded WebView and shared cookies. The self-implemented email registration/login function works normally. However, when using Google OAuth login, it shows a blank screen at the step where you click the button to select an account.

Logging into Google is normal(this is step1). After logging into Google, the button will display my account. Then when I click the button, it shows a blank screen.(step2 fails)

The webpage works normally on both PC Chrome browser and Android Chrome browser.

**To Reproduce:**
the code:
```typescript
import { View, Text, Platform } from 'react-native'
import React, { useEffect, useState } from 'react'
import WebView, { WebViewNavigation, WebViewProps } from 'react-native-webview'
import CookieManager from '@react-native-cookies/cookies'

const userAgent = Platform.select({
  android: 'Mozilla/5.0 (Linux; Android 10; Android SDK built for x86) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.120 Mobile Safari/537.36',
  ios: 'Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1',
});

const LoginPage = () => {
  const onNavigationStateChange = async (event: WebViewNavigation) => {
    console.log("url", event.url)
    const cookie = await CookieManager.get("https://admin.heichat.net");
    console.log("cookie", cookie);
  }

  useEffect(() => {
    // CookieManager.clearAll()
  }, [])

  return (
    <View className='flex-1'>
      <WebView
        className='flex-1'
        source={{ uri: 'https://admin.heichat.net/login'}}
        userAgent={userAgent}
        sharedCookiesEnabled={true}
        thirdPartyCookiesEnabled={true}
        onNavigationStateChange={onNavigationStateChange}
        setSupportMultipleWindows={false}
        originWhitelist={['*']}
        pullToRefreshEnabled={true}
        webviewDebuggingEnabled={true}
        domStorageEnabled={true}
        startInLoadingState={true}
        onError={(syntheticEvent) => {
          const { nativeEvent } = syntheticEvent;
          console.warn('WebView error: ', nativeEvent);
        }}
        onHttpError={(event) => {
          console.log("http error", event);
        }}
        onMessage={(event) => {
          console.log('Message from webview:', event.nativeEvent.data);
        }}
      />
    </View>
  )
}

export default LoginPage
```

I set setSupportMultipleWindows to false because if I don't set it to false, the logging to google step fails(step 1), it opens the system browser and shows a blank screen.

**Expected behavior:**
logging to google success.

**Screenshots/Videos:**
<video src='https://github.com/react-native-webview/react-native-webview/assets/4281721/41bd645f-4f3c-4502-967e-a57c61ed4112' width=180/>

dev tools:
![image](https://github.com/react-native-webview/react-native-webview/assets/4281721/b89d07c6-9cb7-4b29-b12a-fcca9feb8b49)

**Environment:**
 - OS: android
 - OS version: android 12
 - react-native version: 0.74.3
 - react-native-webview version: 13.0.3

**Comment by fairjm** [comment]
I found that this Google login method requires communication between two windows. When I tried to copy the link from the pop-up window on the PC browser and open it directly in a new tab, it also showed a blank screen. The WebView's behavior seems consistent with this. It only opens the link to the account selection page. So, is it impossible to implement this scenario using WebView?

**Comment by Sankeerth-g7** [comment]
hi @fairjm have you found any solutions for this

**Comment by vahemm** [comment]
` <View style={styles.container}>
      <Button title="Open WebView" onPress={openModal} />
      <Modal visible={visible} transparent={true} animationType="fade">
        <View style={styles.modalContainer}>
          <View style={styles.modalContent}>
            <WebView
              style={styles.webview}
              userAgent={CHROME_USER_AGENT}
              
              source={{ uri: authUrl }}
              onLoadStart={() => console.log('true')}
              onLoadEnd={() => console.log('false')}
              onNavigationStateChange={(navState) => {
                if (navState.url.includes('your-app://auth')) {
                  closeModal();
                  // Handle deep link redirect and extract data
                }
              }}
            />
            <Button title="Close" onPress={closeModal} />
          </View>
        </View>
      </Modal>
      </View>
      
      const styles = StyleSheet.create({

  container: {
    flex: 1,
    alignItems: 'center',
    // backgroundColor: '#ffffff',
    paddingTop: 5,
  },
   modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)', // semi-transparent background
  },
  modalContent: {
    backgroundColor: 'white',
    margin: 20,
    borderRadius: 10,
    width: 350,
    height: 700,
    padding: 20,
    alignItems: 'center',
  },
  webview: {
    flex: 1,
    width: 350,
    height: 700,
  
    // backgroundColor: 'red',
  },})`

**Comment by fairjm** [comment]
> hi @fairjm have you found any solutions for this

I use web browser instead, it works fine.

**Comment by raahimkhan** [comment]
Has anyone resolved this. Getting same in web view.

**Comment by Aikenwu** [comment]
same like the window open is not working in webview. find other ways to use it. https://github.com/react-native-webview/react-native-webview/issues/3065
