### ISSUE TITLE
Initial Black Screen When Playing Loom Videos on IOS

### ISSUE THREAD

**Issue by salmaAlouane** [react-native-webview/react-native-webview#3490]
Bug description:

When playing Loom videos using react-native-webview, the video initially opens with a black screen while the audio plays. To view the video correctly, you need to close it and reopen it.

To Reproduce:

1-Use the following component to display a Loom video

```
import React from "react";
import { View } from "react-native";
import { WebView } from "react-native-webview";
import Modal from "react-native-modal";
import { VideoModalProps } from "../interface/interface";
import IconButton from "./IconButton";
import { Theme } from "../Constants/Colors";

const ModalVideo: React.FC<VideoModalProps> = (props) => {
  const { modalVisible, setModalVisible, url } = props;

  return (
    <Modal isVisible={modalVisible}>
      <View style={{ paddingTop: 50 }}>
        <View style={{ borderRadius: 12, backgroundColor: "#020202", height: "80%" }}>
          <View style={{ backgroundColor: "#020202", padding: 10, alignItems: "flex-end", borderTopLeftRadius: 12, borderTopEndRadius: 12 }}>
            <IconButton onPress={() => setModalVisible(!modalVisible)} iconType="antDesign" iconName="close" color={Theme.white100} />
          </View>
          <View style={{ flex: 0.9, backgroundColor: "#020202" }}>
            <WebView
              javaScriptEnabled={true}
              allowsFullscreenVideo={true}
              scrollEnabled={false}
              source={{ uri: url }}
              style={{ opacity: 0.99 }}
            />
          </View>
        </View>
      </View>
    </Modal>
  );
};

export default ModalVideo;

```

2-Use the following example video link: https://www.loom.com/embed/1bb02967f1524281b3cb29761284b0c7?hideEmbedTopBar=true

3- Open the video by clicking on it. Observe that it initially shows a black screen with audio only.
4- Close and reopen the video to see it play correctly.

**Screenshots/Videos:**
<img width="347" alt="Capture d’écran 2024-07-09 à 6 41 18 PM" src="https://github.com/react-native-webview/react-native-webview/assets/77794805/4a6db4f9-7b03-4d3a-a725-d4180e2aefd8">

**Environment:**
OS: iOS
OS version: tested on 17.5
react-native version: "^0.73.8"
react-native-webview version: "^13.10.0"

**Comment by MbuthiaWaKihara** [comment]
Same problem here. For me, the black screen shows by default when the video is loaded.

**Comment by zchengb** [comment]
Same issue for me, hoping for a solution :(

**Comment by zchengb** [comment]
OHHHH~~~ adding the `allowsInlineMediaPlayback=true` prop fixed my problem :)

**Comment by alx4329** [comment]
Same problem here.. allowsInlineMediaPlayback set to true didnt help. It starts to load but gets stuck after a few seconds of the video.

**Comment by cjhines** [comment]
This happens even if `preload="auto"` or `preload="metadata"` is appended to `<video/>` elements. I haven't found a workaround

**Comment by maciejken** [comment]
Occurs on iOS 17 version only (not 16 or 18) and adding `allowsInlineMediaPlayback` flag for iOS seems to solve this (together with `webkit-playsinline` attribute to video tag as mentioned here https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#allowsinlinemediaplayback), but the video doesn't go full-screen after tapping on the video for the first time, still might work for some people as the user can still go full screen after tapping the button in video toolbar

**Comment by iremsilamadenli** [comment]
I was getting a weird fullscreen black screen with video controls when opening certain pages in WebView on iOS. Turned out it was either some kind of bot detection (an invisible <video autoplay>) or just a media playback quirk in iOS 17 WebView.

Fixed it with:

config.allowsInlineMediaPlayback = true  
config.mediaTypesRequiringUserActionForPlayback = []  
webView.customUserAgent = "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0...)"

No more fullscreen — everything loads fine now.  
(Solved in SwiftUI — not React Native or Flutter.)
