### ISSUE TITLE
blob url download issue in ios its directly opening not saving it to local storage for android its working fine

### ISSUE THREAD

**Issue by vinayroy1** [react-native-webview/react-native-webview#3494]
Hi Team , i am using react native webview to open my company webpage.  its opening webpage fine for both android and ios.
company webpage is having download document button which generating blob url for download .
In case of android on press of download button its giving download popup and on confirmation its downloading document correclty 

but in case of ios its directly opening pdf or image file its not downloading it to local storage. but on browser also download functionality working fine

code snipper i am using :-

import React, { useRef, useEffect } from "react";
import { SafeAreaView, Platform } from "react-native";
import { WebView } from "react-native-webview";
import { useAppSelector } from "../../../infrastructure/store";
import { getLoginResponse } from "../../../infrastructure/stateSelector/authStateSelector";
import { setCookie } from "../../../utils";

interface RouteParams {
  link?: string;
  // Define any other parameters you expect in route.params
}

interface GrowProScreenProps {
  route: {
    params?: RouteParams;
  };
}

const GrowProScreen: React.FC<GrowProScreenProps> = () => {
  const webviewRef = useRef<WebView>(null);
  const loginResponse = useAppSelector(getLoginResponse);

  useEffect(() => {
    setCookie("https://example.com", {
      name: "vo-auth-token",
      value: loginResponse?.voToken,
      domain: "example.com",
      path: "/",
      version: "1",
      //secure: true,
    });
    setCookie("https://example.com", {
      name: "vo-login-id",
      value: loginResponse?.intermediaryId,
      domain: "example.com",
      path: "/",
      version: "1",
      //secure: true,
    });
  }, [loginResponse]);

  return (
    <SafeAreaView style={{ flex: 1 }}>
     
        <WebView
          ref={webviewRef}
          source={{
            uri: "example.com",
          }}
          onError={(event) => console.log('WebView Error:', event.nativeEvent)}
          onLoadStart={() => console.log('WebView load start')}
          onLoadEnd={() => console.log('WebView load end')}
          sharedCookiesEnabled={true}
          thirdPartyCookiesEnabled={true}
          javaScriptEnabled={true}
          domStorageEnabled={true}
          allowFileAccessFromFileURLs={true}
          allowUniversalAccessFromFileURLs={true}
          allowFileAccess={true}
          originWhitelist={["*"]}
          mixedContentMode={"always"}
         
        />

    </SafeAreaView>
  );
};

export default GrowProScreen;

**Comment by vitexikora** [comment]
Duplicate to this - https://github.com/react-native-webview/react-native-webview/issues/3251
They seem to not care at all.
