### ISSUE TITLE
iOS webview no dealloc

### ISSUE THREAD

**Issue by zdpdsy** [react-native-webview/react-native-webview#3498]
Hi Team, i find some question in webview，The RNCWKWebView not dealloc，i find the reason after debug。
 destroyWebView（602 line in RNCWebViewImpl.m）Code will never be executed because RNCWebViewImpl.m don't change to RNCWebViewImpl.mm，mean is RCT_NEW_ARCH_ENABLED it always return false。

the solution is: change RNCWebViewImpl.m  to RNCWebViewImpl.mm

![image](https://github.com/user-attachments/assets/0a31cf7e-1e26-4ce7-b271-2decff632c2b)

react-native:0.73.0
"react-native-webview": "13.10.5",

**Comment by MatthiasDh** [comment]
https://github.com/facebook/react-native/pull/43088
