### ISSUE TITLE
Khmer character/text font become bold on Android

### ISSUE THREAD

**Issue by AkhmadFarid** [react-native-webview/react-native-webview#3507]
In our app, we use both English and Khmer/Cambodian language. On Android, we face an issue when switched to Khmer, the text become bold, while it is displayed correctly with English language.

**_Khmer_**
![WhatsApp Image 2024-07-23 at 17 51 50](https://github.com/user-attachments/assets/545fcb30-995d-4bce-8bee-34abd3d2fa87)

**_English_**
![WhatsApp Image 2024-07-23 at 17 51 51](https://github.com/user-attachments/assets/ec558f07-47ca-41c4-9d44-878bc91a6283)

My recent research suggest that this is due the default rendering engine which bind to the Android OS, which is Chromium engine have no support for the Khmer scripts and characters.

**Comment by sovannratana** [comment]
I've faced this issue as well recently.

**Comment by sovannratana** [comment]
Have you found a workaround on this issue? @AkhmadFarid

**Comment by AkhmadFarid** [comment]
> Have you found a workaround on this issue? @AkhmadFarid

@sovannratana Nope. I spent more than a week searching for solution for this, I couldn't come out with the solution yet, that's why I raised an issue on this.

**Comment by RothaSoeurn** [comment]
can u have solution  ?

**Comment by RothaSoeurn** [comment]
but i have same problem
