### ISSUE TITLE
window.open popup does not show up on android

### ISSUE THREAD

**Issue by nymphetamineinside** [react-native-webview/react-native-webview#3509]
**Bug description:**
if i run `window.open('https://www.google.com', '_blank', 'popup')` inside a webview on Android
I don't see popup coming.

Works perfectly on IOS at the same time.

**To Reproduce:**
1. webpage with a button that does `window.open('https://www.google.com', '_blank', 'popup')` is opened in webview.
2. button click
3. there is no popup on android

**Expected behavior:**
the same way it works on IOS, we should be able to have popup opened

**Screenshots/Videos:**

**Environment:**
 - OS: Android
 - OS version: API 35
 - react-native version:  0.74.1
 - react-native-webview version: 13.10.2

**Comment by FionaLMcLaren** [comment]
Hi there! I am having a similar issue so I am wondering if anyone found a solution? My React Native version is "0.74.5" and my React Native Webview is "^13.8.6". Like the OP, it works perfectly fine on my iOS 17 but not on my Android 14. Thank you for any help!
