### ISSUE TITLE
Video items inside of a Flatlist disappear when orientation changes in fullscreen mode

### ISSUE THREAD

**Issue by t0ma5h** [react-native-webview/react-native-webview#3511]
**Bug description:**

When a `WebView` component is used inside a `Flatlist` to display video,  it does not react ok with orientation changes. 
When going to full screen  and rotating the phone puts the video into landscape more, going back to Flatlist will make that particular components disappear from the list. 
My guess is this happens because the `WebView` does not react to orientation changes and does not recalculate it's width/height. I'm not sure. 
I've added a reproductible example and video.

**To Reproduce:**

https://snack.expo.dev/_niEY54oN

Steps to reproduce:

Scroll to the bottom of the list
Play the last item
Enter full screen
Rotate the device
Go back
After doing this a couple of times, the webview will just disappear.
This has nothing to do with orientation locking or any other lib associated with orientation. It just doesn't work.
If anyone has a fix for this please let me know.

**Expected behavior:**

Video should still be there and adhere to the orientation changes in sizing.

**Screenshots/Videos:**

https://github.com/user-attachments/assets/b83e077e-e232-4aa5-b4d8-41f7a89946fe

**Environment:**
 - OS: Android/Expo
 - OS version:  Expo SDK 51
 - react-native version: 0.74
 - react-native-webview version: "13.8.6",

**Comment by prutkovvv** [comment]
same issue
