### ISSUE TITLE
[IOS] Scroll get stuck

### ISSUE THREAD

**Issue by qerseri** [react-native-webview/react-native-webview#3513]
Hello, in places where there is a scroll, with some movements, the scroll gets stuck on iOS, and in order for it to decompose, you need to wait a couple of seconds and not continue scrolling and then it starts working.

scrolling gets stuck in content made in React

**Environment:**
 - OS: IOS
 - OS version: no matter
 - react-native version: 0.73.6
 - react-native-webview version: 13.6.4

**Comment by duskload** [comment]
Getting similar issue. Any way to fix that?
