### ISSUE TITLE
No +[RCTConvert WKDataDetectorTypes:] function found

### ISSUE THREAD

**Issue by Teinble** [react-native-webview/react-native-webview#3518]
**Bug description:**

When using `react-native-pell-rich-editor` which requires `react-native-webview`, it still shows "No +[RCTConvert WKDataDetectorTypes:] function found" even https://github.com/laurent22/joplin/pull/10761 says this issue is fixed at @13.10.4
**To Reproduce:**

```
import React from 'react';
import { View } from 'react-native';
import { useRef } from 'react';
import {
  RichEditor,
  RichToolbar,
  actions,
} from "react-native-pell-rich-editor";

export default function App() {
  const richTextContext = useRef(null);
  return (
    <View className={styles.richEditorContainer}>
      <RichToolbar
        className={styles.richToolbar}
        editor={richTextContext}
        selectedIconTint="#873c1e"
        iconTint="#312921"
        actions={[
          actions.insertImage,
          actions.setBold,
          actions.setItalic,
          actions.insertBulletsList,
          actions.insertOrderedList,
          actions.insertLink,
          actions.setStrikethrough,
          actions.setUnderline,
        ]}
      />
      <RichEditor
        ref={richTextContext}
        onChange={(text) => {
          handleOnChange(text, "content");
        }}
        className={styles.richEditorError}
        initialHeight={styles.richEditorInitHeight}
        placeholder="Enter Content Here"
      />
    </View>

  );
}

const styles = {
  richEditorContainer: "flex flex-col-reverse",
  textInput: "border border-gray-300 p-2 rounded-md",
  richEditor: "border border-gray-300 rounded-b-md",
  richEditorError: "border border-red-600 rounded-b-md",
  richEditorInitHeight: 170,
  richToolbar: "rounded-t-md",
};

```
**Expected behavior:**

When open up a project with `react-native-pell-rich-editor`, it should not have such error showing up. 

**Screenshots/Videos:**

<img width="364" alt="image" src="https://github.com/user-attachments/assets/a6f6c91b-39c7-467a-a609-6c9aeb8e15df">

**Environment:**
 - OS: macOs
 - OS version: 14.5
 - react-native version: 0.74.3
 - react-native-webview version: 13.10.4

**Comment by tomgiam** [comment]
I'm having the same problem. it works when running the app through expo go on android device, but not expo go on iOS device. I've heard from others that it works on production builds (i.e. no expo go), but I have not verified this. There is also a way to patch it through patch-package, but I have not verified it.
