### ISSUE TITLE
 WebView on a Xiaomi tablet enters an infinite loading loop.

### ISSUE THREAD

**Issue by tmKnight01** [react-native-webview/react-native-webview#3546]
**Bug description:**

The WebView on a Xiaomi tablet enters an infinite loading loop. The expected behavior is for the page to display normally.

**To Reproduce:**

```
import React from 'react';

import {SafeAreaView, StyleSheet, View} from 'react-native';

import WebView from 'react-native-webview';

function App(): JSX.Element {
  return (
    <SafeAreaView style={{flex: 1}}>
      <View
        style={{
          flex: 1,
        }}>
        <WebView
          style={{flex: 1, backgroundColor: 'skyblue'}}
          source={{uri: 'https://www.google.com/'}}
          startInLoadingState={true}
          javaScriptEnabled
          onError={err => {
            console.log('err', err);
          }}
        />
      </View>
    </SafeAreaView>
  );
}

export default App;
```

**Expected behavior:**

The WebView should load and display the content from the URL without entering an infinite loading loop.

**Screenshots/Videos:**

https://github.com/user-attachments/assets/f275da97-4814-41cc-ba11-39db50bca0a9

**Environment:**
- Operating System: Xiaomi HyperOS 1
- Android Version: 14 UKQ1.231003.002
- React Native Version: 0.71.15
- React Native WebView Version: 13.12.1
- Android System Webview version: 127.0.6533.105

**Comment by tmKnight01** [comment]
his works fine on other platforms (iOS, Android phones), but this issue only occurs on the Xiaomi tablet. I suspect it might be related to the version of Android System WebView. However, when I checked the logs using Android Studio, I didn't find any anomalies, which make me feel  bad

**Comment by tmKnight01** [comment]
If an incorrect website URL is entered, such as https://www.googe.com, the WebView correctly displays the ERR_SSL_PROTOCOL_ERROR. but, if a correct website URL is used, it results in an infinite loading loop.

**Comment by tmKnight01** [comment]
Is there any other debugging method to let me know what happened? I also used Google DevTool but found that the content was blank. Please help me. Thank you very much.

**Comment by ekko2665** [comment]
I think  used the key refresh , instead of webview.current.reload()

**Comment by tmKnight01** [comment]
> I think used the key refresh , instead of webview.current.reload()

alright bro,   finally this problem resolved way  was restart   Mi Table,  i still dont what`s happen util now

**Comment by chanphillip** [comment]
> > I think used the key refresh , instead of webview.current.reload()
> 
> alright bro, finally this problem resolved way was restart Mi Table, i still dont what`s happen util now

Spent whole night to try to find a solution. Turns out rebooting fixes my huawei phone.

**Comment by Harshit13777** [comment]
I have same problem , some in Android phone it working , and some it don't with same Android version

**Comment by Rambos** [comment]
same +1

After reload, stay on the loading

**Comment by BestKai** [comment]
same + 1
have the same error

**Comment by xylieong** [comment]
Still can't work after restarting mi phone
