### ISSUE TITLE
Web view become unresponsive when siri is activated on ios device

### ISSUE THREAD

**Issue by Manm33t** [react-native-webview/react-native-webview#3550]
Hey, I am using **react-native-webview** for my app, but when I activate Siri my web view becomes unresponsive. 
I tried logging the app state, It goes to inactive and then it hangs the app. But when I am activating Siri on any other screen it's working fine.

I am using the below version
"react-native-webview": "^13.10.5"

**Comment by mrzslr** [comment]
@Manm33t did you find any work around this issue? I have the same problem on iOS 18.3

**Comment by mrzslr** [comment]
@Manm33t Seems it's happening in our case when using `@react-navigation/stack` and `createStackNavigator`. I changed it to use `@react-navigation/native-stack` and `createNativeStackNavigator, ' and the issue went away. However, when opening and closing Siri, it takes a brief moment to interact with the page.
