### ISSUE TITLE
Is react-native-webview broken for expo 51.x ?

### ISSUE THREAD

**Issue by ieow** [react-native-webview/react-native-webview#3565]
**Bug description:**
Not able to render webview page. 
Got blank page instead

**To Reproduce:**

npx create-expo-app@latest
cd dir

npm run reset-project
npx expo install react-native-webview

edit app/index.tsx
```
import { StyleSheet, Text, View } from "react-native";
import WebView from "react-native-webview";
const styles = StyleSheet.create({
  container: {
    // flex: 1,
    // height: 10,
    // marginTop: 10,
  },
});
export default function Index() {
  return (
    <View
      style={{
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
      }}
    >

      <WebView style={styles.container} originWhitelist={["*"]} source={{ uri: 'https://reactnative.dev/' }} />
      <Text>Edit app/index.tsx to edit this screen.</Text>

    </View>
  );
}
```

npx expo run:ios

ios simulator render this
![Screenshot 2024-09-20 at 6 35 28 PM](https://github.com/user-attachments/assets/c8c743b1-eb20-482c-956f-6d3aa8cc1322)

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS: mac
 - OS version: 14.6.1
 - react-native version: 0.74.5,   EXPO : 51.0.28
 - react-native-webview version: 13.8.6

**Comment by ieow** [comment]
it works after remove all the <View> component


```
import { StyleSheet, Text, View } from "react-native";
import WebView from "react-native-webview";
const styles = StyleSheet.create({
  container: {
  },
});
export default function Index() {
  return (

      <WebView
        source={{ uri: 'https://infinite.red' }}
        style={{ marginTop: 20 }}
      />

  );
}
```

**Comment by vjanssens** [comment]
Removing the parent component works, but it is not a workable situation. Even a single wrapping <View> causes the webview to be invisible. I think this ticket should be re-opened and investigated.
