### ISSUE TITLE
iOS localStorage gets cleared on every app restart

### ISSUE THREAD

**Issue by Nikit-Singh** [react-native-webview/react-native-webview#3572]
**Bug description:**
I am running a website in webview that is setting some localStorage state in multiple places. But when I close and reopen the app, the previous state is not maintained in iOS. It works perfectly fine on the Android

**To Reproduce:**
Set any localStorage state in you website running inside you webview and then close and reopen the app. The state will not be maintained on iOS.

**Expected behavior:**
Should maintain the localStorage state

**Environment:**
 - OS: iOS
 - OS version:  18 and 17.4
 - react-native version: 0.74.5 - expo: ~51.0.28"
 - react-native-webview version: 13.8.6

**Comment by coluccini** [comment]
Did you find an explanation to this? I facing the same issue, but I'm not finding any docs pointing that this should/may be happening

**Comment by nftechie** [comment]
@Nikit-Singh did you ever figure this out? Hitting this issue as well.
