### ISSUE TITLE
webview in IOS can't restrict zoom-in

### ISSUE THREAD

**Issue by arjunAbcd** [react-native-webview/react-native-webview#3579]
**Bug description:**

I am using SVG url as source in webview. I can't restrict pinch-in zoom in IOS , especially iPad. 
If anyone knows any properies to restrict them please comment. 

**Expected behavior:**

Restrict users from zooming

**Environment:**
 - OS: iOS
 - OS version: 15.4
 - react-native version: 75.3
 - react-native-webview version: 13.6.3

**Comment by arjunAbcd** [comment]
Issue solved:  Using property injectedJavaScript

**Comment by pvinis** [comment]
@arjunAbcd and what did you inject?

**Comment by KrishW231** [comment]
here's working disableZoomScript
inject before url loads

const disableZoomScript = `
    (function() {
      // Remove all existing viewport meta tags
      var existing = document.querySelectorAll('meta[name="viewport"]');
      existing.forEach(function(el) { el.parentNode.removeChild(el); });

      // Create a new viewport meta tag
      var meta = document.createElement('meta');
      meta.name = 'viewport';
      meta.content = 'width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no';
      document.getElementsByTagName('head')[0].appendChild(meta);

      // Add CSS to disable touch zoom and text size adjustment
      var style = document.createElement('style');
      style.textContent = '* { touch-action: pan-x pan-y; } body { -webkit-text-size-adjust: 100%; }';
      document.head.appendChild(style);

      // Block multi-touch (pinch zoom)
      document.addEventListener('touchstart', function(e) {
        if (e.touches.length > 1) { e.preventDefault(); }
      }, { passive: false });

      // Block double-tap zoom
      var lastTouchEnd = 0;
      document.addEventListener('touchend', function(e) {
        var now = Date.now();
        if (now - lastTouchEnd <= 300) { e.preventDefault(); }
        lastTouchEnd = now;
      }, false);

      // Block gesture-based zoom (iOS)
      document.addEventListener('gesturestart', function(e) { e.preventDefault(); }, false);
      document.addEventListener('gesturechange', function(e) { e.preventDefault(); }, false);
      document.addEventListener('gestureend', function(e) { e.preventDefault(); }, false);

      // Watch for dynamically added viewport meta tags and fix them
      var observer = new MutationObserver(function(mutations) {
        mutations.forEach(function(mutation) {
          mutation.addedNodes.forEach(function(node) {
            if (node.nodeName === 'META' && node.getAttribute('name') === 'viewport') {
              node.setAttribute('content', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no');
            }
          });
        });
      });
      observer.observe(document.head, { childList: true });
    })();
    true;
  `;

//props for webView
injectedJavaScriptBeforeContentLoaded={disableZoomScript}
injectedJavaScript={disableZoomScript}
onMessage={() => {}}
scalesPageToFit={false}
